### ISSUE TITLE
Termux apt repository is moving

### ISSUE THREAD

**Issue by fornwall** [tuna/issues#10]
In https://github.com/tuna/issues/issues/3 there was an apt mirror setup for http://apt.termux.com, available at https://mirrors.tuna.tsinghua.edu.cn/termux/.

The Termux apt repository is now moving to http://termux.net, an improved hosting solution behind a CDN to improve performance and reliability, so the tuna mirror should be updated to use the new repository url, as the old one will be shut down sometime next year.

**Comment by huiyiqun** [comment]
We have updated the URL, Thanks.
