### ISSUE TITLE
Nexus 镜像工具

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#100]
[Nexus](http://www.sonatype.com/download-oss-sonatype) 开源版支持多种仓库的反向代理缓存镜像，包括 Maven, NPM, RubyGems, Docker 等。

官方有构建好的 docker image 
- Nexus 2.x: https://hub.docker.com/r/sonatype/nexus/
- Nexus 3.x: https://hub.docker.com/r/sonatype/nexus3/

**Comment by abcfy2** [comment]
发现maven.aliyun.com用的就是nexus2镜像的多个maven仓库

**Comment by huiyiqun** [comment]
看上去和tunasync是两个体系了

Feng Yu <notifications@github.com>于2016年8月8日周一 下午11:23写道：

**Comment by abcfy2** [comment]
如果用反向代理访问的话，看上去就像一个体系了。后端可以用nexus镜像maven仓库，在mirrors.tuna.tsinghua.edu.cn上做一个反向代理就行了

**Comment by bigeagle** [comment]
没事，现在 npm 也不是用 tunasync 管理的。

**Comment by Harry-Chen** [comment]
这样的话 jcenter 和 maven center 都可以解决了吧

**Comment by abcfy2** [comment]
这个issue完成怎么样了？发现国外的很多maven仓库都用上CDN了，不幸的是，几乎都选择的是AWS，比如`https://repo.grails.org/`，希望能搞定这个issue，将这些被墙掉的仓库一并镜像了吧

**Comment by bigeagle** [comment]
这个我们比较纠结，我们这里一群 java 白和 java 黑，对于 java 相关技术实在不了解，就算搭起来，自己不去用的话，质量是无法保证的。到时候出了问题，我们连出错信息都可能看不懂。

我记得阿里云有一个 maven 镜像，鉴于阿里全栈高度依赖 java，又有大量 java 专家，他们的靠谱程度会比我们高的多。所以，只要阿里云 maven 还能用得好的话，我们大概率就不开了。

**Comment by abcfy2** [comment]
并不算高，官方文档也不长。使用上无非是建一个用于反向代理的prefix，本地缓存没有就会从上游请求并缓存下来。还可以建个组，把多个prefix放一起。至于host镜像站是用不到的，除非是准备用作私有仓库

**Comment by Harry-Chen** [comment]
经过讨论，我们依旧原则上不进行反向代理+缓存，无论使用何种工具。

**Comment by snowman** [comment]
能否在主页搜索 `gradle` 的时候显示 "暂不支持, `点击查看详情", 或者直接增加 `gradle` 列表项, 但是 `last update` 一列显示不支持`N/A`, 这样别人用`Ctrl-F`快捷键也可以直接定位到, 而不是只能在网页的搜索输入框搜索
![Clip_20230820_143241](https://github.com/tuna/issues/assets/16096559/9dcd789a-79c8-4e24-ac9f-6fde18f60978)

**Comment by Harry-Chen** [comment]
> 能否在主页输入框搜索 `gradle` 的时候显示 `暂不支持, 点击查看详情`, 或者直接增加 `gradle` 列表项, 但是 `last update` 一列显示`不支持`或者`N/A`或者`NOT Support`, 这样别人用`Ctrl-F`快捷键也可以直接定位到, 而不是只能在网页的搜索输入框搜索 ![image](https://user-images.githubusercontent.com/16096559/261835681-1d12bb4b-16b2-4dfb-918e-8df33cf2ed45.png)

我们不会为不存在的镜像增加条目，“不支持”也不是合适的描述方式。此外，这里讨论的是 maven 仓库，与具体的构建工具（如 gradle）也没有关系。

**Comment by abcfy2** [comment]
> 能否在主页输入框搜索 `gradle` 的时候显示 `暂不支持, 点击查看详情`, 或者直接增加 `gradle` 列表项, 但是 `last update` 一列显示`不支持`或者`N/A`或者`NOT Support`, 这样别人用`Ctrl-F`快捷键也可以直接定位到, 而不是只能在网页的搜索输入框搜索 ![image](https://user-images.githubusercontent.com/16096559/261835681-1d12bb4b-16b2-4dfb-918e-8df33cf2ed45.png)

这个只是gradle download镜像而已，gradle使用的仓库还是maven仓库
