### ISSUE TITLE
404无法访问

### ISSUE THREAD

**Issue by yaott2020-666** [tuna/issues#1003]
#### 发生了什么（What happened）
https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/           404
#### 期望的现象（What you expected to happen）
正常使用
#### 如何重现（How to reproduce it）
我怎么知道
#### 您的环境（Environment）
- 操作系统（OS Version）：无关
- 浏览器（如果适用）（Browser version, if applicable）：无关
- 其他（Others）：无

**Comment by phy25** [comment]
See #619.
