### ISSUE TITLE
SBT deb/rpm 镜像

### ISSUE THREAD

**Issue by jiegec** [tuna/issues#1004]
#### 项目名称与简介(Project Intro.)

The slow build tool.

#### 上游地址与镜像方法(How to Mirror)

地址：https://dl.bintray.com/sbt/
方法：apt-sync + yum-sync

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by 210hcl** [comment]
https://dl.bintray.com/ 中科大提供了反向代理，把dl.bintray.com/改为bintray.proxy.ustclug.org即可
