### ISSUE TITLE
repo-ck源内容过期

### ISSUE THREAD

**Issue by logicinu** [tuna/issues#1005]
### 发生了什么（What happened）
repo-ck源内容过期

#### 期望的现象（What you expected to happen）
同步更新

#### 如何重现（How to reproduce it）
http://repo-ck.com/x86_64/
`linux-ck-5.9.1-1-x86_64.pkg.tar.zst   2020-10-19 04:29 `

https://mirrors.tuna.tsinghua.edu.cn/repo-ck/x86_64/
`linux-ck-5.7.19-1-x86_64.pkg.tar.zst  2020-08-27 20:08`

**Comment by shankerwangmiao** [comment]
上述文件已经同步。

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/repo-ck/x86_64/linux-ck-5.9.1-1-x86_64.pkg.tar.zst
