### ISSUE TITLE
[tuna]404 at /anaconda/cloud/peterjc123/linux-64/

### ISSUE THREAD

**Issue by Snailgoo** [tuna/issues#1006]
#### 发生了什么（What happened）
Fetching package metadata ................CondaHTTPError: HTTP Error: Could not find URL: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/linux-64/

#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu16.04
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
https://anaconda.org/peterjc123/pytorch 是第三方用户贡献的 pytorch Windows的第三方库，因此不含 linux 相关的文件。
