### ISSUE TITLE
[镜像请求] DD烤肉机2.0

### ISSUE THREAD

**Issue by ky-bd** [tuna/issues#1008]
- 项目名称
   [DD烤肉机2.0](https://github.com/jiafangjun/DD_KaoRou2)

- 项目简介
   一个从视频音轨中自动识别、分离人声，并生成时间轴，大幅提高字幕制作效率的软件，[视频介绍](https://www.bilibili.com/video/BV1p5411b7o7)
   由于部分用户不熟悉加速github连接的方法，导致无法正常下载，希望可以镜像该软件的安装包

- 镜像源地址
   https://github.com/jiafangjun/DD_KaoRou2/releases

- 镜像大小
   约400MB

**Comment by jiegec** [comment]
这个软件太小众了吧。而且并没有开源许可证。

**Comment by Gallium70** [comment]
> 这个软件太小众了吧。而且并没有开源许可证。

添加了MIT许可，可以考虑一下吗？
