### ISSUE TITLE
[镜像请求]Chaotic-AUR

### ISSUE THREAD

**Issue by yachen4ever** [tuna/issues#1009]
项目名称与简介(Project Intro.)
Chaotic-AUR包含了大量AUR构建的二进制包，给本就不方便使用AUR的中国用户提供了方便。
根据pkgs.org统计有2800多个包(https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/)，其中和archlinuxcn重合度不算高，包含了很多如chromium-vaapi,oh-my-zsh-git这种archlinuxcn由于无人维护不再可用的包。可以减轻archlinuxcn的工作量，避免重复劳动.

上游地址与镜像方法(How to Mirror)
https://lonewolf.pedrohlc.com/chaotic-aur/
Mirror Script:
https://gist.github.com/BangL/86c2700e169994bc147ebf076fcb1888

其他信息(Other)
镜像大小(Mirror Size):
未知，目测约10G-50G

**Comment by ZenithalHourlyRate** [comment]
我们在 chaotic-aur 的 tg 群中沟通了一下，主要关于源中一些包的版权相关问题，
得到的是以下回复：

```
"If you find any package license infringement, please notify me at
root[at]pedrohlc.com. I'll then remove it and blacklist."

taken from the chaotic aur page
```

感觉该源对版权问题并无严格保证。

-- 
GPG Fingerprint: 9424DF6A677958023ACA3A6323470D4FD461AA84

**Comment by Harry-Chen** [comment]
编译 AUR 可能带来潜在的版权问题，看起来上游对于此问题态度也较消极

**Comment by yachen4ever** [comment]
明白了，谢谢

**Comment by QiangF** [comment]
> "If you find any package license infringement, please notify me at root[at]pedrohlc.com. I'll then remove it and blacklist."

这个应该可以了吧？我感觉没有哪一个源可以对所有的包的所有代码进行审查，所谓的保证实际上跟这个声明是一样的

**Comment by skyzh** [comment]
> > "If you find any package license infringement, please notify me at root[at]pedrohlc.com. I'll then remove it and blacklist."
> 
> 这个应该可以了吧？我感觉没有哪一个源可以对所有的包的所有代码进行审查，所谓的保证实际上跟这个声明是一样的

license 应该是大部分源基本的准入门槛

**Comment by QiangF** [comment]
就是说要象征性的弄个license就行了嘛，你能不能给一个模板连接，然后大家和上游沟通一下让放在醒目的位置。其实AUR帐号随便就能注册几乎没有审查的（所以传点恶意代码、侵犯版权的也能传的），别的aur可以镜像，这个弄的太麻烦了

**Comment by QiangF** [comment]
这样声明够不够：

All packages in this Chaotic-AUR is in compliance with the licensing terms of the content. If you find any package license infringement, please notify me at root[at]pedrohlc.com. I'll then remove it and blacklist.

**Comment by shankerwangmiao** [comment]
不够，确定一个上游镜像是否存在版权问题是严肃的，并非“象征性的弄个license就行了”，也不是只要其声称没问题就可以了。它应当至少存在一个审查所包含软件是否含有不允许重新分发的内容的机制。事实上，这样的机制在 Chaotic-AUR 中是缺乏的，并且我确实发现了存在问题的内容。
