### ISSUE TITLE
【镜像请求】OPNsense

### ISSUE THREAD

**Issue by RivenNero** [tuna/issues#1011]
## 项目名称与简介(Project Intro.)

项目名称：OPNsense

简介：<https://zh.wikipedia.org/wiki/OPNsense>

## 上游地址与镜像方法(How to Mirror)

上游地址：`rsync://rsync.opnsense.org/opnsense-dist/`

镜像方法：`rsync`

## 其他信息(Other)

- 镜像大小(Mirror Size): 大约 `80GiB`
- 由于国内目前 OPNsense 的镜像源极少，官方的 HK 镜像站速度在一些地区也比较慢，目前在中国大陆我只发现 BFSU Mirror 有 OPNsense 的镜像源，为了提高中国大陆 OPNsense 镜像源的可用性和可靠性，希望 TUNA Mirror 也可以增添 OPNsense 镜像源。

**Comment by shankerwangmiao** [comment]
ref: #820 

BFSU 和 TUNA 一样可靠。
