### ISSUE TITLE
AUR上次更新时间异常

### ISSUE THREAD

**Issue by ScottliuNonwin** [tuna/issues#1013]
#### 发生了什么（What happened）
镜像站AUR上次更新时间异常
#### 期望的现象（What you expected to happen）
希望能将上次更新时间矫正过来
#### 如何重现（How to reproduce it）
![1](https://user-images.githubusercontent.com/58081491/97292089-c03ef300-1885-11eb-8568-6bb1109749a8.png)
#### 您的环境（Environment）
![image](https://user-images.githubusercontent.com/58081491/97292212-ecf30a80-1885-11eb-9f1b-be624279fd2a.png)

**Comment by shankerwangmiao** [comment]
AUR 我们没有同步，因此显示为 0
