### ISSUE TITLE
【镜像请求】请求新建Mine-imator镜像站！

### ISSUE THREAD

**Issue by ScottliuNonwin** [tuna/issues#1014]
# 项目名称与简介(Project Intro.)
### 简介
Mine-imator是一个3D电影制作人基于沙盒游戏Minecraft，创建于GameMaker Studio 2。

使用 Minecraft 中的方块、项目和可爱的人物创建动画视频
![](https://www.mineimator.com/images/frame1.png)

使用粒子、灯光和相机效果使您的作品流行起来
![](https://www.mineimator.com/images/frame2.png)

使用 YouTube 等网站与全世界分享您完成的视频
![](https://www.mineimator.com/images/frame3.png)

## 项目地址
网站： https://www.mineimator.com
下载： https://www.mineimator.com/download
# 上游地址与镜像方法(How to Mirror)
定时下载此网站的安装程序及二进制归档
# 其他信息(Other)
# 镜像大小(Mirror Size)
未知

**Comment by jiegec** [comment]
不是自由软件。
