### ISSUE TITLE
【镜像请求】DisplayCAL

### ISSUE THREAD

**Issue by MasterLiu-su** [tuna/issues#1015]
# 项目名称与简介(Project Intro.)
## 关于DisplayCAL
DisplayCAL（以前称为 dispcalGUI）是一种显示校准和分析解决方案，侧重于准确性和多功能性（事实上，作者是诚实的意见，这可能是任何地方最准确和通用的 ICC 兼容显示分析解决方案）。其核心是AryllCMS，一个先进的开源色彩管理系统，进行测量，创建校准和配置文件，以及各种其他高级色彩相关任务。

使用众多支持测量仪器之一校准和描述您的显示设备，支持多显示器设置和各种高级用户可用选项，例如验证和报告功能，以评估ICC配置文件和显示设备，创建视频3D LUT，以及可选的CIECAM02色域映射，以考虑到不同的观看条件。其他功能包括：

支持不同显示设备类型的色度计校正，以提高色度计的绝对精度。如果光谱仪可用，可以从供应商软件导入修正或根据测量结果创建校正。
通过测量检查显示设备的均匀性。
测试图表编辑器：创建包含任何数量和颜色补丁成分的图表，从 CGATS、CSV 文件（仅分标签）和电子表格应用程序轻松复制和粘贴图表，以便进行配置文件验证和评估。
创建具有自定义主、白点和黑点以及音调响应的合成 ICC 配置文件，以用作设备链接 （3D LUT） 转换中的工作空间或源配置文件。
DisplayCAL由弗洛里安·赫奇开发和维护，如果没有AryllCMS和他本人是不可能的。
## 截图

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-calibration-settings.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-profiling-settings.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-3DLUT-settings.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-verification-settings.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-edit-testchart.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-adjust.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-profile-information.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-GNOME-view-curves.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-KDE5.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-Mac.png)

![](https://displaycal.net/screenshots/DisplayCAL-screenshot-Win10.png)
## 免责声明
这个程序是自由软件;您可以根据自由软件基金会发布的 GNU 通用公共许可证的条款重新分发和/或修改它;许可证的版本 3，或（由您选择）任何以后的版本。

这个程序是分发的希望，这将是有用的，但没有任何保证;甚至没有默示的保证的商人或适合特定用途。有关详细信息，请参阅 GNU 通用公共许可证。

DisplayCAL 以Python 编写，并使用第三方包NumPy， wxPython (Gui工具包），Certifi， PyGObject或dbus-python用于 Linux （Wayland 支持着色），以及用于 Windows 的 Python 扩展、comtype和Python WMI 模块，以提供特定于 Windows 的功能。其他次要依赖项包括故障处理器、psutil、PyChromecast和 pyglet（macOS/Windows）或 libSDL2 （Linux）。 它广泛使用并依赖于ArgyllCMS 提供的功能。生成系统用于创建独立可执行文件，在 Mac OS X 上或 Windows 上的py2exe 上使用py2app。所有这些软件包都©各自作者创建。
# 上游地址与镜像方法(How to Mirror)
定期下载
## 网址
https://displaycal.net
### Windows
安装程序：https://displaycal.net/download/standalone/DisplayCAL-Setup.exe
ZIP归档：https://displaycal.net/download/standalone/DisplayCAL-win32.zip
### macOS
https://displaycal.net/download/standalone/DisplayCAL.pkg
### 源代码
https://displaycal.net/download/DisplayCAL.tar.gz
# 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by shankerwangmiao** [comment]
您好，DisplayCAL 已经被若干发行版收录进官方软件仓库，后者 TUNA 已经有镜像。因此不再考虑单独镜像。

**Comment by ScottliuNonwin** [comment]
建议只单独镜像Windows版和macOS版

**Comment by ZenithalHourlyRate** [comment]
该软件的源只有 sourceforge，之上提供的链接也会跳转到sourceforge，而根据 #928，我们较难镜像 sourceforge 提供的软件

**Comment by ScottliuNonwin** [comment]
建议联系下开发者提供官方镜像，再不济就使用国外的服务器代理镜像。

**Comment by Harry-Chen** [comment]
对于特定的某个软件，我们没有精力一一联系开发者，也倾向于不单独设立镜像（除非有 GitHub Releases 等发布形式）。本软件已经提供了 SourceForge 镜像，我们也没有必要单独再设立。

此外，TUNA 原则上不进行反向代理。

**Comment by ScottliuNonwin** [comment]
联系下开发者将代码和软件迁移至github

**Comment by shankerwangmiao** [comment]
您好，我们并非要求开发者必须使用指定的代码托管平台，而是考虑到该软件已经被各发行版软件仓库收录，并且该软件的托管平台已经为其提供了镜像服务，因此我们不再考虑重复提供镜像。
