### ISSUE TITLE
numpy-1.19.3-cp36-cp36m-manylinux1_x86_64.whl

### ISSUE THREAD

**Issue by chengziya** [tuna/issues#1017]
numpy-1.19.3-cp36-cp36m-manylinux1_x86_64.whl
源地址：https://files.pythonhosted.org/packages/8f/40/ddb5109614aabad67e6fe426b3579a879b7b3cdd375eb27af467c4367ae0/numpy-1.19.3-cp36-cp36m-manylinux1_x86_64.whl
文件大小：12.8MB

**Comment by shankerwangmiao** [comment]
您好，该文件已经在镜像站上存在。
