### ISSUE TITLE
【镜像请求】Raspberry Pi OS（原Raspbian）

### ISSUE THREAD

**Issue by hmsjy2017** [tuna/issues#1020]
#### 项目名称与简介(Project Intro.)
树莓派（Raspberry Pi）是基于Linux的单片机电脑，由英国树莓派基金会开发。此为树莓派官方系统 Raspberry Pi OS 的软件源。
#### 上游地址与镜像方法(How to Mirror)
- raspbian
Raspbian 安装镜像和软件源
rsync://archive.raspbian.org/archive/
大小：484.56G
- raspberrypi
树莓派基金会提供的软件源，包括 ui 相关程序 ( 如 Raspbian 的桌面环境 PIXEL DE) 及部分由树莓派基金会为 树莓派编写的软件
rsync://apt-repo.raspberrypi.org/archive/debian/
大小：92.04G

同步方法：http://www.raspbian.org/RaspbianMirrors

**Comment by ZenithalHourlyRate** [comment]
镜像中已有
[raspberry-pi-os-images](https://mirrors.tuna.tsinghua.edu.cn/raspberry-pi-os-images/)
[raspberrypi](https://mirrors.tuna.tsinghua.edu.cn/raspberrypi/)
[raspbian](https://mirrors.tuna.tsinghua.edu.cn/raspbian/)

![Screenshot2020-10-31-04:26:02](https://user-images.githubusercontent.com/19512674/97753769-47fc5a00-1b31-11eb-802d-b47ba7a4568a.png)
且其上游与issue中提到上游一致。
