### ISSUE TITLE
gitlab-ce版本缺失

### ISSUE THREAD

**Issue by MDDTGitHub** [tuna/issues#1023]
gitlab中文汉化版在gitlab-ce在el8镜像中没有对应版本

**Comment by shankerwangmiao** [comment]
您好，TUNA 镜像上的 gitlab-ce 原样镜像自 Gitlab 官方上游。您提到的所谓汉化版本并非官方提供，因此并不存在于该镜像中。

**Comment by MDDTGitHub** [comment]
收到
