### ISSUE TITLE
使用tunasync镜像ubuntu源过程中多次失败

### ISSUE THREAD

**Issue by Alberthchang** [tuna/issues#1024]
多次失败，报错如下：
rsync: [generator] write error: Connection reset by peer (104)
rsync: connection unexpectedly closed (458547604445 bytes received so far) [receiver]rsync error: error in socket IO (code 10) at io.c(829) [generator=3.1.2]
rsync error: Error in socket I/O
rsync error: received SIGUSR1 (code 19) at main.c(1447) [receiver=3.1.2]

我采用10个线程从`http://mirrors.yun-idc.com/ ` 镜像ubuntu的源，每次镜像一段大小之后就是这个情况

**Comment by shankerwangmiao** [comment]
您好，使用 rsync 协议制作镜像，rsync 协议不支持多线程。Connection reset by peer 错误表示您的 TCP 链接由于故障被中断，建议您自行与您的上游排查网络连接问题。

**Comment by Alberthchang** [comment]
@shankerwangmiao  我说的10个线程是在worker配置文件中配置concurrent = 10，通过测试发现网络一直是联通良好，网络波动也没有明显断网，但是就是会出现这个错误，重启worker之后就恢复了

**Comment by shankerwangmiao** [comment]
`concurrent` 表示 worker 限制同时进行的同步任务数量，并非某个同步任务多线程并发进行。对于 rsync 协议，tunasync 是调用 rsync 工具进行的同步。出现 connection reset 的问题，意味着 tcp 链接出现了异常，该问题与 tunasync 工具无关。对于失败的任务，可以在配置中通过 `retry` 指定重试次数，这样，worker 会在同步失败后自动重试至多指定的次数，然后不再重试，等待指定的同步间隔时间后再尝试同步。如果需要手动启动某一任务，可以使用 `tunasynctl start`
