### ISSUE TITLE
AOSP 清华镜像下载 11.0.0 出现问题 

### ISSUE THREAD

**Issue by lvxian-git** [tuna/issues#1025]
发生了什么（What happened）
下载源码检查失败

期望的现象（What you expected to happen）
成功下载完成

如何重现（How to reproduce it）
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android-11.0.0_r1
repo sync -c -j4

其他事项（Anything else we need to know）

您的环境（Environment）

    操作系统（OS Version）：ubuntu20.04
    浏览器（如果适用）（Browser version, if applicable）：无
    其他（Others）：

报错日志如下：
error: Cannot fetch platform/art from https://mirrors.bfsu.edu.cn/git/AOSP/platform/art
Fetching projects: 100% (1/1), done.
error: Cannot checkout platform/art: ManifestInvalidRevisionError: revision refs/tags/android-11.0.0_r1 in platform/art not found
error: in `sync platform/art`: revision refs/tags/android-11.0.0_r1 in platform/art not found

**Comment by shankerwangmiao** [comment]
请问你用的是 tuna 镜像还是 bfsu 镜像？目前看服务器上是有这个 tag 的，建议重试一次。

**Comment by lvxian-git** [comment]
change the mirror source to tuna, got the same result:

error: Cannot fetch platform/external/noto-fonts from https://aosp.tuna.tsinghua.edu.cn/platform/external/noto-fonts
Fetching projects: 100% (781/781), done.
error: Cannot checkout platform/art: ManifestInvalidRevisionError: revision refs/tags/android-11.0.0_r1 in platform/art not found
error: in `sync -j20`: revision refs/tags/android-11.0.0_r1 in platform/art not found

**Comment by lvxian-git** [comment]
更换成清华镜像，同样的结果：

error: Cannot fetch platform/external/noto-fonts from https://aosp.tuna.tsinghua.edu.cn/platform/external/noto-fonts
Fetching projects: 100% (781/781), done.
error: Cannot checkout platform/art: ManifestInvalidRevisionError: revision refs/tags/android-11.0.0_r1 in platform/art not found
error: in sync -j20: revision refs/tags/android-11.0.0_r1 in platform/art not found

**Comment by shankerwangmiao** [comment]
目前暂无结论，在两个服务器上均排查过，`android-11.0.0_r1` 都是存在的。

**Comment by asking1233** [comment]
下载8.1.0 也是同样的问题

**Comment by asking1233** [comment]
8.1.0_r10 也是同样的问题

**Comment by lvxian-git** [comment]
只能解释为网络或者curl不稳定。多下载几次就好了。

**Comment by shankerwangmiao** [comment]
建议发生类似情况的时候，不要只看最后结束地方的错误，而是进一步观察 sync 的过程中是否有任何错误，以便能够进一步分析。

**Comment by 3db-noise** [comment]
如果输出日志有“fatal: not a git repository (or any of the parent directories)”，可能是./repo目录下的对应的.git文件/文件夹损坏了
