### ISSUE TITLE
【镜像请求】请求建立openSUSE ports镜像

### ISSUE THREAD

**Issue by BavonChao** [tuna/issues#1026]
**项目名称与简介(Project Intro.)** 
    openSUSE ports 镜像
**上游地址与镜像方法(How to Mirror)**
    [https://download.opensuse.org/ports/](https://download.opensuse.org/ports/)
    [官方提供的镜像方法](https://en.opensuse.org/openSUSE:Mirror_howto)
**其他信息(Other)**
    TUNA 已经提供了openSUSE的镜像，但是其中并未包含官方源中ports文件夹的完整内容，只有其中的[aarch64](https://mirrors.tuna.tsinghua.edu.cn/opensuse/ports/aarch64/)文件夹，作为openSUSE的忠实用户，我在树莓派上也安装了这款作业系统，但是国内还没找到提供完整镜像源的服务器，希望TUNA能够将官方的ports文件夹完整镜像下来，谢谢。
    镜像大小(Mirror Size): 未知

**Comment by shankerwangmiao** [comment]
树莓派不是 aarch64 架构吗？

**Comment by BavonChao** [comment]
树莓派是aarch64架构，但是系统安装之后自带的官方源中除了[aarch64](https://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/)这个地址，还包含了[https://download.opensuse.org/ports/update/leap/15.2/oss/](https://download.opensuse.org/ports/update/leap/15.2/oss/)这个地址，TUNA目前提供的镜像中并不包含这个文件夹。所以希望TUNA能够将ports整个文件夹镜像下来。

**Comment by 210hcl** [comment]
相似，请求清华镜像同步repositories镜像，所有的obs以及opensuse tumbleweeded的update都是在repositories，repositories国内没有任何镜像，严重妨碍用户使用，请求添加同步

**Comment by hillwoodroc** [comment]
/ports/<arch>/update 对用户没用，可以过滤掉。

**Comment by BavonChao** [comment]
> 
> 
> /ports/<arch>/update 对用户没用，可以过滤掉。

openSUSE 社区的大佬来了，失敬失敬😄️

**Comment by 210hcl** [comment]
> 树莓派是aarch64架构，但是系统安装之后自带的官方源中除了[aarch64](https://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/)这个地址，还包含了https://download.opensuse.org/ports/update/leap/15.2/oss/这个地址，TUNA目前提供的镜像中并不包含这个文件夹。所以希望TUNA能够将ports整个文件夹镜像下来。

网易云以及阿里云均同步了

**Comment by 210hcl** [comment]
作为一个开发者，再次请求同步repositories镜像以及sources镜像。fedora, centos, mageia大陆都有源代码镜像，唯独opensuse没有源代码镜像。（最近的源代码镜像在台湾，因为中国的特殊网络环境，速度非常慢）

**Comment by BavonChao** [comment]
> 
> 
> > 树莓派是aarch64架构，但是系统安装之后自带的官方源中除了[aarch64](https://download.opensuse.org/ports/aarch64/distribution/leap/15.2/repo/oss/)这个地址，还包含了[https://download.opensuse.org/ports/update/leap/15.2/oss/这个地址，TUNA目前提供的镜像中并不包含这个文件夹。所以希望TUNA能够将ports整个文件夹镜像下来。](https://download.opensuse.org/ports/update/leap/15.2/oss/%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%EF%BC%8CTUNA%E7%9B%AE%E5%89%8D%E6%8F%90%E4%BE%9B%E7%9A%84%E9%95%9C%E5%83%8F%E4%B8%AD%E5%B9%B6%E4%B8%8D%E5%8C%85%E5%90%AB%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%E3%80%82%E6%89%80%E4%BB%A5%E5%B8%8C%E6%9C%9BTUNA%E8%83%BD%E5%A4%9F%E5%B0%86ports%E6%95%B4%E4%B8%AA%E6%96%87%E4%BB%B6%E5%A4%B9%E9%95%9C%E5%83%8F%E4%B8%8B%E6%9D%A5%E3%80%82)
> 
> 网易以及阿里云均同步了

阿里云上/ports/update/ 目录并没有同步；网易那个很旧，配置了之后更新竟然会将本机软件降级

**Comment by shankerwangmiao** [comment]
`/ports/update/` 已经添加。
