### ISSUE TITLE
换源后找不到 wheel

### ISSUE THREAD

**Issue by non-trace** [tuna/issues#1028]
树莓派4B换源后找不到 wheel

```shell
sudo apt-get install wheel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wheel
```

**Comment by phy25** [comment]
原来的源是什么呢？原来的源可以下载到 wheel 吗？

**Comment by non-trace** [comment]
我是树莓派，之前没有换源，比较慢，但是能装上，今天突然想重装一下系统，换了源，结果装不上。。。


| |
姚洪肖
|
|
yaohongxiao@126.com
|
签名由网易邮箱大师定制


在2020年11月8日 08:35，Henry Pan<notifications@github.com> 写道：

原来的源是什么呢？原来的源可以下载到 wheel 吗？

**Comment by ZenithalHourlyRate** [comment]
换源后是否运行了 `sudo apt-get update`

**Comment by non-trace** [comment]
sudo apt-get update

sudo apt-get upgrade

两个都运行了



| |
姚洪肖
|
|
yaohongxiao@126.com
|
签名由网易邮箱大师定制


在2020年11月8日 09:00，Zenithal<notifications@github.com> 写道：

换源后是否运行了 sudo apt-get update

**Comment by ZenithalHourlyRate** [comment]
能把您的 `/etc/apt/sources.list` 与 发行版信息 贴一份上来吗

**Comment by non-trace** [comment]
不要意思，我已经重装系统了，我是想装个 Home Assistant ，本来想在Raspberry Pi OS上装，结果没装上，已经放弃了，直接使用 Home Assistant OS 了


| |
姚洪肖
|
|
yaohongxiao@126.com
|
签名由网易邮箱大师定制


在2020年11月8日 09:09，Zenithal<notifications@github.com> 写道：

能把您的 /etc/apt/sources.list 与 发行版信息 贴一份上来吗
