### ISSUE TITLE
Gitlab 仓库包信息的哈希值校验失败

### ISSUE THREAD

**Issue by zhujunsan** [tuna/issues#103]
apt-get update 以后：
```W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch```

**Comment by zhujunsan** [comment]
以及，官方应该已经更新 8.10.6 了，镜像这里似乎也没同步，是不是同步脚本坏了@@？

**Comment by bigeagle** [comment]
一天同步一次，别急啊…… 这不已经有了么

**Comment by zhujunsan** [comment]
好吧～没有问题了～
