### ISSUE TITLE
【编译错误】 android_11.0.0_r17 missing file：prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc'

### ISSUE THREAD

**Issue by lvxian-git** [tuna/issues#1030]
发生了什么（What happened）
代码编译失败

期望的现象（What you expected to happen）
编译成功

如何重现（How to reproduce it）
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android-11.0.0_r17
repo sync -c -j4
source build/envsetup.sh
lunch 8
make ARCH=arm64 CROSS_COMPILE=$AOSP_ROOT/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-'

其他事项（Anything else we need to know）

您的环境（Environment）

操作系统（OS Version）：ubuntu20.04
浏览器（如果适用）（Browser version, if applicable）：无
其他（Others）：
报错日志如下：
prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc : no such file or directory

**Comment by shankerwangmiao** [comment]
dup with 1025

**Comment by lvxian-git** [comment]
和1025不是一个问题。请repoen 谢谢。

**Comment by shankerwangmiao** [comment]
TUNA 原样镜像 AOSP 的源代码。具体 AOSP 编译问题，请向上游咨询。
