### ISSUE TITLE
北外的 OpenWrt Snapshots 镜像炸了（

### ISSUE THREAD

**Issue by ManaSoy** [tuna/issues#1031]
#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 20H2
- 浏览器（如果适用）（Browser version, if applicable）：Google Chrome 86.0.4240.193
- 其他（Others）：无

![image](https://user-images.githubusercontent.com/47733293/98917170-02fbfe80-2507-11eb-81b1-5ddecf22ae2e.png)

**Comment by shankerwangmiao** [comment]
dup with #619
