### ISSUE TITLE
Tuna 同步的 AlpineLinux 比官方的慢了6个小时

### ISSUE THREAD

**Issue by wenerme** [tuna/issues#1036]
#### 发生了什么（What happened）

![image](https://user-images.githubusercontent.com/1777211/99152428-b0743b00-26dc-11eb-8f90-be7656dde93d.png)

Alpine 基本 2 小时同步一次，tuna 慢了差不多6小时，上海交大的基本一致

![image](https://user-images.githubusercontent.com/1777211/99152450-ce41a000-26dc-11eb-8595-0f4d84f518b6.png)

#### 期望的现象（What you expected to happen）

tuna 跟进同步周期，因为阿里云同步延迟实在高，选择了tuna，但也有好几个小时延时，更新包到 aports https://github.com/alpinelinux/aports 后需要一段时间才能用到

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by wenerme** [comment]
查询地址 https://alpine.ink/mirror/mirrors.tuna.tsinghua.edu.cn

**Comment by shankerwangmiao** [comment]
您好，镜像站无法保证时时刻刻都与上游同步，对于上游在活跃更新的分支和版本，可能会稍有延迟。这是正常现象。

**Comment by wenerme** [comment]
那tuna是否考虑定一些sla 做到一定程度的保障？

**Comment by shankerwangmiao** [comment]
目前 TUNA 镜像站不就任何可用性的保障作出承诺，但是会尽量做好维护工作，方便大家使用。
