### ISSUE TITLE
【镜像请求】Sury

### ISSUE THREAD

**Issue by drsanwujiang** [tuna/issues#1037]
#### 项目名称与简介(Project Intro.)
优秀的 Debian PHP 软件源，提供最新版本的 PHP（同时还提供最新的 Nginx 和 Apache）
#### 上游地址与镜像方法(How to Mirror)
官方：https://packages.sury.org/
xTom：https://mirror.xtom.com.hk/sury/

rsync rsync://rsync.sury.org/repositories

**Comment by Harry-Chen** [comment]
作者提到：

> All packaging work is either done directly in the Debian unstable, or it will be in the unstable sooner or later.

那么是否还有必要单独镜像？

**Comment by drsanwujiang** [comment]
> 作者提到：
> 
> > All packaging work is either done directly in the Debian unstable, or it will be in the unstable sooner or later.
> 
> 那么是否还有必要单独镜像？

确实一直在 testing 和 unstable 里，但是 sury 源可以以 https://packages.sury.org/php 这样的形式来只引入 PHP 软件包；如果直接使用 testing 和 unstable 的话会影响其他软件。

**Comment by skyzh** [comment]
Available at https://mirror.sjtu.edu.cn/sury/

**Comment by drsanwujiang** [comment]
> Available at https://mirror.sjtu.edu.cn/sury/

Thx.
