### ISSUE TITLE
jkp.tuna.tsinghua.edu.cn 无法解析

### ISSUE THREAD

**Issue by heroxbd** [tuna/issues#104]
$ dig jkp.tuna.tsinghua.edu.cn +trace

; <<>> DiG 9.9.5-12+b1-Debian <<>> jkp.tuna.tsinghua.edu.cn +trace
;; global options: +cmd
.                       3600    IN      NS      e.root-servers.net.
.                       3600    IN      NS      d.root-servers.net.
.                       3600    IN      NS      c.root-servers.net.
.                       3600    IN      NS      b.root-servers.net.
.                       3600    IN      NS      a.root-servers.net.
.                       3600    IN      NS      m.root-servers.net.
.                       3600    IN      NS      l.root-servers.net.
.                       3600    IN      NS      k.root-servers.net.
.                       3600    IN      NS      j.root-servers.net.
.                       3600    IN      NS      i.root-servers.net.
.                       3600    IN      NS      h.root-servers.net.
.                       3600    IN      NS      g.root-servers.net.
.                       3600    IN      NS      f.root-servers.net.
;; Received 1479 bytes from 10.240.12.130#53(10.240.12.130) in 8 ms

cn.                     172800  IN      NS      a.dns.cn.
cn.                     172800  IN      NS      b.dns.cn.
cn.                     172800  IN      NS      c.dns.cn.
cn.                     172800  IN      NS      d.dns.cn.
cn.                     172800  IN      NS      e.dns.cn.
cn.                     172800  IN      NS      ns.cernet.net.
cn.                     86400   IN      DS      24697 8 2 A8BD8346D72C8C08FCE76D85298A8D58025323487122C5354D6E34AD 857498E3
cn.                     86400   IN      RRSIG   DS 8 1 86400 20160829050000 20160819040000 46551 . U2vzdsQGqmNxHTbIAmXmfAicXwKFp9C16pGfuwWpW1cq8gER7CfBdnpJ wbEvspQaEp+58iZkdcO0Dpf0qqTLeAs+uaaozsWkc+MKhZcoYmG2UOah mhkVlnLp4HQQBdewEBoT8DOR7mcdnhyCwry3D+KEj5pi0Nb7YcZPx6xr PZc=
;; Received 523 bytes from 199.7.83.42#53(l.root-servers.net) in 232 ms

edu.cn.                 172800  IN      NS      dns2.edu.cn.
edu.cn.                 172800  IN      NS      dns.edu.cn.
edu.cn.                 172800  IN      NS      ns2.cuhk.hk.
edu.cn.                 172800  IN      NS      ns2.cernet.net.
edu.cn.                 172800  IN      NS      deneb.dfn.de.
3QDAQA092EE5BELP64A74EBNB8J53D7E.cn. 21600 IN NSEC3 1 1 10 AEF123AB 3QLMP0QRNQ96G5AFGOPNB7U7IJ4MBP4B NS SOA RRSIG DNSKEY NSEC3PARAM TYPE65534
3QDAQA092EE5BELP64A74EBNB8J53D7E.cn. 21600 IN RRSIG NSEC3 8 2 21600 20160827071024 20160728061024 55980 cn. E+8EsHVvpXuGmfZ7FyPDH+nBuBbbiV7Zq+n8Rhux6ivq7/hii3awQd+u 5xuM/44VaNyxSgoO7uE7iiQu+LbSdQ800AgqGQ1uNzqAo70XKFi8kEPP 8KItI7SP9INHwepDpW0wO3zg5Z334HIuxM9E11gxdtZgT0IvL1bqkrFt /bk=
39RHJMG7OQR8QCTU59OBQ62NRDQE045I.cn. 21600 IN NSEC3 1 1 10 AEF123AB 3A62EEG57NMMFHK1O7347GBEBUJUESOH CNAME RRSIG
39RHJMG7OQR8QCTU59OBQ62NRDQE045I.cn. 21600 IN RRSIG NSEC3 8 2 21600 20160904023147 20160805015527 55980 cn. SA5yqXfvFg0OJS7rL/K2RUTTyr4VHsR6jx9nBXxIG+ESAXXGBC9P4t0U THfLXl5Qybf/XBAt5rsYiw2+3zl9xrqWOdYKYCUUifma5mBTrY7919m/ AQKGIVD39rLHdnfziZsahpn5l3/atoOaE8uW2wceSYukEnhmzJugKCCY Oyw=
;; Received 726 bytes from 203.119.28.1#53(d.dns.cn) in 123 ms

TSINGHUA.edu.cn.        172800  IN      NS      DNS.TSINGHUA.edu.cn.
TSINGHUA.edu.cn.        172800  IN      NS      DNS2.TSINGHUA.edu.cn.
TSINGHUA.edu.cn.        172800  IN      NS      NS2.CUHK.EDU.HK.
TSINGHUA.edu.cn.        172800  IN      NS      DNS2.edu.cn.
;; Received 211 bytes from 192.76.176.9#53(deneb.dfn.de) in 345 ms

tuna.tsinghua.edu.cn.   21600   IN      NS      dns2.tuna.tsinghua.edu.cn.
tuna.tsinghua.edu.cn.   21600   IN      NS      dns1.tuna.tsinghua.edu.cn.
tuna.tsinghua.edu.cn.   21600   IN      NS      dns3.tuna.tsinghua.edu.cn.
;; Received 214 bytes from 166.111.8.30#53(DNS2.TSINGHUA.edu.cn) in 378 ms

tuna.tsinghua.edu.cn.   86400   IN      SOA     dns1.tuna.tsinghua.edu.cn.tuna.tsinghua.edu.cn. stuff.tuna.tsinghua.edu.cn.tuna.tsinghua.edu.cn. 2016081602 300 30 31536000 86400
;; Received 121 bytes from 202.204.128.61#53(dns3.tuna.tsinghua.edu.cn) in 177 ms

**Comment by bigeagle** [comment]
搞定，因为换了域名服务器
