### ISSUE TITLE
关于Anaconda镜像速度慢的问题

### ISSUE THREAD

**Issue by Yuzuki-N** [tuna/issues#1041]
我最近在 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/` 下载 `anaconda`以及`conda install`的过程中，都发现速度及其慢，和不用差不多，不知道是不是除了什么问题

**Comment by ZenithalHourlyRate** [comment]
可以发相关日志上来吗，`conda install` 时是否换源。

另：可以尝试 `https://mirrors.bfsu.edu.cn/anaconda/`

**Comment by Yuzuki-N** [comment]
已经按照官方教程换源了，主要是下载`pytorch`时比较慢，还有从镜像站下载`anaconda`时只有几十kb的下载速度，所以提了一个issue

**Comment by ZenithalHourlyRate** [comment]
据了解，主站目前在对服务器进行一些操作，有时可能速度不太行；内部正在解决该问题。推荐使用bfsu的镜像。

**Comment by wanzysky** [comment]
反复出现同样的问题，已尝试很多次：

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by skyzh** [comment]
```
curl -v https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2
```

看看结果？

也可以考虑使用 bfsu 源。

**Comment by shankerwangmiao** [comment]
> 反复出现同样的问题，已尝试很多次：
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.

Connection Failed 建议您排查服务器到 TUNA 的网络是否能联通。

**Comment by wanzysky** [comment]
手动下载偶尔可以的，但是速度很慢，1G+的包大概需要1h。
另外访问主页面都不会有问题。
附失败的log：

curl -v https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2
*   Trying 101.6.8.193...
* TCP_NODELAY set
* Connected to mirrors.tuna.tsinghua.edu.cn (101.6.8.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=tuna.tsinghua.edu.cn
*  start date: Apr 14 08:44:00 2021 GMT
*  expire date: Jul 13 08:44:00 2021 GMT
*  subjectAltName: host "mirrors.tuna.tsinghua.edu.cn" matched cert's "*.tuna.tsinghua.edu.cn"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56456fd34600)
> GET /anaconda/cloud/pytorch/linux-64/pytorch-1.8.1-py3.8_cuda11.1_cudnn8.0.5_0.tar.bz2 HTTP/2
> Host: mirrors.tuna.tsinghua.edu.cn
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< server: nginx/1.18.0
< date: Tue, 20 Apr 2021 08:29:33 GMT
< content-type: application/octet-stream
< content-length: 1367239816
< last-modified: Thu, 25 Mar 2021 15:27:16 GMT
< etag: "605cabd4-517e6c88"
< x-tuna-mirror-id: neomirrors
< strict-transport-security: max-age=31536000
< accept-ranges: bytes
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 16366)
* Connection #0 to host mirrors.tuna.tsinghua.edu.cn left intact

**Comment by shankerwangmiao** [comment]
建议尝试使用 mirrors.bfsu.edu.cn
