### ISSUE TITLE
建议增加https://anaconda.org/nvidia/

### ISSUE THREAD

**Issue by psn-anonymous** [tuna/issues#1042]
很多初学者对于NVIDIA NVCC CUDA CUDNN配置很麻烦  conda官方库的cudnn和cuda更新较慢，建议增加nvidia channel
谢谢TUNA

**Comment by ZenithalHourlyRate** [comment]
CUDA 与 cuDNN 需要与下层的显卡驱动相配合，感觉单独镜像的意义不大。
