### ISSUE TITLE
[tuna]Mirror Request for ntensorflow-1.2.0-cp36-cp36m-win_amd64.whlew mirror 404-help-hidden.html

### ISSUE THREAD

**Issue by Panzhongsheng** [tuna/issues#1043]
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by ZenithalHourlyRate** [comment]
该文件在 <https://pypi.tuna.tsinghua.edu.cn/packages/8e/4b/764e86b8b6a61ca49c9f6fb55b4193063f7021e2c1c51cde7bbf228158b4/tensorflow-1.2.0-cp36-cp36m-win_amd64.whl> 中。

TUNA 已经镜像了pypi，下载 wheel 文件请通过 pip。可以参见[帮助页面](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)。
