### ISSUE TITLE
基于ubuntu 16.04构建docker镜像时换源, 报404错误

### ISSUE THREAD

**Issue by leyiwang** [tuna/issues#1044]
#### 发生了什么（What happened）
基于ubuntu 16.04构建docker镜像时换源, 报如下错误：
```
Get:34 http://mirrors.tuna.tsinghua.edu.cn/ubuntu xenial-updates/main amd64 unattended-upgrades all 1.1ubuntu1.18.04.7~16.04.6 [42.1 kB]
Fetched 15.5 MB in 4s (3363 kB/s)
E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/d/distro-info-data/distro-info-data_0.28ubuntu0.14_all.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
#### 如何重现（How to reproduce it）
```
RUN sed -i s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g /etc/apt/sources.list && apt-get clean && apt update && \
apt-get install -y apt-utils libffi-dev zlibc zlib1g-dev openssl libssl-dev libsm6 libxrender1 libfontconfig1 lrzsz \
net-tools iputils-ping telnet curl wget vim debconf-utils gcc g++ make unzip language-pack-en

```
#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 16.04
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by ZenithalHourlyRate** [comment]
在上游，即（http://archive.ubuntu.com/ubuntu/pool/main/d/distro-info-data/ ）中也不存在 `distro-info-data_0.28ubuntu0.14_all.deb` 文件。

重现dockerfile中使用的是阿里云镜像，而非TUNA。

此问题应该报给上游。

**Comment by leyiwang** [comment]
> 在上游，即（http://archive.ubuntu.com/ubuntu/pool/main/d/distro-info-data/ ）中也不存在 `distro-info-data_0.28ubuntu0.14_all.deb` 文件。
> 
> 重现dockerfile中使用的是阿里云镜像，而非TUNA。
> 
> 此问题应该报给上游。

不好意思，复现应该是清华源，已更新，更换了阿里源后问题解决了

**Comment by ZenithalHourlyRate** [comment]
那 TUNA 应该是在一些其他的文件上出现问题，在 `apt-get update` 后从 TUNA 获取的数据库指向的是老的 `distro-info-data_0.28ubuntu0.14_all.deb` 而阿里云指向的是新的 `distro-info-data_0.28ubuntu0.16_all.deb`。

如果使用 BFSU 作为镜像源是否可以复现该问题？

需要深入调查。

**Comment by shankerwangmiao** [comment]
目前可见镜像站上的包列表均已更新至  distro-info-data_0.28ubuntu0.16

**Comment by ZenithalHourlyRate** [comment]
`docker build` 未能复现上述问题
