### ISSUE TITLE
【安全通知】PyPI 官方仓库遭遇covd恶意包投毒

### ISSUE THREAD

**Issue by light4** [tuna/issues#1045]
如果可以请删掉这个包，或者 Nginx 加个禁止访问。
<https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/c3/40/c101fc829b5101f1f8259590b4f1075ddd489c4041ac21d06f77451a5f8f/>

[【安全通知】PyPI 官方仓库遭遇covd恶意包投毒](https://security.tencent.com/index.php/blog/msg/170)

**Comment by shankerwangmiao** [comment]
您好，该问题已经处理。感谢反馈。
