### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by SunHui-Candy** [tuna/issues#1048]
在 macOS Big Sur版本上，

s@s ~ %  Git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master
Cloning into 'master'...
remote: Counting objects: 4504119, done.
remote: Compressing objects: 100% (1314723/1314723), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by shankerwangmiao** [comment]
您好，该问题是网络不稳定所致，请重试一至二次，如果仍然有问题，请尝试使用 mirrors.bfsu.edu.cn
