### ISSUE TITLE
镜像请求：PyTorch Wheels

### ISSUE THREAD

**Issue by TooYoungTooSimp** [tuna/issues#1050]
#### 项目名称与简介(Project Intro.)
PyTorch Wheels
当使用pip安装pytorch时，官网提供了
```
pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```
这种方式，tuna现在只镜像了conda中的pytorch部分，但是并没有镜像wheel部分。
#### 上游地址与镜像方法(How to Mirror)
https://download.pytorch.org/whl/torch_stable.html
镜像方法：lftp
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
暂时不知，我猜可能有几十gb
- 希望达到的效果
通过
```
pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -f https://mirrors.tuna.tsinghua.edu.cn/pytorch/whl/torch_stable.html
```
就能使用pip安装pytorch。

**Comment by ZenithalHourlyRate** [comment]
例如 ` https://pypi.tuna.tsinghua.edu.cn/packages/80/2a/58f8078744e0408619c63148f7a2e8e48cf007e4146b74d4bb67c56d161b/torch-1.7.0-cp36-cp36m-manylinux1_x86_64.whl`，TUNA已经镜像 pypi，您可以尝试一下

```bash
pip install torch===1.7.0 torchvision===0.8.1 torchaudio===0.7.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
来通过 pip 安装 pytorch

**Comment by TooYoungTooSimp** [comment]
pytorch只向pypi上上传了某个特定版本（现在是linux/cu10.2），而其他系统（Windows）或者其他版本（cu11.0）的wheels都没有上传到pypi，也就没有被tuna镜像到。现在希望的就是所有的这种包都能被镜像到。

// 确实最近tuna的pypi有时候会read timeout，我还以为我网不好

**Comment by Harry-Chen** [comment]
> pytorch只向pypi上上传了某个特定版本（现在是linux/cu10.2），而其他系统（Windows）或者其他版本（cu11.0）的wheels都没有上传到pypi，也就没有被tuna镜像到。现在希望的就是所有的这种包都能被镜像到。
> 
> // 确实最近tuna的pypi有时候会read timeout，我还以为我网不好

目前看起来对于非默认 variant 的需求并不是很大，而用户也可以使用安装对应版本 CUDA  的方式来解决（conda 似乎能够自行处理这个问题）。所以我们不会立刻接受这个请求，如果有类似的需求较大，再考虑继续推进。

**Comment by skyzh** [comment]
SJTUG 已经上线该镜像。可以通过 `-f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html` 使用。

```
pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
```

**Comment by ZenithalHourlyRate** [comment]
考虑到 SJTU 已有该镜像，该 issue 关闭。如果有更多需求，可以重新开启该 issue。
