### ISSUE TITLE
Homebrew 首次安装困难

### ISSUE THREAD

**Issue by holymonson** [tuna/issues#1056]
根据 https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/ 

> ### 首次安装 Homebrew
> 
> 官网上提供的安装脚本是 `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"` ，为了加速克隆的速度，你需要下载 `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` 并编辑其中的：
> 
> ```
> BREW_REPO="https://github.com/Homebrew/brew"
> # 变成：
> BREW_REPO="https://{{ site.hostname }}/git/homebrew/brew.git"
> ```
> 
> 接着，运行 `install.sh` 以安装 Homebrew：
> 
> ```
> HOMEBREW_CORE_GIT_REMOTE=https://{{ site.hostname }}/git/homebrew/homebrew-core.git bash install.sh
> ```
> 
> 这样在首次安装的时候也可以使用镜像。

本来`Homebrew`镜像在tuna都有，唯独安装时需要的`install.sh`在墙外，但新系统的梯子又要通过`Homebrew`安装，于是装起来就很麻烦。

希望能够镜像`https://github.com/Homebrew/install`，或者单独代理`install.sh`文件（原始或修改过`BREW_REPO`的都可以）。

**Comment by jiegec** [comment]
这一个文件应该还是可以直接下载下来的吧？

**Comment by holymonson** [comment]
> 这一个文件应该还是可以直接下载下来的吧？

```
❯ curl -Lv https://raw.githubusercontent.com/Homebrew/install/master/install.sh
*   Trying 151.101.228.133:443...
* connect to 151.101.228.133 port 443 failed: Connection refused
* Failed to connect to raw.githubusercontent.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
```
`raw.githubusercontent.com`的连通性一直都很浮云。。

**Comment by YadominJinta** [comment]
https://cdn.jsdelivr.net/gh/Homebrew/install@master/install.sh

**Comment by IITII** [comment]
> > 这一个文件应该还是可以直接下载下来的吧？
> 
> ```
> ❯ curl -Lv https://raw.githubusercontent.com/Homebrew/install/master/install.sh
> *   Trying 151.101.228.133:443...
> * connect to 151.101.228.133 port 443 failed: Connection refused
> * Failed to connect to raw.githubusercontent.com port 443: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
> ```
> 
> `raw.githubusercontent.com`的连通性一直都很浮云。。

GitHub有 jsdelivr.net 的cdn加速，如 @YadominJinta 给出的链接

你可以将一键脚本修改为：

```bash
/bin/bash -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/Homebrew/install@master/install.sh)"
```

再进行尝试。

**Comment by holymonson** [comment]
> GitHub有 jsdelivr.net 的cdn加速，如 @YadominJinta 给出的链接
> 
> 你可以将一键脚本修改为：
> 
> ```shell
> /bin/bash -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/Homebrew/install@master/install.sh)"
> ```
> 
> 再进行尝试。

其实这个问题我是已经解决了的，从别的机器传个`install.sh`不难，但对于其他后来者而言，这始终是个坑。而且之前我遇到一个情况，需要在学校一台服务器上装`linuxbrew`，该服务器不连外网、只有校内网和教育网IPv6，那 cdn.jsdelivr.net 的解决方案就不可行了。

所以，我还是优先建议 tuna 能以某种方式提供`install.sh`；次之，将上面的 cdn.jsdelivr.net 方案贴到 help 里（但这一定程度是给 cdn.jsdelivr.net 做背书了）。

**Comment by Harry-Chen** [comment]
tuna 和 bfsu 部署了 homebrew/install.git，更新了帮助
