### ISSUE TITLE
[linuxbrew-bottles] Failed to download resource "openssl@1.1"

### ISSUE THREAD

**Issue by mumashanren** [tuna/issues#1057]
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Error: Failed to download resource "openssl@1.1"
Download failed: https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz

But linuxbrew.bintray.com is ok

==> Downloading https://linuxbrew.bintray.com/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/61/61bf82b4b62e07589dec1fdc9eb9eb053da01565581fb18dd5df6232182238ec?__gda__=exp=1606235004~hmac=e668bdb2312764a6996a5146431a77ac0b5acea782fe86812e34fefc47c74687&re
#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu 20.04

**Comment by shankerwangmiao** [comment]
dup of https://github.com/tuna/tunasync-scripts/issues/104
