### ISSUE TITLE
希望可以对Arch linux 32进行镜像

### ISSUE THREAD

**Issue by Mdog2008** [tuna/issues#1058]
#### 
项目名称：Arch linux 32 简介：Arch linux 32是一个来自社区的Arch Linux 发行版，因为Arch Linux官方不再对32位设备产生

#### 上游地址与镜像方法(How to Mirror)
上游地址：https://mirror.archlinux32.org/$arch/$repo/ 镜像方法同arch
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
~~~希望清华tuna协会耗子尾汁，抓紧上源，开源界要以和

**Comment by ZenithalHourlyRate** [comment]
Dup of #926

合并至 #926 处理。

**Comment by Harry-Chen** [comment]
> `~~~希望清华tuna协会耗子尾汁，抓紧上源，开源界要以和`

P.S. 请勿在 issue 中发表 off-topic 的言论。
