### ISSUE TITLE
更新ROS2软件包列表出错

### ISSUE THREAD

**Issue by simon7238** [tuna/issues#1059]
#### 发生了什么（What happened）
我今天更新用sudo apt update更新ROS2软件包列表时出现以下错误：
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/dists/bionic/main/binary-i386/Packages  404  Not Found [IP: 101.6.8.193 443]
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。
出现了该错误之后，我直接到https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/dists/bionic/查看Release文件情况，发现以下内容：
Origin: ROS
Label: ROS bionic
Suite: bionic
Codename: bionic
Date: Sat, 28 Nov 2020 23:18:44 UTC
Architectures: i386 amd64 arm64 armhf
但是我再查看Index of /ros2/ubuntu/dists/bionic/main/时只找到以下三个索引：
binary-amd64/
binary-arm64/
binary-armhf/
这明显与Release文件内容相矛盾。

#### 期望的现象（What you expected to happen）
希望能修正Release文件错误，或者增加binary-i386/索引内容。谢谢！

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu18.04 AMD64版本
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by jiegec** [comment]
您好，我们目前只同步了 amd64 armhf 和 arm64 三个架构，暂不包括 i386.

**Comment by simon7238** [comment]
> 
> 
> 您好，我们目前只同步了 amd64 armhf 和 arm64 三个架构，暂不包括 i386.

如果还没有同步完成，能否先屏蔽i386架构呢？这样其它架构可以先更新或安装起来。谢谢！

**Comment by jiegec** [comment]
在其他镜像里，不同步 i386 也可以正常使用其他架构的包。您的环境中是否配置了 i386 的设置？

**Comment by simon7238** [comment]
> 
> 
> 在其他镜像里，不同步 i386 也可以正常使用其他架构的包。您的环境中是否配置了 i386 的设置？

我的环境中应该是没有配置 i386 的设置，之前也是能正常更新的，只是更新过程中会提示i386有异常，自动屏蔽掉了。但是今天不知道为什么更新的时候一直都报错，无法正常更新。

**Comment by shankerwangmiao** [comment]
我无法复现您的故障，请您给出 `dpkg --print-architecture` 和 `dpkg --print-foreign-architectures` 的输出。

**Comment by simon7238** [comment]
> 
> 我无法复现您的故障，请您给出 `dpkg --print-architecture` 和 `dpkg --print-foreign-architectures` 的输出。
> […](#)
> 2020年11月30日 16:32，simon7238 ***@***.***> 写道： 在其他镜像里，不同步 i386 也可以正常使用其他架构的包。您的环境中是否配置了 i386 的设置？ 我的环境中应该是没有配置 i386 的设置，之前也是能正常更新的，只是更新过程中会提示i386有异常，自动屏蔽掉了。但是今天不知道为什么更新的时候一直都报错，无法正常更新。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dpkg --print-architecture的输出是amd64
dpkg --print-foreign-architectures的输出i386

**Comment by jiegec** [comment]
> dpkg --print-foreign-architectures的输出i386

问题就在这里。

**Comment by simon7238** [comment]
> 
> 
> > dpkg --print-foreign-architectures的输出i386
> 
> 问题就在这里。

我通过sudo dpkg --remove-architecture i386去除i386架构，已经可以正常更新软件包了，谢谢！
