### ISSUE TITLE
Homebrew 镜像使用帮助 地址配置错误

### ISSUE THREAD

**Issue by qhsong** [tuna/issues#106]
帮助中设置remote地址为：
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/brew.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew-core.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew-science.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew-python.git`

实际应该为：
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/homebrew/brew.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-core.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-science.git`
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-python.git`

**Comment by bigeagle** [comment]
我试了一下 `https://mirrors.tuna.tsinghua.edu.cn/git/homebrew-python.git` 这个地址可以 clone 下来呀……

你写的地址是旧镜像，一个月没更新了…… 我忘了删

**Comment by bigeagle** [comment]
我根据现在的情况更新了一下，https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/ 再试试？

**Comment by qhsong** [comment]
我试试

**Comment by qhsong** [comment]
`git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git`
这个在fetch的时候报错：
```
error: inflate: data stream error (invalid distance too far back)
fatal: pack has bad object at offset 32330497: inflate returned -3
error: Unable to find efc271f683e8d00ebf62cfcc1f928c1291f8fd36 under https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Cannot obtain needed object efc271f683e8d00ebf62cfcc1f928c1291f8fd36
error: fetch failed.
```

难道是我homebrew的问题？

**Comment by qhsong** [comment]
2333，怎么404了，大鹰你在维护么？

**Comment by bigeagle** [comment]
我直接 git clone 是可以的…… 难道跟历史有关系？
404 是把那个旧的删了，现在所有 git 镜像都在另一台机器上

**Comment by qhsong** [comment]
现在可以了，应该修复了。多谢大鹰。
