### ISSUE TITLE
[tuna]Mirror Request for new mirror github-release

### ISSUE THREAD

**Issue by ray-zyh** [tuna/issues#1060]
#### 项目名称与简介(Project Intro.)
window freeCAD镜像
#### 上游地址与镜像方法(How to Mirror)
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x64-installer.exe
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
486MB

**Comment by shankerwangmiao** [comment]
您好，目前 FreeCAD 最新的版本是 0.18.5，而上游在 Releases 中并未提供编译好的二进制文件。因此我们未能成功镜像有意义的文件。

参见：https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.5
