### ISSUE TITLE
debian8 软件源404

### ISSUE THREAD

**Issue by DATA-GaMi** [tuna/issues#1061]
#### 发生了什么（What happened）
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/dists/jessie-backports/main/binary-amd64/Packages  
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/dists/jessie-backports/contrib/binary-amd64/Packages  
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/dists/jessie-backports/non-free/binary-amd64/Packages  HttpError404
E: Some index files failed to download. They have been ignored, or old ones used instead.
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
与 #539 类似。

**Comment by shankerwangmiao** [comment]
jessie-backports 已经被上游移除
