### ISSUE TITLE
Garuda Linux

### ISSUE THREAD

**Issue by h0cheung** [tuna/issues#1062]
#### 项目名称与简介(Project Intro.)

[Garuda Linux](https://garudalinux.org/)

一个 Arch Linux 的衍生发行版，使用 Arch Linux 的官方仓库加自己的仓库。

该仓库最大的特点是移植了 manjaro 的一套 GUI 配置工具（好像还有自己的）。 同时有不少 AUR 的打包，和 archlinuxcn 有较小程度重合。

直观感觉，该发行版较注重开箱即用和美化，提供大量桌面环境选择。 定制程度高于 EndeavourOS 和 Arco Linux，比如前面提到的 GUI 工具、较高程度的美化、默认使用 btrfs 并配置好 timeshift、默认使用 Linux-zen 并默认提供一些性能调整等。

它移植的 GUI 工具本人在 Arch Linux 上安装测试表现很好，未发现明显 bug。

#### 上游地址与镜像方法(How to Mirror)

 rsync://lonewolf-builder.duckdns.org/chaotic-aur/
 使用 rsync，`--exclude='/archive' --exclude='/lost+found' --exclude='/makepkglogs' --exclude='/pkgs.txt' --exclude='/*.html'  `

#### 其他信息(Other)
 - 镜像大小(Mirror Size): 约 116.8 GB

**Comment by ZenithalHourlyRate** [comment]
参考 #1009
