### ISSUE TITLE
镜像请求：Leptonica

### ISSUE THREAD

**Issue by ijliym** [tuna/issues#1063]
项目名称：Leptonica
项目简介：Leptonica 是一个面向教学的开源网站，广泛的应用于图像处理和图像分析的应用中。
上游源地址：
http://www.leptonica.org/download.html
http://www.leptonica.org/source/leptonica-1.80.0.tar.gz

尽量详细的镜像信息
大小：`leptonica-1.80.0.tar.gz 13.3MB`

**Comment by ZenithalHourlyRate** [comment]
该软件已经被各大发行版（经过调查Arch，Debian，Ubuntu均有该包）打包，是否有单独镜像的必要

**Comment by shankerwangmiao** [comment]
一般这种情况，TUNA 不再镜像。

**Comment by ijliym** [comment]
Debian可以直接安装`Tesseract+Leptonica`，这个我知道，但是我们公司用的是CentOS，生成Docker镜像的时候，也只能用CentOS，再源码安装`Tesseract+Leptonica`，但是`Leptonica`下载太慢了。

**Comment by shankerwangmiao** [comment]
您好，CentOS 可以使用 epel，后者 TUNA 有镜像。

**Comment by ijliym** [comment]
有道理，我等会试试。多谢！
