### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/centos/6/os/x86_64/repodata/repomd.xml

### ISSUE THREAD

**Issue by dongshaoshuai** [tuna/issues#1067]
404

**Comment by jiegec** [comment]
centos 6 is obsolete.

**Comment by shankerwangmiao** [comment]
如果你仍然需要获取 centos6 的软件包，可以考虑使用 https://mirrors.tuna.tsinghua.edu.cn/centos-vault/ 。但是请留意 CentOS6 已经停止了支持，因此您不会获得任何软件更新，包括安全性更新。
