### ISSUE TITLE
melpa出错

### ISSUE THREAD

**Issue by scateu** [tuna/issues#107]
使用                         ("melpa" . "http://elpa.zilongshanren.com/melpa/")))  则无问题...

**Comment by bigeagle** [comment]
太模糊了……

**Comment by scateu** [comment]
没事，先放一下好了。

我在Mac上的Emacs没问题，只是在Windows上的Emacs出了这个错误。

也有可能是我的Emacs知识水平还不太够....

先记录一下好了。我再去水木emacs版上问问...
