### ISSUE TITLE
【镜像请求】Microsoft packages镜像

### ISSUE THREAD

**Issue by hmsjy2017** [tuna/issues#1070]
#### 项目名称与简介(Project Intro.)

适用于 Microsoft 产品的 Linux 软件存储库

Microsoft 构建并支持适用于 Linux 系统的各种软件产品，并使它们可通过标准 APT 和 YUM 程序包存储库提供。

#### 上游地址与镜像方法(How to Mirror)

https://packages.microsoft.com/

支持apt/yum，rsync未知

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

文档：https://docs.microsoft.com/zh-cn/windows-server/administration/linux-package-repository-for-microsoft-software

**Comment by shankerwangmiao** [comment]
dup with #335
