### ISSUE TITLE
[tuna]404 at /centos/6/os/x86_64/repodata/repomd.xml

### ISSUE THREAD

**Issue by gutfpgpm2020** [tuna/issues#1071]
#### 发生了什么（What happened）
[root@localhost ~]# yum makecache
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
https://mirrors.tuna.tsinghua.edu.cn/centos/6/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again

#### 您的环境（Environment）
- 操作系统（OS Version）：centos6
- 浏览器（如果适用）（Browser version, if applicable）：chrome
- 其他（Others）：

**Comment by phy25** [comment]
#1067
