### ISSUE TITLE
epel6官网镜像给删除了，有没有vault存档可用

### ISSUE THREAD

**Issue by 1265578519** [tuna/issues#1072]
epel6官网镜像给删除了，有没有vault存档可用

http://fedoraproject.org/wiki/EPEL/zh-cn

就和centos官方的centos-vault版本一样
https://vault.centos.org/

**Comment by 1265578519** [comment]
找到了，https://archives.fedoraproject.org/pub/archive/epel/
镜像站能加一份吗？

**Comment by ZenithalHourlyRate** [comment]
参考 #872
如果相关需求增加，可以重新打开改 issue。

**Comment by 1265578519** [comment]
希望增加一份单独的epel-archives同步官方这个存档库，需要使用centos6版本的2.6内核
