### ISSUE TITLE
Mirror Requests 镜像请求

### ISSUE THREAD

**Issue by HealerKnight** [tuna/issues#1074]
omnirom
Open Source Android Firmware
https://github.com/omnirom
也很出名的第三方rom版本，托管在github上，但是访问速度非常慢，请求能添加该rom源

**Comment by shankerwangmiao** [comment]
请问具体要镜像什么？

**Comment by HealerKnight** [comment]
> 请问具体要镜像什么？
和aosp以及lineageos一样，镜像该安卓三方系统项目的所有仓库源码以方便下载编译该三方安卓系统
