### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/  无法访问

### ISSUE THREAD

**Issue by myFrank** [tuna/issues#1075]
#### 发生了什么（What happened）
您好，我本来是打算下载https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/qt-5.6.2-vc14_1.tar.bz2这个文件的，但是在网站上显示找不到了，所以我退回上一目录，只显示了“Too many files to list”这句话，解决不了，麻烦您
看一下
#### 期望的现象（What you expected to happen）
能够下载我所需要的文件
#### 您的环境（Environment）
win10
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
QQ浏览器、谷歌浏览器
- 其他（Others）：

**Comment by myFrank** [comment]
![问题](https://user-images.githubusercontent.com/28703200/101352468-28451800-38cd-11eb-8adb-2703f02594e2.jpg)

**Comment by shankerwangmiao** [comment]
您好，上述文件并不存在，该目录由于文件过多，不开放目录浏览。建议您使用正确的使用方式安装 Anaconda 的软件包。

**Comment by myFrank** [comment]
> 您好，上述文件并不存在，该目录由于文件过多，不开放目录浏览。建议您使用正确的使用方式安装 Anaconda 的软件包。
您好我主要是下载此目录的下的如下文件
jpeg-9b-vc14_2.tar.bz2
libtiff-4.0.9-vc14_0.tar.bz2
qt-5.6.2-vc14_1.tar.bz2
您看有镜像链接没

**Comment by shankerwangmiao** [comment]
上述文件皆不存在

**Comment by myFrank** [comment]
> 上述文件皆不存在

好的 多谢 我去找找  
麻烦了
