### ISSUE TITLE
【镜像请求】OpenWrt Snapshot

### ISSUE THREAD

**Issue by hmsjy2017** [tuna/issues#1076]
#### 项目名称与简介(Project Intro.)
名称：OpenWrt Snapshot
OpenWrt 第三方源，作为官方源的补充，收录了市面上大部分主流第三方插件
适用于 [OpenWrt Snapshot](https://github.com/garypang13/Actions-OpenWrt) 固件

#### 上游地址与镜像方法(How to Mirror)
https://op.supes.top/packages/
支持opkg，其他方式未知
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
10GB以下

**Comment by shankerwangmiao** [comment]
您好，我们不考虑为该仓库提供镜像服务，具体原因如下：

1. 该仓库所含软件数量、大小过少；
2. 我们无法证实该仓库有一定的用户量；
3. 该仓库的部分软件存在重分发授权问题。

**Comment by ZR-RAN** [comment]
1.红米AC2100路由器使用人数不少吧https://openwrt.org/toh/xiaomi/xiaomi_redmi_router_ac2100，目前该路由器只有snapshot系统可以下载。
2.能说明一下“重分发授权问题”是指的什么吗？

**Comment by ZR-RAN** [comment]
红米AC2100路由器使用人数不少吧，只需要/openwrt/snapshots/targets/ramips/mt7621目录下的文件

**Comment by shankerwangmiao** [comment]
特定型号设备的销售量与第三方固件的需求量没有必然联系。openwrt 官方镜像中的 snapshot 目录由于更新过于频繁，无法在合理时间内完成同步，因此被排除在同步的范围之外。

重分发授权问题是指一个软件的权利所有人是否允许第三方向不特定多数人重分发或再分发该软件。

**Comment by hmsjy2017** [comment]
> 重分发授权问题

仓库里面都是开源软件，也会有重分发授权问题吗？

**Comment by shankerwangmiao** [comment]
> > 重分发授权问题
> 
> 
> 
> 仓库里面都是开源软件，也会有重分发授权问题吗？

开源软件，无论许可证，在多数情况下不会有这样的问题。但是具体到该镜像请求所提及的仓库，里面有部分软件并非开源软件，其许可也并不允许再分发和重分发。
