### ISSUE TITLE
更新时 gitlab-ce 报 Hash Sum mismatch

### ISSUE THREAD

**Issue by jk2K** [tuna/issues#108]
执行`apt-get update`时报

`W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch`

**Comment by bigeagle** [comment]
正在同步，等同步完

**Comment by jk2K** [comment]
还没同步完？

**Comment by bigeagle** [comment]
查了下，脚本写错了。
