### ISSUE TITLE
请求建立 PuTTY 镜像

### ISSUE THREAD

**Issue by hmsjy2017** [tuna/issues#1080]
#### 项目名称与简介(Project Intro.)
PuTTY 是一款开源免费的远程登录工具，支持SSH、Telnet、Serial等协议的连接。该软件支持Windows和Unix。
软件很小，但国内下载极慢
#### 上游地址与镜像方法(How to Mirror)
同步方法：https://www.chiark.greenend.org.uk/~sgtatham/putty/mirrors.html#guidelines
支持rsync
rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by 210hcl** [comment]
https://mirror.bit.edu.cn/putty/latest.html
北京理工大学有镜像

**Comment by skyzh** [comment]
> https://mirror.bit.edu.cn/putty/latest.html
> 北京理工大学有镜像

https://mirrors.sjtug.sjtu.edu.cn/putty/ 也欢迎使用我们的镜像。补充一下信息，镜像大小为 57M。

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/putty/ 已经增加该镜像
