### ISSUE TITLE
jenkins 镜像下载速度不稳定

### ISSUE THREAD

**Issue by c332030** [tuna/issues#1081]
#### 发生了什么（What happened）
jenkins war 包下载速度不稳定，刚开始可以跑满 2m/s（宽带最大速度），然后越来越慢，最后下载失败

#### 期望的现象（What you expected to happen）
不要求很快，能稳定下载就行

#### 如何重现（How to reproduce it）
wget https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.263.1/jenkins.war

#### 您的环境（Environment）
- 操作系统（OS Version）：centos8
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

[root@work ~]# wget https://get.jenkins.io/war-stable/2.263.1/jenkins.war
--2020-12-10 10:35:43--  https://get.jenkins.io/war-stable/2.263.1/jenkins.war
Resolving get.jenkins.io (get.jenkins.io)... 52.202.51.185
Connecting to get.jenkins.io (get.jenkins.io)|52.202.51.185|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.263.1/jenkins.war [following]
--2020-12-10 10:35:44--  https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.263.1/jenkins.war
Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.8.193, 2402:f000:1:408:8100::1
Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.8.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67270143 (64M) [application/java-archive]
Saving to: ‘jenkins.war’

jenkins.war                                      30%[==============================>                                                                        ]  19.74M   102KB/s    eta 2m 38s

![image](https://user-images.githubusercontent.com/15310784/101714248-1e413600-3ad4-11eb-85e2-a350c9738aac.png)

**Comment by shankerwangmiao** [comment]
您好，该问题系已知问题，我们正在设法处理，但是时间可能较长。您可以重试几次，或者使用 mirrors.bfsu.edu.cn
