### ISSUE TITLE
请求: 配置nginx支持文本文件gzip传输

### ISSUE THREAD

**Issue by holymonson** [tuna/issues#1082]
每次conda更新，都需要下载元数据文件 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64/repodata.json ，近百M，而且不会断点续传，一旦断了就得从头来，很是痛苦，也增加了服务器压力。

nginx本身就有gzip和gzip_static模块，支持文本文件压缩传输，TUNA是否可考虑打开相关配置？感谢。

**Comment by shankerwangmiao** [comment]
您好，开启 gzip 压缩会给服务器带来非常大量的 CPU 开销，并且由于 gzip 压缩效率问题，可能导致传输速率反而不如不压缩。anaconda 提供了压缩后的 repodata，例如： https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64/repodata.json.bz2。
