### ISSUE TITLE
【服务故障】rapids

### ISSUE THREAD

**Issue by ysq151944** [tuna/issues#1083]
您好，我按https://rapids.ai/start.html#details的官方代码安装rapids：
conda create -n rapids-core-0.17 -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.17 python=3.8 cudatoolkit=11.0

返回：
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: rapidsai
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/rapidsai
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by ZenithalHourlyRate** [comment]
能贴上来您的 `conda config --show channels` 的输出吗

**Comment by ysq151944** [comment]
> 能贴上来您的 `conda config --show channels` 的输出吗

channels:
  - defaults

**Comment by ZenithalHourlyRate** [comment]
对于例如 rapids 之类的 第三方 channel，其镜像在 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud 中，需要您手动在 `custom_channels` 中添加

**Comment by shankerwangmiao** [comment]
该包正确的路径是 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/rapidsai/ ，建议您手动在 channels 中仿照其它 channel 添加。

**Comment by ysq151944** [comment]
> 对于例如 rapids 之类的 第三方 channel，其镜像在 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud 中，需要您手动在 `custom_channels` 中添加

您好：

我在~/.condarc 中添加了，目前是：
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  rapidsai: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud


输入conda create -n rapids-core-0.17 -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.17 python=3.8 cudatoolkit=11.0

返回：
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: nvidia
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/nvidia
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

我在列表中（https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/）找了，没有nvidia这个文件夹，请问我该怎么处理？

**Comment by ysq151944** [comment]
> 该包正确的路径是 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/rapidsai/ ，建议您手动在 channels 中仿照其它 channel 添加。

您好，我手动添加了rapidsai，这次返回找不到nvidia，但/cloud/下没有这个文件夹，我该添加什么？

**Comment by shankerwangmiao** [comment]
我们并镜像 nvidia 的第三方频道，您可以有两种处理方式，一个是编辑 channels 将 nvidia 指向 anaconda 上游；或者可以使用 anaconda 官方源里的 cudatoolkit。

**Comment by ysq151944** [comment]
> 我们并未镜像 nvidia 的第三方频道，您可以有两种处理方式，一个是编辑 channels 将 nvidia 指向 anaconda 上游；或者可以使用 anaconda 官方源里的 cudatoolkit。

您好，我不太明白具体怎么操作，已经尝试了1个多小时。

能否麻烦你你贴一下您的~/.condarc ？

**Comment by skyzh** [comment]
把 `channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda` 去掉即可。

**Comment by skyzh** [comment]
btw, 建议帮助文档中去掉这几行。去掉也可以照常工作，并且可以避免 conda 使用镜像下载官方源未同步的内容。

<img width="947" alt="image" src="https://user-images.githubusercontent.com/4198311/101987016-7b074100-3ccc-11eb-88ea-4a6aafaaec12.png">

**Comment by ysq151944** [comment]
> * 若使用 `nvidia` channel 安装，把 `channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda` 去掉即可。
> * 若使用镜像安装，在安装指令中去掉 `-c nvidia` 即可。

非常感谢！

使用 nvidia channel 安装。

但若去掉-c nvidia，会报错：
(base) ysq@ysq-virtual-machine:~$ conda create -n rapids-core-0.17 -c rapidsai -c conda-forge -c defaults rapids=0.17 python=3.8 cudatoolkit=11.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
rapids=0.17 -> cudatoolkit=11.0 -> libgcc-ng[version='>=4.9|>=7.3.0|>=9.3.0|>=7.5.0|>=7.2.0']
cudatoolkit=11.0 -> libgcc-ng[version='>=7.3.0|>=9.3.0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']

Package python conflicts for:
rapids=0.17 -> cupy[version='>7.1.0,<9.0.0a0'] -> python[version='3.7.*|3.8.*|>=3.5|>=3.6|>=3.6,<3.7.0a0|>=3.9,<3.10.0a0']
python=3.8
rapids=0.17 -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Package cudatoolkit conflicts for:
rapids=0.17 -> cudatoolkit[version='10.1.*|11.0.*|10.2.*']
cudatoolkit=11.0
rapids=0.17 -> cudf=0.17 -> cudatoolkit[version='10.0|10.0.*|10.1|10.1.*|11.0|11.0.*|>=10.1.243,<10.2.0a0|>=11.0.221,<11.1.0a0|>=10.2.89,<10.3.0a0|10.2|10.2.*|9.2|9.2.*']

Package _libgcc_mutex conflicts for:
cudatoolkit=11.0 -> libgcc-ng[version='>=9.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
python=3.8 -> libgcc-ng[version='>=9.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - cudatoolkit=11.0 -> __glibc[version='>=2.17,<3.0.a0']
  - rapids=0.17 -> cudatoolkit=11.0 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.27

**Comment by ZenithalHourlyRate** [comment]
On Sat, Dec 12, 2020 at 06:51:23AM -0800, Alex Chi wrote:
> btw, 建议帮助文档中去掉这几行。去掉也可以照常工作，并且可以避免 conda 使用镜像下载官方源未同步的内容。

已经作出相关修改，参见该 commit 

https://github.com/tuna/mirror-web/commit/606ae3a2b6061dd7ebcd9859415eacb2bd158535

-- 
GPG Fingerprint: 1127F188280AE3123619332987E17EEF9B18B6C9
