### ISSUE TITLE
【其他事项】conda安装rapids遇到的问题

### ISSUE THREAD

**Issue by ysq151944** [tuna/issues#1084]
您好，我按https://rapids.ai/start.html#details的官方代码安装rapids：
conda create -n rapids-core-0.17 -c rapidsai -c nvidia -c conda-forge
-c defaults rapids=0.17 python=3.8 cudatoolkit=11.0

返回：
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
channel name: nvidia
channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/nvidia
error code: 404

You will need to adjust your conda configuration to proceed.
Use conda config --show channels to view your configuration's current state,
and use conda config --show-sources to view config file locations.

channels:
 - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2

custom_channels:
- conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
- rapidsai: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud

cloud下没有nvidia这个文件夹（https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/）

请问这是否意味着我无法通过清华镜像安装rapids？

**Comment by shankerwangmiao** [comment]
dup with #1083
