### ISSUE TITLE
【镜像请求】postmarketOS

### ISSUE THREAD

**Issue by zuishikonghuan** [tuna/issues#1085]
#### 项目名称与简介(Project Intro.)

postmarketOS

postmarketOS 基于 Alpine Linux，使其可以在智能手机和其他移动设备上运行。

网站：https://postmarketos.org/

#### 上游地址与镜像方法(How to Mirror)

rsync

```
rsync -av --delete rsync://mirror.postmarketos.org::postmarketos postmarketos
```

参考：
http://mirror.postmarketos.org/
https://wiki.postmarketos.org/wiki/Mirrors

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by ZenithalHourlyRate** [comment]
`https://mirrors.{tuna.tsinghua,bfsu}.edu.cn/postmarketOS/` 同步完成。
`https://mirrors.{tuna.tsinghua,bfsu}.edu.cn/postmarketOS-images/` 同步完成。 未同步 old 以及以 . 开头的文件夹
