### ISSUE TITLE
FreeCAD镜像无可用文件

### ISSUE THREAD

**Issue by TonySue2000** [tuna/issues#1087]
到github-release下的FreeCAD文件夹下未看到最新的可用发行版
https://mirrors.tuna.tsinghua.edu.cn/github-release/FreeCAD/FreeCAD/
猜测：几周前FreeCAD发布了0.18.5,但只有源码，并无编译完的二进制文件
同步时就把有二进制文件的0.18.4视为过期，删掉了，但并无新的文件增加

**Comment by shankerwangmiao** [comment]
see #1060 
你猜得对
