### ISSUE TITLE
[Mirror Request] Chaotic-AUR (Garuda Linux)

### ISSUE THREAD

**Issue by KsRyY** [tuna/issues#1088]
- 项目名称: `Chaotic-AUR` (`Garuda Linux`)
- 项目简介: Garuda Linux的附加源, 是AUR中部分Garuda Linux选用的软件的binary distribution
- 镜像方法: [Script](https://gist.github.com/BangL/86c2700e169994bc147ebf076fcb1888)

镜像大小未知, 但是保守估计1~2个GB(包含Garuda的自定义Linux内核和一些附加的Helper GUI, Garuda的KDE Theme和部分Garuda用到的软件插件)

**Comment by ZenithalHourlyRate** [comment]
Dup of #1009
