### ISSUE TITLE
openSUSE 镜像缺少 /update/tumbleweed/ 和 /update/tumbleweed-non-oss/ 文件夹

### ISSUE THREAD

**Issue by OrwillT** [tuna/issues#1091]
#### 发生了什么（What happened）

openSUSE 镜像缺少 /update/tumbleweed/ 和 /update/tumbleweed-non-oss/ 文件夹，无法设置 Main Update Repository 的镜像

#### 期望的现象（What you expected to happen）

能正常设置 Main Update Repository 的镜像

#### 您的环境（Environment）
- 操作系统（OS Version）：openSUSE tumbleweed

**Comment by shankerwangmiao** [comment]
您好，opensuse 滚动升级的源每日变化过大，难以在合理时间内同步完成，因此被过滤掉了。
