### ISSUE TITLE
（镜像请求）Rocky Linux

### ISSUE THREAD

**Issue by QianYuChan** [tuna/issues#1093]
####Rocky Linux
由于RedHat的调整，CentOS将不再发行新版本。原有对CentOS8承诺的截止到2029年的技术支持也缩短到2021年。

CentOS-Stream将不再源于RHEL，而是介于Fedora和RHEL之间，并且是一个滚动更新的Linux发行版。
CentOS创始人由于不满RedHat对CentOS的调整而离职，Rocky Linux诞生。该系统继承原有CentOS的理念，继续源于RHEL源代码进行构建，版本号也继承了CentOS的版本号，从8开始。
即使Rocky还没有发布任何一个版本，我盼望镜像站未来能增加Rocky Linux的镜像。

#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：否

**Comment by shankerwangmiao** [comment]
您好，

据我们所知，CentOS 8Stream 并非完全脱离于 Rhel 发布，也不会像 Archlinux 或者 Debian sid 那样“滚动发行”，只是可以更早地得到将要进入 Rhel8 的包，并且在进入之前，这些包应该都是得到了足够多的测试的。

您提到的 rockylinux 我们暂时不考虑镜像，因为我们无法镜像一个尚不存在的软件。待该软件发布后，我们会再行考虑。

**Comment by lijhj** [comment]
已经发布了 Rocky Linux 8.4
请建一个镜像源支持国内开发者

**Comment by shankerwangmiao** [comment]
> 已经发布了 Rocky Linux 8.4
> 请建一个镜像源支持国内开发者

See https://github.com/tuna/issues/issues/1236#issuecomment-868641135

**Comment by lijhj** [comment]
其它镜像源带宽都不稳定，有时比从官网下载还慢。国内有些机构建这些镜像源，就是挂羊头卖狗肉，为了和开源挂点边，蹭点名声。
贵校占着国内人民支持的大把资源，可以多支持一下国内开发者。

**Comment by jiegec** [comment]
@lijhj 好奇一下，为什么是支持国内开发者呢？我看了看官网，没有看到什么国内开发者的痕迹。

**Comment by jiegec** [comment]
另外，我看到 Rocky Linux 目前已有的国内镜像有重庆大学，南京大学，山东大学，上海交通大学。

**Comment by shankerwangmiao** [comment]
据我了解，目前 TUNA 镜像站的相关设备并未占用国家纵向经费，谈不上“占着国内人民支持的大把资源”

**Comment by sunmy2019** [comment]
> 有时比从官网下载还慢

说明你选错了源
