### ISSUE TITLE
（镜像请求）Oracle linux

### ISSUE THREAD

**Issue by QianYuChan** [tuna/issues#1095]
#### 项目名称与简介(Project Intro.)
Oracle linux
#### 上游地址与镜像方法(How to Mirror)
https://www.oracle.com/cn/storage/technologies/linux/downloads/default.html
#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：未知

**Comment by happyaron** [comment]
Oracle Linux 官方没有提供例如 rsync 的同步方式，目前无法镜像。

**Comment by stevapple** [comment]
目前 Oracle Linux 官方已经提供了对 [`reposync`](https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-SetUpLocalYumMirror.html#local-yum-mirror) 和 [`rsync`](https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-SetUpLocalYumMirror.html#task_rrh_z2y_4wb) 两种同步工具的支持，希望重新考虑收录
