### ISSUE TITLE
请求在 opentuna 建立 raspbian && raspberrypi 镜像

### ISSUE THREAD

**Issue by makeding** [tuna/issues#1098]
#### 项目名称与简介(Project Intro.)
树莓派（Raspberry Pi）是基于Linux的单片机电脑，由英国树莓派基金会开发。此为树莓派官方系统 Raspberry Pi OS 的软件源。

#### 上游地址与镜像方法(How to Mirror)
#1020

**Comment by shankerwangmiao** [comment]
请见 
[raspberry-pi-os-images](https://mirrors.tuna.tsinghua.edu.cn/raspberry-pi-os-images)
[raspberrypi](https://mirrors.tuna.tsinghua.edu.cn/raspberrypi)
[raspbian](https://mirrors.tuna.tsinghua.edu.cn/raspbian)

**Comment by makeding** [comment]
加急（（（

@jiegec

**Comment by jiegec** [comment]
Done
