### ISSUE TITLE
request for adding linux mirror

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#11]
hello,
         can you add the funtoo linux mirror to your mirror website ? Because the original mirror is too  far for me.

**Comment by zhangteng331** [comment]
the funtoo linux is similar to Gentoo linu, but they are different in some ways.(funtoo linux is forked from Gentoo linux)

**Comment by zhangteng331** [comment]
the funtoo linux mirror lies in github and  some part of files lies in the build.fumtoo.org.

**Comment by huiyiqun** [comment]
There must be a typo: http://build.funtoo.org/

**Comment by zhangteng331** [comment]
Well, what's the meaning of "typo" ?
I wonder whether this mirror will be added to your website.

**Comment by bigeagle** [comment]
Not today.

--
Justin Wong
 
 
On Tue, Dec 29, 2015, at 18:28, zhangteng331 wrote:
> Well, what's the meaning of "typo" ?
> 
I wonder whether this mirror will be added to your website.


> —
> Reply to this email directly or view it on GitHub[1]. 


>  


Links:

  1. https://github.com/tuna/issues/issues/11#issuecomment-167762104

**Comment by zhangteng331** [comment]
OK, I will wait for your reply. I just hope it can be added to there.

**Comment by bigeagle** [comment]
Hi, I've posted a email to (Funtoo mailing list)[https://groups.google.com/forum/#!forum/funtoo-dev], but they seemed to ignore it.

Do you have any means to contact them?
We have two questions:
1. How to mirror funtoo, there's no official document.
2. What's the size of funtoo repo, since we don't have much disk space left.

Cheers,

**Comment by zhangteng331** [comment]
I almost can't find efficient way to solve the problem. Maybe you can
contact Daniel Robbins(he created funtoo) at drobbins@funtoo.org or ask
them at the terrible forum (http://forums.funtoo.org)
2016年1月15日星期五，bigeagle <notifications@github.com> 写道：
