### ISSUE TITLE
Percona 二进制版本

### ISSUE THREAD

**Issue by oneinstack** [tuna/issues#110]
https://mirrors.tuna.tsinghua.edu.cn/percona/ 只有yum和apt，可否加上Percona 源码版本和二进制版本呢？
国内还没有
#### 项目名称与简介(Project Intro.)

Percona
#### 上游地址与镜像方法(How to Mirror)

未知
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by bigeagle** [comment]
官方下载地址可有？

**Comment by lj2007331** [comment]
https://www.percona.com/downloads/Percona-Server-5.7
https://www.percona.com/downloads/Percona-Server-5.6
https://www.percona.com/downloads/Percona-Server-5.7
好像官方没有rsync，可能只能自己写爬虫了

**Comment by guoxiaod** [comment]
Using Percona rsync repositories to set up the local CentOS mirror
https://www.percona.com/blog/2014/02/14/using-percona-rsync-repositories-set-local-centos-mirror/

**Comment by lj2007331** [comment]
@guoxiaod  二进制版本。。。这个只有yum 、apt
