### ISSUE TITLE
[BFSU] 404 at https://mirrors.bfsu.edu.cn/gitlab-ce/debian/pool/buster/main/g/gitlab-ce/gitlab-ce_13.7.0-ce.0_amd64.deb

### ISSUE THREAD

**Issue by laozhoubuluo** [tuna/issues#1100]
#### 发生了什么（What happened）
北外镜像站 https://mirrors.bfsu.edu.cn/gitlab-ce/debian/pool/buster/main/g/gitlab-ce/gitlab-ce_13.7.0-ce.0_amd64.deb 报 404错误，导致 gitlab-ce 软件包无法正常更新。
Tuna 镜像站 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/debian/pool/buster/main/g/gitlab-ce/gitlab-ce_13.7.0-ce.0_amd64.deb 无此问题，可以正常下载。

#### 期望的现象（What you expected to happen）
恢复该文件正常下载。

#### 如何重现（How to reproduce it）
访问相关链接对比。

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：Debian 10
- 浏览器（如果适用）（Browser version, if applicable）：无
- 其他（Others）：配置了 gitlab-ce 镜像

**Comment by shankerwangmiao** [comment]
您好，该问题已经处理。感谢反馈。
