### ISSUE TITLE
OpenCAD的镜像没有了

### ISSUE THREAD

**Issue by VeiLiang** [tuna/issues#1104]
#### 发生了什么（What happened）
访问不了OpenCAD的镜像
#### 期望的现象（What you expected to happen）
能够下载OpenCAD的镜像
#### 如何重现（How to reproduce it）
直接点击OpenCAD镜像连接
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
没有
#### 您的环境（Environment）
- 操作系统（OS Version）：Windows
- 浏览器（如果适用）（Browser version, if applicable）：QQ浏览器
- 其他（Others）：无

**Comment by shankerwangmiao** [comment]
dup with #1060
