### ISSUE TITLE
请求Fuchsia操作系统镜像

### ISSUE THREAD

**Issue by fripSide** [tuna/issues#1105]
#### 项目名称与简介(Project Intro.)
https://fuchsia.dev/  
fuchsia OS是Google开发的下一代微内核通用操作系统，在不久的将来将会替代Android系统。  

#### 上游地址与镜像方法(How to Mirror)
https://fuchsia.googlesource.com/   
提供了和repo类似的Jiri分支同步工具。   

#### 其他信息(Other)
- 镜像大小(Mirror Size)：纯源码压缩之后19G    
- 该镜像需求是否被之前的 issue 提出过：未搜到相关issue记录

**Comment by shankerwangmiao** [comment]
dup with #409
