### ISSUE TITLE
[tuna]404 at /centos/6/os/x86_64/repodata/repomd.xml

### ISSUE THREAD

**Issue by haichaoqinfen** [tuna/issues#1109]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
请使用 centos-vault。

**Comment by ZenithalHourlyRate** [comment]
#1067
