### ISSUE TITLE
期望 opensuse/repositories 国内镜像

### ISSUE THREAD

**Issue by houkunlin** [tuna/issues#1111]
#### 项目名称与简介(Project Intro.)
在 `https://download.opensuse.org/` 中有一个 [repositories](https://download.opensuse.org/repositories/) 的路径，但是在 `https://mirrors.tuna.tsinghua.edu.cn/opensuse/` 中并没有 `repositories` 这个东西，期望添加相应的

#### 上游地址与镜像方法(How to Mirror)
https://download.opensuse.org/repositories/

**Comment by shankerwangmiao** [comment]
您好，由于这个目录中的内容是自动构建服务实时生成的，目前已达到 6T 多，且不断更新。TUNA 难以对其镜像。
