### ISSUE TITLE
Kodi镜像需要checksum文件

### ISSUE THREAD

**Issue by CreeperKong** [tuna/issues#1112]
Kodi的上游服务器的addons.xml.gz更新十分迅速，镜像站的addons.xml.gz很快就会和官网不一致导致问题

![image](https://user-images.githubusercontent.com/28486081/103415501-4a287680-4bbd-11eb-8939-1ff2888c4036.png)

由图可见，这是指向上游服务器的checksum文件（推测是服务器CGI生成），但是在镜像站就没有对应的checksum。

由于更新很快，这个文件也不断变化

![image](https://user-images.githubusercontent.com/28486081/103415625-f8342080-4bbd-11eb-981e-dd5dd62d51de.png)

此图展示了同一时刻镜像站和上游的文件内容已经不同，从而导致获取repo信息失败。

建议在同目录增加一个checksum文件以便于使用镜像，我个人觉得增加更新频率的方法不太可行

**Comment by shankerwangmiao** [comment]
您好，根据 https://kodi.wiki/view/Add-on_repositories#checksum ，`checksum` 仅用于检查文件是否有更新，并不用于检测文件完整性。
