### ISSUE TITLE
kubernetes镜像内容不完整

### ISSUE THREAD

**Issue by hieastz** [tuna/issues#1114]
#### 发生了什么（What happened）
使用kubernetes  https://mirrors.tuna.tsinghua.edu.cn/kubernetes/yum/
缺失doc目录

官方地址：
https://packages.cloud.google.com/yum/

**Comment by shankerwangmiao** [comment]
`doc/` 目录中是上游的公钥。上游的公钥应该从上游获取。

**Comment by hieastz** [comment]
@shankerwangmiao 没太理解为何这样做？

我看aliyun  https://mirrors.aliyun.com/kubernetes/yum/

是包含doc/的。


求指教！

**Comment by shankerwangmiao** [comment]
因为上游的公钥没有镜像的必要性。上游的公钥应当从上游获取，以便最终用户验证镜像站上文件的完整性。

**Comment by bigeagle** [comment]
> @shankerwangmiao 没太理解为何这样做？

因为公钥的意义是用于校验镜像内容是否是和原始内容一致。
如果 TUNA 篡改了镜像内容(例如在里面加后门)，而你又使用 TUNA 提供的公钥验证，就发现不了问题；使用上游提供的原始公钥就能直接发现镜像篡改。
