### ISSUE TITLE
gitlab-runner 缺少文件

### ISSUE THREAD

**Issue by brainbush** [tuna/issues#1116]
https://mirrors.tuna.tsinghua.edu.cn/gitlab-runner/debian/pool/buster/main/g/gitlab-runner/gitlab-runner_13.7.0_amd64.deb
访问404
希望修复一下，谢谢

**Comment by shankerwangmiao** [comment]
经查，该问题是上游 apt 镜像索引文件出现问题所致。在索引文件 https://packages.gitlab.com/runner/gitlab-runner/debian/dists/buster/main/binary-amd64/Packages 中，`13.7.0` 版本的  `gitlab-runner` 在文件末尾出现了两次，指向了同一文件，但文件大小和 Hash 不一致，因此导致镜像工具无法正常下载包文件。我们会持续关注此事。
