### ISSUE TITLE
FreeCad安装包镜像

### ISSUE THREAD

**Issue by rocjohn** [tuna/issues#1118]
#### 项目名称与简介(Project Intro.)
FreeCad 安装包

#### 上游地址与镜像方法(How to Mirror)
Windows-32位:
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-installer.exe
Windows-64位:
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x64-installer.exe
Mac OS X:
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-rev1-OSX-x86_64-conda-Qt5-Py3.dmg
Linux:
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-rev1-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 大约600MB
- 该镜像需求是否被之前的 issue 提出过：
- 没有

**Comment by skyzh** [comment]
dup of https://github.com/tuna/issues/issues/1103 https://github.com/tuna/issues/issues/1113 https://github.com/tuna/issues/issues/1087  https://github.com/tuna/issues/issues/1073 https://github.com/tuna/issues/issues/759

You may use https://mirror.sjtu.edu.cn/github-release/FreeCAD/FreeCAD/releases/download/?mirror_intel_list for rescue.
