### ISSUE TITLE
Arch源故障

### ISSUE THREAD

**Issue by jianjiandandan221** [tuna/issues#1120]
2021年1月11日
一些Arch包出现下载到一半出现停止下载的现象
报错“”错误：无法从 mirrors.tuna.tsinghua.edu.cn : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds 获取文件 'libspiro-1:20200505-2-x86_64.pkg.tar.zst'”（下载gimp的时候看见的,还有一些包也这样，没截取到）
网络环境：韶关移动100M
系统：
OS: Arch Linux x86_64 
Kernel: 5.10.4-arch2-1 
设备：ASUS K40IN

![Screenshot_20210112_043516](https://user-images.githubusercontent.com/65161476/104183423-e7e93480-544c-11eb-8326-b80f31b91e25.png)

**Comment by ZenithalHourlyRate** [comment]
您可以重试几次，或者使用 [mirrors.bfsu.edu.cn](https://mirrors.bfsu.edu.cn)
