### ISSUE TITLE
gns3-gui

### ISSUE THREAD

**Issue by idamini** [tuna/issues#1121]
用GNS3来模拟，配置，测试虚拟和真实网络并进行故障排除。GNS3允许您运行一个小型拓扑，该拓扑仅包含便携式计算机上的少数设备，也可以运行具有多个设备托管在多个服务器上甚至托管在云中的设备。

https://github.com/GNS3/gns3-gui/releases/tag/v2.2.17
请求添加该页面所有链接下载镜像

**Comment by skyzh** [comment]
您可以参照这个 PR https://github.com/tuna/tunasync-scripts/pull/112 向 tunasync 添加 repo。与此同时，我们也在 SJTUG 服务器上上添加了 [gns3-gui 的镜像](https://mirrors.sjtug.sjtu.edu.cn/github-release/GNS3/gns3-gui/releases/download/v2.2.17/?mirror_intel_list)。

**Comment by ZenithalHourlyRate** [comment]
SJTU 已有镜像，已能满足使用
