### ISSUE TITLE
elasticstack相关的组件增加单独的binary包

### ISSUE THREAD

**Issue by donkeywon** [tuna/issues#1123]
镜像里的elasticstack组件只有deb和rpm包，没有单独的binary包，例如zip或者tar.gz格式
![image](https://user-images.githubusercontent.com/18396127/104397586-128bd800-5588-11eb-900f-49dd7acde8cb.png)

**Comment by shankerwangmiao** [comment]
deb 和 rpm 包可以直接用于在 linux 操作系统上安装 elasticstack；如果您需要 binary，可以手工展开提取。
