### ISSUE TITLE
Ubuntu有更新了，帮助页面咋没改

### ISSUE THREAD

**Issue by haotian2004** [tuna/issues#1126]
话说帮助页面和里面的文件咋不做一个列表

**Comment by skyzh** [comment]
您可以更新 https://github.com/tuna/mirror-web/blob/master/help/_posts/1970-01-01-ubuntu.md 。

**Comment by ZenithalHourlyRate** [comment]
Closed by https://github.com/tuna/mirror-web/commit/7258c63b88d9f01d20649edee000866b0dad3d4e.

Ref to https://mirrors.bfsu.edu.cn/help/ubuntu/
