### ISSUE TITLE
可以增加一个一个开源软件veusz 的镜像么 

### ISSUE THREAD

**Issue by lyzenliu** [tuna/issues#1128]
[veusz](https://veusz.github.io)
这是一款开源软件，可以用来代替origin等科学绘图软件
Veusz is a scientific plotting and graphing program with a graphical user interface, designed to produce publication-ready 2D and 3D plots. In addition it can be used as a module in Python for plotting. Veusz is multiplatform, running on Windows, Linux/Unix and macOS. It supports vector and bitmap output, including PDF, Postscript, SVG and EMF. Veusz is Free Software.

With the help of a tutorial the program can be used by the novice user and is flexible for advanced work. In Veusz plots are created by building up plotting widgets with a consistent object-based interface, where the user sets the properties of the widgets. There are many options for customization of plots. See features, 2D examples and 3D examples to see what can be done with the program.

It allows data to be imported from text, CSV, HDF5 and FITS files. Datasets can also be entered within the program and new datasets can be created via the manipulation of existing datasets using mathematical expressions and more. The program can also be extended, by adding plugins supporting importing new data formats, different types of data manipulation or for automating tasks.

**Comment by ZenithalHourlyRate** [comment]
这是一个python包，可以通过pypi获取。各大Linux发行版也有相关打包。

其余部分为相关Windows与macOS的github-relesase，您是想镜像这些吗

**Comment by lyzenliu** [comment]
是的，我看到了。可以通过pypi获取，谢谢



2804058434@qq.com
 
发件人： Zenithal
发送时间： 2021-01-16 09:32
收件人： tuna/issues
抄送： lyzenliu; Author
主题： Re: [tuna/issues] 可以增加一个一个开源软件veusz 的镜像么 (#1128)
这是一个python包，可以通过pypi获取。各大Linux发行版也有相关打包。
其余部分为相关Windows与macOS的github-relesase，您是想镜像这些吗
