### ISSUE TITLE
openSUSE Tumbleweed KDE中部分文件404

### ISSUE THREAD

**Issue by AMIRIOX** [tuna/issues#1130]
#### 发生了什么（What happened）

OpenSUSE镜像中一下文件链接点进去是404页面（在[这里](https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/iso/)
openSUSE-Tumbleweed-KDE-Live-i686-Current.iso
openSUSE-Tumbleweed-KDE-Live-i686-Current.iso.sha256
openSUSE-Tumbleweed-KDE-Live-i686-Current.iso.sha256.asc
openSUSE-Tumbleweed-KDE-Live-x86_64-Current.iso
openSUSE-Tumbleweed-KDE-Live-x86_64-Current.iso.sha256
openSUSE-Tumbleweed-KDE-Live-x86_64-Current.iso.sha256.asc

#### 期望的现象（What you expected to happen）

正常下载文件

#### 如何重现（How to reproduce it）
在清华大学开源软件镜像站的这个页面[Index of /opensuse/tumbleweed/iso/
](https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/iso/)
点击上述六个文件的链接

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
没有

#### 您的环境（Environment）
-操作系统（OS Version）：`Manjaro Linux | Linux Kernel 5.8.16`
- 浏览器（如果适用）（Browser version, if applicable）：`Chromium 86.0.4240.111 Arch Linux`
- 其他（Others）：无

**Comment by ZenithalHourlyRate** [comment]
您好，我这边不能复现，可以请您再尝试一下吗

**Comment by AMIRIOX** [comment]
> 您好，我这边不能复现，可以请您再尝试一下吗

昨天不行的来着...现在好了 没事了 谢谢您
