### ISSUE TITLE
为 GCC/Homebrew/Linux/LLVM 等 Git 镜像提供 Git Protocol

### ISSUE THREAD

**Issue by XuehaiPan** [tuna/issues#1131]
目前 Git 镜像仅提供 HTTP 协议。既然镜像不提供 push 操作，希望额外添加 Git 协议，以方便 `git archive` 等命令的使用。

```bash
git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git  # HTTPS protocol
git clone git://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git    # Git protocol
```

参考链接：
[服务器上的 Git - 协议](https://git-scm.com/book/zh/v2/%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A%E7%9A%84-Git-%E5%8D%8F%E8%AE%AE)
[服务器上的 Git - Git 守护进程](https://git-scm.com/book/zh/v2/%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A%E7%9A%84-Git-Git-%E5%AE%88%E6%8A%A4%E8%BF%9B%E7%A8%8B)

**Comment by shankerwangmiao** [comment]
您好，我们不提供 git 协议，主要是因为 git 协议难以进行调度和路由。作为代替， TUNA 提供的 http(s) 协议事实上是带有 cgi 后端的 smart 协议。

目前，我们并未注意到任何 git 功能强依赖于 git 协议。
