### ISSUE TITLE
建议增加powershell的镜像

### ISSUE THREAD

**Issue by above-the-law** [tuna/issues#1136]
Mirror Requests 镜像请求
项目名称：powershell
项目简介：`https://docs.microsoft.com/zh-cn/powershell/scripting/overview?view=powershell-7.1`
项目release版本源地址：`https://github.com/PowerShell/PowerShell/releases`
尽量详细的镜像信息：`https://github.com/PowerShell/PowerShell`

**Comment by skyzh** [comment]
您可以参照这个 PR https://github.com/tuna/tunasync-scripts/pull/112 向 tunasync 添加 repo。

**Comment by Harry-Chen** [comment]
推迟到新服务器上线后进行

**Comment by 210hcl** [comment]
https://mirror.sjtu.edu.cn/github-release/PowerShell/PowerShell/releases/download/?mirror_intel_list
可以使用上海交通大学镜像提供的。

**Comment by Harry-Chen** [comment]
已经同步到 https://mirrors.tuna.tsinghua.edu.cn/github-release/PowerShell/PowerShell/LatestRelease/
