### ISSUE TITLE
请求添加Garuda Linux镜像

### ISSUE THREAD

**Issue by zebulon2020** [tuna/issues#1137]
#### 项目名称与简介(Project Intro.)
[Garuda Linux](https://garudalinux.org/index.html)

+ Garuda Linux是基于Arch Linux操作系统的滚动式发行。
+ Garuda是面向性能而优化的发行。
+ 带有多种桌面环境(KDE, GNOME, Xfce, Cinnamon, MATE, LXQt-kwin, Wayfire, Qtile, BSPWM and i3wm)。界面美观。
+ 默认使用btrfs文件系统。

只是大陆能找到的下载地址的速度都比较慢，希望能同步一下iso镜像。之前有人提到过这个发行版，但好像在讲它独有的Chaotic-AUR的问题。我的意思是能不能同步它的iso镜像。

#### 上游地址与镜像方法(How to Mirror)
https://builds.garudalinux.org/iso/garuda/
#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：[#1062](https://github.com/tuna/issues/issues/1062)

**Comment by makeding** [comment]
那其实iso已经有镜像了的，在 OSDN 里面

![image](https://user-images.githubusercontent.com/6511667/105574602-a76cad80-5da0-11eb-917f-e93055732ffa.png)

https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/g/ga/garuda-linux/
https://mirrors.bfsu.edu.cn/osdn/storage/g/g/ga/garuda-linux/
请

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/g/ga/garuda-linux/
> https://mirrors.bfsu.edu.cn/osdn/storage/g/g/ga/garuda-linux/

目前BFSU首页已经增加了 `garuda-linux` 项，指向 `/osdn/storage/g/g/ga/garuda-linux/`（TUNA首页请等待部署）
