### ISSUE TITLE
【镜像请求】RubyInstaller2

### ISSUE THREAD

**Issue by ccmywish** [tuna/issues#1138]
#### 项目名称与简介(Project Intro.)
RubyInstaller2 是Windows上安装Ruby的现有最流行方法
官网：https://rubyinstaller.org/
GitHub：https://github.com/oneclick/rubyinstaller2

目前中国大陆没有镜像源

#### 上游地址与镜像方法(How to Mirror)
Github Release:
https://github.com/oneclick/rubyinstaller2/releases

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
未知，每个安装包大小在130MB左右

**Comment by ccmywish** [comment]
正在询问维护者有无更好的 mirror 存储方法， see https://github.com/oneclick/rubyinstaller2/issues/209

**Comment by larskanis** [comment]
Thank you for providing a RubyInstaller mirror! That would help some users.

Size of the complete github release content is currently around 8GByte. This is for versions starting with ruby-2.4.1. Older versions are stored on bintray, but they are probably no longer of interest.

I would like to list the mirror on the official https://rubyinstaller.org site. Is this mirror only usable in china or can it be useful for other countries as well?

**Comment by larskanis** [comment]
There are between 150000 and 200000 downloads per month international. Hence the cumulative download traffic is between 15 and 20 TByte per month. I don't know how much originates from China.

**Comment by skyzh** [comment]
> Thank you for providing a RubyInstaller mirror! That would help some users.
> 
> Size of the complete github release content is currently around 8GByte. This is for versions starting with ruby-2.4.1. Older versions are stored on bintray, but they are probably no longer of interest.
> 
> I would like to list the mirror on the official https://rubyinstaller.org site. Is this mirror only usable in china or can it be useful for other countries as well?

Yes, we are glad that our mirror could be listed on official website. SJTUG mirror can be used in other countries and regions (except Europe due to GDPR), but may have slow download speed. It is recommended only for users in mainland China.
