### ISSUE TITLE
ros 希望增加 ros-win的镜像支持

### ISSUE THREAD

**Issue by GWinfinity** [tuna/issues#1139]
希望tuna增加ros2和ros-win的镜像支持。这部分海外体验超差。

**Comment by ZenithalHourlyRate** [comment]
ros2 已经有镜像了。

> 这部分海外体验超差。

海外是指从海外访问 TUNA 镜像站吗

以及您可以参考 #741

> 以国内访问速度缓慢为由提出镜像请求的
