### ISSUE TITLE
请求添加一个archlinux的社区源: arch4edu

### ISSUE THREAD

**Issue by petronny** [tuna/issues#114]
#### 项目名称与简介(Project Intro.)
[Arch4edu](https://github.com/arch4edu/arch4edu)是我创建的一个Archlinux社区源
主要用来构建各种主流炼丹工具比如tensorflow, caffe以及其他学校实验室使用的软件包
目标覆盖机器翻译，数字图像处理，语音信号处理等等所需的各种奇怪工具

基本是仿照[Archlinuxcn](https://github.com/archlinuxcn/repo)构建的，
所以可以实现所有包自动检查更新并打包。

从创建起到现在已经平稳运行了2周，维护者现在还只有我一个人

#### 上游地址与镜像方法(How to Mirror)
现在上游只有我在FIT的实验室服务器。。如果想体验一下可以
```
[arch4edu]
SigLevel = Never
Server = http://166.111.139.117/arch4edu
```
(没有登录tunet，所以限校内IP访问。。)

* 镜像方法

我打算把tuna作为source发布的，我希望可以在服务器上有一个账号petron
然后我rsync到下面的一个文件夹arch4edu中

#### 其他信息(Other)
- 镜像大小(Mirror Size): ~650M(不断扩充中)
- 软件包数量: 45(不断扩充中)

**Comment by bigeagle** [comment]
这个好！
方便的话给 mirrors@tuna.tsinghua.edu.cn 发个 email，我们给你分配个虚拟机专门用来发布。

**Comment by petronny** [comment]
好的，然后我顺便把authorized_keys也作为附件发过去好了
