### ISSUE TITLE
镜像QEMU的git子模块

### ISSUE THREAD

**Issue by Evian-Zhang** [tuna/issues#1140]
#### 项目名称与简介(Project Intro.)

Qemu is the most famous machine emulator and virtualizer in the open source community. It can be used to emulate a lot of virtual machine on one physical machine. It plays an important role in the cloud computing industry. A lot of cloud vendors use Qemu to construct cloud infrastructure.

#### 上游地址与镜像方法(How to Mirror)

```bash
git clone --recurse-submodules git://git.qemu.org/qemu.git
```

对于镜像的用户来说，可以使用

```bash
git config submodule.MySubmodule.url mirror-of-my-submodule
```

将本地的`MySubmodule`子模块的url设置为`mirror-of-my-submodule`，而不会影响`.gitmodules`文件。

#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知（上不去。。）
- 该镜像需求是否被之前的 issue 提出过：
  由#707 提出过镜像QEMU。但是QEMU的代码实际上还包括部分git submodule（可参见[qemu/.gitmodules](https://github.com/qemu/qemu/blob/master/.gitmodules)）。如果只是镜像主模块，子模块没有被镜像，那么代码完全无法编译，也就失去了镜像的意义。

**Comment by ZenithalHourlyRate** [comment]
参考 http://shz.al/niQn ，目前最新的 QEMU 依赖 28 个子模块，其中不乏子模块的子模块。虽然我很愿意镜像子模块，但以下因素都需要讨论和花时间实现

1. `.gitmodules` 是由 commit 追踪的，那么，我们是不是要对每个 commit 中涉及到的 submodule 都要镜像，还是我只镜像 master （或 main） 追踪的子模块？
2. 一些现有的基础设施的问题，需要一定程度的改动（tunasync-scripts/git.sh，需要实现递归获取所有子模块）
3. 对于用户来说，对每个子模块都要运行 `git config submodule.MySubmodule.url mirror-of-my-submodule` ，这就需要我们及时更新乃至自动更新（现在没有这个机制）镜像帮助 ；对用户来说最不方便的地方在于不能一次 `git submodule update --init --recursive` 更新完所有子模块，而是需要在更新完第一层子模块后，进入每个子模块，在进行上述过程。当然，如果有时间写，这也可以引入一个 类似 `qemu-tuna.sh` 的脚本辅助解决。

**Comment by ZenithalHourlyRate** [comment]
目前实验性地加上了该功能，可以通过以下方式获取 qemu 及其子模块
```
curl https://mirrors.tuna.tsinghua.edu.cn/git/qemu/qemu.sh | sh
```

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/tunasync-scripts/commit/9038ddb7e221b7fe113326dc2ad2392bcf01c318
