### ISSUE TITLE
current_repodata.json 丢失

### ISSUE THREAD

**Issue by youkaichao** [tuna/issues#1141]
`wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json` 得到404状态码

这导致`conda install` 失败

**Comment by shankerwangmiao** [comment]
请给出完整的出错信息，该文件不存在一般不影响正常使用。

**Comment by shankerwangmiao** [comment]
上游亦无此文件 https://repo.anaconda.com/pkgs/free/linux-64/current_repodata.json 。

**Comment by youkaichao** [comment]
conda install的第一步就是 `Collecting package metadata (current_repodata.json)`

我想这有可能是因为free channel不再受支持了 https://www.anaconda.com/blog/why-we-removed-the-free-channel-in-conda-4-7 

我换用main channel就好了

谢谢
