### ISSUE TITLE
有关Homebrew-Install install.sh文件近期内容更新

### ISSUE THREAD

**Issue by intStupid** [tuna/issues#1142]
#### 发生了什么（What happened）
最近在使用其安装Homebrew时发现网站上提供的Homebrew / Linuxbrew 镜像使用帮助并不能顺利的安装Homebrew。猜测是Homebrew-Install的install.sh文件近期更新的结果，而在更新中BREW_REPO变量被移除了。[详情](https://github.com/Homebrew/install/commit/30c06c476579e587f2610e088781a285fdc4b5b9)

#### 期望的现象（What you expected to happen）
能通过Homebrew / Linuxbrew 镜像使用帮助顺利安装Homebrew。

#### 如何重现（How to reproduce it）
尝试使用Homebrew / Linuxbrew 镜像使用帮助安装Homebrew。

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：猜测暂无

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 1909
- 浏览器（如果适用）（Browser version, if applicable）：Chrome 87.0.4280.141
- 其他（Others）：无

**Comment by Harry-Chen** [comment]
欢迎提供 PR。

**Comment by ZenithalHourlyRate** [comment]
参考 https://github.com/Homebrew/install/commit/dc614dd8166d237d0bd8cbfa589030c7e4b1cd6a ，该变量被重命名
