### ISSUE TITLE
Deleted pypi package is not deleted from tuna mirror

### ISSUE THREAD

**Issue by mohamed-ali** [tuna/issues#1143]
Could you please activate removing deleted packages. This deleted pypi package is still showing on your mirror: https://pypi.org/project/rakuten.spark/

**Comment by shankerwangmiao** [comment]
> @shankerwangmiao If so, could you please let me know when the mirror will get refreshed to remove the deleted repository ? Thanks.

We sync pypi using bandersnatch every 5 minutes. I have no idea why the package you mentioned failed to get deleted. The removal is done manually.
