### ISSUE TITLE
conda和pip下载安装包经常失败

### ISSUE THREAD

**Issue by mjdxyr** [tuna/issues#1144]
用镜像的时候下载大一点的安装包经常卡住，然后就超时了，用学校服务器和自己的电脑都出现了这种问题。换其他镜像源时没有这种问题。

**Comment by mjdxyr** [comment]
复制链接用wget下载也会卡住。

**Comment by skyzh** [comment]
请使用 bfsu 或其他镜像站。

**Comment by Harry-Chen** [comment]
您好，您反映的问题可能是您到 TUNA 的链路问题，也可能是 TUNA 的服务存在问题。我们有计划在近期对于负载均衡方式进行调整，以尝试缓解后者。在此期间，您可以选择使用 BFSU、OpenTUNA 或其他兄弟镜像站。
