### ISSUE TITLE
pypi日志下载缓慢

### ISSUE THREAD

**Issue by ShenYuhan** [tuna/issues#1145]
由于需要使用pypi日志来分析每日下载量，但最近发现下载日志速度很慢，服务器是否不在境内，有什么解决办法？
是否可以提供类似google bigquery的方式能够快速查询日志中某个wheel包的下载次数等方法？

**Comment by shankerwangmiao** [comment]
您好，TUNA 服务器部署在清华校内。我们仅原样提供隐去真实 IP 地址的文本日志。
