### ISSUE TITLE
希望能增加DBeaver数据库IDE的镜像

### ISSUE THREAD

**Issue by ghost** [tuna/issues#1146]
#### 项目名称与简介(Project Intro.)
项目名称：DBeaver

社区版是一款由社区维护的免费工具，是可以连接多种数据库的集成开发环境，方便在项目或组织内同时使用多款数据库时进行数据查询。国内从其官网下载巨慢。

Free multi-platform database tool for developers, database administrators, analysts and all people who need to work with databases. Supports all popular databases: MySQL, PostgreSQL, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Apache Hive, Phoenix, Presto, etc.
 
#### 上游地址与镜像方法(How to Mirror)
https://dbeaver.io/files/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：最新版58MB，所有版本Achieve估计500MB，建议从7+版开始镜像。
- 该镜像需求是否被之前的 issue 提出过：否

**Comment by ZenithalHourlyRate** [comment]
> 国内从其官网下载巨慢。

> #741 以国内访问速度缓慢为由提出镜像请求的

FYI https://mirrors.cernet.edu.cn/list/dbeaver
