### ISSUE TITLE
mongodb 缺少其它平台的源

### ISSUE THREAD

**Issue by makeding** [tuna/issues#1149]
RT 目前 mongodb 镜像仅同步了 i386 amd64 两个平台
还需要同步的：
binary-arm64
binary-ppc64el
binary-s390x
-- 
参考：
https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/4.4/multiverse/

https://opentuna.cn/mongodb/apt/ubuntu/dists/focal/mongodb-org/4.4/multiverse/
https://mirrors.tuna.tsinghua.edu.cn/mongodb/apt/debian/dists/buster/mongodb-org/4.4/main/

<img width="649" alt="image" src="https://user-images.githubusercontent.com/6511667/106353799-237a6e80-6328-11eb-9052-d7c3d7f8894c.png">

**Comment by Harry-Chen** [comment]
非常用架构我们原则上不同步，arm64 可以添加，其他的目前不予考虑

**Comment by makeding** [comment]
还是写新文档的时候发现了这个问题
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/6511667/106358202-8b8b7d80-6345-11eb-9106-d953532a313f.png">
我多加一行提示吧（（
