### ISSUE TITLE
Logstash 2.4镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#115]
Logstash 2.4已经发布，但是镜像站目前只有2.3和5.0的。

**Comment by abcfy2** [comment]
或者可以考虑`elastic.co`公司的镜像改用反向代理提供加速？

**Comment by bigeagle** [comment]
反向代理主要是不好管理

**Comment by abcfy2** [comment]
发现kibana也更新到4.6了。

这样的话感觉反向代理维护量更小。否则一个版本就得同步一遍。

**Comment by abcfy2** [comment]
发现已经添加logstash 2.4和kibana 4.6的仓库了，这个issue已经解决了。
