### ISSUE TITLE
清华软件镜像站出现莫名奇妙的掉速

### ISSUE THREAD

**Issue by gamecss** [tuna/issues#1151]
我使用清华软件镜像站当作ubuntu软件源已经有一段时间了，但是我最近观察到一个奇怪的现象，就是刚开始下载文件时速度是非常快的，可以到2M/s（我的宽带只有10Mbps，这个速度已经是跑满了）但几秒后，速度就掉到0.7M/s，然后就一直掉，一直掉，有时候会掉到5b/s，这是为啥？？？
（我的dns是114.114.114.114）
PS:这段话原来是发给support@tuna.tsinghua.edu.cn的，不过我刚发出去，就收到了postmaster@tuna.tsinghua.edu.cn发来的邮件，里面写了：
Delivery has failed to these recipients or groups:
scateu@tuna.tsinghua.edu.cn
Your message wasn't delivered because the recipient's email provider rejected it.
把邮件拒收了。不知道这算不算个bug？

**Comment by phy25** [comment]
您的宽带是在哪个运营商哪个地区呢？有没有测试过 mirrors.bfsu.edu.cn 或 opentuna.cn 呢？

**Comment by Harry-Chen** [comment]
support 能够收到您的邮件，目前由于配置原因，可能会产生一些拒信，请谅解

**Comment by Harry-Chen** [comment]
support 能够收到您的邮件，目前由于配置原因，可能会产生一些拒信，请谅解

**Comment by gamecss** [comment]
宽带是电信 福州

**Comment by shankerwangmiao** [comment]
我们确实接获了一些处于南方的宽带用户的类似的报告，目前该问题原因已经初步定位到了，但是短时间内无法解决，建议您使用 mirrors.bfsu.edu.cn 或者 opentuna.cn 。此问题暂时关闭，如有任何其他问题，可以 reopen。
