### ISSUE TITLE
请求新建OBS镜像！！国内下载太慢！！！！！

### ISSUE THREAD

**Issue by LiuShaoYe-173** [tuna/issues#1153]
# 项目名称与简介(Project Intro.)
### 简介
免费且开源的用于视频录制以及直播串流的软件。
## 上游地址与镜像方法(How to Mirror)
定时下载，链接：[Windows](https://cdn-fastly.obsproject.com/downloads/OBS-Studio-26.1.1-Full-Installer-x64.exe)，[macOS](https://cdn-fastly.obsproject.com/downloads/obs-mac-26.1.2.dmg)
#### 其他信息(Other)
- 镜像大小(Mirror Size)：安装程序100MB~200MB，BT文件不到800KB

**Comment by skyzh** [comment]
和 https://github.com/obsproject/obs-studio/releases 是否一致？用 GitHub Release 脚本同步或许会方便一点。

**Comment by LiuShaoYe-173** [comment]
是

**Comment by LiuShaoYe-173** [comment]
Github下载在个别地区个别时间下载速度非常薛定谔（诸如江西省地区、晚上）

**Comment by LiuShaoYe-173** [comment]
意思是有时候很慢，但有时候很快

**Comment by Harry-Chen** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/obsproject/obs-studio/，只同步最近五个正式 release

**Comment by LiuShaoYe-173** [comment]
Nice！！
![image](https://user-images.githubusercontent.com/58081491/106681907-66746480-65fc-11eb-8eb6-212f8420bf27.png)
