### ISSUE TITLE
obs-studio的帮助文档有点不好写

### ISSUE THREAD

**Issue by haotian2004** [tuna/issues#1155]
原因：无法定位LatestRelease
我给出的解决办法：结构改为
下面这样，这种也方便用户查询
也可能是我的理解能力不行
谁有想法就写吧
obs-studio
├── Parent directory
├── Latest
└── 版本号

**Comment by haotian2004** [comment]
我这样写的
---
category: help
layout: help
mirrorid: obs-studio
---
免费且开源的用于视频录制以及直播串流的软件。
下载以在Windows, Mac以及Linux上简单且快速的开始串流。
Linux系列:
---
发行版:命令
debian：sudo apt install obs-studio
deepin：sudo apt install obs-studio
ubuntu：sudo apt install obs-studio
archlinux：sudo pacman -S obs-studio
---
Windows系列：
---
类型：食用方式：下载链接
x86安装包：双击安装：
x86完整包：解压即可食用：
x64安装包：双击安装：
x64完整包：解压即可食用：
---
MacOS（苹果）系列：
---
dmg安装包下载链接：
---

**Comment by haotian2004** [comment]
本人不怎么会markdown
最近才开始学习食用Typroa

**Comment by ZenithalHourlyRate** [comment]
您好，可以参考[镜像站](https://mirrors.tuna.tsinghua.edu.cn/)的「获取下载链接」这一子页面（该子页面也在 https://mirrorz.org/app 中渲染），该页面可以渲染出相应的下载链接，不过目前尚未有相应的支持（参考 [mirror-web](https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini)），在帮助页面中可以直接导向该页面，帮助页面中只需对相应版本问题作出说明

**Comment by Harry-Chen** [comment]
GitHub release 的软件目前无需帮助文档
