### ISSUE TITLE
请求建立magisk的镜像

### ISSUE THREAD

**Issue by mdogwoop** [tuna/issues#1156]
#### 项目名称与简介(Project Intro.)
Magisk,是现在主流的Android设备root方案
#### 上游地址与镜像方法(How to Mirror)
上游https://github.com/topjohnwu/Magisk
镜像方式：git
#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：

**Comment by makeding** [comment]
这个只要 release 就好了吧。

**Comment by Harry-Chen** [comment]
推迟到新服务器上线后进行

**Comment by Harry-Chen** [comment]
已经同步到 https://mirrors.tuna.tsinghua.edu.cn/github-release/topjohnwu/Magisk/LatestRelease/
