### ISSUE TITLE
ubuntu-cdimage镜像中，部分网页的链接问题

### ISSUE THREAD

**Issue by foresee-io** [tuna/issues#1158]
#### 发生了什么（What happened）
下述仅用作示例，不代表只有此问题。
`https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cdimage/netboot/bionic/` 是在实机安装最小 Ubuntu 的途径。
点击本网页中的任何一个链接（guide 除外），都将跳转至 `archive.ubuntu.com` 而非镜像源，尽管我可以手动将其改为 `mirrors.tsinghua.tuna.edu.cn`。

#### 期望的现象（What you expected to happen）
解决此问题可能需要一定精力。
期望将网页链接所指 `archive.ubuntu.com` 均自动地改为镜像源。

**Comment by shankerwangmiao** [comment]
您好，确实存在此问题。但是镜像站上的内容以原样提供，因此这些页面的链接我们无法修改。如果您需要类似的镜像，可以手工修改 URL 处理。

**Comment by ZenithalHourlyRate** [comment]
目前在镜像站首页的「获取下载链接-Ubuntu」中有类似于 [xenial (amd64, network installer directory)](https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot) 的快捷链接
