### ISSUE TITLE
ROS mirror request

### ISSUE THREAD

**Issue by liuyang12** [tuna/issues#116]
#### 项目名称与简介(Project Intro.)
The Robot Operating System ([ROS](http://www.ros.org/)) is a flexible framework for writing robot software. It is a collection of tools, libraries, and conventions that aim to simplify the task of creating complex and robust robot behavior across a wide variety of robotic platforms.

Why? Because creating truly robust, general-purpose robot software is hard. From the robot's perspective, problems that seem trivial to humans often vary wildly between instances of tasks and environments. Dealing with these variations is so hard that no single individual, laboratory, or institution can hope to do it on their own.

As a result, ROS was built from the ground up to encourage collaborative robotics software development. For example, one laboratory might have experts in mapping indoor environments, and could contribute a world-class system for producing maps. Another group might have experts at using maps to navigate, and yet another group might have discovered a computer vision approach that works well for recognizing small objects in clutter. ROS was designed specifically for groups like these to collaborate and build upon each other's work, as is described throughout this site.

#### 上游地址与镜像方法(How to Mirror)
http://packages.ros.org/ros/ubuntu
the mirror setup is stated in [Creating a ROS mirror](http://wiki.ros.org/Mirrors) as the github repository [ROS Mirroring Config](https://github.com/ros-infrastructure/mirror).

#### 其他信息(Other)
- 镜像大小(Mirror Size): version dependent.

**Comment by bigeagle** [comment]
不让 rsync 不幸福 >_<

**Comment by cicku** [comment]
ROS 最恶心的就是没有 rsync。

**Comment by gaoyifan** [comment]
目前USTC用的上游：rsync://mirror.umd.edu/packages.ros.org/ros/

**Comment by bigeagle** [comment]
开始同步了

**Comment by bigeagle** [comment]
好了～
