### ISSUE TITLE
Wireshark使用了不当的源

### ISSUE THREAD

**Issue by TonySue2000** [tuna/issues#1160]
#### 发生了什么（What happened）
贵站使用的Wireshark源来自OSDN,但是显然Wireshark已不在此站发布新版软件（OSDN上该软件的最近更新记录为18年5月，明显过于老旧）
#### 期望的现象（What you expected to happen）
在官方网站下载页（https://www.wireshark.org/download.html）有给出下载镜像，且刚好有镜像支持rsync
![image](https://user-images.githubusercontent.com/44887097/107734557-a9d77d00-6d38-11eb-9b0d-1fb214301058.png)
#### 如何重现（How to reproduce it）
NA
#### 其他事项（Anything else we need to know）
话说真的有必要花费8TB*3的空间给OSDN做国内镜像吗？感觉没啥人用，不如给SourceForge做镜像（尽管SF也过气哩）

**Comment by ZenithalHourlyRate** [comment]
SourceForge相关可以参考 #928

**Comment by skyzh** [comment]
官方的上游是 rsync://rsync.wireshark.org/wsdl

FYI https://www.wireshark.org/mirror.html

**Comment by laozhoubuluo** [comment]
Wireshark 这个问题其实感觉更像是一个特殊的 Mirror Request ，增加个新源同步应该可以解决。

Tuna 和 BFSU 是中国大陆唯二的 OSDN 镜像站点，并且根据 https://zh.osdn.net/top/topdl.php 可以看到 OSDN 上还是有不少常用软件的，如 CrystalDisk 系列软件 / MinGW / TortoiseSVN / 7-Zip 等，不过考虑到二八定律的话肯定没有发行版镜像用户数多。如果确实资源不够的话建议考虑保留一个，或者转移到 OpenTuna 。

**Comment by Harry-Chen** [comment]
关于 OSDN 的问题，我们已经找了上游询问，正在等待答复
