### ISSUE TITLE
TUNA的OpenWrt镜像有问题 好像蒸发了一样

### ISSUE THREAD

**Issue by 8MiYile** [tuna/issues#1161]
#### 发生了什么（What happened）
- 尝试访问 https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/
- 触发404
#### 期望的现象（What you expected to happen）
- 访问进去应该是文件夹列表才对
#### 如何重现（How to reproduce it）
- 访问 https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：查看了一篇类似的 但那个是说OpenWrt的Source站而不是官方软件包站

#### 您的环境（Environment）
- 操作系统（OS Version）：Linux Deepin 20.1
- 浏览器（如果适用）（Browser version, if applicable）：Firefox Developer(啥版本搞忘了)
- 其他（Others）：

**Comment by ZenithalHourlyRate** [comment]
参考 #619 ，您可以在 https://mirrorz.org/list/openwrt?filter=openwrt 中寻找有 snapshots 的镜像站
