### ISSUE TITLE
[important]请问有什么方法克隆该镜像站吗

### ISSUE THREAD

**Issue by 8MiYile** [tuna/issues#1162]
我手头有一台1PB的服务器，请问一下如何镜像该站点并额外自定义自己的logo之类的

**Comment by ZenithalHourlyRate** [comment]
以下链接可以供您参考：
https://github.com/tuna/tunasync/wiki/Mirroring-Howto
https://github.com/tuna/mirror-web/issues/65
https://github.com/tuna/mirror-web/issues/105
https://github.com/tuna/mirror-web/issues/233

本站的大部分配置与工具均公开与开源，您可以参考本组织内的相关项目进行部署。本站对大部分镜像提供 rsync 服务，贵站可以通过 rsync 获取相关数据。logo相关的问题不在本组织的考虑范围内。
