### ISSUE TITLE
Mirror request: Wireshark

### ISSUE THREAD

**Issue by Harry-Chen** [tuna/issues#1164]
See #1160, rsync://rsync.wireshark.org/wsdl

**Comment by Harry-Chen** [comment]
计划推迟到新服务器上线后进行

**Comment by laozhoubuluo** [comment]
您好，请问近期是否有上线该镜像的规划？

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/wireshark/
