### ISSUE TITLE
[OpenTUNA] 考虑和 Linux 发行版团队或其他第三方软件团队申请加入官方源

### ISSUE THREAD

**Issue by laozhoubuluo** [tuna/issues#1165]
之前在安装 Debian 时发现默认官方源列表内并不包含 OpenTUNA ，很好奇为何此镜像未加入官方源列表，于是进行了一个简单的小调查。

在 Debian / Ubuntu / Arch / Alpine 四个发行版中，Tuna 主站全部拥有官方源，BFSU 缺少了 Alpine ，而 OpenTUNA 无一入驻官方源。

考虑到官方源可以在安装时选择，且后续版本更新默认使用官方源，因此建议考虑和镜像过的 Linux 发行版团队或其他第三方软件团队（尤其是 OpenTUNA 已经镜像且未加入官方源的 Linux 发行版）取得联系，在相关团队同意的基础上争取加入官方源，以进一步扩大 OpenTUNA 用户基数，进一步降低现有 Tuna 以及 BFSU 镜像的压力，进一步优化终端用户的使用体验。

以上仅为个人观点，如和官方观点相左或存在我方不了解的其他情况请直接关闭 Issue 即可，多有打扰敬请谅解。

**Comment by Harry-Chen** [comment]
目前 opentuna 存在主体问题尚待讨论，故没有申请加入任何的官方列表。

**Comment by laozhoubuluo** [comment]
> 
> 
> 目前 opentuna 存在主体问题尚待讨论，故没有申请加入任何的官方列表。

了解了，谢谢。

**Comment by happyaron** [comment]
opentuna 即将停止服务，关闭 issue
