### ISSUE TITLE
Mirror request: Typora

### ISSUE THREAD

**Issue by llxlr** [tuna/issues#1167]
软件名称：Typora, 很常用的即时预览Markdown编辑器

地址：[https://typora.io](https://typora.io) 

原因：苦于官网下很慢

**Comment by shankerwangmiao** [comment]
参见 #741 第十条

**Comment by abc1763613206** [comment]
参见 https://github.com/typora/typora-issues
*Typora is commercial software (not open source), but is free during beta.*

**Comment by TechCiel** [comment]
这种非常见开源协议的免费软件（仅指 beta ），请求镜像前建议至少先取得明示授权，再考虑其他问题（。
