### ISSUE TITLE
请求建立Motrix镜像，下载经常失败！！

### ISSUE THREAD

**Issue by LiuShaoYe-173** [tuna/issues#1168]
#### 项目名称与简介(Project Intro.)
A full-featured download manager.
一个全能的下载管理器。
#### 上游地址与镜像方法(How to Mirror)
地址：https://github.com/agalwood/Motrix/releases
镜像方案：Github Release 脚本同步
##### 镜像大小(Mirror Size)
yml文件：343B-657B
压缩文件：71.1MB-73.8MB
DMG（macOS压缩镜像）文件:75.1MB
Appimage文件：80.9MB
EXE（可执行文件）文件：94.6MB-94.9MB

**Comment by shankerwangmiao** [comment]
参见 #741 第十条
