### ISSUE TITLE
请求更新julia-1.5.3-linux-aarch64.tar.gz.asc

### ISSUE THREAD

**Issue by WindnBike** [tuna/issues#1169]
位于[https://opentuna.cn/julia-releases/bin/linux/aarch64/1.5/](https://opentuna.cn/julia-releases/bin/linux/aarch64/1.5/)的`julia-1.5.3-linux-aarch64.tar.gz.asc`未更新，与`julia-1.5.3-linux-aarch64.tar.gz`并不对应。
导致通过jill安装julia时提示校验失败，提示如下：
```
failed to verify 1.5.3-linux-ARMv8 downloads
remove untrusted/broken files
```

**Comment by jiegec** [comment]
经查，是上游更新了 asc 文件，但是没有被更新所致。正在处理。
