### ISSUE TITLE
OPENTUNA镜像请求:Ubuntu-Ports

### ISSUE THREAD

**Issue by tazkeung** [tuna/issues#1170]
#### 项目名称与简介(Project Intro.)
Ubuntu-Ports
armhf,arm64和powerpc等平台的ubuntu软件仓库

#### 上游地址与镜像方法(How to Mirror)
rsync://ports.ubuntu.com/ubuntu-ports/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：1.88T
- 该镜像需求是否被之前的 issue 提出过：好像没有。

**Comment by happyaron** [comment]
opentuna 即将停止服务，关闭 issue
