### ISSUE TITLE
如果我国的最高学府无法负担起带宽的费用，请体面的关闭镜像源，而不是在下载2M后限速10KB/S，谢谢

### ISSUE THREAD

**Issue by forbxy** [tuna/issues#1174]

**Comment by skyzh** [comment]
具体是哪个镜像源的问题呢？

另外似乎 dup of https://github.com/tuna/issues/issues/894 https://github.com/tuna/issues/issues/809 等。

**Comment by jiegec** [comment]
您好，TUNA 没有对用户进行限速，也不需要负担带宽的费。

**Comment by Harry-Chen** [comment]
不存在这样的限速，谢谢。

**Comment by forbxy** [comment]
conda和pypi源

**Comment by shankerwangmiao** [comment]
TUNA 共有两台服务器，监控数据可以在“服务器状态”中看到。两台服务器总带宽已经达到了 5Gbps 以上。如果要是我们限速 10KB/s，怎么会有如此之高的带宽？

TUNA 是镜像站，不是下载加速器。网络传输带宽是一个复杂的科学问题，受到包括服务器、客户端、中间传输网络等极多环节的影响。TUNA 无法保证到任何一个客户端都有较高的下载速度。上述镜像并非 TUNA 独家提供，如果您发现下载速度缓慢，那么建议您更换到其它您下载速度快的镜像站。
