### ISSUE TITLE
镜像 ArcoLinux 

### ISSUE THREAD

**Issue by FANminiworld** [tuna/issues#1175]
#### 项目名称与简介(Project Intro.)

[ArcoLinux](https://arcolinux.info)，ArchLinux的衍生发行版

#### 上游地址与镜像方法(How to Mirror)

https://bike.seedhost.eu/arcolinux

#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：无

**Comment by Harry-Chen** [comment]
调查看起来用户基数并不大，目前暂不予考虑
