### ISSUE TITLE
请求建立Ubuntu Unity镜像

### ISSUE THREAD

**Issue by DengSW0423** [tuna/issues#1177]
# 项目名称 
Ubuntu Unity 
官网：https://ubuntuunity.org/
# 项目简介
社区维护的使用Unity 7 桌面环境的Ubuntu衍生版
# 上游源地址 
http://linux.darkpenguin.net/distros/ubuntu-unity/
# 镜像信息
http://www.darkpenguin.net/

**Comment by ZenithalHourlyRate** [comment]
https://github.com/ustclug/mirrorrequest/issues/315#issuecomment-1517399442
