### ISSUE TITLE
Manjaro的镜像貌似改到了github

### ISSUE THREAD

**Issue by 1900011604** [tuna/issues#1178]
#### 项目名称与简介(Project Intro.)

Release-Review ISOs of Manjaro Linux

#### 上游地址与镜像方法(How to Mirror)

https://github.com/manjaro/release-review

https://github.com/manjaro/release-review/releases

#### 其他信息(Other)

https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/m/ma/manjaro-community/kde-dev/

这个貌似改到了https://github.com/manjaro/plasma-daily/releases

它的Mirror可以参考https://github.com/manjaro-plasma/iso-profiles

应该也可以在`https://github.com/tuna/tunasync-scripts/blob/master/github-release.py`加一行解决

**Comment by ZenithalHourlyRate** [comment]
感谢您提供的信息

考虑到 release-review / plasma-daily 的构建频率较高，以及用户需求可能较小，暂不进行镜像
