### ISSUE TITLE
Ubuntu Cloud镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#118]
#### 项目名称与简介(Project Intro.)

Ubuntu Cloud是Ubuntu专为云平台部署定制的镜像(如Openstack, LXD/LXC，AWS等等)
#### 上游地址与镜像方法(How to Mirror)

主页: https://cloud-images.ubuntu.com/
镜像方法: Via rsync: rsync://cloud-images.ubuntu.com/cloud-images (from [here](https://jujucharms.com/u/tribaal/ubuntu-mirror#charm-config-cloudimage-sync-location))
或反向代理也可
#### 其他信息(Other)
- 镜像大小(Mirror Size): 暂未知

**Comment by bigeagle** [comment]
好几天都没同步玩，我看了一下它的 released 目录里把所有历史 build 都包括进来了…… 于是 exclude 掉，用 daily 就好了

**Comment by abcfy2** [comment]
恩，只同步`release`目录应该就够了, `release-YYYYMMDD`这种目录可以不用同步，一般也不会有人去用

**Comment by abcfy2** [comment]
发现`release`目录这玩意还不能忽略，下面有个`stream/`目录，LXD，AWS之类的部署(不确定openstack是否需要)都要看这个目录的内容。

如果数据量实在太大，可以考虑忽略掉`\d{7}(\.\d+)?$`(比如release-YYYYMMDD, YYYYMMDD.d)这样的目录，减少存储与提高同步速率

**Comment by Harry-Chen** [comment]
Seems it's done.

**Comment by bigeagle** [comment]
@Harry-Chen 别瞎搞……

**Comment by huiyiqun** [comment]
还没同步完吗？这也太久了
