### ISSUE TITLE
nodesource镜像换地址了吗？

### ISSUE THREAD

**Issue by fearlessxjdx** [tuna/issues#1180]
`https://mirrors.tuna.tsinghua.edu.cn/nodesource/deb_14.x/` 等地址404了，请问是换了地址吗？

如果不维护了，有没有其他的推荐源？

**Comment by jiegec** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-nodesource/

**Comment by Alan-Liang** [comment]
您好，想问一下上游出了什么问题？Rate limiting 吗？想自建一个内部镜像，想知道可能遇到什么事情。

**Comment by shankerwangmiao** [comment]
我们不太了解具体的问题。出现的现象是，nodesource 服务器对于所有同步的 HTTP 请求返回了 403.
