### ISSUE TITLE
[tuna]Mirror Request for new mirror prometheus/promu

### ISSUE THREAD

**Issue by chanjarster** [tuna/issues#1181]
#### 项目名称与简介(Project Intro.)

prometheus/promu

#### 上游地址与镜像方法(How to Mirror)

https://github.com/prometheus/promu/releases

#### 其他信息(Other)
- 镜像大小(Mirror Size)：~100M
- 该镜像需求是否被之前的 issue 提出过：没有

**Comment by ZenithalHourlyRate** [comment]
> promu is the utility tool for building and releasing Prometheus projects

如果能获取和构建 prometheus projects，则也应该能直接获取和构建 promu，单独镜像意义较小。
