### ISSUE TITLE
cocoapods源clone总是失败

### ISSUE THREAD

**Issue by ufogxl** [tuna/issues#1182]
当我使用cocoapods更换源的提示进行操作时，执行到clone这一步后，刚开始速度还是很快的，几十兆之后就一直没速度了，最后会失败，报eof错误

**Comment by skyzh** [comment]
类似的问题似乎有很多。https://github.com/tuna/issues/issues/1151 有尝试过 BFSU 的 CocoaPods 源吗？

**Comment by ufogxl** [comment]
> 类似的问题似乎有很多。FYI #1151 有尝试过 BFSU 的 CocoaPods 源吗？

谢谢提醒，使用了gitee的源clone后将remote改为清华的地址可用了。
