### ISSUE TITLE
DNS666 解析出的部分 GitHub ip结果无法访问

### ISSUE THREAD

**Issue by YujiaCheng1996** [tuna/issues#1185]
一直在使用 101.6.6.6:5353 加速 GitHub 访问，最近有概率返回的一些ip无法访问，并有概率无结果。
当前能够解析github.com到：
```
无结果
52.74.223.119
13.229.188.59
13.250.177.223
```
但是测试发现不能用 13.229.188.59 访问，加上概率的无结果NXDOMAIN，使得GitHub时而能上时而不能上。
运营商是江苏联通，之前使用DNS666一切正常，最近出现这个问题很苦恼，目前只能在hosts文件中写死ip。

**Comment by Harry-Chen** [comment]
DNS 666 的 [许可协议] 中写明：

> 由于 TUNA DNS666 服务位于教育网内，查询结果可能与校外用户有所不同：例如可能会获得位于教育网内的内容分发网络 IP 地址。可能导致的后果，依据内容分发提供商实现方式的不同，包含但不限于连接失败、访问缓慢。校外使用者必须对此类状况有所认知，并且知晓在故障出现时，应当直接与内容分发提供商、或是其他对应服务提供商进行联系，且造成的所有直接或间接损失与 TUNA 无关。

建议您更换别的 DNS 服务。
