### ISSUE TITLE
请求增加镜像请求AlmaLinux

### ISSUE THREAD

**Issue by chinacdj** [tuna/issues#1186]
#### 项目名称与简介(Project Intro.)
AlmaLinux 的官网：https://almalinux.org
AlmaLinux OS是RHEL®8的1：1二进制兼容的分支，它由已建立的CloudLinux OS的创建者构建。是一个开放源代码，社区驱动的项目，旨在弥补CentOS稳定版本的废止所留下的空白。
#### 上游地址与镜像方法(How to Mirror)
上游地址：https://repo.almalinux.org/almalinux/
镜像方法：/usr/bin/rsync -avSH -f 'R .~tmp~' --delete-delay --delay-updates rsync://rsync.repo.almalinux.org/almalinux/ /almalinux/dir/on/your/server/ 或者 参考官方镜像文档https://wiki.almalinux.org/Mirrors.html
#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：

**Comment by Harry-Chen** [comment]
由于与 Rocky Linux 类似的原因 (#1281)，不予镜像。

**Comment by salmon5** [comment]
可以考虑下，AlmaLinux的更新速度比Rocky Linux更快，对于一些安全更新还是有价值的。

**Comment by salmon5** [comment]
https://news.fnal.gov/2022/12/fermilab-cern-recommendation-for-linux-distribution/
AlmaLinux被费米实验室和CERN采用；
我想核心原因还是"AlmaLinux OS基金会是一个 501(c)(6) 非营利组织"，
Rocky Linux属于Rocky Enterprise Software Foundation (RESF) ，RESF 由 Gregory Kurtzer 创立并拥有。
Rocky Linux有可能会想CentOS一样被卖。

所以提供AlmaLinux的镜像也不算冗余。
