### ISSUE TITLE
请求建立Atom编辑器镜像

### ISSUE THREAD

**Issue by LiuAlexanderII** [tuna/issues#1187]
#### 项目名称与简介(Project Intro.)
atom，专门为程序员推出的一个跨平台文本编辑器           ——百度百科
Github下载慢（江西赣州），而且没有任何一家镜像站提供此镜像
#### 上游地址与镜像方法(How to Mirror)
地址：https://github.com/atom/atom/releases
#### 其他信息(Other)
- 镜像大小(Mirror Size)：单版本2.14GB 3个版本6.32GB
- 该镜像需求是否被之前的 issue 提出过：否

**Comment by Harry-Chen** [comment]
已经开始同步，位于 https://mirrors.tuna.tsinghua.edu.cn/github-release/atom/atom/
