### ISSUE TITLE
申请images.maas.io镜像站

### ISSUE THREAD

**Issue by yanxiaomu-1** [tuna/issues#1188]
项目名称与简介(Project Intro.)
MAAS是用于物理机初始安装和管理的系统，由Canonical提供。MAAS可以将操作系统镜像通过网络启动（PXE）的方式主动部署到多个空的物理机上，实现集群装机的第一步。
这里的操作系统镜像软件和一般的ubuntu软件有区别，而且国内还没有镜像网站。

#### 上游地址与镜像方法(How to Mirror)

images.maasd.io

#### 其他信息(Other)
- 镜像大小(Mirror Size)：常用的ubuntu20.04约1G、，ubuntu18.04大概1G，Ubuntu16.04约1G，centos7约400M，centos8约1G
- 该镜像需求是否被之前的 issue 提出过：没有

**Comment by makeding** [comment]
images.maasd.io -> images.maas.io

**Comment by Harry-Chen** [comment]
根据 <https://maas.io/docs/snap/3.0/ui/local-image-mirror> 的说法，似乎无法简单镜像
