### ISSUE TITLE
raspbian镜像已经换到https了，但是使用说明中还是http的

### ISSUE THREAD

**Issue by non-trace** [tuna/issues#1189]
#### 发生了什么（What happened）
换源后无法使用
<img width="926" alt="图片" src="https://user-images.githubusercontent.com/7167108/110225436-8dd29000-7f20-11eb-846f-6e3d1a46e22b.png">
<img width="890" alt="图片" src="https://user-images.githubusercontent.com/7167108/110225460-bfe3f200-7f20-11eb-9521-7eabe8393c8e.png">

#### 期望的现象（What you expected to happen）

希望将使用说明中的地址修改正确

#### 您的环境（Environment）
- 操作系统（OS Version）：树莓派

**Comment by ZenithalHourlyRate** [comment]
```
$ wget -4 http://mirrors.bfsu.edu.cn/raspbian/raspbian/dists/buster/InRelease
--2021-03-07 17:29:29--  http://mirrors.bfsu.edu.cn/raspbian/raspbian/dists/buster/InRelease
Resolving mirrors.bfsu.edu.cn (mirrors.bfsu.edu.cn)... 39.155.141.16
Connecting to mirrors.bfsu.edu.cn (mirrors.bfsu.edu.cn)|39.155.141.16|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14974 (15K) [application/octet-stream]
Saving to: 'InRelease'

InRelease                               100%[===============================================================================>]  14.62K  --.-KB/s    in 0.04s

2021-03-07 17:29:29 (391 KB/s) - 'InRelease' saved [14974/14974]
```

我这边在多台机器上不能复现。这可能是您的网络问题，需要您的排查。

同时，对该软件源来说，提供 http 是有必要的，因为有一部分的系统上并没有安装 apt-transport-https，无法使用 https 的镜像源。
