### ISSUE TITLE
Jenkins在更新时自动跳转至清华镜像站，但无法完成更新

### ISSUE THREAD

**Issue by ethnchao** [tuna/issues#119]
不管Jenkins设置的更新站点是什么，都会判断地区，然后**最终**跳转到该地区分配的镜像站，中国区域跳转到了清华TUNA，但是这一跳转出现了问题，更新plugin失败。

![image](https://cloud.githubusercontent.com/assets/20638812/18622899/b3a53638-7e68-11e6-971f-646354746374.png)

查看jpi文件内容：

![image](https://cloud.githubusercontent.com/assets/20638812/18622936/2a8523c6-7e69-11e6-944a-ed96ef939ba0.png)

Jenkins版本： 2.23

**Comment by bigeagle** [comment]
这是因为我们强制跳转了 HTTPS，不知 jenkins 为何会写个 HTTP 的 URL 出去。

**Comment by bigeagle** [comment]
请到 jenkins 的 jira 反应一下这个问题，我们只是忠实地镜像上游提供的内容，至于上游的跳转不对，我们也无能为力。https://issues.jenkins-ci.org/

**Comment by ethnchao** [comment]
已经在JIRA里找到类似的issue，更改为reopened状态，且发现就在我之前也有人已经报告了这个问题：
https://issues.jenkins-ci.org/browse/JENKINS-8028

**Comment by bigeagle** [comment]
好的～

**Comment by coreywei** [comment]
因为tuna mirror只支持https，而jenkins的现有代码不支持http->https的跳转，所以导致了这个问题。现在tuna mirror已经被disabled了。
是否可以考虑tuna mirror也支持http，而不仅仅是https?

https://issues.jenkins-ci.org/browse/JENKINS-8028
https://issues.jenkins-ci.org/browse/JENKINS-38340

**Comment by bigeagle** [comment]
是的，我已经在邮件列表反映了这个问题。由于各路运营商少则做缓存，多则中间人攻击，HTTPS 是唯一选择。我们已经在 jenkins 邮件列表说明态度。

**Comment by abcfy2** [comment]
似乎jenkins官方并未对这个issue做特别处理，仅仅只是disable掉CN的region。报告的issue依旧在jenkins的jira上挂着，不知道处理的进度怎么样了。
