### ISSUE TITLE
HTTP connection was reset on mirrors.bfsu.edu.cn (39.155.141.16)

### ISSUE THREAD

**Issue by bclswl0827** [tuna/issues#1190]
I encountered the HTTP connection reset problem on mirrors.bfsu.edu.cn (39.155.141.16), I can't use apt to update the package list and install packages right now.

```
$ curl -v mirrors.bfsu.edu.cn
* Expire in 0 ms for 6 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
...
* Expire in 0 ms for 1 (transfer 0x11cb880)
* Expire in 2 ms for 1 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
* Expire in 2 ms for 1 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
* Expire in 1 ms for 1 (transfer 0x11cb880)
*   Trying 39.155.141.16...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x11cb880)
* Connected to mirrors.bfsu.edu.cn (39.155.141.16) port 80 (#0)
> GET / HTTP/1.1
> Host: mirrors.bfsu.edu.cn
> User-Agent: curl/7.64.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by bclswl0827** [comment]
This problem seems to have appeared yesterday. I have tested it on servers in many different places and got the same results.
This may be a blow to users who use mirrors.bfsu.edu.cn as the apt mirror.

**Comment by shankerwangmiao** [comment]
I have tested on several servers, but I cannot reproduce this issue.

**Comment by skyzh** [comment]
可以尝试一下 https 是否能连接。https://github.com/tuna/issues/issues/1189 似乎是类似的问题。

**Comment by skyzh** [comment]
另外 SJTU 这边也有观察到外部连教育网的 http 连接被 reset 的情况，不太确定具体的原因。

**Comment by shankerwangmiao** [comment]
> 另外 SJTU 这边也有观察到外部连教育网的 http 连接被 reset 的情况，不太确定具体的原因。

BFSU 的 v4 是移动。

**Comment by bclswl0827** [comment]
Keeping HTTP is necessary because for some older debian distributions, they don’t have apt-transport-https built in, which may cause errors. So is Docker image e.g. `debian:buster-slim`

**Comment by bclswl0827** [comment]
In addition, I can't access your website via HTTP any more, it seems to be your server fault.
![a](https://user-images.githubusercontent.com/24319042/110244484-dc704080-7f99-11eb-9cfe-57a9fd5df1de.png)

**Comment by skyzh** [comment]
我用 https://tools.ipip.net/traceroute.php 看了一下，看起来从“北京 (bgp)”到 bfsu 有两跳在教育网里？不知道对前面提到的 reset 现象有没有什么影响，或许过几天就好了？（大雾

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/4198311/110244459-b8146400-7f99-11eb-9161-ce9d88437f16.png">

Anyway, 目前应该可以试试用 https 能不能访问，看看情况是不是如我所推测的“仅 http 被阻断”。

**Comment by bclswl0827** [comment]
> 我用 https://tools.ipip.net/traceroute.php 看了一下，看起来从“北京 (bgp)”到 bfsu 有两跳在教育网里？不知道对前面提到的 reset 现象有没有什么影响，或许过几天就好了？（大雾
> 
> <img alt="image" width="1014" src="https://user-images.githubusercontent.com/4198311/110244459-b8146400-7f99-11eb-9161-ce9d88437f16.png">
> 
> Anyway, 目前应该可以试试用 https 能不能访问，看看情况是不是如我所推测的“仅 http 被阻断”。

Sure, but what matters is I use bfsu in minimised docker images, which dont has `apt-transport-https` included :(

**Comment by bclswl0827** [comment]
> I encountered the HTTP connection reset problem on mirrors.bfsu.edu.cn (39.155.141.16), I can't use apt to update the package list and install packages right now.
> 
> ```
> $ curl -v mirrors.bfsu.edu.cn
> * Expire in 0 ms for 6 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> ...
> * Expire in 0 ms for 1 (transfer 0x11cb880)
> * Expire in 2 ms for 1 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> * Expire in 2 ms for 1 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> * Expire in 1 ms for 1 (transfer 0x11cb880)
> *   Trying 39.155.141.16...
> * TCP_NODELAY set
> * Expire in 200 ms for 4 (transfer 0x11cb880)
> * Connected to mirrors.bfsu.edu.cn (39.155.141.16) port 80 (#0)
> > GET / HTTP/1.1
> > Host: mirrors.bfsu.edu.cn
> > User-Agent: curl/7.64.0
> > Accept: */*
> > 
> * Recv failure: Connection reset by peer
> * Closing connection 0
> curl: (56) Recv failure: Connection reset by peer
> ```

Compared with Tuna, it worked well.
```
$ curl -v mirrors.tuna.tsinghua.edu.cn
* Expire in 0 ms for 6 (transfer 0xaaaae7b9df10)
* Expire in 1 ms for 1 (transfer 0xaaaae7b9df10)
...
* Expire in 8 ms for 1 (transfer 0xaaaae7b9df10)
* Expire in 10 ms for 1 (transfer 0xaaaae7b9df10)
* Expire in 10 ms for 1 (transfer 0xaaaae7b9df10)
* Expire in 13 ms for 1 (transfer 0xaaaae7b9df10)
*   Trying 101.6.8.193...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0xaaaae7b9df10)
* Connected to mirrors.tuna.tsinghua.edu.cn (101.6.8.193) port 80 (#0)
> GET / HTTP/1.1
> Host: mirrors.tuna.tsinghua.edu.cn
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.18.0
< Date: Sun, 07 Mar 2021 15:25:43 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< Location: https://mirrors.tuna.tsinghua.edu.cn/
< X-TUNA-MIRROR-ID: neomirrors
< Strict-Transport-Security: max-age=31536000
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
* Connection #0 to host mirrors.tuna.tsinghua.edu.cn left intact
```

**Comment by bclswl0827** [comment]
It looks like your firewall is blocking the IP of my server
I changed the IP of the server and it seems normal now
