### ISSUE TITLE
opentuna镜像请求Homebrew / Linuxbrew

### ISSUE THREAD

**Issue by fcying** [tuna/issues#1193]
项目名称与简介(Project Intro.)
https://brew.sh/

Homebrew是一款自由及開放原始碼的軟體套件管理系統，用以簡化macOS Linux系統上的軟體安裝過程，最初由馬克斯·霍威爾寫成。因其可延伸性得到了一致好評，而在Ruby on Rails社群廣為人知。 Homebrew使用GitHub，通過用戶的貢獻擴大對軟體包的支援

上游地址与镜像方法(How to Mirror)
https://github.com/Homebrew/homebrew-core or https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

其他信息(Other)
镜像大小(Mirror Size): 未知

**Comment by johnnychen94** [comment]
已经有了：https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

**Comment by shankerwangmiao** [comment]
> 已经有了：https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

他说的是 opentuna 上的

**Comment by happyaron** [comment]
opentuna 即将停止服务，关闭 issue
