### ISSUE TITLE
LineageOS上次成功同步已经是5天前了

### ISSUE THREAD

**Issue by Nappp** [tuna/issues#1194]
#### 发生了什么（What happened）
代码不同步导致repo sync过程中很多失败，可否处理一下

#### 如何重现（How to reproduce it）
https://mirror.tuna.tsinghua.edu.cn/status/

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by ZenithalHourlyRate** [comment]
目前的同步已较新
