### ISSUE TITLE
建议删除RepoForge镜像或注明该镜像已不再更新请不要使用

### ISSUE THREAD

**Issue by yachen4ever** [tuna/issues#1197]
rpmforge/repoforge 是一个为rhel/centos提供php/mysql等软件最新版本的第三方软件源，但已经常年不更新，其官网http://repoforge.org/ 也告知了用户 RepoForge might be outdated. We have no updates since very long time.
同时 centos 第三方源介绍界面也告知用户不要继续使用repoforge/rpmforge。一个不再更新的镜像不应继续出现在tuna镜像源中，何况mouseover时还标注了“Repoforge 是 RHEL 系统下的软件仓库，拥有 10000 多个软件包，被认为是最安全、最稳定的一个软件仓库” 
建议删除该镜像，使用ius替代，谢谢

**Comment by ZenithalHourlyRate** [comment]
目前镜像站前端已不再显示 repoforge，尽管仍可通过 https://mirrors.tuna.tsinghua.edu.cn/repoforge/ 访问相关数据
