### ISSUE TITLE
镜像源中anaconda/cloud/conda-forge/win-64无法正常打开

### ISSUE THREAD

**Issue by TJJJK** [tuna/issues#1198]
#### 发生了什么（What happened）
打开镜像中anaconda/cloud/conda-forge/win-64时显示Too many files to list
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10
- 浏览器（如果适用）（Browser version, if applicable）：Chrome
- 其他（Others）：

**Comment by skyzh** [comment]
如你所见，因为文件太多，所以不能浏览。但是 conda 应该是可以正常使用的。
