### ISSUE TITLE
希望能有Saltstack的镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#12]
官方仓库地址: https://repo.saltstack.com/

Saltstack是使用Python编写的服务器配置管理工具。目前用户也越来越多。但是Salt官方仓库在我这边感觉被墙了一样，速度奇慢无比，而且经常无法update。希望tuna可以镜像这个仓库。

**Comment by scateu** [comment]
Not today.

**Comment by alick** [comment]
楼主给的链接都不对-_-

On Wed, Dec 30, 2015 at 10:24 PM, Wang Kang <notifications@github.com>
wrote:

> Not today.
>
>
> On Wed, 30 Dec 2015, Feng Yu wrote:
>
> > 官方仓库地址: https://reposaltstackcom/
> >
> >
> Saltstack是使用Python编写的服务器配置管理工具。目前用户也越来越多。但是Salt官方仓库在我这边感觉被墙了一样，速度奇慢无比，而且经常无法update。希望tuna可以镜像这个仓库。
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/tuna/issues/issues/12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuna/issues/issues/12#issuecomment-168123399>.
>



-- 
Regards,
Alick

**Comment by huiyiqun** [comment]
链接貌似没什么问题。

我dig了一下，这个repo好像没有CDN，解析出来的v4地址在198.199.77.106，是纽约do的。
理论上do应该没有被和谐，应该只是单纯网速慢吧。

有v6地址，同步应该没什么问题，不过好多发行版(包括windows)，要用http扒吗？

**Comment by abcfy2** [comment]
Windows的话如果存储容量允许可以考虑一并同步。否则的话只同步Linux应该就够了。Salt在Windows上跑的用例似乎不算多。

**Comment by scateu** [comment]
链接是由于Github的邮件通知中，自动把所有的链接中的\dot给去掉了...

**Comment by scateu** [comment]
我收到的邮件是这样：

官方仓库地址: https://reposaltstackcom/

Saltstack是使用Python编写的服务器配置管理工具。目前用户也越来越多。但是Salt官方仓库在我这边感觉被墙了一样，速度奇慢无比，而且经常无法update。希望tuna可以镜像这个仓库。

**Comment by huiyiqun** [comment]
发现了 我收到的也是这样 只是我先打开了github

**Comment by alick** [comment]
@scateu 康哥好眼力

**Comment by bubbleatgit** [comment]
支持tuna镜像salt

**Comment by abcfy2** [comment]
墙越来越高了，最近连apt-get update都困难，repo.saltstack.com经常超时。

**Comment by shankerwangmiao** [comment]
syncing

**Comment by shankerwangmiao** [comment]
won't do, rsync failed

**Comment by shankerwangmiao** [comment]
![2016-11-22 11 55 46](https://cloud.githubusercontent.com/assets/6825907/20510369/9ec8544c-b0aa-11e6-8455-8fea77b8c6cb.png)

**Comment by bigeagle** [comment]
刚挂了梯子搞，还被 reset，这个神奇了……

**Comment by bigeagle** [comment]
我觉得是上游有问题

**Comment by bigeagle** [comment]
换了个姿势挂梯子，还是被 reset ……
我尽力了…

**Comment by abcfy2** [comment]
这个是salt服务器的问题？可以考虑给salt官方递交issue问问

**Comment by huiyiqun** [comment]
顺便问一下为什么没有v6吧 有v6的话同步会轻松很多。

**Comment by shankerwangmiao** [comment]
似乎已经同步好了，之前的问题应该是上游的毛病
