### ISSUE TITLE
Loongson 龙芯相关

### ISSUE THREAD

**Issue by scateu** [tuna/issues#120]
#### 项目名称与简介(Project Intro.)

龙芯相关的镜像。目前是由龙芯开源社区的刘世伟前辈在维护，这几天USTC的挂掉了之后没有镜像了。
#### 上游地址与镜像方法(How to Mirror)

rsync.anheng.com.cn/bjlx
rsync.anheng.com.cn/loongson
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
  未知

刘世伟的GPG Fingerprint: C882 2846

**Comment by lshw** [comment]
bjlx 是debian的龙芯补充源， 用来补充一些龙芯的一些包和源码，包含squeeze,wheezy,jessie,stretch,即debian6,7,8,9   
镜像大小:bjlx  5G
loongson 
是比较杂乱的一些关于龙芯的一些东西， 包括各种补丁， 以前的基于龙芯的发行版的安装镜像，各种龙芯硬件的pmon  bios源码，等等，  以及龙芯快速刷机系统，和各种刷机包。
镜像大小:loongson 15G

**Comment by bigeagle** [comment]
好嗒，已加入同步队列～

**Comment by bigeagle** [comment]
![deepinscreenshot20160922194322](https://cloud.githubusercontent.com/assets/548512/18746936/eb6fb4ee-80fc-11e6-9ec8-4f1661e2d223.png)
@lshw 有一些文件权限不太对，同步不下来，您看一下？

**Comment by lshw** [comment]
修复了。再试试，

**Comment by bigeagle** [comment]
![deepinscreenshot20160923202502](https://cloud.githubusercontent.com/assets/548512/18785629/dda4fd22-81cb-11e6-98ab-58b96411f809.png)
@lshw 还是有一些

**Comment by bigeagle** [comment]
@lshw Hi, 最近 rsync.anheng.com.cn 连接不上了，是遇到什么故障了吗？

**Comment by lshw** [comment]
哦，抱歉，刚看到，服务器升级系统，systemd没有把rsync自动启动设置搞过去，

**Comment by shankerwangmiao** [comment]
@lshw 最近同步的上游服务器又频繁出现连接不能的情况，请协助排查。我们这边的日志显示是 Connection Refused

**Comment by lshw** [comment]
好的， 我检查一下， 最近公司从海淀搬到了丰台，可能有些东西需要调整一下，

**Comment by shankerwangmiao** [comment]
不过很奇怪的是，偶尔还可以连接上。
