### ISSUE TITLE
bfsu的pypi镜像出问题了

### ISSUE THREAD

**Issue by mjdxyr** [tuna/issues#1200]
#### 发生了什么（What happened）
当我pip install tensorflow时，下载好2.4.1版本后又继续下了2.4.0、2.3、2.2等更低版本的包，当我下载nuscene-devkit时也一直下载notebook包
#### 期望的现象（What you expected to happen）
下载好2.4.1就开始安装
#### 如何重现（How to reproduce it）
pip install tensorflow

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by XYenon** [comment]
https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020

可以参考下是不是受新版 pip 依赖解析行为更改影响

**Comment by mjdxyr** [comment]
我已经更新到最新的pip,更改了网易的镜像后这个问题就解决了

**Comment by skyzh** [comment]
最近 SJTUG 镜像站的用户也反馈了相同的问题。似乎是这个 issue 导致的 https://github.com/pypa/pip/issues/8713

**Comment by skyzh** [comment]
总结一下就是由于用户 pip 环境中对某个包的版本有限制，pip 需要下载所有的中间版本，但不需要包的内容，只需要看看它们的版本依赖关系。

> @jcugat, pip download the distributions only to retrieve the dependency information. Say if some project has dependency requirements (e.g. spam>42) conflicting with that of boto3>1.12.32 (e.g. spam<42), there's no way pip can know what spam version that boto3 from 1.12.33 to 1.14.34 require by just looking at boto3 1.14.35. It seems that there's no way to lower the complexity of dependency resolution (which is NP-hard).

所以解决办法应该是使用老的解析器 `--use-deprecated=legacy-resolver`，当然有可能造出一个坏掉的 pip 环境。

**Comment by ZenithalHourlyRate** [comment]
我们当时是通过 `pip -vvv` 发现镜像站上通过缺少某包使得 `pip` 降级到较老版本的，在同步该缺少的包后 pip 能正常安装。建议在诊断时考虑该因素。
