### ISSUE TITLE
服务故障 

### ISSUE THREAD

**Issue by bAdOoWindy** [tuna/issues#1202]
https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/tools/repohooks/
404
是需要重新INIT吗？还是说我这边IPV6连接不稳定？

**Comment by bAdOoWindy** [comment]
fatal: unable to access 'https://mirrors6.tuna.tsinghua.edu.cn/git/AOSP/platform/tools/repohooks/': Failed to connect to mirrors6.tuna.tsinghua.edu.cn port 443: Connection timed out

**Comment by dramforever** [comment]
该地址处是一个 Git 的仓库，无法直接通过 HTTP（如浏览器）直接访问。

这个仓库在我这边使用 Git 去 clone 是正常的，可能是您那里的网络问题。可以尝试使用 https://mirrors6.bfsu.edu.cn 上的 AOSP 镜像。

**Comment by bAdOoWindy** [comment]
> 
> 
> 该地址处是一个 Git 的仓库，无法直接通过 HTTP（如浏览器）直接访问。
> 
> 这个仓库在我这边使用 Git 去 clone 是正常的，可能是您那里的网络问题。可以尝试使用 https://mirrors6.bfsu.edu.cn 上的 AOSP 镜像。

好的谢谢
关闭了
