### ISSUE TITLE
anacoda镜像申请补充/conda-forge/osx-arm64目录

### ISSUE THREAD

**Issue by victor201314** [tuna/issues#1203]
##  一。采用tuna镜像源：
.condarc了文件如下：
···
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
···

安装pandas，显示如下：
···
~ » conda install -c conda-forge pandas                                                  zhangweitao@Victor-MacBook-Air
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pandas

Current channels:

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
··· 
## 切换回国外源：
.condarc配置如下

···
channel_priority: strict
channels:
  - conda-forge
  - defaults
···

search conda显示如下：
···
~ » conda search pandas                                                            127 ↵ zhangweitao@Victor-MacBook-Air
Loading channels: done
# Name                       Version           Build  Channel             
pandas                         1.1.3  py38h73c04be_2  conda-forge         
pandas                         1.1.3  py39h88a2970_2  conda-forge         
pandas                         1.1.4  py38h9b9bf68_0  conda-forge         
pandas                         1.1.4  py39ha4bedbf_0  conda-forge         
pandas                         1.1.5  py38h9b9bf68_0  conda-forge         
pandas                         1.1.5  py39ha4bedbf_0  conda-forge         
pandas                         1.2.0  py38h9b9bf68_0  conda-forge         
pandas                         1.2.0  py38h9b9bf68_1  conda-forge         
pandas                         1.2.0  py39ha4bedbf_0  conda-forge         
pandas                         1.2.0  py39ha4bedbf_1  conda-forge         
pandas                         1.2.1  py38h9b9bf68_0  conda-forge         
pandas                         1.2.1  py39ha4bedbf_0  conda-forge         
pandas                         1.2.2  py38h9b9bf68_0  conda-forge         
pandas                         1.2.2  py39ha4bedbf_0  conda-forge         
pandas                         1.2.3  py38h9b9bf68_0  conda-forge         
pandas                         1.2.3  py39ha4bedbf_0  conda-forge  

···

## 在https://conda.anaconda.org/conda-forge/osx-arm64/网站，可以找到相关的panda包：

···
pandas-1.2.3-py38h9b9bf68_0.tar.bz2 | 10.5 MB | 2021-03-02 15:28:16 +0000 | 0e6cee80d7ab2114edb7e93ea2b4d1d257f7689aaa52d76e4616e8a6f70f4027 | 2f852c6bbe75a1bfc2dd056c6ebb58e7
-- | -- | -- | -- | --
pandas-1.2.3-py39ha4bedbf_0.tar.bz2 | 10.6 MB | 2021-03-02 15:26:25 +0000
···

综上所述，请核实tuna的conda是否完整包含了osx-arm64的python包。

谢谢

**Comment by skyzh** [comment]
conda-forge 没有同步 osx-arm64。FYI https://github.com/tuna/tunasync-scripts/blob/master/anaconda.py#L33

**Comment by victor201314** [comment]
所以希望tuna能够同步完整的conda-forge，这个是社区维护的python包，

**Comment by shankerwangmiao** [comment]
已经补充了。
