### ISSUE TITLE
申请镜像rosdep

### ISSUE THREAD

**Issue by GWinfinity** [tuna/issues#1204]
项目简介
rosdep是用来检查ros package 依赖项是否完整，并进行下载和安装的工具

上游镜像在 raw.githubsercontent.com
镜像方式: git

**Comment by ZenithalHourlyRate** [comment]
注意到问题主要出现在 `rosdep init` 的过程中，参考 https://github.com/ros-infrastructure/rosdep/blob/d6c44cb9a41dc7db871626d969b788cb27d9f7f8/src/rosdep2/sources_list.py#L328 可以知道，其默认下载 https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list， 但参考其文件内容可知，其内包含的配置链接也在 https://raw.githubusercontent.com 下，所以如果要进行有效的镜像，不仅要镜像 20-default.list，并将其指向的链接进行镜像，还要改写 20-default.list 这个文件。目前我们没有这样的同步工具。

可以向 https://github.com/tuna/tunasync-scripts 贡献相关同步脚本。

**Comment by ZenithalHourlyRate** [comment]
已经镜像，使用帮助可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/rosdistro/
