### ISSUE TITLE
Contents of kali-rolling has unexpected size

### ISSUE THREAD

**Issue by suxpert** [tuna/issues#1206]
Environment:
Kali-rolling on Windows 10, linux-5.4.72-...-WSL2,

`sudo apt update` sometimes (usually) gives such error message:
> Err:5 https://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling/main amd64 Contents (deb)
>   File has unexpected size (39742687 != 39742747). Mirror sync in progress? [IP: 101.6.8.193 443]
>   Hashes of expected file:
> ...
> E: Failed to fetch ....

But the `syncing-status` show that kali has successfully synchronized. Are there disk errors?

**Comment by shankerwangmiao** [comment]
The sync has been started since 9:55. The inconsistency is because by-hash mechanism is not adopted by kail.

**Comment by suxpert** [comment]
During these days, I met this issue for more several times.
I'll have to move to other mirrors instead.

**Comment by skyzh** [comment]
> During these days, I met this issue for more several times.
> I'll have to move to other mirrors instead.

I suggest leaving this issue open and investigating what happened exactly. Different mirrors generally use similar ways to synchronize a repo. If the issue exists at TUNA, it's highly possible that other mirrors would have the same issue.

**Comment by suxpert** [comment]
The fact is that when I change to other mirrors (aliyun for example) immediately after this error, `apt update` works without any problem, so I report this issue here (but seems that they do not care).

**Comment by phy25** [comment]
Disclaimer: I am not affiliated with TUNA.

Well at least your ISP, curl result and a lot more information is missing from this issue. CERNET suffers from cross-ISP connectivity issue so it might not meet your need at all. There are [alternatives](https://mirrors.bfsu.edu.cn/kali/) (but seems that you do not care).

**Comment by Harry-Chen** [comment]
> (but seems that they do not care).

Does this look nonsense to you? https://github.com/tuna/issues/issues/1206#issuecomment-801589582
