### ISSUE TITLE
Termux上游开始尝试使用ipfs

### ISSUE THREAD

**Issue by darkgeek** [tuna/issues#1207]
Hi,
一直使用咱们mirror来更新termux的deb包。但最近2周开始，apt update就再也没有更新，是不是因为[termux开始使用ipfs](https://github.com/termux/termux-packages/issues/6348)来分发deb包的原因？

**Comment by Harry-Chen** [comment]
我们的上游是 bintray，确实是这个原因。

**Comment by iBug** [comment]
https://github.com/termux/termux-packages/issues/6348#issuecomment-803312899

> You could setup `ipfs`, pin the hashes posted in [#6348 (comment)](https://github.com/termux/termux-packages/issues/6348#issuecomment-776169136) and optionally serve a public ipfs gateway in your area. that's basically equivalent to hosting a repo mirror

**Comment by GalaxySnail** [comment]
是的，termux上游由于bintray停止服务，已经切换到ipfs。
termux-packages仓库的这个issue：[issue6348](https://github.com/termux/termux-packages/issues/6348) 已经描述了发生的情况。
目前来说，tuna镜像的termux镜像已经长时间没有得到更新，应该需要把上游软件源切换到ipfs来获取更新。

> 我们的上游是 bintray，确实是这个原因。

不过国内似乎没法正常访问ipfs.io，我不知道可以通过上游切换到ipfs来解决吗？

**Comment by GalaxySnail** [comment]
刚试了一下，目前的 https://termux.org/packages 是可以使用的。希望tuna镜像可以尽快更新

**Comment by skyzh** [comment]
> 刚试了一下，目前的 https://termux.org/packages 是可以使用的。希望tuna镜像可以尽快更新

这个页面里各种文件的 last-modified header 并不固定，应该没法用 lftp 之类的工具做增量同步。

**Comment by iBug** [comment]
> 这个页面里各种文件的 last-modified header 并不固定，应该没法用 lftp 之类的工具做增量同步。

为啥不用 [apt-sync][1] 呢？它不依赖 Last-Modified

  [1]: https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py

**Comment by skyzh** [comment]
> > 这个页面里各种文件的 last-modified header 并不固定，应该没法用 lftp 之类的工具做增量同步。
> 
> 为啥不用 [apt-sync](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py) 呢？它不依赖 Last-Modified

确实可以.png

**Comment by iBug** [comment]
USTC 镜像站已经开始从 IPFS 同步，使用 IPFS Gateway 为 dweb.link，也就是 <https://termux.org/packages/> 的跳转目标。其余几个仓库（Root, X11, Games etc.）的 IPFS hash 从[这里][1]获取，也就是最终同步的上游 URL 为

    https://dweb.link/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx
    https://dweb.link/ipns/k51qzi5uqu5dhngjg68o8x9uimwy5h8iqt91n2266idc7uet9ew3lc472upy27
    https://dweb.link/ipns/k51qzi5uqu5dlp5yjlahzcp3kfpnhbifo9ka9iybo3bp5vt781duafkyyvt9al
    https://dweb.link/ipns/k51qzi5uqu5dhvbtvdf46kkhobzgamhiirte6s6k28l2c1iapumphh3cpkw33f
    https://dweb.link/ipns/k51qzi5uqu5dj05z8mr958kwvrg7a0wqouj5nnoo5uqu1btnsljvpznfaav9nk
    https://dweb.link/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4

  [1]: https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-xeffyr

**Comment by GalaxySnail** [comment]
我有个疑问，为什么镜像站不能直接使用 https://termux.org/packages/ 作为上游进行同步，而要使用重定向后的链接呢？直接使用原链接的话应该更能及时适应上游变更吧

**Comment by iBug** [comment]
> 我有个疑问，为什么镜像站不能直接使用 [termux.org/packages](https://termux.org/packages/) 作为上游进行同步，而要使用重定向后的链接呢？直接使用原链接的话应该更能及时适应上游变更吧

因为 termux.org/packages 并没有提供主仓库以外的重定向，并且这个 IPFS 的 hash 也是由维护者给出来的，具体从哪个 IPFS Gateway 同步不太重要，IPNS 对了就行

（次要原因是同步工具的配置方式）

**Comment by GalaxySnail** [comment]
> 因为 termux.org/packages 并没有提供主仓库以外的重定向

但是主仓库里的 [game-repo](https://github.com/termux/termux-packages/blob/master/packages/game-repo/build.sh) 、 [root-repo](https://github.com/termux/termux-packages/blob/master/packages/root-repo/build.sh) 、 [science-repo](https://github.com/termux/termux-packages/blob/master/packages/science-repo/build.sh) 、 [unsable-repo](https://github.com/termux/termux-packages/blob/master/packages/unstable-repo/build.sh) 以及 [x11-repo](https://github.com/termux/termux-packages/blob/master/packages/x11-repo/build.sh) 这几个包分别提供了这些次要仓库的默认地址。

以及，[termux-change-repo](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/termux-change-repo) 脚本里也包含了它们。

``` bash
select_repository() {
    if [ "$1" == "Default repositories" ]; then
        echo "[*] Default repositories selected"
        MAIN="https://termux.org/packages/"
        GAME="https://grimler.se/game-packages-24"
        ROOT="https://grimler.se/termux-root-packages-24"
        SCIENCE="https://grimler.se/science-packages-24"
        UNSTABLE="https://termux.com/unstable-packages-bin"
        X11="https://termux.com/x11-packages-bin"
    ...
}
```

从主仓库的软件包里的这几个软件包拆包来获取当前次要仓库的上游地址应该是一个比较可靠的方式了

**Comment by iBug** [comment]
> 从主仓库的软件包里的这几个软件包拆包来获取当前次要仓库的上游地址应该是一个比较可靠的方式了

话是这么说，但是对于镜像站的同步工具来说这个维护成本可能有点高了，一个是要专门为这个做法写代码，一个是后续还需要跟进维护，如果能有更通用的方式会更好。

**Comment by ZenithalHourlyRate** [comment]
参考 https://github.com/tuna/tunasync-scripts/commit/836c5681bd3ba53a726bc63bfe1026dca06335f0
