### ISSUE TITLE
CTAN gpg not verified

### ISSUE THREAD

**Issue by 1900011604** [tuna/issues#1209]
`tlmgr.pl: package repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)`

How can I make it available?

**Comment by shankerwangmiao** [comment]
It's a local thing. Your system doesn't provide 'gpg[2]' for verification.
 
If you want to get rid of the warning (that you may as well ignore), install GnuPG.

**Comment by 1900011604** [comment]
I am using windows, I ran `gpg --list-options show-keyring texlive.asc` but its not working, what should I do?

**Comment by wangjunji0920** [comment]
> OK `tlmgr --repository http://www.texlive.info/tlgpg/ install tlgpg` can solve the problem.
> 
> see https://texlive.info/tlgpg/

![图片](https://github.com/tuna/issues/assets/77260727/bb11cfc3-a934-4d08-ba33-f4182502af7b)
