### ISSUE TITLE
请求增加 Rufus 镜像

### ISSUE THREAD

**Issue by gugutt** [tuna/issues#1210]
#### 项目名称与简介(Project Intro.)

Rufus 官方网站位于 https://rufus.ie/，官方的介绍是：

> Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.

该介绍大致意思是，Rufus 是一个帮助创建可启动的 USB 设备（启动盘）、完成 ISO 等文件的烧录的软件。

Rufus 可以用于烧录操作系统 ISO 文件到 U 盘，从而进行系统的安装。相比与其他软件，Rufus 更加轻量和迅速，这在官方网站上有说明及数据来源。目前，Rufus 官方网站上的下载链接速度过慢，无法使用。为 Rufus 提供镜像，可以方便普通用户安装系统，吸引更多人尝试新系统，包括 Linux 各发行版等。

#### 上游地址与镜像方法(How to Mirror)

Github release，https://github.com/pbatard/rufus/releases

#### 其他信息(Other)
- 镜像大小(Mirror Size)：单个版本约 10 MB
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by wlnirvana** [comment]
FYI http://mirrors.ustc.edu.cn/github-release/pbatard/rufus/

**Comment by ZenithalHourlyRate** [comment]
See https://mirrors.cernet.edu.cn/list/rufus

ustc/nju 两个镜像站已经能满足使用
