### ISSUE TITLE
同步 gentoo-portage.git 所用的 git 协议可能受到中间人攻击

### ISSUE THREAD

**Issue by jian-lin** [tuna/issues#1211]
Hi, 我在 [mirrorz](https://mirrorz.org/list/gentoo-portage.git) 上看到同步 gentoo-portage.git 用的是 git 协议，而 git 协议可能会受到中间人攻击。可以考虑更换成 https 协议来同步吗？

**Comment by Harry-Chen** [comment]
到上游的连接被 MITM 目前不在我们考虑的威胁模型中，暂无更换的打算。否则的话，我们就无法信任任何 rsync 上游了。
