### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jr1024** [tuna/issues#1213]
https://www.bahamuts.com/packagist/index/p/
建议对上面的网站进行检查，尽管里面都是空文件，但是看起来都是视频一类的东西，与镜像无关
https://www.bahamuts.com/
首页的index.html文件建议去除日文注释

**Comment by Harry-Chen** [comment]
此网站与 TUNA 完全无关。

**Comment by jr1024** [comment]
https://mirrors.tuna.tsinghua.edu.cn/packagist/index/p/ 这个是你们网站吧，同样的问题

**Comment by skyzh** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/packagist/index/p/ 这个是你们网站吧，同样的问题

里面似乎都是 PHP 的包名。可以详细叙述一下问题吗？

**Comment by jr1024** [comment]
仔细看看里面的内容吧，里面电影的资源都出来了，这个是镜像站嘛？？这个适合暴露在外嘛

**Comment by skyzh** [comment]
> 仔细看看里面的内容吧，里面电影的资源都出来了，这个是镜像站嘛？？这个适合暴露在外嘛

似乎是上游/工具的问题。packagist 上游存在这些名为电影名的包。您可以和 packagist / packagist-mirror 项目反映这个问题。

**Comment by skyzh** [comment]
Related issue: 1080p-avengers-endgame packagist

**Comment by skyzh** [comment]
Related issue: 1080p-avengers-endgame packagist

**Comment by skyzh** [comment]
Related issue: https://github.com/composer/packagist/issues/1008

**Comment by jr1024** [comment]
> > 仔细看看里面的内容吧，里面电影的资源都出来了，这个是镜像站嘛？？这个适合暴露在外嘛
> 
> 似乎是上游/工具的问题。packagist 上游存在这些名为电影名的包。您可以和 packagist / packagist-mirror 项目反映这个问题。

不管是不是这个项目的问题，那个网址显示的就是清华的，我报告问题而已，今天那个网页也打不开了，我不知道是不是我反映之后才关的，另外清华的源https://mirrors.tuna.tsinghua.edu.cn/packagist/index/p/  还有另外一个网站https://gt1.bahamuts.com/ 也有同样的问题，这个是清华的嘛？

**Comment by skyzh** [comment]
packagist 同步之外的非技术问题需要等 TUNA 镜像的维护者解答。以我个人之见，应该不是。

**Comment by jiegec** [comment]
您好，TUNA 镜像站原样提供 packagist 上游的文件。bahamuts.com 不是 TUNA 的域名，请不要使用。

**Comment by jr1024** [comment]
> 您好，TUNA 镜像站原样提供 packagist 上游的文件。bahamuts.com 不是 TUNA 的域名，请不要使用。对于电影的问题，可能是有人滥用 packagist 上传电影，请联系 packagist 进行删除；上游删除后，TUNA 镜像在同步时也会自动删除。
> 
> 从个人的角度来说，我对 packagist 未及时解决滥用问题表示遗憾。

即使反映错地方，但问题还是解决了，那两个网站目前都无法使用了，那说明还是解决问题了，另外一个就看是网站删除，还是上游删除了。

**Comment by jr1024** [comment]
> packagist 同步之外的非技术问题需要等 TUNA 镜像的维护者解答。以我个人之见，应该不是。

非常感谢关注这个问题，目前那两个网站已经无法使用，清华本身的源就等上游删除。但是另外我的另外一个问题还没有解决，清华源的进入界面会有个 index文件一闪而过，我都不知道这个网站的维护者怎么想的，这个文件不是访问不畅通的时候出现，而是打开就会出现。。。

**Comment by jiegec** [comment]
> 非常感谢关注这个问题，目前那两个网站已经无法使用，清华本身的源就等上游删除。但是另外我的另外一个问题还没有解决，清华源的进入界面会有个 index文件一闪而过，我都不知道这个网站的维护者怎么想的，这个文件不是访问不畅通的时候出现，而是打开就会出现。。。

您好，这是为了兼容一些老旧的浏览器，仅支持十分古老的 Javascript 版本，故在检测到足够新的浏览器后才显示实际的页面。

**Comment by jr1024** [comment]
> > 非常感谢关注这个问题，目前那两个网站已经无法使用，清华本身的源就等上游删除。但是另外我的另外一个问题还没有解决，清华源的进入界面会有个 index文件一闪而过，我都不知道这个网站的维护者怎么想的，这个文件不是访问不畅通的时候出现，而是打开就会出现。。。
> 
> 您好，这是为了兼容一些老旧的仅支持十分古老的 Javascript 版本的浏览器，故在检测到足够新的浏览器后才显示实际的页面。

https://pypi.tuna.tsinghua.edu.cn/simple/ 这个网页同样的问题
