### ISSUE TITLE
The openmediavault no longer has a Release file

### ISSUE THREAD

**Issue by llloxxx** [tuna/issues#1214]
Err:16 https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers/usul buster Release
  404  Not Found [IP: 101.6.8.193 443]
Reading package lists... Done
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers/usul buster Release' no longer has a Release file.

openmedaivault的extra源无法更新了

**Comment by skyzh** [comment]
https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers/dists/usul/ 这个目录下面看起来有 Release file。请检查一下您的配置？

**Comment by skyzh** [comment]
请参照 https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/ 进行配置。看起来您的配置和推荐配置不太匹配。

**Comment by llloxxx** [comment]
是的，正确的配置应该是：deb https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers usul main
