### ISSUE TITLE
Rustup镜像不完整

### ISSUE THREAD

**Issue by wlnirvana** [tuna/issues#1215]
`rustup -v target add wasm32-unknown-unknown`会从类似 https://static.rust-lang.org/dist/rust-std-1.33.0-wasm32-unknown-unknown.tar.gz 的网址获取所需toolchain，而非crates.io

更新环境变量`RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup`之后，会导致获取失败。

**Comment by jiegec** [comment]
您好，std 1.33.0 太老了，TUNA 的 Rustup 镜像仅保留近期的版本。

**Comment by wlnirvana** [comment]
@jiegec 

恩恩，刚刚看到了tuna上的[说明](https://mirrors.tuna.tsinghua.edu.cn/help/rustup/)。

> TUNA 只会保留一段时间的 nightly，如果在安装时出现错误，请用 RUSTUP_DIST_SERVER= rustup ... 来使用官方源。

不过即便比较新的toolchain好像也不完整哦。。。比如

https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/2021-02-11/rust-std-1.51.0-wasm32-unknown-unknown.tar.xz

是我地址配置有误吗？对应的源地址应为：

https://static.rust-lang.org/dist/rust-std-1.51.0-wasm32-unknown-unknown.tar.gz

**Comment by jiegec** [comment]
只保留了最近三十天的二进制。

**Comment by wlnirvana** [comment]
哦哈哈，怪不得命令行给出的错误是`verbose: downloading file from: 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/2021-02-11/rust-std-1.50.0-wasm32-unknown-unknown.tar.xz'`

改的时候没多考虑，直接更调整成最新版，结果压根URL就错了，哈哈。

谢谢告知！
