### ISSUE TITLE
llvm-apt 镜像没有同步 llvm-toolchain-focal-12

### ISSUE THREAD

**Issue by hcoona** [tuna/issues#1218]
#### 发生了什么（What happened）

llvm-apt 镜像没有提供 llvm-toolchain-focal-12

#### 期望的现象（What you expected to happen）

期望将

```
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
```

替换为

```
deb http://mirrors.tuna.tsinghua.edu.cn/llvm-apt/focal/ llvm-toolchain-focal-12 main
```

#### 如何重现（How to reproduce it）

就这么一提换就不行了，其实就是不知道怎么配置的，同步了 llvm-toolchain-focal-11 但是没有同步 llvm-toolchain-focal-12。

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：N/A

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 20.04 LTS
- 浏览器（如果适用）（Browser version, if applicable）：N/A
- 其他（Others）：N/A

**Comment by skyzh** [comment]
LLVM 同步脚本还没有加入 LLVM12。可以等 TUNA 的开发者处理。https://github.com/tuna/tunasync-scripts/blob/master/llvm-apt.sh

**Comment by hcoona** [comment]
我看你给的链接里面已经有 `$prefix-12` 了，但是我看现在同步的结果里面还是没有 llvm-12 @skyzh

**Comment by ZenithalHourlyRate** [comment]
> 我看你给的链接里面已经有 `$prefix-12` 了

该改动暂未部署到生产环境中，请耐心等待

**Comment by shankerwangmiao** [comment]
已经同步了，请知。
