### ISSUE TITLE
ceph repo 里面没有 repodata

### ISSUE THREAD

**Issue by chengweiv5** [tuna/issues#122]
感谢你们提供了 ceph-rpm 国内 mirror，我们一直在用，但是发现你们的 repo 下面 repodata 是空的，这样的话，yum 是找不到元数据来安装包的。

还得自己在每个 arch 下面手动创建 repodata，非常不方便。

能检查下是不是你们的上游现在也没有 repodata 了吗？

https://mirrors.tuna.tsinghua.edu.cn/ceph/rpm-jewel/el7/x86_64/repodata/

上面是空的。

**Comment by shankerwangmiao** [comment]
> 在 2016年9月23日，11:41，Chengwei Yang <notifications@github.com> 写道：
> 
> 感谢你们提供了 ceph-rpm 国内 mirror，我们一直在用，但是发现你们的 repo 下面 repodata 是空的，这样的话，yum 是找不到元数据来安装包的。
> 
> 还得自己在每个 arch 下面手动创建 repodata，非常不方便。
> 
> 能检查下是不是你们的上游现在也没有 repodata 了吗？
> 
是的。

http://us-east.ceph.com/rpm-jewel/el7/x86_64/repodata/

**Comment by chengweiv5** [comment]
好的，我去问下上上游

**Comment by chengweiv5** [comment]
上游回信了，应该最近会修复。

![screen shot 2016-09-26 at 16 43 31](https://cloud.githubusercontent.com/assets/689798/18828015/80ae816c-8408-11e6-9704-84bbd58af081.png)
