### ISSUE TITLE
linuxbrew的bottles不能正常下载了

### ISSUE THREAD

**Issue by wancocoding** [tuna/issues#1224]
应该是brew更新到3.1.0以后整个bottle做了迁移,导致url路径发生了变化
```
#40 26.26 ==> Downloading https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/ncurses-6.2.x86_64_linux.bottle.tar.gz
#40 29.66 curl: (22) The requested URL returned error: 404
```

**Comment by ZenithalHourlyRate** [comment]
似乎与 https://github.com/Homebrew/brew/commit/7fc52d20655522f7d984174b37c675796ee1abad 有关?
如果您设置 `export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles"` 能否正常下载?

**Comment by wancocoding** [comment]
修改之后在已经安装好的linuxbrew下使用没问题了,可以正常下载了.
我又在docker上试了一下全新安装. `portable-ruby`的下载会找github的源
```
 => => # HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git for Homebrew/brew Git remote.                                                                                                                                
 => => # HOMEBREW_CORE_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/linuxbrew-core.git for Homebrew/brew Git remote.                                                                                                                      
 => => # ==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:97e639a64dcec285392b53ad804b5334c324f1d2a8bdc2b5087b8bf8051e332f                                                                                                       
 => => # ################################################                          66.8%                                                                
```

**Comment by ZenithalHourlyRate** [comment]
由于上游切换到通过 ghcr 分发，而我们暂时没有上线[对 ghcr 的同步](https://github.com/ustclug/ustcmirror-images/tree/master/homebrew-bottles)，所以相关环境变量、镜像帮助乃至 portable-ruby 路径的修改需要等待同步任务的迁移。

**Comment by wancocoding** [comment]
了解,谢谢啦!

**Comment by XuehaiPan** [comment]
上交的 homebrew-bottle 镜像已支持 ghcr.io 同步 ([docs/homebrew-bottles](https://mirror.sjtu.edu.cn/docs/homebrew-bottles))，看文档修改时间为四月中旬 (sjtug/portal@f9cd39cecd7944f26ed3881fae2d84ff05e579e1) 。

![ScreenShot](https://user-images.githubusercontent.com/16078332/126057177-b1027508-9da9-4d1d-baed-0dee5e0ab8e8.png)

**Comment by ZenithalHourlyRate** [comment]
> 由于上游切换到通过 ghcr 分发，而我们暂时没有上线[对 ghcr 的同步](https://github.com/ustclug/ustcmirror-images/tree/master/homebrew-bottles)，所以相关环境变量、镜像帮助乃至 portable-ruby 路径的修改需要等待同步任务的迁移。

我们已经上线[对 ghcr 的同步](https://github.com/tuna/tunasync-scripts/commit/7c5b56b6eb48201d2ef4ada3fe06c64e2dc0f0b7)

> 如果您设置 `export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles"` 能否正常下载?

目前，该环境变量的两种形式均可使用，即
```bash
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles"
```
另注：
```bash
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/bottles/bottles"
```
也能正常使用。

> 乃至 portable-ruby 路径的修改

参考 [vendor-install.sh](https://github.com/Homebrew/brew/blob/e4118bc4ca2bcb77dfd0bb1e823b6b8ff7f4b877/Library/Homebrew/cmd/vendor-install.sh) 可知，其硬编码了相关路径。

该文件只在第一次安装以及 `brew update` 时发现其版本更新时下载。

不过注意到
```
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:97e639a64dcec285392b53ad804b5334c324f1d2a8bdc2b5087b8bf8051e332f
Already downloaded: /home/zenithal/.cache/Homebrew/portable-ruby-2.6.3_2.x86_64_linux.bottle.tar.gz
```
可以让用户在安装 linuxbrew 前手动下载该文件，可惜对于每一次更新就无能为力了。可以在镜像帮助中添加这一方法。

**Comment by Freed-Wu** [comment]
```shell
❯ echo $HOMEBREW_BOTTLE_DOMAIN
https://mirrors.tuna.edu.cn/linuxbrew-bottles
❯ brew install fzf
Error: Your HOMEBREW_BOTTLE_DOMAIN still contains "linuxbrew".
You must unset it (or adjust it to not contain linuxbrew
e.g. by using homebrew instead).
```

Now must use `https://mirrors.tuna.edu.cn/homebrew-bottles`
