### ISSUE TITLE
homebrew bottle domain error

### ISSUE THREAD

**Issue by leegilon** [tuna/issues#1227]
on this page:https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/
you have described that 

HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"

but i have failed many times.
i have found all the files download from this link, but after checked on your web, it should be :

https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles

then all the bottles downloading from tuna works.

**Comment by phy25** [comment]
Duplicate to #1226
