### ISSUE TITLE
一铭 Emind Desktop4.0申请镜像

### ISSUE THREAD

**Issue by xuhuang006** [tuna/issues#123]
#### 项目名称与简介(Project Intro.)
一铭桌面操作系统（Emind Desktop 4.0），是一款基于Linux基础开源技术的面向于政府、军队、教育、金融等行业的通用国产桌面操作系统。支持X86平台及多种国产芯片平台，包含了丰富的桌面应用软件，是一款全新的桌面操作系统。 

#### 上游地址与镜像方法(How to Mirror)
地址:rsync://emdmirror.emindos.org::emindlinux

同步方式rsync

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
1.56G

**Comment by bigeagle** [comment]
```
rsync rsync://emdmirror.emindos.org/emindlinux
rsync: failed to connect to emdmirror.emindos.org (36.110.17.42): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
```
配置有问题。
上周我看了一下，里面似乎是一个 apt 软件仓库？请问这个是周日 SFD 演示的桌面系统吗？

**Comment by xuhuang006** [comment]
这样啊，这个不是上周演示，上周演示在一铭云社区，OPENTHOS，感兴趣免费下载试用


发自网易邮箱大师
在2016年09月27日 15:42，bigeagle 写道:
rsync rsync://emdmirror.emindos.org/emindlinux
rsync: failed to connect to emdmirror.emindos.org (36.110.17.42): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]


配置有问题。
上周我看了一下，里面似乎是一个 apt 软件仓库？请问这个是周日 SFD 演示的桌面系统吗？

**Comment by sunzhigang** [comment]
地址是: emdmirror.emindos.org::emindlinux

**Comment by sunzhigang** [comment]
地址是: emdmirror.emindos.org::emindlinux

**Comment by sunzhigang** [comment]
地址是: emdmirror.emindos.org::emindlinux

**Comment by sunzhigang** [comment]
地址是: emdmirror.emindos.org::emindlinux

**Comment by bigeagle** [comment]
这里面怎么还有debian?

**Comment by xuhuang006** [comment]
我们的系统是基于debiand的
