### ISSUE TITLE
AOSP 清华镜像下载 android-10.0.0_r1 出现问题

### ISSUE THREAD

**Issue by whhqhy** [tuna/issues#1230]
#### 发生了什么（What happened）
下载源码失败
#### 期望的现象（What you expected to happen）
成功下载 android-10.0.0_r1 源码
#### 如何重现（How to reproduce it）
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android-10.0.0_r1
repo sync -j1 platform/prebuilts/android-emulator
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu 18.04
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

报错日志如下：
镜像`bfsu`下载
```
error: Cannot fetch platform/prebuilts/android-emulator from https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/android-emulator
Fetching: 100% (1/1), done in 3m17.942s
error: Cannot checkout platform/prebuilts/android-emulator: ManifestInvalidRevisionError: revision refs/tags/android-10.0.0_r1 in platform/prebuilts/android-emulator not found
error: in `sync -j1 platform/prebuilts/android-emulator`: revision refs/tags/android-10.0.0_r1 in platform/prebuilts/android-emulator not found
```

镜像`tuna`下载
```
error: Cannot fetch platform/prebuilts/android-emulator from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/android-emulator
Fetching: 100% (1/1), done in 5m20.652s
error: Cannot checkout platform/prebuilts/android-emulator: ManifestInvalidRevisionError: revision refs/tags/android-10.0.0_r1 in platform/prebuilts/android-emulator not found
error: in `sync -j1 platform/prebuilts/android-emulator`: revision refs/tags/android-10.0.0_r1 in platform/prebuilts/android-emulator not found
```
致命错误文件
```
remote: Compressing objects: 100% (165/165), done.        
error: inflate: data stream error (incorrect data check)
fatal: packed object e61719158b2b0ef3de7d228559c602ca1f9372a0 (stored in /home/cowboy/aosp/.repo/projects/prebuilts/android-emulator.git/objects/pack/pack-14046b830b453442ebbe21c3057da524abbb21cf.pack) is corrupt
fatal: index-pack failed
```

![微信截图_20210428185610](https://user-images.githubusercontent.com/13471546/116395230-7051e080-a856-11eb-8829-63acd8380774.png)

![微信截图_20210428190435](https://user-images.githubusercontent.com/13471546/116395280-81025680-a856-11eb-9190-caa3c2cde26e.png)

![微信截图_20210428192325](https://user-images.githubusercontent.com/13471546/116396087-814f2180-a857-11eb-9dd5-041cdf0ef8a2.png)

**Comment by ZenithalHourlyRate** [comment]
我这边使用TUNA和BFSU都不能复现

TUNA 
```
$ repo sync -j1 platform/prebuilts/android-emulator                                                       
Fetching: 100% (1/1), done in 1m24.114s                                                                   
Updating files: 100% (268/268), done.                                                                     
Checking out: 100% (1/1), done in 6.052s                                                                  
repo sync has finished successfully.                                                                      
```

BFSU
```
$ repo sync -vj1 platform/prebuilts/android-emulator                                                      
Fetching:  0% (0/1) remote: Enumerating objects: 231, done.                                               
remote: Counting objects: 100% (231/231), done.         
remote: Compressing objects: 100% (180/180), done.         
Receiving objects:  99% (229/231), 419.74 MiB | 9.80 MiB/s                                                
remote: Total 231 (delta 51), reused 156 (delta 40)                                                       
Receiving objects: 100% (231/231), 419.74 MiB | 9.80 MiB/s
Receiving objects: 100% (231/231), 441.14 MiB | 8.58 MiB/s, done.
Resolving deltas: 100% (51/51), done.
From https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/android-emulator
Fetching: 100% (1/1), done in 1m11.433s
Updating files: 100% (268/268), done.
Checking out: 100% (1/1), done in 5.735s
repo sync has finished successfully.

```

**Comment by whhqhy** [comment]
> 我这边使用TUNA和BFSU都不能复现
> 
> TUNA
> 
> ```
> $ repo sync -j1 platform/prebuilts/android-emulator                                                       
> Fetching: 100% (1/1), done in 1m24.114s                                                                   
> Updating files: 100% (268/268), done.                                                                     
> Checking out: 100% (1/1), done in 6.052s                                                                  
> repo sync has finished successfully.                                                                      
> ```
> 
> BFSU
> 
> ```
> $ repo sync -vj1 platform/prebuilts/android-emulator                                                      
> Fetching:  0% (0/1) remote: Enumerating objects: 231, done.                                               
> remote: Counting objects: 100% (231/231), done.         
> remote: Compressing objects: 100% (180/180), done.         
> Receiving objects:  99% (229/231), 419.74 MiB | 9.80 MiB/s                                                
> remote: Total 231 (delta 51), reused 156 (delta 40)                                                       
> Receiving objects: 100% (231/231), 419.74 MiB | 9.80 MiB/s
> Receiving objects: 100% (231/231), 441.14 MiB | 8.58 MiB/s, done.
> Resolving deltas: 100% (51/51), done.
> From https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/android-emulator
> Fetching: 100% (1/1), done in 1m11.433s
> Updating files: 100% (268/268), done.
> Checking out: 100% (1/1), done in 5.735s
> repo sync has finished successfully.
> ```
> 
> 建议您重新尝试一下

谢谢，我再试试

**Comment by charming-z** [comment]
要确定下是不是使用了正确的Ubuntu的网卡驱动，因为不正确的驱动会导致命令行下网络不稳定。
我这的现象是，wifi是连接的，打开网页浏览没问题，但是用命令行repo sync同步文件就报一样的错。然后考虑原因是网络连接不稳定导致的，在Ubuntu中的"软件更新"->"附加驱动"中，将网卡驱动从"不使用此设备"改成了第一项正确的broadcom驱动后，问题解决。
