### ISSUE TITLE
openmediavault 源不全

### ISSUE THREAD

**Issue by 315666123** [tuna/issues#1231]
补全：
deb http://packages.openmediavault.org/public/ arrakis partner
deb http://packages.openmediavault.org/public/ usul partner

另希望添加OMV6（Shaitan）：
DISTS=shaitan-proposed,shaitan
EXTRA_DISTS=shaitan-beta,shaitan-testing,shaitan

**Comment by ZenithalHourlyRate** [comment]
> deb http://packages.openmediavault.org/public/ arrakis partner
> deb http://packages.openmediavault.org/public/ usul partner

这两者已有，参见 https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/public/dists/usul/partner/
与 https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/public/dists/arrakis/partner/

> 另希望添加OMV6（Shaitan）：
> DISTS=shaitan-proposed,shaitan
> EXTRA_DISTS=shaitan-beta,shaitan-testing,shaitan

已经添加，只需等待同步
