### ISSUE TITLE
重新考虑增加 anaconda 的 nvidia channel

### ISSUE THREAD

**Issue by MoetaYuko** [tuna/issues#1232]
#### 项目名称与简介(Project Intro.)

NVIDIA CUDA

#### 上游地址与镜像方法(How to Mirror)

https://anaconda.org/nvidia

#### 其他信息(Other)
- 镜像大小(Mirror Size)：unknown
- 该镜像需求是否被之前的 issue 提出过：是，https://github.com/tuna/tunasync-scripts/pull/106
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

近期 PyTorch 切换到 nvidia 通道的 `cudatoolkit` 了（以前是 default 通道），炼丹家配环境十分受伤。之前似乎由于重分发的限制没能添加，是否有可能联系老黄家以请求 license？
```
# https://pytorch.org/get-started/locally/
NOTE: 'nvidia' channel is required for cudatoolkit 11.1
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```

**Comment by skyzh** [comment]
SJTUG 这边已经发邮件问了，可以的话应该 TUNA 也能加上（

**Comment by Harry-Chen** [comment]
由于无法取得进一步进展，暂时不考虑此镜像。

**Comment by MoetaYuko** [comment]
问题不大，他们现在又把cudatoolkit切回default通道了😅

**Comment by ZenithalHourlyRate** [comment]
另可参考 https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/

**Comment by Whisht** [comment]
pytorch 1.13 版本开始使用 nvida 镜像中的 pytorch-cuda，建议重新考虑添加该 channel

**Comment by 4-0-4-notfound** [comment]
> pytorch 1.13 版本开始使用 nvida 镜像中的 pytorch-cuda，建议重新考虑添加该 channel

复议

**Comment by ZenithalHourlyRate** [comment]
我个人的态度是，谁主张添加 nvidia channel，谁就需要解读 nvidia 的许可证或者联系 nvidia 获得分发许可。

另外，anaconda 已经通过 cloudflare 分发；同时，anaconda 仓库的大小平均一个月增加 200G，半年增加了 1.5T，一年增加了 3T，这种无限制的增长是不可持续的。

**Comment by ZenithalHourlyRate** [comment]
> 同时，anaconda 仓库的大小平均一个月增加 200G，半年增加了 1.5T，一年增加了 3T，这种无限制的增长是不可持续的。

距离上次评论（三周前）anaconda 又增长了 230G；今日 TUNA 一台后端服务器存储占用率来到了 99.8%（剩余 177G，总空间 90T）
