### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by pysio2007** [tuna/issues#1233]
Centos 7.XMysql数据库无法正常安装

**Comment by skyzh** [comment]
是否有测试指令/报错信息可以提供？

**Comment by pysio2007** [comment]
yum时报错无法链接，查看yum日志是发现获取的链接报错404.

**Comment by pysio2007** [comment]
同时此问题也在Centos8.X出现

**Comment by skyzh** [comment]
可以提供具体报错的链接和安装的指令吗？

**Comment by pysio2007** [comment]
好的，请稍等片刻。

**Comment by pysio2007** [comment]
安装指令：yum remove mysql mysql-server mysql-libs
目前直接提示找不到包。

**Comment by phy25** [comment]
请复制完整的日志。其他包能否安装呢？

**Comment by pysio2007** [comment]
q其他包可以正常安装。
