### ISSUE TITLE
AUR 镜像最后更新时间显示异常

### ISSUE THREAD

**Issue by xiaopangju** [tuna/issues#1234]
#### 发生了什么（What happened）
最后更新时间显示为0000-00-00 00:00
#### 期望的现象（What you expected to happen）
显示上次更新的时间
#### 如何重现（How to reproduce it）
访问https://mirrors.tuna.tsinghua.edu.cn/  即可
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：可能和 #1173  有关

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 7 32bit
- 浏览器（如果适用）（Browser version, if applicable）：https://paste.ubuntu.com/p/MsSxdPJjHS/
- 其他（Others）：

**Comment by phy25** [comment]
请问对于反代的镜像，您期望看到的最后更新时间是什么呢？

**Comment by xiaopangju** [comment]
> 
> 
> 请问对于反代的镜像，您期望看到的最后更新时间是什么呢？

抱歉，我忘记这是个反代镜像了
