### ISSUE TITLE
请求建立Zerotier客户端镜像

### ISSUE THREAD

**Issue by sparkcyf** [tuna/issues#1235]
#### 项目名称
`Zerotier客户端`
#### 项目简介
>ZeroTier is a smart programmable Ethernet switch for planet Earth. It allows all networked devices, VMs, containers, and applications to communicate as if they all reside in the same physical data center or cloud region.
>Zerotier客户端（或称`ZeroTierOne`）是用于zerotier组网使用的程序。

#### 镜像方法：lftp

同步时可能会有部分目录返回404/403，不过实测不影响使用。

<details><summary>返回错误的目录</summary>

```
Transferring file `RELEASES/1.1.6/dist/redhat/el/6/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.0/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.1/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.2/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.3/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.4/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.5/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.6/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.7/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.8/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6.9/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6Client/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6Server/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.1.6/dist/redhat/el/6Workstation/6'
mirror: Access failed: 403 Forbidden (6)
Transferring file `RELEASES/1.6.0/dist/sdk'
mirror: Access failed: 404 Not Found (sdk)
```
</details>

### 其他信息(Other)
- 镜像大小(Mirror Size)：`18G`
- 该镜像需求是否被之前的 issue 提出过：`否`
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：`是`
- 更换镜像的帮助文档（如需要）： https://github.com/SUSTech-CRA/ccse-mirrors-web/blob/master/site/help/zerotier.md
- 国内已有镜像：[SUSTech](https://mirrors.sustech.edu.cn/zerotier/);
- 重分发许可：根据该项目的[LICENSE](https://github.com/zerotier/ZeroTierOne/blob/master/LICENSE.txt)，ZeroTierOne的许可证基于Business Source License 1.1，相关许可证允许对软件进行重分发。

**Comment by ZenithalHourlyRate** [comment]
sustech/nju 已有镜像，基本能满足日常使用与冗余需求
