### ISSUE TITLE
Mirror request: Rocky Linux

### ISSUE THREAD

**Issue by Bambooin** [tuna/issues#1236]
#### Rocky Linux
A community-driven effort to bring you enterprise-grade, production-ready Linux.

All information can be found in release announcement:
https://forums.rockylinux.org/t/rocky-linux-8-3-rc1-available-now/2393

"Please email mirrors@rockylinux.org to express your interest."

It's already closed in #1093, but now the release is announced.

**Comment by skyzh** [comment]
Do you provide any method for synchronizing? e.g. rsync endpoint

(Note that I'm not affiliated with TUNA)

**Comment by Bambooin** [comment]
The Rocky Linux team has an email to address this question, and I'am not the TUNA team.

**Comment by Bambooin** [comment]
TUNA team have the official email(tuna.edu.cn) to contract with Rocky Linux team.

**Comment by LuoTR** [comment]
也能够在[https://wiki.rockylinux.org/contributing](https://wiki.rockylinux.org/contributing)里填写表格来取得联系

**Comment by qist** [comment]
现有mirror列表信息，含rsync：
https://mirrors.rockylinux.org/mirrormanager/mirrors/Rocky/8/x86_64

**Comment by oubayun** [comment]
参考Rsync同步文档：https://www.oubayun.com/use-rsync-and-nginx-to-create-rocky-linux-83-rc1-local-repository-mirror.html

**Comment by oubayun** [comment]
目前南京大学，上海交通大学，山东大学都有提供Rocky Linux国内更新源，希望清华大学也能够为Rocky Linux做源。
参考链接：https : //mirror.rockylinux.org/mirrormanager/mirrors
Rocky Linux中文社区：https : //rockylinux.cn/rocky-linux-update-source-summary.html

**Comment by zhangboyang** [comment]
[Rocky Linux 8.4 GA](https://rockylinux.org/news/rocky-linux-8-4-ga-release/)已经发布了
希望清华大学mirror也能跟进~~

**Comment by Harry-Chen** [comment]
目前国内的镜像已经足够使用了，在没有证据表明需要更多的镜像之前，我们不会考虑增加。
