### ISSUE TITLE
LXC streams file is outdated

### ISSUE THREAD

**Issue by KenetJervet** [tuna/issues#124]
The image dates defined in https://mirrors.tuna.tsinghua.edu.cn/lxc-images/streams/v1/images.json range between 20160917 to 20160922, while the actual images have names with more recent dates.

This results in the following error:
```bash
$ lxc launch tuna-images:centos/7 centos7_rpmwand
Creating centos7_rpmwand
error: invalid simplestreams source: got 404 looking for images/centos/7/amd64/default/20160921_02:16/lxd.tar.xz
$
```

**Comment by bigeagle** [comment]
应该已经解决了
