### ISSUE TITLE
Manjaro 清华镜像同步被repo.manjaro.org标记为out of date

### ISSUE THREAD

**Issue by 1900011604** [tuna/issues#1242]
https://repo.manjaro.org/

可以看到现在国内只能搜索到上海交大的“比你清记者跑得还要快”的源，其余国内源的Last Sync都慢于上海交大源，包括TUNA镜像站和北大镜像站，`sudo pacman-mirrors -i -c China -m rank` 也只能搜索到上海交大的镜像站。

**Comment by phy25** [comment]
Duplicate to #972

**Comment by 1900011604** [comment]
实际上中间好了一段时间，现在又是这样了

**Comment by shankerwangmiao** [comment]
应该还是原来的问题，就是我们的上游也略有延迟。

不过现在好了。

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/6825907/117405129-ab7e9e80-af3d-11eb-99c2-8ae2d6f6f7b9.png">
