### ISSUE TITLE
Rust crates.io下载出错

### ISSUE THREAD

**Issue by binbowang1987** [tuna/issues#1244]
#### 发生了什么（What happened）
我们公司内部使用Nexus Repository Manager连接到tuna镜像，在git clone crates.io.git的时候，通过wireshark看到可以下载`git/crates.io-index.git/objects/pack/pack-9f463e7b2be7859812a0e780688bafac8c31ab62.idx`，但是下载`git/crates.io-index.git/objects/pack/pack-9f463e7b2be7859812a0e780688bafac8c31ab62.pack`出错，报500错误

#### 期望的现象（What you expected to happen）
可以下载pack文件

#### 如何重现（How to reproduce it）
使用Nexus Repository Manager连接tuna镜像，然后通过Nexus Repository Manager中的url进行git clone 

#### 您的环境（Environment）
- 操作系统（OS Version）：Linux

**Comment by shankerwangmiao** [comment]
您在同一个主机上使用 git clone https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git 可以正常运行吗？

**Comment by binbowang1987** [comment]
公司电脑无法访问互联网，我在自己家用电脑上`git clone https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git `是正常运行的

**Comment by skyzh** [comment]
正常来说对于 crates.io 这个大小的 repo，git 应该不会直接下载 *.idx *.pack，而是在远程做压缩后再传输？是不是超过了 rate limit？

**Comment by binbowang1987** [comment]
怀疑可能是镜像代理的问题
