### ISSUE TITLE
bioconductor-genomeinfodbdata包镜像不存在

### ISSUE THREAD

**Issue by LinkMedicine** [tuna/issues#1245]
#### 发生了什么（What happened）
在使用conda从清华源安装 
bioconductor-genomicalignments
bioconductor-genomicranges
bioconductor-bsgenome时，出现
ERROR conda.core.link:_execute(699): An error occurred while installing package 'http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2'.

conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2
location of failed script: /THL4/home/jli02/miniconda3/envs/458/bin/.bioconductor-genomeinfodbdata-post-link.sh
通常情况下conda可以使用国外源作为替代，但部分机房无法访问外网，只能使用清华源
#### 期望的现象（What you expected to happen）
正常安装
#### 如何重现（How to reproduce it）
在仅使用清华源的情况下 使用conda install 命令安装上述软件即可出现如上错误
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
未
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
请提供您的 `.condarc` 配置。理论上 `http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2` 不应该访问这种形式的网址。

**Comment by LinkMedicine** [comment]
> 请提供您的 `.condarc` 配置。理论上 `http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2` 不应该访问这种形式的网址。
.condarc 配置如下


# by zhenggang @ 2020.12.31
show_channel_urls: true
channels:
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
  - http://conda.anaconda.org/bioconda/linux-64
  - bioconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://conda.anaconda.org/conda-forge/
report_errors: false
channel_priority: flexible

**Comment by skyzh** [comment]
bioconda 似乎出现了多次。参考现在 tuna 的最新文档重新配置应该能解决问题。

**Comment by LinkMedicine** [comment]
> bioconda 似乎出现了多次。参考现在 tuna 的最新文档重新配置应该能解决问题。

ERROR conda.core.link:_execute(699): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0'.
配置之后问题似乎仍然存在

.condarc配置如下

# by zhenggang @ 2020.12.31
show_channel_urls: true
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://conda.anaconda.org/conda-forge/
  - defaults
