### ISSUE TITLE
请愿提供Rocky Linux国内更新源

### ISSUE THREAD

**Issue by oubayun** [tuna/issues#1246]
目前南京大学、上海交通大学、山东大学都有提供Rocky Linux国内更新源，希望清华大学也能够为Rocky Linux做源。
参考链接：https://mirror.rockylinux.org/mirrormanager/mirrors
Rocky Linux 中文社区：https://rockylinux.cn/rocky-linux-update-source-summary.html

**Comment by shankerwangmiao** [comment]
dup with #1236

**Comment by scateu** [comment]
Rocky Linux好处都有啥？

-- 
Wang Kang
