### ISSUE TITLE
conda 无法找到 current_repodata.json

### ISSUE THREAD

**Issue by Amon1412** [tuna/issues#1247]
#### 在使用天池云的环境时,换源后也无法正常建立网络连接
报错信息:
-----------------------------------------
sh-4.2$ conda create -n yolov5 python=3.6
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/free/linux-64/current_repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9dfc5b82b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
-----------------------------------------
通过访问对应网址(https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json)无法获取资源
（What happened）

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 天池云的GPU环境（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
`HTTP 000 CONNECTION FAILED` 是网络连接问题。请检查您的机器是否能成功连上 TUNA 镜像站。

**Comment by skyzh** [comment]
`current_repodata.json` 不存在/无法获取不影响包的安装。conda 会自动 fallback 到 `repodata.json`。

**Comment by Amon1412** [comment]
好像是不能访问,这个是天池云实验室的环境,我小白不知道应该怎么修改,能否指点一下

**Comment by shankerwangmiao** [comment]
> 好像是不能访问,这个是天池云实验室的环境,我小白不知道应该怎么修改,能否指点一下

建议您与相关平台的管理和支持人员取得联系和帮助。

**Comment by Amon1412** [comment]
好的,我去询问一下,谢谢你们了
