### ISSUE TITLE
Rocky Linux

### ISSUE THREAD

**Issue by GuHuaijiu** [tuna/issues#1249]
Rocky Linux

Rocky Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with America's top enterprise Linux distribution now that its downstream partner has shifted direction. It is under intensive development by the community. Rocky Linux is led by Gregory Kurtzer, founder of the CentOS project. Release Candidate 1 is now available for testing. Contributors are asked to reach out using the communication options offered on this site.

https://download.rockylinux.org/pub/rocky/8.3/BaseOS/x86_64/

x86_64 BaseOS 8.1GB

**Comment by shankerwangmiao** [comment]
dup with #1236
