### ISSUE TITLE
申请 Infinality-bundle相关仓库

### ISSUE THREAD

**Issue by nkypy** [tuna/issues#125]
#### 项目名称与简介(Project Intro.)

Infinality-bundle 是一套ARCH LINUX专用的加强字体渲染的软件包. 与ARCH有着极高的相溶性.
主要包含:
freetype2-infinality-ultimate
-- freetype2 built with Infinality and additional patches.

fontconfig-infinality-ultimate
-- fontconfig optimized for use with freetype2-infinality-ultimate,including separate configuration presets for free (default), MS and custom font collections.

cairo-infinality-ultimate
-- cairo built with Ubuntu and additional patches.

还有一些字体

#### 上游地址与镜像方法(How to Mirror)
地址

```bash
[infinality-bundle]
Server = http://bohoomil.com/repo/$arch

[infinality-bundle-multilib]
Server = http://bohoomil.com/repo/multilib/$arch

[infinality-bundle-fonts]
Server = http://bohoomil.com/repo/fonts
```

同步方式 rsync

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by nkypy** [comment]
bohoomil/fontconfig-ultimate#26

**Comment by huiyiqun** [comment]
这个好像可以搞 赞

**Comment by bigeagle** [comment]
已加入同步队列

**Comment by huiyiqun** [comment]
好赞

2016-10-07 15:47 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by nkypy** [comment]
感谢
