### ISSUE TITLE
Mirror for OpenHarmony

### ISSUE THREAD

**Issue by qigangzhu** [tuna/issues#1250]
#### 项目名称与简介(Project Intro.)
OpenHarmony是开放原子开源基金会（OpenAtom Foundation）旗下开源项目，定位是一款面向全场景的开源分布式操作系统。
#### 上游地址与镜像方法(How to Mirror)
https://openharmony.gitee.com
#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- >=50G
- 该镜像需求是否被之前的 issue 提出过：
否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：
否

**Comment by jiegec** [comment]
需要镜像的是 git 仓库么？如果只是 git 仓库，并且考虑到 gitee 是国内的网站，似乎并没有镜像的必要。

**Comment by qigangzhu** [comment]
你好，考虑到OpenHarmony进高校的相关教育活动及大赛，希望在教育网内部提供一个高速连接。

**Comment by Harry-Chen** [comment]
> * 是否阅读了请求新镜像前必读（试行）：
> 否
