### ISSUE TITLE
使用 aosp-latest.tar，repo sync 失败（connect refused）

### ISSUE THREAD

**Issue by GithubZwZhou** [tuna/issues#1256]
在下载解压 `aosp-latest.tar` 并进入 aosp 目录后，执行 `repo sync` 会出现
![image](https://user-images.githubusercontent.com/72545187/119290960-2eaf2c80-bc80-11eb-99ce-871526513d4e.png)
在 `~/.bashrc` 中 添加如下字段
`export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'`
仍然会出现该错误。

**Comment by shankerwangmiao** [comment]
请自行检查您的代理和 git 配置。TUNA 的 IP 地址并非 `172.30.225.215`
