### ISSUE TITLE
能否恢复对chromiumos的镜像支持

### ISSUE THREAD

**Issue by Heroeshigh** [tuna/issues#1257]
chromiumos的镜像在一或两年前的清理中被清理掉了，能否恢复支持呢？

**Comment by phy25** [comment]
需要恢复的原因是？

Reference: #838

**Comment by skyzh** [comment]
> 需要恢复的原因是？
> 
> Reference: #838

那个 issue 已经被锁了，之后可能要在这个 issue 下面做相关讨论了（

**Comment by Heroeshigh** [comment]
一台pixelbook假死，需要重新写入Cr50来救砖chromiumos环境是必须的，所有的镜像站中只有tuna曾经有过支持；
chromeos在国内确实很小众，chromiumos镜像也确实不稳定且性价比很低，但相对于直接访问外网资源要稳定得多；

**Comment by skyzh** [comment]
之前 chromiumos 镜像的内容应该是源代码。关于 Chrome OS 本身的 image，由于包含了类似 Google Chrome 之类的私有软件，我猜想是不能重分发和镜像的。

**Comment by skyzh** [comment]
之前 ChromiumOS 镜像的内容应该是源代码，并不包含刷机所需要的编译好的 ChromiumOS image。

**Comment by Heroeshigh** [comment]
需要的是chromiumos的开发环境，image之类的可以编译

**Comment by shankerwangmiao** [comment]
您好，同步 chromiumos 的周期很长，而且这部分源代码的用户十分稀有。因此无法帮助您解决眼前需要维修设备的需求。
