### ISSUE TITLE
希望增加AlmaLinux 镜像

### ISSUE THREAD

**Issue by wangyu1314** [tuna/issues#1258]
#### 项目名称与简介(Project Intro.)
AlmaLinux 镜像
CentOS 8.x 在2021年底即将停止支持，目前有一些新发行版代替它而出现，其中AlmaLinux 发展很快，RHEL 8.4 在5月19日发布后，今天发现AlmaLinux 8.4正式版已经出来了，效率非常高，此发行版未来可期，希望能增加镜像，谢谢。
#### 上游地址与镜像方法(How to Mirror)
官网https://almalinux.org/
上游应该使用rsync进行同步的，但是未见公开信息，可能需要邮件联系获取。
#### 其他信息(Other)
- 镜像大小(Mirror Size)：估计100G
- 该镜像需求是否被之前的 issue 提出过：没有
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：已阅读。

**Comment by skyzh** [comment]
Duplicate with https://github.com/tuna/issues/issues/1186

**Comment by skyzh** [comment]
AlmaLinux 已经 255G 了。

**Comment by wangyu1314** [comment]
抱歉，重复了，感谢你们。
