### ISSUE TITLE
安装Pipeline Maven Integration时找不到文件

### ISSUE THREAD

**Issue by kdush** [tuna/issues#1259]
#### 发生了什么（What happened）
jenkins更新Pipeline Maven Integration时出错
[tuna]404 at /jenkins/plugins/pipeline-maven/3.10.0/pipeline-maven.hpi%20to%20/var/jenkins_home/plugins/pipeline-maven.jpi.tmp #1259
#### 期望的现象（What you expected to happen）
正常安装 结果404
#### 如何重现（How to reproduce it）
安装插件即可
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）docker
- 浏览器（如果适用）（Browser version, if applicable）：chrome  版本 90.0.4430.212（正式版本） (x86_64)
- 其他（Others）：jenkins 2.277.4

**Comment by shankerwangmiao** [comment]
该文件现在已经存在于镜像站上。
