### ISSUE TITLE
能否恢复 https://mirrors.bfsu.edu.cn/anaconda/AgBiome

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tuna/issues#1260]
#### 上游地址与镜像方法(How to Mirror)

https://mirrors.bfsu.edu.cn/anaconda/AgBiome
#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by skyzh** [comment]
`AgBiome` 之前有被加入过 anaconda 吗？如果有，也应该在 `anaconda/cloud/AgBiome` 才对。。。
