### ISSUE TITLE
信息错误：Homebrew-bottles 镜像使用帮助

### ISSUE THREAD

**Issue by yansh15** [tuna/issues#1262]
URL：https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/

"https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles" 应该为 "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles"。

**Comment by shankerwangmiao** [comment]
dup with https://github.com/tuna/mirror-web/issues/272
