### ISSUE TITLE
您好，conda-forge/linux-64镜像源故障了

### ISSUE THREAD

**Issue by FakeStoic** [tuna/issues#1264]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/
这两个镜像源最近一两个星期都时常故障，显示too many files to list

**Comment by skyzh** [comment]
由于文件太多不能展示内容，但文件都是可以下载的。

**Comment by skyzh** [comment]
Duplicate of https://github.com/tuna/issues/issues/1198
