### ISSUE TITLE
Mirror request: https://github.com/NixOS/nixpkgs.git

### ISSUE THREAD

**Issue by NickCao** [tuna/issues#1265]
### 项目名称
nixpkgs

### 项目简介
> Nixpkgs is a collection of over 60,000 software packages that can be installed with the Nix package manager. It also implements NixOS, a purely-functional Linux distribution.

### 上游地址与镜像方法
上游地址：https://github.com/NixOS/nixpkgs.git
镜像方法：git

### 其他信息
该镜像需求是否被之前的 issue 提出过：否
是否阅读了请求新镜像前必读（试行）：是
重分发许可：该项目的LICENSE为MIT，相关许可证允许对软件进行重分发。

**Comment by ZenithalHourlyRate** [comment]
已添加，在 https://mirrors.tuna.tsinghua.edu.cn/git/nixpkgs.git 中
