### ISSUE TITLE
F-droid 镜像无法正常使用，请检查

### ISSUE THREAD

**Issue by 1970633640** [tuna/issues#1267]
#### 发生了什么（What happened）

添加tuna的fdroid镜像后，更新存储库结束后会报错 No mirror is available. 或 Supplied fingerprint… 
#### 期望的现象（What you expected to happen）

快速同步存储库，快速下载app
#### 如何重现（How to reproduce it）

点击镜像链接添加这个镜像，然后刷新存储库
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：Android 11
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
似乎同步未见异常，还有其他人可以复现此现象吗？

**Comment by ZenithalHourlyRate** [comment]
我测试的结果是 [fdroid/repo](https://mirrors.tuna.tsinghua.edu.cn/fdroid/repo/) 可以正常使用，但 [fdroid/archive](https://mirrors.tuna.tsinghua.edu.cn/fdroid/archive) 会报 Repository was not signed correctly: supplied certificate fingerprint does not match.

**Comment by Harry-Chen** [comment]
实测目前 repo 和 archive 都没有问题，可能是当时同步或者上游问题
