### ISSUE TITLE
docker-ce速度过慢

### ISSUE THREAD

**Issue by 81pla** [tuna/issues#1268]
#### 发生了什么（What happened）
更新docker-ce时  本地网络正常的情况下报源速度太慢，无法正常更新

docker-ce-20.10.7-3.el8.x86_64.rpm: Curl error (28): Timeout was reached for https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/8/x86_64/stable/Packages/docker-ce-20.10.7-3.el8.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]

#### 期望的现象（What you expected to happen）
正常使用

#### 如何重现（How to reproduce it）
直接yum update

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：centos8
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
Maybe duplicate of https://github.com/tuna/issues/issues/1174 https://github.com/tuna/issues/issues/894 https://github.com/tuna/issues/issues/809 >

**Comment by ZenithalHourlyRate** [comment]
建议您多次重试。如果一直速度较慢，建议使用 https://mirrors.bfsu.edu.cn/
