### ISSUE TITLE
lede-project的镜像请求

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [tuna/issues#127]
#### 项目名称与简介(Project Intro.)

LEDE Project是一个面向多种无线SOHO路由器和非网络设备的基于OpenWRT的以Linux为内核的嵌入式元发行版(好吧，就是OpenWRT开发者嫌弃OpenWRT的版本线又长又臭，软件包难以在这种多分支系统下维护，然后弃坑重新开的一个新的项目。可以视为是Next Gen of OpenWRT.)

然后这个项目在全世界也没多少镜像，所以很希望TUNA能够给这个项目做一个镜像，提前感谢一下镜像维护组的各位！
#### 上游地址与镜像方法(How to Mirror)

rsync://downloads.lede-project.org/downloads
镜像方法：rsync
#### 其他信息(Other)
- 镜像大小(Mirror Size): 现在Snapshot的大小暂时只有35GB，在这之后，每个新的Release的大小有望在30-40GB之间。
- 镜像同步限制: 因为该项目的上游带宽有限，所以建议在初始同步时使用 rsync --bwlimit 8000 限制一下同步速率以减小上游服务器的压力，非常感谢！
- 理想的镜像同步频率: 建议每12-24小时同步一次
- 如果想加入官方镜像列表 ( https://www.lede-project.org/downloads.html )，欢迎联系 lede-adm@lists.lede-project.org 
- 附加信息：该项目的buildbot每次编译需要从 http://sources.lede-project.org/ 拉取代码，该代码库的编译链可以在 https://github.com/lede-project/source ( https://git.lede-project.org/?p=source.git 在GitHub上的镜像)上找到。

**Comment by scateu** [comment]
我初步看了一下，LEDE 项目貌似只有一个 Snapshot 目录？感觉里面的结构和 OpenWrt 的很相似。 所以求详细科普一下这个项目跟 OpenWrt 有啥不同？我有机会想试一下...

另外，看了镜像列表貌似德国亚琛也有一个镜像？

**Comment by bigeagle** [comment]
几个月前我试图镜像过，因为只有 snapshot 所以镜像的速度跟不上 snapshot 更新的速度，一直不成功。
等出稳定版了再说吧～

**Comment by ChizuruAmamiya** [comment]
吼啊

**Comment by Harry-Chen** [comment]
@scateu 现在Openwrt已经不更新了，LEDE是openwrt的一部分成员做的reboot项目。
嗯，同步snapshot还是挺麻烦的，我也想等稳定版啊……
那么等以后吧。

**Comment by bigeagle** [comment]
#196 中有 source tree 镜像描述。

**Comment by legendtang** [comment]
已经出现稳定分支的 image 和软件源，请考虑同步 https://downloads.lede-project.org/releases/

**Comment by shankerwangmiao** [comment]
似乎只要同步 rsync://downloads.lede-project.org/downloads 就好了？

**Comment by legendtang** [comment]
@shankerwangmiao 没错，非常容易

**Comment by shankerwangmiao** [comment]
已经开始下载数据了

**Comment by shankerwangmiao** [comment]
唔，貌似还是老问题，每次同步的 diff 过大，同步赶不上文件更新的速度。

**Comment by legendtang** [comment]
@shankerwangmiao 是因为境内 rsync 速度过慢？或许可以试试从新加坡的镜像节点 rsync 同步尝试一下？

**Comment by shankerwangmiao** [comment]
暂时先搁置吧，每次一同步，有将近一半的文件发生变化。。。。

<img width="445" alt="2017-02-06 13 32 48" src="https://cloud.githubusercontent.com/assets/6825907/22635750/d65ce5e2-ec70-11e6-9c25-208e66d75121.png">

**Comment by legendtang** [comment]
@shankerwangmiao rsync 暂时行不通的话先学 USTC 搞反代也行 https://lede.proxy.ustclug.org/

**Comment by shankerwangmiao** [comment]
唔，我们不作反向代理

**Comment by huiyiqun** [comment]
> [Ayane] 前些天已经发了stable release 了 https://lede-project.org/releases/17.01/notes-17.01.0

这个issue可以继续讨论了，只同步release？

**Comment by huiyiqun** [comment]
```~> rsync rsync://downloads.lede-project.org/downloads/releases/
drwxr-xr-x          4,096 2017/03/19 20:44:51 .
drwxr-xr-x          4,096 2017/03/19 20:44:51 17.01-SNAPSHOT
drwxr-xr-x          4,096 2017/01/31 12:05:45 17.01.0-rc1
drwxr-xr-x          4,096 2017/02/08 13:18:44 17.01.0-rc2
drwxr-xr-x          4,096 2017/02/21 21:08:53 17.01.0
drwxr-xr-x          4,096 2017/03/17 10:07:19 faillogs
drwxr-xr-x          4,096 2017/03/17 10:07:19 packages-17.01
```

**Comment by legendtang** [comment]
@huiyiqun 是的，所以可以同步上线了？

**Comment by icymind** [comment]
好几个月过去了, LEDE镜像有好消息吗?

**Comment by shankerwangmiao** [comment]
暂时冻结该请求，由于 #249

**Comment by RichardMei** [comment]
看公告，10月23已经扩容了，LEDE啥时能同步

**Comment by shankerwangmiao** [comment]
同步完成

目前的 exclude 是

```
/snapshots/
/releases/*-SNAPSHOT/
```
