### ISSUE TITLE
/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso 流量过大

### ISSUE THREAD

**Issue by Erope** [tuna/issues#1270]
下载了Tuna的日志，分析06-13的日志，原本是准备给自建镜像站做参考以便选择哪些镜像进行同步，但在做分析的时候发现有两个系统镜像流量较为异常:
* /centos/7/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso 18.3 TiB
* /raspberry-pi-os-images/raspios_arm64/images/raspios_arm64-2021-04-09/2021-03-04-raspios-buster-arm64.zip 2.81 TiB

尤其是raspberry的，最新镜像是05-07的而非04-09，主页的系统下载也指向的是05-07的镜像; 而CentOS的系统iso貌似占了镜像站一半的流量，建议考虑采用和USTC一样的JS置入cookies方式简单拦截。
![image](https://user-images.githubusercontent.com/44471469/121851481-c3a5c280-cd20-11eb-81d6-230dcba3cb1b.png)
![image](https://user-images.githubusercontent.com/44471469/121851564-dfa96400-cd20-11eb-9a60-f1f92fa8e602.png)

**Comment by skyzh** [comment]
之前好像有通过 UA 来限制，不知道这些请求的 UA 有没有什么特征？

**Comment by taoky** [comment]
> 之前好像有通过 UA 来限制，不知道这些请求的 UA 有没有什么特征？

我猜是 `Go-http-client/1.1`。可以传一下 goaccess 生成的 HTML report 一起看一下。

**Comment by Erope** [comment]
GoAccess自带的UA列表不太全，全是Unknown，我重新编辑一下生成吧，不过CentOS的Go-http-client/2.0

**Comment by skyzh** [comment]
> GoAccess自带的UA列表不太全，全是Unknown，我重新编辑一下生成吧，不过CentOS的几乎全是Go-http-client/2.0

从 1.1 升级到 2.0 了 🤣🤣

**Comment by Erope** [comment]
弄好了，因为无法直接上传html就打了个压缩包
[tuna0613.zip](https://github.com/tuna/issues/files/6647276/tuna0613.zip)

**Comment by skyzh** [comment]
快速扫了一眼，都和限制过的 UA 多多少少有点关联（

<img width="690" alt="image" src="https://user-images.githubusercontent.com/4198311/121876844-8f3fff80-cd3c-11eb-95ad-5aab4b1786f8.png">

**Comment by Erope** [comment]
> 快速扫了一眼，都和之前限制过的 UA 多多少少有点关联（
> 
> <img alt="image" width="690" src="https://user-images.githubusercontent.com/4198311/121876844-8f3fff80-cd3c-11eb-95ad-5aab4b1786f8.png">

CentOS的流量异常的很，看起来甚至像是刷的，为什么要这么做呢

**Comment by shankerwangmiao** [comment]
您好，感谢您的反馈。经查，发现确有这样的现象。类似的请求集中在山东联通的若干 IP 地址段内，目前已经封禁。

**Comment by Erope** [comment]
> 您好，感谢您的反馈。经查，发现确有这样的现象。类似的请求集中在山东联通的若干 IP 地址段内，目前已经封禁。

好的 很高兴能帮上忙 看到夜间的流量图明显下降了 也祝tuna越办越好
