### ISSUE TITLE
【BFSU Mirror】使用 MacPorts 镜像，如何从 BFSU 处下载 distfiles?

### ISSUE THREAD

**Issue by zhiyuanzhai** [tuna/issues#1271]
最近因为 TUNA 流量拥堵问题，考虑改用 BFSU 镜像。但是最重要的 distfiles （也就是各软件包的源码，下载后编译）的下载仍然避不开 TUNA 站。

根据官方文档的说法[1]，MacPorts 会自动选择已知的 distfiles 镜像，而 distfiles 镜像在国内对应的官方域名
```
https://pek.cn.distfiles.macports.org/macports/distfiles/
```
应该是对接到 TUNA 而不是 BFSU. 但是从官方的文档中，我没有找到设置 distfiles 下载镜像（或者优先镜像）的接口。不知这里是存在一个文档未说明的「隐藏接口」，还是说这里确实无法设置？如果是后者，那么是否有可能像 TUNA 本站一样为 BFSU 的 MacPorts 镜像也申请一个官方的镜像域名？

参考：
[1] Mirrors - MacPorts : https://trac.macports.org/wiki/Mirrors

**Comment by shankerwangmiao** [comment]
> 最近因为 TUNA 流量拥堵问题，考虑改用 BFSU 镜像。但是最重要的 distfiles （也就是各软件包的源码，下载后编译）的下载仍然避不开 TUNA 站。
近期 TUNA 镜像站的流量较为平稳，大约为 5Gbps 左右，目前未见显著拥堵情况，在北京联通下载速度可达 400Mb/s 。
> 
> 根据官方文档的说法[1]，MacPorts 会自动选择已知的 distfiles 镜像，而 distfiles 镜像在国内对应的官方域名
> 
> ```
> https://pek.cn.distfiles.macports.org/macports/distfiles/
> ```
> 
> 应该是对接到 TUNA 而不是 BFSU. 但是从官方的文档中，我没有找到设置 distfiles 下载镜像（或者优先镜像）的接口。不知这里是存在一个文档未说明的「隐藏接口」，还是说这里确实无法设置？如果是后者，那么是否有可能像 TUNA 本站一样为 BFSU 的 MacPorts 镜像也申请一个官方的镜像域名？

确实 distfile 没有办法设置下载的代替路径。但是由于非技术原因，我们不能为 bfsu 增加这样的域名，并且根据 MacPorts 的文档，BFSU 也位于北京，但是 pek.cn 的域名已经指向了 TUNA。

> 
> 参考：
> [1] Mirrors - MacPorts : https://trac.macports.org/wiki/Mirrors
