### ISSUE TITLE
移动网络 多次repo sync 出现的 同一个错误

### ISSUE THREAD

**Issue by bAdOoWindy** [tuna/issues#1272]
#### 发生了什么（What happened）

```
Cannot fetch platform/prebuilts/misc from http://mirrors4.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/misc
```

#### 期望的现象（What you expected to happen）
期望顺利完成 `repo sync`
#### 如何重现（How to reproduce it）
使用移动网络(不知道是不是问题起因) win10 wsl2 UBUNTU 20.4 LTS
repo 代码 `repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b lineage-18.1`
然后 `vi .repo/manifests/default.xml` 修改 将 `https://android.googlesource.com/` 全部使用 `https://mirrors4.tuna.tsinghua.edu.cn/git/AOSP/` 代替
之后使用

``` bash
#!/bin/bash  
echo "======start repo sync======"  
repo sync -c --no-clone-bundle -j2 -f
while [ $? = 1 ]; do  
echo "======sync failed, re-sync again======"  
sleep 1  
repo sync -c --no-clone-bundle -j2 -f
done
```

这个脚本进行同步 结果多次出现上面的报错

```
Cannot fetch platform/prebuilts/misc from http://mirrors4.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/misc
```
一整行就是这样 没有报错代码
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
没有搜索到
#### 您的环境（Environment）
- 操作系统（OS Version）：win10 21h1
- 浏览器（如果适用）（Browser version, if applicable）：不相关
- 其他（Others）：无

**Comment by shankerwangmiao** [comment]
为何您在代替的时候用的是 https 的链接，但是报错里却是 http？以及出现报错信息后，repo sync 是否终止运行？

**Comment by bAdOoWindy** [comment]
> 
> 
> 为何您在代替的时候用的是 https 的链接，但是报错里却是 http？以及出现报错信息后，repo sync 是否终止运行？

Fetching:  0% (3/856) LineageOS/android_external_ant-wireless_antradio-libraryerror: Cannot fetch platform/prebuilts/misc from https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc
error: Cannot fetch platform/prebuilts/misc from https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc
Fetching: 99% (855/856) LineageOS/android_vendor_qcom_opensource_wfd-commonsyserror: Cannot fetch platform/prebuilts/misc from https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc
HTTPS也一样 

我用了-f 所以出现报错后 repo sync没有终止

**Comment by bAdOoWindy** [comment]
奇怪的是去到对应目录

git clone却可以完成

**Comment by bAdOoWindy** [comment]
git clone 搭了梯 在骨骼源

**Comment by shankerwangmiao** [comment]
直接 clone https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc 有何现象？能正常结束吗？

**Comment by bAdOoWindy** [comment]
> 
> 
> 直接 clone https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc 有何现象？能正常结束吗？

*:/mnt/e/ losbuild/ prebuilts $ git clone https://mirrors.bfsu.edu.cn/git/AOSP/platform/prebuilts/misc
Cloning into 'misc'...
remote: Enumerating objects: 11755, done.
remote: Total 11755 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (11755/11755), 1.86 GiB | 14.65 MiB/s, done.
Resolving deltas: 100% (4893/4893), done.
Updating files: 100% (600/600), done.

目录的空格是方便识别,实际去掉
就很奇怪 clone 可以完成 sync不行

**Comment by shankerwangmiao** [comment]
我未能复现所述的故障，`repo sync` 可以正常运行。您可以启用调试选项再试一次：

``` bash
env REPO_TRACE=1 repo sync -c --no-clone-bundle -j2 -v
```

其中，`REPO_TRACE=1` 表示打印执行的 git 命令内容，`-v` 表示输出 git 命令的正常输出。

**Comment by bAdOoWindy** [comment]
谢谢参数 不知道怎么的一次完成repo sync

repo sync -c --no-clone-bundle -j1 -f --force-sync
放上我用的sync参数

**Comment by bAdOoWindy** [comment]
结果而言,你可以尝试向你的移动宽带维修师傅吐槽 发http://mirrors4.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/misc给他说是清华镜像的AOSP源码
