### ISSUE TITLE
linuxbrew-bottles version needed

### ISSUE THREAD

**Issue by jianzhou520** [tuna/issues#1273]
#### 项目名称与简介(Project Intro.)
linuxbrew-bottles
https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/libxml2-2.9.12.x86_64_linux.bottle.tar.gz 404，目前只镜像缓存了2.9.10的几个版本，请更新

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by shankerwangmiao** [comment]
dup with #1224
