### ISSUE TITLE
[镜像请求] Homebrew Command Not Found

### ISSUE THREAD

**Issue by aaronliu0130** [tuna/issues#1274]
#### 项目名称与简介(Project Intro.)
homebrew command not found, 当命令找不着时会搜寻homebrew formulae有没有这个命令，如有则提示用户安装
#### 上游地址与镜像方法(How to Mirror)
上游: https://github.com/Homebrew/homebrew-command-not-found.git
同步方式: git mirror
#### 其他信息(Other)
- 镜像大小(Mirror Size)：5508281B(5.6MB)
- 该镜像需求是否被之前的 issue 提出过：0
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：1

**Comment by Harry-Chen** [comment]
已经上线： <https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-command-not-found.git>，帮助已经更新。
