### ISSUE TITLE
Pypi镜像同步停留在了两天前，木有及时更新~

### ISSUE THREAD

**Issue by GT-ZhangAcer** [tuna/issues#1278]
#### 发生了什么（What happened）
Hi，清华源维护的同学，最近我在Pypi上更新了自己的Python库，但部分开发者表示在清华源中无法下载该包。  
刚刚我发现咱们清华源在Pypi镜像上更新貌似出现了问题，之前是可以几分钟一次，但现在貌似镜像还是1天前的。
![图片](https://user-images.githubusercontent.com/46156734/123279216-3b9e9480-d53a-11eb-90bc-4be6d1cb86ae.png)

#### 期望的现象（What you expected to happen）
希望Pypi镜像可以恢复更新啦~
#### 如何重现（How to reproduce it）
[https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status)
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
否
#### 您的环境（Environment）
- 操作系统（OS Version）：Win10
- 浏览器（如果适用）（Browser version, if applicable）：FireFox
- 其他（Others）：None

**Comment by shankerwangmiao** [comment]
您好，感谢反馈。目前正在追赶进度，应该还需要若干小时。

**Comment by shankerwangmiao** [comment]
> 您好，感谢反馈。目前正在追赶进度，应该还需要若干小时。

进度已经追上了。

**Comment by GT-ZhangAcer** [comment]
感谢感谢~
