### ISSUE TITLE
SteamOS 镜像

### ISSUE THREAD

**Issue by wbsdty331** [tuna/issues#128]
#### 项目名称与简介(Project Intro.)
SteamOS 是 Valve 的一个基于 Debian  的Linux发行版，预装了Steam客户端和各种硬件驱动，目的是提升大屏幕的游戏体验

~~主要原因是USTC的源在我们这里速度太慢（~~
#### 上游地址与镜像方法(How to Mirror)
http://repo.steampowered.com/

此为官方 APT 源，直接 lftp 或者其他办法拉下来即可
#### 其他信息(Other)
- 镜像大小(Mirror Size): 100G 左右

**Comment by bigeagle** [comment]
开始同步了

**Comment by wbsdty331** [comment]
我继续写个说明吧

**Comment by bigeagle** [comment]
现在已经可以用了，虽然同步失败（有目录 403，不影响）

**Comment by danyi** [comment]
我发现有缺失，目前电脑要安装steamos要用他的holoiso发行版，而且后面steamos换archlinux了，里面的2个源分别是http://dl.thevakhovske.pw 
https://steamdeck-packages.steamos.cloud/archlinux-mirror/
目前正常的archlinux没有holo这个文件夹
