### ISSUE TITLE
希望增加 composer 源

### ISSUE THREAD

**Issue by yuwenlong** [tuna/issues#1280]
#### 项目名称与简介(Project Intro.)
php composer 包管理

#### 上游地址与镜像方法(How to Mirror)
https://packagist.org/explore/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by skyzh** [comment]
我怎么记得之前是有的 https://github.com/tuna/issues/issues/1213 ……应该是这两个月刚移除的

**Comment by skyzh** [comment]
另外 packagist 里面只有元数据，新版 API 需要能提供动态内容的后端，镜像站能提供的 API 估计快 deprecate 了。

**Comment by shankerwangmiao** [comment]
由于 packagist 里面并不存放实际要下载的数据，再加上使用的用户非常少，因此进行镜像的意义不大。

**Comment by season886** [comment]
用PHP的都在用composer，不可能用户少的，望采纳

**Comment by Harry-Chen** [comment]
> 用PHP的都在用composer，不可能用户少的，望采纳

镜像站不具备提供动态内容的能力，因此我们无法提供镜像。
