### ISSUE TITLE
希望增加 Rocky Linux 源

### ISSUE THREAD

**Issue by yuwenlong** [tuna/issues#1281]
#### 项目名称与简介(Project Intro.)
Rocky 是 Centos 的替代品
具体介绍：https://www.oschina.net/p/rocky-linux

#### 上游地址与镜像方法(How to Mirror)
https://rockylinux.org/download/

可以加入贡献者社区，提供镜像
https://chat.rockylinux.org/

As you download and use Rocky Linux, the Rocky Enterprise Software Foundation invites you to be a part of the community as a contributor . There are many ways to contribute to the project, from documentation, QA, and testing to coding changes for SIGs, providing mirroring or hosting, and helping other users.

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by yuwenlong** [comment]
这是目前的第三方源列表
https://mirror.rockylinux.org/mirrormanager/mirrors

**Comment by skyzh** [comment]
Hi，请不要重复提交镜像源请求。

**Comment by Harry-Chen** [comment]
模版最下方的三行信息不是可选的。
