### ISSUE TITLE
conda-forge/linux-64 故障

### ISSUE THREAD

**Issue by szh-bash** [tuna/issues#1283]
#### 发生了什么（What happened）
命令：conda env create -f environment/psp_env.yaml

结果：
    
    Collecting package metadata (repodata.json): failed
    
    CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json>
    Elapsed: -
    
    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64'

其他：无法 ping 通 conda-forge/linux-64

#### 期望的现象（What you expected to happen）
正常安装 anaconda 环境，ping 通 conda-forge/linux-64

#### 如何重现（How to reproduce it）
ping https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：是，但似乎没有被认为是 BUG

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 16, windows10
- 浏览器（如果适用）（Browser version, if applicable）：latest google chrome
- 其他（Others）：~

**Comment by skyzh** [comment]
Duplicate of https://github.com/tuna/issues/issues/1266

**Comment by skyzh** [comment]
ping 的参数应该是一个 IP 或域名。`ping https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64` 当然会失败。

**Comment by shankerwangmiao** [comment]
000 CONNECTION FAILED 表示你到 TUNA 的网络出现了问题，建议重试。如果重试还不能解决的话，可以考虑该用 mirrors.bfsu.edu.cn .
