### ISSUE TITLE
[tuna]404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by xiaole51** [tuna/issues#1285]
openwrt/snapshots 出现404
https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/

目前许多固件用snapshots目录下的文件. 没有它镜像无意义.

**Comment by ZenithalHourlyRate** [comment]
参考 #619

可以参考 https://s.mirrorz.org/openwrt/snapshots/targets/zynq/generic/sha256sums
