### ISSUE TITLE
https://adaptivecomputing.com/resources/downloads/torque/

### ISSUE THREAD

**Issue by zhuwoxingfu** [tuna/issues#1286]
#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by skyzh** [comment]
Hi, 你提供的网页无法打开。希望你可以填写模版中的内容，以供镜像源管理员决定是否接受。
