### ISSUE TITLE
请求补充proxmox  bullseye源

### ISSUE THREAD

**Issue by nevinen** [tuna/issues#1287]
#### 项目名称与简介(Project Intro.)
proxmox，目前已经有了
#### 上游地址与镜像方法(How to Mirror)
基于现有内容补充同步proxmox 7的apt源，即；http://download.proxmox.com/debian/dists/bullseye
#### 其他信息(Other)
- 镜像大小(Mirror Size)：10G
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by shankerwangmiao** [comment]
已经补充同步。
