### ISSUE TITLE
apache镜像下载速度逐渐降为0kb

### ISSUE THREAD

**Issue by willzhang** [tuna/issues#1289]
#### 发生了什么（What happened）
下载这个包还没下载完速度逐渐降为0
https://mirrors.tuna.tsinghua.edu.cn/apache/flink/flink-1.13.1/flink-1.13.1-bin-scala_2.12.tgz

#### 期望的现象（What you expected to happen）
下载完成
#### 如何重现（How to reproduce it）
打开浏览器下载
https://mirrors.tuna.tsinghua.edu.cn/apache/flink/flink-1.13.1/flink-1.13.1-bin-scala_2.12.tgz
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：chrome
- 其他（Others）：移动网络

**Comment by shankerwangmiao** [comment]
这可能是由于您到 TUNA 的网络带宽不足所致。您可以重试几次，或者尝试使用 https://mirrors.bfsu.edu.cn/ 作为代替。
