### ISSUE TITLE
建议增加KDE NEON镜像

### ISSUE THREAD

**Issue by ytfh44** [tuna/issues#1291]
#### 项目名称与简介(Project Intro.)
KDE NEON，是KDE官方的一个操作系统，用于使KDE用户测试KDE组件的最新版
基于UBUNTU-LTS开发

#### 上游地址与镜像方法(How to Mirror)
用户稳定版 http://archive.neon.kde.org/user/
测试版 http://archive.neon.kde.org/testing/
不稳定版 http://archive.neon.kde.org/unstable/
开发者稳定版 http://archive.neon.kde.org/dev/

镜像方式 https://packages.debian.org/stable/apt-mirror （或其他APT镜像工具）

#### 其他信息(Other)
- 镜像大小(Mirror Size)：每个版本约 几十GB
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是
- 如果太多了，就只同步user

**Comment by skyzh** [comment]
Duplicate of https://github.com/tuna/issues/issues/562

**Comment by shankerwangmiao** [comment]
您好，您可以使用 https://mirrors.bfsu.edu.cn/ 作为代替。
