### ISSUE TITLE
建议加入tor project

### ISSUE THREAD

**Issue by ytfh44** [tuna/issues#1293]
#### 项目名称与简介(Project Intro.)
Tor project,曾经是电子前哨基金会的一个顶级项目，起源于美国海军的洋葱路由计划，是一个仍具有实验性的匿名解决方案。
#### 上游地址与镜像方法(How to Mirror)
官方源在国内无法访问
可通过法国镜像中转
rsync://mirrors.standaloneinstaller.com/torproject/
#### 其他信息(Other)
- 镜像大小(Mirror Size)：网页部分约100MB，存储库部分约40GB
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by Harry-Chen** [comment]
出于合规性原因，我们无法提供这一镜像。
