### ISSUE TITLE
npm.tuna 被重定向，npm失败

### ISSUE THREAD

**Issue by gdh1995** [tuna/issues#13]
按http://mirrors.tuna.tsinghua.edu.cn/help/#npm 的教程设的`npmrc`
> `registry=https://npm.tuna.tsinghua.edu.cn`

然后`npm install path`报错
* npm请求https://npm.tuna.tsinghua.edu.cn/path
* nginx返回502
* 手动试了`npm install path --registry https://mirrors.tuna.tsinghua.edu.cn/npm/storage/`，仍然是json解析失败。

**Comment by bigeagle** [comment]
现在应该好了，你试一下？

**Comment by gdh1995** [comment]
好了

**Comment by gdh1995** [comment]
又错了，
https://npm.tuna.tsinghua.edu.cn/requirejs/ 502

**Comment by bigeagle** [comment]
现在好了。

--
Justin Wong
 
 
On Sun, Jan 10, 2016, at 09:26, Dahan Gong wrote:
> Reopened #13[1].


> —
> Reply to this email directly or view it on GitHub[2]. 


>  


Links:

  1. https://github.com/tuna/issues/issues/13
  2. https://github.com/tuna/issues/issues/13#event-510340942

**Comment by gdh1995** [comment]
谢谢 :-D

我等两天再试试，可以的话再Close。

**Comment by gdh1995** [comment]
仍然正常。

谢谢！

**Comment by gdh1995** [comment]
最近这个月npm的镜像应该是又挂了。http和https都报502

**Comment by bigeagle** [comment]
对，因为没有能力维护，挂了一个月都没人发现，说明也没人用，已经停掉几个月了。

**Comment by gdh1995** [comment]
好吧，不过我想说我8月发现了这个问题，只是懒得报告。。。那我就转淘宝吧。

辛苦了。

**Comment by bigeagle** [comment]
恩，我们原先也是从淘宝同步的。
