### ISSUE TITLE
求同步Homebrew-bottles

### ISSUE THREAD

**Issue by roooooooot** [tuna/issues#130]
9-20后就未更新过(paused字样溶于背景中Orz)
![2016-10-04 1 43 09](https://cloud.githubusercontent.com/assets/8992956/19063815/8c05ed62-8a38-11e6-83d6-e2d7e474b4df.png)

**Comment by shankerwangmiao** [comment]
这是因为上游的 USTC 挂了。。。。

不过这个前端是咋回事？ @bigeagle 快来修！

**Comment by roooooooot** [comment]
USTC现在应该活了。。

**Comment by bigeagle** [comment]
![deepinscreenshot20161004142320](https://cloud.githubusercontent.com/assets/548512/19064268/d6e0e296-8a3e-11e6-9d1c-7ac99d587225.png)
上游并没有活过来哦……
