### ISSUE TITLE
对llvm预构建二进制的请求

### ISSUE THREAD

**Issue by ytfh44** [tuna/issues#1301]
#### 项目名称与简介(Project Intro.)
LLVM binary
是llvm官方的预构建二进制包
#### 上游地址与镜像方法(How to Mirror)
https://github.com/llvm/llvm-project/releases/
镜像方法：和其他GitHub-release方法一样
#### 其他信息(Other)
- 镜像大小(Mirror Size)：每个版本约5GB
- 该镜像需求是否被之前的 issue 提出过：是的
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是的

**Comment by skyzh** [comment]
似乎已经有了。https://mirrors.tuna.tsinghua.edu.cn/github-release/llvm/llvm-project/

**Comment by ytfh44** [comment]
但是只有12.0.1，而GitHub release已经到了13，请考虑使用脚本自动轮询拉取所有需要镜像的GitHub release

**Comment by skyzh** [comment]
> 但是只有12.0.1，而GitHub release已经到了13，请考虑使用脚本自动轮询拉取所有需要镜像的GitHub release

https://github.com/llvm/llvm-project/releases/ 上发布的最新版就是 12.0.1

**Comment by ytfh44** [comment]
sorry。。。

**Comment by Harry-Chen** [comment]
> 但是只有12.0.1，而GitHub release已经到了13，请考虑使用脚本自动轮询拉取所有需要镜像的GitHub release

https://github.com/tuna/tunasync-scripts/blob/master/github-release.py 请考虑阅读代码。
