### ISSUE TITLE
mongodb 5.0 镜像请求

### ISSUE THREAD

**Issue by lyzenghq** [tuna/issues#1303]
#### 项目名称与简介(Project Intro.)

mongodb

tuna 中的 mongodb 仓库缺少 5.0 版本。

#### 上游地址与镜像方法(How to Mirror)

yum 仓库:
https://repo.mongodb.org/yum/

5.0 的完整 url：
https://repo.mongodb.org/yum/redhat/7/mongodb-org/5.0/
https://repo.mongodb.org/yum/redhat/7Server/mongodb-org/5.0/
https://repo.mongodb.org/yum/redhat/8/mongodb-org/5.0/
https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/5.0/

apt 仓库：
https://repo.mongodb.org/apt/

5.0 的完整 url（以 ubuntu 20.04 为例）：
https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by skyzh** [comment]
看起来是因为脚本里没有同步这个版本 https://github.com/tuna/tunasync-scripts/blob/master/mongodb.sh

**Comment by lyzenghq** [comment]
> 看起来是因为脚本里没有同步这个版本 https://github.com/tuna/tunasync-scripts/blob/master/mongodb.sh

现在脚本更新了，但仓库中依然没有发现 5.0 ：https://mirror.tuna.tsinghua.edu.cn/mongodb/yum/

**Comment by jiegec** [comment]
已经解决。
