### ISSUE TITLE
我在安装anaconda pytorch时候遇到了问题

### ISSUE THREAD

**Issue by XuantingGu** [tuna/issues#1305]
在下载cuda11.1版本时候在下载包的过程中，第二个1G多的那个包的时候卡住不动

**Comment by skyzh** [comment]
Hi, 这有可能是您的网络链路问题。

https://github.com/tuna/issues/issues/1144#issuecomment-767353135

> 您好，您反映的问题可能是您到 TUNA 的链路问题，也可能是 TUNA 的服务存在问题。我们有计划在近期对于负载均衡方式进行调整，以尝试缓解后者。在此期间，您可以选择使用 BFSU、OpenTUNA 或其他兄弟镜像站。

**Comment by XuantingGu** [comment]
谢谢，我会尝试一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 中午12:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuna/issues] 我在安装anaconda pytorch时候遇到了问题 (#1305)





 
Hi, 这有可能是您的网络链路问题。
 
#1144 (comment)
  
您好，您反映的问题可能是您到 TUNA 的链路问题，也可能是 TUNA 的服务存在问题。我们有计划在近期对于负载均衡方式进行调整，以尝试缓解后者。在此期间，您可以选择使用 BFSU、OpenTUNA 或其他兄弟镜像站。

**Comment by skyzh** [comment]
另外 CUDA 11.1 仅在 anaconda/nvidia 频道提供。由于授权原因，目前国内应该没有镜像。

**Comment by XuantingGu** [comment]
请问那是否可以使用10的版本进行替代呢？还是说我只能选择none这一项呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 中午12:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuna/issues] 我在安装anaconda pytorch时候遇到了问题 (#1305)





 
另外 CUDA 11.1 仅在 anaconda/nvidia 频道提供。由于授权原因，目前国内应该没有镜像。

**Comment by skyzh** [comment]
安装选项去掉 `-c nvidia` 即可。
