### ISSUE TITLE
Garuda Linux 新版本不可用

### ISSUE THREAD

**Issue by AnErW** [tuna/issues#1306]
#### 发生了什么（What happened）
Garuda Linux 在osdn上的版本长期未更新，似乎官方已经迁移到了其他的发布平台(Fosshost)。
#### 期望的现象（What you expected to happen）
获取最新版本的Garuda Linux镜像

#### 如何重现（How to reproduce it）
可直接前往Garuda Linux的官方网站的下载页面查询版本。

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：Garuda Linux x86_64 (210729)
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
可以提供一下具体的上游和同步方式吗？

**Comment by AnErW** [comment]
似乎官方并没有给出上游和同步方式，这个issues先关了吧

**Comment by zebulon2020** [comment]
[https://mirrors.fossho.st/garuda/iso/garuda/](https://mirrors.fossho.st/garuda/iso/garuda/)或者[https://iso.builds.garudalinux.org/iso/garuda/](https://iso.builds.garudalinux.org/iso/garuda/)可以作上游地址吗？
