### ISSUE TITLE
[tuna]404 at /ubuntu-ports/dists/bionic/restricted/binary-amd64/Packages

### ISSUE THREAD

**Issue by Yiling7299** [tuna/issues#1307]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by taoky** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu-ports/

(amd64 != arm64)
