### ISSUE TITLE
镜像失效了

### ISSUE THREAD

**Issue by mp55** [tuna/issues#1308]
#### 发生了什么（What happened）
镜像失效了，求恢复 https://mirrors.tuna.tsinghua.edu.cn/repoforge/RPM-GPG-KEY.dag.txt
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
根据 repoforge 官方的说明，它已经过时并不再更新，因此被移除了。它是在 3 月 12 日被移除的。
