### ISSUE TITLE
Bintray shuts down

### ISSUE THREAD

**Issue by Kevincible** [tuna/issues#1309]
#### 发生了什么（What happened）
Homebrew源请求二进制bottle时仍然重定向到Bintray
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://github.com/Homebrew/discussions/discussions/691

#### 期望的现象（What you expected to happen）
参考[Homebrew](https://github.com/Homebrew/brew/pull/11070)，应从Bintray迁移

#### 如何重现（How to reproduce it）
```bash
$ curl -Ls -o /dev/null -w %{url_effective} https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/six-1.16.0_1.big_sur.bottle.tar.gz
https://homebrew.bintray.com/six-1.16.0_1.big_sur.bottle.tar.gz
$ curl https://homebrew.bintray.com/six-1.16.0_1.big_sur.bottle.tar.gz
Forbidden!
```

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
#1243
#1229

#### 您的环境（Environment）
- 操作系统（OS Version）：macOS Big sur 11.4
- 浏览器（如果适用）（Browser version, if applicable）：N/A
- 其他（Others）：
```bash
$ brew -v
Homebrew 3.2.6-41-g239bd3c
Homebrew/homebrew-core (git revision 5a7f9c3ac1; last commit 2021-08-09)

**Comment by skyzh** [comment]
Hi, 国内的各大镜像站正在和 Homebrew 上游沟通。等上游 API 稳定后将重新开始镜像。

https://github.com/Homebrew/discussions/discussions/1906

**Comment by Kevincible** [comment]
Thanks for the follow up!
