### ISSUE TITLE
NPM挂了

### ISSUE THREAD

**Issue by scateu** [tuna/issues#131]
502 Bad Gateway
nginx/1.10.1

https://cnpm.tuna.tsinghua.edu.cn/

**Comment by scateu** [comment]
而且貌似在首页也没有这个条目了？

**Comment by huiyiqun** [comment]
下线了 bug多且无人维护 首页上一直没有

Wang Kang <notifications@github.com>于2016年10月8日周六 上午9:18写道：

**Comment by STayinloves** [comment]
建议撤去help里的npm或设置下线提醒
