### ISSUE TITLE
[镜像请求] git-for-windows msys2 源

### ISSUE THREAD

**Issue by Berrysoft** [tuna/issues#1310]
#### 项目名称与简介(Project Intro.)
名称（建议）：git-for-windows-msys2

这是git-for-windows开发者维护的针对msys2的软件源。git-for-windows本来是基于修改版的msys2开发并分发，该源提供了在原版msys2上安装与开发git-for-windows的可能。

#### 上游地址与镜像方法(How to Mirror)
* https://wingit.blob.core.windows.net/x86-64

* https://wingit.blob.core.windows.net/i686

镜像方法应该与 msys2 相同，还有待进一步调查。

#### 其他信息(Other)
- 镜像大小(Mirror Size)：不清楚
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by Berrysoft** [comment]
x64的数据库文件：https://wingit.blob.core.windows.net/x86-64/git-for-windows.db
x86的数据库文件：https://wingit.blob.core.windows.net/i686/git-for-windows-mingw32.db

**Comment by skyzh** [comment]
> 镜像方法应该与 msys2 相同，还有待进一步调查。

msys2 是提供 rsync 的……这个软件源提供 rsync 吗？

**Comment by taoky** [comment]
> > 镜像方法应该与 msys2 相同，还有待进一步调查。
> 
> msys2 是提供 rsync 的……这个软件源提供 rsync 吗？

Azure blob storage 应该能用 [`rclone`](https://rclone.org/azureblob/) 同步。

**Comment by Berrysoft** [comment]
同步方法：使用巨硬提供的 [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

```
$ azcopy copy --recursive https://wingit.blob.core.windows.net/x86-64/ .
$ azcopy copy --recursive https://wingit.blob.core.windows.net/i686/ .
```

**Comment by ZenithalHourlyRate** [comment]
> 同步方法：使用巨硬提供的 [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)

看起来并没有相关发行版打包该工具，需要自行构建相关软件并打包

注：不能直接下载 binary，因为
```
$ file azcopy
azcopy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=CR2L9CiWBbMX_gDe_3aQ/ZwCp_KnPaQENPYAUNm_X/q263ahmZS3z2QZO0EiLb/A3f9HRnJDeYu7YOqSK48, not stripped
```
而我们有 ARM 机器

大小估计为 6~7G
```
$ ./azcopy sync --recursive https://wingit.blob.core.windows.net/x86-64/ .

$ du -hd1
3.2G    .
```

**Comment by Berrysoft** [comment]
仓库在这里：[Azure/azure-storage-azcopy](https://github.com/Azure/azure-storage-azcopy)，是 go 写的，在 ARM 上也没问题。如果空间不够大的话，只同步 x86_64 的部分也行。

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/tunasync-scripts/tree/git-for-windows-msys2 相关脚本正在开发中，不过由于一些原因（go build），而我的机器都在国内，无法测试，需要相关测试的支持

**Comment by abcfy2** [comment]
这个有后续吗？wingit官方msys2仓库国内访问经常超时，希望可以镜像

**Comment by Berrysoft** [comment]
我已经在自己编译了🤣不过能有这个镜像源更好

**Comment by Berrysoft** [comment]
我自己的打包： https://github.com/Berrysoft/msys-git-for-windows/

不再请求wingit的源
