### ISSUE TITLE
tuna.moe 建立安全连接失败 PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by TSaltedfishKing** [tuna/issues#1312]
#### 发生了什么（What happened）
如图
![图片](https://user-images.githubusercontent.com/60768370/129475318-104ccfc4-3d64-4f57-96d5-aa519d68e752.png)
#### 期望的现象（What you expected to happen）
![图片](https://user-images.githubusercontent.com/60768370/129475347-73992a73-2cef-4aae-9453-3f732899bfaa.png)
#### 如何重现（How to reproduce it）
在Firefox中打开一个隐私标签页(并不是隐私标签页的问题)
然后在地址栏输入https://tuna.moe/
![图片](https://user-images.githubusercontent.com/60768370/129475455-035e1cda-e556-4b46-a965-4f85d6e607e8.png)
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
并未
#### 您的环境（Environment）
- 操作系统（OS Version）：Microsoft Windows 版本 20H2 (操作系统内部版本 19042.985)
- 浏览器（如果适用）（Browser version, if applicable）：Firefox Browser DEVELOPER 92.0b3(64位)
- 其他（Others）：

**Comment by skyzh** [comment]
北京联通不能复现。可能是暂时性的网络问题。

**Comment by Harry-Chen** [comment]
该网站搭建在 GitHub Pages 上，TUNA 无法诊断这一问题
