### ISSUE TITLE
[镜像请求] 新增 Eclipse Temurin (Adoptium) 镜像

### ISSUE THREAD

**Issue by RealHeart** [tuna/issues#1313]
#### 项目名称与简介(Project Intro.)

Eclipse Temurin (Adoptium)
AdoptOpenJDK 宣布在3月就宣布过度到Adoptium [详细](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/)
目前从AdoptOpenJDK官网下载的部分文件已变为Adoptium
建议删除AdoptOpenJDK并转换到Adoptium

#### 上游地址与镜像方法(How to Mirror)

官网: https://adoptium.net/
API文档: https://api.adoptium.net/q/swagger-ui/
Github Releases: 
  - [Java8](https://github.com/adoptium/temurin8-binaries/releases)
  - [Java11](https://github.com/adoptium/temurin11-binaries/releases)
  - [Java16](https://github.com/adoptium/temurin16-binaries/releases)
  - [Java17](https://github.com/adoptium/temurin17-binaries/releases)

#### 其他信息(Other)
- 镜像大小(Mirror Size)：基本与AdoptOpenJDK相同
- 该镜像需求是否被之前的 issue 提出过：#723
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：是

**Comment by ZenithalHourlyRate** [comment]
binary release 部分
Adoptium 与 AdoptOpenJDK 采用同一套 API，可直接复用现有脚本。不过注意到，两者的内容并不相同，前者只有 8,11,16，而后者有 8 至 16；JVM impl 中，前者也只有 hotspot，而后者有 hotspot 和 openj9

可参考 https://api.adoptium.net/v3/info/available_releases 与 https://api.adoptopenjdk.net/v3/info/available_releases ，以及 https://api.adoptium.net/q/swagger-ui/#/Assets/getLatestAssets

deb / rpm 部分，参考 https://github.com/adoptium/adoptium-support/issues/332 ，上游还没有决定何处托管。

**Comment by shanoaice** [comment]
OpenJ9 的 JVM impl 现在有 IBM 自家的 [IBM Semeru JDK](https://developer.ibm.com/languages/java/semeru-runtimes/), 不清楚这个是否能够镜像，我准备去开个新 issue。
根据这篇[官方 blog](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/)的内容来看 Adoptium 未来似乎也会把 OpenJ9 带回来。

**Comment by zlay0701** [comment]
2021 年 9 月 22 日Eclipse Temurin 17 GA 初始平台可用！
JDK17GA了 希望可以对应镜像

**Comment by zlay0701** [comment]
希望保留AdoptOpenJDK并新增 Adoptium

**Comment by zlay0701** [comment]
2021 年 9 月 22 日Eclipse Temurin 17 GA 初始平台可用！
JDK17GA了 希望可以对应镜像
希望**保留AdoptOpenJDK**并**新增 Adoptium**

**Comment by zlay0701** [comment]
2021 年 9 月 22 日Eclipse Temurin 17 GA 初始平台可用！
JDK17GA了 希望可以对应镜像
希望**保留AdoptOpenJDK并新增 Adoptium**

关于保留AdoptOpenJDK的原因 官方 blog提到 
为了确保顺利过渡，我们将在未来一段时间内保持AdaptOpenJDK 网站和AdaptOpenJDK API处于活动状态，并且我们将保留旧存档的 AdoptOpenJDK 版本- 尽管我们建议您始终使用最新的生产版本

**Comment by zlay0701** [comment]
关于OpenJ9  AdoptOpenJDK提供的也是IBM的等效实现 在官方blog中也提到

**Comment by zlay0701** [comment]
关于OpenJ9  AdoptOpenJDK提供的也是IBM的等效实现 在官方blog中也提到

**Comment by zlay0701** [comment]
希望增加jdk18

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/rename-adoptopenjdk-to-adoptium/
