### ISSUE TITLE
[tuna]404 at /ros/ubuntu/pool/main/r/ros-melodic-rviz/ros-melodic-rviz_1.13.17-1bionic.20210505.041235_amd64.deb

### ISSUE THREAD

**Issue by Eksanf** [tuna/issues#1315]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
请执行 apt update。
