### ISSUE TITLE
鱼屋打不开

### ISSUE THREAD

**Issue by CoderYangXiaoXu** [tuna/issues#1316]
#### 发生了什么（What happened）
鱼屋打不开，提示:
Failed to start
Your Element is misconfigured
Invalid homeserver discovery response
#### 期望的现象（What you expected to happen）
恢复鱼屋，期望能与清华学子交流
#### 如何重现（How to reproduce it）
首先，点开鱼屋，然后没了QWQ
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
貌似木有
#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 专业版 x64 20H2
- 浏览器（如果适用）（Browser version, if applicable）：Microsoft Edge 94.0.992.0 (官方内部版本) Canary (64 位)
- 其他（Others）：使用清华大学IPV4 DNS

**Comment by skyzh** [comment]
![image](https://user-images.githubusercontent.com/4198311/130716974-192210b5-fd1e-4bf4-876b-f00399293e27.png)

经测试可以打开。现在 TUNA 的交流平台已经迁移到 Matrix / Telegram。您可以根据 tuna.moe 首页指引加入。

**Comment by CoderYangXiaoXu** [comment]
OK，谢谢回复

**Comment by CoderYangXiaoXu** [comment]
我是点了链接打不开

**Comment by shankerwangmiao** [comment]
> 我是点了链接打不开

有截图吗？

**Comment by CoderYangXiaoXu** [comment]
![BaiduShurufa_2021-08-25_12-42-42](https://user-images.githubusercontent.com/58098001/130727787-23a49fd1-d86d-4485-b64b-e8ac87a32f31.png)

**Comment by fernvenue** [comment]
> 
> 
> ![BaiduShurufa_2021-08-25_12-42-42](https://user-images.githubusercontent.com/58098001/130727787-23a49fd1-d86d-4485-b64b-e8ac87a32f31.png)

网络问题，请参阅：https://github.com/vector-im/element-web/issues/14773
