### ISSUE TITLE
OpenTuna 的 ArchLinux 镜像更新频率

### ISSUE THREAD

**Issue by Hill-98** [tuna/issues#1317]
目前位于 opentuna.cn 的 ArchLinux 镜像更新频率是不是太低了，现在每天好像只同步两次，而清华镜像和外国语镜像都是每小时同步一次。

**Comment by sky96111** [comment]
opentuna是以tuna为上游同步的，而不是arch官方。个人猜测受限于tuna同步状态，高频同步可能有点困难

**Comment by Hill-98** [comment]
> opentuna是以tuna为上游同步的，而不是arch官方。个人猜测受限于tuna同步状态，高频同步可能有点困难

tuna 自身更新频率是每小时更新
