### ISSUE TITLE
elvish mirror request

### ISSUE THREAD

**Issue by xiaq** [tuna/issues#132]
#### 项目名称与简介(Project Intro.)

Elvish 还需要介绍嘛

#### 上游地址与镜像方法(How to Mirror)

rsync://dl.elvish.io

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

目前 34MB

**Comment by xiaq** [comment]
可以开一个 cn.dl.elvish.io 的 vhost 嘛？

**Comment by bigeagle** [comment]
可以呢～

**Comment by bigeagle** [comment]
但是即使是 ipv6 也慢得连不上，要不要绕过 cloudflare

**Comment by xiaq** [comment]
用 rsync.elvish.io

cn.dl.elvish.io 已经 CNAME 到 mirrors.tuna.tsinghua.edu.cn 啦

**Comment by bigeagle** [comment]
Done~ 
https://cn.dl.elvish.io/
