### ISSUE TITLE
[镜像请求] Rocky Linux 源

### ISSUE THREAD

**Issue by Lvzhenqian** [tuna/issues#1320]
#### 项目名称与简介(Project Intro.)
https://rockylinux.org/zh-cn/

#### 上游地址与镜像方法(How to Mirror)
https://docs.rockylinux.org/guides/add_mirror_manager/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：未知
- 该镜像需求是否被之前的 issue 提出过：否
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)： 是

众所周知，centos 抛弃了社区，rocky linux 崛起

**Comment by skyzh** [comment]
Hi, 请不要提重复的镜像请求。
