### ISSUE TITLE
archlinuxcn 和 arch4edu 部分软件包可能存在版权问题

### ISSUE THREAD

**Issue by zhmars** [tuna/issues#1326]
你好，我了解到 archlinuxcn 源的部分软件因为版权或许可证限制是不允许打包和分发的，也有部分存在争议[1]。这些问题在反馈后并没有得到管理员和维护者的积极处理[2][3][4]，反而又有新的二进制包加入[5]。

arch4edu 源的问题还没有反馈给他们。在读完他们的管理员（也是 archlinuxcn 部分包的维护者）的相关评论[6][7]之后，我想直接反馈给 TUNA 或许更合适。

考虑到两者问题类似，维护者也有部分重合，在这里统一描述。请问它们的行为是否是 TUNA 镜像站所允许的？如果不是的话，对于这种情况，TUNA 会怎样处理？

```
[1] https://github.com/archlinuxcn/repo/issues/2455
[2] https://github.com/archlinuxcn/repo/issues/2458
[3] https://github.com/archlinuxcn/repo/issues/2460
[4] https://github.com/archlinuxcn/repo/issues/2462
[5] https://github.com/archlinuxcn/repo/commit/3d0b875667984a4b7053b0827ad1e353dabc9754
[6] https://github.com/archlinuxcn/repo/issues/2458#issuecomment-913390476
[7] https://github.com/archlinuxcn/repo/issues/2462#issuecomment-913372349
```

**Comment by ClayStan** [comment]
针对第五条，我想官方是鼓励分发的态度 
![dingtalk](https://user-images.githubusercontent.com/44052361/132291818-08d49e47-bce7-46cb-8751-25ad1fa9ec8e.png)

**Comment by ClayStan** [comment]
![dingtalk](https://user-images.githubusercontent.com/44052361/132291852-9ca77929-9e28-449d-af96-f038c7779da9.png)

**Comment by zjuyk** [comment]
针对第五个软件包，只会更新开发人员指定的公测版本，即可向外界分发的版本

**Comment by shankerwangmiao** [comment]
关于具体您提及的软件仓库中具体的包是否符合相关的 EULA 的问题，我们暂时不在此处探讨。TUNA 对镜像内容的合规性的要求是一贯的。如果您认为软件仓库中存在相关问题，我们建议您直接与上游取得联系，以便更好地厘清问题。如果确实存在不顺畅的情况，我们也会协助进行沟通。如果个别软件仓库长期反复出现不符合 EULA 的内容，我们可能会采取措施，以免类似的内容出现。

**Comment by zhmars** [comment]
@ClayStan @zjuyk

关于第五条，原来的根据是软件包自带和钉钉官网的[专有钉钉服务协议](https://terms.alicdn.com/legal-agreement/terms/suit_bu1_alibaba_group/suit_bu1_alibaba_group202003271403_38651.html?spm=a2q2b.13441934.0.0.12366fbaXPPpUW)：

> 五、服务使用规范
> 3、除非另有说明，本协议项下的服务只能用于非商业用途。您承诺不对本服务任何部分或本服务之使用或获得，进行复制、拷贝、出售、转售或用于包括但不限于广告及任何其它商业目的。

我把它理解成「未明确允许第三方打包分发」。因为没有加入这个群，所以也没有看到这条信息。如果这是群管理员允许的，我很抱歉，以后会更加注意。

---

@shankerwangmiao

我不确定有没有理解清楚你的话，这些问题我已经向上游（archlinuxcn）反馈了，至于为什么没有向 arch4edu 反馈，参考原描述第二部分。如果你有时间检查现在的镜像源，还可以找到其它软件包：

- clion
- goland
- intellij-idea-ultimate-edition
- webstorm
- google-earth-pro
- lastpass
- masterpdfeditor
- minecraft-server
- plex-media-server
- skypeforlinux-stable-bin
- slack-desktop
- spotify
- sublime-merge
- teamviewer
- vmware-horizon-client
- vmware-workstation
- yandex-browser-beta

这些包部分可以追溯到 2014 年[1]，它们的 EULA 明确写着不允许修改和二次分发。我很难相信 archlinuxcn 一方面表达着对 EULA 的尊重[2][3]，另一方面还在维护这样的包。老实说，我可能没有足够的时间和耐心检查所有包，发送申请邮件或者在这种显而易见的的问题上向他们解释为什么[4]。即便反馈了，等待处理的时间也可能长达一个[5]或几个月[6]。

结合 #1009 看，我个人觉得 archlinuxcn 在对待包版权的态度上和 Chaotic-AUR 并没什么不同，甚至可能更消极。或者应该说选择性的积极。

请问在这种情况下，我是否可以认为我需要得到你们的协助沟通呢？

```
[1] https://github.com/archlinuxcn/repo/commit/30114779283c96c0280e2b36553206acfd416a72
[2] https://github.com/archlinuxcn/repo/issues/1949
[3] https://github.com/archlinuxcn/repo/issues/1968
[4] https://github.com/archlinuxcn/repo/issues/2463
[5] https://github.com/archlinuxcn/repo/issues/2152
[6] https://github.com/archlinuxcn/repo/issues/2342
```

**Comment by zjuyk** [comment]
@zhmars 首先很赞赏你对协议内容的看重，针对你在 archlinuxcn 提的几个 issue ，我发现你对协议内容的理解和我们部分维护者有分歧，这边的 issue 已经关了，可以回 cn 继续，但我个人认为解决这种理解分歧最有效的途径是向包的官方人员发文咨询，如果你可以很方便的联系到官方人员，可以直接凭官方人员的书面通知要求我们停止分发。

**Comment by lilydjwg** [comment]
> 发送申请邮件或者在这种显而易见的的问题上向他们解释为什么[4]

我并不觉得显而易见。你既然认为有违反软件的协议，你自然是看过了协议的。那么，将协议的获取方式和相关条款摘录出来，不是很容易的事情吗？

至于你提及的其它包，请提交 issue 以便处理。
