### ISSUE TITLE
Request for support of "pytorch-lts " and "nvidia" channels

### ISSUE THREAD

**Issue by JalinWang** [tuna/issues#1327]
The newest pytorch homepage suggests to install 1.8.2 by `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-lts -c nvidia`. Is there any plan to support the "pytorch-lts " and "nvidia" channels?

![image](https://user-images.githubusercontent.com/20621784/132357944-6b5f6678-c48a-4c0e-ac49-32f78c7e2d62.png)

**Comment by skyzh** [comment]
Some packages in NVIDIA repository subject to license that disallows us to mirror it. We have been reaching out for NVIDIA, but we get no reply till now.

**Comment by JalinWang** [comment]
> Some packages in NVIDIA repository subject to license that disallows us to mirror it. We have been reaching out for NVIDIA, but we get no reply till now.

Thanks for your commitment. I'm looking forwarding to favorable reply.

BTW, how about the `pytorch-lts` channel?

**Comment by Python-37** [comment]
Aye, the newest pytorch has some weird bugs, I have to use the previous version, like 1.8.x

**Comment by Starrah** [comment]
Now when using `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia` as the pytorch official website suggests, a 404 error will be raised: 
```
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: nvidia
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/nvidia
  error code: 404
```
I understand the situation that some packages in NVIDIA repository subject to license that disallows you to mirror it, but may you just add a 302 for any HTTP requests to https://mirrors.tuna.tsinghua.edu.cn/anaconda/nvidia and redirect them to https://conda.anaconda.org/nvidia ? 
Thank you!

**Comment by skyzh** [comment]
You can remove the configuration item from your config. Conda repository is configured on a repo-by-repo basis.

**Comment by Starrah** [comment]
> You can remove the configuration item from your config. Conda repository is configured on a repo-by-repo basis.

Thank you! I found I used a wrong `.condarc` config, which contains a line `channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda`. 
After changing to use the config in https://mirrors.tuna.tsinghua.edu.cn/help/anaconda , it works. 
Thank you!

**Comment by ZenithalHourlyRate** [comment]
> BTW, how about the `pytorch-lts` channel?

`pytorch-lts` now available at https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch-lts/

**Comment by genghisun** [comment]
maybe better to add `pytorch-lts` to custom_channels in [the document](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)?

**Comment by ZenithalHourlyRate** [comment]
> maybe better to add `pytorch-lts` to custom_channels in [the document](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)?

Done
