### ISSUE TITLE
[tuna]Mirror Request for new mirror hugging-face-models/princeton-nlp

### ISSUE THREAD

**Issue by BeHappyForMe** [tuna/issues#1328]
#### 项目名称与简介(Project Intro.)
基于bert的dropout对比学习Simcse

#### 上游地址与镜像方法(How to Mirror)
https://huggingface.co/princeton-nlp/

#### 其他信息(Other)
- 镜像大小(Mirror Size)：
- 该镜像需求是否被之前的 issue 提出过：
- 是否阅读了[请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)：

**Comment by skyzh** [comment]
> 关于移除 hugging-face-models 镜像的通知 https://mirrors.tuna.tsinghua.edu.cn/news/remove-hugging-face/
