### ISSUE TITLE
[Discussion] 考虑在新镜像请求中使用 GitHub Issue Template

### ISSUE THREAD

**Issue by skyzh** [tuna/issues#1330]
Docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Example: https://github.com/sjtug/mirror-requests/blob/master/.github/ISSUE_TEMPLATE/6-mirror-request-new.yaml https://github.com/sjtug/mirror-requests/issues/new?assignees=&labels=new-mirror&template=6-mirror-request-new.yaml&title=%5BMirror+Request%5D%3A+

这样用户就不用手动填写“是否阅读了请求新镜像前必读（试行）：是”了。只有打勾才能成功创建 issue。

**Comment by Harry-Chen** [comment]
有兴趣帮我们 PR 一个吗（雾

**Comment by skyzh** [comment]
明天一定！
