### ISSUE TITLE
[镜像请求] IBM Semeru Runtimes

### ISSUE THREAD

**Issue by shanoaice** [tuna/issues#1335]
### 项目名称与简介 (Project introduction)

IBM 提供的 OpenJ9 JVM impl Java 运行时和 SDK, 从 AdoptOpenJDK 官方的告别博客来看似乎是因为新的 Adoptium 由于 Eclipse 的一些限制暂时无法提供 OpenJ9-based JDK/JRE，于是 IBM 决定自行开始分发基于 OpenJ9 JVM 实现的 Java 运行时。

### 上游地址与镜像方法 (How to mirror)

官网：https://developer.ibm.com/languages/java/semeru-runtimes/
Github Releases: 
- Java 11: https://github.com/ibmruntimes/semeru11-binaries/
- Java 8: https://github.com/ibmruntimes/semeru8-binaries/
- Java 16: https://github.com/ibmruntimes/semeru16-binaries/
- 其他的（像 Java 17) 估计以后也会分开来开 repo，看上去同步有些小小的麻烦

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by ZenithalHourlyRate** [comment]
TUNA 和 BFSU 上已经同步了 LTS 版本 semeru8-binaries 和 semeru11-binaries；目前 semeru17-binaries 未放出正式 release，等待放出正式 release 后添加。

**Comment by ZenithalHourlyRate** [comment]
> 目前 semeru17-binaries 未放出正式 release，等待放出正式 release 后添加。

已添加，正在同步
