### ISSUE TITLE
[镜像请求] Joplin

### ISSUE THREAD

**Issue by JaimeZeng** [tuna/issues#1336]
### 项目名称与简介 (Project introduction)

> Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor. The notes are in Markdown format.

Joplin 是一款全平台的开源且完全免费的笔记应用，同时也是一个高效的 To-Do 待办事项工具和生产力工具。可以用标签或笔记本进行分类整理，笔记支持 Markdown，可实现全文搜索，并且可以使用自己喜欢的第三方外置编辑器如 Typora、VIM 来编辑笔记，以获得更好的写作体验。客户端跨平台加密同步，iOS、Mac、Windows、Chrome 插件等都有，并且可以通过 CLI 运行。

- Desktop : [https://github.com/laurent22/joplin](https://github.com/laurent22/joplin)
- Mobile: [https://github.com/laurent22/joplin-android](https://github.com/laurent22/joplin-android)

### 上游地址与镜像方法 (How to mirror)

- 上游地址
  - Desktop: [https://github.com/laurent22/joplin/releases/latest](https://github.com/laurent22/joplin/releases/latest)
  - Mobile: [https://github.com/laurent22/joplin-android/releases/latest](https://github.com/laurent22/joplin-android/releases/latest)

- 镜像方法 Github Release

### 镜像大小 (Mirror size)

Desktop 一个版本 600MB 左右，Mobile 一个版本 100MB 左右。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [x] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/laurent22/joplin/LatestRelease/
https://mirrors.tuna.tsinghua.edu.cn/github-release/laurent22/joplin-android/LatestRelease/
