### ISSUE TITLE
[镜像请求] nodejs 14

### ISSUE THREAD

**Issue by shuimoshusheng** [tuna/issues#1338]
### 项目名称与简介 (Project introduction)

nodejs

### 上游地址与镜像方法 (How to mirror)

https://deb.nodesource.com/node_14.x 

curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by shankerwangmiao** [comment]
http://mirrors.tuna.tsinghua.edu.cn

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-nodesource/
