### ISSUE TITLE
macosx isatap设置问题请教

### ISSUE THREAD

**Issue by gaozhi120525** [tuna/issues#1341]
ipv6.tsinghua.edu.cn网页中提到有问题可到这里提问。![WechatIMG5](https://user-images.githubusercontent.com/91653781/135399842-bb17e0bd-b593-46da-8f73-4b233fe16689.jpeg)网页中提到isatap设置用于部分院系内网未包含ipv6情况，在校外使用清华sslvpn连接在windows端已确认同样可以使用ipv6（如北邮人），那么sslvpn客户端是否同样对于macosx也可行呢？是我的设置方法有问题吗？

**Comment by jiegec** [comment]
IPv4="" 里面是你的公网 IP 地址，而不是那个字符串。

**Comment by shankerwangmiao** [comment]
另外请先执行 `sudo ifconfig gif0 destroy`

**Comment by shankerwangmiao** [comment]
以及引号请输入英文引号

**Comment by shankerwangmiao** [comment]
目前暂时不能从校外连接 isatap，但是可以经由 sslvpn 连接。如果需要这样做，应先拨通 sslvpn 之后，使用 `ifconfig -a` 命令检查本机的 IP 地址，找到 VPN 分配的校内地址，一般以 `166.111` 开头，此后所有的操作中都以此地址作为你的公网 IP 地址。

**Comment by gaozhi120525** [comment]
> 目前暂时不能从校外连接 isatap，但是可以经由 sslvpn 连接。如果需要这样做，应先拨通 sslvpn 之后，使用 `ifconfig -a` 命令检查本机的 IP 地址，找到 VPN 分配的校内地址，一般以 `166.111` 开头，此后所有的操作中都以此地址作为你的公网 IP 地址。![1632996088383](https://user-images.githubusercontent.com/91653781/135435871-5dafdbd5-d0c4-4faa-bdfe-95ec1c5e40ec.jpg)![1632996230344](https://user-images.githubusercontent.com/91653781/135435913-e1407a2a-f542-440a-81e0-6e6a77f17884.jpg)哦哦，我似乎有了一些进展，但还没到最后一步，不知道哪里出了问题![1632996303781](https://user-images.githubusercontent.com/91653781/135435958-d714e3f0-cbb9-4d2c-85b8-265f7eb2ae4c.jpg)

**Comment by gaozhi120525** [comment]
@shankerwangmiao 忘了@了

**Comment by shankerwangmiao** [comment]
应该是已经正确连接上了，但是手动添加的隧道接口不能被 macOS 识别，导致系统没能识别出来你开启了 v6，并且优选 v4。

这个就是最终的效果，你现在应该可以访问纯 v6 的网站了。

**Comment by gaozhi120525** [comment]
@shankerwangmiao 哦哦，那我试了一下北邮人、六维空间等网页都不行讷，这个是算纯v6网站吧？
