### ISSUE TITLE
TUNA 证书（链？）错误

### ISSUE THREAD

**Issue by ljcbaby** [tuna/issues#1344]
#### 发生了什么（What happened）
![image](https://user-images.githubusercontent.com/46277145/136052204-870ccd8f-2ca4-432b-b622-fada703fcc11.png)

#### 期望的现象（What you expected to happen）
正常更新
#### 如何重现（How to reproduce it）
<https://myssl.com/mirrors.tuna.tsinghua.edu.cn?domain=mirrors.tuna.tsinghua.edu.cn&ip=101.6.15.130&f=1>
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：网络：浙江金华电信
特殊的，浏览器直接访问 <https://mirrors.tuna.tsinghua.edu.cn/> 没有问题

**Comment by Harry-Chen** [comment]
duplicate with #1342
