### ISSUE TITLE
DST CA 证书过期导致 conda SSL 认证错误

### ISSUE THREAD

**Issue by sandyzikun** [tuna/issues#1345]
#### 发生了什么（What happened）

当我使用镜像站下载keras的时候，

```sh
$ conda install keras==2.3.1
```

它输出

```py
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'mirrors.tuna.tsinghua.edu.cn\', port=443): Max retries exceeded with url: /anaconda/pkgs/main/linux-64/repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')])")))'))
```

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：是

#### 您的环境（Environment）
- 操作系统（OS Version）： `Ubuntu-20.04`
- `Anaconda-5.3.1`

# 我想说的是（What I\'m trying to say）
这个问题解决方案很明显，就是把`conda`配置中的`ssl_verify`设为`false`，但这大概率是镜像站的https证书过期所致，如若真的是这样，希望清华镜像的朋友们能够抽时间解决一下这个问题，非常感谢！

**Comment by sandyzikun** [comment]
> 你的理解是错误的。 duplicate with #1342 #1344

感谢指路！我正在读

**Comment by skyzh** [comment]
一些 Python 库不使用系统 CA。请用 pip 升级相关包（比如 certifi）的版本。

**Comment by sandyzikun** [comment]
> 一些 Python 库不使用系统 CA。请用 pip 升级相关包（比如 certifi）的版本。

@skyzh 谢谢，我也意识到这一块问题，但发现还是没有通过升级相应模块解决它，我在 [#1342](https://github.com/tuna/issues/issues/1342#issuecomment-935534968) 里面详细描述了这个新的问题。

**Comment by shankerwangmiao** [comment]
似乎是 conda 的 python 的 ssl 相关问题，与此前系统的情况不一致，所以还是在此处理。

**Comment by taoky** [comment]
> 我的环境是 Ubuntu(server)-20.04 with Anaconda-5.3.1 on VirtualBox-6.0.4 （本体是win10

Anaconda 5.3.1 已经是 2018 年的事情了，如果系统的 `curl` 连 HTTPS 确认没问题，建议改一下 `.condarc` 先用 http，然后在 anaconda 中把以下的包升级到最新：

- ca-certificates
- certifi
- openssl

有可能可以解决问题。

（根据坏人的建议，在这里贴回复。另外我测试了 continuumio 的官方 anaconda3/miniconda3 docker image 中比较老的几个（都是基于 Debian Buster 的）都没有出现问题，怀疑还是和系统环境相关

**Comment by sandyzikun** [comment]
> > 我的环境是 Ubuntu(server)-20.04 with Anaconda-5.3.1 on VirtualBox-6.0.4 （本体是win10
> 
> Anaconda 5.3.1 已经是 2018 年的事情了，如果系统的 `curl` 连 HTTPS 确认没问题，建议改一下 `.condarc` 先用 http，然后在 anaconda 中把以下的包升级到最新：
> 
> * ca-certificates
> * certifi
> * openssl
> 
> 有可能可以解决问题。
> 
> （根据坏人的建议，在这里贴回复。另外我测试了 continuumio 的官方 anaconda3/miniconda3 docker image 中比较老的几个（都是基于 Debian Buster 的）都没有出现问题，怀疑还是和系统环境相关

@taoky 我回去试试更新 `certifi` 和 `openssl` ，看来有可能是虚拟系统或者虚拟机的问题，非常感谢
