### ISSUE TITLE
rustup mirror 因为 User-Agent 缺失暂时不可用

### ISSUE THREAD

**Issue by jiegec** [tuna/issues#1346]
#### 发生了什么（What happened）

rustup 失败：

```shell
$ RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup install stable
info: syncing channel updates for 'stable-aarch64-apple-darwin'
warning: Signature verification failed for 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/channel-rust-stable.toml'
info: latest update on 2021-09-09, rust version 1.55.0 (c8dfcfe04 2021-09-06)
info: downloading component 'rust-std' for 'x86_64-unknown-linux-musl'
error: component download failed for rust-std-x86_64-unknown-linux-musl: could not download file from 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/2021-09-09/rust-std-1.55.0-x86_64-unknown-linux-musl.tar.xz' to '/REDACTED/.rustup/downloads/a7f02bd5b4fd2b1f55edaddfa869d2ce210ce4951cb752ce7b380129bc2d1882.partial'
```

#### 期望的现象（What you expected to happen）

rustup 添加 User-Agent 头部：https://github.com/rust-lang/rustup/issues/2860

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by luojia65** [comment]
好像现在还是坏的？我这里的情况似乎是类似的。
![图片](https://user-images.githubusercontent.com/40385009/155266121-6c27fe07-49e7-42b3-accc-1d7fdfa7749b.png)

**Comment by jiegec** [comment]
rustup 上游版本已经修复，等 rustup 发布正式版后就恢复使用。

**Comment by jiegec** [comment]
rustup 1.25.1 版本已经提供 User-Agent。
