### ISSUE TITLE
[镜像请求] DBeaver CE 镜像同步

### ISSUE THREAD

**Issue by zhaojul** [tuna/issues#1348]
### 项目名称与简介 (Project introduction)

# dbeaver-ce

## 镜像地址

https://github.com/dbeaver/dbeaver/releases

### 镜像大小 (Mirror size)

每个release版本接近1G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by wsq93** [comment]
我也在用dbeaver-ce，每次提醒更新我都想下载新版本的，GitHub要么不可访问，要么下载慢ε=(´ο｀*)))唉

**Comment by CherryRum** [comment]
`https://github.com/fhefh2015/Fast-GitHub`

**Comment by Harry-Chen** [comment]
已同步： https://mirrors.tuna.tsinghua.edu.cn/github-release/dbeaver/dbeaver/LatestRelease/
