### ISSUE TITLE
Termux没更新上

### ISSUE THREAD

**Issue by hemon** [tuna/issues#135]
http://termux.net/dists/stable/main/binary-aarch64/
Index of /dists/stable/main/binary-aarch64
Packages                                           16-Oct-2016 16:44  198K  
Packages.xz                                        16-Oct-2016 16:44   43K  

https://mirrors.tuna.tsinghua.edu.cn/termux/dists/stable/main/binary-aarch64/
Index of /termux/dists/stable/main/binary-aarch64/
Packages                                           29-Sep-2016 23:30              203393
Packages.bz2                                       12-Mar-2016 22:53               33751
Packages.xz                                        03-Oct-2016 21:49               43884

**Comment by Harry-Chen** [comment]
Solved.

**Comment by bigeagle** [comment]
@Harry-Chen 瞎搞……

**Comment by bigeagle** [comment]
![deepinscreenshot20161031001645](https://cloud.githubusercontent.com/assets/548512/19837944/55802dbc-9eff-11e6-87a8-02c073bb4c6c.png)
看了下日志，aarch64 部分 Packages 一直校验不通过所以失败了，我在查下具体原因。不排除是上游问题。

**Comment by bigeagle** [comment]
找到原因了，配置文件里是这么写的

```ini
[[mirrors]]
name = "termux"
interval = 1440
provider = "command"
upstream = "https://termux.net/"
command = "/home/scripts/termux.sh"
```

脚本拼 URL 的时候，拼出了 `https://termux.net//dists/stable/main/....`，多了一个 '/'，这个正常情况下是没事的，但是 termux 用了 cloudflare 的 CDN，就把这个请求给缓存下来了……
所以有几个文件一直是旧的。

**Comment by Alan-Liang** [comment]
现在又没更新上……

```sh
$ curl -s http://packages.termux.org/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2 | sha256sum
07c6826290ebd2ea4e0377b2b24c2d8dd928fe6244d6210c8e4d61f8fed9d4f1  -
$ curl -s https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2 | sha256sum
ca35287e04d4024502e977cbd9f33a9083302e0b9ccd0c35707786d7455fe052  -
```

**Comment by ZenithalHourlyRate** [comment]
> 现在又没更新上……
```
$ curl -s https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2 | sha256sum
07c6826290ebd2ea4e0377b2b24c2d8dd928fe6244d6210c8e4d61f8fed9d4f1  -
```

现在已更新。

注：与上游有一定的同步延迟是正常现象。
