### ISSUE TITLE
[tuna]404 at /ubuntu/dists/xenial-updates/main/binary-amd64/Packages

### ISSUE THREAD

**Issue by zimengxueying** [tuna/issues#1350]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/xenial-updates/main/binary-amd64/ 下面有你所说的文件。请详细描述你的问题。

**Comment by shankerwangmiao** [comment]
因为已经有 Packages.gz 和 Packages.xz 了，因此不再需要未压缩过的原始文件。

上游也是如此：http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/
