### ISSUE TITLE
[tuna]404 at /flutter/flutter_infra_release/flutter/2d8b3571d074c222e2382b1e369bc140bc7fd4eb/ios/artifacts.zip

### ISSUE THREAD

**Issue by yingshaoxo** [tuna/issues#1354]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
Flutter 只同步 stable；另外这个文件在上游也不存在。
