### ISSUE TITLE
[tuna]404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by liudaobenyuan** [tuna/issues#1356]
snapshtos的packages为空，帮忙检查下。另外可用添加openwrt源码镜像吗？

#### 

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 X86-64 2004（19041.1237）
- 浏览器：Microsoft Edge 版本 94.0.992.47 (官方内部版本) (64 位)
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
see #619
