### ISSUE TITLE
Mirror Request: HHVM

### ISSUE THREAD

**Issue by ym** [tuna/issues#136]
#### 项目名称与简介(Project Intro.)

HHVM is an open-source virtual machine designed for executing programs written in Hack and PHP. HHVM uses a just-in-time (JIT) compilation approach to achieve superior performance while maintaining the development flexibility that PHP provides.
HHVM supports Hack, PHP 5 and the major features of PHP 7. We are aware of minor incompatibilities, so please open issues when you find them. HHVM also supports many extensions as well.
#### 上游地址与镜像方法(How to Mirror)

rsync://rsync.osuosl.org/hhvm/
#### 其他信息(Other)
- 镜像大小(Mirror Size): ~ 78.2G

**Comment by bigeagle** [comment]
syncing

**Comment by bigeagle** [comment]
Done.

**Comment by fredemmott** [comment]
Sorry, we've not been able to prioritize looking at the documentation until recently :(

Closing as:
 - this mirror is now stale (see instructions for updating on https://github.com/hhvm/user-documentation/commit/ca087dfcb5eb269350ee1c79c0132935b6e9fb5b )
 - dl.hhvm.com is now fronted by a CDN (CloudFront) so this should be less useful.
