### ISSUE TITLE
[Service Issues] bfsu pypi 有包 404

### ISSUE THREAD

**Issue by lonelyevil** [tuna/issues#1360]
#### 发生了什么（What happened）
存在 pypi 包 404。

#### 期望的现象（What you expected to happen）
200

#### 如何重现（How to reproduce it）
```
https://mirrors.bfsu.edu.cn/pypi/web/simple/pysocks/ 试图下载 PySocks-1.7.1-py3-none-any.whl
https://mirrors.bfsu.edu.cn/pypi/web/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl#sha256=2725bd0a9925919b9b51739eea5f9e2bae91e83288108a9ad338b2e3a4435ee5
```

404

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：否
- 该问题在 tuna 镜像不存在，最少已持续 12 小时。

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 21H1
- 其他（Others）：
```
pipx --version
0.16.4
python -V
Python 3.9.7
```

**Comment by shankerwangmiao** [comment]
已经修复。
