### ISSUE TITLE
[镜像请求] C++准标准库Boost库

### ISSUE THREAD

**Issue by ssssup** [tuna/issues#1362]
### 项目名称与简介 (Project introduction)

Boost库

- Boost库由C++标准委员会库工作组成员发起，其中有些内容有望成为下一代C++标准库内容。在C++社区中影响甚大，是不折不扣的“准”标准库。

- Boost库由Boost社区组织开发、维护。其目的是为C++程序员提供免费、同行审查的、可移植的程序库。Boost库可以与C++标准库完美共同工作，并且为其提供扩展功能。Boost库使用Boost License来授权使用，根据该协议，商业的非商业的使用都是允许并鼓励的。

### 上游地址与镜像方法 (How to mirror)

从2021年4月开始，Boost库下载站转移至JFrog，国内访问困难，官方转移地址的公告：[https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html](https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html)

Boost库的地址在：[https://boostorg.jfrog.io/artifactory/main/](https://boostorg.jfrog.io/artifactory/main/)

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by Harry-Chen** [comment]
由于没有合适的同步办法，且我们通常不接受以国内访问速度缓慢为由提出的镜像请求，因此暂不考虑增加。
