### ISSUE TITLE
Anaconda conda-forge 镜像 没有 spyder？

### ISSUE THREAD

**Issue by QiangF** [tuna/issues#1369]
$ conda install  spyder
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.

    PackagesNotFoundError: The following packages are not available from current channels:

    - spyder

    Current channels:

    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch

**Comment by Harry-Chen** [comment]
由于没有更多信息而关闭。

**Comment by QiangF** [comment]
已经有了。
