### ISSUE TITLE
多个镜像同步时速度会变慢

### ISSUE THREAD

**Issue by SuperWangCC** [tuna/issues#137]
多个镜像同步时速度会变慢，是否应根据源的更新速度设置不同的更新时间？
以前速度基本上是2-3MB，最近速度只能上1mb。
建议设置内存缓存机制和错峰更新

**Comment by shankerwangmiao** [comment]
您是指您从我们这里同步变慢还是我们从上游同步变慢？

**Comment by SuperWangCC** [comment]
从你们那里同步变慢

**Comment by shankerwangmiao** [comment]
建议您在从我们这里同步的时候错开高峰同步，并减少同时同步的 repo 数量。
