### ISSUE TITLE
elpa上游仓库地址变更

### ISSUE THREAD

**Issue by TomoeMami** [tuna/issues#1373]
#### 发生了什么（What happened）

根据emacs-china管理员在[这个帖子里面的回复](https://emacs-china.org/t/elpa/16909/24)：

![Snipaste_2021-10-28_16-41-17](https://user-images.githubusercontent.com/16950305/139219990-33b213a4-9293-4f7f-aac4-cda3ac65a172.png)
![Snipaste_2021-10-28_16-41-21](https://user-images.githubusercontent.com/16950305/139220003-46aa3615-1b6a-40c8-b175-da7acf07ea43.png)

得知tuna镜像站的elpa上游

>本镜像的上游为 http://elpa.emacs-china.org/ ，本文档也参考了emacs-china提供的帮助。

已经改为了 http://elpa.zilongshanren.com/ 。 访问 https://elpa.emacs-china.org/ 也能看见仓库地址全部指向了elpa.zilongshanren.com

![Snipaste_2021-10-28_16-43-32](https://user-images.githubusercontent.com/16950305/139220396-2910a876-b290-412e-8ff5-f7c844d25783.png)

#### 期望的现象（What you expected to happen）

将tuna镜像站的elpa镜像上游地址更改为现行地址。

**Comment by QiangF** [comment]
为什么不改成上游的上游呢？：-）
 上游 GNU ELPA 和 MELPA 提供了 Rsync 服务，其地址分别为：

  rsync://elpa.gnu.org/elpa/
  rsync://melpa.org/packages/

**Comment by taoky** [comment]
> 为什么不改成上游的上游呢？：-） 上游 GNU ELPA 和 MELPA 提供了 Rsync 服务，其地址分别为：
> 
> rsync://elpa.gnu.org/elpa/ rsync://melpa.org/packages/

如果直接从 elpa.gnu.org 和 melpa.org 同步，看起来要改目录结构。
