### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by aaronmaomao** [tuna/issues#1376]
### 项目名称与简介 (Project introduction)

eclipse updates site.

url: https://wiki.eclipse.org/Eclipse_Project_Update_Sites

### 上游地址与镜像方法 (How to mirror)

eclipse p2 repository

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/eclipse/eclipse

已有 eclipse 镜像，如果有部分内容还被镜像到，请提出。

同时，可以在 https://github.com/tuna/mirror-web/ 中给 eclipse 镜像提供镜像帮助
