### ISSUE TITLE
下载oniguruma-6.9.6.catalina.bottle.tar.gz失败

### ISSUE THREAD

**Issue by nanfengkkkkkkk** [tuna/issues#1377]
#### 发生了什么（What happened）
使用homebrew下载jq镜像文件发生404错误
#### 如何重现（How to reproduce it）
brew install jq
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：mac os
- 浏览器（如果适用）（Browser version, if applicable）： chrome
- 其他（Others）：

**Comment by ZenithalHourlyRate** [comment]
```
$ find ./ -name "oniguruma*"
./oniguruma-6.9.7.1.mojave.bottle.tar.gz
./oniguruma-6.9.7.1.arm64_big_sur.bottle.tar.gz
./oniguruma-6.9.7.1.big_sur.bottle.tar.gz
./oniguruma-6.9.7.1.x86_64_linux.bottle.tar.gz
./oniguruma-6.9.7.1.catalina.bottle.tar.gz
./oniguruma-6.9.7.1.monterey.bottle.tar.gz
./oniguruma-6.9.7.1.arm64_monterey.bottle.tar.gz
```
可能需要 `brew update`

**Comment by nanfengkkkkkkk** [comment]
解决了  谢谢~
