### ISSUE TITLE
[bfsu]404 at /pypi/web/packages/80/f1/cd7626c763e58f967317023c3dd01a2fab5d6f00f8e1c672ccceb3aae5cb/amqp-5.0.6-py3-none-any.whl

### ISSUE THREAD

**Issue by findlayfeng** [tuna/issues#1378]
#### 发生了什么（What happened）

https://mirrors.bfsu.edu.cn/pypi/web/packages/80/f1/cd7626c763e58f967317023c3dd01a2fab5d6f00f8e1c672ccceb3aae5cb/amqp-5.0.6-py3-none-any.whl#sha256=493a2ac6788ce270a2f6a765b017299f60c1998f5a8617908ee9be082f7300fb

404 了

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
已经修复了。
