### ISSUE TITLE
申请chromium镜像

### ISSUE THREAD

**Issue by jyunfan2015** [tuna/issues#138]
#### 项目名称与简介(Project Intro.)

chromium
chromium是谷歌仅次于android的开源项目，众多第三方浏览器和其他项目都以此为基础。
#### 上游地址与镜像方法(How to Mirror)

项目主页
https://www.chromium.org/chromium-projects

创建镜像方法
https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/creating-local-mirrors

**Comment by xavieryao** [comment]
和AOSP一样用的是repo那一套…可能会比较耗费资源





On Mon, Oct 24, 2016 at 12:14 AM +0800, "jyunfan2015" <notifications@github.com<mailto:notifications@github.com>> wrote:

项目名称与简介(Project Intro.)

chromium
chromium是谷歌仅次于android的开源项目，众多第三方浏览器和其他项目都以此为基础。

上游地址与镜像方法(How to Mirror)

项目主页
https://www.chromium.org/chromium-projects

创建镜像方法
https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/creating-local-mirrors

―

**Comment by shankerwangmiao** [comment]
似乎是的
> 在 2016年10月26日，02:32，Xavier Yao <notifications@github.com> 写道：
> 
> 和AOSP一样用的是repo那一套…可能会比较耗费资源 
> 
> 
> 
> 
>

**Comment by huiyiqun** [comment]
反过来想 如果aosp稳定了 这个也能比较稳定 chromium的镜像用的人应该相对少很多吧？

**Comment by bigeagle** [comment]
不见得，已经收到很多 chromium 镜像的请求了。不过这个请求是唯一一个有诚意的，带了镜像方法的。

**Comment by Harry-Chen** [comment]
顺便，我们可以把 Chromium OS 的一系列 repos 都镜像了。也是 repo 那一套的。
（昨天康哥强烈要求的）

**Comment by bigeagle** [comment]
这个是源码…… 你们要编译吗？

**Comment by huiyiqun** [comment]
有源码也挺有用的

我昨天下了一个branch 有几个G

一会儿我全量下载一下 看看有多大

2016-10-30 23:51 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by bigeagle** [comment]
好的，惠老师你能登 bravo 吗？

**Comment by huiyiqun** [comment]
可以 今天忙了一下 忘了下全量了 我直接同步到bravo上？

bigeagle <notifications@github.com>于2016年10月31日周一 下午5:52写道：

**Comment by bigeagle** [comment]
别急，先看看大小。这个可能要开 docker，可能要同步到 ssd 里。

**Comment by huiyiqun** [comment]
我明天用我实验室电脑同步看下大小 我们再讨论怎么镜像吧

bigeagle <notifications@github.com>于2016年10月31日周一 下午10:20写道：

**Comment by jyunfan2015** [comment]
好期待啊。希望尽早看到。可以肯定的是chromium是浏览器届的Linux，连Atom编辑器都是以chromium为基础呢。人们评价chromium是C++跨平台的标本，google c++风格的代码，有着Python的语法优雅和可读性。理论上说C++桌面程序跨平台可以以chromium为内核。

**Comment by huiyiqun** [comment]
刚刚调查了一下 基本结论如下 当然我对chromium这个项目也不是特别熟悉，可能有些出入，欢迎指正：

1. chromium和chromium OS是两个不同的项目，管理的方式上有很大区别，从 @jyunfan2015 的说法来看，想要的应该是chromium的镜像，chromium OS的相关问题不要在这个issue里讨论了，我另开issue。

2. chromium.org 这个域名下实际上host了两个项目的wiki，[chromium-os](https://www.chromium.org/chromium-os)下是chromium OS相关的，[developers](https://www.chromium.org/developers)下是chromium相关的。 @jyunfan2015 给出的镜像方法实际上是chromium-os而不是chromium的。

3. [这里](https://www.chromium.org/developers/how-tos/get-the-code)给出了chromium的代码下载方式，用的是[depot_tools](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up)，里面也有repo，但是实际下代码用的是fetch.py，我没有继续向下看，有可能也是基于repo的又一层封装，不弄懂这个我们就没法镜像了。

4. 对于android、chomium、chromium os、cyanogenmod这样的由多个git构成的项目，镜像的主要难度在于，我们没法简单的知道究竟有哪些git存在，他们应该放在什么地方。Android之所以能够镜像是因为官方提供并且维护了一个特殊的[mirror manifest](https://android.googlesource.com/mirror/manifest)里面描述了所有活跃的git repo列表，所以我们只要根据这个manifest把所有git镜像下来就可以了。平时我们下载代码用的manifest里有很多branch，每个branch的manifest都是mirror manifest的列表的子集。但是不幸的是，据我所知，上面列出来的项目里，只有aosp官方维护了这个mirror manifest，cm曾经有三方维护的。

5. 当然4并不是不能解决的，可以遍历普通manifest的branch，然后取并集，就能自己构建一个mirror manifest，不过写这个需要时间精力，不见什么时候能写出来，因为维护者都是学生，不见得什么时候有时间。

6. `repo`有一个`--mirror`选项，不知道有什么用。

**Comment by chanjsq** [comment]
Google 了很多页，找 Chromium 浏览器二进制镜像，找不到，心好累 😢

**Comment by chanjsq** [comment]
1. 其实希望要的是 https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/512433/chrome-mac.zip  以及其他平台和版本的国内镜像
2. 即 https://commondatastorage.googleapis.com/chromium-browser-snapshots/ 下的文件
3. 需要可以直接替代 HOST，然后 `HOST/chromium-browser-snapshots/Mac/512433/chrome-mac.zip` 可以访问

**Comment by chanjsq** [comment]
看这里 https://www.chromium.org/getting-involved/download-chromium

**Comment by jingjingxyk** [comment]
git 仓库地址
git clone https://chromium.googlesource.com/chromium/src

**Comment by jingjingxyk** [comment]
申请chromium镜像  https://github.com/tuna/issues/issues/365

**Comment by showerying** [comment]
没有动静了吗？🤔

**Comment by swizl** [comment]
github 上clone 的 chromiun 源码没有 fetch 的全。

高通有个两镜像，还没试过 怎么样。
https://source.codeaurora.org/quic/chrome4sdp/chromium/
这个应该比较全，但目录结构跟fetch的还是有一些不同，缺的代码应该都在边上，可能得自己再加。

https://source.codeaurora.org/mirrors/chromium.googlesource.com/chromium/src/
这个跟git的估计一样 ，没带V8等一些东西。

不过 还是希望tuna能开一个能配成fetch的镜像

**Comment by huiyiqun** [comment]
@swizl tuna 当前并没有提供 chromium 的源代码/二进制 镜像。

如果官方维护的 github 镜像都“不全”的话，那么我们应该更没有办法维护一个完整的镜像了。

另外 fetch 是一个代码下载工具，不是一个代码镜像工具，两者有本质的区别。当前 repo 的镜像是了解了 repo 的工作方式根据它的工作方式自己实现的[镜像工具](https://github.com/tuna/tunasync-scripts/blob/master/cros.sh)。我们当前并没有熟悉 fetch 的人，欢迎对 fetch 熟悉的人贡献同步脚本。

**Comment by FlyGoat** [comment]
http://gclxry.com/build-chromium-repo-mirror/
找到一篇Blog Post，不知道有没有参考价值。

**Comment by jingjingxyk** [comment]
https://github.com/chromium/chromium.git

**Comment by jerryjoejj** [comment]
> https://github.com/chromium/chromium.git

这是完整的代码吗？

**Comment by liudongmiao** [comment]
虽然曾期望 tuna 可以同步 chromium/src，但是在使用 chromium 的 fetch / gclient 下载完 chromium 源码之后，建议是不要同步 chromium 源。

1. 整个 fetch / gclient 会使用 chromium/src/DEPS 下所有的 .git
  而这些源，目前没有看到可以配置 repo 之类。
  也就是说，同步完 chromium/src 之后，需要像 aosp 更新 manifest.xml 一样更新 chromium/src/DEPS
  而这个，涉及数十个外部源，虽然绝大部分都是 chromium
  
  ```
   1 aomedia.googlesource.com
   1 boringssl.googlesource.com
   1 dawn.googlesource.com
   1 pdfium.googlesource.com
   1 quiche.googlesource.com
   1 skia.googlesource.com
   1 swiftshader.googlesource.com
   1 webrtc.googlesource.com
   2 android.googlesource.com
  96 chromium.googlesource.com
  ```

2. 即使把这些源全部同步，依旧无法直接使用。
   在整个同步 chromium 源码过程中，还需要去访问几个站点，这些是没有办法镜像的。

**Comment by Harry-Chen** [comment]
Closed according to https://github.com/tuna/issues/issues/138#issuecomment-502491547
