### ISSUE TITLE
about the mirrors synchronize 

### ISSUE THREAD

**Issue by dongzhe1208** [tuna/issues#1381]
Good afternoon!Our company is a IDC Service provider in Beijing.We want to synchronize some mirrors with high user frequency to my station. Can I provide a list of the top ten mirrors in the higher frequency of your station?

**Comment by ZenithalHourlyRate** [comment]
> Can I provide a list of the top ten mirrors in the higher frequency of your station?

I assume you meant by "Can you provide"

Top 10 by bytes: centos, anaconda, ubuntu, aosp-monthly, epel, AOSP, CTAN, qt, fedora, pypi
