### ISSUE TITLE
[tuna]404 at /centos-altarch/8/AppStream/aarch64/os/repodata/repomd.xml

### ISSUE THREAD

**Issue by DINGDOM** [tuna/issues#1382]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
aarch64 没有同步。

**Comment by DINGDOM** [comment]
那里有啊

**Comment by shankerwangmiao** [comment]
您好，上游亦无此目录。

http://mirror.centos.org/altarch/8/AppStream/

**Comment by shankerwangmiao** [comment]
你找的是不是：https://mirrors.tuna.tsinghua.edu.cn/centos/8/AppStream/aarch64/os/repodata/repomd.xml

centos 7 开始，aarch64 架构相关的内容在主仓库里。
