### ISSUE TITLE
[镜像请求] ghcr.io的docker源

### ISSUE THREAD

**Issue by Luoxin** [tuna/issues#1384]
### 项目名称与简介 (Project introduction)

GitHub Packages 是一种包托管服务，与 GitHub 完全集成。 GitHub Packages 将您的源代码和软件包组合在一起，以提供集成的权限管理和计费，使您能够在 GitHub 上专注于软件开发。

您可以将 GitHub Packages 与 GitHub API、GitHub Actions 以及 web 挂钩集成在一起，以创建端到端的 DevOps 工作流程，其中包括您的代码、CI 和部署解决方案。

GitHub Packages 为常用的包管理器提供不同的包注册表，例如 npm、RubyGems、Apache Maven、Gradle、Docker 和 Nuget。 GitHub 的 Container registry 针对容器进行了优化，支持 Docker 和 OCI 映像。

### 上游地址与镜像方法 (How to mirror)

> 预期希望加入docker部分的镜像
- 上游：ghcr.io
- 镜像方式：同docker的镜像方式

### 备注 (Note)

随着docker hub的价格政策的调整，有众多原本位于docker hub的image迁移至GitHub Packages，由于众所周知的原因，ghcr.io在国内是无法访问的

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by skyzh** [comment]
TUNA 到目前为止应该没有同步过 DockerHub。DockerHub 到目前为止没有靠谱的同步方案，ghcr.io 同理。

**Comment by soulteary** [comment]
@skyzh 或许你可以试试 https://github.com/distribution/distribution 可以用比较低的成本启动一个容器仓库服务。

简单的使用或者去掉认证（本地、上游）等，可以参考这里的操作：[配置无须身份验证的容器仓库](https://soulteary.com/2021/04/13/use-docker-to-build-a-simple-and-reliable-container-registry.html#%E9%85%8D%E7%BD%AE%E6%97%A0%E9%A1%BB%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81%E7%9A%84%E5%AE%B9%E5%99%A8%E4%BB%93%E5%BA%93)

实际使用的时候，配置中配好上游就行了：

```
proxy:
  remoteurl: https://gcr.io
```

至于具体镜像的数据同步问题，我认为或许不需要全量进行，只缓存有需求的镜像即可。

**Comment by Harry-Chen** [comment]
我们更新了政策，目前不接受 docker 相关的镜像
