### ISSUE TITLE
[镜像请求]  FreeDOS

### ISSUE THREAD

**Issue by spz2020** [tuna/issues#1385]
### 项目名称与简介 (Project introduction)

FreeDOS（曾叫做Free-DOS和PD-DOS）是一个在IBM PC兼容机下运行的操作系统。FreeDOS由许多不同的独立程序组成，这些程序就是整个FreeDOS项目中的“包”。作为DOS家族中的一员，它主要通过内核来提供磁盘访问和文件系统，以及部分内存管理，但是没有默认的GUI（尽管FreeDos 0.9及以上版本推荐使用OpenGEM）。FreeDOS支持老式和新式IBM PC，以及嵌入式系统。像MS-DOS一样，它可以从软盘、硬盘以及ROM启动。与MS-DOS不同，它支持从CD-ROM安装，并且人们可以自由创建属于自己的定制发行版，而不用为再发行支付使用费。

### 上游地址与镜像方法 (How to mirror)

bin 
https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc4/
repo
http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos

### 镜像大小 (Mirror size)

?

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [x] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by Harry-Chen** [comment]
它目前有任何有意义的用途和实际用户吗？

**Comment by spz2020** [comment]
FreeDOS与MS-DOS
为FreeDOS设计的DOS软件正在源源不断的推出和发展，不仅有各种外部命令，还有许多其它的增强程序和附件，而且质量既高也很实用，往往超过MS-DOS中的同类命令。

FreeDOS命令行
例如在它上面开发的Cute Mouse，就是DOS下最好（体积最小，功能最强）的鼠标驱动程序。而ATTRIB、XCOPY等众多外部命令，不仅比MS-DOS的同类命令效率要高，而且体积不到后者的二分之一甚至几分之一。尤其重要的是，作为自由软件，它的源代码是完全公开的，显然对于需要学习和借鉴的国人，这是最好不过的事了。
FreeDOS与MS-DOS是完全兼容的，因此为它开发的软件基本上都可以直接移植过来在MS-DOS等DOS下使用。
FreeDOS跟MS-DOS相比有一些改进，大部分改进支持了在微软停止支持MS-DOS时不存在的新标准和技术，例如国际化，高级能源管理，内存常驻程序并且综合了ASPI。另外还支持逻辑块寻址和FAT32文件系统（包括从FAT32引导）。尽管由6.22版以前的MS-DOS不能支持这些功能，但是MS-DOS 7.10等的版本有了部分支持。
我们国内外已经开发的绝大多数DOS软件可以在它上面正常的运行。它的功能也十分强大，比如同样支持FAT32分区和大硬盘，部分功能已经远远超过MS-DOS。还有许多其它非常实用的功能，如内置DOSKEY支持、支持极大的内存（最大高达4G）等。至于更多的功能，如长文件名功能等等，正在大家不断的努力下开发着，相信不久后就会成为现实。不仅如此，它的系统启动文件也比MS-DOS等小巧得多。它的核心文件只有一个，再加上一个SYS文件和一个命令处理器command文件，总共才130K，放在启动盘中是十分合适的。

**Comment by shankerwangmiao** [comment]
> FreeDOS与MS-DOS 为FreeDOS设计的DOS软件正在源源不断的推出和发展，不仅有各种外部命令，还有许多其它的增强程序和附件，而且质量既高也很实用，往往超过MS-DOS中的同类命令。
> 
> FreeDOS命令行 例如在它上面开发的Cute Mouse，就是DOS下最好（体积最小，功能最强）的鼠标驱动程序。而ATTRIB、XCOPY等众多外部命令，不仅比MS-DOS的同类命令效率要高，而且体积不到后者的二分之一甚至几分之一。尤其重要的是，作为自由软件，它的源代码是完全公开的，显然对于需要学习和借鉴的国人，这是最好不过的事了。 FreeDOS与MS-DOS是完全兼容的，因此为它开发的软件基本上都可以直接移植过来在MS-DOS等DOS下使用。 FreeDOS跟MS-DOS相比有一些改进，大部分改进支持了在微软停止支持MS-DOS时不存在的新标准和技术，例如国际化，高级能源管理，内存常驻程序并且综合了ASPI。另外还支持逻辑块寻址和FAT32文件系统（包括从FAT32引导）。尽管由6.22版以前的MS-DOS不能支持这些功能，但是MS-DOS 7.10等的版本有了部分支持。 我们国内外已经开发的绝大多数DOS软件可以在它上面正常的运行。它的功能也十分强大，比如同样支持FAT32分区和大硬盘，部分功能已经远远超过MS-DOS。还有许多其它非常实用的功能，如内置DOSKEY支持、支持极大的内存（最大高达4G）等。至于更多的功能，如长文件名功能等等，正在大家不断的努力下开发着，相信不久后就会成为现实。不仅如此，它的系统启动文件也比MS-DOS等小巧得多。它的核心文件只有一个，再加上一个SYS文件和一个命令处理器command文件，总共才130K，放在启动盘中是十分合适的。

确实 FreeDOS 功能上比 MSDOS 要有很多优势，但是似乎二者几乎没有常见的使用场景
