### ISSUE TITLE
安装PHP@7.2时会自动安装python@3.9的版本

### ISSUE THREAD

**Issue by hide-in-code** [tuna/issues#1386]
清华开源软件镜像站的老师你好，我在使用brew安装php7.2的时候，brew会提示并安装python3.9，据我所知php本身并不依赖python的任何东西，且我本地已经安装了python3.7.3的版本，本次的使用安装会导致我原先的环境受到影响而无法正常工作(python3.9比较新，很多其他开源依赖包未支持3.9版本，其次之前工作中的所编写的代码都是基于python3.7，项目迁移会有影响)，暂不清楚这是bug还是有意为之，但对使用的人始终不太友好，希望能提供一种相对便捷合理解决方案。
![image](https://user-images.githubusercontent.com/19517597/142976838-6e8836b8-7ea5-4f7f-9e9a-3a3f27909928.png)

**Comment by shankerwangmiao** [comment]
您好，从您的截图来看，该问题与 TUNA 无关，请您前往 USTC 镜像站寻求相关帮助。

**Comment by hide-in-code** [comment]
从homebrew 官方问到了一些合理的解释
https://github.com/Homebrew/discussions/discussions/2514#discussioncomment-1692308
https://justinmayer.com/posts/homebrew-python-is-not-for-you/
homebrew python 并不适合开发

**Comment by hide-in-code** [comment]
官方已经移除了php7.2对python3.9的依赖
https://github.com/Homebrew/discussions/discussions/2514#discussioncomment-1693794
