### ISSUE TITLE
[镜像请求]  Proxmox Backup Server 的镜像

### ISSUE THREAD

**Issue by darcyg** [tuna/issues#1387]
### 项目名称与简介 (Project introduction)

# proxmox的备份服务器
## 说明
proxmox ve配套的备份服务器，2020年7月发行首个测试版，2020年12月加入proxmox ve 6.4进行支持
支持开源和免费使用
专门用于pve的虚拟机,模版的备份。清华大学的镜像站已经提供pve的镜像，但对pbs等未镜像
wiki文档地址 [pbs.proxmox.com](pbs.proxmox.com)

ISO已经镜像，主要是debian10/11的apt源需要镜像

### 上游地址与镜像方法 (How to mirror)

无订阅备份(非企业版/社区付费版的镜像)
以下是官方文档
https://pbs.proxmox.com/docs/installation.html#proxmox-backup-no-subscription-repository

Proxmox Backup No-Subscription Repository
> deb http://ftp.debian.org/debian bullseye main contrib
> deb http://ftp.debian.org/debian bullseye-updates main contrib
> 
> # PBS pbs-no-subscription repository provided by proxmox.com,
> # NOT recommended for production use
> deb http://download.proxmox.com/debian/pbs bullseye pbs-no-subscription
> 
> # security updates
> deb http://security.debian.org/debian-security bullseye-security main contrib

Proxmox Backup Test Repository

> deb http://download.proxmox.com/debian/pbs bullseye pbstest

Proxmox Backup Client-only Repository

> deb http://download.proxmox.com/debian/pbs-client bullseye main

### 镜像大小 (Mirror size)

官方镜像iso为1G，估计目前数据总共在10G以内

### 备注 (Note)

如有可能
proxmox mail gateway也镜像一下吧。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by ZenithalHourlyRate** [comment]
已同步 pbs 和 pmg。pbstest 和 pmgtest 未同步。

https://mirrors.tuna.tsinghua.edu.cn/proxmox/pbs/
https://mirrors.tuna.tsinghua.edu.cn/proxmox/pbs-client/
https://mirrors.tuna.tsinghua.edu.cn/proxmox/pmg/

你能在 mirror-web 加一些文档吗

**Comment by ZenithalHourlyRate** [comment]
> 能在 mirror-web 加一些文档吗

https://github.com/mirrorz-org/mirrorz-help/commit/4c22f32e5bde8c3d2d36cd505b17a6e66261435a
