### ISSUE TITLE
浏览器访问 MacPorts 镜像出现 ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by laggardkernel** [tuna/issues#1388]
#### 描述

`https://pek.cn.packages.macports.org/macports/packages/` 可以被 `port` 命令行正常使用。但是如果直接在浏览器内访问页面爆出 
`ERR_HTTP2_PROTOCOL_ERROR` 错误. 如果访问 `http` 而不是 `https` 爆出 502 错误。根据 `curl` 下测试 `https` 地址结果

- curl without user agent: 访问成功
- curl with browser  user agent: 访问失败

#### 您的环境（Environment）

- UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36`

**Comment by shankerwangmiao** [comment]
这是正常现象。

**Comment by laggardkernel** [comment]
@shankerwangmiao 可是其他官方提供的镜像站网页是可以访问的。比如 http://atl.us.distfiles.macports.org/。但我们的 https://pek.cn.packages.macports.org/macports/distfiles/ 访问会报错。不过 http://mirrors.tuna.tsinghua.edu.cn/macports/distfiles/ 不受影响。

**Comment by shankerwangmiao** [comment]
是的，您如果需要浏览器访问，可以直接从 http://mirrors.tuna.tsinghua.edu.cn/macports/distfiles/  进入。

**Comment by Harry-Chen** [comment]
@laggardkernel 这是**正常**现象，请不要这样使用。
