### ISSUE TITLE
[镜像请求] Maven Cenral

### ISSUE THREAD

**Issue by CherryRum** [tuna/issues#1389]
### 项目名称与简介 (Project introduction)

我知道大家在2018年讨论过这个镜像设立问题，由于2021年不知道为什么阿里云的Maven仓库少同步很多依赖包。而且不支持浏览器查看包结构。
现有国内存在的几个同步都不是最新的，可能是考虑私有化（云效），也可能是源问题（失败，或者不允许大量同步）
```xml
  <mirror>
      <id>aliyunmaven</id>
      <mirrorOf>central</mirrorOf>
      <name>aliyun</name>
      <url>https://maven.aliyun.com/repository/central</url>
    </mirror>

    <mirror>
      <id>nexus-tencentyun</id>
      <mirrorOf>central</mirrorOf>
      <name>tencent</name>
      <url>http://mirrors.cloud.tencent.com/nexus/repository/maven-public/</url>
    </mirror> 

    <mirror>
      <id>huaweicloud</id>
      <mirrorOf>central</mirrorOf>
      <name>huawei</name>
      <url>https://repo.huaweicloud.com/repository/maven/</url>
   </mirror>  
```
大概看了下2021年可以在`https://issues.sonatype.org/projects/MVNCENTRAL/issues/MVNCENTRAL-7043?filter=allissues`
提交申请，是否有rsync协议，其他的貌似国外用的AWS S3 

### 上游地址与镜像方法 (How to mirror)

地址：
https://maven.apache.org/guides/mini/guide-mirror-settings.html

https://issues.sonatype.org/projects/MVNCENTRAL/issues/MVNCENTRAL-7043?filter=allissues

方法：

-`https://issues.sonatype.org/projects/MVNCENTRAL/issues/MVNCENTRAL-7043?filter=allissues`提交申请 

- `AWS S3 `
- 国内其他应该用的`nexus反代(此方法暂时不考虑)`

### 镜像大小 (Mirror size)

100Gib+

### 备注 (Note)

https://github.com/tuna/issues/issues/59
https://github.com/tuna/issues/issues/100
https://github.com/tuna/issues/issues/329
https://github.com/tuna/issues/issues/438

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [ ] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by skyzh** [comment]
> mirroring the entire central repository is not allowed. (Doing so will get you automatically banned.) 

全量同步是禁止的。

**Comment by CherryRum** [comment]
是的，可能是确实比较大，不知道官方会不会提供一个正式的，貌似国内和华为云合作过，最后尝试了下南京大学镜像还不错。



---原始邮件---
发件人: "Alex ***@***.***&gt;
发送时间: 2021年11月24日(周三) 晚上11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tuna/issues] [镜像请求]  (Issue #1389)




  
mirroring the entire central repository is not allowed. (Doing so will get you automatically banned.)
  
全量同步是禁止的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Harry-Chen** [comment]
我认为 maven central 的文件数量会带来较大的压力。此外，国内似乎并没有很大的访问性问题？

**Comment by CherryRum** [comment]
主要是阿里那边的关闭了浏览器访问，而且貌似最近一段时间的同步会延迟大概24小时（貌似维护开源的不维护了），国内除了阿里云，其他的腾讯云，华为云，新浪（半死），其他公司都是私有的，高校我就找到南京大学有。

**Comment by Harry-Chen** [comment]
> 主要是阿里那边的关闭了浏览器访问，而且貌似最近一段时间的同步会延迟大概24小时（貌似维护开源的不维护了），国内除了阿里云，其他的腾讯云，华为云，新浪（半死），其他公司都是私有的，高校我就找到南京大学有。

我指的是直接到 Maven Central 的连接性似乎比较良好。考虑到我们依旧没有能力维护此镜像（原则上也不进行反代），并且官方禁止全量同步，因此我们依旧不会接受这一请求。如有需要，请使用南京大学的镜像。
