### ISSUE TITLE
osdn怎么用？点进去什么都看不懂

### ISSUE THREAD

**Issue by cok3307788** [tuna/issues#1390]
好歹写个帮助啊，我想查一个文件的最新版本

**Comment by shankerwangmiao** [comment]
请您直接前往 https://osdn.net 浏览感兴趣的项目。当您下载文件时，OSDN 会根据您的地理位置，自动转向合适的镜像站。您或许可以被 OSDN 转向 TUNA 镜像站。这个过程是自动的，您不需要直接前往 TUNA 浏览相关目录。

**Comment by Harry-Chen** [comment]
@cok3307788 鉴于您提问时不友好的语气，我们提出正式的警告。如果再有此类行为，您将被从 TUNA 的 GitHub 组织永久封禁。
