### ISSUE TITLE
[tuna]404 at /homebrew-bottles/bottles/openldap-2.5.8.mojave.bottle.tar.gz

### ISSUE THREAD

**Issue by nick2550123097** [tuna/issues#1391]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
dup with #1392
