### ISSUE TITLE
[镜像请求] Rocky Linux

### ISSUE THREAD

**Issue by CoiaPrant** [tuna/issues#1393]
### 项目名称与简介 (Project introduction)

Rocky Linux
Rocky Linux 是一个社区企业操作系统。Rocky Linux 由 CentOS 项目的创始人 Gregory Kurtzer 领导

### 上游地址与镜像方法 (How to mirror)

上游地址 http://download.rockylinux.org/pub/rocky/

### 镜像大小 (Mirror size)

不清楚

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by phy25** [comment]
https://github.com/tuna/issues/issues/1281
