### ISSUE TITLE
[镜像请求] AlmaLinux

### ISSUE THREAD

**Issue by CoiaPrant** [tuna/issues#1394]
### 项目名称与简介 (Project introduction)

AlmaLinux
AlmaLinux OS 是一个开源的、社区驱动的 Linux 操作系统，它填补了 CentOS Linux 稳定版本停产留下的空白。AlmaLinux OS 是 RHEL® 的 1:1 二进制兼容分支，由社区指导和构建。

### 上游地址与镜像方法 (How to mirror)

镜像方法 https://wiki.almalinux.org/Mirrors.html

### 镜像大小 (Mirror size)

未知

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

### 注意事项 (Confirmations)

- [X] 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。
I am sure that this repo has NEVER been discussion at https://github.com/tuna/issues.

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

**Comment by skyzh** [comment]
Hi, 您是否有翻阅过 issue 列表？

Dup with https://github.com/tuna/issues/issues/1258

**Comment by Harry-Chen** [comment]
> 我已确认这个镜像源从未在 https://github.com/tuna/issues 讨论过。

请不要把它当作软件的 EULA 不看就勾选。
