### ISSUE TITLE
tuna镜像站提供的各linux发行版的lxc-image是否有使用说明？

### ISSUE THREAD

**Issue by Frodez** [tuna/issues#1395]
我今天想试用一下镜像站提供的[debian-sid-lxc-image](https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/sid/amd64/cloud/20211127_05%3A24/)，但是进入后登录需要密码，然而这个image是已经安装好了的，并没有配置密码的选项。现在面对登录框无从下手。

**Comment by skyzh** [comment]
在 Google 搜索“lxc debian image password”，第一条就是使用方法，没有 root 密码；也可以使用 `lxc-attach -n <container> passwd` 设置。

https://wiki.debian.org/LXC#root_passwords

镜像站只提供镜像服务，此类问题应该咨询上游软件源。

**Comment by Frodez** [comment]
> 在 Google 搜索“lxc debian image password”，第一条就是使用方法，没有 root 密码；也可以使用 `lxc-attach -n <container> passwd` 设置。
> 
> https://wiki.debian.org/LXC#root_passwords
> 
> 镜像站只提供镜像服务，此类问题应该咨询上游软件源。

十分感谢，打扰了。
