### ISSUE TITLE
希望增加mongodb的镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#14]
mongodb记得以前好像用的是CDN，但是最近似乎撤了，官方网站下载和更新巨慢无比。

附上mongodb官方仓库地址: 

Ubuntu: https://docs.mongodb.org/master/tutorial/install-mongodb-on-ubuntu/

RHEL: https://docs.mongodb.org/master/tutorial/install-mongodb-on-red-hat/#install-mongodb-community-edition

Debian: https://docs.mongodb.org/master/tutorial/install-mongodb-on-debian/#install-mongodb-community-edition

希望同时镜像3.0和3.2版本。

**Comment by huiyiqun** [comment]
Under progress but need to solve a problem tuna/tunasync#7

**Comment by bigeagle** [comment]
http://mirrors.tuna.tsinghua.edu.cn/mongodb/
We've downloaded version 3.0 and 3.2, for RHEL, Debian and Ubuntu.

Please give a test, and I'll finish the document tomorrow.

**Comment by abcfy2** [comment]
我这边只有ubuntu 14.04环境，测试了3.0和3.2版本，都没有问题。

**Comment by zxdvd** [comment]
debian jessie的3.0,3.2,stable目录里都是空的，不知道是暂时的还是怎么回事。

http://mirrors.4.tuna.tsinghua.edu.cn/mongodb/apt/debian/dists/jessie/mongodb-org/3.2/main/binary-amd64/

**Comment by abcfy2** [comment]
应该是官方仓库没有jessie的软件包了。去官方仓库看了下，只有3.3版本和unstable。

**Comment by bigeagle** [comment]
是的，官方没有 jessie 的 3.2 和 3.0 的包。
我把 jessie 从帮助文档里去掉了。
