### ISSUE TITLE
ELK脚本需要更新下

### ISSUE THREAD

**Issue by bubbleatgit** [tuna/issues#140]
elk上游服务器由packages.elastic.co变更为artifacts.elastic.co

至于镜像的方法貌似也跟以前不一样了,至于怎么搞,我也不会..

**Comment by huiyiqun** [comment]
有官方的提示吗？关于新的镜像方法

**Comment by bubbleatgit** [comment]
@huiyiqun  没找到官方的提示。

**Comment by abcfy2** [comment]
看了下官方文档，rpm和deb仓库的路径迁移到了artifacts.elastic.co，但是其他一些组件，比如ES-hadoop却在download.elastic.co

**Comment by abcfy2** [comment]
不妨这么处理吧，原来的ELK依旧保留，新开一个坑`elastic/`，将新版本的Elastic Stack 5.0家族全部入新坑算了。

**Comment by bigeagle** [comment]
赞成～
我们周日集中开发的时候搞～

**Comment by abcfy2** [comment]
ElasticStack 5.0版本下载页面: https://www.elastic.co/downloads

这几个组件如果支持rpm/deb包的话，都会有个 ***Repositories in the Guide*** 页面，里面会显示组件的仓库配置，同步这里的仓库就可以了。

**Comment by bigeagle** [comment]
搞定～
https://mirrors.tuna.tsinghua.edu.cn/elasticstack/
