### ISSUE TITLE
PC端下载镜像文件，返回异常提示

### ISSUE THREAD

**Issue by chenchunlai** [tuna/issues#1400]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用PC端浏览器下载镜像，返回如下结果：
![image](https://user-images.githubusercontent.com/35135934/145503675-a3dfec21-27ab-47f0-b492-67a17d44d292.png)

### 期望的现象（What you expected to happen）

能够正常下载

### 如何重现此问题（How to reproduce it）

举例：用PC浏览器访问 https://mirrors.tuna.tsinghua.edu.cn/virtualbox/virtualbox-Win-latest.exe

### 操作系统（OS Version）

windows 10

### 浏览器（如果适用）（Browser version, if applicable）

Chrome 96.0.4664.93 64位

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by phy25** [comment]
您尝试过其它浏览器、隐身模式、其它网络环境吗？我试了一下 Windows Chrome 并没有复现哦。

**Comment by shankerwangmiao** [comment]
您好，相关反馈已经通过邮件单独回复了。
