### ISSUE TITLE
Specific files are 404 on BFSU (but normal on original TUNA server)

### ISSUE THREAD

**Issue by Icenowy** [tuna/issues#1401]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.bfsu.edu.cn/pypi/web/packages/40/e0/ad1edd74311831ca71b32a5b83352b490d78d11a90a1cde04e1b6830e018/aiosqlite-0.17.0.tar.gz is 404, but https://mirrors.tuna.edu.cn/pypi/web/packages/40/e0/ad1edd74311831ca71b32a5b83352b490d78d11a90a1cde04e1b6830e018/aiosqlite-0.17.0.tar.gz is okay

### 期望的现象（What you expected to happen）

This file should be downloadable.

### 如何重现此问题（How to reproduce it）

`wget https://mirrors.bfsu.edu.cn/pypi/web/packages/40/e0/ad1edd74311831ca71b32a5b83352b490d78d11a90a1cde04e1b6830e018/aiosqlite-0.17.0.tar.gz`

### 其他需要说明的事项（Anything else we need to know）

Checking previous issues shows that multiple files in pypi/ are reported, see #1378 #1374 etc.

**Comment by shankerwangmiao** [comment]
已经修理了。
