### ISSUE TITLE
Would you please include the python package of Weibull in your conda install source?

### ISSUE THREAD

**Issue by vvorrn** [tuna/issues#1404]
Would you please include the python package of Weibull in your conda install source?

For the Weibull package refer to this:
https://weibull.readthedocs.io/en/v0.0.12/

**Comment by ZenithalHourlyRate** [comment]
The document mentions conda only when referring to its dependencies `pandas`, `numpy`, `matplotlib`, and `scipy`. Its use case may be using conda to install these _difficult_ packages and then using pip to install weibull.

Also I have not found any weibull package distributed by anaconda.
