### ISSUE TITLE
[镜像请求] Qt6

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [tuna/issues#1405]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

现在已经有了 Qt5 的镜像，请添加最近新发布的 Qt6 的镜像。

### 上游地址与镜像方法 (How to mirror)

应该与 Qt5 相同或相差不大

### 镜像大小 (Mirror size)

应该与 Qt5 相同或相差不大

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by skyzh** [comment]
这个不是 Qt6 吗？

https://mirrors.tuna.tsinghua.edu.cn/qt/official_releases/qt/6.2/

**Comment by ZenithalHourlyRate** [comment]
镜像中已有 Qt6

> Due to The Qt Company offering changes, open source offline installers are not available any more since Qt 5.15. Read more about offering changes in the https://www.qt.io/blog/qt-offering-changes-2020 blog.
>
> If you need offline installers, please consider our new Qt for Small Business offering: https://www.qt.io/blog/available-now-qt-for-small-businesses

来源：https://mirrors.tuna.tsinghua.edu.cn/qt/official_releases/qt/6.2/6.2.2/OFFLINE_README.txt

与此同时，参考在线安装器的文档 https://www.qt.io/blog/qt-online-installer-4.0.1-1-released 可知可以在安装器中指定镜像站。

**Comment by Ravenclaw-OIer** [comment]
那旁边的“常用软件安装链接”那个，需不需要把 Qt6 加进去。

那个里面就只有 Qt5
