### ISSUE TITLE
网页无法打开

### ISSUE THREAD

**Issue by Gisele515** [tuna/issues#1406]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/anaconda/anaconda
网页无法打开

### 期望的现象（What you expected to happen）

网页可以正常访问

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/anaconda/anaconda
网页无法打开

**Comment by skyzh** [comment]
这个目录原本就不存在，您是从哪里找到这个链接的？

**Comment by Gisele515** [comment]
您好，非常感谢您的回复，


我是在使用附件中的yml文件创建虚拟环境时，程序报错，发现的这个链接





使用的创建环境命令：
conda env create -f conda_env_vggish.yml




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tuna/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tuna/issues] 网页无法打开 (Issue #1406)





 
这个目录原本就不存在，您是从哪里找到这个链接的？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shankerwangmiao** [comment]
请在 github 的页面上上传 conda_env_vggish.yml

**Comment by Gisele515** [comment]
您好，文件上传总是出错









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tuna/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tuna/issues] 网页无法打开 (Issue #1406)





 
请在 github 的页面上上传 conda_env_vggish.yml
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shankerwangmiao** [comment]
请您直接将文件内容粘贴上来，同时提供完整的执行的命令和命令的输出。
