### ISSUE TITLE
[镜像请求] BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [tuna/issues#1407]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Name: BioArchLinux
Introduction: Arch Community for Biologists & Arch Repository for Biological Software
Official web: https://bioarchlinux.org 
Github Repo: https://github.com/BioArchLinux/Packages

### 上游地址与镜像方法 (How to mirror)
```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```
### 镜像大小 (Mirror size)

24G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by starsareintherose** [comment]
I've updated the rsync method

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.cernet.edu.cn/list/bioarchlinux

国内镜像已较多，在有更多需求时可以重开该 issue。

**Comment by starsareintherose** [comment]
申请重开，已经失去了一个镜像
