### ISSUE TITLE
OrangePi One的armbian系统镜像找不到

### ISSUE THREAD

**Issue by kaidegit** [tuna/issues#1408]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

orangepi one的armbian镜像似乎不见了？不论是focal还是bullseye，跳转到的链接均显示404，从镜像站的获取安装镜像处也找不到orangepi one的armbian。

### 期望的现象（What you expected to happen）

能正常地跳转到镜像站下载到系统镜像

### 如何重现此问题（How to reproduce it）

https://www.armbian.com/orange-pi-one/
从armbian官网该开发板页下载镜像

**Comment by shankerwangmiao** [comment]
经查，上游及其它镜像站上也没有此文件。这些文件可能已经被官方移除。

您可以从官方的历史归档中查找您需要的文件：https://armbian.hosthatch.com/archive/orangepione/archive/
