### ISSUE TITLE
TensorFlow镜像

### ISSUE THREAD

**Issue by ppwwyyxx** [tuna/issues#141]
#### 项目名称与简介(Project Intro.)
TensorFlow. 流行的图计算/机器学习框架.

#### 上游地址与镜像方法(How to Mirror)
https://ci.tensorflow.org/　
包含了stable/nightly 的whl binary.　应该用permanent link抓下来就够用了

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
一个whl<200MB. 根据不同平台 x CPU/GPU x python版本大概有一二十个whl.

想assign给自己但是没有权限..

**Comment by bigeagle** [comment]
2333, 直接给 tuna/tunasync-scripts 发 PR?

**Comment by bigeagle** [comment]
开始下载了 tuna/tunasync-scripts@74ac686202cab17c31ab8f3e9a4f4927049b9462

**Comment by bigeagle** [comment]
https://mirrors.tuna.tsinghua.edu.cn/tensorflow/linux/gpu/
