### ISSUE TITLE
erlang-solutions 镜像库缺少公钥

### ISSUE THREAD

**Issue by dp9212** [tuna/issues#1410]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

ubuntu 20.04 添加erlang镜像库地址：deb https://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal contrib
更新报镜像库未签名，无法拉取软件列表，在库中没有找到公钥，以下为错误信息
root@dp9212:/opt# apt update
Hit:1 http://mirrors.aliyun.com/ubuntu focal InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu focal-updates InRelease
Get:3 http://mirrors.aliyun.com/ubuntu focal-backports InRelease [108 kB]
Hit:4 http://mirrors.aliyun.com/ubuntu focal-security InRelease
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal InRelease
Get:6 http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal Release [3,132 B]
Get:7 http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal Release.gpg [833 B]
Ign:7 http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal Release.gpg
Reading package lists... Done
W: GPG error: http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D208507CA14F4FCA
E: The repository 'http://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@dp9212:/opt#

### 期望的现象（What you expected to happen）

能否在 https://mirrors.tuna.tsinghua.edu.cn/erlang-solutions 库中添加公钥呢

### 如何重现此问题（How to reproduce it）

在 /etc/apt/sources.list 末尾追加 
deb https://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/ubuntu focal contrib
使用sudo apt update 更新

### 操作系统（OS Version）

ubuntu 20.04.3

### 其他环境（Other environments）

erlang

**Comment by ZenithalHourlyRate** [comment]
关于镜像公钥，可参考 #1114 #1223

我们会在镜像帮助中给出直接从上游获取公钥的方法。

**Comment by dp9212** [comment]
感谢
