### ISSUE TITLE
[镜像请求] ohmyzsh

### ISSUE THREAD

**Issue by aaronliu0130** [tuna/issues#1411]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

著名终端主题工具。~~如果你用zsh却没听说过omz，那么你就是假程序员~~
官方简介：
一个令人愉快的社区驱动的（有2000多个贡献者）框架，用于管理你的zsh配置。包括300多个可选的插件（rails, git, macOS, hub, docker, homebrew, node, php, python等），140多个主题来调剂你的早晨，还有一个自动更新工具，这样就能很容易地跟上社区的最新更新。

### 上游地址与镜像方法 (How to mirror)

git: https://github.com/ohmyzsh/ohmyzsh.git

### 镜像大小 (Mirror size)

14003152B(13.3MB)

### 备注 (Note)

所以说三个镜像站有啥区别

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by skyzh** [comment]
dup w/ https://github.com/tuna/issues/issues/32 ?

**Comment by ZenithalHourlyRate** [comment]
已经添加，可以通过 
```
git -C ~/.oh-my-zsh remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git
git -C ~/.oh-my-zsh pull
```
切换到 TUNA 镜像源

**Comment by aaronliu0130** [comment]
> dup w/ #32 ?

emm没搜到hh

**Comment by aaronliu0130** [comment]
> 已经添加，可以通过
> 
> ```
> git -C ~/.oh-my-zsh remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git
> git -C ~/.oh-my-zsh pull
> ```
> 
> 切换到 TUNA 镜像源

```
Cloning into 'ohmyzsh'...
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/ohmyzsh.git/' not found
```
怎么没找到

**Comment by ZenithalHourlyRate** [comment]
> > 已经添加，可以通过
> > ```
> > git -C ~/.oh-my-zsh remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git
> > git -C ~/.oh-my-zsh pull
> > ```

注意路径是 `/git/ohmyzsh.git`


> ```
> Cloning into 'ohmyzsh'...
> fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/ohmyzsh.git/' not found
> ```
> 
> 怎么没找到

**Comment by aaronliu0130** [comment]
好的，谢谢

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by waytoarcher** [comment]
快捷安装命令：
`wget -O - https://github.com/ohmyzsh/ohmyzsh/raw/master/tools/install.sh | bash - || true`
如果用镜像站点，能直接使用吗？
```bash
wget https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git/master/tools/install.sh  
--2022-12-30 13:56:19--  https://mirrors.tuna.tsinghua.edu.cn/git/ohmyzsh.git/master/tools/install.sh
Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.15.130, 2402:f000:1:400::2
Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.15.130|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-30 13:56:19 ERROR 404: Not Found.
```

**Comment by ZenithalHourlyRate** [comment]
> 如果用镜像站点，能直接使用吗？

镜像站上镜像的是 bare repo，并不直接存在 install.sh 的文件。

**Comment by waytoarcher** [comment]
> > 如果用镜像站点，能直接使用吗？
> 
> 镜像站上镜像的是 bare repo，并不直接存在 install.sh 的文件。

这种镜像方式改变了使用脚本的方式，不太合适。有没有考虑将git导入到gitlab的服务中？

**Comment by ZenithalHourlyRate** [comment]
> 这种镜像方式改变了使用脚本的方式，不太合适。有没有考虑将git导入到gitlab的服务中？

gitlab 攻击面大，不考虑使用。
