### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by wozuishuai997** [tuna/issues#1412]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

ububtu50.10 5.8.0-63

### 上游地址与镜像方法 (How to mirror)

不清楚

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> ububtu50.10 5.8.0-63

这是什么

**Comment by wozuishuai997** [comment]
应该是 ubuntu20.10 5.8.0-63我们之前使用了ubuntu20.10 5.8.0-25 但是这个版本停止了维护也无法再更新  我们需要一个相同版本的系统镜像发送自我的盖乐世
-------- 原始信息 --------发件人： Zenithal ***@***.***> 日期: 2022/1/9  20:12  (GMT+08:00) 收件人： tuna/issues ***@***.***> 抄送： wozuishuai997 ***@***.***>, Author ***@***.***> 主题： Re: [tuna/issues] [镜像请求]  (Issue #1412) 



ububtu50.10 5.8.0-63



这是什么

**Comment by ZenithalHourlyRate** [comment]
> 应该是 ubuntu20.10 5.8.0-63我们之前使用了ubuntu20.10 5.8.0-25 但是这个版本停止了维护也无法再更新  我们需要一个相同版本的系统镜像发送自我的盖乐世 --

我们跟随 ubuntu 上游更新而更新，且 old-release [内容较大](https://mirrorz.org/list/ubuntu-old-releases)。

如果要临时使用 20.10 的镜像源，可参考 https://mirrors.ustc.edu.cn/ubuntu-old-releases

**Comment by shankerwangmiao** [comment]
Ubuntu 20.10 是 Ubuntu 的短期支持版，其支持期限是 1 年。也就是说，到 21 年 10 月份，其软件仓库就不再更新和维护，并随后会被移除。

如果您需要安装软件，您可以直接使用 old-releases 镜像。如果您需要更新系统上已有的软件，建议您等到 4 月份后直接更新 22.04 长期支持版。
