### ISSUE TITLE
[镜像请求] TrueNAS SCALE 插件与 ISO

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [tuna/issues#1414]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

TrueNAS SCALE 是免费的开源超融合基础架构（HCI）解决方案。和 TrueNAS CORE（即原来基于 FreeBSD 的 FreeNAS）相比，TrueNAS SCALE提供了集群系统，以及横向扩展存储的能力。

### 上游地址与镜像方法 (How to mirror)

因为 TrueNAS 没有提供 rsync，所以只能用传统的 lftp

https://download.truenas.com/

### 镜像大小 (Mirror size)

~25G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
TrueNAS 是商业公司的产品，提出者能否与官方确认是否可以镜像?

根据其服务条款，其相应内容可以被个人非商业使用，并严禁分发

These Terms of Use permit you to use the Website(s) for your personal, non-commercial use only. You must not reproduce, **distribute**, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website(s), except as follows:
...[omitted]...

对于是否能使用 truenas 这一名称也有要求

The Company name, the terms **TrueNAS**, iX, iXsystems, and all related names, logos, product and service names, designs, and slogans are trademarks of the Company or its affiliates or licensors. You **must not use such marks without the Company’s prior written permission.**

参考 https://www.truenas.com/terms/

**Comment by Harry-Chen** [comment]
如无进一步反馈，我们不会考虑镜像
