### ISSUE TITLE
[镜像请求] 新增newlib或sourceware FTP站点镜像

### ISSUE THREAD

**Issue by imi415** [tuna/issues#1415]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Newlib是一个知名的C标准库实现，常用于嵌入式系统中

[首页](https://sourceware.org/newlib/)

### 上游地址与镜像方法 (How to mirror)

https://sourceware.org/newlib/
Download section中列出了FTP站点 sourceware.org 的文件列表

目前的官方[镜像列表](https://sourceware.org/mirrors.html)

### 镜像大小 (Mirror size)

未知

### 备注 (Note)

目前镜像站存在托管于sourceware.org的项目如glibc及binutils，是以git仓库形式镜像的。-> #726 

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by imi415** [comment]
sourceware.org 包含除newlib外其他项目，请一并考虑是否镜像全站

**Comment by ZenithalHourlyRate** [comment]
https://github.com/bminor/newlib

bminor 的一系列 repo 应该足够使用。

**Comment by imi415** [comment]
该镜像为git仓库镜像，非FTP镜像站点，提供的内容并不相同

**Comment by ZenithalHourlyRate** [comment]
找到一个上游 `rsync://mirrors.kernel.org/sourceware/`

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/sourceware/

不过并不是全量镜像，由于之前已经有 [cygwin 镜像](https://mirrors.tuna.tsinghua.edu.cn/cygwin/)，故而过滤了 cygwin 目录，基于此原因，不申请加入官方镜像列表。

直接将 `/cygwin` 302 重定向到 `/sourceware/cygwin` 并不可行，这会让下游无法使用 `rsync://mirrors.tuna.tsinghua.edu.cn/cygwin`

在 `/sourceware/cygwin` 中加入 `/cygwin` 软链接也不可行，这会让下游无法使用 `rsync://mirrors.tuna.tsinghua.edu.cn/sourceware`

**Comment by imi415** [comment]
Closing as request fullfilled

**Comment by ZenithalHourlyRate** [comment]
> 不过并不是全量镜像，由于之前已经有 [cygwin 镜像](https://mirrors.tuna.tsinghua.edu.cn/cygwin/)，故而过滤了 cygwin 目录

现已在 TUNA 将 cygwin 合并进入 sourceware 镜像，保留了首页项目，以及保留了用户 https/rsync 的兼容性

**Comment by imi415** [comment]
https://sourceware.org/mirrors.html 鉴于现在镜像内容已完整，或许可以重新考虑加入官方镜像列表？

**Comment by ZenithalHourlyRate** [comment]
> Hi, 此站点官方的rsync上游是 `rsync rsync://sourceware.org/ftp`，似乎比kernel.org的可靠一点？

```
sent 668.57K bytes  received 794.52M bytes  4.33M bytes/sec
total size is 360.76G  speedup is 453.68
```

看起来还可以，已经切换过去了

**Comment by ZenithalHourlyRate** [comment]
> 或许可以重新考虑加入官方镜像列表？

我半年前（Date: Sat, 31 Dec 2022）联系了 sourcemaster@sourceware.org，不过没得到回复

**Comment by FlyGoat** [comment]
> > 或许可以重新考虑加入官方镜像列表？
> 
> 我半年前（Date: Sat, 31 Dec 2022）联系了 [sourcemaster@sourceware.org](mailto:sourcemaster@sourceware.org)，不过没得到回复

已联系相关人员解决: https://sourceware.org/mirrors.html

**Comment by FlyGoat** [comment]
同时要求他们在mirrorlist上增加了mirrorz的链接以方便分流。
