### ISSUE TITLE
[镜像请求] Mellanox Technologies Ltd. Public Repository

### ISSUE THREAD

**Issue by charles820** [tuna/issues#1416]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

The Mellanox Technologies Ltd. public repository provides all packages required for InfiniBand, Ethernet and RDMA.

### 上游地址与镜像方法 (How to mirror)

yum/apt 仓库
https://www.mellanox.com/support/mlnx-ofed-public-repository
https://linux.mellanox.com/public/repo/

### 镜像大小 (Mirror size)

未知

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [x] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by phy25** [comment]
这个仓库包含的是开源软件吗？是否允许再分发呢？

**Comment by Harry-Chen** [comment]
OFED 套件并非开源软件，同时也有自己的 CDN，国内下载速度并不缓慢。
