### ISSUE TITLE
[BFSU] 特定包在 bfsu 的 pypi 为 404, tuna 正常

### ISSUE THREAD

**Issue by rmb122** [tuna/issues#1417]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.bfsu.edu.cn/pypi/web/simple/aiosmtplib/
https://mirrors.bfsu.edu.cn/pypi/web/packages/02/53/d67f5e2cf8d46bed77ce823a4bac3f4be56e91dde37036e1e76046bd60c1/aiosmtplib-1.1.6.tar.gz#sha256=d138fe6ffecbc9e6320269690b9ac0b75e540ef96e8f5c77d4a306760014dce2

aiosmtplib 在 bsft 无法正常下载, 

https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/aiosmtplib/
https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/02/53/d67f5e2cf8d46bed77ce823a4bac3f4be56e91dde37036e1e76046bd60c1/aiosmtplib-1.1.6.tar.gz#sha256=d138fe6ffecbc9e6320269690b9ac0b75e540ef96e8f5c77d4a306760014dce2

tuna 正常

### 期望的现象（What you expected to happen）

正常下载

### 如何重现此问题（How to reproduce it）

```
curl https://mirrors.bfsu.edu.cn/pypi/web/packages/02/53/d67f5e2cf8d46bed77ce823a4bac3f4be56e91dde37036e1e76046bd60c1/aiosmtplib-1.1.6.tar.gz
```

**Comment by shankerwangmiao** [comment]
已经处理完毕。
