### ISSUE TITLE
Manjaro-cd镜像为空

### ISSUE THREAD

**Issue by issaccv** [tuna/issues#1418]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

manjaro主站cdn从osdn切换为cdn77，并且osdn删除了manjaro相关内容
导致tuna mirrors的manjaro-cd同步异常

### 期望的现象（What you expected to happen）

manjaro-cd正确同步或删除manjaro-cd

### 如何重现此问题（How to reproduce it）

访问 https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/m/ma/manjaro/

manjaro下载页(xfce)
https://manjaro.org/downloads/official/xfce/

**Comment by skyzh** [comment]
> 删除manjaro-cd

这个包含在 OSDN 里，应该不能单独删除

> manjaro-cd正确同步

manjaro-cd 的新上游之前讨论过多次，但都不太好同步，可以看一下 issue 记录。

**Comment by shankerwangmiao** [comment]
应该可以把首页的 manjaro-cd 删掉
