### ISSUE TITLE
[镜像请求] nginx.io

### ISSUE THREAD

**Issue by Showfom** [tuna/issues#1419]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Nginx.io - A nginx Debian / Ubuntu repository 

### 上游地址与镜像方法 (How to mirror)

```
rsync rsync://mirrors.xtom.com/repo/sb/
```

### 镜像大小 (Mirror size)

91 MB

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
已经在 TUNA 和 BFSU 上线。

**Comment by Harry-Chen** [comment]
@Showfom 我注意到 index page 是用户帮助，是不是考虑修改一下，引导用户到源站下载 pgp key？

**Comment by Showfom** [comment]
@Harry-Chen 我们的 pgp key 同时也会同步在这个 repo 的，应该不需要更改

**Comment by Harry-Chen** [comment]
> @Harry-Chen 我们的 pgp key 同时也会同步在这个 repo 的，为了防止有些国内的网络连接国外不通畅，应该不需要更改

这么做是通行操作，即签名 key 应该由上游分发，已验证镜像站的文件没有被篡改或者损坏。

**Comment by Showfom** [comment]
@Harry-Chen 也有道理，下次更新的时候更换下 URL =。=
