### ISSUE TITLE
关于mysql

### ISSUE THREAD

**Issue by JayceCao** [tuna/issues#142]
不好意思，我是新手，不知道mysql的仓库配置文件在哪里，也没有help，烦请问配置文件在哪里呀？还有，为什么有的项目有help，有的项目没有help？

**Comment by bigeagle** [comment]
没有help的原因有两个:
1. 没人写
2. 有人请求搭了，用了，没有下文了，最后我们自己也不知道怎么用

mysql 属于后者

**Comment by huiyiqun** [comment]
可以去mysql官网看看他们的repo怎么用 把url改成我们的

如果可以最好给我们pr一个help

bigeagle <notifications@github.com>于2016年11月5日周六 下午9:42写道：
