### ISSUE TITLE
android kernel是不是不是最新的？找不到build/build.sh

### ISSUE THREAD

**Issue by wudehua2016** [tuna/issues#1421]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我按照谷歌的文档进行安卓内核编译时，发现找不到build.sh。我的操作过程为：
git clone https://aosp.tuna.tsinghua.edu.cn/kernel/msm.git
 git checkout remotes/origin/android-msm-bonito-4.9-android12-qpr1

猜测的原因是没有更新到最新的吧。

### 期望的现象（What you expected to happen）

能够找到build.sh

### 如何重现此问题（How to reproduce it）

https://android.googlesource.com/kernel/manifest
相关branch可能需要根据文档

### 操作系统（OS Version）

ubuntu

**Comment by shankerwangmiao** [comment]
经查，上游 https://android.googlesource.com/kernel/msm.git 亦无此文件。建议您检查您是否参考了正确的文档。
