### ISSUE TITLE
[镜像请求] CircleLinux 社区企业级Linux操作系统

### ISSUE THREAD

**Issue by bella485** [tuna/issues#1422]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

名称: CircleLinux
介绍如下：
Circle Linux 是国际化社区驱动的开源软件，使命在与努力专注于围绕 Linux 平台提供更强大的开源生态。
提供企业级、生产环境就绪的 Linux 发行版。
Global Community-driven Opensource software effort focus on delivering a robust open source ecosystem around a Linux platform.
bring you Enterprise-grade, Production-ready Linux Distro.
官网：www.cclinux.org
GitHub：https://github.com/circle-linux

### 上游地址与镜像方法 (How to mirror)

rsync -avh rsync://msync.cclinux.org/circle/pub/ 

### 镜像大小 (Mirror size)

目前是400G，建议预留，随着全新版本的发布容量随之可能会到600G左右。

### 备注 (Note)

Hi ， 各位老师，同学。 提前预祝农历新年快乐！！！

非常感谢你们提供的镜像服务，希望可以早日使用Tuna 提供的CircleLinux的Mirror 。 

Best Regards ！

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by earthloong** [comment]
Come on! 期待早日上线！

**Comment by rouzer-zhou** [comment]
I hope more and more people will use Circle Linux OS, which is free and easy to use.
If you are interested in it, you also can join Circle Linux community.

**Comment by James6xie** [comment]
https://bugzilla.cclinux.org/show_bug.cgi?id=9

欧洲用户这边也是比较慢， mirrors 站点支持需要多联系一些。 希望tuna的mirrors也能支持，惠及国内用户。

**Comment by James6xie** [comment]
@shankerwangmiao  Hi , we noticed you closed issuse circlelinux request.

**Comment by Harry-Chen** [comment]
参照 #741 的第六条，以与 #1281 相同的理由拒绝。

**Comment by James6xie** [comment]
您好，centos 8 已经停止服务，现在国内centos用户在寻找合适的替代版本，在用户交流群里面，大家对tuna的镜像体验都非常不错。
包括我们都是tuna镜像的粉丝。

感谢tuna的同学添加同步，开源同行，感恩帮助。

**Comment by salmon5** [comment]
这个发行版社区不够活跃，RHEL8.8/9.2已经更新很久了，Circle Linux还停留在8.7/9.1。
勘误表最后的日期是2022-01-20，也看上去社区不够活跃。

**Comment by James6xie** [comment]
> 这个发行版社区不够活跃，RHEL8.8/9.2已经更新很久了，Circle Linux还停留在8.7/9.1。 勘误表最后的日期是2022-01-20，也看上去社区不够活跃。
看着是已经发布了，rhel 8 五月低发布的，间隔不到一个月差不多哈哈哈
