### ISSUE TITLE
proposal: 移除 AUR 反代

### ISSUE THREAD

**Issue by Xuanwo** [tuna/issues#1424]
## 现状

目前 TUNA 提供的服务是 AUR **反代**，只能代理托管在 AUR 上的 git repo，不能代理任何实际的资源，比如说下载来自 Github/Gitlab 等服务的资源。

该*镜像*的存在引起了很多用户混淆，可观察到的反馈包括但不限于：

- https://github.com/tuna/issues/issues/649
- https://github.com/tuna/issues/issues/886
- https://github.com/tuna/issues/issues/912
- https://github.com/tuna/issues/issues/956
- https://github.com/tuna/issues/issues/1013
- https://github.com/tuna/issues/issues/1173
- https://github.com/tuna/issues/issues/1234

## 提案

AUR 反代的功能并不符合用户预期，所以我在此提议删除 AUR 反代。

### 支持意见

- 不需要再维护一个实际上无法工作的 *镜像*
- AUR 无有效的数据同步方式，只能代理，不能镜像

### 反对意见

- 可能存在用户就是需要下载 PKGBUILD？（欢迎在评论区反馈这样的使用案例）

## 迁移方案

可能的迁移方案如下：

- 在各个渠道发布移除反代通知
- 在指定的时间点到达后，将所有 AUR 请求重定向至 aur.archlinux.org
- 彻底删除 AUR 相关的服务

**Comment by oldherl** [comment]
可能的 use case：
中国某军事管制区内的某用户（你明白我在说谁）无法访问aur，他可能会使用tuna的反代并配合其他的github国内反代服务来获取部分的aur资源。

**Comment by oldherl** [comment]
另一个可能的 use case：
用来安装微信、wps等国内资源的aur包

**Comment by zhullyb** [comment]
AUR 的单个 git repo 最大限制也就200KB左右，就算从 aur.archlinux.org 的下载速度只有 30 KB/s，也只需要6秒就能下完，在此之后 tuna 的 AUR 反代就没有更大的作用。这么一个反代似乎并不能帮助国内用户获得更好的使用体验。

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-aur/

**Comment by xiangsheng** [comment]
能否在停止服务通知中说明如何恢复aur的初始设置。我将yay的配置文件中aur地址改为
```
"aururl": "https://aur.archlinux.org",
```
之后，再使用yay时仍然会遇到如下错误。
```
error fetching vorta: fatal: unable to update url base from redirection:
  asked for: https://aur.tuna.tsinghua.edu.cn/vorta.git/info/refs?service=git-upload-pack
   redirect: https://aur.archlinux.org/vorta.git/info/refs 
         context: exit status 1
```
似乎仍然有其他地方地址使用的是tuna地址，但是由于tuna的aur页面已经删除，我已经无法回忆出当时到底还修改了哪些配置文件。

**Comment by zhullyb** [comment]
yay --aururl "https://aur.archlinux.org" --save

________________________________
发件人: Wang Xiangsheng ***@***.***>
发送时间: 2022年2月9日星期三 下午12:14
收件人: tuna/issues
抄送: zhullyb; Comment
主题: Re: [tuna/issues] proposal: 移除 AUR 反代 (Issue #1424)


能否在停止服务通知中说明如何恢复aur的初始设置。我将yay的配置文件中aur地址改为

"aururl": "https://aur.archlinux.org",



之后，再使用yay时仍然会遇到如下错误。

error fetching vorta: fatal: unable to update url base from redirection:

  asked for: https://aur.tuna.tsinghua.edu.cn/vorta.git/info/refs?service=git-upload-pack

   redirect: https://aur.archlinux.org/vorta.git/info/refs

         context: exit status 1



似乎仍然有其他地方地址使用的是tuna地址，但是由于tuna的aur页面已经删除，我已经无法回忆出当时到底还修改了哪些配置文件。

―

**Comment by xiangsheng** [comment]
@zhullyb 谢谢，我发现之前的错误是cache导致的。

**Comment by BenSYZ** [comment]
写了个简单的脚本：
https://gist.github.com/BenSYZ/c18179a4e97dde32c8f1a10df9a90b1e

**Comment by jiegec** [comment]
AUR 反代不解决 GitHub 的问题。
