### ISSUE TITLE
PyPI 镜像同步问题

### ISSUE THREAD

**Issue by ricky8955555** [tuna/issues#1425]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我的包（cyansdk）已经向 PyPI 推送了最新版（v0.2.0）有几个小时了，但是未同步到 tuna 镜像源上。

```
> pip index versions cyansdk -i https://pypi.tuna.tsinghua.edu.cn/simple

cyansdk (0.1.1)
Available versions: 0.1.1, 0.1.0
  INSTALLED: 0.1.1
  LATEST:    0.1.1
```

```
> pip index versions cyansdk -i https://pypi.org/simple

cyansdk (0.2.0)
Available versions: 0.2.0, 0.1.1, 0.1.0
  INSTALLED: 0.1.1
  LATEST:    0.2.0
```

### 期望的现象（What you expected to happen）

tuna 镜像源上能够获取到最新版本。

### 如何重现此问题（How to reproduce it）

```bash
pip index versions cyansdk -i https://pypi.tuna.tsinghua.edu.cn/simple
pip index versions cyansdk -i https://pypi.org/simple
```

**Comment by Rongronggg9** [comment]
这个问题似乎更早一天就出现了。`2022-01-24T16:56:02+0000` 更新的 [multidict](https://pypi.org/project/multidict) 同样没有被同步。

**Comment by shankerwangmiao** [comment]
感谢反馈此故障。抱歉我们花费了较长的时间排查此问题。我们与我们的网络提供方一起处理了此问题。该问题是由于我们的网络提供方的某个关键设备工作状态异常，导致镜像站与 PyPI 官方的网络连接不稳定，进而造成同步任务反复重试。目前该问题已经排除，同步任务正在追赶上游进度。请耐心等待。

**Comment by shankerwangmiao** [comment]
已经追上
