### ISSUE TITLE
[镜像请求] 能否添加Manjaro的镜像？

### ISSUE THREAD

**Issue by yohosun** [tuna/issues#1426]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

镜像站里没有Manjaro的镜像，之前应该有一个Manjaro-cd的项目，但是现在没了。而且到Manjaro官网下载镜像需要很长的时间。

### 期望的现象（What you expected to happen）

希望镜像站里能推出Manjaro Xfce,kde和gnome的镜像。

### 如何重现此问题（How to reproduce it）

无

### 操作系统（OS Version）

windows，mac，linux

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by ZenithalHourlyRate** [comment]
参考 #1418

问题的主要原因是 Manjaro 社区并没有成功将新的发行版本上传到 OSDN 上。
您可以参考[这个帖子](https://forum.manjaro.org/t/manjaro-21-0-rc1-iso-download-size-only-41-78-mb/58706)与[这个帖子](https://forum.manjaro.org/t/manjaro-21-0-rc1-ornara-released/58586)。可以注意到官网将下载链接指向了
SourceForge，参考[这里](https://github.com/tuna/issues/issues/928)可知我们难以镜像 SourceForge 的内容。
