### ISSUE TITLE
DNS ECS 配置错误

### ISSUE THREAD

**Issue by wordlesswind** [tuna/issues#1431]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

edns_client_subnet 字段被错误地配置为 `/0` 网段

### 期望的现象（What you expected to happen）

应当为 `/24` 等网段

### 如何重现此问题（How to reproduce it）

DoH ?name=tuna.moe
![图片](https://user-images.githubusercontent.com/9050713/152945834-72b2d484-0f57-4636-a78c-56896d5bd771.png)

**Comment by shankerwangmiao** [comment]
您好，TUNA 的 DNS 服务不支持 ECS。
