### ISSUE TITLE
OSDN 官网似乎无法选择到 Tuna 或者 BFSU 镜像源

### ISSUE THREAD

**Issue by laozhoubuluo** [tuna/issues#1434]
近几个月多次在 OSDN 上下载应用，发现每次下载应用时都不会显示 Tuna 或者 BFSU 镜像源，不管是使用大陆 IP （北京联通/苏州电信）还是香港 IP 均只能看到日本、美国、德国等国家或地区的镜像源，最后只能使用手动拼接地址的方式使用 Tuna 或者 BFSU 镜像源下载相关资源。

如果方便的话辛苦 Tuna 镜像站帮忙确认一下是否能够在下载应用时正常选择 Tuna 或者 BFSU 镜像源，如果不可以的话是否方便联系 OSDN 确认一下为何在使用中国大陆 IP 地址的情况下仍然无法选择到相关镜像源。

考虑到源站点选路并非是镜像站决策的，如果测试无问题或者不方便确认请告知我并直接关闭 Issue ，谢谢。

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-osdn-bananian/
