### ISSUE TITLE
libgccjit版本过期

### ISSUE THREAD

**Issue by TomoeMami** [tuna/issues#1435]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

目前archlinuxcn里的libgccjit版本号为11.1.0-2，在进行更新时会提示：
```
 installing gcc-libs (11.2.0-3) breaks dependency 'gcc-libs=11.1.0' required by libgccjit
```

aur源的libgccjit（https://aur.archlinux.org/packages/libgccjit ）已更新至11.2.0-2，有望解决此依赖问题。

### 期望的现象（What you expected to happen）

更新archlinuxcn里的libgccjit。

### 如何重现此问题（How to reproduce it）

在安装有libgccjit版本号为11.1.0-2的arch linux下运行`sudo pacman -Syu`即可重现。

### 操作系统（OS Version）

Arch Linux

**Comment by TomoeMami** [comment]
新版libgccjit似乎也没解决依赖问题，需要手动操作，故关闭此issue

**Comment by shankerwangmiao** [comment]
经查，ArchlinuxCN 软件仓库（https://repo.archlinuxcn.org/x86_64/）中，您提及的 libgccjit 软件的版本亦为11.1.0-2，TUNA 镜像上的与之相符。

如果您需要 ArchlinuxCN 更新此软件，请向其反馈。

ref: https://github.com/archlinuxcn/repo/issues/2670
