### ISSUE TITLE
QEMU!!!

### ISSUE THREAD

**Issue by dontknowhy** [tuna/issues#1437]
### 先决条件 (Prerequisites)

- [x] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

QEMU的镜像GG了（文件缺失或损坏）

### 期望的现象（What you expected to happen）

编译
运行

### 如何重现此问题（How to reproduce it）

git clone https://mirrors.tuna.tsinghua.edu.cn/git/qemu.git
cd qemu
sudo apt update
sudo apt install pkg-config -y
sudo apt install libglib2.0-dev -y
sudo apt install libpixman-1-dev -y
sudo apt install bison flex -y
sudo apt-get install automake texinfo libffi-dev libpcre3-dev -y
sudo apt install meson python3-pip -y
pip install mako
sudo apt install xmount vde2 u-boot-qemu seabios libqcow1 libqcow-utils libqcow-dev ksmtuned ipxe-qemu aqemu libjpeg* libsdl2* libvirglrenderer* libspice* libasound* libpulse* libvde* liburing* libaio* libepoxy-dev -y
sudo apt purge libasound2-doc libsdl2-doc libsdl2-gfx-doc -y
./configure --enable-alsa --enable-bzip2 --enable-gettext --enable-gtk --enable-kvm --enable-multiprocess --enable-pa --enable-sdl --enable-sdl-image --enable-spice --enable-spice-protocol --enable-tcg --enable-vde --enable-vnc --enable-system --enable-user --enable-tpm --enable-coroutine-pool --enable-vdi --enable-vvfat --enable-qcow1 --enable-tools --enable-bochs --enable-opengl --enable-virglrenderer --enable-linux-aio --enable-oss --enable-linux-io-uring --enable-rng-none  --enable-vnc-png --enable-vnc-jpeg
make -j8
sudo make -j8 install
sudo rm -rf build
cd ..
sudo rm -rf qemu

### 操作系统（OS Version）

(Proot)Debian bullseye

### 浏览器（如果适用）（Browser version, if applicable）

git

### 其他环境（Other environments）

Android 11 
Termux 0.118
latest Proot
newest Debian bullseye

### 其他需要说明的事项（Anything else we need to know）

上游镜像改成 https://gitlab.com/qemu-project/qemu.git
（虽然改成这个tuna也是无用，因为gitlab不用AZure服务器（笑），不需要考虑gitlab访问快不快，直接就可以流畅git）

**Comment by skyzh** [comment]
TUNA 镜像是原样同步上游的；编译问题可能和镜像站无关。

**Comment by ZenithalHourlyRate** [comment]
dup with #1140
