### ISSUE TITLE
[镜像请求] 请求在 OpenTUNA 建立 adobe-fonts 镜像

### ISSUE THREAD

**Issue by fernvenue** [tuna/issues#1438]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

> Adobe Fonts is an online service that provides its subscribers with access to its font library, under a single licensing agreement. The fonts may be used directly on websites, or synced via Adobe Creative Cloud to applications on the subscriber's computers.

### 上游地址与镜像方法 (How to mirror)

TUNA - https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/
GitHub - git://github.com/adobe-fonts

### 镜像大小 (Mirror size)

53.0G [src](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status)

### 备注 (Note)

对于各类站点频繁调用的字体设计类静态资源，特别是 Adobe Fonts 这种被广泛使用的素材，如果能够通过 OpenTUNA 的 CDN 帮助下分发相信能够帮助更多用户的同时也能有效缓解 TUNA 主站的访问压力。

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by fernvenue** [comment]
> > Adobe Fonts is an online service that provides its subscribers with access to its font library, under a single licensing agreement. The fonts may be used directly on websites, or synced via Adobe Creative Cloud to applications on the subscriber's computers.
> 
> Adobe Fonts 服务和 adobe-fonts 不是一个东西吧（

复制粘贴（
这里就默认指代 TUNA 现有的 adobe-fonts 镜像仓库。

**Comment by Ryan83602** [comment]
感觉没有必要啊,https://mirrors.tuna.tsinghua.edu.cn已经够用了

**Comment by happyaron** [comment]
opentuna 即将停止服务，关闭 issue
