### ISSUE TITLE
Ubuntu18.04LTS镜像源地址中https更新报错,修改为http更新正常

### ISSUE THREAD

**Issue by renzhengwei** [tuna/issues#1439]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在更换镜像源文件时依照提示修改无误并保存后，
sudo apt-get update    
执行后对应原地址分别都提示报错如下：
Certificate verification failed: The certificate is NOT trusted.

在寻求网友帮助后，发现将地址中的https改为http即可正常更新下载。且发现好多人遇到此类问题，给大家带来了困扰。
参考文章及评论  https://blog.csdn.net/sinat_38800908/article/details/102839087

### 期望的现象（What you expected to happen）

https://mirror.tuna.tsinghua.edu.cn/help/ubuntu/
将该页面镜像源地址中的https修改为http，
或者在下方添加出错提示，减少开发者们的问题困扰。

### 如何重现此问题（How to reproduce it）

在windows10系统中的微软应用商店中下载安装Ubuntu18.04LTS，并打开，更换其源地址为tuna清华的源后，
执行 sudo apt-get update 
出现更新失败的报错。

### 操作系统（OS Version）

Ubuntu18.04LTS in window10

### 其他环境（Other environments）

在 Windows 10 系统应用商店中直接下载安装运行的Ubuntu18.04LTS

**Comment by ZenithalHourlyRate** [comment]
Ref to #1342
