### ISSUE TITLE
[镜像请求]  Circle Linux

### ISSUE THREAD

**Issue by taotieren** [tuna/issues#1440]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

 Circle Linux 是国际化社区驱动的开源软件，使命在与努力专注于围绕 Linux 平台提供更强大的开源生态。提供企业级、生产环境就绪的 Linux 发行版。 

### 上游地址与镜像方法 (How to mirror)

mirror.cclinux.org

rsync

### 镜像大小 (Mirror size)

<= 390 GB

### 备注 (Note)

Circle Linux 是国内开源社区维护的 CentOS Linux 替代产品，便于原 CentOS Linux 用户系统升级，继续享受上游的升级维护，主站点用户太多，经常拥堵，希望申请镜像，分流下载压力

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by shankerwangmiao** [comment]
dup with #1422
