### ISSUE TITLE
pip源是否能使用IP进行访问

### ISSUE THREAD

**Issue by cobraOps** [tuna/issues#1442]
我这边有台服务器，不能访问外网，只能申请访问某个公网IP，想在服务器上通过pip安装包，我尝试了使用101.6.15.130这个IP访问清华的pip源，但是无法访问，所以想问问是否有IP访问PIP源的方式

**Comment by Harry-Chen** [comment]
镜像站不支持仅通过 IP 进行 HTTP 访问，必须带有正确的 host。您可以通过自行修改机器的 hosts 或者自行搭建 DNS 的方式
