### ISSUE TITLE
[镜像请求] 请求openTUNA增加Packman镜像

### ISSUE THREAD

**Issue by sky96111** [tuna/issues#1443]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Packman
Packman包含了由于或有专利纠纷而不能存在于openSUSE官方构建服务中的软件，比如 FFMPEG，MPLAYER，MP3, AMULE。为了满足多媒体的播放，大多数openSUSE用户都需要添加这个仓库。

目前有此仓库的镜像源tuna, ustc, opsx, tencent均存在速度缓慢的情况（300k/s, 1.1M/s, 900k/s, 200k/s），故请求使用openTUNA的CDN提升镜像速度

### 上游地址与镜像方法 (How to mirror)

tuna已有镜像
https://mirrors.tuna.tsinghua.edu.cn/packman/

### 镜像大小 (Mirror size)

148G

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by happyaron** [comment]
opentuna 即将停止服务，关闭 issue
