### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by YufanBu0507** [tuna/issues#1445]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

请求CentOS-Stream-9的系统镜像

### 上游地址与镜像方法 (How to mirror)

https://www.centos.org/centos-stream/#centos-stream-9

### 镜像大小 (Mirror size)

6.0~7.8GB 取决于架构

### 备注 (Note)

官方尚未发布RPM源，只有ISO

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by shankerwangmiao** [comment]
请见 https://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/x86_64/iso/
