### ISSUE TITLE
[镜像请求] 更新anaconda中rdkit的请求

### ISSUE THREAD

**Issue by chenxin199261** [tuna/issues#1448]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [ ] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

你们好，我在使用rdkit过程中，发现rdkit依然为2019年的版本。
rdkit                     2019.09.3        py38hb31dc5d_0    conda-forge
新版本为2021年版本，修复了很多错误，为目前主流版本。

请求TUNA团队更新下rdkit。
感谢你们的工作

### 上游地址与镜像方法 (How to mirror)

conda install -c rdkit rdkit

### 镜像大小 (Mirror size)

39 MB

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> 请求TUNA团队更新下rdkit。

镜像站依原样镜像上游内容。目前在 conda-forge channel 中已经有 2021.09.5 的相关内容
```
# /anaconda/cloud/conda-forge [13:44:47] 
$ find . -name "*2021.09.5*"
./osx-64/rdkit-2021.09.5-py37h72bc793_0.tar.bz2
./osx-64/rdkit-dev-2021.09.5-h694c41f_0.tar.bz2
./osx-64/rdkit-2021.09.5-py38hc2778ef_0.tar.bz2
./osx-64/rdkit-2021.09.5-py39h1ae426c_0.tar.bz2
./linux-aarch64/rdkit-2021.09.5-py37h2e28282_0.tar.bz2
./linux-aarch64/rdkit-dev-2021.09.5-h8af1aa0_0.tar.bz2
./linux-aarch64/rdkit-2021.09.5-py38ha76fdbe_0.tar.bz2
./linux-aarch64/rdkit-2021.09.5-py39h3f581e4_0.tar.bz2
./osx-arm64/rdkit-2021.09.5-py39h71be56f_0.tar.bz2
./osx-arm64/rdkit-dev-2021.09.5-hce30654_0.tar.bz2
./osx-arm64/rdkit-2021.09.5-py38h5f6ed43_0.tar.bz2
./win-64/rdkit-2021.09.5-py37hd1be60c_0.tar.bz2
./win-64/rdkit-2021.09.5-py38h6643f78_0.tar.bz2
./win-64/rdkit-2021.09.5-py39hfadf033_0.tar.bz2
./win-64/rdkit-dev-2021.09.5-h57928b3_0.tar.bz2
./linux-64/rdkit-2021.09.5-py39h89e00b9_0.tar.bz2
./linux-64/rdkit-2021.09.5-py37h4ddd313_0.tar.bz2
./linux-64/rdkit-dev-2021.09.5-ha770c72_0.tar.bz2
./linux-64/rdkit-2021.09.5-py38ha848acd_0.tar.bz2
```

您可以尝试使用 `conda install -c conda-forge rdkit` 以安装最新版本。

> conda install -c rdkit rdkit

上游的 rdkit channel 并没有更新新内容，参考 https://anaconda.org/rdkit
