### ISSUE TITLE
需要修改OpenMediaVault使用帮助来适配Debian 11

### ISSUE THREAD

**Issue by 210hcl** [tuna/issues#1449]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在OpenMediaVault使用帮助出现未适配Debian 11 的问题（文档问题）

### 期望的现象（What you expected to happen）

参见[官方说明](https://forum.openmediavault.org/index.php?thread/39490-install-omv6-on-debian-11-bullseye/)
buster用现有的，bullseye用新版的

### 如何重现此问题（How to reproduce it）

在Debian 11上安装OMV时候发现的

### 操作系统（OS Version）

Debian 11.2

### 浏览器（如果适用）（Browser version, if applicable）

Chrome

### 其他需要说明的事项（Anything else we need to know）

只需要修改文档，暂时没发现其他问题

**Comment by shankerwangmiao** [comment]
您可以直接对 https://github.com/tuna/mirror-web/blob/master/help/_posts/1970-01-01-openmediavault.md 进行修改并提出 pull request
