### ISSUE TITLE
11月6日接锅会总结

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#145]
### mirrors
 * [x] ELK
 * [x] Tensorflow

### mirrors-web
 * [x] 增加帮助
 * [ ] 服务器状态，列表在手机上效果不好 
 * [x] iso下载向导

### tunaccount
custom database <—> ldap and other  protocols
* [ ] restful api 欠完善
* [ ] 需要一个前端 vuejs 纯前端
* [ ] 公私钥认证系统

### danmaku
* [x] 客户端移植到Qt5
* [x] 服务器或许移植到Python3

### fishroom
* [ ] 频道选择页面
* [x] authentication(GitHub等)
* [x] 多线程->多进程 用redis通信

### podcast

**Comment by bigeagle** [comment]
干掉的 issues:
- tensorflow
- ELK

**Comment by huiyiqun** [comment]
把registr-lite的i18n加进去吧？

**Comment by z4yx** [comment]
这些锅都差不多解决完了吧（fishroom反正也凉了）
