### ISSUE TITLE
[镜像请求] bazel 的 apt 包镜像

### ISSUE THREAD

**Issue by CareF** [tuna/issues#1451]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

bazel 是 Google 内部构建工具 Blaze 的开源版本，可能是市面上对于 monorepo 支持最好的构建工具。支持高级本地缓存，分布式编译。

### 上游地址与镜像方法 (How to mirror)

有现成的 apt 上游 https://bazel.build/install/ubuntu 
```
deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
```

### 镜像大小 (Mirror size)

2.4G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/bazel-apt/

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/bazel-apt/
