### ISSUE TITLE
Hackage 镜像 index 非常旧

### ISSUE THREAD

**Issue by felixonmars** [tuna/issues#1456]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

设置 cabal 使用 tuna/bfsu 镜像时，hackage index db 里缺少很多新版本的软件包。

### 期望的现象（What you expected to happen）

使用 tuna/bfsu 应与默认镜像基本一致。

### 如何重现此问题（How to reproduce it）

按照教程设置镜像为 tuna 或 bfsu，运行 cabal update，然后查询数据库里的软件包版本。

设置为官方镜像（默认设置）时：
```
$ cabal info attoparsec | grep -i2 version
* attoparsec       (library)
    Synopsis:      Fast combinator parsing for bytestrings and text
    Versions available: 0.12.1.6, 0.13.1.0, 0.13.2.3, 0.13.2.4, 0.13.2.5,
                        0.14.1, 0.14.2, 0.14.3, 0.14.4 (and 52 others)
    Versions installed: 0.14.4
    Homepage:      https://github.com/bgamari/attoparsec
    Bug reports:   https://github.com/bgamari/attoparsec/issues
```

设置为 tuna/bfsu 时：
```
$ cabal info attoparsec | grep -i2 version
* attoparsec       (library)
    Synopsis:      Fast combinator parsing for bytestrings and text
    Versions available: 0.11.3.4, 0.12.0.0, 0.12.1.5, 0.12.1.6, 0.13.0.2,
                        0.13.1.0, 0.13.2.2, 0.13.2.3, 0.13.2.4 (and 47 others)
    Versions installed: 0.14.4
    Homepage:      https://github.com/bos/attoparsec
    Bug reports:   https://github.com/bos/attoparsec/issues
```

### 操作系统（OS Version）

Arch Linux

### 其他环境（Other environments）

cabal-install 3.4.0.0
ghc 9.0.2

### 其他需要说明的事项（Anything else we need to know）

使用 tuna/bfsu 镜像时似乎不能增量更新，也不显示 db 的同步状态。对比如下：

```
$ cabal update
Downloading the latest package list from mirrors.tuna.tsinghua.edu.cn
$
```
（^此过程中下载了全量db。）

```
$ cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-03-20T22:19:30Z
$
```
（^只有大约70K的下载量。如果本地db可以更新，则只有delta量。）

**Comment by ZenithalHourlyRate** [comment]
这是由于 https://github.com/tuna/tunasync-scripts/commit/a79b312cbb7ea048fc63e2fc7f4341c3c02dd063 造成的。

参考 https://github.com/haskell/cabal/blob/906a8bcabc307c6c607cf1b9826a6b329e3ceb7f/cabal-install/src/Distribution/Client/IndexUtils.hs#L145 可知，在配置镜像时应该使用

```
repository mirrors.tuna.tsinghua.edu.cn
  url: http://mirrors.tuna.tsinghua.edu.cn/hackage
  secure: True
```
这种格式

这将在 mirror-web 镜像帮助中更新。
