### ISSUE TITLE
git-repo镜像下载返回证书过期

### ISSUE THREAD

**Issue by st01cs** [tuna/issues#1458]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Downloading Repo source from https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
fatal: 无法访问 'https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'：The certificate issuer's certificate has expired.  Check your system date and time.
repo: error: "git" failed with exit status 128

### 期望的现象（What you expected to happen）

正常下载repo程序

### 如何重现此问题（How to reproduce it）

repo init -u ssh://gerrit_site/platform/manifest.git \
> -b some_branch \
> -m some_manifest.xml \
> --repo-url=https://mirrors.tuna.tsinghua.edu.cn/git/git-repo \
> --no-repo-verify

**Comment by phy25** [comment]
请提供您的操作系统。另请参见 #1342.

**Comment by st01cs** [comment]
> 请提供您的操作系统。另请参见 #1342.

CentOS-7
