### ISSUE TITLE
brew install 出现 证书错误 无法下载 ca-certificates

### ISSUE THREAD

**Issue by julypanda** [tuna/issues#1459]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/ca-certificates-2022-02-01.all.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Error: No such file or directory @ rb_sysopen - /Users/user/Library/Caches/Homebrew/downloads/ae40d5d61d102016b5bc08a11628302037ca83f07e5c54ad9064a0212f65f0e3--ca-certificates-2022-02-01.all.bottle.tar.gz

### 期望的现象（What you expected to happen）

download without error

### 如何重现此问题（How to reproduce it）

brew install mysql

### 操作系统（OS Version）

macOS

**Comment by julypanda** [comment]
works fine after Sync。

**Comment by Harry-Chen** [comment]
虽然包名是 `ca-certificates`，问题和证书完全没有关系。
