### ISSUE TITLE
termux软件包分类更改

### ISSUE THREAD

**Issue by SherkeyXD** [tuna/issues#1460]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

apt update时连接termux官方源
检查发现termux软件包分类更改，由原来的stable, games, science三类变更为stable, root两类
手动修改后恢复正常

### 期望的现象（What you expected to happen）

正常连接tuna源

### 如何重现此问题（How to reproduce it）

> apt update
Hit:1 https://packages.termux.org/apt/termux-root root InRelease
Hit:2 https://packages-cf.termux.org/apt/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.

### 操作系统（OS Version）

termux 0.118

### 其他需要说明的事项（Anything else we need to know）

建议修改termux的使用说明

**Comment by Harry-Chen** [comment]
您可直接在 tuna/mirror-web 的相应文件中提出 pull request

**Comment by SherkeyXD** [comment]
pr已提交
