### ISSUE TITLE
[故障报告] AdoptOpenJDK 更换了品牌名称且迁移了服务地址

### ISSUE THREAD

**Issue by luooyii** [tuna/issues#1461]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

AdoptOpenJDK 提供了预编译的openjdk服务。在2021年7月移交至eclipse基金会托管，并更换了品牌名称为 Adoptium 后重新运营。之前的服务已在今年一月陆续停止更新。
关于迁移的公告：https://adoptopenjdk.net/

> 24th July 2021: [AdoptOpenJDK is moving to the Eclipse Foundation](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/) and rebranding.
Our July 2021 and future releases will come from [Adoptium.net](https://www.adoptium.net/)

新的品牌 Adoptium 官网：https://adoptium.net/

### 期望的现象（What you expected to happen）

将 AdoptOpenJDK 改名为 Adoptium 
使用新的镜像源 https://adoptium.net/
tip: jdk版本较多，可以只保留最新版本（目前AdoptOpenJDK就是这样）

### 如何重现此问题（How to reproduce it）

AdoptOpenJDK 镜像库已数月没有更新
https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1313#issuecomment-915421887 近期会跟进一下，毕竟 Java 18 发版了

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/rename-adoptopenjdk-to-adoptium/
