### ISSUE TITLE
404

### ISSUE THREAD

**Issue by WeichengZong** [tuna/issues#1462]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Err:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 apache2-bin amd64 2.4.41-4ubuntu3.9
  404  Not Found [IP: 101.6.15.130 443]
Err:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 apache2-data all 2.4.41-4ubuntu3.9
  404  Not Found [IP: 101.6.15.130 443]
Err:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 apache2-utils amd64 2.4.41-4ubuntu3.9
  404  Not Found [IP: 101.6.15.130 443]
Err:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 apache2 amd64 2.4.41-4ubuntu3.9
  404  Not Found [IP: 101.6.15.130 443]

### 期望的现象（What you expected to happen）

refind

### 如何重现此问题（How to reproduce it）

sudo apt-get install apache2

### 操作系统（OS Version）

ubuntu

**Comment by Harry-Chen** [comment]
请先 `apt update`
