### ISSUE TITLE
fedora-updates 出现故障

### ISSUE THREAD

**Issue by watneyx** [tuna/issues#1463]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[xwt@fedora ~]$ sudo dnf makecache
Copr repo for PyCharm owned by phracek                                                                                                                                                                         43 kB/s | 178 kB     00:04    
Fedora 35 - x86_64                                                   7.8 MB/s |  79 MB     00:10    
Fedora Modular 35 - x86_64                                     1.6 MB/s | 3.3 MB     00:02    
Fedora 35 - x86_64 - Updates                                   294 kB/s | 423 kB     00:01    
Errors during downloading metadata for repository 'updates':
  - Status code: 404 for https://mirrors.bfsu.edu.cn/fedora/updates/35/Everything/x86_64/repodata/7a7a4daaeb49244b63791fe3c18a9755aa702dddffbca870a806910ed90e1423-filelists.xml.zck (IP: 39.155.141.16)
  - Status code: 404 for https://mirrors.bfsu.edu.cn/fedora/updates/35/Everything/x86_64/repodata/354553f79fb85542c61ade839418fe0f5cdf706d879fdbe551e0d7c96d5d68e7-primary.xml.zck (IP: 39.155.141.16)
错误：为仓库 'updates' 下载元数据失败 : Yum repo downloading error: Downloading error(s): repodata/354553f79fb85542c61ade839418fe0f5cdf706d879fdbe551e0d7c96d5d68e7-primary.xml.zck - Cannot download, all mirrors were already tried without success; repodata/7a7a4daaeb49244b63791fe3c18a9755aa702dddffbca870a806910ed90e1423-filelists.xml.zck - Cannot download, all mirrors were already tried without success; repodata/cf97177db681a2af05f039ea5f32d77e3b10a090221d3e60cc2a4f7052571614-prestodelta.xml.zck - Cannot download, all mirrors were already tried without success; repodata/b0bdd55332a59c062d2b76223a1a3eb665df113932dbd1abf52a01ad9e1dc63b-updateinfo.xml.zck - Cannot download, all mirrors were already tried without success

### 期望的现象（What you expected to happen）

修复或给出解决方案

### 如何重现此问题（How to reproduce it）

阿里云源似乎出现过同类问题

### 操作系统（OS Version）

fedora

**Comment by ZenithalHourlyRate** [comment]
由于上游发布 Fedora 36 beta，上游压力较大，同步较为缓慢，正在逐渐同步中。

目前 TUNA 已将相关文件同步回来，BFSU 正在同步中。

**Comment by ZenithalHourlyRate** [comment]
已经同步完成。
