### ISSUE TITLE
Debian sid更新异常缓慢

### ISSUE THREAD

**Issue by dontknowhy** [tuna/issues#1467]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

一般的讲，Debian Sid源只是包不同，仓库还是一样的，但apt update基本保持在500KB/s左右。（不是网络问题，包源小文件真的很慢。作为对比，ustc一般都能没计算出网速就下载好）

### 期望的现象（What you expected to happen）

update速度保持在1MB/s或以上

### 如何重现此问题（How to reproduce it）

nice -n 99 ionice -c 2 -n 7 sudo apt update

### 操作系统（OS Version）

(Proot)Debian bullseye (主机为Android 11)

### 浏览器（如果适用）（Browser version, if applicable）

apt(笑)

### 其他环境（Other environments）

透过WLAN使用apt
路由器无线网速满载在7MB/s左右

### 其他需要说明的事项（Anything else we need to know）

我也不知道发生什么事了
stable源永远比Sid慢
ustc就不会
是不是Sid被放在单独服务器上并且这个服务器规模比stable小了亿点?

**Comment by dontknowhy** [comment]
[注]大文件（deb安装包）也比stable慢了很多，基本在500KB/S左右

**Comment by dontknowhy** [comment]
> 您先说是 “stable源永远比Sid慢”，后称 “大文件（deb安装包）也比stable慢了很多”，到底 stable 和 sid 谁比谁慢？有 APT 输出的截图吗？

oer 
是Sid慢
（脑子永远都是在抽筋状态）
目前只有Sid系统在用（要论Stable我只有Ubuntu 22.04）
![Screenshot_20220408_195736.jpg](https://user-images.githubusercontent.com/85813508/162431069-4747593d-0733-439d-b673-471d5c19f2c9.jpg)
一般ustc在1MB/s左右，tuna就500KB/s
update是够用，但500KB/s且还有提速过程就真的离谱

**Comment by dontknowhy** [comment]
> 您先说是 “stable源永远比Sid慢”，后称 “大文件（deb安装包）也比stable慢了很多”，到底 stable 和 sid 谁比谁慢？有 APT 输出的截图吗？

PS:要看见我脑子抽经就以标题为准

**Comment by Harry-Chen** [comment]
TUNA 并没有将 debian 源拆分，这样做也没有意义。网络问题是一个复杂的问题，「下载速度慢」的现象可能由多种因素导致。

此外，不建议在 apt 配置中混用多个镜像站。如果 USTC 始终更快，那建议您完全切换至 USTC 镜像。

**Comment by dontknowhy** [comment]
> TUNA 并没有将 debian 源拆分，这样做也没有意义。网络问题是一个复杂的问题，「下载速度慢」的现象可能由多种因素导致。
> 
> 此外，不建议在 apt 配置中混用多个镜像站。如果 USTC 始终更快，那建议您完全切换至 USTC 镜像。

混用就是为了防止哪个镜像站抽筋更新慢有个备用
（你怕不是没见过我之前写了3KB左右的sources.list）
但很离谱的是：tuna又快了，变为正常网速
