### ISSUE TITLE
安装gdb 镜像文件缺失

### ISSUE THREAD

**Issue by swxs** [tuna/issues#1469]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

root@bi-xm:/XM# apt install gdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libbabeltrace1 libc6-dbg libdw1 libipt2 libpopt0 libpython3.7
  libpython3.7-minimal libpython3.7-stdlib python3.7
  python3.7-minimal
Suggested packages:
  gdb-doc gdbserver python3.7-venv python3.7-doc binfmt-support
The following NEW packages will be installed:
  gdb libbabeltrace1 libc6-dbg libdw1 libipt2 libpopt0 libpython3.7
The following packages will be upgraded:
  libpython3.7-minimal libpython3.7-stdlib python3.7
  python3.7-minimal
4 upgraded, 7 newly installed, 0 to remove and 86 not upgraded.
Need to get 21.0 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 python3.7 amd64 3.7.3-2+deb10u3 [330 kB]
Get:2 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libpython3.7-stdlib amd64 3.7.3-2+deb10u3 [1734 kB]
Get:3 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 python3.7-minimal amd64 3.7.3-2+deb10u3 [1737 kB]
Get:4 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libpython3.7-minimal amd64 3.7.3-2+deb10u3 [589 kB]
Get:5 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libdw1 amd64 0.176-1.1 [235 kB]
Get:6 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libpopt0 amd64 1.16-12 [49.4 kB]
Get:7 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libbabeltrace1 amd64 1.5.6-2+deb10u1 [172 kB]
Get:8 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libipt2 amd64 2.0-2 [41.7 kB]
Get:9 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libpython3.7 amd64 3.7.3-2+deb10u3 [1498 kB]
Get:10 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 gdb amd64 8.2.1-2+b3 [3133 kB]
Err:11 https://mirrors.tuna.tsinghua.edu.cn/debian buster/main amd64 libc6-dbg amd64 2.28-10
  404  Not Found [IP: 101.6.15.130 443]
Fetched 9518 kB in 5s (1812 kB/s)
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/g/glibc/libc6-dbg_2.28-10_amd64.deb  404  Not Found [IP: 101.6.15.130 443]

### 期望的现象（What you expected to happen）

正常安装

该文件在https://github.com/tuna/issues/issues/725中说明会删除，但是删除后会导致该问题，希望恢复

### 如何重现此问题（How to reproduce it）

apt install gdb

**Comment by jiegec** [comment]
请 apt update 再 apt install
