### ISSUE TITLE
node_6.x nodesource deb 镜像

### ISSUE THREAD

**Issue by NStal** [tuna/issues#147]
#### Nodejs 6.x (Project Intro.)
更新的Node.js LTS

#### 上游地址与镜像方法(How to Mirror)
目前已经有nodesource的镜像, 
`https://deb.nodesource.com/node/` => `http://mirrors.tuna.tsinghua.edu.cn/nodesource/deb/`
希望增加
`https://deb.nodesource.com/node_6.x/` => `http://mirrors.tuna.tsinghua.edu.cn/nodesource/node_6.x/deb/`

镜像与使用方法与原镜像一致. 相关信息: https://github.com/nodesource/distributions

#### 其他信息(Other)
- 镜像大小(Mirror Size): 不是很确定, QAQ

**Comment by bigeagle** [comment]
不是一直都有么…… 
https://mirrors.tuna.tsinghua.edu.cn/nodesource/deb_6.x/
