### ISSUE TITLE
[镜像请求] cri-o & cri-o-runc for kubernetes container runtime

### ISSUE THREAD

**Issue by willzhang** [tuna/issues#1470]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

install docs:
https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems

### 上游地址与镜像方法 (How to mirror)

i just know install method ,but i don't know how to mirror
```
export OS=xUbuntu_20.04
export VERSION=1.23

echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list

curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -

apt-get update
apt-get install -y cri-o cri-o-runc
```

### 镜像大小 (Mirror size)

80M

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> `echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list`

这是通过 opensuse/repositories 分发的，而通过

```
$ rsync rsync://rsync.opensuse.org

This is rsync.opensuse.org, public rsync server of openSUSE.org,
limited to 50 connections.

If you run a public mirror, please get in contact so we can give you
access to the stage rsync server.
You'll find conditions for access and further information at
http://en.opensuse.org/Mirror_Infrastructure

Thanks!
admin@opensuse.org


opensuse-full   Without daily devel snapshots
opensuse-full-with-factory      Includes daily devel snapshots
opensuse-full-with-factory-dvd5 Includes daily devel snapshots and large, short-lived Beta DVDs
opensuse-full-really-everything *not recomended* includes updates every minute
opensuse-full-really-everything-including-repositories  *not recomended* includes updates every minute
opensuse-updates        Official updates for released openSUSE distributions
buildservice-repos      The repositories from the openSUSE build service
buildservice-repos-main The repositories from the openSUSE build service without the home: directories
```

中的 `opensuse-full-really-everything-including-repositories` 可以发现其更新频繁，镜像站难以追上同步

> #741 同步和维护困难
