### ISSUE TITLE
NixOS unstable image request

### ISSUE THREAD

**Issue by senqiqi** [tuna/issues#1471]
Hi there,

Would you please consider adding `https://nixos.org/channels/nixos-unstable` unstable image to nixos-images `https://mirrors.tuna.tsinghua.edu.cn/nixos-images/`? I can see it's currently missing atm.

Best

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/nixos-images/nixos-unstable/
