### ISSUE TITLE
地址 elpa/melpa/ 访问故障

### ISSUE THREAD

**Issue by ImAmelie** [tuna/issues#1476]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

<https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/>
这个页面无法访问，和他同级的 gnu 就可以正常访问

### 期望的现象（What you expected to happen）

希望能恢复访问

### 如何重现此问题（How to reproduce it）

浏览器打开 <https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/>

### 操作系统（OS Version）

Windows 11

### 浏览器（如果适用）（Browser version, if applicable）

Google Chrome 版本 100.0.4896.127（正式版本） （64 位）

**Comment by ZenithalHourlyRate** [comment]
您好，这是由于上游 melpa 提供的 index.html 中的 package list 直接指向了镜像站根目录，如果您使用 emacs 能够继续获取相关软件包。如果您需要包列表，可以直接访问 https://melpa.org/#/

**Comment by ImAmelie** [comment]
emacs下载插件提示：
```
Error (use-package): Failed to install lsp-mode: https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/lsp-mode-20220421.1428.tar: Not found
```

**Comment by ZenithalHourlyRate** [comment]
您好，镜像站上有 lsp-mode-20220425.1901.tar 文件，请您更新相关元数据。

**Comment by ImAmelie** [comment]
好的，谢谢
