### ISSUE TITLE
同步 AOSP 某些 branch 时报错

### ISSUE THREAD

**Issue by DeepAQ** [tuna/issues#1477]
### 先决条件 (Prerequisites)

- [ ] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用某些 branch 初始化并同步 AOSP 代码，提示找不到对应的 branch：

```
$ repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android11-platform-release
$ repo sync
Fetching:  1% (12/758) platform/developers/samples/android
fatal: couldn't find remote ref refs/heads/android11-platform-release

device/amlogic/yukawa:
fatal: couldn't find remote ref refs/heads/android11-platform-release
device/amlogic/yukawa: sleeping 4.0 seconds before retrying
fatal: couldn't find remote ref refs/heads/android11-platform-release

...
```

### 期望的现象（What you expected to happen）

上游对应仓库包含对应 branch，使用镜像时应该也能正常同步。

### 如何重现此问题（How to reproduce it）

经测试，此问题仅会出现在部分 branch 中（如 `android11-platform-release`），使用 tag 时（如 `android-11.0.0_r48`）无此问题。使用其他镜像时（如 USTC 镜像）亦无此问题。

**Comment by ZenithalHourlyRate** [comment]
已经修复，您可以重试一下

**Comment by DeepAQ** [comment]
已确认修复，十分感谢！
