### ISSUE TITLE
pip包用不了了

### ISSUE THREAD

**Issue by 11072162** [tuna/issues#1478]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

python pip包的镜像用不了了
https://mirrors.tuna.tsinghua.edu.cn/simple/

### 期望的现象（What you expected to happen）

正常

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/simple/

**Comment by Harry-Chen** [comment]
根据帮助，可用的 URL 为 `https://pypi.tuna.tsinghua.edu.cn/simple` 或者 `https://mirrors.tuna.tsinghua.edu.cn/pypi/simple`
