### ISSUE TITLE
chromium os镜像

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#148]
#### 项目名称与简介(Project Intro.)

> Chromium OS is an open-source project that aims to build an operating system that provides a fast, simple, and more secure computing experience for people who spend most of their time on the web.

最近不少人购入了 chromebook，所以镜像chromium os有助于大家愉快地折腾。

#### 上游地址与镜像方法(How to Mirror)

方法：遍历manifest找到所有git，下载所有git
上游地址：https://chromium.googlesource.com/chromiumos/manifest.git
#### 其他信息(Other)

- 镜像大小(Mirror Size): master分支有6.7G，如果包括所有分支应该比这个数值要大一些。

**Comment by huiyiqun** [comment]
#138 中已经有一些讨论

**Comment by huiyiqun** [comment]
如果考虑到方便的话，可以只镜像master分支，那么

```
repo -u https://android.googlesource.com/platform/manifest --mirror
```

大概就可以了

**Comment by bigeagle** [comment]
为何是 android.googlesource.com?

**Comment by huiyiqun** [comment]
手贱敲错了。woc

**Comment by huiyiqun** [comment]
我在我PC上镜像一个试试。

**Comment by huiyiqun** [comment]
认真看了一下chromium os的[manifests](https://chromium.googlesource.com/chromiumos/manifest/+/master)，得出如下结论：

当前chromium os这个项目总共由四个子项目的代码构成，在git-repo里表现为四个remote：

1. [aosp](https://android.googlesource.com/)
2. [chromium](https://chromium.googlesource.com)
3. [weave](https://weave.googlesource.com/)
4. chromium os 自己的内容现在也托管在chromium的git仓库下

我们现在已经有了aosp，我准备先把weave同步下来，再考虑chromiumos。

同步weave主要考虑到：

1. weave这个项目比较小，只有几个子项目。
2. 作为官方不提供mirror用的manifest的典型。

如果weave能同步下来，剩下的问题就很简单了。

**Comment by huiyiqun** [comment]
[weave](https://mirrors.tuna.tsinghua.edu.cn/help/weave/) 和 [chromium os](https://mirrors.tuna.tsinghua.edu.cn/help/weave/) 都已经同步下来了，现在只有master分支的内容，即只有出现在[这个文件中的项目](https://chromium.googlesource.com/chromiumos/manifest/+/master/full.xml)才会被同步。

如果需要全量同步，那么我们需要同步：
1. 曾经出现在这个文件中。
2. 至今还在[这里](https://chromium.googlesource.com/)，未被移除的项目。

我不认为遍历600个commit是个好办法，所以这个镜像暂时就这样了，等需求。
