### ISSUE TITLE
Termux 镜像分类多余以及地址问题

### ISSUE THREAD

**Issue by SherkeyXD** [tuna/issues#1480]
来自[官方wiki](https://github.com/termux/termux-packages/wiki/Mirrors#info-for-mirror-maintainers):
> unstable-packages, game-packages and science-packages have been merged into the main (termux-packages) repository and no longer have to be synced.

即：不再需要同步unstable, science, game三种软件包，它们已经被整合入main/termux-packages（即main分类）
官方目前的分类仅有main, root, x11三种

以及，`https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main` 和 `https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24` 指向的内容完全一致，将这两个地址设为镜像地址均可正常获取软件源。但termux官方授意写成 `/apt/termux-main` 的形势 ( see [this](https://github.com/termux/termux-packages/wiki/Mirrors#mirrors-by-tsinghua-university-tuna-association) )，是否需要做出更改？

**Comment by SherkeyXD** [comment]
see https://github.com/termux/termux-packages/discussions/10408

**Comment by ZenithalHourlyRate** [comment]
已经停止对相关软件包的同步，为了保证用户和下游的兼容性，我们将保留相关数据（约 10M）。

对 mirror-web 的 PR 已经部署。
