### ISSUE TITLE
ubuntu死循环超链接

### ISSUE THREAD

**Issue by xiaxinzhe** [tuna/issues#1482]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![image](https://user-images.githubusercontent.com/61304326/166151717-92b3e9fc-ce9a-4f64-a79f-8a954a043632.png)
点击这个ubuntu超链接，会产生死循环

### 期望的现象（What you expected to happen）

为何这个现象应该存在（雾

### 如何重现此问题（How to reproduce it）

Just Click It

### 操作系统（OS Version）

Windows 10 Education

### 浏览器（如果适用）（Browser version, if applicable）

Microsoft Edge

**Comment by jiegec** [comment]
就是这样的。

**Comment by Arnie97** [comment]
这个符号链接和上游是一致的，是 feature
http://archive.ubuntu.com/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/
