### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by BarryWater** [tuna/issues#1483]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

树莓派上部署miniconda环境
使用内置的conda install

### 上游地址与镜像方法 (How to mirror)

壁外调查回到深圳是没有想到的

https://mirrors.sustech.edu.cn/anaconda/pkgs/free/
https://mirrors.sustech.edu.cn/anaconda/pkgs/main/

### 备注 (Note)

https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-armv7l/
直到/anaconda/cloud/pytorch都有文件夹，但是没有/linux-armv7l/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-armv7l/

您好，上游并未提供相应架构的文件，详细可以参考 https://anaconda.org/pytorch/pytorch

> https://mirrors.sustech.edu.cn/anaconda/pkgs/free/

这并不是 pytorch channel 的上游
