### ISSUE TITLE
无限循环的Ubuntu

### ISSUE THREAD

**Issue by poet123** [tuna/issues#1485]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![图片](https://user-images.githubusercontent.com/45881802/167058412-61c7e1e1-9966-419c-9da8-0e870e545387.png)
点击ubuntu 无限循环

### 期望的现象（What you expected to happen）

进入到ubuntu 文件夹

### 如何重现此问题（How to reproduce it）

如图所示点击Ubuntu

### 浏览器（如果适用）（Browser version, if applicable）

firefox

**Comment by shankerwangmiao** [comment]
dup with #1296
