### ISSUE TITLE
postmarketOS-images自动跳转postmarketOS官网

### ISSUE THREAD

**Issue by tkw6688** [tuna/issues#1487]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在镜像站首页点击postmarketOS-images自动跳转到postmarketOS官方镜像下载https://images.postmarketos.org/bpo/

### 期望的现象（What you expected to happen）

访问镜像站下的postmarketOS-images

### 如何重现此问题（How to reproduce it）

在镜像站首页点击postmarketOS-images

### 操作系统（OS Version）

Windows10 21H2 19044.1682

### 浏览器（如果适用）（Browser version, if applicable）

Chrome 101.0.4951.54

**Comment by ZenithalHourlyRate** [comment]
该问题已修复。
