### ISSUE TITLE
pypi 镜像中包含nightly的大部分报404了

### ISSUE THREAD

**Issue by shitou1992** [tuna/issues#1489]
pypi 镜像中包含nightly的大部分报404了
这类镜像现在不同步了吗？
比如：
tf_nightly
pyAgrum_nightly

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/tunasync-scripts/blob/989faa98f6b95e7bcda5d0c2b7fb9f071f39a0bf/pypi.sh#L44

对于 nightly 的同步难以追上上游，我们不同步 nightly 部分
