### ISSUE TITLE
git-repo镜像

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#149]
#### 项目名称与简介(Project Intro.)

git-repo是Google使用的管理复数git的版本控制工具。

当前tuna已经镜像和可能镜像的项目里，AOSP和ChromiumOS都使用了repo来管理项目。

镜像git-repo有两个意义：

1. 用户可以方便地获得工具，进而开始下载AOSP和ChromiumOS。
2. 使用`repo`的过程中，它会尝试更新自己，在镜像站镜像这个repo有助于加速更新过程。（也就可以去掉对gerrit的反向代理了？）

#### 上游地址与镜像方法(How to Mirror)

1. https://code.google.com/p/git-repo/
2. https://gerrit.googlesource.com/git-repo
3. https://android.googlesource.com/tools/repo
4. https://chromium.googlesource.com/external/repo.git

1是主页，它让从2或3下载，4是chromium-os用的repo，三者的关系如下：

![screenshot_2016-11-09_10-42-46](https://cloud.githubusercontent.com/assets/3468160/20125608/76f74824-a669-11e6-998a-1ae6f5bad7e6.png)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 2.5M

**Comment by huiyiqun** [comment]
镜像脚本已添加：

https://github.com/tuna/tunasync-scripts/commit/202690620b70bcf893e0bef2d5521e15c6f2ba6b

**Comment by huiyiqun** [comment]
Done.

不过最好把repo这个脚本单独拎出来提供下载，再根据现在的help修改一下，我不知道怎么从bare repo里把文件弄出来，必须要clone出来吗？

**Comment by bigeagle** [comment]
@huiyiqun http://stackoverflow.com/questions/13602751/git-checkout-single-file-under-bare-repository

**Comment by huiyiqun** [comment]
repo这个脚本提取出来了：https://github.com/tuna/tunasync-scripts/commit/c42b7c54d1a830f43fbed8741eacaffb0b963048

现在通过 https://mirrors.tuna.tsinghua.edu.cn/git/git-repo 下载，help也已经更新了：https://github.com/tuna/mirror-web/commit/9eb31225052ef177c8b6e0ef7d2199a9813625c3

等 help 上线测试无误之后就可以 close 了

**Comment by huiyiqun** [comment]
可以close了，我自己用了一段时间了。（不会我是唯一用户吧
