### ISSUE TITLE
[镜像请求] 请求在 OpenTUNA 增加 Anaconda 镜像

### ISSUE THREAD

**Issue by StarsbySea** [tuna/issues#1492]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Anaconda 是一个用于科学计算的 Python 发行版，支持 Linux, Mac, Windows, 包含了众多流行的科学计算、数据分析的 Python 包。

### 上游地址与镜像方法 (How to mirror)

https://repo.continuum.io/
rsync://mirrors.tuna.tsinghua.edu.cn/anaconda/

### 镜像大小 (Mirror size)

7T+

### 备注 (Note)

当前TUNA和BFSU已经上线了该镜像，希望OpenTUNA也能同步上线该镜像。
（因为OpenTUNA三网都能直达并随时跑满带宽）
（不知道有没有版权问题）

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by shankerwangmiao** [comment]
由于 Anaconda 相关授权的原因，我们不能在 OpenTUNA 上提供 Anaconda 镜像。

**Comment by StarsbySea** [comment]
感谢解答❤
