### ISSUE TITLE
打开https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge 提示too many files to list

### ISSUE THREAD

**Issue by LINDADA1997** [tuna/issues#1493]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法打开https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge 提示too many files to list

### 期望的现象（What you expected to happen）

可以下载以下资源
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/jpeg-9b-vc14_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/libtiff-4.0.9-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/qt-5.6.2-vc14_1.tar.bz2

### 如何重现此问题（How to reproduce it）

浏览器访问https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

### 操作系统（OS Version）

win10专业版

### 浏览器（如果适用）（Browser version, if applicable）

Google、Edge

**Comment by shankerwangmiao** [comment]
该页面下文件数目较多，因此禁止列举目录，但不影响正常 Anaconda 从上面下载和安装程序包。

**Comment by LINDADA1997** [comment]
issue提交中的三个资源都无法用浏览器访问，浏览器提示404，这也是正常现象吗

**Comment by shankerwangmiao** [comment]
根据文件索引，https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/repodata.json 中的记载，这些文件确实不存在。

**Comment by ZenithalHourlyRate** [comment]
上游的确存在这三个文件，例如 libtiff 可以参考 https://anaconda.org/conda-forge/libtiff/files?page=3 ，但上游提供的 repodata.json 中并不包含这三个文件，因此没有被镜像。参考 https://docs.conda.io/projects/conda-build/en/latest/concepts/generating-index.html 可知除了 repodata.json 并没有别的地方记录了这些元数据信息，这可能是上游的问题。
