### ISSUE TITLE
您好，2001:da8::666这个dns非校园网还能用吗，外网nslookup解析比较慢……是不是可以修复一下，谢谢

### ISSUE THREAD

**Issue by yk00365** [tuna/issues#1495]
PS C:\Users\yk003> nslookup www.jd.com 2001:da8::666
**DNS request timed out.
    timeout was 2 seconds**.
服务器:  UnKnown
Address:  2001:da8::666

非权威应答:
名称:    img20.jcloud-cdn.com
Address:  117.72.224.129
Aliases:  www.jd.com
          www.jd.com.gslb.qianxun.com
          www.jdcdn.com
          img20.360buyimg.com.s.galileo.jcloud-cdn.com

**Comment by shankerwangmiao** [comment]
您好，

经查该服务的运行日志，并未发现异常。如果您连接该服务器有障碍，请您尝试使用其它的 DNS 服务器。

祝好，

Miao Wang
