### ISSUE TITLE
anaconda2022-05安装包5月11日上线，镜像至今未更新

### ISSUE THREAD

**Issue by kanon7** [tuna/issues#1497]
先决条件 (Prerequisites)
anaconda安装版最新版2022-05已经在5月11日上线,镜像还未更新，停留在2021-11版本，
https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/

期望的现象（What you expected to happen）
该镜像只更新2022年5月份的数据

如何重现此问题（How to reproduce it）
官网下载地址：
https://www.anaconda.com/products/distribution

**Comment by ZenithalHourlyRate** [comment]
已经同步
https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2022.05-Windows-x86_64.exe
