### ISSUE TITLE
[镜像请求] Arco Linux

### ISSUE THREAD

**Issue by Molyuu** [tuna/issues#1499]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Arco Linux,是一个基于Arch Linux的发行版，提供了一个开箱即用但并不臃肿的操作系统；另外，其与Manjaro完全使用自己的源不同，是Arch源和Arco源同时使用。Arco源内包含了一些Arco社区开发的管理系统的工具，来自AUR的预编译的包（包含某些商业软件，比如 `visual-studio-bin`）和经过Arco社区配置的桌面环境（如Plasma），软件(如zsh)等。

### 上游地址与镜像方法 (How to mirror)

https://ant.seedhost.eu/arcolinux/
https://ftp.belnet.be/arcolinux/

ftp.belnet.be 源提供 rsync 地址：
- HTTP http://ftp.belnet.be (IPv4 + IPv6)
- FTP ftp://ftp.belnet.be (IPv4 + IPv6)
- RSYNC rsync://rsync.belnet.be (IPv4)

### 镜像大小 (Mirror size)

未知。软件源应该在20GiB到100GiB中间，iso文件的源可能在100GiB左右。

### 备注 (Note)

此发行版国内外用户都较少，镜像站也较少，国内尚无软件源，且源内的包与archlinuxcn，arch4edu高度重合，并且源内包含大量商业软件。

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> 来自AUR的预编译的包（包含某些商业软件，比如 `visual-studio-bin`

可以参考 https://github.com/tuna/issues/issues/1009
