### ISSUE TITLE
MirrorRequest: Postgresql

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#15]
postgresql现在在功能上已经不输于oracle，而且完全开源免费。在很多程度上被视为oracle的开源版本。

希望tuna能镜像postgresql的软件仓库: http://www.postgresql.org/download/

**Comment by shankerwangmiao** [comment]
Syncing

**Comment by shankerwangmiao** [comment]
done

**Comment by shankerwangmiao** [comment]
因存储空间耗尽，我们已经移除该镜像。

**Comment by yylbfyl** [comment]
> 因存储空间耗尽，我们已经移除该镜像。

哥，别随便删啊，Postgresql的源我们正在用呢！
