### ISSUE TITLE
debian-multimedia 错误

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#150]
Hi:

你好。

使用 debmirror 同步 debian-multimedia，最近一直报错。看了下日志

pool/main/x/xine-ui-dmo/xine-ui_0.99.9-dmo13_amd64.deb
       1,302,086 100%    2.61MB/s    0:00:00 (xfr#101, to-chk=1/123)
pool/main/x/xine-ui-dmo/xine-ui_0.99.9-dmo13_i386.deb
       1,322,048 100%    1.42MB/s    0:00:00 (xfr#102, to-chk=0/123)
pool/main/w/wxsvg-dmo/wxsvg-dmo_1.5.10.orig.tar.bz2 missing
Download completed in 2086s.
Everything OK. Moving meta files ...
Cleanup mirror.
All done.
Failed to download files (1 errors)!

去 
https://mirrors.tuna.tsinghua.edu.cn/debian-multimedia/pool/main/w/wxsvg-dmo/ 
翻了下，的确没有这。

而 http://mirrors.ustc.edu.cn/debian-multimedia/pool/main/w/wxsvg-dmo/ 
内是有的。

Regards

River

**Comment by shankerwangmiao** [comment]
检查了一下，我们的上游服务器上也没有这个文件

http://mirror.yandex.ru/debian-multimedia/pool/main/w/wxsvg-dmo/

**Comment by shankerwangmiao** [comment]
我们已经更换了官方上游，故障已排除。
