### ISSUE TITLE
github-release/goharbor not the latest version

### ISSUE THREAD

**Issue by willzhang** [tuna/issues#1500]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

current LatestRelease not LatestRelease
https://mirrors.tuna.tsinghua.edu.cn/github-release/goharbor/harbor/LatestRelease/

v1.10.11 not latest version 
v2.5.0 is latest verison 

can you sort it by version tag?

### 期望的现象（What you expected to happen）

sycn v2.5.0

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/github-release/goharbor/harbor/LatestRelease/
diff 
https://github.com/goharbor/harbor/releases

### 操作系统（OS Version）

ubuntu 22.04

### 其他需要说明的事项（Anything else we need to know）

can you sync all version, or latest three version, thanks?

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/goharbor/harbor/v2.5.0/
