### ISSUE TITLE
Feature request: 为镜像列表提供raw file

### ISSUE THREAD

**Issue by caic99** [tuna/issues#1502]
- 需求：以[ubuntu源](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/)为例，修改`/etc/apt/sources.list`需要打开网页，复制相应的内容，在系统中打开该文件，黏贴进去。希望能提供一个`sources.list`的raw file，以实现形如`curl mirrors.tuna.tsinghua.edu.cn/config/ubuntu-22.04 | tee /etc/apt/sources.list`的操作。
- 场景：在docker镜像等不方便/不希望使用文本编辑器/从剪贴板读取内容的情况下。

**Comment by jingjingxyk** [comment]
> 

这样不久解决了
```shell

    test ! -f /etc/apt/source.list.save && cp  /etc/apt/sources.list /etc/apt/sources.list.save 

    sed -i "s@security.ubuntu.com@mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    sed -i "s@archive.ubuntu.com@mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list &&

```

**Comment by YouJiacheng** [comment]
你贴的链接里就有命令替换的方法……

**Comment by caic99** [comment]
> 你贴的链接里就有命令替换的方法……

@YouJiacheng 哈哈，这部分是新加上的，我提issue的时候还没有。

感谢 @jingjingxyk ！

由于该feature已实现，关闭此issue。
