### ISSUE TITLE
LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.tuna.tsinghua.edu.cn:443

### ISSUE THREAD

**Issue by jiangxiaoqiang** [tuna/issues#1503]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

```
➜  ~ brew tap --custom-remote --force-auto-update homebrew/cask https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-core, skipping update!
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
==> Tapping homebrew/cask
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-cask'...
fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.tuna.tsinghua.edu.cn:443
Error: Failure while executing; `git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git /opt/homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin --template=` exited with 128.
```

### 期望的现象（What you expected to happen）

正常运行

### 如何重现此问题（How to reproduce it）

macOS Monterey下执行指令：

`brew tap --custom-remote --force-auto-update homebrew/cask https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git`

### 操作系统（OS Version）

macOS Monterey 12.3.1

### 浏览器（如果适用）（Browser version, if applicable）

Google Chrome

### 其他需要说明的事项（Anything else we need to know）

```
[http]
	sslBackend = openssl
	proxy = socks5://127.0.0.1:7890
[https]
	sslBackend = openssl
	proxy = socks5://127.0.0.1:7890
[core]
	ignorecase = false
```

**Comment by ESiangChioa** [comment]
这个问题我也遇到过，和本机网络环境有关。我在家里连接正常，在公司就报错OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.tuna.tsinghua.edu.cn:443。修改了host也没用，我估计是公司网络做了过滤。

**Comment by Arnie97** [comment]
这就是收到了 TCP RST 的表现之一吧。
