### ISSUE TITLE
pypi 镜像不会随上游更改移除软件包

### ISSUE THREAD

**Issue by determ1ne** [tuna/issues#1505]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

由于 pypi 中的软件包 ctx 最近受到污染， pypi 已移除该软件包：https://pypi.org/simple/ctx/

tuna 各镜像站中的 pypi 源不能根据上游更改移除该软件包： https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/ctx/

解包 [./ctx-0.2.2.tar.gz](https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/83/2a/ea9818cdb7256ef86546d56c893d8c6504208766763e838583bded1353d4/ctx-0.2.2.tar.gz#sha256=b7644fa1e0872780690ce050c98aa2407c093473031ab5f7a8ce35c0d2fc077e) ，在 `ctx.py` 中可以搜索到恶意代码。

### 期望的现象（What you expected to happen）

根据上游移除软件包的行为删除镜像站中对应软件包

### 如何重现此问题（How to reproduce it）

-

**Comment by ZenithalHourlyRate** [comment]
感谢发现该情况，现在已经删除该软件包。

对于不会随着上游删除文件的情况，这是因为我们的同步脚本中并没有调用 `bandersnatch verify`。由于每次 `bandersnatch verify` 所需的磁盘 IO 较大，并不能每次都进行；同时，我们也出现过 verify 时某些包被误删除的情况，对此较为谨慎，故不能概率性自动化进行。

现在的策略是遇到一个包删除一个包。
