### ISSUE TITLE
请求更新voidlinux镜像使用帮助

### ISSUE THREAD

**Issue by EdenQwQ** [tuna/issues#1506]
voidlinux最近更新后将默认官方repository改成了https://repo-default.voidlinux.org
但是voidlinux的snapshot iso还没有更新
所以可以加入命令
```
sed -i 's|https://repo-default.voidlinux.org|https://mirrors.tuna.tsinghua.edu.cn/voidlinux|g'
```
或将sed方式改成使用nano/vi直接修改配置文件，将官方连接替换为tuna连接

**Comment by ZenithalHourlyRate** [comment]
您好，您可以直接对 https://github.com/tuna/mirror-web 提出 PR
