### ISSUE TITLE
mirrors 通用反向代理方案

### ISSUE THREAD

**Issue by gaoyichuan** [tuna/issues#151]
我们需要一套统一的方案，用来维护各种需要反向代理的镜像，以便于维护

**Comment by huiyiqun** [comment]
nginx

2016-11-10 10:26 GMT+08:00 Gao Yichuan <notifications@github.com>:

**Comment by bigeagle** [comment]
我个人反对这个。

**Comment by shankerwangmiao** [comment]
我也反对，所以关了吧。

**Comment by gaoyichuan** [comment]
这个东西主要考虑是有一些项目，直接镜像不方便（npm，composer）之类的，反代会比较容易

**Comment by bigeagle** [comment]
量力而行，有所为而有所不为。cnpm 有淘宝一群拿工资的职业人专门就维护一个 npm，要是他们都搞不定，我们也没那个精力。
