### ISSUE TITLE
Update Package Prompt Error

### ISSUE THREAD

**Issue by avenir2027** [tuna/issues#1510]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Update Package Prompt Error
Err:4 https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable/main aarch64 Packages
  File has unexpected size (426563 != 425938). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - Filesize:425938 [weak]
   - SHA512:0610e8c7b0ec3d6fe84ac83203a6743b8ddc4521e9ab25957c2ea9b9d6ffd63c22b425f516fff84641c33b78898bc55b82a8bebde8ac4b945df6947b9275f0d6
   - SHA256:fe56700b01ef84bcc5230f93e5cbd1c222d8605c70f5acebea80cf07d9cb1001
   - SHA1:18a28b0a743491af8ad48386c7591d7701862f20 [weak]
   - MD5Sum:0855f577b5fa4aa785f675a70a969083 [weak]
  Release file created at: Sun, 12 Jun 2022 18:27:31 +0000
Fetched 28.2 kB in 4s (7295 B/s)
Reading package lists... Done
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main/dists/stable/main/binary-aarch64/Packages.bz2  File has unexpected size (426563 != 425938). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - Filesize:425938 [weak]
    - SHA512:0610e8c7b0ec3d6fe84ac83203a6743b8ddc4521e9ab25957c2ea9b9d6ffd63c22b425f516fff84641c33b78898bc55b82a8bebde8ac4b945df6947b9275f0d6
    - SHA256:fe56700b01ef84bcc5230f93e5cbd1c222d8605c70f5acebea80cf07d9cb1001
    - SHA1:18a28b0a743491af8ad48386c7591d7701862f20 [weak]
    - MD5Sum:0855f577b5fa4aa785f675a70a969083 [weak]
   Release file created at: Sun, 12 Jun 2022 18:27:31 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

### 期望的现象（What you expected to happen）

Update Package Normally

### 如何重现此问题（How to reproduce it）

Execute  'pkg up' or 'pkg upgrade' Command

**Comment by ZenithalHourlyRate** [comment]
We have tried to sync again from upstream. You could try again to see whether the problem is resolved.

It seems that we could not connect to the upstream stably or the upstream itself is not stable.

```
Started mirroring https://packages.termux.org/apt/termux-main stable, main, aarch64!
('Connection aborted.', OSError(0, 'Error'))
('Connection aborted.', OSError(0, 'Error'))
404 Client Error: Not Found for url: https://packages.termux.dev/apt/termux-main/dists/stable/Contents-aarch64
Invalid Repository
Started mirroring https://packages.termux.org/apt/termux-main stable, main, arm!
('Connection aborted.', OSError(0, 'Error'))
('Connection aborted.', OSError(0, 'Error'))
Invalid Repository
```

**Comment by avenir2027** [comment]
> We have tried to sync again from upstream. You could try again to see whether the problem is resolved.
> 
> It seems that we could not connect to the upstream stably or the upstream itself is not stable.
> 
> ```
> Started mirroring https://packages.termux.org/apt/termux-main stable, main, aarch64!
> ('Connection aborted.', OSError(0, 'Error'))
> ('Connection aborted.', OSError(0, 'Error'))
> 404 Client Error: Not Found for url: https://packages.termux.dev/apt/termux-main/dists/stable/Contents-aarch64
> Invalid Repository
> Started mirroring https://packages.termux.org/apt/termux-main stable, main, arm!
> ('Connection aborted.', OSError(0, 'Error'))
> ('Connection aborted.', OSError(0, 'Error'))
> Invalid Repository
> ```

the error still exists, and some mirrors have the same problem.(https://github.com/termux/termux-packages/wiki/Mirrors)

**Comment by ZenithalHourlyRate** [comment]
We have switched to `packages-cf.termux.dev`. @avenir2027 could you try again?

**Comment by avenir2027** [comment]
> We have switched to `packages-cf.termux.dev`. @avenir2027 could you try again?

It's back to normal,thank you.
