### ISSUE TITLE
使用rsync同步时报错，通过排查发现是帮我加黑名单了？

### ISSUE THREAD

**Issue by lianggegithub** [tuna/issues#1511]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

你好，下面是我同步执行的语句，提示rsync: safe_read failed to read 1 bytes 报错，通过查找资料说明是服务端把我ip地址拉黑了？我折腾了好几天，花了多大量时间，我使用其它的公网ip，他就可以。

[root@localhost ~]# rsync -vvvvvt -rltDv --copy-unsafe-links --delete-after  --delete rsync://mirrors.tuna.tsinghua.edu.cn/docker-ce/ /var/www/cobbler/repo_mirror/docker-ce 
FILE_STRUCT_LEN=24, EXTRA_LEN=4
opening tcp connection to mirrors.tuna.tsinghua.edu.cn port 873
Connected to mirrors.tuna.tsinghua.edu.cn (101.6.15.130)
msg checking charset: UTF-8
rsync: safe_read failed to read 1 bytes [Receiver]: Connection reset by peer (104)
[Receiver] _exit_cleanup(code=12, file=io.c, line=276): entered
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [Receiver=3.1.2]
[Receiver] _exit_cleanup(code=12, file=io.c, line=276): about to call exit(12)

### 期望的现象（What you expected to happen）

同步成功

### 如何重现此问题（How to reproduce it）

重新执行语句：
rsync -vvvvvt -rltDv --copy-unsafe-links --delete-after  --delete rsync://mirrors.tuna.tsinghua.edu.cn/docker-ce/ /var/www/cobbler/repo_mirror/docker-ce 

### 操作系统（OS Version）

centos7

**Comment by ZenithalHourlyRate** [comment]
您好，请提供您的 IP 地址。

**Comment by lianggegithub** [comment]
我的公网ip：
58.255.37.53，
59.36.23.197



我从清华源同步的仓库比较多，有docker，centos，Ubuntu，python，k8s，cygwin等，用来做内部源使用，同步的频率比较频繁。




Liberation&nbsp;&nbsp;&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tuna/issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 中午12:36
***@***.***&gt;;
抄送:&nbsp;"Liberation   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [tuna/issues] 使用rsync同步时报错，通过排查发现是帮我加黑名单了？ (Issue #1511)





 
您好，请提供您的 IP 地址。

**Comment by Iatbzh** [comment]
您好，可以邮件沟通下吗，我的地址貌似也被拉黑了呢

**Comment by shankerwangmiao** [comment]
> 您好，可以邮件沟通下吗，我的地址貌似也被拉黑了呢

可以

**Comment by Iatbzh** [comment]
[support@tuna.tsinghua.edu.cn](maiilto:support@tuna.tsinghua.edu.cn)
是这个邮箱吗

**Comment by shankerwangmiao** [comment]
> support@tuna.tsinghua.edu.cn 是这个邮箱吗

是的
