### ISSUE TITLE
ip被禁

### ISSUE THREAD

**Issue by cuijianzhe** [tuna/issues#1512]
你好，我们的出口ip访问清华源地址https://pypi.mirrors.ustc.edu.cn/simple  不被允许，请问是把我们的IP封禁了吗？如何申诉，附ip：117.161.12.146。
![image](https://user-images.githubusercontent.com/48144475/173830074-84c98c4a-b01b-4d7d-af34-ea9f62ff4e65.png)

**Comment by cuijianzhe** [comment]
> 您好，请检查您的网络设置。如果是封禁页面，呈现的是 403 而不是该页面。

通过查看，能ping通域名，但是网站没有响应。我这里更换别的出口ip就可以。所以怀疑是咱们这边做限制了。况且到别的王炸都是正常的

**Comment by shankerwangmiao** [comment]
您好，pypi.mirrors.ustc.edu.cn 是 USTC 提供的服务，请您前往 https://github.com/ustclug/discussions/issues 反馈。
