### ISSUE TITLE
could not download nonexistent rust version `1.56.0-aarch64-apple-darwin`

### ISSUE THREAD

**Issue by jiangxiaoqiang** [tuna/issues#1513]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

➜  diesel git:(master) ✗ cargo build
info: syncing channel updates for '1.56.0-aarch64-apple-darwin'
info: downloading component 'rust'
error: could not download nonexistent rust version `1.56.0-aarch64-apple-darwin`: could not download file from 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/rust-1.56.0-aarch64-apple-darwin.tar.gz.sha256' to '/Users/xiaoqiangjiang/.rustup/tmp/srjfbbelfk248d_r_file': http request returned an unsuccessful status code: 403

### 期望的现象（What you expected to happen）

download success

### 如何重现此问题（How to reproduce it）

```
git clone https://github.com.cnpmjs.org/diesel-rs/diesel.git
cargo build
```

### 操作系统（OS Version）

macOS Monterey 12.4

**Comment by ZenithalHourlyRate** [comment]
See https://github.com/tuna/issues/issues/1346

**Comment by jiegec** [comment]
rustup mirror 仅实现了 stable/beta/nightly 的方式指定版本，没有实现按版本号。见 https://github.com/jiegec/rustup-mirror

**Comment by jiangxiaoqiang** [comment]
> rustup mirror 仅实现了 stable/beta/nightly 的方式指定版本，没有实现按版本号。见 https://github.com/jiegec/rustup-mirror

按版本号可以有么？ 中科大貌似可用

**Comment by jiegec** [comment]
> > rustup mirror 仅实现了 stable/beta/nightly 的方式指定版本，没有实现按版本号。见 https://github.com/jiegec/rustup-mirror
> 
> 按版本号可以有么？ 中科大貌似可用

可以有，目前没有实现，如果你感兴趣的话，可以贡献代码。据我所知，ustc 没有 rustup mirror。

**Comment by taoky** [comment]
> 据我所知，ustc 没有 rustup mirror。

是[反代](https://mirrors.ustc.edu.cn/help/rust-static.html)（

**Comment by jiegec** [comment]
rustup 1.25.1 版本已经提供 User-Agent。
