### ISSUE TITLE
[镜像请求] 关于trisquel的镜像请求

### ISSUE THREAD

**Issue by HuYihe2008** [tuna/issues#1517]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

镜像名称：trisquel
简介：Trisquel is an open project set in motion by the University of Vigo and developed by a volunteer community with support from the Ourense Science Faculty, the Ourense Computer Science High School and the work at initiatives such as Sognus. The project was born out of the necessity to create a free operating system with Galician language support.

### 上游地址与镜像方法 (How to mirror)

http://mirror.fsf.org/trisquel-images/

### 镜像大小 (Mirror size)

2.73GB

### 期望上线的镜像站 (Expected mirroring sites)

- [x] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [x] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> #741 用户群体小且国内已有其它镜像

https://mirrors.cernet.edu.cn/list/trisquel-images 与 https://mirrors.cernet.edu.cn/list/trisquel
