### ISSUE TITLE
Conda安装第三方包失败

### ISSUE THREAD

**Issue by qscas** [tuna/issues#1518]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用 `Anaconda Prompt(Anaconda3)` 尝试安装`cvxpy`时，`conda install -c conda-forge cvxpy`,得到如下的报错信息：
`Unable to retrieve repodata (response: 404) for https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch/current_repodata.js`
`Unable to retrieve repodata (response: 404) for https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/current_repodata.js`
将报错信息中的网址在浏览器中确实无法打开，查看 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch`后发现没有名为 `current_repodata.js`的文件，只有 `repodata.json`

### 期望的现象（What you expected to happen）

请问这个问题发生的原因以及解决办法

### 如何重现此问题（How to reproduce it）

使用 `conda install <any_package>`均会触发此问题

### 操作系统（OS Version）

Windows 10 21H1

### 其他环境（Other environments）

Anaconda 版本 ： `Anaconda3-2020.11-Windows-x86_64` 

### 其他需要说明的事项（Anything else we need to know）

`conda`配置信息
    active environment : base
    active env location : F:\anaconda3
            shell level : 1
       user config file : C:\Users\DELL\.condarc
 populated config files : C:\Users\DELL\.condarc
          conda version : 4.13.0
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=9.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : F:\anaconda3  (writable)
      conda av data dir : F:\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/msys2/repo.anaconda.com/pkgs/win-64
                          https://repo.anaconda.com/pkgs/msys2/repo.anaconda.com/pkgs/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/win-64
                          https://repo.continuum.io/pkgs/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/archive/win-64
                          https://repo.anaconda.com/pkgs/archive/noarch
          package cache : F:\anaconda3\pkgs
                          C:\Users\DELL\.conda\pkgs
                          C:\Users\DELL\AppData\Local\conda\conda\pkgs
       envs directories : F:\anaconda3\envs
                          C:\Users\DELL\.conda\envs
                          C:\Users\DELL\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.13.0 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

**Comment by ZenithalHourlyRate** [comment]
这与您的配置有关，请您删除配置中的以下两行。这可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/

```
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
```

**Comment by danny0dong163** [comment]
> 这与您的配置有关，请您删除配置中的以下两行。这可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/
> 
> ```
> https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
> https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
> ```

麻烦在不删除这两行的情况下，有办法自动从另外的地址拉取软件包么？目前我也是遇到404的错误，直接导致安装失败，后续的操作都被中断，而且因为机器比较多，一台一台修改也很麻烦啊。

**Comment by ZenithalHourlyRate** [comment]
> 麻烦在不删除这两行的情况下，有办法自动从另外的地址拉取软件包么？

上游也不包含这两个 channel，参考 https://github.com/tuna/mirror-web/commit/4b02a804f01059806f3e6361625d5b2e6ee7dbdb 和 https://github.com/tuna/issues/issues/1141

> 而且因为机器比较多，一台一台修改也很麻烦啊。

您可以使用 `for` 和 `sed` 删除它们

```
for remote in remote1 remote2 remote3; do
  ssh $remote "sed -i.bak '/\/anaconda\/pkgs\/free/d; /\/anaconda\/pkgs\/pro/d' .condarc"
done
```
