### ISSUE TITLE
composer 镜像

### ISSUE THREAD

**Issue by gaoyichuan** [tuna/issues#152]
#### 项目名称与简介(Project Intro.)
[composer](https://getcomposer.org) 是 PHP 的 package manager, 现代 PHP 框架如 [Symfony](https://symfony.com), [Laravel](https://laravel.com) 均使用了 composer 作为其依赖管理器。
#### 上游地址与镜像方法(How to Mirror)
composer 的镜像结构类似 npm, 在 [Packagist](https://packagist.org) 服务器上仅存有各包的 metadata, 包的内容通常为各个 Git repository ，全量镜像较困难。
在 composer 官方文档中给出了[几种反代+缓存的方式](https://getcomposer.org/doc/05-repositories.md#hosting-your-own)，可以考虑。
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知，全量的话应该比较大

**Comment by huiyiqun** [comment]
大鹰估计是不会同步这个的。你们想要估计得自力更生。

**Comment by gaoyichuan** [comment]
@huiyiqun 这个先放在这里，等我这一阵忙过来我来搞

**Comment by z4yx** [comment]
Replaced by 582
