### ISSUE TITLE
apt安装kubernetes返回404错误

### ISSUE THREAD

**Issue by zggzcgy** [tuna/issues#1521]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

下载程序包出现404错误（https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt/pool/*.deb）

按照[帮助文档](https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/)进行配置Ubuntu 16.04.7 ，执行`sudo apt install kubectl`返回下面错误：
```shell
user@ubuntu:~$ sudo apt install kubectl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  kubectl
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 9318 kB of archives.
After this operation, 45.7 MB of additional disk space will be used.
Err:1 https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt kubernetes-xenial/main amd64 kubectl amd64 1.24.1-00
  404  Not Found
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt/pool/kubectl_1.24.1-00_amd64_318700df48dd5dd107daca0a0c84c82d43cec827a676a597be34402635e34dfd.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### 期望的现象（What you expected to happen）

如果还支持**kubernetes**同步，期待如下：

* 安装kubernetes的操作能成功执行，并且无报错信息。
* 使用浏览器等支持http网络协议客户端访问网页https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt/pool/ 可以显示同步成功的镜像文件。

如果不再支持**kubernetes**镜像同步，期待如下：

* 镜像[主页](https://mirrors.tuna.tsinghua.edu.cn/)移除**kubernetes**超级链接
* 移除教程kubernetes[教程](https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/)内容
* 在相关位置发表为何不再支持**kubernetes**镜像同步通告

### 如何重现此问题（How to reproduce it）

按照教程https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/ 进行环境配置，配置完毕后执行下面命令：
```shell
sudo apt update
sudo apt install kubeadm kubelet kubectl
```

### 操作系统（OS Version）

Ubuntu 16.04.7 LTS

### 浏览器（如果适用）（Browser version, if applicable）

Any

### 其他环境（Other environments）

- **Operating System**: `Ubuntu 16.04.7 LTS`
- **Kernel**: `Linux 4.4.0-210-generic`
- **Architecture**: `x86-64`

### 其他需要说明的事项（Anything else we need to know）

其他镜像站点一同存在上诉问题

* TUNA - https://mirrors.tuna.tsinghua.edu.cn/
* OpenTUNA - https://opentuna.cn/

**Comment by ZenithalHourlyRate** [comment]
> * 在相关位置发表为何不再支持**kubernetes**镜像同步通告

https://mirrors.tuna.tsinghua.edu.cn/news/#remove-eol-repo

在移除较旧版本时，我们预期存在相应软件的新版本；不过目前上游 <https://packages.cloud.google.com> 并没有发布 Ubuntu 16.04 以后的版本的软件源，可能需要切换上游

> * 镜像[主页](https://mirrors.tuna.tsinghua.edu.cn/)移除**kubernetes**超级链接
> * 移除教程kubernetes[教程](https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/)内容

kubernetes yum 源仍能使用

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/news/#remove-eol-repo
> 
> 在移除较旧版本时，我们预期存在相应软件的新版本；不过目前上游 https://packages.cloud.google.com 并没有发布 Ubuntu 16.04 以后的版本的软件源，可能需要切换上游
> 

参考 https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ 与 
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/Release 中的时间戳，kubernetes 应该是只维护 xenial，该软件源应该适用于所有的版本

**Comment by ZenithalHourlyRate** [comment]
现已同步完成。
