### ISSUE TITLE
获取Androidx-main代码时出错

### ISSUE THREAD

**Issue by yuchuangu85** [tuna/issues#1522]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

执行获取命令：
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b androidx-main --partial-clone --clone-filter=blob:limit=10M

然后执行：
repo sync -j8 -c 

出现：

Fetching: 50% (20/40) platform/external/doclava
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/tools/fetch_artifact/' not found

tools/fetch_artifact:
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/tools/fetch_artifact/' not found
tools/fetch_artifact: sleeping 4.0 seconds before retrying
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/tools/fetch_artifact/' not found

tools/fetch_artifact:
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/tools/fetch_artifact/' not found
error: Cannot fetch tools/fetch_artifact from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/tools/fetch_artifact

试了多次仍然出现。

### 期望的现象（What you expected to happen）

不出现找到问题。

### 如何重现此问题（How to reproduce it）

执行上面命令即可出现

### 操作系统（OS Version）

macOS 12.4

### 其他环境（Other environments）

M1处理器

**Comment by ZenithalHourlyRate** [comment]
上游并未包含该 repo，已经向上游提交 issue，参考 https://issuetracker.google.com/issues/238579158

**Comment by yuchuangu85** [comment]
@ZenithalHourlyRate 好，谢谢

**Comment by ZenithalHourlyRate** [comment]
https://android.googlesource.com/mirror/manifest/+/0f674fbaac8872199b3de3d8ce9400c2cb63e528%5E%21/#F0

已经修复

**Comment by yuchuangu85** [comment]
@ZenithalHourlyRate 谢谢
