### ISSUE TITLE
[镜像请求] ubuntu 历史版本

### ISSUE THREAD

**Issue by leaf918** [tuna/issues#1523]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

ubuntu-release

ubuntu 16.04有多个版本，在使用硬件CUDA时，需要使用指定内核 kernel版本（如，4.4.0）的linux,现在网站上的镜像文件默认只包含最新kernel版本的镜像，这是不对的。

### 上游地址与镜像方法 (How to mirror)

https://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases/16.04/

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> ubuntu 16.04有多个版本，在使用硬件CUDA时，需要使用指定内核 kernel版本（如，4.4.0）的linux,现在网站上的镜像文件默认只包含最新kernel版本的镜像，这是不对的。

您好，镜像站中存在上述版本的内核
https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/l/linux-meta/linux-image-generic_4.4.0.21.22_amd64.deb

ubuntu-release 中仅包含 ISO，与软件源不同
