### ISSUE TITLE
[镜像请求] rocky-vault

### ISSUE THREAD

**Issue by ruixingw** [tuna/issues#1525]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Rocky Linux的历史版本仓库，类似centos-vault。

### 上游地址与镜像方法 (How to mirror)

官方似乎没有提供rsync，但至少可以yum：http://dl.rockylinux.org/vault/rocky/
如果做tier2镜像也可考虑rsync南京大学镜像站：https://mirrors.nju.edu.cn/rocky-vault/  （因为更新频率低 做tier2也不是不可以？）

### 镜像大小 (Mirror size)

876.62G as of 14 Jul 2022

### 备注 (Note)

基于与centos-vault同样的理由（https://github.com/tuna/issues/issues/440 ），申请同步rocky-vault。因为历史版本镜像几乎无更新，可以低频率同步（如一周一次）。
经搜索，目前国内的镜像站中仅南京大学镜像站有rocky-vault仓库；当南京大学镜像站因维护等原因临时不可用时，rocky-vault仓库即无国内镜像可用。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
基于与 #1236 同样的理由（#741 第六条）不予考虑。
