### ISSUE TITLE
libgfortran-ng-7.5.0-hdf63c60_6.tar.bz2和google-api-core-1.20.1-py37hc8dfbb8_0.tar.bz2,包丢失

### ISSUE THREAD

**Issue by lokizh** [tuna/issues#1526]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/libgfortran-ng-7.5.0-hdf63c60_6.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/google-api-core-1.20.1-py37hc8dfbb8_0.tar.bz2
这两个包在镜像网站上丢失

### 期望的现象（What you expected to happen）

在清华源镜像网站上能下载这两个包

### 如何重现此问题（How to reproduce it）

在清华源镜像网站上能下载这两个包

**Comment by ZenithalHourlyRate** [comment]
您好，参考 <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/repodata.json> 中的 removed 一节可知，`libgfortran-ng-7.5.0-hdf63c60_6.tar.bz2` 与 `google-api-core-1.20.1-py37hc8dfbb8_0.tar.bz2` 均不应该被同步。

**Comment by lokizh** [comment]
> 您好，参考 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/repodata.json 中的 removed 一节可知，`libgfortran-ng-7.5.0-hdf63c60_6.tar.bz2` 与 `google-api-core-1.20.1-py37hc8dfbb8_0.tar.bz2` 均不应该被同步。

您好，https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/repodata.json也无法访问

**Comment by ZenithalHourlyRate** [comment]
> 您好，[https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/repodata.json也无法访问](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/repodata.json%E4%B9%9F%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE)

我少了一段，应该是 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json
