### ISSUE TITLE
centos8的gitlab镜像为什么找不到了

### ISSUE THREAD

**Issue by MisteryLiuCode** [tuna/issues#1528]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

下载centos8的gitlab发生了404

### 期望的现象（What you expected to happen）

可以下载

### 如何重现此问题（How to reproduce it）

官网没有了8版本的镜像

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-eol-repo/
