### ISSUE TITLE
[镜像请求] fedora 仓库中的 /development 和 /updates/testing

### ISSUE THREAD

**Issue by h0cheung** [tuna/issues#1529]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

/development 包含 rawhide 和 beta 版本的 fedora 的仓库，/updates/testing 包含处于测试阶段的更新包的仓库

### 上游地址与镜像方法 (How to mirror)

同 fedora

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> #741 用户群体小且国内已有其它镜像

https://mirror.iscas.ac.cn/fedora/development/rawhide/
https://mirrors.nju.edu.cn/fedora/development/rawhide/
https://mirror.sjtu.edu.cn/fedora/linux/development/rawhide/

https://mirror.iscas.ac.cn/fedora/updates/testing/
https://mirrors.nju.edu.cn/fedora/updates/testing/
https://mirror.sjtu.edu.cn/fedora/linux/updates/testing/
