### ISSUE TITLE
brew仓库故障

### ISSUE THREAD

**Issue by xbeark** [tuna/issues#1530]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/
无法访问

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/
可以访问

### 如何重现此问题（How to reproduce it）

访问 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/ 无法从网页端访问是正常现象，使用 git 访问该网址是可以正常 clone/pull 的
