### ISSUE TITLE
jenkins 插件源

### ISSUE THREAD

**Issue by min1854** [tuna/issues#1531]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json。json 文件中的插件仍是 jenkins官方的地址，而不是镜像源的地址，导致仍然去官方源下载

### 期望的现象（What you expected to happen）

希望将 json 文件中的插件下载地址替换为镜像源。

### 如何重现此问题（How to reproduce it）

在 jenkins 中配置插件源 

### 操作系统（OS Version）

deepin

### 浏览器（如果适用）（Browser version, if applicable）

edge

**Comment by ZenithalHourlyRate** [comment]
看起来只需要将文件中的 updates.jenkins.io/download 全部替换为 mirrors.tuna.tsinghua.edu.cn/jenkins 即可？需要替换其中别的内容比如 connectionCheckUrl 吗

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/737#issuecomment-596045315

参考这里
