### ISSUE TITLE
在 Arch Linux 下使用 Firefox 和 curl 被识别为移动设备

### ISSUE THREAD

**Issue by nukemiko** [tuna/issues#1532]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

点击镜像站首页的获取镜像链接，下载任何镜像时，都会弹出页面：

> “我们检测到您正在使用移动设备下载镜像站上较大的二进制文件，为防止消耗过多流量，我们建议您改用计算机下载。”
> 00000069 969068eb66a560c1b4b4df139be2f3b1

因为开关代理、把镜像站域名加入代理排除列表不会消除此问题，可以确认与代理无关。

切换网络环境无法消除此问题。

### 期望的现象（What you expected to happen）

正常下载文件。

### 如何重现此问题（How to reproduce it）

（疑似）使用 Arch Linux 下的 Firefox/curl/wget 等工具，从以上路径下载镜像文件

### 操作系统（OS Version）

Arch Linux

### 浏览器（如果适用）（Browser version, if applicable）

Firefox

**Comment by ZenithalHourlyRate** [comment]
您所在的网段存在异常流量，即大量下载 ISO 和通过 http 遍历服务器目录，对服务器造成较大的负载，故而列入了关注列表。

建议您切换网络环境使用。

**Comment by nukemiko** [comment]
> 您所在的网段存在异常流量，即大量下载 ISO 和通过 http 遍历服务器目录，对服务器造成较大的负载，故而列入了关注列表。
> 
> 建议您切换网络环境使用。

> 大量下载ISO

我近期没有过这种行为

> 通过 http 遍历服务器目录

请问我每天运行一次 `pacman -Syu` 从你们站更新软件包也算吗？

> 建议您切换网络环境使用。

我前面说过了，切换网络环境不管用。

以及，这个关注列表是只增不减的吗？

**Comment by ZenithalHourlyRate** [comment]
> 我近期没有过这种行为

您所在的网段，并没有单指您

> 通过 http 遍历服务器目录

我们在日志中发现该网段有遍历 pypi, lede 等仓库的行为

> 我前面说过了，切换网络环境不管用。

我们的判断是基于 IP 的，您可能并没有成功切换网络环境

> 以及，这个关注列表是只增不减的吗？

一般在没有异常行为三个月后移除。
