### ISSUE TITLE
[镜像请求] 请求增加fedora-archive镜像

### ISSUE THREAD

**Issue by linuxbckp** [tuna/issues#1533]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

fedora-archive镜像是因为某些Fedora版本太老而归档的镜像，因此老版本Fedora只有通过此镜像才能使用dnf软件包管理器安装软件。
国内目前只有阿里云镜像源在同步这个镜像，点此查看阿里云的fedora-archive镜像的网址：
https://mirrors.aliyun.com/fedora-archive
也是由于阿里云镜像源把这个镜像叫做fedora-archive，所以我在这里直接沿用了fedora-archive这个名称。

由于Docker、Vagrant等虚拟化技术的普遍使用，并且这些软件所运行的操作系统的版本通常大幅度地落后于最新的版本，所以需要可以获取老版本的操作系统的软件包的镜像。对于Fedora而言，目前Vagrant最新支持的版本是Fedora33，它必须使用fedora-archive镜像才能使用dnf软件包管理器安装软件。同步fedora-archive镜像可以使软件开发和维护的过程更加方便。

### 上游地址与镜像方法 (How to mirror)

上游地址：
https://archives.fedoraproject.org/pub/archive/fedora/linux/
镜像方法：
fedora-archive镜像支持和目前的Fedora镜像的镜像方法相同的镜像方法（例如rsync）。
实质上二者都是Fedora的镜像，只不过fedora-archive镜像就是换了个服务器托管的、曾经的Fedora镜像。

### 镜像大小 (Mirror size)

Index of /pub/archive/fedora/linux
Icon  Name                    Last modified      Size  Description
[PARENTDIR] Parent Directory                             -   
[DIR] atomic/                 2016-05-16 14:56    -   
[DIR] core/                   2008-08-25 15:37    -   
[DIR] extras/                 2007-06-18 21:00    -   
[DIR] releases/               2022-05-11 22:43    -   
[DIR] updates/                2022-05-12 17:43    -   

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
> #741 用户群体小且国内已有其它镜像

> 镜像大小 (Mirror size)

Fedora 本体占用 1T 空间，archive 所占空间更大，以一个 release 占用 500G 估算，全部镜像约在 36*500G = 18T，利用率低
