### ISSUE TITLE
[镜像请求] kde-neon i386

### ISSUE THREAD

**Issue by ozqs** [tuna/issues#1534]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

<https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/>

清华已经上线了 KDE-Neon 的镜像，但缺失了i386模块。

### 上游地址与镜像方法 (How to mirror)

https://origin.archive.neon.kde.org/user/dists/focal/main/
对源地址添加即可

### 镜像大小 (Mirror size)

< 3M

### 备注 (Note)

望支持！！
望支持！！

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/binary-i386/
