### ISSUE TITLE
adoptium源有差异

### ISSUE THREAD

**Issue by LongTaiJun** [tuna/issues#1535]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/news/#rename-adoptopenjdk-to-adoptium
根据这个公告，地址已经发生改变没错，但是我发现里面存在差异，centos添加后会验证失败，确认发现url不同，对比发现tuna的镜像和官方的似乎存在差异~

### 期望的现象（What you expected to happen）

https://packages.adoptium.net/ui/native/rpm/
官方的仓库目录

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/Adoptium/rpm/
tuna的目录，似乎和官方的路径不同

### 操作系统（OS Version）

centos/rocky

### 其他环境（Other environments）

docker

### 其他需要说明的事项（Anything else we need to know）

centos下配置tuna镜像源无法进行jdk的安装~

**Comment by LongTaiJun** [comment]
https://adoptium.net/zh-CN/installation/linux/#_centosrhelfedora_instructions
这是官方添加源的文档，似乎和tuna的没有什么差异~

**Comment by ZenithalHourlyRate** [comment]
```
baseurl=https://mirrors.tuna.tsinghua.edu.cn/Adoptium/rpm/centos$releasever-$basearch/
```

应该改成这个

之前 https://github.com/tuna/mirror-web/pull/320 改的时候没注意到目录结构不同

**Comment by LongTaiJun** [comment]
https://packages.adoptium.net/ui/native/rpm/
官方的镜像库还支持rocky/fedora/rhel等系统的支持，咱们的只有centos，可以一起同步吗？

**Comment by LongTaiJun** [comment]
因为centos的生态周期问题，已经迁移到rocky了，主流公有云也支持rocky了
