### ISSUE TITLE
github的el8版本出现异常

### ISSUE THREAD

**Issue by qingchengithub** [tuna/issues#1539]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8/ 无法打开

### 期望的现象（What you expected to happen）

下载el8的github版本

### 如何重现此问题（How to reproduce it）

直接访问下面网站即可
https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8/

### 操作系统（OS Version）

centos8

### 浏览器（如果适用）（Browser version, if applicable）

google

**Comment by taoky** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/#remove-eol-repo
