### ISSUE TITLE
AOSP镜像和AOSP每月打包镜像同步失败

### ISSUE THREAD

**Issue by wzwtt** [tuna/issues#1542]
### 先决条件 (Prerequisites)

- [x] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Tuna的AOSP镜像和AOSP每月打包镜像同步失败。网站同步状态显示其最近同步成功于2022-07-25 23:18，已同步失败多时，且AOSP的八月打包镜像也没有生成。我们严重依赖于Tuna的AOSP镜像，恳请Tuna团队检查一下AOSP的同步问题。谢谢！

### 期望的现象（What you expected to happen）

同步成功

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status

**Comment by taoky** [comment]
https://issuetracker.google.com/issues/241021909

**Comment by ZenithalHourlyRate** [comment]
https://android.googlesource.com/mirror/manifest/+/f5977139b6ea7d38da32d7f51c8ada99ff70c1ed

上游已修复，AOSP 同步已成功，aosp-monthly 正在构建中

**Comment by ZenithalHourlyRate** [comment]
> aosp-monthly 正在构建中

上游在 `platform/manifest` 中[新增](https://android.googlesource.com/platform/manifest/+/9de04ec284e54130893067a5301931fb3f899de6%5E%21/)的 `external/pandora/bt-test-interfaces` 并不存在 `mirror/manifest` 中，导致镜像站中并不存在该项目，近期的 `repo sync` 均会失败，样例如下，从而导致 `aosp-monthly` 不能构建，正在等待上游解决该问题，参考 https://issuetracker.google.com/issues/241527714 。

```
fatal: repository 'http://aosp.tuna.tsinghua.edu.cn/platform/external/pandora/bt-test-interfaces/' not found
```

**Comment by ZenithalHourlyRate** [comment]
上游已修复，已经构建 aosp-20220809.tar
