### ISSUE TITLE
Ubuntu 16.04上安装gitlab，提示找不到资源

### ISSUE THREAD

**Issue by a4a404** [tuna/issues#1543]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Ubuntu 16.04上安装gitlab
使用清华大学的镜像资源，下载gitlab软件包：
deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu xenial main
sudo apt-get update 下载下来镜像资源
sudo apt-get install gitlab-ce  安装镜像资源
提示如下错误：
Err:1 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu xenial/main amd64 gitlab-ce amd64 13.12.15-ce.0
  404  Not Found
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu/pool/xenial/main/g/gitlab-ce/gitlab-ce_13.12.15-ce.0_amd64.deb  404  Not Found

### 期望的现象（What you expected to happen）

ubuntu16.04正确的镜像

### 如何重现此问题（How to reproduce it）

Ubuntu 16.04上安装gitlab
使用清华大学的镜像资源，下载gitlab软件包：

### 操作系统（OS Version）

ubuntu 16.04

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/#remove-eol-repo
