### ISSUE TITLE
无法访问 https://mirrors-i.tuna.tsinghua.edu.cn/help/docker

### ISSUE THREAD

**Issue by DevDengChao** [tuna/issues#1544]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法从 https://mirrors-i.tuna.tsinghua.edu.cn/news/docker-update/ 点击链接访问 https://mirrors-i.tuna.tsinghua.edu.cn/help/docker

### 期望的现象（What you expected to happen）

点击高亮的 “[docker镜像帮助](https://mirrors-i.tuna.tsinghua.edu.cn/help/docker)” 时， 应当跳转到正确的帮助页。

### 如何重现此问题（How to reproduce it）

如上所述。

### 操作系统（OS Version）

-

### 浏览器（如果适用）（Browser version, if applicable）

-

### 其他环境（Other environments）

-

### 其他需要说明的事项（Anything else we need to know）

-

**Comment by ZenithalHourlyRate** [comment]
> 点击高亮的 “[docker镜像帮助](https://mirrors-i.tuna.tsinghua.edu.cn/help/docker)” 时， 应当跳转到正确的帮助页。

已经不存在相应的正确帮助页面，见 https://github.com/tuna/mirror-web/commit/8f8cb1ae2bd049fd13c9cf81c5503606a4405568 ，而将上述页面指向 docker-ce 并不妥当。

**Comment by DevDengChao** [comment]
🤔 那在 https://mirrors-i.tuna.tsinghua.edu.cn/help/docker 这个位置放置一个公告是否更合适 ?
