### ISSUE TITLE
FileNotFoundError(conda-forge::absl-py-1.2.0-pyhd8ed1ab_0）

### ISSUE THREAD

**Issue by kickerqing** [tuna/issues#1545]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

conda install tensorflow=1.14
结果发现无法正常安装，提示找不到文件（https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::absl-py-1.2.0-pyhd8ed1ab_0）

### 期望的现象（What you expected to happen）

能正常安装

### 如何重现此问题（How to reproduce it）

conda install tensorflow=1.14 或 conda install numpy 都能重现

### 操作系统（OS Version）

windows10

**Comment by ZenithalHourlyRate** [comment]
> 你现在还能复现吗。

由于无回应，该 issue 关闭
