### ISSUE TITLE
清华overleaf服务需要改进

### ISSUE THREAD

**Issue by lqy16** [tuna/issues#1546]
请问overleaf.tsinghua.edu.cn是tuna管吗？服务器上缺少一些常用的latex包，比如IEEEtrans.bst (对应指令\bibliographystyle{IEEEtran})，希望改进

**Comment by lqy16** [comment]
此外源码与pdf的双向导航也不太好使，原因不明

**Comment by ZenithalHourlyRate** [comment]
@Sengxian

**Comment by Sengxian** [comment]
> 此外源码与pdf的双向导航也不太好使，原因不明

缺宏包这个事情我们已经注意到了，是 TeX Image 里面环境变量有问题导致未能识别我们额外装的宝

**Comment by lqy16** [comment]
> > 此外源码与pdf的双向导航也不太好使，原因不明
> 
> 缺宏包这个事情我们已经注意到了，是 TeX Image 里面环境变量有问题导致未能识别我们额外装的宏包
> 
> 双向导航是 Pro 付费版本功能，TsinghuaOverlaef 基于 Community 版本，因而无此功能（可能会考虑手动魔改一个

真的吗，我看Overleaf Enterprise的介绍并没有提到这个啊，把这么基础的功能做成付费是不是有点太夸张了。
我之前用本地软件texstudio编译的时候，如果安装的是texlive，也会出现无法双向导航的情况，换成miktex就好了，不知道会不会有关系（俺也不太懂，大佬轻喷

**Comment by Sengxian** [comment]
> > > 此外源码与pdf的双向导航也不太好使，原因不明
> > 
> > 
> > 缺宏包这个事情我们已经注意到了，是 TeX Image 里面环境变量有问题导致未能识别我们额外装的宏包
> > 双向导航是 Pro 付费版本功能，TsinghuaOverlaef 基于 Community 版本，因而无此功能（可能会考虑手动魔改一个
> 
> 真的吗，我看Overleaf Enterprise的介绍并没有提到这个啊，把这么基础的功能做成付费是不是有点太夸张了。 我之前用本地软件texstudio编译的时候，如果安装的是texlive，也会出现无法双向导航的情况，换成miktex就好了，不知道会不会有关系（俺也不太懂，大佬轻喷

自部署版本和 Enterprise 还不太一样，Enterprise 我理解是 Overleaf 主站提供的服务方案；如果需要单独部署 Overleaf 对应的方案是 Overleaf Server Pro。

**Comment by sparkcyf** [comment]
> 

https://github.com/overleaf/overleaf/commit/913a62fbc824eb3a6fd2620f961463688d94f240#diff-7c72797cb2d4fc6ae2b7f6fb2844348a1b9f82c1abaa3da3b051da2d4bace847

overleaf的community版本似乎在21年10月左右加入了基于synctex的双向导航，目前在[南科大的自部署overleaf](https://mirrors.sustech.edu.cn/git/sustech-cra/overleaf-ldap-oauth2)（基础镜像基于overleaf 3.1）里也能正常使用这个选项，感觉可能是tuna的版本从overleaf的上游分叉出来的太早了，以至于没有引入这个功能。

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14960340/187462939-31c155b3-49ec-4c64-bc09-a6bc081c4205.png">

**Comment by Sengxian** [comment]
@sparkcyf 收到，近期考虑升级一下

**Comment by nvmotou** [comment]
@Harry-Chen @Sengxian 不好意思挖个坟贴。请问这个功能升级了吗？现在貌似还是不太对，双向导航还是不可用的状态，焦点变化时会有加载态，但是还是没办法正常跳转。
