### ISSUE TITLE
debian源个别依赖包无法下载

### ISSUE THREAD

**Issue by smilence86** [tuna/issues#1547]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在docker中使用清华大学debian源：

```
FROM python:3.8.13-slim-bullseye

RUN sed -i "s@http://deb.debian.org@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
 && sed -i "s@http://security.debian.org@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* && cat /etc/apt/sources.list && apt update && apt autoremove -y \
 && apt upgrade -y && apt install curl ffmpeg -y
```

试了2台机器，随机遇到个别包无法下载

machine A:
Get:190 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 xkb-data all 2.29-2 [655 kB]
Get:191 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxkbcommon0 amd64 1.0.3-2 [101 kB]
Err:191 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxkbcommon0 amd64 1.0.3-2
  Error reading from server - read (5: Input/output error) [IP: 101.6.15.130 443]
Get:192 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxrandr2 amd64 2:1.5.1-1 [37.5 kB]
Get:193 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 x11-common all 1:7.7+22 [252 kB]

machine B:
Get:191 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxkbcommon0 amd64 1.0.3-2 [101 kB]
Get:192 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxrandr2 amd64 2:1.5.1-1 [37.5 kB]
Err:192 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxrandr2 amd64 2:1.5.1-1
  Error reading from server - read (5: Input/output error) [IP: 101.6.15.130 443]
Get:193 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 x11-common all 1:7.7+22 [252 kB]
Get:194 https://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libxss1 amd64 1:1.2.3-1 [17.8 kB]

我现在网络是四川移动，大部分包能正常下载，其中一个失败会导致docker build整个过程失败。

换成阿里源则正常：
```
RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list \
 && sed -i "s@http://security.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* && cat /etc/apt/sources.list && apt update && apt autoremove -y \
 && apt upgrade -y && apt install curl ffmpeg -y
```

### 期望的现象（What you expected to happen）

希望所有依赖包正常下载

### 如何重现此问题（How to reproduce it）

```
FROM python:3.8.13-slim-bullseye

RUN sed -i "s@http://deb.debian.org@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
 && sed -i "s@http://security.debian.org@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
 && rm -Rf /var/lib/apt/lists/* && cat /etc/apt/sources.list && apt update && apt autoremove -y \
 && apt upgrade -y && apt install curl ffmpeg -y
```

docker build  --network=host -t test:v1 .

**Comment by taoky** [comment]
可以尝试关闭 HTTP pipelining，参考：

- https://mirrors.ustc.edu.cn/help/debian.html
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973581

**Comment by smilence86** [comment]
> 可以尝试关闭 HTTP pipelining，参考：
> 
> * https://mirrors.ustc.edu.cn/help/debian.html
> * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973581

我在Dockerfile加了一行貌似解决了，多谢。

```
RUN echo "Acquire::http::Pipeline-Depth \"0\";" > /etc/apt/apt.conf.d/99nopipelining
```
