### ISSUE TITLE
Qt 镜像资源问题

### ISSUE THREAD

**Issue by L-Super** [tuna/issues#1548]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

当我在镜像站试图下载Qt的安装包镜像文件时，发现版本并不全，而且并无可用安装包资源可供下载。路径为`https://mirrors.tuna.tsinghua.edu.cn/qt/archive/qt/` 相对于官网或其他镜像站，缺少很多资源。

### 期望的现象（What you expected to happen）

如图，其他镜像站所提供的资源
![image](https://user-images.githubusercontent.com/40905056/183792810-0965c322-a955-429b-9ecf-4d7ae13ae67f.png)
故，希望能将对应资源补充完整，以更好的为广大中国用户进行学习研究使用。

### 如何重现此问题（How to reproduce it）

进入对应路径即可

**Comment by ZenithalHourlyRate** [comment]
> 发现版本并不全

由于 qt 占用空间较大，我们只保留了尚未 EOL 的版本，参考 https://en.wikipedia.org/wiki/Qt_version_history
