### ISSUE TITLE
SteamOS 镜像 #128 已经非常老了 目前steamos已经换用archlinux了

### ISSUE THREAD

**Issue by danyi** [tuna/issues#1549]
之前同步的steamos是2016年的事情了
当时SteamOS 是 Valve 的一个基于 Debian 的Linux发行版
目前SteamOS已经更新到3.0了，换用了Archlinux发行版
Valve 将它改名为了holoiso https://github.com/theVakhovskeIsTaken/holoiso
目前电脑要安装steamos要用他的holoiso发行版，而且后面steamos换archlinux了
里面的2个源分别是http://dl.thevakhovske.pw/
https://steamdeck-packages.steamos.cloud/archlinux-mirror/
目前正常的archlinux源没有holo这个文件夹

**Comment by ZenithalHourlyRate** [comment]
> 当时SteamOS 是 Valve 的一个基于 Debian 的Linux发行版

嗯，现有镜像已经不能发挥其作用，考虑移除这部分（目前占 500G 空间）

> 里面的2个源分别是http://dl.thevakhovske.pw/
> https://steamdeck-packages.steamos.cloud/archlinux-mirror/

有 rsync 上游吗，有预计的空间占用吗，我们目前不知道是否有镜像的必要，应该会在移除旧版本后不同步新版本了。

该 archlinux-mirror 与正常的 archlinux 除了 holo 文件夹外是否有别的区别

从 https://steamdeck-packages.steamos.cloud/archlinux-mirror/iso/latest/ 来看应该是旧版本镜像加上 valve 自己的工具

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-steamos-clickhouse/

**Comment by danyi** [comment]
我已经联系官方索取rsync 上游了，需要等待官方的回复

**Comment by Lapis-Apple** [comment]
HoloISO 似乎只是一个第三方的项目，提供通用的 ISO 和安装工具以在非 Deck 计算机安装 SteamOS3，而非 Valve 出品。

**Comment by wordlesswind** [comment]
> 我已经联系官方索取rsync 上游了，需要等待官方的回复

感觉除非 Valve 的 SteamOS 3 正式公开发行，现阶段他们不太可能回应这些请求。
又或者期待一下完美世界代理的国行版本出现，虽然这也是不太可能的事情。
