### ISSUE TITLE
[镜像请求] About new mirrors of opencv and opencv_contrib github repository.

### ISSUE THREAD

**Issue by larryw3i** [tuna/issues#1552]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Hello, TUNA Association. [opencv](https://github.com/opencv/opencv) and  [opencv_contrib](https://github.com/opencv/opencv_contrib) repositories  of OpenCV are popular Computer Vision repository, and they include many `cascades` for the computer vision beginners. It's helpful for the computer vision beginners if you make new mirrors of OpenCV. 
Regards.
larryw3i

### 上游地址与镜像方法 (How to mirror)

https://github.com/opencv/opencv
https://github.com/opencv/opencv_contrib

### 镜像大小 (Mirror size)

About 15 G to 18 G.

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
对于源码仓库我们更期待一些公开的 git 镜像服务平台提供该服务。相对于镜像站提供该服务，集中提供 git 服务的平台能更好地提高仓库的利用率。

参考 #741 第十条
