### ISSUE TITLE
下载android13正式版代码，-b哪个分支？

### ISSUE THREAD

**Issue by gengzhaoyun** [tuna/issues#1554]
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android-10.0.0_r1

android13正式版代码，后面-b哪个分支，多谢。

**Comment by ZenithalHourlyRate** [comment]
您好，与 android13 相关的分支有

```
android-13.0.0_r1
android-13.0.0_r2
android-13.0.0_r3
android13-dev
android13-gsi
android13-release
android13-security-release
android-security-13.0.0_r1
```

您可以根据您的需求选取分支

**Comment by gengzhaoyun** [comment]
看名字应该是这个了 android13-release
多谢。

**Comment by gengzhaoyun** [comment]
多谢楼上。后来我在英文版的AOSP里面看到前3个对应的不同品牌的谷歌手机，下载这仨其中之一应该不会错。
