### ISSUE TITLE
MySQL最新版本未同步

### ISSUE THREAD

**Issue by oneinstack** [tuna/issues#1555]
如题：
MySQL-8.0.30
MySQL-5.7.38
未及时同步

**Comment by wuwei928** [comment]
麻烦问下mysql-server 8.0.30 arm版官方网站没有，我们是怎么获取到的！谢谢（[mysql-server-8.0_8.0.30-0ubuntu0.20.04.2_arm64.deb](https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/pool/main/m/mysql-8.0/mysql-server-8.0_8.0.30-0ubuntu0.20.04.2_arm64.deb)）

**Comment by ZenithalHourlyRate** [comment]
> 麻烦问下mysql-server 8.0.30 arm版官方网站没有，我们是怎么获取到的！谢谢（[mysql-server-8.0_8.0.30-0ubuntu0.20.04.2_arm64.deb](https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/pool/main/m/mysql-8.0/mysql-server-8.0_8.0.30-0ubuntu0.20.04.2_arm64.deb)）

这是 ubuntu-ports 的版本，是由 ubuntu/debian 的打包者维护的，您可以参考 https://packages.ubuntu.com/focal/mysql-server

**Comment by ZenithalHourlyRate** [comment]
> 但在找到合适的上游之前该问题无法被修复

MySQL 上游已经停止工作

从我们的上游 https://ftp5.gwdg.de/ 得知其上游为 rsync.mysql.com，而该上游已停止工作

参考 https://bugs.mysql.com/bug.php?id=108203

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-julia-openresty-mysql-ftp/
