### ISSUE TITLE
[镜像请求] opus-1.3.1.tar.gz

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [tuna/issues#1558]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Opus: 高度灵活的语音和音频编码器，音视频瑞士军刀，需求量大（FFmpeg编译中）

### 上游地址与镜像方法 (How to mirror)

上游地址： https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz

### 镜像大小 (Mirror size)

不超过1M

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
单独镜像一个文件无法被用户使用

**Comment by Wheeeeeeeeels** [comment]
https://opus-codec.org/downloads/

**Comment by Wheeeeeeeeels** [comment]
ok
