### ISSUE TITLE
GNU-名称介绍-修改建议

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#156]
根据GNU的名称介绍，“GNU项目的软件包源码”，我个人认为有一些歧义，
因为该目录下大多数的软件包都包含文档，部分移植到windows的还有
二进制文件，所以，我想是不是可以把介绍改为“GNU项目的软件包（包括
文档，源代码，和部分平台的二进制文件）”。

**Comment by Harry-Chen** [comment]
十分感谢，昨天写得比较匆忙，会修改的。

**Comment by Harry-Chen** [comment]
如果您对我们的简介还有其他的意见，请不吝一并提出，谢谢您对 TUNA 的支持！

**Comment by zhangteng331** [comment]
嗯嗯，好的
