### ISSUE TITLE
gitlab-ce/yum/el8访问不了镜像

### ISSUE THREAD

**Issue by yang-qingshan** [tuna/issues#1560]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8 这个源访问不了

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8 

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/#remove-eol-repo

**Comment by ZenithalHourlyRate** [comment]
另可参考 https://mirror.nju.edu.cn/gitlab-ce/yum/el8/

**Comment by higherly** [comment]
[gitlab-ce]
name=Gitlab CE Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el$releasever/
gpgcheck=0
enabled=1
把上面的baseurl 替换成下面的就可以了么
https://mirror.nju.edu.cn/gitlab-ce/yum/el8/

**Comment by ZenithalHourlyRate** [comment]
> 把上面的baseurl 替换成下面的就可以了么

是的
