### ISSUE TITLE
It seems `tuna Server` is not included in Ubuntu updater's server list.

### ISSUE THREAD

**Issue by larryw3i** [tuna/issues#1561]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

It seems `tuna Server` is not included in Ubuntu updater's server list.
![Screenshot from 2022-08-25 18-11-20](https://user-images.githubusercontent.com/24457116/186639691-241c86a8-c561-4ec4-9666-6c6caedc694c.png)
![Screenshot from 2022-08-25 18-11-33](https://user-images.githubusercontent.com/24457116/186639936-a244f4b5-2bc0-4a6d-b1a3-4cd3b056181a.png)
![Screenshot from 2022-08-25 18-11-48](https://user-images.githubusercontent.com/24457116/186639961-0210a419-3341-475d-b569-695a495568ef.png)
And `bfsu mirror` is the same.

### 期望的现象（What you expected to happen）

Expect `tuna` and `bfsu` mirrors are included in Ubuntu updater list and they could be used easier. 

### 如何重现此问题（How to reproduce it）

Just start the Ubuntu's system application `Software & Updates`.

**Comment by ZenithalHourlyRate** [comment]
Ubuntu did not provide UA in the requests of their probers so they are blocked. We tried to report this problem but there is no response yet.

**Comment by ZenithalHourlyRate** [comment]
We have added the `HEAD` method to our whitelist so their prober should work now. They should probe a correct result in a few hours.

**Comment by ZenithalHourlyRate** [comment]
Fixed now.

**Comment by happyaron** [comment]
@ZenithalHourlyRate the same problem also exists on mirrors.bfsu.edu.cn https://launchpad.net/ubuntu/+mirror/mirrors.bfsu.edu.cn-archive
