### ISSUE TITLE
[镜像请求] epel archive

### ISSUE THREAD

**Issue by lygstate** [tuna/issues#1562]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

http://download.fedoraproject.org/pub/archive/epel
没有镜像
centos6没法从其更新

### 上游地址与镜像方法 (How to mirror)

参考 http://download.fedoraproject.org/pub/epel

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您可以参考 #1072 与 #872

鉴于类似 *-archive 的仓库占用空间较大（往往达到数T），用户需求相对较少，而 TUNA 空间有限（考虑到诸如 pypi 等仓库无休止的增长），建议寻求其余空间较大的镜像站的支持

您可以参考 https://mirrors.cernet.edu.cn/site/
