### ISSUE TITLE
[镜像请求] centos debuginfo

### ISSUE THREAD

**Issue by lygstate** [tuna/issues#1563]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

http://debuginfo.centos.org/

### 上游地址与镜像方法 (How to mirror)

http://debuginfo.centos.org/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by YouJiacheng** [comment]
tuna的政策不镜像发行版的调试符号包。https://github.com/tuna/issues/issues/741
9.占用空间大而利用率低
例如：各发行版提供调试符号包
