### ISSUE TITLE
[镜像请求] micromamba

### ISSUE THREAD

**Issue by YouJiacheng** [tuna/issues#1565]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html

### 上游地址与镜像方法 (How to mirror)

严格意义上讲，该软件可于https://anaconda.org/conda-forge/micromamba/files 下载，因而已经被包含于tuna的conda-forge镜像中，但tuna拒绝对非conda的user-agent提供文件，制作docker image或编写CI时用wget或curl下载不方便。即使不考虑user-agent限制，需要指定版本而非如miniforge那样可以直接下载latest也不方便。
除了conda-forge之外，也可以从官方提供的
https://micro.mamba.pm/api/micromamba/$PLATFORM/latest 通过http下载（但似乎两者指向同一个s3存储），其中PLATFORM可为linux-64，linux-aarch64，linux-ppc64le，win-64，osx-64，osx-arm64

### 镜像大小 (Mirror size)

31.4MB，也许可复用conda-forge镜像存储

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by YouJiacheng** [comment]
似乎在不符合政策的边缘试探，不过micromamba和miniforge性质类似，感觉应该可以

**Comment by ZenithalHourlyRate** [comment]
> 但tuna拒绝对非conda的user-agent提供文件，制作docker image或编写CI时用wget或curl下载不方便。

这里的「不方便」能详细展开吗，我们目前是对无 UA 用户以及部分被滥用的 UA 返回 403，并没有对于 /anaconda 拒绝非 conda user-agent

**Comment by YouJiacheng** [comment]
OK发现其实还好，因为映射关系有点复杂没有实际试过（tuna的conda-forge永远是"Too many files to list"，参考别的channel才搞对）
```bash
MICROMAMBA_VERSION='0.25.1'
TARGET_PLATFORM='linux-64'
wget "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/${TARGET_PLATFORM}/micromamba-${MICROMAMBA_VERSION}-0.tar.bz2"
wget "https://anaconda.org/conda-forge/micromamba/${MICROMAMBA_VERSION}/download/${TARGET_PLATFORM}/micromamba-${MICROMAMBA_VERSION}-0.tar.bz2"
```
