### ISSUE TITLE
快速下载链接Git未同步更新并404

### ISSUE THREAD

**Issue by Goojoe** [tuna/issues#1566]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

获取下载链接>应用软件>Git 404 没有开始下载

### 期望的现象（What you expected to happen）

同步更新最新版本并正常下载

### 如何重现此问题（How to reproduce it）

此页所有Git下载链接
![image](https://user-images.githubusercontent.com/78355492/187659209-7430b9d6-a0f3-47c7-8c72-763138f1e5c9.png)

### 操作系统（OS Version）

Windows

### 浏览器（如果适用）（Browser version, if applicable）

Chrome 105.0.5195.54 64bit

### 其他需要说明的事项（Anything else we need to know）

[此页正常](https://mirrors.tuna.tsinghua.edu.cn/github-release/git-for-windows/git/LatestRelease/)
快速下载链接没有同步更新

**Comment by ZenithalHourlyRate** [comment]
Fixed now
