### ISSUE TITLE
pip安装pynwb包的2.5.1版本应该从tuna源中删去

### ISSUE THREAD

**Issue by bjmiao** [tuna/issues#1567]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用tuna源时，使用`pip install pynwb`时，会安装一个错误的版本2.5.1。
![image](https://user-images.githubusercontent.com/23629902/187686034-fdb2e7d9-1bed-47eb-b991-0f6cba01f14c.png)

现在[pynwb](https://github.com/NeurodataWithoutBorders/pynwb)最高版本只有2.1.0. 这个2.5.1是一个写错版本号的发布（在解了pip包的commit号之后，发现其对应的版本在github上是**1**.5.1，所以大胆猜测是pynwb开发者在打包时手抖写错了第一位版本号）。

这一错误的版本会导致后续的问题。由于在不指定版本号时，pip似乎会自动安装版本号最大的版本，所以在默认情况下使用tuna的pip源就会安装到这个错误版本，在别的包（例如AllenSDK）的requirements里面写了一个不指定版本号的pynwb依赖时，整个安装的依赖就会出现问题。

关于2.5.1这个版本是错误的，在别的issue中也被提到
by @rly in https://github.com/NeurodataWithoutBorders/matnwb/issues/304#issuecomment-908532013_

在默认的pypi源中，pynwb的版本是正确的2.1.0
![image](https://user-images.githubusercontent.com/23629902/187687166-4cf4cf0f-76cf-46ea-ba8a-aa74f29cbae2.png)

所以看起来这是tuna的源本身的问题。

### 期望的现象（What you expected to happen）

把tuna里面pynwb的2.5.1版本删掉

### 如何重现此问题（How to reproduce it）

`pip download -i https://pypi.tuna.tsinghua.edu.cn/simple pynwb`
然后应该会看到安装了2.5.1版本。但这是个错误的版本。

**Comment by ZenithalHourlyRate** [comment]
现在应该已经修好了
