### ISSUE TITLE
MacPorts 镜像

### ISSUE THREAD

**Issue by xuchunyang** [tuna/issues#157]
#### 项目名称与简介(Project Intro.)

[MacPorts](https://www.macports.org/) 是一个 Mac OS 包管理器，

#### 上游地址与镜像方法(How to Mirror)

大致步骤：

1. 用 Rsync 同步文件
2. 用 Web Server 和 Rsync 服务
3. 联系上游以启用镜像

详细文档见：https://trac.macports.org/wiki/Mirroring

#### 其他信息(Other)
- 镜像大小(Mirror Size): 约 1 TB

**Comment by shankerwangmiao** [comment]
Syncing

**Comment by xuchunyang** [comment]
MacPorts 用户可以修改

- MacPorts Source （用来升级 MacPorts 自身的）
- Portfiles （Package 的描述文件，类似 `apt update`）

的获取方式，需要通过 `rsync`，等你们的 `rsync` 服务好了，我试试。

而更关键的二进制包和源代码包的获取方式用户没法改，需要等开发者修改 MacPorts 的源代码。

**Comment by Harry-Chen** [comment]
done

**Comment by xuchunyang** [comment]
由于 MacPorts 镜像几乎必须要上游主动添加支持之后才能用。联系方法见：https://trac.macports.org/wiki/Mirroring#Contactus ，请问有没有联系上？

---

另外，同步 Portfiles 的时候遇到一个问题。把 `/opt/local/etc/macports/sources.conf` 的内容改成

    rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs/ports.tar [default]

后，`sudo port -d selfupdate` 会卡在 

```
...

--->  Updating the ports tree
Synchronizing local ports tree from rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs/ports.tar
DEBUG: /usr/bin/rsync -rtzv --delete-after --progress --include=/ports.tar --include=/ports.tar.rmd160 --exclude=* rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs/ /opt/local/var/macports/sources/mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs

...

receiving file list ... 
3 files to consider
./
ports.tar
```

试了几次都卡在这里，但是手动执行完全相同的 `rsync` 命令并没有问题。不像是镜像的问题。我现在改成了 HTTP 方式同步

    https://mirrors.tuna.tsinghua.edu.cn/macports/release/ports.tar.gz [default]

这种方法没问题。

**Comment by shankerwangmiao** [comment]
已经发信了，没有回信。

**Comment by bigeagle** [comment]
刚收到官方回信，分配了三个官方域名

https://pek.cn.distfiles.macports.org/macports/
https://pek.cn.packages.macports.org/macports/
rsync://pek.cn.rsync.macports.org/macports/

**Comment by alick** [comment]
看着有点像隔壁呵呵

Regards,
Tao

**Comment by shankerwangmiao** [comment]
pek 是机场名
> 在 2016年12月7日，07:28，Alick Zhao <notifications@github.com> 写道：
> 
> 看着有点像隔壁呵呵
> 
> Regards,
> Tao
>
