### ISSUE TITLE
default_channels中的地址404错误导致conda安装中断

### ISSUE THREAD

**Issue by danny0dong163** [tuna/issues#1572]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

default_channels中包含无效url，conda安装过程遇到404错误，安装中断。

想知道不删除无效的url的情况下，有没有办法自动从另外的地址拉取软件包。否则后续的操作都被中断，而且因为机器比较多，一台一台修改也很麻烦。
 

### 期望的现象（What you expected to happen）

conda安装软件包依然可以继续工作

### 如何重现此问题（How to reproduce it）

default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
 

### 操作系统（OS Version）

centos

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1518#issuecomment-1234060346
