### ISSUE TITLE
openresty源文件缺失。

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1573]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/openresty/centos/7/x86_64/repodata/repomd.xml中的文件：
10a658583ca24aea2d5c31a3ae35b93c0ff2b20409e5bad05f8990204896889e-primary.sqlite.bz2不存在，导致无法下载

https://mirrors.tuna.tsinghua.edu.cn/openresty/centos/7/x86_64/repodata/10a658583ca24aea2d5c31a3ae35b93c0ff2b20409e5bad05f8990204896889e-primary.sqlite.bz2

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/openresty/centos/7/x86_64/repodata/10a658583ca24aea2d5c31a3ae35b93c0ff2b20409e5bad05f8990204896889e-primary.sqlite.bz2

### 如何重现此问题（How to reproduce it）

wget https://mirrors.tuna.tsinghua.edu.cn/openresty/centos/7/x86_64/repodata/10a658583ca24aea2d5c31a3ae35b93c0ff2b20409e5bad05f8990204896889e-primary.sqlite.bz2

**Comment by ZenithalHourlyRate** [comment]
参考 https://mirrors.tuna.tsinghua.edu.cn/openresty/centos/7/x86_64/repodata/ 与 https://openresty.org/package/centos/7/x86_64/repodata/ ，我们的 repodata.xml 比上游新……

```
# 上游
repomd.xml                                         17-May-2022 19:46                2987
repomd.xml.asc                                     17-May-2022 19:46                 490
# 我们
repomd.xml | 2.9 KiB | 2022-05-18 03:49
repomd.xml.asc | 490 B | 2022-05-18 03:49
```

可能是上游更新了文件后再次更「新」（使其时间戳变旧）而 lftp 第二次同步时认为我们的比上游更新（我们配置了 only-newer 选项）故而没更新

正在删除文件并重新同步

**Comment by ZenithalHourlyRate** [comment]
已经修复
