### ISSUE TITLE
无vulkan-icd-loader-1.3.226-1-x86_64.pkg.tar.zst

### ISSUE THREAD

**Issue by beta-Cyg** [tuna/issues#1575]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在更新软件包时，pacman无法在镜像源中找到vulkan-icd-loader-1.3.226-1-x86_64.pkg.tar.zst包

### 期望的现象（What you expected to happen）

成功下载此包

### 如何重现此问题（How to reproduce it）

运行命令行
```sudo pacman -S vulkan-icd-loader```

### 操作系统（OS Version）

Arch Linux

### 其他环境（Other environments）

/

### 其他需要说明的事项（Anything else we need to know）

/

**Comment by cubercsl** [comment]
https://mirrors.tuna.tsinghua.edu.cn/archlinux/extra/os/x86_64/chromium-105.0.5195.102-2-x86_64.pkg.tar.zst

![image](https://user-images.githubusercontent.com/22931465/189121149-fdd9c90c-dc87-48e1-826a-d551f89c1a31.png)

此文件下载也得到 404 的结果。

**Comment by ZenithalHourlyRate** [comment]
镜像站正在同步，extra 中的软链接与 pool 中的状态并不对应

**Comment by ZenithalHourlyRate** [comment]
同步完成
