### ISSUE TITLE
似乎mongodb的镜像内容和官方不一致

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1576]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/

https://mirrors.tuna.tsinghua.edu.cn/mongodb/apt/ubuntu/dists/jammy/mongodb-org/

官方源和tuna源的jammy mongodb-org目录内容不一致。

### 期望的现象（What you expected to happen）

烦请同步，并协助看下其他目录是否存在不同步？

### 如何重现此问题（How to reproduce it）

浏览器访问。

### 操作系统（OS Version）

any

### 浏览器（如果适用）（Browser version, if applicable）

any

**Comment by ZenithalHourlyRate** [comment]
由于我们使用脚本而非 rsync 同步，与上游文件结构不一致是预期现象

3.6/4.0 等老文件夹的内容已经不存在，我们目前同步了 4.2/4.4/5.0 版本

看起来 6.0 版本已经发布，会增加相应的同步

**Comment by ZenithalHourlyRate** [comment]
已经同步

**Comment by 89ao** [comment]
> 已经同步

目前看，似乎官方又增加了development和testing目录，建议自动发现并增加新目录同步哈。
