### ISSUE TITLE
centos-vault 有文件损坏

### ISSUE THREAD

**Issue by CyanoHao** [tuna/issues#1577]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

`centos-vault/3.9/updates/x86_64/headers/XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr` 文件内容和上游不一致，导致 CentOS 3 更新失败。

### 期望的现象（What you expected to happen）

文件内容和上游一致，能更新成功。

### 如何重现此问题（How to reproduce it）

```bash
$ curl https://mirrors.tuna.tsinghua.edu.cn/centos-vault/3.9/updates/x86_64/headers/XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr | sha1sum
f37b5a2b4c8924e6874f46f45e6f0e83d5bdbead  -
$ curl https://vault.centos.org/3.9/updates/x86_64/headers/XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr | sha1sum
aaca7a4c2163e69396e67e21940d2768d92c7210  -
```

**Comment by CyanoHao** [comment]
更新：`centos-vault/3.9/updates/x86_64/headers/kernel-source-0-2.4.21-63.EL.x86_64.hdr` 也损坏了。
```bash
$ curl https://mirrors.tuna.tsinghua.edu.cn/centos-vault/3.9/updates/x86_64/headers/kernel-source-0-2.4.21-63.EL.x86_64.hdr | sha1sum
16169d4bc755a5ec6da042d6c6545cf1557bf8f2  -
$ curl https://vault.centos.org/3.9/updates/x86_64/headers/kernel-source-0-2.4.21-63.EL.x86_64.hdr | sha1sum
165313abebfcd108b4107fafb925679a08e191fb  -
```
可能需要进一步核查其他文件是否一致。

**Comment by ZenithalHourlyRate** [comment]
```
https://ftp.jaist.ac.jp/pub/Linux/CentOS-vault/3.9/updates/x86_64/headers/XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr
https://archive.kernel.org/centos-vault/3.9/updates/x86_64/headers/XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr 
```

这几家和我们的 sha1sum 是相同的

可能上游通过 rsync 和通过 https 提供的文件不是同一个文件

**Comment by ZenithalHourlyRate** [comment]
我们和 kernel.org 的文件是损坏的,我们正在重新同步

**Comment by ZenithalHourlyRate** [comment]
损坏的 XFree86-Xnest-0-4.3.0-128.EL.x86_64.hdr 的前 64K 与正常文件不同, 剩下的部分相同

损坏的 kernel-source-0-2.4.21-63.EL.x86_64.hdr 的前 320K 与正常文件不同, 剩下的部分相同

**Comment by ZenithalHourlyRate** [comment]
据不完整排查，文件损坏的镜像有

https://archive.kernel.org/centos-vault/
https://mirrors.cernet.edu.cn/list/centos-vault 中的所有镜像
https://mirrors.cloud.tencent.com/centos-vault/
https://ftp.iij.ad.jp/pub/linux/centos-vault/
https://ftp.riken.jp/Linux/centos-vault/
https://mirror.math.princeton.edu/pub/centos-vault/

**Comment by ZenithalHourlyRate** [comment]
通过与 cern 的同步修复了其中一台服务器的文件，我们将应用该改动到别的服务器上

以下是损坏文件列表
https://gist.github.com/ZenithalHourlyRate/4268e632ccfd2337d5e92d6e16dc0590

**Comment by taoky** [comment]
作为参考，rsync 支持从文件列表进行更新：

```
rsync -cavP --files-from=/tmp/centos-vault-list rsync://linuxsoft.cern.ch/centos-vault/ .
```

**Comment by ZenithalHourlyRate** [comment]
> 通过与 cern 的同步修复了其中一台服务器的文件，我们将应用该改动到别的服务器上

已经修复了 tuna 和 bfsu
