### ISSUE TITLE
Invalid Repository 'tuna-sle-update'

### ISSUE THREAD

**Issue by 1216892614** [tuna/issues#1578]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

- `sudo zypper ref` on my `openSUSE Leap 15.3`

```shell
Repository 'tuna-sle-update' is invalid.
[tuna-sle-update|https://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.3/sle/] Valid metadata not found at specified URL
History:
 - File './repodata/90b3029a245c047eb8a7895372bc410b8cc9a68857b54b70d9d28188e9eeeeec-deltainfo.xml.gz' not found on medium 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.3/sle/'
 - Can't provide ./repodata/90b3029a245c047eb8a7895372bc410b8cc9a68857b54b70d9d28188e9eeeeec-deltainfo.xml.gz

Please check if the URIs defined for this repository are pointing to a valid repository.
```

### 期望的现象（What you expected to happen）

all Repositorys work.

### 如何重现此问题（How to reproduce it）

`sudo zypper ref` on my `openSUSE Leap 15.3`

### 操作系统（OS Version）

openSUSE Leap 15.3 in WSL2 on Windows11

### 浏览器（如果适用）（Browser version, if applicable）

No such thing.

**Comment by ZenithalHourlyRate** [comment]
我们的上游 rsync://fr2.rpmfind.net/linux/opensuse/ 也是这个状态，需要等上游更新。rsync://stage.opensuse.org/opensuse-full-with-factory/opensuse/ 其余使用该上游的镜子正在同步中（最近教育网到欧洲状态较差）

可以耐心等待或切到其他状态较老的镜像，例如 USTC/NJU
