### ISSUE TITLE
issues on homebrew-bottle mirror

### ISSUE THREAD

**Issue by zeminha** [tuna/issues#158]
尊敬的TUNA团队，你好：
本人使用贵团队维护的homebrew mirror已有很长时间，但最近出现了问题，贵网站也显示“failed”，请问具体是何种原因，是不是upstrem的问题，谢谢，并对耽误贵团队的时间表示微小的歉意
此致 敬礼

**Comment by shankerwangmiao** [comment]
是的，我们的上游 USTC 的 rsync 挂了

**Comment by shankerwangmiao** [comment]
目前正在与上游联系

**Comment by zeminha** [comment]
谢谢 蛤蛤

**Comment by shankerwangmiao** [comment]
目前勉强更新了一次，不过 ustc 那边压力也很大，不一定都是成功的。

**Comment by xavieryao** [comment]
本质在于使用 gaoyifan/homebrew-bottole-mirror 或者其他手段直接镜像 homebrew-bottle。Refer: #172
