### ISSUE TITLE
tuna git镜像无响应

### ISSUE THREAD

**Issue by everything411** [tuna/issues#1580]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用git克隆tuna的镜像，镜像站没有响应，git卡住
```
git clone https://mirrors.tuna.tsinghua.edu.cn/git/binutils-gdb.git
正克隆到 'binutils-gdb'...
```
此外基于git的crates.io索引也无法工作，运行cargo卡住
```
cargo run
    Updating `tuna` index
```

### 期望的现象（What you expected to happen）

git镜像可以正常工作

### 如何重现此问题（How to reproduce it）

```
git clone https://mirrors.tuna.tsinghua.edu.cn/git/binutils-gdb.git
```

### 操作系统（OS Version）

Windows 11 Dev 25197

### 其他需要说明的事项（Anything else we need to know）

更换网络环境没有用，ipv4/ipv6均无响应

**Comment by ZenithalHourlyRate** [comment]
我们用来服务 git 的镜像 OOM 中……

**Comment by ZenithalHourlyRate** [comment]
重启了服务，现在应该工作了

**Comment by XuehaiPan** [comment]
响应非常慢，会在 clone into 'xxx' 的位置卡很久：

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/16078332/190840941-65a11b3e-b99a-4a9f-9669-0799f0f3b9c8.png">
