### ISSUE TITLE
lineageos镜像更新失败

### ISSUE THREAD

**Issue by miangou** [tuna/issues#1581]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/full/sagit/ 
最近更新的都是空文件夹

### 期望的现象（What you expected to happen）

出现正确的包

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/full/sagit/

### 操作系统（OS Version）

linux

### 浏览器（如果适用）（Browser version, if applicable）

chrome

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by ZenithalHourlyRate** [comment]
最近到上游速度不佳（约 20KB/s），同步难以追上

暂无解决方案

**Comment by ZenithalHourlyRate** [comment]
> 最近到上游速度不佳（约 20KB/s），同步难以追上

上游切换到了 USTC，已经恢复同步。
