### ISSUE TITLE
homebrew-core访问504

### ISSUE THREAD

**Issue by qiqizjl** [tuna/issues#1585]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/7540584/190845837-6fe3a3f2-c0ff-47eb-aa58-51fc9ab10135.png">
克隆 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
返回504

### 期望的现象（What you expected to happen）

可以正常克隆

### 如何重现此问题（How to reproduce it）

git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

**Comment by qiqizjl** [comment]
brew和homebrew-cask 也有类似的问题 只是很慢，不至于出现504

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/7540584/190846358-4fbbd9b5-7b62-4d85-9457-5c245ee5d8b7.png">

**Comment by ZenithalHourlyRate** [comment]
参考 #1580 ，最近正在 OOM

**Comment by ZenithalHourlyRate** [comment]
现已恢复
