### ISSUE TITLE
[镜像请求] Homebrew/glibc-bootstrap

### ISSUE THREAD

**Issue by XuehaiPan** [tuna/issues#1586]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

自 `brew` 3.6.0 开始，`glibc` 将成为 Linux 上所有软件包的依赖。如果用户没有安装 Homebrew 至 `/home/linuxbrew/.linuxbrew` (如无 `sudo` 权限)，则用户无法使用 Homebrew 预编译的 bottles。此时 Homebrew 将下载 `https://github.com/Homebrew/glibc-bootstrap` 仓库中的文件来编译 `glibc`。对于国内用户，访问 github.com 可能较慢，故此请求镜像。

### 上游地址与镜像方法 (How to mirror)

将 `Homebrew/glibc-bootstrap` 仓库的 release assets 同步至 `HOMEBREW_BOTTLE_DOMAIN/glibc-bootstrap/<tag>/<filename>`.

例如：

将

```
https://github.com/Homebrew/glibc-bootstrap/releases/download/1.0.0/bootstrap-binutils-2.38.tar.gz
```

镜像至 (`HOMEBRWE_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"`)

```
https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/glibc-bootstrap/1.0.0/bootstrap-binutils-2.38.tar.gz
```

### 镜像大小 (Mirror size)

200MB

### 备注 (Note)

相关 issue/PR:

- Homebrew/glibc-bootstrap#6
- Homebrew/brew#13875

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/glibc-bootstrap/1.0.0/
https://mirrors.bfsu.edu.cn/homebrew-bottles/glibc-bootstrap/1.0.0/

**Comment by XuehaiPan** [comment]
Resolved by tuna/tunasync-scripts@f25bb97936adf4629da9c7ce5b54a7b54c570451

**Comment by yueyinqiu** [comment]
请问这个是如何使用的？我已配置 `export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"` 但是它仍然试图访问 GitHub ：

```
✘ Resource glibc--bootstrap-binutils
Error: Failed to download resource "glibc--bootstrap-binutils"
Download failed: https://github.com/Homebrew/glibc-bootstrap/releases/download/1.1.1/bootstrap-x86_64-binutils-2.43.1.tar.gzesource glibc--bootstrap-gcc
-#O=#   #    #                                                                                                          
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```

**Comment by ZenithalHourlyRate** [comment]
homebrew 一般来说不提供稳定的接口；在issue开启当时可能是该路径，现在可能是另一个路径，需要具体分析 brew 的源码才能知道现在的接口。
