### ISSUE TITLE
pkgsrc镜像使用问题

### ISSUE THREAD

**Issue by Wongboo** [tuna/issues#1588]
现在pkgsrc镜像的使用其实是一个问题，具体表现在pkgsrc的更新上，现在的镜像对更新不太方便。pkgsrc的更新可以分为两种：一，基于tar包，但据[NetBSD文档](https://www.netbsd.org/docs/pkgsrc/getting.html#uptodate)该种方法官方不推荐；二，基于版本控制，具体又分两种，一种是官方文档中的CVS，但一方面CVS极不流行，另一方面镜像站似乎不支持CVS（也可能是我没找到），二种，是[官方的git库](https://github.com/NetBSD/pkgsrc)，个人感觉这种方式较为方便，虽然官方文档没有写，其中
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/current/pkgsrc/ 基本对应trunk分支
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/pkgsrc-2021Q4/pkgsrc/ 基本对应pkgsrc-2021Q4分支
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/pkgsrc-2022Q1/pkgsrc/ 基本对应pkgsrc-2022Q1分支
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/pkgsrc-2022Q2/pkgsrc/ 基本对应pkgsrc-2022Q2分支
希望能够根据其git库的形式有更好的解决方案，个人认为镜像中现在能被使用的主要是package和tarball，distfile，pkgsrc更新并不方便。
另：镜像站中pkgsrc的文档似乎较少，如果git库能提供，我可以贡献git库相应文档

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/git/pkgsrc.git

试试能否使用该地址更新 pkgsrc?

**Comment by Wongboo** [comment]
@ZenithalHourlyRate 有道理，用sparse checkout将https://mirrors.tuna.tsinghua.edu.cn/git/pkgsrc.git 中的current/pkgsrc clone下来，用其他分支的也可以类似。
不过这样可能会有一个小问题，这样pkgsrc的目录会变成$REPO_DIR/current/pkgsrc。编译时又将多次使用这个长长的目录名，用symlink感觉也不能解决这个问题。

**Comment by ZenithalHourlyRate** [comment]
> current/pkgsrc

这个 git 仓库中应该没有这个路径?

**Comment by ZenithalHourlyRate** [comment]
> 另：镜像站中pkgsrc的文档似乎较少，如果git库能提供，我可以贡献git库相应文档

可以提供相应文档吗
