### ISSUE TITLE
香港拉取epel镜像时获取了更新时间比网站上对应repomd.xml更新时间更晚的文件

### ISSUE THREAD

**Issue by yizaber** [tuna/issues#1591]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我们在香港存在两台epel镜像服务器，但是9/23日拉取epel文件时两台服务器出现了不一致，其中一台拉取的对应repomd.xml与另一台的repomd.xml不一致，假设为server1与server2，其中server2种的repomd.xml文件及db文件与网站上可视的repomd.xml文件及db文件一致，且更新时间为9/21，但是server1中 的repomd.xml文件与db文件与网站上不一致，且文件更新时间为9/23，为验证问题，从两台服务器上直接wget https://mirrors.tuna.tsinghua.edu.cn/epel/7/x86_64/repodata/repomd.xml，结果也不一致，同时检查/epel/8/Everything/x86_64/repodata/repomd.xml及对应的db文件也存在不一致的问题

### 期望的现象（What you expected to happen）

两台服务器通过rsync拉取获得的文件应该一致

### 如何重现此问题（How to reproduce it）

在两台服务器上执行wget https://mirrors.tuna.tsinghua.edu.cn/epel/7/x86_64/repodata/repomd.xml

### 操作系统（OS Version）

centos 7.6

### 浏览器（如果适用）（Browser version, if applicable）

none

### 其他环境（Other environments）

none

### 其他需要说明的事项（Anything else we need to know）

none

**Comment by shankerwangmiao** [comment]
（与您询问的具体问题无关）注意到您的服务器位于香港，建议您从 rsync://mirrors.xtom.hk 同步会获得更好的效果。

**Comment by yizaber** [comment]
我们会考虑修改镜像源至香港本地的源，但是这个问题实在是让我困惑，或许是香港附近的cache服务器缓存了脏数据么

**Comment by shankerwangmiao** [comment]
不是，我们没有额外的缓存服务器。

**Comment by yizaber** [comment]
那非常奇怪了，我在邮件群组中发了邮件，收到了其他人的邮件似乎也有存在相同问题的源，例如https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/repodata/ 中的repomd.xml与当前目录的db文件并不匹配

**Comment by shankerwangmiao** [comment]
您好，现在应该已经处理好了，都更新成了 23 日版本的文件了。
