### ISSUE TITLE
 juliaup 镜像同步问题

### ISSUE THREAD

**Issue by zsz00** [tuna/issues#1593]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

juliaup 的镜像服务站 里的 [RELEASECHANNELVERSION](https://mirrors.tuna.tsinghua.edu.cn/julia-releases/juliaup/RELEASECHANNELVERSION) 更新总是不同步, 导致用镜像站 更新升级 juliaup 会得到旧版本的juliaup.

### 期望的现象（What you expected to happen）

juliaup 的镜像服务站 里的 [RELEASECHANNELVERSION](https://mirrors.tuna.tsinghua.edu.cn/julia-releases/juliaup/RELEASECHANNELVERSION)  能正常更新, 同步

### 如何重现此问题（How to reproduce it）

直接查看RELEASECHANNELVERSION里的版本 和 juliaup 上游版本是否一致, 或看其更新时间

https://discourse.juliacn.com/t/topic/6712   juliaup 镜像同步问题

**Comment by zsz00** [comment]
https://discourse.juliacn.com/t/topic/6712

**Comment by ZenithalHourlyRate** [comment]
我们并没有开启 `--size-only`，不过文档中说

> --size-only (boolean) Makes the size of each key the only criteria used to decide whether to sync from source to destination.
>
> --exact-timestamps (boolean) When syncing from S3 to local, same-sized items will be ignored only when the timestamps match exactly. **The default behavior is to ignore same-sized items unless the local version is newer than the S3 version.**

看起来这些旧文件也不会被更新，我加一个 `--exact-timestamps` 试试

**Comment by ZenithalHourlyRate** [comment]
> 我加一个 `--exact-timestamps` 试试

现在工作了

参考 https://github.com/aws/aws-cli/issues/3415 ，应该对所有的 s3 sync 加上这个选项
