### ISSUE TITLE
Stackage: 过时的 7z.dll 

### ISSUE THREAD

**Issue by HoshinoTented** [tuna/issues#1595]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

stack version: `Version 2.9.1`
镜像版本: `stackage, stack >= v2.5.1`

尝试在没有通过 `stack` 安装过 `ghc` 的计算机上运行 `stack ghc`，`ghc` 下载成功，但其他部件下载失败：

```
> stack ghc --resolver ghc-9.2.2
Warning: http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml: Unrecognized field in GHCDownloadInfo: version
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.
Preparing to download 7z.dll ...
Download expectation failure: ContentLength header
Expected: 1814016
Actual:   447488
For: https://mirrors.tuna.tsinghua.edu.cn/github-raw/fpco/minghc/master/bin/7z.dll
```

发现是镜像使用了 [过时的](https://github.com/fpco/minghc) 的 `7z.dll` （`7z.exe` 也是），而 [官方的 `stack-setup.yaml`](https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml) 引用的则是 [其仓库 release 中的文件](https://github.com/commercialhaskell/stackage-content/releases)

### 期望的现象（What you expected to happen）

安装成功，没有 `Content-Length` 错误。

### 如何重现此问题（How to reproduce it）

在问题解决前，在一台没有通过 `stack` 安装过 `ghc` 的计算机上 [配置 tuna 的 stackage 镜像](https://mirrors.tuna.tsinghua.edu.cn/help/stackage/)，并运行 `stack ghc`

### 操作系统（OS Version）

Windows 11

**Comment by ZenithalHourlyRate** [comment]
已修复。
