### ISSUE TITLE
 rustup warning: Signature verification failed

### ISSUE THREAD

**Issue by rock2dust** [tuna/issues#1596]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

安装了rustup清华源
```bash
echo 'export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup' >> ~/.bashrc
echo 'export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup' >> ~/.bashrc
```

运行 rustup check

```bash
~$ rustup check
warning: Signature verification failed for 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/channel-rust-stable.toml'
```

### 期望的现象（What you expected to happen）

不应该有warning

### 如何重现此问题（How to reproduce it）

rustup check
rustup update

**Comment by jiegec** [comment]
这个没有办法，rustup 镜像会修改 toml 文件里面的 url，所以 signature 一定是被破坏的。
