### ISSUE TITLE
conda-forge::colorama-0.4.5-pyhd8ed1ab_0镜像消失

### ISSUE THREAD

**Issue by Wu2017211646** [tuna/issues#1598]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

ERROR conda.core.link:_execute(502): An error occurred while installing package 'http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::colorama-0.4.5-pyhd8ed1ab_0'.

### 期望的现象（What you expected to happen）

conda-forge::colorama-0.4.5-pyhd8ed1ab_0

### 如何重现此问题（How to reproduce it）

conda升级python版本中出现

### 操作系统（OS Version）

win10

**Comment by ZenithalHourlyRate** [comment]
镜像站上存在
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/colorama-0.4.5-pyhd8ed1ab_0.tar.bz2 文件

> ERROR conda.core.link:_execute(502): An error occurred while installing package 'http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::colorama-0.4.5-pyhd8ed1ab_0'.

请附上更详细的报错信息，如果返回值是 403，您可以提供您的 IP 地址
