### ISSUE TITLE
可以添加一下FreeBSD的pkg镜像和ports镜像吗？

### ISSUE THREAD

**Issue by MagiCarbon** [tuna/issues#16]
如题。

**Comment by bigeagle** [comment]
磁盘快满了，等到有新磁盘再议。

同时由于FreeBSD [不再接受第三方源](https://www.freebsd.org/doc/en/articles/hubs/mirror-official.html#mirror-official-become)，我个人不太愿意同步。

**Comment by KenetJervet** [comment]
Bump on this one. The official China mirror is literally unusable.

We wouldn't really mind if you are official or not. It would just be as good given it works.

**Comment by bigeagle** [comment]
Hi @KenetJervet ,

We are sorry that none of our team members has solid experience on FreeBSD. Even if we were to setup a FreeBSD mirror, we would not be able to even test whether it works. No mentioning that the FreeBSD community did not provide any documentation on how to setup a mirror. 

To make this simple, we don't know how to setup and maintain a FreeBSD mirror, and we don't provide services that we ourselves cannot test it. Providing that the FreeBSD community is very unfriendly to mirror site maintainers, we think it's more appropriate to respect the FreeBSD community's decision.

Cheers,

**Comment by KenetJervet** [comment]
@bigeagle Fair enough. Thanks. ;)

**Comment by ykla** [comment]
中科大最近同步了PKG源，并提供了脚本，TUNA可否一并给予同步？..?
附脚本：
https://github.com/ustclug/ustcmirror-images/blob/master/freebsd-pkg/sync.sh

**Comment by shankerwangmiao** [comment]
暂不考虑
