### ISSUE TITLE
[镜像请求]请求镜像GitHub上优秀项目的release

### ISSUE THREAD

**Issue by wzwtt** [tuna/issues#1600]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Ventoy：一个新的u盘启动方案，解决了u盘内多镜像启动时需要反复格式化的问题。
MifareClassicTool：经典的安卓 NFC 读写工具。
rustdesk：开源的远程控制软件。
notepad2：轻量的文本编辑器。
a32nx：开源的 Airbus A320neo 飞机机模。
NanaZip：适配了 Windows 11 右键菜单的 7-zip 衍生品。
MuseScore：开源、流行的音乐制谱软件。
PowerToys：微软出品的开源生产力小工具

### 上游地址与镜像方法 (How to mirror)

https://github.com/ventoy/Ventoy/releases
https://github.com/ikarus23/MifareClassicTool/releases
https://github.com/rustdesk/rustdesk/releases
https://github.com/zufuliu/notepad2/releases
https://github.com/flybywiresim/a32nx/releases
https://github.com/M2Team/NanaZip/releases
https://github.com/musescore/MuseScore/releases
https://github.com/microsoft/PowerToys/releases

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
感谢提议，我们会在最近的空间问题缓解后添加其中的部分软件

**Comment by Harry-Chen** [comment]
已经同步完成，增加了 Ventoy、Rustdesk、Notepad2、NanaZip、MuseScore、PowerToys。

可提出 PR 更新 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 以增加下载链接。

**Comment by Harry-Chen** [comment]
Fixed by https://github.com/tuna/mirror-web/pull/422
