### ISSUE TITLE
话说Stream ⑨ stream 要如何换源

### ISSUE THREAD

**Issue by KudouShinnyan** [tuna/issues#1603]
镜像源那里没有帮助文档, 虽然有人提供了把全部内容替换的方法(没尝试), 莪更喜欢基于原文件修改
莪是用Termux启动rootfs的, arm64的, 源的文件貌似没有baseurl, 所以只能插入了, 莪执行下面的命令把metalink注释掉然后把全部源都插入了对应的baseurl, 打开文件看起来像是成功插入, 但是没办法更新源

`sed -e 's!^metalink=!#metalink=!g' \`
`-e '/\[baseos\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/BaseOS\/$basearch\/os\/|}' \`
`-e '/\[baseos-debug/{n;s|$|\nhttps:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/BaseOS\/$basearch\/debug\/tree\/|}' \`
`-e '/\[baseos-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/BaseOS\/source\/tree\/|}' \`
`-e '/\[appstream\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/AppStream\/$basearch\/os\/|}' \`
`-e '/\[appstream-debug/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/AppStream\/$basearch\/debug\/tree\/|}' \`
`-e '/\[appstream-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/AppStream\/source\/tree\/|}' \`
`-e '/\[crb\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/CRB\/$basearch\/os\/|}' \`
`-e '/\[crb-debug/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/CRB\/$basearch\/debug\/tree\/|}' \`
`-e '/\[crb-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/CRB\/source\/tree\/|}' \`
`-i /etc/yum.repos.d/centos.repo`

`sed -e 's!^metalink=!#metalink=!g' \`
`-e '/\[highavailability\]/{n;s|$|\nhttps:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/HighAvailability\/$basearch\/os\/|}' \`
`-e '/\[highavailability-debug/{n;s|$|\nhttps:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/HighAvailability\/$basearch\/debug\/tree\/|}' \`
`-e '/\[highavailability-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/HighAvailability\/source\/tree\/|}' \`
`-e '/\[nfv\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/NFV\/$basearch\/os\/|}' \`
`-e '/\[nfv-debug/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/NFV\/$basearch\/debug\/tree\/|}' \`
`-e '/\[nfv-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/NFV\/source\/tree\/|}' \`
`-e '/\[rt\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/RT\/$basearch\/os\/|}' \`
`-e '/\[rt-debug/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/RT\/$basearch\/debug\/tree\/|}' \`
`-e '/\[rt-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/RT\/source\/tree\/|}' \`
`-e '/\[resilientstorage\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/ResilientStorage\/$basearch\/os\/|}' \`
`-e '/\[resilientstorage-debug/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/ResilientStorage\/$basearch\/debug\/tree\/|}' \`
`-e '/\[resilientstorage-source\]/{n;s|$|\nbaseurl=https:\/\/mirrors.bfsu.edu.cn\/centos-stream\/9-stream\/ResilientStorage\/source\/tree\/|}' \`
`-i /etc/yum.repos.d/centos-addons.repo`

`sed -i 's/#metalink=https:\/\/mirrors.centos.org\/metalink?repo=centos-extras/metalink=https:\/\/mirrors.centos.org\/metalink?repo=centos-extras/g' /etc/yum.repos.d/centos-addons.repo`

`yum makecache`

**Comment by Zhuoy3** [comment]
我也遇到了这个问题，我尝试写了脚本来实现……

有点糙，不过用起来没什么问题，yum makecache能正常更新

```
#!/usr/bin/perl

use strict;
use warnings;
use autodie;

my $mirrors = 'https://mirrors.tuna.tsinghua.edu.cn';

my $filename = shift @ARGV;
if (!defined $filename) {
    die "Usage: $0 <filename>\n";
}

my $backup_filename = $filename . '.bak';
rename $filename, $backup_filename;

open my $input, "<", $backup_filename;
open my $output, ">", $filename;

while (<$input>) {
    s/^metalink/# metalink/;

    if (m/^name/) {
        my (undef, $repo, $arch) = split /-/;
        $repo = trim($repo);
        $arch = defined $arch ? lc(trim($arch)) : '';

        $_ .= "baseurl=${mirrors}/centos-stream/9-stream/$repo" . ($arch eq 'source' ? "/" : "/\$basearch/") . ($arch ne '' ? "${arch}/tree/" : "os") . "\n";
    }
    
    print $output $_;
}

sub trim {
    my ($s) = @_;
    $s =~ s/^\s+|\s+$//g;
    return $s;
}
```

**Comment by ZenithalHourlyRate** [comment]
我一直没看看这个事情[捂脸]，centos 9 需要这么复杂吗

**Comment by Zhuoy3** [comment]
> 我一直没看看这个事情[捂脸]，centos 9 需要这么复杂吗

因为centos 9的repo里没有baseurl，没法直接替换，只能硬插，所以有点麻烦:joy:

**Comment by ZenithalHourlyRate** [comment]
> 没法直接替换，只能硬插，所以有点麻烦

您有兴趣把它变成帮助文档的一部分吗，参考 https://github.com/mirrorz-org/mirrorz-help/issues/53

**Comment by Zhuoy3** [comment]
> 您有兴趣把它变成帮助文档的一部分吗

我很乐意，但我没有相关经验，是通过创建一个PR吗？

**Comment by ZenithalHourlyRate** [comment]
@Zhuoy3 是的，您可以往 mirrorz-help 创建 PR，内容放在 contents/ 下。您可以参考 centos.mdx （文字部分）与 CPAN.mdx （语法高亮部分）书写相关内容

**Comment by KudouShinnyan** [comment]
> 我也遇到了这个问题，我尝试写了脚本来实现……
> 
> 有点糙，不过用起来没什么问题，yum makecache能正常更新
> 

![Screenshot_20230511-105729_Termux](https://github.com/tuna/issues/assets/68854981/57a0c8a4-0c76-41c1-8660-d07e2a6db6c2)

**Comment by Zhuoy3** [comment]
@KudouShinnyan 额这是一个perl脚本，你安装的centos镜像没有包含perl或者相关的编译环境？

可以尝试一下```sudo dnf install -y perl perl-devel```

**Comment by KudouShinnyan** [comment]
> @KudouShinnyan 额这是一个perl脚本，你安装的centos镜像没有包含perl或者相关的编译环境？
> 
> 可以尝试一下`sudo dnf install -y perl perl-devel`

莪是用Termux启动这里的镜像使用的https://mirrors.bfsu.edu.cn/lxc-images/images/centos/9-Stream/arm64/default/

话说只安装perl它也会自动关联依赖包括不限于perl-devel, 不过装了近300个包并且以后不一定会再次使用它们, 感觉有点多, 感觉最理想的状态是不装什么直接用现有的完成
![Screenshot_20230511-151010_Termux](https://github.com/tuna/issues/assets/68854981/237d2e5e-e7c6-4dd4-930b-46beb677e0d7)

装完再次执行是这样的
![Screenshot_20230511-152529_Termux](https://github.com/tuna/issues/assets/68854981/c1386ef0-540c-4193-9a10-ea0cfd06fd10)

没成功插入baseurl
![Screenshot_20230511-152817_MT管理器](https://github.com/tuna/issues/assets/68854981/3f6bcf9e-c741-4e22-a9c6-d3ceb2915a47)

**Comment by Zhuoy3** [comment]
> 装完再次执行是这样的

> 没成功插入baseurl

这里运行没问题了，它需要一个参数，你需要修改的文件…


我没有考虑到部分镜像会移除perl的问题，如果是最小化安装的话，是不是py3也被移除了？

如果使用sh实现……有点丑😂

**Comment by KudouShinnyan** [comment]
> > 装完再次执行是这样的
> 
> > 没成功插入baseurl
> 
> 这里运行没问题了，它需要一个参数，你需要修改的文件…
> 
> 我没有考虑到部分镜像会移除perl的问题，如果是最小化安装的话，是不是py3也被移除了？
> 
> 如果使用sh实现……有点丑😂

自带python3.9, yum依赖它

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/mirror-web/commit/435e746c6c0de658de27e68a24f930ab174a77e2
