### ISSUE TITLE
influxdata 的 yum 镜像，repodata 文件体积偏大

### ISSUE THREAD

**Issue by HuangShaoyan** [tuna/issues#1604]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

influxdata 的 yum 镜像，repodata 目录下的文件体积比官方源大，且文件名与官方源不同。

特别是 primary.sqlite.bz2，超过 600MiB，下载耗时很大。

https://mirrors.tuna.tsinghua.edu.cn/influxdata/yum/el7-x86_64/repodata/
https://repos.influxdata.com/rhel/7/x86_64/stable/repodata/

### 期望的现象（What you expected to happen）

repodata 与官方源站相同，或至少能有合理的文件体积。

### 如何重现此问题（How to reproduce it）

直接从浏览器查看即可。

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/1252429/197387971-61fa3f43-b604-40a6-9574-3b603dc752e2.png">

**Comment by ZenithalHourlyRate** [comment]
已修复
