### ISSUE TITLE
[镜像请求]  Hello Minecraft! Launcher(HMCL)

### ISSUE THREAD

**Issue by FurryRbl** [tuna/issues#1606]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Hello Minecraft! Launcher是一个在GPL3.0下开源的Minecraft 启动器

### 上游地址与镜像方法 (How to mirror)

https://github.com/huanghongxun/HMCL/releases

### 镜像大小 (Mirror size)

≈20M

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by wxkj123** [comment]
It seems so crazy of you! 
Tsinghua University OpenSource Mirror is used only for study but not gaming.

**Comment by FurryRbl** [comment]
> 

ah so sorry, maybe I didn't read the code of conduct carefully
