### ISSUE TITLE
mongodb源与官方的目录差异

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1609]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

经查，tuna源的同步上游是https://repo.mongodb.org：
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/5635923/200464819-8bbc0942-e31f-46fc-8291-88c3aa28a80b.png">

但似乎发现有目录不一致的情况，例如：
 https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/ 
Index of mongodb-org
Parent Directory
4.2
4.4
5.0
6.0
development
testing
repo.mongodb.org

但tuna的目录结构如下：
https://mirrors.tuna.tsinghua.edu.cn/mongodb/apt/ubuntu/dists/jammy/mongodb-org/
File Name  ↓ 	File Size  ↓ 	Date  ↓ 
Parent directory/	-	-
3.6/	-	2022-05-04 00:23
4.0/	-	2022-05-04 00:23
4.2/	-	2022-11-07 16:49
4.4/	-	2022-11-07 16:49
5.0/	-	2022-11-07 16:48
6.0/	-	2022-11-07 16:47

### 期望的现象（What you expected to happen）

是否对目录结构有额外修改？如无是否建议与官方保持一致更好？

### 如何重现此问题（How to reproduce it）

https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/ 
https://mirrors.tuna.tsinghua.edu.cn/mongodb/apt/ubuntu/dists/jammy/mongodb-org/

**Comment by ZenithalHourlyRate** [comment]
> 是否对目录结构有额外修改？如无是否建议与官方保持一致更好？

https://github.com/tuna/issues/issues/1576#issuecomment-1241500484

并无额外修改，只是选择了部分目录进行同步，参考 https://github.com/tuna/tunasync-scripts/blob/48e45fa12ee13a802efee46a810dc8f99f2ed67d/mongodb.sh#L11

3.6 等旧目录元数据未被删除（同步脚本只删除具体软件包）

> 目前看，似乎官方又增加了development和testing目录，建议自动发现并增加新目录同步哈。 https://github.com/tuna/issues/issues/1576#issuecomment-1306559228

对于这类源我们一般不同步测试与开发分支，用户较少
