### ISSUE TITLE
google chrome镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#161]
#### 项目名称与简介(Project Intro.)
chrome是目前市场占有率最高的浏览器了。不过最近发现google最后一片净土dl.google.com也因为某种不可抗拒的力量消失了。导致国内彻底与chrome仓库绝缘。

#### 上游地址与镜像方法(How to Mirror)
直接镜像chrome的deb/rpm仓库即可，也可以考虑反向代理dl.google.com,因为这样不止可以镜像chrome，也能镜像google earch, android sdk等其他从dl.google.com走的资源

**Comment by gaoyichuan** [comment]
chrome会涉及版权问题吧，我们会另行讨论

**Comment by abcfy2** [comment]
如果是反向代理`dl.google.com`的方式呢？也涉及到版权吗？

**Comment by bigeagle** [comment]
很为难，反向代理是灰色地带，我个人很不愿意搞。访问不便、又很有用的东西太多了，我们是开源镜像站，而不是科学上网提供商。开这个先例，难免哪天会有人来说要不要给 [一系列网站] 也反向代理了。
