### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by liangzi10101** [tuna/issues#1612]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/protobuf-3.17.3.big_sur.bottle.tar.gz

### 上游地址与镜像方法 (How to mirror)

https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/protobuf-3.17.3.big_sur.bottle.tar.gz

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您好，镜像站上有 protobuf@3-3.20.3.arm64_big_sur.bottle.tar.gz

您可以在 `brew update` 后再次尝试
