### ISSUE TITLE
Bioconductor源是不是不会同步以前版本的R包，我用3.6.3版本的R，对应的biocversion是3.10

### ISSUE THREAD

**Issue by Le-dawn** [tuna/issues#1614]
报错信息如下：

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> chooseBioCmirror()
Secure BioC mirrors 

 1: 0-Bioconductor (World-wide) [https]
 2: Germany (Gottingen) [https]
 3: Japan (Tachikawa) [https]
 4: Japan (Wako) [https]
 5: China (Peking) [https]
 6: China (Hefei Anhui) [https]
 7: Norway (Bergen) [https]
 8: Denmark (Aalborg) [https]
 9: Sweden (Umea) [https]
10: (other mirrors)

Selection: 5
> BiocManager::install("BiocVersion"='3.10')
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://mirrors.bfsu.edu.cn/CRAN/

Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/bioc/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/workflows/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/workflows/src/contrib/PACKAGES'
Bioconductor version 3.10 (BiocManager 1.30.15), R 3.6.3 (2020-02-29)
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/bioc/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/workflows/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.10/workflows/src/contrib/PACKAGES'
Old packages: 'aroma.core', 'BiocManager', 'bit', 'Cairo', 'data.table',
  'ggpubr', 'magic', 'markdown', 'Matrix', 'modelr', 'pbapply', 'pkgload',
  'plyr', 'R.utils', 'rbibutils', 'roxygen2', 'vctrs', 'xfun'
Update all/some/none? [a/s/n]:

**Comment by ZenithalHourlyRate** [comment]
服务器上确实没有 3.10 版本的软件包

**Comment by ZenithalHourlyRate** [comment]
> 我记得以前还能用的，最近才用不了，你知道是啥情况吗

四月份时 bioconductor 占 2TB 空间，现在只占 500G，应该是上游删掉了旧版本

**Comment by Le-dawn** [comment]
> > 我记得以前还能用的，最近才用不了，你知道是啥情况吗
> 
> 四月份时 bioconductor 占 2TB 空间，现在只占 500G，应该是上游删掉了旧版本

上游指得是bioconductor官方源吗，我试过用bioconductor官方源安装R包可以正常安装，但是速度太慢了

**Comment by ZenithalHourlyRate** [comment]
> 上游指得是bioconductor官方源吗

是的。不过上游通过 rsync 提供的官方源和 https 提供的官方源可能不同，一般来说，由于镜像站空间限制，前者仅包含最新版本

**Comment by Le-dawn** [comment]
> > 上游指得是bioconductor官方源吗
> 
> 是的。不过上游通过 rsync 提供的官方源和 https 提供的官方源可能不同，一般来说，由于镜像站空间限制，前者仅包含最新版本

官方源删除旧版本的同步，镜像站的旧版本软件包没有保留在本地吗，以前同步的软件包是否还在呢

**Comment by Le-dawn** [comment]
> > 上游指得是bioconductor官方源吗
> 
> 是的。不过上游通过 rsync 提供的官方源和 https 提供的官方源可能不同，一般来说，由于镜像站空间限制，前者仅包含最新版本

我看官方镜像同步文件中有指定版本的rsync同步方式，示例命令如下，是否可以尝试一下：

rsync -e "ssh -i ~/.ssh" -zrtlv --delete \
    bioc-rsync@master.bioconductor.org:3.16/bioc \
    ~/bioconductor_repositories/3.16/bioc

**Comment by shankerwangmiao** [comment]
我们已经同步了全部版本

**Comment by ZenithalHourlyRate** [comment]
> 执行多次把以前的版本也加入到同步

上游的这些目录也已经没有数据了

**Comment by Le-dawn** [comment]
> > 执行多次把以前的版本也加入到同步
> 
> 上游的这些目录也已经没有数据了

这样啊，那以前同步过的安装包还在吗

**Comment by ZenithalHourlyRate** [comment]
> 那以前同步过的安装包还在吗

不在了，我们严格同步上游

**Comment by Le-dawn** [comment]
> 不在了，我们严格同步上游

> 我们已经同步了全部版本

好吧，还是谢谢二位的解答
