### ISSUE TITLE
jenkins的镜像updator里面的地址修改

### ISSUE THREAD

**Issue by hightall** [tuna/issues#162]
#### 希望在你们的updator json里面的下载地址能替换成清华的jenkins的plugins的下载地址，要不然，用了你们的updator json还是从官网下载。现在只能是手动下载下来，自己去把地址替换掉。

**Comment by abcfy2** [comment]
见这个issue: https://github.com/tuna/issues/issues/119

jenkins使用的`updates.jenkins.io`域名会cname到`mirrors.jenkins.io`，会自动解析到jenkins的其他镜像站上。曾经jenkins的镜像站是有tuna的: http://mirrors.jenkins-ci.org/status.html ，后来撤掉了，理由就是上面的那个issue。因为tuna强制走https，但是jenkins的代码中并未对30x跳转做友好的处理，导致在更新插件的时候会各种报错，目前官方也没修复这个问题，所以你改了也没什么用。

**Comment by bigeagle** [comment]
看起来 jenkins 是打算长期不管 https 了……
当时觉得他们可能很快搞定这个的。

我们联系一下 jenkins 把 HTTP 方式加进去好了。

**Comment by huiyiqun** [comment]
http://mirrors.jenkins-ci.org/status.html#CN

看起来已经改好了，并且type也已经改成了http。
