### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu vaness

### ISSUE THREAD

**Issue by yyfashundun** [tuna/issues#1620]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu vanessa Release” 没有 Release 文件。

### 期望的现象（What you expected to happen）

更新成功

### 如何重现此问题（How to reproduce it）

按照网站给的教程

### 操作系统（OS Version）

linux minit

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu vanessa Release

我们没有镜像 linux mint 相关版本

您可以尝试使用 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu yammy
