### ISSUE TITLE
缺失一些Python模块的版本

### ISSUE THREAD

**Issue by xmubeta** [tuna/issues#1621]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

有些模块没有最新或者特定版本

pip3 install awscli==1.25.84  - 旧版本
pip3 install snowflake-connector-python==2.8.2  -- 次新版本 

### 期望的现象（What you expected to happen）

想问一下pypi是否同步正常？ 

### 如何重现此问题（How to reproduce it）

[ec2-user@ip-172-31-189-232 ~]$ pip3 install snowflake-connector-python==2.8.2
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://opentuna.cn/pypi/web/simple
ERROR: Could not find a version that satisfies the requirement snowflake-connector-python==2.8.2 (from versions: 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.6.12, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.9.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9)
ERROR: No matching distribution found for snowflake-connector-python==2.8.2

[ec2-user@ip-172-31-189-232 ~]$ pip3 install awscli==1.25.84
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://opentuna.cn/pypi/web/simple
ERROR: Could not find a version that satisfies the requirement awscli==1.25.84 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.1, 0.9.2, 0.9.3, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.3.19, 1.3.20, 1.3.21, 1.3.22, 1.3.23, 1.3.24, 1.3.25, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.7.12, 1.7.13, 1.7.14, 1.7.15, 1.7.16, 1.7.17, 1.7.18, 1.7.19, 1.7.20, 1.7.21, 1.7.22, 1.7.23, 1.7.24, 1.7.25, 1.7.26, 1.7.27, 1.7.28, 1.7.29, 1.7.30, 1.7.31, 1.7.32, 1.7.33, 1.7.34, 1.7.35, 1.7.36, 1.7.37, 1.7.38, 1.7.39, 1.7.40, 1.7.41, 1.7.42, 1.7.43, 1.7.44, 1.7.45, 1.7.46, 1.7.47, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.9.14, 1.9.15, 1.9.16, 1.9.17, 1.9.18, 1.9.19, 1.9.20, 1.9.21, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.10.13, 1.10.14, 1.10.15, 1.10.16, 1.10.17, 1.10.18, 1.10.19, 1.10.20, 1.10.21, 1.10.22, 1.10.23, 1.10.24, 1.10.25, 1.10.26, 1.10.27, 1.10.28, 1.10.29, 1.10.30, 1.10.31, 1.10.32, 1.10.33, 1.10.34, 1.10.35, 1.10.36, 1.10.37, 1.10.38, 1.10.39, 1.10.40, 1.10.41, 1.10.42, 1.10.43, 1.10.44, 1.10.45, 1.10.46, 1.10.47, 1.10.48, 1.10.49, 1.10.50, 1.10.51, 1.10.52, 1.10.53, 1.10.54, 1.10.56, 1.10.57, 1.10.58, 1.10.59, 1.10.60, 1.10.61, 1.10.62, 1.10.63, 1.10.64, 1.10.65, 1.10.66, 1.10.67, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.19, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29, 1.11.30, 1.11.31, 1.11.32, 1.11.33, 1.11.34, 1.11.35, 1.11.36, 1.11.37, 1.11.38, 1.11.39, 1.11.40, 1.11.41, 1.11.42, 1.11.43, 1.11.44, 1.11.45, 1.11.46, 1.11.47, 1.11.48, 1.11.49, 1.11.50, 1.11.51, 1.11.52, 1.11.53, 1.11.54, 1.11.55, 1.11.56, 1.11.57, 1.11.58, 1.11.59, 1.11.60, 1.11.61, 1.11.62, 1.11.63, 1.11.64, 1.11.65, 1.11.66, 1.11.67, 1.11.68, 1.11.69, 1.11.70, 1.11.71, 1.11.72, 1.11.73, 1.11.74, 1.11.75, 1.11.76, 1.11.77, 1.11.78, 1.11.79, 1.11.80, 1.11.81, 1.11.82, 1.11.83, 1.11.84, 1.11.85, 1.11.86, 1.11.87, 1.11.88, 1.11.89, 1.11.90, 1.11.91, 1.11.92, 1.11.93, 1.11.94, 1.11.95, 1.11.96, 1.11.97, 1.11.98, 1.11.99, 1.11.100, 1.11.101, 1.11.102, 1.11.103, 1.11.104, 1.11.105, 1.11.106, 1.11.107, 1.11.108, 1.11.109, 1.11.110, 1.11.111, 1.11.112, 1.11.113, 1.11.114, 1.11.115, 1.11.116, 1.11.117, 1.11.118, 1.11.119, 1.11.120, 1.11.121, 1.11.122, 1.11.123, 1.11.124, 1.11.125, 1.11.126, 1.11.127, 1.11.128, 1.11.129, 1.11.130, 1.11.131, 1.11.132, 1.11.133, 1.11.134, 1.11.135, 1.11.136, 1.11.137, 1.11.138, 1.11.139, 1.11.140, 1.11.141, 1.11.142, 1.11.143, 1.11.144, 1.11.145, 1.11.146, 1.11.147, 1.11.148, 1.11.149, 1.11.150, 1.11.151, 1.11.152, 1.11.153, 1.11.154, 1.11.155, 1.11.156, 1.11.157, 1.11.158, 1.11.159, 1.11.160, 1.11.161, 1.11.162, 1.11.163, 1.11.164, 1.11.165, 1.11.166, 1.11.167, 1.11.168, 1.11.169, 1.11.170, 1.11.171, 1.11.172, 1.11.173, 1.11.174, 1.11.175, 1.11.176, 1.11.177, 1.11.178, 1.11.179, 1.11.180, 1.11.181, 1.11.182, 1.11.183, 1.11.184, 1.11.185, 1.11.186, 1.11.187, 1.11.188, 1.11.189, 1.11.190, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.14.7, 1.14.8, 1.14.9, 1.14.10, 1.14.11, 1.14.12, 1.14.13, 1.14.14, 1.14.15, 1.14.16, 1.14.17, 1.14.18, 1.14.19, 1.14.20, 1.14.21, 1.14.22, 1.14.23, 1.14.24, 1.14.25, 1.14.26, 1.14.27, 1.14.28, 1.14.29, 1.14.30, 1.14.31, 1.14.32, 1.14.33, 1.14.34, 1.14.35, 1.14.36, 1.14.37, 1.14.38, 1.14.39, 1.14.40, 1.14.41, 1.14.42, 1.14.43, 1.14.44, 1.14.45, 1.14.46, 1.14.47, 1.14.48, 1.14.49, 1.14.50, 1.14.51, 1.14.52, 1.14.53, 1.14.54, 1.14.55, 1.14.56, 1.14.57, 1.14.58, 1.14.59, 1.14.60, 1.14.61, 1.14.62, 1.14.63, 1.14.64, 1.14.65, 1.14.66, 1.14.67, 1.14.68, 1.14.69, 1.14.70, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.15.6, 1.15.7, 1.15.8, 1.15.9, 1.15.10, 1.15.11, 1.15.12, 1.15.13, 1.15.14, 1.15.15, 1.15.16, 1.15.17, 1.15.18, 1.15.19, 1.15.20, 1.15.21, 1.15.22, 1.15.23, 1.15.24, 1.15.25, 1.15.26, 1.15.27, 1.15.28, 1.15.29, 1.15.30, 1.15.31, 1.15.32, 1.15.33, 1.15.34, 1.15.35, 1.15.36, 1.15.37, 1.15.38, 1.15.39, 1.15.40, 1.15.41, 1.15.42, 1.15.43, 1.15.44, 1.15.45, 1.15.46, 1.15.47, 1.15.48, 1.15.49, 1.15.50, 1.15.51, 1.15.52, 1.15.53, 1.15.54, 1.15.55, 1.15.56, 1.15.57, 1.15.58, 1.15.59, 1.15.60, 1.15.61, 1.15.62, 1.15.63, 1.15.64, 1.15.65, 1.15.66, 1.15.67, 1.15.68, 1.15.69, 1.15.70, 1.15.71, 1.15.72, 1.15.73, 1.15.74, 1.15.75, 1.15.76, 1.15.77, 1.15.78, 1.15.79, 1.15.80, 1.15.81, 1.15.82, 1.15.83, 1.15.84, 1.15.85, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.16.7, 1.16.8, 1.16.9, 1.16.10, 1.16.11, 1.16.12, 1.16.13, 1.16.14, 1.16.15, 1.16.16, 1.16.17, 1.16.18, 1.16.19, 1.16.20, 1.16.21, 1.16.22, 1.16.23, 1.16.24, 1.16.25, 1.16.26, 1.16.27, 1.16.28, 1.16.29, 1.16.30, 1.16.31, 1.16.32, 1.16.33, 1.16.34, 1.16.35, 1.16.36, 1.16.37, 1.16.38, 1.16.39, 1.16.40, 1.16.41, 1.16.42, 1.16.43, 1.16.44, 1.16.45, 1.16.46, 1.16.47, 1.16.48, 1.16.49, 1.16.50, 1.16.51, 1.16.52, 1.16.53, 1.16.54, 1.16.55, 1.16.56, 1.16.57, 1.16.58, 1.16.59, 1.16.60, 1.16.61, 1.16.62, 1.16.63, 1.16.64, 1.16.65, 1.16.66, 1.16.67, 1.16.68, 1.16.69, 1.16.70, 1.16.71, 1.16.72, 1.16.73, 1.16.74, 1.16.75, 1.16.76, 1.16.77, 1.16.78, 1.16.79, 1.16.80, 1.16.81, 1.16.82, 1.16.83, 1.16.84, 1.16.85, 1.16.86, 1.16.87, 1.16.88, 1.16.89, 1.16.90, 1.16.91, 1.16.92, 1.16.93, 1.16.94, 1.16.95, 1.16.96, 1.16.97, 1.16.98, 1.16.99, 1.16.100, 1.16.101, 1.16.102, 1.16.103, 1.16.104, 1.16.105, 1.16.106, 1.16.107, 1.16.108, 1.16.109, 1.16.110, 1.16.111, 1.16.112, 1.16.113, 1.16.114, 1.16.115, 1.16.116, 1.16.117, 1.16.118, 1.16.119, 1.16.120, 1.16.121, 1.16.122, 1.16.123, 1.16.124, 1.16.125, 1.16.126, 1.16.127, 1.16.128, 1.16.129, 1.16.130, 1.16.131, 1.16.132, 1.16.133, 1.16.134, 1.16.135, 1.16.136, 1.16.137, 1.16.138, 1.16.139, 1.16.140, 1.16.141, 1.16.142, 1.16.143, 1.16.144, 1.16.145, 1.16.146, 1.16.147, 1.16.148, 1.16.149, 1.16.150, 1.16.151, 1.16.152, 1.16.153, 1.16.154, 1.16.155, 1.16.156, 1.16.157, 1.16.158, 1.16.159, 1.16.160, 1.16.161, 1.16.162, 1.16.163, 1.16.164, 1.16.165, 1.16.166, 1.16.167, 1.16.168, 1.16.169, 1.16.170, 1.16.171, 1.16.172, 1.16.173, 1.16.174, 1.16.175, 1.16.176, 1.16.177, 1.16.178, 1.16.179, 1.16.180, 1.16.181, 1.16.182, 1.16.183, 1.16.184, 1.16.185, 1.16.186, 1.16.187, 1.16.188, 1.16.189, 1.16.190, 1.16.191, 1.16.192, 1.16.193, 1.16.194, 1.16.195, 1.16.196, 1.16.197, 1.16.198, 1.16.199, 1.16.200, 1.16.201, 1.16.202, 1.16.203, 1.16.204, 1.16.205, 1.16.206, 1.16.207, 1.16.208, 1.16.209, 1.16.210, 1.16.211, 1.16.212, 1.16.213, 1.16.214, 1.16.215, 1.16.216, 1.16.217, 1.16.218, 1.16.219, 1.16.220, 1.16.221, 1.16.222, 1.16.223, 1.16.224, 1.16.225, 1.16.226, 1.16.227, 1.16.228, 1.16.229, 1.16.230, 1.16.231, 1.16.232, 1.16.233, 1.16.234, 1.16.235, 1.16.236, 1.16.237, 1.16.238, 1.16.239, 1.16.240, 1.16.241, 1.16.242, 1.16.243, 1.16.244, 1.16.245, 1.16.246, 1.16.247, 1.16.248, 1.16.249, 1.16.250, 1.16.251, 1.16.252, 1.16.253, 1.16.254, 1.16.255, 1.16.256, 1.16.257, 1.16.258, 1.16.259, 1.16.260, 1.16.261, 1.16.262, 1.16.263, 1.16.264, 1.16.265, 1.16.266, 1.16.267, 1.16.268, 1.16.269, 1.16.270, 1.16.271, 1.16.272, 1.16.273, 1.16.274, 1.16.275, 1.16.276, 1.16.277, 1.16.278, 1.16.279, 1.16.280, 1.16.281, 1.16.282, 1.16.283, 1.16.284, 1.16.285, 1.16.286, 1.16.287, 1.16.288, 1.16.289, 1.16.290, 1.16.291, 1.16.292, 1.16.293, 1.16.294, 1.16.295, 1.16.296, 1.16.297, 1.16.298, 1.16.299, 1.16.300, 1.16.301, 1.16.302, 1.16.303, 1.16.304, 1.16.305, 1.16.306, 1.16.307, 1.16.308, 1.16.309, 1.16.310, 1.16.311, 1.16.312, 1.16.313, 1.16.314, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.17.6, 1.17.7, 1.17.8, 1.17.9, 1.17.10, 1.17.11, 1.17.12, 1.17.13, 1.17.14, 1.17.15, 1.17.16, 1.17.17, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.18.6, 1.18.7, 1.18.8, 1.18.9, 1.18.10, 1.18.11, 1.18.12, 1.18.13, 1.18.14, 1.18.15, 1.18.16, 1.18.17, 1.18.18, 1.18.19, 1.18.20, 1.18.21, 1.18.22, 1.18.23, 1.18.24, 1.18.25, 1.18.26, 1.18.27, 1.18.28, 1.18.29, 1.18.30, 1.18.31, 1.18.32, 1.18.33, 1.18.34, 1.18.35, 1.18.36, 1.18.37, 1.18.38, 1.18.39, 1.18.40, 1.18.41, 1.18.42, 1.18.43, 1.18.44, 1.18.45, 1.18.46, 1.18.47, 1.18.48, 1.18.49, 1.18.50, 1.18.51, 1.18.52, 1.18.53, 1.18.54, 1.18.55, 1.18.56, 1.18.57, 1.18.58, 1.18.59, 1.18.60, 1.18.61, 1.18.62, 1.18.63, 1.18.64, 1.18.65, 1.18.66, 1.18.67, 1.18.68, 1.18.69, 1.18.70, 1.18.71, 1.18.72, 1.18.73, 1.18.74, 1.18.75, 1.18.76, 1.18.77, 1.18.78, 1.18.79, 1.18.80, 1.18.81, 1.18.82, 1.18.83, 1.18.84, 1.18.85, 1.18.86, 1.18.87, 1.18.88, 1.18.89, 1.18.90, 1.18.91, 1.18.92, 1.18.93, 1.18.94, 1.18.95, 1.18.96, 1.18.97, 1.18.98, 1.18.99, 1.18.100, 1.18.101, 1.18.102, 1.18.103, 1.18.104, 1.18.105, 1.18.106, 1.18.107, 1.18.108, 1.18.109, 1.18.110, 1.18.111, 1.18.112, 1.18.113, 1.18.114, 1.18.115, 1.18.116, 1.18.117, 1.18.118, 1.18.119, 1.18.120, 1.18.121, 1.18.122, 1.18.123, 1.18.124, 1.18.125, 1.18.126, 1.18.127, 1.18.128, 1.18.129, 1.18.130, 1.18.131, 1.18.132, 1.18.133, 1.18.134, 1.18.135, 1.18.136, 1.18.137, 1.18.138, 1.18.139, 1.18.140, 1.18.141, 1.18.142, 1.18.143, 1.18.144, 1.18.145, 1.18.146, 1.18.147, 1.18.148, 1.18.149, 1.18.150, 1.18.151, 1.18.152, 1.18.153, 1.18.154, 1.18.155, 1.18.156, 1.18.157, 1.18.158, 1.18.159, 1.18.160, 1.18.161, 1.18.162, 1.18.163, 1.18.164, 1.18.165, 1.18.166, 1.18.167, 1.18.168, 1.18.169, 1.18.170, 1.18.171, 1.18.172, 1.18.173, 1.18.174, 1.18.175, 1.18.176, 1.18.177, 1.18.178, 1.18.179, 1.18.180, 1.18.181, 1.18.182, 1.18.183, 1.18.184, 1.18.185, 1.18.186, 1.18.187, 1.18.188, 1.18.189, 1.18.190, 1.18.191, 1.18.192, 1.18.193, 1.18.194, 1.18.195, 1.18.196, 1.18.197, 1.18.198, 1.18.199, 1.18.200, 1.18.201, 1.18.202, 1.18.203, 1.18.204, 1.18.205, 1.18.206, 1.18.207, 1.18.208, 1.18.209, 1.18.210, 1.18.211, 1.18.212, 1.18.213, 1.18.214, 1.18.215, 1.18.216, 1.18.217, 1.18.218, 1.18.219, 1.18.220, 1.18.221, 1.18.222, 1.18.223, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.19.6, 1.19.7, 1.19.8, 1.19.9, 1.19.10, 1.19.11, 1.19.12, 1.19.13, 1.19.14, 1.19.15, 1.19.16, 1.19.17, 1.19.18, 1.19.19, 1.19.20, 1.19.21, 1.19.22, 1.19.23, 1.19.24, 1.19.25, 1.19.26, 1.19.27, 1.19.28, 1.19.29, 1.19.30, 1.19.31, 1.19.32, 1.19.33, 1.19.34, 1.19.35, 1.19.36, 1.19.37, 1.19.38, 1.19.39, 1.19.40, 1.19.41, 1.19.42, 1.19.43, 1.19.44, 1.19.45, 1.19.46, 1.19.47, 1.19.48, 1.19.49, 1.19.50, 1.19.51, 1.19.52, 1.19.53, 1.19.54, 1.19.55, 1.19.56, 1.19.57, 1.19.58, 1.19.59, 1.19.60, 1.19.61, 1.19.62, 1.19.63, 1.19.64, 1.19.65, 1.19.66, 1.19.67, 1.19.68, 1.19.69, 1.19.70, 1.19.71, 1.19.72, 1.19.73, 1.19.74, 1.19.75, 1.19.76, 1.19.77, 1.19.78, 1.19.79, 1.19.80, 1.19.81, 1.19.82, 1.19.83, 1.19.84, 1.19.85, 1.19.86, 1.19.87, 1.19.88, 1.19.89, 1.19.90, 1.19.91, 1.19.92, 1.19.93, 1.19.94, 1.19.95, 1.19.96, 1.19.97, 1.19.98, 1.19.99, 1.19.100, 1.19.101, 1.19.102, 1.19.103, 1.19.104, 1.19.105, 1.19.106, 1.19.107, 1.19.108, 1.19.109, 1.19.110, 1.19.111, 1.19.112, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.20.4, 1.20.5, 1.20.6, 1.20.7, 1.20.8, 1.20.9, 1.20.10, 1.20.11, 1.20.12, 1.20.13, 1.20.14, 1.20.15, 1.20.16, 1.20.17, 1.20.18, 1.20.19, 1.20.20, 1.20.21, 1.20.22, 1.20.23, 1.20.24, 1.20.25, 1.20.26, 1.20.27, 1.20.28, 1.20.29, 1.20.30, 1.20.31, 1.20.32, 1.20.33, 1.20.34, 1.20.35, 1.20.36, 1.20.37, 1.20.38, 1.20.39, 1.20.40, 1.20.41, 1.20.42, 1.20.43, 1.20.44, 1.20.45, 1.20.46, 1.20.47, 1.20.48, 1.20.49, 1.20.50, 1.20.51, 1.20.52, 1.20.53, 1.20.54, 1.20.55, 1.20.56, 1.20.57, 1.20.58, 1.20.59, 1.20.60, 1.20.61, 1.20.62, 1.20.63, 1.20.64, 1.20.65, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.21.7, 1.21.8, 1.21.9, 1.21.10, 1.21.11, 1.21.12, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.22.5, 1.22.6, 1.22.7, 1.22.8, 1.22.9, 1.22.10, 1.22.11, 1.22.12, 1.22.13, 1.22.14, 1.22.15, 1.22.16, 1.22.17, 1.22.18, 1.22.19, 1.22.20, 1.22.21, 1.22.22, 1.22.23, 1.22.24, 1.22.25, 1.22.26, 1.22.27, 1.22.28, 1.22.29, 1.22.30, 1.22.31, 1.22.32, 1.22.33, 1.22.34, 1.22.35, 1.22.36, 1.22.37, 1.22.38, 1.22.39, 1.22.40, 1.22.41, 1.22.42, 1.22.43, 1.22.44, 1.22.45, 1.22.46, 1.22.47, 1.22.48, 1.22.49, 1.22.50, 1.22.51, 1.22.52, 1.22.53, 1.22.54, 1.22.55, 1.22.56, 1.22.57, 1.22.58, 1.22.59, 1.22.60, 1.22.61, 1.22.62, 1.22.63, 1.22.64, 1.22.65, 1.22.66, 1.22.67, 1.22.68, 1.22.69, 1.22.70, 1.22.71, 1.22.72, 1.22.73, 1.22.74, 1.22.75, 1.22.76, 1.22.77, 1.22.78, 1.22.79, 1.22.80, 1.22.81, 1.22.82, 1.22.83, 1.22.84, 1.22.85, 1.22.86, 1.22.87, 1.22.88, 1.22.89, 1.22.90, 1.22.91, 1.22.92, 1.22.93, 1.22.94, 1.22.95, 1.22.96, 1.22.97, 1.22.98, 1.22.99, 1.22.100, 1.22.101, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.23.6, 1.23.7, 1.23.8, 1.23.9, 1.23.10, 1.23.11, 1.23.12, 1.23.13, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.24.5, 1.24.6, 1.24.7, 1.24.8, 1.24.9, 1.24.10, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.25.5, 1.25.6, 1.25.7, 1.25.8, 1.25.9, 1.25.10, 1.25.11, 1.25.12, 1.25.13, 1.25.14, 1.25.15, 1.25.16, 1.25.17, 1.25.18, 1.25.19, 1.25.20, 1.25.21, 1.25.22, 1.25.23, 1.25.24, 1.25.25, 1.25.26, 1.25.27, 1.25.28, 1.25.29, 1.25.30, 1.25.31, 1.25.32, 1.25.33, 1.25.34, 1.25.35, 1.25.36)
ERROR: No matching distribution found for awscli==1.25.84

**Comment by ZeroAurora** [comment]
遇见相同问题，OpenTuna 中包版本严重落后于 PyPI 上游和清华域名镜像

**Comment by ZenithalHourlyRate** [comment]
未同步原因与 #1538 相同，正在修复中

**Comment by jiegec** [comment]
已解决。
