### ISSUE TITLE
conda 更新时，报 channel 地址请求异常

### ISSUE THREAD

**Issue by ThunderboltLei** [tuna/issues#1622]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/developments/anaconda/anaconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/opt/developments/anaconda/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/current_repodata.json
    
    During handling of the above exception, another exception occurred:

### 期望的现象（What you expected to happen）

http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/current_repodata.json 或 http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch/current_repodata.json
应该保证可以访问到文件

### 如何重现此问题（How to reproduce it）

1、conda 更新
2、condarc 使用清华源

### 操作系统（OS Version）

mac

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1518#issuecomment-1234060346

您使用的配置可能是过时配置，请认准帮助文档中的最新配置。
