### ISSUE TITLE
【解析出来的ip地址ping不通】

### ISSUE THREAD

**Issue by MacroMoon** [tuna/issues#1623]
我们在使用你们源的时候，会解析出一些其他地址，但是这些地址并ping不通，不知道是啥情况哎，不通信的地址有：101.6.8.193，
麻烦帮忙看看是什么情况？

**Comment by ZenithalHourlyRate** [comment]
> 101.6.8.193

这是我们的旧地址，被 cdnmirrors.tuna.tsinghua.edu.cn 指向

主域名 mirrors.tuna.tsinghua.edu.cn 在**去年八月**之前是 CNAME 到 cdnmirrors 的，在那之后我们做了架构升级，CNAME 到了 bfdmirrors，参考 https://mirrors.tuna.tsinghua.edu.cn/news/huawei-sponsorship/

有可能您的机器上 mirrors.tuna.tsinghua.edu.cn 的 CNAME 解析未更新，或者您直接使用了 cdnmirrors

**Comment by James4Ever0** [comment]
解析出来的还有`101.6.15.130` 虽然可以ping通 但是浏览器访问不了

**Comment by ZenithalHourlyRate** [comment]
> 报502错误 即使是重新插拔 换了IP照样不行 换设备也不行

502 错误一般会由贵方本地的代理或网关返回，我们的服务目前正常运行，不返回 502

**Comment by James4Ever0** [comment]
有没有什么好的免费国内代理池可以推荐一下吗 好多项目都要用国内镜像源 QAQ

**Comment by James4Ever0** [comment]
111.18.***.***

**Comment by ZenithalHourlyRate** [comment]
> 111.18.0.0/16

关于这个 IP 段可以参考 
https://github.com/tuna/issues/issues/1625#issuecomment-1336220953

**Comment by James4Ever0** [comment]
暂时只能代理了QAQ
