### ISSUE TITLE
Conda更新所有包发现缺失

### ISSUE THREAD

**Issue by mengyingsui** [tuna/issues#1624]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

> conda update --all -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xz-5.2.8                   |       h8cc25b3_0         205 KB  defaults
    ------------------------------------------------------------
                                           Total:         205 KB

The following NEW packages will be INSTALLED:

  flit-core          anaconda/pkgs/main/noarch::flit-core-3.6.0-pyhd3eb1b0_0 None
  pluggy             anaconda/pkgs/main/win-64::pluggy-1.0.0-py39haa95532_1 None
  ruamel.yaml        anaconda/pkgs/main/win-64::ruamel.yaml-0.16.12-py39h2bbff1b_3 None
  ruamel.yaml.clib   anaconda/pkgs/main/win-64::ruamel.yaml.clib-0.2.6-py39h2bbff1b_1 None

The following packages will be REMOVED:

  ruamel_yaml-0.15.100-py39h2bbff1b_0
  yaml-0.2.5-he774522_0

The following packages will be UPDATED:

  conda                               22.9.0-py39haa95532_0 --> 22.11.0-py39haa95532_1 None
  pywin32                                302-py39h2bbff1b_2 --> 305-py39h2bbff1b_0 None
  typing-extensions                    4.3.0-py39haa95532_0 --> 4.4.0-py39haa95532_0 None
  typing_extensions                    4.3.0-py39haa95532_0 --> 4.4.0-py39haa95532_0 None
  xz                                       5.2.6-h8cc25b3_0 --> 5.2.8-h8cc25b3_0 None

Downloading and Extracting Packages
xz-5.2.8             | 205 KB    |                                                                              |   0%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/xz-5.2.8-h8cc25b3_0.conda>
Elapsed: 00:00.415029

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

### 期望的现象（What you expected to happen）

conda update --all -y更新成功

### 如何重现此问题（How to reproduce it）

conda install xz=5.2.8 -y

### 操作系统（OS Version）

Windows11

**Comment by MUTED64** [comment]
遇到相同问题。
在此issue发布两小时后的最近一次同步中仍然缺失xz-5.2.8，可能还存在其它包的缺失。

**Comment by ZenithalHourlyRate** [comment]
现已同步成功，可以正常使用
