### ISSUE TITLE
无法连接到TUNA服务器

### ISSUE THREAD

**Issue by CoiaPrant233** [tuna/issues#1625]
解析地址 101.6.15.130
客户端IP地址 111.18.93.130 （中国移动）
Ping: 正常
浏览器以及APT报错 connection refused

**Comment by ZenithalHourlyRate** [comment]
我们在 12 月 2 日时收到了来自 111.18.0.0/15, 111.20.0.0/16 与相应 IPv6 的下载 20Gbps，上传 10Gbps 的异常请求流量，故而拒绝了相应 IP 段的连接

**Comment by CoiaPrant233** [comment]
请问何时能恢复，能否降低限制，这个CIDR一般被用作家用宽带NAT网络出口

**Comment by shankerwangmiao** [comment]
由于此次攻击流量巨大，IP 地址众多，遍布上述地址段，因此无法解除封禁。

**Comment by CoiaPrant233** [comment]
请问封禁持续多久

**Comment by shankerwangmiao** [comment]
直到监测不到流量后为止。

**Comment by CoiaPrant233** [comment]
好的
