### ISSUE TITLE
[BFSU] Kali apt update 报错

### ISSUE THREAD

**Issue by SherkeyXD** [tuna/issues#1626]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

> sudo apt update
Get:1 https://mirrors.bfsu.edu.cn/kali kali-rolling InRelease [30.6 kB]
Get:2 https://mirrors.bfsu.edu.cn/kali kali-rolling/main amd64 Packages [18.8 MB]
Get:3 https://mirrors.bfsu.edu.cn/kali kali-rolling/main amd64 Contents (deb) [43.3 MB]
Fetched 62.1 MB in 9s (7,078 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
89 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'non-free-contrib/binary-amd64/Packages' as repository 'https://mirrors.bfsu.edu.cn/kali kali-rolling InRelease' doesn't have the component 'non-free-contrib' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'non-free-contrib/i18n/Translation-en_US' as repository 'https://mirrors.bfsu.edu.cn/kali kali-rolling InRelease' doesn't have the component 'non-free-contrib' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'non-free-contrib/i18n/Translation-en' as repository 'https://mirrors.bfsu.edu.cn/kali kali-rolling InRelease' doesn't have the component 'non-free-contrib' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'non-free-contrib/Contents-amd64' as repository 'https://mirrors.bfsu.edu.cn/kali kali-rolling InRelease' doesn't have the component 'non-free-contrib' (component misspelt in sources.list?)

### 期望的现象（What you expected to happen）

正常更新包信息

### 如何重现此问题（How to reproduce it）

sudo apt update

### 操作系统（OS Version）

Kali 2022.03

**Comment by ZenithalHourlyRate** [comment]
您可以将 `/etc/apt/sources.list` 中的

```
deb https://mirrors.bfsu.edu.cn/kali kali-rolling main non-free-contrib
```

改为

```
deb https://mirrors.bfsu.edu.cn/kali kali-rolling main non-free contrib
```

**Comment by ZenithalHourlyRate** [comment]
现已在帮助文档中修复

https://github.com/tuna/mirror-web/commit/056d9d170e171c34c504a3c10fef92fa4c2d3b2e
