### ISSUE TITLE
exim-4.96-3.el8.x86_64.rpm

### ISSUE THREAD

**Issue by pengyiheng** [tuna/issues#1627]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Cockpit 更新

### 上游地址与镜像方法 (How to mirror)

https://mirrors.tuna.tsinghua.edu.cn/epel/8/Everything/x86_64/Packages/e/exim-4.96-3.el8.x86_64.rpm

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
镜像站上有 exim-4.96-5.el8.x86_64.rpm，您可能需要 yum upate 后再安装相应软件包
