### ISSUE TITLE
网站突然无法访问

### ISSUE THREAD

**Issue by WenChao1Hou** [tuna/issues#1628]
一直在使用该镜像，前天突然就无法访问。
错误信息如截图
<img width="643" alt="Snipaste_2022-12-07_20-40-34" src="https://user-images.githubusercontent.com/116722017/206182054-d62b00e7-1e43-4def-945f-9a20b6fd79a0.png">
<img width="1406" alt="Snipaste_2022-12-07_20-41-16" src="https://user-images.githubusercontent.com/116722017/206182053-ecbf8073-5fc7-47d5-b788-6ba6bde8ef76.png">
是被增加到了异常访问名单中吗

**Comment by ZenithalHourlyRate** [comment]
参考 https://github.com/tuna/issues/issues/1625#issuecomment-1336220953
