### ISSUE TITLE
路径与BiocManager::install不匹配

### ISSUE THREAD

**Issue by LiCanhui-Huyi** [tuna/issues#1629]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我的R版本的4.1.3,对应bioconductor在4.1最新的版本是3.14.当我用chooseBioCmirror()选择了清华源之后,尝试用BiocManager::install("msa"),出现了错误
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/bioc/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/data/annotation/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/data/experiment/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/workflows/src/contrib:
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/workflows/src/contrib/PACKAGES'
这错误似乎是找不到包的索引,我尝试用浏览器打开上面的链接,返回404. 我发现你们的包索引的链接似乎是https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.14/bioc/manuals/ 
事实上,不管我选择哪一个源,BiocManager::install都会在源网址加上/packages/3.14/bioc/src/contrib 等链接以寻找包索引

### 期望的现象（What you expected to happen）

我应该怎么样设置才能使得在使用BiocManager::install时,使其能够到正确的链接安装包

### 如何重现此问题（How to reproduce it）

.

### 操作系统（OS Version）

在Windows10 和 linux(CentOS7)上都遇到了这样的问题

### 其他需要说明的事项（Anything else we need to know）

这是一个新的电脑,刚安装R语言环境不久,不知道是不是缺少了什么设置才导致此错误.我在自己个人常用的电脑上并不会遇到此错误

**Comment by ZenithalHourlyRate** [comment]
bioconductor 上游最近删除了旧版本的包，镜像站上不存在 3.14 版本了

**Comment by gjzhuang** [comment]
https://new.bioconductor.org/about/mirrors/

你可以是试试将这个镜像改成西湖大学的
options(BioC_mirror="https://mirrors.westlake.edu.cn/bioconductor")
然后使用BiocManager::install()你想安装的包。

或者用清华的镜像，但是得安装最新的R和BiocManager::install

**Comment by erlun1** [comment]
给我感觉是,清华源只有最新的BiocManager才能挂,比如我现在挂3.19就没办法用(现在发布版是3.20),至于bioconductor给的其他源,有一些都不怎么维护了,只有西湖大学还可以用

**Comment by shankerwangmiao** [comment]
> 给我感觉是,清华源只有最新的BiocManager才能挂,比如我现在挂3.19就没办法用(现在发布版是3.20),至于bioconductor给的其他源,有一些都不怎么维护了,只有西湖大学还可以用

这是因为 bioconductor 官方会定期将较旧的发行版本从镜像移入至归档中，因此这部分数据就会被相应从镜像站上移除。最近一次是在 11  月 13 日，移除了 3.19。

**Comment by lishengting** [comment]
> https://new.bioconductor.org/about/mirrors/
> 
> 你可以是试试将这个镜像改成西湖大学的 options(BioC_mirror="https://mirrors.westlake.edu.cn/bioconductor") 然后使用BiocManager::install()你想安装的包。
> 
> 或者用清华的镜像，但是得安装最新的R和BiocManager::install

还是西湖大学靠谱，清华不咋地
