### ISSUE TITLE
openwrt镜像404

### ISSUE THREAD

**Issue by wehooshen** [tuna/issues#1630]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

所有地址都404了

### 期望的现象（What you expected to happen）

all

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/

**Comment by taoky** [comment]
#1618
