### ISSUE TITLE
清华源pypi日志下载量疑问

### ISSUE THREAD

**Issue by lelelelelez** [tuna/issues#1631]
请问清华源关于某个包的下载信息是否会被记录到Pypi中？
也就是说，我通过bigquery请求到的下载量是否包含清华源的下载量？
还是说只有清华源仓库定期与pypi同步时，这部分的下载量才会被记录到Pypi中？

请求解答。

**Comment by Harry-Chen** [comment]
PyPI 没有途径从下游镜像站收集下载量信息，因此也不可能包含 TUNA 的下载量数据。

如果您需要 TUNA 的数据，请自行由我们公布的日志中分析，详情请查阅 <https://mirrors.tuna.tsinghua.edu.cn/news/release-logs/>
