### ISSUE TITLE
[镜像请求] pypi源镜像请求

### ISSUE THREAD

**Issue by chenjiuhai** [tuna/issues#1632]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

上海清华国际创新中心集成电路研究平台信息技术中心申请镜像pypi源用于内部网络加速。

### 上游地址与镜像方法 (How to mirror)

https://pypi.python.org/
目前使用以上地址同步，速度较慢。

### 镜像大小 (Mirror size)

14TB

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您好，该模板用于向 TUNA 本身提出镜像请求。如果您需要从 TUNA 同步相关内容，您可以通过 support@tuna.tsinghua.edu.cn 联系我们。

同步 pypi 可以使用 bandersnatch，在 download-mirror 中指向 TUNA。这可以参考样例脚本 https://github.com/tuna/tunasync-scripts/blob/cae1194534d6cce0ddea031a2bf318b9aa0261a3/pypi.sh#L17

我们建议您通过 IPv6 同步，目前 TUNA 的 IPv4 带宽占用率较高。
