### ISSUE TITLE
Anaconda源更新current_repodata.json跳转的问题

### ISSUE THREAD

**Issue by williamyizhu** [tuna/issues#1633]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照以下流程设置了源
https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/

安装Anaconda Package的时候，需要下载
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json

但是直接转发到了
https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json

内网环境下防火墙只放开了 mirrors.tuna.tsinghua.edu.cn，因此安装失败

### 期望的现象（What you expected to happen）

访问【https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json】不跳转

### 如何重现此问题（How to reproduce it）

浏览器中输入
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json

直接跳转到
https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json

### 操作系统（OS Version）

Debian 11

**Comment by ZenithalHourlyRate** [comment]
根据之前的统计，anaconda 流量是 TUNA 流量大头（30%），而 TUNA IPv4 带宽日常占用较高，单个用户体验不佳，为此我们最近做出了架构调整，将非校内 IPv4 对 anaconda 的请求全部重定向到了 bfsu

**Comment by williamyizhu** [comment]
请问是否会经常跳转，或者跳转至其他的地址？因为我们企业安全要求较高，开一个防火墙例外很不容易。谢谢。

**Comment by ZenithalHourlyRate** [comment]
> 请问是否会经常跳转，或者跳转至其他的地址？

不会跳转到其他的地址；如果您的出口地址段固定，我们也可以将该地址段转为 TUNA 本身提供服务。

**Comment by TDIT-haha** [comment]
> > 请问是否会经常跳转，或者跳转至其他的地址？
> 
> 不会跳转到其他的地址；如果您的出口地址段固定，我们也可以将该地址段转为 TUNA 本身提供服务。

我有个疑问，由于将非校内 IPv4 的anaconda 的请求全部重定向到了 bfsu，在企业中使用bfsu会存在版权问题之类的么？

**Comment by ZenithalHourlyRate** [comment]
> 我有个疑问，由于将非校内 IPv4 的anaconda 的请求全部重定向到了 bfsu，在企业中使用bfsu会存在版权问题之类的么？

关于版权问题，BFSU 镜像站也由我们维护，因此并不存在额外的版权问题。Anaconda 公司已经授权境内的高校镜像站向不特定用户原样再分发 Anaconda 的软件包。但是，您使用 Anaconda
软件时，仍然需要遵守其原始许可。
