### ISSUE TITLE
raspberry-pi-os-images 文件夹过时

### ISSUE THREAD

**Issue by stl0755** [tuna/issues#1634]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

raspbian
raspbian_full
raspbian_lite
raspbmc
raspios_arm64
raspios_armhf
raspios_full_arm64
raspios_full_armhf
raspios_lite_arm64
raspios_lite_armhf
raspios_oldstable_armhf
raspios_oldstable_lite_armhf
以上文件夹没有同步到最新
以及
eeprom_recovery.json operating-systems-categories.json os_list.json os_list_imagingutility.json os_list_imagingutility_v2.json os_list_imagingutility_v3.json os_list_v2.json os_list_v3.json piserver.json rss.xml wp-slice-noobs wp-slice-noobs-lite wp-slice-other wp-slice-raspbian
以上文件不是最新的

### 期望的现象（What you expected to happen）

与上游同步

### 如何重现此问题（How to reproduce it）

wget 下载相关的os.json 并比较
如
https://mirrors.tuna.tsinghua.edu.cn/raspberry-pi-os-images/raspios_arm64/os.json

**Comment by ZenithalHourlyRate** [comment]
现已更新。
