### ISSUE TITLE
[镜像请求] termux-pacman

### ISSUE THREAD

**Issue by Freed-Wu** [tuna/issues#1635]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Support for pacman packages in termux

tuna has owned a mirror of termux. May be termux-pacman can also be supported? TIA!

### 上游地址与镜像方法 (How to mirror)

https://termux-pacman.github.io/

### 备注 (Note)

In <https://github.com/ustclug/mirrorrequest/issues/348>, the maintainer of termux-pacman said:

> Even though the pacman service and apt have the same content, it is a bit wrong to think that the pacman service is a duplicate (there are 3 main reasons).
>
>     The pacman service has termux packages in the pacman format (which is obvious and logical), but the addition of these packages is done from scratch, that is, these packages are completely compiled in the forked termux-packages repository.
>     The pacman service has its own signature for packages and for files that work with pacman (these are db and files). Signature link.
>     In the pacman service, in addition to the usual repositories from Termux (main, x11 and root), there are also repositories from TUR (Termux User Repository). These are tur and tur-continuous.
>
> Hope this answers your question. And since I manage pacman services, I wanted to know more about your mirror service.

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by mingfengpigeon** [comment]
I need it too. Thanks.

**Comment by Freed-Wu** [comment]
@Maxython

**Comment by Harry-Chen** [comment]
与 https://github.com/ustclug/mirrorrequest/issues/348 相同理由不予接受。
