### ISSUE TITLE
你好，咨询一下anaconda相关

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1636]
你好，

看之前的文章：https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/
anaconda好像说停止更新了，但是看现在好像已经重新开始同步了，所以想咨询一下，是后来解决授权问题了吗？
我司这边是想参考一下，能否帮看下，这个授权的流程是怎么获取的呢？

**Comment by ZenithalHourlyRate** [comment]
您可以参考
https://mirrors.tuna.tsinghua.edu.cn/news/anaconda-restored/
