### ISSUE TITLE
Grafana 9.3后官方RPM仓库地址更换，镜像软件包陈旧

### ISSUE THREAD

**Issue by Vonng** [tuna/issues#1637]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Grafana 镜像， RedHat / CentOS 系统

Grafana 官方Yum Repo发生变化， Grafana 9.3 后使用了的新的仓库地址。
而清华镜像一直停留在 9.2.x 版本：

https://mirrors.tuna.tsinghua.edu.cn/grafana/yum/rpm/

镜像中最新版本为：9.2.3，官方最新版本已经为 9.3.2 

### 期望的现象（What you expected to happen）

跟进新的Grafana RPM镜像

https://rpm.grafana.com

### 如何重现此问题（How to reproduce it）

访问链接即可。

### 操作系统（OS Version）

EL 7,8,9

### 浏览器（如果适用）（Browser version, if applicable）

N/A

### 其他环境（Other environments）

N/A

### 其他需要说明的事项（Anything else we need to know）

N/A

**Comment by ZenithalHourlyRate** [comment]
上游更换了目录结构，现已修复。

https://mirrors.tuna.tsinghua.edu.cn/grafana/yum/rpm/Packages/grafana-9.3.2-1.x86_64.rpm
