### ISSUE TITLE
github-release/balena-io/etcher未成功镜像

### ISSUE THREAD

**Issue by waytoarcher** [tuna/issues#1638]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/github-release/balena-io/etcher/LatestRelease

404 NOT FOUND
呜喵，金枪鱼被吃掉了

### 期望的现象（What you expected to happen）

成功同步

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/github-release/balena-io/etcher/LatestRelease

**Comment by ZenithalHourlyRate** [comment]
现已修复
