### ISSUE TITLE
本地搭建mirror使用github-release.py镜像部分项目时，如何禁止在index页面显示子项目

### ISSUE THREAD

**Issue by waytoarcher** [tuna/issues#1639]
默认的github-release.py里面已经设定了某些github项目，
本地做mirror时仅想对个别项目或自定义项目进行镜像，
在github-release.py里面删除了部分项目，比如cmder，
但是执行同步时依然会在主页显示cmder的链接，
请问：如何禁止在主页显示子项目？

**Comment by ZenithalHourlyRate** [comment]
这与 mirror-web 有关，您可以更改这一部分 https://github.com/tuna/mirror-web/blob/89da8ee010e2ba868ce953bac117c3dfbb736d56/_data/options.yml#L454

**Comment by waytoarcher** [comment]
> 这与 mirror-web 有关，您可以更改这一部分 https://github.com/tuna/mirror-web/blob/89da8ee010e2ba868ce953bac117c3dfbb736d56/_data/options.yml#L454

谢谢，修改后生成站点，解决了。
