### ISSUE TITLE
无法使用Homebrew安装pstree

### ISSUE THREAD

**Issue by MikuAndRabbit** [tuna/issues#1640]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用命令`brew install pstree`时发现无法从镜像站安装`pstree`，具体的错误信息如下所示：
```
Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/pstree-2.3
curl: (22) The requested URL returned error: 404

Warning: Bottle missing, falling back to the default domain...
```

### 期望的现象（What you expected to happen）

能够从镜像站下载

### 如何重现此问题（How to reproduce it）

使用`brew install pstree`命令

### 操作系统（OS Version）

MacOS 12.6

### 其他环境（Other environments）

Homebrew 3.5.10

### 其他需要说明的事项（Anything else we need to know）

麻烦各位开发者抽空排查一下这个问题，谢谢你们。祝你们新年快乐！

**Comment by ZenithalHourlyRate** [comment]
您可以在尝试 brew update 后再次安装

镜像站上有 `pstree-2.40`

**Comment by MikuAndRabbit** [comment]
> 您可以在尝试 brew update 后再次安装
> 
> 镜像站上有 `pstree-2.40`

刚才根据您的建议升级了Homebrew，目前已经成功安装 `pstree-2.40` 了。感谢您的帮助。
