### ISSUE TITLE
mysql源安装包更新问题

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1642]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

官方安装包已经更新到了8.0.31
![企业微信截图_16729845738149](https://user-images.githubusercontent.com/5635923/210940060-e72c6497-6999-4c1c-acd4-f803e79c2234.png)

但这里还是mysql-installer-community-8.0.29.0.msi
https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQLInstaller/

排查了一下tuna的脚本，应该是这个地方
 12 MYSQL_RSYNC_UPSTREAM="${DOWNLOADS_RSYNC_UPSTREAM:-rsync://ftp5.gwdg.de/pub/linux/mysql/Downloads/}"
由于上游源未更新导致了后续的问题

### 期望的现象（What you expected to happen）

这里是否应该更换一个及时更新的上游源以修复问题呢？

### 如何重现此问题（How to reproduce it）

curl https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQLInstaller/

**Comment by ZenithalHourlyRate** [comment]
您可以参考 https://github.com/tuna/issues/issues/1555#issuecomment-1236353936
