### ISSUE TITLE
pypi镜像lbg包不同步

### ISSUE THREAD

**Issue by KZHIWEI** [tuna/issues#1643]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://pypi.org/project/lbg/
这个包好像不同步了，可以帮忙看一下吗
最新版本：1.2.13
tuna最新版本: 1.2.12

十分感谢！

### 期望的现象（What you expected to happen）

pypi lbg
同步最新版本

### 如何重现此问题（How to reproduce it）

https://pypi.tuna.tsinghua.edu.cn/simple/lbg/

https://pypi.org/simple/lbg/
对比两个最新版本

**Comment by ZenithalHourlyRate** [comment]
pypi 上游正在故障（其他包的错误影响到整个同步），现已手动同步该包

```
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://pypi.org//pypi/cybrid-api-bank-python/json')
```
