### ISSUE TITLE
Debian 源无法访问

### ISSUE THREAD

**Issue by ericbrownrenzan** [tuna/issues#1644]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

# root @ 54519d143f8e in ~ [9:15:48] 
$ apt-get update
Err:1 https://mirrors.tuna.tsinghua.edu.cn/debian buster InRelease
  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
Err:2 https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates InRelease
  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
Err:3 https://mirrors.tuna.tsinghua.edu.cn/debian buster-updates InRelease
  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
Reading package lists... Done
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/dists/buster/InRelease  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/debian/dists/buster-updates/InRelease  Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'
W: Some index files failed to download. They have been ignored, or old ones used instead.

### 期望的现象（What you expected to happen）

正常更新包内容

### 如何重现此问题（How to reproduce it）

更改Debian源为tuna源，终端中执行sudo apt-get update

### 操作系统（OS Version）

debian 10.13

**Comment by ZenithalHourlyRate** [comment]
> Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'

您好，请您检查您的 DNS 设置。
