### ISSUE TITLE
llvm-apt Sources 404

### ISSUE THREAD

**Issue by c8ef** [tuna/issues#1648]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

`sudo apt update`
Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-bullseye/main/source/Sources  404  Not Found

### 期望的现象（What you expected to happen）

正常更新.

### 如何重现此问题（How to reproduce it）

wget https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh all -m https://mirrors.tuna.tsinghua.edu.cn/llvm-apt

### 操作系统（OS Version）

debian 11

**Comment by ZenithalHourlyRate** [comment]
> sudo ./llvm.sh all -m https://mirrors.tuna.tsinghua.edu.cn/llvm-apt
> Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-bullseye/main/source/Sources 404 Not Found

可以附上脚本执行的 log 吗，按照脚本，不应该同时检测到 jammy 与 bullseye，除非系统配置有问题

您是否有手动更改过 `/etc/apt/sources.list.d/llvm-apt.list`? 我在全新的 debian:bullseye docker 镜像上执行上述脚本时能正常工作

```
add-apt-repository 'deb https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/bullseye/  llvm-toolchain-bullseye-15 main'
```

**Comment by c8ef** [comment]
感谢！问题解决了。
