### ISSUE TITLE
tunasync同步出错

### ISSUE THREAD

**Issue by waterloo3122** [tuna/issues#1649]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

同步的仓库如下：
[[mirrors]]
name = "centos"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/"
use_ipv6 = false

[[mirrors]]
name = "epel"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/epel/"
use_ipv6 = false

[[mirrors]]
name = "docker-ce"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/docker-ce/"
use_ipv6 = false

[[mirrors]]
name = "remi"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/remi/"
use_ipv6 = false

[[mirrors]]
name = "ubuntu"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/ubuntu/"
use_ipv6 = false

[[mirrors]]
name = "proxmox"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/proxmox/"
use_ipv6 = false

[[mirrors]]
name = "ius"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/ius/"
use_ipv6 = false

[[mirrors]]
name = "elrepo"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/elrepo/"
use_ipv6 = false

[[mirrors]]
name = "elasticstack"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/elasticstack/"
use_ipv6 = false

[[mirrors]]
name = "debian"
provider = "rsync"
upstream = "rsync://unicom.mirrors.ustc.edu.cn/debian/"
use_ipv6 = false

[[mirrors]]
name = "debian-security"
provider = "rsync"
upstream = "rsync://unicom.mirrors.ustc.edu.cn/debian-security/"
use_ipv6 = false

报错如下：
23-01-18 12:55:03][NOTICE] retry syncing: remi, retry: 1
[23-01-18 12:55:04][WARNIN] failed syncing remi: exit status 5
[23-01-18 12:55:04][NOTICE] Next scheduled time for remi: 2023-01-18 12:56:04
[23-01-18 12:55:08][NOTICE] start syncing: elasticstack
[23-01-18 12:55:08][WARNIN] failed syncing elasticstack: exit status 5
[23-01-18 12:55:08][NOTICE] retry syncing: elasticstack, retry: 1
[23-01-18 12:55:08][WARNIN] failed syncing elasticstack: exit status 5
[23-01-18 12:55:08][NOTICE] Next scheduled time for elasticstack: 2023-01-18 12:56:08
[23-01-18 12:55:13][NOTICE] start syncing: ius
[23-01-18 12:55:13][WARNIN] failed syncing ius: exit status 12
[23-01-18 12:55:13][NOTICE] retry syncing: ius, retry: 1
[23-01-18 12:55:13][WARNIN] failed syncing ius: exit status 5

我同步的仓库比较多，家里的服务器没有公网ip，是不是把我加入黑名单了？

### 期望的现象（What you expected to happen）

同步成功

### 如何重现此问题（How to reproduce it）

日志一直报错

### 操作系统（OS Version）

debian 11

**Comment by waterloo3122** [comment]
麻烦帮忙看一下什么问题

**Comment by waterloo3122** [comment]
北京联通的网络，路由器上没有公网ip，出口的公网ip目前为114.248.124.56

**Comment by waterloo3122** [comment]
公司的带宽不够，同步太慢，打算在家里同步好后，机器拿到公司进行增量同步

**Comment by ZenithalHourlyRate** [comment]
> 我同步的仓库比较多，家里的服务器没有公网ip，是不是把我加入黑名单了？

是的，我们注意到您的同步频率较高，为服务器存储 IO 带来较大的影响

![Screenshot2023-01-18-13:21:32](https://user-images.githubusercontent.com/19512674/213090814-cdbcebd7-6a31-4df3-aef3-643d0ad3a12f.png)

您可以尝试调整同步频率，从现有的一分钟内一次变为十二个小时一次。我们判断的指标一般为一天总同步次数不超过500次。

**Comment by waterloo3122** [comment]
好的 已经修改 下次同步时间为凌晨1点半左右

**Comment by waterloo3122** [comment]
不好意思 全部采用了tunasync教程中的默认设置 建议在tunasync的帮助文件中修改一下默认internal 为12小时

**Comment by ZenithalHourlyRate** [comment]
现已可正常同步
