### ISSUE TITLE
centos镜像的package展示界面卡死

### ISSUE THREAD

**Issue by zhouyk-library** [tuna/issues#1654]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

centos镜像的package展示界面卡死，且只能展示一小部分包，不能找到需要的软件

页面地址：https://mirrors.tuna.tsinghua.edu.cn/centos/7/os/x86_64/Packages/

### 期望的现象（What you expected to happen）

完整的展示Packages以寻找软件进行下载

### 如何重现此问题（How to reproduce it）

进页面就会出现
页面地址：https://mirrors.tuna.tsinghua.edu.cn/centos/7/os/x86_64/Packages/

### 操作系统（OS Version）

win10

### 浏览器（如果适用）（Browser version, if applicable）

edge

### 其他环境（Other environments）

无

**Comment by ZenithalHourlyRate** [comment]
由于文件较多，nginx 渲染能力有限。一般来说，我们会阻止这类目录的渲染。

> 完整的展示Packages以寻找软件进行下载

您可以尝试通过 yum 等工具搜索，而不是通过网页端搜索。

**Comment by zhouyk-library** [comment]
edge 有问题，Google Chrome 显示正确

**Comment by zhouyk-library** [comment]
> 由于文件较多，nginx 渲染能力有限。一般来说，我们会阻止这类目录的渲染。
> 
> > 完整的展示Packages以寻找软件进行下载
> 
> 您可以尝试通过 yum 等工具搜索，而不是通过网页端搜索。

鉴于服务器环境不能连外网，只能离线安装依赖软件，所以会在网页端查找下载

**Comment by ZenithalHourlyRate** [comment]
> 由于文件较多，浏览器渲染能力有限。一般来说，我们会阻止这类目录的渲染。
> 
> > 完整的展示Packages以寻找软件进行下载
> 
> 您可以尝试通过 yum 等工具搜索，而不是通过网页端搜索。

**Comment by jiegec** [comment]
可以用 pkgs.org：https://centos.pkgs.org/7/centos-x86_64/lsof-4.87-6.el7.x86_64.rpm.html
