### ISSUE TITLE
关于MongoDB镜像的故障报告

### ISSUE THREAD

**Issue by gamaBHC** [tuna/issues#1655]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照官网的说明在Fedora37Server中配置了MongoDB镜像，下载元数据失败

‘’‘
[root@fedora yum.repos.d]# cat mongodb.repo 
[mongodb-org]
name=MongoDB Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el$releasever/
gpgcheck=0
enabled=1
[root@fedora yum.repos.d]# yum makecache 
Fedora 37 - x86_64                                                                                   22 kB/s | 6.1 kB     00:00    
Fedora Modular 37 - x86_64                                                                           12 kB/s | 6.5 kB     00:00    
Fedora 37 - x86_64 - Updates                                                                         11 kB/s | 8.1 kB     00:00    
Fedora Modular 37 - x86_64 - Updates                                                                2.1 kB/s | 4.9 kB     00:02    
MongoDB Repository                                                                                  175  B/s | 153  B     00:00    
Errors during downloading metadata for repository 'mongodb-org':
  - Status code: 404 for https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el37/repodata/repomd.xml (IP: 101.6.15.130)
Error: 为仓库 'mongodb-org' 下载元数据失败 : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
PostgreSQL common RPMs for Fedora 37 - x86_64                                                        73  B/s | 195  B     00:02    
PostgreSQL 15 for Fedora 37 - x86_64                                                                 61  B/s | 195  B     00:03    
正在忽略仓库:mongodb-org
元数据缓存已建立。
’‘’

### 期望的现象（What you expected to happen）

正常使用Tuna的MongoDB源

### 如何重现此问题（How to reproduce it）

‘’‘
[root@fedora yum.repos.d]# cat mongodb.repo 
[mongodb-org]
name=MongoDB Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el$releasever/
gpgcheck=0
enabled=1
[root@fedora yum.repos.d]# yum makecache 
Fedora 37 - x86_64                                                                                   22 kB/s | 6.1 kB     00:00    
Fedora Modular 37 - x86_64                                                                           12 kB/s | 6.5 kB     00:00    
Fedora 37 - x86_64 - Updates                                                                         11 kB/s | 8.1 kB     00:00    
Fedora Modular 37 - x86_64 - Updates                                                                2.1 kB/s | 4.9 kB     00:02    
MongoDB Repository                                                                                  175  B/s | 153  B     00:00    
Errors during downloading metadata for repository 'mongodb-org':
  - Status code: 404 for https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el37/repodata/repomd.xml (IP: 101.6.15.130)
Error: 为仓库 'mongodb-org' 下载元数据失败 : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
PostgreSQL common RPMs for Fedora 37 - x86_64                                                        73  B/s | 195  B     00:02    
PostgreSQL 15 for Fedora 37 - x86_64                                                                 61  B/s | 195  B     00:03    
正在忽略仓库:mongodb-org
元数据缓存已建立。
’‘’

### 操作系统（OS Version）

Fedora 37 Server (6.1.7-200.fc37.x86_64)

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/el37/repodata/repomd.xml

注意到 el37 中的 37 是 Fedora 的版本号，而镜像站提供的是 CentOS/RHEL 版本号（在[目录](https://mirrors.tuna.tsinghua.edu.cn/mongodb/yum/)中有 el7），故而会 404

上游并不支持 Fedora，参考 https://www.mongodb.com/docs/manual/administration/install-on-linux/

您可以联系上游提供 Fedora 相关支持。
