### ISSUE TITLE
[镜像请求] PowerToys

### ISSUE THREAD

**Issue by lihaoyu1234** [tuna/issues#1659]
### 先决条件 (Prerequisites)

- [x] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

PowerToys：Microsoft PowerToys 是一组实用工具，可帮助高级用户调整和简化其 Windows 体验，从而提高工作效率。

### 上游地址与镜像方法 (How to mirror)

https://github.com/microsoft/PowerToys/releases

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by lihaoyu1234** [comment]
突然发现之前好像有人提到了……

https://github.com/tuna/issues/issues/1600

**Comment by Harry-Chen** [comment]
Duplicate with #1600
