### ISSUE TITLE
MongoDB 的 3.4 版本目前没有同步到

### ISSUE THREAD

**Issue by pupboss** [tuna/issues#166]
官方的 stable 版本已经变成了 3.4

    https://github.com/tuna/tunasync-scripts/blob/master/mongodb.sh

这个脚本的 16，17 行似乎应该改成如下

```
MONGO_VERSIONS=("3.4" "3.2" "3.0")
STABLE_VERSION="3.4"
```

**Comment by pupboss** [comment]
不好意思，刚才去

    http://repo.mongodb.org/apt/debian

看了看，并没有 3.4 这个文件夹，但是添加

    deb https://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main

是有效的，这个我不清楚是怎么回事

**Comment by bigeagle** [comment]
哈，这就是 repo.mongodb.org 没把目录暴露出来。没事我们能镜像下来，任务已经发下去了。
