### ISSUE TITLE
Google Fonts 的 noto-cjk 在 TUNA 镜像站上 release 版本过少

### ISSUE THREAD

**Issue by MS-Windows** [tuna/issues#1660]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

镜像站主页，通过右侧按钮（获取下载链接）中“字体”选项卡，点击“Google Fonts”，此处展示的 CJK 字体仅有无衬线（Noto Sans CJK）字形，缺少衬线（Noto Serif CJK）字形的 CJK 字体。

### 期望的现象（What you expected to happen）

镜像站主页，通过右侧按钮（获取下载链接）中“字体”选项卡，点击“Google Fonts”，此处展示的 CJK 字体不仅有无衬线（Noto Sans CJK）字形，还有衬线（Noto Serif CJK）字形的 CJK 字体。

### 如何重现此问题（How to reproduce it）

该问题是由于同步的上游镜像（Google Fonts 下的 Noto CJK 存储库的 Release assets）将 Sans 和 Serif 两种字体作为不同的版本发布，导致 Sans 比 Serif 更晚发布，TUNA 镜像站只拉取了最近的 assets，故而只有 Sans 可供镜像站用户下载。
建议保留近两次的发布版本所属资源文件，而不只是最近一次，这样一来即便无法从快速下载链接中获取全部资源文件，但也可在左侧搜索 googlefonts 后手动找到 Serif 自行，暂时在一定程度上解决本 issue 所描述问题。

### 操作系统（OS Version）

Almost ANY

### 浏览器（如果适用）（Browser version, if applicable）

Almost ANY

### 其他环境（Other environments）

Almost ANY

### 其他需要说明的事项（Anything else we need to know）

可能需要也向 Google Fonts 的 Noto CJK 提出建议，建议将 Noto CJK 也像 Adobe 那样拆分为 Sans 和 Serif 两个仓库，从而区分开这两个字形所属存储库。（该意见仅供参考）

**Comment by ZenithalHourlyRate** [comment]
现已修复。

**Comment by MS-Windows** [comment]
对于 2023 年 2 月 3 日 晚 10:26，验证确已修复。感谢 ZenithalHourlyRate 等关注本 issue 的朋友们！
