### ISSUE TITLE
RedHat、PyBOMBS 镜像已过时

### ISSUE THREAD

**Issue by ljlofficial** [tuna/issues#1661]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

检查镜像站同步情况时，发现RedHat、PyBOMBS同步状态为failed，检查上一次正常同步时间分别为2022年6月和4月
访问PyBOMBS时发现已不存在，RedHat情况不明。

### 期望的现象（What you expected to happen）

检查RedHat、PyBOMBS镜像上游情况，如果不存在请删除，如果上游更换同步链接请更换

### 如何重现此问题（How to reproduce it）

请检查镜像站同步情况即可看到

**Comment by ZenithalHourlyRate** [comment]
redhat 上游拒绝了我们的 rsync 访问，我们也找不到联系上游的方式。

pybombs 无法从网页端访问，需要通过 git 访问，参考 https://mirrors.tuna.tsinghua.edu.cn/help/pybombs/
。该镜像是正常同步的，出现问题的是某个消失的 repo，参考 https://github.com/gnuradio/gr-recipes/issues/285

**Comment by LJLonGithub** [comment]
太草了，可否能fetch一下Pybombs的同步信息？毕竟看到failed就血压高:(

**Comment by scateu** [comment]
https://github.com/gnuradio/gr-recipes/issues/285  上游刚刚已经把最后一个failed修掉了，过段时间应该就不fail了。
