### ISSUE TITLE
Debian 镜像正在同步中？

### ISSUE THREAD

**Issue by UMU618** [tuna/issues#1662]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

错误:7 https://opentuna.cn/debian bullseye-backports/main amd64 Packages
  文件尺寸不符(384460 != 384452)。您使用的镜像正在同步中？ [IP: 180.163.57.93 443]
  Hashes of expected file:
   - Filesize:384452 [weak]
   - SHA256:bfbfc86d58f69637fd551436bca490a7f66b3576a7ae01df668ea4348b58683c
  Release file created at: Fri, 03 Feb 2023 20:14:48 +0000
已下载 905 kB，耗时 12秒 (77.6 kB/s)
正在读取软件包列表... 完成
E: 无法下载 https://opentuna.cn/debian/dists/bullseye-backports/main/binary-amd64/Packages.xz  文件尺寸不符(384460 != 384452)。您使用的镜像 正在同步中？ [IP: 180.163.57.93 443]
   Hashes of expected file:
    - Filesize:384452 [weak]
    - SHA256:bfbfc86d58f69637fd551436bca490a7f66b3576a7ae01df668ea4348b58683c
   Release file created at: Fri, 03 Feb 2023 20:14:48 +0000
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

### 期望的现象（What you expected to happen）

速度秒杀 aliyun，不料居然 bug 了。

### 如何重现此问题（How to reproduce it）

用 Debian 11 的 apt update

### 操作系统（OS Version）

Debian 11

**Comment by ZenithalHourlyRate** [comment]
统一在 #1597 跟踪
