### ISSUE TITLE
关于如何让VSCodium从tuna源更新

### ISSUE THREAD

**Issue by stackinspector** [tuna/issues#1663]
今天发现机器上的VSCodium很久没有更新了，才发现VSCodium自己搭建的更新API是从GitHub release下载更新的（参考[文档](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#replacement-online-services)和[API的源码](https://github.com/VSCodium/update-api/blob/master/api/update/index.js#L42)）。要想实现从tuna源下载更新，似乎需要再搭建一个更新API，然后手动改product.json里的`updateUrl`。在那边提了一个[issue](https://github.com/VSCodium/vscodium/issues/1399)，说不定他们会想别的办法。另外如果需要再搭建一个更新API的话，tuna的服务器有地方运行吗？

**Comment by Harry-Chen** [comment]
原则上我们不会运行此类第三方服务，仅提供静态文件下载
