### ISSUE TITLE
使用llvm镜像404：https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/

### ISSUE THREAD

**Issue by githublaohu** [tuna/issues#1665]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照https://mirrors.tuna.tsinghua.edu.cn/help/llvm-apt/ 文档操作。执行apt-get update 报一下异常
```code

错误:11 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy/main i386 Packages
  404  Not Found [IP: 101.6.15.130 443]
```

### 期望的现象（What you expected to happen）

正常使用，不报404

### 如何重现此问题（How to reproduce it）

按照文档执行

### 操作系统（OS Version）

Ubuntu22.04

**Comment by ZenithalHourlyRate** [comment]
这是由于您开启了 i386 架构，而 llvm-apt 并未提供该架构。

您可以管边该架构，或者在配置中使用类似 `deb [arch=amd64]` 的语法限定使用 amd64 源。
