### ISSUE TITLE
[镜像请求] Homebrew JSON API

### ISSUE THREAD

**Issue by XuehaiPan** [tuna/issues#1666]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

原链接: [https://formulae.brew.sh](https://formulae.brew.sh/docs/api)

Homebrew JSON API 将在 `brew` 4.0 之后成为用户默认安装软件包的方式。大部分用户将在 `brew` 4.0 后无需 git clone [homebrew/core](https://github.com/homebrew/homebrew-core) 仓库即可安装所需软件。该 API 类似于 conda 的 `repodata.json` 的形式，包括所有可用的软件包的版本、依赖、下载链接。`brew` 将依该 metadata 直接安装对应的软件而无需 clone [homebrew/core](https://github.com/homebrew/homebrew-core) 整个仓库。由于该 API 将 host 在 GitHub 上，故请求添加国内镜像。

### 上游地址与镜像方法 (How to mirror)

```bash
wget https://formulae.brew.sh/api/formula.json
wget https://formulae.brew.sh/api/cask.json
wget https://formulae.brew.sh/api/formula/<formula>.json  # e.g., https://formulae.brew.sh/api/formula/wget.json
wget https://formulae.brew.sh/api/cask/<cask>.json        # e.g., https://formulae.brew.sh/api/cask/qq.json
```

然后提供一个入口可以用户用户使用 GET 方法下载 `${HOMEBREW_API_DOMAIN}/formula.json` 等文件，如：

```
GET https://mirrors.tuna.tsinghua.edu.cn/homebrew/api/formula.json
```

### 镜像大小 (Mirror size)

300 MB

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
恐怕不只是 wget 这么简单，按我的理解，json 文件里面的 ghcr 链接应该也要修改？ @XuehaiPan

**Comment by XuehaiPan** [comment]
> json 文件里面的 ghcr 链接应该也要修改？

不需要，如果用户设置了 `HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles`，`brew` 将会自动处理。

**Comment by taoky** [comment]
> 不需要，如果用户设置了 HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles，brew 将会自动处理。

但是就我刚才的测试，即使设置了 `HOMEBREW_BOTTLE_DOMAIN`，brew 在使用新 API 的时候也不会采用这个环境变量的值。

brew version: 3.6.20-298-g8fdf6ac

**Comment by ZenithalHourlyRate** [comment]
json 太多了，我在[问上游](https://github.com/Homebrew/formulae.brew.sh/issues/730)是否可以发布一个 API tarball

**Comment by ZenithalHourlyRate** [comment]
现已在 https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api/ 镜像相关 API。

@XuehaiPan 能帮忙写一下这个的镜像帮助吗。
