### ISSUE TITLE
homebrew安装中报告404错误

### ISSUE THREAD

**Issue by bztia** [tuna/issues#1668]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照说明执行homebrew安装,报告:

==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/portable-ruby-2.6.8_1.el_capitan.bottle.tar.gz
-#O=#   #    #                                                                                                         
curl: (22) The requested URL returned error: 404 

### 期望的现象（What you expected to happen）

安装成功

### 如何重现此问题（How to reproduce it）

export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"

git clone --depth=1 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/install.git brew-install
/bin/bash brew-install/install.sh

### 操作系统（OS Version）

macOS 15

**Comment by ZenithalHourlyRate** [comment]
你试试 `export HOMEBREW_NO_INSTALL_FROM_API=1` 后安装会如何?

**Comment by ZenithalHourlyRate** [comment]
找到了，是上游去年十月[更新](https://github.com/Homebrew/homebrew-portable-ruby/releases/tag/2.6.10)了 portable-ruby 到 2.6.10，镜像站随后更新到了该版本；但 brew 中依旧使用的是[旧版本 2.6.8](https://github.com/Homebrew/brew/blob/eb7c6ad195e444ce04178b2c3a98d42bdc756065/Library/Homebrew/cmd/vendor-install.sh#L23)，导致不一致

**Comment by ZenithalHourlyRate** [comment]
> 你试试 `export HOMEBREW_NO_INSTALL_FROM_API=1` 后安装会如何?

关于这个有个额外说明……根据我的尝试，在 brew 4.0 之前，默认已经是 NO_INSTALL_FROM_API，只有在 4.0 后（应该快要发布了），才会启用 INSTALL_FROM_API，参考 https://github.com/Homebrew/install/pull/732 ，所以现在的安装命令仍旧会 tap homebrew/core

另外，即使设置了 INSTALL_FROM_API，install 的行为似乎也是坏的，它仍旧 tap 了 homebrew.core，log 如下

```
==> Skip tapping homebrew/core because `$HOMEBREW_INSTALL_FROM_API` is set.
HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git for Homebrew/brew Git remote.
HOMEBREW_CORE_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git for Homebrew/core Git remote.
remote: Enumerating objects: 570113, done.
remote: Counting objects: 100% (570113/570113), done.
remote: Compressing objects: 100% (44494/44494), done.
remote: Total 1413385 (delta 559248), reused 525619 (delta 525619), pack-reused 843272
Receiving objects: 100% (1413385/1413385), 489.90 MiB | 3.36 MiB/s, done.
Resolving deltas: 100% (991754/991754), done.
From https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core
 * [new branch]      master     -> origin/master
```

Cc @XuehaiPan 能麻烦帮忙修复 brew 用老的 portable-ruby 的问题以及看一下 install 的这个坏行为吗。我会先手动临时链接 portable-ruby 到 2.6.8，然后在帮助里加上 HOMEBREW_INSTALL_FROM_API。

**Comment by ZenithalHourlyRate** [comment]
以及其实这个问题并不影响用户的安装，install 会自动 fallback 到 ghcr

```
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404

==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:fc45ee6eddf4c7a17f4373dde7b1bc8a58255ea61e6847d3bf895225b28d072a
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
```

**Comment by XuehaiPan** [comment]
> 修复 brew 用老的 portable-ruby 的问题以及看一下 install 的这个坏行为吗。我会先手动临时链接 portable-ruby 到 2.6.8

镜像里保留至少两个 portable-ruby 版本应该就可以了吧。每次同步的时候不要马上把老版本删掉。

**Comment by ZenithalHourlyRate** [comment]
> 镜像里保留至少两个 portable-ruby 版本应该就可以了吧。每次同步的时候不要马上把老版本删掉。

```
$ ls -alh bottles-portable-ruby
lrwxrwxrwx 1 tunasync tunasync 63 Mar  9  2020 bottles-portable-ruby -> ../github-release/Homebrew/homebrew-portable-ruby/LatestRelease
```
portable-ruby 其实是另外同步的， homebrew-bottles 这边是软链接，保留两个版本也没法工作；也不可能每次手动更新软链接吧。

**Comment by XuehaiPan** [comment]
> ```
> ==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
> ```

链接里应该会有版本后缀吧

**Comment by ZenithalHourlyRate** [comment]
目前这样修了

```
$ ln -sTf ../github-release/Homebrew/homebrew-portable-ruby/2.6.8_1 bottles-portable-ruby
$ ls -alh bottles-portable-ruby
lrwxrwxrwx 1 tunasync tunasync 57 Feb 11 00:30 bottles-portable-ruby -> ../github-release/Homebrew/homebrew-portable-ruby/2.6.8_1
```
