### ISSUE TITLE
opentuna 的 Ubuntu 帮助页需要更新

### ISSUE THREAD

**Issue by zhullyb** [tuna/issues#1669]
https://opentuna.cn/help/ubuntu/
至少应当更新 22.04 LTS 的换源帮助

**Comment by ZenithalHourlyRate** [comment]
@jiegec https://github.com/tuna/opentuna/pull/222

**Comment by laozhoubuluo** [comment]
这个页面的 "请使用 [ubuntu-ports 镜像](https://opentuna.cn/ubuntu-ports/)" 链接也是 404 ，可以考虑直接链接到其他镜像站或者索性在 OpenTUNA 上新增 ubuntu-ports 镜像。

**Comment by ZenithalHourlyRate** [comment]
> 链接到其他镜像站

这个是 by design 的，页面是静态生成的，404是动态做得，比较难改

**Comment by laozhoubuluo** [comment]
> > 链接到其他镜像站
> 
> 这个是 by design 的，页面是静态生成的，404是动态做得，比较难改

 看了看 https://opentuna.cn/help/kubernetes/ 里面的 "请到 [minikube 镜像](https://opentuna.cn/github-release/kubernetes/minikube/LatestRelease/) 下载" 也有这问题。
本来想说不如直接加镜像完了相信后人的智慧，但是现在看来如果不是孤例需要架构解决的话，确实头疼。

**Comment by jiegec** [comment]
Updated.

**Comment by ZenithalHourlyRate** [comment]
> 可以考虑直接链接到其他镜像站

现在可以部分解决这个问题

参考 https://mirrors.bfsu.edu.cn/help/netbsd/ ，其中的 pkgsrc 帮助由于 BFSU 不存在镜像而会跳转到通用帮助页面。
