### ISSUE TITLE
我是一个新手，对于如何使用anaconda镜像下载包有一些问题

### ISSUE THREAD

**Issue by cobaltyang** [tuna/issues#1670]
Question1：pkgs和cloud有什么区别呢？pkgs和cloud目录的子目录中各自又代表什么呢？我该具体选择哪个子目录来下载呢？
![image](https://user-images.githubusercontent.com/41852561/219250909-645759f8-8a9e-4928-a4af-c5b1aa0f05d3.png)

我是一个编程新手，刚接触anaconda。想使用tuna的anaconda镜像下载包，但是发现tuna上并没有详细的介绍文档，在其他博客网站也没有找到相关的帖子，这让我想用但不会用。有人可以给我推荐一些相关资料吗？
此外，我有个建议，tuna可以增加详细的文档吗？

**Comment by ZenithalHourlyRate** [comment]
您好，您可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/

**Comment by cobaltyang** [comment]
您好，我在tuna的官网看到了，

> 您好，您可以参考 [mirrors.tuna.tsinghua.edu.cn/help/anaconda](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)

但是我感觉介绍内容有些简略，没有对目录树的结构说明，无法完全解答我的问题😭

**Comment by ZenithalHourlyRate** [comment]
您好，如介绍中的配置所示，`pkgs` 是官方软件包存放的地方，例如 main, r, msys2；而 `cloud` 是存放第三方（custom）软件包的地方，例如 pytorch, conda-forge
