### ISSUE TITLE
[镜像请求] anaconda 的nvidia channel

### ISSUE THREAD

**Issue by 6ixGODD** [tuna/issues#1671]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Nvidia 的 channel 是 Anaconda 源中提供的一个额外渠道，其中包含了许多 Nvidia 相关的软件包和工具。这些软件包和工具主要是针对 Nvidia 的 GPU 技术进行优化和支持的。这些软件包和工具包括了深度学习框架 Tensorflow、PyTorch、MXNet、CUDA、cuDNN 等。使用 Nvidia 的 channel 可以方便地安装和管理这些软件包和工具，以及利用 Nvidia 的 GPU 技术来加速深度学习和其他计算密集型任务

### 上游地址与镜像方法 (How to mirror)

https://conda.anaconda.org/nvidia/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
重复 issue；https://github.com/tuna/issues/issues/1232
