### ISSUE TITLE
镜像源技术支持

### ISSUE THREAD

**Issue by jiangsha1007** [tuna/issues#1673]
你好，我们想搭建一套与清华大学开源软件镜像站相似的平台[清华大学开源软件镜像站 | Tsinghua Open Source Mirror](https://mirrors.tuna.tsinghua.edu.cn/)。我们想得到你们的技术支持，包括但不限于搭建所需的硬件资源，部署方法等，我们可能更多地希望同步pip源，rpm源，docker镜像仓库，npm源，go源等。可以联系我的邮箱 jiangsha1007@sina.com。谢谢！

**Comment by shankerwangmiao** [comment]
您好，我们整理了一份相关技术的文档，供您参考：https://github.com/tuna/tunasync/wiki/Mirroring-Howto

**Comment by jiangsha1007** [comment]
太好了，求更新后面内容

**Comment by shankerwangmiao** [comment]
目前暂无较好的同步 npm 的方案

**Comment by jiangsha1007** [comment]
在内外网无法相连 的环境下部署，是不是内外网的机子都要用ZFS的文件系统？

**Comment by shankerwangmiao** [comment]
对的

**Comment by jiangsha1007** [comment]
不好意思，能加您微信吗？

**Comment by jiangsha1007** [comment]
> 目前暂无较好的同步 npm 的方案

go的镜像是不是也不太好实现？
