### ISSUE TITLE
[镜像请求] winget source

### ISSUE THREAD

**Issue by CDboyOne** [tuna/issues#1674]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

用户可以在 Windows 10 和 Windows 11 计算机上使用 winget 命令行工具来发现、安装、升级、删除和配置应用程序。 此工具是 Windows 程序包管理器服务的客户端接口。
winget-cli 工具依赖于源。目前微软提供 msstore 和 winget 两个官方源。
开发者可以托管自定义的基于 REST 的源。

### 上游地址与镜像方法 (How to mirror)

官方 winget 源仓库。软件维护者只要将新版软件的版本、下载地址等信息提交到此库中即可。
[https://github.com/microsoft/winget-pkgs]
下面这个是微软提供的 REST 源示例：
https://github.com/microsoft/winget-cli-restsource
目前，msstore 源在国内可以正常访问，但 winget 源的访问速度基本为零，难以使用。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您可以参考

https://github.com/ustclug/mirrorrequest/issues/275
> 同时 yaml 中指定的 InstallerUrl 依然是软件官网的链接，对索引进行镜像/反代就和反代 aur 一样，感觉没有啥实际意义或者体验提升
> 
> 至于 stackoverflow 这篇回答里面提到的用 https://github.com/microsoft/winget-cli-restsource/ 的方案，目前不考虑为了 winget 单独开个第三方的服务端程序。

https://github.com/tuna/issues/issues/1663
> 原则上我们不会运行此类第三方服务，仅提供静态文件下载

**Comment by CDboyOne** [comment]
感谢指引
