### ISSUE TITLE
centos的mysql镜像配置和实际的镜像不符合

### ISSUE THREAD

**Issue by onetech17** [tuna/issues#1675]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

你们在使用帮助中配置的是：
[mysql-connectors-community]
name=MySQL Connectors Community
baseurl=https://mirrors.bfsu.edu.cn/mysql/yum/mysql-connectors-community-el8-$basearch/
enabled=1
gpgcheck=1
gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql

[mysql-tools-community]
name=MySQL Tools Community
baseurl=https://mirrors.bfsu.edu.cn/mysql/yum/mysql-tools-community-el8-$basearch/
enabled=1
gpgcheck=1
gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql

[mysql-8.0-community]
name=MySQL 8.0 Community Server
baseurl=https://mirrors.bfsu.edu.cn/mysql/yum/mysql-8.0-community-el8-$basearch/
enabled=1
gpgcheck=1
gpgkey=https://repo.mysql.com/RPM-GPG-KEY-mysql

实际上相应文件路径却是
https://mirrors.bfsu.edu.cn/mysql/yum/
这里只有7，没有8。
8被放在7的目录中。

### 期望的现象（What you expected to happen）

镜像文件和使用帮助写的一致。应该把镜像源中的文件放置在正确的目录下。

### 如何重现此问题（How to reproduce it）

https://mirrors.bfsu.edu.cn/mysql/yum/
这是镜像源
https://mirrors.bfsu.edu.cn/help/mysql/
这是配置帮助，需要把centos版本设置为8

### 操作系统（OS Version）

centos

### 浏览器（如果适用）（Browser version, if applicable）

任意

**Comment by ZenithalHourlyRate** [comment]
@onetech17 https://mirrors.bfsu.edu.cn/news/remove-eol-repo/
