### ISSUE TITLE
Ubuntu下载python3-pip时报错

### ISSUE THREAD

**Issue by XDzzzzzZyq** [tuna/issues#1676]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![image](https://user-images.githubusercontent.com/81028185/220061463-52aad6d9-bf14-460c-b496-70482cf47c84.png)
![image](https://user-images.githubusercontent.com/81028185/220061551-42f6db98-d2e3-4a9d-87a6-e43246f7a206.png)

好像是有文件缺失

### 期望的现象（What you expected to happen）

正常下载

### 如何重现此问题（How to reproduce it）

试试看用Ubuntu运行sudo apt install python3-pip指令

### 操作系统（OS Version）

Ubuntu 2022

### 其他环境（Other environments）

win10

**Comment by ZenithalHourlyRate** [comment]
```
# zenithal @ nanomirrors in ubuntu/pool/main/l/linux [17:13:58] 
$ ls linux-libc-dev_5.15.0*
linux-libc-dev_5.15.0-25.25_amd64.deb  linux-libc-dev_5.15.0-60.66_amd64.deb  linux-libc-dev_5.15.0-66.73_amd64.deb
linux-libc-dev_5.15.0-25.25_i386.deb   linux-libc-dev_5.15.0-60.66_i386.deb   linux-libc-dev_5.15.0-66.73_i386.deb
```

Try `apt update` then `apt install python3-pip`

**Comment by XDzzzzzZyq** [comment]
problem resolved, thank!
