### ISSUE TITLE
考虑移除 Julia 镜像或切换同步方式

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [tuna/issues#1677]
目前 Julia 镜像占用大，利用率低，提议移除

1. Julia 镜像占用约 3.6T，占用 TUNA 与 BFSU 镜像站总储存空间的约 4%
2. 过去一周 /julia 的 TUNA 流量为 30G，BFSU 的为 40G；而 TUNA 过去一周流量约 570T，BFSU 约 163T。

注意到 https://discourse.juliacn.com/t/topic/2969 中 juliacn 已经提供了相应的镜像

我们认为该问题可以有两个方法解决

1. 移除相应镜像，并将其重定向到 juliacn 的相关站点
2. 修改同步脚本，使得空间占用量降低

我们倾向于使用第一种方法解决，因为镜像站维护人员并不熟悉 julia，且时间精力有限。

移除可能在任何空间告警的时候发生。目前，BFSU 的空间利用已达 99.1%，TUNA 的空间利用已达 98.5%，会随时在镜像大小波动中占满储存。

Cc @johnnychen94

**Comment by johnnychen94** [comment]
社区目前的服务器在容量和稳定性上不是很优，实际上很多用户还是会手动定向至校园镜像站来使用 Julia，重定向的话可能会导致用户大批量开始抱怨。

从我所知道的来说，Julia 社区里目前确实存在对 Artifacts 进行滥用的情况，例如: [BinaryBuilderBase](https://github.com/JuliaPackaging/BinaryBuilderBase.jl) 以一己之力占了 300GB 的 artifacts 空间[^1] 官方对此的态度应该是这些都属于 S3 考虑的东西而 S3 存储很便宜所以导致增长有点过快

我能想到的几个更平滑的策略是：

- 找商业化支持来支撑代理服务器的部署，优化社区的服务器质量
- 定位 artifacts 占用量高的包，然后在同步脚本中引入黑名单机制屏蔽这些包的 artifacts 下载（这样做会导致用户的下载会被导向 github）：如果这样做的话，大约需要将空间压缩到什么程度才算是可行的呢，比如说，1T 以内？

[^1]: https://gist.github.com/johnnychen94/ade1d5fd1eb398edf017ab42623397c1

**Comment by xgdgsc** [comment]
就这么大吗，有没有出钱加硬盘的选项？

**Comment by jiegec** [comment]
主要是性价比的问题，单台服务器插满的硬盘容量也就那么多，需要优先考虑用的人多的。

**Comment by ZenithalHourlyRate** [comment]
> * 定位 artifacts 占用量高的包，然后在同步脚本中引入黑名单机制屏蔽这些包的 artifacts 下载（这样做会导致用户的下载会被导向 github）：如果这样做的话，大约需要将空间压缩到什么程度才算是可行的呢，比如说，1T 以内？
> 

我们可以接受这种方案；当然，也可以屏蔽一些旧的 artifact，例如只同步最新版本；我们期待总占用小于 500G。

**Comment by johnnychen94** [comment]
我现在在全职工作所以可能没有这么快响应，我会尽量在 3.15 之前给出一个新的满足需求的同步方案。

**Comment by GiggleLiu** [comment]
> 由于架构要求，扩容的成本不仅仅是增加单块硬盘。例如，镜像站单台主力服务器的扩容需要超过 20 块的大容量高速 NVMe 硬盘，目前每块的成本超过 10000 人民币。我想这一成本对于非盈利的开源组织来说是很沉重的。

感谢说明，JuliaCN 支持一块是没有问题的，但是20块对开源组织肯定有沉重的负担。不知道这里的一块盘能否支撑 3.5 T 的开销。
总是让镜像源用爱发电肯定不是可持续的方案，所以我建议核算清楚成本，提供个可选方案，让其它组织一起承担开销。只要开销合理，JuliaCN 可以向一些公司去拉赞助，这样开源生态才可以转起来。

> 作为一个 HPC 从业者，我目前没有见到显著的使用 Julia 进行的严肃计算。

引用你的个人经验来说明问题是不公平的，科学计算本来就是从学术届慢慢向工业界扩散的过程，普通用户少只是暂时的。Julia 对于开发新的算法是很有吸引力的，从学术界对 Julia 软件包的引用就可以看出来

## 引用数学优化软件 JuMP.jl 进行计算的工作：
![image](https://user-images.githubusercontent.com/6257240/223894686-fd207957-4c9f-4b2c-bf2e-08de5190fd73.png)

## 引用 Julia package ITensor.jl 的工作：
![image](https://user-images.githubusercontent.com/6257240/223894975-58fafd06-91eb-4381-bce7-ff75858dccd9.png)

http://itensor.org/docs.cgi?page=papers

## 引用量子计算模拟器 Yao.jl 进行计算的工作，其中就包括清华的某量子课题组的约十篇工作：
![image](https://user-images.githubusercontent.com/6257240/223894529-d0d37c43-fc57-45f4-819d-6ece9458cefa.png)

**Comment by GiggleLiu** [comment]
> > > 由于架构要求，扩容的成本不仅仅是增加单块硬盘。例如，镜像站单台主力服务器的扩容需要超过 20 块的大容量高速 NVMe 硬盘，目前每块的成本超过 10000 人民币。我想这一成本对于非盈利的开源组织来说是很沉重的。
> > 
> > 
> > 感谢说明，JuliaCN 支持一块是没有问题的，但是20块对开源组织肯定有沉重的负担。不知道这里的一块盘能否支撑 3.5 T 的开销。 总是让镜像源用爱发电肯定不是可持续的方案，所以我建议核算清楚成本，提供个可选方案，让其它组织一起承担开销。只要开销合理，JuliaCN 可以向一些公司去拉赞助，这样开源生态才可以转起来。
> 
> 这里面其实是有个问题的，作为小型的存储系统，它并非是可以无限分割的，不能像水那样想要多少就可以量取多少。即使添加，也不可能是一块一块地添加，更何况硬盘的插槽其实也快满了。所以要扩容的话可能是所有盘一起都换掉。因此核算成本其实并不能解决眼下存储即将耗尽的问题。目前我们还在争取条件看看能否进一步扩充容量，不过暂时没有时间表。

恩，希望可以争取下。感谢

> 
> > > 2% 不解决本质问题，但能缓解其他在目前更重要、用户更多的软件或系统的燃眉之急。
> > 
> > 
> > 很多国内 julia 的软件源写的是 tuna 的，网上的教程也是写 tuna 的源的居多。撤销 tuna 源之后，大家得重新找源。教程也得修改。除非可以加个重定向，否则对 julia 生态打击是很大的。
> 
> 如果确实不得不出现这样的遗憾情况，我们会做好后续收尾工作。

恩，做好两手准备吧。@johnnychen94  也在找新的解决方案，如果必须删除，我们再看下如何才能更加平滑的重定向过去。

**Comment by leavelet** [comment]
北大镜像站 Julia 源正在同步，预计 3.15 之前可以上线。我们正在和 TUNA 积极沟通，看怎么过渡会比较合适。

**Comment by zsz00** [comment]
现在 北大镜像站 Julia 源 可用了吗? 地址是什么?

**Comment by zsz00** [comment]
现在 北大镜像站 Julia 源 可用了吗? 地址是什么?

**Comment by ZenithalHourlyRate** [comment]
在 2 月 22 日时 BFSU 存储利用率达到了 99.6%，当时即移除 julia 镜像并将其重定向到 TUNA

现在 TUNA 一台后端服务器端存储利用率达到了 99.3%

**Comment by ZenithalHourlyRate** [comment]
> 现在 TUNA 一台后端服务器存储利用率达到了 99.3%

现在 TUNA 一台后端服务器存储利用率达到了 99.7%，已移除相应镜像。

目前，http 服务仍能正常工作，rsync 因为负载均衡会按照来源IP出现不工作的情况

**Comment by leavelet** [comment]
欢迎大家测试：mirrors.pku.edu.cn/julia

**Comment by ZenithalHourlyRate** [comment]
> 现在 TUNA 一台后端服务器存储利用率达到了 99.7%，已移除相应镜像。

另一台后端服务器存储利用率也来到了 99.7%，已移除相应镜像，并将相应 http 流量重定向到 PKU；rsync 服务已停止，并通知到了已知的下游。

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/news/remove-julia-openresty-mysql-ftp/

**Comment by yaoge123** [comment]
https://mirror.nju.edu.cn/julia/ 继续服务

**Comment by johnnychen94** [comment]
请问 opentuna.cn 是否也计划做相应移除？我看它上一次同步是在一周前 (0322)
