### ISSUE TITLE
mac brew install ffmpeg。jpeg-turbo  404

### ISSUE THREAD

**Issue by yangfangkuo** [tuna/issues#1678]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

mac brew install ffmpeg。jpeg-turbo 资源404

### 期望的现象（What you expected to happen）

资源可以找到

### 如何重现此问题（How to reproduce it）

brew install ffmpeg

### 操作系统（OS Version）

Mac arm64_ventura

### 浏览器（如果适用）（Browser version, if applicable）

终端

### 其他环境（Other environments）

13.2.1 (22D68)

### 其他需要说明的事项（Anything else we need to know）

安装ffmpeg 过程中间报404==> Fetching jpeg-turbo
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles//jpeg-turbo-2.1.4.arm64_ventura.bottle.tar.gz
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-167-g7a5f614\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/yangfangkuo/Library/Caches/Homebrew/downloads/46635bf5ab7d534c7e723d77d7372bfb99158038c088c9bacf0721c4d392bb6f--jpeg-turbo-2.1.4.arm64_ventura.bottle.tar.gz.incomplete https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles//jpeg-turbo-2.1.4.arm64_ventura.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Warning: Bottle missing, falling back to the default domain...

**Comment by ZenithalHourlyRate** [comment]
您可能需要在安装前先允许 `brew update`

镜像站上有更新的文件

```
$ ls jpeg-turbo-*                                         
jpeg-turbo-2.1.5.1.arm64_big_sur.bottle.tar.gz   jpeg-turbo-2.1.5.1.arm64_ventura.bottle.tar.gz  jpeg-turbo-2.1.5.1.monterey.bottle.tar.gz  jpeg-turbo-2.1.5.1.x86_64_linux.bottle.tar.gz
jpeg-turbo-2.1.5.1.arm64_monterey.bottle.tar.gz  jpeg-turbo-2.1.5.1.big_sur.bottle.tar.gz        jpeg-turbo-2.1.5.1.ventura.bottle.tar.gz

```
