### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/anaconda/ 重定向到北外

### ISSUE THREAD

**Issue by Sakurasan** [tuna/issues#1679]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

访问https://mirrors.tuna.tsinghua.edu.cn/anaconda/ 重定向到 https://mirrors.tuna.tsinghua.edu.cn/anaconda/，北外的小水管没速度

### 期望的现象（What you expected to happen）

不跳

### 如何重现此问题（How to reproduce it）

访问上面地址

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1633#issuecomment-1355955939
