### ISSUE TITLE
anaconda部分文件被截断

### ISSUE THREAD

**Issue by guokr321** [tuna/issues#168]
#### 项目名称与简介(Project Intro.)
anaconda
#### 地址
https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/
### 问题
这个url下最后的一大半文件被截断为6000多字节了，本来应该是几百兆。

**Comment by bigeagle** [comment]
woc这个好坑……

**Comment by bigeagle** [comment]
重写了脚本，等这次同步完应该就好了。

**Comment by bigeagle** [comment]
看了下，昨天已经修复了。现在同步脚本会 check md5，应该靠谱多了。
