### ISSUE TITLE
镜像 https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git 404错误

### ISSUE THREAD

**Issue by chenxing640** [tuna/issues#1680]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

访问https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git产生了404错误

### 期望的现象（What you expected to happen）

恢复使用

### 如何重现此问题（How to reproduce it）

![截屏2023-02-22 10 45 16](https://user-images.githubusercontent.com/15623781/220508072-5d5c7328-6464-4734-ac88-6815518b71b2.png)

**Comment by ZenithalHourlyRate** [comment]
您好，该页面不通过 web 服务，您可以通过 git 下载使用，参考 https://mirrors.tuna.tsinghua.edu.cn/help/CocoaPods/

**Comment by chenxing640** [comment]
@ZenithalHourlyRate 谢谢您！在Podfile里添加了`source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'` ，前一段时间执行`pod install --repo-update`，一直在等待，更新不了。
