### ISSUE TITLE
请求 Adoptium 镜像保留历史版本

### ISSUE THREAD

**Issue by liaozan** [tuna/issues#1681]

**Comment by ZenithalHourlyRate** [comment]
您好，请您详细描述问题

**Comment by liaozan** [comment]
比如说，jdk11 升了 11.0.16，之前的 11.0.15就会被删除，导致 404

**Comment by ZenithalHourlyRate** [comment]
我们是通过
```
https://api.adoptium.net/v3/assets/latest/11/hotspot
```
获取文件列表的，该 API 只返回了最新的部分。

通过
```
https://api.adoptium.net/v3/assets/feature_releases/11/ga
```
获取所有版本，可知目前约有8个版本，目前服务器上通过 API 获取的文件约有 13G，如果获取全部历史文件这部分占用会达到 100G；这目前是可以接受的。

您可以通过修改 https://github.com/tuna/tunasync-scripts/blob/master/adoptium.py 并提交 PR 以增加该特性。

**Comment by liaozan** [comment]
实在有心无力，python八窍通了七窍，只剩下一窍不通了

**Comment by liaozan** [comment]
不知有没有进展？
