### ISSUE TITLE
ROS2镜像使用帮助文档修改建议

### ISSUE THREAD

**Issue by MyZQL** [tuna/issues#1682]
文档链接：https://mirrors.tuna.tsinghua.edu.cn/help/ros2/
由于镜像站内存在rosdistro镜像源，因此为提升获取GPG key的速度，对应命令可改为：
`sudo curl -sSL https://mirrors.tuna.tsinghua.edu.cn/rosdistro/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg`

**Comment by ZenithalHourlyRate** [comment]
我们不推荐通过镜像站获取 gpg key，这样可能存在安全问题。
