### ISSUE TITLE
[其他事项] CTEX 镜像需要更新

### ISSUE THREAD

**Issue by ganyuanzhen** [tuna/issues#1683]
如题，tuna镜像中的CTEX套装已经停止更新许久了，但是官网<https://ctex.org/ctex/download/> 已恢复更新。

希望可以重新开始更新CTEX套装

P.S. 近期CTEX更新说明

v3.0.212.1 — 2023.02.25
升级 MiKTeX 20230224
升级 WinEdt 11.1 (64-bit)
 
v3.0.208.0 — 2023.01.23
升级 MiKTeX 20230120
升级 GSview 6.0 (32/64)
升级 Ghostscript 10.00.0 (32/64)
升级 WinEdt 11.0 (64-bit) / 10.3 (32-bit)
 
v3.0.202.0 — 2022.10.24
修改版本号格式为 major.minor.build.stage，最后一个数字： 0-alpha, 1-beta, 2-release
升级 MiKTeX-x86 21.6-20221024
增加 MiKTeX-x64 22.7-20221024
更新 SumatraPDF 3.4.6 (32/64)
增加 MiKTeX 预装常用宏包
删除宏包 CJKpunct/hypernat，使用 MiKTeX 内含的版本
删除过时的宏包 CASthesis/PostDocRep
 
v2.9.2.167 — 2022.10.10
升级安装程序为 NSIS 3.08
修正安装时 Path 过长可能被覆盖的错误

**Comment by Harry-Chen** [comment]
感谢提醒，此镜像是由 CTEX 开发方推送的，而不是 TUNA 主动同步。我已经联系了 @wulingyun 协商相应事宜。

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/ctex/3.0/
