### ISSUE TITLE
[镜像请求] Debian Cloud Images

### ISSUE THREAD

**Issue by Jimmy-Z** [tuna/issues#1686]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Debian Cloud Images

### 上游地址与镜像方法 (How to mirror)

https://cloud.debian.org/images/cloud/
https://cdimage.debian.org/cdimage/cloud/

镜像方法未调查，应与debian-cd相似

### 镜像大小 (Mirror size)

未知

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ahdiua** [comment]
看了一眼bfsu也没有

**Comment by Harry-Chen** [comment]
目前的 `debian-cd` 上游是 `rsync://cdimage.debian.org/debian-cd/`，相关镜像存在于 `rsync://cdimage.debian.org/cdimage/cloud/`

**Comment by Harry-Chen** [comment]
我检查了一下内容，感觉发布内容过于频繁，并且都是二进制 ISO。此外，这些镜像是提供给 cloud provider 的，普通用户很少使用，没有太大镜像的意义。
