### ISSUE TITLE
安装包丢失

### ISSUE THREAD

**Issue by ahjcahkl** [tuna/issues#1687]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法下载 https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/p/python-pip/python3-pip_22.0.2%2bdfsg-1ubuntu0.1_all.deb  404  Not Found [IP: 101.6.15.130 443]

### 期望的现象（What you expected to happen）

能够正常安装python3-pip包

### 如何重现此问题（How to reproduce it）

进行sudo apt-get update之后，直接执行sudo apt install python3-pip指令

### 操作系统（OS Version）

Ubuntu

**Comment by shankerwangmiao** [comment]
请先 `apt-get update` 之后再执行 `apt-get install`
