### ISSUE TITLE
pypi.tuna.tsinghua.edu.cn 缺少 /pypi/<package>/<version>/json 资源

### ISSUE THREAD

**Issue by johnnychen94** [tuna/issues#1688]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

JSON API: https://wiki.python.org/moin/PyPIJSON

- 返回状态 200: `curl https://pypi.org/pypi/numpy/1.23.0/json`
- 返回状态 200: `curl https://pypi.org/pypi/numpy/json`
- 返回状态 200: `curl https://pypi.tuna.tsinghua.edu.cn/pypi/numpy/json`
- 返回状态 404: `curl https://pypi.tuna.tsinghua.edu.cn/pypi/numpy/1.23.0/json`

背景: [conda-lock](https://github.com/conda/conda-lock) 在利用 poetry 进行 pip 包版本解析时，会试图去查询 `/pypi/<package>/json` 以及 `/pypi/<package>/<version>/json` 这两个 API 然后生成 lock 文件。

### 期望的现象（What you expected to happen）

`curl https://pypi.tuna.tsinghua.edu.cn/pypi/numpy/1.23.0/json` 与 `curl https://pypi.org/pypi/numpy/1.23.0/json` 的结果一致

### 如何重现此问题（How to reproduce it）

利用 curl 或其他 http 请求工具查询上述 API 端口

**Comment by shankerwangmiao** [comment]
这个应该是 bandersnatch 的问题，我看其他镜像站也没这个接口

**Comment by happyaron** [comment]
bandersnatch 是按照 [PEP 381](https://peps.python.org/pep-0381/) 进行的静态镜像，XMLRPC和JSONAPI都属于动态部分，不在支持范围。

**Comment by johnnychen94** [comment]
https://pypi.tuna.tsinghua.edu.cn/ 的定位也是全量静态资源的镜像么？如果是的话那么这个 issue 大概就要关闭了

**Comment by shankerwangmiao** [comment]
tuna 上的镜像基本都是静态的。如果这个接口能静态化，并且 bandersnatch 能支持的话，我们是不反对的。
