### ISSUE TITLE
[镜像请求] Manjaro Mirror on OpenTUNA

### ISSUE THREAD

**Issue by Firestar-Reimu** [tuna/issues#1689]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Manjaro Linux是快速的、用户友好的、面向桌面的、基于Arch Linux的操作系统。它的一些显著特性包括：一份直观的安装程序、自动硬件检测、稳定的滚动式发布模式、对安装多个内核的支持、用于管理图形卡的特别Bash脚本、高度的桌面可配置性。Manjaro Linux提供Xfce桌面作为核心选项，并为高级用户提供一份最小主义的Net版本。用户还可以获得社区支持的GNOME 3/Cinnamon及KDE版本。Manjaro的社区论坛可提供帮助并充满活力，用户受益其中。

### 上游地址与镜像方法 (How to mirror)

https://wiki.manjaro.org/index.php/Manjaro_Mirrors

Asia / Japan:
rsync://ftp.tsukuba.wide.ad.jp/manjaro

RU / Russian Federation:
rsync://mirror.yandex.ru/mirrors/manjaro/

### 镜像大小 (Mirror size)

https://wiki.manjaro.org/index.php/Manjaro_Mirrors

> We are at around 90 GB. Minimum of 120 GB is recommended, since we might have bigger rebuilds, which might double our space need temporally. 200 GB or higher would be better. As an example see also [this](https://lists.manjaro.org/pipermail/manjaro-mirrors/Week-of-Mon-20151207/000013.html).

### 备注 (Note)

See https://github.com/tuna/opentuna/issues/230

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
OpenTUNA 即将关闭。
