### ISSUE TITLE
故障：在使用官方路径安装pytorch时，当删除掉“-c pytorch”（即启用清华源）后，清华源提供的并不是所需的pytorch版本，而是cpu版本

### ISSUE THREAD

**Issue by Jason-Dragon** [tuna/issues#1690]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

故障：在使用官方路径安装pytorch时，当删除掉“-c pytorch”（即启用清华源）后，清华源提供的并不是所需的pytorch版本（如cuda17），而是cpu版本，

### 期望的现象（What you expected to happen）

在启用清华源后，能够提供所需的pytorch版本

### 如何重现此问题（How to reproduce it）

写过了

### 操作系统（OS Version）

windows10

### 其他环境（Other environments）

cuda11 conda

**Comment by ZenithalHourlyRate** [comment]
> 当删除掉“-c pytorch”（即启用清华源）

这并不是启用清华源

**Comment by patrickwangqy** [comment]
因为现在pytorch的cuda需要-c nvidia，然而清华源没有提供nvidia的源

**Comment by ZenithalHourlyRate** [comment]
关于 nvidia channel，参考 https://github.com/tuna/issues/issues/1232

**Comment by appenuote** [comment]
补充一种可行的安装方式（pip + 国内镜像）

对于使用 pip 安装 PyTorch 的用户，可以使用 南京大学开源镜像站。该镜像站同步了官方的 PyTorch CPU / GPU（各 CUDA 版本）whl 文件，速度和稳定性都比较好。

使用方法很简单：
将官方安装命令中的

`https://download.pytorch.org/whl/`


替换为

`https://mirrors.nju.edu.cn/pytorch/whl/`


例如，安装 CUDA 12.6 版本的 PyTorch：

```
pip install torch torchvision torchaudio \
  --index-url https://mirrors.nju.edu.cn/pytorch/whl/cu126
```


在国内网络环境下，该方式通常可以顺利安装 GPU 版 PyTorch。

**Comment by shenpengfii** [comment]
For anyone who got this, it's a kindly auto-reply for your message: HAVE A GOOD DAY!
