### ISSUE TITLE
[镜像请求] 404 NOT FOUND https://mirrors.tuna.tsinghua.edu.cn/centos/8.5.2111/isos/x86_64/

### ISSUE THREAD

**Issue by workingMan-li** [tuna/issues#1693]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

下载镜像提示404  ngix代理失败

### 上游地址与镜像方法 (How to mirror)

http://isoredirect.centos.org/centos/8/isos/x86_64/

### 镜像大小 (Mirror size)

位置

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
centos 8 已经 EOL，官方的该 isoredirect 服务也应该 EOL，您可以向上游反馈该信息。

您如果要获取 centos8，可以前往 [centos-vault](https://mirrors.tuna.tsinghua.edu.cn/centos-vault/8.5.2111/isos/x86_64/)；centos-vault 并非官方服务，不在 isoredirect 的覆盖范围内。

您也可以使用 centos-stream，这时的 isoredirect 链接应该为 <http://isoredirect.centos.org/centos/8-stream/isos/x86_64/>，对应到 TUNA 的链接为 <https://mirrors.tuna.tsinghua.edu.cn/centos/8-stream/isos/x86_64/>，而这是工作的。
