### ISSUE TITLE
llvm ubuntu 22.04 GPG key 无法验证

### ISSUE THREAD

**Issue by ShenQingchuan** [tuna/issues#1694]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法正常执行 官方指导上给的 LLVM 安装自动脚本
执行日志如下：
sudo ./llvm.sh 15 -m https://mirrors.tuna.tsinghua.edu.cn/llvm-apt
+ CURRENT_LLVM_STABLE=15
+ BASE_URL=http://apt.llvm.org
+ needed_binaries=(lsb_release wget add-apt-repository gpg)
+ missing_binaries=()
+ for binary in "${needed_binaries[@]}"
+ which lsb_release
+ for binary in "${needed_binaries[@]}"
+ which wget
+ for binary in "${needed_binaries[@]}"
+ which add-apt-repository
+ for binary in "${needed_binaries[@]}"
+ which gpg
+ [[ 0 -gt 0 ]]
+ LLVM_VERSION=15
+ ALL=0
++ lsb_release -is
+ DISTRO=Ubuntu
++ lsb_release -sr
+ VERSION=22.04
+ UBUNTU_CODENAME=
+ CODENAME_FROM_ARGUMENTS=
+ source /etc/os-release
++ PRETTY_NAME='Ubuntu 22.04.2 LTS'
++ NAME=Ubuntu
++ VERSION_ID=22.04
++ VERSION='22.04.2 LTS (Jammy Jellyfish)'
++ VERSION_CODENAME=jammy
++ ID=ubuntu
++ ID_LIKE=debian
++ HOME_URL=https://www.ubuntu.com/
++ SUPPORT_URL=https://help.ubuntu.com/
++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
++ UBUNTU_CODENAME=jammy
+ DISTRO=ubuntu
+ case ${DISTRO} in
+ [[ -n jammy ]]
+ CODENAME=jammy
+ [[ -n jammy ]]
+ LINKNAME=-jammy
+ '[' 3 -ge 1 ']'
+ '[' 1 '!=' - ']'
+ '[' 15 '!=' all ']'
+ LLVM_VERSION=15
+ OPTIND=2
+ '[' 3 -ge 2 ']'
+ '[' -m == all ']'
+ getopts :hm:n: arg
+ case $arg in
+ BASE_URL=https://mirrors.tuna.tsinghua.edu.cn/llvm-apt
+ getopts :hm:n: arg
+ [[ 0 -ne 0 ]]
+ declare -A LLVM_VERSION_PATTERNS
+ LLVM_VERSION_PATTERNS[9]=-9
+ LLVM_VERSION_PATTERNS[10]=-10
+ LLVM_VERSION_PATTERNS[11]=-11
+ LLVM_VERSION_PATTERNS[12]=-12
+ LLVM_VERSION_PATTERNS[13]=-13
+ LLVM_VERSION_PATTERNS[14]=-14
+ LLVM_VERSION_PATTERNS[15]=-15
+ LLVM_VERSION_PATTERNS[16]=-16
+ LLVM_VERSION_PATTERNS[17]=
+ '[' '!' _ ']'
+ LLVM_VERSION_STRING=-15
+ [[ -n jammy ]]
+ REPO_NAME='deb https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/  llvm-toolchain-jammy-15 main'
+ wget -q --method=HEAD https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy
+ [[ ! -f /etc/apt/trusted.gpg.d/apt.llvm.org.asc ]]
++ apt-key list
++ grep -i llvm
+ [[ -z '' ]]
+ apt-key del AF4F7421
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
+ add-apt-repository 'deb https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/  llvm-toolchain-jammy-15 main'
源： 'deb https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/ llvm-toolchain-jammy-15 main'
描述：
Archive for codename: llvm-toolchain-jammy-15 components: main
更多信息：https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/
正在添加源。
按 [ENTER] 继续，或按 Ctrl-c 取消。
Found existing deb entry in /etc/apt/sources.list.d/archive_uri-https_mirrors_tuna_tsinghua_edu_cn_llvm-apt_jammy_-jammy.list
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_mirrors_tuna_tsinghua_edu_cn_llvm-apt_jammy_-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/archive_uri-https_mirrors_tuna_tsinghua_edu_cn_llvm-apt_jammy_-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_mirrors_tuna_tsinghua_edu_cn_llvm-apt_jammy_-jammy.list
命中:1 https://repo.steampowered.com/steam stable InRelease
命中:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy InRelease                                   
命中:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-updates InRelease                           
命中:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-backports InRelease                         
命中:5 http://security.ubuntu.com/ubuntu jammy-security InRelease                                    
命中:6 https://ppa.launchpadcontent.net/linuxuprising/apps/ubuntu jammy InRelease                    
获取:7 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease [6,833 B]
错误:7 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease  
  由于没有公钥，无法验证下列签名： NO_PUBKEY 15CF4D18AF4F7421
命中:8 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu jammy InRelease
正在读取软件包列表... 完成
W: GPG 错误：https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 15CF4D18AF4F7421
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
+ apt-get update
命中:1 https://repo.steampowered.com/steam stable InRelease
命中:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy InRelease                                   
命中:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-updates InRelease                           
命中:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-backports InRelease                         
获取:5 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease [6,833 B]
命中:6 http://security.ubuntu.com/ubuntu jammy-security InRelease                                    
错误:5 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease
  由于没有公钥，无法验证下列签名： NO_PUBKEY 15CF4D18AF4F7421
命中:7 https://ppa.launchpadcontent.net/linuxuprising/apps/ubuntu jammy InRelease
命中:8 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu jammy InRelease
正在读取软件包列表... 完成                                 
W: GPG 错误：https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 15CF4D18AF4F7421
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

### 期望的现象（What you expected to happen）

能够正常完成 llvm 自动安装脚本 llvm.sh

### 如何重现此问题（How to reproduce it）

ubuntu 22.04 下执行 llvm.sh

### 操作系统（OS Version）

ubuntu 22.04 jammy

**Comment by ShenQingchuan** [comment]
我罗列 `/etc/apt/trusted.gpg.d/` 的结果是 

```
> ll /etc/apt/trusted.gpg.d/
总计 20K
-rw-r--r-- 1 root root    0  3月 15 23:42 apt.llvm.org.asc
-rw-r--r-- 1 root root 1.2K  3月 13 02:24 linuxuprising-ubuntu-apps.gpg
-rw-r--r-- 1 root root    0  3月 13 02:24 linuxuprising-ubuntu-apps.gpg~
-rw-r--r-- 1 root root 1.2K  3月 13 04:06 neovim-ppa-ubuntu-stable.gpg
-rw-r--r-- 1 root root    0  3月 13 04:06 neovim-ppa-ubuntu-stable.gpg~
-rw-r--r-- 1 root root 1.9K  7月 13  2022 steam.gpg
-rw-r--r-- 1 root root 2.8K  3月 27  2021 ubuntu-keyring-2012-cdimage.gpg
-rw-r--r-- 1 root root 1.7K  3月 27  2021 ubuntu-keyring-2018-archive.gpg


```

**Comment by ShenQingchuan** [comment]
> 手动启用
> 首先信任来自 https://apt.llvm.org/ 的 PGP 公钥：
>
> wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
> 新增 /etc/apt/sources.list.d/llvm-apt.list，内容为
> 
> 发行版： 
> Ubuntu 22.04 LTS
> LLVM 版本： 
> 15
> 启用源码镜像： 
> 否
> # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
> deb https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/ llvm-toolchain-jammy-15 main
> # deb-src https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/ llvm-toolchain-jammy-15 main

使用了手动安装后，

并且解决了 #1665 的问题后，得到以下报错

```
> sudo apt update; sudo apt upgrade -y
命中:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy InRelease
命中:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-updates InRelease                           
命中:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu jammy-backports InRelease                                                                              
获取:4 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15 InRelease [6,833 B]                                                    
获取:5 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy-15/main amd64 Packages [12.4 kB]                                          
命中:6 https://repo.steampowered.com/steam stable InRelease                                                                 
命中:7 http://security.ubuntu.com/ubuntu jammy-security InRelease                                    
命中:8 https://ppa.launchpadcontent.net/linuxuprising/apps/ubuntu jammy InRelease
命中:9 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu jammy InRelease
已下载 6,833 B，耗时 2秒 (3,500 B/s)                       
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
有 1 个软件包可以升级。请执行 ‘apt list --upgradable’ 来查看它们。
W: https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-jammy-15/InRelease: 密钥存储在过时的 trusted.gpg 密钥环中（/etc/apt/trusted.gpg），请参见 apt-key(8) 的 DEPRECATION 一节以了解详情。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
正在计算更新... 完成
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libimage-magick-perl imagemagick libavdevice58 ffmpeg libopenexr25
  libmagick++-6.q16-8 libpostproc55 libmagickcore-6.q16-6-extra libavcodec58
  libimage-magick-q16-perl libmagickwand-6.q16-6 libavutil56 imagemagick-6.q16
  libswscale5 libmagickcore-6.q16-6 libswresample3 imagemagick-6-common
  libavformat58 libavfilter7
Learn more about Ubuntu Pro at https://ubuntu.com/pro
下列软件包的版本将保持不变：
  libllvm15
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 1 个软件包未被升级。
```

**Comment by ZenithalHourlyRate** [comment]
> W: https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-jammy-15/InRelease: 密钥存储在过时的 trusted.gpg 密钥环中（/etc/apt/trusted.gpg），请参见 apt-key(8) 的 DEPRECATION 一节以了解详情。

这是 warning，您现在已可正常使用 llvm apt 源



> * [[ ! -f /etc/apt/trusted.gpg.d/apt.llvm.org.asc ]]
>   ++ apt-key list
>   ++ grep -i llvm
> 
> * [[ -z '' ]]
> 
> * apt-key del AF4F7421
>   Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
>   OK


> -rw-r--r-- 1 root root    0  3月 15 23:42 apt.llvm.org.asc

您在之前的安装脚本中并未正确安装公钥
