### ISSUE TITLE
LineageOS的chromium问题

### ISSUE THREAD

**Issue by liqideqq** [tuna/issues#1695]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用LineageOS的清华源拉库时候，看到了chromium显示远程拒绝，无法下载，再次更新，然后编译报错了，提示是缺少了webview.apk就中断,无法正常编译。

### 期望的现象（What you expected to happen）

希望修复这个问题，早点编译ROM。

### 如何重现此问题（How to reproduce it）

以前拉库并编译没问题，现在不行了，是chromium问题。

### 操作系统（OS Version）

lixun

### 浏览器（如果适用）（Browser version, if applicable）

火狐

### 其他环境（Other environments）

编译依赖环境

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by ZenithalHourlyRate** [comment]
@liqideqq 您好，请您附上报错信息以及相应命令

**Comment by liqideqq** [comment]
> @liqideqq 您好，请您附上报错信息以及相应命令
我在抓问题

**Comment by liqideqq** [comment]
> @liqideqq 您好，请您附上报错信息以及相应命令

LineageOS/android_external_chromium-webview远端意外挂断了

**Comment by liqideqq** [comment]
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86_64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64

**Comment by liqideqq** [comment]
> @liqideqq 您好，请您附上报错信息以及相应命令
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86_64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64

**Comment by liqideqq** [comment]
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86
git-lfs filter-process --skip: 1: git-lfs: not found
fatal: 远端意外挂断了
error.GitError: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64: Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86_64
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86_64

**Comment by liqideqq** [comment]
[ZenithalHourlyRate](https://github.com/ZenithalHourlyRate)这个怎么解决？

**Comment by ZenithalHourlyRate** [comment]
> git-lfs filter-process --skip: 1: git-lfs: not found

您需要在本地安装 git-lfs

**Comment by liqideqq** [comment]
> > git-lfs filter-process --skip: 1: git-lfs: 未找到
> 
> 您需要在本地安装 git-lfs

好的，我去安装吧

**Comment by liqideqq** [comment]
@ZenithalHourlyRate 我已经安装git-lfs，仍是这个问题，你试了吗？

**Comment by ZenithalHourlyRate** [comment]
> @ZenithalHourlyRate 我已经安装git-lfs，仍是这个问题，你试了吗？

您在命令行中 `git-lfs` 是否有输出

**Comment by liqideqq** [comment]
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.3; git 77deabdf)
git lfs <command> [<args>]

Git LFS is a system for managing and versioning large files in
association with a Git repository. Instead of storing the large files
within the Git repository as blobs, Git LFS stores special "pointer
files" in the repository, while storing the actual file contents on a
Git LFS server. The contents of the large file are downloaded
automatically when needed, for example when a Git branch containing the
large file is checked out.

Git LFS works by using a "smudge" filter to look up the large file
contents based on the pointer file, and a "clean" filter to create a new
version of the pointer file when the large file's contents change. It
also uses a pre-push hook to upload the large file contents to the Git
LFS server whenever a commit containing a new large file version is
about to be pushed to the corresponding Git server.

Commands
--------

**Comment by liqideqq** [comment]
是，看起来已经输出了，重新拉库，谢谢您~

**Comment by kanadeblisst00** [comment]
@liqideqq 解决了吗，我在同步Lineageos19.1的时候，也是这个问题:
```
error: Unable to fully sync the tree
error: Checking out local projects failed.
Failing repos:
external/chromium-webview/prebuilt/arm
external/chromium-webview/prebuilt/arm64
external/chromium-webview/prebuilt/x86
external/chromium-webview/prebuilt/x86_64
Try re-running with "-j1 --fail-fast" to exit at the first error.
================================================================================
Repo command failed due to the following `SyncError` errors:
Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm
Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_arm64
Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86
Cannot initialize work tree for LineageOS/android_external_chromium-webview_prebuilt_x86_64
```

继续`repo sync`显示成功，但是编译时说缺少webview
