### ISSUE TITLE
LineageOS的webview编译问题

### ISSUE THREAD

**Issue by liqideqq** [tuna/issues#1696]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

FAILED: Verifying uses-libraries: external/chromium-webview/prebuilt/arm64/webview.apk
Outputs: out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status
Error: exited with code: 1
Command: /bin/bash -c "(rm -f out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  external/chromium-webview/prebuilt/arm64/webview.apk )"
Output:
zipro W 03-18 08:22:10 595921 595921] Error opening archive external/chromium-webview/prebuilt/arm64/webview.apk: Invalid file
ERROR: dump failed because no AndroidManifest.xml found
[1;31merror:[0m Command '['out/host/linux-x86/bin/aapt', 'dump', 'badging', 'external/chromium-webview/prebuilt/arm64/webview.apk']' returned non-zero exit status 1

### 期望的现象（What you expected to happen）

希望这个问题早点解决，先谢谢您指导，辛苦了~

### 如何重现此问题（How to reproduce it）

拉库是完整文件，开始编译，过程都没问题，到了62%时候，开始编译webview.apk，一会就中断了，怎么处理？

### 操作系统（OS Version）

Linux Mint 21.1 Cinnamon

### 浏览器（如果适用）（Browser version, if applicable）

火狐

### 其他环境（Other environments）

编译依赖环境

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by liqideqq** [comment]
还有bash: ./development/tools/make_key: No such file or directory

**Comment by ZenithalHourlyRate** [comment]
您可以参考

https://stackoverflow.com/questions/16590629/error-dump-failed-because-no-androidmanifest-xml-found

https://forums.unrealengine.com/t/no-androidmanifest-xml-found-what-can-i-do/251841

https://blog.csdn.net/BJ1599449/article/details/118074858

https://www.cnblogs.com/dinghanhua/p/16661824.html

**Comment by a645993095** [comment]
@ZenithalHourlyRate  并不是这个原因哦，我也是昨天遇到这个问题。在此之前，我已经正常编译几个月了，昨天重新repo后出现这个问题，18.1版本下  external/chromium-webview/prebuilt/arm64/webview.apk这个文件不存在，不知道为什么

**Comment by a645993095** [comment]
@ZenithalHourlyRate  并不是这个原因哦，我也是昨天遇到这个问题。在此之前，我已经正常编译几个月了，昨天重新repo后出现这个问题，18.1版本下  external/chromium-webview/prebuilt/arm64/webview.apk这个文件不存在，在atm和x86_64下也没有，只有x86文件夹下有，不知道为什么

**Comment by liqideqq** [comment]
> @ZenithalHourlyRate 并不是这个原因哦，我也是昨天遇到这个问题。在此之前，我已经经常编译几个月了，昨天重新repo后出现这个问题，18.1版下arm4/webpreview external/webpreview/webpreview6 apk这个文件不存在，在atm和x86_64下也没有，只有x86文件夹下面有，不知道为什么

我已经解决了，需要安装sudo apt-get install git git-lfs，再下载源码 repo sync -c，然后repo forall -c 'git lfs pull' ，可以愉快编译了。

**Comment by a645993095** [comment]
> > @ZenithalHourlyRate 并不是这个原因哦，我也是昨天遇到这个问题。在此之前，我已经经常编译几个月了，昨天重新repo后出现这个问题，18.1版下arm4/webpreview external/webpreview/webpreview6 apk这个文件不存在，在atm和x86_64下也没有，只有x86文件夹下面有，不知道为什么
> 
> 我已经解决了，需要安装sudo apt-get install git git-lfs，再下载源码 repo sync -c，然后repo forall -c 'git lfs pull' ，可以愉快编译了。

@liqideqq  我从头操作了一遍，并且也按照你的方法来同步，但在external/chromium-webview/prebuilt/arm64/下依然没有webview.apk这个文件，编译还是报错提示缺少这个文件。 你的这个目录下有这个apk吗？

**Comment by liqideqq** [comment]
> > > @ZenithalHourlyRate 并不是这个原因哦，我也是昨天遇到这个问题。在此之前，我已经经常编译几个月了，昨天重新repo后出现这个问题，18.1版下arm4/webpreview external/webpreview/webpreview6 apk这个文件不存在，在atm和x86_64下也没有，只有x86文件夹下面有，不知道为什么
> > 
> > 
> > 我已经解决了，需要安装sudo apt-get install git git-lfs，再下载源码 repo sync -c，然后repo forall -c 'git lfs pull' ，可以愉快编译了。
> 
> @liqideqq 我从头操作了一遍，并且也按照你的方法来同步，但在external/chromium-webview/prebuilt/arm64/下依然没有webview.apk这个文件，编译还是报错提示缺少这个文件。 你的这个目录下有这个apk吗？

我用了repo forall -c 'git lfs pull' ，看了webview.apk是完整。

**Comment by wjwABCDEFG** [comment]
lineageos 20.0，奇怪的是我检查了external/chromium-webview/prebuilt/arm64/webview.apk文件是存在的，但仍然报这个错误

**Comment by Kfkcome** [comment]
> lineageos 20.0，奇怪的是我检查了external/chromium-webview/prebuilt/arm64/webview.apk文件是存在的，但仍然报这个错误

我也是，是不是最近的产生的问题啊

**Comment by wjwABCDEFG** [comment]
> > lineageos 20.0，奇怪的是我检查了external/chromium-webview/prebuilt/arm64/webview.apk文件是存在的，但仍然报这个错误
> 
> 我也是，是不是最近的产生的问题啊
[liqideqq](https://github.com/liqideqq)提供的方法是有效的，先repo sync -c，然后repo forall -c 'git lfs pull'，不报这个错了，报其他错doge

**Comment by Kfkcome** [comment]
> > > lineageos 20.0，奇怪的是我检查了external/chromium-webview/prebuilt/arm64/webview.apk文件是存在的，但仍然报这个错误
> > 
> > 
> > 我也是，是不是最近的产生的问题啊
> > [liqideqq](https://github.com/liqideqq)提供的方法是有效的，先repo sync -c，然后repo forall -c 'git lfs pull'，不报这个错了，报其他错doge

我不报错了，但是不开机

**Comment by wjwABCDEFG** [comment]
> > > > lineageos 20.0，奇怪的是我检查了external/chromium-webview/prebuilt/arm64/webview.apk文件是存在的，但仍然报这个错误
> > > 
> > > 
> > > 我也是，是不是最近的产生的问题啊
> > > [liqideqq](https://github.com/liqideqq)提供的方法是有效的，先repo sync -c，然后repo forall -c 'git lfs pull'，不报这个错了，报其他错doge
> 
> 我不报错了，但是不开机

我解bl锁等一个星期后刷成功了,你是卡开机画面吗?

**Comment by Harry-Chen** [comment]
@wjwABCDEFG @Kfkcome 请不要在此讨论与 TUNA 镜像站无关的问题
