### ISSUE TITLE
DNS666增加doh查询方式

### ISSUE THREAD

**Issue by wzwtt** [tuna/issues#1697]
DNS666的明文查询方式传输过程不安全，而且目前明文版DNS666的IPv4服务器无法为教育网以外的用户服务。
是否有为DNS666增加doh查询方式的计划？

**Comment by Harry-Chen** [comment]
> DNS666的明文查询方式传输过程不安全

您可以启用 DNSSEC 验证。

> 而且目前明文版DNS666的IPv4服务器无法为教育网以外的用户服务。

请参考 <https://tuna.moe/help/dns-license/>：

TUNA DNS666 服务位于清华校内，服务质量不向校外用户提供保证，目的不包含为非清华师生进行服务。在任何时刻，TUNA 有权在不进行任何通知的情况下，暂停或终止对来自校外的请求的响应。包括校内用户在内，由于服务暂停或停止而导致的所有直接或间接损失，均由使用者自行承担。

**Comment by wzwtt** [comment]
是否有增加doh查询方式的计划？

**Comment by FHYQ-Dong** [comment]
> 是否有增加doh查询方式的计划？

同问
