### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/anaconda/hcc 404报错

### ISSUE THREAD

**Issue by BernieeeX** [tuna/issues#1698]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

安装环境时 hcc报错

### 期望的现象（What you expected to happen）

希望可以安装

### 如何重现此问题（How to reproduce it）

wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
chmod 777 Miniconda3-py37_4.8.3-Linux-x86_64.sh
./Miniconda3-py37_4.8.3-Linux-x86_64.sh

tar -xvzf nanom6A_2022_12_23.tar.gz
cd nanom6A_2022_12_23
conda env create -f conda.yml #install conda environment

### 操作系统（OS Version）

Linux

**Comment by ZenithalHourlyRate** [comment]
请您提供具体的报错信息
