### ISSUE TITLE
HTTPS 证书错误

### ISSUE THREAD

**Issue by swinglinux** [tuna/issues#17]
证书给出的是*.tuna.tsinghua.edu.cn，不能匹配mirrors.6.tuna.tsinghua.edu.cn
可以考虑加一个域名mirrors6.tuna.tsinghua.edu.cn

**Comment by huiyiqun** [comment]
confirmed with android.

**Comment by bigeagle** [comment]
已加上 https://mirrors6.tuna.tsinghua.edu.cn/ 和 https://mirrors4.tuna.tsinghua.edu.cn/

**Comment by swinglinux** [comment]
Thanks.
