### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/libpng-1.6

### ISSUE THREAD

**Issue by nidiy** [tuna/issues#1700]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

opencascade 

### 上游地址与镜像方法 (How to mirror)

opencascade  

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
```
$ ls *libpng-1.6*
libpng-1.6.39.arm64_big_sur.bottle.1.tar.gz   libpng-1.6.39.arm64_ventura.bottle.1.tar.gz  libpng-1.6.39.monterey.bottle.1.tar.gz  libpng-1.6.39.x86_64_linux.bottle.1.tar.gz
libpng-1.6.39.arm64_monterey.bottle.1.tar.gz  libpng-1.6.39.big_sur.bottle.1.tar.gz        libpng-1.6.39.ventura.bottle.1.tar.gz
```

您好，镜像站上存在相关文件。请您在安装相关软件前先执行 `brew update`

**Comment by nidiy** [comment]
非常谢谢！
