### ISSUE TITLE
[pypi]anyforce lib missing versions

### ISSUE THREAD

**Issue by exherb** [tuna/issues#1701]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[anyforce](https://pypi.org/project/anyforce/0.21.3/) 这个库昨天发布了两个版本 anyforce-0.21.2、anyforce-0.21.3，可以在 https://pypi.org/simple/anyforce/ 找到，但是在 https://pypi.tuna.tsinghua.edu.cn/simple/anyforce/ 找不到这两个版本

<img width="334" alt="image" src="https://user-images.githubusercontent.com/65154/226774644-9c0d4cf2-8ebe-41d0-a7de-2a17bc199fed.png">

### 期望的现象（What you expected to happen）

期望 https://pypi.tuna.tsinghua.edu.cn/simple/anyforce/ 能找到这两个版本

### 如何重现此问题（How to reproduce it）

`pip install anyforce==0.21.3 -i https://pypi.tuna.tsinghua.edu.cn/simple`

### 操作系统（OS Version）

macOS

**Comment by aldlss** [comment]
同，我在升级其他包的时候遇到了类似的问题

**Comment by ZenithalHourlyRate** [comment]
这是上游的问题，在上游修复之前我们无法修复该问题。

具体来说，由于 pypi CDN 服务了部分 repo 的旧内容，导致我们部署的 pypi 同步工具 bandersnatch 在同步到某一项目时出错，从而导致整个同步的中止与失败。

https://github.com/pypi/warehouse/issues/12214#issuecomment-1476371282

**Comment by exherb** [comment]
非常感谢, 那我先关闭了

**Comment by jiegec** [comment]
已经同步。
