### ISSUE TITLE
LineageOS 镜像中 `android_frameworks_base` 库出现问题

### ISSUE THREAD

**Issue by Molyuu** [tuna/issues#1702]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我尝试使用 TUNA 提供的 LineageOS 源同步 LineageOS 源码，根据使用帮助中的步骤修改 `manifest` 后使用 `env REPO_TRACE=1 repo sync -j16 --no-clone-bundle -v` 命令同步源代码，在最后同步 `android_frameworks_base` 时出现了如下的报错：

```
error: RPC failed; curl 18 HTTP/2 stream 5 was not closed cleanly before end of the underlying connection
fetch-pack: unexpected disconnect while reading sideband packet
fatal: protocol error: bad pack header
error: Cannot fetch LineageOS/android_frameworks_base from https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_frameworks_base
Fetching: 100% (1/1), done in 3m36.141s
Checking out: 20% (251/1235) platform/external/google-java-formaterror: Cannot checkout LineageOS/android_frameworks_base: ManifestInvalidRevisionError: revision refs/heads/lineage-20.0 in LineageOS/android_frameworks_base not found
Checking out:  44% (544/1235), done in 30.461s
error: in `sync -j16 --no-clone-bundle -v`: revision refs/heads/lineage-20.0 in LineageOS/android_frameworks_base not found
```

### 期望的现象（What you expected to happen）

希望源码能够正常同步

### 如何重现此问题（How to reproduce it）

经测试，能稳定复现

### 操作系统（OS Version）

Arch Linux

### 其他需要说明的事项（Anything else we need to know）

尝试单独 clone 此 repo 时(`git clone https://mirrors.bfsu.edu.cn/git/lineageOS/LineageOS/android_frameworks_base -b lineage-20.0`，一切正常)

**Comment by shankerwangmiao** [comment]
应该是在 fetch 过程中连接断开导致的。重新再从 TUNA 试一次是否可以复现？

**Comment by Molyuu** [comment]
> 应该是在 fetch 过程中连接断开导致的。重新再从 TUNA 试一次是否可以复现？

尝试使用 `-j4` 同步后能正常 fetch 了，感谢！
