### ISSUE TITLE
pypi源缺少gradio==3.23

### ISSUE THREAD

**Issue by ahdiua** [tuna/issues#1704]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

stable-diffusion-webui 需要 gradio==3.23，目前发现阿里云和清华源都没有，但是服务器状态都是4分钟前同步。

https://pypi.org/search/?q=gradio 21号就发布了3.23.0，不知为何没同步过来。

### 期望的现象（What you expected to happen）

成功安装

### 如何重现此问题（How to reproduce it）

pip install gradio==3.23

### 操作系统（OS Version）

ubuntu jammy

**Comment by ZenithalHourlyRate** [comment]
@ahdiua 您可以参考 #1701

**Comment by ahdiua** [comment]
> @ahdiua 您可以参考 #1701

抱歉，没仔细看 https://github.com/tuna/issues/issues/1701 。原来是pypi的锅，issue重复了我先关了

**Comment by tianmo373** [comment]
pip install gradio==3.23 -i https://pypi.org/simple/

**Comment by jiegec** [comment]
已经修复。
