### ISSUE TITLE
pypi未同步最新的ppdiffusers库

### ISSUE THREAD

**Issue by JunnYu** [tuna/issues#1706]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

嗨，请问一下我发现 https://pypi.tuna.tsinghua.edu.cn/simple/ppdiffusers/ 这里未及时同步 https://pypi.org/simple/ppdiffusers/ 中的 0.14.0 版本的包，请问会是什么问题呢？是不是是我们这里发包不太规范导致的呢？还有请问有什么解决办法吗？（我这里已经发布了有10多个小时了呢）
![image](https://user-images.githubusercontent.com/50394665/229006711-37d66497-b3f0-477b-b75a-e13cc6428837.png)
![image](https://user-images.githubusercontent.com/50394665/229006747-d9d57f55-d2b2-4ee0-8148-dd6a5716bbf2.png)
![image](https://user-images.githubusercontent.com/50394665/229006680-186c6b91-f832-4669-9783-d27d6dffafec.png)

### 期望的现象（What you expected to happen）

正确同步最新的库

### 如何重现此问题（How to reproduce it）

如图所示

**Comment by ZenithalHourlyRate** [comment]
@JunnYu 参考 #1701

**Comment by JunnYu** [comment]
@ZenithalHourlyRate 好的，谢谢！

**Comment by jiegec** [comment]
已经修复。
