### ISSUE TITLE
voidlinux镜像问题

### ISSUE THREAD

**Issue by zero2076** [tuna/issues#1709]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Void Linux 软件仓库镜像使用帮助中命令错误

### 期望的现象（What you expected to happen）

更换镜像成功

### 如何重现此问题（How to reproduce it）

void-live-x86_64-20221001-base中试着更换镜像

### 操作系统（OS Version）

void-live-x86_64-20221001-base

### 其他需要说明的事项（Anything else we need to know）

mkdir -p /etc/xbps.d
cp /usr/share/xbps.d/00-repository-main.conf /etc/xbps.d/
sed -i 's|https://repo-default.voidlinux.org|https://mirrors.tuna.tsinghua.edu.cn/voidlinux/current|g' /etc/xbps.d/00-repository-main.conf
经测试可用

**Comment by ZenithalHourlyRate** [comment]
> /usr/share/xbps.d/00-repository-main.conf

能看看原始文件吗，我看官方手册中并未说明要加上 `/current` ?

**Comment by ZenithalHourlyRate** [comment]
注意到 https://mirrors.tuna.tsinghua.edu.cn/voidlinux/current/current/ 是不可访问的

**Comment by zero2076** [comment]
repository=https://repo-default.voidlinux.org/current
应该是这个

2023年4月5日 下午4:04:11 Hongren (Zenithal) Zheng ***@***.***>:

**Comment by zero2076** [comment]
了解了，不好意思

2023年4月5日 下午4:12:56 Hongren (Zenithal) Zheng ***@***.***>:
