### ISSUE TITLE
Pypi镜像中 Django 4.2 正式版未及时同步

### ISSUE THREAD

**Issue by exidot** [tuna/issues#1710]
非常感谢提供的镜像，一直在使用清华源的 Pypi 镜像。但最近有以下的问题

Django 4.2 正式版已经发布3天了，pypi.org 中很早就有 django 4.2, 去看了清华源的pypi同步状态, 已经显示同步成功, 但没有 django 4.2, 是否可以查看一下是什么原因导致了 django 4.2 同步失败呀?

非常感谢！

**Comment by ZenithalHourlyRate** [comment]
@exidot #1701

**Comment by exidot** [comment]
> @exidot #1701

感谢！看着只有等待上游修复了

**Comment by jiegec** [comment]
已经修复。
