### ISSUE TITLE
北京外国语大学NetBSD软件包地址404

### ISSUE THREAD

**Issue by lbp0200** [tuna/issues#1711]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

根据北外的文档 https://mirrors.bfsu.edu.cn/help/netbsd/
修改了软件包配置文件，发现路径是404

https://mirrors.bfsu.edu.cn/pkgsrc/packages/NetBSD

### 期望的现象（What you expected to happen）

正常访问

### 如何重现此问题（How to reproduce it）

访问 https://mirrors.bfsu.edu.cn/pkgsrc/packages/NetBSD

### 操作系统（OS Version）

NETBSD

**Comment by ZenithalHourlyRate** [comment]
该帮助在书写时参考的是 TUNA 的镜像情况，未考虑到 BFSU 不存在 pkgsrc 镜像。

在之后的改动中会将 pkgsrc 部分重定向到 https://help.mirrors.cernet.edu.cn/pkgsrc/
