### ISSUE TITLE
[镜像请求] homebrew-services

### ISSUE THREAD

**Issue by qianbinbin** [tuna/issues#1712]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

最近发现 brew 不知何故自动拉取了 [homebrew-services](https://github.com/Homebrew/homebrew-services) 这个仓库，建议添加到镜像

我看到交大是有的：https://mirror.sjtu.edu.cn/git/homebrew-services.git

### 上游地址与镜像方法 (How to mirror)

https://github.com/Homebrew/homebrew-services

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
同步中。

你可以为 https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/ 写相关的镜像帮助吗。

**Comment by qianbinbin** [comment]
谢谢哈，没想到效率这么高
我试试，应该和其它 tap 仓库类似的吧

**Comment by qianbinbin** [comment]
我这没有搭建 web 环境，你看这么写可以吗 https://github.com/tuna/mirror-web/pull/360

**Comment by ZenithalHourlyRate** [comment]
可以，你本地测试过换源吗

**Comment by qianbinbin** [comment]
试了，已经可以正常拉取了
