### ISSUE TITLE
yum -y install amavisd-new 404

### ISSUE THREAD

**Issue by 1804909625** [tuna/issues#1713]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Loaded plugins: langpacks
base-openlogic                                                                      | 3.1 kB  00:00:00     
extras-openlogic                                                                    | 2.5 kB  00:00:00     
updates-openlogic                                                                   | 2.6 kB  00:00:00     
base                                                                                | 3.6 kB  00:00:00     
epel                                                                                | 4.7 kB  00:00:00     
extras                                                                              | 2.9 kB  00:00:00     
openlogic                                                                           | 2.9 kB  00:00:00     
updates                                                                             | 2.9 kB  00:00:00     
epel/x86_64/primary_db         FAILED                                          
https://mirrors.bfsu.edu.cn/epel/7/x86_64/repodata/a30d98eba3713f2c7905fc1d864d00293c889e68ea6a955b72c017e7a8575d9d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

epel/x86_64/updateinfo         FAILED                                          
https://mirrors.bfsu.edu.cn/epel/7/x86_64/repodata/7eb14f0319a9137916919a5fdc4056c9c2d23d88c0d441acfae25628ec29f2c3-updateinfo.xml.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
epel/x86_64/primary_db         FAILED                                          
https://mirrors.bfsu.edu.cn/epel/7/x86_64/repodata/a30d98eba3713f2c7905fc1d864d00293c889e68ea6a955b72c017e7a8575d9d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirrors.bfsu.edu.cn/epel/7/x86_64/repodata/a30d98eba3713f2c7905fc1d864d00293c889e68ea6a955b72c017e7a8575d9d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Extra Packages for Enterprise Linux 7 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=epel ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable epel
        or
            subscription-manager repos --disable=epel

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=epel.skip_if_unavailable=true

failure: repodata/a30d98eba3713f2c7905fc1d864d00293c889e68ea6a955b72c017e7a8575d9d-primary.sqlite.bz2 from epel: [Errno 256] No more mirrors to try.
https://mirrors.bfsu.edu.cn/epel/7/x86_64/repodata/a30d98eba3713f2c7905fc1d864d00293c889e68ea6a955b72c017e7a8575d9d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found

### 期望的现象（What you expected to happen）

installation

### 如何重现此问题（How to reproduce it）

Please try running
yum -y install amavisd-new

### 操作系统（OS Version）

Centos 7.9

### 其他需要说明的事项（Anything else we need to know）

My complete shell statement is：
yum -y install amavisd-new clamav-server clamav-server-systemd

**Comment by ZenithalHourlyRate** [comment]
今天 BFSU 到上游的网络连接问题较多，多次出现
```
rsync: [receiver] read error: Connection timed out (110)
```
建议您切换到其他镜像站缓解该问题
