### ISSUE TITLE
下载crate时发生超时与其它错误

### ISSUE THREAD

**Issue by andyzysjtu** [tuna/issues#1714]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![企业微信截图_16811828293833](https://user-images.githubusercontent.com/20332952/231047329-e3f31cdf-54e7-444e-9d1e-82e5d2e93851.png)

### 期望的现象（What you expected to happen）

能够正常下载crate。

### 如何重现此问题（How to reproduce it）

并不是一直发生的，但是每次发生后短时间内会重复出现。

### 操作系统（OS Version）

Debian GNU/Linux 11

**Comment by ZenithalHourlyRate** [comment]
> 能够正常下载crate。

您好，我们只镜像了 crates 的索引，具体 crates 还是要访问 crates.io，这可能与您的网络环境有关

**Comment by andyzysjtu** [comment]
> > 能够正常下载crate。
> 
> 您好，我们只镜像了 crates 的索引，具体 crates 还是要访问 crates.io，这可能与您的网络环境有关

谢谢，那我这边在本地观察观察。
