### ISSUE TITLE
python包matpplotlib疑似包含恶意代码

### ISSUE THREAD

**Issue by fxr1993** [tuna/issues#1721]
https://pypi.tuna.tsinghua.edu.cn/simple/matpplotlib/matpplotlib-0.1.tar.gz
似乎是伪装成matplotlib的包（名称里多了一个字母p），实际上包含的内容只有一个setup.py，根据参考博客分析，会自动安装浏览器插件，盗取加密货币。目前pypi上已经没有这个包了。
烦请调查，谢谢～

参考：https://medium.com/checkmarx-security/17-malicious-python-packages-targeting-selenium-users-to-steal-crypto-8d24628ec656

**Comment by ZenithalHourlyRate** [comment]
现已删除。
