### ISSUE TITLE
Conda 404

### ISSUE THREAD

**Issue by xgdgsc** [tuna/issues#173]
按 https://mirrors4.tuna.tsinghua.edu.cn/help/anaconda/ 的说明配置之后，`conda update --all` 报如下错误
```
>conda update --all
Fetching package metadata ..........
CondaHTTPError: HTTP 404 None
for url <None>

The remote server could not find the channel you requested.

You will need to adjust your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.
```

**Comment by huiyiqun** [comment]
用的是哪个版本的Anaconda？什么平台？

2016-12-11 10:42 GMT+08:00 xgdgsc <notifications@github.com>:

**Comment by xgdgsc** [comment]
应该是最新的吧，windows 10 64位，python 3.5.2的。因为升级anaconda的版本号变成了custom。

**Comment by huiyiqun** [comment]
这会儿手边没有windows，稍晚一点我找windows测试一下。

2016-12-11 11:25 GMT+08:00 xgdgsc <notifications@github.com>:

**Comment by xgdgsc** [comment]
Linux 64位下的没问题。

**Comment by xgdgsc** [comment]
我发现问题在于windows下运行这个命令会生成配置文件里面3引号包含的url，去掉多余的引号就可以了。或者文档里不加单引号也行。

**Comment by huiyiqun** [comment]
感谢反馈 我更新一下

**Comment by bigeagle** [comment]
@huiyiqun assign 给你？文档更新完 pia 我部署就好

**Comment by bigeagle** [comment]
@huiyiqun assign 给你？文档更新完 pia 我部署就好

**Comment by huiyiqun** [comment]
回家正准备写代码，发现已经更新了，一头晕。
