### ISSUE TITLE
希望能够为KODI开发一款可以切换插件库的插件

### ISSUE THREAD

**Issue by AkarinLiu** [tuna/issues#1731]
我用的是KODI安卓版，我更改插件库遇到了麻烦：就是在`Android/data/org.xbmc.kodi/files/addons/repository.xbmc.org/`下没有找到`addon.xml`文件，希望能够推出能够切换插件库的插件。

**Comment by ZenithalHourlyRate** [comment]
@AkarinLiu 您好，我们并没有 kodi 的开发者，您可以联系 kodi 官方或联系相关使用者开发相应插件
