### ISSUE TITLE
添加Adoptium源时出现问题

### ISSUE THREAD

**Issue by Keviince** [tuna/issues#1733]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照帮助页面：[https://mirrors.tuna.tsinghua.edu.cn/help/adoptium/](url) 的提示添加Adoptium源后。在`yum makecache`时出现以下错误：
> [root@Code ~]# yum makecache
Adoptium                                                                                          1.3 kB/s | 153  B     00:00    
Errors during downloading metadata for repository 'Adoptium':
Status code: 404 for http://mirrors.tuna.tsinghua.edu.cn/Adoptium/rpm/centos9-x86_64/repodata/repomd.xml (IP: 101.6.15.130)
Error: Failed to download metadata for repo 'Adoptium': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

点击链接发现为404页面，查询目录结构发现并没有centos9的选项，应为rhel9。

### 期望的现象（What you expected to happen）

在帮助页面中应写明Centos 7以上应用rhel代替链接中的centos。

### 如何重现此问题（How to reproduce it）

按照帮助页面：[https://mirrors.tuna.tsinghua.edu.cn/help/adoptium/](url) 的提示添加Adoptium源即可复现。

### 操作系统（OS Version）

CentOS Stream 9

**Comment by Harry-Chen** [comment]
如有需要，可暂时使用 `rhel9-x86_64`
