### ISSUE TITLE
conda 使用中conda-forege 报错

### ISSUE THREAD

**Issue by Yunjuanli** [tuna/issues#1734]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

最近在使用miniconda安装软件过程中总出现conda-forge channel is not accessible or is invalid的情况，上tuna的mirror查看相应的镜像，发现conda-forge点开后提示“内容过多”，其他镜像显示没有问题。
报错截图如下：

![image](https://user-images.githubusercontent.com/132866194/236726689-f19bb7b4-1a90-400c-9192-79980bb95d2b.png)

### 期望的现象（What you expected to happen）

请查看conda-forge的镜像文件是不是出现问题，如有问题，请及时修复。
感谢！

### 如何重现此问题（How to reproduce it）

请查看conda-forge的镜像文件是不是出现问题，如有问题，请及时修复。
感谢！

### 操作系统（OS Version）

7

**Comment by Yunjuanli** [comment]
PS：此错误在conda install 或conda update 时出现

**Comment by ZenithalHourlyRate** [comment]
@Yunjuanli 显示内容过多是正常现象

**Comment by Yunjuanli** [comment]
请问不能正常安装和更新软件的原因是什么?

**Comment by Yunjuanli** [comment]
基本已经尝试过各种方法，卸载重新安装miniconda、重新add所有channel、删除 .condarc文件中的default栏

**Comment by Yunjuanli** [comment]
基本已经尝试过各种方法，卸载重新安装miniconda、重新add所有channel、删除 .condarc文件中的default栏

**Comment by ZenithalHourlyRate** [comment]
@Yunjuanli 您好，您可以附上您的 .condarc，我猜测您的配置文件中出现了两次 tuna 的链接

**Comment by Yunjuanli** [comment]
![1683528024860](https://user-images.githubusercontent.com/132866194/236752624-2f01c4c5-72f7-4b69-ad1a-8ca5700311f4.png)
以上即是我的.condarc文件内容，劳烦您给看一下，多谢

**Comment by ZenithalHourlyRate** [comment]
@Yunjuanli 您好，请您参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 中的方式配置

**Comment by Yunjuanli** [comment]
感谢，可以用了。不过很好奇，我最初也是用您给的链接配置的，不能用才又走了弯路，无效操作一通。。。大概是那个没粘贴对。总之，感谢！
