### ISSUE TITLE
llvm-apt 镜像缺少 arm64

### ISSUE THREAD

**Issue by HuangShaoyan** [tuna/issues#1735]
https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/focal/ 缺少 arm64 的镜像。

官网目前已经提供，如：https://apt.llvm.org/focal/pool/main/l/llvm-toolchain-14/ 目录下，就能看到名称包含 arm64 的 .deb

镜像站能否也相应提供？

**Comment by ZenithalHourlyRate** [comment]
现已同步。
