### ISSUE TITLE
Linuxbrew 使用TUNA源安装时提示缺少bottle

### ISSUE THREAD

**Issue by iforgetmyname** [tuna/issues#1736]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在 Debian 11 上按[Homebrew / Linuxbrew 镜像使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/)安装 Linuxbrew 时，
提示缺失portable-ruby-2.6.10_1.x86_64_linux.bottle.tar.gz，
进[bottles](https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/)查看了一下确实没有这个bottle，
而且这个文件夹上次同步还在2022年6月。
之后Linuxbrew转从Github Packages下载并正常安装了，但是下载速度堪忧。

### 期望的现象（What you expected to happen）

Linuxbrew利用TUNA正常安装

### 如何重现此问题（How to reproduce it）

```bash
export HOMEBREW_INSTALL_FROM_API=1
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"

git clone --depth=1 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/install.git brew-install
/bin/bash brew-install/install.sh
```

输出：
```
###以上省略一段
HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git as the Homebrew/brew Git remote.
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/portable-ruby-2.6.10_1.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404

==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:68923daf3e139482b977c3deba63a3b54ea37bb5f716482948878819ef911bad
```

### 操作系统（OS Version）

Debian 11 bullseye

### 浏览器（如果适用）（Browser version, if applicable）

N/A

### 其他环境（Other environments）

N/A

### 其他需要说明的事项（Anything else we need to know）

只是题外话：有点好奇TUNA是怎么同步Github Packages的，Homebrew bottles现在应该全部host在ghcr上了

**Comment by ZenithalHourlyRate** [comment]
现已修复。

这个问题可以参考 #1668，由于安装脚本和 portable-ruby 并不是同时更新的，现在每次都需要手动干涉。

```
ln -sTf ../github-release/Homebrew/homebrew-portable-ruby/2.6.10_1 bottles-portable-ruby
```



> 有点好奇TUNA是怎么同步Github Packages的，Homebrew bottles现在应该全部host在ghcr上了

您可以参考 https://github.com/tuna/tunasync-scripts/blob/master/homebrew-bottles.py
