### ISSUE TITLE
[镜像请求] 新增 GitHub Release: Genymobile/scrcpy

### ISSUE THREAD

**Issue by HikariCalyx** [tuna/issues#1738]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Genymobile/scrcpy
This application mirrors Android devices (video and audio) connected via USB or over TCP/IP, and allows to control the device with the keyboard and the mouse of the computer. It does not require any root access. 
这款应用可以将打开了 adbd 调试端口的安卓设备的画面和音频投屏到电脑上并使用电脑的键盘鼠标进行操作，不需要为手机获取 root 权限。

此项目为 Apache 2.0 协议。

### 上游地址与镜像方法 (How to mirror)

https://github.com/Genymobile/scrcpy/releases/

### 镜像大小 (Mirror size)

20MB

### 备注 (Note)

此镜像为 **_github-release_** 镜像

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
根据官方文档，在 Windows、Linux、macOS 下均有多种包管理器可供安装，因此不再额外镜像。
