### ISSUE TITLE
[镜像请求] 请求新增Docker Registry镜像！

### ISSUE THREAD

**Issue by AkarinLiu** [tuna/issues#1739]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Docker Registry是在Docker Hub生态中一个重要的注册表

### 上游地址与镜像方法 (How to mirror)

反向代理
地址：https://index.docker.io/v1

### 备注 (Note)

Docker Hub最近无法拉取镜像，请求新增镜像以解决问题！

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/741

> 对于下列情况我们原则上不予镜像：
> 
> 11. 包含用户产生的内容（User-generated content） 
>   - 例如：任何 Docker 镜像 (https://github.com/tuna/issues/issues/948, https://github.com/tuna/issues/issues/1384)
