### ISSUE TITLE
考虑自动更新页面？

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#174]
现在更新网页内容(比如help和新闻)需要pia来pia去感觉很蛋疼，我感觉可以:

- [ ] 做个docker用来build页面，不然在rhel上装jekyll有点麻烦？
- [ ] 写个简单脚本跑git pull，发现更新就jekyll build一下。

**Comment by bigeagle** [comment]
蒽，这个 tuna.moe 就是这样做的，挺简单的。

**Comment by huiyiqun** [comment]
那就移植一下？

2016-12-11 23:13 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by huiyiqun** [comment]
Done
