### ISSUE TITLE
添加vcpkg的二进制包缓存

### ISSUE THREAD

**Issue by heheda123123** [tuna/issues#1740]
![image](https://github.com/tuna/issues/assets/97490782/9e83f5c3-2bea-406c-9835-dd119e3c93dc)

https://zhuanlan.zhihu.com/p/629267791?utm_medium=social&utm_oi=46207929942016&utm_psn=1641764534678552576&utm_source=qq
有没有可能编译最新的二进制包放到镜像源里，vcpkg的一大痛点就是都要本地编译

**Comment by ZenithalHourlyRate** [comment]
> 有没有可能编译最新的二进制包放到镜像源里

您好，镜像站原则上只提供静态文件服务，不提供编译服务。

**Comment by Harry-Chen** [comment]
此外，不按照格式提出的镜像请求将不会被接受。
