### ISSUE TITLE
[镜像请求] 希望能够镜像HeidiSQL

### ISSUE THREAD

**Issue by AkarinLiu** [tuna/issues#1741]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

HeidiSQL是一款用于简单化迷你的 [MySQL](https://baike.baidu.com/item/MySQL/471251?fromModule=lemma_inlink) 服务器和数据库管理的图形化界面。HeidiSQL提供了一个用于在[数据库浏览](https://baike.baidu.com/item/%E6%95%B0%E6%8D%AE%E5%BA%93%E6%B5%8F%E8%A7%88/56279903?fromModule=lemma_inlink)之间切换 SQL 查询和标签带有语法[突出显示](https://baike.baidu.com/item/%E7%AA%81%E5%87%BA%E6%98%BE%E7%A4%BA/7321494?fromModule=lemma_inlink)的简单易用的界面。其它功能包括BLOB 和 MEMO 编辑，大型SQL脚本支持，用户[进程管理](https://baike.baidu.com/item/%E8%BF%9B%E7%A8%8B%E7%AE%A1%E7%90%86/6627066?fromModule=lemma_inlink)等，该软件资源开放。
——来自百度百科

### 上游地址与镜像方法 (How to mirror)

https://github.com/HeidiSQL/HeidiSQL

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
观察到 GitHub 上只有代码，release 在软件官网发布，这样是无法镜像的。

**Comment by AkarinLiu** [comment]
这是它的下载地址：
https://www.heidisql.com/download.php?download=installer

**Comment by AkarinLiu** [comment]
@Harry-Chen 那就没办法了
