### ISSUE TITLE
[镜像请求] QuSpin 

### ISSUE THREAD

**Issue by Galileo-sun** [tuna/issues#1743]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

QuSpin is an open-source Python package for exact diagonalization and quantum dynamics of arbitrary boson, fermion and spin many-body systems. QuSpin supports the use of various (user-defined) symmetries for one and higher-dimensional lattice systems, (imaginary) time evolution following arbitrary user-specified driving protocols, and constrained Hilbert spaces.

### 上游地址与镜像方法 (How to mirror)

https://github.com/weinbe58/QuSpin/tree/master

### 镜像大小 (Mirror size)

<2.2MB

### 备注 (Note)

网站上有quspin-vqa等两个package，但没有这个。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
官方地址应该为 https://github.com/QuSpin/QuSpin

此外，官方已经提供了 conda / pypi 的安装方式，为何需要额外镜像？

**Comment by Galileo-sun** [comment]
因为研究组自己的集群无法连接外网，只能连接到清华镜像，所以只有清华镜像的包才能装到集群上～






------------------ 原始邮件 ------------------
发件人: Shengqi Chen ***@***.***&gt;
发送时间: 2023年5月29日 14:22
收件人: tuna/issues ***@***.***&gt;
抄送: Galileo-sun ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [tuna/issues] [镜像请求] QuSpin  (Issue #1743)





 
官方地址应该为 https://github.com/QuSpin/QuSpin
 
此外，官方已经提供了 conda / pypi 的安装方式，为何需要额外镜像？

**Comment by Harry-Chen** [comment]
> 因为研究组自己的集群无法连接外网，只能连接到清华镜像，所以只有清华镜像的包才能装到集群上～
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Shengqi Chen ***@***.***&gt; 发送时间: 2023年5月29日 14:22 收件人: tuna/issues ***@***.***&gt; 抄送: Galileo-sun ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [tuna/issues] [镜像请求] QuSpin (Issue #1743) 官方地址应该为 https://github.com/QuSpin/QuSpin 此外，官方已经提供了 conda / pypi 的安装方式，为何需要额外镜像？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以直接使用 TUNA 提供的 conda / pypi 镜像。

**Comment by Galileo-sun** [comment]
您好，我想请问一下为什么我看网站上jax和jaxlib的最新版本有0.4.11和0.4.9，但我安装的时候却显示最新的只能安装0.2.17和0.1.69呢？谢谢～






------------------ 原始邮件 ------------------
发件人: Shengqi Chen ***@***.***&gt;
发送时间: 2023年5月29日 16:36
收件人: tuna/issues ***@***.***&gt;
抄送: Galileo-sun ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [tuna/issues] [镜像请求] QuSpin  (Issue #1743)





  
因为研究组自己的集群无法连接外网，只能连接到清华镜像，所以只有清华镜像的包才能装到集群上～
 …
 ------------------ 原始邮件 ------------------ 发件人: Shengqi Chen @.&gt; 发送时间: 2023年5月29日 14:22 收件人: tuna/issues @.&gt; 抄送: Galileo-sun @.&gt;, Author @.&gt; 主题: Re: [tuna/issues] [镜像请求] QuSpin (Issue #1743) 官方地址应该为 https://github.com/QuSpin/QuSpin 此外，官方已经提供了 conda / pypi 的安装方式，为何需要额外镜像？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以直接使用 TUNA 提供的 conda / pypi 镜像。

**Comment by jiegec** [comment]
同步问题已经接近，请重试。
