### ISSUE TITLE
[镜像请求] 请求镜像Wireguard

### ISSUE THREAD

**Issue by AkarinLiu** [tuna/issues#1744]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

WireGuard是一个非常简单但快速和现代的VPN，它利用最先进的[加密技术](https://www.wireguard.com/protocol/)。它[的目标是比](https://www.wireguard.com/performance/)IPsec更快，[更简单](https://www.wireguard.com/quickstart/)，更精简，更有用，同时避免了头痛问题。它打算比OpenVPN的性能高得多。WireGuard被设计为一种通用VPN，用于在嵌入式接口和超级计算机上运行，适用于许多不同的情况。它最初是为Linux内核发布的，现在是跨平台的（Windows，macOS，BSD，iOS，Android）并且可以广泛部署。它目前正在大量开发中，但它已经被认为是业内最安全、最易于使用和最简单的 VPN 解决方案。®

### 上游地址与镜像方法 (How to mirror)

Windows系统：https://download.wireguard.com/windows-client/
Android系统：https://download.wireguard.com/android-client/

使用HTTP镜像

### 备注 (Note)

此项目为企业和个人VPN私有网络，用于登录公司或组织及家庭的内部网络，希望官方不要把它作为非法VPN处理。
同时希望官方能够发布免责声明。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by AkarinLiu** [comment]
@Harry-Chen 可以尝试手动镜像

**Comment by Lanius-collaris** [comment]
You can enable DNS over HTTPS on windows to download these clients.
