### ISSUE TITLE
metar包在bfsu pypi mirror中不是最新的

### ISSUE THREAD

**Issue by ghost** [tuna/issues#1747]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

metar已在3天前更新到[1.10.0](https://pypi.org/project/metar/1.10.0/)。[BFSU镜像](https://mirrors.bfsu.edu.cn/pypi/web/simple/metar/)的最后更新显示为2023-05-22 19:34，但metar包的版本仍停留在1.9.0。

### 期望的现象（What you expected to happen）

更新

### 如何重现此问题（How to reproduce it）

```
pip install -i https://pypi.org/simple metar==1.10.0 # Ok
pip install -i https://mirrors.bfsu.edu.cn/pypi/web/simple metar==1.10.0 # Error
```

### 操作系统（OS Version）

Ubuntu 22.04

### 其他环境（Other environments）

Python 3.10 + pip 23.1.2

### 其他需要说明的事项（Anything else we need to know）

tuna pypi mirror也一样。

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1701#issuecomment-1483821881

**Comment by gamecss** [comment]
那有什么办法可以缓解吗？比如说手动同步什么的

**Comment by gamecss** [comment]
开放一个网页允许用户手动同步，像npmmirror那样？

**Comment by ZenithalHourlyRate** [comment]
原则上镜像站只开放静态文件服务，不开放 API
