### ISSUE TITLE
macOS下载latexindent时perl的路径不能正确展开

### ISSUE THREAD

**Issue by ChenZhongPu** [tuna/issues#1749]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用镜像安装`latexindent`，

```sh
brew install latexindent
```
它会同时下载依赖perl。`/opt/homebrew/Cellar/latexindent/3.21.1/libexec/bin/latexindent.pl`文件第一行没有被正确展开：

> #!/usr/bin/perl

使用的时候，会报错**SystemDirectory.c: loadable library and perl binaries are mismatched**。

如果不使用镜像，第一行能够被正确展开成"#!/opt/homebrew/opt/perl/bin/perl"。相关讨论参考[latexindent issue#91974](https://github.com/Homebrew/homebrew-core/issues/91974)。

### 期望的现象（What you expected to happen）

安装的latexindent.pl文件的第一行能正确展开成`#!/opt/homebrew/opt/perl/bin/perl`。

运行latexindent命令不报错。

### 如何重现此问题（How to reproduce it）

```sh
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
brew install latexindent
```

### 操作系统（OS Version）

macOS

**Comment by taoky** [comment]
https://github.com/ustclug/discussions/issues/382

**Comment by ZenithalHourlyRate** [comment]
将主要在 ustc 侧讨论
