### ISSUE TITLE
将lmde下载链接放到获取安装镜像选项卡中

### ISSUE THREAD

**Issue by dabao1955** [tuna/issues#1754]
rt
![捕获](https://github.com/tuna/issues/assets/79307765/9b3002bc-719a-4509-9fd3-940542b86d95)
在linux mint中无法下载lmde，只能手动进入目录下载

**Comment by Harry-Chen** [comment]
您可以修改 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 并提出 PR。
