### ISSUE TITLE
没有 qt5.12.6的离线安装包

### ISSUE THREAD

**Issue by starfoxxin** [tuna/issues#1756]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

没有 qt5.12.6的离线安装包

### 期望的现象（What you expected to happen）

 qt5.12.6的离线安装包

### 如何重现此问题（How to reproduce it）

没有 qt5.12.6的离线安装包

### 操作系统（OS Version）

windows11

### 浏览器（如果适用）（Browser version, if applicable）

edge

**Comment by ZenithalHourlyRate** [comment]
> 没有 qt5.12.6的离线安装包

这是由于 5.12 已经 EOL，由于镜像站空间不足，我们选择不保留旧版本
