### ISSUE TITLE
[镜像请求]pypi不同步  pyatp库 

### ISSUE THREAD

**Issue by whybeyoung** [tuna/issues#1760]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

python 的一个sdk库，用于讯飞相关ai训练产品

### 上游地址与镜像方法 (How to mirror)

python pypi

### 镜像大小 (Mirror size)

<= 20Mb

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您可以参考 https://github.com/tuna/issues/issues/1701#issuecomment-1483821881

**Comment by jiegec** [comment]
```shell
$ pip3 index versions pyatp -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
pyatp (1.1.1)
Available versions: 1.1.1
```

**Comment by whybeyoung** [comment]
> ```shell
> $ pip3 index versions pyatp -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
> WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
> pyatp (1.1.1)
> Available versions: 1.1.1
> $ pip3 index versions pyatp -i https://pypi.org/simple
> WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
> pyatp (1.1.2)
> Available versions: 1.1.2, 1.1.1
> ```

有啥办法让其同步吗。。现在基础镜像配置都是基于你们的 这个源

**Comment by jiegec** [comment]
已经恢复同步了，但又因为存储空间的问题暂停了。

**Comment by jiegec** [comment]
已经恢复。

**Comment by whybeyoung** [comment]
goodjob

**Comment by jjyyxx** [comment]
@jiegec Cython 3.0.0 尚未同步也是这个原因吗？

发布时间：2023-07-17 23:18:21 (+08:00)
检查时间：2023-07-18 11:40:10 (+08:00)

**Comment by jiegec** [comment]
Cython 3.0.0 已同步。

**Comment by fuzhenxin** [comment]
> > 我们有同样的问题PKU Mirror，请问除了手动同步，还有别的建议方案吗？
> 
> 也可以把有问题的包 exclude 出去，但还是有点手动

感谢
