### ISSUE TITLE
安装 window版 paddlepaddle-gpu  conda报连接404

### ISSUE THREAD

**Issue by umie0128** [tuna/issues#1761]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

命令
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
报错
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/current_repodata.json

### 期望的现象（What you expected to happen）

无

### 如何重现此问题（How to reproduce it）

conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

**Comment by ZenithalHourlyRate** [comment]
您可以尝试在配置中添加该 channel 并重试

**Comment by umie0128** [comment]
> 您可以尝试在配置中添加该 channel 并重试

请问要怎么操作？

**Comment by ZenithalHourlyRate** [comment]
您可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 更改您的 .condarc，在其中 custom_channels 加上

```
  Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

**Comment by umie0128** [comment]
> 您可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 更改您的 .condarc，在其中 custom_channels 加上
> 
> ```
>   Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
> ```

![image](https://github.com/tuna/issues/assets/49420977/409af17b-ec10-4a1b-9a4e-03e39eb7a563)
还是不行

**Comment by umie0128** [comment]
> 您可以参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 更改您的 .condarc，在其中 custom_channels 加上
> 
> ```
>   Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
> ```
![image](https://github.com/tuna/issues/assets/49420977/590d47e7-d9bc-4523-a26f-48ea692d8259)
还是不行

**Comment by ZenithalHourlyRate** [comment]
这时候您的命令行可能需要改成

```
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c Paddle -c conda-forge
```

不过我也不知道 conda 需要 current_repodata.json 的行为到底是配置问题还是平台问题还是版本问题，因为例如 linux-64 中也没有 current_repodata.json，用户也能工作

**Comment by umie0128** [comment]
> 
一样404..

**Comment by ZenithalHourlyRate** [comment]
上游其实也没有这个文件

https://conda.anaconda.org/Paddle/win-64/current_repodata.json

您如果改用如下命令是否可以安装?

```
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://conda.anaconda.org/Paddle/ -c conda-forge
```

**Comment by umie0128** [comment]
> 上游其实也没有这个文件
> 
> https://conda.anaconda.org/Paddle/win-64/current_repodata.json
> 
> 您如果改用如下命令是否可以安装?
> 
> ```
> conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://conda.anaconda.org/Paddle/ -c conda-forge
> ```

不行

**Comment by ZenithalHourlyRate** [comment]
> 不行

那可能需要找 anaconda 官方，或找到 Paddle 的相关人员得到正确的安装命令；现在这个问题并不是镜像站的问题。

**Comment by ZenithalHourlyRate** [comment]
或者您用的是较久版本的 conda
