### ISSUE TITLE
[镜像请求] 请求建立TrueNAS镜像，在国内下载有点麻烦

### ISSUE THREAD

**Issue by AkarinLiu** [tuna/issues#1762]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

[TrueNAS](https://truenas.com)是由[iX System](https://ixsystem.com)开发的一款开源网络附属存储的解决方案，前身为[FreeNAS](https://freenas.com)

### 上游地址与镜像方法 (How to mirror)

TrueNAS Scale：https://download.truenas.com/
TrueNAS Core：https://download.freenas.com
TrueNAS Core 13.X：https://download.freenas.com/13.0

### 开源证明如下：
![图片](https://github.com/tuna/issues/assets/58081491/007d1cd0-2b46-4b93-bb96-1abfe8e45406)
[开源中国](https://www.oschina.net/news/113934/freenas-truenas-unification)
### 其他
TrueNAS Core的下载页面只展示了11和12版本，13版本需要额外的URL。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [x] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/1414
