### ISSUE TITLE
建议在首页“获取下载链接”中添加crystaldiskinfo和crystaldiskmark

### ISSUE THREAD

**Issue by wzwtt** [tuna/issues#1763]
如题。
位置分别为：
/osdn/crystaldiskinfo/
/osdn/crystaldiskmark/

**Comment by Harry-Chen** [comment]
您可以修改 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 并提出 PR。

**Comment by Harry-Chen** [comment]
Fixed by https://github.com/tuna/mirror-web/pull/422
