### ISSUE TITLE
air_data_server-0.4.1-py3-none-any.whl文件不存在

### ISSUE THREAD

**Issue by chengjon** [tuna/issues#1764]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

 ERROR: HTTP error 404 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/e7/a3/0e7651adce146c17eea516ffcb530f7ee769671e59395bc10838eca827db/altair_data_server-0.4.1-py3-none-any.whl#sha256=bd1414d69dbfec22c804b34210491d7313e5edc7736504dfb8c405ded0e2015b (from https://mirrors.bfsu.edu.cn/pypi/web/simple/altair-data-server/)
ERROR: Could not install requirement altair-data-server>=0.4.0 from https://mirrors.bfsu.edu.cn/pypi/web/packages/e7/a3/0e7651adce146c17eea516ffcb530f7ee769671e59395bc10838eca827db/altair_data_server-0.4.1-py3-none-any.whl#sha256=bd1414d69dbfec22c804b34210491d7313e5edc7736504dfb8c405ded0e2015b (from altair_viewer) because of HTTP error 404 Client Error: Not Found for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/e7/a3/0e7651adce146c17eea516ffcb530f7ee769671e59395bc10838eca827db/altair_data_server-0.4.1-py3-none-any.whl for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/e7/a3/0e7651adce146c17eea516ffcb530f7ee769671e59395bc10838eca827db/altair_data_server-0.4.1-py3-none-any.whl#sha256=bd1414d69dbfec22c804b34210491d7313e5edc7736504dfb8c405ded0e2015b (from https://mirrors.bfsu.edu.cn/pypi/web/simple/altair-data-server/)

### 期望的现象（What you expected to happen）

恢复文件下载

### 如何重现此问题（How to reproduce it）

 pip install altair_viewer

### 操作系统（OS Version）

windows

### 浏览器（如果适用）（Browser version, if applicable）

edge

### 其他环境（Other environments）

-

### 其他需要说明的事项（Anything else we need to know）

-

**Comment by ZenithalHourlyRate** [comment]
现已修复。
