### ISSUE TITLE
北京外国语大学的AOSP镜像同步失败

### ISSUE THREAD

**Issue by YoungJack-Y** [tuna/issues#1766]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

你的好兄弟北京外国语大学的AOSP镜像同步失败一直没修

### 期望的现象（What you expected to happen）

无

### 如何重现此问题（How to reproduce it）

访问https://mirrors.bfsu.edu.cn/

**Comment by ZenithalHourlyRate** [comment]
现已同步。
