### ISSUE TITLE
镜像站ubuntu目录有死循环

### ISSUE THREAD

**Issue by sjc2870** [tuna/issues#1767]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

进入清华大学开源镜像站，并进入ubuntu目录后，点击ubuntu目录，并不会发现下面的文件，而是和上层目录一样的文件，不停点击，会发现死循环

### 期望的现象（What you expected to happen）

点击ubuntu目录后，正常展示出该有的文件

### 如何重现此问题（How to reproduce it）

1. 进入https://mirrors.tuna.tsinghua.edu.cn/
2. 按ctrl + f搜索ubuntu
3. 进入第一个搜索项，也就是(ubuntu ?)
4. 进入后，点击ubuntu，会发现展示出和上层目录一样的内容，不停点击，会发现死循环

![image](https://github.com/tuna/issues/assets/51011799/dc441c23-a894-4cfe-99da-ad37098f8da1)

![image](https://github.com/tuna/issues/assets/51011799/b1d9df4f-56e5-4d23-8375-8873f1532e8d)

### 浏览器（如果适用）（Browser version, if applicable）

edge浏览器可以复现

**Comment by ZenithalHourlyRate** [comment]
@sjc2870 这是预期现象，上游即为如此设置
