### ISSUE TITLE
nix-channel 镜像失去同步

### ISSUE THREAD

**Issue by EndCredits** [tuna/issues#1769]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

正在使用 NixOS unstable ，近期发现 nixos-rebuild 无法正常更新系统，查看 TUNA Mirrors 后发现 nix-channel 镜像日期停止在 6 月 7 日。通过重新将 channel 设置为 NixOS 原始的 channel 后问题解决

### 期望的现象（What you expected to happen）

NixOS 可以正常使用 TUNA 的 nix-channel 镜像更新

### 如何重现此问题（How to reproduce it）

法一：
1. 将 NixOS unstable 的 channel 设置为 TUNA 镜像的 unstable channel
2. 执行
 ```
sudo nixos-rebuild switch --update
```
法二：
查看 TUNA Mirror Status
![Screenshot_20230617-122051_Chrome](https://github.com/tuna/issues/assets/64133324/049b6597-429c-47fa-b497-f42d0188ef1e)

### 操作系统（OS Version）

NixOS 23.11pre494976.7c67f006ea0 ( Tapir )

### 浏览器（如果适用）（Browser version, if applicable）

Google Chrome Stable 114.0.5735.133

### 其他环境（Other environments）

我的 NixOS 配置： [EndCredits/nix-configurations - Github](https://github.com/EndCredits/nix-configurations)

### 其他需要说明的事项（Anything else we need to know）

NixOS Unstable 与 Arch Linux 性质类似，相当于是一个滚动发行频道，因此可以排除系统本身出现问题的可能

**Comment by ZenithalHourlyRate** [comment]
由于空间有限，我们暂停了同步。

**Comment by EndCredits** [comment]
好的，感谢回复，期待它可以恢复同步，TUNA 的镜像服务真的非常好用 ，你们辛苦了👍

**Comment by ZenithalHourlyRate** [comment]
目前恢复了 nix-channels 中 channel 部分的同步，binary cache 部分仍旧暂停。

**Comment by EndCredits** [comment]
好的，谢谢你
