### ISSUE TITLE
官网网页“联系我们”一系列内容错位bug

### ISSUE THREAD

**Issue by Huayuluoshi** [tuna/issues#1770]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

1.2023-06-19 13:03打开官网，点击“使用帮助”，点击“wine-builds”
2.等待1~2秒，出现如图错位现象：
![截图 2023-06-19 13-00-20](https://github.com/tuna/issues/assets/117527694/71ab3b62-48ca-46b8-87cb-32b5622c8ae3)
3.选择ubuntu2204LTS无任何变化；刷新后刚开始几秒正常，但是之后问题依旧。

### 期望的现象（What you expected to happen）

弹出的联系我们不影响复制代码内容。

### 如何重现此问题（How to reproduce it）

暂时未确定；但是之前没有出现过。

### 操作系统（OS Version）

Ubuntu2204LTS（已启用ubuntu Pro）

### 浏览器（如果适用）（Browser version, if applicable）

Firefox（snap）

### 其他环境（Other environments）

1.ThinkPad-T440；
2.联通的网络环境&用WiFi模式连接

### 其他需要说明的事项（Anything else we need to know）

请问是否为我的网络环境和设备问题？我之前电脑用其他浏览器的时候未出现此问题。谢谢。

**Comment by Huayuluoshi** [comment]
补充：只要左键选中代码块，松开鼠标左键即出现bug，同时由于弹出的内容挡住代码块，只能通过快捷键复制。

**Comment by ZenithalHourlyRate** [comment]
@Huayuluoshi 这是已知问题，与浏览器有关，由于我们无法复现故而难以定位

**Comment by ZenithalHourlyRate** [comment]
参考 https://github.com/tuna/mirror-web/issues/328

**Comment by Huayuluoshi** [comment]
> @Huayuluoshi 这是已知问题，与浏览器有关，由于我们无法复现故而难以定位

或许我可以帮忙提供日志，但是请问要如何做呢？谢谢你。

**Comment by ZenithalHourlyRate** [comment]
> 或许我可以帮忙提供日志，但是请问要如何做呢？谢谢你。

或许可以在 F12 审查元素中的 console 部分获得一些有效的信息

**Comment by Crystal-RainSlide** [comment]
> > 或许我可以帮忙提供日志，但是请问要如何做呢？谢谢你。
> 
> 或许可以在 F12 审查元素中的 console 部分获得一些有效的信息

不幸地，CSS 问题一般是不会吐日志的。

可以做的：
- Ctrl + F5 强制刷新看看是不是缓存里的旧资源导致问题；
- F12 - 网络里检查一下是不是有资源没成功加载；
- 确定一下可否稳定复现，提供浏览器版本以便复现。

**Comment by Harry-Chen** [comment]
我们最近更新了一版首页，此问题是否还存在？

**Comment by Huayuluoshi** [comment]
经过反复测试，看起来问题不存在了，故将本issue关闭。
