### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by jokewwww** [tuna/issues#1771]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

adoptopenjdk/openjdk8-openj9:jdk8u181-b13_openj9-0.9.0

### 上游地址与镜像方法 (How to mirror)

adoptopenjdk/openjdk8-openj9:jdk8u181-b13_openj9-0.9.0

### 镜像大小 (Mirror size)

100M

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by ZenithalHourlyRate** [comment]
您好，adoptopenjdk 已经更名为 adoptium https://mirrors.tuna.tsinghua.edu.cn/news/rename-adoptopenjdk-to-adoptium/

同时 adoptium 由于一些原因，不提供 openj9，参考 https://github.com/tuna/issues/issues/1335#issue-999268808

您可以参考 https://mirrors.tuna.tsinghua.edu.cn/github-release/ibmruntimes/semeru8-binaries/
