### ISSUE TITLE
[OpenTUNA] ubuntu-releases 缺失

### ISSUE THREAD

**Issue by wordlesswind** [tuna/issues#1777]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法下载镜像文件。

例如 `22.04/ubuntu-22.04.2-live-server-amd64.iso`：

```
curl -I https://opentuna.cn/ubuntu-releases/22.04/ubuntu-22.04.2-live-server-amd64.iso
HTTP/2 404
content-type: text/html
content-length: 15822
date: Wed, 05 Jul 2023 23:35:25 GMT
server: nginx/1.18.0
last-modified: Wed, 01 Mar 2023 02:41:31 GMT
etag: "63febb5b-3dce"
accept-ranges: bytes
vary: Accept-Encoding
x-cache: Error from cloudfront
via: 1.1 b821b09a58c2e4c59caee1b010c1d042.cloudfront.net (CloudFront)
x-amz-cf-pop: SZX51-E1
x-amz-cf-id: 781iChrNswnlLF-b5aglVCY6pUvhVVqxRRgV5kZBPxB_6wSf6fPaCg==
age: 10719
```

### 期望的现象（What you expected to happen）

正常下载镜像文件。

### 如何重现此问题（How to reproduce it）

https://opentuna.cn/ubuntu-releases/22.04/ubuntu-22.04.2-live-server-amd64.iso

**Comment by ZenithalHourlyRate** [comment]
@wordlesswind 由于被滥用，屏蔽 iso 下载为预期行为
