### ISSUE TITLE
something wrong with conda mirros

### ISSUE THREAD

**Issue by liuxiawei** [tuna/issues#1778]
![图片](https://github.com/tuna/tunasync-scripts/assets/5093541/df1685fe-0b9c-4e97-9122-54225316bdd6)
I tried in different computer, and with conda, mamba, miniconda
20230707 10:40

**Comment by Harry-Chen** [comment]
可以用中文描述问题。

**Comment by liuxiawei** [comment]
我使用mamba更新的时候报错，`    RuntimeError: Could not read JSON repodata file (${userpath}/Applications/mambaforge/pkgs/cache/9cdf7780.json) parse error line 1`
里面的内容是：
```
{"_cache_control":"","_etag":"\"6494895f-0\"","_mod":"Thu, 22 Jun 2023 17:48:15 GMT","_url":"https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/repodata.json",
```
看起来是一个不完整的json。

**Comment by shankerwangmiao** [comment]
您好，请您再试一次，可能是同步出错所致

**Comment by liuxiawei** [comment]
谢谢大佬！恢复正常了！！！！！
