### ISSUE TITLE
6.5.1-0-202305220814tqtc-qtinsighttracker-examples-6.5.1.7z.sha1  server replied:Not Found

### ISSUE THREAD

**Issue by fly2sky2018** [tuna/issues#1779]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法下载存档
https:/mirrors.tuna.tsinghua.edu.cn/qt/qtsdkrepository/windows x86/desktop/gt6_651_insighttracker/qt.qt6.651.examples.qtinsighttracker/6.5.1-0-202305220814tqtc-qtinsighttracker-examples-6.5.1.7z
:Error transferring 

https://mirrors.tuna.tsinghua.edu.cn/qt//qtsdkrepository/windows_x86/desktop/qt6_651_insighttracker/qt.qt6.651.examples.qtinsighttracker/6.5.1-0-202305220814tqtc-qtinsighttracker-examples-6.5.1.7z.sha1 
server replied:Not Found

### 期望的现象（What you expected to happen）

希望能解决

### 如何重现此问题（How to reproduce it）

  ./qt-unified-windows-x64-online --mirror https://mirrors.tuna.tsinghua.edu.cn/qt/

### 操作系统（OS Version）

win11

**Comment by shankerwangmiao** [comment]
您好，上游 download.qt.io 也不存在此文件：

https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/ 下没有 “qt6_651_insighttracker”
