### ISSUE TITLE
 外国语的镜像站点 很多pypi 包都没有更新 ，比如 pyatp，还有很多包版本都落后于 清华站点

### ISSUE THREAD

**Issue by whybeyoung** [tuna/issues#1782]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）
其实我们一直用的是 科大源：
(https://pypi.mirrors.ustc.edu.cn/simple/)
但是  这个链接 自动跳转到了  外国语，然后外国的主站又指引我们找到 tsinghua的 issue区。。我想问下，这个问题如何解决。。。我们很多配置都是基于ustc的源，因为某些节点ustc的下载速度会比较快一些。。

https://mirrors.bfsu.edu.cn/index.html

外国语的镜像站点 很多pypi 包都没有更新 ，比如 pyatp，还有很多包版本都落后于 清华站点

### 期望的现象（What you expected to happen）

https://mirrors.bfsu.edu.cn/index.html 和清华站点保持一致， https://mirrors.bfsu.edu.cn/index.html 页面联系我们直接给的地址是到这里提交问题。。。

<img width="1453" alt="image" src="https://github.com/tuna/issues/assets/10629930/0edfdda8-f9bd-43bd-961f-fe8b0f66e52e">

### 如何重现此问题（How to reproduce it）

 查看 清华站点 pyatp包和  bfsu的

**Comment by ZenithalHourlyRate** [comment]
@whybeyoung 由于近期bfsu存储空间用满，pypi同步状态不正常，将手动重新同步

**Comment by shankerwangmiao** [comment]
已经开始追赶了。

**Comment by whybeyoung** [comment]
> 已经开始追赶了。

牛呀， 如有需要支持可以联系我

**Comment by shankerwangmiao** [comment]
已经同步完成。
