### ISSUE TITLE
OpenBSD 镜像同步停止多日

### ISSUE THREAD

**Issue by wmtdru8xip** [tuna/issues#1783]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

自 2023-06-27 以来，OpenBSD 镜像同步停止多日。

### 期望的现象（What you expected to happen）

OpenBSD 镜像继续同步。

### 如何重现此问题（How to reproduce it）

打开镜像站首页。

**Comment by jiegec** [comment]
上游死活连不上，现在换了个上游继续同步。

**Comment by jiegec** [comment]
一台服务器已经跟上同步，另一台机器也快了。
