### ISSUE TITLE
https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/hfl/ 显示404

### ISSUE THREAD

**Issue by lsm03624** [tuna/issues#1786]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/hfl/ 显示404，是主动删除了吗？

### 期望的现象（What you expected to happen）

希望恢复这个镜像，谢谢！

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/hfl/

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/937#issuecomment-1520149600
