### ISSUE TITLE
ubuntu-cloud-images 缺少 releases 文件夹

### ISSUE THREAD

**Issue by bin456789** [tuna/issues#1788]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

ubuntu-cloud-images 缺少 releases 文件夹

https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/releases/  缺少

https://mirror.nju.edu.cn/ubuntu-cloud-images/
https://mirror.nju.edu.cn/ubuntu-cloud-images/releases/

https://cloud-images.ubuntu.com/
https://cloud-images.ubuntu.com/releases/

### 期望的现象（What you expected to happen）

无

### 如何重现此问题（How to reproduce it）

无

**Comment by shankerwangmiao** [comment]
由于  `releases/` 目录占用空间较大，且更新频繁，为节省服务器资源，我们排除了该目录。

您可以在 `ubuntu-cloud-images` 下相应 code name 的目录下找到所需的文件。

**Comment by bin456789** [comment]
但是只有 releases 目录有版本号不需要 codename
其他文件夹都要找 codename

**Comment by bin456789** [comment]
> 由于 `releases/` 目录占用空间较大，且更新频繁，为节省服务器资源，我们排除了该目录。

 `releases/` 目录占用空间较大，这点同意

但是
以 22.04 jammy 为例
https://cloud-images.ubuntu.com/jammy/
https://cloud-images.ubuntu.com/releases/22.04/

点开可以看到标题分别是
Ubuntu Cloud Images 22.04 Daily Build
Ubuntu 22.04 LTS (Jammy Jellyfish) Release Build

`Daily` 更新比 `releases` 更频繁
没理由同步 `Daily` 而不同步 `Release`

**Comment by taoky** [comment]
> `Daily` 更新比 `releases` 更频繁 没理由同步 `Daily` 而不同步 `Release`

但是似乎 `daily` 是 `releases` 的子集，并且 https://cloud-images.ubuntu.com/releases/22.04/release/ 的内容也是最新的 daily。

**Comment by bin456789** [comment]
> > `Daily` 更新比 `releases` 更频繁 没理由同步 `Daily` 而不同步 `Release`
> 
> 但是似乎 `daily` 是 `releases` 的子集，并且 https://cloud-images.ubuntu.com/releases/22.04/release/ 的内容也是最新的 daily。

反了，`releases` 是 `daily` 的子集，你看6月构建的版本就知道
只是 release 会保留全部旧的 release
同步的话把几个月前的旧版本删掉，或者只同步 release 里面的 release 也行啊
https://cloud-images.ubuntu.com/releases/22.04/release/
