### ISSUE TITLE
我使用的移动宽带，使用清华等镜像源安装python库，报403错误。查了很久没解决，请问这个是什么问题。

### ISSUE THREAD

**Issue by li123-web** [tuna/issues#1789]
ERROR: HTTP error 403 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/51/60/ac90db4e9dbb954fcc545524d244981c5a9ffbe96ee8407ec4f052523ac7/shap-0.40.0-cp37-cp37m-win_amd64.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/shap/)
ERROR: Could not install requirement shap==0.40.0 from https://mirrors.bfsu.edu.cn/pypi/web/packages/51/60/ac90db4e9dbb954fcc545524d244981c5a9ffbe96ee8407ec4f052523ac7/shap-0.40.0-cp37-cp37m-win_amd64.whl because of HTTP error 403 Client Error: Forbidden for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/51/60/ac90db4e9dbb954fcc545524d244981c5a9ffbe96ee8407ec4f052523ac7/shap-0.40.0-cp37-cp37m-win_amd64.whl for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/51/60/ac90db4e9dbb954fcc545524d244981c5a9ffbe96ee8407ec4f052523ac7/shap-0.40.0-cp37-cp37m-win_amd64.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/shap/)

**Comment by shankerwangmiao** [comment]
您好，请提供返回结果正文末尾处的标识符。

**Comment by Stevesuk0** [comment]
我电信也出现了这样情况，建议临时用阿里源替代。

**Comment by xuyanshi** [comment]
I met the same problem.

**Comment by shankerwangmiao** [comment]
遇到类似问题的，请提供返回结果正文末尾处的标识符，以便我们诊断问题。

**Comment by xuyanshi** [comment]
> 遇到类似问题的，请提供返回结果正文末尾处的标识符，以便我们诊断问题。
我的网络环境是北京教育网，以下是我更新conda包时的返回信息。
```
sudo conda update --all

Retrieving notices: ...working... DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.util.retry:Incremented Retry for (url='/pkgs/r/notices.json'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /pkgs/r/notices.json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/notices.json HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/notices.json HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/notices.json HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/notices.json HTTP/1.1" 404 None
done
Collecting package metadata (current_repodata.json): / DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
\ DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/noarch/current_repodata.json HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/osx-arm64/current_repodata.json HTTP/1.1" 404 None
| DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/osx-arm64/repodata.json HTTP/1.1" 304 0
/ DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/noarch/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/osx-arm64/current_repodata.json HTTP/1.1" 200 None
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/osx-arm64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/osx-arm64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
done
Solving environment: done

Downloading and Extracting Packages
python-on-whales-0.6 | 72 KB     |                                                                               |   0% DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/noarch/python-on-whales-0.64.1-pyhd8ed1ab_0.conda HTTP/1.1" 200 73773
                                                                                                                        
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by shankerwangmiao** [comment]
> > 遇到类似问题的，请提供返回结果正文末尾处的标识符，以便我们诊断问题。
> 
> 我的网络环境是北京教育网，以下是我更新anaconda包时的返回信息。
> 
> ```
> sudo conda update --all
> 
> Retrieving notices: ...working... DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> DEBUG:urllib3.util.retry:Incremented Retry for (url='/pkgs/r/notices.json'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
> WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /pkgs/r/notices.json
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): repo.anaconda.com:443
> DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/notices.json HTTP/1.1" 404 None
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/notices.json HTTP/1.1" 404 None
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/notices.json HTTP/1.1" 404 None
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/notices.json HTTP/1.1" 404 None
> done
> Collecting package metadata (current_repodata.json): / DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
> \ DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/noarch/current_repodata.json HTTP/1.1" 404 None
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/osx-arm64/current_repodata.json HTTP/1.1" 404 None
> | DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/noarch/repodata.json HTTP/1.1" 304 0
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/pkgs/free/osx-arm64/repodata.json HTTP/1.1" 304 0
> / DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/noarch/current_repodata.json HTTP/1.1" 200 None
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/osx-arm64/current_repodata.json HTTP/1.1" 200 None
> \ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
> | DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/osx-arm64/current_repodata.json HTTP/1.1" 304 0
> DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/osx-arm64/current_repodata.json HTTP/1.1" 304 0
> DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
> done
> Solving environment: done
> 
> （略去了一些包的详细信息）
> 
> Downloading and Extracting Packages
> python-on-whales-0.6 | 72 KB     |                                                                               |   0% DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
> DEBUG:urllib3.connectionpool:https://mirrors.tuna.tsinghua.edu.cn:443 "GET /anaconda/cloud/conda-forge/noarch/python-on-whales-0.64.1-pyhd8ed1ab_0.conda HTTP/1.1" 200 73773
>                                                                                                                         
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> ```
这日志里也没提示错误啊，这不是成功了吗？

**Comment by xuyanshi** [comment]
> 

确实是成功了。不过我想表达的是，以前并没有这么多的 `DEBUG` 信息（这是大约半个月前开始出现的），因为这样看起来显得很繁杂。
不过实际上也没有什么负面影响，所以抱歉打扰，我的问题到此为止，感谢您的耐心解答。

**Comment by Harry-Chen** [comment]
> > 
> 
> 确实是成功了。不过我想表达的是，以前并没有这么多的 `DEBUG` 信息（这是大约半个月前开始出现的），因为这样看起来显得很繁杂。 不过实际上也没有什么负面影响，所以抱歉打扰，我的问题到此为止，感谢您的耐心解答。

如果你仔细阅读这些信息，会发现其中涉及到 TUNA 镜像站的内容并不多。超过一半来自于 anaconda.com 的重定向以及下载连接相关。

通常来说，DEBUG 级别的日志默认是不输出的。或许你应该检查自己的设置，尤其是是否全局地打开了某种 verbose 模式。
