### ISSUE TITLE
在线安装Qt时找不到文件

### ISSUE THREAD

**Issue by c-my** [tuna/issues#1792]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在线安装Qt时，出现找不到文件错误：
> 无法下载存档 https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip：Error transferring https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip.sha1 - server replied: Not Found

但在Qt官方仓库中，该文件存在（<https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip.sha1>）

### 期望的现象（What you expected to happen）

正常安装

### 如何重现此问题（How to reproduce it）

运行`.\qt-unified-windows-x64-online.exe --mirror https://mirrors.tuna.tsinghua.edu.cn/qt`，安装套件选择`Qt 6.5.2`相关组件，安装进行一段时间后会出现。

### 操作系统（OS Version）

Windows 11

**Comment by full-of-fei** [comment]
我在使用4.6.0版本下载器下载Qt 6.5.2时遇到了同样的情况，后面尝试使用低版本下载器看是否可以下载6.5.1版本时发现使用4.5.2版本下载器可以正常下载Qt 6.5.2. 可能这个版本下载器不需要下载缺失的那几个文件？题主需要尽快下载的话可以尝试下更换下载器

**Comment by Harry-Chen** [comment]
可能是上游问题，暂时认为已解决。
