### ISSUE TITLE
pkgsrc 镜像有关 NetBSD 的部分不完整

### ISSUE THREAD

**Issue by ykla** [tuna/issues#1793]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

`https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/packages/NetBSD/amd64/9.0_current` 为空，并没有镜像下来。

### 期望的现象（What you expected to happen）

进行镜像。

### 如何重现此问题（How to reproduce it）

打开链接即可。

**Comment by jiegec** [comment]
9.0_current 指向了 `.9.0_current-2023-06-25-15.48`，这个路径还没有同步完。

**Comment by ykla** [comment]
@jiegec 仍然为空目录。且 TUNA 无 `.9.0_current-2023-06-25-15.48`。

**Comment by jiegec** [comment]
仔细看了一下同步配置，同步的时候跳过了这个目录。

**Comment by jiegec** [comment]
什么场合下需要用到 9.0_current？按理说应该用其他具体的版本号。

**Comment by ykla** [comment]
> 什么场合下需要用到 9.0_current？按理说应该用其他具体的版本号。

 9.0_current 的软件比较全。其他的源缺斤短两。

**Comment by jiegec** [comment]
已经同步完成。
