### ISSUE TITLE
opentuna 的 PyPI 挂了好几天了

### ISSUE THREAD

**Issue by huxuan** [tuna/issues#1797]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

opentuna 的 PyPI 挂了好几天了

### 期望的现象（What you expected to happen）

恢复 PyPI

### 如何重现此问题（How to reproduce it）

https://opentuna.cn/status/#syncing-status

**Comment by jiegec** [comment]
已解决。
