### ISSUE TITLE
tuna dns 解析异常

### ISSUE THREAD

**Issue by solidarity-forever** [tuna/issues#1800]
设置dns服务器为`101.6.6.6`
不管什么网站，返回结果均为`10.0.0.1`
![图片](https://github.com/tuna/issues/assets/6008932/fcce6fe2-4f37-41c3-8478-fbddc271fc27)

**Comment by jiegec** [comment]
无法复现，请确认 DNS 是否被拦截

**Comment by solidarity-forever** [comment]
> 

好的

**Comment by solidarity-forever** [comment]
应该是DNS被本地网络污染，任何dns服务器都不能正确返回解析结果，已通过DoH解决
