### ISSUE TITLE
Opentuna 的 PyPI 比官方（甚至是 tuna.tsinghua）晚的有点久，这个有可能改善吗？

### ISSUE THREAD

**Issue by huxuan** [tuna/issues#1801]
感谢伟大的 tuna 源，最近正在把所有开发环境都默认指向 opentuna，但是遇到了一个小问题。

时常遇到已经发布了好些（将近10）天的包，在 tuna.tsinghua 是有的，但是在 opentuna 里面还没有。

比如此刻的 furo 的 2023.07.26，pypi.org 上显示是 2023.07.27（可能有时差） 发布的。

截了一个同屏的图，同样拉到了页面最下方，opentuna里就没有最新的 2023.07.26 版本。

![image](https://github.com/tuna/issues/assets/726061/13ae9913-11c3-4215-9b64-f4a3075ce50d)

**Comment by jiegec** [comment]
因为之前有一段时间 pypi 同步失败，所以落后了，现在一直在追赶。

**Comment by huxuan** [comment]
Gotcha. Thanks.
