### ISSUE TITLE
git-repo下载下来大小为0B

### ISSUE THREAD

**Issue by ChenMoGe2** [tuna/issues#1803]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

根据https://mirrors.tuna.tsinghua.edu.cn/help/git-repo/帮助页面的提示下载repo
curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o repo 下载的repo文件0B

### 期望的现象（What you expected to happen）

repo有大小可用

### 如何重现此问题（How to reproduce it）

执行命令即可

### 操作系统（OS Version）

任意

### 浏览器（如果适用）（Browser version, if applicable）

任意

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by shankerwangmiao** [comment]
已修复
