### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by huidaoweilai2024** [tuna/issues#1805]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/ 连接超时

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/ 恢复连接

### 如何重现此问题（How to reproduce it）

打开 https://mirrors.tuna.tsinghua.edu.cn/

**Comment by phy25** [comment]
您使用的是移动的手机网络还是宽带网络？方便提供具体的地区吗？您有尝试更换运营商连接吗？能否提供路由追踪的结果吗？

**Comment by huidaoweilai2024** [comment]
宽带网络, 跃点跟踪结果: 
traceroute to mirrors.tuna.tsinghua.edu.cn (101.6.15.130), 30 hops max, 60 byte packets
 1  192.168.10.1 (192.168.10.1)  14.299 ms  19.252 ms  18.473 ms                                                 2  192.168.1.1 (192.168.1.1)  18.193 ms  17.615 ms  17.084 ms                                                   3  10.229.0.1 (10.229.0.1)  20.487 ms  20.586 ms  20.199 ms                                                     4  211.103.87.21 (211.103.87.21)  19.771 ms  19.293 ms  18.669 ms                                               5  * * *
 6  * * *                                                7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by shankerwangmiao** [comment]
你能打开 www.tsinghua.edu.cn 吗？到 166.111.4.100 的 trace 结果是什么？

**Comment by huidaoweilai2024** [comment]
可以
traceroute to www.tsinghua.edu.cn (166.111.4.100), 30 hops max, 60 byte packets
 1  192.168.10.1 (192.168.10.1)  14.992 ms  14.182 ms  13.729 ms
 2  192.168.1.1 (192.168.1.1)  13.384 ms  13.760 ms  14.731 ms
 3  10.229.0.1 (10.229.0.1)  32.368 ms  31.843 ms  30.709 ms                                                     4  211.103.87.18 (211.103.87.18)  22.749 ms 211.103.87.21 (211.103.87.21)  26.054 ms  25.884 ms                 5  221.183.47.193 (221.183.47.193)  21.431 ms 221.183.47.197 (221.183.47.197)  20.734 ms  20.317 ms             6  221.183.37.185 (221.183.37.185)  30.756 ms 221.183.40.13 (221.183.40.13)  32.726 ms 221.183.132.241 (221.183.132.241)  26.056 ms
 7  221.183.94.22 (221.183.94.22)  26.520 ms 221.183.94.26 (221.183.94.26)  23.610 ms *                          8  211.136.0.74 (211.136.0.74)  44.837 ms  39.903 ms  39.538 ms                                                 9  101.4.118.25 (101.4.118.25)  40.692 ms  39.412 ms  38.457 ms
10  101.4.116.213 (101.4.116.213)  35.298 ms  40.044 ms 101.4.113.209 (101.4.113.209)  32.214 ms
11  101.4.113.234 (101.4.113.234)  63.956 ms  40.920 ms  39.873 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by shankerwangmiao** [comment]
您好，根据您提供的诊断结果，应该是您的网络服务提供商到 TUNA 服务器的路由出现异常，请联系您的网络服务提供商以寻求协助。

**Comment by curtisrecords** [comment]
移动部分省市访问mirrors报RESET 和移动上游反馈了
![image](https://github.com/tuna/issues/assets/71839629/f31dca4d-6f03-4a46-8e8a-d915410cde78)

**Comment by shankerwangmiao** [comment]
感谢，我们也发现几个地方的移动的用户访问 TUNA 出现异常，已经在排查了。

**Comment by huidaoweilai2024** [comment]
https://tuna.moe/ bootstrap.min.js jquery.min.js bootstrap.min.css可能会因为https://cdn.jsdelivr.net/连接异常无法加载影响网页式样, 为了不同地区, 不同ISP服务提供商下网页加载正常, 建议使用https://unpkg.com/代替https://cdn.jsdelivr.net/
