### ISSUE TITLE
搜索功能: 添加关键词, 当搜索 emacs 显示 elpa

### ISSUE THREAD

**Issue by snowman** [tuna/issues#1806]
`ELPA` stands for Emacs Lisp Package Archive.

![image](https://github.com/tuna/issues/assets/16096559/dda4a2a6-829b-4ae5-b7c8-76c26927a00b)

**Comment by snowman** [comment]
或许搜索`emacs`前缀比如`ema`也显示`elpa`结果?

**Comment by Harry-Chen** [comment]
增加 alias 会导致用户困惑，我们目前也没有计划增加此类模糊搜索功能。
