### ISSUE TITLE
中国移动网络环境国内部分区域出现无法访问

### ISSUE THREAD

**Issue by ecturing** [tuna/issues#1808]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

更新镜像源出现失败，显示网络不可达。同时使用itdog进行测试，发现中国移动网络部分省市出现访问失败
![mirrors tuna tsinghua edu cn_多地区多线路HTTP测速(1)](https://github.com/tuna/issues/assets/42050852/c12602af-0252-4441-86f3-96ca93a74c13)

### 期望的现象（What you expected to happen）

恢复访问

### 如何重现此问题（How to reproduce it）

使用itdog测试网站，失败响应几乎全是中国移动

**Comment by shankerwangmiao** [comment]
您好，感谢反馈。此问题集中在 #1805 讨论。
