### ISSUE TITLE
erlang-solutions

### ISSUE THREAD

**Issue by wh211212** [tuna/issues#181]
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by bigeagle** [comment]
只镜像 19.2 standard 版本，可以吧？

**Comment by wh211212** [comment]
可以的，我本地配置好他们的repo，yum可以，IDC里面的机器yum超级慢，我自己搭本地源都搭好啦，想想还不如直接放到你们的项目里面呢，哈哈 如果能搞好 非常感谢的

**Comment by wh211212** [comment]
搞rabbitmq集群的时候需要的，估计erlang repo能搞好，用的人还挺多的

**Comment by bigeagle** [comment]
好的，apt 和 yum 的仓库都有脚本直接镜像，我找时间搞起来。

**Comment by wh211212** [comment]
thanks，
另外一个关联项目，rabbitmq
https://packagecloud.io/rabbitmq/rabbitmq-server/el/6

# 如何能加入你们的团队？期待。。。

**Comment by alick** [comment]
# 加入我们 订阅邮件列表

发送任意内容邮件到 tuna-general+subscribe@googlegroups.com, 并回复确认邮件。
如果你是清华学生

除了订阅邮件列表，请再在 校团委社团部平台
<http://shetuan.student.tsinghua.edu.cn/f/ckstzy/20140027> 点击 "我要加入" 加入协会。

CC @bigeagle, 感觉这段话在首页上不够醒目

Regards,
Tao

**Comment by bigeagle** [comment]
正在同步了，包比较多，但愿今年能同步完

**Comment by wh211212** [comment]
多谢啦。。。我现在用的是本地自建的repo，yum正常啦，但是后面更新还是没官方源方便。。。

**Comment by bigeagle** [comment]
https://neomirrors.tuna.tsinghua.edu.cn/erlang-solutions/
已经好了～ rabbitmq 后续再搞

**Comment by wh211212** [comment]
非常感谢。。。。
