### ISSUE TITLE
[镜像请求] makedeb

### ISSUE THREAD

**Issue by MoetaYuko** [tuna/issues#1812]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

makedeb 是适用于 deb 系的打包工具，语法类似 arch 的 PKGBUILD，（相比于原生 deb 打包工具）更简洁

makedeb 维护了两个二进制仓库：
1. https://docs.makedeb.org/installing/apt-repository/ ，用于分发 makedeb 本体
2. https://docs.makedeb.org/prebuilt-mpr/getting-started/ ，用于分发一小部分使用 makedeb 打包而成的二进制 deb 包。由于对应的源码仓库是滚动更新的，因此相比于原生 deb 包的优势是版本新，

以及一个源码仓库 https://mpr.makedeb.org/ ，性质类似 AUR。

希望至少能对二进制仓库进行镜像

### 上游地址与镜像方法 (How to mirror)

https://proget.makedeb.org

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by hosiet** [comment]
prebuilt-mpr 包含一些禁止重分发的软件（如 minecraft-launcher https://proget.makedeb.org/feeds/prebuilt-mpr/bullseye/minecraft-launcher%3Aamd64/1.0.1221-3 详见 https://minecraft.net/terms ），因此可能无法合法进行镜像。

**Comment by MoetaYuko** [comment]
好吧
