### ISSUE TITLE
huggingface的模型镜像网址无法使用

### ISSUE THREAD

**Issue by swltown** [tuna/issues#1813]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

访问该镜像网址'https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models'提示是无法访问。

### 期望的现象（What you expected to happen）

期望是能访问该网址，可以找到需要的transformer模型

### 如何重现此问题（How to reproduce it）

访问该网址'https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models'即可看到错误现象

### 浏览器（如果适用）（Browser version, if applicable）

Chrome

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/937#issuecomment-1520149600
