### ISSUE TITLE
自建 nix 镜像源及同步脚本

### ISSUE THREAD

**Issue by dayinfinite** [tuna/issues#1816]
你好，我想要自建 nix 镜像源，有对应教程和同步脚本么？如果有的话，可是帮助我节省很多时间，多谢

**Comment by taoky** [comment]
https://github.com/tuna/tunasync-scripts/blob/master/nix-channels.py

**Comment by dayinfinite** [comment]
> https://github.com/tuna/tunasync-scripts/blob/master/nix-channels.py

你好：
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(24142054 bytes read, 140365290 more expected)', IncompleteRead(24142054 bytes read, 140365290 more expected))

出现这个报错，你这边是怎么解决的，我这边查看我的网络和设置的重试次数，没有问题，但是总会出现这个问题

**Comment by Harry-Chen** [comment]
我本地测试并没有遇到问题，请检查网络环境。
