### ISSUE TITLE
CocoaPod 镜像貌似不同步了

### ISSUE THREAD

**Issue by baogechen** [tuna/issues#182]
看了下目前最后一次同步是2016年7月了

**Comment by huiyiqun** [comment]
似乎好了？今天12点和16点分别成功了两次

**Comment by huiyiqun** [comment]
```
$ git -C /data/git/CocoaPods/Specs.git log | head
commit 1d0438422307ae30fb074bfec6f62f4a74a72078
Author: AndrewZhu <zaz92537@126.com>
Date:   Thu Dec 29 03:24:25 2016 -0500

    [Add] AZ-THPerformanceMonitor 0.0.13

commit 7a61cbfcf856c81ca02946744cc39e36a318e206
Author: codeaddslife <andy.vandenheuvel@gmail.com>
Date:   Thu Dec 29 03:20:57 2016 -0500
```

从服务器上看数据是最新的。

可以提供一下你的信息吗，也就是为什么你认为最后一次同步是7月？

**Comment by huiyiqun** [comment]
我从这里可以正常clone到一个git仓库：https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git
并且最近一个commit是今天的。

但是我不是object-C开发者，不清楚这个仓库应该怎么用，是否还缺别的东西。

**Comment by baogechen** [comment]
我用的这个地址

https://mirrors.tuna.tsinghua.edu.cn/CocoaPods/Specs.git/



在 2016年12月29日，下午5:09，huiyiqun <notifications@github.com<mailto:notifications@github.com>> 写道：


我从这里可以正常clone到一个git仓库：https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git
并且最近一个commit是今天的。

但是我不是object-C开发者，不清楚这个仓库应该怎么用，是否还缺别的东西。

**Comment by baogechen** [comment]
我从首页进入的，正确的链接在哪查看？
另外多谢提供这个镜像，很好用

**Comment by bigeagle** [comment]
我知道了，这个应该写个帮助。很久很久很久以前有人提过要镜像，我们搞下来但是不会用，就没下文了。

**Comment by huiyiqun** [comment]
我们没有Object-C开发者，方便帮我们写一个简单的帮助吗？

**Comment by bigeagle** [comment]
#46 中 @xavieryao 写过步骤，不知道对不对

**Comment by baogechen** [comment]
把原来的步骤改善了一下

**Comment by huiyiqun** [comment]
十分感谢
