### ISSUE TITLE
docker-ce仓库不可用

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1822]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

当前发现清华源的docker-ce在ubuntu20.04版本下apt-get install docker-ce有异常（官方正常）。

```
Get:77 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 git amd64 1:2.25.1-1ubuntu3.11 [4605 kB]             
Get:78 http://archive.ubuntu.com/ubuntu focal/main amd64 patch amd64 2.7.6-6 [105 kB]                                 
Get:79 http://archive.ubuntu.com/ubuntu focal/universe amd64 slirp4netns amd64 0.4.3-1 [74.3 kB]                      
Fetched 154 MB in 25s (6169 kB/s)                                                                                     
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_24.0.6-1~ubuntu.20.04~focal_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:bfab4390fe61b8af372d2fb88ff5343407de4a857ea26e5b25266fad3d1c13a4fd39f5bb47dc134d78d1161aace92b4c9e70a083b247e82b1a214ce27dc37556
    - SHA256:6ef661f741780de72785e20d0420abe219a1641631eeaa498fe8befa0e0451ec
    - SHA1:642de6ed6d4ab58bc3ca0f312947d903cdf71e8f [weak]
    - MD5Sum:bbd38911923ac2487da5a1024498c15c [weak]
    - Filesize:22594406 [weak]
   Hashes of received file:
    - SHA512:c531d0b39ac7adda4606bee84b14ac922d99e2faa351c40aeb9d57aacd047213e721c54c2c3c05a95d7d33f20451c0c7ebb2208356a33ec4628a08631d96406c
    - SHA256:078fa6be2c76c61bc53d4c04b3f8794c29dd27da13cfa471395a6999986df21c
    - SHA1:fb4914a16643d029de5f98e4770c92a49af76d4b [weak]
    - MD5Sum:c0eae530ec6b8bc96ec5006800c192d0 [weak]
    - Filesize:22594406 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:17:36 +0000
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1~ubuntu.20.04~focal_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:eefbd1db94ef5a668a26f1d743e5943e9099aa9545d8deacbd34b870a1e48be6a2f1302405225d5c88e8578167a3753cb7dd70a4d7b1c4480b4937ed84b947d3
    - SHA256:5f02da7a08735173003aa44cabeac5f15471eb99174180251d58b5633fccfccb
    - SHA1:075a067e63963162d6f077dbc784cb718293f961 [weak]
    - MD5Sum:515f4a055b2a27ea696538bc017be580 [weak]
    - Filesize:9037876 [weak]
   Hashes of received file:
    - SHA512:cd75b801a9dca90e28a8fe17a00ee85c9d2531e8ff97da9f4eaab64de84c0705a36f1714412cd812897c02fba1c05cadf25332f5ec0d98cd7276206063b50cf5
    - SHA256:0916c2be3705104be9712fe0f00c916d74fee748fba3ce38b47c8dfeb6fb86fe
    - SHA1:2916e916d7e5b8d23a9fa25242f9c2c7ebeafeef [weak]
    - MD5Sum:f33df4e0a90342aaaf63b6504f692cf8 [weak]
    - Filesize:9037876 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:17:35 +0000
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/dists/focal/pool/stable/amd64/docker-compose-plugin_2.21.0-1~ubuntu.20.04~focal_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:fc49fe287eaea291b7dc9216bf4d049d6afcf1c67f201341176b28b26b5d27fb72a9095213c96a687cfbdbd3a63d597624e427bcda603377024b59f8415b308b
    - SHA256:afee28f01d858b5d052d3d2b3efbdb84306bb3bd85f1529cc6d087930475db0c
    - SHA1:766497ea5a59c3f0c120486cefe7e153187b8353 [weak]
    - MD5Sum:f9d40de85c31a3b1aebf5d631008b3d3 [weak]
    - Filesize:11931062 [weak]
   Hashes of received file:
    - SHA512:2507e1fb3a2c70c9964b921c9ccbd6c2592ec041ceb52f9df732565cc531d94279e5a2dbc12c3f788605368382c524bfb995f0cfb75ea07f84f8b3a18b6a3592
    - SHA256:d43f0ac8929bc715c3664b639d2b6458d7b0857b0a4d1e67b51cdbbee74d62ad
    - SHA1:7e7d494c02359532ac19c9ed007c4b871e2e617e [weak]
    - MD5Sum:f3ce53187095ce43cb65ffc7f229e92c [weak]
    - Filesize:11931062 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:17:37 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### 期望的现象（What you expected to happen）

和官方行为保持一致。

### 如何重现此问题（How to reproduce it）

/etc/apt/sources.list
```
deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu focal stable
```

### 操作系统（OS Version）

ubuntu focal

**Comment by lishunan246** [comment]
+1

**Comment by Harry-Chen** [comment]
Duplicated with #1819

**Comment by jiegec** [comment]
focal 的 docker-ce 包已经手动同步，请测试。

**Comment by lishunan246** [comment]
```
获取:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm [9029 kB]
错误:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm
  Hash 校验和不符
  Hashes of expected file:
   - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
   - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
   - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
   - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
   - Filesize:9029488 [weak]
  Hashes of received file:
   - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
   - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
   - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
   - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
   - Filesize:9029488 [weak]
  Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
已下载 9029 kB，耗时 1秒 (10.9 MB/s)
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  Hash 校验和不符
   Hashes of expected file:
    - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
    - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
    - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
    - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
    - Filesize:9029488 [weak]
   Hashes of received file:
    - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
    - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
    - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
    - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
    - Filesize:9029488 [weak]
   Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
```
debian的还有点问题

**Comment by jiegec** [comment]
> ```
> 获取:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm [9029 kB]
> 错误:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm
>   Hash 校验和不符
>   Hashes of expected file:
>    - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
>    - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
>    - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
>    - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
>    - Filesize:9029488 [weak]
>   Hashes of received file:
>    - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
>    - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
>    - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
>    - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
>    - Filesize:9029488 [weak]
>   Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
> 已下载 9029 kB，耗时 1秒 (10.9 MB/s)
> E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  Hash 校验和不符
>    Hashes of expected file:
>     - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
>     - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
>     - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
>     - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
>     - Filesize:9029488 [weak]
>    Hashes of received file:
>     - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
>     - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
>     - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
>     - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
>     - Filesize:9029488 [weak]
>    Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
> E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
> ```
> 
> debian的还有点问题

已解决

**Comment by lishunan246** [comment]
> > ```
> > 获取:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm [9029 kB]
> > 错误:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.6-1~debian.12~bookworm
> >   Hash 校验和不符
> >   Hashes of expected file:
> >    - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
> >    - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
> >    - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
> >    - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
> >    - Filesize:9029488 [weak]
> >   Hashes of received file:
> >    - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
> >    - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
> >    - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
> >    - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
> >    - Filesize:9029488 [weak]
> >   Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
> > 已下载 9029 kB，耗时 1秒 (10.9 MB/s)
> > E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  Hash 校验和不符
> >    Hashes of expected file:
> >     - SHA512:3a594269b05133c82ca97b017ec21bac24afc30fdf9e3c46d00797a4cc28613608b3e120a91872bd2e7335c7579ac300b927c4c6ef18914f6ea1c870bb49e871
> >     - SHA256:e9ae9b8c0cd732582e459d2e18770ad475b7efc6649ae07e12fd52fa58418e02
> >     - SHA1:e07a3bcaf38e485d72ec57d2d5c93dae06e447f1 [weak]
> >     - MD5Sum:451759f2c70e6bcb4d1c6c405cc7ccb1 [weak]
> >     - Filesize:9029488 [weak]
> >    Hashes of received file:
> >     - SHA512:fed8cd8f199b1f53d8d5b76abc9287fd3250775787bd18d2a77fadc9c07630938aac32591d4d24fcddcd09a3900b485f28d2b7c46fa0eadd93a2caa7a7e7ac21
> >     - SHA256:912acdee314fa5245599e7b03fcacc1eec08e00e71e26fe689c35e3fd89e9bb3
> >     - SHA1:4dd97f3013ef6cf1aeae401a5380a26b4ea15487 [weak]
> >     - MD5Sum:adb71a4983115c61428c87d1856e32bf [weak]
> >     - Filesize:9029488 [weak]
> >    Last modification reported: Tue, 05 Sep 2023 19:27:27 +0000
> > E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > debian的还有点问题
> 
> 已解决

验证ok了，感谢

**Comment by miauyo** [comment]
Get:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 containerd.io amd64 1.6.33-1 [30.0 MB]
Err:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 containerd.io amd64 1.6.33-1
  File has unexpected size (14680064 != 29989528). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - SHA512:63c107173101fded661180389697eed4c2aaad849a731e56980eb99b4f4595afdf53c7640aa7ebb281736a08f2951cb8156eb20d109a82395a5a62ceaa1048bb
   - SHA256:b52824b48e25d31a99f2d5b00b53e09698bc52d8718d3e2e4d0b5afea60d8d14
   - SHA1:4a4a8339dad6148cca8f4fb026b5a308f15ba6de [weak]
   - MD5Sum:a2e15b725c61e85694b784d051502906 [weak]
   - Filesize:29989528 [weak]
Get:2 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-buildx-plugin amd64 0.14.1-1~debian.12~bookworm [29.6 MB]
Err:2 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-buildx-plugin amd64 0.14.1-1~debian.12~bookworm
  File has unexpected size (10485760 != 29644668). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - SHA512:e2b822a5ec527e5de9d51413b391bbcdf5622bb9c714b67750ad069aedc3a311e0dcf246dcc0c21c809ea59bcad5a5d4acce3ad95b83fcf66a52d0bf32513ccb
   - SHA256:941e206fbf2ddeec0b902f5abbfcb5d702301f99559e1e8578023e04b98a3d4b
   - SHA1:6cd201bfacfac78fb6d9a87637ffdd2cafbf3829 [weak]
   - MD5Sum:6fc936174695f1026cf69797d27247e6 [weak]
   - Filesize:29644668 [weak]
Get:3 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce amd64 5:26.1.4-1~debian.12~bookworm [25.3 MB]
Err:3 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce amd64 5:26.1.4-1~debian.12~bookworm
  File has unexpected size (18874368 != 25262432). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - SHA512:d53e70aa96dc4724dba3d56dac44b5d73d145e5c22f32cf102b69bb7d1561058c2fe1abddd91e50ed9290fa3f7abe4adfaf6a3a095111ac1886ff77e9e669ebc
   - SHA256:602b5fcecb4359b79fbb6abc63805d12e7c75abcceed6f01bef2a6d22438da99
   - SHA1:c253945fde6ac04a546cbece8281d0ab4b921e2a [weak]
   - MD5Sum:18653d664e36f480b2109e73609c1002 [weak]
   - Filesize:25262432 [weak]
Get:4 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:26.1.4-1~debian.12~bookworm [9,316 kB]
Err:4 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:26.1.4-1~debian.12~bookworm
  File has unexpected size (1048576 != 9316050). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - SHA512:3ca8e82b5e00dfc0c7201cf38ead23b813b21a6314d1b80a953867710eab584d9c5753aa2d43a405154454ba983685b5a6e8ba78315793df04bac9f524e41898
   - SHA256:9d323b32fff351caeb24b4dcf52a7af4be9a88c32f3d49e6ef11a01112e7d6ed
   - SHA1:c36eb703045dcf341f718fc718aa913f28039870 [weak]
   - MD5Sum:0e97fc3f5910242c39cff8b42652381b [weak]
   - Filesize:9316050 [weak]
Get:5 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-compose-plugin amd64 2.27.1-1~debian.12~bookworm [12.5 MB]
Err:5 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-compose-plugin amd64 2.27.1-1~debian.12~bookworm
  File has unexpected size (6291456 != 12494496). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - SHA512:06926b47bcb28d85a2a92c6ade01b60eb11de4f292e87a170704d674f0f10a457506192b339fd755c5e0f1cd7c7f7ec56d818b743ebae7f4098eca089b87fd96
   - SHA256:22a105bbc6ff429526a69ec7defc9c79783eb89cb81f575b2b55645943592168
   - SHA1:358d1c55eaf4d6043c26f5c2427b63fe52c052c6 [weak]
   - MD5Sum:07317ed6b8cf7415002203e5ef2c1dce [weak]
   - Filesize:12494496 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/containerd.io_1.6.33-1_amd64.deb  File has unexpected size (14680064 != 29989528). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - SHA512:63c107173101fded661180389697eed4c2aaad849a731e56980eb99b4f4595afdf53c7640aa7ebb281736a08f2951cb8156eb20d109a82395a5a62ceaa1048bb
    - SHA256:b52824b48e25d31a99f2d5b00b53e09698bc52d8718d3e2e4d0b5afea60d8d14
    - SHA1:4a4a8339dad6148cca8f4fb026b5a308f15ba6de [weak]
    - MD5Sum:a2e15b725c61e85694b784d051502906 [weak]
    - Filesize:29989528 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-buildx-plugin_0.14.1-1%7edebian.12%7ebookworm_amd64.deb  File has unexpected size (10485760 != 29644668). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - SHA512:e2b822a5ec527e5de9d51413b391bbcdf5622bb9c714b67750ad069aedc3a311e0dcf246dcc0c21c809ea59bcad5a5d4acce3ad95b83fcf66a52d0bf32513ccb
    - SHA256:941e206fbf2ddeec0b902f5abbfcb5d702301f99559e1e8578023e04b98a3d4b
    - SHA1:6cd201bfacfac78fb6d9a87637ffdd2cafbf3829 [weak]
    - MD5Sum:6fc936174695f1026cf69797d27247e6 [weak]
    - Filesize:29644668 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce_26.1.4-1%7edebian.12%7ebookworm_amd64.deb  File has unexpected size (18874368 != 25262432). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - SHA512:d53e70aa96dc4724dba3d56dac44b5d73d145e5c22f32cf102b69bb7d1561058c2fe1abddd91e50ed9290fa3f7abe4adfaf6a3a095111ac1886ff77e9e669ebc
    - SHA256:602b5fcecb4359b79fbb6abc63805d12e7c75abcceed6f01bef2a6d22438da99
    - SHA1:c253945fde6ac04a546cbece8281d0ab4b921e2a [weak]
    - MD5Sum:18653d664e36f480b2109e73609c1002 [weak]
    - Filesize:25262432 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_26.1.4-1%7edebian.12%7ebookworm_amd64.deb  File has unexpected size (1048576 != 9316050). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - SHA512:3ca8e82b5e00dfc0c7201cf38ead23b813b21a6314d1b80a953867710eab584d9c5753aa2d43a405154454ba983685b5a6e8ba78315793df04bac9f524e41898
    - SHA256:9d323b32fff351caeb24b4dcf52a7af4be9a88c32f3d49e6ef11a01112e7d6ed
    - SHA1:c36eb703045dcf341f718fc718aa913f28039870 [weak]
    - MD5Sum:0e97fc3f5910242c39cff8b42652381b [weak]
    - Filesize:9316050 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-compose-plugin_2.27.1-1%7edebian.12%7ebookworm_amd64.deb  File has unexpected size (6291456 != 12494496). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - SHA512:06926b47bcb28d85a2a92c6ade01b60eb11de4f292e87a170704d674f0f10a457506192b339fd755c5e0f1cd7c7f7ec56d818b743ebae7f4098eca089b87fd96
    - SHA256:22a105bbc6ff429526a69ec7defc9c79783eb89cb81f575b2b55645943592168
    - SHA1:358d1c55eaf4d6043c26f5c2427b63fe52c052c6 [weak]
    - MD5Sum:07317ed6b8cf7415002203e5ef2c1dce [weak]
    - Filesize:12494496 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by chacha20** [comment]
+1
`deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian   bookworm stable`
日志输出是docker-ce-rootless-extra这个包的文件大小不对：
`Get:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:26.1.4-1~debian.12~bookworm [9,316 kB]
Err:1 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:26.1.4-1~debian.12~bookworm
  File has unexpected size (1048576 != 9316050). Mirror sync in progress? [IP: 2402:f000:1:400::2 443]
  Hashes of expected file:
   - SHA512:3ca8e82b5e00dfc0c7201cf38ead23b813b21a6314d1b80a953867710eab584d9c5753aa2d43a405154454ba983685b5a6e8ba78315793df04bac9f524e41898
   - SHA256:9d323b32fff351caeb24b4dcf52a7af4be9a88c32f3d49e6ef11a01112e7d6ed
   - SHA1:c36eb703045dcf341f718fc718aa913f28039870 [weak]
   - MD5Sum:0e97fc3f5910242c39cff8b42652381b [weak]
   - Filesize:9316050 [weak]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_26.1.4-1%7edebian.12%7ebookworm_amd64.deb  File has unexpected size (1048576 != 9316050). Mirror sync in progress? [IP: 2402:f000:1:400::2 443]
   Hashes of expected file:
    - SHA512:3ca8e82b5e00dfc0c7201cf38ead23b813b21a6314d1b80a953867710eab584d9c5753aa2d43a405154454ba983685b5a6e8ba78315793df04bac9f524e41898
    - SHA256:9d323b32fff351caeb24b4dcf52a7af4be9a88c32f3d49e6ef11a01112e7d6ed
    - SHA1:c36eb703045dcf341f718fc718aa913f28039870 [weak]
    - MD5Sum:0e97fc3f5910242c39cff8b42652381b [weak]
    - Filesize:9316050 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by shankerwangmiao** [comment]
这个文件的问题也已经修理了。

**Comment by 89ao** [comment]
> 这个文件的问题也已经修理了。

shanker好，这里的修理，是指数据重新同步，还是有逻辑避免不可用的同步数据再上线呢？

**Comment by shankerwangmiao** [comment]
> > 这个文件的问题也已经修理了。
> 
> shanker好，这里的修理，是指数据重新同步，还是有逻辑避免不可用的同步数据再上线呢？

目前只针对出现异常的文件重新同步了。受限于存储性能，无法在每次同步时都对所有文件进行校验。
