### ISSUE TITLE
wsl的ubuntu无法访问ipv4镜像

### ISSUE THREAD

**Issue by zzw-111-bit** [tuna/issues#1823]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

wsl中访问镜像网站只能使用ipv4，使用sudo apt update的时候，会自动访问ipv6的地址，并且手动指定ipv4无法访问

### 期望的现象（What you expected to happen）

可以通过ipv4访问镜像网站

### 如何重现此问题（How to reproduce it）

使用sudo apt update命令

### 操作系统（OS Version）

ubuntu18.04

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

win10+wsl2

### 其他需要说明的事项（Anything else we need to know）

更换原来ubuntu的默认镜像源

**Comment by shankerwangmiao** [comment]
请提供具体 sources.list 的配置和 apt 命令的输出

**Comment by zzw-111-bit** [comment]
> 请提供具体 sources.list 的配置和 apt 命令的输出

/etc/apt/sources.list.d/ros2.list的配置：deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu jammy main

apt命令执行之后：
Ign:17 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu jammy InRelease
Ign:17 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu jammy InRelease
Ign:17 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu jammy InRelease
Err:17 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu jammy InRelease
  Cannot initiate the connection to mirrors.tuna.tsinghua.edu.cn:443 (2402:f000:1:400::2). - connect (101: Network is unreachable) Could not connect to mirrors.tuna.tsinghua.edu.cn:443 (101.6.15.130), connection timed out
Fetched 5734 kB in 38s (152 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
36 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/dists/jammy/InRelease  Cannot initiate the connection to mirrors.tuna.tsinghua.edu.cn:443 (2402:f000:1:400::2). - connect (101: Network is unreachable) Could not connect to mirrors.tuna.tsinghua.edu.cn:443 (101.6.15.130), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by shankerwangmiao** [comment]
您好，从 apt 命令输出来看，您的 WSL 环境内无法连接 TUNA 镜像站。建议您排查 WSL 内网络是否正常，同时排查您本机的网络是否能访问 TUNA 镜像站。

该问题与 IPv6 无关，根据日志显示，其同时尝试连接 IPv4 和 IPv6，而二者都未能连通。
