### ISSUE TITLE
aosp-latest.tar下载下来很小，只有2761字节

### ISSUE THREAD

**Issue by bu2zhouzhu** [tuna/issues#1824]
使用 `curl -OC - https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-latest.tar` 命令下载下来的 `aosp-latest.tar` 文件只有 2761B 大小，1秒就下载完了。请问这是怎么回事呢，要怎么解决呢？
![1](https://github.com/tuna/issues/assets/7880389/5c205594-1ed7-4ddd-a5fa-1835990337ac)

**Comment by shankerwangmiao** [comment]
请注意 curl 的输出，可以看到从服务器返回的状态码是 403，因此意味着请求被阻断了。您可以观察响应体结尾处的标识代码，以便我们进一步诊断。

**Comment by qianbinbin** [comment]
用 curl 下载后是一个 html 文件，内容是
> 我们检测到您所在的子网和/或所使用的客户端存在大量下载某些较大二进制文件的行为，为保证用户的正常使用，我们阻断了此类请求。

估计是当成爬虫禁了

指定 UA 后可以下载，比如 `-A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"`
