### ISSUE TITLE
OUT_OF_MEMORY in /pypi/web/pypi/

### ISSUE THREAD

**Issue by biggycao** [tuna/issues#1825]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在 /pypi/web/pypi/ 中的文件过多，导致RAM被占满，最后报错OUT_OF_MEMORY

### 期望的现象（What you expected to happen）

减少该目录下的文件

### 如何重现此问题（How to reproduce it）

用任意浏览器（最好是Chromium内核的）打开
https://mirrors.tuna.tsinghua.edu.cn/pypi/web/pypi/wheel/

### 操作系统（OS Version）

Windows 11 23H2 (25951.1000)

### 浏览器（如果适用）（Browser version, if applicable）

Edge & Chrome

### 其他环境（Other environments）

-

### 其他需要说明的事项（Anything else we need to know）

-

**Comment by Harry-Chen** [comment]
此目录不是供浏览使用的，TUNA 作为镜像站，原则上不能更改来自上游的内容。

**Comment by yaoge123** [comment]
换个OS和浏览器在1T内存的机器上测试https://mirror.nju.edu.cn/pypi/web/pypi/正常
