### ISSUE TITLE
Nodejs镜像的使用帮助有误

### ISSUE THREAD

**Issue by niaodan2b** [tuna/issues#1828]
在[Nodejs Release 镜像使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/nodejs-release/)中的`volta`一节，给出的模版文件名是`node-v{{version}}-{{os}}-{{arch}}.tar.gz`，但按此配置在Windows下是无法获取到对应文件的，因为Nodejs Release上面的Windows压缩包只有zip和7z格式。

![](https://i.imgur.com/apWi7Jf.png)

（奇怪的是，我以前就按这个文档配置，一直没有问题，最近才发现获取不到。但是翻看了Nodejs Release上面的以前版本，一直都没有Windows的tar.gz包，并非最近的改动。不排除是我记错了。）

**Comment by shankerwangmiao** [comment]
volta 的配置可能确实存在这个问题，你要不直接给 https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/nodejs-release.mdx  这个提交个 PR？

**Comment by Harry-Chen** [comment]
Fixed in https://github.com/mirrorz-org/mirrorz-help/commit/7a3b783c31e3c773af81f947e1dd07d4923efdf8
