### ISSUE TITLE
archlinux安装octave时文件openmpi获取失败，404

### ISSUE THREAD

**Issue by Toocc** [tuna/issues#183]
系统：archlinux
镜像：mirrors-i.tuna.tsinghua.edu.cn
问题：pacman 安装 octave时文件openmpi-1.10.4-1-x86_64.pkg.tar.xz获取失败
描述：error: failed retrieving file 'openmpi-1.10.4-1-x86_64.pkg.tar.xz' from mirrors-i.tuna.tsinghua.edu.cn : The requested URL returned error: 404

**Comment by huiyiqun** [comment]
但是我这里是正常的。

https://mirrors-i.tuna.tsinghua.edu.cn/archlinux/extra/os/x86_64/openmpi-1.10.5-1-x86_64.pkg.tar.xz

你看看能直接下载这个文件吗？

**Comment by huiyiqun** [comment]
我知道了 是因为你安装之前没有
```
-> sudo pacman -Sy
```

**Comment by Toocc** [comment]
嗯，好了，谢谢
