### ISSUE TITLE
esl-erlang版本未与erlang官网同步

### ISSUE THREAD

**Issue by wxmeng04** [tuna/issues#1830]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

这貌似是镜像没有同步。
tuna镜像最新版本是：
https://mirrors.tuna.tsinghua.edu.cn/erlang-solutions/debian/pool/esl-erlang_25.3-2~debian~bullseye_amd64.deb
erlang-solution官方最新esl-erlang下载链接：
https://binaries2.erlang-solutions.com/debian/pool/contrib/e/esl-erlang/esl-erlang_26.0.2-1~debian~bullseye_amd64.deb
erlang-solution官方网站地址：
不清楚下边两个是什么关系，但是都有26.0.2版本。https://github.com/esl/packages 这里解释说，下边那个是最新的。
https://www.erlang-solutions.com/downloads/
https://binaries2.erlang-solutions.com/#debian/pool/contrib/e/esl-erlang/

### 期望的现象（What you expected to happen）

同步最新版erlang

### 如何重现此问题（How to reproduce it）

见问题描述

### 操作系统（OS Version）

debian

**Comment by Harry-Chen** [comment]
erlang 上游从 packages.erlang-solutions.com 切换到了 binaries2.erlang-solutions.com，目录结构也有变化，需要重新编写脚本同步。

**Comment by Harry-Chen** [comment]
现在的目录结构是 

```
- debian
    - dists/{codename}-{product}-{version}
- ubuntu
    - dists/{codename}-{product}-{version}
- centos
    - {product}-{version}/repodata
```

其中 debian 包括 `stretch, buster, bullseye`, ubuntu 包括 `xenial, jammy, focal, bionic`，产品包括 `mongooseim-{5,6}`, `esl-erlang-{24,25,26}`, `elixir-1.{12,13,14,15}`。

同步应该不困难，但值得注意的是 centos 对应的 repodata 都是空的，例如 https://binaries2.erlang-solutions.com/#centos/esl-erlang-24/repodata/ 会导致什么也同步不下来（对于 rockylinux 也是一样的）。如果上游不解决此问题，则我们无法同步这些 RPM。

**Comment by Harry-Chen** [comment]
@wxmeng04 可以尝试一下，以下源是否正确（**地址仅供测试，未来很可能变化，请不要依赖**）：

```text
deb https://mirrors.tuna.tsinghua.edu.cn/erlang-new/debian bullseye-esl-erlang-26 contrib
deb https://mirrors.tuna.tsinghua.edu.cn/erlang-new/debian bullseye-elixir-1.15 contrib
deb https://mirrors.tuna.tsinghua.edu.cn/erlang-new/debian bullseye-mongooseim-6 contrib
```

同步的版本在上面有说明。根据我的测试，这些源因为依赖了太旧的 libssl，在 bookworm 是无法使用的。

**Comment by Harry-Chen** [comment]
TUNA 和 BFSU 镜像站已经切换到了新的上游，旧的上游随之下线。请参考（稍后更新）的帮助文档获取使用方法。

**Comment by wxmeng04** [comment]
好的，多谢了。

**Comment by wxmeng04** [comment]
还是没更新呀。官方的地址如下： 
https://binaries2.erlang-solutions.com/#debian/
