### ISSUE TITLE
bfsu 镜像站中大量镜像同步失败，疑似与硬盘空间不足有关

### ISSUE THREAD

**Issue by GalaxySnail** [tuna/issues#1831]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

如标题所述，近日 bfsu 镜像站中大量镜像同步失败，并且在服务器状态页面上看到硬盘空间几乎耗尽。

![](https://github.com/tuna/issues/assets/53637421/eae2c3b5-3f1a-40ff-b86c-c9fb545e315e)
![](https://github.com/tuna/issues/assets/53637421/b2731a4c-4940-4f4e-90dd-d327ac422bde)

### 期望的现象（What you expected to happen）

镜像成功同步

### 如何重现此问题（How to reproduce it）

在 bfsu 镜像站的网页上即可观察到

**Comment by Harry-Chen** [comment]
感谢提醒，我们注意到了此问题，并会尝试移除一些不常用镜像来缓解此问题。

**Comment by Harry-Chen** [comment]
目前同步正在逐步恢复中。
