### ISSUE TITLE
[镜像请求] 请求添加huggingface镜像

### ISSUE THREAD

**Issue by xiehuanyi** [tuna/issues#1833]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

huggingface是一个模型托管的平台，几乎现在所有主流的开源大模型权重都在上面。但是国内目前几乎无法访问，严重影响了国内NLP开发者的工作效率，甚至在一些不方便使用科学上网的环境下（例如服务器中）huggingface完全无法访问，只能先下载到本地，在上传，而且随着LLM的爆火，现在的模型体积越来越大，下载到本地上传服务器的成本也越来越高。所以我请求添加huggingface镜像，这将极大的提高国内NLP研究者的开发效率，同时，也可以为一些对LLM和SD感兴趣的同学提供极大的方便。

### 上游地址与镜像方法 (How to mirror)

https://huggingface.co/

### 期望上线的镜像站 (Expected mirroring sites)

- [ ] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn
- [ ] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/937#issuecomment-1519522616

**Comment by Harry-Chen** [comment]
duplicated
