### ISSUE TITLE
[镜像请求] RWKV模型 / RWKV model

### ISSUE THREAD

**Issue by Triang-jyed-driung** [tuna/issues#1836]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

RWKV是RNN模型，由国内的AI创业者彭博开发，它具有与Transformer相当的语言模型性能，而且可以像GPT一样并行化地训练。它结合了RNN和Transformer的优点，具有高性能、快速推理、快速训练、节省显存、无限上下文长度等特点，并且100%免注意力机制。

RWKV遵循Apache 2.0协议，这是一个开源可商用的协议，允许镜像。

最近，RWKV已经被Linux Foundation AI & Data基金会选中，成为首个入选Generative AI Commons的模型。（https://lfaidata.foundation/blog/2023/09/21/lf-ai-data-launches-generative-ai-commons/）

论文链接：https://arxiv.org/abs/2305.13048

RWKV is an RNN architecture developed by Chinese AI entrepreneur Bo Peng. It has a performance comparable to Transformers and can be trained in parallel like GPT. It combines the advantages of RNNs and Transformers, with the advantages of high performance, fast inference, fast training, memory-saving, infinite context length, and is 100% attention-free.

RWKV follows the Apache 2.0 license, which is an open source and commercial friendly protocol that allows mirroring.

Recently, RWKV has been accepted by the Linux Foundation AI & Data Foundation, becoming the first model selected into Generative AI Commons. (https://lfaidata.foundation/blog/2023/09/21/lf-ai-data-launches-generative-ai-commons/)

Link to RWKV paper: https://arxiv.org/abs/2305.13048

### 上游地址与镜像方法 (How to mirror)

有很多模型，我觉得以下就够了。
There are older models, but these are sufficient:

RWKV Raven (version 4): https://huggingface.co/BlinkDL/rwkv-4-raven/tree/main
RWKV World (version 4): https://huggingface.co/BlinkDL/rwkv-4-world/tree/main
RWKV Music (version 4): https://huggingface.co/BlinkDL/rwkv-4-music/tree/main
RWKV World (version 5, training in progress): https://huggingface.co/BlinkDL/rwkv-5-world/tree/main
RWKV Music (version 5): https://huggingface.co/BlinkDL/rwkv-5-music/tree/main

All models are located under https://huggingface.co/BlinkDL which is the official distribution site. 

Models can either be downloaded directly or via Git.

### 镜像大小 (Mirror size)

目前这些模型总量约183GB，但随着后期更多模型训练完成，总量会增加。

Currently existing models in these repositories add up to 183GB in total, but will increase as more models finish training later.

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
Hugging face 相关内容在 #937 有讨论，我们暂不考虑单独镜像其中的内容，目前也没有这样的能力。
