### ISSUE TITLE
Kubernetes 镜像源需要更新

### ISSUE THREAD

**Issue by ajl520** [tuna/issues#1837]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Kubernetes 官方宣布启用新的官方源地址：pkgs.k8s.io
参考官方说明：
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

### 期望的现象（What you expected to happen）

将现有镜像的源更新为最新源

### 如何重现此问题（How to reproduce it）

官方已宣布计划从2023 年 9 月 13 日起冻结原存储库的内容。
https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

**Comment by ajl520** [comment]
https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/

**Comment by taoky** [comment]
Related discussion: https://github.com/ustclug/discussions/issues/433

**Comment by Harry-Chen** [comment]
由于上游的重大变更，我们将考虑移除相关镜像。

**Comment by Harry-Chen** [comment]
Kubernetes 镜像已经移除。

**Comment by Harry-Chen** [comment]
目前 kubernetes 镜像已经重新上线，上游更改为 `rsync://rsync.opensuse.org/buildservice-repos-main/isv:/kubernetes:/`
