### ISSUE TITLE
OpenVSX

### ISSUE THREAD

**Issue by goddaneel** [tuna/issues#1838]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Open VSX Registry

Open VSX Registry 是 VS Code 的开源扩展商店。 任何支持此类扩展的开发环境都可以使用它。 
该服务由Eclipse 基金会运营 。

### 上游地址与镜像方法 (How to mirror)

https://open-vsx.org/

### 备注 (Note)

源替换参考指南
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-openvsx-marketplace

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by Harry-Chen** [comment]
商店并没有提供可行的镜像方式，我认为在现阶段也没有镜像的价值。
