### ISSUE TITLE
建议添加Solus Linux发行版的镜像。

### ISSUE THREAD

**Issue by Chao-zhi** [tuna/issues#184]
#### 项目名称与简介(Project Intro.)

Solus Linux发行版镜像

Solus是一个新兴的Linux发行版，它简洁优雅快速，他有着独立的软件包管理方案，是一个活动发行版。十分十分值得为他提供一个镜像。

#### 上游地址与镜像方法(How to Mirror)

官网在这https://solus-project.com/

包镜像没找到-_-||，想来你们应该有办法，，，

#### 其他信息(Other)
- 镜像大小(Mirror Size): 不晓得

**Comment by huiyiqun** [comment]
**独立的软件包管理方案** 具体是什么。。

另外也没有找到wiki，没找到downloads，爱莫能助啊。

**Comment by bigeagle** [comment]
同…… 找了一圈不知道如何镜像…

**Comment by Chao-zhi** [comment]
好吧，可能是太新了，还没有第三方的镜像。

**Comment by gaoyichuan** [comment]
在官方forum发了帖子，看他们的回复吧
[https://solus-project.com/forums/viewtopic.php?f=14&p=13421#p13421](url)

**Comment by shankerwangmiao** [comment]
赞

**Comment by kosmosoahc** [comment]
这里有个包的 https://packages.solus-project.com/

**Comment by huiyiqun** [comment]
有rsync 也有ipv6 不过有ACL 得他们添加白名单才能同步

**Comment by huiyiqun** [comment]
@gaoyichuan 他们回邮件了吗？

**Comment by gaoyichuan** [comment]
并没有，，我重新发一封吧

**Comment by kosmosoahc** [comment]
他有给你们回复邮件吗？ikey.doherty@gmail.com 给我回信息说暂时还没有收到你们的信息。

**Comment by gaoyichuan** [comment]
@kosmosoahc 我很久以前发的邮件，就是给这个email，大概他们没看见吧。。

**Comment by kosmosoahc** [comment]
他们表示没有收到邮件耶
https://solus-project.com/forums/viewtopic.php?f=14&p=13421#p13421

**Comment by huiyiqun** [comment]
@gaoyichuan 有时间再发一封邮件？

**Comment by hashhsah** [comment]
刚刚迁移到solus, 期待国内的mirror~

**Comment by hashhsah** [comment]
写信到 ikey.doherty@gmail.com 问进展，回复如下：

> I've had multiple queries from the TUNA team, and responded each time, and then the conversation has gone
> dead. For us to list a mirror on our site would require knowing that the mirror could sufficiently host and meet
> the requirements, i.e. in terms of storage capacity and bandwidth.
> 
> Our repository fluctuates rapidly in size, and today is 97GB with hard linking. Without, it is significantly more.
> We have an rsync target on archive.solus-project.com. The default account has a password restriction, though
> we can (and have) create accounts based on IP addresses without passwords for the TUNA mirror.
> The default combination is mirror:mirror on target archive.solus-project.com:packages, and should be used
> with the relevant rsync flags (i.e. `-avzHL --delete`)
> 
> Cheers
> 
> - Ikey (Solus Founder)

**Comment by shankerwangmiao** [comment]
这邮件不通真是💊

**Comment by Harry-Chen** [comment]
所以我们现在应该直接和负责人联系吧？看起来他们回的邮件我们收不到。

**Comment by hashhsah** [comment]
@Harry-Chen 我不介意临时传个话。但长远看还是需要TUNA团队把邮箱问题解决好。

我们公司的邮件服务器也在国内，收发gmail都是畅通的。

**Comment by shankerwangmiao** [comment]
@hashhsah 感谢帮忙，邮件请抄 mirrors@tuna.tsinghua.edu.cn

我们的邮件服务器是托管在 office 365  上，这是第一起邮件不通的 case，我表示很疑惑。

**Comment by hashhsah** [comment]
@shankerwangmiao  请查收来邮件。

**Comment by shankerwangmiao** [comment]
@hashhsah 已经同步完毕并上线。

另请帮忙联系上游，让他们确认一下 archive.solus-project.com 这个服务器的 ipv6 是不是出了问题。如果他们的 v6 不修理好，或者不把 v6 地址从 DNS 记录里去掉的话，我们这边没法更新同步

**Comment by hashhsah** [comment]
@shankerwangmiao 方便把你这里看到的关于ipv6的错误信息贴给我么？

**Comment by huiyiqun** [comment]
@shankerwangmiao 先走v4吧

**Comment by shankerwangmiao** [comment]
@hashhsah ipv6 地址直接 ping 不通，没有响应。

**Comment by lowy** [comment]
国内镜像源能用了吗？

**Comment by shankerwangmiao** [comment]
目前的状态是初始同步成功，但是没法更新，等待上游修理他们的服务器的 ipv6 的问题

**Comment by hashhsah** [comment]
solus的ikey表示会暂时去掉 ipv6 AAAA记录。等下再看是否能更新了。

**Comment by shankerwangmiao** [comment]
多谢！

**Comment by shankerwangmiao** [comment]
同步完成
