### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by onepiecettt** [tuna/issues#1840]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

树莓派bookworm软件源

### 上游地址与镜像方法 (How to mirror)

  1 deb [ arch=armhf ] http://raspbian.raspberrypi.com/raspbian/ bookworm main contrib non-free rpi 

### 镜像大小 (Mirror size)

1.2G

### 备注 (Note)

使用Debian12报错

pi@raspberrypi:~ $ sudo apt update
Get:1 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease [151 kB]
Get:2 https://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease [52.1 kB]
Get:4 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease [56.5 kB]
Get:5 https://mirrors.tuna.tsinghua.edu.cn/raspberrypi bullseye InRelease [23.6 kB]
Err:1 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
Err:3 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Err:2 https://security.debian.org/debian-security bookworm-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
Err:4 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Reading package lists... Done
W: GPG error: https://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://security.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'https://security.debian.org/debian-security bookworm-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
从错误信息看，和 http://raspbian.raspberrypi.com/raspbian/ 没有任何关系。

```
 W: GPG error: https://security.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
```

需要检查是否正确安装了 keyring。

**Comment by onepiecettt** [comment]
因为我看树莓派的新软件源还没有更新，所以我使用的是Debian12的软件源
我通过指令添加缺少的公钥，首先要一个个添加，添加后报错得以解决，但是这个更新速度太慢了
![image](https://github.com/tuna/issues/assets/147893670/81821eba-dc85-40d6-ad76-507ca8e31a1c)
![image](https://github.com/tuna/issues/assets/147893670/f86fbeed-5eb9-4ba3-8a73-fcb1edf5f223)

pi@raspberrypi:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 54404762BBB6E853 BDE6D2B9216EC7A8
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.3jnEO7di4F/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 54404762BBB6E853 BDE6D2B9216EC7A8
gpg: key 254CF3B5AEC0A8F0: public key "Debian Security Archive Automatic Signing Key (12/bookworm) <ftpmaster@debian.org>" imported
gpg: key A48449044AAD5C5D: public key "Debian Security Archive Automatic Signing Key (11/bullseye) <ftpmaster@debian.org>" imported
gpg: Total number processed: 2
gpg:               imported: 2
pi@raspberrypi:~ $ sudo apt update
Get:1 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease [151 kB]
Get:2 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease [52.1 kB]                       
Get:3 https://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease [56.5 kB]                       
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease                                                 
Get:5 https://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]                                                            
Ign:6 https://security.debian.org/debian-security bookworm-security/main armhf Packages                                                            
Get:7 https://security.debian.org/debian-security bookworm-security/main arm64 Packages [79.5 kB]
Ign:7 https://security.debian.org/debian-security bookworm-security/main arm64 Packages
Get:8 https://security.debian.org/debian-security bookworm-security/main Translation-en [46.7 kB]
Ign:8 https://security.debian.org/debian-security bookworm-security/main Translation-en
Get:9 https://security.debian.org/debian-security bookworm-security/non-free-firmware Translation-en [472 B]
Get:6 https://security.debian.org/debian-security bookworm-security/main armhf Packages [77.0 kB]
Get:7 https://security.debian.org/debian-security bookworm-security/main arm64 Packages [79.5 kB]                                                  
Get:8 https://security.debian.org/debian-security bookworm-security/main Translation-en [46.7 kB]                                                  
Ign:8 https://security.debian.org/debian-security bookworm-security/main Translation-en                                                            
Get:8 https://security.debian.org/debian-security bookworm-security/main Translation-en [46.7 kB]
Fetched 463 kB in 6min 9s (1,254 B/s)                                                                                                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
715 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://mirrors.tuna.tsinghua.edu.cn/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://mirrors.tuna.tsinghua.edu.cn/debian/dists/bookworm-updates/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://mirrors.tuna.tsinghua.edu.cn/debian/dists/bookworm-backports/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://security.debian.org/debian-security/dists/bookworm-security/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by onepiecettt** [comment]
后面的更新也是一样的，260KB的大小用时1分14秒。。。
![image](https://github.com/tuna/issues/assets/147893670/56b6d13f-5db0-4fa0-ae48-c60b29a5194f)

**Comment by taoky** [comment]
> 因为我看树莓派的新软件源还没有更新

有，只是帮助没更新。

**Comment by onepiecettt** [comment]
> > 因为我看树莓派的新软件源还没有更新
> 
> 有，只是帮助没更新。

好的，我现在去主页看看

**Comment by onepiecettt** [comment]
还没更新到帮助？？？

**Comment by Harry-Chen** [comment]
> 还没更新到帮助？？？

该评论违反了[行为准则](https://github.com/tuna/issues/blob/master/CODE_OF_CONDUCT.md)，这是一次正式的警告。

此外，如果使用 TUNA 速度过慢，建议更换其他镜像站，详见 <https://mirrors.cernet.edu.cn/>
