### ISSUE TITLE
BFSU的Arch Linux仓库同步异常

### ISSUE THREAD

**Issue by Bryan2333** [tuna/issues#1842]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![图片](https://github.com/tuna/issues/assets/31512600/5a625f66-48d5-4c98-8546-4975c1c02355)

截止到2023/10/20 15:10 已超过一天未能正常同步

### 期望的现象（What you expected to happen）

Arch Linux仓库可以正常同步

### 如何重现此问题（How to reproduce it）

无

**Comment by Harry-Chen** [comment]
由于 BFSU 服务器的一些网络问题，同步开始产生堆积。我们正在解决此问题。
