### ISSUE TITLE
Adoptium的jdk11镜像消失（？）

### ISSUE THREAD

**Issue by AGH11111** [tuna/issues#1843]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

今天准备下载jdk11时发现win、macos、linux的java11包都不见了，除alpine-linux外

### 期望的现象（What you expected to happen）

重新补充镜像

### 如何重现此问题（How to reproduce it）

IDK

### 操作系统（OS Version）

ArchLinux x86_64

### 浏览器（如果适用）（Browser version, if applicable）

Google Chrome 118.0.5993.70（正式版本）

**Comment by jiegec** [comment]
因为网络问题，新的jdk11版本没下载成功，旧的被gc了。正在尝试处理。

**Comment by jiegec** [comment]
已经恢复。
