### ISSUE TITLE
关于debian镜像源Release文件的错误

### ISSUE THREAD

**Issue by xinmend** [tuna/issues#1845]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

“Origin: Debian Backports
Label: Debian Backports
Suite: bullseye-backports
Codename: bullseye-backports
Changelogs: https://metadata.ftp-master.debian.org/changelogs/@CHANGEPATH@_changelog
Date: Tue, 31 Oct 2023 08:09:38 UTC
Valid-Until: Tue, 07 Nov 2023 08:09:38 UTC
NotAutomatic: yes
ButAutomaticUpgrades: yes
Acquire-By-Hash: yes
No-Support-for-Architecture-all: Packages
Architectures: all amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x
Components: main contrib non-free
Description: Debian 11 - Backports
...”
这来自”mirrors.tuna.tsinghua.edu.cn/debian/dists/oldstable-backports/Release“文件
理应是oldstable的Release文件 现在被错误的替换成了bullseye的Release文件

### 期望的现象（What you expected to happen）

Release文件变为oldstable的 而不再是现在的bullseye版本

### 如何重现此问题（How to reproduce it）

使用debian操作系统
更改或注释其他镜像源后添加apt镜像源配置( /etc/apt/sources.list )如下
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ oldstable main contrib non-free
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ oldstable-updates main contrib non-free
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ oldstable-backports main contrib non-free
deb https://mirrors.tuna.tsinghua.edu.cn/debian-security oldstable-updates main contrib non-free

### 操作系统（OS Version）

debian

### 其他需要说明的事项（Anything else we need to know）

请快点修改 因为某些老版本因为此镜像源可能无法apt update

(包括新版本因某些原因要获取老版本的软件包

**Comment by taoky** [comment]
bullseye 就是 oldstable，现在的 stable 是 bookworm。
