### ISSUE TITLE
flutter 源的同步有点问题

### ISSUE THREAD

**Issue by Nekobaex** [tuna/issues#1848]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[flutter 镜像](https://mirrors.tuna.tsinghua.edu.cn/flutter/) 在表面上更新比较及时, 但里面的文件, 最新的仍是 2023-3-12 的:  

![image](https://github.com/tuna/issues/assets/89440464/0273a297-a0f9-4ff2-a5af-9e4c33f3a38c)

而且有一个类似的问题, 可能和这个有关:  

![image](https://github.com/tuna/issues/assets/89440464/f9834b6b-5079-4cb9-a881-41cf51cce086)

切换并下载 flutter beta 版本时, 可以访问到源仓库, 但又会跳到 github, 导致无法切换和更新

### 期望的现象（What you expected to happen）

希望能修复 flutter 源

### 如何重现此问题（How to reproduce it）

访问 [flutter 镜像](https://mirrors.tuna.tsinghua.edu.cn/flutter/)

使用 `flutter channel beta`

**Comment by Harry-Chen** [comment]
文件夹的更新时间不能说明问题，里面有更新的文件，如 <https://mirrors.tuna.tsinghua.edu.cn/flutter/dart-archive/channels/stable/release/3.1.5/>。

下图中切换失败和 TUNA 没有关系，你没有把 flutter-sdk 的下载也配置到镜像站，所以访问了 GitHub 导致失败。
