### ISSUE TITLE
lineageOS 源码镜像文档给出的 fetch url 地址错误

### ISSUE THREAD

**Issue by hitmoon** [tuna/issues#1849]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按照目前文档，如下lineage 的remote定义：
`
<remote  name="lineage"
           fetch="https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/"
           review="review.lineageos.org" />
`
sync 时报错

### 期望的现象（What you expected to happen）

能正常下载仓库

### 如何重现此问题（How to reproduce it）

按照 https://mirrors.tuna.tsinghua.edu.cn/help/lineageOS/ 文档操作即可复现

### 操作系统（OS Version）

linux

### 其他需要说明的事项（Anything else we need to know）

改成：
fetch="https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/" 
就可以正常下载了

**Comment by Harry-Chen** [comment]
欢迎提出 PR: https://github.com/tuna/mirror-web/blob/master/help/_posts/1970-01-01-lineageOS.md

**Comment by shankerwangmiao** [comment]
@hitmoon 请参考 #1867 ，我感觉这里的 `<remote>` 的 `fetch=` 不应该再加 `LineageOS` 后缀，你的修改是不正确的。请你再检查一下。

**Comment by shankerwangmiao** [comment]
该修改已经 revert。

**Comment by hitmoon** [comment]
> @hitmoon 请参考 #1867 ，我感觉这里的 `<remote>` 的 `fetch=` 不应该再加 `LineageOS` 后缀，你的修改是不正确的。请你再检查一下。

时间略久了，当时我遇到的情况是需要加的，现在不需要了就ok
