### ISSUE TITLE
tuna pypi  junoplatform包未被同步到最新

### ISSUE THREAD

**Issue by lzbgt** [tuna/issues#1851]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

tuna pypi 包未更新： junoplatform
例如： junoplatform 版本停止在1.2.0
pypi.org中该包版本为1.3.8

### 期望的现象（What you expected to happen）

同步最新官方包。 （按tuna文档里每5分钟）

### 如何重现此问题（How to reproduce it）

tuna中查看junoplatform最新版本为1.2.0： https://pypi.tuna.tsinghua.edu.cn/simple/junoplatform/ 
pypi中查看junoplatform最新版本为1.3.8： https://pypi.org/simple/junoplatform/

### 操作系统（OS Version）

any

### 浏览器（如果适用）（Browser version, if applicable）

any

### 其他环境（Other environments）

none

### 其他需要说明的事项（Anything else we need to know）

none

**Comment by shankerwangmiao** [comment]
您好，我们未复现您反馈的问题。目前 TUNA 两台服务器上的 junoplatform 最新版本都是 1.3.8，与上游一致。
