### ISSUE TITLE
EPEL 9 - GPG verification is enabled, but GPG signature is not available

### ISSUE THREAD

**Issue by teunbruijnen** [tuna/issues#1852]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

```
yum update
Extra Packages for Enterprise Linux 9 - x86_64                                                                                 35  B/s | 162  B     00:04    
Extra Packages for Enterprise Linux 9 - x86_64                                                                                1.6 MB/s | 1.6 kB     00:00    
Extra Packages for Enterprise Linux 9 - x86_64                                                                                 54  B/s | 162  B     00:02    
Errors during downloading metadata for repository 'epel':
  - Status code: 404 for http://mirror.dimensi.cloud/epel/9/Everything/x86_64/repodata/repomd.xml.asc (IP: 112.78.36.34)
Error: Failed to download metadata for repo 'epel': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for http://mirror.dimensi.cloud/epel/9/Everything/x86_64/repodata/repomd.xml.asc (IP: 112.78.36.34)
```

### 期望的现象（What you expected to happen）

For EPEL 9 to support GPG verification

### 如何重现此问题（How to reproduce it）

enable GPG verification by adding `repo_gpgcheck=1` to `/etc/yum.conf `

### 操作系统（OS Version）

CentOS Stream 9

### 浏览器（如果适用）（Browser version, if applicable）

N/A

**Comment by teunbruijnen** [comment]
I just noticed this at the top of the /epel/ index: `Last Update: 2023-11-07 12:41 failed`. Don't know if related? 
![image](https://github.com/tuna/issues/assets/22060261/5a177b33-cfdd-4db1-bc5a-9ed730fe9f28)

**Comment by Harry-Chen** [comment]
报错 URL 与 TUNA 没有关系，请重新阅读错误消息。

**Comment by teunbruijnen** [comment]
Apologies I pasted that while trying to update using another repository here's the error with the tuna URL :)
```
Errors during downloading metadata for repository 'epel':
  - Status code: 404 for https://mirrors.tuna.tsinghua.edu.cn/epel/9/Everything/x86_64/repodata/repomd.xml.asc (IP: 101.6.15.130)
Error: Failed to download metadata for repo 'epel': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for https://mirrors.tuna.tsinghua.edu.cn/epel/9/Everything/x86_64/repodata/repomd.xml.asc (IP: 101.6.15.130)
```

**Comment by teunbruijnen** [comment]
@Harry-Chen seems something is going on with the centos stream mirror as the dimensicloud mirror also has a failed status
![image](https://github.com/tuna/issues/assets/22060261/34ce4498-51b0-4d8a-bb35-22bd3dc6dca8)

**Comment by shankerwangmiao** [comment]
This issue is not related to TUNA, since this file also does not exist on upstream server, see https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/repodata/

A possible root cause of your issue might be related with your yum repo configuration. It is not expected that the signature of the repo metadata is fetched, since the metadata of normal yum repos is not signed, but the actual package files are signed.
