### ISSUE TITLE
LineageOS/android_vendor_qcom_opensource_dataipa 缺失

### ISSUE THREAD

**Issue by Zhoneym** [tuna/issues#1853]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

error: Cannot fetch LineageOS/android_vendor_qcom_opensource_dataipa from https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_vendor_qcom_opensource_dataipa

### 期望的现象（What you expected to happen）

successfully

### 如何重现此问题（How to reproduce it）

repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b lineage-21.0 --git-lfs

repo sync

### 操作系统（OS Version）

ubuntu

### 其他需要说明的事项（Anything else we need to know）

lineage-21 分支

**Comment by shankerwangmiao** [comment]
您好，这是 LineageOS 上游用于镜像的 manifest （https://github.com/LineageOS/mirror ）的分支由 master 更换为 main 导致的。目前我们已经相应切换了分支并补充同步了确实的仓库。
