### ISSUE TITLE
Gitlab 上游镜像问题

### ISSUE THREAD

**Issue by fangzhengjin** [tuna/issues#1854]
目前镜像站提供的 Gitlab 镜像不完整, 所支持的系统版本及软件版本与官网库中的差异有些大, 能否考虑将上游镜像改为 Gitlab 官方地址: https://packages.gitlab.com/gitlab 或 https://packages.gitlab.com/gitlab/gitlab-ce

**Comment by shankerwangmiao** [comment]
我们的上游就是您所提供的地址，但是我们没有完整同步全部内容，去掉了 nightly 构建的部分。你具体遇到了什么问题，缺少什么文件。

**Comment by fangzhengjin** [comment]
yum源中, 只有el7的镜像, el8 / el9 都没有, 但是像 AlmaLinux9 / Kylin Linux v10 这些系统, 都是用 el9的软件包

**Comment by shankerwangmiao** [comment]
已经添加同步了

**Comment by fangzhengjin** [comment]
> 已经添加同步了

刚看了下，el9 下没有repodata数据

**Comment by shankerwangmiao** [comment]
已经同步完成。
