### ISSUE TITLE
BFSU镜像站大规模不可用

### ISSUE THREAD

**Issue by Seele-Vollerei32** [tuna/issues#1857]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

经由[Arch Linux CN用户](https://t.me/archlinuxcn_offtopic/6405752)发现，目前[北京外国语大学软件镜像站](https://mirrors.bfsu.edu.cn/)再次发生大规模同步失败。状况同 #1831

### 期望的现象（What you expected to happen）

-

### 如何重现此问题（How to reproduce it）

-

**Comment by Seele-Vollerei32** [comment]
补充一些故障截图![Screenshot_20231125-123023.png](https://github.com/tuna/issues/assets/83913312/6ba62331-7a80-432b-a71f-1a303e90412d)

![Screenshot_20231125-122944.png](https://github.com/tuna/issues/assets/83913312/938a5c94-7239-4d0a-815e-376a901659fb)

![IMG_20231125_122907_450.jpg](https://github.com/tuna/issues/assets/83913312/4e1d5543-6cea-4311-8f9c-6fb2f0f1159e)

**Comment by Harry-Chen** [comment]
我们知悉这一情况。nix-channels 同步占用了大量的空间，导致可用空间不足，进一步致使其他镜像同步失败。

此外，同步失败并不代表镜像不可用。

**Comment by Seele-Vollerei32** [comment]
> 我们知悉这一情况。nix-channels 同步占用了大量的空间，导致可用空间不足，进一步致使其他镜像同步失败。
> 
> 此外，同步失败并不代表镜像不可用。

好的，会修改标题

**Comment by shankerwangmiao** [comment]
目前已经完成修复，正在逐步恢复同步。
