### ISSUE TITLE
pypi.org/simple 包 未同步 : junoplatform 包 pypi: 1.3.27， tuna: 1.3.25

### ISSUE THREAD

**Issue by lzbgt** [tuna/issues#1858]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

junoplatform包 在 pypi.org/simple 版本为1.3.27
在tuna simple 版本为1.3.25

### 期望的现象（What you expected to happen）

junoplatform包版本与pypi一致

### 如何重现此问题（How to reproduce it）

https://pypi.tuna.tsinghua.edu.cn/simple/junoplatform/
https://pypi.org/simple/junoplatform/

### 操作系统（OS Version）

any

### 浏览器（如果适用）（Browser version, if applicable）

any

**Comment by shankerwangmiao** [comment]
目前二者都是 1.3.28
