### ISSUE TITLE
BFSU pypi openai库未同步最新版本

### ISSUE THREAD

**Issue by lyj0309** [tuna/issues#1859]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

BFSU pypi openai库未同步最新版本

https://mirrors.bfsu.edu.cn/pypi/web/simple/openai/
https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/openai/
https://pypi.org/project/openai/#history

可以看到最新是1.36， 但是bfsu最新只有1

### 期望的现象（What you expected to happen）

同步最新包

### 如何重现此问题（How to reproduce it）

https://mirrors.bfsu.edu.cn/pypi/web/simple/openai/

**Comment by shankerwangmiao** [comment]
正在补充同步近几天的新包。

**Comment by lyj0309** [comment]
> 正在补充同步近几天的新包。

难道不是自动同步吗，我看网页上更新时间已经是最新了

**Comment by shankerwangmiao** [comment]
因为近期碰到了上游问题，导致同步被阻塞，需要手工排除。


ref: https://github.com/pypi/warehouse/issues/12933
