### ISSUE TITLE
grafana官方已经提供单独的Ubuntu的Repo，不再和Debian的jessie混合

### ISSUE THREAD

**Issue by ihipop** [tuna/issues#186]
> APT Repository
> Add the following line to your /etc/apt/sources.list file.

>> deb https://packagecloud.io/grafana/stable/debian/ jessie main

> **Use the above line even if you are on Ubuntu or another Debian version**

[虽然帮助文档里面还留着这句话](http://docs.grafana.org/installation/debian/#apt-repository)
![image](https://cloud.githubusercontent.com/assets/423077/21704324/721f7ef4-d3f3-11e6-9c0d-75edf7d7a6c0.png)
但是实际上在[最新的packagecloud的镜像说明里面](https://packagecloud.io/grafana/stable/mirror#apt)
[以及官方的InstallScript提供的API里面](https://packagecloud.io/grafana/stable/install#bash) （[API地址](https://packagecloud.io/install/repositories/grafana/stable/config_file.list?os=Ubuntu&dist=xenial&source=script)）
都已经和Debian的Repo分开，但是清华源并没跟进。
![image](https://cloud.githubusercontent.com/assets/423077/21704465/a5987d70-d3f4-11e6-9a08-bd63e0aebbfe.png)
是否考虑跟进？

**Comment by ihipop** [comment]
https://packagecloud.io/grafana/stable/ubuntu/dists/xenial/Release.gpg

**Comment by bigeagle** [comment]
额…… 懵逼脸
