### ISSUE TITLE
Fedora can't update to fedora39

### ISSUE THREAD

**Issue by suxiaogang223** [tuna/issues#1864]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在升级fedora到39版本时，报错表示找不到关于fedora39的资源：
```text
cannot update repo 'fedora-modular': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://mirrors.ustc.edu.cn/fedora/releases/39/Modular/x86_64/os/repodata/repomd.xml
```

### 期望的现象（What you expected to happen）

升级成功

### 如何重现此问题（How to reproduce it）

在软件商店尝试升级系统到fedora39

### 操作系统（OS Version）

fedora38

### 浏览器（如果适用）（Browser version, if applicable）

firefox

**Comment by taoky** [comment]
Fedora 39 已经没有 Modular 了：https://fedoraproject.org/wiki/Changes/RetireModularity

**Comment by suxiaogang223** [comment]
我把metalink的注释取消了之后就更新成功了，可能是fedora38不知道39不再使用modular了？
