### ISSUE TITLE
Solus的镜像源同步有问题，已经滞后与官方仓库

### ISSUE THREAD

**Issue by hantang** [tuna/issues#1865]
如题：现在的镜像源一直停留在8月，麻烦修复。

提供的镜像中软件包信息一直停留在7、8月份：[tuna镜像](https://mirrors.tuna.tsinghua.edu.cn/solus/packages/shannon/)
![image1](https://github.com/tuna/issues/assets/34468720/a994faa4-9527-49c3-8b31-6c262dee34fe)

官方仓库一直在更新的：[getsol.us](https://cdn.getsol.us/repo/shannon/)
![image2](https://github.com/tuna/issues/assets/34468720/ea6585cd-e19b-4758-9d2a-826632934ec1)

另外：Solus 4.4版本已经释出，镜像ISO一直也没有更新，还停留在4.3版本。
[Solus 4.4 Released, July 8, 2023](https://getsol.us/2023/07/08/solus-4-4-released/)

**Comment by shankerwangmiao** [comment]
目前看来我们的上游  https://mirrors.rit.edu/solus/ 也存在同样的问题。你知道 solus 官方有任何更可靠的 rsync 的同步来源吗？

**Comment by hantang** [comment]
看[博客](https://getsol.us/2023/04/18/a-new-voyage/), Solus 年初发生过故障，现在仓库托管到Cloudfare CDN了。RIT也就不更新。

[文档](https://help.getsol.us/docs/user/package-management/repo-management/) 现在提供的官方仓库只有CDN这个，没看到其他镜像源，不确定这个你们是否能更新。

![image](https://github.com/tuna/issues/assets/34468720/6504e136-7b99-47db-8ae9-5d25be2ee660)

**Comment by shankerwangmiao** [comment]
一般而言，我们更希望从 rsync 来源更新。因为 http 提供的资源，没有通用的方法实现镜像同步。

**Comment by Harry-Chen** [comment]
如果没有可靠的同步方法，且上游始终滞后，我们会不得不考虑移除镜像。

**Comment by hantang** [comment]
了解

**Comment by GZGavinZhao** [comment]
您好，我是Solus的维护者，感谢这么多年来一直的mirror！我们在`packages.getsol.us`有一个官方rsync源，用浏览器访问可以直接看到它的目录结构。请尝试一下它可不可行，如果不能用的话我会跟维护服务器的人反馈。

**Comment by GZGavinZhao** [comment]
我没用过rsync，简单看了一下rsync使用指南和我们服务器的设置，请问您们同步是需要一个我们这边给一个ssh用户名和密码吗？我刚刚跟服务器管理员发信息询问了之前RIT同步时给了他们什么，等他回复了我会转告这边。

**Comment by shankerwangmiao** [comment]
我看那个服务器的 rsync 服务是开启的，应该不需要额外再做什么，我们这边修改上游指向即可。

**Comment by shankerwangmiao** [comment]
目前 solus 已经完成和官方上游的同步。

**Comment by GZGavinZhao** [comment]
感谢！
