### ISSUE TITLE
关于LineageOS源码镜像使用帮助

### ISSUE THREAD

**Issue by Oopas** [tuna/issues#1867]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![Web](https://github.com/tuna/issues/assets/69417818/bc8bc8b9-e2f0-4572-a1c6-c9cec1223ad4)

`fetch="https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/"`
中似乎不应该有最后一个LineageOS即应改为
`fetch="https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/"`
如果不这样写拉取lineage-20.0源码会报错找不到

<img width="841" alt="Error" src="https://github.com/tuna/issues/assets/69417818/3afe6540-7992-4bed-bd6d-f0cfc50c4bbe">

### 期望的现象（What you expected to happen）

正常拉取源码

### 如何重现此问题（How to reproduce it）

repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b lineage-20.0

按教程修改`.repo/manifests/default.xml`

repo sync

### 操作系统（OS Version）

Ubuntu 20.04

### 其他需要说明的事项（Anything else we need to know）

至少上个月是正常的

**Comment by glzlaohuai** [comment]
遇到了跟你同样的问题，文档中的地址不正确。

**Comment by shankerwangmiao** [comment]
我刚刚又检查了一下，文档上原本的 url 是 `git/lineageOS`，后有人提出问题 #1849 和 PR https://github.com/tuna/mirror-web/pull/403 所以改成了 `git/lineageOS/LineageOS`。

我看了一下目前 lineage 的 manifest https://github.com/LineageOS/android/blob/lineage-21.0/snippets/lineage.xml，发现其中 `<project>` 的 `name=` 里带有 `LineageOS` 前缀，因此我认为在 `<remote>` 的 `fetch=` 不应再加 `LineageOS`。

此问题暂时关闭，该问题转移至 #1849 讨论。
