### ISSUE TITLE
Ubuntu22LTS使用北外源更新docker-ce时提示docker-compose-plugin组件哈希值错误

### ISSUE THREAD

**Issue by KeitaroDPVF** [tuna/issues#1874]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在北外源的 `/docker-ce/linux/ubuntu/dists/jammy/pool/stable/amd64/` 下
`docker-compose-plugin_2.21.0-1~ubuntu.22.04~jammy_amd64.deb`
和清华源的同路径同名文件，其哈希内容不同。
使用北外源mirrors.bfsu.edu.cn做docker-ce的软件仓库时，发现docker-compose-plugin无法正常upgrade，并提示
`Failed to fetch https://mirrors.bfsu.edu.cn/docker-ce/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.21.0-1%7eubuntu.22.04%7ejammy_amd64.deb  Hash Sum mismatch`

### 期望的现象（What you expected to happen）

正常安装和更新。

### 如何重现此问题（How to reproduce it）

环境Ubuntu22.04LTS
在/etc/apt/sources.list.d/添加docker.list内容为
`deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.bfsu.edu.cn/docker-ce/linux/ubuntu jammy stable`
并保存，再安装最新的docker-ce及相关docker-compose-plugin组件即可复现。

### 操作系统（OS Version）

Ubuntu22.04LTS

### 其他需要说明的事项（Anything else we need to know）

补充：
①将docker-ce的镜像源改至阿里云，问题消失。
②使用阿里云的docker-ce镜像同位置下载同名文件，得到哈希值不同
③使用清华tuna源镜像站同位置下载同名文件，与阿里云得到的哈希值相同
④比较后发现文件差异点在尾部，似乎是打包时间和密钥不同？

**Comment by Harry-Chen** [comment]
还是 #1822 的问题。docker-ce 上游总是胡乱更新文件，无法被检测到

**Comment by Calcifer97** [comment]
![image](https://github.com/tuna/issues/assets/37408196/9a058064-2dda-4006-b330-82b083060b35)

**Comment by shankerwangmiao** [comment]
这个文件的问题也已经修理了。
