### ISSUE TITLE
rsync 同步失败。求助

### ISSUE THREAD

**Issue by Lzh566566** [tuna/issues#1877]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我们是华为云内部镜像团队，部分镜像 rsync 同步了清华源的站点。最近这段时间貌似被rsync出问题了？还是我们被封禁了呢？

### 期望的现象（What you expected to happen）

rsync centos成功

### 如何重现此问题（How to reproduce it）

rsync 报错：
Connection reset by peer

**Comment by shankerwangmiao** [comment]
我们近期没有修改过 rsync 的相关配置。请提供您的 IP 地址以便进一步诊断。


请问 “Connection reset by peer” 错误是在什么上下文中出现的？是 Rsync 报的错误吗？是一执行 rsync 就报上述错误，还是可以看见 TUNA 站的 motd 之后才报错的，还是同步进行过程中报错的？

**Comment by Lzh566566** [comment]
> 我们近期没有修改过 rsync 的相关配置。请提供您的 IP 地址以便进一步诊断。
> 
> 请问 “Connection reset by peer” 错误是在什么上下文中出现的？是 Rsync 报的错误吗？是一执行 rsync 就报上述错误，还是可以看见 TUNA 站的 motd 之后才报错的，还是同步进行过程中报错的？

ip 应该是 116.205.148.x

相关报错：

`
2024/01/08 16:45:59 [19405] +==================================================+
2024/01/08 16:45:59 [19405] |               Tsinghua University                |
2024/01/08 16:45:59 [19405] |          -= Open Source Mirror Site =-           |
2024/01/08 16:45:59 [19405] +--------------------------------------------------+
2024/01/08 16:45:59 [19405] |   Welcome to Tsinghua Open Source Mirror Site.   |
2024/01/08 16:45:59 [19405] |                                                  |
2024/01/08 16:45:59 [19405] |   This mirror is also available on HTTP.         |
2024/01/08 16:45:59 [19405] |   HTTP  [https://mirrors.tuna.tsinghua.edu.cn]   |
2024/01/08 16:45:59 [19405] |   RSYNC [rsync://mirrors.tuna.tsinghua.edu.cn]   |
2024/01/08 16:45:59 [19405] |                                                  |
2024/01/08 16:45:59 [19405] |   If you have any issues, please contact us      |
2024/01/08 16:45:59 [19405] |   via GitHub @ https://github.com/tuna/issues    |
2024/01/08 16:45:59 [19405] |   or IRC at #tuna on Libera.Chat                 |
2024/01/08 16:45:59 [19405] |   or Fishroom at https://fishroom.tuna.moe/      |
2024/01/08 16:45:59 [19405] |                                                  |
2024/01/08 16:45:59 [19405] |   Supported by                                   |
2024/01/08 16:45:59 [19405] |      Tsinghua Information Technology Center      |
2024/01/08 16:45:59 [19405] |   Maintained by                                  |
2024/01/08 16:45:59 [19405] |      Tsinghua University TUNA Association        |
2024/01/08 16:45:59 [19405] |   Service Provided by                            |
2024/01/08 16:45:59 [19405] |      nanomirrors                                 |
2024/01/08 16:45:59 [19405] |   This storage server is sponsored by            |
2024/01/08 16:45:59 [19405] |      Megvii Technology Ltd.                      |
2024/01/08 16:45:59 [19405] |                                                  |
2024/01/08 16:45:59 [19405] |   TUNA acknowledges the contribution from        |
2024/01/08 16:45:59 [19405] |   Megvii and Huawei to open source software and  |
2024/01/08 16:45:59 [19405] |   communities                                    |
2024/01/08 16:45:59 [19405] |                                                  |
2024/01/08 16:45:59 [19405] +==================================================+
2024/01/08 16:45:59 [19405] 
2024/01/08 16:46:00 [19405] receiving file list
2024/01/08 16:49:28 [19444] rsync: read error: Connection reset by peer (104)
2024/01/08 16:49:28 [19444] rsync error: error in socket IO (code 10) at io.c(785) [receiver=3.1.3]`

**Comment by shankerwangmiao** [comment]
我调阅了服务器上的日志。我注意到，与您的请求相关的 IP 为 `14.137.135.x`，位于伦敦。如果这不是您期望的，请您检查您系统的路由设定是否正确。

根据日志显示，问题的直接原因是我们服务器上的 rsync 进程报错退出，其错误是 `deflate on token returned 0`。我们服务器上 rsync 的版本为 `3.2.3`，debian 包的版本是 `3.2.3-4+deb11u1`。

检索相关资料显示，该版本的 rsync 作为 sender 与 3.1.x 版本的 receiver 配合工作，在开启压缩（`-z`）时且遇到较大文件时可能造成上述错误。请参考 \[1\] \[2\] \[3\]。

请提供您的系统版本和 rsync 版本，以便进一步证实是上述问题所致。建议您升级 rsync 的版本，或者作为 work around，关闭压缩选项。

\[1\]: <https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/1971932>
\[2\]: <https://bugzilla.opensuse.org/show_bug.cgi?id=1175854>
\[3\]: <https://github.com/WayneD/rsync/issues/86>

**Comment by Lzh566566** [comment]
> 我调阅了服务器上的日志。我注意到，与您的请求相关的 IP 为 `14.137.135.x`，位于伦敦。如果这不是您期望的，请您检查您系统的路由设定是否正确。
> 
> 根据日志显示，问题的直接原因是我们服务器上的 rsync 进程报错退出，其错误是 `deflate on token returned 0`。我们服务器上 rsync 的版本为 `3.2.3`，debian 包的版本是 `3.2.3-4+deb11u1`。
> 
> 检索相关资料显示，该版本的 rsync 作为 sender 与 3.1.x 版本的 receiver 配合工作，在开启压缩（`-z`）时且遇到较大文件时可能造成上述错误。请参考 [1] [2] [3]。
> 
> 请提供您的系统版本和 rsync 版本，以便进一步证实是上述问题所致。建议您升级 rsync 的版本，或者作为 work around，关闭压缩选项。
> 
> [1]: https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/1971932 [2]: https://bugzilla.opensuse.org/show_bug.cgi?id=1175854 [3]: [WayneD/rsync#86](https://github.com/WayneD/rsync/issues/86)

您好 。我确认了下 我们客户端版本确实是 3.1.3. 并且也确实开启了压缩

`rsync ${common_rsync_opts} -avzH --delete --log-file="${CURRENT_DIR}/${log_filename}" ${centos_url} ${target_dir} --bwlimit=2000 --exclude="*.iso"`

我们将客户端rsync版本到3.2.3试试
