### ISSUE TITLE
junoplatform 镜像无法在 从pypi同步到https://pypi.tuna.tsinghua.edu.cn/simple/junoplatform/

### ISSUE THREAD

**Issue by lzbgt** [tuna/issues#1878]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

镜像同步问题

### 期望的现象（What you expected to happen）

tuna版本与pypi一致, 为1.4.1

### 如何重现此问题（How to reproduce it）

查看https://pypi.org/simple和https://pypi.tuna.tsinghua.edu.cn/simple/junoplatform/ 对比

### 操作系统（OS Version）

any

### 浏览器（如果适用）（Browser version, if applicable）

any

### 其他环境（Other environments）

any

**Comment by shankerwangmiao** [comment]
是因为 pypi 上游出现的问题引发的。目前正在追赶进度。

**Comment by shankerwangmiao** [comment]
已经完成同步。
