### ISSUE TITLE
给NTP加一些页面

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#188]
ntp.tuna.tsinghua.edu.cn已经上线了，经过几天测试似乎工作良好，现在看来有以下几点可以加强一下：

- [ ] 主页 https://ntp.tuna.tsinghua.edu.cn
- [ ] 帮助页面 https://ntp.tuna.tsinghua.edu.cn/help
- [ ] 状态页面 https://ntp.tuna.tsinghua.edu.cn/status
- [ ] 主站链接 https://tuna.moe 加一个链接

**Comment by xavieryao** [comment]
有 https://tuna.moe/help/ntp/ 应该够了
