### ISSUE TITLE
BFSU镜像站Gentoo distfiles源同步失败

### ISSUE THREAD

**Issue by Nuralii1i** [tuna/issues#1881]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

北外镜像站说来这儿提issue,所以。。。
北外的Gentoo源连续同步失败已经8天了，之前好像也有一次连续同步失败很久的情况，用联合镜像站看了一下，用了同一个同步源（rsync://mirror.us.leaseweb.net/gentoo/）的镜像站都出现失败的情况

### 期望的现象（What you expected to happen）

感觉可以考虑换个同步源来同步

### 如何重现此问题（How to reproduce it）

无需复现

### 操作系统（OS Version）

Gentoo

**Comment by Harry-Chen** [comment]
已经更换上游并恢复同步。
