### ISSUE TITLE
访问openeuler镜像502

### ISSUE THREAD

**Issue by nicliuqi** [tuna/issues#1882]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

如图
![image](https://github.com/tuna/issues/assets/69004854/53c2bebe-56e2-4272-a064-6d588dfaa562)

### 期望的现象（What you expected to happen）

正常访问资源

### 如何重现此问题（How to reproduce it）

目前是必现的

### 操作系统（OS Version）

Mac OS

### 浏览器（如果适用）（Browser version, if applicable）

Google Chrome 120.0.6099.217

**Comment by xiaoxx970** [comment]
同样, IPv4和IPv6都显示502

**Comment by xiaoxx970** [comment]
看来是因为镜像在维护: https://mirrors.tuna.tsinghua.edu.cn/news/maintainance-jan/

**Comment by shankerwangmiao** [comment]
目前维护已经结束。
