### ISSUE TITLE
jenkins 2.164 update-center.json 有误

### ISSUE THREAD

**Issue by OrleaArtagnan** [tuna/issues#1883]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

jenkins 2.164 update-center.json 有误，该文件并非一个 json 格式的文件
[update-center.json](https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/2.164/update-center.json)
能看到该 json 外部嵌套了一层 updateCenter.post();

### 期望的现象（What you expected to happen）

访问 
[update-center.json](https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/2.164/update-center.json)
时返回一个 json 格式的文件

### 如何重现此问题（How to reproduce it）

直接下载镜像站上的该 json 即可：
[update-center.json](https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/2.164/update-center.json)

### 操作系统（OS Version）

CentOS7

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by shankerwangmiao** [comment]
您发现的现象属实。TUNA 按原样提供镜像的文件。经查，上游 https://mirrors.osuosl.org/pub/jenkins/updates/update-center.json 也是如此。因此，TUNA 镜像不存在问题。如果您认为 jenkins 发布的该文件有误，建议您可以与其联系以获取进一步的支持。
