### ISSUE TITLE
qt在线安装失败，下载错误

### ISSUE THREAD

**Issue by Rimits** [tuna/issues#1885]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Qt 在线安装失败，下载错误
![ksnip_20240119-152520](https://github.com/tuna/issues/assets/42634955/ae8027e1-3a5b-4e60-a79d-e1f19ceb9976)

### 期望的现象（What you expected to happen）

  ``

### 如何重现此问题（How to reproduce it）

``

### 操作系统（OS Version）

linux

**Comment by jinzhongjia** [comment]
一样问题，目前仍会出现

**Comment by shankerwangmiao** [comment]
根据图示错误信息，这是因为服务器拒绝了该请求导致的。要排查具体原因，可以在浏览器中查看该 URL，在最下方有识别代码，我们可以根据它来进一步排查。
