### ISSUE TITLE
LLVM APT Ubuntu 2204 i386 错误

### ISSUE THREAD

**Issue by levihuayuzhang** [tuna/issues#1886]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Ubuntu 22.04 运行`apt update`输出如下：
```
Ign:9 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy/main i386 Packages   
Err:9 https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy llvm-toolchain-jammy/main i386 Packages                      
  404  Not Found [IP: 101.6.15.130 443]

```

### 期望的现象（What you expected to happen）

在官网`https://apt.llvm.org/`中已有提示：`Packages are available for amd64, i386 (except for recent Ubuntu)`。

也许某些版本的ubuntu需要移除i386包以去除错误提示。

### 如何重现此问题（How to reproduce it）

添加tuna源，更新apt缓存。

### 操作系统（OS Version）

Ubuntu2204

**Comment by shankerwangmiao** [comment]
您好，

由于 i386 架构不常用，我们没有收录 i386 架构的 deb 包。如果用户的系统中额外启用了 i386 架构，则会自动试图下载 i386 架构的索引。于是出现了您反馈的现象。

该现象不会影响您正常在 amd64 架构上安装相关软件包，忽略即可。
