### ISSUE TITLE
通过TUNA镜像源安装的kafka无法正常启动

### ISSUE THREAD

**Issue by buildyuan** [tuna/issues#1887]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

1. `brew install kafka`
2. `brew services start kafka`
3. `brew services`
kafka status 无法启动报错
查询日志：`/opt/homebrew/var/log/kafka/kafka_output.log`

内容：
```
/opt/homebrew/Cellar/kafka/3.6.1/libexec/bin/kafka-run-class.sh: line 346: /opt/homebrew/@@HOMEBREW_JAVA@@/bin/java: No such file or directory
/opt/homebrew/Cellar/kafka/3.6.1/libexec/bin/kafka-run-class.sh: line 346: exec: /opt/homebrew/@@HOMEBREW_JAVA@@/bin/java: cannot execute: No such file or directory
```

### 期望的现象（What you expected to happen）

使用命令`brew services start kafka` 可以正常使用kafka

### 如何重现此问题（How to reproduce it）

1. `brew install kafka`
2. `brew services start kafka`

### 操作系统（OS Version）

14.2.1

### 其他环境（Other environments）

zshrc 配置如下
```
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"
export HOMEBREW_NO_ENV_HINTS=1
eval "$(/opt/homebrew/bin/brew shellenv)"
```

### 其他需要说明的事项（Anything else we need to know）

最后在github上搜到了类似的情况
修改后重新安装`HOMEBREW_BOTTLE_DOMAIN= brew install Kafka`解决

参考：https://github.com/l0o0/jasminum/issues/55#issuecomment-1093914510

**Comment by shankerwangmiao** [comment]
感谢您的反馈，正如 https://github.com/orgs/Homebrew/discussions/2530#discussioncomment-2002374 中指出的那样，目前  bottle mirrors 中的与 JAVA 相关的 formulae 不能正常工作。该问题目前看来与镜像站没有直接的关系，而是 homebrew 对镜像的兼容性问题所致。
