### ISSUE TITLE
Xshell服务器在使用miniconda的清华镜像源时出bug

### ISSUE THREAD

**Issue by fengy95** [tuna/issues#1888]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

您好，我在Xshell服务器的miniconda中使用了清华镜像源（miniconda安装包从官网‘ https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/ ’处下载），但在后续的软件安装和卸载中都出现了连接超时的报错。该报错是在我确保网络连接正常的情况出现的，反映的是在试图连接到地址‘mirrors.tuna.tsinghua.edu.cn’或地址‘s3.jcloud.sjtu.edu.cn’时发生了连接超时。相关报错情况如下所示：
1. 命令conda search r
报错：Loading channels: \ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=9.15)")': /anaconda/cloud/conda-forge/noarch/repodata.json
                                                                    - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /conda-forge/linux-64/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /r/linux-64/repodata.json
                                                                    \ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /biobakery/linux-64/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /bioconda/noarch/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /conda-forge/noarch/repodata.json
                                                                    - ERROR conda.auxlib.logz:stringify(171): Expecting ',' delimiter: line 1 column 28396289 (char 28396288)
2. 命令conda remove conda
报错：Collecting package metadata (repodata.json): | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))': /pkgs/r/noarch/repodata.json
                                                                    \ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='s3.jcloud.sjtu.edu.cn', port=443): Read timed out. (read timeout=9.15)")': /899a892efef34b1b944a19981040f55b-oss01/anaconda/cloud/conda-forge/noarch/repodata.json
                                                                    failed
发生错误后无法再次进行软件的查询或卸载。

### 期望的现象（What you expected to happen）

希望各位老师能够排查一下miniconda的清华镜像源是否有任何问题，恢复miniconda的正常使用。

### 如何重现此问题（How to reproduce it）

问题来自于我的账号在使用miniconda发生的报错，因此您的账号不一定会出现这种报错，但是我的账号在网络连接正常的情况下，只要使用conda search或conda remove命令都会发生报错，不清楚其他账号是否有相同的问题发生。

### 操作系统（OS Version）

Xshell.exe: 7.0.0029

**Comment by shankerwangmiao** [comment]
您好，Xshell 是一种通过 ssh 协议远程登录到服务器上的客户端软件。您在登录到服务器后所执行的命令都是在服务器上运行的，利用的是服务器的运行资源和网络资源，与您本机的网络连通性没有关系。请确认服务器可以正常与镜像站通信。
