### ISSUE TITLE
[镜像请求] Sublime Text 包管理器channel_v3镜像

### ISSUE THREAD

**Issue by 176807694** [tuna/issues#1889]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Sublime Text包管理器，让查找、安装和更新包变得非常简单。

### 上游地址与镜像方法 (How to mirror)

https://packagecontrol.io/channel_v3.json

### 镜像大小 (Mirror size)

800kb

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by shankerwangmiao** [comment]
sublime 不是开源软件，受限于版权许可原因，我们不能镜像。

对于其包管理器，您给出的文件仅包含索引，并非包的集中存储位置。即便镜像了，实际下载包的时候仍然要指向实际存放包的位置。因此镜像意义不大。
