### ISSUE TITLE
add Bioconductor mirror

### ISSUE THREAD

**Issue by zhilongjia** [tuna/issues#189]
#### 项目名称与简介(Project Intro.)
[Bioconductor](http://bioconductor.org/) (Bioconductor provides tools for the analysis and comprehension of high-throughput genomic data. Bioconductor uses the R statistical programming language, and is open source and open development. It has two releases each year, 1296 software packages, and an active user community. Bioconductor is also available as an AMI (Amazon Machine Image) and a series of Docker images.)

#### 上游地址与镜像方法(How to Mirror)
上游地址:http://bioconductor.org/packages/release/BiocViews.html#___Software
镜像方法:
http://www.bioconductor.org/about/mirrors/mirror-how-to/
http://www.tengfei.name/BiocWithTea/chapters/Development/mirror-bioc

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
188GB for BioC 3.5

**Comment by huiyiqun** [comment]
同步中了，只同步了release，也就是3.4。

**Comment by huiyiqun** [comment]
Done

如果方便，欢迎到 [这里](https://github.com/tuna/mirror-web/tree/master/_posts/help) 提交pull request帮我们添加帮助。

**Comment by zhilongjia** [comment]
能否将当前到https://mirrors.tuna.tsinghua.edu.cn/bioconductor/ 修改为 https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.4/bioc/ 。再链接一个release版本。这样和其他镜像保持一致，便于自由切换镜像。

**Comment by huiyiqun** [comment]
@bigeagle tunasync能指定working directory吗？

**Comment by bigeagle** [comment]
可以的，在 mirror config 里指定 `mirror_dir` 即可。
https://github.com/tuna/tunasync/blob/master/worker/config.go#L111

**Comment by zhilongjia** [comment]
@huiyiqun 抱歉，应该为https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.4， 不是https://mirrors.tuna.tsinghua.edu.cn/bioconductor/packages/3.4/bioc/ 。

**Comment by bigeagle** [comment]
@huiyiqun 不过我建议换成 script mirror，毕竟以后可能会有多 release 的问题。

**Comment by huiyiqun** [comment]
现在neo空间也不多了…我觉得先同步一个版本吧 位置我先不挪了 在nginx里配一个alias 马上就能上线

**Comment by bigeagle** [comment]
科学

**Comment by huiyiqun** [comment]
Done.

@zhilongjia 你测试一下吧？如果有时间最好能帮我们[写一个简单的help](https://github.com/tuna/mirror-web/tree/master/_posts/help)，关于如何使用镜像，我们这里似乎没有bioconductor用户。
