### ISSUE TITLE
OpenTUNA域名过期？

### ISSUE THREAD

**Issue by xiao-k233** [tuna/issues#1890]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

打开opentuna.cn，结果显示证书来自https://dessert-map.com/，实际打开网页也是https://dessert-map.com/
aria2报错errorCode=1 SSL/TLS handshake failure: hostname does not match

### 期望的现象（What you expected to happen）

opentuna镜像站页面

### 如何重现此问题（How to reproduce it）

稳定复现，打开opentuna.cn

### 操作系统（OS Version）

w11，ArchLinux

### 浏览器（如果适用）（Browser version, if applicable）

Edge版本 121.0.2277.83 (正式版本) (64 位)

### 其他环境（Other environments）

DNSserver:223.5.5.5

### 其他需要说明的事项（Anything else we need to know）

莫不是你们忘了续费？

**Comment by makeding** [comment]
opentuna 已经停止维护，请使用 tuna / bfsu 或者其它镜像站代替。
