### ISSUE TITLE
OSDN 镜像近一个月同步失败

### ISSUE THREAD

**Issue by laozhoubuluo** [tuna/issues#1892]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

OSDN 镜像近一个月同步失败。

### 期望的现象（What you expected to happen）

OSDN 镜像同步成功，可下载最新版本 CrystalDiskInfo 等保留同步的软件。

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/status/#server-status

### 操作系统（OS Version）

Windows 11

### 浏览器（如果适用）（Browser version, if applicable）

Vivaldi

### 其他需要说明的事项（Anything else we need to know）

根据 https://ja.osdn.net/docs/DownloadMirrorsWanted 描述，其要求的同步地址与目前配置不完全相同。

**Comment by Harry-Chen** [comment]
> 根据 https://osdn.net/docs/DownloadMirrorsWanted 描述，其要求的同步地址与目前配置不完全相同。

我们从 OSDN 的日本官方镜像同步。但目前上游的若干 rsync 服务器看起来无法连接，我们会调查此问题。

**Comment by shankerwangmiao** [comment]
已经更换了上游。
