### ISSUE TITLE
缺少 rustup-init 二进制

### ISSUE THREAD

**Issue by SadPencil** [tuna/issues#1893]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

设置了 RUSTUP_UPDATE_ROOT 后，执行 rust 官网提供的安装 rustup 命令会由于 404 失败。

```bash
user@debian:~$ echo $RUSTUP_UPDATE_ROOT
https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
user@debian:~$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: downloader https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.RgWn5pm2Wb/rustup-init x86_64-unknown-linux-gnu
user@debian:~$ curl -I https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
HTTP/2 404
```

请求的 URL 是 https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup/dist/x86_64-unknown-linux-gnu/rustup-init

### 期望的现象（What you expected to happen）

该 URL 所在的 `dist` 目录或许应该镜像 rustup-init 二进制（debian 直到 13 才会把 rustup 程序加入官方源）

### 如何重现此问题（How to reproduce it）

debian 11 amd64，默认安装，并先进行了换源 https://mirrors.tuna.tsinghua.edu.cn/help/rustup/ ，然后执行 `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

### 操作系统（OS Version）

Debian GNU/Linux 11 (bullseye)

### 其他需要说明的事项（Anything else we need to know）

目前的 workaround 是手动下载 https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init ，然后执行此程序，或者把 RUSTUP_UPDATE_ROOT 置空。这两种方式都要跨洋。

**Comment by jiegec** [comment]
该功能已经在 rustup-mirror v0.8.0 中添加。

**Comment by Harry-Chen** [comment]
已经完成同步，所述地址已经存在文件
