### ISSUE TITLE
安装cdlib时，thresholdclustering包报错404

### ISSUE THREAD

**Issue by MintArvask** [tuna/issues#1895]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我在miniconda中输入：
pip install cdlib
一开始的依赖包都可以正常安装，然而当进展到：
Collecting thresholdclustering
的时候，报错了404。打开源网站：https://mirrors.bfsu.edu.cn/pypi/web/packages/2d/71/47b603fc148d3fbba7c8eb057ef208da736d02e27bec8bab686b7f4900b7/thresholdclustering-1.0-py3-none-any.whl#sha256=75464d53e990d54089f48c8c10b5c5c602dd98b51b07997c02391d46927109ff
的确存在404错误。
<img width="849" alt="image" src="https://github.com/tuna/issues/assets/142889193/2c50a4df-2761-48f6-a17a-74e4c5851f0a">

### 期望的现象（What you expected to happen）

我希望可修正此错误。

### 如何重现此问题（How to reproduce it）

在miniconda中输入
pip install cdlib
我使用python3.9。

### 操作系统（OS Version）

Windows

### 浏览器（如果适用）（Browser version, if applicable）

Edge

### 其他环境（Other environments）

miniconda3

**Comment by shankerwangmiao** [comment]
已经修复，请再测试一次。

**Comment by MintArvask** [comment]
> 已经修复，请再测试一次。

经测试已经修复了，感谢。
