### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tb-nightly (from versions: none) 

### ISSUE THREAD

**Issue by yisuanwang** [tuna/issues#1896]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

清华源没有这个pip包

### 期望的现象（What you expected to happen）

下载成功

### 如何重现此问题（How to reproduce it）

使用清华源pip install tb-nightly

### 其他需要说明的事项（Anything else we need to know）

 在使用清华源的时候会报错  pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple

**Comment by Harry-Chen** [comment]
由于占用空间和更新频率原因，我们不同步任何以 nightly 结尾的软件包，请知悉。
