### ISSUE TITLE
MirrorRequest: Anaconda

### ISSUE THREAD

**Issue by lvzongting** [tuna/issues#19]
官方地址: https://www.continuum.io/
下载地址:https://www.continuum.io/downloads

Anaconda是Python的一个发行版，系统独立，可以运行在Linux，MacOS，Win下，开源，社区维护。现在基本上只能从官网下载，速度很慢300K+，没找到任何镜像源。希望tuna可以镜像这个仓库。

#先写这么多，后面再添加why-Anaconda

**Comment by bigeagle** [comment]
Done, http://mirrors.tuna.tsinghua.edu.cn/anaconda/

最好可以给 https://github.com/tuna/mirror-web 发个使用文档的PR

**Comment by lvzongting** [comment]
好速度，我有空的时候，就这几天，我发一个使用兼介绍文档。

**Comment by bigeagle** [comment]
https://docs.continuum.io/anaconda-repository/install
