### ISSUE TITLE
nix-channel nixpkgs-unstable is out of date

### ISSUE THREAD

**Issue by networkhermit** [tuna/issues#1900]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

tuna nix-channel [nixpkgs-unstable](https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable/) 很长一段时间没有正常同步，最近一次正常同步是 2024-01-29 11:47，而 [ustc nixpkgs-unstable](https://mirrors.ustc.edu.cn/nix-channels/nixpkgs-unstable/) 和 [官方 nixpkgs-unstable](https://releases.nixos.org/nixpkgs/nixpkgs-24.05pre587252.48b75eb6e521) 分别为 23-Feb-2024 和 2024-02-24。

### 期望的现象（What you expected to happen）

tuna nix-channel [nixpkgs-unstable](https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable/) 正常同步。

### 如何重现此问题（How to reproduce it）

打开正文中 tuna, ustc，nixos官方的 nixpkgs-unstable 链接，查看目录树时间戳可验证。

**Comment by shankerwangmiao** [comment]
目前已经恢复。

该问题和 #1855 原因一致。目前上游已经修复相关问题。
