### ISSUE TITLE
[镜像请求] 增加CERN AlmaLinux的镜像

### ISSUE THREAD

**Issue by laf070810** [tuna/issues#1902]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

由CERN维护的AlmaLinux软件包仓库，面向在CERN学习和工作的广大用户。目前CentOS 7的生命周期即将结束，未来CERN用户的主流操作系统将从CERN CentOS 7转换到CERN AlmaLinux 9或RHEL，因此镜像CERN AlmaLinux可带来较大帮助。

### 上游地址与镜像方法 (How to mirror)

rsync://linuxsoft.cern.ch/alma/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
根据我的理解，在 CERN 学习和工作的用户大部分应该位于欧洲，而 TUNA 不对欧盟用户提供服务。

**Comment by Harry-Chen** [comment]
Duplicated with #1186.
