### ISSUE TITLE
无法使用tuna的帮助 安装Kubernetes

### ISSUE THREAD

**Issue by LxnChan** [tuna/issues#1903]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

tuna官方帮助提到：

![image](https://github.com/tuna/issues/assets/46388610/c43aa133-bfa7-44d9-8f1a-dc632ee0a128)

根据该步骤会得到`NO PUBKEY`的报错。

---

事实上应该采用`apt-key add`方式添加Key而不是在source.list文件中

```bash
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
apt-key add /usr/share/keyrings/kubernetes-archive-keyring.gpg
```

### 期望的现象（What you expected to happen）

能够正常update

### 如何重现此问题（How to reproduce it）

按官方说明即可复现。

### 操作系统（OS Version）

Ubuntu 20.04.6 LTS x86

### 浏览器（如果适用）（Browser version, if applicable）

-

### 其他环境（Other environments）

- APT: `apt 2.0.9 (amd64)`
- Kernel: `Linux k8s-learn-n2 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by shankerwangmiao** [comment]
文档中的方法是正确的。您所说的方法曾经也是正确的，但是现在不推荐使用。因为 `apt-key add` 命令添加的公钥会始终被系统信任。而用文档中的方法，只有当使用所指定的那个软件仓库时，才会信任对应的公钥；而在使用其它软件仓库时，则不会信任该公钥，从而更为安全。

如果您按照文档中的操作遇到了问题，请反馈具体的错误现象。
