### ISSUE TITLE
[镜像请求] BMCLAPI（MC镜像）

### ISSUE THREAD

**Issue by EastCation** [tuna/issues#1904]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

[原文见此](https://bmclapidoc.bangbang93.com/)

[Github项目](https://github.com/bangbang93/BMCL/tree/master/BMCLV2/Mirrors)

### 上游地址与镜像方法 (How to mirror)

项目主页并未*明确*提供上游以及如何镜像此软件源，但鉴于有其他高校已镜像此源，可以使用以下地址进行镜像
```bash

rsync://rsync.mirrors.ustc.edu.cn/bmclapi/ #USTC

```

### 镜像大小 (Mirror size)

大约75.39G

## 天下苦MCBBS久矣！

如今已经倒闭，BMCLAPI下载不堪重负。国内的MC下载源将何去何从？

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by 8MiYile** [comment]
你好，目前已经有其他大学已经在使用这个镜像站了，你可以先看一下教育网的大学联合镜像源，清华这边肯定是会跟进的

**Comment by Harry-Chen** [comment]
现有软件已经耗尽了带宽。考虑此此软件可能带来的极大压力，tuna 短期内不会考虑增加此镜像，以免影响其他用户。

**Comment by shankerwangmiao** [comment]
目前 TUNA 的出口带宽处于满载状态，因此暂不考虑镜像。
