### ISSUE TITLE
[镜像请求] tur 

### ISSUE THREAD

**Issue by Freed-Wu** [tuna/issues#1906]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

> Sounds like Archlinux User repository aka AUR ? TUR functioning mechanism is bit different. Instead of building packages in device that too in android is quite hectic work for user. So TUR saves resources and time since user could install pre-compiled package.

### 上游地址与镜像方法 (How to mirror)

https://tur.kcubeterm.com/

### 备注 (Note)

Related issue:

- tur:
  - https://github.com/ustclug/mirrorrequest/issues/360
- termux-pacman
  - https://github.com/ustclug/mirrorrequest/issues/348
  - https://github.com/tuna/issues/issues/1635
- termux-packages.git
  - https://github.com/tuna/issues/issues/1907
  - https://github.com/ustclug/mirrorrequest/issues/386

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
由于用户量较小，并且同步困难，不予接受。具体讨论可参考 https://github.com/ustclug/mirrorrequest/issues/360 。
