### ISSUE TITLE
[镜像请求] termux-packages.git

### ISSUE THREAD

**Issue by Freed-Wu** [tuna/issues#1907]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

git repo of termux packages

### 上游地址与镜像方法 (How to mirror)

https://github.com/termux/termux-packages.git

### 备注 (Note)

Related issue:

- tur:
  - https://github.com/ustclug/mirrorrequest/issues/360
  - https://github.com/tuna/issues/issues/1906
- termux-pacman
  - https://github.com/ustclug/mirrorrequest/issues/348
  - https://github.com/tuna/issues/issues/1635
- termux-packages.git
  - https://github.com/ustclug/mirrorrequest/issues/386

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
与 https://github.com/ustclug/mirrorrequest/issues/385 相同理由关闭。

**Comment by Freed-Wu** [comment]
nixpkgs.git has been accepted <https://github.com/tuna/issues/issues/1265>.

What is the difference of them?

**Comment by Harry-Chen** [comment]
> nixpkgs.git has been accepted #1265.
> 
> What is the difference of them?

https://github.com/ustclug/mirrorrequest/issues/385#issuecomment-1976404783

termux-packages.git 并没有此用途。此外，镜像站管理员对此也没有需求。
