### ISSUE TITLE
Qt5.14及以前的版本无法下载

### ISSUE THREAD

**Issue by yiqifeiyang** [tuna/issues#1909]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

qt/archive/qt/下Qt5.14及以前的版本无法下载，Qt5.15及之后的版本正常。

### 期望的现象（What you expected to happen）

正常应可以打开相应的文件夹并下载指定版本的文件。

### 如何重现此问题（How to reproduce it）

打开https://mirror.tuna.tsinghua.edu.cn/qt/archive/qt/5.14，提示：
![image](https://github.com/tuna/issues/assets/3292707/e8845f6b-6334-4771-9c11-5e344cdcb5e9)

### 操作系统（OS Version）

windows 11

### 浏览器（如果适用）（Browser version, if applicable）

chrome

### 其他需要说明的事项（Anything else we need to know）

从https://mirror.tuna.tsinghua.edu.cn/qt/archive/qt下的列表看，5.14及之前的版本从正常的文件夹变为了文件。
进一步从download.qt.io里的文件信息看，可能是Qt将5.14及以前的版本从archive文件夹移到了new_archive文件夹，原来archive下放置的是文件链接导致。

**Comment by taoky** [comment]
- https://github.com/tuna/issues/issues/757#issuecomment-604243686
- https://github.com/ustclug/discussions/issues/391#issuecomment-1139337825
- https://github.com/tuna/issues/issues/1504
- https://github.com/tuna/issues/issues/919

**Comment by shankerwangmiao** [comment]
受限于同步机制，该问题暂时无法解决
