### ISSUE TITLE
请求更改 pypi 镜像源使用帮助中 Poetry 设置默认镜像的方法

### ISSUE THREAD

**Issue by vagreargnatry** [tuna/issues#1910]
[pypi 镜像源使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)

[Poetry 1.8.0](https://github.com/python-poetry/poetry/releases/tag/1.8.0) 不再建议使用 `--priority=default` 而是使用 `--priority=primary`

新的命令应该是这样 `poetry source add --priority=primary mirrors https://pypi.tuna.tsinghua.edu.cn/simple/`

**Comment by shankerwangmiao** [comment]
您好，

目前 TUNA 镜像站的帮助页面由教育网联合镜像站提供。请前往 https://github.com/mirrorz-org/mirrorz-docs 提出修改意见。
