### ISSUE TITLE
这两天北外的源，似乎挺多的项目同步都出了问题，是出了什么状况吗？

### ISSUE THREAD

**Issue by jerry3055** [tuna/issues#1911]
![image](https://github.com/tuna/issues/assets/35842285/ebcb0075-32ba-4a37-878d-e883fa7190e0)

**Comment by shankerwangmiao** [comment]
是的，存储空间用尽了。但是暂时不影响用户使用。

**Comment by jerry3055** [comment]
> 是的，存储空间用尽了。但是暂时不影响用户使用。

好的，感谢解答！
