### ISSUE TITLE
[nodejs-release]: 缺少`latest`文件夹

### ISSUE THREAD

**Issue by uiolee** [tuna/issues#1912]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

```
Error retrieving "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/latest/SHASUMS256.txt": HTTP Status 404
```

https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

`nodejs-release/latest*/` get 404

![image](https://github.com/tuna/issues/assets/22849383/c939e5b1-ff8e-4670-a62e-7c25a85503e3)

### 期望的现象（What you expected to happen）

keep sync with https://nodejs.org/dist/

![nodejs-dist](https://github.com/tuna/issues/assets/22849383/1c34d799-6c08-466f-b32d-e501f454ea15)

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/latest

![reproduce ](https://github.com/tuna/issues/assets/22849383/75f20ea5-5d02-42fa-b093-b66afc2b6958)

**Comment by taoky** [comment]
与 https://github.com/tuna/issues/issues/1898 重复。

**Comment by uiolee** [comment]
Duplicate of #1898

抱歉。我搜索时没有发现那个issue

![search](https://github.com/tuna/issues/assets/22849383/6b4f29da-64b8-4b30-9446-e19d740e7775)
