### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by TsingHeSZU** [tuna/issues#1915]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Qt老版本离线安装工具

### 上游地址与镜像方法 (How to mirror)

无

### 镜像大小 (Mirror size)

2.3G

### 备注 (Note)

无

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
我们不知道如何获得您所说的“Qt老版本离线安装工具”

**Comment by TsingHeSZU** [comment]
貌似我用清华开源镜像下载老版本的QT 5.14.2 的离线安装包的时候，找不到下载源，报错404




TsingHe
***@***.***







                       
Original Email
                       
                     

Sender:"Shengqi Chen"< ***@***.*** &gt;;

Sent Time:2024/3/12 15:01

To:"tuna/issues"< ***@***.*** &gt;;

Cc recipient:"TsingHe"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [tuna/issues] [镜像请求]  (Issue #1915)




 
我们不知道如何获得您所说的“Qt老版本离线安装工具”

**Comment by Harry-Chen** [comment]
Duplicated with #1909 

这不是镜像请求，请不要使用错误类型的模板。
