### ISSUE TITLE
Macports在sync的时候发生错误

### ISSUE THREAD

**Issue by JacobW92** [tuna/issues#192]
macports 在sync后会出现这个错误

`receiving file list ... rsync: change_dir "/release/PortIndex_darwin_16_i386" (in macports) failed: No such file or directory (2)`
`done`

`sent 4 bytes  received 9 bytes  8.67 bytes/sec`
`total size is 0  speedup is 0.00`
`rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(1404) [receiver=2.6.9]
Command failed: /usr/bin/rsync -rtzv --delete-after rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/PortIndex_darwin_16_i386/PortIndex /opt/local/var/macports/sources/mirrors.tuna.tsinghua.edu.cn/macports/release`
`Exit code: 23`
`Creating port index in /opt/local/var/macports/sources/mirrors.tuna.tsinghua.edu.cn/macports/release`

`Total number of ports parsed:	0`
`Ports successfully parsed:	0`
`Ports failed:			0`
`Up-to-date ports skipped:	0`

dalao们。。这个要怎么解决？

**Comment by huiyiqun** [comment]
我不是mac用户，但是从你的日志来看是路径配置有问题。

你日志里提到的
rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/PortIndex_darwin_16_i386/
实际应该在
rsync rsync://mirrors.tuna.tsinghua.edu.cn/macports/release/ports/PortIndex_darwin_16_i386/

你看看在配置里能否修改一下路径？
