### ISSUE TITLE
[镜像请求] dfx development tool package mirror

### ISSUE THREAD

**Issue by vincent-dfinity** [tuna/issues#1920]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

我们是来自瑞士的 [DFINITY 基金会](https://dfinity.org/)，致力于 Web3。
- 我们的核心产品是互联网计算机，这是我们的[开发文档](https://internetcomputer.org/docs/current/developer-docs/getting-started/overview-of-icp) 
- 我们的开发工具叫 [dfx](https://internetcomputer.org/docs/current/developer-docs/developer-tools/cli-tools/cli-reference/) 发布在 [GitHub](https://github.com/dfinity/sdk/releases)，我们希望能发布在国内镜像，提高国内开发者的体验。

### 上游地址与镜像方法 (How to mirror)

https://github.com/dfinity/sdk/releases

### 镜像大小 (Mirror size)

一次版本发布约 370MB（包括Linux、Mac多平台）。

### 备注 (Note)

可以跳过Beta版本以节约系统资源。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
根据 #941 第 8、13 条，不予接受。
