### ISSUE TITLE
Linuxbrew 使用TUNA源安装时提示缺少bottle

### ISSUE THREAD

**Issue by liangqijie** [tuna/issues#1921]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在 安装清华源的 homebrew 时，curl 没能从清华源下载 homebrew-bottles/bottles-portable-ruby 文件夹下的 portable-ruby-3.1.4.x86_64_linux.bottle.tar.gz，而是从 ghcr-io 上下载了

截图如下：
![图片](https://github.com/tuna/issues/assets/73884246/c55e0958-78fe-4aa6-8c15-5c54e92c69e5)

而且我在 homebrew-bottles/bottles-portable-ruby 文件夹下也没发现 portable-ruby-3.1.4.x86_64_linux.bottle.tar.gz

### 期望的现象（What you expected to happen）

希望能正常下载 portable-ruby-3.1.4.x86_64_linux.bottle.tar.gz

### 如何重现此问题（How to reproduce it）

```shell
export HOMEBREW_INSTALL_FROM_API=1
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"

git clone --depth=1 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/install.git brew-install
/bin/bash brew-install/install.sh
```

输出：
如图所示
![图片](https://github.com/tuna/issues/assets/73884246/dc88a4d9-ddbb-49c3-b6e6-706d8ae0794d)

### 操作系统（OS Version）

Debian 12 bookworm stable

**Comment by Harry-Chen** [comment]
感谢，已经修复
