### ISSUE TITLE
404：https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu-old-releases/

### ISSUE THREAD

**Issue by shuaiplusplus** [tuna/issues#1923]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

404 when accessing https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu-old-releases/

### 期望的现象（What you expected to happen）

show clearly

### 如何重现此问题（How to reproduce it）

just open the link

**Comment by Harry-Chen** [comment]
我们没有镜像过此仓库，这不是预期现象。如有需要，请考虑使用 https://mirrors.ustc.edu.cn/ubuntu-old-releases/

**Comment by shuaiplusplus** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/ 但是在此页面中包含了此链接：
![image](https://github.com/tuna/issues/assets/21326839/3ae7f43f-0a1d-47f3-b45d-fcd9e6f02c73)

**Comment by Harry-Chen** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/ 但是在此页面中包含了此链接： ![image](https://private-user-images.githubusercontent.com/21326839/319007463-3ae7f43f-0a1d-47f3-b45d-fcd9e6f02c73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTQ2ODcsIm5iZiI6MTcxMjExNDM4NywicGF0aCI6Ii8yMTMyNjgzOS8zMTkwMDc0NjMtM2FlN2Y0M2YtMGExZC00N2YzLWI0NWQtZmNkOWU2ZjAyYzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAzMTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2M2RhZWJkYzA0YzBjZTc2YmRhY2FkYzEyMjY1ZWEzNmMzYjY1MTQxZTBlNTg3MGQzY2VhY2I4OWIzMmI5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1yfrfX81nzBLHFScsTXUo354GiONvyGeMwGUIn3EoKA)

感谢指出，我们会更新此文档，移除相关内容。
