### ISSUE TITLE
rsync  --delete-after 同步centos-stream报错

### ISSUE THREAD

**Issue by Lzh566566** [tuna/issues#1924]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

rsync 同步时，如果加了--delete-after 参数，同步到一定进度，会报错 connetion reset by peer 
![image](https://github.com/tuna/issues/assets/33414509/b68c6e8c-a7c3-449d-bfff-4f2c3b4c4f43)
--delete-after 改成--delete后可以正常同步

### 期望的现象（What you expected to happen）

同步成功

### 如何重现此问题（How to reproduce it）

rsync   --delete-after

**Comment by shankerwangmiao** [comment]
请您参考 https://github.com/tuna/issues/issues/1877#issuecomment-1880945750，检查是否是 rsync 的问题导致的。

**Comment by Lzh566566** [comment]
> 请您参考 [https://github.com/tuna/issues/issues/1877#issuecomment-1880945750，检查是否是](https://github.com/tuna/issues/issues/1877#issuecomment-1880945750%EF%BC%8C%E6%A3%80%E6%9F%A5%E6%98%AF%E5%90%A6%E6%98%AF) rsync 的问题导致的。

应该不是这个问题。已经升级版本了

**Comment by shankerwangmiao** [comment]
我排查了一下我们服务器的日志，目前看到是因为 IO 超时导致的。建议您检查您的网络中是否存在限制连接时常的防火墙一类的设备干扰了同步。
