### ISSUE TITLE
Wireshark同步停止在2023年

### ISSUE THREAD

**Issue by happyaron** [tuna/issues#1925]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Wireshark已更新4.2.4，镜像里最新4.2.0rc2，发布于2023年10月。

### 期望的现象（What you expected to happen）

同步最新版本

### 如何重现此问题（How to reproduce it）

查看地址 https://mirrors.tuna.tsinghua.edu.cn/wireshark/win64/

**Comment by Harry-Chen** [comment]
rsync 上游 rsync://rsync.wireshark.org/wsdl/ 看起来已经停止更新了，目前只有 HTTP 上游 https://1.as.dl.wireshark.org/

**Comment by Harry-Chen** [comment]
官方页面上列出的非官方镜像站 https://www.wireshark.org/mirror.html 也都有此问题

**Comment by Harry-Chen** [comment]
已经向上游提交： https://gitlab.com/wireshark/wireshark/-/issues/19748

**Comment by Harry-Chen** [comment]
上游已经修复，TUNA 也已经同步了最新的版本。
