### ISSUE TITLE
Debian12bookworm 403错误

### ISSUE THREAD

**Issue by lbp0200** [tuna/issues#1927]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Debian 12 bookworm 使用北外镜像
apt update 出现403错误
改为北邮镜像正常

### 期望的现象（What you expected to happen）

正常apt update

### 如何重现此问题（How to reproduce it）

Debian 12 bookworm 使用北外镜像
apt update

### 操作系统（OS Version）

Debian 12 bookworm

**Comment by Harry-Chen** [comment]
请使用浏览器下载相应文件，检查是否有错误页面，并给我们发送对应的诊断代码。
