### ISSUE TITLE
Fedora 升级到 39 的时候，下载 fedora-modular 元数据返回 404

### ISSUE THREAD

**Issue by oodzchen** [tuna/issues#1929]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

当前系统为Fedora 38, 执行`sudo dnf system-upgrade download --releasever=39`下载Fedora 39升级文件，结果出现404错误
> Errors during downloading metadata for repository 'fedora-modular':  
Status code: 404 for https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/39/Modular/x86_64/os/repodata/repomd.xml (IP: 101.6.15.130)
错误：为仓库 'fedora-modular' 下载元数据失败 : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

### 期望的现象（What you expected to happen）

可以正常下载文件

### 如何重现此问题（How to reproduce it）

按照Fedora官方的升级文件进行发行版升级操作：https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/

### 操作系统（OS Version）

Fedora 39

**Comment by taoky** [comment]
Fedora 39 压根就没有 fedora-modular：https://fedoraproject.org/wiki/Changes/No_default_fedora-repos-modular

**Comment by oodzchen** [comment]
@taoky 嗯呐，我刚刚也发现了，那没事了
