### ISSUE TITLE
升级Anaconda的WARNING

### ISSUE THREAD

**Issue by muxuezi** [tuna/issues#193]
Hello, 
最近升级Anaconda的WARNING：

Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the requested
channel with url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please **request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty**.

希望创建 `noarch/repodata.json` 和 `noarch/repodata.json.bz2` 

Thank you very much!

**Comment by bigeagle** [comment]
好的～

**Comment by bigeagle** [comment]
抱歉跟进晚了，现在正在同步。

**Comment by shankerwangmiao** [comment]
已经同步完了
