### ISSUE TITLE
[镜像请求] https://mirrors.tuna.tsinghua.edu.cn/npm/

### ISSUE THREAD

**Issue by wwh133** [tuna/issues#1931]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

NPM 镜像源

### 上游地址与镜像方法 (How to mirror)

https://mirrors.tuna.tsinghua.edu.cn/npm/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
NPM 在 #290 已经讨论过，也在 #741 中作为典型例子给出。我们的 Issue 模板不是 EULA，不应当不加思考地点确认。

根据[行为准则](https://github.com/tuna/issues/blob/master/CODE_OF_CONDUCT.md)，这是一次正式警告。
