### ISSUE TITLE
Homebrew 镜像报错 502 Bad Gateway

### ISSUE THREAD

**Issue by doctormin** [tuna/issues#1934]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

brew update 运行报错如下
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git/': The requested URL returned error: 502
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-drivers.git/': The requested URL returned error: 502
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-command-not-found.git/': The requested URL returned error: 502
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-versions.git/': The requested URL returned error: 502
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-fonts.git/': The requested URL returned error: 502
- fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-services.git/': The requested URL returned error: 502

### 如何重现此问题（How to reproduce it）

按照官方指引配置 https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/ 后，运行 brew update

### 操作系统（OS Version）

MacOS Sonoma 14.5 (Apple Silicon)

### 其他需要说明的事项（Anything else we need to know）
1. 已排除本地代理、VPN等影响
2. Tuna 的 brew 镜像我已正常使用约两年，大约是昨日开始出现 502 报错

**Comment by shankerwangmiao** [comment]
感谢反馈，已经恢复。
