### ISSUE TITLE
清华大学的开源镜像站怎么没更新收录rocky这个linux？（rocky是原centos创始人和它的团队在centos被收购后重新开发的兼容现有centos软件） 

### ISSUE THREAD

**Issue by applist365** [tuna/issues#1935]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

清华大学的开源镜像站怎么没更新收录rocky这个linux？（rocky是原centos创始人和它的团队在centos被收购后重新开发的兼容现有centos软件）
Rocky Linux社区提供的免费Linux操作系统
一个开源、社区拥有和管理、免费的企业Linux发行版，提供强大的生产级平台。可作为CentOS停止维护（改为滚动更新的Stream版）后，RHEL的下游Linux操作系统替代方案，并继承了原CentOS的开源免费特点。
CentOS宣布停止开发后，CentOS的原创始人Gregory Kurtzer在CentOS网站上发表评论宣布，他将再次启动一个项目以实现CentOS的最初目标。它的名字被选为对早期CentOS联合创始人Rocky McGaugh的致敬。到12月12 日，Rocky Linux的代码仓库已经成为GitHub上的热门仓库 [2]。
2020年12月，Rocky Linux宣布初始版本的目标是在2021年3月至5月之间的任何时间。2021年1月20日，宣布将在2月底之前向公众提供一个测试存储库，并且发布候选版本的目标是2021年3月底。但是，那个日期稍微推迟了些。
2021年4月30日，社区发布了首个候选版本8.3。
2021年6月4日，社区发布了第二个候选版本8.4，这也是稳定版本之前的最后一个版本。
2021年6月21日，社区发布了Rocky Linux 8.4的稳定版本，代号为“Green Obsidian”，并作为首个正式稳定版 [3]。
2022年中旬，Rocky Linux 9.0进入测试验证阶段。社区计划在2022年6月至2022年7月的时间范围内正式发布新版本 [4]。（对应前期发布的RHEL 9.0，Linux5.x内核）
2022年7月16日，IT之家消息，Rocky Linux社区宣布，Rocky Linux 9.0 操作系统全面上市，可作为CentOS Linux和CentOS Stream的直接替代品。 [5]
2023年5月16日，Rocky Linux社区官博发表了Rocky Linux 9.2发布的消息。 [9]
2023年11月20日，Rocky Linux社区官博发表了Rocky Linux 9.3发布的消息。

### 上游地址与镜像方法 (How to mirror)

rocky官方中文网站
https://rockylinux.org/zh_CN/download/

### 镜像大小 (Mirror size)

DVD版本9.8GB    
有好几种版本

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Songxwn** [comment]
![image](https://github.com/tuna/issues/assets/21145071/db9066de-3a8a-4be3-a3e2-a0d17bbace5f)

EPEL 软件库的访问日志数据，Rocky Linux占比已经很大了，目前已经有必要加入镜像

**Comment by applist365** [comment]
他必须添加这个镜像，因为国内没有比国际开源做的好的。都是换壳改版。
而且centos7 2024年结束支持，到时候连安全补丁都没有。
centos8早就结束支持了。
centos9 是上游开发版本，不适合商用。。
目前只有rocky linux 沿袭centos架构和体系结构以及操作方式，因为rocky是centos创始人在centos被oracle收购之后重新出的系统，完全兼容centos的软件
我已经生产使用rocky到现在7个月了。没有任何问题。

**Comment by applist365** [comment]
并且rocky linux是完全开源和免费的。

**Comment by so1ve** [comment]
《必须添加这个镜像》😄
