### ISSUE TITLE
qt镜像源报错,提示某个文件无法下载

### ISSUE THREAD

**Issue by NampSec** [tuna/issues#1936]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用qt官方的安装器，加上参数 --mirror https://mirrors.bfsu.edu.cn/qt，选择qt 6.7.0版本进行下载，下载后会提示某个文件不存在。

### 期望的现象（What you expected to happen）

能够成功安装

### 如何重现此问题（How to reproduce it）

使用qt官方的安装器，加上参数 --mirror https://mirrors.bfsu.edu.cn/qt，选择qt 6.7.0版本进行下载，下载后会提示某个文件不存在。

### 操作系统（OS Version）

win11

**Comment by Harry-Chen** [comment]
“某个文件”，具体是哪个文件？

**Comment by NampSec** [comment]
> “某个文件”，具体是哪个文件？
qt的报错为：
Cannot download archive https://mirrors.bfsu.edu.cn/qt//online/qtsdkrepository/windows_x86/desktop/tools_qtdesignstudio_generation2/qt.tools.qtdesignstudio/4.4.0-0-202402190721qtdesignviewer_arm64-v8a.zip: Error transferring https://mirrors.bfsu.edu.cn/qt//online/qtsdkrepository/windows_x86/desktop/tools_qtdesignstudio_generation2/qt.tools.qtdesignstudio/4.4.0-0-202402190721qtdesignviewer_arm64-v8a.zip - server replied: Forbidden

**Comment by Harry-Chen** [comment]
请使用浏览器打开此路径，并回复网页上的识别码。

**Comment by snylonue** [comment]
请重新打开该问题，遇到了相同的问题。

在浏览器中打开会直接进行下载

**Comment by NampSec** [comment]
> 请重新打开该问题，遇到了相同的问题。
> 
> 在浏览器中打开会直接进行下载

已打开

**Comment by yangon99** [comment]
今天尝试时遇到了类似的问题，使用 qt online 安装器会提示 ` server replied: Forbidden` ，浏览器和使用 `curl.exe` 可以正常下载
尝试抓包获取到的code为 ： `00000071 622c6977d2ded88580fb17507b6d7d49`

qt 安装器错误信息：
```
无法下载存档 http://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/windows_x86/desktop/tools_qtdesignstudio_generation2/qt.tools.qtdesignstudio/4.5.1-0-202406201234qtdesignviewer_arm64-v8a.zip：Error transferring http://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/windows_x86/desktop/tools_qtdesignstudio_generation2/qt.tools.qtdesignstudio/4.5.1-0-202406201234qtdesignviewer_arm64-v8a.zip - server replied: Forbidden
```

**Comment by huawu107** [comment]
同样的问题，打开链接会直接下载。
`无法下载存档 https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/all_os/qt/qt6_681_windows_line_endings_src/qt.qt6.681.doc/6.8.1-0-202411221531qt5-documentation.zip：Error transferring https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/all_os/qt/qt6_681_windows_line_endings_src/qt.qt6.681.doc/6.8.1-0-202411221531qt5-documentation.zip - server replied: Forbidden`

**Comment by OkayPJ** [comment]
遇到同样问题，清华源、ustc和腾讯源都有同样报错

**Comment by GADDQ** [comment]
遇到同样问题，下载qt6.8.1时遇到该问题

**Comment by GADDQ** [comment]
@utmux

**Comment by Xiaoyouyou** [comment]
我也遇到这个问题了，有什么好的方案解决吗？
下载“https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/all_os/unified_patching/2023-11-21-1039_meta.7z”时出现网络错误：Error transferring https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/all_os/unified_patching/2023-11-21-1039_meta.7z - server replied: Forbidden。

您可以为开源的元数据和下载选择一个不同的镜像。您可以在控制台下通过--mirror选项进行设置。这里是可用的镜像：
https://download.qt.io/online/qtsdkrepository/windows_x86/root/qt/Updates.xml.mirrorlist
不要使用完整路径，请使用'/online'之前的路径(末尾没有正斜杠)

**Comment by sc3263** [comment]
我这边也遇到了。简单试了下，可能和User-Agent有关。
* Charles抓包看，Qt Maintenance Tool向镜像站发起的网络请求，User-Agent均为`Mozilla/5.0`。
![Image](https://github.com/user-attachments/assets/d179dff5-9cd3-442f-b23b-2eca23de4fbf)
镜像站会返回403错误页
* 使用curl测试。
`curl "https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/all_os/qt/qt6_682_unix_line_endings_src/qt.qt6.682.src/6.8.2-0-202501260838qtdoc-everywhere-src-6.8.2.tar.xz.sha1"`
可以正常访问。
`curl -H "User-Agent: Mozilla/5.0" "https://mirrors.tuna.tsinghua.edu.cn/qt/online/qtsdkrepository/all_os/qt/qt6_682_unix_line_endings_src/qt.qt6.682.src/6.8.2-0-202501260838qtdoc-everywhere-src-6.8.2.tar.xz.sha1"`
就会返回403错误页。

**Comment by taoky** [comment]
https://bugreports.qt.io/browse/QTBUG-129057

**Comment by shapled** [comment]
pip install mitmproxy
mitmproxy -p 80 --mode reverse:mirrors.tuna.tsinghua.edu.cn -H "/~q/User-Agent/QtUnifiedInstaller"
installer --mirror http://127.0.0.1/qt
