### ISSUE TITLE
Kodi的插件源无法使用

### ISSUE THREAD

**Issue by lvzhenbo** [tuna/issues#1937]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

和这个issue https://github.com/xbmc/xbmc/issues/16104 一样的问题，我看这个issue https://github.com/tuna/issues/issues/1112 所说不需要sha256，但是官方确实目前在程序中进行了校验

### 期望的现象（What you expected to happen）

插件镜像源可用

### 如何重现此问题（How to reproduce it）

下载安装kodi 21版本，按照镜像库 https://mirrors.tuna.tsinghua.edu.cn/help/kodi/ 所说修改对应文件，启动kodi，刷新插件库信息

### 操作系统（OS Version）

Win 11

### 其他环境（Other environments）

Kodi 21.0

**Comment by Harry-Chen** [comment]
直接尝试我们的上游是否可以工作? 链接为 `mirror.yandex.ru/mirrors/xbmc/`

**Comment by lvzhenbo** [comment]
好吧，我想是上游的问题
