### ISSUE TITLE
https://pypi.tuna.tsinghua.edu.cn/simple

### ISSUE THREAD

**Issue by xiaoyanbuzai** [tuna/issues#1939]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

镜像源打不开 

### 期望的现象（What you expected to happen）

能打开 下载包

### 如何重现此问题（How to reproduce it）

被攻击了？

### 操作系统（OS Version）

windows

### 其他环境（Other environments）

python

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by Harry-Chen** [comment]
请仔细描述“打不开”的现象、错误码、URL 等。
