### ISSUE TITLE
帮助文档需要更新：Ubuntu noble默认使用DEB822格式的配置文件

### ISSUE THREAD

**Issue by thelastlin** [tuna/issues#1940]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

从noble开始，Ubuntu使用DEB822格式，对应的配置文件应修改为 `/etc/apt/sources.list.d/ubuntu.sources`。

对于全新安装，`/etc/apt/sources.list`内容为：
```
# Ubuntu sources have moved to /etc/apt/sources.list.d/ubuntu.sources
```

`/etc/apt/sources.list.d/ubuntu.sources` 内容为：
```

Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu/
Suites: noble-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

### 期望的现象（What you expected to happen）

对于Ubuntu noble及以后的版本，帮助文档里应说明需按照DEB822的格式修改 `/etc/apt/sources.list.d/ubuntu.sources` 的内容。

### 如何重现此问题（How to reproduce it）

-

### 操作系统（OS Version）

Ubuntu noble

### 其他需要说明的事项（Anything else we need to know）

参考信息：
- [[Spec] APT deb822 sources by default ](https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333)

- ustclug/mirrorhelp#244

**Comment by Huayuluoshi** [comment]
并且，帮助手册未更新ubuntu2404相关内容

**Comment by Harry-Chen** [comment]
目前 Debian 和 Ubuntu 的帮助均已经更新。
