### ISSUE TITLE
北外镜像站 openSUSE 镜像已过期近一个月

### ISSUE THREAD

**Issue by emf37** [tuna/issues#1941]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

查看北外openSUSE镜像发现镜像内容停止在3月30日，查看上游发现https://ftp.gwdg.de/pub/opensuse中内容亦停留在3月30日，上游显示同步正常，北外镜像站显示同步正常；
查看Tuna openSUSE镜像发现镜像内容为4月21日，镜像上游https://ftp.gwdg.de/pub/opensuse中内容为4月20日为正常更新日期

### 期望的现象（What you expected to happen）

建议更换北外镜像站openSUSE镜像上游以保持更新

### 如何重现此问题（How to reproduce it）

对比https://mirrors.bfsu.edu.cn/opensuse/tumbleweed/iso/ 与 https://ftp.gwdg.de/pub/opensuse/tumbleweed/iso/

**Comment by shankerwangmiao** [comment]
已经向上游反馈此问题。目测是上游的 https://ftp.gwdg.de/pub/opensuse/Archive-Update-in-Progress-ftp6.gwdg.de 阻碍了同步。

**Comment by emf37** [comment]
> 已经向上游反馈此问题。目测是上游的 https://ftp.gwdg.de/pub/opensuse/Archive-Update-in-Progress-ftp6.gwdg.de 阻碍了同步。

好的，谢谢您

**Comment by Harry-Chen** [comment]
问题已经修复
