### ISSUE TITLE
[镜像请求] cef资源

### ISSUE THREAD

**Issue by errorcode7** [tuna/issues#1942]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Chromium Embedded Framework (CEF)是个基于Google Chromium项目的开源Web browser控件，支持Windows, Linux, Mac平台。除了提供C/C++接口外，也有其他语言的移植版。

### 上游地址与镜像方法 (How to mirror)

[arm,linux] https://cef-builds.spotifycdn.com/index.html
[loongarch] http://ftp.loongnix.cn/cef/LoongArch/

### 镜像大小 (Mirror size)

300 MB	

### 备注 (Note)

https://cef-builds.spotifycdn.com/index.html 是静态网页，资源需要解析https://cef-builds.spotifycdn.com/index.json 才能获取到地址。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
下载的具体是什么？SDK / 共享库 / 二进制文件？对于用户有什么用处？

**Comment by errorcode7** [comment]
属于二进制文件\共享库,使用web技术开发gui的框架，类似electron。
参考：https://www.cnblogs.com/feipeng8848/p/10831842.html

**Comment by Harry-Chen** [comment]
1. 镜像文件**单个**体积就有 300MB 左右，整个仓库的体积远大于这个数字
2. 看起来项目本身已经有 CDN 分发了

**Comment by Harry-Chen** [comment]
在目前情况下，我们暂不考虑增加此镜像。
