### ISSUE TITLE
[镜像请求] Deno releases

### ISSUE THREAD

**Issue by stackinspector** [tuna/issues#1944]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

来自[官网](https://deno.com/)
Deno is the open-source JavaScript runtime for the modern web. Built on web standards with zero-config TypeScript, unmatched security, and a complete built-in toolchain, Deno is the easiest, most productive way to JavaScript.

### 上游地址与镜像方法 (How to mirror)

https://github.com/denoland/deno/releases/
常规的GitHub releases，鉴于《必读》中已写明支持该种同步方式且有Git、VS Codium等先例，不再赘述。

### 镜像大小 (Mirror size)

最新的release（`1.42.4 / 2024.04.15`，不含source code）所有平台总大小335.1MB。鉴于这是一个runtime，保存历史版本可能有一定价值，但我不确定有多大。

### 备注 (Note)

Deno发布1.0已经近4年了。我不确定它在国内的用户群体有多大，是否值得添加镜像。国内绝大多数听说它的人都是通过营销号文章和某些事件，转化为真正的使用者的我不好说有多少。这个由你们评估吧。
据我所知还没有国内高校镜像站镜像了它的release，在[教育网联合镜像站](https://mirrors.cernet.edu.cn/)搜索也没有找到相关结果。
@justjavac 运行了一个[镜像站](dl.deno.js.cn)，目前仍包含最新的Deno版本。（在写这个issue的时候才发现他建立了新的镜像站，之前他的安装器的镜像方式是手动更新到Gitee，早已停更。）

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
已经完成同步。由于历史版本过多，只下载了最新的版本。

可提出 PR 更新 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 以增加下载链接。

**Comment by stackinspector** [comment]
> 可提出 PR 更新 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 以增加下载链接。

已在 tuna/mirror-web#428 中添加。
