### ISSUE TITLE
pypi镜像源未同步更新

### ISSUE THREAD

**Issue by JaheimLee** [tuna/issues#1946]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

最近更新停留在2024-04-25 01:40

### 期望的现象（What you expected to happen）

按照pypi帮助文档里的说法，同步成功后5分钟进行下一次同步

### 如何重现此问题（How to reproduce it）

无

**Comment by shankerwangmiao** [comment]
您好，同步的启动会收到服务器同时进行的任务数目限制。如果超出了该限制，则会相应顺延。目前同步已经启动。
