### ISSUE TITLE
QT 5.12.12 can't download

### ISSUE THREAD

**Issue by damaoNo** [tuna/issues#1947]
QT 5.12.12 can't download

**Comment by Harry-Chen** [comment]
请详细说明您下载的 URL、遇到的问题。

**Comment by damaoNo** [comment]
> 请详细说明您下载的 URL、遇到的问题。

![微信图片_20240427002030](https://github.com/tuna/issues/assets/28343723/c3b66f7a-d471-4975-95a5-99889af715ee)

**Comment by Harry-Chen** [comment]
Duplicated with #1909
