### ISSUE TITLE
提议：停止更新 Dotdeb 镜像

### ISSUE THREAD

**Issue by DarkmatterUAE** [tuna/issues#1951]
据 [Debian Wiki 相关页面](https://wiki.debian.org/DebianRepository/Unofficial) 和 www.Dotdeb.org ，Dotdeb 已停止更新，且 rsync 访问已关闭，故提议停止更新该镜像以节约频宽和伺服资源。

另，若据统计该镜像访问量不高，可附加提议删除，节约硬碟空间。

https://github.com/tuna/issues/issues/725

**Comment by Harry-Chen** [comment]
感谢，我们将会移除此镜像。

**Comment by Harry-Chen** [comment]
镜像已经移除。

**Comment by DarkmatterUAE** [comment]
@Harry-Chen 感谢！
