### ISSUE TITLE
  base.yaml的3911行：gentoo: [dev-cpp/gtkmm:3.0]  报错！！！

### ISSUE THREAD

**Issue by sillybisme** [tuna/issues#1952]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

ubuntu@ubuntu-virtual-machine:~$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/osx-homebrew.yaml
ERROR: unable to process source [https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/base.yaml]:
	while scanning a plain scalar
  in "<byte string>", line 3911, column 12:
      gentoo: [dev-cpp/gtkmm:3.0]
               ^
found unexpected ':'
  in "<byte string>", line 3911, column 25:
      gentoo: [dev-cpp/gtkmm:3.0]
                            ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/python.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/ruby.yaml

### 期望的现象（What you expected to happen）

rosdep update直接能运行

### 如何重现此问题（How to reproduce it）

安装不了ros melodic

### 操作系统（OS Version）

ubuntu 18.04

**Comment by Harry-Chen** [comment]
上游如此，请向上游报告问题。

https://github.com/ros/rosdistro/blob/75f6f9c6883d333958eedf5e2eee418933b579dd/rosdep/base.yaml#L3906-L3913
