### ISSUE TITLE
无法用该镜像源创建新环境

### ISSUE THREAD

**Issue by ljs12321** [tuna/issues#1954]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/current_repodata.json>
不存在该current_repodata.json文件。

### 期望的现象（What you expected to happen）

正常找到该文件

### 如何重现此问题（How to reproduce it）

用conda无法安装新的python环境

**Comment by shankerwangmiao** [comment]
该文件不存在不影响正常使用。注意到您提供的错误信息中，具体错误是 CONNECTION FAILED，说明是您的主机无法正常连接镜像站服务器，建议您排查网络是否正常。
