### ISSUE TITLE
pypi transformers包未同步

### ISSUE THREAD

**Issue by Quarkstar** [tuna/issues#1955]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[pypi transformers](https://pypi.org/simple/transformers/) 最新版本为4.40.2，发布时间为一天前。
[tuna pypi transformers](https://pypi.tuna.tsinghua.edu.cn/simple/transformers/) 的最新版本为4.40.1，[网页](https://mirrors.cernet.edu.cn/list/pypi)显示tuna已经成功同步pypi。

### 期望的现象（What you expected to happen）

[tuna pypi transformers](https://pypi.tuna.tsinghua.edu.cn/simple/transformers/) 与 [pypi transformers](https://pypi.org/simple/transformers/) 内容相同 

### 如何重现此问题（How to reproduce it）

[tuna pypi transformers](https://pypi.tuna.tsinghua.edu.cn/simple/transformers/)
[pypi transformers](https://pypi.org/simple/transformers/) 

### 其他需要说明的事项（Anything else we need to know）

该问题与 #1701 #1897 #1908 等问题相似。

**Comment by shankerwangmiao** [comment]
您好，已经完成同步

**Comment by Quarkstar** [comment]
感谢！
