### ISSUE TITLE
AOSP repo sync 出现问题 24-05-01

### ISSUE THREAD

**Issue by OYXS520** [tuna/issues#1958]
使用的是最新的 
https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-20240501.tar

```
aosp$ repo sync
==========
Repo command failed: RepoUnhandledExceptionError
```

去  `aosp/.repo/repo`  执行了  `git pull` 后
再次执行出现同样的报错

系统Ubuntu 22.04

**Comment by shankerwangmiao** [comment]
您好，请给出完整的报错输出。

**Comment by OYXS520** [comment]
```
aosp$ repo sync
==========
Repo command failed: RepoUnhandledExceptionError
```
这个就是完整的日志输出，后续我发现我的python使用的3.10的版本，导致上述问题，我尝试降低为3.9该问题解决了，但是又陆陆续续出现一些新的问题，貌似都是和python版本有关的，我需要去找到一个合适的python版本

**Comment by shankerwangmiao** [comment]
我刚才用 Python 3.11.2 测试了一下，没能复现您所说的问题

**Comment by OYXS520** [comment]
抱歉是我的问题，我使用的mac下载aosp.tar并在移动固态硬盘中解压的，移动硬盘的文件格式exFat，解压时就抱错了，可惜我并没有及时发现，项目中的.git链接文件，支持的ext4的格式，我是用Ubuntu系统重新尝试，一点问题也没有，Thanks
