### ISSUE TITLE
antiX-23.1 未同步

### ISSUE THREAD

**Issue by Arnie97** [tuna/issues#1959]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/mxlinux-isos/ANTIX/Final/antiX-23.1/ 不存在

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/mxlinux-isos/ANTIX/Final/ 包含 antiX-23.1 子目录，不再包含 antiX-23

### 如何重现此问题（How to reproduce it）

https://antixlinux.com/download/ 搜索 tuna 并点击，进入 404 页面

### 其他需要说明的事项（Anything else we need to know）

不太确定 /mxlinux-isos 是否是 /osdn/storage/g/m/mx/mx-linux/ISOs 的符号链接。若是，则此问题是 #1892 的一部分

**Comment by shankerwangmiao** [comment]
感谢您反馈此问题，已经修复。
