### ISSUE TITLE
希望添加LEDE Projects镜像

### ISSUE THREAD

**Issue by leon0516** [tuna/issues#196]
#### 项目名称与简介(Project Intro.)

官方解释说，LEDE 是 OpenWrt 的一个分支，或者说是副产品，该项目主要关注透明性，协作和分权。

LEDE 是 OpenWrt 社区的新生，有很多目标是与 OpenWrt 相同的，但是相比于 OpenWrt 也有很大的区别。

LEDE 当前的目标是：
* 构建一个巨大的嵌入式 Linux 发行版，主要关注稳定性和功能
* 拥有规律，可预测的发行周期
* 建立透明的决策过程，加强社区参与和公共反馈
* 创建 LEDE 是因为 OpenWrt 有一些长期存在的问题，一直悬而未决：
    * 核心开发者活跃度低，也没有鼓励更多新成员加入的策略
    * 不可靠的基础设施，因为淡点故障和内部分歧而阻碍修复
    * 缺乏沟通，透明和协作，无论是核心团队还是核心团队与社区之间
    * 提交 commit 的人较少，不怎么关注测试和常规构建
    * 不关注稳定性和文档

为了解决这些问题，创建了 LEDE 项目，相比 OpenWrt 不同之处在于：

* 所有沟通频道都是公开的，一些对非开发成员限制只读权限
* 决策过程是公正公开的，大约有 50/50 的开发者和权威用户有投票权
* 基础设施非常简单，降低维护工作的难度
* 基于 OpenWrt 包在 Github 收到的反馈，合并策略更自由
* 强烈关注自动化测试，简历一个简单的发布流程

LEDE 项目地址：https://www.lede-project.org/

#### 上游地址与镜像方法(How to Mirror)
参见 [lede-manifest](https://github.com/troth/lede-manifest "Google Repo manifest to ease getting all lede projects." ) (Google Repo manifest to ease getting all lede projects.) 这里更详细

Docs:

* https://lede-project.org/docs/guide-developer/the-source-code

Git repos:

* https://git.lede-project.org/

#### 其他信息(Other)

- 镜像大小(Mirror Size):  

    和已镜像的openwrt大小差不多

**Comment by alick** [comment]
与 #127 重复
