### ISSUE TITLE
[镜像请求]  X.Org 

### ISSUE THREAD

**Issue by dZ8Lx9OwX** [tuna/issues#1960]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

X.Org 项目提供了 X Window System 的开源实现。

### 上游地址与镜像方法 (How to mirror)

上游地址：https://www.x.org/releases/
参考：https://www.x.org/wiki/Releases/Download/
[ftp]/[http]

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
你所述的是 Xorg 项目的源码，我们通常不镜像源码。此项目的二进制已经被各大发行版广泛打包。

**Comment by dZ8Lx9OwX** [comment]
非常感谢回复，尝试在Windows下编译，这些很难获得。并且没有一个很好的镜像去跟踪相关内容的变化。所以尝试提交这个镜像申请。可能是我对镜像提交的条件理解不到位，不过还是非常感谢回复。
