### ISSUE TITLE
kubernetes仓库是删掉了吗

### ISSUE THREAD

**Issue by liujie-jss** [tuna/issues#1962]
https://mirrors.tuna.tsinghua.edu.cn/kubernetes

Errors during downloading metadata for repository 'kubernetes':
  - Status code: 404 for https://mirrors.cqupt.edu.cn/kubernetes/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml 
错误：为仓库 'kubernetes' 下载元数据失败 : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by Harry-Chen** [comment]
您使用的是 cqupt 镜像，请转向相关管理方提出问题。

关于 tuna 删除 kubernetes 的相应决定，请参见 #1837 。

**Comment by Harry-Chen** [comment]
目前 TUNA 的 kubernetes 镜像已经重新上线，上游更改为 `rsync://rsync.opensuse.org/buildservice-repos-main/isv:/kubernetes:/`
