### ISSUE TITLE
关于CDI/CDM镜像的一些可能值得讨论的情况和建议

### ISSUE THREAD

**Issue by stackinspector** [tuna/issues#1963]
1. 软件作者似乎停止了在OSDN（[CDI](https://osdn.net/projects/crystaldiskinfo/) [CDM](https://osdn.net/projects/crystaldiskmark/)）上游的更新，导致目前版本相对陈旧，新的Aoi主题这里都没有。与之相比SourceForge（[CDI](https://sourceforge.net/projects/crystaldiskinfo/) [CDM](https://sourceforge.net/projects/crystaldiskmark/)）一直保持最新。
2. 关于主题版本，个人感觉把这种媒体资源占大头的东西放在空间紧张的开源镜像站有点奇怪，虽然确实是开源软件（）
3. 个人认为CDI/CDM没有保留历史版本的必要，不过不知道对于OSDN上游是否有方便的实现方式。

**Comment by Harry-Chen** [comment]
1. 根据 #928 以及目前镜像站的容量限制，我们无法同步 SourceForge
2. 我不了解您说的主题版本是指什么，具体在什么位置？
3. 对某个软件源内部，我们通常进行原样同步；只要不是占据太大空间，对其中的部分内容进行精细的排除需要的成本较大。
