### ISSUE TITLE
使用过一段时间清华源镜像之后会出现下面这种情况

### ISSUE THREAD

**Issue by Moxin1044** [tuna/issues#1965]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

尊敬的访问者，

Dear visitor,

Chère cliente,

訪問者へ 、

 

您好！

Hello!

Bonjour!

こんにちは ！

 

我们检测到您所在的子网和/或所使用的客户端存在大量下载某些较大二进制文件的行为，为保证用户的正常使用，我们阻断了此类请求。

We have detected enormous traffic from your network or client and have blocked your requests to ensure the quality of service for normal users.

Nous avons détecté un grand nombre de téléchargements de certains fichiers binaires volumineux à partir de votre sous-réseau et/ou du client que vous utilisez et avons bloqué ces requêtes pour garantir un accès normal aux utilisateurs.

お客様のサブネットおよび/またはクライアントで、特定の大きなバイナリのダウンロードを多数検出しました。お客様の通常の使用のためこれらのリクエストをブロックさせていただきます。

 

您可以尝试更改网络环境或更换客户端；您也可以联系 [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) 并附上下方的标识符。

You could try another network or client, or have your network administrator contact [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) with the identifier below.

Vous pouvez essayer de modifier votre environnement réseau ou de changer de client ; vous pouvez également contacter [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) avec l'identifiant ci-dessous.

ネットワーク環境の変更、クライアントの変更などをお試しください。また、下記の識別子を用いて [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) までご連絡ください。

 

00000069 e3a6515a1f7d29b33cf8187672e6647c

### 期望的现象（What you expected to happen）

大家使用清华源肯定是期望下载内容的，而正好拦截的原因就又是大量下载，这样感觉很抽象啊。

### 如何重现此问题（How to reproduce it）

大量的下载？或者？？多人使用了同一个宽带同时使用清华源？

**Comment by ZhiShengYuan** [comment]
请问您是否能够提供你所下载的文件列表

**Comment by Moxin1044** [comment]
> 请问您是否能够提供你所下载的文件列表

https://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases/24.04/ubuntu-24.04-live-server-amd64.iso

**Comment by shankerwangmiao** [comment]
您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。

您可以更换网络环境，或从其它来源获取您所需的资源。

**Comment by Moxin1044** [comment]
> 您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。
> 
> 您可以更换网络环境，或从其它来源获取您所需的资源。

抱歉，我们无法更换该地址段，该地址段为信阳职业技术学院校内连通运营商的IP段。另外，我认为别的软件源好像并没有相关限制，或许可以适当调整当前检测机制。

**Comment by Harry-Chen** [comment]
> > 您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。
> > 您可以更换网络环境，或从其它来源获取您所需的资源。
> 
> 抱歉，我们无法更换该地址段，该地址段为信阳职业技术学院校内连通运营商的IP段。另外，我认为别的软件源好像并没有相关限制，或许可以适当调整当前检测机制。

正如上面所说的，您可以更换没有进行限制的镜像。请参考 mirrors.cernet.edu.cn 获得更多列表。

**Comment by Moxin1044** [comment]
> > > 您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。
> > > 您可以更换网络环境，或从其它来源获取您所需的资源。
> > 
> > 
> > 抱歉，我们无法更换该地址段，该地址段为信阳职业技术学院校内连通运营商的IP段。另外，我认为别的软件源好像并没有相关限制，或许可以适当调整当前检测机制。
> 
> 正如上面所说的，您可以更换没有进行限制的镜像。请参考 mirrors.cernet.edu.cn 获得更多列表。

但是正如上所说，我们如果Docker PUll某个镜像的时候，他内置源是tuna，我们仍需要花费更多的精力去更换，如果是其他脚本，那更为致命。

**Comment by ZhiShengYuan** [comment]
> > > > 您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。
> > > > 您可以更换网络环境，或从其它来源获取您所需的资源。
> > > 
> > > 
> > > 抱歉，我们无法更换该地址段，该地址段为信阳职业技术学院校内连通运营商的IP段。另外，我认为别的软件源好像并没有相关限制，或许可以适当调整当前检测机制。
> > 
> > 
> > 正如上面所说的，您可以更换没有进行限制的镜像。请参考 mirrors.cernet.edu.cn 获得更多列表。
> 
> 但是正如上所说，我们如果Docker PUll某个镜像的时候，他内置源是tuna，我们仍需要花费更多的精力去更换，如果是其他脚本，那更为致命。

如果我没有记错的话贵校的IP(特别是IPV6)本身就存在反复下载ISO文件的行为？

**Comment by Moxin1044** [comment]
> > > > > 您好，您所在的 123.4.***.0/23 地址段因为存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。
> > > > > 您可以更换网络环境，或从其它来源获取您所需的资源。
> > > > 
> > > > 
> > > > 抱歉，我们无法更换该地址段，该地址段为信阳职业技术学院校内连通运营商的IP段。另外，我认为别的软件源好像并没有相关限制，或许可以适当调整当前检测机制。
> > > 
> > > 
> > > 正如上面所说的，您可以更换没有进行限制的镜像。请参考 mirrors.cernet.edu.cn 获得更多列表。
> > 
> > 
> > 但是正如上所说，我们如果Docker PUll某个镜像的时候，他内置源是tuna，我们仍需要花费更多的精力去更换，如果是其他脚本，那更为致命。
> 
> 如果我没有记错的话贵校的IP(特别是IPV6)本身就存在反复下载ISO文件的行为？

貌似是因为我们学校服务器用的都是CentOS，而且存在教学方式问题。
Eg: 某一老师讲述Linux操作的时候，可能会让大家都去某个指定页面下载ISO然后安装。毕竟是臭带专，很抽象的。

**Comment by Moxin1044** [comment]
个人觉得这个因为IP段而禁IP很抽象的。

**Comment by Harry-Chen** [comment]
> 个人觉得这个因为IP段而禁IP很抽象的。

如果不进行必要的限制，大多数用户的正常使用都会受到影响，请理解。在列入关注列表的地址段停止滥用行为 90 天后，我们会考虑移除。

**Comment by Moxin1044** [comment]
> > 个人觉得这个因为IP段而禁IP很抽象的。
> 
> 如果不进行必要的限制，大多数用户的正常使用都会受到影响，请理解。在列入关注列表的地址段停止滥用行为 90 天后，我们会考虑移除。

收到，并表示理解。

**Comment by charlesmz** [comment]
这个限制方式很不友好，就如上所说，它应该是根据外网IP来判定的，像我在的小区用的移动宽带，整个小区 区域就相当于一个局域网，都使用同一个对外的IP的，现在的宽带运营商都是这样。

**Comment by ZhiShengYuan** [comment]
> 这个限制方式很不友好，就如上所说，它应该是根据外网IP来判定的，像我在的小区用的移动宽带，整个小区 区域就相当于一个局域网，都使用同一个对外的IP的，现在的宽带运营商都是这样。

您好：请问您有什么更好的想法吗

*我不是TUNA的成员，我和TUNA不存在任何直接或者间接的关系

**Comment by charlesmz** [comment]
这个限制方式很不友好，就如上所说，它应该是根据外网IP来判定的，像我在的小区用的移动宽带，整个小区 区域就相当于一个局域网，都使用同一个对外的IP的，现在的宽带运营商都是这样。

**Comment by ZhiShengYuan** [comment]
> 这个限制方式很不友好，就如上所说，它应该是根据外网IP来判定的，像我在的小区用的移动宽带，整个小区 区域就相当于一个局域网，都使用同一个对外的IP的，现在的宽带运营商都是这样。

您好：那么您有什么更加友好的限制方式吗

*我不是TUNA的成员，我和TUNA不存在任何直接或者间接的关系

**Comment by SunJiaJing90** [comment]
我也遇到了同样的问题  我只更新一下Anaconda 然后几天没用在来更新 就发现ip被封了,必须三个月后才能接触是吗

**Comment by Moxin1044** [comment]
> 我也遇到了同样的问题  我只更新一下Anaconda 然后几天没用在来更新 就发现ip被封了,必须三个月后才能接触是吗

不清楚，很久没用了。之前在家里也是，更新一下pip，依赖有点多，然后就这样了。后面感觉nju和pku的挺快。经常用nju就没有这样子。

**Comment by AduosPiggy** [comment]
能否考虑付费下载呢，这样就限制了下载次数了？因为这ip莫名其妙被禁用了，下载镜像直接gg。
