### ISSUE TITLE
pypi镜像源有pywxdump软件包没有同步最新

### ISSUE THREAD

**Issue by xaoyaoo** [tuna/issues#1967]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

pypi镜像源有pywxdump软件包没有同步最新

### 期望的现象（What you expected to happen）

python的pywxdump软件包没有最新的几个版本
3.0.22，3.0.23

### 如何重现此问题（How to reproduce it）

pip install pywxdump=3.0.23

### 操作系统（OS Version）

window 10

### 浏览器（如果适用）（Browser version, if applicable）

不适用

### 其他环境（Other environments）

python 3.10

### 其他需要说明的事项（Anything else we need to know）

同时请问一下，同步时间大概多久同步一次

**Comment by shankerwangmiao** [comment]
已经补充同步完毕。

目前 pypi 会在前一次同步结束约 10 分钟左右开始下一次同步。
