### ISSUE TITLE
repomd.xml.asc is missing on grafana repo

### ISSUE THREAD

**Issue by yuniers** [tuna/issues#197]
Hi guys.
I'm trying install grafana on Centos 7 and when I made `yum makecache` this error is triggered:

```sh
failure: repodata/repomd.xml.asc from grafana: [Errno 256] No more mirrors to try.
https://mirrors.tuna.tsinghua.edu.cn/grafana/yum/el7/repodata/repomd.xml.asc: [Errno 14] HTTP Error 404 - Not Found
```

And it is true, the file doesn't exists.
Please, can you re sync or see what happens.

Thanks for this magnificent and wonderful mirror.

**Comment by yuniers** [comment]
On **packagecloud.io** [the file exist](https://packagecloud.io/grafana/stable/el/6/x86_64/repodata/repomd.xml.asc)
And it look like this:

```pgp
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQIcBAABAgAGBQJYd1SgAAoJEDe77j962Vs/5W8QAKsTxLyvKu5qgY62FUV6jKuC
FeM1wCs6QkDEhtlC0zNyCMWk9c0MC0bpEGxSRblRKF35xfQFha5wN2vy3E4Hth4y
u76RwnWSMDp0vefNvXj/BaXMOZ3uueBNDoP87QeESd+Q33sK8azcZqr/EkL3ejPQ
ntQPf6OzoslqWfmPzlBY4vSxNkOaAen3Tf0swlZLcex5LC3FUOxVU701eGNSpr0i
7NH2+XNci2eIfsPTRLAaZ9bGcGPU080ycsGW4rn1+xAQ51BndrvLnXJ7T0Jvg4+W
DE//JBtbiBLT+J4y8aqtHUcHg0XF6/ToR2QEcEUJMWGZzXQ8j1AGUPMhWtNc4CZL
yV9aqP+zYQec4Dy4o8ahUhMr2mAWpAfHgd8z1BcDvw9hZMV/qotGko/yhc2PrOk8
zattBJMk4w2b33Ww8vthiqbFLZghcF7KcJhEU2LTul1aUvyPVorWI+wq07orMWKU
LxmWSyTGSKNwzMzrHh5eUaWCL6mYYixmRFPGu/i+K1yCJlKJrPn5seHkHGXCyRkq
70Vt73zl1eAjxGY296WfmCZGdIF/itfkui8YIzNUwByMHFZttoCLpGvnP1sS5Idh
r1igZ2cUywd78HKfTU9HMWMq0KfOvVrLDde3n9YKEPXDKCgMdbR8ij9gHLbOnpsW
mf5ko1sKJRrehsOuurr6
=cceJ
-----END PGP SIGNATURE-----
```

**Comment by bigeagle** [comment]
You can try disabling GPG check by setting 
```
gpgcheck=1
```
in your repo file.

**Comment by alick** [comment]
@bigeagle, I think you have a typo. Your command actually enables the
checking.

Anyway, disabling GPG check should not be recommended except as a temporary
walkaround. There might be some issue with our upstream or syncing.

Regards,
Alick

**Comment by yuniers** [comment]
Thank you @bigeagle and @alick for answer. For security reasons, I have decided provide the repomd.xml.asc file for some repos like grafana and elasticstack using an alias on Nginx config file.

I expect that repomd.xml.asc file not change on very long time 😃 

```sh
location /path/to/tsinghua.edu.cn/elasticstack/5.x/yum/repodata/repomd.xml.asc {
   alias /path/to/extras/elasticstack/repomd.xml.asc;
}
```

**Comment by bigeagle** [comment]
@alick GPG checking is actually not quite needed for our grafana mirror, since the repo metadata are in-place generated by `createrepo`, not downloaded from upstream. 

@yuniers The `repomd.xml.asc` changes everytime grafana content changes.

**Comment by alick** [comment]
@bigeagle Hmm, users may still prefer to enable GPG checking to ensure no tampering of repo between tuna mirror and the end user.

What's the rationale for `createrepo` by ourselves after every sync(?)?
