### ISSUE TITLE
lineageos repo sync failed

### ISSUE THREAD

**Issue by daveyoung** [tuna/issues#1973]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

编译lineageos 使用tuna mirror 报错：
（步骤参考：https://wiki.lineageos.org/devices/enchilada/build/　　and   https://zhuanlan.zhihu.com/p/689945053）

Checking out: 98% (1224/1244) platform/prebuilts/module_sdk/OnDevicePersonaChecking out: 100% (1244/1244), done in 4m49.394s
error: Unable to fully sync the tree
error: Downloading network changes failed.
Try re-running with "-j1 --fail-fast" to exit at the first error.
================================================================================
Repo command failed due to the following `SyncError` errors:
GitCommandError: 'fetch --quiet --progress aosp --prune --recurse-submodules=no --tags tag android-13.0.0_r75 +refs/tags/android-13.0.0_r75:refs/tags/android-13.0.0_r75 +refs/tags/*:refs/tags/*' on platform/external/rust/crates/hashbrown failed
stdout: fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/external/rust/crates/hashbrown/': CONNECT tunnel failed, response 503
GitCommandError: 'fetch --quiet --progress aosp --prune --recurse-submodules=no --tags tag android-13.0.0_r75 +refs/tags/android-13.0.0_r75:refs/tags/android-13.0.0_r75 +refs/tags/*:refs/tags/*' on platform/external/rust/crates/memchr failed
stdout: fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/external/rust/crates/memchr/': CONNECT tunnel failed, response 503
GitCommandError: 'fetch --quiet --progress aosp --prune --recurse-submodules=no --tags tag android-13.0.0_r75 +refs/tags/android-13.0.0_r75:refs/tags/android-13.0.0_r75 +refs/tags/*:refs/tags/*' on platform/external/rust/crates/rand_chacha failed
stdout: fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/external/rust/crates/rand_chacha/': CONNECT tunnel failed, response 503
GitCommandError: 'fetch --quiet --progress aosp --prune --recurse-submodules=no --tags tag android-13.0.0_r75 +refs/tags/android-13.0.0_r75:refs/tags/android-13.0.0_r75 +refs/tags/*:refs/tags/*' on platform/external/rust/crates/serde_test failed
stdout: fatal: unable to access 'https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/external/rust/crates/serde_test/': CONNECT tunnel failed, response 503

### 期望的现象（What you expected to happen）

不报错　sync成功

### 如何重现此问题（How to reproduce it）

见描述

### 操作系统（OS Version）

Fedora 40

### 浏览器（如果适用）（Browser version, if applicable）

n/a

**Comment by shankerwangmiao** [comment]
您好，您给出的错误中，包含有 `CONNECT tunnel failed, response 503` 字样，是指 git 程序在向您配置的代理服务器发送 `CONNECT` 指令时，后者返回了 503 错误。建议您排查您配置的代理服务器工作是否正常。

**Comment by daveyoung** [comment]
我的gitconfig代理设置的是针对github使用代理，不过我可以下次重新试试，多谢。
[https "https://github.com"]
	proxy = ...
[http "https://github.com"]
	proxy = ...
