### ISSUE TITLE
[镜像请求] openSUSE 的 Build Service 镜像添加

### ISSUE THREAD

**Issue by dZ8Lx9OwX** [tuna/issues#1975]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

https://mirrors.opensuse.org/
查看上面的网站，你会发现TUNA没有提供 Build Service 的镜像。
国内好像只要163提供了这个镜像，但提供的是不完整的。
能否考虑添加此镜像。

### 上游地址与镜像方法 (How to mirror)

[上游地址] https://download.opensuse.org/repositories/
[镜像方法] https://en.opensuse.org/openSUSE:Mirror_howto

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
OBS 中包含了大量第三方来源的软件包，体积较大，也不是 openSUSE 发行版的组成部分，我们暂无此考虑。

**Comment by dZ8Lx9OwX** [comment]
明白了，期待添加这个镜像的原因就是因为它提供了openSUSE以外的很多扩展库，尤其是交叉编译的开发库或者其它第三方自动编译的程序。虽然没有考虑添加，但依旧很高兴能获得回复。那现阶段只能从别的途径获得相关库支持了。
