### ISSUE TITLE
Centos Vault 未完整同步 Centos Stream 8 的软件源

### ISSUE THREAD

**Issue by sandtechnology** [tuna/issues#1977]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/centos-vault/centos/8-stream/AppStream/ 下的目录没有被完整同步，尚未确认其他repo是否也有相同情况。
可打开源 https://vault.centos.org/centos/8-stream/AppStream/ 进行对照。

### 期望的现象（What you expected to happen）

https://mirrors.tuna.tsinghua.edu.cn/centos-vault/centos/8-stream/AppStream/ 下的目录被完整同步。

### 如何重现此问题（How to reproduce it）

打开 https://mirrors.tuna.tsinghua.edu.cn/centos-vault/centos/8-stream/AppStream/ ，确认目录下有没有x86_64等架构的文件夹

### 操作系统（OS Version）

Centos Stream 8

### 其他需要说明的事项（Anything else we need to know）

Centos Stream 8 自 2024/5/31 起进入了 EOL 阶段，因此软件源被官方移动到了centos-vault的/centos/下，希望镜像源使用教程（ https://mirrors.tuna.tsinghua.edu.cn/help/centos/ ）也能为此更新一下（感觉这个centos源已经可以被301重定向了？）

**Comment by Harry-Chen** [comment]
我们的上游并没有完成同步： https://linuxsoft.cern.ch/centos-vault/8-stream/AppStream/ 请耐心等待。

此外，centos 7 的支持期并没有结束，还有一个月。

**Comment by sandtechnology** [comment]
好的，感谢帮忙查看，目前看已经同步了。
