### ISSUE TITLE
ubuntu18.04在安装ros-eloquent时出现404

### ISSUE THREAD

**Issue by Gaben21** [tuna/issues#1978]
rt
设定的源为：https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/
在执行`sudo apt install ros-eloquent-desktop `时出现以下问题
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/pool/main/r/ros-eloquent-examples-rclpy-minimal-client/ros-eloquent-examples-rclpy-minimal-client_0.8.3-1bionic.20201207.163052_amd64.deb  404  Not Found [IP: 2402:f000:1:400::2 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/pool/main/r/ros-eloquent-examples-rclpy-minimal-publisher/ros-eloquent-examples-rclpy-minimal-publisher_0.8.3-1bionic.20201207.163134_amd64.deb  404  Not Found [IP: 2402:f000:1:400::2 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu/pool/main/r/ros-eloquent-examples-rclpy-minimal-service/ros-eloquent-examples-rclpy-minimal-service_0.8.3-1bionic.20201207.163111_amd64.deb  404  Not Found [IP: 2402:f000:1:400::2 443]
打开链接发现404了

**Comment by Harry-Chen** [comment]
请执行 apt update

**Comment by Gaben21** [comment]
> 请执行 apt update

执行了还是不行

我是按照镜像站使用帮助中的命令来安装的

```
sudo apt install curl gnupg2
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
```
```

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] https://mirrors6.tuna.tsinghua.edu.cn/ros2/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update
```
然后再执行`sudo apt install ros-eloquent-desktop`的时候还是出现上述的报错

错误:193 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu bionic/main amd64 ros-eloquent-rosidl-default-generators amd64 0.8.0-1bionic.20201207.151832
  404  Not Found [IP: 2402:f000:1:400::2 443]
错误:194 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu bionic/main amd64 ros-eloquent-sros2 amd64 0.8.2-1bionic.20201207.172800
  404  Not Found [IP: 2402:f000:1:400::2 443]
错误:195 https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu bionic/main amd64 ros-eloquent-sros2-cmake amd64 0.8.2-1bionic.20201207.173438

**Comment by shankerwangmiao** [comment]
您好，ubuntu 18.04 已于 23 年 4 月 EOL，我们相应停止了针对该版本的软件仓库的同步。
