### ISSUE TITLE
docker-ce 镜像 gpg 公钥地址有误

### ISSUE THREAD

**Issue by enjeei** [tuna/issues#1979]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

docker-ce 软件软镜像指南里的公钥下载连接有问题
https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/

### 期望的现象（What you expected to happen）

公钥连接应该是
https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/gpg
指南里还是 docker 官网的连接

### 如何重现此问题（How to reproduce it）

选择发行版 ubuntu
gpg 公钥下载代码里的公钥地址不对：
https://download.docker.com/linux/ubuntu/gpg

**Comment by shankerwangmiao** [comment]
关于公钥的获取，可参考 https://github.com/tuna/issues/issues/1114 https://github.com/tuna/issues/issues/1223
