### ISSUE TITLE
openSUSE 同步脚本可能已失效

### ISSUE THREAD

**Issue by sjx95** [tuna/issues#198]
同步状态上是：
opensuse  2017-02-08 09:04  rsync://rsync.opensuse.org/opensuse-full/opensuse/  success  702G
同步成功。但是，在镜像下面，没有看到新的包，比如说2017年更新的那些包都没有。
https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/oss/suse/x86_64/
参考官方镜像：
https://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64/
官方镜像已经有很多2017年的包了，所以我想是不是脚本失效了，啥的。

另外，我在tuna更新完毕后，切换到官方源，还要更新900多个包。

**Comment by shankerwangmiao** [comment]
hi, 我们注意到问题了，但是似乎是上游的问题。上游的 rsync 服务器上没有这些文件。

rsync --list-only rsync://rsync.opensuse.org/opensuse-full/opensuse/tumbleweed/repo/oss/suse/x86_64/

**Comment by sjx95** [comment]
中科大源直到1月底的rsync是可用的，不过他们用的是
rsync://stage.opensuse.org/opensuse-full-with-factory/opensuse/
好像不是一个服务器

虽然他们两天前开始同步，至今没同步完……

---
Non-authoritative answer:
Name:   stage.opensuse.org
Address: 195.135.221.130
Non-authoritative answer:
rsync.opensuse.org      canonical name = widehat.opensuse.org.
Name:   widehat.opensuse.org
Address: 62.146.92.202

**Comment by shankerwangmiao** [comment]
https://en.opensuse.org/openSUSE:Mirror_infrastructure#Rsync_servers

这个文档里已经说得很详细了，我们目前没有访问 stage 的服务器的权限。另外，按照该文档的介绍，stage 服务器上多出来的文件，属于尚未发布的文件，提前在这个服务器上公布，以便提前传播到各镜像站上；这部分多出来的文件即使是镜像好了，也不会公开给用户访问。

**Comment by shankerwangmiao** [comment]
因此，鉴于我们服务器上的文件与上游一致，因此关闭此 issue.

**Comment by bigeagle** [comment]
目前 openSUSE 官方 mirror 基本处于三不管状态，我们曾多次申请 staging 权限，openSUSE mirror 邮件列表里也经常有人反馈 bug，但没有看到官方回应过。

**Comment by sjx95** [comment]
明白了，感谢。
话说起来openSUSE官方的镜像源列表还有tuna呢，居然都不给你们权限，GG……
