### ISSUE TITLE
llvm 404

### ISSUE THREAD

**Issue by vipcxj** [tuna/issues#1983]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/llvm.sh
这个链接404
呜喵，金枪鱼被吃掉了

### 期望的现象（What you expected to happen）

不要404

### 如何重现此问题（How to reproduce it）

wget https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/llvm.sh

**Comment by shankerwangmiao** [comment]
目前已经恢复了。
