### ISSUE TITLE
repository  does not have a Release file.

### ISSUE THREAD

**Issue by Calcifer97** [tuna/issues#1984]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

root@armbian:/etc/apt/sources.list.d# apt update
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/debian bookworm InRelease
Hit:2 http://mirrors.tuna.tsinghua.edu.cn/debian bookworm-updates InRelease
Hit:3 http://mirrors.tuna.tsinghua.edu.cn/debian bookworm-backports InRelease
Hit:4 http://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security InRelease
Get:5 https://pkgs.tailscale.com/stable/debian bookworm InRelease
Ign:6 https://mirrors.tuna.tsinghua.edu.cn/armbian bookworm InRelease
Err:7 https://mirrors.tuna.tsinghua.edu.cn/armbian bookworm Release
  404  Not Found [IP: 101.6.15.130 443]
Reading package lists... Done
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/armbian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
 
![image](https://github.com/tuna/issues/assets/37408196/f20a78b9-9e1b-40eb-8b92-377d67d3bd69)

### 期望的现象（What you expected to happen）

正常更新不报错

### 如何重现此问题（How to reproduce it）

root@armbian:/etc/apt/sources.list.d# cat armbian.list
deb https://mirrors.tuna.tsinghua.edu.cn/armbian bookworm main bookworm-utils bookworm-desktop

**Comment by shankerwangmiao** [comment]
目前已经恢复。
