### ISSUE TITLE
blocked download requests

### ISSUE THREAD

**Issue by xiaoyao9184** [tuna/issues#1985]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

尊敬的访问者，

Dear visitor,

Chère cliente,

訪問者へ 、

 

您好！

Hello!

Bonjour!

こんにちは ！

 

我们检测到您所在的子网和/或所使用的客户端存在大量下载某些较大二进制文件的行为，为保证用户的正常使用，我们阻断了此类请求。

We have detected enormous traffic from your network or client and have blocked your requests to ensure the quality of service for normal users.

Nous avons détecté un grand nombre de téléchargements de certains fichiers binaires volumineux à partir de votre sous-réseau et/ou du client que vous utilisez et avons bloqué ces requêtes pour garantir un accès normal aux utilisateurs.

お客様のサブネットおよび/またはクライアントで、特定の大きなバイナリのダウンロードを多数検出しました。お客様の通常の使用のためこれらのリクエストをブロックさせていただきます。

 

您可以尝试更改网络环境或更换客户端；您也可以联系 [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) 并附上下方的标识符。

You could try another network or client, or have your network administrator contact [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) with the identifier below.

Vous pouvez essayer de modifier votre environnement réseau ou de changer de client ; vous pouvez également contacter [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) avec l'identifiant ci-dessous.

ネットワーク環境の変更、クライアントの変更などをお試しください。また、下記の識別子を用いて [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn) までご連絡ください。

 

00000069 21ac026ccb18efa75d2b2c3d8168bbcc

### 期望的现象（What you expected to happen）

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package

### 如何重现此问题（How to reproduce it）

与 https://www.v2ex.com/t/1011185 类型同理 https://mirrors.aliyun.com/ ，请帮忙查询block原因，顺便咨询大量下载block的阈值是多少？

这几天有通过 https://downloads.raspberrypi.com/ 下载过几个版本镜像，种子直连总量不到50G，一是raspberrypi应该与tuna aliyun无关，二是应该不至于流量超过

**Comment by shankerwangmiao** [comment]
您所在的 106.114.160.0/19 地址段，因存在大量持续反复下载镜像站上 CentOS 安装镜像的行为，而被列入关注列表。

**Comment by xiaoyao9184** [comment]
我去找ISP排查下

**Comment by xiaoyao9184** [comment]
当前问题未解决，请求移除封锁，并删除回复中设计隐私的的IP地址段
