### ISSUE TITLE
lineageos同步失败

### ISSUE THREAD

**Issue by admin9527cg** [tuna/issues#1986]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

按步骤repo sync lineageos17.1 的时候失败
![{8CECDC75-2470-4f51-B6D9-C840CBE78D09}](https://github.com/tuna/issues/assets/38268573/92b83d4a-8837-460d-8479-3272a34d2f56)
![{BDB3C640-8FD0-45b0-8834-0EAC9ECE3D69}](https://github.com/tuna/issues/assets/38268573/87075dde-0ed5-48ec-9dff-17d2f1efd177)

### 期望的现象（What you expected to happen）

能够同步成功

### 如何重现此问题（How to reproduce it）

按照镜像使用帮助页面步骤

### 操作系统（OS Version）

Ubuntu20.04.6

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by shankerwangmiao** [comment]
您好，请您再试一次。目前我这边是无法复现该问题的。暂未发现您日志中提及的仓库存在问题。

**Comment by admin9527cg** [comment]
> 您好，请您再试一次。目前我这边是无法复现该问题的。暂未发现您日志中提及的仓库存在问题。

![{5F2A44C5-7F2C-4f1e-85EA-62D75314EE23}](https://github.com/tuna/issues/assets/38268573/39377c5f-38e2-4465-a352-be69bc9e2576)
sh
试了好多次了

**Comment by shankerwangmiao** [comment]
经查，在您给出的日志截图中涉及的两个 sha1 散列值对应的文件均在我们的服务器上存在，目前暂时无法确定是服务器的问题。您截图的配置是正确的。

如果您是已经建立了仓库并进行更新，建议您尝试将 `.repo/project-objects/platform/external/deqp.git` 目录删除（或移动到工作目录之外的其它位置作为备份），然后再尝试同步，看是否能正常结束。

**Comment by admin9527cg** [comment]
repo forall -c git checkout -f
repo sync -f
以上命令将问题解决
