### ISSUE TITLE
Miniforge-pypy3-Windows-x86_64.exe文件下载后360扫描报存在病毒

### ISSUE THREAD

**Issue by robinsds** [tuna/issues#1987]
Miniforge-pypy3-Windows-x86_64.exe文件名：
MD5：8dee47242868b65fdc96da90a7dcc205
URL：https://mirrors.tuna.tsinghua.edu.cn/github-release/conda-forge/miniforge/Release%2024.3.0-0/Miniforge-pypy3-Windows-x86_64.exe
病毒名：Win32/Heur.Generic.HxQBVyoA

**Comment by shankerwangmiao** [comment]
您好，

经查，您下载到的文件的 MD5 散列值与镜像站服务器上存储的和在 Github 官方提供的均一致。对于涉及第三方软件的问题，建议您向其提供者反馈咨询。
