### ISSUE TITLE
BFSU镜像站KDE Neon更新失败

### ISSUE THREAD

**Issue by SnDream** [tuna/issues#1989]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

apt更新时打印如下提示，已经持续多天：
```
获取:6 http://mirrors.bfsu.edu.cn/kde-neon/user jammy/main amd64 Packages [3,984 kB]
错误:6 http://mirrors.bfsu.edu.cn/kde-neon/user jammy/main amd64 Packages
  文件尺寸不符(4018404 != 3984327)。您使用的镜像正在同步中？ [IP: 39.155.141.16 80]
  Hashes of expected file:
   - Filesize:3984327 [weak]
   - SHA512:a9954b0d2eec3830996729e2a3032a0007cca5b16dfe066bffca5946f2f06ae2f830b0bdd0514e9b2e7649db12692758bc47627323d8c9acfdad4dee62568469
   - SHA256:cc0c3774b5267f6395b7728337ff3ec4f0ae5ec62abcbe73fce05193829aa564
   - SHA1:1a76cfe0d48752d5c0938c54ab82dae6ff8cd399 [weak]
   - MD5Sum:e0d0989b53344790b2f65c20b7b8edf2 [weak]
```

### 期望的现象（What you expected to happen）

apt能正常更新

### 如何重现此问题（How to reproduce it）

使用BFSU源更新kde neon镜像

### 操作系统（OS Version）

KDE Neon

### 浏览器（如果适用）（Browser version, if applicable）

N/A

### 其他环境（Other environments）

N/A

### 其他需要说明的事项（Anything else we need to know）

检查[镜像站](https://mirrors.bfsu.edu.cn/kde-neon/user/dists/jammy/main/binary-amd64/)上的文件，提供如下信息：
```
Packages	20.3 MiB	2024-06-25 01:03
Packages.bz2	3.8 MiB	2024-06-18 22:43
Packages.gz	4.4 MiB	2024-06-25 01:03
Release	130 B	2024-06-18 22:43
```
检查[上游](https://archive.neon.kde.org/user/dists/jammy/main/binary-amd64/)上的文件，提供如下信息
```
[   ]	Packages	2024-06-26 12:53	21M	 
[   ]	Packages.bz2	2024-06-26 12:53	3.9M	 
[   ]	Packages.gz	2024-06-26 12:53	4.5M	 
[   ]	Release	2024-06-26 12:53	130	 
```

看起来有一些文件不能正常同步了。

**Comment by shankerwangmiao** [comment]
已经恢复。
