### ISSUE TITLE
Debian 10 buster 更新系统源报错

### ISSUE THREAD

**Issue by obladlee** [tuna/issues#1991]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

对Debian10 buster 
执行sudo apt update
命中:1 https://mirrors.tuna.tsinghua.edu.cn/debian buster InRelease
命中:2 https://mirrors.tuna.tsinghua.edu.cn/debian buster-updates InRelease
忽略:3 https://mirrors.tuna.tsinghua.edu.cn/debian buster-backports InRelease
错误:4 https://mirrors.tuna.tsinghua.edu.cn/debian buster-backports Release 
  404  Not Found [IP: 101.6.15.130 443]
命中:5 https://security.debian.org/debian-security buster/updates InRelease 
正在读取软件包列表... 完成                             
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/debian buster-backports Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。

### 期望的现象（What you expected to happen）

正常更新系统源

### 如何重现此问题（How to reproduce it）

更换debian10 buster系统源，执行sudo apt update

### 操作系统（OS Version）

uos 20

### 其他需要说明的事项（Anything else we need to know）

Debian buster 镜像文件做了更新，没有buster-backports文件。
但是在https://mirrors.tuna.tsinghua.edu.cn/help/debian/
debian的帮助文档中，更换系统源文档没有更新。

**Comment by taoky** [comment]
Debian 10 还有两天就结束 LTS 支持了：https://endoflife.date/debian

或许帮助可以直接去掉 buster。

**Comment by Harry-Chen** [comment]
Debian 10 的发行代号是 Buster，发布于 2019 年，距今已有 5 年，即将接近其官方支持期限的终点。backports 源不支持 LTS，因此其支持期限在三年。buster-backports 已于 2022 年 8 月从仓库中移除，详见 https://backports.debian.org/news/Removal_of_buster-backports_from_the_debian_archive/ 。

您遇到的错误信息是由于 buster-backports 已不再提供所致。您可以从 sources.list 中去掉相关语句。即使不去掉，也不影响您正常获取其主软件仓库中的软件包。

鉴于 Debian Buster 已接近其官方支持期限的终点，对于新部署的系统，我们强烈建议您安装 Debian 的最新版本，即 Debian Bookworm。
