### ISSUE TITLE
[镜像请求] Chromium

### ISSUE THREAD

**Issue by LiarOnce** [tuna/issues#1992]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

Chromium 是一个开源浏览器项目

### 上游地址与镜像方法 (How to mirror)

上游地址：https://chromium.googlesource.com/chromium
上游地址（位于GitHub的镜像）：https://github.com/chromium/chromium
Tarball：https://gsdview.appspot.com/chromium-browser-official/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
Duplicated with #836, #365, #138.

根据 [行为准则](https://github.com/tuna/issues/blob/master/CODE_OF_CONDUCT.md)，提出正式警告并关闭 issue。
