### ISSUE TITLE
Proxmox镜像文件尺寸不一致

### ISSUE THREAD

**Issue by x-Felix** [tuna/issues#1995]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

`Err:6 https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian bookworm/pve-no-subscription amd64 Packages
  File has unexpected size (321024 != 325472). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - Filesize:325472 [weak]
   - SHA512:11dc9794365649ea502fe5e4447ce39f286e52b32f285b4b38cfde83ddae33653e9ddece2aaf8416349d73f5d1029017a5414e5791f46817fc4cc908ae3ff142
   - SHA256:860978e4ff6bfc40134fb5156181e081afacc3718cea8965d5e4bf49f0b46572
   - MD5Sum:43160e467c0797bac87c524dd2884fbc [weak]
  Release file created at: Fri, 05 Jul 2024 07:52:35 +0000
Reading package lists... Done 
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/dists/bookworm/pve-no-subscription/binary-amd64/Packages.gz  File has unexpected size (321024 != 325472). Mirror sync in progress? [IP: 101.6.15.130 443]
   Hashes of expected file:
    - Filesize:325472 [weak]
    - SHA512:11dc9794365649ea502fe5e4447ce39f286e52b32f285b4b38cfde83ddae33653e9ddece2aaf8416349d73f5d1029017a5414e5791f46817fc4cc908ae3ff142
    - SHA256:860978e4ff6bfc40134fb5156181e081afacc3718cea8965d5e4bf49f0b46572
    - MD5Sum:43160e467c0797bac87c524dd2884fbc [weak]
   Release file created at: Fri, 05 Jul 2024 07:52:35 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

### 期望的现象（What you expected to happen）

Apt update successful

### 如何重现此问题（How to reproduce it）

Apt update

### 操作系统（OS Version）

Debian

**Comment by shankerwangmiao** [comment]
已经恢复了，请再试一次。
