### ISSUE TITLE
http://mirrors.tuna.tsinghua.edu.cn/centos/7/os/x86_64/repodata/repomd.xml

### ISSUE THREAD

**Issue by likunpeng06** [tuna/issues#1997]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

此连接的镜像访问不到

### 期望的现象（What you expected to happen）

尽快修复

### 如何重现此问题（How to reproduce it）

浏览器访问此连接，返回404页面

**Comment by shankerwangmiao** [comment]
dup with #1993
