### ISSUE TITLE
[UBUNTU] ubuntu 18.04的source有问题 

### ISSUE THREAD

**Issue by carloscn** [tuna/issues#1998]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

选择ubuntu 18.04

apt update && apt upgrade 之后 库的版本估计有问题，sudo都不可以用了直接报非法elf。其他命令比如ls cat等运行后coredump

新装的ubuntu18.04 虚拟机没有任何其他操作，一上来直接换的清华的源。重新装了两次虚拟机，第一次还以为是贴错了发行版，后来确认没有弄错发行版。

测试中科大的源没问题

### 期望的现象（What you expected to happen）

正常apt update && apt upgrade 

### 如何重现此问题（How to reproduce it）

1. 新装一个ubuntu 18.04的虚拟机；
2. 什么也不操作，直接换18.04的源
3. sudo apt update && sudo apt upgrade -y

### 操作系统（OS Version）

ubuntu 18.04.4

**Comment by Harry-Chen** [comment]
关于您所述的 ubuntu 镜像，我们与 USTC 使用相同的上游，提供相同的文件

请您提供详细的复现步骤（使用命令、修改的文件、获得的报错）。

**Comment by Harry-Chen** [comment]
如果不提供复现，我们无法处理问题。

**Comment by carloscn** [comment]
> 如果不提供复现，我们无法处理问题。

今天在docker环境测试了一下没有问题了。我close这个问题，非常感谢回复！

![image](https://github.com/user-attachments/assets/baff5e3b-d8ea-4903-b702-3b2519406a0d)
