### ISSUE TITLE
debian-elts 文件内容和上游不一致

### ISSUE THREAD

**Issue by bin456789** [tuna/issues#1999]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

文件内容和上游不一致
https://deb.freexian.com/extended-lts/dists/stretch/main/debian-installer/binary-amd64/Packages.gz
https://mirrors.tuna.tsinghua.edu.cn/debian-elts/dists/stretch/main/debian-installer/binary-amd64/Packages.gz

### 期望的现象（What you expected to happen）

。

### 如何重现此问题（How to reproduce it）

```
curl -s https://deb.freexian.com/extended-lts/dists/stretch/main/debian-installer/binary-amd64/Packages.gz | md5sum
1454d1a18eac5bc86062ea860108d844  -
curl -s https://mirrors.tuna.tsinghua.edu.cn/debian-elts/dists/stretch/main/debian-installer/binary-amd64/Packages.gz | md5sum
74aa5cce2ba59bb82839420cb20dfc8e  -
```

**Comment by Harry-Chen** [comment]
我们并未同步 debian-installer 相关组件，这些文件是曾经的遗留
