### ISSUE TITLE
把TUNA的wiki迁移到github wiki上 

### ISSUE THREAD

**Issue by scateu** [tuna/issues#200]
以前的MoinMoin Wiki是xiaq老师建的
MoinMoin Wiki的数据貌似是以纯文本方式存的.

 - [ ] 尽量保持原有URL不变
 - [ ] 尽量保持原有的内部互联链接继续可用
 - [ ] 私有敏感数据的脱敏归档

**Comment by heroxbd** [comment]
MoinMoin Wiki 留着不好吗？

**Comment by Harry-Chen** [comment]
MoinMoin 的问题在于校外无法访问

**Comment by huiyiqun** [comment]
其实…可以高端口…

Harry Chen <notifications@github.com> 于 2019年2月28日周四 上午10:47写道：

**Comment by z4yx** [comment]
已经可以用 https://tuna.wiki 访问 wiki.ts... 。暂时不迁了。
