### ISSUE TITLE
kubernetes 镜像同步错误

### ISSUE THREAD

**Issue by YadominJinta** [tuna/issues#2002]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

kubernetes 镜像似乎存在同步错误, apt update 时报错，但是网站页面上没有显示 syning 或者 failed
```
Err:25 https://mirrors.tuna.tsinghua.edu.cn/kubernetes/core:/stable:/v1.28/deb  Packages
  File has unexpected size (16328 != 17601). Mirror sync in progress? [IP: 101.6.15.130 443]
  Hashes of expected file:
   - Filesize:17601 [weak]
   - SHA256:96e3ed804e58f69bd432757b70a62f4ab3af71584545f41b81fd33bd302fa401
   - SHA1:20ed3c7be2a37771ba0650539d3fafddce0f6e54 [weak]
   - MD5Sum:6f510bf38f812f269392b5e4b5ddfe12 [weak]
  Release file created at: Wed, 17 Jul 2024 10:57:18 +0000
```

### 期望的现象（What you expected to happen）

apt update 无报错

### 如何重现此问题（How to reproduce it）

添加 kubernetes 源，执行 apt update
```
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/kubernetes/core:/stable:/v1.28/deb/ /
```

### 操作系统（OS Version）

Debian 12 Bookworm

**Comment by shankerwangmiao** [comment]
您好，目前确实存在 Packages 文件的 hash 与 Release 不一致的情况。但是我们的同步上游也存在同样问题。我们需要等待上游修复该问题后自然恢复。

**Comment by YadominJinta** [comment]
> 您好，目前确实存在 Packages 文件的 hash 与 Release 不一致的情况。但是我们的同步上游也存在同样问题。我们需要等待上游修复该问题后自然恢复。

请问你们的上游是？我看 `https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb` 这个仓库是好的

**Comment by Harry-Chen** [comment]
> > 您好，目前确实存在 Packages 文件的 hash 与 Release 不一致的情况。但是我们的同步上游也存在同样问题。我们需要等待上游修复该问题后自然恢复。
> 
> 请问你们的上游是？我看 `https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb` 这个仓库是好的

rsync://rsync.opensuse.org/buildservice-repos-main/isv:/kubernetes:/

**Comment by YadominJinta** [comment]
上游应该修好了
