### ISSUE TITLE
brew update 出错

### ISSUE THREAD

**Issue by kwlreal** [tuna/issues#2003]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

==> Updating Homebrew...
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles-portable-ruby/portable-ruby-3.3.3.el_capitan.bottle.tar.gz
curl: (22) The requested URL returned error: 404
Error: Checksum mismatch.
Expected: a5ef040e054444a0eb2cbcc1032fed14702dfbe2e55b25e609f3ce643f23c4ee
  Actual: 246ba784b5639687fa611a6623d51a69dde13fdbbd47969d0667f85c7087abda
 Archive: /Users/kevin/Library/Caches/Homebrew/portable-ruby-3.3.3.el_capitan.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade Homebrew Portable Ruby!

### 期望的现象（What you expected to happen）

brew success

### 如何重现此问题（How to reproduce it）

brew update

### 操作系统（OS Version）

mac os 12.7.5

### 其他需要说明的事项（Anything else we need to know）

我在官网找到了 https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/bottles/bottles-portable-ruby/portable-ruby-3.3.4.el_capitan.bottle.tar.gz，无论是版本还是地址都与终端报错信息中的文件不一致

**Comment by Harry-Chen** [comment]
此文件应该在重新同步之后恢复正常了

**Comment by liusy58** [comment]
+1 还是报错
