### ISSUE TITLE
LXC images mirror doesn't work with LXC/LXD anymore

### ISSUE THREAD

**Issue by wxiaoguang** [tuna/issues#2004]
Background: https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479

The linuxcontainers project has its own "incus" daemon/client now, their images doesn't work with Canonical LXD's images anymore.

If an user installed incus:

* They could only use linuxcontainers images (https://mirrors.tuna.tsinghua.edu.cn/help/lxc-images/)
* They do not have `lxc` command anymore

If an user installed lxd/lxc:

* They could only use Canonical LXD images (https://images.lxd.canonical.com/)
* The command is still `lxc`, but they can't use this lxc-images mirror.
----

What if the Incus/LXD and images mismatch? the `lxc/incus exec vm ....` command doesn't work because the agents are different. And there could be more and more bugs in the future.

----

What to do? I guess the helps on https://mirrors.tuna.tsinghua.edu.cn/help/lxc-images/ could be improved:

* Tell users that this mirror is for Incus/linuxcontainers.org only, do not misuse it
* Change the commands from `lxc ...` to `incus ...` because end users do not have `lxc` command anymore.

**Comment by wxiaoguang** [comment]
Anything need to be clarified more?

@Harry-Chen @shankerwangmiao

**Comment by shankerwangmiao** [comment]
Hi, thanks for the explanation. 

If you have any suggestions to our docs, PRs are welcomed directly to https://github.com/mirrorz-org/mirrorz-docs/. The corresponding file containing the help you mentioned is located at https://github.com/mirrorz-org/mirrorz-docs/blob/main/lxc-images/lxc-images.zh.md?plain=1 .

**Comment by wxiaoguang** [comment]
Thank you for pointing out the repo (I didn't find it 🤣 )

* https://github.com/mirrorz-org/mirrorz-docs/pull/18
