### ISSUE TITLE
清华镜像站点访问提示拒绝

### ISSUE THREAD

**Issue by lianggegithub** [tuna/issues#2008]
我是中泰证券股份有限公司IT人员，今天我从机房下载https://mirrors.tuna.tsinghua.edu.cn/​站点的镜像，发现提示如下：
我们检测到您所在的子网和/或所使用的客户端存在大量下载某些较大二进制文件的行为，为保证用户的正常使用，我们阻断了此类请求。

您可以尝试更改网络环境或更换客户端；您也可以联系 [support@tuna.tsinghua.edu.cn](mailto:support@tuna.tsinghua.edu.cn)。

​我们机房申请了新的互联网线路，300M专线带宽，目前机房机器切到该线路运行，公网地址3个：123.88.23.74-76，属于东莞市。
我们机器需每周（一般是周末）从[https://mirrors.tuna.tsinghua.edu.cn/站点同步镜像到内部](https://mirrors.tuna.tsinghua.edu.cn/%E7%AB%99%E7%82%B9%E5%90%8C%E6%AD%A5%E9%95%9C%E5%83%8F%E5%88%B0%E5%86%85%E9%83%A8)，供内部机器使用，包含：Ubuntu，centos，
Ubuntu，OpenEuler,almalinux，rockLinux，k8s，epel源等，机房同步带宽较大目的是为了同步快，频率每周末同步，正规用途，烦请帮开通下白名单，谢谢！
另之前的旧公网ip也请保留​​，主备线路同时在用，非常感谢！。

![qinghua](https://github.com/user-attachments/assets/2e36731d-02d8-43a5-a940-6e5d85fc62d2)

**Comment by shankerwangmiao** [comment]
您好，此前您的来信已经收到，并已经作了回复。请按照回复信息提供识别代码，以便我们进一步查证。

**Comment by lianggegithub** [comment]
你好，没有收到提供识别码回复信息。

**Comment by shankerwangmiao** [comment]
请复制页面下方的识别代码，并以文字形式粘贴在邮件内，以便我们进一步诊断。

**Comment by lianggegithub** [comment]
ok，识别代码：00000070 7b194bb00b65bf7d64ab2446fa69b2b4

**Comment by shankerwangmiao** [comment]
您好，

感谢您致信 TUNA。受限于服务能力，我们拒绝了使用 curl 下载 CentOS 安装程序的请求，请使用浏览器下载。

如果您确需使用 curl 工具下载，可以为 curl 命令增加 -H "User-Agent: xxxxx" 参数，人工指定一个 User-Agent。其中请将 xxxxx 替换为能反映您下载意图或所在组织机构的字符串，以便识别。

祝好，

Miao Wang

**Comment by lianggegithub** [comment]
好的，谢谢！
