### ISSUE TITLE
请帮忙删除 tbsdk 这个 pip 包

### ISSUE THREAD

**Issue by zhangcj1** [tuna/issues#2009]
在 pypi.org 已经删除了这个项目，但是tuna还有，使用pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tbsdk 的时能够正常安装。请帮忙删除 tbsdk 这个包。谢谢🙏

**Comment by zhangcj1** [comment]
@shankerwangmiao  您好，看见您之前帮其它人处理的帖子。所以可以麻烦您帮忙处理一下吗？

**Comment by Harry-Chen** [comment]
@zhangcj1 维护者有自己的工作和时间安排，这样并不礼貌。

**Comment by zhangcj1** [comment]
> @zhangcj1 维护者有自己的工作和时间安排，这样并不礼貌。

抱歉，头一回玩这个issues和使用清华的镜像，我为我的行为感到抱歉。因为这个项目中包含了一些隐私，所以迫切的想尽快得到解决，为此带来的冒昧我很抱歉

**Comment by shankerwangmiao** [comment]
您好，已经移除了您提及的软件包。

**Comment by zhangcj1** [comment]
> 您好，已经移除了您提及的软件包。

谢谢大佬。所以大佬，如果pypi中的项目删除掉了，tuna是不会自动更新的对吗？

**Comment by shankerwangmiao** [comment]
是的，受限于同步原理，上游没有提供包删除的信息，因此我们这边无法自动删除。需要不定期与上游全量对照。
