### ISSUE TITLE
希望添加 GitHub Git-lfs / GitHub orchestrator 的镜像

### ISSUE THREAD

**Issue by yuniers** [tuna/issues#201]
#### 项目名称与简介(Project Intro.)

github / git-lfs 
Git LFS is a command line extension and specification for managing large files with Git. The client is written in Go, with pre-compiled binaries available for Mac, Windows, Linux, and FreeBSD.

github / orchestrator
orchestrator is a MySQL replication topology management and visualization tool, allowing for discovery, refactoring, recovery, auditing and more features.

#### 上游地址与镜像方法(How to Mirror)

Git-lfs: https://packagecloud.io/github/git-lfs/mirror
orchestrator: https://packagecloud.io/github/orchestrator/mirror

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

Git-lfs: DEB and RPM, each package is around 2~3 MB. Actually this repo contains 641 packages

orchestrator: DEB and RPM, each package is around 4~5 MB.  Actually this repo contains 38 packages

**Comment by z4yx** [comment]
With the new synchronizing tool, the latest releases are downloaded from Github.

- https://mirrors.tuna.tsinghua.edu.cn/github-release/openark/orchestrator/
- https://mirrors.tuna.tsinghua.edu.cn/github-release/git-lfs/git-lfs/
