### ISSUE TITLE
PC无法访问清华源

### ISSUE THREAD

**Issue by TrueAbc** [tuna/issues#2014]
- 问题
- 本人的PC无法访问清华源官网，也无法下载软件，可以正常ping到网址，但是telnet无法连接；手机可以正常访问官网

---
- 期望
- PC可以正常访问官网下载软件

**Comment by phy25** [comment]
请问您的 PC 和手机是同样的网络环境吗？是什么网络环境呢？

**Comment by TrueAbc** [comment]
是在同一个wifi下面，手机没有挂vpn，PC（mac和win）挂VPN和取消都无法访问。

**Comment by shankerwangmiao** [comment]
请提供您的 IP 地址

**Comment by TrueAbc** [comment]
> 请提供您的 IP 地址


- 两张图分别是PC和手机的IP地址，均为局域网地址
<img width="561" alt="image" src="https://github.com/user-attachments/assets/635eaeb9-645b-4c4e-bdde-3c49be530abc">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/6e7f4542-1921-4987-8285-62e9eeced6d7">

- 网址登录状态
![image](https://github.com/user-attachments/assets/480811c0-a851-4681-a576-a5afc4e32483)
![image](https://github.com/user-attachments/assets/dc2f088c-988c-485f-ad43-ee72e94e0d01)

- PC 的域名解析状态
![image](https://github.com/user-attachments/assets/b01e54a5-59d7-49bd-8c64-74c5dc146017)

**Comment by taoky** [comment]
IP 地址需要是公网地址，内网地址（RFC1918，比如这里的 192.168.0.0/16）对于诊断问题没有意义。

**Comment by TrueAbc** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/5c70e298-e139-4bcb-9306-a385c32fbb14">

**Comment by shankerwangmiao** [comment]
您好，您所在的 111.18.128.0/20 地址段因为向镜像站发送攻击流量而被屏蔽。

**Comment by TrueAbc** [comment]
🙏十分感谢
