### ISSUE TITLE
Mozilla deb 仓库

### ISSUE THREAD

**Issue by goddaneel** [tuna/issues#2016]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

由 Mozilla 提供的 Firefox deb 包。

https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

### 上游地址与镜像方法 (How to mirror)

https://packages.mozilla.org/apt/

aptsync

### 备注 (Note)

参考 issue：
https://github.com/ustclug/mirrorrequest/issues/387

> Ubuntu 在 22.04 后不再提供 deb 格式的 Firefox，转而使用 snap。但从实际体验上 snap 仍然存在问题：
  无法在 chroot 中配置，导致 labstrap 和 101strap 均无法提供 snap 版本 Firefox（前者目前共享一份解包后的 Firefox，后者目前使用 GNOME Web）。
  访问速度缓慢。今日 LIP 出现了安装 Ubuntu GNOME desktop 包时在 Firefox snap 安装上卡住，之后只能跳过的情况。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
可以测试 https://mirrors.tuna.tsinghua.edu.cn/mozilla/apt/

**Comment by Harry-Chen** [comment]
TUNA 已经上线。BFSU 目前暂不上线。
