### ISSUE TITLE
关于Anaconda镜像无法获取m2w64-toolchain的Issue

### ISSUE THREAD

**Issue by TsingJyujing** [tuna/issues#202]
我在安装Theano的过程中（该死的重装系统嘤嘤嘤），遇到了无法从清华镜像获取包括m2w64-binutils等包（合计为m2w64-toolchain），以及例如mpmath等包的问题，只能从默认源获取，但是速度又十分的不堪（准确的说是直接掉线了），请问能否增加这些包的同步？
感谢~

**Comment by huiyiqun** [comment]
统一汇总到 #112 讨论
