### ISSUE TITLE
请求获取CrystalDiskInfo和CrystalDiskMark这两个软件的一个主题安装包镜像 

### ISSUE THREAD

**Issue by ljlofficial** [tuna/issues#2020]
目前，CrystalDiskMark和CrystalDiskInfo有普通版、shizuku和kureikei(只在CrystalDiskInfo镜像)，Aoi主题的版本和kureikei版本的CrystalDiskMark没镜像，能不能把这两个版本补完？谢谢！

**Comment by Harry-Chen** [comment]
由于主题并非必要部分，我们不予接受。
