### ISSUE TITLE
brew设置下载源时出错homebrew/cask-fonts was deprecated

### ISSUE THREAD

**Issue by yunbokai** [tuna/issues#2021]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在执行brew tap --custom-remote --force-auto-update homebrew/cask-fonts https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-fonts.git时报错Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.

### 期望的现象（What you expected to happen）

实际上后几条设置如brew tap --custom-remote --force-auto-update homebrew/cask-versions https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-versions.git
都出现了错误；希望您帮我指出这是我的系统设置问题还是源本身出现了问题

### 如何重现此问题（How to reproduce it）

brew tap --custom-remote --force-auto-update homebrew/cask-fonts https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-fonts.git

### 操作系统（OS Version）

Apple M3 14.6.1 (23G93)

### 浏览器（如果适用）（Browser version, if applicable）

无

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

 Updating Homebrew功能正常
cd "$(brew --repo)" && git remote -v
origin	https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git (fetch)
origin	https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git (push)

cd "$(brew --repo homebrew/core)" && git remote -v
cd: no such file or directory: /opt/homebrew/Library/Taps/homebrew/homebrew-core

**Comment by taoky** [comment]
https://github.com/Homebrew/homebrew-cask-fonts

> Formerly contained font Casks.
>
> These have mostly been migrated to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)

可以直接把这个 fonts cask 删了。

**Comment by yunbokai** [comment]
> https://github.com/Homebrew/homebrew-cask-fonts
> 
> > Formerly contained font Casks.
> > These have mostly been migrated to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask)
> 
> 可以直接把这个 fonts cask 删了。
您好，修改为
 brew tap --custom-remote --force-auto-update homebrew/cask https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git并不能解决问题，麻烦给我一条正确的代码或者修改一下原页面信息吧谢谢

**Comment by Harry-Chen** [comment]
@yunbokai 请见文档：

> 注：自 brew 4.0 起，大部分 Homebrew 用户无需设置 homebrew/core 和 homebrew/cask 镜像，只需设置 HOMEBREW_API_DOMAIN 即可。

因此您无需进行任何操作，即可使用。我们稍后会移除相关信息。

**Comment by Harry-Chen** [comment]
Fixed by https://github.com/mirrorz-org/mirrorz-docs/commit/7734dc783e16fd36675ab94d76d865d57d3f26c8

TUNA 的帮助会在后续同步。
