### ISSUE TITLE
brew update failed

### ISSUE THREAD

**Issue by liusy58** [tuna/issues#2024]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

```
brew update
HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/homebrew/brew.git as the Homebrew/brew Git remote.
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/homebrew/brew.git/' not found
```

### 期望的现象（What you expected to happen）

成功更新brew

### 如何重现此问题（How to reproduce it）

```
brew update
```

### 操作系统（OS Version）

macos

### 浏览器（如果适用）（Browser version, if applicable）

no

### 其他环境（Other environments）

no

### 其他需要说明的事项（Anything else we need to know）

no

**Comment by Harry-Chen** [comment]
如帮助文档中描述的，路径为 `https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git`

**Comment by Harry-Chen** [comment]
我们在帮助文档中发现了部分问题，稍后将修复

**Comment by Harry-Chen** [comment]
Fixed by https://github.com/tuna/mirror-web/commit/8b143c090b467acb8f4d0683a70a0d523e494dbd
