### ISSUE TITLE
pypi源同步

### ISSUE THREAD

**Issue by chenkuiace** [tuna/issues#2025]
希望能放开pypi源的rsync同步

**Comment by shankerwangmiao** [comment]
您好，由于 pypi 文件数目过多，提供 rsync 服务会消耗过多的资源，因此我们不提供 pypi 的 rsync 服务。

如果您想在本地制作 pypi 镜像，您可以使用 bandersnatch 工具。该工具依赖于 pypi 官方提供的 rpc 接口工作，该接口可以提供需要同步的软件包清单。默认情况下，软件包数据是从 pypi 官方下载；也可以通过配置，使其从其它镜像站下载软件包数据。
