### ISSUE TITLE
Add version 19 branch in llvm-apt mirror

### ISSUE THREAD

**Issue by ImpleLee** [tuna/issues#2026]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

Official LLVM APT Snapshot has been changed to version 20 and branch 19 was created.

### 期望的现象（What you expected to happen）

Version 19 branches are available in TUNA llvm-apt mirror, e.g. https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-jammy-19/.

### 如何重现此问题（How to reproduce it）

Currently no version 19 branches are available, and https://mirrors.tuna.tsinghua.edu.cn/llvm-apt/jammy/dists/llvm-toolchain-jammy/ provides a mostly trunk (actually version 20) packages.

### 其他需要说明的事项（Anything else we need to know）

FYI: Former relevant issue #1894

**Comment by ImpleLee** [comment]
*这个issue是直接抄前一个issue的，label是使用模板时自带的。

有可能直接同步整个llvm-apt里的内容吗，这样就不用每次发布新版本时开新issue了。

**Comment by Harry-Chen** [comment]
> *这个issue是直接抄前一个issue的，label是使用模板时自带的。
> 
> 有可能直接同步整个llvm-apt里的内容吗，这样就不用每次发布新版本时开新issue了。

受限于同步脚本的能力，无法探测 dists/ 中目前具有的版本，和需要哪部分。如果您有兴趣，或许可以修改同步脚本来达成这一点。

https://github.com/tuna/tunasync-scripts/blob/master/llvm-apt.sh

**Comment by Harry-Chen** [comment]
您所述的 llvm-19 已经开始同步，但我们仍需相关帮助，否则无法使流程自动化。

**Comment by ImpleLee** [comment]
好像可以解析`conf/distributions`文件来得到有哪些版本的信息，例如 https://apt.llvm.org/noble/conf/distributions .
