### ISSUE TITLE
rubygems rsync失败？ -->  Unknown module 'rubygems'

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#2027]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

# /usr/bin/rsync -rtlzv  --delete rsync://mirrors.tuna.tsinghua.edu.cn/rubygems/ ./aa/
+==================================================+
|               Tsinghua University                |
|          -= Open Source Mirror Site =-           |
+--------------------------------------------------+
|   Welcome to Tsinghua Open Source Mirror Site.   |
|                                                  |
|   This mirror is also available on HTTP.         |
|   HTTP  [https://mirrors.tuna.tsinghua.edu.cn]   |
|   RSYNC [rsync://mirrors.tuna.tsinghua.edu.cn]   |
|                                                  |
|   If you have any issues, please contact us      |
|   via GitHub @ https://github.com/tuna/issues    |
|   or IRC at #tuna on Libera.Chat                 |
|   or Fishroom at https://fishroom.tuna.moe/      |
|                                                  |
|   Supported by                                   |
|      Tsinghua Information Technology Center      |
|   Maintained by                                  |
|      Tsinghua University TUNA Association        |
|   Service Provided by                            |
|      nanomirrors                                 |
|   This storage server is sponsored by            |
|      Megvii Technology Ltd.                      |
|                                                  |
|   TUNA acknowledges the contribution from        |
|   Megvii and Huawei to open source software and  |
|   communities                                    |
|                                                  |
+==================================================+

@ERROR: Unknown module 'rubygems'

### 期望的现象（What you expected to happen）

rubygems rsync 正常同步。

### 如何重现此问题（How to reproduce it）

/usr/bin/rsync -rtlzv  --delete rsync://mirrors.tuna.tsinghua.edu.cn/rubygems/ ./aa/

### 操作系统（OS Version）

any

**Comment by shankerwangmiao** [comment]
您好，受限于服务器服务能力，我们暂时不提供 rubygems 的 rsync 服务。
