### ISSUE TITLE
[镜像请求] docker-compose

### ISSUE THREAD

**Issue by willzhang** [tuna/issues#2029]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

docker-compose项目：Define and run multi-container applications with Docker。

想要独立安装最新版docker-compose二进制文件
```
mkdir -p /usr/local/lib/docker/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
```

### 上游地址与镜像方法 (How to mirror)

项目地址：[https://github.com/docker/compose](https://github.com/docker/compose)
需同步release页面发布的二进制文件：[docker-compose-linux-x86_64](https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64)。

### 镜像大小 (Mirror size)

60.2MB

### 备注 (Note)

之前国内唯一的镜像源daocloud已经没有最新同步的版本了
```
sudo curl -L https://get.daocloud.io/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
```

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by shankerwangmiao** [comment]
您好，我们提供的 docker-ce 镜像已经包含了您所述的软件。请参考：https://mirrors.tuna.tsinghua.edu.cn/docker-ce/

**Comment by willzhang** [comment]
> 您好，我们提供的 docker-ce 镜像已经包含了您所述的软件。请参考：https://mirrors.tuna.tsinghua.edu.cn/docker-ce/

这里面是特定包的文件不是二进制文件，可以提供纯二进制文件吗，这样安装方便
[docker-compose-plugin_2.6.0~ubuntu-jammy_amd64.deb](https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.6.0~ubuntu-jammy_amd64.deb)

**Comment by shankerwangmiao** [comment]
您好，我们提供的 docer-ce 镜像，是适合于多种平台的软件仓库，来源于 docker 官方构建。使用软件仓库安装软件，与直接下载二进制可执行程序相比，更有利于识别系统中缺失的依赖和/或存在冲突的软件，更有利于管理软件版本。
