### ISSUE TITLE
anaconda失效

### ISSUE THREAD

**Issue by Kristopher02** [tuna/issues#2030]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

安装包的时候清华镜像的anaconda失效了
Channels:
 - conda-forge
 - bioconda
 - anaconda
 - defaults
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Platform: linux-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel anaconda <https://mirrors.bfsu.edu.cn/anaconda/anaconda>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

### 期望的现象（What you expected to happen）

我期望能够顺利安装我想要的包

### 如何重现此问题（How to reproduce it）

Nothing to preview

### 操作系统（OS Version）

linux-64

**Comment by shankerwangmiao** [comment]
您好，请提供您 anaconda 的配置。

**Comment by Kristopher02** [comment]
envs_dirs:
  - /home/miniconda3/envs/
channels:
  - conda-forge
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
channel_alias: https://mirrors.bfsu.edu.cn/anaconda
default_channels:
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/pro
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.bfsu.edu.cn/anaconda/cloud
  msys2: https://mirrors.bfsu.edu.cn/anaconda/cloud
  bioconda: https://mirrors.bfsu.edu.cn/anaconda/cloud
  menpo: https://mirrors.bfsu.edu.cn/anaconda/cloud
  pytorch: https://mirrors.bfsu.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.bfsu.edu.cn/anaconda/cloud
  r: https://mirrors.bfsu.edu.cn/anaconda/pkgs/
pkgs_dirs:
  - /home/miniconda/envs
derectories:
  - /home
ssl_verify: true
show_channel_urls: true

**Comment by Harry-Chen** [comment]
请使用代码块（\'\'\'）包裹您的配置文件，以保证可读性

**Comment by Harry-Chen** [comment]
由于没有回复，关闭 issue。
