### ISSUE TITLE
CTAN缺少binhex包

### ISSUE THREAD

**Issue by Firestar-Reimu** [tuna/issues#2032]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

CTAN缺少[binhex](https://www.ctan.org/pkg/binhex)包
```
(base) [firestar@Archlinux ~]$ sudo tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet
tlmgr: setting default package repository to https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet
tlmgr: updating /usr/local/texlive/2024/tlpkg/texlive.tlpdb
(base) [firestar@Archlinux ~]$ sudo tlmgr install binhex
tlmgr: package repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet (verified)
tlmgr install: package binhex not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.
[ble: exit 1]
(base) [firestar@Archlinux ~]$
```

### 期望的现象（What you expected to happen）

正常下载binhex软件包

### 如何重现此问题（How to reproduce it）

如上代码所述

### 操作系统（OS Version）

archlinux

**Comment by Harry-Chen** [comment]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/02e28b5a-573a-45e0-b228-c41073b00b1e">

您所叙述的软件包名为 kastrup。运行 `tlmgr info binhex` 也可以得到相关提示。
