### ISSUE TITLE
fedora 源同步故障，最新日期为2024-05-29

### ISSUE THREAD

**Issue by hwdef** [tuna/issues#2034]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

fedora 源同步故障，最新日期为2024-05-29
<img width="771" alt="image" src="https://github.com/user-attachments/assets/64b94f16-0443-436b-a6c7-ac32cba19bab">

### 期望的现象（What you expected to happen）

fedora软件源正确同步

### 如何重现此问题（How to reproduce it）

页面可以查看
在fedora中 sudo dnf update 也可以复现

### 操作系统（OS Version）

fedora40

**Comment by Harry-Chen** [comment]
rsync 同步没有故障，错误来源于同步后其他 hook 执行失败，用户可以正常使用。
