### ISSUE TITLE
Mozilla 帮助页面下拉框重复

### ISSUE THREAD

**Issue by RalXYZ** [tuna/issues#2035]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![image](https://github.com/user-attachments/assets/c5f2f87a-270c-4f6e-888e-335996a86b15)

上边的那个下拉框是个假的

### 期望的现象（What you expected to happen）

去掉重复的下拉框

### 如何重现此问题（How to reproduce it）

打开 https://mirrors.tuna.tsinghua.edu.cn/help/mozilla/

### 其他需要说明的事项（Anything else we need to know）

我不清楚是什么原因造成的；如果具备普遍性，可以顺便检查一下是否有其他类似的问题，统一进行修复

与此同时，https://help.mirrorz.org/mozilla/ 就没问题

**Comment by Harry-Chen** [comment]
Fixed in https://github.com/mirrorz-org/mirrorz-docs/commit/4f5cd7b57ded0c24121473e5a381ac6b2c11b84b. 稍后部署。
