### ISSUE TITLE
[镜像请求] NPM 反向代理

### ISSUE THREAD

**Issue by snowdream** [tuna/issues#2037]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

NPM 镜像源 反向代理

（之前提到的 NPM 镜像源方案，是直接同步https://registry.npmjs.org/  ， 而不是反向代理。）

### 上游地址与镜像方法 (How to mirror)

https://registry.npmjs.org/

### 镜像大小 (Mirror size)

未知

### 备注 (Note)

参考中科大的 NPM 反向代理：
https://mirrors.ustc.edu.cn/help/npm.html

NPM 反向代理[¶](https://mirrors.ustc.edu.cn/help/npm.html#npm)
中科大镜像站的 npm 镜像是 https://registry.npmjs.org/ 的反代。

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by shankerwangmiao** [comment]
您好，TUNA 不提供反向代理服务。

**Comment by Harry-Chen** [comment]
#741 第五条：一般不使用反向代理的方式提供镜像
