### ISSUE TITLE
[镜像请求] XanMod is a general-purpose Linux kernel distribution with custom settings and new features. Built to provide a stable, smooth and solid system experience.

### ISSUE THREAD

**Issue by minmemory** [tuna/issues#2039]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

XanMod is a general-purpose Linux kernel distribution with custom settings and new features. Built to provide a stable, smooth and solid system experience.
The real-time version is recommended for critical runtime applications such as Linux gaming server / client for eSports, streaming, live productions and
ultra-low latency enthusiasts.
一款为游戏和实时性优化的Debian/Ubuntu内核

Main Features

Core and Process Scheduling, Load Balancing, Caching, Virtual Memory Manager and CPUFreq Governor optimized for heavy workloads.
Block layer runqueue requests for high IOPS throughput.
ORC Unwinder for kernel stack traces (debuginfo) implementation.
Real-time Linux kernel (PREEMPT_RT) build available [6.6-rt].
Third-party patchset available: [patches](https://gitlab.com/xanmod/linux-patches)
Cloudflare's TCP collapse processing for high throughput and low latency [[info](https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency)].
Google's Multigenerational LRU framework [default].
Google's BBRv3 TCP congestion control [built-in: tcp_bbr] [default].
Netfilter nf_tables RFC3489 full-cone NAT support.
Netfilter FLOWOFFLOAD target to speed up processing of packets.
NT synchronization primitives emulation driver [as module: ntsync].
Valve's Steam Deck EC sensors / MFD core and LEDs driver support
[as module: steamdeck, steamdeck-hwmon, leds-steamdeck] [6.10] [6.11].
PCIe ACS Override for bypassing IOMMU groups support.
Graysky's additional GCC and Clang CPU options.
Clear Linux patchset [partial].
Android Binder IPC driver for Waydroid [as module: binder_linux].
Generic packages for compatibility with any Debian or Ubuntu based distribution.
GPLv2 license. Can be built for any distribution or purpose.

### 上游地址与镜像方法 (How to mirror)

apt源 deb.xanmod.org

### 镜像大小 (Mirror size)

不详，由于提供的Kernel版本并不多，猜测占据空间不大

### 备注 (Note)

国内没有任何可用镜像，裸连基于Cloudflare的源甚至有时速度低于1KB/s
![image](https://github.com/user-attachments/assets/22772cc0-2ce4-410e-b7eb-6b3c0a0f5293)

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
```

**Comment by Harry-Chen** [comment]
可尝试使用 <https://mirrors.tuna.tsinghua.edu.cn/xanmod/> 检查是否有问题（尚未正式上线）

**Comment by Harry-Chen** [comment]
所属的镜像和帮助已经上线
