### ISSUE TITLE
F-Droid 镜像出现 502 Bad Gateway

### ISSUE THREAD

**Issue by qianbinbin** [tuna/issues#2043]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[F-Droid 仓库](https://mirrors.tuna.tsinghua.edu.cn/fdroid/repo/?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB) 客户端无法使用，打开网页出现 502

### 期望的现象（What you expected to happen）

正常使用

### 如何重现此问题（How to reproduce it）

点击 https://mirrors.tuna.tsinghua.edu.cn/fdroid/repo/?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB

**Comment by Harry-Chen** [comment]
感谢告知，已经恢复服务。
