### ISSUE TITLE
openwrt镜像地址502错误

### ISSUE THREAD

**Issue by Nguyendream** [tuna/issues#2044]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

访问 https://mirrors.tuna.tsinghua.edu.cn/openwrt/ 提示502
![image](https://github.com/user-attachments/assets/f9fac0e7-4659-47ce-a4c5-64edf83375f1)

### 期望的现象（What you expected to happen）

能够正常得访问

### 如何重现此问题（How to reproduce it）

访问https://mirrors.tuna.tsinghua.edu.cn/openwrt/

**Comment by Harry-Chen** [comment]
Duplicated with #2043.
