### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by wxlch** [tuna/issues#2045]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

无法下载文件http://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQL-8.0/mysql-8.0.36-linux-glibc2.12-x86_64.tar.xz

### 期望的现象（What you expected to happen）

能下载http://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQL-8.0/mysql-8.0.36-linux-glibc2.12-x86_64.tar.xz

### 如何重现此问题（How to reproduce it）

直接点链接http://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQL-8.0/mysql-8.0.36-linux-glibc2.12-x86_64.tar.xz

### 操作系统（OS Version）

window10

**Comment by wxlch** [comment]
能不能更新呢

**Comment by Harry-Chen** [comment]
您从哪里取得的这个链接？镜像站并不存在 /mysql/downloads/ 目录。

**Comment by wxlch** [comment]
https://oneinstack.com/auto/，这个服务商用的，但是我联系不上他，希望咱这里能下载对应资源


&nbsp;


李春辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shengqi ***@***.***&gt;; 
发送时间: 2024年9月24日(星期二) 中午1:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuna/issues] 崩溃 (Issue #2045)















您从哪里取得的这个链接？镜像站并不存在 /mysql/downloads/ 目录。

**Comment by Harry-Chen** [comment]
您所述的服务和 TUNA 没有关系，TUNA 不曾也不会为第三方提供资源下载保证，请您联系相应服务商解决。
