### ISSUE TITLE
增加对Juliaup的镜像加速使用方式的文档介绍

### ISSUE THREAD

**Issue by Evian-Zhang** [tuna/issues#2046]
目前，Julia[官方推荐的下载安装方式](https://docs.julialang.org/en/v1.12-dev/manual/installation/#Mac-and-Linux)是使用[Juliaup](https://github.com/JuliaLang/juliaup)这个工具，并且该工具提供了非常简易的[镜像加速使用方式](https://github.com/JuliaLang/juliaup#juliaup-server)。按照我的理解，目前TUNA的Julia镜像服务器可以直接被用于Juliaup的镜像加速。是否考虑在帮助文档中增加对此的介绍？

**Comment by Harry-Chen** [comment]
请向 https://github.com/mirrorz-org/mirrorz-docs 提出 PR。

**Comment by Evian-Zhang** [comment]
OK, Thanks :)
