### ISSUE TITLE
MacPorts 镜像域名  pek.cn.*.macports.org 不可用

### ISSUE THREAD

**Issue by laggardkernel** [tuna/issues#2047]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

`pek.cn.*.macports.org` 访问报 HTTP 错误 ERR_HTTP2_PROTOCOL_ERROR，这好像是 macports 授权给 tuna 的域名。不确定是不是由你们管理。

https://github.com/tuna/issues/issues/157#issuecomment-265130083

### 期望的现象（What you expected to happen）

`pek.cn.*.macports.org` 是内置在 [macports-ports](https://github.com/macports/macports-ports) 库中默认 archive mirror, distfiles mirror 列表的。希望能处理一下正常访问。如果 `pek.cn.*.macports.org` 不怎么维护，也可以考虑替换 macports-ports 库中域名为 `mirrors.tuna.tsinghua.com`.

### 如何重现此问题（How to reproduce it）

- https://pek.cn.distfiles.macports.org/macports/distfiles/aria2/aria2-1.37.0.tar.gz
- https://pek.cn.distfiles.macports.org/macports/packages/aria2/aria2-1.37.0_5.darwin_21.arm64.tbz2

但 mirrors.tuna.tsinghua.com 域名访问正常。

- https://mirrors.tuna.tsinghua.edu.cn/macports/distfiles/aria2/aria2-1.37.0.tar.gz
- https://mirrors.tuna.tsinghua.edu.cn/macports/packages/aria2/aria2-1.37.0_5.darwin_21.arm64.tbz2

**Comment by Harry-Chen** [comment]
pek.cn.distfiles.macports.org 不能通过浏览器访问，命令行工具可以正常使用，这是预期现象。

**Comment by laggardkernel** [comment]
抱歉，是我 `preferred_hosts` 写法有问题，distfiles mirror 没有命中 pek.cn. 昨天在排查过程中我就是用的就是命令行 curl，但 curlrc 配置了 user-agent 为浏览器 UA，curl 请求也失败。（port install 中 curl 不会有这种问题，因为 port install 运行用户是 macports，而非当前用户。）

另外想起来我之前是知道 `pek.cn.*.macports.org` 不能浏览器访问的，但时间一长有点忘记了。谢谢你的帮助。
