### ISSUE TITLE
MacPorts: 使用TUNA镜像时可能无法检测Portfile更新

### ISSUE THREAD

**Issue by thelastlin** [tuna/issues#2049]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在使用TUNA镜像时，`port selfupdate`会给出警告，提示无法检查Portfile是否有更新，原因是请求被拒绝。

### 期望的现象（What you expected to happen）

在配置使用TUNA镜像时，`port selfupdate`可检查ports.tar的Last-Modified字段属性并决定是否需要更新portfiles。

### 如何重现此问题（How to reproduce it）

修改 `$PORTPREFIX/etc/macports/sources.conf` 为：
```
https://mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs/ports.tar [default]
```

### 其他需要说明的事项（Anything else we need to know）

审阅发现MacPorts中检查Portfile的请求未设置useragent，已发送相应的patch （ https://github.com/macports/macports-base/pull/349 ）。

可考虑暂时容许在不设置useragent的情况下请求`https://mirrors.tuna.tsinghua.edu.cn/macports/release/tarballs/ports.tar`，以允许现有MacPorts客户端获取响应中的Last-Modified字段。

**Comment by Harry-Chen** [comment]
很遗憾，此文件较大，我们无法设置例外。

**Comment by thelastlin** [comment]
相关patch已被合并且跟随MacPorts 2.10.2发布。
