### ISSUE TITLE
AOSP镜像服务器同步失败

### ISSUE THREAD

**Issue by kirkowen** [tuna/issues#205]
#### 项目名称与简介(Project Intro.)
AOSP源码repo sync失败
#### 错误异常
fatal: repository 'https://aosp.tuna.tsinghua.edu.cn/platform/test/vts-testcase/vndk/' not found
Cannot fetch platform/test/vts-testcase/vndk

**Comment by Hollz** [comment]
到 99% 同步不了了。。。。。。

**Comment by kirkowen** [comment]
查看谷歌的AOSP包含这个文件夹，是不是因为test包的原因，tuna并没有同步此文件，而清单文件中存在这个文件，导致 服务器 未找到该文件，repo sync不成功，文件不能checkout出来啊，有没有管理员介绍下如何忽略此文件，或者同步tuna的AOSP中此文件夹

**Comment by huiyiqun** [comment]
TUNA镜像的文件列表严格遵照AOSP给出的[repo列表](https://android.googlesource.com/mirror/manifest/)，vndk并不在这个列表里，所以tuna不镜像它是合理的。

你可以尝试在你的项目目录的 `.repo/manifests.xml`这个文件里搜索vndk并删掉，或者联系AOSP的管理者，让他们把vndk加上。

**Comment by huiyiqun** [comment]
99% 同步不了可能有很多原因，如果没有报错可以多等一下，最后一步比较慢。

**Comment by Hollz** [comment]
注释掉 vndk 就可以同步完了。

**Comment by kirkowen** [comment]
非常感谢，删除到vndk后，同步成功了
