### ISSUE TITLE
Not FOUND

### ISSUE THREAD

**Issue by Royluoyi123** [tuna/issues#2050]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

CondaHTTPError: HTTP 404 NOT FOUND for url <http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/ld_impl_linux-64-2.40-h12ee557_0.tar.bz2>
Elapsed: 00:00.028273

### 期望的现象（What you expected to happen）

创建新环境时出现

### 如何重现此问题（How to reproduce it）

HTTP 404

**Comment by shankerwangmiao** [comment]
您好，`.tar.bz2` 扩展名的 anaconda 包是较旧的软件包格式，我们不再提供。请使用 4.7.0 及以上版本的 anaconda 客户端程序即可正常使用。
