### ISSUE TITLE
conda仓库似乎没有同步

### ISSUE THREAD

**Issue by zhang-stephen** [tuna/issues#2051]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用miniconda安装`coverage 7.6.1`失败，报错如下：

```
CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/coverage-7.6.1-py312h827c3e9_0.conda>
Elapsed: 00:00.182074
```

但是`conda search`命令显示该软件包存在于main channel中：
![image](https://github.com/user-attachments/assets/aa61d1cd-05c3-40c6-8582-d2888a73e5da)

在main channel页面进行搜索，该软件包最新版本是去年发布的7.2.2:
![image](https://github.com/user-attachments/assets/5385e043-3b26-49fe-aa44-1321748bfede)

### 期望的现象（What you expected to happen）

该软件包可以正常安装。

### 如何重现此问题（How to reproduce it）

将conda源设置为清华大学Tuna，然后运行此命令：
```bash
conda install coverage=7.6.1
```

### 操作系统（OS Version）

Windows 11 Pro 23H2

**Comment by shankerwangmiao** [comment]
从同步日志看，该软件包在今天 18 时的同步时，还未出现在软件包仓库的清单中。目前已重新同步。

**Comment by shankerwangmiao** [comment]
您好，经查，我们服务器从 CloudFlare 获取到的 `/pkgs/main/win-64/repodata.json` 的修改日期为 `Fri, 04 Oct 2024 14:26:35 GMT`；目前较新的版本的修改日期应为 `Fri, 04 Oct 2024 19:02:17 GMT`。推测 CloudFlare 缓存的问题，导致服务器获取到了较旧版本的索引文件，致使缺少该软件包。

该问题可能需要等待 CloudFlare 缓存更新方可解决。

**Comment by zhang-stephen** [comment]
感谢，今天可以正常安装该软件包了。
