### ISSUE TITLE
镜像缺失：https://mirrors.tuna.tsinghua.edu.cn/gentoo/distfiles/72/chromium-129.0.6668.89.tar.xz 

### ISSUE THREAD

**Issue by dingjingmaster** [tuna/issues#2052]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

镜像文件不存在

https://mirrors.tuna.tsinghua.edu.cn/gentoo/distfiles/72/chromium-129.0.6668.89.tar.xz

### 期望的现象（What you expected to happen）

修复镜像文件，原始文件位置：
https://commondatastorage.googleapis.com/chromium-browser-official/chromium-129.0.6668.89.tar.xz

### 如何重现此问题（How to reproduce it）

打开浏览器访问：

https://mirrors.tuna.tsinghua.edu.cn/gentoo/distfiles/72/chromium-129.0.6668.89.tar.xz

提示不存在

### 操作系统（OS Version）

gentoo

### 浏览器（如果适用）（Browser version, if applicable）

任何浏览器

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by shankerwangmiao** [comment]
目前 Gentoo 镜像不能在合理的时间内同步完毕。经查，其原因可能是 IIJ 在 HKIX 的接入存在异常，丢包率较高。我们已经切换上游。您可以等待同步完成后再使用，或使用 BFSU 镜像。后者同步是正常的。

**Comment by shankerwangmiao** [comment]
目前应该已经同步完成了。
