### ISSUE TITLE
访问tuna报错SSL连接失败，http无返回

### ISSUE THREAD

**Issue by zyppe** [tuna/issues#2056]
坐标南京栖霞区，使用南京电信IP 121.229.242.27 (已被NAT)
curl访问 http://mirrors.tuna.tsinghua.edu.cn 无返回
访问 https://mirrors.tuna.tsinghua.edu.cn 报错
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.tuna.tsinghua.edu.cn:443`
同样问题出现在bfsu镜像

**Comment by shankerwangmiao** [comment]
您所在的地址段 121.229.242.0/24 因大量反复持续下载 proxmox 安装镜像而被禁止访问本站。
