### ISSUE TITLE
下载cuda11.6对应pytorch无非

### ISSUE THREAD

**Issue by ThereIsHu** [tuna/issues#2057]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

![image](https://github.com/user-attachments/assets/331f0ca5-ba29-4fc7-a12f-d05532039e52)
![微信截图_20241024114612](https://github.com/user-attachments/assets/2ea3b627-61b8-447d-a007-d589bfb062dd)

### 期望的现象（What you expected to happen）

能够安装成功

### 如何重现此问题（How to reproduce it）

conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c nvidia执行这个

### 操作系统（OS Version）

win10

**Comment by shankerwangmiao** [comment]
您好，由于 #1232 的原因，我们无法提供 anaconda 的 nvidia channel。
