### ISSUE TITLE
[镜像请求] 请增加almalinux镜像

### ISSUE THREAD

**Issue by wqxl** [tuna/issues#2058]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

# almalinux镜像源
---
almalinux是后centos时代下使用最广泛的Linux开源系统，它是centos的继承者，目前国内的镜像站基本都包含了almalinux的镜像源，只有清华的没有，建议同步一下。

### 上游地址与镜像方法 (How to mirror)

https://repo.almalinux.org/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by Harry-Chen** [comment]
> 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。

Duplicated with #1186, #1613, #1218.

> 只有清华的没有

以下是 USTC 镜像站的搜索结果：

<img width="706" alt="image" src="https://github.com/user-attachments/assets/87be57c2-6bdd-497c-8971-b227233bd1d6">
