### ISSUE TITLE
[镜像请求] 请增加rocky镜像源

### ISSUE THREAD

**Issue by henglgh** [tuna/issues#2059]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

# rocky镜像源
---
rocky Linux是redhad继承者，它是开源免费。和almalinux一样，现在在企业中使用比较广泛，建议增加rocky Linux的镜像源

### 上游地址与镜像方法 (How to mirror)

http://dl.rockylinux.org/

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [ ] BFSU - https://mirrors.bfsu.edu.cn

**Comment by KexyBiscuit** [comment]
See also: https://github.com/tuna/issues/issues/1236#issuecomment-868641135

**Comment by Harry-Chen** [comment]
> 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。

Duplicated with #1935, #1320, #1284, #1281, #1249, #1246, #1236, #1093.

> 我已仔细阅读 https://github.com/tuna/issues/issues/741。

其中也有相应的表述。

> 如果是因为“国内镜像源已经足够用了”，那么清华镜像站存在的理由是什么？

根据 [行为准则](https://github.com/tuna/issues/blob/master/CODE_OF_CONDUCT.md)，鉴于您此类不友好的言论，以及与 #2058 相同的违反提交先决条件的行为，我决定将您从 TUNA 组织中封禁一段时间。
