### ISSUE TITLE
whl包推送到pypi半个月tuna源未同步

### ISSUE THREAD

**Issue by myhloli** [tuna/issues#2061]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

https://pypi.org/project/doclayout-yolo/
10月16号推送到pypi上，至今近半个月，tuna仍无法缓存该软件包

### 期望的现象（What you expected to happen）

在tuna源可以正常下载该软件包

### 如何重现此问题（How to reproduce it）

pip install doclayout_yolo -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by Harry-Chen** [comment]
可能是新同步工具 shadowmire 的问题，@taoky 正在协助调查中

**Comment by SherkeyXD** [comment]
发现同样情况 https://pypi.org/project/nonebot-plugin-nailongremove/
最新为 2.1.4，tuna 源为 1.1.7

**Comment by taoky** [comment]
> 发现同样情况 https://pypi.org/project/nonebot-plugin-nailongremove/ 最新为 2.1.4，tuna 源为 1.1.7

```
> curl https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/nonebot-plugin-nailongremove/ | grep 2.1.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14681  100 14681    0     0  10181      0  0:00:01  0:00:01 --:--:-- 10188
    <a href="../../packages/6d/03/60072c1c958745b52c84d46ceb8082f3a9b0e6110d1701e68ed266878b62/nonebot_plugin_nailongremove-2.1.4-py3-none-any.whl#sha256=7ecf3e31a3bc4b2f986913ca901b5d147c4b8dbde2d8bd703291f94ed3ca678d" data-requires-python="&lt;4.0,&gt;=3.9">nonebot_plugin_nailongremove-2.1.4-py3-none-any.whl</a><br/>
    <a href="../../packages/68/0a/2bff07f5bc03224211184511225a94ad1c0ce3e9530e6a848fc22567f466/nonebot_plugin_nailongremove-2.1.4.tar.gz#sha256=d5602a04e1457d60f71eb94285086ce67decf3a3a371dd82496f7b6561cac3a8" data-requires-python="&lt;4.0,&gt;=3.9">nonebot_plugin_nailongremove-2.1.4.tar.gz</a><br/>
```

请给出复现「tuna 源为 1.1.7」判断的方法。

**Comment by SherkeyXD** [comment]
> 请给出复现「tuna 源为 1.1.7」判断的方法

刚才尝试复现失败了，不过昨天下午直接 `pip install nailomgremove` 的时候装的是 1.1.7，且尝试 `pip install nailomgremove==2.1.4` 提示找不到版本
