### ISSUE TITLE
fedora换源帮助

### ISSUE THREAD

**Issue by happy-game** [tuna/issues#2062]
在fedora39以上就不再使用/etc/yum.repos.d/fedora-modular.repo和/etc/yum.repos.d/fedora-update-modular.repo了，但是清华源的[换源帮助](https://mirrors.tuna.tsinghua.edu.cn/help/fedora/)并没有作出修改，感觉可以像[ustc](https://mirrors.ustc.edu.cn/help/fedora.html)一样分为39以上和39以下，是否有计划对此进行更新呢?

**Comment by taoky** [comment]
欢迎向 https://github.com/mirrorz-org/mirrorz-help 或 https://github.com/mirrorz-org/mirrorz-docs 任一仓库提交相关修改 PR。在合并之后 TUNA 目前的帮助会自动创建更新 PR。

**Comment by happy-game** [comment]
好的，那我去 mirrorz-help重新开一个issue
