### ISSUE TITLE
突然ping不上清华源mirrors.tuna.tsinghua.edu.cn

### ISSUE THREAD

**Issue by EastbeanZhang** [tuna/issues#2064]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

不清楚发生了什么，本来好好的，这两天突然就连接不上。服务器可以正常ping上国内其它网址，唯独清华源ping不上，不知道是否被黑名单了。平常偶尔安装一下conda envs，也没有频繁使用，不清楚为啥突然连接不上，周围的其它服务器可以正常连接，唯独这台服务器连接不上。
ping mirrors4.tuna.tsinghua.edu.cn
PING bfdmirrors4.a.s.tuna.tsinghua.edu.cn (101.6.15.130) 56(84) bytes of data.
^C
--- bfdmirrors4.a.s.tuna.tsinghua.edu.cn ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7158ms

### 期望的现象（What you expected to happen）

希望能帮忙解决问题

### 如何重现此问题（How to reproduce it）

不懂，莫名其妙就被连接不上

### 操作系统（OS Version）

Linux

### 其他环境（Other environments）

Ubuntu focal

**Comment by EastbeanZhang** [comment]
ping mirrors.tuna.tsinghua.edu.cn
PING bfdmirrors.s.tuna.tsinghua.edu.cn (101.6.15.130) 56(84) bytes of data.
^C
--- bfdmirrors.s.tuna.tsinghua.edu.cn ping statistics ---
12 packets transmitted, 0 received, 100% packet loss, time 11254ms

**Comment by shankerwangmiao** [comment]
请您测试能否正常访问清华大学主页，https://www.tsinghua.edu.cn；并测试是否能 ping 通 166.111.4.100

**Comment by EastbeanZhang** [comment]
仍然没有响应：
 ping 166.111.4.100
PING 166.111.4.100 (166.111.4.100) 56(84) bytes of data.
^C
--- 166.111.4.100 ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8185ms

其它国内网址都可以
ping www.baidu.com
PING www.a.shifen.com (183.2.172.42) 56(84) bytes of data.
64 bytes from 183.2.172.42 (183.2.172.42): icmp_seq=1 ttl=50 time=6.19 ms
64 bytes from 183.2.172.42 (183.2.172.42): icmp_seq=2 ttl=50 time=5.59 ms
64 bytes from 183.2.172.42 (183.2.172.42): icmp_seq=3 ttl=50 time=5.93 ms
ping mirrors.aliyun.com
PING mirrors.aliyun.com.w.alikunlun.com (113.240.105.115) 56(84) bytes of data.
64 bytes from 113.240.105.115 (113.240.105.115): icmp_seq=1 ttl=49 time=21.1 ms
64 bytes from 113.240.105.115 (113.240.105.115): icmp_seq=2 ttl=49 time=20.4 ms
64 bytes from 113.240.105.115 (113.240.105.115): icmp_seq=3 ttl=49 time=20.5 ms

**Comment by shankerwangmiao** [comment]
说明您的 IP 地址已经被我校信息中心封禁。

**Comment by EastbeanZhang** [comment]
请问怎么恢复，没有任何不当操作

**Comment by shankerwangmiao** [comment]
信息中心会按其策略完成解封，具体策略我们不掌握。
