### ISSUE TITLE
rustup 指定rust-toolchain版本下载出错

### ISSUE THREAD

**Issue by afs0939** [tuna/issues#2065]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

rust-toolchain
[toolchain]
channel = "1.80.0"

❯ git clone https://github.com/emilk/eframe_template.git
❯ cargo run
info: syncing channel updates for '1.76-x86_64-unknown-linux-gnu'
info: downloading component 'rust'
error: could not download nonexistent rust version `1.76-x86_64-unknown-linux-gnu`: could not download file from 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/rust-1.76-x86_64-unknown-linux-gnu.tar.gz.sha256' to '/home/xxx/.rustup/tmp/51z56dpzfntwf6_c_file': http request returned an unsuccessful status code: 404

### 期望的现象（What you expected to happen）

应该是直接执行下载流程的

### 如何重现此问题（How to reproduce it）

export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
git clone https://github.com/emilk/eframe_template.git
cargo run

### 操作系统（OS Version）

ubuntu

### 其他环境（Other environments）

rust、cargo

**Comment by jiegec** [comment]
Duplicate with https://github.com/tuna/issues/issues/1961
