### ISSUE TITLE
请求优化 pypi 镜像对于阿里云的屏蔽策略

### ISSUE THREAD

**Issue by oraluben** [tuna/issues#2067]
https://github.com/tuna/issues/issues/1781#issuecomment-1630255653 中提及由于带宽原因，屏蔽了来自阿里云的请求。

首先，我想表达对该决定的理解和对以往镜像站服务的感激。

其次，我希望在屏蔽时对（pypi 下）所有访问进行屏蔽，而不只是屏蔽whl文件的下载。这能让pip在被屏蔽的环境下自动选择其他index，而不是选择tuna/bfsu镜像后在下载时报错。这样能更好支持如下的配置：

```
pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
pip config set global.trusted-host mirrors.aliyun.com
pip config set global.extra-index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
```

**Comment by Tigerdwgth** [comment]
我没在阿里云上也被屏蔽了，什么原因造成的

**Comment by shankerwangmiao** [comment]
> 我没在阿里云上也被屏蔽了，什么原因造成的

您好，您如果发现您被屏蔽了，请按照响应内容中的指示，提供访问标识符以便我们进一步诊断。

**Comment by shankerwangmiao** [comment]
> [#1781 (comment)](https://github.com/tuna/issues/issues/1781#issuecomment-1630255653) 中提及由于带宽原因，屏蔽了来自阿里云的请求。
> 
> 首先，我想表达对该决定的理解和对以往镜像站服务的感激。
> 
> 其次，我希望在屏蔽时对（pypi 下）所有访问进行屏蔽，而不只是屏蔽whl文件的下载。这能让pip在被屏蔽的环境下自动选择其他index，而不是选择tuna/bfsu镜像后在下载时报错。这样能更好支持如下的配置：
> 
> ```
> pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
> pip config set global.trusted-host mirrors.aliyun.com
> pip config set global.extra-index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
> ```

目前我们会对请求 `web/simple` 索引的情形返回 403 响应。建议贵司内部使用自行建设的镜像，以提高访问效率。
