### ISSUE TITLE
[504]https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra_release/ios-usb-dependencies/ios-deploy/7a29ab0b6d611f2bf5de4b6f929a82a091866 307/ios-deploy.zip

### ISSUE THREAD

**Issue by slxz** [tuna/issues#2068]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

flutter下载，flutter doctor初始化时报错

### 期望的现象（What you expected to happen）

正常下载，目前https://storage.flutter-io.cn/flutter_infra_release/ios-usb-dependencies/ios-deploy/7a29ab0b6d611f2bf5de4b6f929a82a091866
307/ios-deploy.zip 能正常下载

### 如何重现此问题（How to reproduce it）

flutter SDK version 3.7.12

### 操作系统（OS Version）

Macos 13.7 (22H123)

**Comment by shankerwangmiao** [comment]
感谢报告，已经恢复了。
