### ISSUE TITLE
docker发布重大更新，包名和仓库全换

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#207]
3月2日，docker官方发布了blog: https://blog.docker.com/2017/03/docker-enterprise-edition/

之后，docker将版本分为社区版(CE)和企业版(EE)，版本号也从13.x直接跳跃到17.03，之后每个月一个edge版本(17.03,17.04,17.05...)，每三个月一个stable版本(17.03,17.06,17.09...)

- 仓库变更为: `https://download.docker.com/` (dig结果显示cloudfront.net，某不存在的网站)
- 软件包变更为: `docker-ce`和`docker-ee`
- 旧的仓库依旧维护，但不确定什么时候会被干掉。包名依旧维持`docker-engine`，但是版本号变成了`17.03.0~ce-0`这样的

希望考虑下这种变更如何维护，是否考虑镜像新仓库？

**Comment by huiyiqun** [comment]
有时间重新建一个新的repo吧 方法上可以沿用原来的方式

**Comment by abcfy2** [comment]
或者在以前的目录下建立一个子目录？

**Comment by abcfy2** [comment]
或者干脆把原来的`docker/`目录干掉，重新从新的仓库`download.docker.com`重新同步算了，需要对应的更新下doc，安装的包名改为`docker-ce`

**Comment by huiyiqun** [comment]
不太好…用老版本的人一脸懵逼…

**Comment by abcfy2** [comment]
那就新建一个`docker-ce/`也行，我去官方文档看了一下，`download.docker.com`只有`docker-ce`软件包，`docker-ee`并不在`download.docker.com`

**Comment by knight42** [comment]
USTC Mirrors 已加, 不过目前只有 ubuntu 跟 debian 的:

http://mirrors.ustc.edu.cn/docker-ce/

**Comment by bigeagle** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/
更新了～
