### ISSUE TITLE
ArchLinux下载Waydroid镜像失败

### ISSUE THREAD

**Issue by stvsl** [tuna/issues#2071]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

waydroid-image 下载失败
sudo pacman -S waydroid-image
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) waydroid-image-18.1_20241116-2

下载大小：       624.34 MiB
全部安装大小：  2238.23 MiB
净更新大小：      28.90 MiB

:: 进行安装吗？ [Y/n] 
:: 正在获取软件包......
waydroid-image-18.1_20241116-2-x86_64.pkg.tar.zst下载失败
错误：无法从 mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 403 获取文件 'waydroid-image-18.1_20241116-2-x86_64.pkg.tar.zst'
警告：无法获取某些文件
错误：无法提交处理 (无法获取某些文件)
发生错误，没有软件包被更新。

### 期望的现象（What you expected to happen）

正常下载，完成安装

### 如何重现此问题（How to reproduce it）

sudo pacman -S waydroid-image

### 操作系统（OS Version）

Arch Linux

**Comment by stvsl** [comment]
这是公司网络，大概两三周前同事下载Qt源码可能次数比较多，问一下这个网段还有恢复正常的可能吗？如果可以恢复大概需要多久？

**Comment by shankerwangmiao** [comment]
日志显示，上述下载行为与正常人为的下载具有显著区别。我们会在异常请求停止 90 天之后考虑将网段从关注列表中移除。
