### ISSUE TITLE
ubuntu 23.04 没有 Release 文件

### ISSUE THREAD

**Issue by Enborgrn** [tuna/issues#2075]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

忽略:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar InRelease
忽略:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-updates InRelease
忽略:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-backports InRelease
忽略:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-security InRelease
错误:5 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar Release
  404  Not Found [IP: 198.18.1.66 443]
错误:6 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-updates Release
  404  Not Found [IP: 198.18.1.66 443]
错误:7 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-backports Release
  404  Not Found [IP: 198.18.1.66 443]
错误:8 https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-security Release
  404  Not Found [IP: 198.18.1.66 443]
正在读取软件包列表... 完成
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-updates Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-backports Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://mirrors.tuna.tsinghua.edu.cn/ubuntu lunar-security Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

### 期望的现象（What you expected to happen）

更新

### 如何重现此问题（How to reproduce it）

无

### 操作系统（OS Version）

linux(ubuntu 23.04)

### 浏览器（如果适用）（Browser version, if applicable）

firefox

### 其他环境（Other environments）

无

### 其他需要说明的事项（Anything else we need to know）

无

**Comment by taoky** [comment]
Ubuntu 23.04 已经 EOL 了，被上游删除并且不再会有任何软件更新：<https://endoflife.date/ubuntu>

如果仍然要继续使用，需要使用其他镜像站的 ubuntu-old-releases 仓库：https://mirrorz.org/list/ubuntu-old-releases
