### ISSUE TITLE
北外 xanmod 镜像异常

### ISSUE THREAD

**Issue by lc0a** [tuna/issues#2077]
### 先决条件 (Prerequisites)

- [x] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

[北外镜像站提供的 XanMod 内核 APT 仓库镜像](https://mirrors.bfsu.edu.cn/xanmod)无法正常使用。

### 期望的现象（What you expected to happen）

能够顺利地执行 `apt update` 等命令。

### 如何重现此问题（How to reproduce it）

 - 按照镜像站提供的[方法](https://mirrors.bfsu.edu.cn/help/xanmod)配置镜像源；
 - 执行 `apt update` ，出现错误
```
$ sudo apt update

...

获取:7 https://mirrors.bfsu.edu.cn/xanmod releases InRelease [2,091 B]
获取:8 https://mirrors.bfsu.edu.cn/xanmod releases/main amd64 Packages [61.0 kB]
错误:8 https://mirrors.bfsu.edu.cn/xanmod releases/main amd64 Packages
  文件尺寸不符(59982 != 61044)。您使用的镜像正在同步中？ [IP: 39.155.141.16 443]
  Hashes of expected file:
   - Filesize:61044 [weak]
   - SHA256:8c9737664590d8fe590f961a0469b11901ea61c2401625efe75f0726d0038bf4
   - SHA1:bc17f528abad926e34012b1aab3d9097902f355e [weak]
   - MD5Sum:da9efdb7c2b257bde799b97436f8b5ab [weak]
  Release file created at: Fri, 29 Nov 2024 01:22:49 +0000
已下载 7,517 B，耗时 1秒 (8,239 B/s)
正在读取软件包列表... 完成
E: 无法下载 https://mirrors.bfsu.edu.cn/xanmod/dists/releases/main/binary-amd64/Packages.gz  文件尺寸不符(59982 != 61044)。您使用的镜像正在同步中？ [IP: 39.155.141.16 443]
   Hashes of expected file:
    - Filesize:61044 [weak]
    - SHA256:8c9737664590d8fe590f961a0469b11901ea61c2401625efe75f0726d0038bf4
    - SHA1:bc17f528abad926e34012b1aab3d9097902f355e [weak]
    - MD5Sum:da9efdb7c2b257bde799b97436f8b5ab [weak]
   Release file created at: Fri, 29 Nov 2024 01:22:49 +0000
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

```

### 操作系统（OS Version）

Debian bookworm 12.8 amd64

### 浏览器（如果适用）（Browser version, if applicable）

N/A

### 其他环境（Other environments）

/etc/apt/sources.list.d/xanmod.list 文件内容：
```
deb [signed-by=/usr/share/keyrings/xanmod-archive-keyring.gpg] https://mirrors.bfsu.edu.cn/xanmod releases main
```

### 其他需要说明的事项（Anything else we need to know）

如果将上述文件中相应 URL 替换为清华源 (https://mirrors.tuna.tsinghua.edu.cn/xanmod) 或官方源 (https://deb.xanmod.org)  ，那么 `apt update` 等命令也可顺利执行。

对比两镜像站相关页面（ [清华](https://mirrors.tuna.tsinghua.edu.cn/xanmod/dists/releases/main/binary-amd64/) 和 [北外](https://mirrors.bfsu.edu.cn/xanmod/dists/releases/main/binary-amd64/) ）可以发现，有文件（Packages.gz）的日期不一致，且清华源该文件日期较新，北外的较旧。如图：

![issue_20241130](https://github.com/user-attachments/assets/2d1f99e3-3fce-441b-8438-f0dea00c40ad)

个人猜测，可能北外镜像站同步该镜像时出错。

截图时，北外镜像站显示该镜像更新时间为今天（11 月 30 日） 凌晨 5 时左右，但该站于今天下午 5 时 30 分再次成功更新该镜像后，问题依旧存在。

希望贵方能检查这个镜像的完整性，并重新同步该镜像。

**Comment by shankerwangmiao** [comment]
您好，感谢您反馈此问题，已经重新安排北外同步。

**Comment by shankerwangmiao** [comment]
目前已经恢复正常。
