### ISSUE TITLE
apt报告mozilla镜像文件尺寸不符

### ISSUE THREAD

**Issue by ImpleLee** [tuna/issues#2081]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

添加tuna的mozilla镜像到apt后，运行`sudo aptitude update`，报告错误。
```
读取： 10 https://mirrors.tuna.tsinghua.edu.cn/mozilla/apt mozilla/main all Packages [5,293 kB]                                                                        
错误 https://mirrors.tuna.tsinghua.edu.cn/mozilla/apt mozilla/main all Packages                                                                                        
  文件尺寸不符(17720195 != 5293198)。您使用的镜像正在同步中？
Hashes of expected file:
 - Filesize:5293198 [weak]
 - SHA256:f4573addb3b67c9a3b69020668f1ad87ae4f940afbbf5f84801bcbb94c53c5a2
 - MD5Sum:978bd5f62161f46991efd135a81f3cbb [weak]
Release file created at: Wed, 04 Dec 2024 16:41:38 +0000
```

### 期望的现象（What you expected to happen）

能够正常更新（注意到镜像站首页并未将该镜像标为syncing）。

### 如何重现此问题（How to reproduce it）

1. 遵循[tuna提供的帮助](https://mirrors.tuna.tsinghua.edu.cn/help/mozilla/)，将mozilla apt mirror添加到本地。
2. 运行`sudo aptitude update`。

### 操作系统（OS Version）

x86_64 Ubuntu 24.04.1 LTS

**Comment by shankerwangmiao** [comment]
感谢您反馈此问题，目前已经修复了，请等待同步完毕后即可恢复正常。
