### ISSUE TITLE
使用 poetry 无法从 pypi 镜像源安装包

### ISSUE THREAD

**Issue by akkuman** [tuna/issues#2083]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

poetry 设置镜像源为 https://pypi.tuna.tsinghua.edu.cn/simple/
安装会提示 403
经过调试，发现 poetry 安装包时会使用 requests 库，会带上 UA 头，这个 UA 头会被镜像源阻断

### 期望的现象（What you expected to happen）

正常安装

### 如何重现此问题（How to reproduce it）

```shell
curl -vvv -H 'User-Agent: python-requests/2.32.3' https://pypi.tuna.tsinghua.edu.cn/packages/d5/74/da832196702d0c56eb86b75bfa346db9238617e29b0b7ee3b8b4eccfe654/pydantic-2.10.2-py3-none-any.whl#sha256=cfb96e45951117c3024e6b67b25cdc33a3cb7b2fa62e239f7af1378358a1d99e
```

**Comment by akkuman** [comment]
![image](https://github.com/user-attachments/assets/930755eb-59bd-4ac2-a902-86e040e2a155)

**Comment by akkuman** [comment]
![image](https://github.com/user-attachments/assets/765b0f9f-ee30-4e5b-a498-7752aa5a6b92)

**Comment by akkuman** [comment]
上面两个图是带 `User-Agent: python-requests/2.32.3` 和不带的，可以看到带上这个 UA 头就会被阻断

**Comment by taoky** [comment]
根据 https://github.com/python-poetry/poetry/pull/8394 的信息，新版的 poetry 不应该继续使用 `python-requests/2.32.3`。请提供你的 poetry 版本。

**Comment by akkuman** [comment]
> 根据 [python-poetry/poetry#8394](https://github.com/python-poetry/poetry/pull/8394) 的信息，新版的 poetry 不应该继续使用 `python-requests/2.32.3`。请提供你的 poetry 版本。

Poetry (version 1.6.1)

**Comment by taoky** [comment]
> Poetry (version 1.6.1)

1.6.1 不包含上述 PR 的修复。目前最新版为 1.8.4 (<https://github.com/python-poetry/poetry/releases>)，请升级。

**Comment by akkuman** [comment]
好的

**Comment by shankerwangmiao** [comment]
此 issue 先关闭了，如有问题请继续留言。
