### ISSUE TITLE
AOSC OS/Anthon软件源指引已经过期

### ISSUE THREAD

**Issue by model-err** [tuna/issues#2085]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

发现AOSC OS/Anthon镜像源指引([这里](https://mirrors.tuna.tsinghua.edu.cn/help/anthon/))已经过期了。现在AOSC OS已经不再内置apt-gen-list，可使用oma mirror或oma mirrors换源，也可进行手动换源。

### 期望的现象（What you expected to happen）

标记为使用oma mirror换源，或手动换源。

### 如何重现此问题（How to reproduce it）

查看网站.

### 操作系统（OS Version）

AOSC OS

**Comment by eatradish** [comment]
事实有误，现在使用 `oma mirror/mirrors` 提供交互式界面或 cli 命令修改软件源，

**Comment by MingcongBai** [comment]
安同 OS 目前使用的方式是 `oma mirrors` 界面

**Comment by taoky** [comment]
请在 https://github.com/mirrorz-org/mirrorz-help 或 https://github.com/mirrorz-org/mirrorz-docs 仓库提交更正后的新切换镜像方式的 PR。
