### ISSUE TITLE
Is the homebrew-bottle mirror down?

### ISSUE THREAD

**Issue by aereobert** [tuna/issues#2089]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

curl http 403 when using homebrew bottle mirror, automatically failing back go ghcr.io

### 期望的现象（What you expected to happen）

e.g., https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/x264-r3108 should not be 403

### 如何重现此问题（How to reproduce it）

1. follow https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/
2. brew install x264
3. error

### 操作系统（OS Version）

macOS 15.1.1

**Comment by shankerwangmiao** [comment]
您好，请在浏览器中打开返回 403 的 URL，并提供显示的内容下方的标识符，以便我们进一步诊断。

**Comment by aereobert** [comment]
https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/x264-r3108 
 
 这个底下没有标识符。

这个URL是按照文档设置后安装x264之类的包的时候brew自己生成的

**Comment by shankerwangmiao** [comment]
请用浏览器访问： https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/x264-r3108.arm64_sequoia.bottle.tar.gz

**Comment by aereobert** [comment]
这个URL是没问题的，但是如果按照文档设置换源，然后运行brew install x264就会出问题。所有包似乎都会出这个url拼接问题

**Comment by shankerwangmiao** [comment]
您好，经检索镜像站日志确认，您所在的地址段 119.131.*.0/24 因存在大量持续反复下载镜像站上 Qt 安装器的行为，而被列入关注列表。您可以更换网络环境，或从其它来源获取您所需的资源。

**Comment by aereobert** [comment]
老哥删了你这条回复吧。。。我只是提个issue不值得被挂，下qt的也不是我。。。

**Comment by asdf2adsfad** [comment]
Hi 不好意思，我这里确实是不太想我的id被和这个ip的关系被搜索引擎检索到，我个人不希望在网上留痕。
是否方便编辑掉ip段或直接删掉整个comment？十分感谢

**Comment by shankerwangmiao** [comment]
> Hi 不好意思，我这里确实是不太想我的id被和这个ip的关系被搜索引擎检索到，我个人不希望在网上留痕。 是否方便编辑掉ip段或直接删掉整个comment？十分感谢

原本是只有精确到 /16 的 IP 地址，已经足够模糊了；已经按您的要求进一步隐去特定的 IP 地址。
