### ISSUE TITLE
新镜像请求: wine-staging for Fedora

### ISSUE THREAD

**Issue by sztsian** [tuna/issues#209]
#### 项目名称与简介(Project Intro.)
Wine-staging 存放了大量 Wine HQ 没有接受的patch。据Fedora用户称这个在国内访问很慢.
#### 上游地址与镜像方法(How to Mirror)
我查看了下，上游是一个yum repo，所以可以参考 [这篇文档](https://access.redhat.com/solutions/23016)

#### 其他信息(Other)
- 原始issue: https://github.com/FZUG/repo/issues/225
- https://github.com/wine-compholio/wine-staging/wiki/Installation#-fedora

**Comment by sztsian** [comment]
啊我没有权限添加label. cc @alick @Harry-Chen

**Comment by shankerwangmiao** [comment]
最近我们暂时发现了一个镜像 rpm 源的比较大的bug，在修复之前，我们可能不会再镜像新的了。

**Comment by huiyiqun** [comment]
准确说是 “通过 http 方式同步 rpm 源的问题”，如果有通过rsync同步的方式，则不受这个 bug 影响。

**Comment by sztsian** [comment]
根据讨论，我报了一个[feature](https://bugzilla.redhat.com/show_bug.cgi?id=1430662)

**Comment by huiyiqun** [comment]
bug 修好了，有时间会重新考虑这个。
