### ISSUE TITLE
Overleaf 无法双向导航以及没有github同步功能

### ISSUE THREAD

**Issue by zyma-Jasper** [tuna/issues#2094]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

发现目前TUNA的overleaf无法pdf和source code双向导航，以及能否考虑一下增加github的同步功能？

### 期望的现象（What you expected to happen）

希望可以实现pdf和source code双向导航，以及考虑一下增加github的同步功能

### 如何重现此问题（How to reproduce it）

tuna overleaf

**Comment by Harry-Chen** [comment]
此服务和 TUNA 没有直接关系，请向 its@tsinghua.edu.cn 反映问题。

此外，据我所知，社区版本的 Overleaf 并没有这些功能。
