### ISSUE TITLE
在更换为清华源或者北外源的时候直接报 403了

### ISSUE THREAD

**Issue by ghost** [tuna/issues#2096]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我是在Ubuntu 24.04 LTS容器上更换软件源（清华源和北外源）的时候，突然直接报403，况且我这边WiFi是好好的。我需要尽快修复此bug 谢谢

### 期望的现象（What you expected to happen）

![Screenshot_20241227_135910](https://github.com/user-attachments/assets/7d0beb96-ac82-49d1-8edf-3ac6f92292d4)
![Uploading Screenshot_20241227_135922.jpg…]()
以上为报错图片

### 如何重现此问题（How to reproduce it）

需要尽快修复此bug

### 操作系统（OS Version）

Ubuntu 24.04 LTS

### 其他需要说明的事项（Anything else we need to know）

如果我的IP被封的话，我需要请求解封IP 谢谢

**Comment by jielido2023** [comment]
补充一张北外源更换的时候
![Screenshot_20241227_135922](https://github.com/user-attachments/assets/5f38e4dc-a502-40c8-a9c9-53e90c950717)

**Comment by shankerwangmiao** [comment]
您好，相关情况已经邮件回复了。
