### ISSUE TITLE
获取更新的软件信息报错：签名不再生效，请求镜像地址403错误码

### ISSUE THREAD

**Issue by PiFrancis** [tuna/issues#2098]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

apt update命令获取更新的软件信息报错
<img width="972" alt="image" src="https://github.com/user-attachments/assets/3e6bea11-fe40-4e26-b77b-806fba03ea1b" />

### 期望的现象（What you expected to happen）

正常获取更新的软件信息

### 如何重现此问题（How to reproduce it）

目前获取更新的软件信息一直复现

### 操作系统（OS Version）

Debian11.11

**Comment by shankerwangmiao** [comment]
请用浏览器访问或用 curl 请求该 URL，并复制响应结尾处的识别代码，并以文字形式粘贴在邮件内，以便我们进一步诊断。

**Comment by PiFrancis** [comment]
> 请用浏览器访问或用 curl 请求该 URL，并复制响应结尾处的识别代码，并以文字形式粘贴在邮件内，以便我们进一步诊断。

code：0000005c 90207a8018684cbda3922d42c58ccbe5

**Comment by PiFrancis** [comment]
> 请用浏览器访问或用 curl 请求该 URL，并复制响应结尾处的识别代码，并以文字形式粘贴在邮件内，以便我们进一步诊断。

响应体中提示：我们检测到您所在的子网和/或所使用的客户端存在大量下载某些较大二进制文件的行为，为保证用户的正常使用，我们阻断了此类请求。

**Comment by shankerwangmiao** [comment]
该情况是本站因接收到过多的异常请求而采取的临时措施，目前已经恢复正常。
