### ISSUE TITLE
请镜像下 https:// packages.cloud.google.com/

### ISSUE THREAD

**Issue by Dieken** [tuna/issues#210]
#### 项目名称与简介(Project Intro.)

Google家的开源软件包，kubernetes在其中，mirrors.aliyun.com的 kubernetes 镜像是坏的。

#### 上游地址与镜像方法(How to Mirror)

https://packages.cloud.google.com/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知，应该不是特别大。

拜谢！

**Comment by Dieken** [comment]
能顶一下么。。。

**Comment by huiyiqun** [comment]
和 #129 重复
