### ISSUE TITLE
AOSP是不是不包含设备的Linux内核源码？

### ISSUE THREAD

**Issue by W-quan** [tuna/issues#211]
在kernel目录下只有goldfish。但是Google其他设备的呢？

**Comment by huiyiqun** [comment]
关于我们镜像的AOSP的repo列表，可以参照这个：https://android.googlesource.com/mirror/manifest/+/master/default.xml

凡是这个列表里有的，我们都作了镜像。

关于如何下载设备相关的代码，Google对此语焉不详，你可以参考lineage的文档，比如[这个](http://wiki.lineageos.org/klte_build.html#prepare-the-device-specific-code)。

关于这个问题我们没法帮到你更多，因为我们并没有专业的Android系统开发者，你可以去lineage的irc试一下。

**Comment by W-quan** [comment]
repo列表里存在：  <project name="kernel/msm" />
但是似乎你们没有做镜像。 kernel的仓库基本没有
下载只能用git下载。参考：[https://android.googlesource.com/](https://android.googlesource.com/) 里面的 `Generate Password`

无奈我的socks速度和流量都不够，只能请求你们帮帮忙了

**Comment by huiyiqun** [comment]
我觉得你可能没有理解我的意思。

我的意思是，设备相关的源代码默认不会放到你一开始同步的代码里，aosp有一套相关的工具用来配置设备相关的代码，即`breakfast` `lunch`等。

再简而言之，你下载的代码里没有设备相关的源代码，不是因为我们没有同步，而是因为你没有下载。
