### ISSUE TITLE
镜像bioconda请求

### ISSUE THREAD

**Issue by liutongj828** [tuna/issues#212]
#### 项目名称与简介(Project Intro.)
bioconda，是基于conda包管理器的一个集合大部分生物信息分析工具的源
#### 上游地址与镜像方法(How to Mirror)
https://github.com/bioconda/bioconda-recipes
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

感谢~

**Comment by huiyiqun** [comment]
我们这里没有conda用户，唯一对conda比较熟的同学最近忙着毕业，估计得等一段时间。

**Comment by huiyiqun** [comment]
统一汇总到 #112 讨论吧
