### ISSUE TITLE
机器学习数据集镜像

### ISSUE THREAD

**Issue by ppwwyyxx** [tuna/issues#213]
#### 项目名称与简介(Project Intro.)
常用机器学习数据集

#### 上游地址与镜像方法(How to Mirror)
多个上游，一次同步，终生有效

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
愿意给多少都行吧

我记得这是某天telegram上大家的脑洞。。突然想起来了

**Comment by huiyiqun** [comment]
Duplicated with #171
