### ISSUE TITLE
zabbix 官方源

### ISSUE THREAD

**Issue by wh211212** [tuna/issues#214]
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by gaoyichuan** [comment]
有rsync
`rsync://repo.zabbix.com/mirror`

**Comment by huiyiqun** [comment]
同步中

**Comment by huiyiqun** [comment]
上游的perms有点问题，导致同步下来的文件在我们的镜像站上没法访问，暂时没法解决。

**Comment by shankerwangmiao** [comment]
同步完毕，已经修复 perms
