### ISSUE TITLE
Homebrew bottles 包无法找到应自动跳转

### ISSUE THREAD

**Issue by douglarek** [tuna/issues#215]
如果一个 bottle 在上面 404 not found，会直接报失败，正确的方式是跳转到官方对应的地址去下载:

```
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "awscli"
Download failed: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

USTC 的处理方式是对的：

```
==> Upgrading awscli
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz
==> Downloading from https://homebrew.bintray.com/bottles/awscli-1.11.64.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring awscli-1.11.64.sierra.bottle.tar.gz
```

**Comment by douglarek** [comment]
使用 mirror 的目的不一定是要翻墙也可能是下载速度的需要

**Comment by xavieryao** [comment]
这个很有道理，USTC是怎么做的我很好奇……homebrew我们不是完全跟USTC一样吗…

回头我看看。

--
姚沛然 | Peiran Yao

Tel：+86 134-8852-3379
E-mail：peiran.yao@tuna.tsinghua.edu.cn

清华大学 TUNA 协会
Tsinghua University TUNA Association

北京市海淀区清华大学 100084
Tsinghua University, Haidian District, Beijing, 100084, P.R. China

On 2017年3月22日 +0800 AM10:54, Lingchao Xin <notifications@github.com>, wrote:

如果一个 bottle 在上面 404 not found，会直接报失败，正确的方式是跳转到官方对应的地址去下载:


==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "awscli"
Download failed: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.



USTC 的处理方式是对的：


==> Upgrading awscli
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/awscli-1.11.64.sierra.bottle.tar.gz
==> Downloading from https://homebrew.bintray.com/bottles/awscli-1.11.64.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring awscli-1.11.64.sierra.bottle.tar.gz

**Comment by douglarek** [comment]
@xavieryao 404 的时候做一个 redirect 即可吧

**Comment by shankerwangmiao** [comment]
done

**Comment by gaoyifan** [comment]
@xavieryao  USTC刚建立homebrew-bottles时，我曾被这个问题坑过。 由于同步有约1小时的延迟，如果用户只替换了homebrew-bottles但没有替换homebrew-core.git，就可能导致索引比bottles镜像新，进而导致404。解决方法正如 @douglarek 所说。

**Comment by shankerwangmiao** [comment]
赞
