### ISSUE TITLE
镜像资源访问404错误

### ISSUE THREAD

**Issue by stduolc** [tuna/issues#216]
这是访问链接:http://mirrors.tuna.tsinghua.edu.cn/virtualbox/rpm/el7/repodata/repomd.xml.asc: [Errno 14] HTTP Error 404 - Not Found
这是请求机器的ip信息：
{
  "ip": "119.147.158.52",
  "hostname": "No Hostname",
  "city": "Guangzhou",
  "region": "Guangdong",
  "country": "CN",
  "loc": "23.1167,113.2500",
  "org": "AS134763 CHINANET Guangdong province network"
}
备注：访问mirror.tuna.tsinghua.edu.cn的域名也是404错误。

**Comment by shankerwangmiao** [comment]
请设定

repo_gpgcheck=0

**Comment by huiyiqun** [comment]
当前 virtualbox 是使用 https://github.com/tuna/tunasync-scripts/blob/master/virtualbox.sh 这个脚本同步的，metadata是在本地用createrepo重新创建的，而不是直接下载上游metadata，再加上tuna本身通过https服务文件，所以认为gpg对于我们没什么意义。

所以这个签名文件在我们服务器上就是不存在的。

可以按如下方式设置repo：

```
[virtualbox]
name=Virtualbox Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/virtualbox/rpm/el$releasever/
gpgcheck=0
enabled=1
```

**Comment by stduolc** [comment]
为什么要关掉gpg。

**Comment by shankerwangmiao** [comment]
因为 “metadata是在本地用createrepo重新创建的，而不是直接下载上游metadata，再加上tuna本身通过https服务文件，所以认为gpg对于我们没什么意义。”

**Comment by bigeagle** [comment]
不是「gpg没有意义」，而是我们本身就是「中间人」，不可能进行 gpg 签名。
