### ISSUE TITLE
tensor flow 没有 windows 版？

### ISSUE THREAD

**Issue by 863zq** [tuna/issues#217]
#### 项目名称与简介(Project Intro.)
tensor flow windows 分支
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by xavieryao** [comment]
提了一个pr

https://github.com/tuna/tunasync-scripts/pull/9/<https://github.com/tuna/tunasync-scripts/pull/9/commits/6bf020916c7afd31ea6e07241e1c9654a265d40f>
________________________________

**Comment by huiyiqun** [comment]
Done

**Comment by 863zq** [comment]
为效率点赞！！！
