### ISSUE TITLE
openresty镜像

### ISSUE THREAD

**Issue by stduolc** [tuna/issues#218]
#### 项目名称与简介(Project Intro.)
OpenResty®
OpenResty® 是一个基于 Nginx 与 Lua 的高性能 Web 平台，其内部集成了大量精良的 Lua 库、第三方模块以及大多数的依赖项。用于方便地搭建能够处理超高并发、扩展性极高的动态 Web 应用、Web 服务和动态网关。

OpenResty® 通过汇聚各种设计精良的 Nginx 模块（主要由 OpenResty 团队自主开发），从而将 Nginx 有效地变成一个强大的通用 Web 应用平台。这样，Web 开发人员和系统工程师可以使用 Lua 脚本语言调动 Nginx 支持的各种 C 以及 Lua 模块，快速构造出足以胜任 10K 乃至 1000K 以上单机并发连接的高性能 Web 应用系统。

OpenResty® 的目标是让你的Web服务直接跑在 Nginx 服务内部，充分利用 Nginx 的非阻塞 I/O 模型，不仅仅对 HTTP 客户端请求,甚至于对远程后端诸如 MySQL、PostgreSQL、Memcached 以及 Redis 等都进行一致的高性能响应。

参考 组件 可以知道 OpenResty® 中包含了多少软件。

参考 上路 学习如何从最简单的 hello world 开始使用 OpenResty® 开发 HTTP 业务，或前往 下载 直接获取 OpenResty® 的源代码包开始体验。

#### 上游地址与镜像方法(How to Mirror)
https://openresty.org/cn/linux-packages.html 这里是镜像地址的描述链接。
整理如下：
CentOS用户：
```
[openresty]
name=Official OpenResty Repository
baseurl=https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/epel-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/pubkey.gpg
enabled=1
enabled_metadata=1
```
Redhat用户：
```
[openresty]
name=Official OpenResty Repository
baseurl=https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/epel-RELEASE-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/pubkey.gpg
enabled=1
enabled_metadata=1
```
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
文件都在这个目录下，可以通过https同步：

https://openresty.org/yum/openresty/openresty/

似乎没有rsync.

**Comment by shankerwangmiao** [comment]
已经电邮作者，看他愿不愿意开 rsync 了

**Comment by huiyiqun** [comment]
感觉走rsync不靠谱，这个目录里很多log，实际上openresty官方似乎只有rpm系的包，所以用http也足够了。

**Comment by ihipop** [comment]
作者已经专门整理了
https://openresty.org/package/
建议使用这个上游

**Comment by shankerwangmiao** [comment]
嗯，所以作者有意愿开 rsync 吗？要是有的话我们这边就直接同步了。

**Comment by shankerwangmiao** [comment]
镜像完毕：https://mirrors.tuna.tsinghua.edu.cn/openresty/
