### ISSUE TITLE
openSUSE的第三方软件源

### ISSUE THREAD

**Issue by ghost** [tuna/issues#22]
openSUSE的第三方软件源
此源中包含
1.特定项目在openSUSE上的比官方源新的二进制,如Apache、Mozilla、Wine、Java
2.openSUSE用户使用官方编译服务所编译的程序

上游地址
http://download.opensuse.org/repositories/

**Comment by sxyzy1016** [comment]
附议。

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1470#issuecomment-1193125000
