### ISSUE TITLE
openwrt镜像http协议访问

### ISSUE THREAD

**Issue by Lingdu0** [tuna/issues#220]
openwrt镜像没有http协议的。由于路由器性能较低一般不自带OpenSSL，所以同步很蛋疼。

**Comment by shankerwangmiao** [comment]
我们的镜像站是可以通过 http 协议访问的。

只不过为了安全性考虑，用浏览器的访问我们会强行跳转到 https，至于各种包管理器自动发出的 http 请求，我们是不会强行跳转的。
