### ISSUE TITLE
新镜像请求: Tiny Core Linux

### ISSUE THREAD

**Issue by zaoqi** [tuna/issues#221]
#### 项目名称与简介(Project Intro.)
Tiny Core Linux
#### 上游地址与镜像方法(How to Mirror)
http://www.tinycorelinux.net/
网易开源镜像站里有：
http://mirrors.163.com/tinycorelinux/

**Comment by shankerwangmiao** [comment]
hi 请提供详细的镜像方法。我在网站上浏览了一圈，并没有找到相关的指南。

**Comment by zaoqi** [comment]
网易开源镜像站里有：
http://mirrors.163.com/tinycorelinux/

**Comment by shankerwangmiao** [comment]
好吧，找到了 rsync://www.tinycorelinux.net/tc

**Comment by shankerwangmiao** [comment]
done
