### ISSUE TITLE
申请加入solus linux源

### ISSUE THREAD

**Issue by laizhiwei123** [tuna/issues#223]
项目名称与简介(Project Intro.)
项目:solus linux，是一个开源系统。官网是https://solus-project.com/home/。希望清华加入solus linux的源，让中国用户也能用上速度更快的源。
 上游地址与镜像方法(How to Mirror)
到官网申请，官网是https://solus-project.com/home
/
 其他信息(Other)
- 镜像大小(Mirror Size): 
976MB

**Comment by gaoyichuan** [comment]
很早以前就联系过了，不回话。现在提供镜像方式了吗？

**Comment by laizhiwei123** [comment]
我给他们发邮件也没回，可以去官网论坛看看

**Comment by huiyiqun** [comment]
和 #184 重复
