### ISSUE TITLE
新镜像请求：pytorch for anaconda

### ISSUE THREAD

**Issue by kylerwang** [tuna/issues#224]
#### 项目名称与简介(Project Intro.)
PyTorch is a deep learning framework that puts Python first.
官网是：http://pytorch.org/

#### 上游地址与镜像方法(How to Mirror)
https://anaconda.org/soumith/repo?type=conda&label=main
我对create mirror不太熟悉。。不太清楚怎么镜像。

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
关于 conda 三方源的讨论，请统一移到 #112
