### ISSUE TITLE
更新官网的anaconda安装描述

### ISSUE THREAD

**Issue by peterjc123** [tuna/issues#225]
请各位大佬更新一下[官网的安装帮助](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ )
目前的描述如下：
```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --set show_channel_urls yes
```
在[#112](https://github.com/tuna/issues/issues/112)中添加了msys2和conda-forge等第三方channel，因此可以将安装描述更新为：
```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
conda config --set show_channel_urls yes
```
此外，也可以加上Miniconda的介绍和下载链接
[https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/](https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/)

**Comment by huiyiqun** [comment]
https://github.com/tuna/mirror-web/blob/c208d78ed628413dbcc2e58a3e48bb90890cee73/_posts/help/1970-01-01-anaconda.md

稍后会更新到主页。
