### ISSUE TITLE
Lineage 源代码的镜像

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#226]
#### 项目名称与简介(Project Intro.)

当前最大的安卓发行版，脱胎于Cyanogenmod，是最容易的自己给自己的设备编译Android系统的方法之一。

#### 上游地址与镜像方法(How to Mirror)

https://github.com/LineageOS/mirror

跟AOSP原理完全相同，直接用aosp.sh，把上游改成这个repo里的文件即可。

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

未知，总共有不到2000个git仓库。

**Comment by huiyiqun** [comment]
同步中。

**Comment by huiyiqun** [comment]
同步好了

**Comment by j2u** [comment]
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
fatal: Couldn't find remote ref refs/heads/14.1
Unexpected end of command stream
fatal: Couldn't find remote ref refs/heads/14.1
Unexpected end of command stream
fatal: cannot obtain manifest https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git

**Comment by Yihuki** [comment]
lineageos的官方manifest.xml中的prebuilts都有clone-depth="1" ，tuna的源用https同步不了bundle， 如果直接把remote里的地址换了不把下面所有的clone-depth="1"  删掉，prebuilts就同步不了。 
所以应该在lineageos的帮助里写一下，应该删除prebuilts里的clone-depth="1"。
其他的直接用repo sync --no-clone-bundle同步都是没有问题的。

**Comment by huiyiqun** [comment]
@Yihuki 十分感谢

不过我不明白为什么clone-depth=1就必须得bundle 这两者似乎没什么关系？

**Comment by huiyiqun** [comment]
@j2u 你的这个错误是因为我之前在帮助里写错了 应该是

```
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b cm-14.1
```

而不是

```
repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b 14.1
```

十分抱歉，代码里已更新，等CI部署之后网页就会更新。

**Comment by Yihuki** [comment]
@huiyiqun 
因为clone-depth是由git仓库提供的选项，使用http同步就没有shadow clone这一说，也就会导致克隆失败。USTC关于aosp的wiki里已经说到了使用http同步会导致--depth选项的包同步失败。
所以ustc现在对aosp的提供还是有git仓库的.
https://lug.ustc.edu.cn/wiki/mirrors/help/aosp

> 不推荐使用 HTTP 协议同步，因为 HTTP 服务器不支持 repo sync 的 --depth 选项，可能导致部分仓库同步失败。

**Comment by huiyiqun** [comment]
@Yihuki 十分感谢 有时间我会考证一下 昨天找了一下 没有找到 git-http-backend 不支持 shadow clone 的出处。

**Comment by huiyiqun** [comment]
帮助还不完善 别关

**Comment by Ang486973** [comment]
yihuki说得对。

**Comment by shankerwangmiao** [comment]
目前关于之前出现的 shallow clone 失败的问题已经解决；目前没有更多反馈，暂时关闭。
