### ISSUE TITLE
old-releases.ubuntu.com

### ISSUE THREAD

**Issue by scateu** [tuna/issues#227]
#### 项目名称与简介(Project Intro.)

Ubuntu旧发行版的镜像

今天偶然间因为要测试一个Ubuntu 13.04才支持的功能，找了一圈，aliyun和ustc都有提供。

不过，这个使用率应该会比较低，各位评估一下剩余的空间再决定好了。

#### 上游地址与镜像方法(How to Mirror)

http://old-releases.ubuntu.com/

#### 其他信息(Other)

 - http://mirrors.ustc.edu.cn/help/ubuntu-old-releases.html
 - https://mirrors.aliyun.com/oldubuntu-releases/

- 镜像大小(Mirror Size): 
未知

**Comment by huiyiqun** [comment]
硬盘很吃紧了

**Comment by shankerwangmiao** [comment]
先不镜像这个了，请使用者自行升级到最接近的 lts

**Comment by canghaiwuhen** [comment]
可以来个从阿里云下载的脚本，ustc的old-release跪了，官方的rsync慢的不行，阿里云的没有rsync

**Comment by canghaiwuhen** [comment]
> 我们仍然建议使用者使用 lts 版本或当前仍在支持的版本，如果用户的 ubuntu 已经超出支持期限，可以直接升级至最近的 lts 版本，一般不会出太大问题。

老应用有glibc依赖，必须要老版本，新版本不兼容

**Comment by shankerwangmiao** [comment]
> > 我们仍然建议使用者使用 lts 版本或当前仍在支持的版本，如果用户的 ubuntu 已经超出支持期限，可以直接升级至最近的 lts 版本，一般不会出太大问题。
> 
> 老应用有glibc依赖，必须要老版本，新版本不兼容

如果您仍然需要维护失去支持的 ubuntu 系统，那么您可以从官方网站上自行通过 rsync 同步。但是您需要特别注意的是，失去支持的 ubuntu 系统不会再得到软件的更新，这意味着如果存在有安全漏洞的软件无法从官方得到升级。

**Comment by canghaiwuhen** [comment]
> > > 我们仍然建议使用者使用 lts 版本或当前仍在支持的版本，如果用户的 ubuntu 已经超出支持期限，可以直接升级至最近的 lts 版本，一般不会出太大问题。
> > 
> > 
> > 老应用有glibc依赖，必须要老版本，新版本不兼容
> 
> 如果您仍然需要维护失去支持的 ubuntu 系统，那么您可以从官方网站上自行通过 rsync 同步。但是您需要特别注意的是，失去支持的 ubuntu 系统不会再得到软件的更新，这意味着如果存在有安全漏洞的软件无法从官方得到升级。

这个问题是已知的，
主要是官方网站太慢了，wget下载镜像有没有参考脚本？

**Comment by shankerwangmiao** [comment]
您或许可以使用 https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py ，使用方法可以参考 https://github.com/tuna/tunasync-scripts/blob/master/gitlab-ce.sh。

**Comment by canghaiwuhen** [comment]
> 您或许可以使用 https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py ，使用方法可以参考 [https://github.com/tuna/tunasync-scripts/blob/master/gitlab-ce.sh。](https://github.com/tuna/tunasync-scripts/blob/master/gitlab-ce.sh%E3%80%82)

好的 非常感谢！
