### ISSUE TITLE
增加mysql镜像

### ISSUE THREAD

**Issue by kalsolio** [tuna/issues#23]
#### 上游地址与镜像方法(How to Mirror)
http://repo.mysql.com/yum/mysql-5.6-community/el/6/$basearch/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by bruceCzK** [comment]
+1

**Comment by bigeagle** [comment]
@NSBlink 我们把这个解决掉吧～

**Comment by bigeagle** [comment]
搞定！

**Comment by abcfy2** [comment]
mysql实际有仓库的https://dev.mysql.com/downloads/repo/

**Comment by youngcow** [comment]
不知道mysql有没有那种全的mirror方法，现在都是按照操作系统来的，不爽

**Comment by youngcow** [comment]
http://dev.mysql.com/downloads/how-to-mirror.html
可以mirror dev.mysql.com

**Comment by shankerwangmiao** [comment]
这很好
发自我的 iPhone

**Comment by bigeagle** [comment]
@youngcow 我看了一下 dev.mysql.com 里只有安装包没有 yum/apt 需要的 metadata

**Comment by bigeagle** [comment]
@youngcow dev.mysql.com 已经镜像在 https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/
