### ISSUE TITLE
是要收费的节奏吗？

### ISSUE THREAD

**Issue by cxwx** [tuna/issues#230]
https://mirrors.tuna.tsinghua.edu.cn/news/#april-fools-day
以后还能使用mirrors吗？

**Comment by huiyiqun** [comment]
注意日期…

**Comment by cxwx** [comment]
没具体日期。

**Comment by sztsian** [comment]
@cxwx 地址栏，"april-fools-day"

**Comment by Harry-Chen** [comment]
哦也可以参见公告的最后一句话😂
