### ISSUE TITLE
镜像 gitignore.io

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#231]
#### 项目名称与简介(Project Intro.)

.gitignore.io is a web service designed to help you create `.gitignore` files for your Git repositories. The site has a graphical and command line method of creating a `.gitignore` for your operating system, programming language, or IDE.

#### 上游地址与镜像方法(How to Mirror)

The web service is written in Swift3 using web framework [Vapor](https://vapor.github.io/). `.gitignore` templates are from [dvcs/gitignore](https://github.com/dvcs/gitignore). So the simplest way is to run the server locally and keep the git repositories up to date.

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
templates: 105.86 KiB
server: 10.58 MiB

**Comment by huiyiqun** [comment]
这个没必要吧。

一是都是小文件，直接从源下也没多慢
二是为这还得起个Web Server，既不知道有没有漏洞，也不知道性能会不会糟
