### ISSUE TITLE
nodesource的使用帮助需要更新

### ISSUE THREAD

**Issue by fengT-T** [tuna/issues#233]
* mongodb镜像好像很久都没有同步了,最近一次同步都是2016年的了
 * nodesourceNodesource 镜像使用帮助应该更新了,

> 把 https://deb.nodesource.com/node/ 替换为 https://mirrors.tuna.tsinghua.edu.cn/nodesource/deb/ 即可。

这句应该改成

> 把 https://deb.nodesource.com/node/ 替换为 https://mirrors.tuna.tsinghua.edu.cn/nodesource/deb_7.x即可。

官方的叫node_7.x,镜像同步之后叫deb_7.x,感觉怪怪的

**Comment by huiyiqun** [comment]
关于mongodb的同步状况，请参照：

https://mirrors.tuna.tsinghua.edu.cn/status/

另外两个问题请分开提两个issue，从我这里看 mongodb 的同步一直都在进行并且一直都是成功的。

**Comment by huiyiqun** [comment]
关于nodesource的镜像确实需要完善一下，现在缺少rpm的帮助，也没有根据版本生成repo文件的脚本。

**Comment by fengT-T** [comment]
昨天晚上没仔细看,内个两个仓库的目录情况一对比,
[tuna仓库](https://mirrors.tuna.tsinghua.edu.cn/mongodb/apt/debian/dists/jessie/mongodb-org/)
[mongodb官方仓库](https://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/)
瞬间就慌了,仔细一看虽然3.4稳定版本貌似一直是新的,但是别的文件夹都不科学啊

**Comment by huiyiqun** [comment]
mongodb没有给出rsync，所以是我们自己用[这个脚本](https://github.com/tuna/tunasync-scripts/blob/master/mongodb.sh)通过http下载的。

等有新的稳定版之后我们会加上新版本。

**Comment by fengT-T** [comment]
我曹,你们居然是写死的,感觉就这个网页,随便写个爬虫解析就好了,

**Comment by bigeagle** [comment]
那网页变了的话爬虫不是照样得重写…搞不好还把所有东西都毁了……

**Comment by bigeagle** [comment]
nodesource 的命名，因为官方是 deb.nodesource/node_xxx，rpm.nodesource/node_xxx，到我们这儿不管怎样都得变成 deb/xxxx, rpm/xxxx。还有历史原因，早期就没有版本号，鬼知道 node 版本号飞起来不要命的，我之前维护的时候原则上是只同步长期支持版本，两个月就抛弃的版本号就不同步了。

**Comment by fengT-T** [comment]
搜嘎,感觉你们也是蛮累的

**Comment by huiyiqun** [comment]
手里没有测试环境（

还是等人PR吧
