### ISSUE TITLE
mysql.he.net 上游失联

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/issues#234]
如题，备忘

**Comment by lj2007331** [comment]
mysql更新好几天同步失败了。https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQL-5.5/

**Comment by huiyiqun** [comment]
奇怪的是 我们的上游并不是 mysql.he.net ？

**Comment by huiyiqun** [comment]
https://github.com/tuna/tunasync-scripts/blob/master/mysql.sh#L15

找到了

**Comment by shankerwangmiao** [comment]
已经切换上游
