### ISSUE TITLE
OpenBSD 6.1缺少文件

### ISSUE THREAD

**Issue by yanghuxiao** [tuna/issues#235]
官网6.1是这些https://mirrors.evowise.com/pub/OpenBSD/6.1/packages/

我们这个镜像怎么只有amd64和i386，能否补全？

**Comment by huiyiqun** [comment]
说一下你需要什么架构以及为什么需要这个架构？

2017-05-08 8:14 GMT+08:00 Tianya <notifications@github.com>:

**Comment by yanghuxiao** [comment]
arm

**Comment by huiyiqun** [comment]
已经添加了arm，正在同步中。

**Comment by yanghuxiao** [comment]
tks.
