### ISSUE TITLE
anaconda 仓库同步脚本太慢

### ISSUE THREAD

**Issue by niheaven** [tuna/issues#236]
conda 的 mirror 显示正在同步中，日期为 3 月 29 日。这个是什么问题？

**Comment by huiyiqun** [comment]
看了下日志 并没有什么问题 看上去像是一个文件一个文件地下 速度太慢 至今没有下载完

有时间改进一下anaconda的同步性能

**Comment by niheaven** [comment]
谢谢！anaconda 的主镜像在国内的同步速度和稳定性实在太差，如果没有 TUNA 的镜像，很多网络条件下根本不能用……

**Comment by bigeagle** [comment]
只能说…… 大家用主镜像有多慢，我们同步就有多慢 >_<

**Comment by niheaven** [comment]
嗯~基本放弃从主镜像拉包了，除非使用代理，不然不停丢包出错……等你们吧~~~

**Comment by huiyiqun** [comment]
我开始怀疑 无论这个同步脚本有多慢 应该不至于要同步 20多天还没有结束吧 而上一次同步似乎四天就结束了

**Comment by liruikaiyao** [comment]
这个应该是脚本有问题吧，我从国外源拉，慢是慢，但是还是可以完成的，不可能三个月都完不成一次同步的。

**Comment by bigeagle** [comment]
还真是慢… 中间断过几次，一直就成功不了。
今天改走科学线路同步了，应该很快能成功。

**Comment by bigeagle** [comment]
Done
