### ISSUE TITLE
增加CentOS altarch仓库

### ISSUE THREAD

**Issue by mingfengwuye** [tuna/issues#237]
#### 上游地址与镜像方法(How to Mirror)
CentOS for ppc64le

OS：http://mirror.centos.org/altarch/7.3.1611/isos/ppc64le/
Package:
http://mirror.centos.org/altarch/7/cr/ppc64le/repodata/
http://mirror.centos.org/altarch/7.3.1611/cr/ppc64le/repodata/
http://mirror.centos.org/altarch/7.3.1611/os/ppc64le/Packages/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
？什么镜像？

**Comment by shankerwangmiao** [comment]
centos

**Comment by huiyiqun** [comment]
同步中

**Comment by mingfengwuye** [comment]
Many thanks

**Comment by stduolc** [comment]
这个是32bit的centos源.我只有在一些虚拟机环境有用过.
