### ISSUE TITLE
请求添加archive.raspberrypi.org源

### ISSUE THREAD

**Issue by KevinMX** [tuna/issues#240]
项目名称与简介(Project Intro.)
树莓派archive.raspberry.org镜像源，补充了少量树莓派基金会而不是Raspbian开发者提供的软件。目前国内貌似只有ustc有他的mirror。（北方小水管表示慢的不行xD）
上游地址与镜像方法(How to Mirror)
http://archive.raspberrypi.org/
Linux小白一个，只能找到这么多了。。
其他信息(Other)
- 镜像大小(Mirror Size): 不知:lol
//这是ustc的。。http://mirrors.ustc.edu.cn/archive.raspberrypi.org/
//ustc wiki:   https://lug.ustc.edu.cn/wiki/mirrors/help/archive.raspberrypi.org

**Comment by alex23m** [comment]
KevinMX, Hi, I want to contact you, to know how to change Secro.img to unlock Meizu ? how can I contact you?

**Comment by KevinMX** [comment]
@huiyiqun
人呢?xD
上面那个comment无视……找我的……

**Comment by huiyiqun** [comment]
似乎没有找到开放的 rsync 服务，我找 USTC 的同学问一下。

**Comment by shankerwangmiao** [comment]
貌似是照着 http 扒的，是时候祭出大鹰的 apt-mirror 了

**Comment by huiyiqun** [comment]
lftp的 要不要上？

我其实想弄一个lftp provider和git provider

2017-05-30 22:31 GMT+08:00 Miao Wang <notifications@github.com>:

**Comment by KevinMX** [comment]
所以现在进展怎么样？
最近比较忙。。。。

**Comment by KevinMX** [comment]
刚刚从USTC server status里面找到的。。mirror size 约28.57GB

**Comment by shankerwangmiao** [comment]
暂时搁置，因为硬盘空间比较紧张

**Comment by KevinMX** [comment]
现在依旧不行吗？莫不成还是没有硬盘空间？xD

**Comment by shankerwangmiao** [comment]
见 https://github.com/tuna/issues/issues/249

**Comment by KevinMX** [comment]
现在可用了吗？这个是吗？https://mirrors.tuna.tsinghua.edu.cn/raspberrypi/
如果可以的话能否添加一下help页面，谢谢！

**Comment by shankerwangmiao** [comment]
这个镜像的上游是 http://archive.raspberrypi.org/debian/

你如果愿意的话，欢迎给我们贡献 help 页面，多谢！方法见：https://github.com/tuna/mirror-web#贡献文档
