### ISSUE TITLE
添加clojure语言库的repo

### ISSUE THREAD

**Issue by linpengcheng** [tuna/issues#241]
#### 项目名称与简介(Project Intro.)
clojure语言库的repo
#### 上游地址与镜像方法(How to Mirror)
https://clojars.org/
https://github.com/clojars/clojars-web/wiki/Data
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by huiyiqun** [comment]
https://github.com/clojars/clojars-web/wiki/Data#rsync-the-whole-repository

看上去可以通过rsync同步，不过不知道有多大。可以同步一下试一下。

**Comment by huiyiqun** [comment]
完成了 测试一下

最后能帮我们pr一个帮助
