### ISSUE TITLE
科学的科学上网方案

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#243]
之前使用 VPN 需要动路由表，并且不算稳定，并不科学。

感觉可以使用 shadowsocks + polipo 搞个 HTTP 代理，镜像时传个 `http_proxy`, `https_proxy`, `all_proxy` 环境变量就好了。

等我搞完论文。

**Comment by scateu** [comment]
我为了给apple tv用代理，在Raspberry Pi上已经polipo+shadowsocks两个星期了，十分稳定。

**Comment by scateu** [comment]
以及平时在桌面上已经用了近一年的proxychains，也十分稳定

**Comment by scateu** [comment]
求用法... 以及Dockerfile在哪里，想学习一下:D

On Wed, May 31, 2017, at 15:07, bigeagle wrote:
> https://hub.docker.com/r/tunathu/shadowsocks/


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/tuna/issues/issues/243#issuecomment-305104017
