### ISSUE TITLE
Request for Project LLVM mirrors

### ISSUE THREAD

**Issue by jeasinema** [tuna/issues#244]
#### 项目名称与简介(Project Intro.)
`llvm` 项目的软件源码, 包括 `llvm`, `clang`, `lldb`, `libcxx` 等
#### 上游地址与镜像方法(How to Mirror)
- llvm
http://llvm.org/git/llvm  
- clang
http://llvm.org/git/clang
- lldb
http://llvm.org/git/lldb
- libcxx
http://llvm.org/git/libcxx

除上述源码外, 还希望能提供上述软件 release code 的直接下载, 以及常见平台下的 pre-built binary 下载, 具体可参见: http://releases.llvm.org/download.html

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知
- 潜在的问题
据说 llvm 项目网站日常崩?

**Comment by Harry-Chen** [comment]
Processing

**Comment by Harry-Chen** [comment]
Git repo 肯定没问题，但是二进制我们可能无法分发，因为上游没有提供 git/rsync 等渠道

**Comment by jeasinema** [comment]
@Harry-Chen 话说你是打算从 `github` 的 [llvm-mirror](https://github.com/llvm-mirror) 同步吗?
