### ISSUE TITLE
使用anaconda镜像出现MD5MismatchError

### ISSUE THREAD

**Issue by Luxios** [tuna/issues#246]
在使用conda安装r-essential时发生以下错误

CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/r-hms-0.3-r3.3.2_0.tar.bz2'.
  download saved to: /usr/miniconda2/pkgs/r-hms-0.3-r3.3.2_0.tar.bz2
  expected md5 sum: 114abcbf8aa16db583a9fcd81dbdf54b
  actual md5 sum: d41d8cd98f00b204e9800998ecf8427e

**Comment by huiyiqun** [comment]
应该是因为 https://github.com/tuna/issues/issues/236 和 https://github.com/tuna/issues/issues/232 同时作用导致的。

我看了一下 两台服务器上的文件确实不一致，你尝试用 https://github.com/tuna/issues/issues/232 里的workaround 能否避开这个问题，我周末找时间改进一下 anaconda 的同步脚步。

**Comment by bigeagle** [comment]
@huiyiqun 改的时候顺便看看能不能把 #243 一块儿弄了

**Comment by huiyiqun** [comment]
OK 周末的时候看一下。

**Comment by panlei7** [comment]
@huiyiqun 

CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/ipyparallel-6.0.2-py36_0.tar.bz2'.
  download saved to: /home/pl/soft/anaconda3/pkgs/ipyparallel-6.0.2-py36_0.tar.bz2
  expected md5 sum: ab85c13b9a222b5612fcd27abbaa5638
  actual md5 sum: d41d8cd98f00b204e9800998ecf8427e

**Comment by panlei7** [comment]
5分钟之后，竟然又好了...
