### ISSUE TITLE
node_8.x nodesource deb 镜像

### ISSUE THREAD

**Issue by Dreamacro** [tuna/issues#247]
#### 项目名称与简介(Project Intro.)
    这两天 Node 更新到 8.x 了, 十月份要加入 LTS
#### 上游地址与镜像方法(How to Mirror)
    `https://deb.nodesource.com/node_8.x/` => `https://mirrors.tuna.tsinghua.edu.cn/nodesource/deb_8.x/`

**Comment by huiyiqun** [comment]
同步中
