### ISSUE TITLE
暂时停止接受新的镜像请求 / Temporarily not accepting new mirror requests due to limited storage

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/issues#249]
由于服务集群之一的机器的存储空间已经饱和，暂时停止接收新的镜像请求，直到下一步扩容为止。

**Comment by Showfom** [comment]
8月12号之后可以恢复提交新的镜像吗？

**Comment by shankerwangmiao** [comment]
你可以随时提交新的镜像请求

**Comment by dotkrnl** [comment]
@Showfom 存储空间未能在这次割接中解决，镜像请求的提交随时都可进行，但关于镜像请求的接受，请关注这一 issue 的后续跟进。

**Comment by icymind** [comment]
扩容有进度安排吗? [新闻公告](https://mirrors.tuna.tsinghua.edu.cn/news)并没有具体的消息

**Comment by shankerwangmiao** [comment]
暂无时间表，预计年底之前可以完成

**Comment by dotkrnl** [comment]
Since no slots available, we are going to replace all disks in servers in order to add storage in the following weeks.
