### ISSUE TITLE
Arch Linux Archive

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#25]
Arch Linux Archive 也就是以前的 Arch Rollback Machine, 每天对 Arch Linux 的镜像做一次快照，方便未来降级。

**建立方法**
-  [这个脚本](https://github.com/seblu/archivetools)
- ZFS/btrfs snapshot

**Comment by huiyiqun** [comment]
snapshot不经济吧?感觉对象存储+索引表要经济一些?

**Comment by bigeagle** [comment]
官方给的脚本是基于硬链接的

**Comment by blahgeek** [comment]
好像一般是用来方便升级的…三年没动的机器得一个月一个月的来升级…（Arch大法好

**Comment by ppwwyyxx** [comment]
@blahgeek 降级也很常用啊！．．我前几天刚降了cups-filters因为新版有bug..

**Comment by happyaron** [comment]
https://arch-archive.tuna.tsinghua.edu.cn 有了，可以关了吧？

**Comment by huiyiqun** [comment]
又一个跨年的issue被拔掉了，赞。

现在是一周一次吧？

**Comment by huiyiqun** [comment]
还缺个文档 有人可以写一下吗？

**Comment by bigeagle** [comment]
我最近比较爆炸，如果我忙完了还没人写的话就我来吧～

**Comment by huiyiqun** [comment]
写好了

@bigeagle 更新一下吧

**Comment by bigeagle** [comment]
@huiyiqun push 一下呀……

**Comment by huiyiqun** [comment]
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-archlinux.md 在这了呀？

**Comment by bigeagle** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/archlinux/ 好了～
