### ISSUE TITLE
Linaro社区及96Boards/ARM工具链等镜像

### ISSUE THREAD

**Issue by scateu** [tuna/issues#251]
#### 项目名称与简介(Project Intro.)

今天Debian 9 Release Party活动中 Haitao Zhang 提到的Linaro社区及96Boards的相关镜像内容。

#### 上游地址与镜像方法(How to Mirror)

请 Haitao Zhang 补充 :D 

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
求详情
