### ISSUE TITLE
安装 [ pbr:       3.0.1-py27_0  ] 时 MD5MismatchError

### ISSUE THREAD

**Issue by wzdark** [tuna/issues#252]
我使用conda install pbr命令安装pbr包：
pbr:       3.0.1-py27_0  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

报错：
CondaError: MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64/pbr-3.0.1-py27_0.tar.bz2'.
  download saved to: /Users/wangzhuo/miniconda2/pkgs/pbr-3.0.1-py27_0.tar.bz2
  expected md5 sum: f670548b66076ffc5747356a981986c1
  actual md5 sum: d41d8cd98f00b204e9800998ecf8427e

是否是版本更新了 而MD5没有？请管理员解决一下

**Comment by shankerwangmiao** [comment]
我们在服务器上已经针对 MD5 值进行了检查，确为 f670548b66076ffc5747356a981986c1，请重试。

**Comment by huiyiqun** [comment]
应该是因为两台服务器的同步时间不一致

2017-08-10 0:27 GMT+08:00 Miao Wang <notifications@github.com>:
