### ISSUE TITLE
增加 kubernetes 镜像

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#254]
#### 项目名称与简介(Project Intro.)

Kubernetes is an open-source platform for automating deployment, scaling, and operations of application containers across clusters of hosts, providing container-centric infrastructure.

#### 上游地址与镜像方法(How to Mirror)

1. 镜像 yum 源，https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml

2. 镜像 binary。和 TensorFlow 类似，binary 在 storage.googleapis.com 上，可以解析 https://storage.googleapis.com/kubernetes-release/ 这个 xml。

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
 Unknown

由于一台服务器的存储空间已经饱和(#249 )， 可能不会立即镜像。

**Comment by bigeagle** [comment]
duplicated with #129
