### ISSUE TITLE
loongson 中文utf8乱码

### ISSUE THREAD

**Issue by lshw** [tuna/issues#255]
loongson 的目录和文件都是utf8的， 而服务器默认是GBK的

nginx:

server {
  location /loongson/ {
	        charset  utf-8;
	        }
...
}

**Comment by shankerwangmiao** [comment]
已经处理。经查，服务器上存储文件名的编码确为 UTF-8，该问题是部分浏览器自动识别编码出错导致的，已经通过添加 http 头修复。感谢反馈。
