### ISSUE TITLE
Bioconductor源不能用了

### ISSUE THREAD

**Issue by JackieMium** [tuna/issues#256]
我从多天前就发现R/Bioconductor源不能用，当是以为是网络故障，暂时切换到USTC的源去了，这两天换回TUNA发现还不能用，决定过来反馈一下：

![image](https://user-images.githubusercontent.com/12944832/28417117-5d38ff76-6d89-11e7-99d2-db36ec2ec2fa.png)

我的网络是畅通的，用USTC源也没有问题。
系统 Debian sid 64位，R 版本 3.4.1 (2017-06-30) -- "Single Candle"，Bioconductor 版本 3.5 (BiocInstaller 1.26.0)。

**Comment by huiyiqun** [comment]
TUNA 的文件目录和 USTC 的不太一样 正确的目录应该是
https://mirrors.tuna.tsinghua.edu.cn/bioconductor/bioc 并且只同步了 3.5 版本

不过从你的截图来看 似乎没办法改成我们现在的目录 我们找时间改一下同步脚本吧

在 2017年7月20日 下午8:27，JackieMe <notifications@github.com>写道：

**Comment by JackieMium** [comment]
@huiyiqun 我这是按照你们的HELP做的，那要么就是你们的帮助页面需要改动咯。

**Comment by huiyiqun** [comment]
这个 help 应该是用户 PR 的

实际上我们内部并没有 Bioconductor 或 R 的用户，所以 help 只能是靠 PR 了

**Comment by JackieMium** [comment]
@huiyiqun 尴尬了，我其实也不知道怎么写:(  
我只会用....

**Comment by huiyiqun** [comment]
应该已经好了 试一下？

**Comment by JackieMium** [comment]
@huiyiqun 可以了！ :100:
