### ISSUE TITLE
申请openshift tar包镜像

### ISSUE THREAD

**Issue by wpengcheng** [tuna/issues#258]
#### 项目名称与简介(Project Intro.)
Openshift：RedHat开源的PAAS平台
#### 上游地址与镜像方法(How to Mirror)
https://github.com/openshift/origin/releases
#### 其他信息(Other)
- 镜像大小(Mirror Size): 100多M

**Comment by shankerwangmiao** [comment]
貌似没有官方的发行渠道，而是通过 github 的 releases 发布的 tar 包。对于这种情况，由于无法很好地归类整理这些 tar 包，且官方没有成型地提供标准的镜像目录结构，因此我们暂时无法镜像。
