### ISSUE TITLE
adobe fonts repo douldn't be clone from *.git

### ISSUE THREAD

**Issue by c0001** [tuna/issues#261]
Adobe fonts repo couldn't be clone from *.git 
**********
Example:
git clone https://mirrors4.tuna.tsinghua.edu.cn/adobe-fonts/source-han-sans.git
**********
And I want to use this repo   , hope for your suggestion for how to clone it or download it manually.

**Comment by shankerwangmiao** [comment]
Because the large size of this repo, it could take long time after the message `cloning into source-han-sans....`. Please wait patiently.

**Comment by c0001** [comment]
Thanks for your reponding, I understand what your meaning.
