### ISSUE TITLE
git clone时出现了一个错误，这是lineage的TUNA源的问题？

### ISSUE THREAD

**Issue by Ang486973** [tuna/issues#262]
git clone时出现了一个错误，这是lineage的TUNA源的问题？
以下是终端信息：
————————————
Fetching project platform/external/javasqlite
Fetching project LineageOS/cm_platform_sdk
error: inflate: data stream error (invalid distance too far back)
fatal: 包中有错误的对象位于 4110385：解压缩返回 -3
error: Unable to find 2b816b58b9e16e3a4ebf11d664b91409b55db869 under https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/cm_platform_sdk
Cannot obtain needed blob 2b816b58b9e16e3a4ebf11d664b91409b55db869
while processing commit 1319a28536e8ecb30661422c82197a66ed3604c5.
error: fetch failed.
来自 https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/cm_platform_sdk
 * [新分支]          cm-14.1    -> github/cm-14.1
Fetching project platform/prebuilts/clang/linux-x86/host/3.6
remote: Counting objects: 845, done.        00 KiB/s   
error: inflate: data stream error (invalid code lengths set)
fatal: 包中有错误的对象位于 59262648：解压缩返回 -3
error: Unable to find 359aafc532a0222a847f8624c3b2c635aef49462 under https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_libcore
Cannot obtain needed object 359aafc532a0222a847f8624c3b2c635aef49462
while processing commit 30ff118538833844c0d72d1dc50c69c98b510861.
error: fetch failed.
来自 https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_packages_apps_Trebuchet
 * [新分支]          cm-14.1    -> github/cm-14.1
——————————
我百度了一下，除了使用github源以外没有找到解决的办法。请问各位大佬，这要如何解决？

**Comment by huiyiqun** [comment]
无法复现，你的日志里面提到的三个 repo：

1.
https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/cm_platform_sdk
2.
https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_libcore
3.
https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_packages_apps_Trebuchet

在我这里都可以正常地使用 git 下载，可以基本排除是镜像站方面的原因，建议检查网络。

2017-08-15 15:32 GMT+08:00 蓝颜 <notifications@github.com>:

**Comment by Ang486973** [comment]
已解决

**Comment by sunnyhare** [comment]
@Ang486973 你这个问题怎么解决的呢？我也遇到你这样的问题。
不过是另外几个projects，谢谢！
