### ISSUE TITLE
netbsd 的二進制包未收入已有的 netbsd 鏡像中

### ISSUE THREAD

**Issue by xieyuheng** [tuna/issues#266]
這個是 http 的主源
  :: http://ftp.netbsd.org/pub/
在鏡像它其下的 NetBSD/ 子目錄的同時
還要鏡像其下的 pkgsrc/ 子目錄
後者是 netbsd 用戶所打包好的二進制程序包
只有同時鏡像這兩個目錄 netbsd 才能在國內易用
相關的文檔可以看這裏
  :: http://www.netbsd.org/docs/pkgsrc/using.html#building-packages-from-source

另外
這裏官方網站上所收錄的鏡像列表 :: https://www.netbsd.org/mirrors
關於建立鏡像的常見問題 :: https://www.netbsd.org/docs/mirror.html
這個是 netbsd 鏡像維護者的郵箱 :: mirrors@NetBSD.org
希望 tuna 在做好完備的鏡像之後能夠聯繫其主頁的維護者
使得 tuna 的鏡像能夠被收錄到主頁的鏡像列表中

感謝清華爲這些軟件做鏡像

**Comment by shankerwangmiao** [comment]
您好，我浏览了选登在 netbsd 官方网站上的一些其他镜像网站，并无你所说的  pkgsrc 目录，如：

http://mirror.isoc.org.il/pub/netbsd/
http://mirror.planetunix.net/pub/NetBSD/

不知应该如何处理此镜像

**Comment by xieyuheng** [comment]
有的鏡像有 pkgsrc 比如 ::
http://ftp.fr.netbsd.org/pub/pkgsrc/
ftp://ftp.ee.netbsd.org/pub/pkgsrc/

沒有 pkgsrc 的
有可能是這些鏡像者選擇不收錄 pkgsrc
也可能是疏忽

**Comment by xieyuheng** [comment]
你提到的不知該如何處理
可能是發現 /pkgsrc 不在 /NetBSD 這個路徑之內

就像你們的源現在有 https://mirrors.tuna.tsinghua.edu.cn/archlinux/
同時也有 https://aur.tuna.tsinghua.edu.cn/ 一樣

可以這樣處理 netbsd 的鏡像 ::
https://mirrors.tuna.tsinghua.edu.cn/NetBSD/ 
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc/

**Comment by Harry-Chen** [comment]
今天 @woodelf 也提到了这个问题
@shankerwangmiao 再跟进一下？

**Comment by shankerwangmiao** [comment]
唔，所以现在的 NetBSD 是源代码？

我简单了解了一下，pkgsrc 看起来像是包管理器的名字，是不是和 apt 是类似的东西？如果是的话，镜像下来取名叫做 pkgsrc 是不是不太恰当？就好比 ubuntu 和 debian 都是用 apt 作包管理，把 debian 的镜像下来取名作 apt 貌似不太对劲。

**Comment by xieyuheng** [comment]
照着官方的路徑結構做就好

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/pkgsrc 已经同步完毕。

**Comment by shankerwangmiao** [comment]
因存储空间已耗尽，我们已经移除该镜像。
