### ISSUE TITLE
Bioconda的Nano源缺失noarch文件夹及相关 

### ISSUE THREAD

**Issue by highwindmx** [tuna/issues#267]
Missing noarch folder in nanomirror of Bioconda
访问请求时出现以下故障，希望管理员帮忙更正。

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

**Comment by shankerwangmiao** [comment]
@huiyiqun  你帮忙看下？

**Comment by bigeagle** [comment]
应该已经解决了～
