### ISSUE TITLE
DNS bug

### ISSUE THREAD

**Issue by yeshujian** [tuna/issues#268]
各位好!
反馈一个bug:
在登陆QQ企业邮箱的时候用101.6.6.6 报timeout, 
切回电信DNS没异常.

**Comment by dotkrnl** [comment]
101.6.6.6 进行的是递归解析，这一情况很可能是由 QQ 企业邮箱方面故障导致的。
但我们将会进一步了解情况，烦请提供 timeout 相关的域名。

**Comment by yeshujian** [comment]
@dotkrnl exmail.qq.com 这次尝试为 ERR_CONNECTION_RESET

**Comment by gaoyichuan** [comment]
烦请提供一下 101.6.6.6 与电信 DNS 各自对于 exmail.qq.com 的解析结果
可以使用 `dig exmail.qq.com @101.6.6.6` 获取

**Comment by yeshujian** [comment]
user@ubuntu:~$ dig @61.139.2.69 exmail.qq.com --LOCAL DNS

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @61.139.2.69 exmail.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15482
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;exmail.qq.com.			IN	A

;; ANSWER SECTION:
exmail.qq.com.		277	IN	A	183.3.226.105

;; Query time: 3 msec
;; SERVER: 61.139.2.69#53(61.139.2.69)
;; WHEN: Wed Aug 30 16:08:10 CST 2017
;; MSG SIZE  rcvd: 58

user@ubuntu:~$ dig @101.6.6.6 exmail.qq.com --TUNA DNS

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @101.6.6.6 exmail.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15304
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;exmail.qq.com.			IN	A

;; ANSWER SECTION:
exmail.qq.com.		430	IN	A	115.25.209.74
exmail.qq.com.		430	IN	A	115.25.209.124

;; AUTHORITY SECTION:
exmail.qq.com.		86230	IN	NS	ns-cmn1.qq.com.
exmail.qq.com.		86230	IN	NS	ns-tel1.qq.com.
exmail.qq.com.		86230	IN	NS	ns-cnc1.qq.com.
exmail.qq.com.		86230	IN	NS	ns-os1.qq.com.

;; Query time: 57 msec
;; SERVER: 101.6.6.6#53(101.6.6.6)
;; WHEN: Wed Aug 30 16:08:34 CST 2017
;; MSG SIZE  rcvd: 161

**Comment by weez15** [comment]
dig exmail.qq.com @101.6.6.6

; <<>> DiG 9.11.2 <<>> baidu.com @101.6.6.6
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11067
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 5, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 795f33d5bfdc12c86874af6259a673f2468570f04a348b15 (good)
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              535     IN      A       220.181.57.217
baidu.com.              535     IN      A       111.13.101.208
baidu.com.              535     IN      A       123.125.114.144

;; AUTHORITY SECTION:
baidu.com.              166766  IN      NS      ns4.baidu.com.
baidu.com.              166766  IN      NS      ns3.baidu.com.
baidu.com.              166766  IN      NS      dns.baidu.com.
baidu.com.              166766  IN      NS      ns7.baidu.com.
baidu.com.              166766  IN      NS      ns2.baidu.com.

;; Query time: 347 msec
;; SERVER: 101.6.6.6#53(101.6.6.6)
;; WHEN: Wed Aug 30 08:14:43 UTC 2017
;; MSG SIZE  rcvd: 204

dig exmail.qq.com @8.8.8.8

; <<>> DiG 9.11.2 <<>> exmail.qq.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42354
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;exmail.qq.com.                 IN      A

;; ANSWER SECTION:
exmail.qq.com.          3599    IN      CNAME   exmail.wechatos.net.
exmail.wechatos.net.    599     IN      A       103.7.30.46

;; Query time: 300 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Aug 30 08:14:08 UTC 2017
;; MSG SIZE  rcvd: 91

**Comment by shankerwangmiao** [comment]
目前我可以复现解析结果，经查，返回的地址系腾讯在教育网内的 CDN。这个现象是我们的解析服务器在教育网内所致。由于我们服务器暂时不支持转发 EDNS-CLIENT-SUBNET，因此暂时不能做到向权威 NS 服务器发送用户的地址的功能。

至于您的网络环境到达该 CDN 节点存在障碍，建议您联系您的网络管理员或服务提供商，以便排查原因。

**Comment by yeshujian** [comment]
好的 多谢!

**Comment by bigeagle** [comment]
2013年的时候，当时我们一个小团队用腾讯企业邮，在教育网死活不 work，我发了好几份bug report石沉大海。现在是 2017 年。
