### ISSUE TITLE
新機器上的 pretty listing 可否採用等寬字體和更爲簡單的配色

### ISSUE THREAD

**Issue by KireinaHoro** [tuna/issues#270]
現在新機器上面部署的 pretty listing 是用的是非等寬字體，手動從目錄裏面下載文件的時候看起來十分疲勞而且容易下載錯文件（看錯版本號之類）
希望能將字體樣式調整喂使用等寬並簡化顏色（現有的藍色在翻找文件的時候很容易頭暈）

**Comment by shankerwangmiao** [comment]
已修理，链接的颜色问题再议。。。。。
