### ISSUE TITLE
添加Ambari仓库

### ISSUE THREAD

**Issue by romewing** [tuna/issues#272]
#### 项目名称与简介(Project Intro.)
Ambari
#### 上游地址与镜像方法(How to Mirror)
https://docs.hortonworks.com/HDPDocuments/Ambari-2.5.2.0/bk_ambari-installation/content/ch_using-local-repos.html
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
您好，Ambari 系 Apahce 基金会之项目，已经在 https://mirrors.tuna.tsinghua.edu.cn/apache/ambari/ 处镜像。

**Comment by romewing** [comment]
@shankerwangmiao 我的意思是能否以仓库的形式提供？

**Comment by shankerwangmiao** [comment]
您是指这些 tar 包吗？

https://docs.hortonworks.com/HDPDocuments/Ambari-2.4.1.0/bk_ambari-installation/content/ambari_repositories.html

**Comment by romewing** [comment]
@shankerwangmiao 恩，就是搭建一个HDP的本地仓库

**Comment by shankerwangmiao** [comment]
但问题是，上述文档中的 tar 包的名称和路径可能发生变化（如版本号升级）且没有可靠方法列举所有的 tar 包

**Comment by romewing** [comment]
@shankerwangmiao 可以手动搭建么？

**Comment by shankerwangmiao** [comment]
这个问题是这样，因为目前一个是维护团队对该软件不熟悉，二是没有标准方法镜像该软件的发型包；我们需要在一定程度上保证镜像的软件的可用性。对于这种情况我们一般是不镜像的，除非有可靠的方法进行镜像。
