### ISSUE TITLE
Mirror Request: LLVM Snapshot Builds

### ISSUE THREAD

**Issue by lijinpei** [tuna/issues#273]
#### LLVM Snapshot Builds
LLVM官方提供的最新svn版的llvm/clang(4.0, 5.0, 6.0)等的build, 有ubtuntu/debian的版本和相应的仓库, 每日更新（具体时间未知）。

#### 上游地址与镜像方法(How to Mirror)
https://llvm.org/builds/
http://apt.llvm.org/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
unknown（目测10个G）

**Comment by shankerwangmiao** [comment]
由于更新过为频繁，且考虑到多数发行版已经提供 stable 版本的包，因此对于此类 nightly build 的包，我们一般不提供镜像。

**Comment by peterjc123** [comment]
较旧版本的debian和ubuntu中的官方源里的llvm或者clang都是老版本的。比如debian 9和ubuntu 16.04中只有3.8的。另外针对nightly的问题，是否可以只对Stable分支的包做镜像呀？谢谢！

**Comment by Harry-Chen** [comment]
> 较旧版本的debian和ubuntu中的官方源里的llvm或者clang都是老版本的。比如debian 9和ubuntu 16.04中只有7.0以下的。

这是发行版的软件包策略。

> 另外针对nightly的问题，是否可以只对Stable分支的包做镜像呀？谢谢！

我们可以评估这一要求。
