### ISSUE TITLE
能聊聊服务器状态里面静态的服务器状态图是怎么生成的吗

### ISSUE THREAD

**Issue by grenaaron** [tuna/issues#277]
能聊聊服务器状态里面静态的服务器状态图是怎么生成的吗

**Comment by grenaaron** [comment]
比如服务器iops图，是用rrdtool画的吗

**Comment by huiyiqun** [comment]
grafana 生成的，服务器上周期从 grafana 拖。

2017-09-23 23:18 GMT+08:00 grenaaron <notifications@github.com>:

**Comment by grenaaron** [comment]
好的，谢谢，我去尝试下
