### ISSUE TITLE
home-brew 镜像是不是有问题啊 =。=

### ISSUE THREAD

**Issue by lllvantis** [tuna/issues#279]
`git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git` 貌似拉不下来啊 =。= 不知道是不是我自己的问题 有大佬帮忙确认下么

**Comment by dotkrnl** [comment]
烦请给出相应错误信息，我这里复现不出你的错误。
另外这一仓库较大，第一次 clone 可能需要较长时间。

**Comment by shankerwangmiao** [comment]
这是正常现象，clone 的过程中没有输出，请耐心等待就好。
