### ISSUE TITLE
镜像站无法访问

### ISSUE THREAD

**Issue by SuperWangCC** [tuna/issues#282]
**网络为联通ADSL，在河南。已经连续两天无法访问。**
![_2017-10-03_22-55-31](https://user-images.githubusercontent.com/8223268/31131984-383b3546-a88e-11e7-9809-497362ce4b5a.png)
![_2017-10-03_22-57-06](https://user-images.githubusercontent.com/8223268/31131991-3b6b79c4-a88e-11e7-9a94-f997d5e6e426.png)

**Comment by xingduan** [comment]
天津联通，上海电信无法访问
是因为国庆放假，还是开会原因，何时恢复
