### ISSUE TITLE
添加Resurrection Remix OS开源项目

### ISSUE THREAD

**Issue by 1582130940** [tuna/issues#286]
#### 项目名称与简介(Project Intro.)
Resurrection Remix OS
#### 上游地址与镜像方法(How to Mirror)
#OS repo：https://github.com/ResurrectionRemix/platform_manifest
#项目地址：https://github.com/ResurrectionRemix 
####  其他信息(Other)
- 镜像大小(Mirror Size): 
=>25GB（视Android版本而定）

**Comment by shankerwangmiao** [comment]
我看了一下这个东西的 manifest，貌似里面主要的部分是 LineageOS 和 AOSP ，鉴于二者我们都已经镜像过了。如果您需要加速您所提及的项目的下载，建议手工修改 manifest 文件，将相关 remote 指向 tuna 即可。

如有进一步的问题，请 reopen 此 issue
