### ISSUE TITLE
增加CoreOS镜像

### ISSUE THREAD

**Issue by qiqizjl** [tuna/issues#287]
#### 项目名称与简介(Project Intro.)
CoreOS 是一个基于Linux 内核的轻量级操作系统，为了计算机集群的基础设施建设而生，专注于自动化，轻松部署，安全，可靠，规模化。作为一个操作系统，CoreOS 提供了在应用容器内部署应用所需要的基础功能环境以及一系列用于服务发现和配置共享的内建工具

#### 上游地址与镜像方法(How to Mirror)
官方地址
https://stable.release.core-os.net/
https://beta.release.core-os.net/
https://alpha.release.core-os.net/
官方暂时无方案，看到有第三方的同步方案，且开源在github上
https://github.com/steigr/coreos-local-mirror
https://github.com/tv42/oppositus
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by z4yx** [comment]
据说这个项目已经凉了

**Comment by z4yx** [comment]
https://coreos.com/os/eol/
