### ISSUE TITLE
Mirror Request:fedora-secondary

### ISSUE THREAD

**Issue by FlyGoat** [tuna/issues#29]
**如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写**

**If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.**
#### 项目名称与简介(Project Intro.)

fedora-secondary
Fedora的官方第三方Mirror
#### 上游地址与镜像方法(How to Mirror)

http://dl.fedoraproject.org/pub/fedora-secondary
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
  抱歉,无从获知.

**Comment by alick** [comment]
官方第三方Mirror -> 次级架构(ARM64, PowerPC, IBM s390x)软件源

镜像大小参见 <https://dl.fedoraproject.org/pub/DIRECTORY_SIZES.txt> fedora-secondary 需要 1.5T

能说下什么场合需要这些架构吗？

**Comment by FlyGoat** [comment]
这里包含了很多主源没有包含的学术包。类似于FlightGear这些第三方维护的包。

**Comment by bigeagle** [comment]
没发现适用于x86 和 x86-64 的包啊

**Comment by sztsian** [comment]
>没发现适用于x86 和 x86-64 的包啊

fedora-secondary 包含的是x86 x86_64 arm之外的架构

**Comment by huiyiqun** [comment]
如果用不上这些架构的话 这个issue就关了吧
