### ISSUE TITLE
没有NPM的镜像??

### ISSUE THREAD

**Issue by lucianspec** [tuna/issues#290]
#### 项目名称与简介(Project Intro.)

npm是nodejs自带的包管理器

#### 上游地址与镜像方法(How to Mirror)

https://registry.npmjs.org/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

3335875766

**Comment by bigeagle** [comment]
开了又关了3次了，过于复杂，每天崩坏，维护不动。

**Comment by lucianspec** [comment]
有教育网能用的NPM镜像推荐么?现在不知道是不是最近的原因,装不动NPM的包...

**Comment by lucianspec** [comment]
问题已解决, 是校内机房的问题. 感谢解答

**Comment by unmem** [comment]
I don't want to use Alibaba product, please considering support NPM mirrors.

**Comment by phy25** [comment]
@unmem See https://github.com/tuna/issues/issues/290#issuecomment-336793125

https://lug.ustc.edu.cn/wiki/mirrors/help/npm may help you.

**Comment by scateu** [comment]
淡定淡定~ 镜像而已

> I don't want to use Alibaba product, please considering support NPM mirrors.

应为 `consider supporting`

**Comment by StevenGardnerGMJ** [comment]
尊敬的tuna：
十分感谢提供的镜像方法为我解决了许多工作上的需求。
另外我找了一下镜像站 没发现有npm的镜像，
尊敬的诸位大佬，有兴趣加入npm镜像源吗，
在此跪谢。

**Comment by puzzle9** [comment]
> 尊敬的tuna： 十分感谢提供的镜像方法为我解决了许多工作上的需求。 另外我找了一下镜像站 没发现有npm的镜像， 尊敬的诸位大佬，有兴趣加入npm镜像源吗， 在此跪谢。

https://github.com/tuna/issues/issues/741

**Comment by DreamEnderKing** [comment]
npm(6.14.4+ds-1ubuntu2)版本似乎和Node.js(10.19.0~dfsg-3ubuntu1)版本不匹配，包管理器非常难搞，有大佬看一下这是怎么回事吗？跪谢。

错误信息：
_ERROR: npm is known not to run on Node.js v10.19.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/_
