### ISSUE TITLE
LEDE Mirror

### ISSUE THREAD

**Issue by RichardMei** [tuna/issues#291]
#### (Project Intro.)
[LEDE](https://lede-project.org/start)
#### (How to Mirror)
Please use **rsync://downloads.lede-project.org/downloads** to obtain a copy of the download repository.
Syncing the downloads share every 12 to 24 hours hours is ideal. Once a mirror has been set up, feel free to announce it at lede-adm@lists.lede-project.org so that it can be published on this page.
[more](https://lede-project.org/downloads#mirrors)
#### (Other)
- (Mirror Size): 
The data volume of the snapshots is roughly 35GB, we expect it to grow by 30-40GB with each release. Due to current bandwidth constraints we kindly ask you to use something like rsync --bwlimit 8000 when initially pulling the data.

**Comment by shankerwangmiao** [comment]
dup with #127

**Comment by RichardMei** [comment]
got it,thanks.
