### ISSUE TITLE
大会期间清华镜像能正常服务吗？

### ISSUE THREAD

**Issue by jhaohai** [tuna/issues#292]
今天下午镜像站一直失联，如果大会期间都是这样的话我们就早点把线上服务器的地址都改了

**Comment by Harry-Chen** [comment]
根据学校精神
> TUNA 镜像站正在不忘初心，继续前进，撸起袖子加油干，迎接党的十九大的胜利召开，为实现中华民族伟大复兴的中国梦，和建设人类命运共同体而努力奋斗！

**Comment by dotkrnl** [comment]
如果明天没有恢复访问，请暂时修改为其他镜像站。

**Comment by jhaohai** [comment]
@Harry-Chen @tizhi @dotkrnl 好的，谢谢

**Comment by dotkrnl** [comment]
@jhaohai 请在……之前修改为其他镜像站。
