### ISSUE TITLE
OpenBSD镜像: 分发版的大部分旧版建议删除

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#300]
考虑到TUNA磁盘的负载，我想可以删除一部分旧的分发版
只保留6.1和6.2（此种只保留最近两个分发版的惯例由以下OpenBSD镜像网站习得：ftp.jaist.ac.jp)

因为，实际上大多数用户只会用到最近两个分发版
只有一小部分人会不厌其烦的纵向的重复测试和维护
比较旧的发行版。

注：每个分发版（我只知道OpenBSD，其他的系统暂时不清楚）中，
       占用磁盘空间最大的文件集应该是软件包集合，而不是分发版的安装镜像。

**Comment by shankerwangmiao** [comment]
硬盘空间还有好多

**Comment by zhangteng331** [comment]
行，那就谢谢你们啦
