### ISSUE TITLE
OpenBSD镜像+NetBSD镜像：建议增加上游同步源

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#301]
ftp.jaist.ac.jp有上述两个镜像的备份

注：经由 http方式/ftp命令行方式 访问，可以得知该镜像源的详细硬件信息

该镜像源支持的访问类型：http,ftp,rsync

建议理由：根据该镜像源的描述，他们的吞吐量应该可以满足
                  rsync同步的条件（未测试）

OpenBSD镜像所在位置: http://ftp.jaist.ac.jp/pub/OpenBSD
NetBSD镜像所在位置: http://ftp.jaist.ac.jp/pub/NetBSD

**Comment by shankerwangmiao** [comment]
目前我们尚不支持从多个来源同步

**Comment by zhangteng331** [comment]
那也行，只要同步源稳定就行（我是因为看到这两个镜像
有时会显示“failed”的标签，才会这样想的）

谢谢你们的付出与贡献
