### ISSUE TITLE
OpenBSD镜像: 磁盘占用量提高的潜在原因

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#302]
从OpenBSD 6.2开始，AMD64平台和i386平台的基础编译工具包
更改为Clang/LLVM，故导致大量的软件包（比如安装镜像本身和
AMD64/i386平台对应的软件包集合）的空间大小会有所提高
(粗略的估计应该会提高原文件大小的1/4或1/3以上)，
请提前进行对磁盘存储量和同步文件量的评估，再进行同步。

（抱歉啊实在，我不太懂如何得知要同步文件量的大小，但是
    用rsync工具应该可以提前进行探测吧）

**Comment by shankerwangmiao** [comment]
存储容量够

**Comment by zhangteng331** [comment]
好的，那就谢谢你们啦
