### ISSUE TITLE
Anaconda 默认 channel 已变成 https://repo.continuum.io/pkgs/main

### ISSUE THREAD

**Issue by OuSatoru** [tuna/issues#303]
#### 项目名称与简介(Project Intro.)
Anaconda
#### 上游地址与镜像方法(How to Mirror)
https://repo.continuum.io/pkgs/main
#### 其他信息(Other)
比如官方anaconda5.0.1，tuna4.4.0; 官方python3.6.3，tuna3.6.2
现在默认的源是https://repo.continuum.io/pkgs/main
在https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/ 里没有main频道
- 镜像大小(Mirror Size):

**Comment by bigeagle** [comment]
和前段时间加速隧道不稳定有关，已更新配置，正在刷新。

**Comment by OuSatoru** [comment]
很赞！！
