### ISSUE TITLE
请求添加WineHQ源

### ISSUE THREAD

**Issue by wangqr** [tuna/issues#304]
#### 项目名称与简介(Project Intro.)

[**Wine**](https://www.winehq.org/) （“Wine Is Not an Emulator” 的首字母缩写）是一个能够在多种 POSIX-compliant 操作系统（诸如 Linux，macOS 及 BSD 等）上运行 Windows 应用的兼容层。 Wine 不是像虚拟机或者模拟器一样模仿内部的 Windows 逻辑，而是將 Windows API 调用翻译成为动态的 POSIX 调用，免除了性能和其他一些行为的内存占用，让你能够干净地集合 Windows 应用到你的桌面。

WineHQ对Ubuntu、Debian、Fedora、Mageia、macOS提供预构建并提供支持。

#### 上游地址与镜像方法(How to Mirror)

* 完整下载（包括源码等）：https://dl.winehq.org/ | ftp://ftp.winehq.org/pub/
* 仅预编译包： https://dl.winehq.org/wine-builds/ | ftp://ftp.winehq.org/pub/wine-builds/
* USTC：https://mirrors.ustc.edu.cn/wine/

#### 其他信息(Other)

* 镜像大小(Mirror Size): 151.1 GiB（全部），65.3GiB（仅预编译包）

**Comment by shankerwangmiao** [comment]
貌似发行版的源里自带了？

**Comment by wangqr** [comment]
发行版的源里版本较早，例如现在Ubuntu Xenial官方源中wine版本为1.6，但wine-builds内提供
```
winehq-devel/xenial,now 2.20.0~xenial amd64
winehq-stable/xenial 2.0.3~xenial amd64
winehq-staging/xenial 2.19.0~xenial amd64
```

**Comment by wangqr** [comment]
此外，
* 因为wine大概安装包20M左右，目前对我个人而言USTC够用了
* 此issue涵盖了#209
