### ISSUE TITLE
Node.js 到 9.0 啦 , 粗来更新啦

### ISSUE THREAD

**Issue by fengT-T** [tuna/issues#305]
如题

**Comment by bigeagle** [comment]
9.0 …… 不是 LTS……

**Comment by fengT-T** [comment]
.... 别啊,不是LTS就不同步了么,  镜像源就应该和官方的一样嘛,

**Comment by bigeagle** [comment]
改代码……测试……下载好几天……每天同步…… 然后过俩月没了……

**Comment by fengT-T** [comment]
T_T

**Comment by bianjp** [comment]
增加个版本也很麻烦么？
同步脚本也许可以参考下 USTC 的：https://github.com/ustclug/ustcmirror-images/blob/master/nodesource/sync-nodesource.sh

**Comment by bigeagle** [comment]
不麻烦呀，但是心里有负担
