### ISSUE TITLE
请求添加Gitlab Runner(version >= 10.0.0)镜像

### ISSUE THREAD

**Issue by xingduan** [tuna/issues#306]
#### 项目名称与简介(Project Intro.)
Gitlab Runner (version >= 10.0.0)
_gitlab-ci-multi-runner自10.0.0版本开始变更为gitlab-runner_
#### 上游地址与镜像方法(How to Mirror)
[https://packages.gitlab.com/runner/gitlab-runner/mirror](https://packages.gitlab.com/runner/gitlab-runner/mirror)
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by w1ndy** [comment]
Repo: https://packages.gitlab.com/runner/gitlab-runner

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/gitlab-runner/

已经镜像完毕
