### ISSUE TITLE
Anaconda Mirror is NOT Allowed

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#307]
根据 https://repo.continuum.io/pkgs/

>  Anaconda and Miniconda are trademarks of Anaconda, Inc. Public mirrors of this are not allowed without express permission from Anaconda, Inc. For private mirrors and technical support, we encourage you to look at Anaconda Enterprise and Anaconda Support.

We need express permission from Anaconda.

**Comment by huiyiqun** [comment]
How is it going?

**Comment by xavieryao** [comment]
之前的邮件还没有回应

**Comment by shubhvachher** [comment]
Is this being followed up? Please take a look at this :

[https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/bE--AVEO5Bk](url)

> Hey everyone,
>We know that efforts like this (and probably others that we are not yet aware of) are well-intentioned and we applaud the enthusiasm and support that it shows for the Anaconda user community.  But over the years of maintaining the infrastructure to do this, we at Continuum have learned that some of the requirements to do this well are non-obvious.  Thus, in order to provide a consistent, secure, reliable, and safe experience for all users of Anaconda, we do have to enforce an official policy that public Anaconda mirrors are not allowed, without explicit permission from Continuum Analytics.  If you are interested in hosting a public mirror, please contact us at in...@continuum.io or contact me directly so that we can discuss the technical and business requirements.
...
>Thanks,
>-Travis

Maybe you can contact him directly?

**Comment by xavieryao** [comment]
Thank you for the information

**Comment by Nekochef** [comment]
![image](https://user-images.githubusercontent.com/22209183/38854113-06a09e6e-4252-11e8-86d8-9c9486b78417.png)
希望他们能同意
