### ISSUE TITLE
Jenkins镜像似乎缺少文件

### ISSUE THREAD

**Issue by wangqr** [tuna/issues#308]
目前的Jenkins镜像对应关系似乎是
https://pkg.jenkins.io/debian/binary/ → https://mirrors.tuna.tsinghua.edu.cn/jenkins/debian/

但是镜像中缺少[Release](https://pkg.jenkins.io/debian/binary/Release)、[Packages](https://pkg.jenkins.io/debian/binary/Packages)、[Packages.bz2](https://pkg.jenkins.io/debian/binary/Packages.bz2)、[Packages.gz](https://pkg.jenkins.io/debian/binary/Packages.gz)、[Packages.lzma](https://pkg.jenkins.io/debian/binary/Packages.lzma)等文件，使得它不能正确地作为deb源工作。

**Comment by shankerwangmiao** [comment]
您好，jenkin 的上游服务器上，亦不存在上述文件。请注意，我们镜像的，并不是 pkg.jenkins.io，而是 mirrors.jenkins-ci.org 。

**Comment by a-wing** [comment]
mirrors.jenkins-ci.org 并不存在 缺少Release、Packages、Packages.bz2、Packages.gz、Packages.lzma等文件

但 pkg.jenkins.io 有啊
https://pkg.jenkins.io/debian/binary/Release

比如debian 如果没有 Release

https://mirrors.tuna.tsinghua.edu.cn/jenkins/debian/ 完全没法用啊

**Comment by Harry-Chen** [comment]
我们严格按照官方给出的镜像指南进行部署，服务器与官方保持一致。
根据我的理解，这并不是一个 apt 源，您需要手动下载以后使用 dpkg 安装。
