### ISSUE TITLE
tunasync删除[[mirrors]]问题

### ISSUE THREAD

**Issue by shengliang1984** [tuna/issues#309]
tunasync删除[[mirrors]]问题，在/etc/tunasync/worker.conf删除了一个[[mirrors]],重新启动服务 ，但是在tunasynctl list mirror_worker 还是能发现这个删除掉了的[[mirrors]]，请问怎么处理

**Comment by shankerwangmiao** [comment]
删掉 [[mirrors]] 之后，请 `tunasynctl flush` 清理掉旧的任务。
