### ISSUE TITLE
希望添加Slackware ARM镜像

### ISSUE THREAD

**Issue by 4679** [tuna/issues#31]
Slackware的arm port
http://mirrors.vbi.vt.edu/ 这里貌似提供rsync 可以当上游

**Comment by bigeagle** [comment]
We'll process this after upgrading our server, as our hard disk is almost full.

**Comment by shankerwangmiao** [comment]
syncing

**Comment by shankerwangmiao** [comment]
leave this open until initial sync finishes

**Comment by shankerwangmiao** [comment]
sync done
