### ISSUE TITLE
NPM 镜像

### ISSUE THREAD

**Issue by bqsgwys** [tuna/issues#310]
#### 项目名称与简介(Project Intro.)
  NPM
npm is the package manager for JavaScript and the world’s largest software registry. Discover packages of reusable code — and assemble them in powerful new ways.
#### 上游地址与镜像方法(How to Mirror)
registry.npmjs.com
#### 其他信息(Other)
- 镜像大小(Mirror Size): 4165128323

**Comment by bigeagle** [comment]
duplicated with #290
