### ISSUE TITLE
清华源中的Docker-CE镜像有问题

### ISSUE THREAD

**Issue by Aitkots** [tuna/issues#311]
官方原始镜像路径：https://download.docker.com/linux/centos/7/x86_64/stable/repodata/
这个路径下的文件在清华源中的对应路径中不存在，导致CentOS的源更新失败。

**Comment by shankerwangmiao** [comment]
见 https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/7/x86_64/stable/repodata/
