### ISSUE TITLE
Firefox Kaios2.0系统镜像

### ISSUE THREAD

**Issue by EricChows** [tuna/issues#313]
#### 项目名称与简介(Project Intro.)
火狐浏览器的B2G项目手机操作系统Kaios 2.0版本
项目详细信息请参考https://wiki.mozilla.org/B2G

#### 上游地址与镜像方法(How to Mirror)
上游地址：https://github.com/mozilla-b2g/B2G
镜像方法：http://blog.csdn.net/nxh_love/article/details/9467707

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
unkown

**Comment by jiegec** [comment]
看Git，最后更新是2016年啊。。我也是第一次听说这个project，感觉需求不大。

**Comment by EricChows** [comment]
管网：http://www.kaiostech.com/

**Comment by EricChows** [comment]
17年官方停止更新来，但是高通还在维护

**Comment by EricChows** [comment]
现在很多的功能机在用这个操作系统，他能做到和苹果的IOS系统一样流畅，还是值得研究的

**Comment by jiegec** [comment]
“高通还在维护” where？

**Comment by EricChows** [comment]
高通内部在使用，没有对外部维护，我们做的高通芯片的手机还在用这个操作系统

**Comment by EricChows** [comment]
Kaios是B2G的一个分支，参见https://zh.wikipedia.org/wiki/Firefox_OS

**Comment by shankerwangmiao** [comment]
我看了一下这个，看起来要镜像的是 https://github.com/mozilla-b2g/ 下的（几乎）所有的仓库。应该形式类似于 AOSP 或者 lineageOS，然而官方貌似没有提供一个完整的 manifest 列举所有的仓库。https://github.com/mozilla-b2g/b2g-manifest 这里面的 manifest 貌似都是按照不同的平台分别的，没有类似于 https://github.com/lineageos/mirror 这样的一下子都列出来的。这样的话镜像起来貌似很困难。

**Comment by shownb** [comment]
@EricChows 很多功能机在用？在哪里可以买到啊？买一个来玩玩也挺过瘾的。

**Comment by EricChows** [comment]
@shownb 国内几乎买不到，都卖到了非洲和印度了.

**Comment by EricChows** [comment]
@shankerwangmiao @jiegec ,好的，thanks
