### ISSUE TITLE
elasticstack6.x

### ISSUE THREAD

**Issue by ld0574** [tuna/issues#314]
请更新6.x的elasticstack

#### 上游地址与镜像方法
name=Elasticsearch repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum

#### 相关文档
https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html

**Comment by steve3d** [comment]
什么时候能更新啊, 国内好象就这一个镜象

**Comment by shankerwangmiao** [comment]
抱歉最近事务繁杂，处理较慢。

更新已经完成，请测试。
