### ISSUE TITLE
增加AnacondaCloud中与Intel相关的包

### ISSUE THREAD

**Issue by memory-yancy** [tuna/issues#315]
#### 项目名称与简介(Project Intro.)

Anaconda Cloud's Intel Channel （作为conda”第三方“包仓库，Intel对其里面的conda包进行了优化与定制，尤其在加速方面，值得使用。但是由于网络原因/Timeout、download rate slow等，体验很不好）

#### 上游地址与镜像方法(How to Mirror)

[Intel Anaconda Channel](https://anaconda.org/intel)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

大小可以参考每个包所提到的SIze

Thanks！

**Comment by shankerwangmiao** [comment]
请在 #112 中跟帖回复需要添加的 channel，多谢！
