### ISSUE TITLE
kubernetes 镜像

### ISSUE THREAD

**Issue by wxh512** [tuna/issues#316]
#### 项目名称与简介(Project Intro.)
kubernetes 
主要管理docker等资源

#### 上游地址与镜像方法(How to Mirror)
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/
http://apt.kubernetes.io kubernetes-xenial main

#### 其他信息(Other)
为了搭建树莓派kubernetes集群
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
dup with #129

**Comment by wxh512** [comment]
已经看了，没有镜像armhf的镜像，请帮忙镜像一下
Err https://mirrors.ustc.edu.cn kubernetes-xenial/main armhf Packages          
  HttpError404

**Comment by wxh512** [comment]
Err https://mirrors.ustc.edu.cn kubernetes-xenial/main armhf Packages
HttpError404
这个镜像没有，请帮忙镜像谢谢
