### ISSUE TITLE
增加NuGet源的镜像

### ISSUE THREAD

**Issue by cmpute** [tuna/issues#318]
#### 项目名称与简介(Project Intro.)

[NuGet](https://www.nuget.org/)是.NET平台的包管理器，在进行.NET开发时经常能用到~尤其是进行Windows 10平台开发的时候一次nuget restore就要更新好几十个包。跨平台的.NET Core也是非常以来于NuGet的。

#### 上游地址与镜像方法(How to Mirror)

抱歉没有仔细了解过= =不过个人感觉镜像NuGet的过程应该是和镜像PyPI类似的。提供两个链接不知道行吗？
http://www.cnblogs.com/cmt/p/nuget-mirror.html
https://stackoverflow.com/questions/4695526/mirroring-the-official-nuget-package-repository
NuGet包远没有PyPI那么多，而且更新周期也可以短一点

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
不多也有将近十万个，我们很少有 Windows 用户，所以可能没有人原因维护。

@Harry-Chen 你对 NuGet 熟吗？

**Comment by Harry-Chen** [comment]
镜像 NuGet 应该不难，就是解析一个 metadata 把包都下回来，提供服务的时候也只需要一个 nginx 就可以了。
不过问题是我不知道许可证是不是允许我们这么干，我觉得可能有点法律上的困难。

**Comment by Harry-Chen** [comment]
哦不对，好像不能直接 server 静态文件
参见 https://github.com/ustclug/mirrorrequest/issues/80
现在可能还多了点技术上的困难

**Comment by cmpute** [comment]
这就有点尴尬了= =不过看了看NuGet.Server，不少依赖在Core上是有替代的，应该还是有希望的。等移植吧。。

**Comment by shankerwangmiao** [comment]
暂时先搁置吧

**Comment by DukeCheng** [comment]
现在微软已经对nuget.org做了cdn加速，这个应该是不需要了.
