### ISSUE TITLE
Hackage镜像结构更新

### ISSUE THREAD

**Issue by soylens** [tuna/issues#319]
--本ISSUE非镜像请求
在最近的一次更新中(1.5.1 -> 1.6.1),stack的Hackage Package Index更改为01-index.tar.gz, 目前stack 1.6.1 不能正确与TUNA Hackage镜像工作,请尽快同步

**Comment by shankerwangmiao** [comment]
移至 https://github.com/tuna/tunasync-scripts/issues/14 讨论
