### ISSUE TITLE
Mirror request: oh-my-zsh

### ISSUE THREAD

**Issue by cty12** [tuna/issues#32]
#### 项目名称与简介(Project Intro.)

A delightful community-driven framework for managing your zsh configuration. 

#### 上游地址与镜像方法(How to Mirror)

https://github.com/robbyrussell/oh-my-zsh

#### 其他信息(Other)

n/a

**Comment by bigeagle** [comment]
这个项目…… 很大吗？

**Comment by cty12** [comment]
不大，你可以把那个 repo clone 下来看一眼。

另外你们需要什么规格的硬盘呢？

**Comment by bigeagle** [comment]
恩，服务器升级换代的事情已经在做了，这个不需要担心。

我的意思是，这个 repo 不大，下载也不困难，所以是否有必要做镜像？
因为 GitHub 上值得 clone 的项目何其多，如果不是下载困难或者太大的 repo，镜像它们的意义是什么？

**Comment by cty12** [comment]
@bigeagle 

你说的这确实是一个问题。

据我所知 GitHub 是无法通过 ipv6 访问的，我现在使用的校内的服务器并没有使用 ipv4 连接外网，如果常用的托管在工具能有校内的源自然是最方便的。虽然没有的话倒是也影响不大。

**Comment by bigeagle** [comment]
嗯嗯，你可以使用 [NAT64](http://ipv6.lt/nat64_en.php) 通过 IPv6 访问 IPv4 :)

**Comment by scateu** [comment]
我记得那时候SourceForge.net上还经常有日本的北陸先科什么全站镜像
