### ISSUE TITLE
Hackage 镜像缺失包 bindings-DSL-1.0.24

### ISSUE THREAD

**Issue by Qinka** [tuna/issues#320]
Hackage 镜像中缺失 bindings-DSL-1.0.24 包

**Comment by jiegec** [comment]
可能正在同步吧。。？之前stack 1.6.1更新的时候，因为改了目录结构，也出过一段时间问题，后来同步的script更新以后就好了

**Comment by shankerwangmiao** [comment]
现在还有故障吗？

**Comment by Qinka** [comment]
能用 cabal get 获取到 那个包了，应该没问题了，关了
