### ISSUE TITLE
请问 percona的源是什么情况~

### ISSUE THREAD

**Issue by linfuchuan** [tuna/issues#321]
[https://mirrors.tuna.tsinghua.edu.cn/percona/](https://mirrors.tuna.tsinghua.edu.cn/percona/) percona源似乎一直都没有项目的 ~
麻烦看看哦 谢谢

**Comment by shankerwangmiao** [comment]
您好，该页面显示为空白的原因是，上游同步下来的数据中，包括一个空白的 index.html。

经查，目前服务器上数据正常，请放心使用。
