### ISSUE TITLE
[故障]Gitlab CI Multi Runner 镜像

### ISSUE THREAD

**Issue by jk2K** [tuna/issues#322]
镜像地址
https://mirrors.tuna.tsinghua.edu.cn/help/gitlab-ci-multi-runner/

最新镜像版本停留在 9.5.1, 最新版本已经是 [10.2.0](https://gitlab.com/gitlab-org/gitlab-runner/blob/master/CHANGELOG.md) 了, 这是官方的安装教程 https://docs.gitlab.com/runner/install/linux-repository.html#installing-the-runner

**Comment by shankerwangmiao** [comment]
dup with #306
