### ISSUE TITLE
NixOS 镜像申请

### ISSUE THREAD

**Issue by OlingCat** [tuna/issues#323]
#### 项目名称与简介(Project Intro.)

NixOS 是一个函数式发行版，它使用 nix 包管理器，通过声明式的配置文件来安装和更新，并可回滚至任意版本。nix 旨在彻底解决不同软件版本间的依赖问题，亦可多版本共存。
#199 GuixDS 的灵感即来源于此。

#### 上游地址与镜像方法(How to Mirror)

NixOS 的源需要用 nix 来同步，具体参见 https://nixos.org/nix-dev/2016-October/022029.html
例如，要添加 unstable channel 的源：
```
nix copy -r --store https://cache.nixos.community/ --to file:///tmp/my-mirror \
$(curl -L https://nixos.org/channels/nixos-unstable/store-paths.xz | xz -d)
```

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知
NixOS 更改源参考 http://nix-cookbook.readthedocs.io/en/latest/faq.html#how-do-i-add-a-new-binary-cache

**Comment by OlingCat** [comment]
https://github.com/NixOS/nixpkgs/issues/32659 里建议改为 https://cache.nixos.community/

**Comment by shankerwangmiao** [comment]
不知道这个有能直接 rsync 的吗？更方便一些，不然要单独准备工具和脚本，部署起来要相对困难很多。

**Comment by OlingCat** [comment]
暂时似乎不能....

Miao Wang <notifications@github.com> 于 2018年1月5日周五 21:30写道：

**Comment by shankerwangmiao** [comment]
我看了一下 Nix 的手册 https://nixos.org/nix/manual/ 并没有找到你说的 nix copy 命令。我去 dockerhub 上拉下来 nixos/nix 这个，进去之后发现只有 `nix-build` 之类的，开头是  `nix-` 的命令。里面貌似有一个长得比较像的 `nix-copy-closure` ，试着运行了一下，感觉也不太对劲：

```
root@ubuntu ~# docker run -it --rm nixos/nix 
83bde6f8675b:/# apk add --update curl xz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20161130-r2)
(2/6) Installing libssh2 (1.8.0-r1)
(3/6) Installing libcurl (7.57.0-r0)
(4/6) Installing curl (7.57.0-r0)
(5/6) Installing xz-libs (5.2.3-r0)
(6/6) Installing xz (5.2.3-r0)
Executing busybox-1.26.2-r5.trigger
Executing ca-certificates-20161130-r2.trigger
OK: 9 MiB in 20 packages
83bde6f8675b:/# mkdir /tmp
mkdir: can't create directory '/tmp': File exists
83bde6f8675b:/# mkdir /tmp/a
83bde6f8675b:/# nix-c
nix-channel          nix-collect-garbage  nix-copy-closure
83bde6f8675b:/# nix-c
nix-channel          nix-collect-garbage  nix-copy-closure
83bde6f8675b:/# nix-copy-closure -r --store https://cache.nixos.community/ --to file:///tmp/a $(curl -L https://nixos.org/channels/nixos-unstable/store-paths.xz | xz -d)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   284  100   284    0     0    284      0  0:00:01  0:00:01 --:--:--   142
100  673k  100  673k    0     0   134k      0  0:00:05  0:00:05 --:--:--  221k
sh: exec: line 1: ssh: not found
unable to connect to ‘-r’; falling back to old closure copying method
getting status of â/--storeâ: No such file or directory at /nix/store/xrqssm90gsrnqdn79rpfcs6dwx8597d2-nix-1.11.14/lib/perl5/site_perl/5.22.3/x86_64-linux-thread-multi/Nix/CopyClosure.pm line 
```

不知道 nix 这个工具去哪里找？

**Comment by dramforever** [comment]
https://nixos.org/nix

**Comment by shankerwangmiao** [comment]
@dramforever 我执行过 `curl https://nixos.org/nix/install | sh` 之后，并没有找到 `nix` 命令，只看到这个脚本装上去了一些  `nix-` 开头的命令，不知道 `nix` 命令要怎么装？

**Comment by dramforever** [comment]
没有 nix 命令的……说实话我不是很确定那个文档是对的。

我询问了 nixos 的人们能不能直接 rsync。nixos binary cache 的格式比较简单，只要提供下载文件的地址就可以了

**Comment by dramforever** [comment]
这些东西我们也不是很熟悉，说实话。对不起，实在是麻烦您了

**Comment by shankerwangmiao** [comment]
这个 nix 的文件结构确实适合于用对象存储来存。

我这边刚同步一部分，https://mirrors.tuna.tsinghua.edu.cn/nix/ 目录内容已经不忍直视了。。。。

**Comment by dramforever** [comment]
嗯，而且那些文件名超长的文件都是理论上不会变的……

**Comment by shankerwangmiao** [comment]
抱歉，这个小文件实在太多了，我们文件系统有些受不了，没法镜像了。

**Comment by shankerwangmiao** [comment]
此 mirror request 暂时搁置

**Comment by dramforever** [comment]
嗯，没关系的！谢谢了

**Comment by ZeroAurora** [comment]
> ## Channel

> The usual way to obtain Nixpkgs is to subscribe to the Nixpkgs channel, which always contains the latest version of Nixpkgs:
```sh
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update
```
> After this, you can use nix-env to install available packages.

From: https://nixos.org/nixpkgs/download.html

这里只需要将 https://nixos.org/channels/nixpkgs-unstable 加入 nix-channel，是否就意味着只要同步 https://nixos.org/channels/nixpkgs-unstable 即可？

**Comment by ZeroAurora** [comment]
这是 Nixpkg Git 托管仓库:
https://github.com/NixOS/nixpkgs.git

**Comment by ZeroAurora** [comment]
@shankerwangmiao 能否通过镜像  https://nixos.org/channels/nixpkgs-unstable 或者构建 nixpkgs 仓库来达到目的？
看了一下，这仓库里的文件只有5个，跟之前许多文件的说法搭不上边，但它确实是 Nix 软件包仓库。（可能是因为 Nix 本身的改动）

**Comment by ZeroAurora** [comment]
@OlingCat nixos 把二进制缓存扔到了 fastly 上。如果 fastly cdn 足够快，那么就可以不用考虑镜像了吧。

**Comment by dramforever** [comment]
@ZeroAurora Fastly 的网速并不能算快。在少数情况下能达到 200 KiB/s 甚至 700 KiB/s，但是绝大多数情况下都是大约 10KiB/s

**Comment by ZeroAurora** [comment]
呃抱歉之前看错了…nix 指令是在 2018 年引入的，根本不老

**Comment by ZeroAurora** [comment]
这个镜像请求的时间是 2017 年，而 nix 命令正式发布是在 2018.2.22
所以现在也许可以试试？虽然我也不是很确定能不能行。

**Comment by ZeroAurora** [comment]
但是由于文件的特殊性，还是适合使用对象存储……所以还是基本没有进展

**Comment by dramforever** [comment]
目前看来还是从 `store-paths.xz` 往下走吧……

**Comment by jiegec** [comment]
nix 本身已经被 mirror 见 https://mirrors.tuna.tsinghua.edu.cn/nix/
nixpkgs 仍在 @dramforever 研究中

**Comment by jiegec** [comment]
any updates? pia @dramforever

**Comment by dramforever** [comment]
@jiegec 递归：我之前发现 `nix` 工具理论上可以 `nix copy --from https://cache.nixos.org --to file://destination $(xzcat store-paths.xz)`，但是实际上所有 store path 的列表长度超过 `ARG_MAX`，而拆成多个调用很不优雅，所以我之前好像提了一个 `@store-paths.txt` 这种格式的 feature request NixOS/nix#2684 但是没人理我 = =

还有一个问题就是 binary cache 如果能缓存反代 https://cache.nixos.org 的话其实能省很多事。一个版本的 nixpkgs 依赖闭包大概有 400GB（不同版本有很大重叠），其中很大很大部分都是非常冷门的东西（比如水量的 haskell 包用的人应该不会太多）

如果不能的话现在的设想是打算研究一下 nix 的 perl 绑定，或者拆成多次调用 nix 工具。现在有 wip 写了一部分的 channel 同步脚本，但是因为开学了没什么进展。

**Comment by KsRyY** [comment]
@dramforever 现在还是没有办法吗？

**Comment by oxalica** [comment]
What's the status of it?

**Comment by dramforever** [comment]
Ref: https://github.com/tuna/tunasync-scripts/pull/49
