### ISSUE TITLE
apache-thrift configuration error

### ISSUE THREAD

**Issue by fzy139** [tuna/issues#326]
Hello tuna，

Raspbian，building  gnuradio and it turns out to be that error installing package apache-thrift after trying for several times.

Thx~

**Comment by shankerwangmiao** [comment]
Is there any more information such as the error shown available?

**Comment by fzy139** [comment]
Hi,
There is a "configure: error: "Error: libcrypto required."" when apache-thrift configuring.And then it stopped.

I tried to install the openssl-devel but it still exists.

Thx

**Comment by shankerwangmiao** [comment]
Maybe you need to install libssl-dev

**Comment by fzy139** [comment]
Have already installed.

I've found this
‘14) 执行thrift的configure时遇到如下的错误(thrift-0.9.0和thrift-0.9.1遇到过):
checking for setsockopt in -lsocket... no
checking for BN_init in -lcrypto... no
configure: error: "Error: libcrypto required."

可能是因为编译安装openssl时指定了--prefix，比如--prefix=/usr/local/thirdparty/openssl，可这样解决:
不指定thrift的configure的--with-openssl=/usr/local/thirdparty/openssl，改为:
CPPFLAGS="-I/usr/local/thirdparty/openssl/include" LDFLAGS="-ldl -L/usr/local/thirdparty/openssl/lib"
替代它就OK了。
‘

But I don‘t have this path in my raspbian.

**Comment by shankerwangmiao** [comment]
我先关掉这个 issue，如果有进一步的问题请 reopen

**Comment by wangyum** [comment]
It works after installing libssl1.0-dev:
```
sudo apt install libssl1.0-dev
```

**Comment by rammiah** [comment]
> It works after installing libssl1.0-dev:
> 
> ```
> sudo apt install libssl1.0-dev
> ```

this worked, thanks
