### ISSUE TITLE
Bioconductor 源是不是有什么问题？

### ISSUE THREAD

**Issue by JackieMium** [tuna/issues#327]
今天 2017-12-21。但是 Bioconductor 源的同步记录：
```
- Last update: 2017-09-28 14:57
- Status: Failed.
```

用起来也发现官方 Bioconductor 已经更新到 3.6 了但是同过 TUNA 更新不上去。

**Comment by shankerwangmiao** [comment]
嗯，是的，目前我们在补充同步，好了之后我会在此反馈

**Comment by shankerwangmiao** [comment]
目前已经全部下载完毕，从 1.8 到 3.7 一共大概 2T 左右。目前正在作最后的部署工作。

**Comment by shankerwangmiao** [comment]
同步完毕
