### ISSUE TITLE
在 Fedora 镜像中增加 Fedora Alternative Architectures: aarch64

### ISSUE THREAD

**Issue by sztsian** [tuna/issues#328]
#### 项目名称与简介(Project Intro.)
Fedora 发行版中，x86_64, ARM-hfp 被称为 Primary Architecture. 其他架构被称为 Alternative Architectures.
自 Fedora 26 以来， x86 (32位) 也被归入 Alternative Architectures
http://fedoraproject.org/wiki/Architectures#Alternative_Architectures
https://alt.fedoraproject.org/alt/

考虑到现在越来越多的人拥有树莓派3等 aarch64 架构的开发板，我认为非常有必要增加 aarch64。

#### 上游地址与镜像方法(How to Mirror)
rsync，与 Fedora Primary Architecture 相同，如
http://dl.fedoraproject.org/pub/fedora-secondary/releases/27/Workstation/aarch64/
http://dl.fedoraproject.org/pub/fedora-secondary/releases/27/Server/aarch64/
http://dl.fedoraproject.org/pub/fedora-secondary/updates/27/aarch64/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
详情： https://dl.fedoraproject.org/pub/DIRECTORY_SIZES.txt

**Comment by shankerwangmiao** [comment]
done
