### ISSUE TITLE
Maven镜像同步

### ISSUE THREAD

**Issue by zater** [tuna/issues#329]
#### 项目名称与简介(Project Intro.)
Apache Maven是一个软件项目管理和综合工具。基于项目对象模型（POM）的概念，Maven可以从一个中心资料片管理项目构建，报告和文件。
本教程将介绍如何使用Maven在Java开发，或任何其他的编程语言的任何项目。
比如hadoop，spark，Spring,Hibernater,mybaits等项目都需要这些jar包。
#### 上游地址与镜像方法(How to Mirror)
http://central.maven.org/maven2/
http://repo2.maven.org/maven2/
可以使用nexus 或apache archiva同步。
#### 其他信息(Other)

- 镜像大小(Mirror Size):
未知， 大约有2,420,235 个jar包

**Comment by Harry-Chen** [comment]
这个问题在 #100 #59 #99 都有讨论过，由于没有相应的技术能力，我们目前的态度倾向于暂缓镜像。请暂时使用阿里云的镜像。

**Comment by shankerwangmiao** [comment]
dup with #59
