### ISSUE TITLE
NTP (网络授时服务)

### ISSUE THREAD

**Issue by cty12** [tuna/issues#33]
#### 项目名称与简介(Project Intro.)

Network Time Protocol (NTP) is a networking protocol for clock synchronization between computer systems over packet-switched, variable-latency data networks. 
#### 上游地址与镜像方法(How to Mirror)

n/a
#### 其他信息(Other)

这个服务曾经是好的，现在不能使用了：

https://wiki.tuna.tsinghua.edu.cn/NtpHowto

**Comment by bigeagle** [comment]
和 tuna/collection#65 重复了，目前人手和资源都不够，等条件成熟吧。
