### ISSUE TITLE
anaconda镜像源安装的一些问题

### ISSUE THREAD

**Issue by liudongmeng** [tuna/issues#330]
按照官网的说明配置了镜像

```sh
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --set show_channel_urls yes
```

然后遇到了一个版本的问题,以`matplotlib`为例
使用`conda install matplotlib`命令,默认会在free的镜像中下载2.0.2版本的包,可是search到的`default`和`https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/`中版本号最高的都是2.1.1,这算不算是bug?还是说这是有意这么设计的?

**Comment by gepcel** [comment]
**估计**，因为你是后添加的 `free` channel，所以 `free` channel 排在上面，因此拥有高优先级，优先搜索 `free`，结果即：matplotlib 2.02

如果是这样的话，建议可以调节 channel 的顺序，或者在 `.condarc` 文件后面 添加 `channel_priority: false`

详情请见：[manage-channels](https://conda.io/docs/user-guide/tasks/manage-channels.html)

**Comment by shankerwangmiao** [comment]
感谢 @gepcel 解答，此 issue 暂时关闭，如果有进一步的问题，请跟帖并 reopen

**Comment by dotkrnl** [comment]
如果问题解决，欢迎帮助修改帮助文档～
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-anaconda.md

**Comment by gepcel** [comment]
@dotkrnl 

根据[文档](https://docs.anaconda.com/anaconda/release-notes)

```
A new channel, pkgs/main, has been added to defaults. The new channel is given top priority within defaults and holds packages built with the new compiler stack.
```

既然 

* main channle 有最高优先级，
* 而默认 `channel_priority` 是 `true`，
* 同时  `conda config --all channels` 是后添加的排在前面

也许 帮助文档 中应该先添加 free, 再添加 main ? 如何？征求一下管理人员的意见，如果同意我可以 pull a request.

**Comment by dotkrnl** [comment]
@gepcel 如果方便，希望您帮忙测试一下这样添加后的正确性，因为我不是 Anaconda 用户，无法测试。您确认后可以直接 pull request 我会进行 merge。十分感谢！

**Comment by dotkrnl** [comment]
merged

**Comment by gepcel** [comment]
觉得应该把 requests 在这里列一下。方便其它人对照查找。[修改在这里](https://github.com/tuna/mirror-web/pull/83#event-1412715295)
