### ISSUE TITLE
gentoo-portage-prefix 鏡像請求

### ISSUE THREAD

**Issue by KireinaHoro** [tuna/issues#331]
#### 项目名称与简介(Project Intro.)

To bring out the virtues of Gentoo Linux on different operating systems, the Gentoo Prefix project develops and maintains a way of installing Gentoo systems in a non-standard location, designated by a "prefix".

`gentoo-portage-prefix` is the Portage `gentoo_prefix` repo for Prefix systems.

#### 上游地址与镜像方法(How to Mirror)

```
rsync://rsync.prefix.bitzolder.nl/gentoo-portage-prefix
```

#### 其他信息(Other)
- 镜像大小(Mirror Size): similar to `gentoo-portage`

**Comment by Harry-Chen** [comment]
我觉得OK

**Comment by MitsuhaMiyamizu** [comment]
我觉得OK

**Comment by shankerwangmiao** [comment]
已经完成同步
