### ISSUE TITLE
建议增加Golang下载镜像

### ISSUE THREAD

**Issue by yanghuxiao** [tuna/issues#332]
#### 项目名称与简介(Project Intro.)
Golang
#### 上游地址与镜像方法(How to Mirror)
https://golang.org/dl/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
貌似这个要想可靠地枚举所有的包之类的有些困难。

不过好像国内已经有镜像了：https://golangtc.com/download

**Comment by erdong** [comment]
上边的地址今天看失效了。

有需要的可以看一下这个地址  https://studygolang.com/dl

**Comment by z4yx** [comment]
USTC 也有的 https://mirrors.ustc.edu.cn/golang/
