### ISSUE TITLE
再次同步的时候出现了一个错误

### ISSUE THREAD

**Issue by chrindex** [tuna/issues#333]
在breakfast find7s的时候出现了一个错误：
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/oppo/find7s/lineage.mk]]: "device/oppo/msm8974-common/msm8974.mk" does not exist。 停止。
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/oppo/find7s/lineage.mk]]: "device/oppo/msm8974-common/msm8974.mk" does not exist。 停止。
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/oppo/find7s/lineage.mk]]: "device/oppo/msm8974-common/msm8974.mk" does not exist。 停止。
Device find7s not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oppo_find7s
Default revision: cm-14.1
Checking branch info
Checking if device/oppo/find7s is fetched from android_device_oppo_find7s
LineageOS/android_device_oppo_find7s already fetched to device/oppo/find7s
Syncing repository to retrieve project.
Fetching project LineageOS/android_device_oppo_find7s
Fetching projects: 100% (1/1), done.  

Repository synced!
Looking for dependencies in device/oppo/find7s
Looking for dependencies in device/oppo/find7-common
Looking for dependencies in device/oppo/msm8974-common
Dependencies file not found, bailing out.
Done
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/oppo/find7s/lineage.mk]]: "device/oppo/msm8974-common/msm8974.mk" does not exist。 停止。
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/oppo/find7s/lineage.mk]]: "device/oppo/msm8974-common/msm8974.mk" does not exist。 停止。

** Don't have a product spec for: 'lineage_find7s'
** Do you have the right repo manifest?

因此在roomservice.xml里加入了：

`<project name="TheMuppets/proprietary_vendor_qcom_binaries" path="vendor/qcom/binaries" remote="github" revision="cm-14.1" />`
再次同步时出现如下错误，说是没有某个文件：
Fetching projects:  99% (580/585)  fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/TheMuppets/proprietary_vendor_qcom_binaries/' not found
error: Cannot fetch TheMuppets/proprietary_vendor_qcom_binaries
warn: --force-broken, continuing to sync
Fetching projects: 100% (585/585)  
error: Exited sync due to fetch errors
chrindex@chrindex-mobile:~/android/lineage$ 
——————
这个问题要如何解决呢？

**Comment by shankerwangmiao** [comment]
您好，我们镜像站仅保证被镜像数据的正确性和可访问性，没有能力解决具体软件的使用/编译问题。请您咨询相关专业人士。

从您给出的错误提示上看，应该是缺少某种组件导致的。您提到的“TheMuppets/proprietary_vendor_qcom_binaries”，经查应该指的是 https://github.com/TheMuppets/proprietary_vendor_qcom_binaries 该仓库并非 lineageos 仓库内的代码，不在镜像范围内，因此会出现 “https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/TheMuppets/proprietary_vendor_qcom_binaries/” 找不到的错误

**Comment by shankerwangmiao** [comment]
补充一句，我们给出的官方帮助里，提到将 `<remote  name="github" fetch=".."` 改成 `<remote  name="github" fetch="https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/"` 。您遇到的错误可能和这个有关。建议您补充一个 remote，name 可以取作 `real_github`，然后将您自行引入的 `TheMuppets/proprietary_vendor_qcom_binaries` 的 remote 改为 `real_github` 应该可以 work around 这个问题

**Comment by chrindex** [comment]
已按楼上方法解决
