### ISSUE TITLE
微软产品镜像源申请

### ISSUE THREAD

**Issue by HalfLegend** [tuna/issues#335]
#### 项目名称与简介(Project Intro.) 

微软现在有很多产品已经可以跨平台部署 支持各种linux发布版本，比如 sql-server 和 dot net
相信不少人已经在用这些产品  

##### 上游地址：_https://packages.microsoft.com_
>比如 dotnet和odbc位置：_https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/_ 
>比如 sql-sverer位置: _https://packages.microsoft.com/rhel/7/mssql-server/_

##### 镜像方法: 直接同步
如果用户需要使用，则把repo文件中的 _packages.microsoft.com_ 改为 _tuna镜像源地址_ 即可
#### 其他信息(Other)
- 镜像大小(Mirror Size):  未知

**Comment by Harry-Chen** [comment]
呃，我们不清楚微软的版权政策是不是允许我们做镜像

**Comment by shankerwangmiao** [comment]
而且还有问题是，我们镜像的东西，并不完全是根据用的人多不多来的。我么也要考虑访问的便捷性。比如这个要是在国内下载的速率没什么太大问题的话，我们就不会镜像了。

不过不知道能不能找到 rsync 的地址，如果能给 rsync 的话，顺手镜像一下也不是啥大问题。

**Comment by HalfLegend** [comment]
微软的软件源速度倒是还可以 我这边可以到1 - 2MB/s  (tuna大概在4MB/s)

**Comment by sztsian** [comment]
我没找到官方的。我看到docker上的有[要求同意EULA](https://hub.docker.com/r/microsoft/mssql-server-linux/)。我没找到官方的EULA网页，但找到了[这么一个](https://documentation.commvault.com/commvault/v11/article?p=features/misc/ms_sql_server_eula.htm)，里面说了 

> You may not
> ......
>*  make more copies of the software than specified in this agreement or allowed by applicable law, despite this limitation;
>*  publish the software, including any application programming interfaces included in the software, for others to copy;

据此我的理解是不能镜像。

**Comment by Harry-Chen** [comment]
@sztsian 多谢！不过你找到的那个应该是 MSSQL Server for Windows 的 EULA，之前我了解到 for Linux 的版本 EULA 不太一样。不过在有明确许可之前我们可能只能搁置这件事情

**Comment by sztsian** [comment]
我没能成功找到~for Linux的EULA

**Comment by Harry-Chen** [comment]
Neither can I. 我觉得不管做不做镜像可以去问一下，好像没什么人知道的样子

**Comment by Harry-Chen** [comment]
正在咨询相关事宜，但是希望不大

**Comment by 210hcl** [comment]
vscode的下载（这货用的人很多）已经受gfw影响很厉害了，还请您确认下能否同步。

**Comment by shankerwangmiao** [comment]
不出意外的话，应该是不能，参见 https://code.visualstudio.com/License/ 第 5 条第 4 点。

**Comment by jiegec** [comment]
也没有观察到vscode下载受到了任何影响，一直非常快速。

**Comment by Harry-Chen** [comment]
UPDATE: 我之前给微软开源相关部门的邮件未得到答复

**Comment by z4yx** [comment]
考虑下这个？
https://github.com/VSCodium/vscodium

**Comment by hg-zt** [comment]
还是希望能考虑一下，现在在一些线路上 code 下载速度很慢。

https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo 这里有一个已经做好的 VSCodium deb/rpm 源

**Comment by phy25** [comment]
> 还是希望能考虑一下，现在在一些线路上 code 下载速度很慢。

印象中 VSCode 的分发域名是有国内 CDN 的（vscode.cdn.azure.cn - https://blog.csdn.net/mingyueyixi/article/details/88653786）。不过不大清楚 packages.microsoft.com 这个提供仓库的域名有没有 CDN。

**Comment by z4yx** [comment]
VS Codium 安装包已同步，可以在镜像站"获取下载链接”处下载。

**Comment by athrunsun** [comment]
@z4yx VSCodium无法使用微软官方的C#扩展，remote扩展套件也不行。

**Comment by microestc** [comment]
中国需要 dotnet-sdk 3.1+ 的镜像,感谢支持

**Comment by ossphil** [comment]
https://packages.microsoft.com/很慢很慢

**Comment by youchennew** [comment]
packages.microsoft.com 在国内一些地区已经出现了频发的DNS污染以及阻断。使用确实受阻。

**Comment by Harry-Chen** [comment]
基于 #741 中的以下条目，本请求将不会被接受：

> * 由于版权、许可证等因素不能镜像
> * 以国内访问速度缓慢为由提出镜像请求的
