### ISSUE TITLE
一键换用 TUNA 镜像

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#337]
提供一个脚本，自动检测常用的包管理器（apt, pip, homebrew 等）并一键改用 TUNA 镜像。不用做的很全，也不用考虑特殊情况（比如特殊的配置文件路径等情况），满足最常见的需求即可。

将来可以做成“上游管理器”之类的东西。

Principle: Keep it simple and stupid

**Comment by jiegec** [comment]
用什么语言啊（
千万别bash

**Comment by xavieryao** [comment]
我不会用 bash。讨论了一下决定用兼容 py3 的 py2

**Comment by xavieryao** [comment]
See https://github.com/tuna/oh-my-tuna

**Comment by dotkrnl** [comment]
track this issue in https://github.com/tuna/oh-my-tuna/issues
