### ISSUE TITLE
镜像请求 linux-next.git

### ISSUE THREAD

**Issue by FlyGoat** [tuna/issues#338]
#### 项目名称与简介(Project Intro.)
linux-next.git 是Stephen Rothwell维护的内核树，主要用与接受及试验即将进入主线内核的代码。
内核开发者在提交新feature的patch之前一般会rebase到这个内核树

#### 上游地址与镜像方法(How to Mirror)
git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
约2GB

**Comment by Harry-Chen** [comment]
已经加入了我们的同步列表，不过目前遇到一些问题，正在解决中，请耐心等待

**Comment by Harry-Chen** [comment]
同步已完成，有待加入使用帮助。
