### ISSUE TITLE
kubernates 的 docker 镜像仓库 k8s.gcr.io (Google Cloud Registry (GCR))

### ISSUE THREAD

**Issue by loverto** [tuna/issues#339]
#### 项目名称与简介(Project Intro.)
kubernates 的 docker 镜像仓库 k8s.gcr.io(Google Cloud Registry (GCR))
#### 上游地址与镜像方法(How to Mirror)
k8s.gcr.io 应该类似于docker官方的镜像仓库第同步方式,不是yum安装的,是docker镜像
#### 其他信息(Other)
- 镜像大小(Mirror Size): 

@scateu

**Comment by shankerwangmiao** [comment]
对于类似这种无法穷尽地枚举要镜像的内容的，我们一般情况下不予镜像，请理解。

**Comment by loverto** [comment]
是因为k8s.gcr.io太大了么?

**Comment by loverto** [comment]
docker的镜像你们不都同步了么?

**Comment by bigeagle** [comment]
docker 镜像并没有同步呢

**Comment by loverto** [comment]
我用的docker镜像就是清华同步的啊  这个地址,https://docker.mirrors.ustc.edu.cn/,很好用的呢

**Comment by xavieryao** [comment]
您搞错了，这是隔壁中科大的镜像。http://mirrors.ustc.edu.cn

在 2018年1月30日，上午9:21，flydragon <notifications@github.com<mailto:notifications@github.com>> 写道：


我用的docker镜像就是清华同步的啊 这个地址,https://docker.mirrors.ustc.edu.cn/,很好用的呢<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocker.mirrors.ustc.edu.cn%2F%2C%25E5%25BE%2588%25E5%25A5%25BD%25E7%2594%25A8%25E7%259A%2584%25E5%2591%25A2&data=02%7C01%7C%7Ceb61f3234dd545f4f84108d5677fbe7d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636528720710463296&sdata=JdLdJI05X4RSnKFmyq%2Fn64zcTZIzZPpbE1FQKjT1EZ0%3D&reserved=0>

**Comment by loverto** [comment]
抱歉
