### ISSUE TITLE
goldfish kernel

### ISSUE THREAD

**Issue by suyiping** [tuna/issues#34]
**如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写**

**If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.**

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
try this:

```
git clone https://aosp.tuna.tsinghua.edu.cn/kernel/goldfish
```

**Comment by bigeagle** [comment]
请尊重我们的工作。
