### ISSUE TITLE
关于使用ipv6访问镜像站的问题

### ISSUE THREAD

**Issue by trollchu** [tuna/issues#340]
您好，我来自北京理工大学，以前使用tuna的anaconda镜像下载软件速度可以到1Mb/s，而近期使用tuna的ubuntu和pip的源速度只有100Kb/s，我猜测可能是使用的ipv4通道，于是参考网上资料将源文件中的mirror改为mirror6，这样反而根本无法update了，请问如何达到较高的下载速度？

Thanks♪(･ω･)ﾉ

**Comment by shankerwangmiao** [comment]
请用 mirrors6
