### ISSUE TITLE
bandersnatch 不包含 data-requires-python 标签

### ISSUE THREAD

**Issue by matinjugou** [tuna/issues#341]
安装了一天tf都没成功，换了豆瓣源一下子就搞定了，可能源有问题或者没更新或者被魔改了？请检查一下。

**Comment by xavieryao** [comment]
我试了一下没有问题 🙈 （macOS + Python 3.6）你先确认一下之前的命令有没有问题？希望你能复现一下并提供更多信息，最好能有 pip 安装失败的输出，以便我们进一步排查，麻烦啦！

**Comment by xavieryao** [comment]
等等 我也遇到了这个问题

**Comment by xavieryao** [comment]
参见这个 issue: https://github.com/tensorflow/tensorboard/issues/916 。

**Comment by xavieryao** [comment]
仿佛是 Google 在打包的时候用的 setuptools 有 bug

**Comment by lspvic** [comment]
tuna是存在问题的，tuna和pypi官方的行为不一致，问题大致是这样：

`tensorflow-tensorboard`里面有个依赖`futures>=3.1.1`，最新版本的`futures`是3.2.0，然而`futures`的3.2.0放弃了对python3的支持（3.1.1支持）, 使用tuna的安装源在python3 安装`tensorflow-tensorboard`的时候会下载`futures`3.2.0版本，因此直接会出错，  **但用pypi官方源的时候，会下载`futures`的3.1.1版本，应该是官方源检测到了3.2.0不支持**， 在 https://pypi.python.org/pypi/futures/3.2.0 ，可以看到 `Requires Python: >=2.6, <3` . 而tuna只是会下载最新版本的3.2.0, 似乎不会检测python版本，如果如@matinjugou 说的，豆瓣源没有出现问题的话，豆瓣源的行为应该和官方是一致的

tensorflow-tensorboard的问题也是存在的

@xavieryao 
不知道issue关闭了还能不能收到消息

**Comment by xavieryao** [comment]
pypi 居然这么复杂，我们再研究一下

**Comment by xavieryao** [comment]
@shankerwangmiao 我们的 PyPi 镜像不会 expose 一些 metadata

https://github.com/tensorflow/tensorboard/issues/916#issuecomment-361967402

**Comment by xavieryao** [comment]
这个问题的原因有二。

首先，打包最新版 `tensorflow-tensorboard` 的时候用的 `setuptools` 有 bug 导致对 Python 版本的要求被忽略了 [1]。

其次，PyPI 的镜像 ( https://pypi.python.org/simple/futures/ ) 返回的 `<a>` 标签里会有 `data-requires-python="&gt;=2.6, &lt;3"`，`pip` 会根据这个属性选择要不要下载 [2]，但我们的镜像里没有这个标签。

我们服务器端的同步使用 PyPA 官方的工具 [bandersnatch](https://bitbucket.org/pypa/bandersnatch)，无论是 bandersnatch 还是关于架设镜像的 [PEP](https://www.python.org/dev/peps/pep-0381/) 都没有考虑 `data-requires-python` 标签的问题。暂时没有想到 quick fix 的办法，目前能做的只有向 bandersnatch 和 Python 社区提 issue。

因为打包旧版 `tensorflow-tensorboard` 的时候没有受第一点原因所述 bug 的影响，所以旧版的 `tensorflow` 不会在 Python 3 的环境中下载 `futures` 。这是豆瓣镜像可以正常使用的原因。

[1] https://github.com/pypa/setuptools/pull/1081
[2] https://www.python.org/dev/peps/pep-0503/

**Comment by xavieryao** [comment]
感谢 @matinjugou 和 @lspvic

**Comment by matinjugou** [comment]
66666，你们发现问题了就好


| |
黄超
邮箱：thss15_huangc@163.com
|

签名由 网易邮箱大师 定制

在2018年02月01日 03:27，Xavier Yao 写道：

感谢 @matinjugou 和 @lspvic

**Comment by xavieryao** [comment]
See: https://github.com/pypa/bandersnatch/issues/68

**Comment by zzh1996** [comment]
现在 bandersnatch 的 master 分支已经支持这个特性了，tuna 镜像要不要更新一下

**Comment by huiyiqun** [comment]
我们修的…已经用上了

Zihan Zheng <notifications@github.com> 于 2019年3月28日周四 上午1:32写道：
