### ISSUE TITLE
Lineage代码同步问题

### ISSUE THREAD

**Issue by huanghe2015** [tuna/issues#345]
望修改Lineage的default.xml，将<remote  name="aosp" ...../>的部分切换到清华源上。
每次repo init完之后，都得要手动修改才能继续repo sync，感觉挺麻烦的，谢谢啦！

**Comment by Harry-Chen** [comment]
作为一个镜像站，我们一般不对上游提供的任何文件进行任何修改，而是照原样(as-is)地提供，敬请知悉。给您带来的不便敬请理解。

**Comment by Harry-Chen** [comment]
在我们的镜像站首页上，'lineageOS'名字的右侧有帮助图标。我们提供了相关的帮助页面: https://mirrors.tuna.tsinghua.edu.cn/help/lineageOS/

**Comment by huanghe2015** [comment]
哦哦
