### ISSUE TITLE
archlinux镜像同步问题

### ISSUE THREAD

**Issue by kosmosoahc** [tuna/issues#346]
- Service Issues 服务故障
-------------
### 1
![1](https://user-images.githubusercontent.com/20462172/36132128-67d754da-10b0-11e8-832b-c202dabb25e5.PNG)
![2](https://user-images.githubusercontent.com/20462172/36132140-76c49a84-10b0-11e8-8f1e-74f1cba03b8c.PNG)
-------------
### 2
![3](https://user-images.githubusercontent.com/20462172/36132315-72acf5bc-10b1-11e8-8a9b-e2a0d50338e3.PNG)
![4](https://user-images.githubusercontent.com/20462172/36132474-86000888-10b2-11e8-8d90-bacf6ebe32ab.PNG)
------------------------------------
# 问题
- 1图中的时间是十点十分，镜像最后同步于八点半
- 2图中的时间为十点五十，镜像最后同步时间为七点半
- 注意对比 archlinux 源中 Testing 的最后升级日期
- 我这边宽带是下游的USTC为佳，6M/s
- USTC镜像是基本隔一小时同步一次上游tuna，问题在于我今天早上九点看的时候ustc中的testing是同步了你们tuna的八点半的镜像，那时archlinux出了 linux 4.15.3-1，在testing里面有此包；但是到了十一点ustc再次同步上游tuna镜像的时候，testing同步的时间却变为了凌晨三点，里面 linux 的包也没有了。因为 archlinux 把 linux 放进testing的时间时早上八点，你们tuna的镜像不知为什么再次同步源的时候同步的是你们自己上个已同步了的镜像。
- 虽然问题不大，只需要等待你们tuna再次更新镜像，ustc一小时后同步回来就好。但是这种镜像同步时间倒回现象应该是出现了好几次了，我想知道这是tuna上游的问题，还是其他原因？

**Comment by kosmosoahc** [comment]
## 再看图
--------------------------------------------
### 1
![6](https://user-images.githubusercontent.com/20462172/36134121-ab253cea-10bd-11e8-8d9b-b5d8456431a2.PNG)
![5](https://user-images.githubusercontent.com/20462172/36134125-b1efa8e4-10bd-11e8-8eb1-5abd0d5e03e1.PNG)
---------------------------------------------
### 2
![8](https://user-images.githubusercontent.com/20462172/36134149-d233b8e8-10bd-11e8-9ed8-6261e84ee84a.PNG)
![7](https://user-images.githubusercontent.com/20462172/36134167-ee70c3f2-10bd-11e8-8502-5d5fd3835b10.PNG)
----------------------------------------------
# 问题
- 1图中的时间是十二点，镜像最后同步于十一点半（UTC时间+8小时时差）
- 2图中的时间为下午一点，镜像最后同步时间为八点半（UTC时间+8小时时差）
- ustc镜像archlinux源Testing中的 **cgrep** 1图为 6.6.22.17，时间是十二点
- ustc镜像archlinux源Testing中的 **cgrep** 2图为 6.6.22.16，时间是一点左右
- ustc在十二点时候同步了上游tuna的十一点半左右更新的镜像，但是tuna在之后却把十一点半更新的镜像退回到早上八点半的镜像，不知道是不是因为镜像同步错误的原因，但是ustc是已经同步了十一点半的镜像，在十二点五十ustc再次更新镜像的时候，tuna的镜像变成了八点半的镜像，ustc同步是也退回到之前的镜像，导致源Community中的包 **cgrep** 在下午一点更新的版本比在中午十二点更新的版本低。

**Comment by jiegec** [comment]
这个大概是因为我们后台有两台同步服务器。

**Comment by gaoyichuan** [comment]
我们的服务由两台服务器提供，两台服务器同步上游的时间各自独立，因此会出现数据不一致的情况。目前 ustc 已经将上游显式指定为其中一台服务器，因此这一问题已经解决。

**Comment by shankerwangmiao** [comment]
这个问题是有俩服务器在独立同时提供服务造成的。之前我们已经采取针对 http 404 的请求反代到对方服务器的措施，缓解了服务器不一致造成的问题，详见 #232

目前我们会考虑其他的方法来进一步处理该问题，相关讨论转至 #232，本 issue 暂时关闭。
