### ISSUE TITLE
Fuchsia OS 镜像申请

### ISSUE THREAD

**Issue by dodola** [tuna/issues#347]
#### 项目名称与简介(Project Intro.)
Fuchsia 是 google 开发的一套新的操作系统

#### 上游地址与镜像方法(How to Mirror)
官方网站：https://fuchsia.googlesource.com/docs/+/master/README.md
github 地址：https://github.com/fuchsia-mirror
镜像方法：
Fuchsia 采用 [jiri](https://fuchsia.googlesource.com/jiri)来管理源码，镜像方法和 AOSP 差不多

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
dup with #409
