### ISSUE TITLE
请求镜像 gitlab-ee

### ISSUE THREAD

**Issue by larryli** [tuna/issues#348]
#### 项目名称与简介(Project Intro.)

GitLab 官方[建议即使不打算申请 EE 许可证的用户也直接使用 EE 版本](https://about.gitlab.com/installation/ce-or-ee/)。默认的 Omnibus 安装文档也是 EE 版本。

#### 上游地址与镜像方法(How to Mirror)

同 [gitlab-ce](https://mirrors.tuna.tsinghua.edu.cn/help/gitlab-ce/)。

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by georgexsh** [comment]
看起来只是因为官方希望售卖 EE 许可更方便，没有提到其他技术/功能/维护上的好处。

**Comment by shankerwangmiao** [comment]
done
