### ISSUE TITLE
PPA 镜像申请

### ISSUE THREAD

**Issue by bqsgwys** [tuna/issues#350]
#### 项目名称与简介(Project Intro.)
PPA : ubuntu 个人源
#### 上游地址与镜像方法(How to Mirror)
ppa.launchpad.net
https://gist.github.com/hvnsweeting/0a70841e5152cbb24eec
#### 其他信息(Other)
- 镜像大小(Mirror Size): 200G+

**Comment by shankerwangmiao** [comment]
Ubuntu 的 PPA，由于不能枚举所有的 PPA 源，因此无法镜像。
