### ISSUE TITLE
fedora 和 fedora-altarch(-secondary) 请注册到 fedora mirrormanager

### ISSUE THREAD

**Issue by cheese** [tuna/issues#352]
Fedora 具有 mirrorlist 机制，只有注册到 fedora mirrormanager https://admin.fedoraproject.org/mirrormanager ，才会解析要具体的镜像站
目前中国已有一些镜像站注册了，但 tuna 镜像没有：
https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/28/x86_64

**Comment by shankerwangmiao** [comment]
已经添加
