### ISSUE TITLE
Raspbian说明页问题

### ISSUE THREAD

**Issue by xaengceilbiths** [tuna/issues#353]
1. 页面 https://mirrors.tuna.tsinghua.edu.cn/help/raspbian/ 有些内容没有更新：stretch已经出了，也有镜像，建议说明页上加上去
2. raspbian除了需要修改/etc/apt/sources.list，还要改/etc/apt/sources.list.d/raspi.list。

**Comment by shankerwangmiao** [comment]
您可想 https://github.com/tuna/mirror-web 直接提交 PR，我们会考虑您的修改意见。
