### ISSUE TITLE
cygwin现在支持https了

### ISSUE THREAD

**Issue by wangqr** [tuna/issues#356]
在[Cygwin帮助页](https://mirrors.tuna.tsinghua.edu.cn/help/cygwin/)说`Cygwin貌似不支持使用https`，但经测试现在的setup-x86.exe和setup-x86_64.exe（在win10 build 16299下）均能够正常使用https镜像进行安装和更新。而且[官方维护的镜像列表](https://cygwin.org/mirrors.html)中也存在使用https的镜像。

因此希望对帮助页进行相应的修改。相关：#44

**Comment by Harry-Chen** [comment]
感谢指出！如果您愿意帮助我们的话，亦可以提出 pull request，是 tuna/mirror-web 这个仓库。

**Comment by wangqr** [comment]
Ref: tuna/mirror-web#88

**Comment by shankerwangmiao** [comment]
merged
