### ISSUE TITLE
Add Flutter Mirror

### ISSUE THREAD

**Issue by OuSatoru** [tuna/issues#357]
#### 项目名称与简介(Project Intro.)
Flutter
A new mobile app SDK to help developers and designers build modern mobile apps for iOS and Android. Flutter is an alpha, open-source project.
#### 上游地址与镜像方法(How to Mirror)
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

> If you’re interested in setting up your own mirror in China, please contact flutter-dev@googlegroups.com for assistance

#### 其他信息(Other)
a currently usable site: https://pub.flutter-io.cn/
- 镜像大小(Mirror Size):

**Comment by chenglu** [comment]
Flutter 是非常火热的移动跨平台解决方案之一，由 Google 开源，由 Flutter 开发的应用可以直接编译成 ARM 代码运行在 Android 和 iOS 系统上。Flutter 使用 Dart 开发，围绕其相关的镜像源（上游）地址如下：

Flutter Storage 镜像，上游是几个 GCS Bucket，空间大约 200 G 左右：
- https://storage.googleapis.com/flutter_infra
- https://storage.googleapis.com/dart-archive
- https://storage.googleapis.com/flutter-catalog
- https://storage.googleapis.com/pub-packages
- https://storage.googleapis.com/download.dartlang.org

Flutter 的生态离不开 Flutter Package Site，所以另外一个镜像是 Dart Package Site 的镜像，
其上游地址是：https://pub.dartlang.org/ 
如果上面的地址有问题，或者可以试试看 https://dartlang-pub.appspot.com/

针对 Dart Package Site 的镜像有**两个地方**需要注意：

一、Flutter 的 Cli 会通过这个 Site 进行 API 调用，需要对镜像源地址的类似 application/json 的返回值做 filter：
- 将 storage.googleapis.com 替换为咱们的 Flutter Storage 镜像
- 将 pub.dartlang.org 替换为咱们的 Dart Package Site 的镜像地址

例如：https://pub.dartlang.org/api/packages/flutter_native_timezonev2
需要确保输出的 JSON 字块儿里，类似 archive_url 里的 pub.dartlang.org 均被替换为镜像地址。

二、对 Package Site 要做 proxy_redirect 设定：

类似 archive_url 里的下载地址，镜像去上游取内容的时候，上游会直接返回 GCS 的下载地址：https://pub.dartlang.org/packages/flutter_native_timezonev2/versions/1.0.2.tar.gz

在 Nginx 里，可能需要对 Package Site 像站做如下设定：
proxy_redirect          https://storage.googleapis.com/     Flutter Storage 镜像 URL;

完整的 Nginx 代码类似：

```

subs_filter_types       application/json text/xml text/css text/js text/javascript;
proxy_set_header        Accept-Encoding '';
proxy_pass              https://dartlang-pub.appspot.com/;
subs_filter             storage.googleapis.com              {Flutter Storage 镜像};
subs_filter             pub.dartlang.org                    {Dart Package Site 的镜像};
subs_filter             dartlang-pub.appspot.com            {Dart Package Site 的镜像};

proxy_redirect          https://pub.dartlang.org/           {Dart Package Site 的镜像};
proxy_redirect          https://storage.googleapis.com/     {Flutter Storage 镜像};
proxy_set_header        X-Real-IP                           $remote_addr;
proxy_set_header        X-Forwarded-For                     $proxy_add_x_forwarded_for;
proxy_set_header        Host                                "dartlang-pub.appspot.com";

```

**Comment by jiegec** [comment]
@chenglu 请问这些 GCS Bucket 可以用类似 rsync 的方式同步而不是反代吗？

**Comment by chenglu** [comment]
抱歉我不是特别清楚，原生似乎是不支持的。
可以问问咱们同步 TensorFlow 镜像的小伙伴，这个解决方案应该可以有参考性。

**Comment by shankerwangmiao** [comment]
@chenglu 抱歉，我们已经不再同步 tensorflow 了。因为 pypi 里已经有了。

**Comment by chenglu** [comment]
@shankerwangmiao 感谢告知，也谢谢为 TF 做出的贡献。

现在的问题是 Dart Package Site 的镜像 肯定需要反代作为解决方案，Flutter Storage 镜像可能仍然需要 rsync 或者类似 rsync 的解决方案，抱歉这部分我不是特别的行家，我搜到了几个方案说：

- [gsutil rsync](https://cloud.google.com/storage/docs/gsutil/commands/rsync)
- [rclone](https://github.com/ncw/rclone)

不知道以上这些是否具备参考价值？
谢谢！

**Comment by z4yx** [comment]
镜像已添加:
https://mirror.tuna.tsinghua.edu.cn/flutter/
https://mirror.tuna.tsinghua.edu.cn/dart-pub/

使用方式:
```bash
export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub/"
```

鸣谢
为了镜像dart pub，惠老师开发了 https://github.com/huiyiqun/pub-mirror 同步工具
