### ISSUE TITLE
请求镜像 chef

### ISSUE THREAD

**Issue by georgexsh** [tuna/issues#358]
#### 项目名称与简介(Project Intro.)

chef 是一个 IT 配置管理自动化工具，许可证为 Apache-2.0。

#### 上游地址与镜像方法(How to Mirror)

上游文档 https://docs.chef.io/packages.html 它分 stable 和 current 两个 channel，应该只需要镜像 stable channel

- yum: https://packages.chef.io/repos/yum/stable/ 
- apt: https://packages.chef.io/repos/apt/stable/

镜像方法官方没有说明，~~猜测~~官方回复可以用 reposync 之类。

#### 其他信息(Other)
- 镜像大小(Mirror Size):  [只算 yum stable](https://gist.github.com/georgexsh/8c6edf59506ce3e826b68446424ba4fa) 大小是 329 GB，apt 应该相仿
- GPG 公钥：https://packages.chef.io/chef.asc

**Comment by z4yx** [comment]
已添加该镜像
