### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#36]
#### 项目名称与简介(Project Intro.)
nodejs 包仓库

#### 镜像方法(How to Mirror)
使用 cnpm + fs-cnpm 应该就可以，
https://github.com/cnpm/cnpmjs.org
https://github.com/cnpm/fs-cnpm

#### 其他信息(Other)
- 镜像大小(Mirror Size):  300G 估计够了吧……

现有的 sinopia 实在是太慢了

**Comment by bubbleatgit** [comment]
你自己怎么还要提个issue- -

**Comment by bigeagle** [comment]
留着怕忘
