### ISSUE TITLE
repo同步lineageos失败

### ISSUE THREAD

**Issue by dksslq** [tuna/issues#362]
按照https://mirrors.tuna.tsinghua.edu.cn/help/lineageOS/页面下的知道进行repo sync，结果出现好多503错误，例如fatal :  unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/libopus/' :  The requested URL returned error: 503

请问这是什么原因造成的？，线程默认j4，网络也正常，我可以配合你们，但是希望快速解决

我同步的lineageos版本是15.1

**Comment by huiyiqun** [comment]
```ancient :: ~ » git clone https://aosp.tuna.tsinghua.edu.cn/platform/external/libopus/
Cloning into 'libopus'...
remote: Counting objects: 1485, done.
remote: Compressing objects: 100% (1290/1290), done.
remote: Total 1485 (delta 645), reused 713 (delta 188)
Receiving objects: 100% (1485/1485), 1.98 MiB | 8.31 MiB/s, done.
Resolving deltas: 100% (645/645), done.
```

**Comment by dksslq** [comment]
难道是昨晚服务器同步导致的？

**Comment by huiyiqun** [comment]
你试试我那个命令，如果出问题了贴一下日志，如果成功了那就再跑一下 `repo sync` 试试。

**Comment by dksslq** [comment]
嗯嗯，非常感谢！

**Comment by dksslq** [comment]
初始化仓库:

repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git -b cm-14.1

url https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android.git 报错404

**Comment by dksslq** [comment]
我像你那样单独用git clong可以成功，但是用repo sync始终报错 503
Fetching project LineageOS/android_hardware_qcom_media MiB/s
Fetching project platform/external/rmi4utils
remote: Total 17383 (delta 12716), reused 17117 (delta 12467)
Receiving objects: 100% (17383/17383), 9.40 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (12716/12716), done.00 KiB | 183.00 KiB/s   s
From https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_external_selinux
 * [new branch]        lineage-15.1 -> github/lineage-15.1
Fetching project platform/external/hamcrest71 MiB | 229.00 KiB/s
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/hamcrest/': The requested URL returned error: 503
remote: Counting objects: 11765, done.         208.00 KiB/s   /s
remote: Compressing objects: 100% (3034/3034), done.
error: Cannot fetch platform/external/webpB | 403.00 KiB/s   0 KiB/s
Fetching project LineageOS/android_packages_apps_Updater
remote: Counting objects: 1831, done.        KiB | 137.00 KiB/s   /s
remote: Compressing objects: 100% (530/530), done.
remote: Total 1831 (delta 939), reused 1416 (delta 736)            s
Receiving objects: 100% (1831/1831), 293.93 KiB | 173.00 KiB/s, done.
Resolving deltas: 100% (939/939), done.24.81 MiB | 214.00 KiB/s
From https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_packages_apps_Updater
 * [new branch]      lineage-15.1 -> github/lineage-15.1
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/pdfium/': The requested URL returned error: 503
error: Cannot fetch platform/frameworks/rs39 MiB | 274.00 KiB/s    s
remote: Total 11765 (delta 8846), reused 11519 (delta 8669)        s
Receiving objects: 100% (11765/11765), 4.15 MiB | 455.00 KiB/s, done.
Resolving deltas: 100% (8846/8846), done.MiB | 395.00 KiB/s   s    s
可能是repo脚本本身的问题吧

**Comment by Liberations** [comment]
repo sync -c -f -j1 --force-sync --no-clone-bundle 注意这个j1

**Comment by huiyiqun** [comment]
嗯 加个 -j1 试试 多线程日志乱七八糟的。。没法看

**Comment by shankerwangmiao** [comment]
hi，可以确认是连接数限制导致的。针对于 AOSP 我们目前单个 IP 限制 8 个连接。虽然您的连接数可能没有超过该限制，但是不排除您是在 NAT 网关之后，且您的出口 IP 地址对我们站的连接数超过了此限制。建议您调小 -j 的值，或者错峰同步。

**Comment by dksslq** [comment]
感谢各位大佬指导，问题已解决

**Comment by yangfan069** [comment]
> 感谢各位大佬指导，问题已解决

你好麻烦问一下怎么解决的  调整下载线程数吗？

**Comment by songyuan136386** [comment]
接收对象中:  25% (3629/14171), 53.50 MiB | 97.00 KiB/s   
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败

error: Cannot fetch platform/prebuilts/tools from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/tools
Fetching: 99% [7 jobs] (776/782) finished platform/prebuilts/tools
请问一下各位，同步 lineageos 出现这个有没有什么好的办法

**Comment by NorthStar1226** [comment]
怎么解决的啊，我也一直报503，糟心啊

**Comment by shankerwangmiao** [comment]
> 怎么解决的啊，我也一直报503，糟心啊

503 是因为服务器有单个 IP 并发量限制，请您减少并发量。

**Comment by NorthStar1226** [comment]
> > 怎么解决的啊，我也一直报503，糟心啊How did it work? I keep calling 503. It sucks
> 
> 503 是因为服务器有单个 IP 并发量限制，请您减少并发量。
> 
> 503 is because the server has a single IP concurrency limit, please reduce the concurrency.
好的，晚上回去我试试，非常感谢

**Comment by boreboluomi** [comment]
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
error: Cannot fetch LineageOS/android_cts from https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_cts

**Comment by shankerwangmiao** [comment]
> error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. fatal: The remote end hung up unexpectedly fatal: 过早的文件结束符（EOF） fatal: index-pack 失败 error: Cannot fetch LineageOS/android_cts from https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_cts

这因为您到 TUNA 的网络连接突然意外中断所致。建议您更换网络环境再试一次。
