### ISSUE TITLE
 申请 Chromium Source Code 镜像

### ISSUE THREAD

**Issue by jingjingxyk** [tuna/issues#365]
##  chromium 浏览器源码
   chromium 浏览器源码

##  上游地址与镜像方法(How to Mirror)
 官方网站： https://www.chromium.org
源码地址：
```
 git clone https://chromium.googlesource.com/chromium/src
```

##  其他信息(Other)
- 镜像大小(Mirror Size):    2018-04-03T00:28:29+08     git master 大小  5.3GB
- 代码预览： https://codereview.chromium.org
- 项目状态 :  http://chromium-status.appspot.com/status
- Chromium Main Console：  https://ci.chromium.org/p/chromium/g/main/console
- 项目文档：  docs/README.md
- 开源许可证： BSD  (Berkeley Software Distribution)
- chromium-browser-snapshots 二进制： https://npm.taobao.org/mirrors/chromium-browser-snapshots/

**Comment by shankerwangmiao** [comment]
dup with #138

**Comment by jingjingxyk** [comment]
https://github.com/chromium/chromium.git
