### ISSUE TITLE
Anaconda 镜像过期

### ISSUE THREAD

**Issue by gaoyifan** [tuna/issues#367]
转发两封来自USTC LUG的邮件：

>您好：
>      本人于今日更新Anaconda内部分包，发现贵镜像站所提供包有版本非最新版本，望知悉。
>
>      此致
> 
>敬礼
>Mika Lahtinen 于北京
>2018.4.5.

>尊敬的ustc lug的成员：
>你们好！我一直在使用你们的镜像服务，最近在使用你们的anaconda镜像时，一直有个疑问。即虽然网站上显示的同步时间是非常新的，但是其中很多包的版本确实和比官方的镜像版本要低（我也尝试过清华tuna的镜像，同样也是这样的情况），因此十分想知道这是什么原因，仅仅是因为正好没有及时同步吗？
>        最后，十分感谢你们的辛勤贡献给我们带来的便利！
>
>
>        此致，
>敬礼！
>
>
>r3dir3ct

**Comment by dotkrnl** [comment]
用户 `free` repo 配置问题，见 #330
