### ISSUE TITLE
Eclipse镜像申请

### ISSUE THREAD

**Issue by hhggit** [tuna/issues#369]
#### 项目名称与简介(Project Intro.)
Eclipse provides IDEs and platforms for nearly every language and architecture. We are famous for our Java IDE, C/C++, JavaScript and PHP IDEs built on extensible platforms for creating desktop, Web and cloud IDEs. These platforms deliver the most extensive collection of add-on tools available for software developers.
#### 上游地址与镜像方法(How to Mirror)
- 上游地址：download.eclipse.org 
- 镜像方法：RSYNC 详细步骤见 https://www.eclipse.org/downloads/mir_request.php
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
700GB

**Comment by shankerwangmiao** [comment]
您好，镜像已经同步完毕，在 https://mirrors.tuna.tsinghua.edu.cn/eclipse
