### ISSUE TITLE
qt内容问题检查

### ISSUE THREAD

**Issue by wiglaf1988** [tuna/issues#37]
你好我来自qt公司，想联系下站点管理员 https://mirrors.tuna.tsinghua.edu.cn/qt/  里面有许多文件缺失。
后来在irc里询问里似乎最近mirror空间有点紧张，qt有些内容被排除在外，听说你们有扩容计划，
可否留个邮件联系方式以便以后确认？多谢

**Comment by bigeagle** [comment]
现在已经是完整镜像了～
