### ISSUE TITLE
申请建立 wine-builds 镜像

### ISSUE THREAD

**Issue by njlyf2011** [tuna/issues#372]
#### 项目名称与简介(Project Intro.)
WineHQ 项目的二进制包，WineHQ  简单来说就是个在 Linux 上跑 Windows 程序的兼容层，具体可以百度。
wine-builds 在国内访问实在是太慢，故申请建立一个同步镜像。。。

#### 上游地址与镜像方法(How to Mirror)
http://dl.winehq.org/wine-builds/

镜像方法：看样子可以 rsync

**Comment by huiyiqun** [comment]
没有开 rsync 的端口，“看样子可以 rsync” 是怎么看出来的。

**Comment by abcfy2** [comment]
wine官方仓库没有提供官方的同步方案，以前有个ftp `ftp://ftp.winehq.org/pub/`可以同步，但是现在这个ftp已经找不见`wine-builds/`目录了，官方将`dl.winehq.org`网站托管在CDN `fastly.net`上，这玩意在国内基本速度为基本不上10KB/s

**Comment by Harry-Chen** [comment]
统一于 #881 追踪
