### ISSUE TITLE
请求同步 Vagrant Cloud

### ISSUE THREAD

**Issue by aunhappy** [tuna/issues#375]
目前的virtualbox源里面好像没有laravel/homestead这个源，目录似乎和[官网](https://app.vagrantup.com/boxes/search)上的不一样，希望尽快同步下，谢谢。
#### 项目名称与简介(Project Intro.)
Laravel Homestead 是一个官方预封装的 Vagrant box，它为你提供了一个完美的开发环境，而无需在本地机器安装 PHP 、Web 服务器和其他服务器软件。不用担心会搞乱你的操作系统！Vagrant boxes 是一次性的。如果出现问题，你可以在几分钟内销毁并创建 Box!
#### 上游地址与镜像方法(How to Mirror)
拿最新版本5.2.0来说，[https://app.vagrantup.com/laravel/boxes/homestead/versions/5.2.0/providers/virtualbox.box](https://app.vagrantup.com/laravel/boxes/homestead/versions/5.2.0/providers/virtualbox.box)，改versions后面的版本号就可以下不同版本的virtualbox.box
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
virtualbox Hosted by Vagrant Cloud (1.49 GB)
- 相关页面:
[https://app.vagrantup.com/laravel/boxes/homestead/versions/5.2.0](https://app.vagrantup.com/laravel/boxes/homestead/versions/5.2.0)

**Comment by huiyiqun** [comment]
Vagrant Cloud 看上去并没有提供同步同步的接口和许可。

**Comment by jingjingxyk** [comment]
docker 更方便
