### ISSUE TITLE
u-boot 同步请求

### ISSUE THREAD

**Issue by SeaflyGithub** [tuna/issues#376]
#### 项目名称与简介(Project Intro.)
项目名称：u-boot
项目简介：嵌入式开发中常用到的BootLoader

#### 上游地址与镜像方法(How to Mirror)
上游地址：
- ftp://ftp.denx.de/pub/u-boot/
- https://github.com/u-boot/u-boot/releases

镜像方法：暂无

#### 其他信息(Other)
- 镜像大小(Mirror Size): <5GB

**Comment by jiegec** [comment]
360doc...?

**Comment by huiyiqun** [comment]
没有 Meter 公司的授权，我们不会镜像他们的软件的评估版本。

u-boot 的可信上游是 [github](https://github.com/u-boot/u-boot/releases)，但是在没有合理的同步方式之前暂时不会考虑同步。
