### ISSUE TITLE
conda install失败

### ISSUE THREAD

**Issue by itiscold** [tuna/issues#377]
系统是ubuntu16.04，连接清华校内有线网。使用conda下载安装各种模块都会报下面这个错误，请问是哪里出了问题呢？
![image](https://user-images.githubusercontent.com/30709368/39230428-07607296-4899-11e8-8e46-44757c0ea15c.png)

**Comment by huiyiqun** [comment]
这个错误是你 dns 配置的问题，检查一下 /etc/resolv.conf 或 NetworkManager 的配置。

**Comment by itiscold** [comment]
修改了dns配置之后又报这个错误了，求指导
![image](https://user-images.githubusercontent.com/30709368/39393311-52751a8e-4af6-11e8-85be-1105f232b123.png)
