### ISSUE TITLE
请求添加新版本的pytorch源

### ISSUE THREAD

**Issue by xanawang** [tuna/issues#378]
#### 项目名称与简介(Project Intro.)
pytorch 0.4.0 for Windows
#### 上游地址与镜像方法(How to Mirror)
http://download.pytorch.org/whl/cu90/torch-0.4.0-cp35-cp35m-win_amd64.whl 
#### 其他信息(Other)
- 镜像大小(Mirror Size): 约600M

**Comment by huiyiqun** [comment]
官方没有提供镜像的方式，需要自己写脚本来镜像。

建议可以先用 anaconda 里的 pytorch，见[这](https://mirror.tuna.tsinghua.edu.cn/help/anaconda/#pytorch)

**Comment by xanawang** [comment]
感谢。在https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/ 目录下找到了

**Comment by peterjc123** [comment]
@huiyiqun 昨天pytorch中win-64的cuda90.tar.bz和cuda91.tar.bz没有上传，能同步一下吗？文件非常小。
