### ISSUE TITLE
大文件下载到 60M 左右停止

### ISSUE THREAD

**Issue by yangkghjh** [tuna/issues#379]
地址： https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-10.7.0-ce.0.el7.x86_64.rpm

使用wget/浏览器下载，下载到60M左右会停止继续下载。测试10.7.0和10.7.1都有这个现象。

正在测试添加源地址后使用yum安装。

**Comment by huiyiqun** [comment]
我这里（校外）可以复现这个问题，怀疑是镜像站端网络的问题？

@shankerwangmiao 求校内测试一下

**Comment by shankerwangmiao** [comment]
校内无问题，校外可复现，但是停止位置不一样

**Comment by dotkrnl** [comment]
校内限速可复现

**Comment by Harry-Chen** [comment]
感谢反映问题！我们目前能够复现这一现象，初步调查怀疑是负载均衡器带来的问题，请耐心等待进一步的结论。如果您急需使用，可以暂时切换至其他镜像。

**Comment by shankerwangmiao** [comment]
@yangkghjh 您反馈的问题对我们非常重要，目前经过排查，初步确定是负载均衡器出现了异常行为。我们已经连夜责成相关部门与设备厂家会商处理。

**Comment by huiyiqun** [comment]
目前已经定位到是LB设备厂商的问题。

**Comment by shankerwangmiao** [comment]
目前此问题已经联系 LB 厂家修复完毕。

**Comment by sztsian** [comment]
确定已经修复了么？我5月2日白天还遇到了同样问题，两个镜像分别在下载62M和64M时中断了

**Comment by huiyiqun** [comment]
@sztsian 和大小无关，这个事件的准确描述是下载到 __30s__ 之后突然 __无响应__。

中断的话应该是其他网络问题，和这个 issue 无关。
