### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by 22wei22** [tuna/issues#380]
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
PackageNotFoundError: Packages missing in current channels:         
  - cuda80
We have searched for the packages in the following channels:
            
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch

实际上我添加进来了，我的是这样的
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/

show_channel_urls: true

**Comment by dotkrnl** [comment]
cuda80 不是一个 anaconda 官方包，请到对应的用户/组织处下载。
与镜像站无关的问题，我们不提供技术支持。
（shanker 你别一言不合 spam 啊，至少说个原因）
