### ISSUE TITLE
lxc-images index先于images完成同步

### ISSUE THREAD

**Issue by abcdabcd987** [tuna/issues#382]
目前 lxc-images 的状态是 `syncing`，我使用以下命令创建 lxc 容器会报错：

```
$ lxc-create -t download -n template -- \
>     --server mirrors.tuna.tsinghua.edu.cn/lxc-images \
>     --dist ubuntu --release xenial --arch amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
ERROR: Failed to download http://mirrors.tuna.tsinghua.edu.cn/lxc-images//images/ubuntu/xenial/amd64/default/20180425_03:49//rootfs.tar.xz
lxc-create: template: lxccontainer.c: create_run_template: 1473 container creation template for template failed
lxc-create: template: tools/lxc_create.c: main: 326 Error creating container template
```

从[index文件](https://mirrors.tuna.tsinghua.edu.cn/lxc-images/meta/1.0/index-system)可以看到最新的image是：

```
ubuntu;xenial;amd64;default;20180425_03:49;/images/ubuntu/xenial/amd64/default/20180425_03:49/
```

然而 `20180425_03:49` 这个目录还没有同步下来（见<https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/xenial/amd64/default/>），因此导致了这个错误。

我在想是不是可以设置成先同步 `/lxc-images/images/`，最后再同步 `/lxc-images/meta/`？

**Comment by shankerwangmiao** [comment]
原则上来说，meta 排在在 images 后面，应该是后同步才对。。。。

**Comment by abcdabcd987** [comment]
对啊 我说的就是这个意思
╮(╯_╰)╭
是不是哪里bug了？

**Comment by shankerwangmiao** [comment]
https://github.com/tuna/tunasync-scripts/blob/master/lxc-images.sh

脚本在这里

觉得有可能是在同步过程中上游发生了变化

**Comment by dotkrnl** [comment]
我觉得是不是应该先同步 index 到一个地方，然后同步 image，然后再把之前的 index 上线上去？

**Comment by shankerwangmiao** [comment]
唔，无论是后同步 index，还是先同步 index 后上线，貌似总是无法很好处理同步过程中服务器文件发生变化的问题。应该属无解问题，多同步两次就好了。
