### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by zmy17** [tuna/issues#383]
按照说明配置了之后，使用conda install始终会报如下错误，请问是什么原因呢？求指导~
![image](https://user-images.githubusercontent.com/38806143/39393626-1740b47e-4afa-11e8-8f01-1861b8b400e7.png)

**Comment by shankerwangmiao** [comment]
从您给出的截图上看，是因为网络不通导致的 “Connection to mirrors.tuna.tsinghua.edu.cn timed out”

请排查您的主机到镜像站的网络故障。

**Comment by zmy17** [comment]
确实是网络的问题，谢谢~
