### ISSUE TITLE
在镜像站帮助中添加 Fedora 28 的支持

### ISSUE THREAD

**Issue by sprders** [tuna/issues#385]
本人的两个repo文件：

**fedora.repo:**
```
[fedora]
name=Fedora $releasever - $basearch
failovermethod=priority
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/$releasever/Everything/$basearch/os/
#baseurl=https://mirrors.aliyun.com/fedora/releases/$releasever/Everything/$basearch/os/
enabled=1
metadata_expire=28d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

**fedora-updates.repo:**
```
[updates]
name=Fedora $releasever - $basearch - Updates
failovermethod=priority
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/$releasever/Everything/$basearch/
#baseurl=https://mirrors.aliyun.com/fedora/updates/$releasever/Everything/$basearch/
enabled=1
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

其实只是文件路径发生了变化，所以只需要修改baseurl，这个变化应该是fedora28带来的。
好像国内的镜像都没有修改相应的baseurl，针对28修改baseurl

**Comment by dotkrnl** [comment]
简化一下问题：

在 Fedora 28 中的 fedora-updates.repo:

    - baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/$releasever/$basearch/
    + baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/$releasever/Everything/$basearch/

原因是:

https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/28/Everything/
https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/27/

**Comment by shankerwangmiao** [comment]
@sztsian 麻烦帮忙确认一下，这个要怎么改

**Comment by sztsian** [comment]
@sprders 你好，感谢您对 Fedora 的支持与厚爱。
为了更好地享受 Fedora 提供的服务，我建议您在软件源配置中使用 metalink 。原因可参考[这篇文章](https://fzug.github.io/2018/04/05/fedora-secures-package-delivery.html)。如果您执意使用手工指定地址的方式，恐怕您暂时需要如您所述的更改。

@shankerwangmiao 感谢 TUNA 对 Fedora 作出的贡献。我查阅了 [metalink 推送的美国的地址](https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=x86_64&country=us)，可以看到 metalink 会自动处理该变更 （对比 [Fedora 27 时的路径](https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64&country=us) ）。与此同时，我将尽快发邮件咨询相关团队。

[(tracking)](https://github.com/FZUG/issues/issues/1)
