### ISSUE TITLE
nodesource镜像更新10.x系列

### ISSUE THREAD

**Issue by pentie** [tuna/issues#387]
#### 项目名称与简介(Project Intro.)
nodesource镜像更新10.x系列
https://mirrors.tuna.tsinghua.edu.cn/nodesource/

#### 上游地址与镜像方法(How to Mirror)
deb:
https://deb.nodesource.com/node_10.x/

rpm:
https://rpm.nodesource.com/pub_10.x/

**Comment by huiyiqun** [comment]
Done
