### ISSUE TITLE
使用 Netdata 做监控

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#39]
支持实时监控，可扩展，看起来很酷

http://netdata.firehol.org/
https://github.com/firehol/netdata

**Comment by abcfy2** [comment]
我们就在用netdata做实时监控。安装部署简单，几乎0配置。

**Comment by bigeagle** [comment]
但是这货不能存太长历史

**Comment by abcfy2** [comment]
功能侧重不一样。正如netdata官方wiki描述的那样，是设计用于轻量级的实时监控，无IO开销。
