### ISSUE TITLE
开源 Pypi 镜像下载数据

### ISSUE THREAD

**Issue by wangtz** [tuna/issues#390]
非常感谢 TUNA 提供的 Pypi 镜像。是否有考虑过把一些下载数据的统计开源出来呢？这样可以方便大家分析国内开源软件的流行程度和趋势。

可以考虑把数据通过 Google Cloud Big Query 的形式展示出来，用起来也非常方便~ Global Pypi 也在 Big Query 上边开放了数据接口。这里是一个例子：https://kirankoduru.github.io/python/pypi-stats.html

**Comment by shankerwangmiao** [comment]
我们公布相关下载日志，您可以邮件 support[at]tuna[dot]tsinghua[dot]edu[dot]cn 索取。
