### ISSUE TITLE
什么时候能有freebsd 的镜像？

### ISSUE THREAD

**Issue by hackshel** [tuna/issues#392]
#### 项目名称与简介(Project Intro.)
freebsd  的项目镜像
#### 上游地址与镜像方法(How to Mirror)
https://www.freebsd.org/

具体的办法，需要参看文档
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
大小在10G左右

**Comment by shankerwangmiao** [comment]
dup with #16
