### ISSUE TITLE
anaconda无法安装python库

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#393]
在使用anaconda安装python库时遇到安装进度为0，无法安装的问题，想请教一下这是什么情况。

我们有两台服务器，在同一个网段，10服务器和11服务器。10服务器运行正常，在docker容器里安装anaconda，可以安装python库。11服务器不管在ubuntu系统下，还是docker容器下，或者conda env里，可以正常执行anaconda search和anaconda show，但conda install执行都无效，无法安装python库，log如下图。用wget命令却可以下载库文件，很困惑，不知道问题在哪。清华的镜像不会对同一网段的服务器有限制吧？

用的是这个镜像 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

![2d04f807 ae4a9631 bf96fa5a](https://user-images.githubusercontent.com/2821051/40044928-723a2bd0-585b-11e8-8c48-39d8d32f7615.jpg)

**Comment by ztwe** [comment]
The following command is ok:
conda create -n tf17_py36 python=3.6

I'm confused.
