### ISSUE TITLE
申请设立 gimp 镜像

### ISSUE THREAD

**Issue by pongfcnkl** [tuna/issues#394]
#### 项目名称与简介(Project Intro.)
GIMP，名称由GNU Image Manipulation Program（GNU图像处理程序）的首字母组成）是一个自由及开放源代码的位图图像编辑器，用于图像照片润饰及编辑、自由绘图、调整大小、裁剪、照片蒙太奇、装换图像格式以及其他专业任务。
GIMP始于1995年，使用GPLv3+，可运行于GNU/Linux、MS Windows、Mac OS X等平台，其原生文件格式的扩展名是.xcf。

#### 上游地址与镜像方法(How to Mirror)
https://download.gimp.org/

#### 其他信息(Other) 
- 镜像大小(Mirror Size): 未知

 国内传输太慢

**Comment by huiyiqun** [comment]
有 rsync，但是有访问控制。

先问一下，访问这个网站主要是什么需求？是因为 GIMP 的插件系统吗？没用过 GIMP，不太熟悉。

**Comment by jingjingxyk** [comment]
https://github.com/GNOME/gimp

**Comment by jingjingxyk** [comment]
镜像地址：https://www.gimp.org/downloads/#mirrors

**Comment by z4yx** [comment]
不再镜像，理由同 https://github.com/tuna/issues/issues/700#issuecomment-581233496

**Comment by happyaron** [comment]
GIMP可能还是有点意义，找Windows版下载发现到处都没有……
