### ISSUE TITLE
希望 增加 Debian 镜像使用帮助

### ISSUE THREAD

**Issue by vmvz** [tuna/issues#395]
#### 项目名称与简介(Project Intro.)
Debian 镜像
#### 上游地址与镜像方法(How to Mirror)
NO
#### 其他信息(Other)
- 镜像大小(Mirror Size):  NO

为了方便使用,希望可以增加 debian镜像文档

类似于: https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

**Comment by shankerwangmiao** [comment]
您好，如欲贡献帮助文档，请前往 https://github.com/tuna/mirror-web
