### ISSUE TITLE
请问是否有可能添加git和gitforwindows的使用镜像

### ISSUE THREAD

**Issue by ka-to-me-gu-mi** [tuna/issues#397]
这个应该使用人群不少吧。而且官网上下载特别特别特别慢。

**Comment by xavieryao** [comment]
git 一般不是直接用系统的包管理器，比如 apt install 吗

________________________________

**Comment by ka-to-me-gu-mi** [comment]
linux上没什么问题，只是在windows上下载git for windows 的时候，官网的下载链接经常容易打不开而且下载特别特别慢。[https://git-scm.com/download/win](url)

**Comment by huiyiqun** [comment]
git-for-windows 现在是一个托管在 github 上面的单个项目，我们暂时没有镜像这类项目的计划。

**Comment by huiyiqun** [comment]
https://npm.taobao.org/mirrors/git-for-windows/

如果确实需要可以用这个

**Comment by ka-to-me-gu-mi** [comment]
非常感谢。从官网试了各种方法都没办法完整下下来，找了很多镜像网站也没看到有收录这个的。所以比较好奇。

**Comment by alingse** [comment]
我想要镜像  git-scm 的这个。

https://mirrors.edge.kernel.org/pub/software/scm/git/

cc @shankerwangmiao 

这个我看了下，不在 https://github.com/tuna/issues/issues/741 1/2/3/4/5/6/7 里面。
