### ISSUE TITLE
pypi的同步好像出问题了？

### ISSUE THREAD

**Issue by SyrakuShaikh** [tuna/issues#399]
昨天和刚才看，“上次同步时间”都是11号，一直有“syncing”的标志。

对比了以下USTC，好多包确实更新落后了。

麻烦看一下，是不是服务出故障了。

谢谢。

**Comment by shankerwangmiao** [comment]
唔，由于最近更新的包较多，因此同步时间较长。请耐心等待。

**Comment by shankerwangmiao** [comment]
我们一直在关注这个问题，因为 pypi 的包增长较快，加上网络不甚通畅，请耐心等待。
