### ISSUE TITLE
NetBSD 镜像

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#4]
可以参考 http://www.netbsd.org/docs/mirror.html
上游列表 http://www.netbsd.org/mirrors/
使用 rsync 镜像即可，大小约 90GB (2008年9月)

**Comment by CDLuminate** [comment]
NetBSD 镜像的确少。

**Comment by Harry-Chen** [comment]
有下文吗？ @bigeagle

**Comment by bigeagle** [comment]
啊，这个已经搞定了 https://mirrors.tuna.tsinghua.edu.cn/NetBSD/

**Comment by bigeagle** [comment]
啊，这个已经搞定了 https://mirrors.tuna.tsinghua.edu.cn/NetBSD/

**Comment by bigeagle** [comment]
啊，这个已经搞定了 https://mirrors.tuna.tsinghua.edu.cn/NetBSD/

**Comment by bigeagle** [comment]
啊，这个已经搞定了 https://mirrors.tuna.tsinghua.edu.cn/NetBSD/

**Comment by Harry-Chen** [comment]
@bigeagle 不知会一下官方，让它把TUNA加入官方列表吗？

**Comment by bigeagle** [comment]
@Harry-Chen 手贱把你评论删了……

**Comment by bigeagle** [comment]
这个需要调研一下怎么加官方镜像

--
Justin Wong


On Thu, Nov 10, 2016, at 11:33, Harry Chen wrote:
> @bigeagle[1] 不知会一下官方，让它把TUNA加入官方列表吗？
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>

Links:

  1. https://github.com/bigeagle
  2. https://github.com/tuna/issues/issues/4#issuecomment-259593684

**Comment by huiyiqun** [comment]
大鹰最近好像最近经常手贱
