### ISSUE TITLE
Homebrew 好像更新不是很及时

### ISSUE THREAD

**Issue by unionx** [tuna/issues#40]
今天 31 号，但是我看好多 brew 的源都还没更新

![snip20160331_1](https://cloud.githubusercontent.com/assets/802884/14177499/1e053c4c-f789-11e5-92fa-4e44c0e9b414.png)

**Comment by bigeagle** [comment]
抱歉…… 跑 homebrew 的节点出了问题，正在修

**Comment by bigeagle** [comment]
应该fix了
