### ISSUE TITLE
请求 Canonical MAAS Images 镜像

### ISSUE THREAD

**Issue by dotkrnl** [tuna/issues#400]
#### 项目名称与简介(Project Intro.)

项目首页：https://maas.io/
镜像地址：https://images.maas.io/

Canonical 的一个项目，目的是简化物理机的部署和网络管理。同时可以对虚拟机进行统一维护。
其中，使用 PXE 进行安装引导的过程需要使用镜像文件（ https://images.maas.io/ ）进行引导。
镜像文件服务器在境内访问缓慢。

#### 上游地址与镜像方法(How to Mirror)

需要镜像的地址：https://images.maas.io/
镜像方法：https://docs.maas.io/2.1/en/installconfig-images-mirror

使用 simplestreams 从 `IMAGE_SRC` 获得内容，储存至 `IMAGE_DIR` 指定的位置。

#### 其他信息(Other)

- 镜像大小(Mirror Size): 大致估算在 150 GB 以内

**Comment by Harry-Chen** [comment]
Duplicate with #1188

**Comment by Harry-Chen** [comment]
（对不起，应该是它 duplicate 了你，但我先看到了前面的）
