### ISSUE TITLE
[Mirror Request] Tensorflow Serving

### ISSUE THREAD

**Issue by luginbash** [tuna/issues#402]
#### 项目名称与简介(Project Intro.)
TensorFlow Serving 是个灵活高性能的机器学习模型服务系统，主要用于生产环境。这个玩意可以简化部署和试验流程，让模型调教和使用起来更方便一些。
TensorFlow Serving is a flexible, high-performance serving system for machine learning models, designed for production environments. TensorFlow Serving makes it easy to deploy new algorithms and experiments, while keeping the same server architecture and APIs. TensorFlow Serving provides out-of-the-box integration with TensorFlow models, but can be easily extended to serve other types of models and data.

#### 上游地址与镜像方法(How to Mirror)
http://storage.googleapis.com/tensorflow-serving-apt
apt-mirror?

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
175M	/var/spool/apt-mirror/mirror/storage.googleapis.com/

**Comment by shankerwangmiao** [comment]
只有不到 1G 的东西，没啥镜像的必要性

**Comment by chzhong** [comment]
@shankerwangmiao 但问题的关键不在于大小，在于上面那个地址是否能被正常访问。
