### ISSUE TITLE
申请设立 k8s 的镜像

### ISSUE THREAD

**Issue by buzai** [tuna/issues#403]
#### 项目名称与简介(Project Intro.)
kubernetes
一个全新的基于容器技术的分布式架构领先方案。Kubernetes(k8s)是Google开源的容器集群管理系统（谷歌内部:Borg）。在Docker技术的基础上，为容器化的应用提供部署运行、资源调度、服务发现和动态伸缩等一系列完整功能，提高了大规模容器集群管理的便捷性。

#### 上游地址与镜像方法(How to Mirror)
https://kubernetes.io/
涉及到 k8s 工具 和 docker image。创建集群的时候总是被墙。希望可以提供一个备份
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by shankerwangmiao** [comment]
dup with #129
