### ISSUE TITLE
gentoo rsync  gentoo-portage怎么使用

### ISSUE THREAD

**Issue by supersndqd** [tuna/issues#404]
gentoo 这个服务有没有用，好像设置了没有用
emerge --sync
>>> Syncing repository 'gentoo' into '/usr/portage'...
!!! getaddrinfo failed for 'rsync.mirrors.tuna.tsinghua.edu.cn': [Errno -2] Name or service not known
>>> Starting rsync with rsync://rsync.mirrors.tuna.tsinghua.edu.cn/gentoo-portage...
>>> Checking server timestamp ...
rsync: getaddrinfo: rsync.mirrors.tuna.tsinghua.edu.cn 873: Name or service not known
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

**Comment by shankerwangmiao** [comment]
您的地址设定有错误，我们没有 rsync.mirrors.tuna.tsinghua.edu.cn 这个域名。

**Comment by supersndqd** [comment]
我其实想问的是正确的地址是什么

**Comment by shankerwangmiao** [comment]
请在首页点击 gentoo-portage  旁边的问号图标获取帮助。
