### ISSUE TITLE
Pytorch官网下载加速

### ISSUE THREAD

**Issue by PistonY** [tuna/issues#405]
#### 项目名称与简介(Project Intro.)
Pytorch
深度学习框架

#### 上游地址与镜像方法(How to Mirror)
https://download.pytorch.org/
镜像加速
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
暂不清楚

**Comment by shankerwangmiao** [comment]
目前我们 anaconda 里面已经有 pytorch 的 channel

**Comment by shankerwangmiao** [comment]
对于您提供的网站，因为无从枚举其上的内容，故无法镜像。
