### ISSUE TITLE
請求 debian-ports 鏡像

### ISSUE THREAD

**Issue by KireinaHoro** [tuna/issues#406]
#### 项目名称与简介(Project Intro.)

Debian Ports:

> ... The Linux kernel has now been ported to a large, and growing, list of architectures. Following close behind, we have ported the Debian distribution to these architectures. In general, this is a process with a sticky start (as we get libc and the dynamic linker working smoothly), and then a relatively routine, if lengthy job, of attempting to recompile all our packages under the new architectures.

#### 上游地址与镜像方法(How to Mirror)

https://www.ports.debian.org/mirrors ; ftp, rsync

**Comment by huiyiqun** [comment]
> Given the limited number of users for the architectures hosted by debian-ports, a lot more bandwidth is used to synchronise the mirrors than by the end users. We have therefore decided to use a content distribution network (CDN) to distribute the debian-ports archive. It is recommended to use it in priority.
