### ISSUE TITLE
RubyGems

### ISSUE THREAD

**Issue by a1exwang** [tuna/issues#41]
#### 项目名称与简介(Project Intro.)
- rubygems: ruby package manager
#### 上游地址与镜像方法(How to Mirror)
- [how to make a rubygems.org mirror](https://github.com/rubygems/rubygems-mirror)
- [rubygems.org](https://rubygems.org)
#### 其他信息(Other)
- 镜像大小(Mirror Size): Unknown

**Comment by bubbleatgit** [comment]
顶起来

**Comment by a1exwang** [comment]
非常感谢～～
