### ISSUE TITLE
nvidia cuda 镜像

### ISSUE THREAD

**Issue by all3n** [tuna/issues#410]
#### 项目名称与简介(Project Intro.)
nvidia cuda 镜像，国内访问非常缓慢

#### 上游地址与镜像方法(How to Mirror)
http://developer.download.nvidia.com/compute/cuda/repos/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
不太赞成镜像非开源软件。

另外 nvidia 应该不会提供 rsync。

**Comment by huiyiqun** [comment]
另外得翻一下 EULA 看看这部分内容是否允许重分发。

**Comment by sztsian** [comment]
1. nvidia 是有国内服务器的。只不过上述地址从我这儿访问的结果是
```
温馨提示：该网站暂时无法访问

	         根据工信部相关法规，由于您的网站尚未备案，该网站无法访问。

        	 按照国家工业和信息化部33号令规定：未取得备案号的网站不得解
	         析和开通，否则需承担相关的法律责任。
        	 
                     请各企事业单位务必完成备案后再开通网站，谢谢支持！
	
        	         世纪互联备案咨询相关联系方式

                	 备案咨询电话：021-36359595
```
解析情况
```
Non-authoritative answer:
developer.download.nvidia.com	canonical name = developer.download.nvidia.com.global.ogslb.com.
developer.download.nvidia.com.global.ogslb.com	canonical name = china-pool-1.zgslb.net.
Name:	china-pool-1.zgslb.net
Address: 58.216.33.90
Name:	china-pool-1.zgslb.net
Address: 58.216.33.89
Name:	china-pool-1.zgslb.net
Address: 58.216.33.88
Name:	china-pool-1.zgslb.net
Address: 58.216.33.91
```
从美国解析
```
Non-authoritative answer:
developer.download.nvidia.com	canonical name = developer.download.nvidia.com.global.ogslb.com.
developer.download.nvidia.com.global.ogslb.com	canonical name = cs5341561.wpc.phicdn.net.
Name:	cs5341561.wpc.phicdn.net
Address: 192.229.211.70
```
2. nvidia cuda 是版权软件，并且其许可证 [1.2.1 条款](https://docs.nvidia.com/cuda/eula/index.html#license-restrictions-driver) 不允许分发

> Except as expressly authorized in the AGREEMENT, you agree that you will not (nor authorize third parties to): (i) copy and use Software that was licensed to you for use in one or more NVIDIA hardware products in other unlicensed products (provided that copies solely for backup purposes are allowed); (ii) reverse engineer, decompile, disassemble (except to the extent applicable laws specifically require that such activities be permitted) or attempt to derive the source code, underlying ideas, algorithm or structure of Software provided to you in object code form; (iii) sell, transfer, assign, **distribute**, rent, loan, lease, sublicense or otherwise make available the Licensed Software or its functionality to third parties (a) as an application services provider or service bureau
......

**Comment by Harry-Chen** [comment]
抱歉，除非您能够从 NVIDIA 取得明确的授权与镜像途径，否则我们无法进行进一步工作。
另外，各个主流发行版似乎都有提供了自己打包的 cuda，比如 Arch Linux，这些是包含在我们的镜像中的。
