### ISSUE TITLE
pypi raven missing recent versions on tuna

### ISSUE THREAD

**Issue by whusnoopy** [tuna/issues#412]
Source: https://pypi.org/project/raven/
Latest version on source: 6.9.0
Latest version updated: 2018-05-30

Tuna: https://pypi.tuna.tsinghua.edu.cn/simple/raven/
Latest version on tuna: 6.7.0
Latest version updated on pypi: 2018-04-18

There is no problem on https://mirrors.aliyun.com/pypi/

**Comment by Harry-Chen** [comment]
Thanks for your report. We are now experiencing some connection problems with upstream server of PyPI repo.

**Comment by Harry-Chen** [comment]
We have fixed the problem of PyPI repo, you can try again.
