### ISSUE TITLE
Yum keeps warning the GitLab and ius repos are out-dated

### ISSUE THREAD

**Issue by w1ndy** [tuna/issues#414]
Here are the latest messages

Jul 2, 2018, 4:10 PM
```
Not using downloaded gitlab-ce/repomd.xml because it is older than what we have:
  Current   : Mon Jul  2 03:10:20 2018
  Downloaded: Sun Jul  1 08:55:13 2018
```

Jul 2, 2018, 8:42 PM
```
Not using downloaded ius/repomd.xml because it is older than what we have:
  Current   : Mon Jul  2 16:33:04 2018
  Downloaded: Sun Jul  1 16:35:23 2018
```

**Comment by w1ndy** [comment]
Looks like it's an issue with CDN...

```
$ wget https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/repodata/repomd.xml
```
results in an out-dated repomd.xml
```
-rw-r--r--.  1 xxx xxx 3.0K Jul  5 03:17 repomd.xml
```
while appending the url with "?v=3.1" (or retrying a few more times) returns a correct repomd.xml
```
-rw-r--r--.  1 xxx xxx 3.0K Jul  5 11:07 repomd.xml?v=3.1
```

**Comment by w1ndy** [comment]
ping @Harry-Chen @shankerwangmiao could it be a service issue?

**Comment by huiyiqun** [comment]
No, there is no CDN actually.

But there is a load balancer which is backed with two mirrors, And the two mirrors synchronize data with upstream separately, which may cause your problem.

I suggest to just ignore the warning.

**Comment by w1ndy** [comment]
@huiyiqun Great, thanks!
