### ISSUE TITLE
OpenWRT镜像中某些文件被截断

### ISSUE THREAD

**Issue by Blaok** [tuna/issues#415]
目前TUNA的OpenWRT镜像与官方源的内容相比，某些文件被截断了。例如[TUNA的`chaos_calmer/15.05/ar71xx/generic/md5sums`](https://mirrors.tuna.tsinghua.edu.cn/openwrt/chaos_calmer/15.05/ar71xx/generic/md5sums)比[OpenWRT官方的`chaos_calmer/15.05/ar71xx/generic/md5sums`](https://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/md5sums)要短。

```
%curl -s https://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/md5sums|wc -c
45661
%curl -s https://mirrors.tuna.tsinghua.edu.cn/openwrt/chaos_calmer/15.05/ar71xx/generic/md5sums|wc -c
41698
%curl -s https://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/md5sums|md5sum
59c42149f3fde1b83bdcdf9c15f44d18  -
%curl -s https://mirrors.tuna.tsinghua.edu.cn/openwrt/chaos_calmer/15.05/ar71xx/generic/md5sums|md5sum
6e12ce2cb35127c3f541e7f7251f5ad6  -
%curl -s https://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/md5sums|head -c 41698|md5sum
6e12ce2cb35127c3f541e7f7251f5ad6  -
```

**Comment by shankerwangmiao** [comment]
唔，貌似 15.05 已经不再同步了，是 archive 的状态。目前来看像是 lftp 的锅。

**Comment by shankerwangmiao** [comment]
经过抽查，确实有不少的这样的情况，但是目前在同步的 15.05.1 没有这个问题。

**Comment by z4yx** [comment]
经过两台mirrors服务器对比，只有如下两个文件不同，已修正。

> openwrt/chaos_calmer/15.05/ar71xx/generic/md5sums
> openwrt/chaos_calmer/15.05/ar71xx/generic/sha256sums
