### ISSUE TITLE
希望添加Anaconda Cloud上Anaconda的官方Channel

### ISSUE THREAD

**Issue by whimian** [tuna/issues#417]
#### 项目名称与简介(Project Intro.)
软件包版本新，跟main和free以及conda-forge都不同

#### 上游地址与镜像方法(How to Mirror)

https://anaconda.org/anaconda

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by x1angli** [comment]
根据 https://repo.continuum.io/pkgs/ 最下方 FAQ，Anaconda的这个channel，实际上就是main, free, pro三个channel的集合

> What about the 'anaconda' channel on anaconda.org at https://anaconda.org/anaconda? 
> The Anaconda channel on anaconda.org is an aggregated mirror of the packages in https://repo.continuum.io/pkgs/main, https://repo.continuum.io/pkgs/free, and https://repo.continuum.io/pkgs/pro. 
> If you are using conda's 'defaults' channel, you do not need the 'anaconda' channel.

在Anaconda里，那个“defaults”实际上就是指这个channel

另一方面，forge又是另外一个channel

“anaconda/defaults/main+free+pro”与“forge”的区别在于：貌似前者是anaconda的运营公司维护，后者是社区维护。

所以建议将main, free, pro等并成anaconda， forge单列。

**Comment by jiegec** [comment]
感受：Anaconda这么不清真，为啥还有这么多人用

**Comment by huiyiqun** [comment]
obsoleted by JIEGE

**Comment by x1angli** [comment]
> 感受：Anaconda这么不清真，为啥还有这么多人用

要从数据学习的初学者和那些没有编程经验的韭菜的角度考虑：你试想一家，你是主讲教师，告诉同学如何pip update pip自己, pip install， pip update，……然后讨论区里七嘴八舌这个import没有那个版本不兼容……你一怒之下，直接让大家用anaconda全家桶，节省沟通成本和troubleshooting成本

另外一个原因是，很多用Windows系统的，从pip安装的包有时候会有问题。知道[Gohlke 维护的Python for Windows编译包下载站](https://www.lfd.uci.edu/~gohlke/pythonlibs/)的人又廖廖无几

并且不幸的是，这个世界上用python做科研计算和数据分析的占多数
