### ISSUE TITLE
anaconda源中没有python3.6.6和python3.7.0

### ISSUE THREAD

**Issue by Hdzi** [tuna/issues#419]
最近想升级一下python版本，发现源中没有python3.6.6和python3.7.0这两个版本的包，但是官方源中是有的：
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.6-hc3d631a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.7.0-hc3d631a_0.tar.bz2

想问一下这边是不是有什么限制?麻烦了

**Comment by shankerwangmiao** [comment]
请等待最近的同步进行完毕

**Comment by shankerwangmiao** [comment]
现在已经同步成功了，感谢反馈！
