### ISSUE TITLE
关于debian-cd的修改建议

### ISSUE THREAD

**Issue by CreeperKong** [tuna/issues#420]
#### 项目名称与简介(Project Intro.)
debian-cd
#### 上游地址与镜像方法(How to Mirror)
http://cdimage.debian.org/cdimage/
使用wget递归下载即可
可以写个脚本来对比目录结构和文件，节省工作量
#### 其他信息(Other)
- 镜像大小(Mirror Size): 1TB左右
你们的网站现在只有当前版本的光盘镜像，我们有可能需要老版本镜像（官方的太慢啦！）

**Comment by huiyiqun** [comment]
考虑到服务可用性与稳定性，镜像站不支持递归 wget 的方式获取同步镜像。

当前看官方并没有提供合理的方式来同步这部分光盘。
