### ISSUE TITLE
LineageOS同步出错

### ISSUE THREAD

**Issue by zhanghua000** [tuna/issues#421]
有项目在进行repo sync时提示未找到。
截取最末端的终端输出数据如下：
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_external_libdrm/' not found
error: Cannot fetch LineageOS/android_external_libdrm

error: Exited sync due to fetch errors
随附终端截图。
![2018-07-16 10-19-15](https://user-images.githubusercontent.com/17194552/42741095-ca64c386-88e1-11e8-9c6f-33dc2a05faa0.png)

**Comment by shankerwangmiao** [comment]
请自行检查你的 manifest。 android_external_libdrm 这个 git 仓库确实不存在 lineageOS 项目的同步列表中。详见：https://github.com/LineageOS/mirror/blob/master/default.xml

**Comment by zhanghua000** [comment]
但是在镜像站中同步lineage15.1得到的mainifest.xml中存在相应的项目，请予以修正。附文件截图。
![2018-07-16 19-43-57](https://user-images.githubusercontent.com/17194552/42757138-65160b34-8931-11e8-9541-a149d5dba529.png)

**Comment by shankerwangmiao** [comment]
这个属上游问题，我们会按照 https://github.com/LineageOS/mirror/blob/master/default.xml 进行镜像。此文件属上游维护，应包括所有可能用到的 git 项目的列表。目前来看，应该是该列表有缺失造成的。对此，请您向上游反馈。

**Comment by huiyiqun** [comment]
这个 issue 留着吧，我很早以前就想讨论这个问题了，但是一直都没有时间。

官方的 mirror 列表更新一直不太及时，但是它有一个[脚本](https://github.com/LineageOS/mirror/blob/master/mirror-regen.py)，可以考虑用这个脚本替换掉 mirror 列表。

**Comment by shankerwangmiao** [comment]
我不建议，应当严格按照官方的指引进行镜像。至于列表更新不及时的问题，提示上有及时更新即可。

**Comment by huiyiqun** [comment]
看了一下他们的 README，还是保持现状吧，不过我们可以考虑在 LineageOS 的帮助里加个链接，让用户去 LineageOS 那边报 bug。
