### ISSUE TITLE
Request for LibreOffice download mirror

### ISSUE THREAD

**Issue by Bambooin** [tuna/issues#422]
#### 项目名称与简介(Project Intro.)
LibreOffice is community-driven and developed software, and is a project of the not-for-profit organization, The Document Foundation. LibreOffice is free and open source software, originally based on OpenOffice.org (commonly known as OpenOffice), and is the most actively developed OpenOffice.org successor project.
#### 上游地址与镜像方法(How to Mirror)
Information on how to mirror: https://wiki.documentfoundation.org/Infra/Mirroring
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
40G

**Comment by huiyiqun** [comment]
已完成

https://mirrors.tuna.tsinghua.edu.cn/libreoffice/

欢迎到 https://github.com/tuna/mirror-web 贡献帮助

**Comment by huiyiqun** [comment]
嗯，之后有时间会联系官方。

**Comment by Ravenclaw-OIer** [comment]
2023 了，[官方](https://download.documentfoundation.org/libreoffice/stable/7.4.3/mac/x86_64/LibreOffice_7.4.3_MacOS_x86-64.dmg.mirrorlist)还是没有啊……

**Comment by ZenithalHourlyRate** [comment]
> 2023 了，[官方](https://download.documentfoundation.org/libreoffice/stable/7.4.3/mac/x86_64/LibreOffice_7.4.3_MacOS_x86-64.dmg.mirrorlist)还是没有啊……

现已添加。
