### ISSUE TITLE
LineageOS源代码出现同步错误

### ISSUE THREAD

**Issue by lk8520157** [tuna/issues#424]
fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_external_libdrm/' not found
error: Cannot fetch LineageOS/android_external_libdrm/s

多次同步仍有错误

**Comment by huiyiqun** [comment]
提 issue 之前应该先搜索一下。

dup https://github.com/tuna/issues/issues/421。

**Comment by lk8520157** [comment]
十分感谢，夜晚打扰了~
