### ISSUE TITLE
关于aosp-latest.tar 下载下来无法进行同步的问题

### ISSUE THREAD

**Issue by senjoeson** [tuna/issues#426]
按照官网的步骤， 我现在也遇到了这样的问题 ，死活无法同步出结果来。这是我执行同步【 repo sync 】地日志
root@senjoeson-GL502VML:/home/senjoeson/WORKING_DIRECTORY/aosp# repo sync
Fetching project kernel/configs
Fetching project toolchain/binutils
Fetching project platform/external/chromium-libpac
Fetching project platform/external/gflags
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/chromium-libpac/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
Fetching projects: 0% (1/647) Fetching project platform/external/python/pyparsing
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/gflags/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/toolchain/binutils/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/pyparsing/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/toolchain/binutils/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/chromium-libpac/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/gflags/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/pyparsing/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
error: Cannot fetch toolchain/binutils
Fetching project platform/external/python/proto-google-cloud-pubsub-v1
error: Cannot fetch platform/external/chromium-libpac
error: Cannot fetch platform/external/gflags
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/proto-google-cloud-pubsub-v1/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
error: Cannot fetch platform/external/python/pyparsing
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
来自 https://aosp.tuna.tsinghua.edu.cn/platform/external/python/proto-google-cloud-pubsub-v1

[新标签] android-p-preview-5 -> android-p-preview-5
error: Exited sync due to fetch errors
root@senjoeson-GL502VML:/home/senjoeson/WORKING_DIRECTORY/aosp#

请告知一下，这个到底怎么解决呢？

**Comment by huiyiqun** [comment]
@sztsian 已经在 #97 答复你了，从日志看确实是网络问题，如果你无法提供你的 DNS 递归服务器的地址的话，我们没法提供进一步的帮助。
