### ISSUE TITLE
获取 LineageOS 15.1 报错

### ISSUE THREAD

**Issue by showerying** [tuna/issues#427]
执行：

> $~/repo sync -f -j8 --no-clone-bundle

输出：

> fatal: repository 'https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_external_libdrm/' not found
> error: Cannot fetch LineageOS/android_external_libdrm
> warn: --force-broken, continuing to sync
> Fetching projects: 100% (643/643)
> error: Exited sync due to fetch errors

请问是什么原因引起的？

**Comment by huiyiqun** [comment]
Dup #421
