### ISSUE TITLE
elpa镜像update failed

### ISSUE THREAD

**Issue by wayto222** [tuna/issues#428]
https://mirrors.tuna.tsinghua.edu.cn/elpa/
Last Update: 2018-07-21 01:04 failed

**Comment by SyrakuShaikh** [comment]
现在还是failed。。。😢

**Comment by shankerwangmiao** [comment]
这是由于上游失联导致的，目前暂无解决方案，等待上游恢复即可。

**Comment by SyrakuShaikh** [comment]
您好，请问上游仍旧处于“失联”状态么？😞

**Comment by shankerwangmiao** [comment]
是的

**Comment by y-usuzumi** [comment]
Hi,

经检验，上游 (emacs-china.org) 运行良好。

遇到问题的各位可以临时切换到上游镜像，参见[这里](http://elpa.emacs-china.org/)
```

**Comment by huiyiqun** [comment]
上游已修复

**Comment by C-Entropy** [comment]
上游似乎又挂了...
