### ISSUE TITLE
Artix Linux 镜像

### ISSUE THREAD

**Issue by PaoJiao** [tuna/issues#431]
为基于 ArchLinux 的发行版提供 systemd 以外的 init 支持的三方源。

这是主页上的声明：

> After more than two years of maintaining repositories with OpenRC packages, the maintainers of separate but closely or loosely related projects (Arch-OpenRC, Manjaro-OpenRC) decided to join forces and create a project that would be systemd-free and unaffected from upstream changes and updates. That required what might technically be considered as a mini-fork. Three new repositories, [system], [world] and [galaxy] have been created which must be placed before the official Arch or Manjaro ones. This ensures that upstream (if this term can be used anymore) will never break the new setup.

**Comment by huiyiqun** [comment]
挺好的项目呀

另外你对你的 issue 做了啥

**Comment by huiyiqun** [comment]
同步完成

**Comment by PaoJiao** [comment]
cool :+1:
