### ISSUE TITLE
Manjaro 发行版ISO更新

### ISSUE THREAD

**Issue by slfmessi** [tuna/issues#432]
镜像列表中 Manjaro-cd 更新到 17.1.7 的版本，后续 Manjaro 社区将下载服务迁移到 OSDN，该站点访问起来比 SourceForge 还要困难，希望能在 TUNA 更新 Manjaro 发行版的镜像

**OSDN**

[OSDN Manjaro Linux](http://onet.dl.osdn.jp/storage/g/m/ma/manjaro/)

[OSDN Mirror Doc](https://zh.osdn.net/docs/DownloadMirrorsWanted)

**Comment by huiyiqun** [comment]
正在联系 OSDN 开放 rsync 权限，感谢提供信息。

**Comment by huiyiqun** [comment]
已经开始同步，请耐心等候。

**Comment by slfmessi** [comment]
感谢TUNA大佬，你们的工作方便了国内很多开发者

**Comment by Harry-Chen** [comment]
已经开始提供服务。

**Comment by FantasqueX** [comment]
现在manjaro-cd镜像的位置还是在sourceforge不是osdn呀

**Comment by phy25** [comment]
@FantasqueX 参见 #491.
