### ISSUE TITLE
建议合并 OpenWRT 和 LEDE 两个镜像

### ISSUE THREAD

**Issue by MisakaMikoto-35c5** [tuna/issues#433]
由于 [LEDE 合并至 OpenWRT](https://openwrt.org/about#announcing_the_openwrtlede_merge) 且 OpenWRT 的镜像已过时超过 2 年，我建议将这两个镜像合并且只保留 OpenWRT 的镜像，而 LEDE 则通过 301 跳转保证用户访问。

**Comment by huiyiqun** [comment]
没必要这么麻烦吧 lede 放那不更新就是

openwrt 则更新到新版本

**Comment by Harry-Chen** [comment]
感谢提醒，目前我们的 openwrt 目录只有 chaos calmer 版本，而 lede 目录追踪了最新的变化。
对于用于提示和跳转相关的内容，我们将会讨论后决定。

**Comment by z4yx** [comment]
已把lede改名为openwrt，原openwrt仓库改名为openwrt-archive。
同时创建了软链接，保证用户还能用原来url访问。
