### ISSUE TITLE
申请增加 ArchlinuxCN 源的 push trigger 

### ISSUE THREAD

**Issue by Xuanwo** [tuna/issues#434]
ref: https://github.com/ustclug/discussions/issues/231

支持 ArchlinuxCN 源的 push trigger，可以缩短 ArchlinuxCN 源的同步间隔

**Comment by shankerwangmiao** [comment]
@lilydjwg 已经配置完毕，trigger 方法是

```
ssh -p 22222 tunasync@nanomirrors.s.tuna.tsinghua.edu.cn
ssh -p 22222 tunasync@neomirrors.s.tuna.tsinghua.edu.cn
```

注意：

* 请两台服务器分别 trigger
* 此 trigger 无视同步任务并发数限制，立刻开始
* 如果 trigger 时 archlinuxcn 正在同步，那么 trigger 会被忽略
* 可以在 https://{nano,neo}mirrors.tuna.tsinghua.edu.cn 上观察到两台服务器的同步状态（v6 only）

请测试。

**Comment by lilydjwg** [comment]
neo 触发成功，nano 报错：
```
bash: tunasynctl: command not found
```
PS: 服务器的 ssh key 指纹确认：
```
SHA256:4RBGljZexH6F2Mtft5iW0qLiiUveixEyXXnOuOQYiDk
SHA256:0GqIqpB8QMctdD2S9DBeTVCDWP0GWvMBdZvMjrOXnLc
```

PPS: 联通 IPv6 貌似访问不了呢，电信的倒是可以。

**Comment by shankerwangmiao** [comment]
修理了，请再试一次.

服务器的指纹没错

确实，因为联通和教育网 v6 的互通仍然有些问题。

**Comment by lilydjwg** [comment]
已经正常运作了～

**Comment by shankerwangmiao** [comment]
okay
