### ISSUE TITLE
申请Gradle镜像

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#435]
#### 项目名称与简介(Project Intro.)
Gradle是一个优秀的项目管理和构建的工具。与Maven不同，Gradle使用了Groovy来声明项目配置，从而更灵活

这里的镜像是Gradle Plugin Portal。Maven在构建时有Maven的插件库，而Gradle在构建时也有自己的库

#### 上游地址与镜像方法(How to Mirror)
镜像方法：
https://plugins.gradle.org/docs/mirroring
（此前可以用Nexus 和Artifactory... 这里之所以提交TUNA，是希望建立一个一站式的解决方案，降低运维成本。）

上游地址：
https://plugins.gradle.org/m2/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by x1angli** [comment]
阿里云的gradle镜像好像有问题（可能版本不够新）

**Comment by Michael200204** [comment]
沙发

**Comment by huiyiqun** [comment]
如果阿里这样专业 Java 的公司都有问题，我们这一群 Java 白和 Java 黑就更不可能解决了。

参见 #100

**Comment by LeonDevLifeLog** [comment]
腾讯镜像了gradle 分发版本     https://mirrors.cloud.tencent.com/gradle/
