### ISSUE TITLE
增加对JetBrains系列软件的下载

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#436]
#### 项目名称与简介(Project Intro.)
JetBrains 系列的软件，包括但不限于：

- PyCharm: https://www.jetbrains.com/pycharm/
- IntelliJIDEA: https://www.jetbrains.com/idea/
- DataGrip: https://www.jetbrains.com/datagrip/
- WebStorm: https://www.jetbrains.com/webstorm/
- TeamCity: https://www.jetbrains.com/teamcity/

………………

#### 上游地址与镜像方法(How to Mirror)
JetBrains系列的软件一般用户在第一次时通过官网下载
在装机后，JetBrains软件会通过自动更新部门，读取delta增量的部分

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
上述软件并非开源软件，其[授权协议](https://www.jetbrains.com/company/useterms.html)也不允许对上述软件进行再分发，因此不予镜像。
