### ISSUE TITLE
申请增加Gohlke的python库

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#437]
#### 项目名称与简介(Project Intro.)

** Unofficial Windows Binaries for Python Extension Packages **

这是由UC Irvine的教师Gohlke自己建立的常用Python库的镜像。其价值在于：由于很多常用的Python库（尤其是涉及到OpenCV及数值计算的库）都会牵涉到C的编译，而C类库的编译在Windows上又对使用者十分不友好，经常会发生编译不通过的情况，因而Gohlke自己建了一个库供Python开发者下载。

对于一个python的扩展（比如OpenCV），库会根据不同的Python版本（如2.7，3.4，3.5等），不同的CPU指令（如x86, x64）提供构建

通过下载这些库，开发者（尤其是数据相关或科学实验）大大加快开发进程，减少不必要的损耗

#### 上游地址与镜像方法(How to Mirror)
https://www.lfd.uci.edu/~gohlke/pythonlibs/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by Michael200204** [comment]
沙发

**Comment by huiyiqun** [comment]
@Michael200204 不要把贴吧的习惯带到这里 善用 github 的 reaction

@x1angli 感觉定位上和 anaconda 很类似，但是是用 pypi 的格式分发的 挺有意思的。

不过问题是上游似乎并没有给出同步的方式，比如 rsync。
