### ISSUE TITLE
求教 + 探讨：关于Maven类的镜像TUNA计划如何处理？

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#438]
所谓的Maven类的镜像包括如下N个镜像，每个镜像

jcenter { url “http://jcenter.bintray.com/"}
maven { url “http://repo1.maven.org/maven2"}
maven { url “http://repo2.maven.org/maven2"}
google { url "https://dl.google.com/dl/android/maven2/" }

上述镜像被多种构建工具支持，包括但不限于：Maven, Gradle, Ivy, SBT, Closure……等

阿里云制作了上述多个镜像，如
- mavenCentral镜像仓库地址
-- http://maven.aliyun.com/nexus/content/groups/public/
- jentral镜像仓库地址
-- http://maven.aliyun.com/nexus/content/repositories/jcenter
- google镜像仓库地址
-- http://maven.aliyun.com/nexus/content/repositories/google

不知道TUNA是否有类似的计划？

**Comment by sztsian** [comment]
TUNA 现在的态度应该是暂缓这类镜像请求。参考
https://github.com/tuna/issues/issues/329#issuecomment-354588076
https://github.com/tuna/issues/issues/100

**Comment by huiyiqun** [comment]
嗯 态度就是阿里比较专业 用阿里的吧
