### ISSUE TITLE
DNS问题

### ISSUE THREAD

**Issue by Michael200204** [tuna/issues#439]
使用TUNA DNS时，无法访问[](https://cloud.189.cn/)，希望解决。

**Comment by Michael200204** [comment]
[https://cloud.189.cn/]

**Comment by Michael200204** [comment]
120.239.197.1

**Comment by dotkrnl** [comment]
根据您的反馈，cloud.189.cn 被解析到了 222.28.152.201，这个解析结果符合预期。这一 IP 地址位于 CERNET 教育网络内，在清华大学校园网可正常访问。同时结合您 NTP 服务出现问题的描述，暂时可以猜测是您互联网提供商与 CERNET 教育网络的连接出现问题，可以与运营商联络。

您可以提交：

Linux / macOS 下：

    traceroute ntp.tuna.tsinghua.edu.cn
    traceroute 222.28.152.201

或者 Windows 下命令行：

    tracert ntp.tuna.tsinghua.edu.cn
    tracert 222.28.152.201

的结果进行进一步判断，但我们应该无法针对运营商故障进行修复。

关于日志，抱歉我们不使用日志进行错误诊断。

**Comment by Michael200204** [comment]
我的意思是使用你们的DNS时你们那边的服务器记录上网日志吗

**Comment by Michael200204** [comment]
会不会被泄露出去

**Comment by Michael200204** [comment]
![default](https://user-images.githubusercontent.com/15242697/44197669-e038df00-a171-11e8-837f-7807fea07398.jpg)

**Comment by Michael200204** [comment]
![default](https://user-images.githubusercontent.com/15242697/44197979-b16f3880-a172-11e8-8ca7-31d19a6ec78e.jpg)

**Comment by Michael200204** [comment]
![default](https://user-images.githubusercontent.com/15242697/44198065-eb403f00-a172-11e8-8c50-3457b7d16e59.jpg)

**Comment by Michael200204** [comment]
用别的DNS都是正常解析：
![default](https://user-images.githubusercontent.com/15242697/44198137-1fb3fb00-a173-11e8-90ff-c8a17ac04af0.jpg)

**Comment by Michael200204** [comment]
在吗？

**Comment by dotkrnl** [comment]
222.28.152.201 是正确的解析结果，是一个有效的 189 服务器。由于 DNS666 位于教育网内，189 的策略向我们提供了教育网内的服务器地址。

出现问题的是您与教育网之间的连接，导致您无法连接上 222.28.152.201。这一问题只能由您的互联网提供商与 CERNET 教育网络共同完成。请与您的服务提供商或 CERNET 联系。

您到 NTP 的服务器链路正常，若时间同步失败，可能是您互联网提供商或是上游例如公司网络策略导致的。我们已知在一些网络中，为了防止 NTP 攻击的影响，服务商直接丢弃了 NTP 的请求数据包。

**Comment by Michael200204** [comment]
如何与CERNET联系？因为运营商是移动，移动防火墙肯定不会解除的。

**Comment by Harry-Chen** [comment]
您好，我们无法对运营商网络相关的问题提供帮助，您或许能在 http://www.cernet.edu.cn/ 找到相关联系方式。

**Comment by shankerwangmiao** [comment]
您好，您反馈的域名的查询结果，可以确定是该网站在教育网内部的 CDN 服务器地址，解析结果没有错误。至于您的主机不能正常连接该服务器，原因可能较为复杂，涉及您的互联网接入商和该网站方面的策略，已经超出了我们的管辖范围，因此无法进一步为您诊断。

请您留意，我们提供的 DNS 查询服务，是面向清华校内提供服务的，我们不保证对校外的服务质量。详情请参考 https://tuna.moe/help/dns-license/ 。

**Comment by shankerwangmiao** [comment]
另外，限于相关限制和安全性考虑，ntp 服务器暂不对校外服务。
