### ISSUE TITLE
Centos-vault 镜像增加申请

### ISSUE THREAD

**Issue by Songxuewen** [tuna/issues#440]
#### 项目名称与简介(Project Intro.)

Centos-vault

作为停止支持的CentOS的yum源。

#### 上游地址与镜像方法(How to Mirror)

http://vault.centos.org/

rsync://archive.kernel.org/centos-vault

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

约1.8TB

**Comment by sztsian** [comment]
个人觉得意义不大。 CentOS 每个大版本 （例如 CentOS 6 )的生命周期至少约5年。所以旧的大版本意义不大。对于当前仍然存活的大版本，更新都会发布在最新的小版本（例如 CentOS 7.5.1804）中，安全更新也不例外。而且默认情况下 CentOS 应该访问的是当前大版本的最新仓库。

**Comment by huiyiqun** [comment]
其实我觉得可以同步，2T 也不是什么大事，而且硬盘空着也是空着？我是遇到过好几次用 Vault 非常痛苦的情况

**Comment by sztsian** [comment]
呃，没想到竟然真有用户。。。我以为没多少人用。。。

好吧，另外我觉得这个可以低频率同步（例如一周一次），毕竟归档的版本变动不会太大

**Comment by Songxuewen** [comment]
请问什么时候可以正式使用呢？
