### ISSUE TITLE
percona mirror can't be browsed via HTTP(s)

### ISSUE THREAD

**Issue by fancy-rabbit** [tuna/issues#441]
The percona mirror on tuna https://mirrors.tuna.tsinghua.edu.cn/percona/
can't be browsed via HTTP(s), (but is rsync-able...)

which may be inconvenient for users.
could you please fix it? :)

**Comment by shankerwangmiao** [comment]
dup with #321

We provide mirrors as-is. An empty index.html file exists in the upstream. That's why the directory is not able to be browsed. You can use the mirror as normal.

**Comment by fancy-rabbit** [comment]
thanks for your explanation :)
