### ISSUE TITLE
tuna的linuxrootfs包多久会更新一次？

### ISSUE THREAD

**Issue by myfreess** [tuna/issues#444]
希望能用固定的url获取到最新版

**Comment by shankerwangmiao** [comment]
您是指哪个镜像？

**Comment by myfreess** [comment]
debian和ubuntu

**Comment by shankerwangmiao** [comment]
我们提供 debian 和 ubuntu 的软件仓库镜像和安装器镜像，分别位于 https://mirrors.tuna.tsinghua.edu.cn/debian https://mirrors.tuna.tsinghua.edu.cn/debian-cd 和 https://mirrors.tuna.tsinghua.edu.cn/ubuntuhttps://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases 。如无特别说明，是两个小时同步一次。
