### ISSUE TITLE
Elpa的镜像挂了吗？

### ISSUE THREAD

**Issue by ProfessorX** [tuna/issues#445]
#### 其他信息(Other)
- 镜像大小(Mirror Size): 

-------
请问下webadmin大哥，刚刚我用Emacs更新，提示没有更新。

上来一看原来Elpa的同步已经挂掉了。

请问是什么原因，大约什么时候可以修复？

**Comment by huiyiqun** [comment]
见 https://github.com/tuna/issues/issues/428
