### ISSUE TITLE
移除 tensorflow 的镜像仓库

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#446]
当前 tensorflow 已经进入 pypi，我们已经没有必要再维护现有的 tensorflow 仓库了。

**Comment by xavieryao** [comment]
Duplicate of https://github.com/tuna/mirror-web/issues/58
我之前发错地方了 orz

**Comment by huiyiqun** [comment]
唔 好吧

不过我的点是：一年过去了。

**Comment by huiyiqun** [comment]
看了一下日志，应该是移除不了了。

这一周有 1k 人访问了 5k 次。各种 csdn 的链接。

**Comment by fly2leoo** [comment]
> 当前 tensorflow 已经进入 pypi，我们已经没有必要再维护现有的 tensorflow 仓库了。

昨天从pypi龟速下载，重试三四次才下完，可以的话还是考虑留下吧，教育网毕竟快


> 看了一下日志，应该是移除不了了。
> 
> 这一周有 1k 人访问了 5k 次。各种 csdn 的链接。

提到csdn，确实写过一个 .......
 https://blog.csdn.net/Fly2Leo/article/details/78498494

**Comment by huiyiqun** [comment]
@fly2leoo 欢迎使用 tuna 的 [pypi 镜像](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)

另外希望可以更新博客，让用户使用 pypi 镜像。从长远来看，这个 tensorflow 仓库毕竟已经弃用了，新用户不应该使用这个镜像。
