### ISSUE TITLE
如何使用 https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo/ 呢？

### ISSUE THREAD

**Issue by chanjarster** [tuna/issues#448]
Hi，我找到你们做了这么一个mirror：https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo/

那么我应该如何在Ubuntu中针对这个mirror配置正确的软件源呢？

比如apt-add-repository这个命令应该如何打呢？

我试过这个，`sudo apt update`的时候不行：

```
sudo add-apt-repository -r "deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo/dists ubuntu-$(lsb_release -cs) stable"
```

**Comment by huiyiqun** [comment]
see #207
