### ISSUE TITLE
Tensorflow 的镜像同步挂掉了

### ISSUE THREAD

**Issue by fly2leoo** [tuna/issues#449]
-- | -- | -- | -- | --
tensorflow | 2018-09-10 07:05 | https://storage.googleapis.com/tensorflow | failed | unknown

看镜像列表最后同步是今年1月
-- | -- | --
tensorflow_gpu-1.5.0rc1-cp27-none-linux_x86_64.whl | 188.4 MiB | 2018-01-13 14:07
tensorflow_gpu-1.5.0rc1-cp33-cp33m-linux_x86_64..> | 188.7 MiB | 2018-01-13 14:07
tensorflow_gpu-1.5.0rc1-cp34-cp34m-linux_x86_64..> | 188.7 MiB | 2018-01-13 14:07
tensorflow_gpu-1.5.0rc1-cp35-cp35m-linux_x86_64..> | 188.4 MiB | 2018-01-13 14:07
tensorflow_gpu-1.5.0rc1-cp36-cp36m-linux_x86_64..> | 188.4 MiB | 2018-01-13 14:07

同步的版本是 1.5.0，之后就再也没有了

**Comment by sztsian** [comment]
参考 #446 , tensorflow 已经进入 pypi, 可以考虑从 pypi 安装。

**Comment by Harry-Chen** [comment]
您好，我们不再单独提供 tensorflow 镜像，您可以使用 PyPI 或者各个发行版自行打包的版本。
