### ISSUE TITLE
Solus的package repo地址变更

### ISSUE THREAD

**Issue by hashhsah** [tuna/issues#450]
Solus linux正在升级服务器/hosting。他们变更了package repo的URL。

新的URL为 rsync://mirrors.rit.edu/solus

详细情况见：https://getsol.us/2018/09/08/supercharging-solus-infrastructure/

联系方式： DataDrake@freenode / #Solus-Dev

**Comment by hashhsah** [comment]
![image](https://user-images.githubusercontent.com/7791055/45358763-134d8180-b5fd-11e8-909f-a6ac68bdc0a8.png)

**Comment by shankerwangmiao** [comment]
@hashhsah 我翻了一下他的 blog ，并没有任何公开的文档指示要更换上游？不知道这个是个什么情况？

**Comment by hashhsah** [comment]
@shankerwangmiao 下面这个页面中
https://getsol.us/2018/09/08/supercharging-solus-infrastructure/

有一节 Repo URLs , 其中最后一句：

>  you are using a repository which is not provided by us (or RIT), we recommend reaching out to the respective administrator to ensure they update their rsync URLs to new endpoint (mirrors.rit.edu).

**Comment by huiyiqun** [comment]
https://getsol.us/2018/09/11/package-repo-migration-now-available/

域名和基础设施迁移了，那咱们换上游吧。

**Comment by huiyiqun** [comment]
done
