### ISSUE TITLE
centos-vault 无法被rsync同步

### ISSUE THREAD

**Issue by Songxuewen** [tuna/issues#451]
rsync://mirrors.tuna.tsinghua.edu.cn/centos-vault/

**Comment by Harry-Chen** [comment]
您好，请给出您的同步命令和遇到的错误详情，以便我们调查

**Comment by shankerwangmiao** [comment]
您好，该镜像正在初始同步，暂时不能使用，请稍等初始同步完成后再进行同步。

**Comment by shankerwangmiao** [comment]
ref: #440
