### ISSUE TITLE
MiKTeX 镜像

### ISSUE THREAD

**Issue by Stone-Zeng** [tuna/issues#452]
现在的 CTAN 镜像似乎不支持 MiKTeX，在官网 <https://miktex.org/pkg/repositories> 并不能看到有中国的镜像站，于是每次就被跳转到台湾，然后又访问不了。

但该有的文件 tuna 上其实都有，只是不知道为什么不能拿来用（设置 `mpm --repository=https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/` 会报错）。是不是应该问下 MiKTeX 他们那边？

来自 <https://github.com/tuna/mirror-web/issues/95>。

**Comment by Harry-Chen** [comment]
![image](https://user-images.githubusercontent.com/2819727/45583953-a76d6080-b8fd-11e8-8018-e135415020de.png)
看起来并没有什么问题，目前还是会出错吗？

**Comment by Stone-Zeng** [comment]
目前看是可以的，先关了。
