### ISSUE TITLE
请求添加CPAN镜像

### ISSUE THREAD

**Issue by Minys233** [tuna/issues#453]
#### 项目名称与简介(Project Intro.)

CPAN（Comprehensive Perl Archive Network），中译Perl综合典藏网。其作用是收录Perl的模块（module），类似Python的pypi。通过同名的软件cpan可以方便地安装Perl包并且解决依赖关系。对使用Perl语言或程序的用户来说十分重要。

> 通过Anaconda可以建立Python、R和Perl的环境，tuna已有pipy和CRAN，唯独缺少了CPAN。所以即使通过conda建立的perl环境也无法通过tuna下载需要的包。

生物信息学**很多**工具（尤其Bioconda）均需要有Perl环境和特定的包并需要从CPAN下载，Bioconda中共有753/8858（[参考链接](https://bioconda.github.io/recipes.html)搜索perl）个包，其中包括如DNA测序中常用的bwa。此外，LaTeX中一些工具也需要使用较多基于Perl的工具，如`latexindent.pl`与`ChkTex`（使用VS code + LaTeX插件时均需要额外配置Perl环境）。但是因为perl安装包的时候需要使用cpan或cpanm命令，均需要从cpan.org或者镜像站下载所需内容。

#### 上游地址与镜像方法(How to Mirror)

其官方网站详细地叙述了如何建立镜像站，不论是使用`rsync`还是Perl脚本，都可以十分方便地建立镜像站并配置。说明如寻找可用站点、更新频率、在cpan官网上墙等都可在[这个网页](http://www.cpan.org/misc/how-to-mirror.html)找到说明。目前中国仅有上海大学、网易有镜像站，详情参考：[亚洲地区CPAN镜像站](https://www.cpan.org/SITES.html#Asia)。

#### 其他信息(Other)

- 镜像大小(Mirror Size): 22.646GB，细节如文件数、目录树变化趋势可参考[链接](http://mirrors.cpan.org/stats/)

谢谢！

**Comment by huiyiqun** [comment]
同步中

**Comment by huiyiqun** [comment]
done
