### ISSUE TITLE
binutils_linux-ppc64l e-7.2.0-h14882df_24.tar.bz2 package checksum error

### ISSUE THREAD

**Issue by songdongmei** [tuna/issues#456]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-ppc64le/binutils_linux-ppc64l
e-7.2.0-h14882df_24.tar.bz2 has wrong md5sum, please check.

**Comment by huiyiqun** [comment]
具体来说是怎么看出来 checksum 不符的？

**Comment by songdongmei** [comment]
conda install的时候报错，说md5sum不符。（没有截图）

手工从贵镜像站wget下载下来md5sum

Channel修改成https://repo.anaconda.com/pkgs/main/linux-ppc64le/ <https://repo.anaconda.com/pkgs/main/linux-ppc64le/，conda> ，conda install 安装没有问题。并且包的md5sum确实跟贵镜像站不一样。

 

*****************************************************

root@ubuntu:~/anaconda3/pkgs# md5sum binutils_linux-ppc64le-7.2.0-h14882df_24*

md5sum: binutils_linux-ppc64le-7.2.0-h14882df_24: Is a directory

23b82b157bd7abddbb4ac4d6c8fd6dc6  binutils_linux-ppc64le-7.2.0-h14882df_24.tar.bz2

898eb82a7bec49f5ca005d9f96f477ec  binutils_linux-ppc64le-7.2.0-h14882df_24.tar.bz2.bak

********************************************************

带bak后缀是从贵镜像站下载的。不带后缀的是conda install安装的

 

发件人: Hui Yiqun [mailto:notifications@github.com] 
发送时间: 2018年9月19日 17:33
收件人: tuna/issues <issues@noreply.github.com>
抄送: Tulip Song(宋冬梅) <songdm@inspur.com>; Author <author@noreply.github.com>
主题: Re: [tuna/issues] binutils_linux-ppc64l e-7.2.0-h14882df_24.tar.bz2 package checksum error (#456)

 

具体来说是怎么看出来 checksum 不符的？

**Comment by shankerwangmiao** [comment]
确实是这样的。目前排查，暂时确定为偶发的故障，文件已经换成了正确的了。抱歉带来不便。
