### ISSUE TITLE
申请增加K8S yum镜像

### ISSUE THREAD

**Issue by wz2026007** [tuna/issues#457]
#### 项目名称与简介(Project Intro.)
kubernetes(k8s) 是google开发的容器集群软件，在国内也得到了大规模应用，但由于某种原因，访问google的网站十分麻烦且速度很慢。

目前tuna上已有apt镜像，但国内使用centos体系的用户更多，yum安装时实在困难

#### 上游地址与镜像方法(How to Mirror)
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
大小未知

**Comment by huiyiqun** [comment]
基本和 #129 是一样的 如果要同步我们肯定会把 apt 和 yum 一起同步。

主要的问题是上游没有提供 rsync 的同步方式，写脚本的方式当然是可以的，不过时间成本比较高。
