### ISSUE TITLE
pypi 的配置方法有拼写错误

### ISSUE THREAD

**Issue by shyoshyo** [tuna/issues#459]
https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

pip config set glo**ab**l.index-url https://pypi.tuna.tsinghua.edu.cn/simple

应为

pip config set glo**ba**l.index-url https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by xavieryao** [comment]
fixed in https://github.com/tuna/mirror-web/commit/b4b0fc99429638d77af255d98aa445eb07aa1209
