### ISSUE TITLE
镜像 CocoaPods 的索引

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#46]
#### 项目名称与简介(Project Intro.)   
CocoaPods 是一个 Cocoa 和 Cocoa Touch 框架的依赖管理器，具体原理和 Homebrew 有点类似，都是从 GitHub 下载索引，然后根据索引下载依赖的源代码……
#### 上游地址与镜像方法(How to Mirror)
所以，可以像镜像 Homebrew 的索引一样把 CocoaPods 的索引也镜像了，只要镜像一个这个 GitHub repository [CocoaPods/Specs](https://github.com/CocoaPods/Specs) 就可以了
用户这边，只要
```bash
$ pod repo remove master
$ pod repo add master https://mirrors.tuna.tsinghua.edu.cn/xxxx.git
$ pod repo update
```
就好了
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
308.87 MiB

**Comment by bigeagle** [comment]
测试一下？

**Comment by baogechen** [comment]
新版的pod 不允许用pod repo add添加master库了，但是可以直接git clone
另外镜像的正确地址是 https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git

所以目前使用该镜像的一种正确方法如下
<code>
$ cd ~/.cocoapods/repos 
$ pod repo remove master
$ git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master
</code>

然后进入自己的工程，在自己工程的podFile第一行加上 
<code>
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
</code>
这样就能替换掉master库了
