### ISSUE TITLE
请求：镜像termux的数个社区源

### ISSUE THREAD

**Issue by myfreess** [tuna/issues#461]
https://its-pointless.github.io/files/ termux extras #its-pointless源
包含gcc和一些难以编译的python包
~~https://termux.xeffyr.ml/ extra main
extra源 包含openjdk，pandoc等非常实用的包。~~
因为这几个源是个人维护的，所以速度很慢，希望tuna能为它们做一个镜像。

**Comment by YadominJinta** [comment]
附议 顺便联系一下，把Termux的换源帮助改为

echo "deb https://mirrors.tuna.tsinghua.edu.cn/termux stable main" > $PREFIX/etc/apt/sources.list && pkg up

**Comment by huiyiqun** [comment]
> https://its-pointless.github.io/files/ termux extras #its-pointless源

这个仓库托管在 github 上面，需要写脚本用于同步。

> https://termux.xeffyr.ml/ extra main

这个仓库无法访问。

**Comment by huiyiqun** [comment]
@myfreess 需要写脚本，短期内看没有人力，如果有人能写好脚本的话我们是愿意 host 的。

**Comment by myfreess** [comment]
2019.03.09

extra源作者xeffyr直接去Termux开发组了。

现在，Termux有数个性质特殊的仓库，包括游戏，科学计算，X11应用，新而不稳定的包。

仓库全都在Termux这个ORG下，应该可以很容易地镜像
@huiyiqun

**Comment by z4yx** [comment]
实际需要镜像的应该是这几个deb源？
https://dl.bintray.com/grimler/termux-root-packages-24/
https://dl.bintray.com/grimler/science-packages-24/
https://dl.bintray.com/grimler/game-packages-24/
https://dl.bintray.com/xeffyr/x11-packages/

**Comment by YadominJinta** [comment]
还有一个unstable-repo
https://dl.bintray.com/xeffyr/unstable-packages/

**Comment by z4yx** [comment]
上述源均已添加，等待同步中。原本 https://mirrors.tuna.tsinghua.edu.cn/termux/(aarch64|all|arm|dists|i686|x86_64) 作了重定向处理。
