### ISSUE TITLE
tensorflow-base-1.10.0-gpu_py36h6e53903_0 无法下载

### ISSUE THREAD

**Issue by hdmyeah** [tuna/issues#462]
tensorflow-base-1.10.0-gpu_py36h6e53903_0 无法下载，下载了很多遍都是到了75%就停了。

**Comment by x1angli** [comment]
> 具体是哪个 URL ？

可能是Anaconda下面的
https://anaconda.org/anaconda/tensorflow-base/1.10.0/download/win-64/tensorflow-base-1.10.0-gpu_py36h6e53903_0.tar.bz2

**Comment by shankerwangmiao** [comment]
服务器上并不存在这个 URL
