### ISSUE TITLE
请求 Armbian 镜像源

### ISSUE THREAD

**Issue by Jamesits** [tuna/issues#463]
#### 项目名称与简介(Project Intro.)

Armbian

大量ARM开发板的Debian/Ubuntu镜像、固件和实用程序。

申请的主要原因：

- Armbian 支持的设备大多数在中国生产并销往中国
- 他们做的镜像比厂商给的 BSP 包好不少，并且能推动 ARM 设备的主线化进程
- 社区比较穷，服务器到中国速度比较糟糕

#### 上游地址与镜像方法(How to Mirror)

- https://dl.armbian.com/ `rsync://rsync.armbian.com/dl` 发行版下载
- https://apt.armbian.com/ `rsync://rsync.armbian.com/apt` APT 软件源
- https://beta.armbian.com/ `rsync://rsync.armbian.com/beta` APT 软件源（beta 版软件）

#### 其他信息(Other)
- 镜像大小(Mirror Size): dl.armbian.com 不到 100GiB，软件源很小，主要是 ARM 硬件相关的驱动程序。

**Comment by shankerwangmiao** [comment]
上游有 rsync 吗？

**Comment by Jamesits** [comment]
他们网站上没写，我发邮件问了，至今没回我
Debian wiki 上说 rsync 是有的，但是也没写地址

**Comment by Jamesits** [comment]
@shankerwangmiao Armbian 那边设置好了 rsync 服务器。

rsync -av rsync://rsync.armbian.com/apt
rsync -av rsync://rsync.armbian.com/dl
rsync -av rsync://rsync.armbian.com/beta

Technical limitations of the service: max 5 users at once and up to
50Mbit/s bandwidth. I think that should do. There are not many changes
except beta repository, which is refreshed daily. All downloadable
images (except test versions) are also available via torrent network.
ATM we have around 15-20 dedicated seeders around the globe. Details
with script for automated refreshing:
https://forum.armbian.com/topic/4198-seed-our-torrents

**Comment by shankerwangmiao** [comment]
beta 就不同步了，其他两个在同步。这个 issue keep open 直到同步完成。

**Comment by shankerwangmiao** [comment]
已经同步好了，在 https://mirrors.tuna.tsinghua.edu.cn/armbian  和 armbian-releases  下
