### ISSUE TITLE
希望能补充tesseract相关包

### ISSUE THREAD

**Issue by loveglory** [tuna/issues#464]
#### 项目名称与简介(Project Intro.)
1. 补充python的tesserocr包（windows build后的whl）
2. 补充tesseract的安装包

#### 上游地址与镜像方法(How to Mirror)
1. https://github.com/simonflueckiger/tesserocr-windows_build/releases
2. https://digi.bib.uni-mannheim.de/tesseract/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
1. 5 MB
2. 30 MB

**Comment by jiegec** [comment]
这么小吗。。。

**Comment by Harry-Chen** [comment]
1. 我们原则上不镜像 GitHub 项目
2. 您给出的镜像大小有误。对方没有提供 rsync 服务，我们无法通过 URL 获得可靠的同步方式
