### ISSUE TITLE
请求snap镜像

### ISSUE THREAD

**Issue by guodf** [tuna/issues#465]
#### 项目名称与简介(Project Intro.)
snap
ubuntu新的包管理器，每个snap包都是独立的个体，所有的依赖都在snap包中，不需要你单独的安装依赖

#### 上游地址与镜像方法(How to Mirror)
未知
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by abcfy2** [comment]
印象中snap目前官方不允许镜像，而且官方也没有提供镜像的方案

**Comment by shankerwangmiao** [comment]
貌似是的，而且 snap 用的人不知道多不多。@happyaron

**Comment by happyaron** [comment]
snap 目前不能镜像，走了纯的商用CDN模式

**Comment by shankerwangmiao** [comment]
那就只好这样了

**Comment by Headcrabed** [comment]
@shankerwangmiao 当前snap开始提供镜像服务器工具了，参见https://docs.ubuntu.com/snap-store-proxy/en/
我认为在当前ubuntu强推snap的情况下还是很有必要进行镜像的，否则每次浏览器滚更新都慢的很。

**Comment by ZenithalHourlyRate** [comment]
> 当前snap开始提供镜像服务器工具了

该工具为 Canonical 私有的反向代理工具

> #741
> 一般不使用反向代理的方式提供镜像
