### ISSUE TITLE
没有mysql 8.0的镜像吗？

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#466]
目前tuna的mysql镜像列表来看: https://mirrors.tuna.tsinghua.edu.cn/mysql/ 无论apt还是yum，都无法安装mysql 8.0版本。

而官方仓库实际是有8.0版本的(https://repo.mysql.com/apt/ubuntu/dists/bionic/) 希望能同步

**Comment by shankerwangmiao** [comment]
开始同步了
