### ISSUE TITLE
Request mirror for Proxmox VE

### ISSUE THREAD

**Issue by Menci** [tuna/issues#468]
#### 项目名称与简介(Project Intro.)
https://en.wikipedia.org/wiki/Proxmox_Virtual_Environment

download.proxmox.com 是 Proxmox VE 下载虚拟机镜像、进行系统组件更新（APT）的域名。

#### 上游地址与镜像方法(How to Mirror)
http://download.proxmox.com or http://mirrors.ustc.edu.cn/proxmox/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by z4yx** [comment]
完成 https://mirrors.tuna.tsinghua.edu.cn/proxmox/
