### ISSUE TITLE
希望镜像ELK Stack

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#47]
# 项目名称与简介(Project Intro.)
ELK Stack指的是elastic.io公司旗下的三款旗舰产品(Elasticsearch, Logstash, Kibana)，是目前非常成熟的日志系统。由于官方仓库将这些软件包托管于S3，造成国内下载困难，故申请镜像。

# 上游地址与镜像方法(How to Mirror)
Elasticsearch地址: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

Logstash地址: https://www.elastic.co/guide/en/logstash/current/package-repositories.html

Kibana地址: https://www.elastic.co/guide/en/logstash/current/package-repositories.html

**Comment by bigeagle** [comment]
我们正有意镜像这些。

**Comment by bubbleatgit** [comment]
顶起来

**Comment by abcfy2** [comment]
@bigeagle 请问下有时间计划表么？
看到issue中的mirror request非常多，所以想请问下有关于镜像的计划表吗？哪些准备镜像，哪些不镜像，优先级之类的？

**Comment by bigeagle** [comment]
目前来说，因为考试期临近，我们都不太有时间搞这个，也并没有计划和优先级之类的。
有些项目镜像方法不明确，我们自己无法测试，且不能保证稳定服务的，就不准备镜像了。

ELK的话，我们这周完成镜像吧。

**Comment by bigeagle** [comment]
https://mirrors.tuna.tsinghua.edu.cn/ELK/apt/ 试一下？

**Comment by abcfy2** [comment]
或者目录名改叫`elastic.co`或`elastic`更合适？

**Comment by bigeagle** [comment]
暂时就叫 ELK 吧

**Comment by abcfy2** [comment]
有个报错:

```
W: https://mirrors.tuna.tsinghua.edu.cn/ELK/apt/elasticsearch/2.x/dists/stable/Release.gpg: Signature by key 46095ACC8548582C1A2699A9D27D666CD88E42B4 uses weak digest algorithm (SHA1)
```

**Comment by bigeagle** [comment]
这个不是我们的问题呀…… 是上游用了弱算法

**Comment by abcfy2** [comment]
确认了一下，的确是上游的问题。ubuntu 14.04不会有这个警告，ubuntu 16.04会打印这个警告。
