### ISSUE TITLE
GITLAB 11.4.0 EL7 镜像错误

### ISSUE THREAD

**Issue by jh163888** [tuna/issues#470]
清华镜像指纹：
MD5 | 08dced210d62c0e77a801a6fce0e7762
SHA1 | f3ec96279a4a574b303bfde37adfd0c10c28aad6
SHA256 | 5de36276b6990915507d4ad6c8a8e51457fd3f2b2fd8e1faa470f81b1ba3900e

REF: https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-11.4.0-ce.0.el7.x86_64.rpm

官方文件指纹：
MD5 | ed12ecaf3cd42800f50bd61540052ef2
SHA1 | 115740c5dab4d6a4d07a07c291373e42ce3abaf3
SHA256 | 6162aab8d7dac7b454467f560ed013abfa87c8a69329554ac042ecf473844493

REF: https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-11.4.0-ce.0.el7.x86_64.rpm

**Comment by huiyiqun** [comment]
https://github.com/tuna/issues/issues/415 不知道是否和这个 issue 有关。

**Comment by huiyiqun** [comment]
```
gitlab-ce-11.4.0-ce.0. (92%) 92% [============ ]  158 B/s | 403 MB  3583:45 ETA ^MCould not      retrieve package gitlab-ce-11.4.0-ce.0.el7.x86_64. Error was failure: gitlab-ce-11.4.0-ce.0.el7.x86_64.rpm from el7: [Errno 256] No more mirrors to try.
```

翻了一下日志，文件下载没有成功，但是留下了一个被截断的文件。

应该删除文件并标记更新失败。

**Comment by huiyiqun** [comment]
经查我们用的是 `reposync` 进行同步，`reposync` 并不支持我们所期待的行为（删除文件并失败退出）。

已经手动触发同步重新下载了该文件，如果该 repo 出现类似问题可以不用管它，下一轮同步(两天之后)的时候会自动解决。

可以考虑在 `tunasync` 里增加搜索日志的功能，当匹配正则时同步失败。

**Comment by jh163888** [comment]
Thanks! 之前一直用清华源YUM更新GITLAB，这次更新失败了GITLAB出错，最后还是手动强制更新了官方源才解决。感谢关注该ISSUE。
