### ISSUE TITLE
Mirror Requests - Ubuntu 18.10

### ISSUE THREAD

**Issue by ToonoW** [tuna/issues#471]
#### 项目名称与简介(Project Intro.)
2018.10.18发布的 ubuntu 18.10

**Comment by xavieryao** [comment]
在 https://mirrors.tuna.tsinghua.edu.cn/ 点击“获取下载链接”，选择 Ubuntu

**Comment by ToonoW** [comment]
> 在 https://mirrors.tuna.tsinghua.edu.cn/ 点击“获取下载链接”，选择 Ubuntu

其实我想表达的是，ubuntu的镜像源文档还没加上ubuntu18.10的文档选项
