### ISSUE TITLE
[feature] 改善Anaconda安装程序的下载UI

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#473]
与 tuna/mirror-web相关的小的feature请求

目前用户在下载anaconda时，有两种方法
 *  一种是纯文本的目录
    https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/
 *  另一种在web上费劲找
    https://mirrors.tuna.tsinghua.edu.cn/ "获取下载链接"->应用软件->conda 

无论哪一种，小白用户都需要figure out相应的版本
建议增加一个简单的网页，上面放置最新的anaconda，并且将python版本和操作系统版本的选择用一个简易的UI展现出来

类似于
![image](https://user-images.githubusercontent.com/8603485/47772047-664fd500-dd20-11e8-8fcd-414c27cc3816.png)

或者
![image](https://user-images.githubusercontent.com/8603485/47772120-9a2afa80-dd20-11e8-9348-f2aea381a517.png)

**Comment by jiegec** [comment]
我感觉更清真的做法是推荐用原生Python（逃

**Comment by huiyiqun** [comment]
…原生 python 在 windows 各种不方便…还要折腾编译器…你饶了他们吧……

而且 anaconda 的定位是 python 发行版…严格说它没什么不原生的…基本就是做打包工作了 这没什么好 diss 的

另外在这讨论这个问题 OT 了…会骚扰到对这个问题不感兴趣的人

**Comment by z4yx** [comment]
关于停止Anaconda镜像服务的通知 https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/

**Comment by x1angli** [comment]
> 关于停止Anaconda镜像服务的通知 https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/

好的，多问一句，是“未能取得授权”还是“未能得到回复”

**Comment by Harry-Chen** [comment]
> > 关于停止Anaconda镜像服务的通知 https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/
> 
> 好的，多问一句，是“未能取得授权”还是“未能得到回复”

他们态度并不积极，我们问了几次也没有 follow up
