### ISSUE TITLE
请求树莓派的linux内核代码树镜像

### ISSUE THREAD

**Issue by lwzheng12138** [tuna/issues#475]
#### 项目名称与简介(Project Intro.)
针对树莓派的linux内核

部分用户需要自己编译内核

#### 上游地址与镜像方法(How to Mirror)

地址:https://github.com/raspberrypi/linux.git

方法:git clone

#### 其他信息(Other)

- 镜像大小(Mirror Size): 约3-4G

**Comment by z4yx** [comment]
建议直接 clone TUNA 的主线linux源码镜像
然后再
 
```
git remove add rasp https://github.com/raspberrypi/linux.git
git fetch rasp
```

这样git会只下载差异部分，速度就很快了。

Linux内核的分支太多，我们不能每个分支都做镜像。

**Comment by scateu** [comment]
我们增加个help?

**Comment by scateu** [comment]
(以及这个用法第一次听说，好棒啊

**Comment by z4yx** [comment]
好我记得加个help，安排上了，
