### ISSUE TITLE
新增MX Linux / Antix镜像

### ISSUE THREAD

**Issue by aledie** [tuna/issues#476]
#### 项目名称与简介(Project Intro.)
https://mxlinux.org
https://distrowatch.com/table-mobile.php?distribution=mx

中文：
 https://www.linuxidc.com/Linux/2018-03/151387.htm

#### 上游地址与镜像方法(How to Mirror)
https://mxlinux.org/wiki/rsync-server/mirroring-mxantix-linux

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
MX-ISOs: 35 Gb
MX-Packages: 160 Gb

**Comment by anticapitalista** [comment]
antiX dev here - joining in on the request

**Comment by shankerwangmiao** [comment]
同步中，此 issue 保持 open 直到同步完成

**Comment by shankerwangmiao** [comment]
已经同步完成，https://mirrors.tuna.tsinghua.edu.cn/mxlinux/ 和 https://mirrors.tuna.tsinghua.edu.cn/mxlinux-isos/
