### ISSUE TITLE
Manjaro sync issue / manjaro 同步故障

### ISSUE THREAD

**Issue by bryango** [tuna/issues#477]
这几天 manjaro 源的同步似乎一直有问题，主页总显示 `failed`, 软件包似乎新旧不一... :joy: 

本人在 11 月 6 日升级系统时，没有注意到这一情况... 上述不一致性导致 `core/` 中的软件包未更新，而其余仓库依赖新版的 `core/`, 结果无法开机，手动干预后才解决... 由于 manjaro 同 arch 完全类似，采用 rolling release, 所有软件包的同步更新非常重要，望能解决。感谢！

There seems to be a persisting issue about the syncing of manjaro repo. Versions of packages seem to be inconsistent. This is particularly harmful for rolling-released systems like manjaro. Hope it is resolved soon!

**Comment by shankerwangmiao** [comment]
切换至 ipv6 后，同步成功。

**Comment by bryango** [comment]
![image](https://user-images.githubusercontent.com/26322692/48315270-f4746700-e60e-11e8-8b0f-6ef03c0618c2.png)
交大的镜像啊，他们有一个好，就是跑得比香港记者还快 [手动滑稽]
