### ISSUE TITLE
NTP server is not working 授时服务器坏了

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#478]
Category: Service Issues 服务故障

ntp服务器，貌似能ping通，但无法授时，显示error 

![image](https://user-images.githubusercontent.com/8603485/48309246-90bb5100-e5b0-11e8-969e-a0268f0c6d25.png)

**Comment by Harry-Chen** [comment]
您好，我们的NTP服务暂时只对清华大学校园网内提供服务。如果您不在清华大学校内，则是正常现象

**Comment by x1angli** [comment]
好的，谢谢楼上

之所以会有校外IP是因为一些下属机构（比如TBSI，甚至深研院）的IP多半和学校不是同一个网段。
既然不支持校外IP，最好网页（https://tuna.moe/help/ntp/）上备注一下“校园网IP地址only”。目前写的是“校内师生”lol

另外，目前ICMP是全开的，在校外`ping ntp.tuna.tsinghua.edu.cn`能通
