### ISSUE TITLE
Ubuntu 14.04 TLS 源出错

### ISSUE THREAD

**Issue by Roller44** [tuna/issues#48]
Err http://ppa.launchpad.net trusty/main Sources                                                                                                      
  
Err http://ppa.launchpad.net trusty/main Sources                                                                                                      
  404  Not Found
Fetched 5,818 kB in 10min 14s (9,466 B/s)
W: Failed to fetch http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/dists/trusty/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/dists/trusty/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/dists/trusty/main/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by bigeagle** [comment]
Hi, 这个报错的是第三方源 PPA 部分，不是从 TUNA 下载的。你看一下 `/etc/apt/sources.list.d/` 中的内容。

**Comment by Roller44** [comment]
好的。

**Comment by Roller44** [comment]
谢谢！
