### ISSUE TITLE
新增 GNU alpha 

### ISSUE THREAD

**Issue by wi24rd** [tuna/issues#480]
#### 项目名称与简介(Project Intro.)
GNU alpha
guix, shepherd, wget2  等一些包还没有完全达到生产的质量，release 在 alpha 里面，在 gnu 目录下还没有 。同时里面还有一些其他的项目的 alpha release。
在[一些情况](https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh)下会用到。
目前亚洲（至少官网上没写）还没有镜像，上面那个脚本里面的[包](https://alpha.gnu.org/gnu/guix/guix-binary-0.15.0.x86_64-linux.tar.xz)西安移动现在的下载速度小于 10KB/s

可以的话希望能顺便同步下下面的 nongnu （里面是一些非 GNU 官方项目的清真软件），暂时用不到就不再开 issue 了。

#### 上游地址与镜像方法(How to Mirror)
https://alpha.gnu.org/gnu
镜像方法应该[跟 GNU released 一样](https://www.gnu.org/server/mirror.en.html)。
```bash
rsync -rltpHS --delete-excluded rsync://ftp.gnu.org/alpha/ /your/dir/
```
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
[官网](https://www.gnu.org/server/mirror.en.html)写的差不多 10GB

**Comment by wi24rd** [comment]
#199 guix 在构建包的过程中会从 alpha 里下包，ftpmirror.gnu.org 能跳到国内的 gnu 镜像，但是 alpha 和 nongnu 的国内没有镜像速度就很慢。

**Comment by shankerwangmiao** [comment]
已经同步完毕了，在 https://mirrors.tuna.tsinghua.edu.cn/gnu-alpha
