### ISSUE TITLE
centos命令模式下如何登陆清华校园网？

### ISSUE THREAD

**Issue by shuyaoyimei** [tuna/issues#482]
学校校园网似乎只能网页登陆，可以通过pppoeconf设置么？

**Comment by z4yx** [comment]
学校是指清华吗？清华的认证可以用 https://github.com/syimyuzya/tunet-cli 或者 https://github.com/z4yx/goauthing

**Comment by shankerwangmiao** [comment]
或者可以使用 usereg 的代认证功能。
