### ISSUE TITLE
关于Solaris类系统的镜像申请

### ISSUE THREAD

**Issue by minmemory** [tuna/issues#486]
#### 项目名称与简介(Project Intro.)
由于Oracle宣布不再发行OpenSolaris，Illumos基金会成立并建立OpenIndiana以为OpenSolaris继续其更新
SmartOS是一个由Joyent创建的基于Illumos核心的系统平台，用于构建云计算和分布式系统(SmartOS的ISO镜像存储于Joyent Manta中)

#### 上游地址与镜像方法(How to Mirror)
官方没有明确说明方法，可以尝试使用常见的同步工具如rsync
* OpenIndiana ISO镜像 [http://dlc.openindiana.org](http://dlc.openindiana.org/isos)
* OpenIndiana软件包 [http://pkg.openindiana.org](http://pkg.openindiana.org)
* SmartOS软件包 [http://pkgsrc.joyent.com](http://pkgsrc.joyent.com)

#### 其他信息(Other)
* 镜像大小(Mirror Size): 不明
* 参考:
[https://smartos.skylime.net](https://smartos.skylime.net)
[http://pkgsrc.smartos.skylime.net](http://pkgsrc.smartos.skylime.net)

**Comment by minmemory** [comment]
rsync镜像源：pkg-origin.openindiana.org，见[Wiki](https://wiki.openindiana.org/oi/Making+a+LAN+mirror+of+global+package+repositories#MakingaLANmirrorofglobalpackagerepositories-rsyncthepackagerepositorycontentsandorupdates)

**Comment by heroxbd** [comment]
谢谢！我和 OpenIndiana 的团队联系了 。OpenIndiana 表示 IPS 系统当前没有可靠的软件包签名支持，镜像会有安全隐患。等 IPS 有了签名之后，再行考虑 OpenIndiana.
