### ISSUE TITLE
联通IPV6网络无法访问https://mirrors6.tuna.tsinghua.edu.cn

### ISSUE THREAD

**Issue by blkf2016** [tuna/issues#487]
地点：西安
traceroute 信息：
traceroute to mirrors6.tuna.tsinghua.edu.cn (2402:f000:1:408:8100::1), 30 hops max, 80 byte packets
 1  2408:8270:a5a:7500::1 (2408:8270:a5a:7500::1)  0.488 ms  0.842 ms  0.820 ms
 2  2408:8001:b010::10 (2408:8001:b010::10)  3.093 ms  3.526 ms  3.717 ms
 3  2408:8001:b011::10:2000 (2408:8001:b011::10:2000)  2.918 ms 2408:8001:b011::10:1004 (2408:8001:b011::10:1004)  4.562 ms 2408:8001:b011::10:1002 (2408:8001:b011::10:1002)  2.947 ms
 4  2408:8001:b011::ffff:2010 (2408:8001:b011::ffff:2010)  6.703 ms !N 2408:8001:b011::ffff:2002 (2408:8001:b011::ffff:2002)  7.756 ms !N 2408:8001:b011::ffff:2006 (2408:8001:b011::ffff:2006)  7.072 ms !N

**Comment by huiyiqun** [comment]
这个问题可能要找连通的 NOC 去解决

现在非教育网的 ipv6 的互联有些问题

Hui Yi-qun

**Comment by blkf2016** [comment]
但是USTC的ipv6服务器可以正常访问：
traceroute to mirrors6.ustc.edu.cn (2001:da8:d800:95::110), 30 hops max, 80 byte packets
 1  2408:8270:a5a:7500::1 (2408:8270:a5a:7500::1)  0.411 ms  0.827 ms  0.813 ms
 2  2408:8001:b010::10 (2408:8001:b010::10)  3.552 ms  3.587 ms  3.565 ms
 3  2408:8001:b011::10:1000 (2408:8001:b011::10:1000)  2.595 ms 2408:8001:b011::10:2002 (2408:8001:b011::10:2002)  2.415 ms 2408:8001:b011::10:1000 (2408:8001:b011::10:1000)  2.700 ms
 4  2408:8001:b011::ffff:2000 (2408:8001:b011::ffff:2000)  3.653 ms 2408:8001:b011::ffff:2010 (2408:8001:b011::ffff:2010)  9.016 ms 2408:8001:b011::ffff:1004 (2408:8001:b011::ffff:1004)  3.489 ms
 5  2408:8000:2:369:: (2408:8000:2:369::)  23.499 ms *  23.299 ms
 6  2408:8000:2:392::1 (2408:8000:2:392::1)  26.063 ms 2408:8000:2:630::1 (2408:8000:2:630::1)  31.150 ms 2408:8000:2:392::1 (2408:8000:2:392::1)  25.702 ms
 7  2408:8000:3::23 (2408:8000:3::23)  24.895 ms  24.890 ms 2408:8000:3::cd (2408:8000:3::cd)  39.801 ms
 8  2001:da8:257:0:101:4:7:1001 (2001:da8:257:0:101:4:7:1001)  37.259 ms 2001:da8:257:0:101:4:116:61 (2001:da8:257:0:101:4:116:61)  22.887 ms  22.886 ms
 9  * * *
10  2001:da8:2:701::1 (2001:da8:2:701::1)  23.108 ms 2001:da8:257:0:101:4:16:2a (2001:da8:257:0:101:4:16:2a)  40.248 ms 2001:da8:2:701::1 (2001:da8:2:701::1)  23.073 ms
11  2001:da8:2:1::2 (2001:da8:2:1::2)  33.096 ms  33.076 ms 2001:da8:257:0:101:4:1:1 (2001:da8:257:0:101:4:1:1)  36.983 ms
12  2001:da8:2:d::1 (2001:da8:2:d::1)  42.482 ms  42.360 ms  42.356 ms
13  * 2001:da8:2:e::2 (2001:da8:2:e::2)  49.433 ms *
14  2001:da8:2:701::1 (2001:da8:2:701::1)  38.479 ms 2001:da8:2:111::2 (2001:da8:2:111::2)  48.602 ms  48.632 ms
15  2001:da8:2:1::2 (2001:da8:2:1::2)  48.248 ms  48.506 ms  46.660 ms
16  2001:da8:2:d::1 (2001:da8:2:d::1)  56.144 ms 2001:da8:b3:fa02::1 (2001:da8:b3:fa02::1)  49.257 ms  49.253 ms
17  2001:da8:2:e::2 (2001:da8:2:e::2)  63.120 ms  62.372 ms  62.280 ms
18  2001:da8:d800:95::110 (2001:da8:d800:95::110)  47.570 ms 2001:da8:2:111::2 (2001:da8:2:111::2)  61.954 ms  61.950 ms

**Comment by shankerwangmiao** [comment]
还是 noc 的毛病。因为清华的地址段是 2402:f000::/32 的，是自有AS。可能是运营商的 BGP 邻居策略没有设置好。此问题已经反馈 noc。

**Comment by shankerwangmiao** [comment]
noc 反馈，近两天会解决此问题。

**Comment by shankerwangmiao** [comment]
此问题已经解决。
