### ISSUE TITLE
关于增加etl镜像的建议

### ISSUE THREAD

**Issue by wllfengshu** [tuna/issues#488]
#### 项目名称与简介(Project Intro.)
名称：kettle
简介：在大数据时代，数据的抽取、转换、清洗 （etl）都非常重要，目前etl在大数据中发挥着重要的作用。市场上最流行的开源etl工具之一kettle，功能也十分强大。希望贵站考虑增加kettle的镜像。

#### 上游地址与镜像方法(How to Mirror)
官网：https://sourceforge.net/projects/pentaho/
下载地址：https://nchc.dl.sourceforge.net/project/pentaho/Pentaho%208.2/client-tools/pdi-ce-8.2.0.0-342.zip

#### 其他信息(Other)
- 镜像大小(Mirror Size): 最新发行版本1.20 GB（zip格式）

**Comment by ZenithalHourlyRate** [comment]
参考 #928 ，TUNA较难镜像 sourceforge 提供的软件。

同时可以参考 https://github.com/BITNP/issues/issues/17
