### ISSUE TITLE
Request mirror for openSUSE arm

### ISSUE THREAD

**Issue by huiyifyj** [tuna/issues#489]
#### 项目名称与简介(Project Intro.)
openSUSE ARM版本（官方版本）的ISO镜像下载

> 虽然tuna已经有相应的open SUSE镜像，但并不是arm版的。

#### 上游地址与镜像方法(How to Mirror)
http://download.opensuse.org/ports/aarch64/

#### 其他信息(Other)
- 镜像大小(Mirror Size):  未知

**Comment by xixiliguo** [comment]
这个目前有计划吗？

**Comment by z4yx** [comment]
已增加 aarch64
