### ISSUE TITLE
请检查gitlab的最新centos7的镜像。文件错误。

### ISSUE THREAD

**Issue by vivuvv** [tuna/issues#49]
https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-8.6.6-ce.0.el7.x86_64.rpm
rt，文件仅仅有12mb。。所以请检查

**Comment by bigeagle** [comment]
感谢反馈！前两天把vpn关了，果然同步就遇到问题。现在已经修复。
