### ISSUE TITLE
关于 openmpi 镜像的请求

### ISSUE THREAD

**Issue by jinyiliu** [tuna/issues#490]
#### 项目名称与简介(Project Intro.)
OpenMpi 是一个 Linux 下的并行计算库，是一个在单台主机上进行并行计算。它在多核或多CPU结构上的效率很高、内存开销小、编程语句简洁直观，优点是编程容易、编译器实现也容易。

#### 上游地址与镜像方法(How to Mirror)
官网地址：[https://www.open-mpi.org](https://www.open-mpi.org)
Version 4.0 下载地址：[https://www.open-mpi.org/software/ompi/v4.0/](https://www.open-mpi.org/software/ompi/v4.0/)

不好意思，镜像方法不知 : (

#### 其他信息(Other)
- 镜像大小(Mirror Size): 不同版本不一样，Version4.0 的压缩文件是16.66 MiB

**Comment by shankerwangmiao** [comment]
openmpi 在各发行版的官方软件源中基本上都有收录，因此不再单独镜像。

**Comment by jinyiliu** [comment]
因为还不是很熟悉 Linux，手滑开了个 issue，问了个比较愚蠢的问题，谢谢！: )
