### ISSUE TITLE
manjaro-cd源位置更新

### ISSUE THREAD

**Issue by xu9010** [tuna/issues#491]
Manjaro-cd改位置了，虽然 #432已经提到这个问题，但是截止到今日依然没有同步上的样子。
引用官方notice如下（https://mirrors.tuna.tsinghua.edu.cn/manjaro-cd/README.md）
 ### ::  IMPORTANT NOTICE  ::

We have **MOVED** our Online Storage to **OSDN**.  
  
[![](https://manjaro.org/wp-content/uploads/2018/04/dl-button.png)](https://osdn.net/projects/manjaro/)

The latest Official Releases can be found at:  
https://osdn.net/projects/manjaro/

PS：
隔壁mirrors同步正常（https://mirrors.ustc.edu.cn/status/），他们的上游是：
rsync://ftp.iij.ad.jp/pub/osdn.jp/storage/g/m/ma/manjaro/

**Comment by huiyiqun** [comment]
https://github.com/tuna/issues/issues/432

现在 manjaro-cd 仅作为 archive 使用，我们直接同步了整个 OSDN，并且是 osdn 的[官方镜像](https://osdn.net/docs/Mirrors)，在正常配置下，从 osdn 下载文件（包括 manjaro）会直接重定向我们的网站。

**Comment by huiyiqun** [comment]
https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/m/ma/manjaro/ 如果想自己遍历文件的话。

有时间会在更新下载链接的脚本，从主页直接获取 manjaro 的安装镜像链接。在此之前留着这个 issue。
