### ISSUE TITLE
移除 tensorflow 仓库的帮助

### ISSUE THREAD

**Issue by x1angli** [tuna/issues#492]
https://mirror.tuna.tsinghua.edu.cn/help/tensorflow/
貌似这个网页的功能没有做完

而且tensorflow的各个版本的.whl文件在mirror上被同步得七晕八素

建议索性把这个网页删了，或者是选择的form删了只保留最基本的文字说明，让大伙自己去
https://mirrors.tuna.tsinghua.edu.cn/tensorflow/
上面手动下载（而不是让pip有选择性地下载）

**Comment by shankerwangmiao** [comment]
请见 #446

**Comment by huiyiqun** [comment]
当前 tensorflow 这个仓库已经不再更新，保留下来仅仅是历史原因。

主页上已经删除了 tensorflow 这个仓库，可以考虑把 tensorflow 的帮助页面也隐藏或删除。

比如在列表中删除，并重命名到 /_tensorflow/

**Comment by x1angli** [comment]
> 当前 tensorflow 这个仓库已经不再更新，保留下来仅仅是历史原因。
> 
> 主页上已经删除了 tensorflow 这个仓库，可以考虑把 tensorflow 的帮助页面也隐藏或删除。
> 
> 比如在列表中删除，并重命名到 /_tensorflow/

好的。不过不改变这个issue，这个issue应该还是处于open状态
理由是，不管删除不删除tensorflow 这个仓库，那个帮助都是有误导性的……所以建议把那些下拉框删除掉
