### ISSUE TITLE
请求OpenJDK源码镜像

### ISSUE THREAD

**Issue by rim99** [tuna/issues#498]
#### 项目名称与简介(Project Intro.)

OpenJDK是开源的Java开发环境，开源协议为GPLv2。

#### 上游地址与镜像方法(How to Mirror)

上游地址：http://hg.openjdk.java.net
镜像方法：未知。可参考[repositories](http://openjdk.java.net/guide/repositories.html)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

源码使用Mercurial管理，如果不方便，可以参考[Git-and-Other-Systems-Migrating-to-Git](https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git)转为Git管理。

**Comment by shankerwangmiao** [comment]
Openjdk 在各发行版的仓库里都有收录。因此不再单独镜像。

**Comment by rim99** [comment]
> Openjdk 在各发行版的仓库里都有收录。因此不再单独镜像。

您指的是$JAVA_HOME下面的src.zip么？这个文件里面只有OpenJDK的一部分，HotSpot虚拟机以及OpenJDK的JNI实现层的代码都没有包括在里面。

[OpenJDK 10](http://hg.openjdk.java.net/jdk10)和之前版本的源代码都包括
corba 、hotspot、jaxp、jaxws、jdk 、langtools 、nashorn等子仓库。

OpenJDK 11开始所有代码合为一个仓库[http://hg.openjdk.java.net/jdk-updates/jdk11u/](http://hg.openjdk.java.net/jdk-updates/jdk11u/)。

希望能够再考虑一下？

**Comment by shankerwangmiao** [comment]
一般情况下，多数软件的源代码不在收录范围内。在镜像站上的多数是开源软件的二进制分发版本。

**Comment by huiyiqun** [comment]
请问在什么场景下需要 openjdk 的"源代码"呢？

大部分情况下只需要编译好的 jdk 和 jre 即可吧？

Hui Yi-qun

**Comment by rim99** [comment]
我也理解错“发行版”的意思了。刚才看了下Linux发行版的包目录，发现确实可以找到源代码。只不过缺少commit history。借贵宝地记录一下，兴许可以帮助有和我同样需求的人。

>以我的Ubuntu 18.04LTS为例，
>
>```shell
>sudo apt-get install openjdk-11-source
>```
>
>然后在`/usr/lib/jvm/openjdk-11/lib/`里的`src.zip`就是源代码文件。
