### ISSUE TITLE
考虑删除 https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/index.html

### ISSUE THREAD

**Issue by hosiet** [tuna/issues#499]
目前 lineage 上游提供了 index.html 将用户重定向到官方下载页，但国内无法访问 https://download.lineageos.org/ 。请考虑将 index.html 删除以方便用户寻找镜像。

实例： https://mirrors.ustc.edu.cn/lineageos/ 从最开始就排除了 index.html 的同步。

**Comment by shankerwangmiao** [comment]
已删除
