### ISSUE TITLE
申请增加LyX镜像

### ISSUE THREAD

**Issue by jincao2013** [tuna/issues#501]
#### 项目名称与简介(Project Intro.)
LyX – The Document Processor
- 基于tex的“可见即所得”的文档处理系统。
- LyX是一个很方便的推导公式，写note，写论文的工具。
- 跨平台，包括Windows, Linux, Mac。

#### 上游地址与镜像方法(How to Mirror)
- 原版下载地址
https://www.lyx.org/Download
- 原版ftp地址
ftp://ftp.lyx.org/
https://ftp.lip6.fr/
- 国内镜像(目前国内只有上海大学有LyX的镜像)
ftp://mirrors.shu.edu.cn/lyx/

#### 其他信息(Other)
- 镜像大小(Mirror Size): Windows和Linux 版本大约50MB，Mac版本大约100MB。

**Comment by shankerwangmiao** [comment]
已经上线 https://mirrors.tuna.tsinghua.edu.cn/lyx

**Comment by jiegec** [comment]
发个邮件给 lyx 加入到列表里？

**Comment by shankerwangmiao** [comment]
没找到他们在哪收邮件。

**Comment by jiegec** [comment]
lyx-devel@lists.lyx.org

**Comment by shankerwangmiao** [comment]
要不你发一份吧
