### ISSUE TITLE
OpenBSD镜像无法下载

### ISSUE THREAD

**Issue by emacsliu1107** [tuna/issues#502]
#### 项目名称与简介(Project Intro.)
OpenBSD
#### 上游地址与镜像方法(How to Mirror)
https://mirrors.tuna.tsinghua.edu.cn/OpenBSD/6.4/amd64/install64.iso
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
网站已经打不开了。。

**Comment by shankerwangmiao** [comment]
经排查，我们服务器暂时未发现异常。建议您仔细排查一下您的网络情况。
