### ISSUE TITLE
Raspberry mirorrs  bluez-tools 404 not found 

### ISSUE THREAD

**Issue by nejidev** [tuna/issues#503]
# raspberry 3b+
* sudo apt-get update
* sudo apt-get install bluez-tools

# lsb_release -a
* Description:	Raspbian GNU/Linux 9.4 (stretch)

# logs
sudo apt-get install bluez-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  bluez-obexd libical2
The following NEW packages will be installed:
  bluez-obexd bluez-tools libical2
0 upgraded, 3 newly installed, 0 to remove and 107 not upgraded.
Need to get 176 kB/447 kB of archives.
After this operation, 1,945 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://mirrors.ustc.edu.cn/archive.raspberrypi.org stretch/main armhf bluez-obexd armhf 5.43-2+rpt2+deb9u2
  404  Not Found [IP: 218.104.71.170 80]
E: Failed to fetch http://mirrors.ustc.edu.cn/archive.raspberrypi.org/pool/main/b/bluez/bluez-obexd_5.43-2+rpt2+deb9u2_armhf.deb  404  Not Found [IP: 218.104.71.170 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by xavieryao** [comment]
你用的貌似是 USTC 的镜像？请移步 LUG@USTC Issue Tracker https://github.com/ustclug/discussions/issues
