### ISSUE TITLE
apache-thrift-0.9.3 configuration error

### ISSUE THREAD

**Issue by Force-King** [tuna/issues#504]
Problem：https://github.com/tuna/issues/issues/326
I also have this problem. According to the solution of the above problem, I tried, but still did not solve.

My environ:
mac os Mojave 10.14.2
openssl 1.0.2q 
apache-thrift-0.9.3

run ./configure.
An error:configure: error: "Error: libcrypto required."

**Comment by shankerwangmiao** [comment]
dup with #326, reopen
