### ISSUE TITLE
gradle的分发仓库

### ISSUE THREAD

**Issue by LeonDevLifeLog** [tuna/issues#505]
#### 项目名称与简介(Project Intro.)
gradle distributions 
gradle的分发仓库
#### 上游地址与镜像方法(How to Mirror)
地址:`https://services.gradle.org/distributions/`
方法: `反向代理` 或 `直接镜像`
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
~50G

**Comment by shankerwangmiao** [comment]
上游是否有 rsync?

**Comment by huiyiqun** [comment]
@shankerwangmiao 就一个目录，文件也不会经常更新，直接写一个爬虫或者 lftp 都可以解决，rsync 不是关键问题。

主要问题是这个东西是给 gradle wrapper 用的，gradle wrapper 还[不支持mirror](https://github.com/gradle/gradle/pull/6349)，即使我们镜像了用户也没法用。

等上面这个 pr 被合并之后再讨论这个问题吧。

**Comment by LeonDevLifeLog** [comment]
@huiyiqun 
每个gradle工程gradle wrapper文件夹里的distributionUrl是可以手动改的

目前找到了替代方案

使用七牛云对象存储功能,把https://services.gradle.org/distributions/配置为对象存储的镜像地址,然后把url替换一下就OK了,免费额度也够用了

**Comment by Harry-Chen** [comment]
以及 Gradle 的许可证是否允许二进制的镜像？

**Comment by LeonDevLifeLog** [comment]
在gradle论坛里找到一个使用Nexus代理的方法 参考[这里](https://discuss.gradle.org/t/how-to-mirror-the-gradle-services-for-internal-distributions/23217)

gradle官方团队应该愿意被代理或分发吧  
参见这里 gradle/gradle#5943

**Comment by Harry-Chen** [comment]
目前 gradle 使用了 CloudFlare 作为 CDN，实测国内下载速度较快，无需镜像
