### ISSUE TITLE
清华大学官方维护的第三方pytorch镜像不生效

### ISSUE THREAD

**Issue by LittleFatHero** [tuna/issues#506]
根据tuna官方的介绍，使用如下命令将清华大学维护的第三方pytorch源添加到conda的源路径中（优先级已经是最高）：
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
然后根据pytorch官方提供的命令来安装pytorch，发现conda并没有从刚才添加的清华大学官方的源下载安装pytorch，而是从默认的源来下载安装，安装时必须使用conda install  -c  来指定清华大学的源才行，为什么？

**Comment by jiegec** [comment]
Anaconda 的其他源正常吗

**Comment by BigBigWolf-AI** [comment]
其它源正常，就是pytorch这个源必须明确在命令行中指定才生效，不知道为什么

**Comment by jinzhen-lin** [comment]
可以试试
```
conda config --set channel_alias https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
```

详见[conda配置文档](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#set-a-channel-alias-channel-alias)

**Comment by shiyongkun** [comment]
同样遇到了这个问题，虽然可能跟楼主的情况不一样，不过姑且写出来提醒一下跟我一样的小白：

pytorch官方提供的安装命令`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`中，最后的`-c pytorch`指定了使用官方源，要使用第三方源的话把这个参数去掉即可。

**Comment by LittleFatHero** [comment]
> 同样遇到了这个问题，虽然可能跟楼主的情况不一样，不过姑且写出来提醒一下跟我一样的小白：
> 
> pytorch官方提供的安装命令`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`中，最后的`-c pytorch`指定了使用官方源，要使用第三方源的话把这个参数去掉即可。

我傻了，竟然没发现这个问题，厉害了

**Comment by TimeLessLing** [comment]
> > 同样遇到了这个问题，虽然可能跟楼主的情况不一样，不过姑且写出来提醒一下跟我一样的小白：
> > pytorch官方提供的安装命令`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`中，最后的`-c pytorch`指定了使用官方源，要使用第三方源的话把这个参数去掉即可。
> 
> 我傻了，竟然没发现这个问题，厉害了

但是我关掉了这个-c命令之后，在Solving enviroment步骤中，显示出来还是在通过default的channel来安装呀

**Comment by z4yx** [comment]
试试用 `conda clean -i` 清缓存
