### ISSUE TITLE
更新Anaconda Cloud 官方channel上的cudatoolkit包

### ISSUE THREAD

**Issue by peterjc123** [tuna/issues#507]
根据conda-forge的[要求](https://github.com/conda-forge/conda-forge.github.io/issues/687?fbclid=IwAR3tM-mLzhezcKmVrPdcyN6Kzl3oaVo4A7uWBeeaxvGl9E-Caw4Uw6is_LY), 依赖CUDA的conda包需要添加对Anaconda Cloud上的cudatoolkit包的依赖，目前tuna的镜像上只有CUDA 8的包，但是官方源上已有CUDA 9，9.2和10的包。希望能早日更新。

**Comment by z4yx** [comment]
关于停止Anaconda镜像服务的通知 https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/
