### ISSUE TITLE
申请增加 OmniROM 源代码镜像

### ISSUE THREAD

**Issue by funnypro** [tuna/issues#508]
#### 项目名称与简介(Project Intro.)
OmniROM 是一个 Android 发行版
> OmniROM is our Android custom ROM variant, feature-packed but always with stability as #1 priority in mind.
> Based on the Android Open Source Project (AOSP) and enriched by our developers with lots of custom enhancements, OmniROM has set out to give you a great Android experience on your mobile.

#### 上游地址与镜像方法(How to Mirror)
git 仓库
git://github.com/omnirom/android.git

镜像方法
repo init -u git://github.com/omnirom/android.git -b android-8.1
repo sync

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by huiyiqun** [comment]
需要镜像这样的项目需要一个 mirror repo（类似于[这个](https://github.com/lineageos/mirror)）

omnirom 似乎没有提供这样的 repo，因此无法镜像。
