### ISSUE TITLE
Mirror Request: Rust toolchain static (for rustup)

### ISSUE THREAD

**Issue by uHOOCCOOHu** [tuna/issues#509]
#### 项目名称与简介(Project Intro.)

Rust toolchains for [`rustup`](https://rustup.rs/), including the the _binary distribution of compiler and some components_.

This is **DIFFER** from rust crates (aka. packages) in #98.

* Currently, [USTC](https://mirrors.ustc.edu.cn/help/rust-static.html) has a reverse proxy of it.

#### 上游地址与镜像方法(How to Mirror)

Upstream: https://static.rust-lang.org/

- The format of index file: rust-lang/rustup.rs#1467
- You can directly view the directory of a version using the url like: https://static.rust-lang.org/dist/2019-01-18/

#### 其他信息(Other)
- 镜像大小(Mirror Size): ~1.5 GiB per version (day). 
  The nightly version (`/dist/channel-rust-nightly.toml`) is updated everyday, and the stable version (`/dist/channel-rust-stable.toml`, see rust-lang/rustup.rs#1467) is published every six weeks.
- 镜像使用方法(Mirror Usage): Mentioned in the first issue above and the documentation from USTC.

**Comment by jiegec** [comment]
Working on it.

**Comment by jiegec** [comment]
See https://github.com/jiegec/rustup-mirror .

**Comment by jiegec** [comment]
说好的1.5G呢？？？光一天我已经下载10G了。。

**Comment by Harry-Chen** [comment]
@jiegec 原文写的是 1.5GB __per version__

**Comment by jiegec** [comment]
就是 rust stable 1.32.0 一个版本啊

**Comment by jiegec** [comment]
唔 nightly 似乎也没问题了。

**Comment by jiegec** [comment]
See https://github.com/tuna/tunasync-scripts/pull/27

**Comment by jiegec** [comment]
见 https://mirrors.tuna.tsinghua.edu.cn/rustup/
