### ISSUE TITLE
ncurses5-compat-libs：signature

### ISSUE THREAD

**Issue by Toocc** [tuna/issues#51]
tuna **[archlinuxcn] **的签名好像有点问题：
error: ncurses5-compat-libs: signature from "lilac (build machine) <lilac@build.archlinuxcn.org>" is invalid
:: File /var/cache/pacman/pkg/ncurses5-compat-libs-6.0-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).

解决：我换成163的镜像就可以装了。
Arch Linux CN Community repo mirrors list：https://github.com/archlinuxcn/mirrorlist-repo

**Comment by bigeagle** [comment]
我换成了官方地址也装不了，感觉是上游的锅
