### ISSUE TITLE
[Mirror Requests]Linuxbrew

### ISSUE THREAD

**Issue by jk2K** [tuna/issues#510]
#### 项目名称与简介(Project Intro.)
[Linuxbrew](https://docs.brew.sh/Linuxbrew), fork 自 [Homebrew](https://brew.sh/), 现已被官方接受, 可以用来管理 Linux 和 Windows 10 (基于  WSL) 的包

#### 上游地址与镜像方法(How to Mirror)
https://github.com/Linuxbrew/brew

https://github.com/Linuxbrew/homebrew-core

也许可以参考 Homebrew 的镜像帮助 https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by jiegec** [comment]
Linuxbrew 也有 bottles 么？

**Comment by jk2K** [comment]
有的   https://bintray.com/linuxbrew/bottles

**Comment by jk2K** [comment]
https://github.com/Linuxbrew/brew 可以不用镜像, https://github.com/Homebrew/brew 同时支持 macOS 和 linux,   https://github.com/Linuxbrew/brew 这个仓库估计后面会不再维护

**Comment by jk2K** [comment]
related to https://github.com/ustclug/mirrorrequest/issues/98

**Comment by athrunsun** [comment]
@jk2K https://github.com/Linuxbrew/brew可以不用了，因为Homebrew 2.0开始官方支持linux了。但是https://github.com/Linuxbrew/homebrew-core需要镜像，这个repo跟https://github.com/Homebrew/homebrew-core是不一样的，包含了linux独有的一些app。

**Comment by jk2K** [comment]
我正在给 https://github.com/gaoyifan/homebrew-bottle-mirror 增加 linux bottles 的镜像功能, 过几天应该可以完成

**Comment by jk2K** [comment]
fixed by https://github.com/gaoyifan/homebrew-bottle-mirror/pull/4

**Comment by menghuu** [comment]
啥时候能用？

**Comment by jiegec** [comment]
Waiting for upstream merge.

**Comment by abcfy2** [comment]
+1 同样等待这个镜像

**Comment by athrunsun** [comment]
@jk2k 已经2020年了还是没有在tuna镜像看到linuxbrew-core和linuxbrew-bottles的镜像呢？还需要什么额外的操作吗？

**Comment by jk2K** [comment]
上游已合并，等待 @jiegec 处理

**Comment by z4yx** [comment]
我先来实验一下 gaoyifan/homebrew-bottle-mirror 工具

**Comment by z4yx** [comment]
加上了，欢迎使用。帮助页面跟原有的homebrew共用。（如果没见到更新请刷新下）

**Comment by athrunsun** [comment]
@jk2K @z4yx 谢谢！
但是我并没有找到https://github.com/Linuxbrew/homebrew-core的镜像呢。。。

**Comment by z4yx** [comment]
Linuxbrew/homebrew-core 已经更名为 Homebrew/linuxbrew-core
使用方法按照 https://neomirrors.tuna.tsinghua.edu.cn/help/homebrew/

**Comment by athrunsun** [comment]
@z4yx 看到了，多谢回复！
