### ISSUE TITLE
[FEATURE REQUEST] 如何捐钱？

### ISSUE THREAD

**Issue by adam900710** [tuna/issues#512]
TUNA源，从archlinuxarm到raspbian都极大的改善了生活质量。

有啥方法捐钱么？最好类似Patreon那种每个月捐个50的那种。

**Comment by shankerwangmiao** [comment]
一般来讲我们不太接受捐赠，因为捐赠的钱几乎不会被用于镜像站运行，捐赠的钱多用于举办社团活动。如果你确实要捐献的话，可以支付宝给 donation@tuna.tsinghua.edu.cn

**Comment by Harry-Chen** [comment]
更正：上述账号应该是 donate@tuna.tsinghua.edu.cn
