### ISSUE TITLE
我是 macport 新手。最近需要安装 mpich-default，但总是失败，是不是镜像里缺少这个？

### ISSUE THREAD

**Issue by phycomdoc** [tuna/issues#513]
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
请执行 `sudo port rev-upgrade`，然后再安装。看起来是 macports 有些 bug。

**Comment by phycomdoc** [comment]
现在可以了。可能是我在网络不好的情况下安装的 macport 不全。重装了下，解决了问题了

**Comment by shankerwangmiao** [comment]
其实不是，我这边也遇到了这个问题，看起来可能是依赖安装不全导致的。
