### ISSUE TITLE
获取debian Stretch的hhvm包报错

### ISSUE THREAD

**Issue by Adpex** [tuna/issues#514]
![image](https://user-images.githubusercontent.com/16286708/53300936-1d4ffd80-3888-11e9-8e17-4aa6f511b760.png)

如图，不知是否使用的方法不对？
完整的操作步骤：

`wget -O- https://mirrors.tuna.tsinghua.edu.cn/HHVM/conf/hhvm.gpg.key | sudo apt-key add -`

`echo deb https://mirrors.tuna.tsinghua.edu.cn/HHVM/debian Stretch main | sudo tee /etc/apt/sources.list.d/hhvm.list`

`sudo apt-get update`

**Comment by jiegec** [comment]
Stretch -> stretch

**Comment by Adpex** [comment]
> Stretch -> stretch

![image](https://user-images.githubusercontent.com/16286708/53307785-ee14ad00-38d6-11e9-88a0-2e13fb26c11e.png)

变成了这样。。。

**Comment by jiegec** [comment]
这可能是正在同步，所以文件不一致。您可以查看一下同步状态，并且稍后再尝试。如果还有问题，请及时回复。

**Comment by Adpex** [comment]
> 这可能是正在同步，所以文件不一致。您可以查看一下同步状态，并且稍后再尝试。如果还有问题，请及时回复。

好的，感谢，我先关闭问题了
