### ISSUE TITLE
android NDK src 镜像同步申请

### ISSUE THREAD

**Issue by haolongzhangm** [tuna/issues#519]
#### 项目名称与简介(Project Intro.)

android NDK src

#### 上游地址与镜像方法(How to Mirror)
repo init -u https://android.googlesource.com/platform/manifest   -b master-ndk

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by huiyiqun** [comment]
android ndk 是 aosp 的一部分，请参考 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ 下载。
