### ISSUE TITLE
百度文库资源共享请求

### ISSUE THREAD

**Issue by gladuo** [tuna/issues#52]
得知贵校与百度合作，可以任意下载百度文库资源，不知道能不能对周围学校提供一个代理接口，方便邻校同学。如果可以请评论或给我个邮件。

**Comment by alick** [comment]
噢？不过这很可能 violate ToS 吧

**Comment by bigeagle** [comment]
百度文库内容并非自由可分发，学校购买的版权仅适用于校内使用。

**Comment by scateu** [comment]
其实对付百度文库这种，最好的办法就是去淘宝啦~
几块钱下个够...

(而且作为校友，觉得贵校买了百度文库不是啥光彩的事情>_<)

**Comment by bigeagle** [comment]
同觉得不光彩。

**Comment by gladuo** [comment]
Thank you, anyway.
