### ISSUE TITLE
pypi 镜像源缺少pre-release版本

### ISSUE THREAD

**Issue by ficapy** [tuna/issues#520]
使用pypi镜像源无法安装预发布版本，能够添加支持吗？
```
pip install psqlparse==1.0rc6 -i https://mirrors.ustc.edu.cn/pypi/web/simple
```

相关页面
[https://pypi.org/project/psqlparse/1.0rc6/#history](https://pypi.org/project/psqlparse/1.0rc6/#history)

**Comment by shitou1992** [comment]
估计没同步完成吧，看json里是有的，packages里的确没有：
‘’‘
"1.0rc6": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "21597894a64675375c52489e8072ff15",
                    "sha256": "a4b2f23a262eab3071e7f042f508147cde494838e60d1dd05ec036f8b6dad302"
                },
                "downloads": -1,
                "filename": "psqlparse-1.0rc6.tar.gz",
                "has_sig": false,
                "md5_digest": "21597894a64675375c52489e8072ff15",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": null,
                "size": 36839,
                "upload_time": "2019-03-03T01:58:41",
                "url": "https://files.pythonhosted.org/packages/71/33/f18f42c43b9c5d8ca4c9d2f3f3cfb4db139572b399684db22b94e795a26a/psqlparse-1.0rc6.tar.gz"
            }
        ]
    },
‘’’

**Comment by ficapy** [comment]
> 估计没同步完成吧，看 json 里是有的，packages 里的确没有：
> ```
> "1.0rc6": [
> {
> "comment_text": "",
> "digests": {
> "md5": "21597894a64675375c52489e8072ff15",
> "sha256": "a4b2f23a262eab3071e7f042f508147cde494838e60d1dd05ec036f8b6dad302"
> },
> "downloads": -1,
> "filename": "psqlparse-1.0rc6.tar.gz",
> "has_sig": false,
> "md5_digest": "21597894a64675375c52489e8072ff15",
> "packagetype": "sdist",
> "python_version": "source",
> "requires_python": null,
> "size": 36839,
> "upload_time": "2019-03-03T01:58:41",
> "url": "https://files.pythonhosted.org/packages/71/33/f18f42c43b9c5d8ca4c9d2f3f3cfb4db139572b399684db22b94e795a26a/psqlparse-1.0rc6.tar.gz"
> }
> ]
> },
> ```

不好意思，没明白这个package.json是从哪里来的，和pypi镜像同步存在什么关系
pip安装的时候访问html页面依次解析URL得到版本号，如果匹配则进行下载安装

**Comment by zmwangx** [comment]
另外，

> https://mirrors.ustc.edu.cn/pypi/web/simple

这是中科大的镜像啊，你好像汇报错地方了……虽然是同一个问题。

**Comment by encofcomic** [comment]
> 
> 
> 另外，
> 
> > https://mirrors.ustc.edu.cn/pypi/web/simple
> 
> 这是中科大的镜像啊，你好像汇报错地方了……虽然是同一个问题。

科大镜像现在的pypi源的http服务是重定向到tuna的，所以也可以算tuna的问题吧

**Comment by z4yx** [comment]
https://pypi.org/simple/web/ 上游也是空的呀

**Comment by z4yx** [comment]
现在这两个包看起来好了。
从pypi的cdn下载文件经常失败，所以会出现文件少的情况。bandersnatch同步工具也不够鲁棒，只能遇到了人工处理。
