### ISSUE TITLE
The Julia Language

### ISSUE THREAD

**Issue by isyt** [tuna/issues#522]
#### The Julia Language
Julia is a high-level, high-performance dynamic language for technical computing. The main homepage for Julia can be found at julialang.org. This is the GitHub repository of Julia source code, including instructions for compiling and installing Julia, below.
#### https://github.com/JuliaLang/julia
git

**Comment by Harry-Chen** [comment]
We don't mirror any repository hosted on GitHub. If you believe this was a mistake, you can re-open this issue and add more detail.
