### ISSUE TITLE
申请镜像CentOS CERN 7

### ISSUE THREAD

**Issue by tuhep** [tuna/issues#524]
#### 项目名称与简介(Project Intro.)
* CentOS CERN 7

    CentOS CERN是欧洲核子研究中心（CERN）基于CentOS内核开发的用于科学计算的Linux发行版，其中定制了很多与科学计算相关的软件包。全球不少大型实验都采用该操作系统作为计算平台，例如大型强子对撞机上的所有实验，包括清华大学2000年加入的LHCb实验。

#### 上游地址与镜像方法(How to Mirror)

  * 上游地址：http://linuxsoft.cern.ch/cern/centos/7/
  * 镜像方法：http,ftp 和 rsync protocols都可以
 
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
  * 662G (其中Updates目录434.5G）

**Comment by jiegec** [comment]
已收到镜像申请，近日正在研究尝试同步，请稍等。

**Comment by tuhep** [comment]
多谢。正式这个源。
祝好！
工物系杨振伟

**Comment by jiegec** [comment]
您好，抱歉之前没有回复您的邮件，如果这个满足了您的需求，烦请您简单写一下这个源的使用方法？我们可以把它贴到网站上让更多人知道如何使用这个源。

**Comment by tuhep** [comment]
好。我找学生试一下，写个说明。发自我的华为手机-------- 原始邮件 --------主题：Re: [tuna/issues] 申请镜像CentOS CERN 7 (#524)发件人：Chen 收件人：tuna/issues 抄送：tuhep ,Author 您好，抱歉之前没有回复您的邮件，如果这个满足了您的需求，烦请您简单写一下这个源的使用方法？我们可以把它贴到网站上让更多人知道如何使用这个源。

**Comment by tuhep** [comment]
这个镜像好像无法访问了（显示404 Not Found）：
https://mirrors.tuna.tsinghua.edu.cn/cc/ 
能帮忙看一下什么原因吗？

**Comment by jiegec** [comment]
您好，很不巧我们有一台服务器的文件系统出现了性能问题，cc刚好只在这台服务器上保存，目前这台服务器处于正在修复的状态，可能要等几天。

**Comment by ericbrownrenzan** [comment]
## About CERN CentOS

CERN CentOS (CC) is CERN customized distribution that is built on top of the CentOS Core and it is tailored to integrate within the CERN computing environment.

## Installation Guidance

1. Prepare a bootable media. You will need a recordable CD or USB memory disk. Available image can be downloaded from
```
http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/images/boot.iso
```
or 
```
https://mirrors.tuna.tsinghua.edu.cn/cc/7/os/x86_64/images/boot.iso
```
Burn file `boot.iso` to your CD or USB disk.
2. Boot your workstation from the CD (or USB disk), then select *Install CentOS 7*
3. Choose the installation language, keyboard, date & time. Click the *Network & Hostname* button and may sure your computer has a valid IP address and can directly access public resources.
4. Click *Installation Source*, choose `On the network` option, type
```
http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/
```
or 
```
https://mirrors.tuna.tsinghua.edu.cn/cc/7/os/x86_64/
```
as installation path.

**Comment by jiegec** [comment]
Many thanks!

**Comment by z4yx** [comment]
cc 已恢复，slc 还在同步中
