### ISSUE TITLE
连接到nanomirrors时会频繁出现没有速度的情况

### ISSUE THREAD

**Issue by xlfjn** [tuna/issues#525]
首先，感谢贵校提供了这么优秀的mirror服务！

最近发现更新软件包时偶尔会没有速度，便尝试调试了一下。使用的命令是
`curl -v -o /dev/null http://mirrors6.tuna.tsinghua.edu.cn/debian-cd/9.8.0/amd64/iso-dvd/debian-9.8.0-amd64-DVD-2.iso`
我所在学校的校园网会通过教育网连接到mirror4和mirrors6。我大致能确认，不论是否使用https还是通过v4/v6连接，这个速度降到0的情况只会出现在HTTP头中有`X-TUNA-MIRROR-ID: nanomirrors`时。如果为`X-TUNA-MIRROR-ID: neomirrors`则能保持较高的速度。

一开始我设置了`net.ipv4.tcp_ecn=1`，开始调试后我把它改回了`net.ipv4.tcp_ecn=2`，并确认发出的TCP包已不再带有ECN，不过看起来对结果没有影响。

![v4](https://user-images.githubusercontent.com/10358113/54331842-ae7bee00-4656-11e9-8118-93647d9093b9.png)
![v6](https://user-images.githubusercontent.com/10358113/54331961-1d594700-4657-11e9-96b1-5c79ede37723.png)

**Comment by Harry-Chen** [comment]
最近 nanomirrors 的磁盘性能出现了一些问题

**Comment by Harry-Chen** [comment]
目前我们暂时下线了 nanomirrors 进行修复

**Comment by z4yx** [comment]
经过 shankerwangmiao 调整参数后， nanomirrors 已恢复服务，目前性能稳定。
