### ISSUE TITLE
[Mirror Request] KiCad 下载

### ISSUE THREAD

**Issue by taotieren** [tuna/issues#526]
#### 项目名称与简介(Project Intro.)
     KiCad 下载
#### 上游地址与镜像方法(How to Mirror)
    https://kicad-downloads.s3.cern.ch/index.html?prefix=
#### 其他信息(Other)
- 镜像大小(Mirror Size): ≈200G

**Comment by z4yx** [comment]
不知是否有工具能够解析并同步这种以http协议提供的s3存储

**Comment by taotieren** [comment]
还没具体了解

**Comment by taotieren** [comment]
wget -m https://kicad-downloads.s3.cern.ch/index.html?prefix=

@z4yx 有尝试wget这种方式吗？tuna 那边是用什么方式做镜像的呢？

**Comment by taotieren** [comment]
http://www.360doc.com/content/18/0324/07/48169514_739732267.shtml

**Comment by z4yx** [comment]
要能支持增量同步，比如 rsync。

**Comment by z4yx** [comment]
s3这种xml我觉得应该是支持用某种工具来同步的，但我没找到

**Comment by z4yx** [comment]
我弄明白同步方法了，可以尝试同步一下。命令为：

`aws --no-sign-request --endpoint-url=https://s3.cern.ch/ s3 sync s3://kicad-downloads/ /tmp/test/`

**Comment by taotieren** [comment]
> 我弄明白同步方法了，可以尝试同步一下。命令为：
> 
> `aws --no-sign-request --endpoint-url=https://s3.cern.ch/ s3 sync s3://kicad-downloads/ /tmp/test/`

测试效果如何

**Comment by z4yx** [comment]
已开始同步

**Comment by taotieren** [comment]
@z4yx Thanks！

**Comment by daiguoliangfirst** [comment]
@z4yx 这种同步方法支持增量同步吗？

**Comment by z4yx** [comment]
> @z4yx 这种同步方法支持增量同步吗？

支持，s3工具内置的同步功能

**Comment by taotieren** [comment]
@z4yx 想为镜像站里面的镜像提供使用帮助，改如何做呢

**Comment by z4yx** [comment]
像这样创建一个文件，然后pr
https://github.com/tuna/mirror-web/blob/master/_posts/help/2019-05-03-qubesos.md

**Comment by z4yx** [comment]
像这样创建一个文件，然后pr
https://github.com/tuna/mirror-web/blob/master/_posts/help/2019-05-03-qubesos.md

**Comment by taotieren** [comment]
@z4yx 这是我新增的 KiCad 帮助文件 https://github.com/tuna/mirror-web/pull/140
