### ISSUE TITLE
tinycore镜像源不能用啊

### ISSUE THREAD

**Issue by mini536** [tuna/issues#527]
我填的是https://mirrors.tuna.tsinghua.edu.cn/tinycorelinux/
但是包管理器提示错误
哪里错了

**Comment by mini536** [comment]
找到问题了，使用终端，输入
vi /opt/tcemirror
按a键，改成https://mirrors4.tuna.tsinghua.edu.cn/tinycorelinux/
esc键，输入ZZ
再打开包管理器就可以正常使用了

**Comment by jiegec** [comment]
这可能是您的ipv6互联网访问不可用导致的。
