### ISSUE TITLE
[Mirror Request] Fedora (Branched)

### ISSUE THREAD

**Issue by ZeroAurora** [tuna/issues#528]
#### 项目名称与简介(Project Intro.)
Fedora Branched 开发版本
#### 上游地址与镜像方法(How to Mirror)
同 fedora，子目录 /development/[下一版本号]
#### 其他信息(Other)
- 镜像大小(Mirror Size): 类似 Fedora 中单个版本软件源的大小

不明白为什么把 branched 和 rawhide 从镜像中去掉了，可能是因为更新太频繁？
Branched 的版本号会变，但 development 目录里除了 rawhide 就只剩 branched 版本了
事实上有其他站点做 branched 镜像了…还是希望多多益善😌

**Comment by xuthus5** [comment]
华为开源镜像站 https://mirrors.huaweicloud.com/fedora/

**Comment by shankerwangmiao** [comment]
@sztsian ?
