### ISSUE TITLE
gitlab-ce 有文件损坏

### ISSUE THREAD

**Issue by zhsj** [tuna/issues#532]
https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/debian/pool/stretch/main/g/gitlab-ce/gitlab-ce_11.9.1-ce.0_amd64.deb

![image](https://user-images.githubusercontent.com/227180/55102780-21c73a80-5102-11e9-9148-f3d8537c8596.png)

大小明显不正常。。

**Comment by chpiter** [comment]
+1

**Comment by AifeiI** [comment]
镜像文件：
https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-11.9.1-ce.0.el7.x86_64.rpm
![image](https://user-images.githubusercontent.com/3113485/55128243-d470ba80-514d-11e9-9bd7-af7ffc0cad57.png)


Gitlab-CE 官方源文件：
https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-11.9.1-ce.0.el7.x86_64.rpm
![image](https://user-images.githubusercontent.com/3113485/55128255-e05c7c80-514d-11e9-8335-71d5fafa9905.png)

同步又一次出现失败

**Comment by z4yx** [comment]
正在同步中，目前网速较慢，请耐心等待。

```
$ tail -f /home/log/tunasync/gitlab-ce/latest 
[el6: 144   of 451   ] Skipping existing gitlab-ce-11.7.5-ce.0.el6.x86_64.rpm
[el6: 145   of 451   ] Skipping existing gitlab-ce-11.7.6-ce.0.el6.x86_64.rpm
[el6: 146   of 451   ] Skipping existing gitlab-ce-11.7.7-ce.0.el6.x86_64.rpm
[el6: 147   of 451   ] Skipping existing gitlab-ce-11.8.0-ce.0.el6.x86_64.rpm
[el6: 148   of 451   ] Skipping existing gitlab-ce-11.8.1-ce.0.el6.x86_64.rpm
[el6: 149   of 451   ] Skipping existing gitlab-ce-11.8.2-ce.0.el6.x86_64.rpm
[el6: 150   of 451   ] Skipping existing gitlab-ce-11.8.3-ce.0.el6.x86_64.rpm
[el6: 151   of 451   ] Skipping existing gitlab-ce-11.9.0-ce.0.el6.x86_64.rpm
[el6: 152   of 451   ] Downloading gitlab-ce-11.9.1-ce.0.el6.x86_64.rpm
gitlab-ce-11.9.1-ce.0.e (4%)  4% [-             ]  20 kB/s |  22 MB  422:00 ETA
```
