### ISSUE TITLE
请求镜像Trisquel

### ISSUE THREAD

**Issue by iotac01** [tuna/issues#535]
#### 项目名称与简介(Project Intro.)
Trisquel是一个完全自由的(FSF认可的)GNU/Linux发行版.
#### 上游地址与镜像方法(How to Mirror)
Packages: rsync://rsync.trisquel.info/trisquel.packages
ISO images: rsync://rsync.trisquel.info/trisquel.iso
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
合计约550GB.

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1517
