### ISSUE TITLE
服务器速度不稳定

### ISSUE THREAD

**Issue by jiyilvcheng** [tuna/issues#536]
本人于3月29日中午，在清华站上下载一次linux镜像，具体发行版已忘记，速度在20-26MB/s之间。3天前发现下载速度变慢，下载arch和Kali镜像时的下载速度都在10M以内，除源码外的其他页面加载速度也明显降低。

**Comment by jiyilvcheng** [comment]
本人于3月29日中午，在清华站上下载一次linux镜像，具体发行版已忘记，速度在20-26MB/s之间。3天前发现下载速度变慢，下载arch和Kali镜像时的下载速度都在10M以内，除源码外的其他页面加载速度也明显降低。

**Comment by Harry-Chen** [comment]
您好，目前我们服务器和网络未见异常。可能是您所处的网络环境至镜像站的网络链路发生了变化。如果问题持续发生，您可以给出更详细的情况（如地理位置、IP等）与我们一同排查。
