### ISSUE TITLE
您好，请问debian jessie版的arm64镜像出现问题了吗？

### ISSUE THREAD

**Issue by maozhifeng** [tuna/issues#539]
您好，我无法获取到debian jessie版的arm64源镜像，这是怎么一回事呢？我查看了各个地方的源站里面都没有debian jessie版的arm64源镜像，还有我也无法获取到debian jessie版的软件，譬如gcc等，我想得到您的帮助，谢谢。

**Comment by shankerwangmiao** [comment]
详见 Debian 官方的下列通告：

https://lists.debian.org/debian-mirrors/2019/03/msg00007.html
