### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by autosquid** [tuna/issues#54]
如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写

If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.

提交时，请去掉上面两句，还有这一句。如果不是设立镜像请求，无需按此格式填写。

#### 项目名称与简介(Project Intro.)
Chocolatey: https://chocolatey.org/

Chocolatey NuGet is a Machine Package Manager, somewhat like apt-get, but built with Windows in mind.

#### 上游地址与镜像方法(How to Mirror)
Hosted on Github: https://github.com/chocolatey/choco
but I do not know how to mirror in details.
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
unknown

**Comment by bigeagle** [comment]
这个存的全是打包脚本，包本身是分散在各地的。
https://chocolatey.org/packages/Firefox

另外，请仔细阅读你的 issue 的前三行。

**Comment by autosquid** [comment]
you are right. My wrong.

**Comment by x1angli** [comment]
I would like to propose reopening this issue. You know, Chocolatey is a package manager for Windows, and unlike other systems, there is no de-facto "official package managing tool" for Windows. Hence, it would be nice for us to provide packages. 

If we consider that the packages included in the Chocolatey are the most frequently used ones such as JRE / Adobe Flash / Google Chrome (see https://chocolatey.org/packages). This is great especially for Google Chrome

I am aware that the TUNA might include only those "open source" packages / software on the official TUNA mirror server. There is a walk-around that might benefit everyone: include those packaging methods in the TUNA code hosted on Github, but not directly cache the binaries on TUNA mirror. 
一个建议：关于非完全开源的软件，TUNA的代码中只集成打包方法，并且可以配置哪些软件可以被打包，但是镜像服务器上不提供下载。

Note: There is an official provider for Windows 10/Windows Server 2016's built-in package manager manager (PackageManagement/OneGet) in the works - no ETA on release date yet.

**Comment by huiyiqun** [comment]
我们不提供 chocolatey 的镜像并不仅仅是因为我们只提供“开源”镜像。

我能想到的有以下几个理由：
1. Chocolatey 官方并没有提供可行的镜像方案，自己写脚本同步需要对这个系统本身有较为深入的理解，我们当前并不具备这样的条件，即使我们提供了镜像的脚本，也不能保证其质量。寄希望于 TUNA 不如寻求 Chocolatey 官方或者相关爱好者的帮助。
2. Chocolatey 仓库中主要是一些脚本集合，镜像 Chocolatey 仓库并不会提高使用 Chocolatey 的体验。这一点 @bigeagle 已经提过了。

**Comment by FranklinYu** [comment]
@huiyiqun 关于第二条，Chocolatey中有很多嵌入式包，将安装文件嵌入在package中了。镜像可以有效提升这一类包的使用体验。Chocolatey也鼓励（合法）嵌入。

对于未嵌入的包，至少镜像负担不会很大，而且用户使用体验也未降低。

**Comment by xuxinhang** [comment]
非常希望可以推出 Chocolatey 镜像，Chocolatey.org 在国内访问确实不太稳定
