### ISSUE TITLE
Ubuntu Arm64 source Problem

### ISSUE THREAD

**Issue by TingliangZhang** [tuna/issues#540]
changed Jetson Pack Source of Nvidia Jetson NANO to Tuna source.list
Those Error occurs.
The NANO KIT is arm64 but.....

E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:408:8100::1 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-updates/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:408:8100::1 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-backports/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:408:8100::1 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-security/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:408:8100::1 443]

**Comment by jiegec** [comment]
ubuntu-ports, plz
