### ISSUE TITLE
elasticstack7.x

### ISSUE THREAD

**Issue by ld0574** [tuna/issues#542]
请更新7.x的elasticstack

#### 上游地址与镜像方法(How to Mirror)
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum

#### 其他信息(Other)
- 相关文档(Doc): https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html

**Comment by z4yx** [comment]
正在同步中，网络比较慢，需要等一段时间。
