### ISSUE TITLE
[鏡像請求] Racket

### ISSUE THREAD

**Issue by zaoqi** [tuna/issues#543]
#### 项目名称与简介(Project Intro.)

![logo2](https://avatars0.githubusercontent.com/u/232371?s=20000&v=4)
Racket 
Racket is a general-purpose programming language as well as the world’s first ecosystem for language-oriented programming. 

#### 上游地址与镜像方法(How to Mirror)

https://download.racket-lang.org/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

![logo](https://racket-lang.org/img/racket-logo.svg)

**Comment by z4yx** [comment]
rsync://mirror.csclub.uwaterloo.ca/racket/

**Comment by Harry-Chen** [comment]
同步完成后，我们会向官方申请纳入列表中

**Comment by z4yx** [comment]
> rsync://mirror.csclub.uwaterloo.ca/racket/

已从上述地址同步完成 https://neomirrors.tuna.tsinghua.edu.cn/racket-installers/

**Comment by z4yx** [comment]
> 同步完成后，我们会向官方申请纳入列表中

建议同时申请官方的rsync地址，以便紧跟最新版本。
