### ISSUE TITLE
pip install flask_monitoringdashboard安装时报编码错误

### ISSUE THREAD

**Issue by curiositer** [tuna/issues#544]
pip安装flask-monitoringdashboard时，报编码错误，试着下载源码后加入了read().decode("utf-8")，但是仍然无法解决，原版的镜像下载来安装也是错误，请指教
File "C:\...\flask-monitoringdashboard\setup.py", line 11, in get_description
        info = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1571: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\...\flask-monitoringdashboard\

**Comment by z4yx** [comment]
如果原站下载也是错误，说明是软件包自身的bug，请向软件作者反馈。
