### ISSUE TITLE
some python packages in pip repo are broken.

### ISSUE THREAD

**Issue by yech1990** [tuna/issues#545]
eg, 

https://pypi.tuna.tsinghua.edu.cn/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl#sha256=09a9dcb7c46ed496a9850b76e4e825d6049ecd38b611f1224857a79bd985a8cf

**Comment by z4yx** [comment]
fixed manually

**Comment by z4yx** [comment]
fixed manually
