### ISSUE TITLE
[Mirror Request] Spack

### ISSUE THREAD

**Issue by saffahyjp** [tuna/issues#546]
#### 项目名称与简介(Project Intro.)

https://spack.io/

Spack is a package manager for supercomputers, Linux, and macOS. It makes installing scientific software easy. With Spack, you can build a package with multiple versions, configurations, platforms, and compilers, and all of these builds can coexist on the same machine.

#### 上游地址与镜像方法(How to Mirror)

https://spack.readthedocs.io/en/latest/mirrors.html

里面写得比较完整，会把文件放到某个目录下，然后需要提供一个http服务

#### 其他信息(Other)
- 镜像大小(Mirror Size): 所有包的所有版本肯定是太大了，可以考虑镜像一些常用的包，或者做on demand的缓存

**Comment by saffahyjp** [comment]
可能的问题是无法简单地识别哪些package是开源项目

**Comment by Harry-Chen** [comment]
License 问题难以解决，因此难以镜像。事实上可以通过配置一个 Spack 镜像指向 TUNA 的 gnu 目录来获得一部分的加速。
