### ISSUE TITLE
kali的vm与virtualbox镜像

### ISSUE THREAD

**Issue by miffyrcee** [tuna/issues#547]
#### 项目名称与简介(Project Intro.)
kali的vm与virtualbox镜像
#### 上游地址与镜像方法(How to Mirror)
https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
2.5/4.9G
ps:谢谢

**Comment by jiegec** [comment]
似乎没有 rsync 同步地址？

**Comment by miffyrcee** [comment]
不好意思，确实如此，因为bt的下载实在难以忍受，所以我才希望能够从清华源里下载的到，但可能添麻烦了。
