### ISSUE TITLE
[Mirror Request] googlefonts git repo

### ISSUE THREAD

**Issue by stone-zeng** [tuna/issues#549]
#### 项目名称与简介(Project Intro.)

Google Fonts: Fonts source files and font utilities

#### 上游地址与镜像方法(How to Mirror)

<https://github.com/googlefonts> 中有很多仓库，大部分可以直接 clone，但有几个 repo 比较大，直接下载很艰难。

| 名称 | 大小 | Git repo URL |
|:-:|:-:|:-:|
| [noto-fonts](https://github.com/googlefonts/noto-fonts)             |   2.27 GB | <https://github.com/googlefonts/noto-fonts.git>       |
| [noto-source](https://github.com/googlefonts/noto-source)           | 313.89 MB | <https://github.com/googlefonts/noto-source.git>      |
| [noto-cjk](https://github.com/googlefonts/noto-cjk)                 |   2.11 GB | <https://github.com/googlefonts/noto-cjk.git>         |
| [noto-emoji](https://github.com/googlefonts/noto-emoji)             | 132.38 MB | <https://github.com/googlefonts/noto-emoji.git>       |
| [noto-fonts-alpha](https://github.com/googlefonts/noto-fonts-alpha) |   1.38 GB | <https://github.com/googlefonts/noto-fonts-alpha.git> |

#### 其他信息(Other)
- 镜像大小(Mirror Size): 见上表。

**Comment by stone-zeng** [comment]
github 打包的 zip 下载一样也很慢，那边 <https://www.google.com/get/noto/> 网站上面下载的主要是稳定版，而且似乎有段时间没有更新了。

**Comment by z4yx** [comment]
三种字体已同步，可以在镜像站"获取下载链接”处下载。
