### ISSUE TITLE
Service issues

### ISSUE THREAD

**Issue by Roller44** [tuna/issues#55]
Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/trusty-proposed/main/i18n/Translation-en  Hash Sum mismatch

Ubuntu Kylin 14.04 LTS

**Comment by bigeagle** [comment]
Try using https://mirrors.tuna.tsinghua.edu.cn/ ?

**Comment by Roller44** [comment]
Course another error: 
"W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch"

**Comment by bigeagle** [comment]
This is because your ISP is hijacking your traffic.
Regarding the second error, you should use https://ppa....../
Use HTTPS as much as you can.

**Comment by Roller44** [comment]
Thanks.


 

-------- Original message --------
Sender: bigeagle <notifications@github.com>
Time: Thu 5/12 20:44
To: tuna/issues <issues@noreply.github.com>
Cc: Yao ShuMin <thisisyaoshumin@gmail.com>,Author <author@noreply.github.com>
 Subject: Re: [tuna/issues] Service issues (#55)
