### ISSUE TITLE
101.6.6.6 是否禁止了校外访问？

### ISSUE THREAD

**Issue by Soulike** [tuna/issues#550]
最近发现 101.6.6.6 的解析结果全部都是

** server can't find www.baidu.com: REFUSED

是否 DNS 服务器已经禁止了校外访问？

**Comment by xavieryao** [comment]
是的，请使用其他 DNS 服务。

**Comment by shankerwangmiao** [comment]
如果是高校用户，可以发学校名和地址段到 support@tuna.tsinghua.edu.cn

**Comment by qianbinbin** [comment]
最近发现又不行了，返回 `status: REFUSED`，DoH 也变成了 403
科大的好像也没了
不知道还有什么无污染、速度快、优先返回境内服务器、注重隐私的 DNS？
