### ISSUE TITLE
请添加对CDH(Cloudera Enterprise)的支持

### ISSUE THREAD

**Issue by anjia0532** [tuna/issues#551]
#### 项目名称与简介(Project Intro.)
Cloudera Enterprise (CDH) 是大数据套件hadoop的一个发行版，目前国内使用量很高。这是google趋势的连接 https://trends.google.com/trends/explore?q=Cloudera,CDH,hadoop

#### 上游地址与镜像方法(How to Mirror)

这是cdh6.2的获取方式

https://www.cloudera.com/documentation/enterprise/latest/topics/cm_ig_create_local_package_repo.html#internal_package_repo

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by anjia0532** [comment]
ref #86

**Comment by z4yx** [comment]
see #682
