### ISSUE TITLE
QubesOS Mirror Request

### ISSUE THREAD

**Issue by LEXUGE** [tuna/issues#552]
#### 项目名称与简介(Project Intro.)
Qubes OS
Qubes OS is a security-oriented operating system (OS). The OS is the software that runs all the other programs on a computer. Some examples of popular OSes are Microsoft Windows, Mac OS X, Android, and iOS. Qubes is free and open-source software (FOSS). This means that everyone is free to use, copy, and change the software in any way. It also means that the source code is openly available so others can contribute to and audit it.

#### 上游地址与镜像方法(How to Mirror)
https://www.qubes-os.org/downloads/mirrors/#instructions-for-mirror-operators

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
Unknown

**Comment by LEXUGE** [comment]
Any information here?

**Comment by jiegec** [comment]
正在同步 https://mirros.tuna.tsinghua.edu.cn/qubesos

**Comment by LEXUGE** [comment]
> 正在同步 https://mirrors.tuna.tsinghua.edu.cn/qubesos 。等我们同步完以后，会联系上游加入到 Mirror 列表中，欢迎贡献 QubesOS 内配置 Mirror 的帮助。

The official `qubes-dom0-update` uses the mechanism of fedora `dnf`.
But it seems that `qubes-dom0-update` didn't follow the dnf `fastestmirror` preference.

**Comment by LEXUGE** [comment]
> 正在同步 https://mirrors.tuna.tsinghua.edu.cn/qubesos 。等我们同步完以后，会联系上游加入到 Mirror 列表中，欢迎贡献 QubesOS 内配置 Mirror 的帮助。

The help page of Qubes OS can simply follow the [fedora help page](https://mirrors.tuna.tsinghua.edu.cn/help/fedora/)

**Comment by jiegec** [comment]
（等待Pull Request的眼神

**Comment by LEXUGE** [comment]
> （等待Pull Request的眼神

准备写PR了...

**Comment by LEXUGE** [comment]
@jiegec https://github.com/tuna/mirror-web/pull/124

**Comment by LEXUGE** [comment]
`fastestmirror` 会在R4.1的时候正常工作，目前只有hardcode的办法了

**Comment by jiegec** [comment]
okay, 等到同步完了以后再 merge 吧

**Comment by LEXUGE** [comment]
上游联系有什么进展吗？

**Comment by Harry-Chen** [comment]
已经同步完成并且通知上游。

**Comment by scateu** [comment]
刚看完斯诺登的书，里面提到Qubes OS... 然后就发现Mirror List里有TUNA 
挖坟赞
