### ISSUE TITLE
lxc-images images部分文件404但index中存在，且没有处于同步状态

### ISSUE THREAD

**Issue by 12101111** [tuna/issues#553]
Creating arch
Error: Failed container creation: Unable to fetch https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/archlinux/current/amd64/default/20190427_04:18/lxd.tar.xz: 404 Not Found

但[images.json](https://mirrors.tuna.tsinghua.edu.cn/lxc-images/streams/v1/images.json)中又可以找到其记录：

{"ftype": "root.tar.xz", "sha256": "11100307940472a74ae732879aa1d182029632fa8aa69de105ab876199fe2717", "size": 126834416, "path": "images/archlinux/current/armhf/default/20190427_04:18/rootfs.tar.xz"},

related:#382
不同的是，此时镜像已经完成同步，不是failed，不是syncing

**Comment by z4yx** [comment]
转移到 #558 讨论
