### ISSUE TITLE
希望为maxima添加镜像

### ISSUE THREAD

**Issue by EricLucife** [tuna/issues#555]
项目名称:Maxima
项目简介:Maxima 是用于操纵符号和数值表达式的系统， 包括微分、积分、泰勒级数、拉普拉斯变换、常微分方程、 线性方程组、多项式、集合、列表、向量、矩阵和张量。 Maxima 通过使用精确分数、任意精度整数和可变精度浮点数 来产生高精度数值结果。Maxima 可以在二维和三维空间中 绘制函数和数据。
Maxima 是 Macsyma 的后裔，后者是 20 世纪 60 年代末 由麻省理工学院开发的享有盛名的计算机代数系统。由于其开源特性，Maxima 是唯一仍然可以公开获得 且具有活跃用户社区的系统。Macsyma 在它的时代是突破性的，以至于后来的许多系统， 如 Maple 和 Mathematica，都受到了它的启发。
上游源地址，或镜像方法:https://sourceforge.net/projects/maxima/
尽量详细的镜像信息（例如镜像大小）

**Comment by z4yx** [comment]
我们没法从 sourceforge 同步，需要有支持增量同步协议的上游。

**Comment by phy25** [comment]
可以尝试这个 rsync://rsync.mirrorservice.org/downloads.sourceforge.net/m/ma/maxima/ 不过不一定是官方源。
