### ISSUE TITLE
OpenBSD mirror 似乎从4月22日后就不再更新了

### ISSUE THREAD

**Issue by darkgeek** [tuna/issues#557]
大佬们好，我是一名OpenBSD的用户，最近这几天发现OpenBSD的mirror同步，自从4月22日后就 处于停滞状态，页面上一直显示syncing，不知是不是上游的问题，还是咱们这卡住了。麻烦帮忙看下哈，谢谢。

**Comment by shankerwangmiao** [comment]
已经处理完毕。
