### ISSUE TITLE
希望添加Linux Mint系统镜像

### ISSUE THREAD

**Issue by teachmain** [tuna/issues#559]
#### 项目名称与简介(Project Intro.)
Linux Mint 由Linux Mint Team团队于2006年开始发行，是一份基于Debian和Ubuntu的Linux发行版。其目标是提供一种更完整的即刻可用体验，这包括提供浏览器插件、多媒体编解码器、对DVD播放的支持、Java和其他组件，它也增加了一套定制桌面及各种菜单，一些独特的配置工具，以及一份基于web的软件包安装界面。Linux Mint是对用户友好而功能强大的操作系统。它诞生的目的是为家庭用户和企业提供一个免费的，易用的，舒适而优雅的桌面操作系统。
其境内官方镜像源: https://mirrors.shu.edu.cn/linuxmint-cd/   (上海大学开源镜像站)目前已完全无法访问
#### 上游地址与镜像方法(How to Mirror)

Archive | Address | Required frequency | Size
-- | -- | -- | --
ISO images | rsync://pub.linuxmint.com::pub | Once a day | 200GB
Linux Mint repositories | rsync://rsync-packages.linuxmint.com::packages | Twice a day | 25GB

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by jiegec** [comment]
不是已经mirror了吗

**Comment by teachmain** [comment]
我的锅，眼瞎了，抱歉xd
