### ISSUE TITLE
gitlab-ce ubuntu镜像几天没同步了

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#56]
发现gitlab-ce的ubuntu镜像落后于/yum/目录下的镜像。
今天gitlab-ce已经发布8.7.5版本，修复了几个安全问题。但是tuna的镜像还停留在8.7.3。

**Comment by xhfeng** [comment]
是呀。。都在等 呢

**Comment by bigeagle** [comment]
这个问题应该已经解决，试试看？

**Comment by abcfy2** [comment]
Fixed.

**Comment by zhujunsan** [comment]
ref #63
