### ISSUE TITLE
New Mirror Suggestion

### ISSUE THREAD

**Issue by JamesZBL** [tuna/issues#560]
#### 项目名称与简介(Project Intro.)
Gradle Wrapper
The most popular build tool now for Java software develpment.

#### 上游地址与镜像方法(How to Mirror)
https://services.gradle.org/distributions

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
less than 100MB

**Comment by Harry-Chen** [comment]
镜像体积远大于 100 MB，几乎每个文件都有 100 MB

**Comment by Harry-Chen** [comment]
我认为镜像意义并不大，用户如果要使用，要手动更新每个项目的 gradle wrapper 的配置，并且 Gradle 升级以后也需要更改。
