### ISSUE TITLE
[Mirror Request] KDE neon

### ISSUE THREAD

**Issue by KspLite** [tuna/issues#562]
#### 项目名称与简介(Project Intro.)
KDE neon是KDE社区维护的一个基于Ubuntu LTS的Linux发行版
需要镜像neon,neon-cd
#### 上游地址与镜像方法(How to Mirror)
neon软件源的HTTP上游为archive.neon.kde.org，可以用apt-mirror镜像
neon-cd位于rsync://rsync.kde.org/applicationdata中一个/neon/images目录
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
    neon：未知，应该也就100G吧（Neon只管KDE应用，其余部分直接用了ubuntu源）
    neon-cd：未知，应该只有几十G

**Comment by KspLite** [comment]
其实相比较而言，kde、kde-application的镜像不是很重要（通常可以直接用发行版自带的）
但是kde neon真的需要镜像，虽然不能rsync，但这个仓库应该不会太大，HTTP线路镜像应该不会有问题
kde官方也表示只要不每次都全量同步，可以不rsync
请考虑一下，谢谢

**Comment by easezhi** [comment]
官方镜像的cdn节点太慢了。现在国内一个neon的镜像都没有。希望支持一下

**Comment by z4yx** [comment]
我建议直接镜像 KDE 了，共200G：https://kde.org/mirrors/ftp_howto.php

**Comment by KspLite** [comment]
@z4yx kde neon的deb软件源不在rsync://rsync.kde.org/中，只镜像kde不能解决此issue

**Comment by z4yx** [comment]
deb源是不是只需要 http://archive.neon.kde.org/user/
testing和dev估计用户很少

**Comment by z4yx** [comment]
https://mirrors.bfsu.edu.cn/kde-neon/
https://mirrors.bfsu.edu.cn/kde-application/neon/

**Comment by SnDream** [comment]
E: 无法下载 https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/dep11/icons-48x48.tar  404  Not Found [IP: 39.155.141.16 443]
这个镜像上没有dep11的部分，不知道是否能补齐？

**Comment by Dieken** [comment]
https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/ 相比上游 http://archive.neon.kde.org/user/dists/focal/main/ 缺了好多啊！

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/ 相比上游 http://archive.neon.kde.org/user/dists/focal/main/ 缺了好多啊！

我们只包含了 amd64 的部分，参考[该同步脚本](https://github.com/tuna/tunasync-scripts/blob/master/kde-neon.sh)。

> E: 无法下载 https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/dep11/icons-48x48.tar 404 Not Found [IP: 39.155.141.16 443]
> 这个镜像上没有dep11的部分，不知道是否能补齐？

由于目前镜像站空间限制，暂不考虑新增其他部分。

**Comment by SnDream** [comment]
> > https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/ 相比上游 http://archive.neon.kde.org/user/dists/focal/main/ 缺了好多啊！
> 
> 我们只包含了 amd64 的部分，参考[该同步脚本](https://github.com/tuna/tunasync-scripts/blob/master/kde-neon.sh)。
> 
> > E: 无法下载 https://mirrors.bfsu.edu.cn/kde-neon/user/dists/focal/main/dep11/icons-48x48.tar 404 Not Found [IP: 39.155.141.16 443]
> > 这个镜像上没有dep11的部分，不知道是否能补齐？
> 
> 由于目前镜像站空间限制，暂不考虑新增其他部分。

DEP11整个目录只有大约4.8G，还是希望能考虑下。

**Comment by ZenithalHourlyRate** [comment]
> DEP11整个目录只有大约4.8G，还是希望能考虑下。

注意到缺少该目录确实影响正常使用，我们正在处理该问题

**Comment by ZenithalHourlyRate** [comment]
已经同步了该目录，需要用户测试是否可用。如果测试可用，该 issue 将关闭。

**Comment by ZenithalHourlyRate** [comment]
![Screenshot2021-06-10-16:30:58](https://user-images.githubusercontent.com/19512674/121492919-e4f96c80-ca09-11eb-9d0e-f7d0bdc213ff.png)
经测试可用。

**Comment by SnDream** [comment]
```
deb [arch=amd64] https://mirrors.bfsu.edu.cn/kde-neon/user/ focal main
# deb-src https://mirrors.bfsu.edu.cn/kde-neon/user/ focal main
# deb http://archive.neon.kde.org/user/ focal main
deb-src http://archive.neon.kde.org/user/ focal main
```

目前如上配置更新正常，应该可以使用，谢谢！

**Comment by ZenithalHourlyRate** [comment]
> ```
> deb [arch=amd64] https://mirrors.bfsu.edu.cn/kde-neon/user/ focal main
> # deb-src https://mirrors.bfsu.edu.cn/kde-neon/user/ focal main
> # deb http://archive.neon.kde.org/user/ focal main
> deb-src http://archive.neon.kde.org/user/ focal main
> ```
> 
> 目前如上配置更新正常，应该可以使用，谢谢！

如果可能，可以往 [mirror-web](https://github.com/tuna/mirror-web/) 中提交相关帮助文档，包含如何修改 `/etc/apt/sources.list` 以及 `/etc/apt/sources.list.d/user.conf` 的内容。可以参考 ubuntu 的[样例](https://github.com/tuna/mirror-web/blob/master/help/_posts/1970-01-01-ubuntu.md)。
