### ISSUE TITLE
StarUML

### ISSUE THREAD

**Issue by JamesZBL** [tuna/issues#563]
#### 项目名称与简介(Project Intro.)
StarUML
#### 上游地址与镜像方法(How to Mirror)
http://staruml-7a0.kxcdn.com/releases/StarUML-3.1.0-x86_64.AppImage
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
<100MB

**Comment by jiegec** [comment]
不允许镜像，参考 http://staruml.io/eula
