### ISSUE TITLE
镜像请求 HDP

### ISSUE THREAD

**Issue by Jiezhi** [tuna/issues#566]
#### 项目名称与简介(Project Intro.)
HDP 3.1.0 Repositories

#### 上游地址与镜像方法(How to Mirror)
https://docs.hortonworks.com/HDPDocuments/Ambari-2.7.3.0/bk_ambari-installation/content/hdp_31_repositories.html

#### 其他信息(Other)
- 镜像大小(Mirror Size): 10G 左右
- 建议能按照[官方文档](https://docs.hortonworks.com/HDPDocuments/Ambari-2.7.3.0/bk_ambari-installation/content/ch_using-local-repos.html)搭建个服务，这样在国内下载 hdp 相关资源时能速度快点

感谢

**Comment by MikePenW** [comment]
镜像搭建好了吗？现在官网都无法下载了...

**Comment by skyzh** [comment]
看起来在 apache 里面有。https://mirrors.tuna.tsinghua.edu.cn/apache/ambari/

**Comment by skyzh** [comment]
是否方便介绍一下 ambari 和 HDP 的关系？具体需要镜像哪些内容？

**Comment by MikePenW** [comment]
> 看起来在 apache 里面有。https://mirrors.tuna.tsinghua.edu.cn/apache/ambari/

阿里云上的这个是源码，在HDP官网下载的是编译好的文件包

**Comment by MikePenW** [comment]
> 是否方便介绍一下 ambari 和 HDP 的关系？具体需要镜像哪些内容？

Ambari：WEB应用程序，后台为Ambari Server，负责与HDP部署的集群工作节点进行通讯，集群控制节点包括Hdfs，Spark，Zk，Hive，Hbase等等。
HDP：HDP包中包含了很多常用的工具，比如Hadoop，Hive，Hbase，Spark等
HDP-Util：包含了公共包，比如ZK等一些公共组件。

**Comment by skyzh** [comment]
感谢。但看起来官方的 repo 已经禁止公开访问了。 https://docs.cloudera.com/HDPDocuments/Ambari-2.7.3.0/bk_ambari-installation/content/ambari_repositories.html

> As of January 31, 2021, all downloads of HDP and Ambari require a username and password and use a modified URL. You must use the modified URL, including the username and password when downloading the repository content.

**Comment by Jiezhi** [comment]
如果有人想下载 CDH 的话，我封装成 Docker 了，可以参考下： 

https://github.com/Jiezhi/docker-cdh-repo

**Comment by Jiezhi** [comment]
HDP 和 CDH 都不对外提供下载了，此问题可以关闭了
