### ISSUE TITLE
docker registry mirror via pull through cache

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#57]
#### 项目名称与简介(Project Intro.)

Docker Hub allows you to link to code repositories, build your images and test them, stores manually pushed images, and links to Docker Cloud so you can deploy images to your hosts.
#### 上游地址与镜像方法(How to Mirror)

最新版本的docker registry貌似还不支持直接镜像，所以退而求其次，用缓存的方式。[见这](https://docs.docker.com/engine/admin/registry_mirror/)

[DaoCloud](https://get.daocloud.io/)也提供了“镜像”和“加速”服务，不清楚他们怎么实现的（访问要注册账号，嫌麻烦）。如果遇到问题可以联系他们。

上游：Docker Hub
如何镜像：[https://docs.docker.com/registry/mirror/]()

具体来说，就是起这样一个[docker](https://hub.docker.com/_/registry/)，然后用户请求的时候由这个docker代替用户来请求，然后把结果缓存下来。

如何配置在：[https://docs.docker.com/registry/configuration/]()，主要看[Proxy](https://docs.docker.com/registry/configuration/#proxy)一节或者[这里](https://docs.docker.com/registry/mirror/#configuring-the-cache)。

配置为pull through cache之后就不允许用户上传image了。
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
  不清楚，不过有gc，容量大小应该是视访问量吧。

**Comment by abcfy2** [comment]
ustc已经有docker hub的mirror了，可以问问他们看: https://servers.ustclug.org/2015/05/new-docker-hub-registry-mirror/

**Comment by meteorlad** [comment]
这个需要proxy来解决了,不过很期待呀
