### ISSUE TITLE
Termux里的gpg key应该在三年前被删掉

### ISSUE THREAD

**Issue by scateu** [tuna/issues#571]
某不愿意写issue的同学说:

> 这个文件似乎已经被 Termux 官方删了，有清华镜像站管理员看到的话可以看看能不能跟着删掉
https://mirrors.tuna.tsinghua.edu.cn/termux/dists/stable/Release.gpg
>> 同步的时候应该也会跟着删除吧
>  （但好像已经三年了
> 总之科大镜像站没有
> emmm 服务并没有故障，让一个空文件呆在那儿也没什么，issue 就算了（

**Comment by z4yx** [comment]
搞定
