### ISSUE TITLE
镜像请求：Chocolatey

### ISSUE THREAD

**Issue by peter17ji** [tuna/issues#574]
#### 项目名称与简介(Project Intro.)
https://chocolatey.org/ 是一个Win10下的软件包管理器，可以实现一键安装各种开发环境。oh-my-tuna如果要支持Macrohard Windoge的话这个工具我认为必不可少。

#### 上游地址与镜像方法(How to Mirror)
https://chocolatey.org/docs/how-to-host-feed 有介绍怎么建立自己的源，因为其技术本质是NuGet，所以支持NuGet的建源方法都行
https://chocolatey.org/packages 官方源的web页面

#### 其他信息(Other)
- 镜像大小(Mirror Size): chocolatey自己的免费源不提供实际软件的安装包下载，只提供包含官网下载地址的自动安装脚本。我个人希望TUNA源同时提供安装脚本和安装包，甚至可以提供类似官方源的。

**Comment by x1angli** [comment]
Duplicate of #54

见
https://github.com/tuna/issues/issues/54#issuecomment-435663761

不知道现在有没有update?

**Comment by FranklinYu** [comment]
@x1angli 关于第二条，Chocolatey中有很多嵌入式包，将安装文件嵌入在package中了。镜像可以有效提升这一类包的使用体验。Chocolatey也鼓励（合法）嵌入的行为。

对于未嵌入的包，至少镜像负担不会很大，而且用户使用体验也未降低。

当然了，如果「开源」是硬性要求，那Chocolatey就不可能。

**Comment by shankerwangmiao** [comment]
感谢 @x1angli 发现 dup，本 issue 关闭。如果希望继续讨论，可以前往 #54 。如果有人讨论的话，我会 reopen。
