### ISSUE TITLE
请求webtatic镜像

### ISSUE THREAD

**Issue by soarteam** [tuna/issues#577]
#### 项目名称与简介(Project Intro.)
Webtatic
此镜像是一个 CentOS/RHEL 软件存储库，其中包含较新的与 WEB 相关的软件包。
#### 上游地址与镜像方法(How to Mirror)
http://us-east.repo.webtatic.com/
可直接下载
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by z4yx** [comment]
看起来主要是php的各版本，包文件很小，我觉得镜像意义不大
