### ISSUE TITLE
请求Varnish镜像

### ISSUE THREAD

**Issue by soarteam** [tuna/issues#578]
#### 项目名称与简介(Project Intro.)
Varnish
Varnish可以有效降低web服务器的负载，提升访问速度。Varnish是一个cache型的HTTP反向代理。
#### 上游地址与镜像方法(How to Mirror)
https://packagecloud.io/varnishcache/varnish62/mirror
直接镜像
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
小

**Comment by Harry-Chen** [comment]
Varnish 已经进入了 Debian、Ubuntu 等系统的官方源，官方使用的 PackageCloud 也是一个带有 CDN 的软件包分发站点，因此目前看来镜像意义不大
