### ISSUE TITLE
Raspbian 镜像的使用说明是否有问题?

### ISSUE THREAD

**Issue by z14git** [tuna/issues#579]
关于 '/etc/apt/sources.list.d/raspi.list' 文件的修改，其它源最后一般都是 'stretch main ui' ，但清华的使用说明里只有 'stretch main'
目前在树莓派上按照使用说明修改 raspi.list ，安装 'libgtk2.0-dev libgtk-3-dev' 时会出错。在 raspi.list 文件结尾加上 'ui' 后就可以正常安装了。

**Comment by scateu** [comment]
多谢指正，已经更新～

-- 
Wang Kang

**Comment by scateu** [comment]
https://github.com/tuna/mirror-web/commit/5cb90db430527c58b1b3b28c5a2b2c9db66ffd05
