### ISSUE TITLE
请求gtk镜像

### ISSUE THREAD

**Issue by zhouwg** [tuna/issues#580]
#### 项目名称与简介(Project Intro.)
GTK, or the GIMP Toolkit, is a multi-platform toolkit for creating graphical user interfaces. Offering a complete set of widgets, GTK is suitable for projects ranging from small one-off tools to complete application suites.

GTK was used in Meego OS, Sailfish OS......

#### 上游地址与镜像方法(How to Mirror)
https://www.gtk.org/download/index.php
http://ftp.gnome.org/pub/gnome/sources/gtk+/

I don't know how to mirror gtk.org currently.

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
unknown

**Comment by ZeroAurora** [comment]
建议直接对整个 GNOME 进行镜像

**Comment by z4yx** [comment]
已经包含在大部分发行版中的软件原则上不再单独维护镜像
