### ISSUE TITLE
Jenkins 的update-center.json地址仍然指向海外服务器

### ISSUE THREAD

**Issue by chenwei0930** [tuna/issues#581]
填写
[插件源](https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json)
后，默认得到的插件清单内的下载地址仍然指向
[http://updates.jenkins-ci.org/download/plugins](http://updates.jenkins-ci.org/download/plugins)
，速度仍然很慢，没有发挥清华镜像的作用，修改成
[https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/](https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/)
速度就很快了。
建议贵站更新一下插件清单文件。

**Comment by shankerwangmiao** [comment]
您好，清华镜像服务器上的数据按原样提供，我们不便作任何修改。如果需要贡献帮助文档，请向 https://github.com/tuna/mirrors-web 提交 PR。

**Comment by LinuxSuRen** [comment]
上面的地址是 https://github.com/tuna/mirror-web 而不是 https://github.com/tuna/mirrors-web

**Comment by LinuxSuRen** [comment]
只做同步不进行修改，很合理。不过，不修改确实无法使用。

**Comment by hulucc** [comment]
笑死了，这么死板的吗？直接关了算了，换其他mirror了，没任何用处

**Comment by LinuxSuRen** [comment]
可以使用由 Jenkins 中文社区提供的方案
https://updates.jenkins-zh.cn/update-center.json

**Comment by hulucc** [comment]
笑死了，这么死板的吗？直接关了算了，换其他mirror了，没任何用处
???

**Comment by z4yx** [comment]
如果修改会导致jenkins报检验错误，也不能使用。这个镜像当初设立的目的是方便jenkins官方把中国流量自动重定向过来，如果现在他们不重定向了，我也建议关闭镜像。

**Comment by snowman** [comment]
Why not use local `update-center.json`, like `127.0.0.1:8081/update-center.json`

Guys, do you work out like this? 😄 

Prepare of `update-center.json`:
1. Download https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json, remove JSONP wrapper.
2. Replace `http://updates.jenkins-ci.org/download` with `https://mirrors.tuna.tsinghua.edu.cn/jenkins`
3. Replace `"http://www.google.com/"` with `"https://www.baidu.com/"`
4. Open command line, change into directory where you `update-center.json` exists, run command `http-server .`
5. Open jenkins plugins settings page `http://127.0.0.1:8080/pluginManager/advanced`, change `URL` field on `Update Site` section into your local `update-center.json` path, like `127.0.0.1:8081/update-center.json`
6. It works 👍

**Comment by viweei** [comment]
@snowman  Thx~~I want kiss you ~ hope you are lady. 😘👍

**Comment by hulucc** [comment]
没 有 用 处，建 议 关 闭
