### ISSUE TITLE
申请设立 PHP Composer 的镜像

### ISSUE THREAD

**Issue by timjuly** [tuna/issues#582]
#### 项目名称与简介(Project Intro.)
PHP 包管理器 Composer

#### 上游地址与镜像方法(How to Mirror)

上游：https://packagist.org/
镜像方法：https://github.com/zencodex/composer-mirror

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
2T

**Comment by pdeantihuman** [comment]
附议

**Comment by leoleoasd** [comment]
复议

**Comment by swatchion** [comment]
复议

**Comment by kotori2** [comment]
附议

**Comment by z4yx** [comment]
packagist索引镜像做好了：

```
composer config -g repo.packagist composer 
 https://neomirrors.tuna.tsinghua.edu.cn/packagist/index/
```

全量镜像下载文件太多，且都是github tarball，暂时不考虑。
