### ISSUE TITLE
请求增加Yocto项目镜像

### ISSUE THREAD

**Issue by dawnscofield** [tuna/issues#584]
项目名称与简介(Project Intro.)
Yocto项目（YP）是一个开源协作项目，可帮助开发人员创建基于Linux的自定义系统，而无需考虑硬件架构。该项目提供了一套灵活的工具和空间，全球嵌入式开发人员可以共享技术，软件堆栈，配置和最佳实践，可用于为嵌入式和IOT设备创建定制的Linux映像，或者在需要定制的Linux操作系统的任何地方。

上游地址与镜像方法(How to Mirror)
https://www.yoctoproject.org/

其他信息(Other)

**Comment by zwx168238** [comment]
+1

**Comment by z4yx** [comment]
上游需要有支持同步的协议才有可能同步。比如rsync、s3等，只有下载链接是没办法同步的。

**Comment by phy25** [comment]
请提出镜像请求的朋友提出具体哪些资源需要镜像——哪些资源最常被用到。只提供项目首页，近似于让镜像站的维护人员新手上路，从 0 开始学习一个从未接触过的新的开发环境。

粗略看了下有资源的位置在下面两个域名：
- git.yoctoproject.org
- downloads.yoctoproject.org

**Comment by z4yx** [comment]
缺少同步手段
