### ISSUE TITLE
metasploit鏡像源

### ISSUE THREAD

**Issue by miffyrcee** [tuna/issues#585]
#### 项目名称与简介(Project Intro.)
metasploit 鏡像源
#### 上游地址与镜像方法(How to Mirror)
https://rpm.metasploit.com/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
202MB
拜求！！

**Comment by Harry-Chen** [comment]
Metasploit 不是自由软件，并没有提及允许镜像。
