### ISSUE TITLE
anaconda main库总是报404

### ISSUE THREAD

**Issue by klyjm** [tuna/issues#589]
win10, anaconda更新main包含的各种库的时候开始报404，其他库正常，大概晚上6点的时候开始出现这种情况

**Comment by phy25** [comment]
Duplicate of l #588.

**Comment by klyjm** [comment]
> Duplicate

什么时候能恢复正常呢？

**Comment by phy25** [comment]
@klyjm 清华的源应该是一天同步一次吧，不要着急
