### ISSUE TITLE
Maven 镜像

### ISSUE THREAD

**Issue by bigeagle** [tuna/issues#59]
#### 项目名称与简介(Project Intro.)

Maven 是 java 包仓库
#### 上游地址与镜像方法(How to Mirror)

https://maven.apache.org/guides/mini/guide-mirror-settings.html
#### 其他信息(Other)
- 镜像大小(Mirror Size): 反向代理

**Comment by bigeagle** [comment]
会和 #100 一同解决

**Comment by Harry-Chen** [comment]
https://maven.apache.org/guides/mini/guide-mirror-settings.html 提到：

> The size of the central repository is increasing steadily To save us bandwidth and you time, mirroring the entire central repository is not allowed. (Doing so will get you automatically banned) Instead, we suggest you setup a repository manager as a proxy.

**Comment by Harry-Chen** [comment]
Closed according to #100
