### ISSUE TITLE
请求镜像Scientific Linux

### ISSUE THREAD

**Issue by CreeperKong** [tuna/issues#590]
#### 项目名称与简介(Project Intro.)
Scientific Linux - 一个用于科研用途的RHEL系Linux发行版
#### 上游地址与镜像方法(How to Mirror)
http://ftp.scientificlinux.org/linux/scientific/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 70GB左右

**Comment by shankerwangmiao** [comment]
您好，由于发行方废弃了该发行版，因此不再考虑镜像。对于现存的 Cern CentOS 7，我们已经有位于 https://mirrors.tuna.tsinghua.edu.cn/cc 的镜像，欢迎使用。

**Comment by CreeperKong** [comment]
![_ AQVK%G6Z_F~E`E(P92TLK](https://user-images.githubusercontent.com/28486081/60413942-3b988200-9c09-11e9-88de-6de9b8790bba.png)
我发现最新的一个版本就在CentOS后面发布

**Comment by shankerwangmiao** [comment]
官方已经废弃了此发行版，因此不再考虑镜像，详见：

https://listserv.fnal.gov/scripts/wa.exe?A2=SCIENTIFIC-LINUX-ANNOUNCE;11d6001.1904
