### ISSUE TITLE
rustup 镜像 failed

### ISSUE THREAD

**Issue by iovw** [tuna/issues#591]
rustup 镜像从昨天就同步失败了。
不知道有人解决这个问题吗？

**Comment by jiegec** [comment]
https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/2019-06-30/ 目测今天的nightly是好的？

**Comment by whimeteor** [comment]
![图片](https://user-images.githubusercontent.com/24983369/60393879-aa64d500-9b4e-11e9-9fde-faad70442c9d.png)
这里我刚才看的时候还是 6/28 7:** failed

![图片](https://user-images.githubusercontent.com/24983369/60393910-07608b00-9b4f-11e9-8fa7-8cf511c91c5f.png)

**Comment by jiegec** [comment]
但是这个文件确实存在 https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/channel-rust-nightly.toml

**Comment by whimeteor** [comment]
emmmmm，刚打开这个文件看了下，日期还是6/27

**Comment by jiegec** [comment]
我的意思是，同步失败了但是不影响使用吧...

**Comment by whimeteor** [comment]
那我 update 失败了还不算影响吗？

**Comment by jiegec** [comment]
网络波动，已经自动恢复。

**Comment by jiegec** [comment]
还是有问题。

**Comment by iovw** [comment]
已经恢复
