### ISSUE TITLE
HTTP 请求随机性响应过慢的问题

### ISSUE THREAD

**Issue by kings-way** [tuna/issues#594]
【背景】
在使用tuna镜像源的过程中，发现 apt 在获取索引文件时一直 0% 

【排查过程】 
仔细排查了一下，发现同一个连接，发送第二个GET请求的时候，服务器响应时间过长（时间不定，范围从 <1s 到数十秒，下方截图里面是等待了30s ）
手动测试命令如下:  
`curl -v \`
`http://mirrors.tuna.tsinghua.edu.cn/debian/dists/stretch/InRelease \`
`http://mirrors.tuna.tsinghua.edu.cn/debian/dists/stretch/InRelease`

抓包截图：
![image](https://user-images.githubusercontent.com/9778377/60488898-ad3e0200-9cd5-11e9-9fc3-66e5682882a6.png)

两次 response 细节：
![image](https://user-images.githubusercontent.com/9778377/60488939-c21a9580-9cd5-11e9-9215-a847f9ec0250.png)

【其他测试】
1. 在不同网络环境、不同系统下使用 curl 测试，问题可复现；
2. 手动给 curl 加 keep-alive 头，问题可复现；
3. curl + https + HTTP/1.1，问题可复现； 
4. curl + https + HTTP/2，问题暂未复现；

【备注】
1. 不稳定复现，需要不断尝试curl请求，有时候稳定复现，有时候概率不到 1/10
2. 此问题已经在隔壁 USTC 群里反馈过，在这里 repost 一下方便跟踪

**Comment by happyaron** [comment]
@shankerwangmiao 只有404的请求是这样，因为互相代理的原因，需要给一个解决方案

**Comment by kings-way** [comment]
> @shankerwangmiao 只有404的请求是这样，因为互相代理的原因，需要给一个解决方案

之前我个人的测试结果是，非404请求一样存在该问题。
但是今天测试还未复现这个问题，目前无论是404还是非404的请求都无法复现这个问题。

**Comment by happyaron** [comment]
> 
> 
> > @shankerwangmiao 只有404的请求是这样，因为互相代理的原因，需要给一个解决方案
> 
> 之前我个人的测试结果是，非404请求一样存在该问题。
> 但是今天测试还未复现这个问题，目前无论是404还是非404的请求都无法复现这个问题。

非 404 请求的性能问题的原因是 I/O 性能导致的，404 的请求一般会更慢，因为涉及到目前 tuna 服务器之间的 fail over 原理。

**Comment by Harry-Chen** [comment]
这个问题在目前的镜像站配置与架构下，无法得到根本性的解决。
