### ISSUE TITLE
[ISSUE] Failed to fetch ubuntu bionic arm64 packages

### ISSUE THREAD

**Issue by mengqlTHU** [tuna/issues#595]
When run sudo apt-get update on Nvidia Jetson Nano

E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic/main/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-updates/main/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-security/main/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/bionic-backports/main/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by shankerwangmiao** [comment]
Please find arm64 packages in ububtu-ports

**Comment by mengqlTHU** [comment]
@shankerwangmiao Problem solved by replacing ubuntu with ubuntu-ports

**Comment by PiseyYou** [comment]
For arm64/armhf embedding device(Tx2) test, not for PC

```
cd /etc/apt
sudo gedit source.list
```


> 
> deb https://mirrors.aliyun.com/ubuntu-ports xenial main restricted universe multiverse
> deb https://mirrors.aliyun.com/ubuntu-ports xenial-security main restricted universe multiverse
> deb https://mirrors.aliyun.com/ubuntu-ports xenial-updates main restricted universe multiverse
> deb https://mirrors.aliyun.com/ubuntu-ports xenial-proposed main restricted universe multiverse
> deb https://mirrors.aliyun.com/ubuntu-ports xenial-backports main restricted universe multiverse
> 

replace abolve source, then 
`sudo apt-get update`

all the 404 no found package will be solved

**Comment by shankerwangmiao** [comment]
> 原因呢?

因为 arm64 架构的 Ubuntu 软件源不在 ubuntu/ 目录下，而在 ubuntu-ports/ 下。
