### ISSUE TITLE
Anaconda的main库依旧404

### ISSUE THREAD

**Issue by klyjm** [tuna/issues#597]
这个问题从28号开始就是这样子了，现在一个星期了依然会报404，同步也停在了上个星期，请问什么时候能恢复正常？

**Comment by z4yx** [comment]
同步一直在进行，因为这次新的*.conda格式涉及的新增文件很多，anaconda在中国访问又很慢，因此完全同步成功可能要好长时间。只能等等了。

**Comment by shankerwangmiao** [comment]
已经同步完毕。
