### ISSUE TITLE
无法拉取 AOSP 最新源码

### ISSUE THREAD

**Issue by Z5X67280** [tuna/issues#598]
## 简单描述
观察了一下 AOSP 镜像的同步状态，自从 7.3 开始就一直处于 Syncing 状态，截止到开 issue 前仍然在 Sync 。

然后我尝试了一下同步 Android P r44（7月安全更新）的 Tag，提示: 
```
fatal: Couldn't find remote ref refs/tags/android-9.0.0_r44
```
找不到 Tag ? 

我下意识地切换到 Android P r40 Tag（6月安全更新），**居然一切正常**，这就有点 emmmm 了

个人觉得这应该是上游问题，要不然不会这样 :no_mouth:

_Sent from my Redmi 5 Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by dkizjun** [comment]
同样的问题，包括

**Comment by Z5X67280** [comment]
@dkizjun r43 r44 r45 都同属于 7 月份安全更新的 Tag

_Sent from my Redmi 5 Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Z5X67280** [comment]
已经可以同步了，问题已解决
