### ISSUE TITLE
希望加入HADOOP和SPARK的相关  组件的源

### ISSUE THREAD

**Issue by ChisenZhang** [tuna/issues#60]
如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写

If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.

提交时，请去掉上面两句，还有这一句。如果不是设立镜像请求，无需按此格式填写。

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by bigeagle** [comment]
Hadoop  和 Spark 都是 Apache 项目，在 https://mirrors.tuna.tsinghua.edu.cn/apache/ 可以下载到。

另外，请认真阅读你提的 issue 的前三行。
