### ISSUE TITLE
申请创建 toolchains.bootlin.com 提供的交叉编译工具链镜像

### ISSUE THREAD

**Issue by lzufalcon** [tuna/issues#601]
#### 交叉编译工具链镜像

交叉编译工具链 是学习处理器架构、汇编语言、Linux 内核、嵌入式 Linux、Linux 设备驱动开发等不可或缺的工具，目前这些工具基本由处理器研发厂商以及相应组织维护，都有提前编译好的版本，但是都托管在国外服务器上，体积都不小（几百M），国内下载很慢。

#### 上游地址与镜像方法(How to Mirror)

长远目标是希望能镜像几大主流处理器架构官方或权威组织提供的交叉编译工具链资源，短期内，建议先做 https://toolchains.bootlin.com/ 。这个网站提供的工具链链基于 buildroot 自动构建，提供了多达 36 种处理器架构的交叉编译工具链，比较全面。

更多的见后面评论补充以及之前在 ustclug 上提交的申请。

#### 其他信息(Other)

每个工具链在几百M左右，36 个的话大概在 18G 以内。

**Comment by lzufalcon** [comment]
USTCLUG 那边的申请：https://github.com/ustclug/mirrorrequest/issues/237

**Comment by lzufalcon** [comment]
其他按架构分类的资源，欢迎大家增补。

**ARM**

  https://releases.linaro.org/components/toolchain/binaries/

  Linaro 是由 ARM 主导的技术联盟，该组织维护了大量 ARM 相关的开源软件，包括工具链，上述链接是提前编译好的 ARM 交叉编译器。

  ARM 公司自己也提供了一些工具链：

  https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
  https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

**Risc-V**

  https://github.com/gnu-mcu-eclipse/riscv-none-gcc/releases

  Risc-V 是当今最热门的处理器之一，相应的开发正热火朝天，所以，这些基础工具的同步非常关键。

  注意：Sifive.com 提供的工具链无法编译最新的内核，因为没提供 -shared 支持，无法编译 vdso。上述工具链是目前找到的更新最快好用的 Risc-V 工具链。

**MIPS**

  https://codescape.mips.com/components/toolchain/2018.09-03/downloads.html

  MIPS 是四大主流处理器架构之一，上述 Toolchains 由 MIPS 官方发布。

**Comment by lzufalcon** [comment]
Buildroot 提供的外部交叉工具链资源：[toolchain-external](https://gitee.com/tinylab/buildroot/tree/master/toolchain/toolchain-external)

toolchain-external-codescape-mti-mips
toolchain-external-linaro-aarch64
toolchain-external-codesourcery-aarch64
toolchain-external-linaro-aarch64-be
toolchain-external-andes-nds32
toolchain-external-codesourcery-amd64
toolchain-external-linaro-arm
toolchain-external-arm-aarch64
toolchain-external-codesourcery-arm
toolchain-external-linaro-armeb
toolchain-external-arm-aarch64-be
toolchain-external-codesourcery-mips
toolchain-external-arm-arm
toolchain-external-codesourcery-niosII
toolchain-external-synopsys-arc
toolchain-external-codescape-img-mips

**Comment by lzufalcon** [comment]
新增一个类似 bootlin，但是针 For Windows 的：

http://gnutoolchains.com/download/

**Comment by shankerwangmiao** [comment]
Close without reason.
