### ISSUE TITLE
Anaconda使用清华源update all后出现问题无法正常使用

### ISSUE THREAD

**Issue by Fr33raNg3r** [tuna/issues#602]
全新安装的Anaconda201903版本，使用conda update -all 更新完成后，无法打开anaconda prompt，也无法使用navigator，也无法运行任何conda命令。
所报错误和https://github.com/ContinuumIO/anaconda-issues/issues/11104一致，但是用官方源，所更新的内容不同，也就不会报错误，不清楚为何。

**Comment by phy25** [comment]
新安装了 Anaconda3-2019.07-Windows-x86_64.exe（未勾选 PATH 及默认程序选项），在 Anaconda Prompt 执行以下命令后关闭 Anaconda Prompt 、Navigator 可正常打开，`conda` 命令可正常运行。

```shell
$ conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
$ conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
$ conda config --set show_channel_urls yes
$ conda update --all
```

Anaconda3-2019.03-Windows-x86_64.exe 进行以上步骤，也无法重现此问题。
