### ISSUE TITLE
请求添加NeoTerm镜像

### ISSUE THREAD

**Issue by EromangaMe** [tuna/issues#603]
#### 项目名称与简介(Project Intro.)
Neo Term
A modern-designed Android terminal emulator for the 21st century. 

#### 上游地址与镜像方法(How to Mirror)
http://120.79.193.152/
#### 其他信息(Other)
[github](https://github.com/NeoTerm/NeoTerm)
- 镜像大小(Mirror Size):

**Comment by phy25** [comment]
My two cents:

- 上游的 IP 地址位于境内阿里云，而且没有域名解析。
- 该产品的使用量可能不是很大？
- 上游似乎不支持 rsync，提供的镜像抓取 sh 文件甚至连浏览器都无法打开下载（防火墙屏蔽）。
