### ISSUE TITLE
anaconda 安装 pytorch的问题，采用清华源和不采用清华源，安装内容不一样

### ISSUE THREAD

**Issue by HBat11233** [tuna/issues#604]
`>>>conda install pytorch torchvision cudatoolkit=10.0`

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3\envs\pytorch

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision

The following NEW packages will be INSTALLED:

  _pytorch_select    anaconda/pkgs/main/win-64::_pytorch_select-1.1.0-cpu
  blas               anaconda/pkgs/main/win-64::blas-1.0-mkl
  cffi               anaconda/pkgs/main/win-64::cffi-1.12.3-py37h7a1dbc1_0
  cudatoolkit        anaconda/pkgs/main/win-64::cudatoolkit-10.0.130-0
  freetype           anaconda/pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             anaconda/pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       anaconda/pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               anaconda/pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             anaconda/pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            anaconda/pkgs/main/win-64::libtiff-4.0.10-hb898794_2
  mkl                anaconda/pkgs/main/win-64::mkl-2019.4-245
  mkl_fft            anaconda/pkgs/main/win-64::mkl_fft-1.0.12-py37h14836fe_0
  mkl_random         anaconda/pkgs/main/win-64::mkl_random-1.0.2-py37h343c172_0
  ninja              anaconda/pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numpy              anaconda/pkgs/main/win-64::numpy-1.16.4-py37h19fb1c0_0
  numpy-base         anaconda/pkgs/main/win-64::numpy-base-1.16.4-py37hc3f5095_0
  olefile            anaconda/pkgs/main/win-64::olefile-0.46-py37_0
  pillow             anaconda/pkgs/main/win-64::pillow-6.1.0-py37hdc69c19_0
  pycparser          anaconda/pkgs/main/win-64::pycparser-2.19-py37_0
  **pytorch            anaconda/pkgs/main/win-64::pytorch-1.0.1-cpu_py37h39a92a0_0**
  six                anaconda/pkgs/main/win-64::six-1.12.0-py37_0
  tk                 anaconda/pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        anaconda/cloud/pytorch/noarch::torchvision-0.2.2-py_3
  xz                 anaconda/pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  zlib               anaconda/pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               anaconda/pkgs/main/win-64::zstd-1.3.7-h508b16e_0

`>>>conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3\envs\pytorch

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.1.0              |py3.7_cuda100_cudnn7_1       496.0 MB  pytorch
    ------------------------------------------------------------
                                           Total:       496.0 MB

The following NEW packages will be INSTALLED:

  blas               anaconda/pkgs/main/win-64::blas-1.0-mkl
  cffi               anaconda/pkgs/main/win-64::cffi-1.12.3-py37h7a1dbc1_0
  cudatoolkit        anaconda/pkgs/main/win-64::cudatoolkit-10.0.130-0
  freetype           anaconda/pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             anaconda/pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       anaconda/pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               anaconda/pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             anaconda/pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            anaconda/pkgs/main/win-64::libtiff-4.0.10-hb898794_2
  mkl                anaconda/pkgs/main/win-64::mkl-2019.4-245
  mkl_fft            anaconda/pkgs/main/win-64::mkl_fft-1.0.12-py37h14836fe_0
  mkl_random         anaconda/pkgs/main/win-64::mkl_random-1.0.2-py37h343c172_0
  ninja              anaconda/pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numpy              anaconda/pkgs/main/win-64::numpy-1.16.4-py37h19fb1c0_0
  numpy-base         anaconda/pkgs/main/win-64::numpy-base-1.16.4-py37hc3f5095_0
  olefile            anaconda/pkgs/main/win-64::olefile-0.46-py37_0
  pillow             anaconda/pkgs/main/win-64::pillow-6.1.0-py37hdc69c19_0
  pycparser          anaconda/pkgs/main/win-64::pycparser-2.19-py37_0
  **pytorch            pytorch/win-64::pytorch-1.1.0-py3.7_cuda100_cudnn7_1**
  six                anaconda/pkgs/main/win-64::six-1.12.0-py37_0
  tk                 anaconda/pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        pytorch/win-64::torchvision-0.3.0-py37_cu100_1
  xz                 anaconda/pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  zlib               anaconda/pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               anaconda/pkgs/main/win-64::zstd-1.3.7-h508b16e_0

**Comment by phy25** [comment]
前后两次解析哪次是在清华源上，哪次不在清华源上（只能猜测后一次在清华源上）？两次的 channel 设置有什么不同？

我的猜测是，前一次解析没有定义 `-c pytorch`，所以会优先解析 default 源而不是第三方源，后一次则有 `-c pytorch` 所以会默认走第三方源，所以会有不同？

**Comment by HBat11233** [comment]
第一次是清华源，第二次加了 -c pytorch 解析的是官方源。应该是这样的。

**Comment by phy25** [comment]
请留意 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 中第三方源的 channel 地址。

个人认为前后两条命令的不同，导致在同一个 channel 配置下可能都会产生不同的效果。能否统一一下命令再试一次呢？

**Comment by HBat11233** [comment]
(pytorchtest) C:\Users\HBat>conda info

     active environment : pytorchtest
    active env location : D:\ProgramData\Anaconda3\envs\pytorchtest
            shell level : 2
       user config file : C:\Users\HBat\.condarc
 populated config files : C:\Users\HBat\.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : D:\ProgramData\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\HBat\.conda\pkgs
                          C:\Users\HBat\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\HBat\.conda\envs
                          C:\Users\HBat\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


(pytorchtest) C:\Users\HBat>conda install pytorch torchvision cudatoolkit=10.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3\envs\pytorchtest

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

  _pytorch_select    anaconda/pkgs/main/win-64::_pytorch_select-1.1.0-cpu
  blas               anaconda/pkgs/main/win-64::blas-1.0-mkl
  cffi               anaconda/pkgs/main/win-64::cffi-1.12.3-py37h7a1dbc1_0
  cudatoolkit        anaconda/pkgs/main/win-64::cudatoolkit-10.0.130-0
  freetype           anaconda/pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             anaconda/pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       anaconda/pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               anaconda/pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             anaconda/pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            anaconda/pkgs/main/win-64::libtiff-4.0.10-hb898794_2
  mkl                anaconda/pkgs/main/win-64::mkl-2019.4-245
  mkl_fft            anaconda/pkgs/main/win-64::mkl_fft-1.0.12-py37h14836fe_0
  mkl_random         anaconda/pkgs/main/win-64::mkl_random-1.0.2-py37h343c172_0
  ninja              anaconda/pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numpy              anaconda/pkgs/main/win-64::numpy-1.16.4-py37h19fb1c0_0
  numpy-base         anaconda/pkgs/main/win-64::numpy-base-1.16.4-py37hc3f5095_0
  olefile            anaconda/pkgs/main/win-64::olefile-0.46-py37_0
  pillow             anaconda/pkgs/main/win-64::pillow-6.1.0-py37hdc69c19_0
  pycparser          anaconda/pkgs/main/win-64::pycparser-2.19-py37_0
  pytorch            anaconda/pkgs/main/win-64::pytorch-1.0.1-cpu_py37h39a92a0_0
  six                anaconda/pkgs/main/win-64::six-1.12.0-py37_0
  tk                 anaconda/pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        anaconda/cloud/pytorch/noarch::torchvision-0.2.2-py_3
  xz                 anaconda/pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  zlib               anaconda/pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               anaconda/pkgs/main/win-64::zstd-1.3.7-h508b16e_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(pytorchtest) C:\Users\HBat>conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3\envs\pytorchtest

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

  blas               anaconda/pkgs/main/win-64::blas-1.0-mkl
  cffi               anaconda/pkgs/main/win-64::cffi-1.12.3-py37h7a1dbc1_0
  cudatoolkit        anaconda/pkgs/main/win-64::cudatoolkit-10.0.130-0
  freetype           anaconda/pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             anaconda/pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       anaconda/pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               anaconda/pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             anaconda/pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            anaconda/pkgs/main/win-64::libtiff-4.0.10-hb898794_2
  mkl                anaconda/pkgs/main/win-64::mkl-2019.4-245
  mkl_fft            anaconda/pkgs/main/win-64::mkl_fft-1.0.12-py37h14836fe_0
  mkl_random         anaconda/pkgs/main/win-64::mkl_random-1.0.2-py37h343c172_0
  ninja              anaconda/pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numpy              anaconda/pkgs/main/win-64::numpy-1.16.4-py37h19fb1c0_0
  numpy-base         anaconda/pkgs/main/win-64::numpy-base-1.16.4-py37hc3f5095_0
  olefile            anaconda/pkgs/main/win-64::olefile-0.46-py37_0
  pillow             anaconda/pkgs/main/win-64::pillow-6.1.0-py37hdc69c19_0
  pycparser          anaconda/pkgs/main/win-64::pycparser-2.19-py37_0
  pytorch            pytorch/win-64::pytorch-1.1.0-py3.7_cuda100_cudnn7_1
  six                anaconda/pkgs/main/win-64::six-1.12.0-py37_0
  tk                 anaconda/pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        pytorch/win-64::torchvision-0.3.0-py37_cu100_1
  xz                 anaconda/pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  zlib               anaconda/pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               anaconda/pkgs/main/win-64::zstd-1.3.7-h508b16e_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(pytorchtest) C:\Users\HBat>

**Comment by phy25** [comment]
https://github.com/tuna/issues/issues/604#issuecomment-516714960 给出的例子显然不是镜像源的问题。前一次不带 `-c pytorch`，后一次带 `-c pytorch`，区别如下：

```
1d0
< _pytorch_select anaconda/pkgs/main/win-64::_pytorch_select-1.1.0-cpu
20c19
< pytorch anaconda/pkgs/main/win-64::pytorch-1.0.1-cpu_py37h39a92a0_0
---
> pytorch pytorch/win-64::pytorch-1.1.0-py3.7_cuda100_cudnn7_1
23c22
< torchvision anaconda/cloud/pytorch/noarch::torchvision-0.2.2-py_3
---
> torchvision pytorch/win-64::torchvision-0.3.0-py37_cu100_1
```

显然前一次没有用到 pytorch 的源（因为 Anaconda 官方源存在同名的项目），而后一次会默认使用。所以会造成不同。
