### ISSUE TITLE
[Mirror Request] 请求增加 homebrew-cask 镜像

### ISSUE THREAD

**Issue by zengxs** [tuna/issues#606]
#### 项目名称与简介(Project Intro.)
[homebrew-cask](https://github.com/Homebrew/homebrew-cask) 是 homebrew 项目中除 homebrew-core 以外的另一个常用 brew-tap。

希望也能将其添加到镜像中。

#### 上游地址与镜像方法(How to Mirror)
上游: <https://github.com/homebrew/homebrew-cask.git>
同步方式: git mirror

#### 其他信息(Other)
- 镜像大小(Mirror Size): 约 200 MiB (完整 Git repo)

**Comment by z4yx** [comment]
已添加至同步脚本。
