### ISSUE TITLE
请问如何使用tuna安装使用cuda10.0.130编译的pytorch？

### ISSUE THREAD

**Issue by Mactarvish** [tuna/issues#607]
Hi，我目前使用Anaconda3-2019.03-Linux-x86_64.sh安装了Anaconda，试图安装使用cuda10.0.130编译的pytorch。我按以下内容配置了conda.rc：

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - default

show_channel_urls: true
remote_read_timeout_secs: 60.0

随后我执行命令：
conda install pytorch
得到的响应是：

Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /root/anaconda3

  added / updated specs:
    - pytorch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.10               |           py37_0         3.0 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    conda-package-handling-1.3.11|           py37_0         257 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    cudatoolkit-8.0            |                3       322.4 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    ninja-1.7.2                |                0         939 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pytorch-1.0.1              |py3.7_cuda8.0.61_cudnn7.1.2_2       291.8 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
    ------------------------------------------------------------
                                           Total:       618.4 MB

The following NEW packages will be INSTALLED:

  conda-package-han~ anaconda/cloud/conda-forge/linux-64::conda-package-handling-1.3.11-py37_0
  cudatoolkit        anaconda/pkgs/free/linux-64::cudatoolkit-8.0-3
  ninja              anaconda/pkgs/free/linux-64::ninja-1.7.2-0
  pytorch            anaconda/cloud/pytorch/linux-64::pytorch-1.0.1-py3.7_cuda8.0.61_cudnn7.1.2_2

The following packages will be UPDATED:

  conda                      pkgs/main::conda-4.6.11-py37_0 --> anaconda/cloud/conda-forge::conda-4.7.10-py37_0

Proceed ([y]/n)? y

可见anaconda在tuna查到的pytorch是用cuda8.0编译的，我看到镜像站上实际上存在使用cuda10编译的pytorch，例如pytorch-nightly-1.0.0.dev20190224-py3.7_cuda10.0.130_cudnn7.4.2_0.tar.bz2，请问如何才能让Anaconda安装该版本的pytorch？我尝试了将其下载下来使用conda离线安装，但是安装之后显示版本是unknown，在安装其它有相关依赖的软件时依然提示缺少该pytorch。谢谢！

**Comment by phy25** [comment]
`conda install pytorch -c pytorch`
