### ISSUE TITLE
anaconda源中的.conda文件

### ISSUE THREAD

**Issue by shitou1992** [tuna/issues#609]
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
在清华源中发现有.conda结尾的文件，请问这个文件是从哪同步过来的

**Comment by z4yx** [comment]
就是从官方来的，他们在推行新格式

**Comment by shitou1992** [comment]
有具体链接吗，我这边想同步弄过来，我在https://repo.continuum.io/pkgs/里没找到

**Comment by z4yx** [comment]
链接请看同目录下的json文件，在里面搜索 .conda

**Comment by shitou1992** [comment]
好的，谢谢大佬

**Comment by z4yx** [comment]
可以参考我们的同步脚本 https://github.com/tuna/tunasync-scripts/blob/master/anaconda.py

**Comment by shitou1992** [comment]
ok，看到了是这段吧，我先试下
packages = repodata['packages']
    if 'packages.conda' in repodata:
        packages.update(repodata['packages.conda'])

**Comment by shitou1992** [comment]
已经在正常同步了，感谢
