### ISSUE TITLE
Meteor 镜像

### ISSUE THREAD

**Issue by laosb** [tuna/issues#61]
#### Meteor

Meteor is an open source platform for web, mobile, and desktop.
#### 上游地址与镜像方法(How to Mirror)

安装 Meteor 时的安装包 upstream（meteor-bootstrap）：`https://static-meteor.netdna-ssl.com/packages-bootstrap/`
下载 Meteor 包的 upstream（meteor-warehouse）： `https://warehouse.meteor.com`
#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知
- 使用 / 测试方法：
  - Meteor 自身安装：`curl https://install.meteor.com > install_meteor.sh`，修改 130 行处 `TARBALL_URL` 为安装包（meteor-bootstrap）的镜像 URL，尝试跑 `install_meteor.sh`。
  - Meteor 包安装：运行 `METEOR_WAREHOUSE_URLBASE=<meteor-warehouse镜像地址> meteor add <未在本机安装过的包>`

**Comment by laosb** [comment]
为了简化使用体验，如果安装包（meteor-bootstrap）镜像做好了，我可以直接在 `install-cn.ourmeteor.com` 提供预修改好的 install script，这样可以通过 `curl install-cn.ourmeteor.com | sh` 安装 Meteor，与 Meteor 官方保持一致。

**Comment by bigeagle** [comment]
请问这个有多大？内容大概是什么？如何镜像呢？

**Comment by laosb** [comment]
直接反代就好，有多大……我不知道……

**Comment by laosb** [comment]
内容是 Meteor 安装包（包含 meteor-tool 以及全部依赖）和社区贡献的模块（包）

**Comment by bigeagle** [comment]
了解了。我们现在反代方面还没有一个成体系的方案，先放到 todo 吧。

**Comment by alick** [comment]
应当给出上游项目主页地址：https://www.meteor.com/

简介用[文档](http://docs.meteor.com/#/full/)里的这个描述就清楚多了：

> What is Meteor?

> Meteor is a full-stack JavaScript platform for developing modern web and mobile applications. Meteor includes a key set of technologies for building connected-client reactive applications, a build tool, and a curated set of packages from the Node.js and general JavaScript community.

**Comment by alick** [comment]
https://warehouse.meteor.com

这个地址我这里访问会得到一个含有 Access denied 内容的 XML

**Comment by laosb** [comment]
@alick 这个并没有首页，下载的目标地址是 meteor-tool 拼接出来的。

**Comment by haobingwang** [comment]
期待 meteor mirror 到来

**Comment by laosb** [comment]
@bigeagle Why closing without comments? Is there any specific reason for not implementing?

**Comment by bigeagle** [comment]
我们无力维护这个，很抱歉。
