### ISSUE TITLE
整理镜像openwrt和lede

### ISSUE THREAD

**Issue by yousong** [tuna/issues#610]
这个issue和 #433 说的是同样的事情

最近相关的issue还有ustclug/discussions#286，在这里复述一下

> LEDE和OpenWrt合并超过一年半了，LEDE这个名字在渐渐淡出
>
>  - 建议同样的内容以`openwrt`这个名字提供 ，原来的`lede`链接依然保留
>  - 首页镜像列表中的`lede`换成`openwrt`

tuna的openwrt名称下还有chaos_calmers的内容，这一点和ustclug的情况不同

chaos_calmers是15.05发布的版本，比较老了。可以确认一下chaos_calmers的文件下载情况，如果所剩无几，可以考虑下线。也可考虑把`/openwrt/chaos_calmer`路径单拎出来处理

**Comment by Argon-Pub** [comment]
我赞同这一议程。
OpenWrt 项目有官方 rsync 源（ rsync://downloads.openwrt.org/downloads ），而 TUNA Mirrors 所同步的 LEDE 项目的 rsync 源（ rsync://downloads.lede-project.org/downloads ）实际上已经是 OpenWrt 的内容。所谓“名正言顺”，难不成 OpenWrt 还不配拥有名字么？（笑

**Comment by z4yx** [comment]
已把lede改名为openwrt，原openwrt仓库改名为openwrt-archive。
同时创建了软链接，保证用户还能用原来url访问。
