### ISSUE TITLE
请求删除上游不强制要求的访问日志，只保留上游要求的访问日志

### ISSUE THREAD

**Issue by zaoqi** [tuna/issues#611]
通过某种算法，应该可以得到反变换的 长期固定的映射关系。
`该映射关系在 30 秒内保持固定`使这种算法更加容易实现。

**Comment by xavieryao** [comment]
您好，针对我们的日志IP变换算法（详见公告中具体算法一节），您所述的算法目前只在理论上可行，请您放心。

Ref: https://crypto.stackexchange.com/questions/8087/sha256-hmac-brute-force-with-chosen-plaintext-attacks

**Comment by zaoqi** [comment]
@xavieryao 如果只是要得到`长期固定的映射关系`,反变换的算法不一定需要直接按着变换算法来实现。

**Comment by Harry-Chen** [comment]
如果您能够指出相应的 `反变换算法`（如提出算法或者提供相关文献），我们将重新评估日志公开策略。否则，您不需要过多担心。

**Comment by zaoqi** [comment]
手写正常的代码分析"$http_user_agent"应该可以得到原始ip不改变时的比较准确的`固定的映射关系`
也许通过`机器学习`等技术可以得到更准确/更久的`固定的映射关系`

我确实不需要过多担心，因为我不再使用tuna源。

**Comment by xavieryao** [comment]
现在这个模式下，通过统计学手段长期追踪一部分人肯定是可行的，但通过某种算法取得对每个人都适用的长期固定的映射关系暂时是不可能的

**Comment by jiegec** [comment]
如果仅仅是通过IP来推断，我认为按照现有的密码学手段是做不到追踪的。

**Comment by xavieryao** [comment]
@jiegec ：@zaoqi 刚刚修改过的回复里说了这点了

**Comment by scateu** [comment]
或者提供一个不纳入统计的新域名(dht.mirrors.tuna.tsinghua.edu.cn)，或标记(Header)之类，供用户选择，并在主页上固定位置告知。

**Comment by scateu** [comment]
> 手写正常的代码分析"$http_user_agent"等应该可以得到原始ip不改变时的比较准确的`固定的映射关系`
> 也许通过`机器学习`等技术可以得到更准确/更久的`固定的映射关系`
> 
> 我确实不需要过多担心，因为我不再使用tuna源。

另外，摸摸 @zaoqi
