### ISSUE TITLE
建议anaconda首页增加default_channels命令行提示

### ISSUE THREAD

**Issue by SunyardSimon** [tuna/issues#612]
conda config --add default_channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
 conda config --add default_channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/

不然还是用的初始源地址，原有ADD命令无法生效。

**Comment by z4yx** [comment]
请直接修改 https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-anaconda.md 提交pr
