### ISSUE TITLE
国内python2-w3lib丢失

### ISSUE THREAD

**Issue by wudimenghuan** [tuna/issues#614]
archlinux

pacman报错

python2-w3lib没有

错误：无法从 mirrors.huaweicloud.com : The requested URL returned error: 404 获取文件 'python2-w3lib-1.21.0-1-any.pkg.tar.xz'
错误：无法从 mirrors.ustc.edu.cn : The requested URL returned error: 404 获取文件 'python2-w3lib-1.21.0-1-any.pkg.tar.xz'
错误：无法从 mirrors.zju.edu.cn : The requested URL returned error: 404 获取文件 'python2-w3lib-1.21.0-1-any.pkg.tar.xz'
错误：无法从 mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404 获取文件 'python2-w3lib-1.21.0-1-any.pkg.tar.xz'
错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'python2-w3lib-1.21.0-1-any.pkg.tar.xz'

community的gvm-libs也没了

```
$ sudo pacman -Ss gvm-libs
```

**Comment by phy25** [comment]
文件存在，请确认你的本地配置是否正确。

https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/python2-w3lib-1.21.0-1-any.pkg.tar.xz
https://mirrors.tuna.tsinghua.edu.cn/archlinux/community/os/x86_64/gvm-libs-10.0.1-1-x86_64.pkg.tar.xz
