### ISSUE TITLE
提议设立全新RGB-D数据集DIODE的镜像

### ISSUE THREAD

**Issue by shanyizhang** [tuna/issues#615]
#### 项目名称与简介(Project Intro.)
全新RGB-D数据集。国内下载速度慢，希望能够建立个镜像啥的。
官网：https://diode-dataset.org/
论文：https://arxiv.org/abs/1908.00463

#### 上游地址与镜像方法(How to Mirror)
Download links: train.tar.gz (81GB) | val.tar.gz (2.6GB)
http://diode-dataset.s3.amazonaws.com/train.tar.gz
http://diode-dataset.s3.amazonaws.com/val.tar.gz
个人不是很懂如何建立镜像，不知道aws下载链接能否镜像。谢谢。

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
上面有标注了

**Comment by z4yx** [comment]
数据集镜像统一在这边 https://github.com/tuna/dataset-issues
不过数据集镜像计划咕咕咕好久了

**Comment by shanyizhang** [comment]
谢谢 请问啥叫“咕咕咕”。不太懂。

**Comment by z4yx** [comment]
就是拖了好长时间，还没人做
