### ISSUE TITLE
Lede的镜像源已经很多天，没法使用了，请检查同步是否出了问题

### ISSUE THREAD

**Issue by liyuhaolol** [tuna/issues#618]
如题

**Comment by phy25** [comment]
Name | Last Update | Upstream | Status | Size
-- | -- | -- | -- | --
lede | 2019-08-04 17:00 | rsync://downloads.lede-project.org/downloads/ | failed | 322.44G

**Comment by liyuhaolol** [comment]
额，这是机器人自动回复么。。。。Status ：failed,有人出来负责维护这个事么？
