### ISSUE TITLE
站内Lede源snapshots分支没有被正确的创建镜像

### ISSUE THREAD

**Issue by liyuhaolol** [tuna/issues#619]
镜像站地址为：https://mirrors4.tuna.tsinghua.edu.cn/lede/snapshots/targets/
直接显示为404，对应的镜像没有被正确创立！
源站对应地址：https://downloads.openwrt.org/snapshots/targets/

**Comment by phy25** [comment]
Name | Last Update | Upstream | Status | Size
-- | -- | -- | -- | --
lede | 2019-08-20 20:26 | rsync://downloads.lede-project.org/downloads/ | success | 321.64G

```shell
$ rsync rsync://downloads.lede-project.org/downloads/snapshots/targets/
drwxr-xr-x          4,096 2019/08/20 21:59:29 .
drwxr-xr-x          4,096 2018/05/24 19:23:40 adm5120
drwxr-xr-x          4,096 2018/05/24 04:34:08 adm8668
drwxr-xr-x          4,096 2019/08/20 18:44:18 apm821xx
drwxr-xr-x          4,096 2019/08/20 20:12:31 ar7
drwxr-xr-x          4,096 2019/06/17 08:17:55 ar71xx
drwxr-xr-x          4,096 2019/08/20 14:22:20 arc770
drwxr-xr-x          4,096 2019/08/20 12:10:20 archs38
drwxr-xr-x          4,096 2019/08/20 17:18:26 armvirt
drwxr-xr-x          4,096 2019/08/20 15:13:42 at91
drwxr-xr-x          4,096 2019/08/20 12:59:53 ath25
drwxr-xr-x          4,096 2019/08/20 20:40:23 ath79
drwxr-xr-x          4,096 2018/05/25 00:10:24 au1000
drwxr-xr-x          4,096 2019/08/20 19:25:33 bcm53xx
drwxr-xr-x          4,096 2019/08/20 19:46:01 brcm2708
drwxr-xr-x          4,096 2019/08/20 17:27:47 brcm47xx
drwxr-xr-x          4,096 2019/08/20 21:14:36 brcm63xx
drwxr-xr-x          4,096 2019/08/20 11:41:51 cns3xxx
drwxr-xr-x          4,096 2019/08/20 16:27:11 gemini
drwxr-xr-x          4,096 2019/08/20 16:40:20 imx6
drwxr-xr-x          4,096 2019/08/20 21:59:29 ipq40xx
drwxr-xr-x          4,096 2019/08/20 14:05:05 ipq806x
drwxr-xr-x          4,096 2019/08/20 16:23:46 ixp4xx
drwxr-xr-x          4,096 2019/08/20 12:49:06 kirkwood
drwxr-xr-x          4,096 2019/08/20 21:45:03 lantiq
drwxr-xr-x          4,096 2019/08/20 21:26:27 layerscape
drwxr-xr-x          4,096 2019/08/20 20:16:48 malta
drwxr-xr-x          4,096 2018/05/24 08:25:21 mcs814x
drwxr-xr-x          4,096 2019/08/20 11:16:57 mediatek
drwxr-xr-x          4,096 2019/08/20 20:51:42 mpc85xx
drwxr-xr-x          4,096 2019/08/20 11:54:08 mvebu
drwxr-xr-x          4,096 2019/08/20 17:34:46 mxs
drwxr-xr-x          4,096 2019/08/20 20:00:50 octeon
drwxr-xr-x          4,096 2019/08/20 12:57:16 octeontx
drwxr-xr-x          4,096 2019/08/20 18:07:33 omap
drwxr-xr-x          4,096 2019/08/20 13:03:01 oxnas
drwxr-xr-x          4,096 2019/08/20 14:41:00 pistachio
drwxr-xr-x          4,096 2017/01/05 19:49:43 ppc44x
drwxr-xr-x          4,096 2019/08/20 21:17:12 ramips
drwxr-xr-x          4,096 2019/08/20 16:00:07 rb532
drwxr-xr-x          4,096 2019/08/20 20:34:57 samsung
drwxr-xr-x          4,096 2019/08/20 18:56:20 sunxi
drwxr-xr-x          4,096 2019/08/20 15:05:18 tegra
drwxr-xr-x          4,096 2019/08/20 19:14:40 x86
drwxr-xr-x          4,096 2018/05/24 21:40:46 xburst
drwxr-xr-x          4,096 2019/08/20 17:39:43 zynq
$ rsync rsync://downloads.lede-project.org/downloads/
drwxr-xr-x          4,096 2019/07/04 15:16:01 .
-rw-r--r--          4,271 2019/07/04 15:15:21 index.html
drwxr-xr-x          4,096 2019/08/20 21:46:31 releases
drwxr-xr-x          4,096 2019/08/20 21:59:29 snapshots
$ rsync rsync://mirrors.tuna.tsinghua.edu.cn/lede/
drwxr-xr-x            104 2019/07/04 15:16:01 .
-rw-r--r--          4,271 2019/07/04 15:15:21 index.html
drwxr-xr-x            672 2019/08/20 19:52:50 releases
```

> **Development Snapshots**
> Development snapshots are automatic unattended daily builds of the current OpenWrt development master branch. Bear in mind that these images are generally not tested, use them at your own risk.

**Comment by shankerwangmiao** [comment]
您好，由于 snapshots 是每日更新的，每日的同步数据量较大，因此该目录被过滤掉了。

**Comment by abc1763613206** [comment]
@shankerwangmiao 还是希望有机会的情况下对其中的`packages`软件包部分单独做个镜像，目前国内基本没有镜像站搞这部分，`opkg`直连OpenWrt装软件包的时候简直自闭。

**Comment by phy25** [comment]
@abc1763613206 releases 下面似乎也有 packeges 文件夹，可否稍微解释一下这个和 snapshots 的区别吗？

**Comment by liyuhaolol** [comment]
> @abc1763613206 releases 下面似乎也有 packeges 文件夹，可否稍微解释一下这个和 snapshots 的区别吗？

snapshots的更新速度比releases要频繁的多，就像上面shankerwangmiao所说的，属于日更新级别，但是我这边实际使用发现如下2个情况。
1，虽然snapshots官方定位为未被测试的日更仓库，但是实际上，里面的package并不是每天都会被更新，某些插件releases里的18.06.4的插件是18年的版本，snapshots是19年3月的版本，其实并不是日更。所以咱们这边clone一次以后，其实每天日更不就是更新改动么？难道每次都是重新clone不成？这个我不懂。
2，虽然是snapshots，但是我这边发现所有固件，不论是官方openwrt，还是lean，还是koolshare，他们默认都是使用snapshots，而不是使用releases的packages，等于其实官方就是一直在用这个snapshots仓库。并没有使用releases。
然而最关键的是国内确实没有任何一个同步的镜像站了，造成软件更新十分困难。所以如果可以，还是希望咱们这边可以同步。

**Comment by liyuhaolol** [comment]
> @shankerwangmiao 还是希望有机会的情况下对其中的`packages`软件包部分单独做个镜像，目前国内基本没有镜像站搞这部分，`opkg`直连OpenWrt装软件包的时候简直自闭。

实在不行，你可以先把你的源换成，新加坡镜像站，这个站带宽和延迟对于中国这边都相对友好一些，地址为：http://mirror.0x.sg/openwrt/，后面接snapshots那些，自己拼连接就好了。

**Comment by abc1763613206** [comment]
> http://mirror.0x.sg/openwrt/

thx, 速度好多了

**Comment by 863zq** [comment]
> > http://mirror.0x.sg/openwrt/
> 
> thx, 速度好多了

Thanks

**Comment by Harry-Chen** [comment]
> 2，虽然是snapshots，但是我这边发现所有固件，不论是官方openwrt，还是lean，还是koolshare，他们默认都是使用snapshots，而不是使用releases的packages，等于其实官方就是一直在用这个snapshots仓库。并没有使用releases。

我当年用 openwrt 的时候所有软件源都是 release 的…其实手动切换一下不至于引起问题吧。

> 然而最关键的是国内确实没有任何一个同步的镜像站了，造成软件更新十分困难。所以如果可以，还是希望咱们这边可以同步。

我们尝试过同步，但是 snapshot 变化很快，我们连初始同步都难以完成，然后也难以追及它的进度。

**Comment by viagram** [comment]
日，用麻花疼的源试试：https://mirrors.cloud.tencent.com/openwrt/snapshots/targets/
