### ISSUE TITLE
关于remi源

### ISSUE THREAD

**Issue by Xiang1993** [tuna/issues#62]
remi源的官方镜像中，RPM-GPG-KEY-remi是网页的内容提供的，而不是文件的形式，所以在remi.repo文件中直接添加官方的remi源的RPM-GPG-KEY-remi链接：http://rpms.remirepo.net/RPM-GPG-KEY-remi  会出错
希望在清华大学镜像网站中添加RPM-GPG-KEY-remi这个文件

**Comment by bigeagle** [comment]
好的，已经加上了～
