### ISSUE TITLE
numpy 1.17.0.zip 

### ISSUE THREAD

**Issue by WillingDil** [tuna/issues#624]
Ubuntu16.04+python2.7  使用pip install sklearn -i https://pypi.tuna.tsinghua.edu.cn/simple 操作，
![YATB64W( PFC)I{`5Z6Y1QA](https://user-images.githubusercontent.com/27851882/63660192-e8e1dd80-c7e7-11e9-9624-4b67a06e9075.png)，为什么我怎么调整 安装的版本，只要使用了镜像就一定会下载numpy1.17.0.zip这个压缩包，只能是卸载python2安装python3,但是我还是想要python2,我应该怎么操作

**Comment by z4yx** [comment]
你可以试试先安装老版本的numpy `pip install numpy==1.14.6  -i https://pypi.tuna.tsinghua.edu.cn/simple `

**Comment by WillingDil** [comment]
谢谢...
