### ISSUE TITLE
镜像请求 Piwheels.org

### ISSUE THREAD

**Issue by inactive-virus** [tuna/issues#626]
#### 项目名称与简介(Project Intro.)

[Piwheels](https://piwheels.org) 是一个面向ARM平台（主要是树莓派）提供预编译的Python软件包的开源项目。所有软件包都在树莓派3上本地编译而成，也适用于国产ARM开发板如[香橙派](http://www.orangepi.cn)，能够为用户节约大量的编译时间。（校内iCenter就有很多树莓派在授课的时候分发给同学使用，未来也有可能引入更多ARM开发板，因此引入Piwheels镜像是有一定意义的。）

#### 上游地址与镜像方法(How to Mirror)

https://piwheels.org/simple

我在推特上联系了piwheels的创建人Ben Nuttall，Ben同意创建镜像，不过细节还有待商议。如果镜像站也同意引入镜像，我会进一步联系Ben获取信息。

![QQ截图20190902104204](https://user-images.githubusercontent.com/28744819/64087318-1e9a3f80-cd6f-11e9-9849-ac1e516eca99.png)

#### 其他信息(Other)

- 镜像大小(Mirror Size): 约1TB

**Comment by inactive-virus** [comment]
已发送私信询问是否能提供rsync

**Comment by lin5464** [comment]
请问进展如何，piwheels.org的镜像什么时候能上线？

**Comment by lin5464** [comment]
@inactive-virus @z4yx Any update?

**Comment by z4yx** [comment]
尚未取得同步方法

**Comment by inactive-virus** [comment]
至今没回复，再问一次好了

**Comment by wlnirvana** [comment]
Any update?

**Comment by shankerwangmiao** [comment]
尚未取得同步方法

**Comment by Harry-Chen** [comment]
由于始终未能获得同步方法，并且对于 PyPI 类站点我们无法进行较好地同步，因此暂时关闭此 issue
