### ISSUE TITLE
希望 gitlab-ce 中加入 Debian buster 的支持

### ISSUE THREAD

**Issue by brainbush** [tuna/issues#627]
Debian 10 正式版在前几个月已发布，且 gitlab-ce 也在最近的版本中加入了对该版本的支持
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4433#note_197405150
如果可以的话麻烦加一下，谢谢（gitlab-runner同样如此）

**Comment by Harry-Chen** [comment]
感谢指出这一问题，我们也会对其他的repo进行排查
