### ISSUE TITLE
Mirror OpenMediaVault

### ISSUE THREAD

**Issue by JustinLiu2012** [tuna/issues#629]
#### 项目名称与简介(Project Intro.)
OpenMediaVault 
OpenMediaVault，是一个开源的基于Debian Linux的下一代网络附加存储(NAS)解决方案。它包含众多服务,如SSH,(S)FTP,SMB / CIFS,DAAP媒体服务器,RSync,BitTorrent客户机等。 并具有通过插件可增强的模块化设计框架特性。
OpenMediaVault主要是设计用于在家庭环境或小的家庭办公室,但不仅限于这些场景。 这是一个简单和易于使用的开箱即用的解决方案,允许任何没有更深的知识的人来安装和管理的网络附加存储(NAS)。
FreeNAS、OpenMediaVault、NAS4Free关系：Olivier Cochard-Labbe在2005年创建了FreeNAS项目，后Volker Theile加入该项目作为核心开发人员 [2]  ；2009年12月Olivier Cochard-Labbe发表声明停止为FreeNAS 0.7版本开发新功能后，Volker Theile创建了基于Debian Linux的OpenMediaVault项目，并采用GPLv3授权；iXsystems收购FreeNAS后重写了网页框架和构架在2011年发布了全新的FreeNAS 8版本 ；2011年其余开发者基于FreeNAS 0.7开发了分支并重新命名为NAS4Free  。
#### 上游地址与镜像方法(How to Mirror)
https://packages.openmediavault.org/public/
or
https://sourceforge.net/projects/openmediavault/files/packages/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知。

**Comment by z4yx** [comment]
已添加到 https://mirrors.bfsu.edu.cn/OpenMediaVault/public/
在 apt 配置中使用该地址即可
