### ISSUE TITLE
gitlab-ce 与 gitlab-ci-multi-runner 包缺失

### ISSUE THREAD

**Issue by zhujunsan** [tuna/issues#63]
gitlab-ce 8.7.5 之后
gitlab-ci-multi-runner 1.1.4 之后
至少是Ubuntu的deb安装包都没有同步过来，虽然别的信息都过来了就导致更新的时候虽然能知道有新版本但是下载地址都是404

p.s.: [同步状态](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status) 那边都显示成功 O_O

**Comment by bigeagle** [comment]
看来还是同步脚本有问题

**Comment by bigeagle** [comment]
我的锅，调试的时候把 wget 注释掉了……

**Comment by zhujunsan** [comment]
(゜o゜)

好吧

**Comment by zhujunsan** [comment]
confirm fixed
