### ISSUE TITLE
镜像请求 raspbian 系统iso请求

### ISSUE THREAD

**Issue by renzibei** [tuna/issues#630]
#### 项目名称与简介(Project Intro.)
raspbian是树莓派的官方支持操作系统，有很多使用树莓派，其操作系统的iso需求也很多,但目前比较靠谱的下载方法只有国外的官网提供。请求进行iso的镜像提供。 现在raspbian的版本为Buster
#### 上游地址与镜像方法(How to Mirror)
[下载地址](https://downloads.raspberrypi.org/raspbian_latest)
#### 其他信息(Other)
size: 1149 MB

**Comment by zichenglang** [comment]
Raspbian is a really important OS, So many young child can learn programing by using it. It is very meaningful to set up an official iso mirror repo in China.

**Comment by z4yx** [comment]
可以从镜像站主页右侧“获取下载链接”快速下载
