### ISSUE TITLE
anaconda 镜像源文档

### ISSUE THREAD

**Issue by hubutui** [tuna/issues#634]
看到 https://mirror.tuna.tsinghua.edu.cn/help/anaconda/ 更新了．目前是直接给出了配置文件 `.condarc` 的内容，default channels 里是不是少了个 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free`?

**Comment by phy25** [comment]
https://github.com/tuna/issues/issues/612#issuecomment-520304763

> 请直接修改 https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-anaconda.md 提交pr

**Comment by z4yx** [comment]
不好意思，由于TUNA这边没有anaconda用户，难以发现和测试问题，相关教程全靠社区贡献。多谢各位了。
