### ISSUE TITLE
申请同步archives.fedoraproject.org的镜像

### ISSUE THREAD

**Issue by j3l11234** [tuna/issues#636]
#### 项目名称与简介(Project Intro.)
fedora官方源 已经将28及其之前版本的源迁移到https://archives.fedoraproject.org/pub/archive/fedora
但是清华的fedora源现在只有 一个readme
https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/28/

#### 上游地址与镜像方法(How to Mirror)
https://archives.fedoraproject.org/pub/archive/fedora

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by sugarfillet** [comment]
fedora29，也已停维，并归档。 支持镜像 achive。

**Comment by j3l11234** [comment]
> fedora29，也已停维，并归档。 支持镜像 achive。

能否给出achive的镜像的地址？

**Comment by z4yx** [comment]
暂时不对各发行版的archive作镜像，涉及的数据量太大。
