### ISSUE TITLE
cudatoolkit-9.2版本没有

### ISSUE THREAD

**Issue by fengxijia** [tuna/issues#637]
#### 项目名称与简介(Project Intro.)
无
#### 上游地址与镜像方法(How to Mirror)
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev

#### 其他信息(Other)
- 镜像大小(Mirror Size): 大概一两百M

**Comment by z4yx** [comment]
不知道你的系统是什么，我们和官方一样，在linux-64架构上提供cudatoolkit 9.2
https://anaconda.org/anaconda/cudatoolkit/files
https://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/cudatoolkit-9.2-0.tar.bz2

**Comment by fengxijia** [comment]
> 不知道你的系统是什么，我们和官方一样，在linux-64架构上提供cudatoolkit 9.2
> https://anaconda.org/anaconda/cudatoolkit/files
> https://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/cudatoolkit-9.2-0.tar.bz
win10的系统

![win-64缺cudatoolkit=9 2](https://user-images.githubusercontent.com/32954412/66247627-7e5e7e80-e751-11e9-87cf-17e265eed42e.PNG)

**Comment by z4yx** [comment]
![image](https://user-images.githubusercontent.com/2733275/66254068-a70f6400-e7a3-11e9-9870-b08ef11cfc91.png)
官方也没有

**Comment by fengxijia** [comment]
> ![image](https://user-images.githubusercontent.com/2733275/66254068-a70f6400-e7a3-11e9-9870-b08ef11cfc91.png)
> 官方也没有

CUDA9.0和10.0的Pytorch官方安装命令和CUDA9.2不一样，可能是9.2放的路径与9.0、10.0不一样？我之前直接运行官网的命令，是有这个cudatoolkit=9.2的，但是因为是从外网下，频繁断网，下不下来。
![Pytorch官网CUDA9 2安装命令](https://user-images.githubusercontent.com/32954412/66254309-26eafd80-e7a7-11e9-8307-136504fa94f8.PNG)
![Pytorch官网CUDA10 0安装命令](https://user-images.githubusercontent.com/32954412/66254310-27839400-e7a7-11e9-90a5-1b8409294229.PNG)

**Comment by peterjc123** [comment]
额 因为windows的cudatoolkit 9.2在官方的channel里面没有，所以使用的是numba/label/dev里面的版本。要解决这个问题需要提供对numba channel的镜像。

**Comment by fengxijia** [comment]
嗯嗯，谢谢~
（题外话，后来去英伟达的官网升级CUDA到最新版本10.1，然后下CUDA10.0对应的Anaconda就可以跳过这个问题惹。）

**Comment by z4yx** [comment]
已添加 numba channel

> 额 因为windows的cudatoolkit 9.2在官方的channel里面没有，所以使用的是numba/label/dev里面的版本。要解决这个问题需要提供对numba channel的镜像。

**Comment by peterjc123** [comment]
现在虽然有了numba channel，但是windows下的cudatoolkit 9.2 是在 dev 这个label 下，而这边好像只对main这个label进行镜像。

**Comment by peterjc123** [comment]
所以，在 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/numba/win-64/ 这个下面不能找到cudatookit9.2版本，但是在anaconda界面上可以找到 https://anaconda.org/numba/cudatoolkit/9.2/download/win-64/cudatoolkit-9.2-0.tar.bz2

**Comment by peterjc123** [comment]
貌似应该添加像这样的URL：https://conda.anaconda.org/numba/label/dev/win-64

**Comment by yuhaoooo** [comment]
在添加numba/label/dev镜像之后，使用`conda install cudatoolkit=9.2`报错，如下图：
![image](https://user-images.githubusercontent.com/24415219/69480588-ae69fa00-0e43-11ea-89e9-9276016744a3.png)

**Comment by peterjc123** [comment]
@yuhaoooo 配置文件能分享下吗？

**Comment by yuhaoooo** [comment]
这是配置文件
![image](https://user-images.githubusercontent.com/24415219/69488502-0258fb00-0ea5-11ea-9440-45a45741092f.png)

**Comment by peterjc123** [comment]
可能还需要添加下noarch, 从日志里发现了这行：
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/numba/label/dev/noarch/repodata.json
```

**Comment by yuhaoooo** [comment]
添加noarch之后，问题解决了。
