### ISSUE TITLE
申请 linux-firmware.git 库的同步

### ISSUE THREAD

**Issue by TelDragon** [tuna/issues#639]
#### 项目名称与简介(Project Intro.)
armbian 项目 编译固件时 需要对 linux-firmware.git  进行检查。目前只有

#### 上游地址与镜像方法(How to Mirror)
```
https://kernel.googlesource.com/pub/scm/linux/kernel/git/firmware/linux-firmware.git
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
```

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

中国大陆 访问此站点及其缓慢。

**Comment by z4yx** [comment]
已添加到 https://mirrors.tuna.tsinghua.edu.cn/git/linux-firmware.git
