### ISSUE TITLE
nginx镜像

### ISSUE THREAD

**Issue by huiyiqun** [tuna/issues#64]
#### 项目名称与简介(Project Intro.)

nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server, originally written by Igor Sysoev. For a long time, it has been running on many heavily loaded Russian sites including Yandex, Mail.Ru, VK, and Rambler. According to Netcraft, nginx served or proxied 27.24% busiest sites in May 2016. Here are some of the success stories: Netflix, Wordpress.com, FastMail.FM.
#### 上游地址与镜像方法(How to Mirror)

http://nginx.org/packages/
没有rsync 只能通过http了
nginx官方对于mirror似乎不太care：[见这](https://forum.nginx.org/read.php?2,236342,236387#msg-236387)
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
  未知

**Comment by Harry-Chen** [comment]
似乎可以通过 lftp 来拖

**Comment by z4yx** [comment]
deb 和 yum 源我们都有同步工具，不需要lftp。

**Comment by z4yx** [comment]
问题是有多少场景会用到这个仓库呢，跟发行版提供的有什么区别？

**Comment by Harry-Chen** [comment]
> 问题是有多少场景会用到这个仓库呢，跟发行版提供的有什么区别？

这个和 mongodb / mariadb 之类是一样的。不太一样的是后两者发行版版本可能不太够（比如缺功能），但是 nginx 我确实没遇到过发行版的功能不够的情况……

**Comment by z4yx** [comment]
后来再也没见谁提过nginx的mirror request，估计需求不大。

**Comment by Harry-Chen** [comment]
好，关了
