### ISSUE TITLE
pytorch 1.3.0 功能缺失

### ISSUE THREAD

**Issue by deipss** [tuna/issues#640]
将pytorch升级到了1.3.0版本，pytorch的官方发布声明中，其新版本已实现了transformer的源码，并在其[官方教程文档](https://pytorch.org/docs/stable/nn.html?highlight=transformerencoder#torch.nn.TransformerEncoder)中，提出了相关的API以及其他使用说明。

而后，我使用清华的开源镜像，将我的pytorch版本，以及相应的cuda一齐升级后，发现新的版本中没有**Transformer**相关的代码实现。
并在pytorch官方github上提交了[issue](https://github.com/pytorch/pytorch/issues/27447#event-2695770683)，并得出答复，应该没会出现此类问题。

在我的Pc中，使用 ```  conda list | grep torch ```后，可以得出以下相关的版本及channel信息。

```
cpuonly                   1.0                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
torchtext                 0.4.0              pyhb384e40_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

```
     所以希望得到维护小组方的确认 这些版本没有问题

**Comment by shankerwangmiao** [comment]
镜像站上的数据是与上游是一致的，您手动下载然后对比就可以确认这一事情。

**Comment by deipss** [comment]
> 镜像站上的数据是与上游是一致的，您手动下载然后对比就可以确认这一事情。

了解，谢谢。

**Comment by deipss** [comment]
可以正常使用。
