### ISSUE TITLE
使用pip安装pytorch1.3时，无法利用清华镜像进行加速

### ISSUE THREAD

**Issue by PingHGao** [tuna/issues#641]
我利用pip安装pytorch1.3时，从官网获取的安装命令是`pip3 install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html`。该命令中由于存在`-f site`部分，使得安装时必须从官网下载相应的安装包，速度实在是太慢（10kb）。
![pytorch](https://user-images.githubusercontent.com/19465753/66905814-23723480-f039-11e9-8baf-fa344382af14.png)

所以我的问题是：**应该如何替换该部分命令以便利用清华镜像进行加速？**

**Comment by shankerwangmiao** [comment]
我们暂时没有提供 pytorch 的 whl 包镜像，如果该 whl 包没有在 pypi.org 的仓库内。您可以选用我们镜像的 anaconda 提供的 pytorch 包，请参考 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/ 。

**Comment by PingHGao** [comment]
请问pytorch的whl包是会慢慢的被pypi.org的仓库包含吗？你们有计划提供pytorch的whl包吗？

**Comment by shankerwangmiao** [comment]
暂时没有计划。

whl 包是否会被 pypi.org 的仓库收录，取决于其作者是否希望把该包提交给 pypi.org
