### ISSUE TITLE
请求添加clickhouse 镜像

### ISSUE THREAD

**Issue by vkingnew** [tuna/issues#642]
上游源（官方镜像）的地址
https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/
https://repo.yandex.ru/clickhouse/deb/stable/

该项目的介绍
ClickHouse是俄罗斯yandex开源的一个用于联机分析(OLAP)的列式数据库管理系统(DBMS)。列式存储，速度快，压缩比高，不支持事务. 是大数据分析的利器。
官方文档：
https://clickhouse.yandex/docs/en/

为什么希望添加该镜像
clickhouse的文件安装和下载，在国内速度很慢，国内有大面积的使用和调研，请求添加clickhouse的镜像。

**Comment by abcfy2** [comment]
这个之前用过，单机分析体验确实特别赞，速度极快，压缩比也高。不过目前我们主要用的还是HBase，生态方面暂时不方便迁移，之前体验过clickhouse，确实非常喜人

**Comment by z4yx** [comment]
开始同步了，可能要等一段时间。

**Comment by vkingnew** [comment]
公开的地址可以贴上来不？

**Comment by z4yx** [comment]
https://mirrors.tuna.tsinghua.edu.cn/clickhouse/

**Comment by vkingnew** [comment]
多谢！  麻烦再写一段帮助信息 ，和别的项目一样的？提示信息

**Comment by z4yx** [comment]
等同步完了会加帮助的，现在还不可用。
