### ISSUE TITLE
镜像请求: GCC Git

### ISSUE THREAD

**Issue by FlyGoat** [tuna/issues#643]
#### 项目名称与简介(Project Intro.)
GCC Git

#### 上游地址与镜像方法(How to Mirror)
https://gcc.gnu.org/git/gcc.git
#### 其他信息(Other)
- 镜像大小(Mirror Size):
About 2GB?

**Comment by z4yx** [comment]
已添加 https://mirror.tuna.tsinghua.edu.cn/git/gcc.git
