### ISSUE TITLE
镜像请求：debian-debug

### ISSUE THREAD

**Issue by cdluminate** [tuna/issues#644]
#### 项目名称与简介(Project Intro.)

Debug information for Debian packages.
https://wiki.debian.org/HowToGetABacktrace
https://wiki.debian.org/AutomaticDebugPackages

#### 上游地址与镜像方法(How to Mirror)

wiki上一般都是推荐从 http://deb.debian.org/debian-debug 下载，
但是我每次用都下载速度奇慢。。。 
在若干 ftp.??.debian.org 镜像逛了一圈发现至少 ftp.de.debian.org
有rsync可以直接拖
```
rsync -av ftp.de.debian.org::debian-debug
```

#### 其他信息(Other)
- 镜像大小(Mirror Size): 800GB (未裁剪）
- 预计用户数量：很少

毕竟只有遇到故障才会去想它。tuna资源比较紧张，或许挂在mirrors.bfsu也不错，如果有精力搞的话。

**Comment by z4yx** [comment]
调试符号用户量很少，占用空间较大，性价比较低。目前几大发行版我们都没有镜像调试符号仓库，或者同步时从仓库中过滤掉了调试符号（主要是yum类的）。

**Comment by yuzibo** [comment]
FYI:
Now iscas has one debian-debug mirror:
https://mirror.iscas.ac.cn/debian-debug/
