### ISSUE TITLE
termux 执行 apt upgrade后报错

### ISSUE THREAD

**Issue by LeIgHlEe** [tuna/issues#646]
termux更新镜像源后，执行apt update成功，执行apt upgrade时卡在90%，报错信息为：

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found

关掉进程后再打开，如附件所示，只能按回车退出，请问如何解决？
![20191021061544](https://user-images.githubusercontent.com/36221673/67167306-e3110e80-f3ca-11e9-814d-2fc4e84d41b2.jpg)

**Comment by uzilla** [comment]
这个问题反馈给termux会更好

**Comment by LeIgHlEe** [comment]
只要用镜像源就会出错，不用挂梯子一切正常

**Comment by z4yx** [comment]
确认问题存在，怀疑可能与termux上游变更有关。在与新的上游同步前，我们将关掉镜像，以免损坏用户的系统。

**Comment by z4yx** [comment]
成功把上游切换到了 dl.bintray.com/termux/termux-packages-24/
