### ISSUE TITLE
AOSP编译完成无法启动模拟器

### ISSUE THREAD

**Issue by Lungffy** [tuna/issues#647]
环境：ubuntu 18.4
aosp 编译完成后，emulator启动模拟器，一直黑屏，提示的异常日志：
statvfs(/aosp/out/target/product/generic/snapshots/default_boot/ram.img) failed:No such file or directory
emulator:WARNING:encryption is off
emulator:ERROR:VKCommonOperations.cpp:496:Failed to create Vulkan instance

初步判断跟新模拟器的QT有关，各位有没有遇到过

**Comment by shankerwangmiao** [comment]
您好，您反馈的关于安卓系统模拟器的问题不属于 TUNA Mirror 的使用问题。建议您选择更合适的讨论区提问。
