### ISSUE TITLE
anaconda更新问题

### ISSUE THREAD

**Issue by jxliu1995** [tuna/issues#648]
按照Anaconda 镜像使用帮助内的指引，配置了.condrc文件后，使用conda update conda进行更新，然后再使用conda update --all更新话，会对前一步升级的包进行降级，然后再用conda update conda，又会对这些再进行升级，一直这样反复循环，这是.condrc哪里配置出问题了么？

**Comment by shankerwangmiao** [comment]
有可能是因为我们服务器上数据暂时不一致所致。您只需正常使用即可，不必过多担心。这样的问题在一段时间之后回有所好转。
