### ISSUE TITLE
避免 AUR 出现在 Google 搜索结果？

### ISSUE THREAD

**Issue by lilydjwg** [tuna/issues#649]
[有人](https://www.reddit.com/r/archlinux/comments/dnj0pv/what_is_httpsaurtunatsinghuaeducn_is_it_an/)不小心 Google 到了 TUNA AUR 镜像，然后还登录进去了……

**Comment by scateu** [comment]
赞二位的回复！

**Comment by shankerwangmiao** [comment]
我把 /register 和 /login 302 到了源站，希望能 work around 掉这种尴尬的问题。

**Comment by hexchain** [comment]
可以放一个 /robots.txt 阻止搜索引擎爬取么？现在搜索 `aur site:aur.tuna.tsinghua.edu.cn` 还有不少结果。

**Comment by shankerwangmiao** [comment]
我觉得就先这样吧，懒得动了。是个反代，要加文件的话得多配好多东西呢。

**Comment by lilydjwg** [comment]
啊咧，不是加个 `location = /robots.txt` 就好了么？

**Comment by shankerwangmiao** [comment]
懒癌发作

**Comment by hexchain** [comment]
```
location = /robots.txt {
    default_type text/plain;
    return 200 "User-agent: *\nDisallow: /";
}
```
