### ISSUE TITLE
AOSP下载android与源码，参见文档已经把repo中的 REPO_URL 一行替换成下面的： REPO_URL = 'https://gerrit-google.tuna.tsinghua.edu.cn/git-repo'，为什么repo init的时候还是会提示“fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle fatal: error [Errno 101] Network is unreachable”

### ISSUE THREAD

**Issue by chuanhengf** [tuna/issues#65]
如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写

If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.

提交时，请去掉上面两句，还有这一句。如果不是设立镜像请求，无需按此格式填写。

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by bigeagle** [comment]
请仔细阅读文档。
