### ISSUE TITLE
termux pkg update failed just now

### ISSUE THREAD

**Issue by dobefore** [tuna/issues#650]
today,When I run `pkg update&pkg upgrade` ,I got the failure either in Android 6 or Android 8.several days ago,it worked out just fine!
tested termux version 0.66&0.75 
Thanks in advance!
result in Android 8
`$ pkg update
Ign:1 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Err:2 http://mirrors.tuna.tsinghua.edu.cn/termux stable Release
  403  Forbidden
Ign:3 https://yadominjinta.github.io/files termux InRelease
Get:4 https://yadominjinta.github.io/files termux Release [1714 B]
Ign:5 https://yadominjinta.github.io/files termux Release.gpg
Ign:6 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:7 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:8 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:8 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:10 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:10 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
E: The repository 'http://mirrors.tuna.tsinghua.edu.cn/termux stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'extras/binary-aarch64/Packages' as repository 'https://yadominjinta.github.io/files termux InRelease' doesn't support architecture 'aarch64'
`
result in Android 6
`$ pkg update
Ign:1 https://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Err:2 https://mirrors.tuna.tsinghua.edu.cn/termux stable Release
  403
Ign:3 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-21 science Release
Reading package lists... Done
E: The repository 'https://mirrors.tuna.tsinghua.edu.cn/termux stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by z4yx** [comment]
Termux mirror is closed since we found cases that `apt upgrade` can brick the whole APP. (#646)
It will be remain closed until we solve the problem.

**Comment by dobefore** [comment]
emmm,got it.wish it be ok very soon
