### ISSUE TITLE
TUNA mirror is not listed in the Ubuntu mirror list

### ISSUE THREAD

**Issue by sztsian** [tuna/issues#651]
As the subject, I see TUNA mirror is not listed in the Ubuntu mirror list

https://launchpad.net/ubuntu/+archivemirrors

I am not a Ubuntu user so please involve someone else for verification.

**Comment by xiaoyinl** [comment]
It is listed as Tsinghua University.

https://launchpad.net/ubuntu/+mirror/mirrors.tuna.tsinghua.edu.cn-archive
