### ISSUE TITLE
conda-forge/label/cf201901

### ISSUE THREAD

**Issue by xxp782** [tuna/issues#652]

**Comment by xxp782** [comment]
在anaconda下安装fermitools时根据https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide的安装说明需要conda-forge/label/cf201901的镜像源防止不兼容。请问在清华镜像站中我该怎么做?

**Comment by shankerwangmiao** [comment]
您好，conda-forge 和 fermi 这两个 channel 我们都有镜像，但是该文档中 conda-forge 的 cf201901 这个 label 我们没有镜像。因此您可能需要使用官方来源的 conda-forge 频道，配合我们镜像的 fermi 频道来使用。

**Comment by xxp782** [comment]
谢谢您的回复，我知道了。不好意思打扰了。



---Original---
