### ISSUE TITLE
termux清华软件源出现错误

### ISSUE THREAD

**Issue by feijunhao6937** [tuna/issues#653]
由于termux软件仓库关闭，无法访问，错误代码403
![Screenshot_20191028-193523](https://user-images.githubusercontent.com/35998281/67675516-3cc09c80-f9ba-11e9-8bf7-e7b49488b9ff.jpg)

**Comment by shankerwangmiao** [comment]
我们暂时下线了 termux 软件源，建议您暂时使用官方源。详见 #646
