### ISSUE TITLE
请求支持Clear Linux的源镜像

### ISSUE THREAD

**Issue by ArcheyChen** [tuna/issues#654]
#### 项目名称与简介(Project Intro.)
Clear Linux
一个英特尔开发的高性能Linux发行版
#### 上游地址与镜像方法(How to Mirror)
地址：
http://cdn.download.clearlinux.org/

官方似乎让我参考这个页面：
https://docs.01.org/clearlinux/latest/guides/clear/mixer.html?highlight=mixer
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
（未知）

**Comment by z4yx** [comment]
看了下Clear Linux的软件管理方式，每个版本的更新源都由大量小文件组成（例如 https://cdn.download.clearlinux.org/update/32550/files/），并支持差异更新，与flatpak比较像。根据之前的经验，这种仓库无论是同步还是存储都非常困难，暂时没有能力镜像。
