### ISSUE TITLE
请求支持Ubunt eoan 的binary-arm64的软件包

### ISSUE THREAD

**Issue by lzwgiter** [tuna/issues#655]
#### 项目名称与简介(Project Intro.)
Ubuntu eoan对于arm64的软件包支持
#### 上游地址与镜像方法(How to Mirror)
http://ports.ubuntu.com/dists/eoan/main/binary-arm64/
#### 其他信息(Other)
Ubuntu Server版本号19.10已经对树莓派4有了支持，但是国内没有对arm64软件包的支持，只能以很低的速度去ports.ubuntu.com下载

**Comment by z4yx** [comment]
是这个吗 https://mirror.tuna.tsinghua.edu.cn/ubuntu-ports/dists/eoan/main/binary-arm64/
