### ISSUE TITLE
repo sync同步无法正确完成，出现错误。

### ISSUE THREAD

**Issue by gitQqqHs** [tuna/issues#658]
完全按照aosp帮助页内容步骤做，但是同步出错。
一下是错误提示。
$ repo sync
warning: redirecting to https://aosp.tuna.tsinghua.edu.cn/platform/manifest/
←[1mproject .repo/manifests/←[m
Updating ca78f371..0626d7b9
Fast-forward
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': unable to create directory for .git/refs/heads/default

**Comment by gitQqqHs** [comment]
再次运行脚步，依然出错  错误提示如下
$repo sync
warning: redirecting to https://aosp.tuna.tsinghua.edu.cn/platform/manifest/
←[31merror: .repo/manifests/: contains uncommitted changes←[m

**Comment by shankerwangmiao** [comment]
您注意一下，是否是文件权限的问题？

**Comment by gitQqqHs** [comment]
> 您注意一下，是否是文件权限的问题？

我用的win10，repo文件是有权限执行的。repo文件里面要改的地方也都改了，不知道什么原因

**Comment by gitQqqHs** [comment]
关于这个问题，我按照网上的各种方法都试了一个遍，最终还是没有解决问题。。。不会是要linux系统吧？？

**Comment by shankerwangmiao** [comment]
建议您使用 linux 系统，或者使用 Windows Subsystem for Linux。因为 AOSP 的编译可能也需要在 linux 下完成。

**Comment by gitQqqHs** [comment]
好的，谢谢啦！
