### ISSUE TITLE
Jenkins镜像的问题，插件并不会从镜像站点下载

### ISSUE THREAD

**Issue by LinuxSuRen** [tuna/issues#659]
例如，Jenkins 的更新中心镜像地址为，https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json。但由于类似如下的内容，在安装插件时并不会从镜像地址下载：
`"url":"http://updates.jenkins-ci.org/download/plugins/AnchorChain/1.0/AnchorChain.hpi"`

正确的镜像地址应该是`https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/AnchorChain/1.0/AnchorChain.hpi`

**Comment by shankerwangmiao** [comment]
dup with #581

**Comment by LinuxSuRen** [comment]
[jcli](https://github.com/jenkins-zh/jenkins-cli/pull/222) 可以配置多个镜像地址，并使用镜像来下载 Jenkins 插件（及其依赖）。使用方法如下：
`jcli plugin download hugo`
