### ISSUE TITLE
Melpa & Elpa

### ISSUE THREAD

**Issue by scateu** [tuna/issues#66]
#### 项目名称与简介(Project Intro.)
Melpa全名Milkypostman’s Emacs Lisp Package Archive
是Emacs里一个很重要的软件源
目前国内访问不畅

Elpa貌似是GNU的软件源仓库，但是印象中这个目前没有Melpa活跃。但是建议一并镜像。

#### 上游地址与镜像方法(How to Mirror)

https://melpa.org

镜像方法可以参考国内已有的一个镜像:
http://elpa.emacs-china.org/
它是使用了[Travis-CI来进行镜像](https://travis-ci.org/emacs-china/elpa)，可以参考 

#### 其他信息(Other)
- 镜像大小(Mirror Size): 不知道咋看>_<

水木社区上对于Melpa镜像的[呼唤](http://www.newsmth.net/nForum/article/Emacs/111386?s=111386)

由于刚用emacs不久，请 @MaskRay 和 @yangsheng6810 帮忙勘误及补充。:-)

**Comment by xuchunyang** [comment]
> 上游地址与镜像方法(How to Mirror)

据我所知，上游 ELPA 们目前都还没提供 rsync 地址，有需要搭建镜像的人应该与上游联系，没必要自己想办法同步。

Emacs China ELPA 镜像提供了 rsync 地址（`rsync://elpa.zilongshanren.com/elpa/`），也可以直接用它来作为上游

https://github.com/emacs-china/elpa#制作新的镜像

> 镜像大小(Mirror Size): 不知道咋看>_<

五个常见的镜像一共 536M，上面给出的链接里有每个镜像各自的大小。

**Comment by scateu** [comment]
wow! 刚发现 youdao-dictionary.el 是您写的～～ 最近刚用上～ 整个人都被治愈了～～～

**Comment by bigeagle** [comment]
看了一下，似乎 emacs china 是使用 emacs 来同步的…… 鉴于我对 emacs 的了解仅限于 `C-x C-c`,  暂时直接使用 rsync 吧，未来 @walkerning 和 @scateu  可以负责维护这个镜像 ^_^

**Comment by scateu** [comment]
卧槽.... 
居然能用emacs来同步emacs镜像..........................................vim能么？

(谁打我....

**Comment by bigeagle** [comment]
同步完了已经，@scateu 测试一下？

**Comment by scateu** [comment]
Melpa测试没问题~~

(我装了一个skype.....

其它的我还没有仔细测...

请 @xuchunyang 帮忙验收并提供一个详细的使用指南吧？

**Comment by xuchunyang** [comment]
> 验收

都没问题，而且速度很快。每一个 ELPA 我都试着从上面安装了几个包。

> 详细的使用指南

Emacs China 的使用方法：https://github.com/emacs-china/elpa#使用方法  (可以做为参考，我也可以提供一个 PR，如果有需要的话）

我觉得关键把每个 ELPA 的地址列出来，之后 Emacs 用户应该能明白怎么用：

（根据自己的喜好选择 ELPA）

``` el
(setq package-archives 
      '(("gnu"          . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
        ("melpa"        . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
        ("melpa-stable" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")
        ("org"          . "https://mirrors.tuna.tsinghua.edu.cn/elpa/org/")
        ("marmalade"    . "https://mirrors.tuna.tsinghua.edu.cn/elpa/marmalade/")))
```

假如不清楚需要用哪些 ELPA 的话（然而这其实跟镜像没什么关系，写了出来就不想删了）：
- `gnu` 一般是必备的，其它的 elpa 中的包会依赖 `gnu` 中的包
- `melpa` 滚动升级，收录了的包的数量最大
- `melpa-stable` 依据源码的 Tag （Git）升级，数量比 `melpa` 少，因为很多包作者根本不打 Tag
- `org` 仅仅为了 `org-plus-contrib` 这一个包，org 重度用户使用
- `marmalade` 似乎已经不维护了，个人不推荐

**Comment by scateu** [comment]
好的，我正在加进来~~

另外，我记得有一些用https有问题？ 貌似部分版本的emacs不支持?

**Comment by xuchunyang** [comment]
对，我忘记说了，HTTP 也应该支持。有些 Emacs 在有些环境下没法用 HTTPS

**Comment by scateu** [comment]
见: https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-elpa.md

请看看有哪些要改的，可以直接提交PR。

没问题了再请大鹰 @bigeagle 帮忙更新到主页上吧~~
