### ISSUE TITLE
是否考虑增加QoS策略：优先校内用户使用带宽

### ISSUE THREAD

**Issue by withlqs** [tuna/issues#661]
Sorry没有使用推荐格式，

最近发现mirrors.tuna高峰时段比较慢，查看服务器状态发现带宽使用率较高；是否考虑增加QoS策略，优先满足校内用户的带宽需求？

**Comment by z4yx** [comment]
通常不是带宽问题，而是硬盘速度跟不上。校内可以试试把 mirrors.tuna 换成 neomirrors.tuna
