### ISSUE TITLE
CentOS5 源或更早版本

### ISSUE THREAD

**Issue by JamCh01** [tuna/issues#664]
#### 项目名称与简介(Project Intro.)
CentOS5 或更早
#### 上游地址与镜像方法(How to Mirror)
http://vault.centos.org
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/centos-vault/

**Comment by JamCh01** [comment]
https://mirror.tuna.tsinghua.edu.cn/help/centos/ 所提供的 CentOS5 的源存在问题，是否可以合并？
```
Loaded plugins: fastestmirror
Determining fastest mirrors
https://mirrors.tuna.tsinghua.edu.cn/centos/5/addons/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: addons. Please verify its path and try again
```

**Comment by shankerwangmiao** [comment]
我们与上游保持一致，https://mirrors.tuna.tsinghua.edu.cn/centos/5/ 中不再有有效的数据。详情请见 https://mirrors.tuna.tsinghua.edu.cn/centos/5/readme

**Comment by JamCh01** [comment]
十分感谢~
