### ISSUE TITLE
申请撤销Archlinuxcn源中的Anbox包组

### ISSUE THREAD

**Issue by AkariMarisa** [tuna/issues#665]
最近在使用Archlinuxcn源的anbox-git时遇到问题，首先是Google的protobuf版本错误，后来发现与AUR中的anbox-git版本并不一致。如果这个包的问题一直未修复，请维护人员将此包撤销，感谢！

**Comment by shankerwangmiao** [comment]
您好，我们 archlinuxcn 源是原样提供的。如果您认为该源中有需要进行变化的，请与其维护者取得联系。

**Comment by dotkrnl** [comment]
如 Shanker 所说，我们并非 ArchLinux CN 的维护者。您可以在 https://github.com/archlinuxcn/repo/issues 反馈此问题。
