### ISSUE TITLE
noarch/repodata.json

### ISSUE THREAD

**Issue by sdwrfg** [tuna/issues#666]
请问我要安装fermitools出现了这个错误怎么解决
~$ conda create -n fermi -c conda-forge/label/cf201901 -c fermi fermitools
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/label/cf201901/noarch/repodata.json>
Elapsed: 00:01.384583

The remote server could not find the noarch directory for the
requested channel with url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/label/cf201901

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by shankerwangmiao** [comment]
dup with #652
