### ISSUE TITLE
镜像请求：F-Droid

### ISSUE THREAD

**Issue by linsui** [tuna/issues#668]
#### 项目名称与简介(Project Intro.)

F-Droid
Android 平台上 FOSS（Free and Open Source Software，自由开源软件）应用程序的目录，并提供下载安装支持。

#### 上游地址与镜像方法(How to Mirror)

https://f-droid.org/repo
可通过 rsync 镜像：
https://f-droid.org/en/docs/Running_a_Mirror/
https://gitlab.com/fdroid/pull-mirror-rsyncd

#### 其他信息(Other)
- 镜像大小(Mirror Size): F-Droid 约 50GB，F-Droid Achieve 约 220GB 。Achieve 源镜像意义不大。

**Comment by ZeroAurora** [comment]
嗯还是问一下吧，这个镜像请求有进展吗？

**Comment by z4yx** [comment]
请问用户要怎么使用这个镜像呢？F-Droid有类似应用商店的客户端吗，用户能否配置镜像地址？

**Comment by ZeroAurora** [comment]
> 
> 
> 请问用户要怎么使用这个镜像呢？F-Droid有类似应用商店的客户端吗，用户能否配置镜像地址？

F-Droid 有应用商店客户端（事实上他们更加推荐使用这种方式安装软件）。
向官方提交 issue 可以被收入至官方镜像，用户只需刷新存储库即可自动应用镜像。

手动配置镜像的步骤（未经实验）：
1. 设置-存储库
![图片](https://user-images.githubusercontent.com/25359455/75657607-8a6b4f80-5ca1-11ea-8a34-96c24587a1d2.png)
2. 关闭已有 F-Droid 仓库。
3. 点击右上角 + 添加，也可以使用 F-Droid 打开存储库链接添加。
![图片](https://user-images.githubusercontent.com/25359455/75658383-35c8d400-5ca3-11ea-8ce6-94299ccf98e8.png)

**Comment by z4yx** [comment]
好的，我去跟官方联系rsync密码等事项。

**Comment by z4yx** [comment]
已经可用了，之后我会与上游联系，希望能进入官方列表

**Comment by linsui** [comment]
用 F-Droid 客户端打开此链接 https://mirrors.tuna.tsinghua.edu.cn/fdroid/repo/?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB 或复制此链接后在客户端中添加存储库，可以将此镜像添加为用户镜像。请问是否可以添加此信息为使用帮助？如果直接打开镜像源路径而不输入指纹会添加为单独的存储库。

**Comment by z4yx** [comment]
没问题

**Comment by linsui** [comment]
谢谢。相应的 Archive 库的链接为 https://mirrors.tuna.tsinghua.edu.cn/fdroid/archive?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB

**Comment by ZeroAurora** [comment]
更正一下，不用禁用原有 F-droid 仓库，F-Droid 会自动将新增加的镜像链接识别为用户镜像。

**Comment by ZeroAurora** [comment]
为达到最大速度，需要在镜像配置界面中关闭其他镜像。如图：
![图片](https://user-images.githubusercontent.com/25359455/75834089-fd85da80-5df5-11ea-8bb9-724bafe3459c.png)

**Comment by ZeroAurora** [comment]
更正，经过测试，发现关闭所有其余镜像后速度提升不明显。
另外，仓库的元数据还是会从 F-Droid 官方下载。如果不满意，理论上可以删除官方仓库手动添加。

**Comment by z4yx** [comment]
如果想要更新帮助信息，可直接在 https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-fdroid.md
编辑文件，并提交pull request

**Comment by ZeroAurora** [comment]
试图测试时发现“仓库的元数据还是会从 F-Droid 官方下载”这个结论其实还是偏主见，经过多次测试仍然无法得出，故我不会去更新镜像站帮助。很抱歉打扰了。

**Comment by linsui** [comment]
目前索引文件仍然默认从官方库下载。https://gitlab.com/fdroid/fdroidclient/issues/1708
