### ISSUE TITLE
centos-vault  里面没有大版本号的目录

### ISSUE THREAD

**Issue by gt945** [tuna/issues#673]
centos-vault  没有以大版本号为名的目录，例如6，7， 8；都是具体的小版本号，例如7.0.1406， 7.7.1908
而repo里面的 $releasever 是大版本号，这就导致升级小版本之后每次都得修改repo文件，不太方便
对比 官方网站 是有大版本号的，例如http://vault.centos.org/centos/7/

**Comment by shankerwangmiao** [comment]
TUNA 服务器上的 centos-vault 镜像与 http://vault.centos.org/ 的内容保持一致。因此，您可能需要将路径调整至 http://mirrors.tuna.tsinghua.edu.cn/centos-vault/centos/7/ 。
