### ISSUE TITLE
aosp mirror sync failure: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by i11m20n** [tuna/issues#676]
搭建次级镜像出错

错误信息：
![image](https://user-images.githubusercontent.com/13911593/69898288-617daa80-1392-11ea-9432-9796ef61ddf9.png)

系统环境：
CentOS Linux release 7.7.1908 (Core)
Python：3.7.3 or 2.7.5

**Comment by phy25** [comment]
这边从头开始使用 `repo init -u` 然后 `repo sync` 无法复现此问题。请问您是怎样初始化仓库的？

**Comment by i11m20n** [comment]
初始化仓库步骤：
1. mkdir ~/bin
2. PATH=~/bin:$PATH
3. curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
4. chmod a+x ~/bin/repo
5. mkdir -p ~/workspace/aosp/mirror
6. cd ~/workspace/aosp/mirror
7. repo init -u https://aosp.tuna.tsinghua.edu.cn/mirror/manifest --mirror
8. repo sync

**Comment by phy25** [comment]
无法复现你的问题。如果你的网络环境访问 storage.googleapis.com 或 gerrit.googlesource.com 不稳定，请考虑使用“初始化包”进行初始化：https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/

```shell
/mnt/d/tuna-mirror$ wget https://storage.googleapis.com/git-repo-downloads/repo
‘repo’ saved [29829/29829]

/mnt/d/tuna-mirror$ chmod +x repo
/mnt/d/tuna-mirror$ ls
repo
/mnt/d/tuna-mirror$ ./repo init -u https://aosp.tuna.tsinghua.edu.cn/mirror/manifest --mirror
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (16/16)
remote: Total 16 (delta 3), reused 16 (delta 3)
Unpacking objects: 100% (16/16), done.
From https://gerrit.googlesource.com/git-repo
   34bc571..4997d1c  master     -> origin/master
Get https://aosp.tuna.tsinghua.edu.cn/mirror/manifest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 3480, done.
remote: Compressing objects: 100% (1830/1830), done.
remote: Total 3480 (delta 1075), reused 1696 (delta 490)
Receiving objects: 100% (3480/3480), 791.90 KiB | 94.00 KiB/s, done.
Resolving deltas: 100% (1075/1075), done.
From https://aosp.tuna.tsinghua.edu.cn/mirror/manifest
 * [new branch]      master     -> origin/master

repo mirror has been initialized in /mnt/d/tuna-mirror
/mnt/d/tuna-mirror$ ./repo sync
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent      %L eTfott a lS pe e d
  R e0c e i v e d0  %   X f0e r d     A0v e r a g0e   S p e e0d      T i m e0        T i m0e  - - : - -T:i-m-e  - -C:u-r-r:e-n-t
- - : - - : - -           0                    Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0       %  0T o t a l    0   -%- :R-e-c:e-i-v e-d- :%- -X:f-e-r d- - :A-v-e:r-a-g e   S p e0ed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
     0      0    0        00  - - : - -0: - -    00 : 0 0 : 001   - - : - -0: - -        0  0--:--:--  0:00:01 --:--:--   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0remote: Counting objects: 447, done.      
remote: Counting objects: 718, done.
remote: Compressing objects: 100% (714/714), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 718 (delta 367), reused 68 (delta 1)        /s    --:--:--     0Receiving objects:   0% (1/447)
Receiving objects: 100% (718/718), 282.73 KiB | 253.00 KiB/s, done.
Resolving deltas: 100% (367/367), done.
From https://aosp.tuna.tsinghua.edu.cn/platform/external/google-fonts/dancing-script
 * [new tag]         android-10.0.0_r1 -> android-10.0.0_r1
 * [new tag]         android-10.0.0_r10 -> android-10.0.0_r10
 * [new tag]         android-10.0.0_r11 -> android-10.0.0_r11
 * [new tag]         android-10.0.0_r12 -> android-10.0.0_r12
remote: Total 447 (delta 174), reused 447 (delta 174)
Receiving objects: 100% (447/447), 118.75 KiB | 197.00 KiB/s, done.
 * [new tag]         android-10.0.0_r13 -> android-10.0.0_r13
^Caborted by user
```

**Comment by i11m20n** [comment]
我想搭建次级镜像，由于使用 repo init -u https://aosp.tuna.tsinghua.edu.cn/mirror/manifest --mirror 初始化仓库并 repo sync 会失败，如果使用下载初始化包的方式的话后续命令该怎么敲呢？我已经使用 wget -c https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-latest.tar 下载并解压好了初始化包。

**Comment by shankerwangmiao** [comment]
请参考 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ 的步骤

**Comment by i11m20n** [comment]
> 请参考 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ 的步骤

参考 help 步骤也没看明白使用 aosp-latest.tar 包初始化仓库后如何建立次级镜像...

**Comment by i11m20n** [comment]
> 请参考 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ 的步骤

我的需求是建立 aosp 次级镜像，由于使用 `repo init -u https://aosp.tuna.tsinghua.edu.cn/mirror/manifest --mirror` 初始化仓库后无法 `repo sync` 所以才更换为使用 `初始化包` 方式进行初始化的。

**Comment by shankerwangmiao** [comment]
根据 https://source.android.com/setup/build/downloading#using-a-local-mirror 这篇文档的介绍，如果要创建 mirror 的话，需要在 init 的时候指定 `--mirror` 参数。而 “Notice the `--mirror` flag, which you can specify only when creating a new client”，因此目前来看，使用初始化包，似乎不能达到创建次级镜像的目的。

**Comment by shankerwangmiao** [comment]
我仔细看了一下您的错误信息，我觉得似乎和 repo 命令的版本也许有关。您用的 repo 命令是什么版本的？

**Comment by i11m20n** [comment]
> 我仔细看了一下您的错误信息，我觉得似乎和 repo 命令的版本也许有关。您用的 repo 命令是什么版本的？

![image](https://user-images.githubusercontent.com/13911593/70391141-e741cb80-1a0c-11ea-98ad-495d2ff6fd74.png)

**Comment by shankerwangmiao** [comment]
这个问题我这边复现出来了，似乎是 `repo` 工具的问题。具体原因待查。

**Comment by huiyiqun** [comment]
> 初始化仓库步骤：
> 
> 1. mkdir ~/bin
> 2. PATH=~/bin:$PATH
> 3. curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
> 4. chmod a+x ~/bin/repo
> 5. mkdir -p ~/workspace/aosp/mirror
> 6. cd ~/workspace/aosp/mirror
> 7. repo init -u https://aosp.tuna.tsinghua.edu.cn/mirror/manifest --mirror

虽然和这个问题无关，但是需要注意我们的所有的 git 仓库都是完全原样同步官方源的，这个 mirror/manifest 也是，也就是说这个 mirror 目录下的 url 依然是指向官方源的，你这一通操作下来依然是从 google 的官方源同步的。

> 8. repo sync

**Comment by huiyiqun** [comment]
经调查，我们复现的现场与 git-repo 有关，如果你使用了 tuna 的 git-repo 镜像可能也存在相同问题，修复方式见 [该 cr](https://github.com/tuna/mirror-web/pull/157)，具体的原因是[这一行代码](https://gerrit.googlesource.com/git-repo/+/refs/heads/master/manifest_xml.py#668)

**Comment by i11m20n** [comment]
> 经调查，我们复现的现场与 git-repo 有关，如果你使用了 tuna 的 git-repo 镜像可能也存在相同问题，修复方式见 [该 cr](https://github.com/tuna/mirror-web/pull/157)，具体的原因是[这一行代码](https://gerrit.googlesource.com/git-repo/+/refs/heads/master/manifest_xml.py#668)。

非常感谢，问题解决了。

**Comment by OYLL123** [comment]
问题是怎么解决的呢？可以详细说说吗？我也遇到了同样的问题。

**Comment by i11m20n** [comment]
> 问题是怎么解决的呢？可以详细说说吗？我也遇到了同样的问题。

修复方式见：https://github.com/tuna/mirror-web/pull/157

**Comment by OYLL123** [comment]
可是我的REPO_URL没有以/结尾啊
![2](https://user-images.githubusercontent.com/42767953/88905461-ea821400-d288-11ea-88c8-ac7e57f9322e.png)

**Comment by shankerwangmiao** [comment]
你在同一个 shell 里面执行一下 `echo $REPO_URL`

**Comment by OYLL123** [comment]
![image](https://user-images.githubusercontent.com/42767953/88906071-94fa3700-d289-11ea-9db5-34fdeda80127.png)

**Comment by shankerwangmiao** [comment]
请新开一个 issue，给出完整的复现步骤和出错的信息。

**Comment by yanniwen** [comment]
哈哈，应该是很多人修改 REPO_URL的时候，在最后加了个/，正确的是：'https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'

**Comment by kgbook** [comment]
> 可是我的REPO_URL没有以/结尾啊 ![2](https://user-images.githubusercontent.com/42767953/88905461-ea821400-d288-11ea-88c8-ac7e57f9322e.png)

遇到同样的问题，`REPO_URL` 确认没有问题，目前怀疑是 python版本管理混乱造成的 。

系统信息：
```bash
$ neofetch 
       _,met$$$$$gg.          cory@debian 
    ,g$$$$$$$$$$$$$$$P.       ----------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: X570 AORUS PRO WIFI -CF 
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-20-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 hours, 4 mins 
 $$P      d$'     ,    $$P    Packages: 2840 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Resolution: 2560x1440 
 Y$$.    `.`"Y$$$$P"'         DE: Plasma 5.20.5 
 `$$b      "-.__              WM: KWin 
  `Y$$                        WM Theme: Breeze 
   `Y$$.                      Theme: Breeze 微风 [Plasma], Breeze [GTK2/3] 
     `$$b.                    Icons: breeze [Plasma], breeze [GTK2/3] 
       `Y$$b.                 Terminal: konsole 
          `"Y$b._             Terminal Font: Monospace 12 
              `"""            CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
                              GPU: NVIDIA GeForce GT 1030 
                              Memory: 5517MiB / 32114MiB 

                                                      
                                                      

```

`REPO_URL` 环境变量：
```bash
$ echo $REPO_URL
https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
``` 

repo 依赖 python 工具.
```bash
$ head -n 1 ~/Tools/repo/repo 
#!/usr/bin/env python
```
而本地没有默认的 python, 一开始我通过创建符号链接方式来管理 python 版本，无论是 python2 还是 python3 都会存在该问题。

python 版本：
```bash
$ python2 -V
Python 2.7.18
$ python3 -V
Python 3.9.1
$ cd /usr/bin
$ sudo ln -sf python3 python
```
后来，通过 miniconda 管理 python 版本后问题解决，下载地址： https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/。

我本地 python3 版本是 python3.9，安装 [Miniconda3-py39_4.9.2-Linux-x86_64.sh](https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh)

```bash
$ aria2 https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
$ bash Miniconda3-py39_4.9.2-Linux-x86_64.sh
```

然后创建并激活 python2 环境：
```bash
$ conda create -n python2 python=2.7
$ conda activate python2
```
 python2 环境下再执行 `repo sync` 后就不再报错。

参考信息：https://github.com/tuna/issues/issues/917#issuecomment-673868227
