### ISSUE TITLE
Manjaro 镜像过期

### ISSUE THREAD

**Issue by shaodan** [tuna/issues#677]
根据Manjaro Repository Status of mirrors https://repo.manjaro.org/ 显示
TUNA的镜像最新同步时间是N/A

最近有什么更新或者公告么？

**Comment by shankerwangmiao** [comment]
我们不清楚该状态显示的依据。

**Comment by phy25** [comment]
看起来现在显示的是 20:40，猜测可能是 Manjaro 监测出现了短暂的网络不稳定？
