### ISSUE TITLE
Termux镜像仓库中软件包版本混合疑问

### ISSUE THREAD

**Issue by King-1025** [tuna/issues#679]
Termux镜像仓库：`https://mirrors.tuna.tsinghua.edu.cn/termux/`，好像混合了来自不同仓库的软件包。

下面这2个仓库中的软件包，貌似混在了一起，导致有些安卓平台不兼容（Android 5 & 6），执行更新操作时，好发生莫名其妙的错误。
```
repo1：https://termux.net 
repo2：http://dl.bintray.com/termux/termux-packages-24/
```

这里有一个软件包版本的错误检测报告。
我想这里应该存在一个问题的，希望能够确认一下。

[version-mismatch.txt](https://github.com/tuna/issues/files/3965965/version-mismatch.txt)

**Comment by z4yx** [comment]
现在是从 http://dl.bintray.com/termux/termux-packages-24/ 同步的，不兼容老版本Android
