### ISSUE TITLE
GIT客户端windows版

### ISSUE THREAD

**Issue by istrwei** [tuna/issues#68]
#### https://github.com/git-for-windows/git/releases/download/v2.8.3.windows.1/Git-2.8.3-32-bit.exe
####https://github.com/git-for-windows/git/releases/download/v2.8.3.windows.1/Git-2.8.3-64-bit.exe

#### 其他信息(Other)
- 镜像大小(Mirror Size): 30M

**Comment by bigeagle** [comment]
请问一个30M的东西，为什么需要镜像呢？

**Comment by istrwei** [comment]
@write 这东西已经被墙了，无法下载，你能下？

**Comment by bigeagle** [comment]
被墙的东西太多了…

**Comment by istrwei** [comment]
我就不明白，为什么要屏蔽亚马逊
