### ISSUE TITLE
求镜像debian-ports

### ISSUE THREAD

**Issue by CreeperKong** [tuna/issues#680]
#### 项目名称与简介(Project Intro.)
Debian的非官方移植版
#### 上游地址与镜像方法(How to Mirror)
https://cdimage.debian.org/cdimage/ports
http://ftp.ports.debian.org/debian-ports/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 2TB

**Comment by jiegec** [comment]
dup with #406
