### ISSUE TITLE
cdh镜像地址

### ISSUE THREAD

**Issue by b306pkqcun** [tuna/issues#682]
#### 项目名称与简介(Project Intro.)
 CDH是Apache Hadoop和相关项目的最完整，经过测试的流行发行版。 CDH提供了Hadoop的核心元素 - 可扩展的存储和分布式计算 - 以及基于Web的用户界面和重要的企业功能。 CDH是Apache许可的开放源码，是唯一提供统一批处理，交互式SQL和交互式搜索以及基于角色的访问控制的Hadoop解决方案。
#### 上游地址与镜像方法(How to Mirror)
https://archive.cloudera.com/cdh6/6.1.1/parcels/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
预计共4G

**Comment by phy25** [comment]
不是很确定这个上游是否允许镜像：

> Unless otherwise specified herein, downloads of software from this site and its use are governed by the Cloudera Standard License. By downloading or using this software from this site you agree to be bound by the Cloudera Standard License. If you do not wish to be bound by these terms, then do not download or use the software from this site

https://www.cloudera.com/legal/terms-and-conditions/cloudera-standard-license/cloudera-standard-license-v8-2018-08-14.html

> 5\. License Restrictions. Unless expressly otherwise set forth in this Agreement, Customer will not:
> 
> (c) sell, assign, sublicense, rent, lease, loan, provide, distribute or otherwise transfer all or any portion of the Product;

**Comment by abcfy2** [comment]
ustc有反向代理镜像
