### ISSUE TITLE
希望tuna能够对AdoptOpenJdk设立镜像

### ISSUE THREAD

**Issue by luooyii** [tuna/issues#686]
#### 项目名称与简介(Project Intro.)
AdoptOpenJdk
AdoptOpenJdk是一个社区版的 OpenJDK 二进制包，Java11后，Oracle修改了Oracle Jdk的授权，商业用途免费使用jdk只能转向社区，但是AdoptOpenJdk托管在GitHub release上，国内访问速度十分感人，并且因为链接重定向，一般软件无法重定向断点续传，所以很难下载，希望tuna能够提供AdoptOpenJdk镜像的支持。

#### 上游地址与镜像方法(How to Mirror)
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/

**Comment by Ray-Eldath** [comment]
+1。表示一直都得`https_proxy`代理才能下... 如果服务器上也要配一遍实在太累。希望能镜像adoptopenjdk，或者有其他的OpenJDK distribution的镜像也行.....？比如Zing之类。

**Comment by z4yx** [comment]
已同步到 https://mirrors.tuna.tsinghua.edu.cn/github-release/AdoptOpenJDK
