### ISSUE TITLE
Jenkins 镜像缺少 repomd.xml 

### ISSUE THREAD

**Issue by zbin** [tuna/issues#688]
在yum 进行更新jenkins时提示：

>https://mirror.tuna.tsinghua.edu.cn/jenkins/redhat-stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

经过手动请求，确定缺少文件。

**Comment by phy25** [comment]
http://ftp.osuosl.org/pub/jenkins/redhat-stable/repodata/repomd.xml 404
https://pkg.jenkins.io/redhat/repodata/repomd.xml 200

**Comment by z4yx** [comment]
参见 https://github.com/tuna/issues/issues/308#issuecomment-399024116
