### ISSUE TITLE
Mirror Request KaOS

### ISSUE THREAD

**Issue by empersoprano** [tuna/issues#689]
#### 项目名称与简介(Project Intro.)
[KaOS](https://kaosx.us/)
#### 上游地址与镜像方法(How to Mirror)
`rsync -avO --delete-after kaosx.tk::kaos kaos`
参考自上海大学的的[Reply](https://forum.kaosx.us/d/2164-mirror-for-kaos)
#### 其他信息(Other)
目前没有可用的中国源😂(SHU的镜像目前只能校内访问...)
- 镜像大小(Mirror Size): 
大约10Gb

**Comment by z4yx** [comment]
https://mirrors.tuna.tsinghua.edu.cn/KaOS/
