### ISSUE TITLE
tuna 的 anaconda 镜像是否支持了label功能？

### ISSUE THREAD

**Issue by youkaichao** [tuna/issues#690]
Anaconda cloud 里面的conda-forge 频道 https://anaconda.org/conda-forge/libstdcxx-ng/files 里面，对于 linux-64/libstdcxx-ng-7.3.0-hdf63c60_0.tar.bz2 这个包加上了 broken 的标注，提示这个包是坏的。

但是我在 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/ 这个页面上还是看到了这个包，而且安装的时候还装上了这个包。

是否是因为 tuna没有支持anaconda 的label功能？

**Comment by shankerwangmiao** [comment]
这是不正常的现象。

根据 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json 中的列表，其中仅含有 `libstdcxx-ng-7.3.0-hdf63c60_2.tar.bz2` 和 `libstdcxx-ng-9.2.0-hdf63c60_0.tar.bz2`。TUNA 仅同步一个 channel 中 main 标签下的包。

https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/ 目录下确实存在有  `libstdcxx-ng-7.3.0-hdf63c60_0.tar.bz2` 这个文件。这是因为该包曾经被列入该 channel 的包列表，于是这个文件会被 TUNA 服务器下载下来。但由于目前 `repodata.json` 中并未将这个文件包括进去，所以正常而言 anaconda 安装器并不会理会这个文件的存在性。
