### ISSUE TITLE
Total Mirror Size? Average Storage IOPS?

### ISSUE THREAD

**Issue by minhoryang** [tuna/issues#691]
Hello TUNA, I'm minhoryang from South Korea.
I want to serve a mirror in my university, so I have a question for size of total mirror data.
- Total Mirror Size(镜像大小)? 
- Average Storage IOPS?

Thanks all from TUNA!!

FYI, I also want Mirrorcon2017's PPT files. If someone got these, please help me!

**Comment by phy25** [comment]
TUNA is one of the largest mirror sites in China education network - I am not sure if their IOPS applies to your scale.

You can get their storage stats here: https://mirrors.tuna.tsinghua.edu.cn/status - I guess you don't want to mirror everything as they do either.

**Comment by shankerwangmiao** [comment]
Till now, we are serving about 72.9 TB files. In average, we can see 1.8 kIOps in total on our both servers, and 6kIOps at its peak value.

To reduce the possible IOps, you can omit the rsync service and only provide http(s) service.

**Comment by minhoryang** [comment]
Thanks all! I found the intel all I needed at the status page!
