### ISSUE TITLE
请求镜像 Prometheus 项目

### ISSUE THREAD

**Issue by JerryChin** [tuna/issues#692]
#### 项目名称与简介(Project Intro.)

[Prometheus](https://prometheus.io), a Cloud Native Computing Foundation project, is a systems and service monitoring system. It collects metrics from configured targets at given intervals, evaluates rule expressions, displays the results, and can trigger alerts if some condition is observed to be true.

简言之，该项目是一个基于时序数据库的监控系统。

#### 上游地址与镜像方法(How to Mirror)

我只知道  https://prometheus.io/download/ 可以下载到各系统的 release 文件，不确定如何镜像。

#### 其他信息(Other)

N/A

- 镜像大小(Mirror Size): 

56M 左右

**Comment by z4yx** [comment]
主程序已从 github release 同步到了 https://mirrors.tuna.tsinghua.edu.cn/github-release/prometheus/prometheus/

如需其它工具，请仿照编辑 https://github.com/tuna/tunasync-scripts/blob/master/github-release.py 并提交pull request。
