### ISSUE TITLE
镜像的size是如何获取的

### ISSUE THREAD

**Issue by shitou1992** [tuna/issues#693]
请问同步状态中的镜像的Size是如何获取
发现有些是Unknown的，如果想知道镜像的Size该如何操作

**Comment by shankerwangmiao** [comment]
同步状态中的大小信息，来源较为复杂，多数是从同步日志中抓取而来，还有通过 ZFS 文件系统的统计数据获取。

如果你确实想要知道某镜像的大小，可以直接询问。

**Comment by shitou1992** [comment]
homebrew 大概多大的？

**Comment by z4yx** [comment]
homebrew是一个git仓库，其大小可以直接在上游（github）上查到

例如 https://api.github.com/repos/Homebrew/homebrew-core
中的size（KB）表示当前大小为280MB左右。

**Comment by shitou1992** [comment]
谢谢
