### ISSUE TITLE
镜像请求 Sarasa Gothic

### ISSUE THREAD

**Issue by leoxxx** [tuna/issues#695]
#### 项目名称与简介(Project Intro.)
Sarasa Gothic (更纱黑体 / 更紗黑體 / 更紗ゴシック / 사라사고딕)
This is SARASA GOTHIC, a CJK programming font based on Iosevka and Source Han Sans.
#### 上游地址与镜像方法(How to Mirror)
https://github.com/be5invis/Sarasa-Gothic
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
这个我不知道怎么填写。

**Comment by Colin-XKL** [comment]
额如果你是想解决Github资源在国内下载慢的问题的话可以去了解下 http://www.jsdelivr.com/

**Comment by z4yx** [comment]
我们原则上不镜像github仓库。
如楼上所说，gitlab文件都可以通过 jsdelivr下载。就本字体而言，地址为（最后路径根据实际文件修改）
https://cdn.jsdelivr.net/gh/be5invis/Sarasa-Gothic/sources/noto-sans/noto-sans-bold.ttf

**Comment by z4yx** [comment]
字体release文件已同步，可以在镜像站"获取下载链接”处下载。

**Comment by Lemmingh** [comment]
@Colin-XKL

jsDelivr 对**文件的大小**有严格的[**限制**](https://github.com/jsdelivr/jsdelivr#restrictions)：

* File size < 20 MB.
* Package size < 50 MB.

你可以试试这两个 URL，一定会报错：

* <https://cdn.jsdelivr.net/gh/adobe-fonts/source-han-sans@release/SuperOTC/SourceHanSans.ttc.zip>
    ```
    File size exceeded the configured limit of 20 MB.
    ```

* <https://cdn.jsdelivr.net/gh/adobe-fonts/source-han-sans@release/SuperOTC>
    ```
    Package size exceeded the configured limit of 50 MB. Try https://github.com/adobe-fonts/source-han-sans/tree/release/SuperOTC instead.
    ```

所以，把 jsDelivr 当作下载器**适用范围偏窄**。

---

从另一个角度讲，jsDelivr [原本的意图](https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/)是

> jsDelivr is a free and open source CDN created to **help developers and webmasters**.

> The idea of jsDelivr was ... to offer a super fast and reliable infrastructure that developers and website owners could trust and use.

> jsDelivr is the first CDN to support this kind of functionality. You can load multiple files using a single HTTP request. Similar to combining and minifying js files in your own server.

> jsDelivr has a fully featured API that can be used by developers in their websites

可以总结出：jsDelivr 本来是为了方便前端开发和部署。

所以，借助 jsDelivr 来**下载资源**是对这项服务的**滥用**，尽管没有人会指责你。

---

最后，TUNA 现在已经支持镜像 GitHub releases，这确实是一件好事。

**Comment by Colin-XKL** [comment]
对，to help developers and webmasters,能在github上下载资源的有几个不是开发者或是未来的开发者？对于偶尔需要下载个别资源的用户来说，能通过jsdelivr的赞助商网宿提供的国内cdn节点来临时加速下载，对于国内的互联网环境来说未尝不是一件好事。这一类的用途应该是是jsdelivr项目所期望的。
但同样应该指出的是，有些人利用这种节点为自己个人博客的大量图片提供cdn服务，这种的确会造成滥用，应当抵制。




在 Lemmingh <notifications@github.com>，2020年2月20日 01:06写道：

@Colin-XKL<https://github.com/Colin-XKL>

jsDelivr 对文件的大小有严格的限制<https://github.com/jsdelivr/jsdelivr#restrictions>：

  *   File size < 20 MB.
  *   Package size < 50 MB.

你可以试试这两个 URL，一定会报错：

  *   https://cdn.jsdelivr.net/gh/adobe-fonts/source-han-sans@release/SuperOTC/SourceHanSans.ttc.zip

File size exceeded the configured limit of 20 MB.



  *   https://cdn.jsdelivr.net/gh/adobe-fonts/source-han-sans@release/SuperOTC

Package size exceeded the configured limit of 50 MB. Try https://github.com/adobe-fonts/source-han-sans/tree/release/SuperOTC instead.



所以，把 jsDelivr 当作下载器适用范围偏窄。

________________________________

从另一个角度讲，jsDelivr 原本的意图<https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/>是

jsDelivr is a free and open source CDN created to help developers and webmasters.

The idea of jsDelivr was ... to offer a super fast and reliable infrastructure that developers and website owners could trust and use.

jsDelivr is the first CDN to support this kind of functionality. You can load multiple files using a single HTTP request. Similar to combining and minifying js files in your own server.

jsDelivr has a fully featured API that can be used by developers in their websites

可以总结出：jsDelivr 本来是为了方便前端开发和部署。

所以，借助 jsDelivr 来下载资源是对这项服务的滥用，尽管没有人会指责你。

________________________________

最后，TUNA 现在已经支持镜像 GitHub releases，这确实是一件好事。
