### ISSUE TITLE
scoop

### ISSUE THREAD

**Issue by wzy2006** [tuna/issues#698]
#### 项目名称与简介(Project Intro.)
scoop
强大的windows上的包管理器
基于powershell5+
包更新及时，而且位置集中在一个文件夹内，比起chocalate，便于管理
#### 上游地址与镜像方法(How to Mirror)
main: 程序员使用的开源程序包：https://github.com/ScoopInstaller/Main
extra: 其他扩展程序包: https://github.com/lukesampson/scoop-extras
还有其他官方库可以到https://github.com/lukesampson/scoop的readme中查看
#### 其他信息(Other)
- 镜像大小(Mirror Size):  未知

**Comment by ZeroAurora** [comment]
个人认为这个镜像没有实际意义，因为这些仓库只是存储配置文件，真正的二进制文件还是要到配置文件指向的地方下载

**Comment by wzy2006** [comment]
同意

**Comment by z4yx** [comment]
scoop缺少像homebrew-bottles那样的集中存储，因此镜像意义不大

**Comment by LittleboyHarry** [comment]
我还是希望 tuna 考虑一下改善 scoop 国内体验，可以帮助很多条件不好的计算机大一新生和IT初学者。

国内每年新人普遍都会去买 Windows 笔记本，本来没有 scoop 手动下载程序包安装并配置环境就已经很劝退。再加上最近网络条件愈加严格，很多新生上来编程和软件实验课不会安装就更懵了。

scoop 有 bucket manifest 可以用来自动检测更新，而且大多数包多托管在 github releases 下载。即便做不到集中存储，我希望把常用的一些软件镜像过来也不错：adoptopenjdk、blender、cmake、docker、mysql、listary、nginx、python、Sysinternals 等等。

最近在构思创作新生攻略时，想到写手动 Windows 环境软件安装部分真是吐了！真心希望能让 scoop 软件推广在国内蔚然成风，降低学习者负担、减少不必要的麻烦，谢谢！

**Comment by DaZui** [comment]
我尝试将一部分 Scoop 软件包中的软件替换为了 tuna 的镜像。

Main 仓库中替换了 cmder 和 git：https://github.com/Tuna-Scoop/Main

Extras 仓库中替换了 VSCodium、VLC 和 anaconda3：https://github.com/Tuna-Scoop/scoop-extras

欢迎大家一同试着维护。
