### ISSUE TITLE
Docker APT出错：Writing more data than expected (4815 > 3203)

### ISSUE THREAD

**Issue by celeron533** [tuna/issues#70]
Ubuntu 16.04 x64 Server
OS安装在Virtualbox虚拟机中，且执行的是全新安装。

Error message when executing `apt-get update`:

> E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo/dists/ubuntu-xenial/main/binary-amd64/Packages  Writing more data than expected (4815 > 3203)
> E: Some index files failed to download. They have been ignored, or old ones used instead.

官方源和Tuna的ubuntu-xenial/main/binary-amd64/Packages文件大小都是4815，等待24小时后，apt-get clean 后错误依旧。
将 /etc/apt/sources.list.d/docker.list 里的deb源重置为docker官方则没有此问题。

**Comment by bigeagle** [comment]
的确比较奇怪，我们下载下来的索引文件sha256校验不通过，所以一直没有成功。

**Comment by bigeagle** [comment]
重新同步了一遍，应该可以用了，但是docker官方仓库仍然有问题，问题已反馈上游。 docker/docker#23396

**Comment by celeron533** [comment]
现在可以正常`apt-get update`了，非常感谢！
