### ISSUE TITLE
请求 镜像  ffmpeg ，磁盘大小不超过 200MB

### ISSUE THREAD

**Issue by handashuai** [tuna/issues#700]
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
鉴于 FFMpeg 总体大小过小，且已经包括在诸发行版的软件仓库内，因此不再单独镜像。

**Comment by amorphobia** [comment]
是否可以将 https://github.com/GyanD/codexffmpeg 添加到 github-release 镜像列表？这是 ffmpeg 官方下载页面所指向的预编译二进制发行版本，对于Windows用户还是有需要的，谢谢
