### ISSUE TITLE
镜像请求：闭社(thu.closed.social)

### ISSUE THREAD

**Issue by OmmyZhang** [tuna/issues#702]
#### 项目名称与简介(Project Intro.)
闭社，一个基于mastodon的分布式高校封闭平台，目前只维护了清华站
项目地址 https://github.com/closed-social/mastodon/

#### 上游地址与镜像方法(How to Mirror)
https://thu.closed.social
简单反向代理，或做一些缓存

#### 其他信息(Other)
主要是为了方便访问希望有一个校园网的镜像。
（画风好像和tuna一般说的镜像不太一样，不过反正都叫镜像，我来提个issue试试）

**Comment by shankerwangmiao** [comment]
您好，TUNA 镜像站一般不提供反向代理，也不对含有用户生成内容的资源提供服务。
