### ISSUE TITLE
hackage同步失败

### ISSUE THREAD

**Issue by Saul-Mirone** [tuna/issues#703]
hackage同步失败，导致使用stack安装，更新包时报错：

```
Verification error: Invalid hash for <repo>/01-index.tar.gz
```

**Comment by z4yx** [comment]
最近一段时间的同步日志都是这样

    skip checking
    Downloading index...
    cleaning up
    rm: cannot remove '/tmp/hackage_local_pklist_1.list': No such file or directory
    rm: cannot remove '/tmp/hackage_remote_pklist_1.list': No such file or directory

随后就失败了

**Comment by z4yx** [comment]
调整了一下网络，麻烦试试现在是否正常了。

**Comment by chenyulue** [comment]
Hackage, Stackage同步同样失败

**Comment by shankerwangmiao** [comment]
已经重新同步了。
