### ISSUE TITLE
OSX上 pip 版本只到9.x

### ISSUE THREAD

**Issue by youkaichao** [tuna/issues#704]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64/  这里的pip版本只到9 [哭泣]

**Comment by phy25** [comment]
你好，源站如此：https://repo.continuum.io/pkgs/free/osx-64/

**Comment by z4yx** [comment]
free channel已经弃用了，新版pip在 main 中

https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/
