### ISSUE TITLE
request to mirror Qemu

### ISSUE THREAD

**Issue by x48Jason** [tuna/issues#707]
#### 项目名称与简介(Project Intro.)
Qemu is the most famous machine emulator and virtualizer in the open source community. It can be used to emulate a lot of virtual machine on one physical machine. It plays an important role in the cloud computing industry. A lot of cloud vendors use Qemu to construct cloud infrastructure.

#### 上游地址与镜像方法(How to Mirror)

git clone git://git.qemu.org/qemu.git
git clone https://git.qemu.org/git/qemu.git
git clone https://github.com/qemu/qemu.git

#### 其他信息(Other)
- 镜像大小(Mirror Size): 400MB

**Comment by z4yx** [comment]
已添加
