### ISSUE TITLE
Clojars mirror synchronization failed

### ISSUE THREAD

**Issue by uncleshushu** [tuna/issues#709]
It seems that the Clojars mirror hasn't been synchronized for a while:

![image](https://user-images.githubusercontent.com/15453351/74661239-84ba3800-51d2-11ea-9a63-0ee47a326808.png)
 
For example, the [latest version of cheshire](https://clojars.org/cheshire) is not synchronized:

Clojars:
![image](https://user-images.githubusercontent.com/15453351/74661790-9bad5a00-51d3-11ea-9883-a03dc2110e7c.png)

Tuna:
![image](https://user-images.githubusercontent.com/15453351/74661715-728cc980-51d3-11ea-9c87-dadab2f9ce46.png)

**Comment by shankerwangmiao** [comment]
https://github.com/clojars/clojars-web/issues/735

**Comment by z4yx** [comment]
Problem solved.
