### ISSUE TITLE
请求增加Void Linux

### ISSUE THREAD

**Issue by Asternmerr642** [tuna/issues#713]
#### 项目名称与简介(Project Intro.)
Void是基于Linux内核独立开发的通用操作系统。其特色在于一份二进制/源代码混合式包管理系统，这使得用户能快速安装、更新、移除软件，或者是借助XBPS源代码集合从源码直接生成软件。该发行的其他特性包括对Raspberry Pi单板计算机（armv6和armv7）的支持，每日更新的滚动式开发模式，对OpenBSD旗下LibreSSL软件的集成，以及名为runit的原生init系统。 

Void Linux目前没有国内源，所以希望tuna能增加Void Linux源

#### 上游地址与镜像方法(How to Mirror)

http://alpha.de.repo.voidlinux.org/ 或 http://alpha.us.repo.voidlinux.org/

其他上游地址参考：https://docs.voidlinux.org/xbps/repositories/mirrors/index.html

#### 其他信息(Other)

- 镜像大小(Mirror Size): 738GB
- 官网(Website): https://voidlinux.org/

**Comment by z4yx** [comment]
完成 https://mirrors.tuna.tsinghua.edu.cn/voidlinux/
