### ISSUE TITLE
镜像文件列表：过长的文件名被截断

### ISSUE THREAD

**Issue by suokunlong** [tuna/issues#714]
例如，这个页面中：https://mirrors.tuna.tsinghua.edu.cn/libreoffice/libreoffice/stable/6.3.5/rpm/x86_64/, 如果文件名过长（超过50个字符），当前会被截断并显示为“..>”。建议你们调整过来显示为完整文件名。

在apache中，Directory 下添加  IndexOptions NameWidth=*  选项可以让列宽根据文件名长度自动调整，nginx 下我不确定应该如何设置。

**Comment by z4yx** [comment]
fancy-index 设计如此吧，为了排版好看

**Comment by suokunlong** [comment]
应该有办法既使用 fancy-index 的效果，也能完整显示文件名吧？否则，好看不中用的话还不如让它难看点呢。
我说的不中用，是说我在那个页面想要下载zh_CN语言包的话翻来覆去找不见，因为被截断了，只能在可能的范围内一个一个把鼠标放上去通过弹出的提示信息中判断。

**Comment by scateu** [comment]
临时先用w3m/lynx之类试试？ 

我记得这个fancy-index有一个策略，对文本浏览器换一种显示方法

-- 
Kang

**Comment by shankerwangmiao** [comment]
那不是 fancy-index 的策略，是我的策略

**Comment by scateu** [comment]
赞一个!

-- 
Kang

**Comment by shankerwangmiao** [comment]
目前无法做到不截断文件名，已经增加显示的文件名长度。

**Comment by suokunlong** [comment]
多谢！
