### ISSUE TITLE
拉取 Cocoapods git 失败

### ISSUE THREAD

**Issue by guloooo128** [tuna/issues#715]
git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master
Cloning into 'master'...
remote: Counting objects: 3838276, done.
remote: Compressing objects: 100% (1153706/1153706), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

试了各种方法都不行，不支持以ssh方式pull吗？

**Comment by shankerwangmiao** [comment]
我们的 git 服务仅支持使用 http(s) clone，因为它是只读的。errno 54 是 Connection reset by peer， 这意味着您和镜像站之间的网络连接存在障碍。在这种情况下，建议您自行排查网络连接是否正常。
