### ISSUE TITLE
VirtualBox APT源地址改变

### ISSUE THREAD

**Issue by zzhiyi** [tuna/issues#716]
原apt地址https://download.virtualbox.org/virtualbox/apt/
新apt地址https://download.virtualbox.org/virtualbox/debian/, 并且增加了很多发行版，https://download.virtualbox.org/virtualbox/debian/dists/

**Comment by shankerwangmiao** [comment]
我们的确是从您所指的路径下载的。详见 https://github.com/tuna/tunasync-scripts/blob/94f3b4c1cdd4da24e9fd5d7b2acaed40481a8359/virtualbox.sh#L57
