### ISSUE TITLE
希望增加anaconda中的c4aarch64和archiarm

### ISSUE THREAD

**Issue by shitou1992** [tuna/issues#717]
#### 上游地址与镜像方法(How to Mirror)
https://anaconda.org/archiarm
https://anaconda.org/c4aarch64

#### 其他信息(Other)
- 镜像大小(Mirror Size):
大小未知

**Comment by z4yx** [comment]
这两个是什么项目的channel？如果只是个人开发者打的几个包，我们觉得镜像的意义不大。

**Comment by shitou1992** [comment]
问题已解决，通过pip可以安装，这个是arm架构的两个项目
