### ISSUE TITLE
Anaconda 镜像使用帮助提供的.condarc修改方式可能导致package解决方案冲突

### ISSUE THREAD

**Issue by GoingTime** [tuna/issues#719]
(py37) C:\Users\Timei>conda install pyqt
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  - defaults::pandoc-2.2.3.2-0, https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1
  - defaults::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  - defaults::defusedxml-0.6.0-py_0, defaults::pandoc-2.2.3.2-0, https://repo.anaconda.com/pkgs/main/noarch::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1
  - defaults::defusedxml-0.6.0-py_0, defaults::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  - defaults::defusedxml-0.6.0-py_0, defaults::imagesize-1.2.0-py_0, defaults::pandoc-2.2.3.2-0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1
  - defaults::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  - defaults::imagesize-1.2.0-py_0, defaults::pandoc-2.2.3.2-0, https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::pathtools-0.1.2-py_1
  - defaults::imagesize-1.2.0-py_0, defaults::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  - defaults::pathtools-0.1.2-py_1, https://repo.anaconda.com/pkgs/main/noarch::defusedxml-0.6.0-py_0, https://repo.anaconda.com/pkgs/main/noarch::imagesize-1.2.0-py_0, https://repo.anaconda.com/pkgs/main/win-64::pandoc-2.2.3.2-0
  ... and othedone

**Comment by z4yx** [comment]
尝试安装pyqt没有发现问题

```
>conda create --show-channel-urls -n test python==3.7 pyqt
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\zyx\Anaconda3\envs\test

  added / updated specs:
    - pyqt
    - python==3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2019.11.28-py37_0
  icu                pkgs/main/win-64::icu-58.2-ha66f8fd_1
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_4
  pip                pkgs/main/win-64::pip-20.0.2-py37_1
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  python             pkgs/main/win-64::python-3.7.0-hea74fb7_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  setuptools         pkgs/main/win-64::setuptools-45.2.0-py37_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3


Proceed ([y]/n)?                                                        
```

**Comment by z4yx** [comment]
另外你贴的日志中显示的url还是anaconda的，是否配置未生效？

**Comment by GoingTime** [comment]
`(base) C:\Users\Timei>conda update spyder
Collecting package metadata (current_repodata.json): done
Solving environment: -
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/main/win-64::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/win-64::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/main/win-64::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.tempfile-1.0-py_1, defaults::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/main/win-64::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.tempfile-1.0-py_1, defaults::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.tempfile-1.0-py_1, defaults::backports.weakref-1.0.post1-py_1, defaults::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::backports.weakref-1.0.post1-py_1, defaults::conda-package-handling-1.6.0-py37h62dcd97_0, https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  - defaults::conda-package-handling-1.6.0-py37h62dcd97_0, defaults::m2w64-gcc-libs-core-5.3.0-7, https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1
  - defaults::m2w64-gcc-libs-core-5.3.0-7, https://repo.anaconda.com/pkgs/main/noarch::backports.tempfile-1.0-py_1, https://repo.anaconda.com/pkgs/main/noarch::backports.weakref-1.0.post1-py_1, https://repo.anaconda.com/pkgs/main/win-64::conda-package-handling-1.6.0-py37h62dcd97_0
  ... and othe\

Updating spyder is constricted by

anaconda -> requires spyder==3.3.6=py37_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

## Package Plan ##

  environment location: D:\ProgramData\Anaconda3

  added / updated specs:
    - spyder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backports.functools_lru_cache-1.6.1|             py_0          11 KB  defaults
    conda-4.8.2                |           py37_0         2.8 MB  defaults
    future-0.18.2              |           py37_0         656 KB  defaults
    ------------------------------------------------------------
                                           Total:         3.5 MB

The following packages will be UPDATED:

  backports.functoo~                               1.5-py_2 --> 1.6.1-py_0
  conda                                       4.7.12-py37_0 --> 4.8.2-py37_0
  future                                      0.17.1-py37_0 --> 0.18.2-py37_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(base) C:\Users\Timei>conda info

     active environment : base
    active env location : D:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Timei\.condarc
 populated config files : C:\Users\Timei\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : D:\ProgramData\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\Timei\.conda\pkgs
                          C:\Users\Timei\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\Timei\.conda\envs
                          C:\Users\Timei\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False`

**Comment by GoingTime** [comment]
切换到default或者只保留main和free不会出现警告

**Comment by z4yx** [comment]
如果用`conda create -n testenv <package>`这样创建新环境会报错吗？

**Comment by GoingTime** [comment]
不是创建环境，是更新或安装package

**Comment by z4yx** [comment]
可以测试下创建环境。因为不知道跟你已有的包的版本有没有关系。

**Comment by GoingTime** [comment]
创建新环境时未出现问题

**Comment by z4yx** [comment]
那我怀疑你已有的包的版本有关系，具体原因我不清楚，我自己也不是anaconda用户😂，帮不上你了。
