### ISSUE TITLE
Linuxbrew安装过程中使用镜像

### ISSUE THREAD

**Issue by OuSatoru** [tuna/issues#720]
Linuxbrew使用帮助中已经是安装好了brew后再使用tuna镜像，但是安装brew的过程中还是使用的原镜像，需要下载两次portable-ruby，以及git clone巨大的linuxbrew-core，能否有安装时就使用镜像的方法？

**Comment by z4yx** [comment]
你可以这样试一下：

1. 下载 https://raw.githubusercontent.com/Linuxbrew/install/master/install-ruby
2. 将其中 `https://homebrew.bintray.com/bottles-portable-ruby/` 换为 `https://mirrors.cloud.tencent.com/homebrew-bottles/bottles-portable-ruby/`
3. 运行 `./install-ruby` 安装 portable ruby
1. 下载 https://raw.githubusercontent.com/Linuxbrew/install/master/install
2. 将其中 `https://github.com/Homebrew/brew` 换为 `https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git`
3. 运行 `./install` 安装 brew

**Comment by OuSatoru** [comment]
@z4yx 谢谢，安装portable-ruby和"brew"都正常，但是进行到"==> Tapping homebrew/core" 这步的时候还是使用的原repo，在脚本中搜索"ohai"也没有这句话，请教一下怎么做？

**Comment by z4yx** [comment]
到那一步是brew应该已经安装好了，可以按照镜像站上的帮助去替换core的git地址，然后正常使用

**Comment by OuSatoru** [comment]
谢谢，安装成功了，直接运行帮助命令会提示linuxbrew-core目录不存在，先把brew添加进PATH，执行`git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/linuxbrew-core.git /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core`，然后再`git -C "$(brew --repo homebrew/core)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/linuxbrew-core.git`，最后执行一下./install就可以看到成功结果

**Comment by z4yx** [comment]
不错不错，这个经验值得分享。

**Comment by jiegec** [comment]
@OuSatoru 不妨把这一部分写一个帮助放到 tuna/mirror-web 中？
