### ISSUE TITLE
希望能够建立AdoptOpenJDK各个版本的镜像

### ISSUE THREAD

**Issue by RobberPhex** [tuna/issues#723]
#### 项目名称与简介
AdoptOpenJDK

AdoptOpenJdk是一个社区版的 OpenJDK 二进制包，Java11后，Oracle修改了Oracle Jdk的授权，商业用途免费使用jdk只能转向社区，但是AdoptOpenJdk托管在GitHub release上，国内访问速度十分感人，并且因为链接重定向至S3，很难下载。
#### 其他信息(Other)

- 以下为各个版本的二进制仓库

  - [Java8](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/)
  - [Java9](https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/)
  - [Java10](https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/)
  - [Java11](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/)
  - [Java12](https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/)
  - [Java13](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/)

每个仓库的最新release下，有附件，就是各个平台的二进制包。
希望能够镜像最新的release下的附件；如果空间允许，也请保留历史版本。

- 镜像大小(Mirror Size): 

每个release约2G，只保留每个版本的最近一次发布，为6个。
共12G

**Comment by phy25** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/AdoptOpenJDK/

**Comment by RobberPhex** [comment]
> 
> 
> https://mirrors.tuna.tsinghua.edu.cn/github-release/AdoptOpenJDK/

这个里面只有OpenJ9的Java8版本，版本还是非常不全。

**Comment by z4yx** [comment]
已添加上述仓库，等待下载。

**Comment by RobberPhex** [comment]
> 
> 
> 已添加上述仓库，等待下载。

我看了下，还是只有openj9，没有hotspot：
![image](https://user-images.githubusercontent.com/1926185/75603130-a4bcf600-5b06-11ea-8e11-ff34277b1452.png)

**Comment by z4yx** [comment]
github在文件托管在aws上，国内下载速度较慢，请耐心等待一段时间。

**Comment by RobberPhex** [comment]
> 
> 
> github在文件托管在aws上，国内下载速度较慢，请耐心等待一段时间。

现在的镜像还是有问题，比如 <https://mirrors.tuna.tsinghua.edu.cn/github-release/AdoptOpenJDK/openjdk11-binaries/> 下就只有openj9的包。

请重新打开此issue，等同步完成后，这个issue才能算完成。

**Comment by z4yx** [comment]
现在已经同步完了，你能具体说明要哪个文件吗

**Comment by RobberPhex** [comment]
> 
> 
> 现在已经同步完了，你能具体说明要哪个文件吗

现在看来，所有jdk11的hotspot版本都没有，比如官网上的：
<https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10.msi>

**Comment by z4yx** [comment]
你这个链接是哪里找的，我从 https://github.com/AdoptOpenJDK/openjdk11-binaries/releases 中没有看到这个版本

**Comment by phy25** [comment]
GitHub 默认会把 pre-release 置顶，他们所有的 nightly 都标记了，导致这个版本的确不好找：
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases?after=jdk11u-2019-01-22-14-45

另外看起来官网会直接生成指向 GitHub releases 的下载链接：https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot

**Comment by z4yx** [comment]
我明白了，那我在脚本中过滤掉 pre-release 吧，感谢 @phy25

**Comment by RobberPhex** [comment]
> 
> 
> 我明白了，那我在脚本中过滤掉 pre-release 吧，感谢 @phy25

还是不行，比如`AdoptOpenJDK/openjdk11-binaries`，通过`/releases/latest`拿到的tag是`jdk-11.0.6+10_openj9-0.18.1`，但是如果要取hotspot的话，tag应该是[jdk-11.0.6+10](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.6%2B10/)

**Comment by RobberPhex** [comment]
目前看起来比较靠谱的办法是AdoptOpenJDK的API了。<https://api.adoptopenjdk.net/>

**Comment by z4yx** [comment]
所以11版本是不是这里面的文件就够了
https://api.adoptopenjdk.net/v2/latestAssets/releases/openjdk11

**Comment by phy25** [comment]
我看了眼同步程序，似乎已经过滤了 pre-release，所以根本问题在于需要把他们所有的 release tags 都拉下来而不是只有最新的版本。不知道全拉下来压力会有多大。

**Comment by RobberPhex** [comment]
> 
> 
> 所以11版本是不是这里面的文件就够了
> https://api.adoptopenjdk.net/v2/latestAssets/releases/openjdk11

是的

**Comment by z4yx** [comment]
好的，那我们就不用github-release同步脚本了，需要新开发一个，从AdoptOpenJDK的API来取文件。@RobberPhex  有兴趣写这个脚本吗，可以参考现有的脚本。

**Comment by RobberPhex** [comment]
> 
> 
> 好的，那我们就不用github-release同步脚本了，需要新开发一个，从AdoptOpenJDK的API来取文件。@RobberPhex 有兴趣写这个脚本吗，可以参考现有的脚本。

脚本大概就这样：
```shell
# 参数为版本，比如8,11等
function downloadRelease() {
  TMP_DIR=$(mktemp -d)
  DIR="adoptopenjdk$i"
  curl -s "https://api.adoptopenjdk.net/v2/latestAssets/releases/openjdk$1" | \
   jq -r '.[]| [.binary_link, .binary_name]| @tsv' | \
   while IFS=$'\t' read -r link filename; do
     echo $filename $link
     curl -sL "$link" -o "$TMP_DIR/$filename"
   done
   mv "$DIR" "$DIR.toremove"
   mv "$TMP_DIR" "$DIR"
   rm -rf "$DIR.toremove"
}

for i in 8 11 13;
do
  downloadRelease $i
done
```
但是我不知道提交到哪儿。

**Comment by z4yx** [comment]
赞，你可以给 https://github.com/tuna/tunasync-scripts/ 提交 pr
存放的文件的目录由 `$TUNASYNC_WORKING_DIR` 环境变量传入，最好能在下面按照版本号和系统建立子目录，以便用户下载。

**Comment by z4yx** [comment]
已用新脚本同步完 https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/

**Comment by fengzhao** [comment]
AdoptOpenJDK镜像为什么删了呢？

**Comment by shankerwangmiao** [comment]
> AdoptOpenJDK镜像为什么删了呢？

请参考 https://mirrors.tuna.tsinghua.edu.cn/news/rename-adoptopenjdk-to-adoptium/
