### ISSUE TITLE
openwrt snapshots 无法打开

### ISSUE THREAD

**Issue by q623928815** [tuna/issues#724]
#### 发生了什么（What happened）
openwrt snapshots 无法打开
#### 如何重现（How to reproduce it）
openwrt镜像，点击Snapshot download
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by phy25** [comment]
https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/ 404 Not Found

Name | Last Update | Upstream | Status | Size
-- | -- | -- | -- | --
openwrt | 2020-02-28 18:33 | rsync://downloads.lede-project.org/downloads/ | syncing | 478.89G

——🤖

**Comment by z4yx** [comment]
见 #619 
“由于 snapshots 是每日更新的，每日的同步数据量较大，因此该目录被过滤掉了。”
