### ISSUE TITLE
增加 glibc 和 binutils-gdb 的 git 镜像

### ISSUE THREAD

**Issue by happyaron** [tuna/issues#726]
#### 项目名称与简介(Project Intro.)

- glibc, GNU C Library
- binutils-gdb

#### 上游地址与镜像方法(How to Mirror)
- glibc: https://sourceware.org/git/?p=glibc.git
   git://sourceware.org/git/glibc.git
- binutils-gdb: https://sourceware.org/git/?p=glibc.git
   git://sourceware.org/git/binutils-gdb.git

#### 镜像大小(Mirror Size)
本地 .git 文件夹大小：
- glibc: 193MiB
- bintuils-gdb: 370MiB

**Comment by z4yx** [comment]
Done
