### ISSUE TITLE
linux-xlnx.git

### ISSUE THREAD

**Issue by jiegec** [tuna/issues#727]
#### 项目名称与简介(Project Intro.)

The official Linux kernel from Xilinx

#### 上游地址与镜像方法(How to Mirror)

https://github.com/xilinx/linux-xlnx

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
参加 https://github.com/tuna/issues/issues/475#issuecomment-477826960
