### ISSUE TITLE
404 at /qt/archive/qt/4.8

### ISSUE THREAD

**Issue by xiaofighting** [tuna/issues#731]
下载qt出现404错误，下载不成功

下载qt及qtcreator成功

- 操作系统（OS Version）：Win10
- 浏览器（如果适用）（Browser version, if applicable）：火狐浏览器
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
请选用 https://mirrors.tuna.tsinghua.edu.cn/qt/official_releases/qt/ 里面提供的版本，或者在首页中“获取下载链接”中查找所需的版本。
