### ISSUE TITLE
404 at /anaconda/pkgs/free/win-64/repodata.json%3E

### ISSUE THREAD

**Issue by ChocolateDave** [tuna/issues#732]
似乎从2020年2月中开始，tuna的镜像源就无法有效连接上了，请问是否是镜像源已经失效了？

# Error info:

Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64'

**Comment by phy25** [comment]
您的网络环境是？请尝试 traceroute？

**Comment by shankerwangmiao** [comment]
可以确认 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/repodata.json 是存在的，没有问题。
