### ISSUE TITLE
404 at /mariadb/mariadb-10.1.43/

### ISSUE THREAD

**Issue by XindongSu** [tuna/issues#735]
#### 发生了什么（What happened）

mariadb 10.1.43 不存在

#### 期望的现象（What you expected to happen）

按maraidb官网指，存在10.1.43此版本

#### 如何重现（How to reproduce it）

直接浏览器访问
https://mirrors.tuna.tsinghua.edu.cn/mariadb/mariadb-10.1.43/
或通过rsync访问
rsync://mirrors.tuna.tsinghua.edu.cn/mariadb/mariadb-10.1.43

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
我们的同步上游是 rsync://rsync.osuosl.org/mariadb/
它们并没有此版本，估计是小版本号只保留最新的。你可以使用 mariadb-10.1.44
