### ISSUE TITLE
404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by 863zq** [tuna/issues#736]
#### 发生了什么（What happened）
打不开https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/

#### 期望的现象（What you expected to happen）
需要做个镜像

#### 如何重现（How to reproduce it）
点链接就能重现

#### 您的环境（Environment）
- 操作系统（OS Version）：OpenWrt R9.12.31 / LuCI Master (git-19.338.43082-9e87e69)
- 浏览器（如果适用）（Browser version, if applicable）：chrome
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
see #619
