### ISSUE TITLE
建议修改Jenkins镜像的update-center.json

### ISSUE THREAD

**Issue by fzyzcjy** [tuna/issues#737]
#### 发生了什么（What happened）
使用jenkins镜像时（将jenkins的“升级站点”设置为 https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json ），只能使得jenkins加速下载这个json文件，而实际上下载插件时还是回到了原站而非tuna下载。原因是，json中所有的链接都是指向源站的。

因此，希望自动修改update-center.json，自动替换所有的`jenkins-ci.org/download/plugins`。比如：原json中有：

```
..."url":"http://updates.jenkins-ci.org/download/plugins/Surround-SCM-plugin/1.12/Surround-SCM-plugin.hpi"...
```

自动批量替换为

```
..."url":"http://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/Surround-SCM-plugin/1.12/Surround-SCM-plugin.hpi"...
```

#### 期望的现象（What you expected to happen）
N/A

#### 如何重现（How to reproduce it）
N/A

#### 其他事项（Anything else we need to know）
N/A

#### 您的环境（Environment）
- 操作系统（OS Version）：N/A
- 浏览器（如果适用）（Browser version, if applicable）：N/A
- 其他（Others）：N/A

**Comment by shankerwangmiao** [comment]
感谢您的建议，但是 TUNA 作为镜像网站，其中数据是依原样提供，一般不作修改。您所说的 TUNA 镜像中的索引文件地址指向的是官方服务器，造成实际下载的来源并非 TUNA 服务器。该问题或许是存在的，但我们目前无能为力，因为我们不能修改这个索引文件，特别是在我们还被列入 Jenkins 官方的镜像服务器列表的情况下。据我们所知，Jenkins 的索引文件所指地址，其实是其官方维护的一个分发器。它会根据访问者的地域，结合其官方对各镜像站的监测结果，将用户重定向至合适的镜像。我们简单进行了测试，发现中国境内的请求并没有被重定向至 TUNA 的服务器，具体的原因和解决方法我们暂时不掌握，但是我们已经就此事和 Jenkins 官方沟通，争取能够将更多的中国境内用户引入到 TUNA 的服务器上。这样的话，境内的用户可以在不经手动配置的情况下，自动从 TUNA 服务器上下载插件。

**Comment by shankerwangmiao** [comment]
您或许可以参考 “Jenkins 中文社区” 上的相关信息。

https://jenkins-zh.cn/tutorial/management/plugin/update-center/

**Comment by fzyzcjy** [comment]
好的，谢谢

**Comment by fzyzcjy** [comment]
> 但是我们已经就此事和 Jenkins 官方沟通，争取能够将更多的中国境内用户引入到 TUNA 的服务器上。这样的话，境内的用户可以在不经手动配置的情况下，自动从 TUNA 服务器上下载插件。

如有新进展，麻烦通知一下
