### ISSUE TITLE
Teamspeak

### ISSUE THREAD

**Issue by fernprinxe** [tuna/issues#739]
Teamspeak镜像请求;
Teamspeak概要：团队语音服务器，镜像分为客户端和服务端，中国大陆地区暂无可用镜像，全国各地直连资源服务器效率低，服务器搭建困难，客户端下载困难；盈利模式为个人用户免费，客户端及其服务端免费，企业及高级用户付费制；项目体积约为11GB；
Teamspeak Wiki: [https://en.wikipedia.org/wiki/TeamSpeak](url)
镜像上游地址&官方资源库: [https://files.teamspeak-services.com/releases/](url)

**Comment by phy25** [comment]
> Mirroring or linking directly to our files is prohibited without our express, written consent.

https://www.teamspeak.com/en/downloads/
