### ISSUE TITLE
Add Antergos Mirror

### ISSUE THREAD

**Issue by wagaaa** [tuna/issues#74]
## Name: Antergos Linux

Or Antergos

## Introduce: 

Essentials Included
Antergos includes everything you need. Its default configuration provides you with a ready-to-use system. No additional steps are required after installation. You’ll be able to surf the web, listen to music, watch videos, and do anything else you like. Simply reboot your system and enjoy.

Rolling Release
Antergos is a rolling release distribution. Your entire system, from the base OS components to the applications that you install, will receive updates as they are released upstream—with only a minimal delay to ensure stability.

Multilingual
Antergos is available in many languages including Spanish, Galician, Catalan, English, German, and more.
Easily install Antergos with our Multilingual Live Medium which includes our easy-to-use graphical installer.
### Adding a new mirror

This article outlines the procedure for adding a new mirror for Antergos packages/releases to antergos-mirrorlist.

### 2-Tier Mirroring Scheme

Due to high load and bandwidth limits, Antergos uses a 2-tier mirroring scheme. There are few **tier 1** mirrors that sync directly from  repo.antergos.com  every hour. All other mirrors are **tier 2** and should sync from one of the **tier 1** mirrors. Syncing from  repo.antergos.com by a **tier 2** mirror is not allowed.

### Mirror Administrators

Please open an issue on the [antergos-packages github repo ](https://github.com/Antergos/antergos-packages/issues/) with a request to become an authorized mirror. Please include the following in your request:
* Mirror domain name
* Geographical location of the mirror
* Supported access methods (http, ftp, rsync, ...)
* URLs for the above access methods
* The name of the tier 1 mirror you are syncing from.
* An administrative contact email

To provide consistent mirroring and keep the upstream mirrors' load as low as possible, please ensure the following:
* Sync all contents of the upstream mirror (eg. do not sync only some repositories).
* Use the following command arguments when running rsync:

`--verbose --recursive --times --safe-links --delay-updates --delete-after --hard-links --ignore-times`

* Do not sync more than once per hour.
* Sync on a random minute so it is more likely the requests will be spaced out amongst other mirrors.
Tier-1 Mirrors

### Tier-1 Mirror	Location	Url
 mirrorservice.org	 United Kingdom |	rsync://rsync.mirrorservice.org/repo.antergos.com/ |
 leaseweb.net	 United States |	rsync://mirror.us.leaseweb.net/antergos |
 leaseweb.net 	Germany	rsync://mirror.de.leaseweb.net/antergos
 leaseweb.net	 Netherlands	rsync://mirror.nl.leaseweb.net/antergos

###Antergos Mirror Administrator

* Add the mirror info to the Mirrorbrain database and enable it
* Rebuild the antergos-mirrorlist package

## 其他信息(Other)
- 镜像大小(Mirror Size): 

To give you an idea of how much space will be needed for a mirror, here are some numbers:
* antergos: < 4GB
* antergos-staging: < 1GB
* iso: < 5GB

---
https://antergos.com/wiki/miscellaneous/new-mirror-guidelines/

by Wagaaa

**Comment by bigeagle** [comment]
同步已完成

**Comment by bigeagle** [comment]
已申请官方镜像。 Antergos/antergos-packages#112

**Comment by bigeagle** [comment]
已加入官方镜像列表。
