### ISSUE TITLE
建议增加clear linux 镜像

### ISSUE THREAD

**Issue by 2018wzh** [tuna/issues#740]
#### 项目名称与简介(Project Intro.)
Clear Linux* OS (Clear Linux OS, Clear Linux*) 是一个开源，滚动发行，针对英特尔架构最优化，讲究性能与信息安全的Linux发行版，能部署云计算平台以至边缘运算上
#### 上游地址与镜像方法(How to Mirror)
https://cdn.download.clearlinux.org/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
unknown

**Comment by z4yx** [comment]
See https://github.com/tuna/issues/issues/654#issuecomment-596206393
