### ISSUE TITLE
404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by octavianus7** [tuna/issues#742]
#### 发生了什么（What happened）
404
#### 期望的现象（What you expected to happen）
出现snapshot镜像页面
#### 如何重现（How to reproduce it）
访问即会出现
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
see #619
