### ISSUE TITLE
希望添加 Iosevka 字体

### ISSUE THREAD

**Issue by lihaoyu1234** [tuna/issues#744]
#### 项目名称与简介(Project Intro.)
Iosevka 是一款由 Belleve Invis(be5invis) 设计的开源等宽字体。

#### 上游地址与镜像方法(How to Mirror)
https://github.com/be5invis/Iosevka/releases

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
已同步好。

**Comment by z4yx** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/be5invis/Iosevka/LatestRelease/
