### ISSUE TITLE
404 at /anaconda/archive/Anaconda3-2020.02-MacOSX-x86_64.pkg

### ISSUE THREAD

**Issue by stfenjobs** [tuna/issues#747]
Anaconda3-2020.02 最新版已经出来了， 麻烦同步下镜像，谢谢

https://www.anaconda.com/anaconda-individual-edition-2020-02/
https://www.anaconda.com/distribution/

**Comment by shankerwangmiao** [comment]
镜像站的同步有其固有频率，不能保证其及时性。请耐心等待。
