### ISSUE TITLE
建议增加 virtualbox 5.2.38 软件包

### ISSUE THREAD

**Issue by lihaoyu1234** [tuna/issues#748]
#### 项目名称与简介(Project Intro.)
virtualbox

#### 上游地址与镜像方法(How to Mirror)
https://download.virtualbox.org/virtualbox/5.2.38/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
我看了一下同步脚本是根据  `LATEST.TXT`   里面的版本号去下载的，你一定需要5.x的版本吗？

**Comment by z4yx** [comment]
改为了同步每个大版本号的最后一个版本，应该满足大部分需求了吧
