### ISSUE TITLE
Wireguard PPA 镜像请求

### ISSUE THREAD

**Issue by lightsing** [tuna/issues#749]
#### 项目名称与简介(Project Intro.)
WireGuard® is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPsec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN.
**Ubuntu ≤ 19.04 的安装需要使用 PPA**

#### 上游地址与镜像方法(How to Mirror)
- 上游地址
https://launchpad.net/~wireguard/+archive/ubuntu/wireguard/
- 镜像方法
`apt-mirror`
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
```Number of packages:
10 source packages (475.1 KiB)
40 binary packages (3.9 MiB)```

**Comment by z4yx** [comment]
考虑到最新发行版都已包含，并且本身文件也很小，我觉得没必要镜像

**Comment by lightsing** [comment]
18.04 LTS 及以下的 LTS 中还没有包含，这些发行版使用的还是挺多的，即使是 HWE 内核，现在也只有到
5.3，要使用wg最好的还是用PPA源，考虑国内的网络情况，apt的使用体验会不太好

Yuxiang Zhang <notifications@github.com>于2020年3月16日 周一16:09写道：

**Comment by z4yx** [comment]
Ubuntu 20.04 LTS 发布在即，其中已内置 wireguard，因此不再镜像其PPA。如果老版本使用可以考虑ustc提供的反代 launchpad.proxy.ustclug.org

**Comment by z4yx** [comment]
https://packages.ubuntu.com/search?keywords=wireguard&searchon=names&suite=all&section=all
已进入16.04，18.04官方源
