### ISSUE TITLE
可不可以提供 Gitee 的分支

### ISSUE THREAD

**Issue by KunMinX** [tuna/issues#753]
刚刚通过 TUNA 托管在 GitHub 上的 homebrew 更新，
下载过程实在太慢了，9MB，1b/s 地下载（/捂脸），
所以可否提供 gitee 分支呢？

https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

**Comment by shankerwangmiao** [comment]
您好，homebrew 是由 Max Howell 等人开发，并将相关资源托管在 github 上，并非 TUNA 所托管的。TUNA 镜像站上的 Homebrew 是从 github 上的版本原样镜像而来。

**Comment by jiegec** [comment]
你可以去 https://gitee.com/mirrors 提出你的建议。

**Comment by KunMinX** [comment]
对不起，打扰了。
最后我的解决办法是，改 hosts，让 github 下载速度变快 …

**Comment by Harry-Chen** [comment]
再次提醒：TUNA 只是提供 GitHub 上 Homebrew 软件的镜像，与您访问 GitHub 的速度没有任何关系

**Comment by dotkrnl** [comment]
> 对不起，打扰了。
> 最后我的解决办法是，改 hosts，让 github 下载速度变快 …

我稍微有一些 confused，如果您根据 TUNA 的帮助文档修改了上游至 https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git ，GitHub 的速度为什么会影响您的 `brew update` 速度呢？

如果您指代 `brew install/upgrade` 的速度，您可能希望参考 https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/ 同时修改您的 bottles 地址

**Comment by KunMinX** [comment]
@dotkrnl 感谢诸位的负责，很抱歉给诸位造成困扰。
我对 brew 及其相关的一系列构件的 背景、结构、关系、作用 并不了解，
只是按照命令一步步执行时，感知进度极慢。
为避免给后来者造成困扰，希望能帮我删除这个帖子。

**Comment by dotkrnl** [comment]
@KunMinX 没事的。如果你有兴趣的话可以帮忙修改一下帮助页面，让大家更好地意识到 homebrew 是两部分组成的：homebrew 的 git 仓库维护版本信息索引，homebrew 的 bottles 维护二进制文件。前者影响 `brew update` 的速度，后者影响具体程序安装和更新的速度。具体参考下面两个链接：

https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
https://mirrors.tuna.tsinghua.edu.cn/help/homebrew-bottles/

如果您希望帮助我们改进帮助文档，可以在这里提交 pull request：

https://github.com/tuna/mirror-web/tree/master/_posts/help
