### ISSUE TITLE
anaconda 镜像 `current_repodata.json` 404

### ISSUE THREAD

**Issue by inkydragon** [tuna/issues#754]
#### 发生了什么（What happened）
以下链接 404
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/current_repodata.json 
官方源：
https://repo.continuum.io/pkgs/main/win-64/current_repodata.json

#### 期望的现象（What you expected to happen）
文件可以正常访问

#### 如何重现（How to reproduce it）
访问链接

#### 其他事项（Anything else we need to know）
无

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10.0.18363
- 浏览器（如果适用）（Browser version, if applicable）：Google Chrome 80.0.3987.149（正式版本）（64 位）

**Comment by z4yx** [comment]
不清楚 current_repodata.json 有什么作用，似乎不影响 conda 正常工作

**Comment by z4yx** [comment]
https://www.anaconda.com/how-we-made-conda-faster-4-7/
根据官方介绍，是用于加速的，可以考虑同步这个文件。
