### ISSUE TITLE
镜像链接出现问题

### ISSUE THREAD

**Issue by c4dr01d** [tuna/issues#756]
我想问一下最近是咋回事？我今天想从站上下载一些源码和ISO镜像报错，说无法链接

**Comment by shankerwangmiao** [comment]
具体是什么现象？是 DNS 解析错误还是连接超时还是显示其他错误？

**Comment by shankerwangmiao** [comment]
您用的是什么工具下载的？

**Comment by c4dr01d** [comment]
@shankerwangmiao Safari, wget, curl

**Comment by c4dr01d** [comment]
@shankerwangmiao 我手机上的termux更新软件仓库也不行，ping测试全是丢包

**Comment by shankerwangmiao** [comment]
请给出 `mtr mirrors.tuna.tsinghua.edu.cn` 的输出截图。

**Comment by c4dr01d** [comment]
@shankerwangmiao 
![截屏2020-03-22下午10 57 40](https://user-images.githubusercontent.com/50952350/77252693-8f179800-6c90-11ea-88f0-ed118f054619.png)

**Comment by shankerwangmiao** [comment]
您好，从您给出的网络路径跟踪结果来看，您是从江西地区的电信网络访问 TUNA 的。我们已经接获类似的故障报告。经反向跟踪查证，目前已经确认网络中断的部位在电信骨干网内部。建议您向您的运营商报告此故障。
