### ISSUE TITLE
【镜像同步】404 at /qt/archive/qt/4.8

### ISSUE THREAD

**Issue by luojunyuan** [tuna/issues#757]
#### 发生了什么（What happened）
Qt 镜像 archive 中 Qt4.0 - 5.1部分全部失效了

#### 其他事项（Anything else we need to know）
前段时间Qt官方下载地址 archive 中 Qt4.0-5.1 下载全部失效了 #734 ，我认为这似乎是官方的操作失误，导致所有国家镜像站跟着同步也全部都访问不了了。

今天再次访问官方地址一切都恢复正常了。

#### 如何重现（How to reproduce it）
访问 官方镜像 http://download.qt.io/archive/qt/4.8/ 一切正常，官方已经恢复了
访问 清华镜像 https://mirrors.tuna.tsinghua.edu.cn/qt/archive/qt/4.8 仍旧404

by the way [中科大](http://mirrors.ustc.edu.cn/qtproject/archive/qt/4.8)也是404

#### 期望的现象（What you expected to happen）
期望尽快同步

#### 您的环境（Environment）
- 操作系统（OS Version）：win10
- 浏览器（如果适用）（Browser version, if applicable）：edge chromium
- 其他（Others）：none

**Comment by z4yx** [comment]
![image](https://user-images.githubusercontent.com/2733275/77271229-1b55a980-6ce9-11ea-8ad1-8d4dd9e06005.png)
上游把这些版本的目录变成了符号链接，而链接指向的目录并不存在与rsync中

**Comment by phy25** [comment]
可以联系 mirrors@qt-project.org

**Comment by phy25** [comment]
> From: Jani Heikkinen
>
> This is expected behavior; it is planned that master.qt-project.org/qt-all/archive/qt/ isn’t mirrored at all; it contains old, unsupported releases and we think master should be able to handle download traffic for those releases. That functionality there is to save space on mirrors, does it cause now some harm to you?

如果有同学想回复一下这封邮件可以单独联系我，我可以把这封邮件会话转给哪位……没有的话我会觉得这个是上游预期的现象。

**Comment by luojunyuan** [comment]
感谢你们联系。如果需要的话可以关闭这个issue了
