### ISSUE TITLE
「安装镜像请求」FreeCAD | GPLv2 | GitHub Releases

### ISSUE THREAD

**Issue by zombie110year** [tuna/issues#759]
# 应用简介
FreeCAD 是一个开源的基于 Qt 的 CAD 应用程序，可进行三维设计。
其官网网址为 https://www.freecadweb.org/。
以 GPLv2 协议发布。
# 上游地址
GitHub Releases: <https://github.com/FreeCAD/FreeCAD/releases/>
# 镜像信息
每次发布大约有 2.5GB 的二进制内容（Windows、Linux、MacOS 的安装包、AppImage、便携版等）

**Comment by jiegec** [comment]
已经列入同步列表，请等待同步完毕。

**Comment by z4yx** [comment]
同步完成

**Comment by zombie110year** [comment]
有链接吗……找不到啊。

**Comment by Harry-Chen** [comment]
> 有链接吗……找不到啊。

https://mirrors.tuna.tsinghua.edu.cn/github-release/FreeCAD/FreeCAD/
 
或者直接点击首页上的获取下载链接按钮
