### ISSUE TITLE
Repoforge(原rpmforge) 镜像

### ISSUE THREAD

**Issue by gaoyichuan** [tuna/issues#76]
#### 项目名称与简介(Project Intro.)
Repoforge(原rpmforge)是CentOS系统下的软件仓库，拥有10000多种的软件包，被CentOS社区认为是最安全也是最稳定的一个软件仓库。由于原本的CentOS源中软件包不全面且版本较低，Repoforge具有重要的作用。
#### 上游地址与镜像方法(How to Mirror)
Tier-1上游列表:
* Asia:

    **ftp.riken.jp** (Japan) - *rsync://ftp.riken.jp/repoforge/*
  
* Europe:

    **mirror1.hs-esslingen.de** (Germany) - *rsync://mirror1.hs-esslingen.de/repoforge/*

    **repository.vsb.cz** (Czech Republic) - *rsync://repository.vsb.cz/repoforge/*
  
* North-America / South-America:

    **repoforge.eecs.wsu.edu** (United States) - *rsync://repoforge.eecs.wsu.edu/repoforge/*

#### 其他信息(Other)
- 镜像大小(Mirror Size): ~90GB
- 官方镜像要求(来自[官方faq](http://repoforge.org/faq/))
  1. You must subscribe to the mailing list for mirror maintainers
  2. At least 140 GB of available disk space. The current distribution directory is around 90 GB, but we wish to leave room for considerable expansion 
  3. You must not trim or abridge the mirrored tree in any way 
  4. You must not modify the mirrored tree in any way. In particular, index.html, HEADER.html and README.html files must not be altered or removed 
  5. Your mirror must not be shown “inside” another site using, for instance, frames 
  6. You must do an update-check at least once a day, and preferably four times a day 
  7. Do not rsync more rapidly than every hour 
  8. Sync on a random minute so it is more likely the requests will be spaced out with other mirrors 
  9. You must use ‘repoforge’ name for the mirror

**Comment by gaoyichuan** [comment]
官方要求镜像后将如下信息发送至mailing list:
Provide us with details of your mirror: * URL of mirror * Supported access methods (http, ftp, rsync, …) 
* Country / state / city where the mirror is located 
* Contact email address 
* Update frequency 
* Approximate bandwidth 
* The name of Tier1 mirror you are syncing from, which should be one of the list

**Comment by bigeagle** [comment]
同步已完成

**Comment by gaoyichuan** [comment]
可以close了吧。回去我写help发你
