### ISSUE TITLE
请求建立ros2镜像

### ISSUE THREAD

**Issue by jian-dong** [tuna/issues#763]
#### 项目名称与简介(Project Intro.)
项目简介（摘自[官方文档](https://index.ros.org/doc/ros2/)): The Robot Operating System (ROS) is a set of software libraries and tools for building robot applications. From drivers to state-of-the-art algorithms, and with powerful developer tools, ROS has what you need for your next robotics project. And it’s all open source.

Since ROS was started in 2007, a lot has changed in the robotics and ROS community. The goal of the ROS 2 project is to adapt to these changes, leveraging what is great about ROS 1 and improving what isn’t.
#### 上游地址与镜像方法(How to Mirror)
- 官方package地址： http://packages.ros.org/ros2/ubuntu

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知

**Comment by z4yx** [comment]
完成
