### ISSUE TITLE
[请求镜像]Blender Release

### ISSUE THREAD

**Issue by RigoLigoRLC** [tuna/issues#766]
#### 项目名称与简介(Project Intro.)
Blender是一个GPLv3协议开源的自由3D创作工具，也包含了2D动画、剪辑合成等工作流程。
Blender.org的官方下载服务器位于荷兰，国外镜像下载速度不尽人意；Windows用户群体大，影响较为严重。
#### 上游地址与镜像方法(How to Mirror)
可从官方release页面：https://download.blender.org/release/
或mirrors.clarkson.edu（每日更新4次）：https://mirror.clarkson.edu/blender/release/
或dotsrc.org镜像rsync（至少每日更新1次）：rsync://mirrors.dotsrc.org/blender/blender-release/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 整个Blender镜像约1.5TB（Clarkson镜像统计数据），Release大小未知。
如有可能，也可镜像整个Blender库；但对于国内常规用户，sources压缩包和demo用处可能并不大。

**Comment by z4yx** [comment]
是不是只要最近的版本就够了

**Comment by RigoLigoRLC** [comment]
如果有可能，我认为可以只保留2.7和2.8系列，GPL License文本和BlenderBenchmark

**Comment by z4yx** [comment]
已完成
