### ISSUE TITLE
[tuna]Mirror Request for new mirror anaconda

### ISSUE THREAD

**Issue by OnlyBelter** [tuna/issues#768]
#### 项目名称与简介(Project Intro.)
mordred
github: https://github.com/mordred-descriptor/mordred
#### 上游地址与镜像方法(How to Mirror)
https://anaconda.org/mordred-descriptor/mordred/files
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
抱歉，现在上面的链接无法打开，因此无法查看大小。

**Comment by z4yx** [comment]
已添加到同步列表
