### ISSUE TITLE
[故障报告]CentOS8 - Base配置文件格式错误

### ISSUE THREAD

**Issue by LuRenJiasWorld** [tuna/issues#769]
## 故障描述
根据你们的文档，CentOS8的Base库名称为`Base OS`：

![image](https://user-images.githubusercontent.com/29622423/77885488-ae6a8280-7299-11ea-9178-ed10d4cefb34.png)

但在实际使用时候会提示错误：
![image](https://user-images.githubusercontent.com/29622423/77885527-c04c2580-7299-11ea-9eaf-4e81a2634d06.png)

## 解决方法

参考CentOS8官方仓库配置文件，需要将你们文档中的`Base OS`修改为`BaseOS`，报错即消失。
![image](https://user-images.githubusercontent.com/29622423/77885628-f5587800-7299-11ea-9053-49f1f55284e7.png)

**Comment by z4yx** [comment]
感谢指出，已修改。
