### ISSUE TITLE
Ceph

### ISSUE THREAD

**Issue by meteorlad** [tuna/issues#77]
##### CEPH
Ceph is highly reliable, easy to manage, and free. The power of Ceph can transform your company’s IT infrastructure and your ability to manage vast amounts of data. To try Ceph, see our Getting Started guides. To learn more about Ceph, see our Architecture section.
#### 上游地址与镜像方法(How to Mirror)
http://download.ceph.com/

EU: Netherlands: http://eu.ceph.com/
AU: Australia: http://au.ceph.com/
CZ: Czech Republic: http://cz.ceph.com/
SE: Sweden: http://se.ceph.com/
DE: Germany: http://de.ceph.com/
HK: Hong Kong: http://hk.ceph.com/
FR: France: http://fr.ceph.com/
US-East: US East Coast: http://us-east.ceph.com/
US-West: US West Coast: http://us-west.ceph.com/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by meteorlad** [comment]
@bigeagle 同步的具体时间点有么? 你们这边什么时间开始同步呢?

**Comment by bigeagle** [comment]
现在是期末考试期间……

**Comment by CDLuminate** [comment]
@bigeagle 期末考试还刷github

**Comment by bigeagle** [comment]
Done.
