### ISSUE TITLE
关于AOSP使用的若干问题

### ISSUE THREAD

**Issue by chason0528** [tuna/issues#770]
最近使用清华镜像 pull 5.x 6.x的 总会遇到一些问题 然后repo sync失败。报错日志如下
`platform/prebuilts/gradle-plugin:`
`remote: Counting objects: 61028, done.       `
`error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

`platform/tools/external/gradle:`
`remote: Counting objects: 1930, done.      ` 
`error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

`platform/frameworks/base:`
`remote: Counting objects: 3497291, done.     `  
`error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

`platform/tools/external/gradle:`
`remote: Counting objects: 1930, done.       `
`error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

`error: Cannot fetch platform/tools/external/gradle from https://aosp.tuna.tsinghua.edu.cn/platform/tools/external/gradle`
`Fetching projects:   0% (1/486) platform/tools/external/gradleplatform/frameworks/base:`
`remote: Counting objects: 3497291, done.  `     
`error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

`platform/prebuilts/gradle-plugin:`
`remote: Counting objects: 61028, done.       `
`error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

**Comment by z4yx** [comment]
可能和 https://github.com/tuna/issues/issues/98#issuecomment-605420483 遇到了同样的问题，猜测是网络原因，无法复现和证实。

**Comment by chason0528** [comment]
是否是新旧库的冲突呢？ 已经在不同的地点，不同的节点都使用过，不同的时间段，带宽均超过1000M，但是都报了这个错。

**Comment by chason0528** [comment]
另外 git缓冲区设为5g 依然会报错

**Comment by shankerwangmiao** [comment]
您能把详细的日志贴上来吗？我们可以一起分析一下

**Comment by yangfan069** [comment]
> 可能和 [#98 (comment)](https://github.com/tuna/issues/issues/98#issuecomment-605420483) 遇到了同样的问题，猜测是网络原因，无法复现和证实。

请问你解决了吗？我最近同步也遇到这个问题了。

**Comment by yangfan069** [comment]
请问一下大家，这个问题解决了吗？我同步lineageos的时候也有同样的问题。

**Comment by z4yx** [comment]
还没有解决，由于问题发生在网络中，很难定位和解决。

**Comment by chason0528** [comment]
> 请问一下大家，这个问题解决了吗？我同步lineageos的时候也有同样的问题。

我的解决方案是：利用脚本， 假如repo sync失败，则再次repo sync

**Comment by chason0528** [comment]
> 您能把详细的日志贴上来吗？我们可以一起分析一下

详细日志没有保存，利用不断重复repo sync 解决改问题

**Comment by yangfan069** [comment]
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

platform/cts:
remote: Counting objects: 905164, done.        
remote: Compressing objects: 100% (254541/254541), done.        
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

经常出现这种错误，  platform/cts  同步好几次到最后这个cts都同步不下来  还有error (-54)，error (-100) 由于有太多  但是都是这种错误。 git各种设置都已调整不管用。

**Comment by yangfan069** [comment]
> > 您能把详细的日志贴上来吗？我们可以一起分析一下
> 
> 详细日志没有保存，利用不断重复repo sync 解决改问题

您重复的repo sync 到最后能成功吗？

**Comment by chason0528** [comment]
> > > 您能把详细的日志贴上来吗？我们可以一起分析一下
> > 
> > 
> > 详细日志没有保存，利用不断重复repo sync 解决改问题
> 
> 您重复的repo sync 到最后能成功吗？

利用脚本 重复sync是可以成功的 但是貌似会耗费较多的硬盘容量 这一点我没有验证过

**Comment by yangfan069** [comment]
> > > > 您能把详细的日志贴上来吗？我们可以一起分析一下
> > > 
> > > 
> > > 详细日志没有保存，利用不断重复repo sync 解决改问题
> > 
> > 
> > 您重复的repo sync 到最后能成功吗？
> 
> 利用脚本 重复sync是可以成功的 但是貌似会耗费较多的硬盘容量 这一点我没有验证过

 我前两天一直在重复 到最后的话，  platform/cts  还有一些包 始终是 下载不下来  而且硬盘容量也不会增加 。

**Comment by z4yx** [comment]
建议换到 https://mirrors.bfsu.edu.cn/help/AOSP/

**Comment by yangfan069** [comment]
> 建议换到 https://mirrors.bfsu.edu.cn/help/AOSP/

你切换过去可以下载吗？

**Comment by z4yx** [comment]
我尝试过在干净的环境 repo init 然后 sync，没有问题。

**Comment by yangfan069** [comment]
> 我尝试过在干净的环境 repo init 然后 sync，没有问题。
Fetching projects:  95% (720/757) LineageOS/android_hardware_qcom_audioReceivingFetching projects:  97% (735/757) LineageOS/android_hardware_qcom_displayReceiviFetching projects:  98% (742/757) LineageOS/android_hardware_qcom_displayReceiviFetching projects:  99% (750/757) platform/external/gflagsReceiving objects:  25remote: Counting objects: 10897, done.        iB | 599.00 KiB/s      
remote: Compressing objects: 100% (4038/4038), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
platform/prebuilts/tools:
remote: Counting objects: 14165, done.        
remote: Compressing objects: 100% (6392/6392), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
platform/frameworks/layoutlib:
remote: Counting objects: 945553, done.        
remote: Compressing objects: 100% (183070/183070), done.        
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

remote: Counting objects: 14165, done.        iB | 3.37 MiB/s   
remote: Compressing objects: 100% (6392/6392), done.        
remote: Counting objects: 945553, done.        B | 2.36 MiB/s   
remote: Compressing objects: 100% (183070/183070), done.        
Receiving objects:  88% (9651/10897), 440.55 MiB | 375.00 KiB/s   


  

error: Cannot fetch platform/prebuilts/tools from https://aosp.tuna.tsinghua.edu.cn/platform/prebuilts/tools
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
platform/frameworks/layoutlib:


remote: Counting objects: 945553, done.        
remote: Compressing objects: 100% (183070/183070), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


Checking out projects:  50% (379/757) LineageOS/android_frameworks_averror: Cannot checkout platform/frameworks/layoutlib: ManifestInvalidRevisionError: revision refs/tags/android-10.0.0_r31 in platform/frameworks/layoutlib not found
error: in `sync --no-clone-bundle`: revision refs/tags/android-10.0.0_r31 in platform/frameworks/layoutlib not found

你好 ，我在同步lineageos 源码的时候遇到这些问题 能帮忙看下吗？

**Comment by z4yx** [comment]
这种错误可能是网络原因造成的，有很多人都报告过。请尝试用 https://mirrors.bfsu.edu.cn/help/AOSP/ ，那边有非教育网的接入，更适合一般国内用户。

**Comment by yangfan069** [comment]
> 这种错误可能是网络原因造成的，有很多人都报告过。请尝试用 https://mirrors.bfsu.edu.cn/help/AOSP/ ，那边有非教育网的接入，更适合一般国内用户。

我就是今天用这个镜像之后 报的。

**Comment by z4yx** [comment]
但你的日志里面显示的还是tsinghua.edu.cn呀

**Comment by yangfan069** [comment]
> 但你的日志里面显示的还是tsinghua.edu.cn呀

<remote  name="aosp"
           fetch="https://aosp.tuna.tsinghua.edu.cn"   那个aosp中间 改的还是从清华这边获取的呀。 您能麻烦发下您这块的配置吗？

**Comment by z4yx** [comment]
把所有的 https://aosp.tuna.tsinghua.edu.cn 替换为 https://mirrors.bfsu.edu.cn/git/AOSP

**Comment by yangfan069** [comment]
> 把所有的 https://aosp.tuna.tsinghua.edu.cn 替换为 https://mirrors.bfsu.edu.cn/git/AOSP

嗯 这下好了 谢谢啊。
