### ISSUE TITLE
rudder国内镜像申请

### ISSUE THREAD

**Issue by laileman** [tuna/issues#772]
1. rudder介绍
自动发现和注册的监控系统。
2. 镜像地址
http://repository.rudder.io/
3. 项目
我司（深圳）使用rudder多年，但是安装和维护起来拉取源文件速度感人。
4. rudder国内
现在很难找到相关文档，只有rudder.io的完整文档。

**Comment by phy25** [comment]
License GPLv3: https://github.com/Normation/rudder/blob/master/LICENSE

不知道发行包是不是同样的协议，他家也是[有 subscription 的](https://www.rudder.io/pricing/subscription/)。

**Comment by z4yx** [comment]
这个仓库文件比较杂，也不提供rsync，缺少同步方式。如果只同步apt和yum源的话倒是有工具。

**Comment by laileman** [comment]
apt和rpm使用比较常见。sources, tools  看能否也实现。这个源的更新频率不高，在国内也是小众使用。可考虑同步周期大一点。

**Comment by z4yx** [comment]
已添加，同步了 4.3 5.0 6.0 三个大版本。
