### ISSUE TITLE
[tuna]404 at /anaconda/pkgs/main/noarch/current_repoda

### ISSUE THREAD

**Issue by Dominic-ZZ** [tuna/issues#773]
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
该文件正常：https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/current_repodata.json
