### ISSUE TITLE
pypi 无法通过rsync进行同步，我使用rsync无法从清华站点下载pypi的目录，提示Unknown module 'pypi'

### ISSUE THREAD

**Issue by navinfo-security** [tuna/issues#775]
pypi 无法通过rsync进行同步，我使用rsync无法从清华站点下载pypi的目录，提示Unknown module 'pypi'

列出清华站点的所有的module，没有看到pypi。

看起来是未开放pypi的rsync同步，请问原因是什么呢？

**Comment by shankerwangmiao** [comment]
见 #517
