### ISSUE TITLE
镜像请求，Harbor

### ISSUE THREAD

**Issue by penglingfeng1995** [tuna/issues#777]
#### 上游地址与镜像方法(How to Mirror)
https://github.com/goharbor/harbor/releases

#### 其他信息(Other)
- 镜像大小(Mirror Size): 600MB

**Comment by z4yx** [comment]
已添加同步

**Comment by willzhang** [comment]
加到哪了，找不到啊

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/goharbor/harbor/
