### ISSUE TITLE
gentoo-portage使用帮助的问题

### ISSUE THREAD

**Issue by SaltyKitkat** [tuna/issues#779]
`emerge --sync`与`eix-sync`遵循` /etc/portage/repos.conf`中相应repo的`sync-uri`进行同步.
`emerge-webrsync`遵循`/etc/portage/make.conf`中`GENTOO_MIRRORS`变量的地址下载快照.
使用帮助中

> 在 /etc/portage/make.conf 中加入：
>`GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo"`
>执行 emerge --sync 或者 eix-sync 进行更新。

是不恰当的.

若tuna有意向为portage提供rsync服务,则建议在使用帮助中提供类似`Gentoo Portage Prefix 镜像配置`修改`/etc/portage/repos.conf`的指导,
否则应建议用户使用`emerge-webrsync`获取来自tuna的每日快照.

**Comment by z4yx** [comment]
tuna/mirror-web#158

**Comment by z4yx** [comment]
我不了解gentoo，这个和上面那个issue的回答是一件事情吗

**Comment by SaltyKitkat** [comment]
并不是
>stage3 和 stage4 里没有 `eix-sync` ，而 `emerge --sync` 走 rsync 又超级慢。建议补充推荐使用 `emerge-webrsync` ，以免新手（比如我）掉坑。

其中`emerge --sync`慢主要是因为`/etc/portage/repos.conf`中的默认配置走了**官方源**而非**tuna**

我的建议是
参考"Gentoo Portage Prefix 镜像配置"
在`/etc/portage/repos.conf`中把gentoo这个repo的`sync-uri`设置为
`rsync://mirrors.tuna.tsinghua.edu.cn/gentoo-portage`

**Comment by z4yx** [comment]
这样吧，你直接修改 https://github.com/tuna/mirror-web/blob/master/_posts/help/2017-12-29-gentoo-portage.md

然后提交pull-request即可
