### ISSUE TITLE
Manjaro Linux ISO镜像

### ISSUE THREAD

**Issue by ilofter** [tuna/issues#78]
#### Manjaro Linux下载镜像
清华大学已经收录了Manjaro Linux的更新服务器。但长期以来下载镜像只能通过 sourceforge进行下载，DNS污染严重，且速度较慢。，因此希望添加Manjaro的下载镜像。
#### Sourceforge
[Manjaro Linux 源](http://sourceforge.mirrorservice.org/m/ma/manjarolinux/)
#### 同步方式
rsync同步或Nginx反向代理

#### 关于
我们是[Manjaro中国 ](http://www.manjaro.cn)

**Comment by bigeagle** [comment]
完成～

**Comment by wi24rd** [comment]
看起來manjaro官方倉庫變成了 [OSDN](https://osdn.net/projects/manjaro/storage/)
參考 [readme](https://mirrors.tuna.tsinghua.edu.cn/manjaro-cd/release/17.1.5/readme.markdown)
