### ISSUE TITLE
CentOS更改软件源问题

### ISSUE THREAD

**Issue by WangJiyuanYo** [tuna/issues#780]
我在更改CentOS软件源的时候按照清华源的教程来操作 https://mirrors.tuna.tsinghua.edu.cn/help/centos/
在那一步使用MV命令备份原文件的时候，原文件被重命名为新的文件，原文件也消失了。之后按照教修改文件配置是一个全新的文件，因此是否可以将mv 命令改用成cp命令比较好？
我对mv 并不是很熟悉。也许是我的问题。

**Comment by z4yx** [comment]
你的建议有道理，我们更新一下内容，谢谢！
