### ISSUE TITLE
 Termux 社区源 its-pointless 的镜像支持

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#781]
#### 项目名称与简介(Project Intro.)
它提供了许多 Termux 官方源没有提供、难以编译的包，例如 numpy, scipy 等。但是国内添加后访问非常慢。

TUNA 是我知道的唯一的 Termux 国内源，因此向你们团队发出这个请求，不管是否能同意，都非常感谢清华源对开源世界的贡献！

#### 上游地址与镜像方法(How to Mirror)
Its-pointless 的开源地址是 https://github.com/its-pointless/gcc_termux 

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
- 提出者：Jackal Zhao

**Comment by xavieryao** [comment]
根据 https://github.com/tuna/issues/issues/741 ，不镜像 GitHub 仓库。

**Comment by CberYellowstone** [comment]
> #### 项目名称与简介 (Project Intro.)
> 它提供了许多 Termux 官方源没有提供、难以编译的包，例如 numpy, scipy 等。但是国内添加后访问非常慢。
> 
> TUNA 是我知道的唯一的 Termux 国内源，因此向你们团队发出这个请求，不管是否能同意，都非常感谢清华源对开源世界的贡献！
> 
> #### 上游地址与镜像方法 (How to Mirror)
> Its-pointless 的开源地址是 https://github.com/its-pointless/gcc_termux
> 
> #### 其他信息 (Other)
> * 镜像大小 (Mirror Size):
> * 提出者：Jackal Zhao

建议使用jsdeliver

**Comment by iBug** [comment]
@xavieryao 并非 GitHub 仓库，所有 deb 包都可以从 [https://its-pointless.github.io/files/](https://github.com/its-pointless/its-pointless.github.io/tree/master/files) 获取。

<https://mirrors.ustc.edu.cn/termux-its-pointless/>
