### ISSUE TITLE
jenkins.war版本 2.222.1暂无，期望您添加一下

### ISSUE THREAD

**Issue by 1725636955** [tuna/issues#782]
#### 上游地址与镜像方法(How to Mirror)
jenkins io
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
该镜像用的是rsync同步，无法人工干预。待上游（rsync://rsync.osuosl.org/jenkins/）更新后自然会同步下来。

**Comment by 1725636955** [comment]
> 该镜像用的是rsync同步，无法人工干预。待上游（rsync://rsync.osuosl.org/jenkins/）更新后自然会同步下来。

好的
