### ISSUE TITLE
Apache的镜像页面怎么与众不同

### ISSUE THREAD

**Issue by zbwxtex** [tuna/issues#783]
为什么https://mirrors.tuna.tsinghua.edu.cn/apache/和别的界面都不同??

**Comment by Harry-Chen** [comment]
对于没有提供主页（一般是`index.html`）的目录，您看到的是 TUNA 使用 `fancyindex` 提供的目录列表。`/apache/` 下存在一个主页，因此我们将会渲染该页面。

此外，如果您仔细观察，有很多镜像都是这样的，比如 `/CTAN/`。

**Comment by z4yx** [comment]
根据Apache基金会的要求，apache的镜像由apache httpd提供服务。（其它镜像都是 nginx）
