### ISSUE TITLE
ros sudo apt update 错误

### ISSUE THREAD

**Issue by Hou-alex** [tuna/issues#785]
安装 ros 

执行到 sudo apt update 

#### 发生了什么（What happened）
E: 无法下载 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/xenial/main/binary-i386/Packages  404  Not Found [IP: 2402:f000:1:408:8100::1 80]

#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu 18.04
- 浏览器（如果适用）（Browser version, if applicable）：firefox
- 其他（Others）：

**Comment by z4yx** [comment]
安装ros使用这个网址是不对的，请看帮助 https://mirrors.tuna.tsinghua.edu.cn/help/ros/

**Comment by z4yx** [comment]
关于ubuntu自身的镜像配置，请看这个帮助 https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/
