### ISSUE TITLE
【镜像请求】gitlab镜像获取失败

### ISSUE THREAD

**Issue by JorkeMooN** [tuna/issues#786]
执行
`sudo apt-get update`
日志如下：
`Hit:1 http://mirrors.tencentyun.com/ubuntu bionic InRelease
Hit:2 http://mirrors.tencentyun.com/ubuntu bionic-security InRelease
Hit:3 http://mirrors.tencentyun.com/ubuntu bionic-updates InRelease
Get:4 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic InRelease [23.3 kB] 
Ign:5 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic/main amd64 Packages
Get:5 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic/main amd64 Packages [34.6 kB]
Err:5 https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu bionic/main amd64 Packages
  File has unexpected size (34089 != 34626). Mirror sync in progress? [IP: 101.6.8.193 443]
  Hashes of expected file:
   - Filesize:34626 [weak]
   - SHA256:90241d73dd4218dda3d8e02a8f38b0793c7dfb95f40bf94918750048bf11244c
   - SHA1:be073f41bc17f02b463ef69f364978d06ed1f2d7 [weak]
   - MD5Sum:0839fd6f7b79fcb3bb9cdb121dd5c1e1 [weak]
  Release file created at: Wed, 15 Apr 2020 00:33:58 +0000
Reading package lists... Done  
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/ubuntu/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (34089 != 34626). Mirror sync in progress? [IP: 101.6.8.193 443]
   Hashes of expected file:
    - Filesize:34626 [weak]
    - SHA256:90241d73dd4218dda3d8e02a8f38b0793c7dfb95f40bf94918750048bf11244c
    - SHA1:be073f41bc17f02b463ef69f364978d06ed1f2d7 [weak]
    - MD5Sum:0839fd6f7b79fcb3bb9cdb121dd5c1e1 [weak]
   Release file created at: Wed, 15 Apr 2020 00:33:58 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by z4yx** [comment]
应该是暂时性的，已经恢复了。

**Comment by JorkeMooN** [comment]
已获取成功，感谢。
