### ISSUE TITLE
[tuna]Mirror Request for new mirror trusty

### ISSUE THREAD

**Issue by fytztx** [tuna/issues#787]
#### 项目名称与简介(Project Intro.)
Trusty TEE
Trusty 是一种安全的操作系统 (OS)，可为 Android 提供可信执行环境 (TEE)。Trusty 操作系统与 Android 操作系统在同一处理器上运行，但 Trusty 通过硬件和软件与系统的其余组件隔离开来。Trusty 与 Android 彼此并行运行。Trusty 可以访问设备主处理器和内存的全部功能，但完全隔离。隔离可以保护 Trusty 免受用户安装的恶意应用以及可能在 Android 中发现的潜在漏洞的侵害。
#### 上游地址与镜像方法(How to Mirror)
    mkdir trusty
    cd trusty
    repo init -u https://android.googlesource.com/trusty/manifest -b master
    repo sync -j32

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
我们已经提供了aosp的镜像，其中包含该项目。

**Comment by z4yx** [comment]
https://aosp.tuna.tsinghua.edu.cn/trusty/manifest

**Comment by carloscn** [comment]
repo init -u https://aosp.tuna.tsinghua.edu.cn/trusty/manifest -b master
