### ISSUE TITLE
[tuna]404 at /CRAN/bin/windows/contrib/3.1

### ISSUE THREAD

**Issue by chenzheng128** [tuna/issues#788]
#### 发生了什么（What happened）
无法下载

#### 期望的现象（What you expected to happen）
下载成功

#### 如何重现（How to reproduce it）
在 rstudio 中点击新建 r markdown 文件

#### 您的环境（Environment）
- 操作系统（OS Version）：Win7
- 浏览器（如果适用）（Browser version, if applicable
![微信截图_20200417011741](https://user-images.githubusercontent.com/10515634/79486435-482b8100-8049-11ea-8ad4-ad8eeb4680f9.png)
）： Chrome
- 其他（Others）：

**Comment by phy25** [comment]
镜像站上[只有 3.2 - 4.1 的版本](https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/)，并没有 3.1 的，可以尝试升级一下。

**Comment by phy25** [comment]
或者你应该使用 old contrib： https://cran-archive.r-project.org/bin/windows/contrib/
