### ISSUE TITLE
申请Flutter的download.flutter.io镜像

### ISSUE THREAD

**Issue by liudonghua123** [tuna/issues#789]
#### 项目名称与简介(Project Intro.)
download.flutter.io
这个镜像是类似于 https://flutter.dev/community/china 这里的 FLUTTER_STORAGE_BASE_URL，但是再开发Flutter应用的时候，还需要下载 https://storage.googleapis.com/download.flutter.io 里面的一些依赖项，但是目前国内没有这个镜像，导致很多时候会经常出现运行不了的问题

#### 上游地址与镜像方法(How to Mirror)
上游地址 https://storage.googleapis.com/download.flutter.io
同步方式类似于 https://github.com/tuna/issues/issues/357 https://github.com/tuna/issues/issues/409

镜像使用方式，修改 <flutter_home>/packages/flutter_tools/gradle/flutter.gradle 中的 MAVEN_REPO，从原来的 https://storage.googleapis.com/download.flutter.io 变为 https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/ 

https://mirrors.tuna.tsinghua.edu.cn/help/flutter/ 这里的 FLUTTER_STORAGE_BASE_URL 其实是从 https://storage.googleapis.com/flutter_infra 同步到 https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra，此 issue 是申请多同步一个目录，从 https://storage.googleapis.com/download.flutter.io 同步到 https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io

#### 其他信息(Other)
- 镜像大小(Mirror Size): 不知道，应该比较小，没有 flutter_infra 大

**Comment by z4yx** [comment]
@chenglu  帮忙评估一下这个有必要吗

**Comment by chenglu** [comment]
我需要去确认一下 `download.flutter.io` 的调用是否走 `FLUTTER_STORAGE_BASE_URL`，印象里好像是 hard code 到客户端直接请求的，如果是这样，镜像了可能也无济于事；如果在 gradle 文件修改可达到目的，镜像这个价值是有的，供参考。

我同步去问一下 Flutter 团队的同学问问看，后面我会安排在 `storage.flutter-io.cn` 上增加这个。
之前确实没有太考虑过 `download.flutter.io` 的可用性，因为 GCS 的域名绑定服务 `c.storage.googleapis.com` 是构建在 GCP 而不是谷歌已经被墙了的数据中心里，现在看起来 [在国内可访问性](http://ping.chinaz.com/c.storage.googleapis.com) 确实有所下降。

谢谢！

**Comment by z4yx** [comment]
感谢解答，如果确实能帮助用户，我们可以镜像。我刚才用 gsutil 统计了下这个仓库的大小为 206GB，全量同步的问题也不大。

**Comment by chenglu** [comment]
感谢 @z4yx，我看到了 `download.flutter.io` 的引用出处是 [这里](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/resolve_dependencies.gradle#L21)，也提出了建议给 Flutter 团队，希望他们把 `download.flutter.io` 合并进 `google()`，这样开发者就无需做出任何改动了。

我在微信群里 at 你了，有空瞅一眼哈。

感谢！

**Comment by liudonghua123** [comment]
@z4yx @chenglu 谢谢你们及时的反馈和支持，其实这个问题在 flutter 的 issue 里面有很多人都遇到，基本上也都是国内开发者 ( https://github.com/flutter/flutter/issues?q=http%3A%2F%2Fdownload.flutter.io%2F )，例如 https://github.com/flutter/flutter/issues/54198 https://github.com/flutter/flutter/issues/52624 https://github.com/flutter/flutter/issues/53498 我使用的是 master 分支的 flutter，每次`flutter upgrade`之后重新运行项目都会更新flutter engine的maven依赖项，遇到这个问题，非常的烦恼，我甚至都写了一个github action下载~/.gradle (https://github.com/liudonghua123/flutter_app/blob/master/.github/workflows/gradle.yml)

目前使用的方式确实不优化，需要手动修改 `<flutter_home>/packages/flutter_tools/gradle/flutter.gradle` 中的 `MAVEN_REPO`，并且每次upgrade之前都需要恢复，其实如果把 `download.flutter.io` 合并进 `google()`，那么使用`aliyun`的镜像也可以，或者提交pr修改`<flutter_home>/packages/flutter_tools/gradle/flutter.gradle`里面的`MAVEN_REPO`，使用`FLUTTER_STORAGE_BASE_URL`环境变量的方式，这样就不用手动修改这个文件。

**Comment by chenglu** [comment]
`download.flutter.io` 构建在 GCS 上，通过 http 可以访问，https 需要在 GCP 后台设定并签发 SSL 证书，应该是没有做这个设定。URL 的修改，我的理解是可能因为 stable 版本不能经常变动（改动了就要发 hotfix 版本），所以只修改了 beta、dev 版本。

再次谢谢 @liudonghua123 对问题的提出和 @z4yx 的快速响应，期待这个问题未来能够得以更好的解决。

**Comment by z4yx** [comment]
镜像已经可用了

**Comment by liudonghua123** [comment]
@z4yx 非常感谢，我看现在 https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/ 已经可以访问了，可以直接看到里面得内容，只是直接访问上述地址显示的是文件列表，不是元数据信息，这个应该没有影响吧。
![image](https://user-images.githubusercontent.com/2276718/79706507-184fd800-82ec-11ea-9ab8-ac1779b25859.png)
![image](https://user-images.githubusercontent.com/2276718/79706549-34ec1000-82ec-11ea-8dff-912faa89e859.png)

**Comment by z4yx** [comment]
没问题，你试试吧。

**Comment by liudonghua123** [comment]
嗯，谢谢 :)
