### ISSUE TITLE
qt内容检查

### ISSUE THREAD

**Issue by wiglaf1988** [tuna/issues#79]
你好，
我来自qt公司，因为将来准备增加很多内容，我们希望在mirror这里减少部分qt内容来减轻你们服务器的磁盘负担。下面这个脚本能不能请管理员更新至脚本里，目的是snapshots/  archive/不需要再通过rsync来同步了。 结尾处是假设/data/pub/qtproject 为你们服务器上的目录,有什么不清楚的话和我联系.

rsync -rlpt -delete master.qt.io::qt-all /data/pub/qtproject --exclude='master.qt.io::qt-snapshots' --exclude='master.qt.io::qt-archive' /data/pub/qtproject

**Comment by bigeagle** [comment]
请问内容大概有多大呢？
`snapshots` 和 `archive` 两个目录常用吗？
我们服务器扩容之后空间比较宽裕，如果能完整一些自然是更好的。

**Comment by wiglaf1988** [comment]
Hi,
听我们release team说将来要增加500GB，具体什么时候还不太清楚，如果mirror管理员当初订阅了[邮件](http://wiki.qt.io/Mirror_howto)，到时候会以邮件通知大家的.

/snapshots 和 /archive不常用，可以选择不同步的

不过这里也想在群发消息前，麻烦管理员配合测试下之前提供的脚本，跑一下看看第二天snapshots,archive目录是不是删除了。如果删除了，这个脚本的目的也就达到了。毕竟我们也没有mirror的权限，没办法做更多测试，这也是为了安全起见。所以希望可以帮忙测试下。测试顺利之后，如果空间足够，可以回滚这个变化，用原来你们的脚本也可以。

谢谢

**Comment by bigeagle** [comment]
我检查了，`/official_releases/qt/` 中的内容是指向 `/archive` 的软链接，所以直接忽略  `/archive` 会导致不可用的。
