### ISSUE TITLE
BFSU 的 pypi 中 ovloop 没有同步 rc 版本

### ISSUE THREAD

**Issue by pandada8** [tuna/issues#791]
#### 发生了什么（What happened）
https://mirrors.bfsu.edu.cn/pypi/web/simple/uvloop/ 中缺少 rc 后缀的版本
#### 期望的现象（What you expected to happen）
https://mirror.tuna.tsinghua.edu.cn/pypi/web/simple/uvloop/ 有 rc 后缀的版本
#### 如何重现（How to reproduce it）
N/A
#### 其他事项（Anything else we need to know）
https://pypi.org/project/uvloop/#history 确实有这些包
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
都是用的 github.com/pypa/bandersnatch 工具同步的，没有配置过滤器，不知道为什么

**Comment by z4yx** [comment]
以手工同步uvloop
