### ISSUE TITLE
conda-forge显示错误：Too many file to list

### ISSUE THREAD

**Issue by monchin** [tuna/issues#792]
#### 发生了什么（What happened）
需要给一个没有联外网的服务器安装包h5py，查到该包是在conda-forge上，想在清华镜像源上下载

#### 期望的现象（What you expected to happen）
像其他目录下的安装包一样，进入相应目录，点击安装包，下载

#### 如何重现（How to reproduce it）
地址栏输入
`https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/`
回车

#### 您的环境（Environment）
- 操作系统（OS Version）：windows10（不重要，只是下载包，之后要拷贝到服务器上）
- 浏览器（如果适用）（Browser version, if applicable）：chrome & edge 
- 其他（Others）：无

**Comment by shankerwangmiao** [comment]
您好，您可以直接使用包的文件路径来下载。由于该目录中文件过多，因此不再提供目录中文件列表的显示。

**Comment by z4yx** [comment]
请按照帮助页面 https://neomirrors.tuna.tsinghua.edu.cn/help/anaconda/
配置 conda 工具，通过它来安装，而不是用网页上下载。

**Comment by monchin** [comment]
谢谢！
