### ISSUE TITLE
AdoptOpenJDK Linux仓库

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#795]
#### 项目名称与简介(Project Intro.)

AdoptOpenJDK 之前只有二进制包的镜像，希望一并同步Linux官方仓库

#### 上游地址与镜像方法(How to Mirror)

官方有yum和apt仓库： https://adoptopenjdk.net/installation.html#linux-pkg

使用的是这个地址： https://adoptopenjdk.jfrog.io/adoptopenjdk/ 似乎是用artifactory搭建的，应该有办法直接同步

**Comment by z4yx** [comment]
已完成，请按照帮助使用
