### ISSUE TITLE
镜像请求：Vagrant centos/7 box

### ISSUE THREAD

**Issue by uzxmx** [tuna/issues#796]
现在清华大学的开源软件镜像站中已经包含了 Vagrant Ubuntu box, 例如：https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/bionic/current/bionic-server-cloudimg-amd64-vagrant.box ，但是却不包含Vagrant Centos box。Centos box和Ubuntu box一样，都是开发人员本地开发、测试或研究人员研究时受欢迎的选择。

Centos 7 box在Vagrant的官方网站的地址是[这个](https://app.vagrantup.com/centos/boxes/7)，但实际下载地址是被重定向到了cloud.centos.org，cloud.centos.org在国内下载速度 ~20KB/s，一个系统镜像大概400M。

上游源地址：https://cloud.centos.org/centos/7/vagrant/x86_64/images/
镜像大小：每个系统镜像在400~500M，总共大约61G

**Comment by z4yx** [comment]
合并到 #222 讨论。
