### ISSUE TITLE
anaconda镜像下载大文件频繁出错

### ISSUE THREAD

**Issue by HearyShen** [tuna/issues#797]
#### 发生了什么（What happened）

例如：conda install cudatoolkit (conda update --all)时，下载300MB+的cudatoolkit频频出错。

具体地，

```
(pytorch) C:\Users\heary>conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\heary\Miniconda3\envs\pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.2.89        |       h74a9793_0       316.9 MB  defaults
    ------------------------------------------------------------
                                           Total:       316.9 MB

The following packages will be UPDATED:

  cudatoolkit                           10.1.243-h74a9793_0 --> 10.2.89-h74a9793_0
  pytorch                      1.4.0-py3.7_cuda101_cudnn7_0 --> 1.5.0-py3.7_cuda102_cudnn7_0
  torchvision                              0.5.0-py37_cu101 --> 0.6.0-py37_cu102


Proceed ([y]/n)? y


Downloading and Extracting Packages
cudatoolkit-10.2.89  | 316.9 MB  | ############5                                                                |  16%

CondaError: Downloaded bytes did not match Content-Length
  url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/cudatoolkit-10.2.89-h74a9793_0.conda
  target_path: C:\Users\heary\Miniconda3\pkgs\cudatoolkit-10.2.89-h74a9793_0.conda
  Content-Length: 332249563
  downloaded bytes: 54820524


```

#### 期望的现象（What you expected to happen）

应该要能正常下载，安装。

#### 如何重现（How to reproduce it）

几乎大多数重试都是下载断开，表现为content-length不足或condaHTTPError。

#### 其他事项（Anything else we need to know）

小型文件正常，该问题只在下载大文件时频繁出现。

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows10 Home, 1909
- 浏览器（如果适用）（Browser version, if applicable）：Edge 81
- 其他（Others）：miniconda, 江苏联通宽带

**Comment by z4yx** [comment]
非教育网用户访问清华镜像站如果存在网络问题，可以提供traceroute信息，我们帮忙向ISP反映。

**Comment by HearyShen** [comment]
> 非教育网用户访问清华镜像站如果存在网络问题，可以提供traceroute信息，我们帮忙向ISP反映。

```
C:\Users\heary>tracert mirrors.tuna.tsinghua.edu.cn

通过最多 30 个跃点跟踪
到 cdnmirrors.s.tuna.tsinghua.edu.cn [101.6.8.193] 的路由:

  1     1 ms    <1 毫秒   <1 毫秒 XiaoQiang [192.168.31.1]
  2     4 ms    14 ms     7 ms  100.122.152.1
  3    13 ms    13 ms     *     58.240.160.93
  4    31 ms    37 ms    12 ms  58.240.161.169
  5    27 ms    25 ms    24 ms  219.158.96.161
  6    31 ms    29 ms    34 ms  219.158.3.66
  7    34 ms    34 ms    38 ms  219.158.40.62
  8     *       29 ms    29 ms  101.4.116.65
  9    31 ms    32 ms    51 ms  101.4.113.201
 10    32 ms    30 ms    30 ms  202.112.38.10
 11    34 ms    30 ms    39 ms  118.229.4.10
 12    29 ms    31 ms    29 ms  118.229.2.130
 13     *        *        *     请求超时。
 14    31 ms    31 ms    31 ms  101.6.8.193

跟踪完成。

```

**Comment by z4yx** [comment]
@shankerwangmiao 该你上场了

**Comment by albertix** [comment]
wget 直接下载archive报错

```
wget.exe https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.02-Windows-x86_64.exe -O D:\apps\conda-2020.02-Windows-x86_64.exe
--2020-04-24 16:28:26--  https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.02-Windows-x86_64.exe
Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.8.193, 2402:f000:1:408:8100::1
Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.8.193|:443... connected.
ERROR: cannot verify mirrors.tuna.tsinghua.edu.cn's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to mirrors.tuna.tsinghua.edu.cn insecurely, use `--no-check-certificate'.
```

**Comment by z4yx** [comment]
> wget 直接下载archive报错
> 
> ```
> wget.exe https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.02-Windows-x86_64.exe -O D:\apps\conda-2020.02-Windows-x86_64.exe
> --2020-04-24 16:28:26--  https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.02-Windows-x86_64.exe
> Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.8.193, 2402:f000:1:408:8100::1
> Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.8.193|:443... connected.
> ERROR: cannot verify mirrors.tuna.tsinghua.edu.cn's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
>   Unable to locally verify the issuer's authority.
> To connect to mirrors.tuna.tsinghua.edu.cn insecurely, use `--no-check-certificate'.
> ```

你的这个现象不是网络问题，是由于你的系统中缺少LE的CA根证书。

**Comment by shankerwangmiao** [comment]
@HearyShen 请再尝试一下，看看问题还是否存在？

**Comment by HearyShen** [comment]
> @HearyShen 请再尝试一下，看看问题还是否存在？

@shankerwangmiao 

试了一下，问题依旧存在。

```
Downloading and Extracting Packages
pytorch-1.3.1        | 479.7 MB  | ########################################################2                    |  74%

CondaError: Downloaded bytes did not match Content-Length
  url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/pytorch-1.3.1-py3.7_cuda101_cudnn7_0.tar.bz2
  target_path: C:\Users\heary\Miniconda3\pkgs\pytorch-1.3.1-py3.7_cuda101_cudnn7_0.tar.bz2
  Content-Length: 502969208
  downloaded bytes: 372424365
```

**Comment by shankerwangmiao** [comment]
您下载出问题的文件时，在出现中断情况之前的下载速度是多少？

**Comment by HearyShen** [comment]
> 您下载出问题的文件时，在出现中断情况之前的下载速度是多少？

@shankerwangmiao 

通常刚开始下载时比较快，快的时候能超过4MB/s左右，下载过程中会在1.5MB/s ~ 3.5MB/s之间波动，中断的时候往往挺突然的，大概降到几百KB/s，就停了。

另外，昨天下载的包经过反复重试，已经完成下载安装。感觉大概是七八次里能成功一次的概率。

**Comment by skychan** [comment]
教育网用户也常常出现断流问题，但如果是 ipv6，就基本没问题，ipv4 遇到大文件，会有大概率断流。

**Comment by phy25** [comment]
> 教育网用户也常常出现断流问题，但如果是 ipv6，就基本没问题，ipv4 遇到大文件，会有大概率断流。

北京教育网基本正常（中间会有一两秒钟速度变为 0 但连接没有断开）：

```console
# curl -4 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/pytorch-1.3.1-py3.7_cuda101_cudnn7_0.tar.bz2 >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  479M  100  479M    0     0  2195k      0  0:03:43  0:03:43 --:--:-- 2713k
```

**Comment by z4yx** [comment]
建议尝试下 **https://mirrors.bfsu.edu.cn/anaconda/**
内容与清华镜像是完全一样的

**Comment by skychan** [comment]
> 建议尝试下 **https://mirrors.bfsu.edu.cn/anaconda/**
> 内容与清华镜像是完全一样的

哈哈哈，这个是整个克隆吗，我试试，感谢

**Comment by skychan** [comment]
> > 教育网用户也常常出现断流问题，但如果是 ipv6，就基本没问题，ipv4 遇到大文件，会有大概率断流。
> 
> 北京教育网基本正常（中间会有一两秒钟速度变为 0 但连接没有断开）：
> 
> ```
> # curl -4 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/pytorch-1.3.1-py3.7_cuda101_cudnn7_0.tar.bz2 >/dev/null
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  479M  100  479M    0     0  2195k      0  0:03:43  0:03:43 --:--:-- 2713k
> ```

杭州地区的教育网，有时会断

**Comment by z4yx** [comment]
> > 建议尝试下 **https://mirrors.bfsu.edu.cn/anaconda/**
> > 内容与清华镜像是完全一样的
> 
> 哈哈哈，这个是整个克隆吗，我试试，感谢

是的，影子站点，给主站分流哈哈

**Comment by wgfi110** [comment]
tracepath mirrors.tuna.tsinghua.edu.cn
 1?: [LOCALHOST]                                         pmtu 1420
 1:  10.82.242.177                                         8.566ms
 1:  10.82.242.177                                         1.574ms
 2:  10.82.243.129                                         9.222ms
 3:  10.82.243.94                                          9.709ms
 4:  10.82.245.138                                         0.315ms
 5:  no reply
 6:  no reply
 7:  no reply
 8:  no reply
 9:  no reply
10:  no reply
11:  no reply

**Comment by shankerwangmiao** [comment]
> tracepath mirrors.tuna.tsinghua.edu.cn
> 1?: [LOCALHOST] pmtu 1420
> 1: 10.82.242.177 8.566ms
> 1: 10.82.242.177 1.574ms
> 2: 10.82.243.129 9.222ms
> 3: 10.82.243.94 9.709ms
> 4: 10.82.245.138 0.315ms
> 5: no reply
> 6: no reply
> 7: no reply
> 8: no reply
> 9: no reply
> 10: no reply
> 11: no reply

这个是您那侧网络的问题，请与您的网路管理员联系

**Comment by Stonesjtu** [comment]
> 建议尝试下 **https://mirrors.bfsu.edu.cn/anaconda/**
> 内容与清华镜像是完全一样的

@z4yx 这个镜像在我这里的速度非常快，感谢。
