### ISSUE TITLE
镜像请求: Julia PkgServer

### ISSUE THREAD

**Issue by zhiyuanzhai** [tuna/issues#798]
#### 项目名称与简介(Project Intro.)

近期Julia语言正式更新到v1.4.0版本, 新增加PkgServer的功能, 允许从镜像站下载Julia语言的包. 详情可参阅[Julia中文社区的置顶帖](https://discourse.juliacn.com/t/topic/2969/2).

PkgServer.jl GitHub地址: [https://github.com/JuliaPackaging/PkgServer.jl](https://github.com/JuliaPackaging/PkgServer.jl)

#### 上游地址与镜像方法(How to Mirror)

可参阅GitHub项目下的"Deployment"目录: [https://github.com/JuliaPackaging/PkgServer.jl/tree/master/deployment](https://github.com/JuliaPackaging/PkgServer.jl/tree/master/deployment)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 未知. 但似乎不大.

**Comment by z4yx** [comment]
看了一下 PkgServer 本质是一个反代程序，根据网站政策（置顶issue），我们不接受反代型镜像。

**Comment by zhiyuanzhai** [comment]
> 看了一下 PkgServer 本质是一个反代程序，根据网站政策（置顶issue），我们不接受反代型镜像。

好吧, 这个确实不太懂. 我关了
