### ISSUE TITLE
建议新增FreeBSD portsnap源

### ISSUE THREAD

**Issue by ykla** [tuna/issues#799]
#### 项目名称与简介(Project Intro.)
FreeBSD 是重要的类UNIX操作系统，portsnap是ports源的打包集合，目前国内尚无镜像。

#### 上游地址与镜像方法(How to Mirror)
https://github.com/ykla/freebsd-mirrors/blob/master/fetchportsnap
使用了lftp方法portsnap.FreeBSD.org
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by shankerwangmiao** [comment]
dup with #16
