### ISSUE TITLE
镜像访问不了

### ISSUE THREAD

**Issue by xgdgsc** [tuna/issues#8]
DNS解析不了，能解析的IP也访问不了

**Comment by bigeagle** [comment]
这几天各个服务器和各个网络接口轮流挂，每天挂一个，修好一个挂第二个…… 心累。
目前的情况是DNS权威服务器和镜像站、web所在的整个网段都挂了，原因比较玄学，事发的时候已经下班了，等明天吧，我们会去机房调整。
