### ISSUE TITLE
建议新增 FreeBSD Update源

### ISSUE THREAD

**Issue by ykla** [tuna/issues#800]
#### 项目名称与简介(Project Intro.)
FreeBSD 的 Update源是 FreeBSD的更新源，通过该源可达到升级系统，安装安全更新的作用。
#### 上游地址与镜像方法(How to Mirror)
http://update3.freebsd.org/ 目前放开了浏览权限。
脚本见https://github.com/ykla/freebsd-mirrors/blob/master/fetchupdate

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by shankerwangmiao** [comment]
dup with #16
