### ISSUE TITLE
[tuna]404 at /anaconda/plotly/noarch/repodata.json

### ISSUE THREAD

**Issue by wenqiushi** [tuna/issues#801]
#### 发生了什么（What happened）
https://mirrors.tuna.tsinghua.edu.cn/anaconda/plotly/noarch/repodata.json
无法获取镜像plotly库
#### 期望的现象（What you expected to happen）
希望修复之
#### 如何重现（How to reproduce it）
conda install -c plotly plotly-orca
#### 其他事项（Anything else we need to know）
-
#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu18.04LTS
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
正确地址是 https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/plotly/noarch/repodata.json
