### ISSUE TITLE
/voidlinux/docs HTTP 403 error

### ISSUE THREAD

**Issue by kad09** [tuna/issues#802]
#### 发生了什么（What happened）
https://mirrors.tuna.tsinghua.edu.cn/voidlinux/docs/ shows 403 error. Judging by /voidlinux index this directory doesn't get updated. It also keeps appearing/disappearing from /voidlinux index page
#### 期望的现象（What you expected to happen）
Should display void linux handbook, like this https://alpha.us.repo.voidlinux.org/docs/
#### 如何重现（How to reproduce it）
Visit /voidlinux/docs
#### 您的环境（Environment）
- 操作系统（OS Version）：Any
- 浏览器（如果适用）（Browser version, if applicable）：Any
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
Actually, `docs/` is excluded on our server on purpose.
