### ISSUE TITLE
建议增加VLC Android版下载二维码

### ISSUE THREAD

**Issue by leonardyan** [tuna/issues#803]
如题，建议在安装镜像下载中的VLC播放器下载页面添加最新版Android VLC下载链接和二维码，方便手机用户下载。VLC手机版貌似在很多国内安卓应用市场都没有，至少我用的酷安和我妈用的小米市场都没有

**Comment by shankerwangmiao** [comment]
您好，通过二维码传递 URL 是一种低效的方法。我们会尽快在“获取下载链接”中增添 VLC 安卓版本的链接，之后您可以直接点击链接下载。
