### ISSUE TITLE
[tuna]404 at /jenkins/war/2.222.3/jenkins.war

### ISSUE THREAD

**Issue by chen645800876** [tuna/issues#808]
#### 发生了什么（What happened）
jenkins提示更新，然而，更新链接返回404
![image](https://user-images.githubusercontent.com/24761804/80301925-8ce9b180-87d9-11ea-8394-b16343012727.png)

#### 期望的现象（What you expected to happen）
上传最新的jenkins包
#### 如何重现（How to reproduce it）
<https://mirrors.tuna.tsinghua.edu.cn/jenkins/war/2.222.3/jenkins.war>
此为更新链接，反回404
#### 您的环境（Environment）
- 操作系统（OS Version）：
deepin_v20
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
文件是自动从上游同步的，一般新版本加入会有一段时间延迟。
