### ISSUE TITLE
镜像请求：openmediavault

### ISSUE THREAD

**Issue by EvineDeng** [tuna/issues#810]
#### 项目名称与简介(Project Intro.)
项目名称：openmediavault
项目简介：openmediavault是一个开源的基于Debian Linux的下一代网络附加存储（NAS）解决方案。一般简称为OMV，由德国人Volker Theile于2009年开始开发，Volker Theile曾经是FreeNAS的开发者之一。openmediavault包含众多服务，如SSH、(S)FTP、SMB/CIFS、DAAP媒体服务器、RSync、BitTorrent客户机等。 并具有通过插件可增强的模块化设计框架特性。

#### 上游地址与镜像方法(How to Mirror)
我在官方论坛了解了下情况，不管是官方软件仓库还是第三方软件仓库，都没有启用rsync，但因为是debian系，所以可以使用apt-mirror镜像仓库工具同步，软件包主要分为两部分：
- 官方软件、插件仓库：https://packages.openmediavault.org/
- 第三方插件仓库（也称作OMV-Extras仓库）：https://dl.bintray.com/openmediavault-plugin-developers/

上述官方软件、插件仓库还有一个备用地址：[sourceforge](https://downloads.sourceforge.net/project/openmediavault/)，备用地址的下一级目录packages就是官方软件、插件仓库，除此之外，这个备用地址还包括openmediavault的所有iso安装包文件。

#### 其他信息(Other)
- 镜像大小(Mirror Size): 如不同步备用地址中的iso安装文件，我估计10G以下；如同步备用地址中的iso安装文件，我估计100G以下。
- 官方的安装使用说明：
1. 总纲：https://openmediavault.readthedocs.io/en/5.x/installation/index.html
2. 基于debian安装：https://openmediavault.readthedocs.io/en/5.x/installation/on_debian.html
- 我现在运行的openmediavault软件源配置文件如下，供参考：
1. /etc/apt/sources.list.d/omvextras.list
```
deb https://dl.bintray.com/openmediavault-plugin-developers/usul buster main
deb [arch=amd64] https://download.docker.com/linux/debian buster stable #这个与OMV本身无关
deb http://linux.teamviewer.com/deb stable main #这个与OMV本身无关
deb https://dl.bintray.com/openmediavault-plugin-developers/usul-testing buster main
deb https://dl.bintray.com/openmediavault-plugin-developers/usul-extras buster main
```

2. /etc/apt/sources.list.d/openmediavault.list
```
deb https://packages.openmediavault.org/public usul main
# deb https://downloads.sourceforge.net/project/openmediavault/packages usul main

## Uncomment the following line to add software from the proposed repository.
deb https://packages.openmediavault.org/public usul-proposed main
# deb https://downloads.sourceforge.net/project/openmediavault/packages usul-proposed main

## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
deb https://packages.openmediavault.org/public usul partner
# deb https://downloads.sourceforge.net/project/openmediavault/packages usul partner
```
- 国内暂时没有发现任何一家开源镜像站点有同步openmediavault

**Comment by z4yx** [comment]
dup with #629

**Comment by EvineDeng** [comment]
那能请求同步extras仓库吗。

**Comment by shankerwangmiao** [comment]
请至 #629 讨论。

**Comment by z4yx** [comment]
既然地址发在这里了就顺便说了吧，看起来extra也是apt源，应该没问题，我尝试加到脚本里面

**Comment by EvineDeng** [comment]
好哒，多谢大佬们。

**Comment by z4yx** [comment]
我发现两个仓库的结构不一样，官方源的dists下面是ovm自己的版本号（usul等），而extra的dists是debian的版本号（buster等），为什么会有这个区别？extra是可以在标准debian上面安装吗？

**Comment by EvineDeng** [comment]
> 我发现两个仓库的结构不一样，官方源的dists下面是ovm自己的版本号（usul等），而extra的dists是debian的版本号（buster等），为什么会有这个区别？extra是可以在标准debian上面安装吗？

omv和omv-extras都可以在标准debian中安装，但一般是将omv-extras基于omv安装，omv-extras也要基于不同的omv版本来安装不同的内容。omv采用了自己的版本号，虽然有自己的版本号，但其实也是和debian一一对应的，比如它的usul就对应debian的buster，在omv中安装omv-extras采用他们提供的脚本自动安装时，也会识别omv版本进而自动在源list文件中生成对应的版本号，只是确实omv-extras没有采用omv的版本，我也不清楚为什么。

**Comment by z4yx** [comment]
明白了。现在正在同步，地址为 https://mirrors.bfsu.edu.cn/OpenMediaVault/openmediavault-plugin-developers/
