### ISSUE TITLE
镜像请求：Open CASCADE Technology

### ISSUE THREAD

**Issue by eryar** [tuna/issues#811]
项目名称: 
    Open CASCADE Technology
项目简介: 
   Open CASCADE（简称OCC）平台是由法国Matra Datavision公司开发的CAD/CAE/CAM软件平台，可以说是世界上最重要的几何造型基础软件平台之一。开源OCC对象库是一个面向对象C++类库，用于快速开发设计领域的专业应用程序。
   OCC是目前世界上唯一一个三维建模、造型功能较完善的开源类库。

协议：
GNU LGPL version 2.1.
https://dev.opencascade.org/doc/overview/html/occt_public_license.html

上游源地址，或镜像方法
http://git.dev.opencascade.org/gitweb/?p=occt.git

谢谢。

**Comment by z4yx** [comment]
没有找到公开的（git协议）同步地址
