### ISSUE TITLE
"Raspbian 镜像使用帮助" 存在拼写错误

### ISSUE THREAD

**Issue by NKID00** [tuna/issues#812]
#### 发生了什么（What happened）
[Raspbian 镜像使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/raspbian/) 这份文档中 `Raspbian 简介` 这一节的第四段中间的 `The Raspbeery Pi Foundation` 拼写错误（应将 `Raspbeery` 改为 `Raspberry`）
#### 期望的现象（What you expected to happen）
改为 `The Raspberry Pi Foundation`
#### 如何重现（How to reproduce it）
点击镜像列表中 `raspbian` 一项右侧的问号
#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 专业版 1909
- 浏览器（如果适用）（Browser version, if applicable）：Mozilla FireFox 75.0 (64 位)
- 其他（Others）：移动LJ宽带

**Comment by z4yx** [comment]
感谢指出，已更正。
