### ISSUE TITLE
[tuna]404 at /cc/8

### ISSUE THREAD

**Issue by tuhep** [tuna/issues#814]
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
```
$ rsync rsync://linuxsoft.cern.ch/cc/8/
rsync: change_dir "/8" (in cc) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1651) [Receiver=3.1.2]
```

上游的rsync没有这个目录（准确的说是符号链接指向了不存在的目录），建议向CERN报告问题。

**Comment by phy25** [comment]
这个问题看起来已经解决了？https://mirrors.tuna.tsinghua.edu.cn/cc/8/ 已经可以访问了。
