### ISSUE TITLE
openSUSE software mirror wanted (will be closed after 60 days inactivity)

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#815]
#### 项目名称与简介(Project Intro.)
openSUSE是一个一般用途的基于Linux内核的GNU/Linux操作系统，由openSUSE项目社区开发维护，该项目由SUSE等公司赞助。在2004年2月Novell收购SUSE Linux之后，Novell决定以100%开源产品发布SUSE Linux专业版，并作为一个开源项目，openSUSE继承与SUSE Linux Professional。SUSE提供基于openSUSE的企业级产品SUSE Linux Enterprise。openSUSE项目除了提供一个发行版，还包括一个Open Build Service，openSUSE的目的是提供提供一个稳定的基础并让用户通过Open Build Service得到额外的更多更新的软件，甚至是一个滚动发行的版本命为Tumbleweed。系统默认KDE作为图形环境，当然GNOME也是很不错的，其他也有Xfce、LXDE等图形环境。
openSUSE是著名Novell公司旗下的 Linux的发行版，发行量在欧洲占第一位。它采用的KDE5作为默认桌面环境，同时也提供GNOME桌面版本。它的软件包管理系统采用RPM和自主开发的zypper，而且提供了一个管理系统和zypper的特色工具—YaST，这些工具颇受好评。他的用户界面非常华丽，甚至超越windows7，而且性能良好，最新版本是openSUSE Leap 15。
#### 上游地址与镜像方法(How to Mirror)
http://download.opensuse.org/
#### 其他信息(Other)
- 镜像大小(Mirror Size): This will be pretty big.About 750GB

**Comment by jiegec** [comment]
https://mirrors.tuna.tsinghua.edu.cn/opensuse/

**Comment by sysdl132** [comment]
--THE NEW COMMENTS ARE NOT ACCEPTED HERE--

**Comment by sysdl132** [comment]
@jiegec Please lock this issue.
