### ISSUE TITLE
支持openEuler的镜像Mirror

### ISSUE THREAD

**Issue by TommyLike** [tuna/issues#818]
#### 项目名称与简介(Project Intro.)
openEuler: openEuler是华为开源的操作系统发型版本
1. 具体官网: https://openeuler.org
2. repo源地址: http://openeuler-repo.huawei.com/

#### 上游地址与镜像方法(How to Mirror)

支持rsync
rsync -av --partial --progress   rsync://root@openeuler-repo.huawei.com/openeuler
秘钥信息: root:openeuler@1234 (只读)

**Comment by Harry-Chen** [comment]
能告知具体的镜像大小吗？

**Comment by TommyLike** [comment]
> 能告知具体的镜像大小吗？

当前repo源内包含rpm和ISO，差不多100G的样子

**Comment by z4yx** [comment]
已开始同步

**Comment by TommyLike** [comment]
> 已开始同步

多谢！ 我们自己创建的mirror站点在同步的时候可能存在同步缓慢或者卡主的问题，不知道是不是跟我们的带宽或者rsync配置参数有关系。

**Comment by z4yx** [comment]
已经同步好了 https://mirrors.tuna.tsinghua.edu.cn/openeuler/
这是我们用的参数，供参考 `rsync -aHvh --no-o --no-g --stats --exclude .~tmp~/ --delete --delete-after --delay-updates --safe-links`

**Comment by shankerwangmiao** [comment]
@TommyLike 上述 rsync 服务已经失效，不知道是否有任何变化？

**Comment by TommyLike** [comment]
@shankerwangmiao 
非常抱歉，最近其他事情比较多，github消息没有及时处理，导致沟通有延迟！
**问题**: 去年底我们内部对安全做过一次排查，因为List目录的原因，域名映射取消，导致没法解析失败。
**修复**: 我们上游的源使用的IP固定是**121.36.97.194**不会变更, 麻烦通过IP来同步吧。
如果后续有其他紧急问题，可以直接邮箱联系， tommylikehu@gmail.com 或者hu.husheng@huawei.com

**Comment by TommyLike** [comment]
@z4yx 请帮忙更正下。

**Comment by shankerwangmiao** [comment]
您好，目前的话我们暂时无法重新上线 openEuler，因为磁盘空间不是很充足了。

**Comment by TommyLike** [comment]
@shankerwangmiao 那是等待你们扩充磁盘后可以上线吗？ 预计会多久呢？

**Comment by shankerwangmiao** [comment]
是的，会安排在扩充磁盘之后。但是目前就扩充磁盘而言，受限于不可控外界因素，暂时没有时间表。

**Comment by TommyLike** [comment]
@shankerwangmiao 好的，确实比较占用空间，你们接受捐赠吗？具体的流程是怎样呢？

**Comment by shankerwangmiao** [comment]
您好，感谢您对 TUNA 的支持。目前关于存储的优化我们已经有一些进展了。

**Comment by TommyLike** [comment]
@shankerwangmiao 十分感谢，还麻烦在有进展的情况下知会下。

**Comment by TommyLike** [comment]
@shankerwangmiao @z4yx sorry to bother you again, could you please share some progess ?

**Comment by shankerwangmiao** [comment]
您好，扩容完成后我们会第一时间恢复该镜像。目前扩容的事项已经在规划中。

**Comment by TommyLike** [comment]
> 您好，扩容完成后我们会第一时间恢复该镜像。目前扩容的事项已经在规划中。

多谢！ @shankerwangmiao 考虑到当前的社区源的上线时间不确定，能否在发布的消息中做下补充说明呢？  
https://github.com/tuna/mirror-web/pull/237

**Comment by TommyLike** [comment]
@shankerwangmiao 你好请问现在进展如何呢？

**Comment by shankerwangmiao** [comment]
> @shankerwangmiao 你好请问现在进展如何呢？

您好，目前并无更新的消息与您分享。

**Comment by TommyLike** [comment]
> > @shankerwangmiao 你好请问现在进展如何呢？
> 
> 您好，目前并无更新的消息与您分享。

新年好，咨询下能否提供源的上线时间呢？

**Comment by shankerwangmiao** [comment]
> > > @shankerwangmiao 你好请问现在进展如何呢？
> > 
> > 
> > 您好，目前并无更新的消息与您分享。
> 
> 新年好，咨询下能否提供源的上线时间呢？

新年好，目前并无更新的消息与您分享。

**Comment by xin3liang** [comment]
请问目前rsync mirror的方法是什么呢？ rsync://repo.openeuler.org/ 好像不能mirror

**Comment by xin3liang** [comment]
> 请问目前rsync mirror的方法是什么呢？ rsync://repo.openeuler.org/ 好像不能mirror

@shankerwangmiao

**Comment by xin3liang** [comment]
请问目前rsync mirror的方法是什么呢？ rsync://repo.openeuler.org/ 好像不能mirror
@TommyLike

**Comment by xin3liang** [comment]
> 请问目前rsync mirror的方法是什么呢？ rsync://repo.openeuler.org/ 好像不能mirror
> @TommyLike

Try bellow cmds, finally it works. Thanks.

export RSYNC_PASSWORD='openeuler@1234'
rsync -rltvz --progress rsync://root@121.36.97.194/openeuler /home/ubuntu/tmp/openeuler

**Comment by TommyLike** [comment]
@xin3liang 意思是咱们的镜像站点在tuna上面恢复了吗？

**Comment by Harry-Chen** [comment]
> @xin3liang 意思是咱们的镜像站点在tuna上面恢复了吗？

这位与 TUNA 没有关系。我们目前刚刚获得了新的镜像服务器，但遭遇了一些硬件故障。在服务器恢复可用之后，我们会继续计划中的上线操作。

**Comment by TommyLike** [comment]
> > @xin3liang 意思是咱们的镜像站点在tuna上面恢复了吗？
> 
> 这位与 TUNA 没有关系。我们目前刚刚获得了新的镜像服务器，但遭遇了一些硬件故障。在服务器恢复可用之后，我们会继续计划中的上线操作。

多谢！

**Comment by xin3liang** [comment]
> > > @xin3liang 意思是咱们的镜像站点在tuna上面恢复了吗？
> > 
> > 
> > 这位与 TUNA 没有关系。我们目前刚刚获得了新的镜像服务器，但遭遇了一些硬件故障。在服务器恢复可用之后，我们会继续计划中的上线操作。
> 
> 多谢！

不好意思搞错了，以为这是openEuler官网讨论mirror 的issue。我确实有几个问题关于openEuler repo mirror的，不知道在哪里讨论好呢？@TommyLike

**Comment by TommyLike** [comment]
@xin3liang 可以直接给我们发邮件哈 infra@openeuler.org

**Comment by xin3liang** [comment]
> @xin3liang 可以直接给我们发邮件哈 [infra@openeuler.org](mailto:infra@openeuler.org)

OK, 多谢~

**Comment by GeorgeCao-hw** [comment]
@Harry-Chen 
@shankerwangmiao 
hi，麻烦问下，近期有恢复上线openEuler镜像的计划了吗 ^-^
谢谢

**Comment by shankerwangmiao** [comment]
已经恢复。

**Comment by TommyLike** [comment]
十分感谢 @shankerwangmiao

**Comment by TommyLike** [comment]
@shankerwangmiao 我们也想捐赠一批硬件，请问有具体的联系方式吗？
