### ISSUE TITLE
[tuna]404 at /anaconda/default

### ISSUE THREAD

**Issue by lucksufe** [tuna/issues#819]
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by lucksufe** [comment]
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: default
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/default
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by shankerwangmiao** [comment]
请提供 conda 的 channel 配置。您填写的 URL 并不存在。

**Comment by z4yx** [comment]
请按帮助页面配置 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/
