### ISSUE TITLE
[ASOP] platform/cts

### ISSUE THREAD

**Issue by fashioncj** [tuna/issues#82]
repo sync --force-sync  platform/cts
Fetching project platform/cts
fatal: unable to connect to aosp.tuna.tsinghua.edu.cn:
aosp.tuna.tsinghua.edu.cn[0: 2001:da8:20f:3101:5054:ff:feb1:be95]: errno=拒绝连                                                                                                                                                             接
aosp.tuna.tsinghua.edu.cn[1: 166.111.206.63]: errno=拒绝连接

**Comment by bigeagle** [comment]
git 协议已作废，请使用 https 协议同步。
参考 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/

**Comment by fashioncj** [comment]
ok- -
sync success
