### ISSUE TITLE
【镜像请求】OPNsense

### ISSUE THREAD

**Issue by zzzz0317** [tuna/issues#820]
#### 项目名称与简介(Project Intro.)
OPNsense 是由Deciso 开发的开源、基于 FreeBSD 的防火墙和路由软件，Deciso 是一家位于荷兰的公司，为 OPNsense 生产硬件并销售支持包。它是pfSense 的一个分支

#### 上游地址与镜像方法(How to Mirror)
官方 https://pkg.opnsense.org/
Cloudflare镜像 https://mirror.dns-root.de/opnsense/
官网给出的China源在香港，速度很慢 https://opnsense.aivian.org/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by laozhoubuluo** [comment]
Official Rsync URL: rsync://rsync.opnsense.org

**Comment by z4yx** [comment]
同步完成 https://mirrors.bfsu.edu.cn/opnsense/
