### ISSUE TITLE
solus install images mirror request

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#821]
#### 项目名称与简介(Project Intro.)
solus OS install images
(the current mirror is about its software packages)
#### 上游地址与镜像方法(How to Mirror)
http://mirrors.rit.edu/solus/images/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
about 20 GB

**Comment by z4yx** [comment]
已调整同步配置。目录结构发生变化，用符号链接保持原用户兼容性。
