### ISSUE TITLE
[tuna]404 at /ubuntu/dists/focal/main/binary-arm64/Packages

### ISSUE THREAD

**Issue by 0x11-dev** [tuna/issues#823]
#### 发生了什么（What happened）
404无法加载

#### 期望的现象（What you expected to happen）
正常加载

#### 如何重现（How to reproduce it）
在arm64位设备上启用qsinghua源

#### 您的环境（Environment）
- 操作系统（OS Version）：ubuntu20.04 Linux ubuntu 5.4.0-1008-raspi #8-Ubuntu SMP Wed Apr 8 11:13:06 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
arm64 设备上请使用 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/
