### ISSUE TITLE
arm64 出错 apt update

### ISSUE THREAD

**Issue by zzc1231** [tuna/issues#826]
Ign:63 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Fetched 357 kB in 9s (38.9 kB/s)
Reading package lists... Done
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal/main/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-updates/main/binary-arm64/Packages
404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-backports/universe/binary-arm64/Packages  404  Not Found [IP: 101.6.8.193 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-security/main/binary-arm64/Packages
 404  Not Found [IP: 101.6.8.193 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by phy25** [comment]
Duplicate with #823.
