### ISSUE TITLE
Can we build Funtoo mirror here?

### ISSUE THREAD

**Issue by urbainy** [tuna/issues#828]
Funtoo is a Gentoo like distro of Linux, but providing easy usage and more stable debian kernel as default. Till now, there is no mirror of Funtoo in China mainland, this blocks Chinese users to try this funny distro. Could you help to make a mirror for Funtoo? If you need my help, I'd like to contribute.

Thanks!

**Comment by phy25** [comment]
Honestly the first thing you want to do is to fill in the blanks in the issue template:

```
<!--
如果你希望 TUNA 对某个开源项目设立镜像，请按以下模板填写

If you request TUNA to setup a mirror site for an open-source project, please submit you issue using the following template.
-->

#### 项目名称与简介(Project Intro.)

#### 上游地址与镜像方法(How to Mirror)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
```

**Comment by Harry-Chen** [comment]
See #11. We need to know how to mirror it.

**Comment by urbainy** [comment]
I give up to use Funtoo, so I'd better close the issue.

**Comment by damon-kwok** [comment]
@urbainy 
see: https://gitee.com/funtoo
``` sh
echo "sync_base_url = https://gitee.com/funtoo/{repo}" >> /etc/ego.conf 
```

**Comment by damon-kwok** [comment]
@Harry-Chen 
It's easy to mirror `Futoo`. You just need to synchronize with the repository of `github.com/futoo`.

Users only need to:
```
echo "sync_base_url = https://balabala.com/funtoo/{repo}" >> /etc/ego.conf 
```

**Comment by urbainy** [comment]
Thank you, damon-kwok!
The main issue is that I live in China. So I access github with very low speed. Chinese users really need a mirror in China domestic to get high speed. Manjaro and some other systems do this well.
Further, for long time I didn't get help from how to create a real mirror. I don't have too much time to wait. I need to go ahead.
And Funtoo needs very large space (20G) to compile the new kernel. I really don't have because the reason I use Funtoo/Gentoo is I don't have expensive machine.
And Funtoo's repo is older than Gentoo. 
So although Gentoo's kernel is really a hard stone, I intend to spend some time to conquer it. Or I could try some other dists.
