### ISSUE TITLE
pypi and ruby error

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#829]
#### 发生了什么（What happened）
directory can't show
#### 期望的现象（What you expected to happen）
file directory show
#### 如何重现（How to reproduce it）
[follow this link](https://mirrors.tuna.tsinghua.edu.cn/pypi/web/pypi/)
[and this link](https://mirrors.tuna.tsinghua.edu.cn/rubygems/gems/)
#### 您的环境（Environment）
- 操作系统（OS Version）：windows 10
- 浏览器（如果适用）（Browser version, if applicable）：  msedge (with chromium 80)
- 其他（Others）：None

**Comment by sysdl132** [comment]
Got it.There are too many files there.Can you make them show?

**Comment by Harry-Chen** [comment]
No due to performance issues.
