### ISSUE TITLE
[Mirror request]Git mirror request

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#830]
#### 项目名称与简介(Project Intro.)
git:是一个开源的分布式版本控制系统，可以有效、高速地处理从很小到非常大的项目版本管理
~~gitea: a painless self-hosted git service~~
#### 上游地址与镜像方法(How to Mirror)
https://github.com/git-for-windows/git/releases
https://dl.gitea.io/
#### 其他信息(Other)
- 镜像大小(Mirror Size): git: about 10GB
                                       gitea: about 20GB

**Comment by z4yx** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/git-for-windows/git/LatestRelease/

**Comment by z4yx** [comment]
gitea 暂无同步方式
