### ISSUE TITLE
软件链接失效

### ISSUE THREAD

**Issue by guispor7** [tuna/issues#831]
#### 发生了什么（What happened）
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/jpeg-9b-vc14_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/libtiff-4.0.9-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/qt-5.6.2-vc14_1.tar.bz2
3个下载链接失效

**Comment by z4yx** [comment]
上述文件由于版本太老，已被删除。服务器只保留索引（repodata.json）中存在的文件。

**Comment by guispor7** [comment]
> 
> 
> 上述文件由于版本太老，已被删除。服务器只保留索引（repodata.json）中存在的文件。

请问repodata.json在哪获取？想查找新版本的软件名字

**Comment by z4yx** [comment]
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64/repodata.json
