### ISSUE TITLE
anaconda 请求添加cudf的源

### ISSUE THREAD

**Issue by yuanzhiroc** [tuna/issues#832]
#### 上游地址与镜像方法(How to Mirror)

GitHub：https://github.com/rapidsai/cudf
conda：https://anaconda.org/rapidsai/repo
              https://anaconda.org/rapidsai-nightly/repo

**Comment by z4yx** [comment]
已添加到 https://neomirrors.tuna.tsinghua.edu.cn/anaconda/cloud/rapidsai/
nightly build 由于更新过于频繁，我们一般不镜像。
