### ISSUE TITLE
添加百度地图（ios） 镜像

### ISSUE THREAD

**Issue by mayizhao** [tuna/issues#833]
你好：
     目前在使用咱们清华的镜像， 但是pod  百度地图BaiduMapKit 包 一直下载不下来。
    它的地址是     https://github.com/BaiduLBS/BaiduMapKit.git
    大小 66M 多
    希望能尽快添加下

**Comment by z4yx** [comment]
根据镜像政策，我们不镜像 github 上的源码仓库，因为实在太多了。
