### ISSUE TITLE
remi镜像源有问题

### ISSUE THREAD

**Issue by wfwf1990** [tuna/issues#834]
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/7d69ceb211f6fa656b82c214f94e6dbca767662ac8acb7fcdda96d85904466f1-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

remi/other_db                  FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/a22f878e520f6c2b33b31277d2ef033910efc1225dfaf85e4e126f1b7d6c49f5-other.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/primary_db            FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/22716e7e2a137b54f79c524e48fcb7fb5ccdac69f5aa85c74441315d55645082-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/other_db              FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/26a138664ef28ceb2ff38020221f59993f39996ad806b7b63dd51f652ba8af5b-other.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/filelists_db          FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/ce6aa836ac65bdd7615d84a167fae02bd72f1b5654d99d8f858aa372a5d1dda9-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remi/filelists_db              FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/75629c7b9b4498e511f889756c8d0feea48c4decdaee4e2b83c0ef20473f5190-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remi/primary_db                FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/7d69ceb211f6fa656b82c214f94e6dbca767662ac8acb7fcdda96d85904466f1-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remi/filelists_db              FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/75629c7b9b4498e511f889756c8d0feea48c4decdaee4e2b83c0ef20473f5190-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/filelists_db          FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/ce6aa836ac65bdd7615d84a167fae02bd72f1b5654d99d8f858aa372a5d1dda9-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/primary_db            FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/22716e7e2a137b54f79c524e48fcb7fb5ccdac69f5aa85c74441315d55645082-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remisafe/other_db              FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/safe/x86_64/repodata/26a138664ef28ceb2ff38020221f59993f39996ad806b7b63dd51f652ba8af5b-other.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
remi/other_db                  FAILED                                          
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/a22f878e520f6c2b33b31277d2ef033910efc1225dfaf85e4e126f1b7d6c49f5-other.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php72/x86_64/repodata/7d69ceb211f6fa656b82c214f94e6dbca767662ac8acb7fcdda96d85904466f1-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

**Comment by z4yx** [comment]
已恢复，可能是同步时遇到上游更新。
