### ISSUE TITLE
请求增加 Chromium

### ISSUE THREAD

**Issue by dingchengshan** [tuna/issues#836]
项目名称：chromium 
项目简介：Chromium是由Google主导开发的网页浏览器。以BSD许可证等多重自由版权发行并开放源代码。
上游源地址，或镜像方法：
url：https://github.com/chromium/chromium
尽量详细的镜像信息（例如镜像大小）
30G左右

**Comment by z4yx** [comment]
参见 https://github.com/tuna/issues/issues/138#issuecomment-502491547
