### ISSUE TITLE
[镜像请求] Julia：General registry

### ISSUE THREAD

**Issue by johnnychen94** [tuna/issues#837]
#### 项目名称与简介(Project Intro.)

[Julia](https://julialang.org/) 是一门新的科学计算语言，在科学计算方面，一定程度上有取代 MATLAB (和 Python ) 的趋势。

目前绝大部分开源代码库都依赖于 Github 存在，这也包括包注册表[General registry](https://github.com/JuliaRegistries/General)（类似于anaconda 的默认channel），所以在国内如果不挂代理的话，装包的体验非常差。

Julia v1.4.0 版本实现了 [Pkg/Storage 协议](https://github.com/JuliaLang/Pkg.jl/issues/1377), 从而允许用户切换上游下载源。根据该协议，装包时以如下方式进行下载（根据优先级排序）

1. (cache hit) Pkg Client <---> Pkg Server
2. (cache missing) Pkg Client <---> Pkg Server <---> Storage Server
3. (fallback) 从原始地址下载

这里涉及到 Pkg Server 和 Storage Server 两种服务器：

* Pkg Server 遵循 Pkg 协议，是一个HTTP(s)协议的缓存反代层，Julia 的官方Pkg服务器的部署均采用此种方式，不过（我猜）由于镜像站管理不便的原因，#798 拒绝了这种方式。(cc: @z4yx )
* Storage Server 是一个单纯的静态资源服务器，它可以是http(s), 也可以是ftp, aliyun obs 或者 aws s3等协议。

这里请求以 Storage 协议而不是以 Pkg 协议来建立 General 的镜像。用 anaconda 作类比的话，就是建立其默认channel的镜像。（Julia 自带类似于anaconda的包管理工具）

可行性：基于HTTP(S)协议的 Storage 协议是 Pkg 协议的子集，因此这样搭建出来的 Storage Server 可以作为一类特殊的 Pkg Server 存在，也就是说，搭建好的镜像可以通过 `Pkg Client <--HTTPS--> Storage Server` 的方式工作（不支持FTP协议）。

---

#### 上游地址与镜像方法(How to Mirror)

上游地址：官方Pkg Server `https://pkg.julialang.org`

镜像方法：[StorageServer.jl](https://github.com/johnnychen94/StorageServer.jl) 是从[官方原始代码](https://github.com/JuliaPackaging/PkgServer.jl/blob/master/bin/gen_static.jl)中重构出的一个版本

1. 安装 Julia 1.4 以上版本
2. 在 Julia 中安装 StorageServer.jl包: `]add https://github.com/johnnychen94/StorageServer.jl#v0.1.0-alpha`
3. 调整[示例脚本](https://github.com/johnnychen94/StorageServer.jl/blob/ebeae546a304029544bdfd92317670f05d47b18b/examples/gen_static_full.example.jl)中的文件夹路径，其中涉及到三个文件夹
    * `STATIC_DIR` 为所有需要对外提供的资源
    * `CLONES_DIR` 为git mirrors，不需要对外提供，但在更新镜像时需要使用到，所以不需要删除
    * `DEPOT_DIR` 是构造镜像时所需要的临时文件夹，可删可不删
4. 运行该脚本即可拉取/更新镜像，例如 `julia gen_static.jl`
5. 将 `STATIC_DIR` 映射给http(s)/ftp服务
6. 配置到`tunasync`

完整的`STATIC_DIR`的文件夹结构：

```text
[jc@storage mirrors]$ du -sh $STATIC_DIR
310G	artifact # 装包时需要的二进制文件
23G	package # 打包好的源代码
512	registries # 纯文本文件，记录当前提供的注册表的最新版本
130M	registry # 各个版本的注册表
```

关于地址映射：

假设映射出来的地址为`https://mirrors.tuna.tsinghua.edu.cn/julia`，则`https://mirrors.tuna.tsinghua.edu.cn/julia/registries` 对应于`STATIC_DIR`中的`registries`，例如：

```text
# 能够正常下载则代表镜像搭建成功

$ curl https://mirrors.tuna.tsinghua.edu.cn/julia/registries
/registry/23338594-aafe-5451-b93e-139f81909106/613fb3584777fef0b66fcc3b80316437e741dc29
```

---

#### 镜像的使用

假设提供的是`https://mirrors.tuna.tsinghua.edu.cn/julia`, 那么使用镜像只需要配置`JULIA_PKG_SERVER`这一环境变量即可，例如：

**临时使用**

```bash
jc@mathlf1:~$ JULIA_PKG_SERVER=https://mirrors.tuna.tsinghua.edu.cn/julia julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.1 (2020-04-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia
```

`versioninfo()`中能够识别到这一变量即表示成功配置好了`JULIA_PKG_SERVER`

**永久使用**

不同系统配置环境变量的方式不都一样，这里暂时就不做介绍。在 julia 下有一个`$JULIA_DEPOT_PATH/config/startup.jl`文件(默认地址为 `~/.julia/config/startup.jl`)，它定义了每一次启动 julia 时都会执行的代码，所以在各个平台下都一致的一种方式是：

```text
# 修改 ~/.julia/config/startup.jl 文件
ENV["JULIA_PKG_SERVER"] = "https://mirrors.tuna.tsinghua.edu.cn/julia"
```

---

#### 镜像的测试

我自己是使用下面代码来测试的

`JULIA_PKG_SERVER=https://mirrors.tuna.tsinghua.edu.cn/julia JULIA_DEPOT_PATH=tmp time julia -e 'using Pkg; Pkg.add("Images")'`

在千兆内网下大概10s即可完成，其中`JULIA_DEPOT_PATH`设定的是包安装的位置，这里使用临时的空文件夹`tmp`来测试。若镜像配置失败则会有下述警告：

```text
JULIA_PKG_SERVER=https://mirrors.tuna.tsinghua.edu.cn/julia JULIA_DEPOT_PATH=tmp time julia -e 'using Pkg; Pkg.add("Images")'
    Cloning default registries into `tmp`
┌ Warning: could not download https://mirrors.tuna.tsinghua.edu.cn/julia/registries
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Types.jl:880
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
...
```

---

#### 其他信息(Other)

* 镜像大小(Mirror Size)：目前为330G，主要为各种二进制artifacts （包括CUDA），后期的存储占用可能会像 anaconda 一样到TB级别

* 构建时间：网络足够好的情况下，首次构建大概需要10个小时；每次增量更新大概需要7分钟左右

* 增量更新间隔：[General 注册表](https://github.com/JuliaRegistries/General/commits/master)的更新的周期为15分钟一次，可以适当降低频率 （例如我在内网搭建的是每6小时一次）

* 兼容性：
  * 向前：需要 Julia v1.4.0 以后的版本
  * 向后：支持。默认使用的是Pkg 协议，后期会支持类似于git一样的只下载版本diff的形式来减少网络传输。如果采用Pkg 协议方式失败，则采用Storage 协议作为首选fallback。

* `StorageServer.jl`与官方版本的差异：
  * 官方版本为纯粹的Storage协议的实现：从零开始构造tarball，耗时比较长（首次构建需要大概3天）且占用CPU资源较多
  * `StorageServer.jl`增加了镜像的功能：若上游地址提供已经构建好的tarball则直接下载，若不存在则试图从零开始构造tarball。

* 若后期需要添加其他非官方注册表的镜像，该工具也同样支持

checklist：

- 版权: General 采用[MIT协议](https://github.com/JuliaRegistries/General/blob/master/LICENSE.md)
- 增量同步: 支持
- 文件内容：每个单独的资源都用tar和gzip打包过了，应该不属于海量小文件
- 是否为反代: 不属于，为纯静态资源
- 单一软件的安装包下载：不属于，类似于anaconda的channel
- 用户群体小且国内已有其它镜像：
  - 为新兴语言所以用户群体目前并不十分大，但是在科研学术领域的发展势头比较好。
  - 国内暂时没有其他镜像。（cref: https://github.com/ustclug/discussions/issues/311 ）
- 占用空间大而利用率低: 类似于anaconda的默认channel （不清楚是否属于这种情况）
- 是否为github源码仓库: `package`文件夹内为各个版本源代码的tar文件打包内容，应该不属于
- 包含用户产生内容：自由度类似于pypi，没有过多的审核机制。
- 同步方式：社区开发的专用同步工具（固定了版本）[不支持rsync](https://github.com/ustclug/discussions/issues/311#issuecomment-623631438)

cc: @findmyway @Roger-luo @staticfloat

**Comment by johnnychen94** [comment]
另一个相关的请求是 julia 二进制程序的镜像，这个不属于该issue的核心需求，但是若能提供的话则更好 :P

* 镜像大小：8G
* 镜像工具：[jill.py](https://github.com/johnnychen94/jill.py#for-who-are-interested-in-setting-up-a-new-release-mirror)

可以与上面请求的 General 镜像一起发布到`https://mirrors.tuna.tsinghua.edu.cn/julia/releases`中：

```text
root@storage:/mnt/mirrors/julia# du -sh *
310G	artifact
23G	package
512	registries
130M	registry
8.6G	releases

root@storage:/mnt/mirrors/julia# tree releases/ -L 1
releases/
├── latest
├── v1.0
├── v1.1
├── v1.2
├── v1.3
└── v1.4
```


存在其他镜像：[USTC](http://mirrors.ustc.edu.cn/julia/releases/) 以及 [ZJU](https://mirrors.zju.edu.cn/julia/releases/)，但是其镜像工具不能自动发现新版本，不是十分可靠 (例如目前已经发布 Julia 1.4.1 快一个月了，镜像站还只提供 1.4.0-rc1 版本）

#### 镜像搭建方式

1. 安装jill: `pip install jill`
2. 拉取镜像：`jill mirror $STATIC_DIR/releases`

P.S. 除了镜像功能以外，`jill.py`的另一个核心功能是一键安装 julia

**Comment by Harry-Chen** [comment]
目前的维护者都不是 Julia 用户，所以可能不太熟悉。方便的话，是否能够打包出 docker image 供使用？可以参考 https://github.com/tuna/tunasync-scripts/tree/master/dockerfiles

**Comment by Harry-Chen** [comment]
此外，这两个其实是两个独立的 repo，有两种方案：

1. 都放在一个同步工具（docker image）里面，一次同步的时候分别调用，这样能放在一个路径下面
2. 使用两个 docker image，分两个 repo（如 `/julia` 和 `/julia-releases`）

我们原则上推荐第二种

**Comment by z4yx** [comment]
https://mirrors.bfsu.edu.cn/julia-releases/ 已同步好
https://mirrors.bfsu.edu.cn/julia/ 同步中，现在完成了 15%

**Comment by johnnychen94** [comment]
`clones`和`registries`不需要提供出来的，应该是直接把`https://mirrors.bfsu.edu.cn/julia/static/`映射成`https://mirrors.bfsu.edu.cn/julia/`

**Comment by z4yx** [comment]
当前的镜像站架构不方便修改路径，之后在帮助文档里面指导用户使用 `/julia/static/` 吧

**Comment by Harry-Chen** [comment]
> 当前的镜像站架构不方便修改路径，之后在帮助文档里面指导用户使用 `/julia/static/` 吧

可以魔改 nginx 配置的 `alias`，不过有一点脏

**Comment by Harry-Chen** [comment]
如果有兴趣的话， @johnnychen94 可以考虑把 `julia-releases` 加到 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 里面

用来在镜像站首页上呈现软件下载链接

**Comment by johnnychen94** [comment]
好，等同步完成之后我测试一下，如果正常工作的话我来添加一下帮助文档。

tuna和bfsu都是修改mirror-web这个仓库就好了是吗？需要写news么？

**Comment by Harry-Chen** [comment]
> 好，等同步完成之后我测试一下，如果正常工作的话我来添加一下帮助文档。
> 
> tuna和bfsu都是修改mirror-web这个仓库就好了是吗？需要写news么？

不需要写news，一般来说需要提供一个 help，还有就是 genisoinfo 的配置

**Comment by johnnychen94** [comment]
从时间来看似乎 julia 的同步在 11:33 卡住了，可以帮忙检查一下么？我在初始化镜像的时候偶尔会遇到任务hang住的情况但是没办法复现，增量更新的时候没遇到过，重启一下任务应该就好了

https://mirrors.bfsu.edu.cn/julia/static/?C=M&O=D

**Comment by z4yx** [comment]
我重启任务了，最后的日志是这样：

```
[ Info: 2020-05-26T03:33:32.974 FunctionalTables@0.3.0  |  ETA: 8:59:43
[ Info: 2020-05-26T03:33:33.222 FunctionalTables@0.3.1  |  ETA: 8:59:33
┌ Warning: failed to request https://github.com/slmcbane/MirroredArrayViews.jl.git: MirroredArrayViews might not exist or is not public.
└ @ StorageServer ~/tmp/julia/packages/StorageServer/4Agnc/src/package.jl:131
```

**Comment by johnnychen94** [comment]
似乎还是会出现进程卡住的情况，目前的猜测是下载的时候卡住的 （artifact 文件夹下遗留了一些本应该被删掉的 *.tmp.* 文件)，我这边在尝试在 StorageServer 修复，但可能没有这么快能搞定。

如果可以的话对 julia 的镜像设置一个 timeout 可能会更好一些，我发现刚才(08:18)似乎进程重启了一次，不清楚是自动重启的还是手动重启的。如果是自动重启的话那么多尝试几次应该就能拉取完了...

**Comment by z4yx** [comment]
最好所有网络访问都加上超时和重试机制，大量下载时难免会遇到网络不畅的时候。

**Comment by z4yx** [comment]
最近几次同步已经可以同步完了。但是结束清除cache的时候会报错，日志如下
```
[ Info: 2020-05-27T19:29:50.605█zrl_jll@1.0.1+0█████████|  ETA: 0:00:01
[ Info: 2020-05-27T19:29:50.613 zrl_jll@1.1.0+0
ERROR: IOError: unlink: operation not permitted (EPERM)
Stacktrace:
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] unlink(::String) at ./file.jl:888
 [3] rm(::String; force::Bool, recursive::Bool) at ./file.jl:268
 [4] #47 at /tmp/julia/packages/StorageServer/4Agnc/src/registry.jl:113 [inlined]
 [5] foreach(::StorageServer.var"#47#50", ::Array{String,1}) at ./abstractarray.jl:1919
 [6] make_tarball(::String; packages::Nothing, upstreams::Array{String,1}, download_only::Bool, show_progress::Bool, static_dir::String, clones_dir::String) at /tmp/julia/packages/StorageServer/4Agnc/src/registry.jl:111
 [7] #mirror_tarball#57 at /tmp/julia/packages/StorageServer/4Agnc/src/registry.jl:139 [inlined]
 [8] mirror_tarball(::String, ::Array{String,1}) at /tmp/julia/packages/StorageServer/4Agnc/src/registry.jl:139
 [9] top-level scope at none:1
```

这是在删除哪个路径呢？我去检查下文件权限

**Comment by johnnychen94** [comment]
hmmm. 在 `/tmp`下会有一些 asc 文件遗留，这段代码是清楚这些用的

**Comment by z4yx** [comment]
能否加个选项跳过这一步，因为`/tmp`在docker容器里面，同步完成后整个容器就销毁了，没有清理的必要。

**Comment by johnnychen94** [comment]
镜像已经能正常使用了 :tada:，Julia CN 社区里的反馈也比较好。我再多观察一阵子，如果正常工作的话就把这个issue关了

@z4yx @Harry-Chen 非常感谢 TUNA 如此迅速积极和专业的反馈和帮助 :heart::heart:

另外好奇问一下，这个镜像是只会在 BFSU 上么，短期内没有在 Tsinghua 镜像添加的计划是吗？

**Comment by z4yx** [comment]
由于清华站的服务器压力过大，访问速度也慢，暂时不添加新镜像。
等新服务器上线后可以考虑。

**Comment by johnnychen94** [comment]
好像还是会出现增量同步时间过长的现象，不太清楚这个是不是由于镜像站高负载引起的，也可能任务又给挂住了... 我这边单线程的话耗时是11分钟，4线程的话耗时是4分钟。

如果要设定多线程的话，就只需要在 https://github.com/tuna/tunasync-scripts/blob/master/julia.sh 设定环境变量就好了，例如`export JULIA_NUM_THREADS=4`

简单来说，目前的镜像脚本会对`clones/`里的每个git repo的每个版本做checkout来获取足够的资源信息，这部分操作会导致一定的IO负载。我有跟 Julia 那边讨论过从上游提供这些信息（提供一个资源索引的意思）从而简化镜像过程，但是这个需要一些额外的时间和精力来推进。

**Comment by z4yx** [comment]
现在已经通过tunasync配置了环境变量 JULIA_NUM_THREADS=4 
卡住应该还是某处有bug，julia能通过什么方法来保存现场吗？比如coredump之类的？

**Comment by johnnychen94** [comment]
我刚才测试了一下用docker跑，确实也遇到这个问题了... 之前一直是直接用 `julia gen_static.jl` 的方式执行的。是必须要用docker么，如果不是必须的话，我可以提供一份 gen_static.jl

这几天可能就先这样观察着了，我下周再花时间检查一下

**Comment by johnnychen94** [comment]
虽然还是没找到问题发生在哪个环节，但 https://github.com/tuna/tunasync-scripts/pull/74 引入的超时机制看起来是能让同步“成功”进行下去，所以大概可以先暂时告一段落了。虽然同步的效率不是很高，但是从服务器状态看来似乎也没太影响服务器的负载，过段时间我再把增量同步的环节做一个优化加速。

@z4yx @Harry-Chen 再次感谢 TUNA 对 Julia 提供的支持！ :heart:

**Comment by johnnychen94** [comment]
刚留意到 OpenTUNA 也提供了Julia的镜像，感谢TUNA提供的支持 :heart:
