### ISSUE TITLE
建议添加ftp.redhat.com的mirror

### ISSUE THREAD

**Issue by euroford123** [tuna/issues#84]
#### 项目名称与简介(Project Intro.)
ftp.redhat.com是红帽公司公开其各类开源软件产品源码的地方，这些代码同时也是centos/SL等克隆产品的基线代码，对于程序员来讲，极具价值。
#### 上游地址与镜像方法(How to Mirror)
ftp://ftp.redhat.com
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
没有确切的数据，但如果全部镜像，估计应该在TB级别

**Comment by Harry-Chen** [comment]
TB...

**Comment by gaoyichuan** [comment]
现在13T / 28T，再来几个TB级的估计新硬盘都要跪了......

**Comment by shankerwangmiao** [comment]
还好，因为像 ubuntu 啥的也都上 TB 了。不过这玩意是多少 T 呀？

**Comment by bigeagle** [comment]
硬盘不是问题，学校支持，我们现在不缺硬件资源。
主要就是这个同步方法…… 用 lftp 强行拉么……

**Comment by alick** [comment]
找个红帽的人问问？ @sztsian

或者订阅这个邮件列表问下？
[1] https://www.redhat.com/mailman/listinfo/mirror-list

**Comment by bigeagle** [comment]
从 rsync://ftp.heanet.ie/mirrors/redhat/ 拉了～

**Comment by bigeagle** [comment]
真是好大…… 9天了还在同步RHEL5呢……

**Comment by shankerwangmiao** [comment]
好大。。。。现在还没同步完

**Comment by bigeagle** [comment]
总共2.84T，终于拖下来了，用时一个多月。

**Comment by ZenithalHourlyRate** [comment]
```
$ cat /var/log/tunasync/redhat/latest
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1817) [Receiver=3.2.3]
rsync error: Error starting client-server protocol
```
由于上游开启了白名单，我们已经与 ftp.redhat.com 失去同步达到九个月，这可以参考[状态页](https://mirrors.cernet.edu.cn/list/redhat)

正在与上游联系。

另外，由于 redhat 占用空间较大（3.63T），而用户较少（过去三十天流量仅5G），近年来空间较为紧张，在与上游联系未果的情况下可以考虑移除。
