### ISSUE TITLE
使用 Flutter 镜像新建项目的时候报错

### ISSUE THREAD

**Issue by yanshouwang** [tuna/issues#840]
#### 发生了什么（What happened）
使用 Flutter 镜像后新建项目失败，[传送门](https://github.com/flutter/flutter/issues/58075)

#### 期望的现象（What you expected to happen）
可以正常使用

#### 如何重现（How to reproduce it）
从[镜像站](https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra/releases/stable/)下载 SDK
添加 PUB_HOSTED_URL 和 FLUTTER_STORAGE_BASE_URL 环境变量
新建项目时报错，日志见上面链接

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
我看了下，主要错误是这句：
`flutter_tools depends on built_collection 4.3.2 which doesn't match any versions, version solving failed.`
说的是缺少版本built_collection 4.3.2

当前镜像站

https://mirrors.tuna.tsinghua.edu.cn/dart-pub/api/packages/built_collection/versions/4.3.2/

这个路径是存在的，但是

https://mirrors.tuna.tsinghua.edu.cn/dart-pub/api/packages/built_collection/

里面没有4.3.2，可能是同步程序出现了问题，我再研究下程序。

**Comment by yanshouwang** [comment]
好的，万分感谢~有阵子没碰 Flutter 了，这两天回来搞就发现镜像出问题了

**Comment by z4yx** [comment]
现在应该修复了

**Comment by yanshouwang** [comment]
灰常给力~
