### ISSUE TITLE
【镜像请求】Celadon project

### ISSUE THREAD

**Issue by jingdlu** [tuna/issues#842]
#### 项目名称与简介(Project Intro.)
Celadon
Celadon is an open source Android* distribution fully optimized for IntelⓇ platforms. It modifies the Android* stack by incorporating critical technologies that allow users to run Android* applications in virtual machines and in containers.

#### 上游地址与镜像方法(How to Mirror)
https://github.com/projectceladon

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by z4yx** [comment]
根据规则 #741 不镜像 github 仓库

**Comment by jingdlu** [comment]
请问下为什么github仓库不能镜像呢？是技术原因还是其他什么原因？因为Celadon项目是Intel推出的x86架构上的安卓，目前国内很多开发者反映github下载代码很慢且不稳定。
