### ISSUE TITLE
【镜像请求】kubeadm kubectl kubelet

### ISSUE THREAD

**Issue by willzhang** [tuna/issues#843]
#### 项目名称与简介(Project Intro.)
kubernetes 客户端二进制文件
#### 上游地址与镜像方法(How to Mirror)
kube_version=v1.18.3
image_arch=amd64

```
kubelet_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/{{ image_arch }}/kubelet"
kubectl_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/{{ image_arch }}/kubectl"
kubeadm_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubeadm_version }}/bin/linux/{{ image_arch }}/kubeadm"
```
#### 其他信息(Other)
- 镜像大小(Mirror Size): 90M

**Comment by phy25** [comment]
https://github.com/kubernetes/kubernetes/releases might work as well.

**Comment by jiegec** [comment]
https://github.com/kubernetes/kubernetes/releases 只有源码，没有二进制

**Comment by z4yx** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
官方教程中的apt/yum软件包我们提供了镜像： https://mirrors.tuna.tsinghua.edu.cn/kubernetes/
