### ISSUE TITLE
【服务故障】openmediavault extras 同步内容不完整

### ISSUE THREAD

**Issue by EvineDeng** [tuna/issues#844]
TUNA在北外开源镜像站同步的openmediavault extras 内容同步不完整。
- 具体目录：https://mirrors.bfsu.edu.cn/OpenMediaVault/openmediavault-plugin-developers/usul-testing/dists/buster/main/binary-amd64/
- 源地址：https://dl.bintray.com/openmediavault-plugin-developers/usul-testing/dists/buster/main/binary-amd64/

源地址是有内容的，同步后内容缺失。

**Comment by z4yx** [comment]
上游存在数据一致性问题：

```
Invalid size of /openmediavault-plugin-developers/usul-testing/dists/buster/main/binary-amd64/.tmp/Packages.gz, expected 2141
```
（Release文件注明的长度为2141）

**Comment by EvineDeng** [comment]
懵逼，直接使用源地址更新apt好像不报错

**Comment by z4yx** [comment]
可能apt使用了别的Package索引文件

**Comment by z4yx** [comment]
由于上游迟迟未修复，现在取消严格校验，直接跳过无效文件。
