### ISSUE TITLE
AOSP 镜像“下次同步时间”显示错误

### ISSUE THREAD

**Issue by Common-D-Service** [tuna/issues#845]
![Screenshot_20200530_134509](https://user-images.githubusercontent.com/53259837/83320626-d0718880-a27b-11ea-89eb-50a344db18de.png)
请排查一下问题。由于不确定是硬盘还是前端的问题，冒昧在这里提 issue

**Comment by z4yx** [comment]
应该是tunasync的调度器bug，已重启。
