### ISSUE TITLE
Request for python mirror

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#846]
I can't see python mirror.
If there has:tell me the address and close this issue.
If there don't:Can you add it?

#### 项目名称与简介(Project Intro.)
一种跨平台的计算机程序设计语言
#### 上游地址与镜像方法(How to Mirror)
https://www.python.org/ftp/
#### 其他信息(Other)
- 镜像大小(Mirror Size): They don't tell me the size:about few GBs

**Comment by z4yx** [comment]
被发行版包含的软件不再单独镜像。另外Python也不乏下载渠道。
