### ISSUE TITLE
Ubuntu源 重复同步

### ISSUE THREAD

**Issue by Zhang-Xianglong** [tuna/issues#848]
#### 发生了什么（What happened）
rsync超时或系统重启（导致tunasync重启），发现本次同步的文件在上次的同步日志中已经出现了。目前发现的是ustc下Ubuntu源的dists、pool、indices目录。

#### 期望的现象（What you expected to happen）
同步中断或重启时，已同步的文件不应再次同步。

#### 如何重现（How to reproduce it）
ps -ef看到的实际命令为rsync -aHvh --no-o --no-g --stats --exclude .tmp/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://rsync.mirrors.ustc.edu.cn/ubuntu/ /mirrors/ubuntu

#### 您的环境（Environment）
- 操作系统（OS Version）：CentOS 7
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
这个是 rsync 在指定 -delay-updates 参数时的行为，我们无法改变。
如果不指定 -delay-updates ，在同步过程中，用户可能访问到不完整的文件。
