### ISSUE TITLE
下载CocoaPods过慢

### ISSUE THREAD

**Issue by AyGs** [tuna/issues#849]
下载CocoaPods过慢 可以帮忙看看嘛

**Comment by phy25** [comment]
您的运营商是？下载其它资源（比如 Debian ISO）慢吗？

**Comment by z4yx** [comment]
有可能是网络慢，也可能是服务器慢。不论哪一个，都建议用先尝试 bfsu 镜像：https://mirrors.bfsu.edu.cn/help/CocoaPods/

**Comment by AyGs** [comment]
好的麻烦啦..



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yuxiang Zhang <notifications@github.com&gt;
发送时间: 2020年6月12日 16:59
收件人: tuna/issues <issues@noreply.github.com&gt;
抄送: AyGs <1058627498@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tuna/issues] 下载CocoaPods过慢 (#849)





 
有可能是网络慢，也可能是服务器慢。不论哪一个，都建议用先尝试 bfsu 镜像：https://mirrors.bfsu.edu.cn/help/CocoaPods/
