### ISSUE TITLE
Homebrew 补充 Tap 镜像请求

### ISSUE THREAD

**Issue by ghost** [tuna/issues#85]
Homebrew 
#### 项目名称与简介(Project Intro.)

Homebrew 是 OS X 系统用户常用的软件包管理系统。

TUNA 镜像源已对部分 Formula Tap (`homebrew-core`, `homebrew-python`, `homebrew-science`) 进行了镜像，但这些 Tap 未能完全满足需要，`homebrew-dupes`、`homebrew-emacs` 和 `homebrew-cask` 等较有用处的 Tap 没有包含在镜像范围内。
#### 上游地址与镜像方法(How to Mirror)

以下仅包括未包含于 TUNA 源的 Homebrew Tap
##### Homebrew 部分
- https://github.com/Homebrew/homebrew-aliases.git
- https://github.com/Homebrew/homebrew-apache.git
- https://github.com/Homebrew/homebrew-bundle.git
- https://github.com/Homebrew/homebrew-command-not-found.git
- https://github.com/Homebrew/homebrew-completions.git
- https://github.com/Homebrew/homebrew-devel-only.git
- https://github.com/Homebrew/homebrew-dev-tools.git
- https://github.com/Homebrew/homebrew-dupes.git
- https://github.com/Homebrew/homebrew-emacs.git
- https://github.com/Homebrew/homebrew-fuse.git
- https://github.com/Homebrew/homebrew-games.git
- https://github.com/Homebrew/homebrew-gui.git
- https://github.com/Homebrew/homebrew-head-only.git
- https://github.com/Homebrew/homebrew-nginx.git
- https://github.com/Homebrew/homebrew-php.git
- https://github.com/Homebrew/homebrew-services.git
- https://github.com/Homebrew/homebrew-tex.git
- https://github.com/Homebrew/homebrew-versions.git
- https://github.com/Homebrew/homebrew-x11.git
##### Homebrew-cask 部分
- https://github.com/caskroom/homebrew-cask.git
- https://github.com/caskroom/homebrew-eid.git
- https://github.com/caskroom/homebrew-fonts.git
- https://github.com/caskroom/homebrew-versions.git
##### 镜像大小(Mirror Size)

以上两个部分大小的总和目前小于 1 MB。

**Comment by bigeagle** [comment]
总和小于 1MB …… 镜像的意义在于？

**Comment by ggarlic** [comment]
homebrew-emacs 确定有用么？不是自带包管理器么？

**Comment by xavieryao** [comment]
+1 这种索引用处不是很大啊……还是Bottle比较有用
