### ISSUE TITLE
镜像请求

### ISSUE THREAD

**Issue by xhemj** [tuna/issues#850]
#### 项目名称与简介(Project Intro.)
Docsify
A magical documentation generator.
doc, docs, documentation, creator, generator
### 上游地址与镜像方法(How to Mirror)
https://cdnjs.cloudflare.com/ajax/libs/docsify/4.11.3/docsify.min.js
因为Docsify还有很多插件，可不可以把https://cdnjs.com/libraries/docsify这里面的都同步一下，或者是同步上面那个docsify.min.js也可以
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by phy25** [comment]
https://cdn.staticfile.org/docsify/4.11.3/docsify.min.js

**Comment by z4yx** [comment]
镜像站与CDN不同,不适合serve这类文件.
