### ISSUE TITLE
请求建立 ovirt 国内镜像源

### ISSUE THREAD

**Issue by shangweixiao** [tuna/issues#851]
#### 项目名称与简介(Project Intro.)
oVirt项目是一个开放的虚拟化项目，提供基于Web的虚拟机管理控制平台。RedHat企业版虚拟化平台的开源版本。oVirt社区2011年11月由红帽、IBM、英特尔、思科、Canonical、NetApp与SUSE赞助成立。oVirt 涵盖虚拟化管理堆栈各个层级,包括hypervisor、管理、图形用户界面、API等,提供一个功能丰富的服务器虚拟化管理系统。社区的管理是透明的，沿袭的是Apache与Eclipse等项目的机制。

#### 上游地址与镜像方法(How to Mirror)
rsync -rltHvvP mirror@resources.ovirt.org:/var/www/html destination/dir

具体可参考官方方法：
https://www.ovirt.org/community/get-involved/repository-mirrors.html

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by z4yx** [comment]
已开始同步，预计明天中午完成

**Comment by z4yx** [comment]
https://mirrors.bfsu.edu.cn/ovirt/
