### ISSUE TITLE
(ONLY A SUGGESTION)create a own forum to ask

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#853]
I think you can make a community forum to request a mirror,report a bug.
The fastest way is discourse (unlimited user)(github:/discourse/discourse) or use [free flarum with a limit user number](https://freeflarum.com)

**Comment by sysdl132** [comment]
If you use gh-issues,I think the issues will up to 100,000

**Comment by Harry-Chen** [comment]
搭建论坛的维护成本太高，对于用户也不友好，我们没有动机这样做。

**Comment by Harry-Chen** [comment]
> If you use gh-issues,I think the issues will up to 100,000
> That's NOT a slight choice

来源请求

**Comment by phy25** [comment]
GitHub will also have a discussion feature if that is needed - https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/

The burden of maintaining a separate forum on technology and moderation doesn't fit for a non-well-funded student organization as well, in my humble opinion.
