### ISSUE TITLE
是否可以同步kubernetes APT源的apt-key.gpg

### ISSUE THREAD

**Issue by ffftwo** [tuna/issues#856]
或者只是在帮助页面加上这条命令,让帮助更完整一些

```shell
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
```

**Comment by jiegec** [comment]
按照 gpg 的工作原理，要求用户从上游获取 gpg 是最安全的做法。

**Comment by phy25** [comment]
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-kubernetes.md

**Comment by ffftwo** [comment]
> 按照 gpg 的工作原理，要求用户从上游获取 gpg key 是最安全的做法。

有道理
