### ISSUE TITLE
ROCm镜像源请求添加

### ISSUE THREAD

**Issue by wnMIT** [tuna/issues#857]
说明：ROCm适用于AMD显卡的深度学习库，当前仅存在美国的官方源，速度极慢。
源地址： http://repo.radeon.com/rocm/apt/debian
文件大小： 400M左右

**Comment by jiegec** [comment]
rocm 有的部件并没有自由的 license。

**Comment by wnMIT** [comment]
已了解，谢谢回复

**Comment by Harry-Chen** [comment]
并不是说非自由软件就一定无法镜像，我们还需要更多的信息，比如对方是否授权镜像

**Comment by Harry-Chen** [comment]
@cdluminate @heroxbd 能否给出一些建议？

**Comment by heroxbd** [comment]
镜像很小，Debian 包非常不规范，不宜镜像。建议关闭此 issue。

@wnMIT 如果你希望更方便地使用 ROCm，可以帮助 Debian 把 ROCm 集成进官方。
