### ISSUE TITLE
opensuse 15.1 更新报错

### ISSUE THREAD

**Issue by yyweii** [tuna/issues#858]
Repository 'tsinghua-update-oss' is invalid.
[oss|https://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.1/oss] Valid metadata not found at specified URL
History:
 - File './repodata/4b5392d5f402df4debdcbdd027669e57c7dac901a2c111b41ee084177d5fed92-deltainfo.xml.gz' not found on medium 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.1/oss'
 - Can't provide ./repodata/4b5392d5f402df4debdcbdd027669e57c7dac901a2c111b41ee084177d5fed92-deltainfo.xml.gz

**Comment by z4yx** [comment]
已更新
