### ISSUE TITLE
mondo  mirror同步请求

### ISSUE THREAD

**Issue by laileman** [tuna/issues#859]
1： 项目名称： 使用mondo制作自定义linux  的iso安装文件
2.： 请求：  同步瑞士源
3.： 同步地址： ftp://ftp.mondorescue.org/    使用wget下载单个包的时候允许匿名下载
4： 请求说明： 使用此工具时访问非常慢，偶尔打不开。使用巴黎代理时才能正常。

**Comment by laileman** [comment]
补充：
1. 可以考虑同步ubuntu版本，从10.04开始。  centos/redhat  5.4版本开始。
2.  debian 8 ,  slackware.

**Comment by Harry-Chen** [comment]
请按照模板提出 issue，补充必要的信息，包括大小等。
