### ISSUE TITLE
希望添加CDH镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#86]
#### 项目名称与简介(Project Intro.)

CDH是Hadoop一个十分重要的分支，是Cloudera公司维护的Hadoop发行版，在社区中名望很高。最重要的的是，CDH是有Linux发行版仓库的，无疑给部署带来了极大地便利。但是CDH官方镜像速度奇慢，国内这边连接经常超时，有些组件又很大，直接使用官方仓库苦不堪言，不亚于用S3仓库。希望tuna能镜像。
#### 上游地址与镜像方法(How to Mirror)

直接同步官方的仓库即可: http://archive.cloudera.com/cdh5/ 这个主机也有https访问的方法

**Comment by shuxin** [comment]
cdh的hadoop，直接yum安装service启动，用户权限在安装过程完全自动配置，只是部署升级都奇慢无比，希望tuna能够同步cdh5的hadoop镜像。

**上游地址与镜像方法(How to Mirror)**

CentOS

https://www.cloudera.com/documentation/enterprise/5-5-x/topics/cdh_ig_yumrepo_local_create.html

**Comment by stduolc** [comment]
+1

**Comment by Statemood** [comment]
强烈支持

**Comment by showerying** [comment]
+1

**Comment by z4yx** [comment]
See #682
