### ISSUE TITLE
请问能否镜像go的各种官方库

### ISSUE THREAD

**Issue by Alberthchang** [tuna/issues#860]
#### 项目名称与简介(Project Intro.)
Go 生态系统中有着许多无法获取的模块，比如golang.org。。。。还有访问比较慢的
#### 上游地址与镜像方法(How to Mirror)
https://mirrors.aliyun.com/goproxy/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 200G？不太清楚

**Comment by shankerwangmiao** [comment]
dup with #332
