### ISSUE TITLE
[REQUEST] linuxbrew-bottles 新增同步 bottles-portable-ruby

### ISSUE THREAD

**Issue by holymonson** [tuna/issues#863]
出错信息：
```
sxy@ubuntu:~$  brew doctor
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles-portable-ruby/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.6.3_1/portable-ruby-2.6.3_1.x86_64_linux.bottle.tar.gz
```

原因是 YUNA 只将 https://linuxbrew.bintray.com/bottles/ 镜像到 https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/ ，却没有将 https://linuxbrew.bintray.com/bottles-portable-ruby/ 镜像成 https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles-portable-ruby/ 。

bottles-portable-ruby 对于初安装 linuxbrew 和升级是必需的，不然必须翻墙才能装 linuxbrew 才能用 TUNA 的 bottles 。

故请求同步 https://bintray.com/linuxbrew/bottles-portable-ruby 。

---

也许 macos 下的 homebrew-bottles 也需要，不过我的mac有翻墙所以没遇到这个问题。建议最好那边也同步。

**Comment by z4yx** [comment]
感谢提醒，之前只配了homebrew的portable-ruby，忘了linuxbrew。现已增加。
