### ISSUE TITLE
Eclipse 部分项目文件名更改造成常用下载链接未更新

### ISSUE THREAD

**Issue by ZeroAurora** [tuna/issues#864]
#### 发生了什么（What happened）
Eclipse IDE 更改了一部分项目的文件名，以用来标明有孵化中组件，这些文件可以被正常镜像，但是似乎并没有被列入常用下载链接内。
例如，原本的 `Eclipse IDE for C/C++ Developers`，文件名为：`eclipse-cpp-2019-12-R-win32-x86_64.zip`。
现在更名为 `Eclipse IDE for C/C++ Developers (includes Incubating components)`，文件名：`eclipse-cpp-2020-03-R-incubation-win32-x86_64.zip`。

#### 期望的现象（What you expected to happen）
常用下载链接内的 Eclipse 一栏保持最新。

（附注：其实本应该可以直接修改[这里](https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini)的配置然后提交给你们就行，但是因为网络问题无法直接发PR，所以拜托了_(:з)∠)_）

**Comment by z4yx** [comment]
你ini文件更新的部分发在这里吧

**Comment by ZeroAurora** [comment]
```
[eclipse]
(...)
pattern = eclipse-([a-z]+)-(\d+-\d+)-R(-incubation)?-(win32|macosx-cocoa|linux-gtk)-(x86_64)\.(zip|tar\.gz|dmg)
(...)
```

**Comment by ZeroAurora** [comment]
解决了，感谢！
