### ISSUE TITLE
[tuna]404 at /opensuse/distribution/leap/15.2/iso/Changes.680.4.txt

### ISSUE THREAD

**Issue by Fierralin** [tuna/issues#865]
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by phy25** [comment]
源站如此：http://widehat.opensuse.org/distribution/leap/15.2/iso/

**Comment by z4yx** [comment]
现在这个上游有些文件过时了，我们正在调整。调整期间请求重定向到bfsu。

**Comment by z4yx** [comment]
已调整完毕
