### ISSUE TITLE
DownloadFile exception (404) with julia

### ISSUE THREAD

**Issue by xgdgsc** [tuna/issues#866]
#### 发生了什么（What happened）
![image](https://user-images.githubusercontent.com/1189869/84606602-03518880-aeda-11ea-85d0-9f1586a64481.png)

#### 期望的现象（What you expected to happen）
正常下载安装
#### 如何重现（How to reproduce it）
```
] add Rmath
]add VegaLite
```
#### 其他事项（Anything else we need to know）
我有时候删除Manifest后可以安装，所以也不能确定是否是镜像问题, 参考 https://discourse.juliacn.com/t/topic/2969/45
 

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 
- 浏览器（如果适用）（Browser version, if applicable）：Chrome
- 其他（Others）：

**Comment by z4yx** [comment]
这个问题是持续存在还是过一段时间就好了？

**Comment by xgdgsc** [comment]
不好说，感觉像持续存在，我中间间隔过很久

**Comment by z4yx** [comment]
@johnnychen94 专家来帮忙分析下

**Comment by johnnychen94** [comment]
嗯，BFSU上的镜像有一小部分内容缺失了，我估计是因为超时机制导致的（我在内网用同样的工具搭的镜像这一部分内容是存在的），然后增量过程考虑到效率问题直接跳过了这一部分。

截图里实际上已经触发了fallback（第二次download），所以在网络状况好的时候能正常安装，与是否删除`Manifest.toml`无关。

等这学期结束了我再来调整一下代码。

**Comment by xiaoniaoyouhuajiang** [comment]
我也遇到了类似的问题，请问同样是镜像内容缺失的问题吗？

(@v1.4) pkg> add IJulia
  Resolving package versions...
Downloading artifact: ZeroMQ
使使用用““2””个个参参数数调调用用““DownloadFile””时时发发生生异异常常:““远远程程服服务务器器返返回回错错误误: (404) 未未找找
到到。。””
所所在在位位置置 行行:15 字字符符: 1
+ $webclient.DownloadFile("https://mirrors.bfsu.edu.cn/julia/static/artifact/a3
d43 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by johnnychen94** [comment]
有可能，不过这个失败不会影响正常的装包过程，依然会尝试从原始地址进行下载。最近这两周学期期末ddl有点多，所以暂时没办法来修复这个问题。

上游PkgServer最近也有一些改变，到时候会一起合并进来。

**Comment by johnnychen94** [comment]
应该是镜像工具出问题了，[artifact目录](https://mirrors.bfsu.edu.cn/julia/static/artifact/) 在6月3日开始就没有任何新资源下载下来，我在内网搭的服务器也是类似的情况。我下周末检查一下

**Comment by johnnychen94** [comment]
这个问题是上游镜像源调整触发了一个HTTP.jl 的重定向bug导致的，通过[更新上游镜像源](https://github.com/tuna/tunasync-scripts/pull/78)已经解决了

linux下的`Rmath`, `VegaLite`, `MbedTLS` 的数据已经同步好了，部分其他资源还在同步中

**Comment by johnnychen94** [comment]
如果可以的话，能否把 julia-general.git 的同步频率稍微调高一些？因为这是注册表，所以一天两次好像有点太少了...

**Comment by z4yx** [comment]
好的，谢谢 @johnnychen94 的帮助。
