### ISSUE TITLE
麻烦同步一下anaconda的 pscondaenvs 

### ISSUE THREAD

**Issue by Gyx200911** [tuna/issues#867]
https://blog.csdn.net/kdongyi/article/details/81905494
该组件是兼容PowerShell的模块

**Comment by z4yx** [comment]
是这个吗  https://anaconda.org/mwcraig/pscondaenvs

**Comment by z4yx** [comment]
应该是这个：https://anaconda.org/pscondaenvs/pscondaenvs 
确认下？

**Comment by Gyx200911** [comment]
不是很清楚 我看文章引用的库是 
https://github.com/BCSharp/PSCondaEnvs
我尝试一下

**Comment by Gyx200911** [comment]
感觉 pscondaenvs 包可能不能用conda自动安装

**Comment by Gyx200911** [comment]
还有个问题 
在 https://mirror.tuna.tsinghua.edu.cn/help/anaconda/ 
上使用复制功能是 网页底下的foot会错位 挡住要复制的东西
如图
https://i.loli.net/2020/06/18/GMbTrOaVCqJgw9c.png

**Comment by z4yx** [comment]
你的浏览器版本是什么

**Comment by Gyx200911** [comment]
浏览器有点拉胯
不怎么习惯用谷歌
浏览器是 360极速
5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

360极速浏览器 | 12.0.1344.0 (正式版本) （32 位）
-- | --
修订版本 | 5e8bae0b628c11c273eeba327a2fa0c480135638
操作系统 | Windows 10 OS Version 1909 (Build 18363.900)
JavaScript | V8 7.8.279.23
Flash | 29.0.0.171
用户代理 | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 QIHU 360EE

**Comment by Gyx200911** [comment]
83版本的谷歌没这个问题

**Comment by z4yx** [comment]
pscondaenvs 的包都非常小，直接从官方下载吧，就不做镜像了。
