### ISSUE TITLE
Jenkins的长期支持版本 (LTS)升级为了每周更新版

### ISSUE THREAD

**Issue by 1725636955** [tuna/issues#868]
发生了什么（What happened）
升级站点url为：https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json，Jenkins的长期支持版本 (LTS)升级为了每周更新版
#### 期望的现象（What you expected to happen）
Jenkins的长期支持版本 (LTS)只可以升级为Jenkins的长期支持版本 (LTS)
#### 如何重现（How to reproduce it）
下载一个长期支持版本 (LTS)在Manage Jenkins里面升级
#### 您的环境（Environment）
- 操作系统（OS Version）：Linux（centos7）
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
我们是用rsync原样从上游同步的，无法控制jenkins的行为，有问题请给jenkins报告。
