### ISSUE TITLE
请求建立 anaconda c4aarch64 镜像

### ISSUE THREAD

**Issue by linboqiao** [tuna/issues#869]
#### 项目名称与简介(Project Intro.)
mirror c4aarch64

#### 上游地址与镜像方法(How to Mirror)
https://anaconda.org/c4aarch64/
与anaconda一致

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
目前只有几百兆，但在快速增长中

**Comment by z4yx** [comment]
已完成
