### ISSUE TITLE
PyPI broken

### ISSUE THREAD

**Issue by zhsj** [tuna/issues#87]
与其他 PyPI 镜像比较，TUNA 的镜像中的软件包似乎已经滞后很久了。

```
virtualenv test1
test1/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple oslo.utils
....
Successfully installed ... oslo.utils-3.10.0 ...
```
```
virtualenv test2
test2/bin/pip install -i https://pypi.mirrors.ustc.edu.cn/simple oslo.utils
Successfully installed ... oslo.utils-3.16.0 ...
```

**Comment by zhsj** [comment]
可能是 bandersnatch 没更新？

**Comment by bigeagle** [comment]
哭死，bandersnatch 1.9+ 一直工作不正常，我就一直停在了 1.8

**Comment by zhsj** [comment]
bandersnatch 版本已经跑到 1.11 了 :smiley:

**Comment by bigeagle** [comment]
是呀…… 但是 [这个bug](https://bitbucket.org/pypa/bandersnatch/issues/67/always-exit-with-code-1) 一直不解决，我也很困扰呢

**Comment by zhsj** [comment]
要不写个wrapper，强行检查下 repo/pypi/todo 的大小，0字节就返回 0。。。。。

**Comment by bigeagle** [comment]
哦？只要这个是 0 就算成功了？
wrapper 是一直有的

**Comment by zhsj** [comment]
不知道成功了是不是0字节，不过不成功肯定不是0字节  :joy: 

不成功的状态：

```
 % cat /srv/repo/pypi/todo
2243647
pyramid_turbo 2242977
javad-monochrome 2243448
skjult 2242592% 
```

**Comment by bigeagle** [comment]
2333

**Comment by zhsj** [comment]
我看 https://mirrors.tuna.tsinghua.edu.cn/pypi/ 这里都没 todo 文件，大概成功了这个文件就没了吧 =。=

**Comment by bigeagle** [comment]
看起来似乎好了

**Comment by zhsj** [comment]
是升级了 bandersnatch？还是自己突然好了。。。。

**Comment by bigeagle** [comment]
更新了bandersnatch到1.11了，改了 wrapper script
