### ISSUE TITLE
在tx2（arm） ubuntu18.04上安装ros mdelodic：sudo apt install ros-melodic-desktop-full出现问题 

### ISSUE THREAD

**Issue by SYSUHPK** [tuna/issues#870]
The same as [https://answers.ros.org/question/306742/install-ros-melodic-on-ubuntu-18-bionic-unmet-dependencies-unable-to-locate-package/]()

#### 发生了什么（What happened）
问题：The following packages have unmet dependencies: ros-melodic-desktop-full:Depends:ros-melodic-desktop but it is not going to be installed Depends:ros-melodic-perception but it is not going to be installed... E:unable to correct problems,you have held broken packages 
用aptitude安装好像也不太行,会报
E:unable to fetch some package;try '-o APT::Get::Fix-Missing=true'
#### 期望的现象（What you expected to happen）
可以成功安装ros melodic
#### 如何重现（How to reproduce it）
在TX2上的ubuntu18.04 安装ros wiki安装melodic，执行到sudo apt install ros-melodic-desktop-full
#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu18.04（TX2开发板）
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
你测试过从官方源安装吗？

**Comment by SYSUHPK** [comment]
> 你测试过从官方源安装吗？

测试过了，一样的问题

**Comment by SYSUHPK** [comment]
我想我找到方法了，应该是解决这个问题的一个方法，已经成功安装

- Reason
Some dependencies are not installed, and the previously installed versions of the dependencies are not correct, some require downgrade, and some require upgrade
- Install environment
Use the original sources.list: dep http://ports.ubuntu.com/bionic main res...
Other sources.list: ustc, tuna... have not been tested

- Solution
1.Install aptitude
 sudo apt-get install aptitude
2.Install ros-melodic-desktop-full with aptitude
sudo aptitude install ros-melodic-desktop-full
3.The first prompt reminds us that there are a lot of things that are not installed, about 100-600, let us choose to keep the original ones, but there is no at all, enter n here
4.The second prompt may ask us to upgrade or downgrade something, this is what we need, choose Y
5.Select Y to install
6.After that, “-O APT:::GET::Fix-Missing=true” may appear, execute: sudo apt-get --fix-missing
7.Repeat a few times from step 1-5, each time you will find that things you need to install will be reduced a lot, and finally, if you have no problem after step 5, it will automatically install ros.
It works for me
****
- 环境
用本来的源:
dep http://ports.ubuntu.com/bionic main res...
ustc，tuna未经过测试

- 原因
一些依赖没装，同时以前安装的依赖版本不对，有的需要downgrade，有的需要upgrade

- solution
1.安装aptitude
sudo apt-get install aptitude
2.用aptitude 安装ros-melodic-desktop-full
sudo aptitude install ros-melodic-desktop-full
3.第一个提示我们有很多没安装的东西，大概100-600个，让我们选择保留原来的这些，但是根本没有，此处输入 n
4.第二个提示可能会让我们upgrade 或者downgrade某些东西，这就是我们需要的，选择 Y
5.之后安装选择 Y
6.之后可能会出现“-O APT:::GET::Fix-Missing=true”，执行 sudo apt-get --fix-missing
7.从1-5重复几次，每次会发现2需要安装的东西会减少很多，最后执行5之后如果没问题就会自动安装ros了
****

**Comment by z4yx** [comment]
解决就好。 http://ports.ubuntu.com/ 换为 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ 应该是一样的。
