### ISSUE TITLE
http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm

### ISSUE THREAD

**Issue by caihonghaiyif** [tuna/issues#872]
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by z4yx** [comment]
5的版本过久，已被上游删除，我们也不再支持。
参见 https://mirrors.tuna.tsinghua.edu.cn/epel/5/README
