### ISSUE TITLE
域名很难记啊

### ISSUE THREAD

**Issue by kawashiro-ryofu** [tuna/issues#873]
你们是否可以把域名简化一下,比如mirrors.tuna.edu.cn，五段只能记住前三段，

**Comment by Harry-Chen** [comment]
基于合规性原因，我们无法对已有域名进行改动，只能使用现有域名。如果觉得长，可以尝试 https://m.tuna.dev/ ，但我们不对该域名的将来可用性提供任何保证。

**Comment by johnnychen94** [comment]
域名反过来记就可以了：mirrors.tuna.tsinghua.edu.cn 解释过来的话就是 中国->教育网->清华大学->TUNA社团->镜像服务

`edu.cn` 域名不能买卖的，需要学校才能申请到，tuna不可能拿到

**Comment by sysdl132** [comment]
you can add this website to your bookmark

**Comment by tim1103** [comment]
> 基于合规性原因，我们无法对已有域名进行改动，只能使用现有域名。如果觉得长，可以尝试 https://m.tuna.dev/ ，但我们不对该域名的将来可用性提供任何保证。

@Harry-Chen 

可否加个短域名跳转？（例如m.tuna.moe），这样既不改动原域名，也方便好记

**Comment by kawashiro-ryofu** [comment]
> 
> 
> > 基于合规性原因，我们无法对已有域名进行改动，只能使用现有域名。如果觉得长，可以尝试 https://m.tuna.dev/ ，但我们不对该域名的将来可用性提供任何保证。
> 
> @Harry-Chen
> 
> 可否加个永久短域名跳转？（例如m.tuna.moe），这样既不改动原域名，也方便好记

赞同

**Comment by kawashiro-ryofu** [comment]
> 
> 
> > 基于合规性原因，我们无法对已有域名进行改动，只能使用现有域名。如果觉得长，可以尝试 https://m.tuna.dev/ ，但我们不对该域名的将来可用性提供任何保证。
> 
> @Harry-Chen
> 
> 可否加个永久短域名跳转？（例如m.tuna.moe），这样既不改动原域名，也方便好记

赞同，但感觉不一定可行
