### ISSUE TITLE
【服务故障】openmediavault extras 同步文件大小不一致。

### ISSUE THREAD

**Issue by GFRIENDYeLin** [tuna/issues#874]
TUNA在北外开源镜像站同步的openmediavault extras 内容同步文件大小不一致。

具体文件位置：https://mirrors.bfsu.edu.cn/OpenMediaVault/openmediavault-plugin-developers/usul/dists/buster/main/binary-amd64/Packages.bz2

源文件位置：https://dl.bintray.com/openmediavault-plugin-developers/usul/dists/buster/main/binary-amd64/Packages.bz2

具体错误详情：
E: Failed to fetch https://mirrors.bfsu.edu.cn/OpenMediaVault/openmediavault-plugin-developers/usul/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (16166 != 16243). Mirror sync in progress? [IP: 39.155.141.16 443]
   Hashes of expected file:
    - Filesize:16243 [weak]
    - SHA256:faa39e4ebfee2968a8f0dd8c05fa8b6b6c7ae05cc6d6eacd6f580fc704adc720
    - SHA1:0fdcb8949b0ff61e1334ba143e8bb685e645b7a4 [weak]
    - MD5Sum:2ae3ece6d343c8505b714079bfd3e426 [weak]
   Release file created at: Wed, 17 Jun 2020 14:55:00 +0000

**Comment by phy25** [comment]
Duplicate to #844.

**Comment by z4yx** [comment]
跟844不完全一样。现已恢复。
