### ISSUE TITLE
Add gitlab for raspberry pi

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#875]
is it mirrored?
#### 项目名称与简介(Project Intro.)
gitlab ce for raspberry pi
#### 上游地址与镜像方法(How to Mirror)
https://packages.gitlab.com/gitlab/gitlab-ce
#### 其他信息(Other)
- 镜像大小(Mirror Size): unknown

**Comment by z4yx** [comment]
上游未提供arm版本：
https://packages.gitlab.com/gitlab/gitlab-ce/debian/dists/buster/Release
索引文件是空的

**Comment by sysdl132** [comment]
oh?

**Comment by z4yx** [comment]
`d41d8cd98f00b204e9800998ecf8427e 0 main/binary-armhf/Packages`

**Comment by sysdl132** [comment]
I will ask gitlab offical.Before I asked please don't leave any comments.
