### ISSUE TITLE
rename raspbian to raspberry pi OS

### ISSUE THREAD

**Issue by sysdl132** [tuna/issues#876]
The raspberry pi website renamed raspbian to raspberry pi OS.You should rename raspbian and raspbian-images

**Comment by z4yx** [comment]
done

**Comment by shankerwangmiao** [comment]
根据 raspbian 官方的回信，其项目并没有改名，因此撤回 raspbian 的名字更改。

**Comment by shankerwangmiao** [comment]
上述变更已经撤回在三个镜像服务器上。
