### ISSUE TITLE
请求Python安装包镜像

### ISSUE THREAD

**Issue by Baigei-Gu** [tuna/issues#877]
#### 项目名称与简介(Project Intro.)
Python 安装包下载
#### 上游地址与镜像方法(How to Mirror)
https://www.python.org/downloads/
请原谅我，我不知道如何镜像
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
请原谅我，我不知道镜像大小

呜呜呜，实在是原来的太慢了

**Comment by shankerwangmiao** [comment]
dup with #846
