### ISSUE TITLE
使用yay更新AUR软件包时出错

### ISSUE THREAD

**Issue by zhanghua000** [tuna/issues#886]
#### 发生了什么（What happened）
yay提示Rate Limit Reached错误
#### 期望的现象（What you expected to happen）
yay完成数据的更新
#### 如何重现（How to reproduce it）
在将镜像地址设置为 https://aur.tuna.tsinghua.edu.cn 后使用yay更新AUR中的软件包
#### 其他事项（Anything else we need to know）
将地址改回 https://aur.archlinux.org 后可以解决
#### 您的环境（Environment）
- 操作系统（OS Version）： Manjaro aarch64 20.06 on RaspberryPi 4B linux 5.7.3-1
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by zhanghua000** [comment]
It seems having been be fixed. Maybe just a common service upgrade. :)

**Comment by ZenithalHourlyRate** [comment]
> 同样的问题，请问如何解决

目前的服务中不应该遇到 Rate Limit. 您可以参考 https://github.com/Jguer/yay/issues/1682

另，注意我们将停止 AUR 镜像服务 https://mirrors.tuna.tsinghua.edu.cn/news/remove-aur/
