### ISSUE TITLE
Miniforge3 安装包下载

### ISSUE THREAD

**Issue by shitou1992** [tuna/issues#887]
anaconda 中可以提供Miniforge3 的安装包吗,类似miniconda的
miniconda目前没有arm架构的，但是miniforge支持

Miniforge3的安装包托管在Amazon的,下载速度太慢，希望贵站可以支持下，具体下载地址：
## Download

Miniforge installers are available here: https://github.com/conda-forge/miniforge/releases

#### Miniforge3
Latest installers with python 3.7 in the base environment

- [linux-aarch64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh) (also called `arm64`)
- [linux-ppc64le](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-ppc64le.sh) (also called `POWER8/9`)
- [linux-x86_64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh) (also called `amd64`)
- [osx-x86_64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh)

#### Miniforge-pypy3
Latest installers with pypy3.6 in the base environment

- [linux-aarch64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-Linux-aarch64.sh)
- [linux-ppc64le](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-Linux-ppc64le.sh)
- [linux-x86_64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-Linux-x86_64.sh)
- [osx-x86_64](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-MacOSX-x86_64.sh)

**Comment by z4yx** [comment]
正在同步到 https://mirrors.tuna.tsinghua.edu.cn/github-release/conda-forge/miniforge/LatestRelease/
