### ISSUE TITLE
希望添加Grafana的镜像

### ISSUE THREAD

**Issue by donhui** [tuna/issues#89]
#### 项目名称与简介(Project Intro.)
Grafana 是开源的，功能齐全的度量仪表盘和图形编辑器，支持 Graphite，InfluxDB 和 OpenTSDB。

#### 上游地址与镜像方法(How to Mirror)
https://packagecloud.io/grafana/stable/el/6/$basearch

#### 其他信息(Other)
- 镜像大小(Mirror Size): 单个rpm包大约40M

**Comment by abcfy2** [comment]
正好我们也在用，一并把ubuntu的也镜像了吧。
http://grafana.org/download/
官方仓库有yum和apt

**Comment by bigeagle** [comment]
嗯，我们也在用～

**Comment by bigeagle** [comment]
同步完成
