### ISSUE TITLE
pip install ilit regularly install old version rather latest one

### ISSUE THREAD

**Issue by ftian1** [tuna/issues#892]
#### 发生了什么（What happened）
when execute "pip install ilit -i https://pypi.tuna.tsinghua.edu.cn/simple", 
it will install ilit v0.1 rather ilit v1.0a. in fact we have deleted ilit 0.1 in pypi offical website.

#### 期望的现象（What you expected to happen）
we expect user to install ilit v1.0a rather v0.1 as v0.1 has been deleted.

#### 如何重现（How to reproduce it）
pip install ilit -i https://pypi.tuna.tsinghua.edu.cn/simple

#### 其他事项（Anything else we need to know）
even use browser, such as chrome, to access https://pypi.tuna.tsinghua.edu.cn/simple/ilit, the web will refresh the whl name regularly, sometimes it's v0.1, sometimes it's v1.0a. looks like the intervel is 5 mins. but the offical pypi website we only keep v1.0a. we assumes TUNA mirror should completely sync with pypi offical rather than caching this old version. we don't know why it happens.

#### 您的环境（Environment）
- 操作系统（OS Version）：
centos 7
- 浏览器（如果适用）（Browser version, if applicable）：
chrome
- 其他（Others）：

**Comment by ftian1** [comment]
PS: other mirrors, such as https://pypi.doubanio.com/simple or offical pypi server, have no this issue.

**Comment by Harry-Chen** [comment]
我们有两台服务器做负载均衡，这个问题估计是某一台没有同步完成

**Comment by ftian1** [comment]
请问负载均衡你们是用的开源库还是自己写的代码？想知道这是一个普遍的bug还是一个只在TUNA上出现的bug。如果是一个普遍的bug,我们可能得从pip install的角度看有没办法解决。

**Comment by jiegec** [comment]
睡一觉，起来的时候就解决了

**Comment by ftian1** [comment]
我们已经睡了两觉了，问题还是在

**Comment by z4yx** [comment]
已手动同步该项目。
我们用的是官方同步工具bandersnatch，由于程序（尤其是早期版本）存在的bug，部分pypi没有成功同步。

**Comment by ftian1** [comment]
非常感谢各位的帮助！
