### ISSUE TITLE
pypi源在下载大文件的时候会出现断流

### ISSUE THREAD

**Issue by paulzhn** [tuna/issues#894]
使用tuna的pypi下tensorflow，这个包大概400+M，下载时的表现是下几秒停几秒，并且偶尔还会出现read timed out的问题

**Comment by phy25** [comment]
您的网络环境和运营商是？

**Comment by paulzhn** [comment]
山西电信，下行200M

**Comment by paulzhn** [comment]
但是有一点很奇怪，在报read timed out的时候只下了大概1/3，然而再次重新开始下载之后，pip直接using cached了...这一点我暂且没想通，或许pip本身也存在一些bug？

**Comment by z4yx** [comment]
下载中断开属于已知问题，暂无解决方案。
建议先换到 https://mirrors.bfsu.edu.cn/pypi/

**Comment by paulzhn** [comment]
有点好奇，是因为流量太大而后端跟不上吗...？

**Comment by z4yx** [comment]
问题有可能出运营商网络中，校内无法复现。

**Comment by Harry-Chen** [comment]
我们目前没有接到更多的报告，先关了。如果还有新问题，可以继续提出。
