### ISSUE TITLE
AUR 帮助似乎总会在一段时间后重定向到404？

### ISSUE THREAD

**Issue by Lapis-Apple** [tuna/issues#896]
### 发生了什么（What happened）
AUR 帮助似乎总会在一段时间后重定向到404？

#### 如何重现（How to reproduce it）
点击AUR旁边帮助按钮即可，100%复现，已在多台设备测试。

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 
- 浏览器（如果适用）（Browser version, if applicable）：Chrome 83

**Comment by you06** [comment]
Same here, and the last-update time of AUR mirror is `0000-00-00 00:00`, seems it has been moved to https://aur.tuna.tsinghua.edu.cn/ .

**Comment by z4yx** [comment]
应该在 https://github.com/tuna/mirror-web/commit/c81dfd31ede498fe12a9b44faf11ed25a4345364 中修复了
