### ISSUE TITLE
Pypi镜像没有face_recognition 1.3.0版本

### ISSUE THREAD

**Issue by tcztzy** [tuna/issues#897]
[Pypip](https://pypi.org/project/face-recognition/)有
[TUNA](https://pypi.tuna.tsinghua.edu.cn/simple/face_recognition/)没有
[豆瓣](https://pypi.douban.com/simple/face_recognition/)有

**Comment by z4yx** [comment]
请使用统一化的包名 face-recognition
https://pypi.tuna.tsinghua.edu.cn/simple/face-recognition/

参考 https://www.python.org/dev/peps/pep-0503/#normalized-names
