### ISSUE TITLE
gitlab-ci-multi-runner

### ISSUE THREAD

**Issue by suxue** [tuna/issues#9]
需要debian jessie源，被墙了，amazon s3也连不上。因为你们提供了gitlab-ce,这个是不是可以一起mirror以下?

**Comment by bigeagle** [comment]
请至少说明下这是个什么项目，上游在哪里，最好能告知建立 mirror 的方法。

**Comment by suxue** [comment]
是gitlab-ci的一部分，gitlab-ci已经整合进了gitlab-ce，"This is the GitLab Runner repository, the official GitLab CI runner written in Go. It runs tests and sends the results to GitLab CI. GitLab CI is the open-source continuous integration server that coordinates the testing.".

项目主页,https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

这个页面里有安装方法，和gitlab-ce一样是脚本文件，里面有gpg key和debian repo的地址（在墙外，我打不开）https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/linux-repository.md

谢谢。

**Comment by suxue** [comment]
https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh这个文件我没法下，被公司ban了还是被墙block了我不太清楚。这个项目实际上只有一个二进制可执行文件，因为是go写的，这个语言用静态编译。

**Comment by suxue** [comment]
https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh这个文件我没法下，被公司ban了还是被墙block了我不太清楚。这个项目实际上只有一个二进制可执行文件，因为是go写的，这个语言用静态链接。

**Comment by bigeagle** [comment]
Hi, gitlab-ci-multi-runner 已经同步完成，用法应该和 gitlab-ce 类似，https://mirrors.tuna.tsinghua.edu.cn/help/gitlab-ce/，请测试一下。

**Comment by jk2K** [comment]
感谢，在`Ubuntu 14.04 LTS`已测试, 使用正常
将以下内容写入`/etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list`
`deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ci-multi-runner/ubuntu/ trusty main`

安装 `gitlab-ci-multi-runner`:

    sudo apt-get update
    sudo apt-get install gitlab-ci-multi-runner
