### ISSUE TITLE
CTAN镜像未在MiKTeX注册

### ISSUE THREAD

**Issue by gaotongsh** [tuna/issues#900]
#### 发生了什么（What happened）
选择TUNA的CTAN镜像，在MiKTeX中更新时，提示

> The remote package repository is not registered. You have to choose another repository.

而晚至2019年下半年仍可更新。在重新选择镜像时，已经找不到TUNA镜像。在 https://miktex.org/pkg/repositories 上也无法找到TUNA镜像。

#### 期望的现象（What you expected to happen）
TUNA镜像应当出现在MiKTeX的镜像选择中。

#### 如何重现（How to reproduce it）
安装MiKTeX，选择镜像时，可以看到列表。或者在 https://miktex.org/pkg/repositories 查看列表。

#### 其他事项（Anything else we need to know）
估计需要和MiKTeX联系添加镜像。

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10
- 浏览器（如果适用）（Browser version, if applicable）：N/A
- 其他（Others）：N/A

**Comment by happyaron** [comment]
可能是临时性问题，目前已经重新出现在列表中，麻烦确认现在是否可用。

**Comment by gaotongsh** [comment]
没有吧，现在网页列表中还是没有TUNA，客户端里也没有。
![网页版](https://user-images.githubusercontent.com/12027397/88365145-b48bee00-cdb7-11ea-9b2f-a7dc0d84193c.png)
![客户端](https://user-images.githubusercontent.com/12027397/88365210-e0a76f00-cdb7-11ea-8976-1efb94792035.png)

**Comment by WeiYuan-Peng** [comment]
我在大概三十分钟前确认了是有的，现在又没了...

**Comment by WeiYuan-Peng** [comment]
check update出错
![image](https://user-images.githubusercontent.com/39028366/88365788-afc83980-cdb9-11ea-9c3e-7dc984f3c943.png)

**Comment by gaotongsh** [comment]
> check update出错
> ![image](https://user-images.githubusercontent.com/39028366/88365788-afc83980-cdb9-11ea-9c3e-7dc984f3c943.png)
我之前的错误是“The remote package repository is not registered. ”，现在是“outdated”。也许这次真是临时问题。不过最好还是搞清楚问题机理，这样动不动不能更新也挺致命的。

**Comment by shankerwangmiao** [comment]
目前应该没问题了。

**Comment by Platinum-Berlitz** [comment]
2021.3.15早该问题再次出现，在MiKTeX Package Repositories的网页版及MiKTeX客户端中TUNA镜像再次消失……

**Comment by Harry-Chen** [comment]
MiKTeX 会进行某种比较奇怪的检测，然后将它认为有延时的 repo 暂时移除。目前我们也没有好办法，可能只能等待一段时间。
