### ISSUE TITLE
AOSP 清华镜像下载 8.1.0 出现问题

### ISSUE THREAD

**Issue by DysaniazzZ** [tuna/issues#906]
#### 发生了什么（What happened）
下载源码检查失败

#### 期望的现象（What you expected to happen）
成功下载完成

#### 如何重现（How to reproduce it）

`repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/manifest -b android-8.1.0_r1`

#### 其他事项（Anything else we need to know）

我是创建了一个大小写分区，日志式的硬盘分区下载的源码。

#### 您的环境（Environment）
- 操作系统（OS Version）：macOS Catalina Version 10.15.5
- 浏览器（如果适用）（Browser version, if applicable）：无
- 其他（Others）：

报错日志如下：
`Checking out projects:   1% (8/592) platform/compatibility/cdderror: Cannot checkout platform/cts: ManifestInvalidRevisionError: revision refs/tags/android-8.1.0_r1 in platform/cts not found
error: in `sync`: revision refs/tags/android-8.1.0_r1 in platform/cts not found`

<img width="759" alt="Screen Shot 2020-07-22 at 09 57 23" src="https://user-images.githubusercontent.com/19492924/88125682-62559c00-cc02-11ea-9021-7fb3baa482a6.png">

**Comment by shankerwangmiao** [comment]
目前服务器上的 git 仓库里已经有这个 tag 了

**Comment by xuyongfeng** [comment]
你好，我只想下载8.1.0中frameworks/base的目录代码。但是出现如下错误。
A8500:~/code/8_AOSP$ repo sync -c platform/frameworks/base
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
remote: Counting objects: 4044348, done.        
remote: Compressing objects: 100% (764182/764182), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
platform/frameworks/base:
remote: Counting objects: 4044348, done.        
remote: Compressing objects: 100% (764182/764182), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

remote: Counting objects: 4044348, done.        
remote: Compressing objects: 100% (764182/764182), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
platform/frameworks/base:
remote: Counting objects: 4044348, done.        
remote: Compressing objects: 100% (764182/764182), done.        
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

error: Cannot fetch platform/frameworks/base from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/frameworks/base
Fetching projects: 100% (1/1), done.
error: Cannot checkout platform/frameworks/base: ManifestInvalidRevisionError: revision refs/tags/android-8.1.0_r1 in platform/frameworks/base not found
error: in `sync -c platform/frameworks/base`: revision refs/tags/android-8.1.0_r1 in platform/frameworks/base not found

**Comment by shankerwangmiao** [comment]
> 你好，我只想下载8.1.0中frameworks/base的目录代码。但是出现如下错误。
> A8500:~/code/8_AOSP$ repo sync -c platform/frameworks/base
> repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
> repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
> remote: Counting objects: 4044348, done.
> remote: Compressing objects: 100% (764182/764182), done.
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> platform/frameworks/base:
> remote: Counting objects: 4044348, done.
> remote: Compressing objects: 100% (764182/764182), done.
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> 
> remote: Counting objects: 4044348, done.
> remote: Compressing objects: 100% (764182/764182), done.
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> platform/frameworks/base:
> remote: Counting objects: 4044348, done.
> remote: Compressing objects: 100% (764182/764182), done.
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> 
> error: Cannot fetch platform/frameworks/base from https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/frameworks/base
> Fetching projects: 100% (1/1), done.
> error: Cannot checkout platform/frameworks/base: ManifestInvalidRevisionError: revision refs/tags/android-8.1.0_r1 in platform/frameworks/base not found
> error: in `sync -c platform/frameworks/base`: revision refs/tags/android-8.1.0_r1 in platform/frameworks/base not found

这是因为在 pull 的过程中出现了网络连接中断的问题，该问题可能与网络环境有关，建议重新尝试，或者切换使用 mirrors.bfsu.edu.cn
