### ISSUE TITLE
2020.7.22: 无法使用TUNA镜像站

### ISSUE THREAD

**Issue by Chen-Junze** [tuna/issues#908]
#### 发生了什么（What happened）
(2020.7.22) WSL Debian (Buster) 在APT安装软件包时一直提示 `Temporary failure resolving 'mirrors.tuna.tsinghua.edu.cn'`且重启电脑后无效
#### 期望的现象（What you expected to happen）
正常安装
#### 如何重现（How to reproduce it）
![image](https://user-images.githubusercontent.com/44717023/88143403-bd4eb980-cc29-11ea-8bcc-afdbb12702ab.png)

#### 其他事项（Anything else we need to know）
浏览器在WSL APT无法访问镜像时依然可以正常访问镜像站网页。
#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 专业工作站版 1909
- 浏览器（如果适用）（Browser version, if applicable）：Microsoft Edge 84.0.522.40
- 其他（Others）：有线网络。

**Comment by Harry-Chen** [comment]
正如错误信息显示的，你的 WSL 无法解析这个域名，而与 TUNA 没有任何关系。请检查你的 DNS 配置，如 `/etc/resolv.conf`。
