### ISSUE TITLE
希望能加入php相关的包以及扩展包

### ISSUE THREAD

**Issue by zhangmazi** [tuna/issues#91]
#### 项目名称与简介(Project Intro.)
homebrew-bottles
#### 上游地址与镜像方法(How to Mirror)
https://homebrew.bintray.com/bottles-php/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 

希望能加入php相关的包以及扩展包

**Comment by bigeagle** [comment]
目前 homebrew-bottles 是从 USTC 同步的， 上游有了我们就能有 @gaoyifan

**Comment by gaoyifan** [comment]
USTC镜像站已添加：http://mirrors.ustc.edu.cn/homebrew-bottles/bottles-php/
同步周期6小时

**Comment by bigeagle** [comment]
好棒～
