### ISSUE TITLE
saltstack3 repo repomd.xml没有同步

### ISSUE THREAD

**Issue by thuhak** [tuna/issues#910]
#### 发生了什么（What happened）
saltstack3/redhat/8/x86_64/latest/repodata/repomd.xml
没有与上游同步，但是xml.gz同步了，导致repo无法使用

#### 期望的现象（What you expected to happen）

repomd.xml中的内容和实际的xml.gz的名称保持一致

#### 如何重现（How to reproduce it）

查看repo中文件的日期，就能很清楚的看见

**Comment by phy25** [comment]
https://mirrors.tuna.tsinghua.edu.cn/saltstack/py3/redhat/8/x86_64/latest/repodata/repomd.xml == https://mirrors.bfsu.edu.cn/saltstack/py3/redhat/8/x86_64/latest/repodata/repomd.xml

!=

https://repo.saltstack.com/py3/redhat/8/x86_64/latest/repodata/repomd.xml == 
https://repo-saltstack-com.s3.amazonaws.com/py3/redhat/8/x86_64/latest/repodata/repomd.xml

**Comment by shankerwangmiao** [comment]
请再尝试一次，看看是否恢复？

**Comment by thuhak** [comment]
> 请再尝试一次，看看是否恢复？

没有哎

**Comment by shankerwangmiao** [comment]
似乎是 s3 sync 的问题，在 https://github.com/tuna/tunasync-scripts/issues/88 中处理。
