### ISSUE TITLE
Bioconductor镜像页面丢失

### ISSUE THREAD

**Issue by WPZgithub** [tuna/issues#913]
#### 发生了什么（What happened）
Bioconductor镜像下没有内容，显示404 NOT FOUND

**Comment by shankerwangmiao** [comment]
请给出具体页面。

**Comment by WPZgithub** [comment]
镜像页面下没有软件列表：
https://mirrors.tuna.tsinghua.edu.cn/bioconductor/3.10/BiocViews.html#___Software
点任一连接以后出现404 NOT FOUND：
https://mirrors.tuna.tsinghua.edu.cn/install/index.html#find-bioconductor-packages

这是官方网站：
http://www.bioconductor.org/packages/3.10/BiocViews.html#___Software

**Comment by WPZgithub** [comment]
> 请给出具体页面。

镜像页面下没有软件列表：
https://mirrors.tuna.tsinghua.edu.cn/bioconductor/3.10/BiocViews.html#___Software
点任一连接以后出现404 NOT FOUND：
https://mirrors.tuna.tsinghua.edu.cn/install/index.html#find-bioconductor-packages

这是官方网站：
http://www.bioconductor.org/packages/3.10/BiocViews.html#___Software

**Comment by shankerwangmiao** [comment]
已经禁止了 bioconductor 的 index 页面
