### ISSUE TITLE
miniconda长时间未能更新

### ISSUE THREAD

**Issue by holymonson** [tuna/issues#915]
#### 发生了什么（What happened）
https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/ 长时间没有更新，最新文件日期为 2020-03-12 。

#### 期望的现象（What you expected to happen）

和官方 https://repo.anaconda.com/miniconda/ 同步，最新文件日期为 2020-06-16。请检查同步记录和设置是否有出错，谢谢。

**Comment by shankerwangmiao** [comment]
是同步脚本工作异常，在 https://github.com/tuna/tunasync-scripts/issues/87 中进一步处理。
