### ISSUE TITLE
Ubuntu APT下载软件时出现大面积404

### ISSUE THREAD

**Issue by langonginc** [tuna/issues#916]
#### 发生了什么（What happened）

使用 `apt` 下载 `xinit` 时出现了大面积 404

#### 期望的现象（What you expected to happen）

顺利下载

#### 如何重现（How to reproduce it）

`apt install xinit`

#### 其他事项（Anything else we need to know）

暂无

#### 您的环境（Environment）
- 操作系统（OS Version）： Ubuntu Server 20 LTS Linux
- 浏览器（如果适用）（Browser version, if applicable）： 不适用
- 其他（Others）： 无桌面系统，ssh登录

**Comment by shankerwangmiao** [comment]
请先 apt-get update 之后再执行一次。
