### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by OYLL123** [tuna/issues#917]
#### 发生了什么（What happened）
repo init -u https://github.com/OP-TEE/manifest.git --mirror
![image](https://user-images.githubusercontent.com/42767953/88906821-79436080-d28a-11ea-9e8d-f8ee89566104.png)

repo sync
![image](https://user-images.githubusercontent.com/42767953/88906869-86f8e600-d28a-11ea-9f46-7a363166d310.png)

#### 其他事项（Anything else we need to know）
![image](https://user-images.githubusercontent.com/42767953/88907040-c293b000-d28a-11ea-87c7-9d942a07ba65.png)

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 20.04

**Comment by OYLL123** [comment]
![image](https://user-images.githubusercontent.com/42767953/88907498-48176000-d28b-11ea-9d1c-ecd42f33f87e.png)

**Comment by OYLL123** [comment]
python升级到3.8之后也遇到了一样的报错
![image](https://user-images.githubusercontent.com/42767953/88908294-44380d80-d28c-11ea-87aa-15f1a0ec3137.png)

**Comment by OYLL123** [comment]
repo 版本
![image](https://user-images.githubusercontent.com/42767953/88908393-629e0900-d28c-11ea-8305-0a0ac98ca4b9.png)

**Comment by shankerwangmiao** [comment]
我在 ubuntu bionic 下，使用 ubuntu 源中自带的 2.7.17 版本的 python，未能复现此故障。
