### ISSUE TITLE
[镜像请求]qt官方近期提供了旧版本的qt源码及安装包下载，建议更新下目前tuna已有的qt镜像源

### ISSUE THREAD

**Issue by clorymmk** [tuna/issues#919]
#### 项目名称与简介(Project Intro.)
qt官方近期更新提供了旧版本的源码及安装包下载，建议更新下镜像源，增加旧版本的镜像下载
#### 上游地址与镜像方法(How to Mirror)
https://download.qt.io/new_archive/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1504
