### ISSUE TITLE
Homebrew 地址变了

### ISSUE THREAD

**Issue by kassadin** [tuna/issues#92]
今天更新的时候发现之前的 https://mirrors.tuna.tsinghua.edu.cn/git/brew.git `not found` 了

https://mirrors.tuna.tsinghua.edu.cn/homebrew/brew.git/

[说明文件](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/)没有更新

**Comment by bigeagle** [comment]
抱歉抱歉，我改了服务器配置，这是改错了……

**Comment by bigeagle** [comment]
现在应该好了。

**Comment by kassadin** [comment]
是改错了吗？现在访问还是这样儿啊~

**Comment by bigeagle** [comment]
前几天把所有 git 镜像迁到另一台服务器了，目录结构搞错了。
https://mirrors.tuna.tsinghua.edu.cn/git/brew.git 这个可以 clone 呀……
