### ISSUE TITLE
推荐加速一下免费开源参考文献zotero插件下载速度。

### ISSUE THREAD

**Issue by baidoufuxuchangqing** [tuna/issues#921]
官方网站插件地址
https://www.zotero.org/support/plugins
大部分为开源插件，放置在github。下载速度极慢或无法下载。
建议将部分常用xpi格式定期同步并提供下载。
如可行，同步GB/T7714-2015 csl文件。

**Comment by shankerwangmiao** [comment]
这些插件实际上已经是独立的各软件了。难以归集为一个软件仓库，因为基本无法镜像。

**Comment by shankerwangmiao** [comment]
另外，TUNA 是开源软件镜像站，并非下载加速器。
