### ISSUE TITLE
Linux Kernel CDN

### ISSUE THREAD

**Issue by wenerme** [tuna/issues#922]
#### 项目名称与简介(Project Intro.)
https://cdn.kernel.org/
https://cdn.kernel.org/pub/linux/kernel/

目前已有 linux git 镜像，但是没有可下载的内核包，构建的时候比 git 更加实用

#### 上游地址与镜像方法(How to Mirror)

Method|URL
----|----
HTTP | https://www.kernel.org/pub/
GIT | https://git.kernel.org/
RSYNC | rsync://rsync.kernel.org/pub/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/kernel/
