### ISSUE TITLE
TeXstudio

### ISSUE THREAD

**Issue by baolenmeng** [tuna/issues#923]
项目名称  TeXstudio
项目简介  TeXstudio is an integrated writing environment for creating LaTeX documents. Our goal is to make writing LaTeX as easy and comfortable as possible. Therefore TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants. TeXstudio is open source and is available for all major operating systems.
上游源地址，或镜像方法  http://texstudio.sourceforge.net/
尽量详细的镜像信息（例如镜像大小）抱歉，新手上路，请多担待。

**Comment by 1900011604** [comment]
我也觉得很有必要，现在我在windows上下载这个都是科学上网才可以的

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/texstudio-org/texstudio/
