### ISSUE TITLE
无法下载 CTAN 的 mactex 的最新包 mactex-20200407.pkg 

### ISSUE THREAD

**Issue by mountain** [tuna/issues#925]
网址是 https://mirrors.tuna.tsinghua.edu.cn/systems/mac/mactex/mactex-20200407.pkg 

谢谢！

**Comment by Harry-Chen** [comment]
这个 URL 是错误的，缺少 /CTAN，应为 https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/mac/mactex/mactex-20200407.pkg
