### ISSUE TITLE
Add Archlinux32

### ISSUE THREAD

**Issue by mochaaP** [tuna/issues#926]
#### 项目名称与简介(Project Intro.)

[Arch Linux 32](https://archlinux32.org/) 是一个社区继续维护的基于 Arch Linux 的发行版。

#### 上游地址与镜像方法(How to Mirror)

源地址 <https://mirror.archlinux32.org/>

<https://bbs.archlinux32.org/viewforum.php?id=10>

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
未知

**Comment by Arnie97** [comment]
#### 上游地址与镜像方法 (How to Mirror)
* rsync://mirror.archlinux32.org/archlinux32

#### 镜像大小 (Mirror size)
* 102.43G (2021-11-26，数据取自 `$ rsync -anh --info=stats rsync://mirror.archlinux32.org/archlinux32 .`)

#### 备注 (Note)
* 亚太地区的其他 Arch Linux 32 镜像目前全挂了 :-(

**Comment by Harry-Chen** [comment]
目前纯 32 位设备已经很少见了，Arch Linux 32 是否有足够的用户呢？

**Comment by iamliuzy** [comment]
很多 15、20 年前的老机器还是 32 位的，Arch Linux 32 能让它们获得新生。

**Comment by mochaaP** [comment]
No longer interested in this, closing.
