### ISSUE TITLE
nanomirrors日志无法获取

### ISSUE THREAD

**Issue by ShenYuhan** [tuna/issues#927]
#### 发生了什么（What happened）
无法下载提供的日志[nanomirrors](https://mirrors.tuna.tsinghua.edu.cn/logs/nanomirrors/)
#### 期望的现象（What you expected to happen）
可正常下载，或者提供其他替换的方式能获取日志，主要通过日志来分析某些包的下载次数
#### 如何重现（How to reproduce it）
访问失败
#### 其他事项（Anything else we need to know）
无
#### 您的环境（Environment）
- 操作系统（OS Version）：mac
- 浏览器（如果适用）（Browser version, if applicable）：chrome
- 其他（Others）：无

**Comment by jiegec** [comment]
nanomirrors 正在维护：https://mirrors.tuna.tsinghua.edu.cn/news/nano-allflash/
