### ISSUE TITLE
sourceforge mirror

### ISSUE THREAD

**Issue by charliez0** [tuna/issues#928]
#### 上游地址与镜像方法(How to Mirror)
https://sourceforge.net/p/forge/documentation/Join%20as%20a%20Mirror/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
A minimum of 10TB of storage. Our full data set now exceeds 50TB; a typical 10–15TB mirror will contain a portion of the file set.

**Comment by shankerwangmiao** [comment]
由于 SF 需要 mirror 向其提供 root 权限，因此不予考虑。

**Comment by TheInterestingSoul** [comment]
直接开放root啊，那弄一个container可以吗

**Comment by shankerwangmiao** [comment]
不可以，根据上述指引，SF 需要完整的管理权限。
