### ISSUE TITLE
MongoDB repository for Ubuntu Xenial 16.04 is missing

### ISSUE THREAD

**Issue by w1ndy** [tuna/issues#93]
upstream url: http://repo.mongodb.org/apt/ubuntu/dists/xenial/

**Comment by abcfy2** [comment]
还发现一个问题，stable/3.2这个目录下，居然同步到了一个rc版本3.2.9-rc0，这个在上游stable/3.2仓库中是没有的

**Comment by bigeagle** [comment]
应该是早前同步下来的，现在的脚本里没有“删除”这个动作。

**Comment by abcfy2** [comment]
哦，原来如此。建议还是实现类似于rsync --delete参数的功能。
