### ISSUE TITLE
请求增加smartos,pkgsrc,软件安装包镜像

### ISSUE THREAD

**Issue by supersndqd** [tuna/issues#933]
smartos是opensolaris的封装版本,主要是在云方面,pkgsrc是clone于netbsd的软件安装包.
上游服务器rsync://pkgsrc.joyent.com/pkgsrc-joyent/packages/SmartOS/trunk/ 
大小大概30g多.

**Comment by supersndqd** [comment]
前面填错信息了，http改成rsync协议

**Comment by zhiyuanzhai** [comment]
如果最后决定接受这个request的话，考虑到joyent.com这个站点上还提供macOS, Linux等其他操作系统上的预编译包，就干脆把这些镜像都做在一起吧

**Comment by supersndqd** [comment]
同意的可能性很小，ustc也发过，也没有反应，就跟网红一样，什么流行mirror什么，大站都一个模子脱出来一样，这些小众的资源就靠我们自己梯子了

**Comment by shankerwangmiao** [comment]
Using mirroring service is a privilege, not a right.

**Comment by taoky** [comment]
> 同意的可能性很小，ustc也发过，也没有反应

ustcmirror 没有收到过有关 "smartos" 的镜像请求 issue (^1 和 ^2 的搜索结果都为空)，也没有收到过类似请求的邮件。

^1: <https://github.com/ustclug/mirrorrequest/issues?q=smartos>
^2: <https://github.com/ustclug/mirrorrequest/issues?q=joyent>
