### ISSUE TITLE
申请新镜像 wikimedia

### ISSUE THREAD

**Issue by atomse** [tuna/issues#934]
项目名称: wikimedia
项目简介: 维基百科等包含所有Wikimedia的文章内容。
上游源地址，或镜像方法

https://meta.wikimedia.org/wiki/Mirroring_Wikimedia_project_XML_dumps

rsync rsync://ftpmirror.your.org/wikimedia-dumps/
rsync rsync://ftpmirror.your.org/wikimedia-images/

尽量详细的镜像信息（例如镜像大小）
Space
We require 16.3 TB for the 5 most recent dumps (most desired option). This would be 3 sets of full dumps and 2 sets of partial dumps. This is based on estimates from June 2019.

Alternative options:

"most recent good dumps": 4.5 TB (June 2019 estimate). This would be one set of full dumps.
"last 2 good dumps": 6.7 TB (June 2019 estimate). This would be one set of full dumps and one set of partial dumps.
"All dumps and other data": ~ 47 TB and growing (as of June 2019).
Additional options:

"Historical archives": 1.6T now (October 2017). This consists of 2 dumps per year from 2002 through 2010. Not expected to change or grow.
"Other": 19.6 TB (June 2019). Pageview analytics, CirrusSearch indexes, Wikidata entity dumps and other datasets.

**Comment by shankerwangmiao** [comment]
因为 Wikimedia 的文章内容难以归类为开源软件或其源代码，因此不予考虑。
