### ISSUE TITLE
AOSP clone bundle

### ISSUE THREAD

**Issue by xavieryao** [tuna/issues#936]
#### 发生了什么（What happened）
同步时出现 curl: (22) The requested URL returned error: 404 Not Found Server does not provide clone.bundle; ignoring.

#### 其他事项（Anything else we need to know）
某不愿透露姓名的热心网友建议直接 clone 上游的 bundle 以减少服务器的 CPU 占用

**Comment by addhaloka** [comment]
支持, 清华源同步最后70%~95%很大概率卡死, 最后换了科大源才成功同步下来

**Comment by bAdOoWindy** [comment]
> 
> 
> 支持, 清华源同步最后70%~95%很大概率卡死, 最后换了科大源才成功同步下来

自从换了ipv6连接 一切都是那么顺畅
跑满宽带轻轻松松

**Comment by hhhaiai** [comment]
次镜像元失败 

```
└ ─ $repo init -u https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/mirror/manifest --mirror
Downloading Repo source from https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
fatal: Cannot get https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/clone.bundle
fatal: error [Errno -3] Temporary failure in name resolution
fatal: double check your --repo-rev setting.
fatal: cloning the git-repo repository failed, will remove '.repo/repo'
```

**Comment by ZenithalHourlyRate** [comment]
> error [Errno -3] Temporary failure in name resolution

请检查您的 DNS 设置
