### ISSUE TITLE
[Mirror Request] Hugging Face Model Hub

### ISSUE THREAD

**Issue by JetRunner** [tuna/issues#937]
#### 项目名称与简介(Project Intro.)
[huggingface/transformers](https://github.com/huggingface/transformers) is the No. 1 open-source project in the field of Natural Language Processing (NLP). It provides state-of-the-art general-purpose architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet, T5, CTRL...) for Natural Language Understanding (NLU) and Natural Language Generation (NLG) with over thousands of pretrained models in 100+ languages and deep interoperability between PyTorch & TensorFlow 2.0.

The requested mirror of Hugging Face's Model Hub is the most important feature of this library. People can download pretrained models from the hub (which is very slow in China) and use for their own applications. The most downloaded [pretrained model](https://huggingface.co/bert-base-multilingual-cased) has >15 million downloads over 30 days.

#### 上游地址与镜像方法(How to Mirror)
https://s3.amazonaws.com/models.huggingface.co/bert/

It's a S3 bucket so it can be synced with the S3 sync tool. We (Hugging Face) can provide necessary assistance from our side.

#### 其他信息(Other)
- 镜像大小(Mirror Size): 1.5 TB

**Comment by JetRunner** [comment]
More context here:

The model hub has a website: https://huggingface.co/models
Since we are requesting as the first-party, there should be no worry for possible legality/authorization concerns.

**Comment by Harry-Chen** [comment]
I wonder how will you distribute these pretrained models if we set up a mirror for them. Will you redirect access to these files on your servers (maybe based on geolocation) or require additional setup from users (such as an environmental variable or some other config)?

**Comment by JetRunner** [comment]
@Harry-Chen Hi Harry, we would go with the later since redirecting seems to be a bad idea given that geolocation is not accurate.

**Comment by Harry-Chen** [comment]
Ok. I noticed that you are using `https://cdn.huggingface.co/` to distribute downloadable contents at the moment. So that means our mirror will be an alternative source for users, correct?

**Comment by JetRunner** [comment]
Good point! We are in the process of transiting the user requests to our `https://cdn.huggingface.co/` (which is a CDN for the S3 bucket, obviously). However, neither way works for our users in China and they have to suffer the download speed below 100KB/s. And yes, Tuna mirror will be an alternative source for our Chinese users.

**Comment by Harry-Chen** [comment]
Thanks for the information. We will discuss it internally and reply ASAP.

**Comment by JetRunner** [comment]
@Harry-Chen Thanks, Harry! I would like to emphasize the importance of our library (and model hub) for NLP researchers and please don't hesitate to ask us again for anything you need.

**Comment by Harry-Chen** [comment]
@sshleifer Thanks for your help! The problem on `mbart-trimmed-enro` is resolved now, but the other still remains.

To reproduce this, you could run `aws --no-sign-request s3 sync s3://models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/ .` anywhere and you will see the error.

I believe it is due to that there is an object named `models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/`, confusing the synchronization tool. You can download that object at <https://s3.amazonaws.com/models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/>. I believe this object should also be removed, and only `models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/README.md` should be kept in S3.

Also there is one object named `unicamp-dl//README.md`. The double slash in the filename causes the matching between object name and directory level (should be `unicamp-dl/README.md`) to always fail. So this file is deleted by `aws s3` and redownloaded every time we initiate a synchronization. This is not a big problem because it's only a text file. But obviously renaming it would be a better choice.

**Comment by sshleifer** [comment]
Does this break your mirror globally or only for the affected paths?

**Comment by Harry-Chen** [comment]
This will not affect other files, but will cause the `aws s3` tool to exit abnormally and then the synchronization process will be considered failed (thought all other files are successfully downloaded).

I can exclude this path in the command we use, but it would not be a good choice because any other downstream (there will be more than one for we have multiple servers for load balancing) will have to use the same config. Could you check about the `models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/` object in S3 and delete it (seems it has the same content with `models.huggingface.co/bert/sampathkethineedi/sampathkethineedi/industry-classification/README.md`)?

**Comment by sshleifer** [comment]
removed the whole dir, it seems accidental.

**Comment by Harry-Chen** [comment]
@sshleifer I tried to sync again and now it works.

I am actually using this command to sync: 

```
aws --no-sign-request s3 sync s3://models.huggingface.co/bert /path/to/hugging-face-models/
```

There might be some options that could stop it from failing on such paths, but its default behaviour is to fail (at least with awscli 1.18.124 that we use). If I could not solve it, maybe I will try other tools such as `rclone`.

**Comment by JetRunner** [comment]
Hi @Harry-Chen, what's the current status of the mirror? Is it actively syncing? I don't see it on the status page. If the mirror is active we can move to the next step.

**Comment by Harry-Chen** [comment]
Yes it is syncing, but only on our one server. So when you are load-balanced to other servers you won't be able to see it on the status page but can still access it by our fallback mechanism.

However the synchronization still will fail due to similar problems like above. This time it is caused by two files `facebook/bart-large` and `facebook/bart-large-xsum`. Directories with the same names also exist. I tried `awscli` and `rclone` and none of them allows file and directory to have the same name. This error makes sense, because any local filesystem does not know how to handle such situation. I hope you could prevent such situation from happening on your side.

**Comment by julien-c** [comment]
Hi @Harry-Chen, we added a periodic integrity check to our S3 so that files bearing the same name as a "folder" (a concept which doesn't exist in S3) will be deleted on our side.

You can go ahead with the mirroring if you'd like.

Thanks for your help!

**Comment by Harry-Chen** [comment]
@julien-c That seems great! I believe everything is fine now. Currently the mirror is located at<https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/> and synchronizes every 6 hours (could be more frequent if needed). You could continue with the next part now (e.g. add mirror option to your `hugging-face-transformers` library). Then you could provide documentation on the usage of our mirror and I will add it to our help page.

Also I am setting up `hugging-face-models` on other mirrors sites that we maintain. Once done, I will update with additional addresses of this mirror.

**Comment by JetRunner** [comment]
It's awesome! Thanks @Harry-Chen @julien-c

**Comment by JetRunner** [comment]
BTW, what are "other mirrors" you are maintaining? Our proposed PR is https://github.com/huggingface/transformers/pull/6679/files.
If you do have other mirrors we would modify the PR to allow selection.

**Comment by Harry-Chen** [comment]
@JetRunner There will be some extra sites:

* https://mirrors.bfsu.edu.cn/hugging-face-models/ (still syncing)
* https://opentuna.cn/hugging-face-models/ (under construction)

And other open-source mirrors sites (such as USTC) might also synchronize your repo.

So I don't believe hardcoding one single mirror address is a good idea. It would be better to provide more options, something more flexible like:

* `use_cn_mirror`: to use a mirror in China (let's say TUNA by default)
* `mirror_address`: let the user override the endpoint

What do you think?

**Comment by JetRunner** [comment]
@Harry-Chen Thanks for the suggestion. I'll modify the PR.

**Comment by JetRunner** [comment]
@Harry-Chen We've merged the PR on our side. 
Here's how to use the mirror:

To use the mirror, you can simply add a parameter `mirror` to the `from_pretrained` method for models. Note that the `mirror` parameter can be a URL or selected from the preset list `['tuna', 'bfsu']`.
```python
AutoModel.from_pretrained('bert-base-uncased', mirror='tuna')
```
or
```python
AutoModel.from_pretrained('bert-base-uncased', mirror='https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models')
```

**Comment by JetRunner** [comment]
@Harry-Chen Could you please update the website with the usage doc above? 

Also I can't find hugging face mirror on tuna now. Is it still syncing?

**Comment by Harry-Chen** [comment]
> @Harry-Chen Could you please update the website with the usage doc above?

Sure. I've been a little busy these days. I will work on it tomorrow.

> Also I can't find hugging face mirror on tuna now. Is it still syncing?

See the first paragraph in <https://github.com/tuna/issues/issues/937#issuecomment-682346502>. Content and help pages can always be served even if only existing on the other server. Maybe later I will try to make it show on in the list.

**Comment by Harry-Chen** [comment]
@JetRunner The help page is located at <https://mirrors.tuna.tsinghua.edu.cn/help/hugging-face-models/>.

You can open an pull request for <https://github.com/tuna/mirror-web/blob/master/help/_posts/2020-09-19-hugging-face-models.md> if you want to modify it.

**Comment by JetRunner** [comment]
@Harry-Chen it's just awesome! Thanks for your help!

**Comment by fuzhenxin** [comment]
Hi @JetRunner ,  hugging face is a great project. We also mirror the models in (https://mirrors.pku.edu.cn/hugging-face-models/). But we find the files in S3 is different from (https://huggingface.co/). Is this a designed feature? Or the S3 models is not updated? Thanks!

1. There are only four models in S3 of /uer/:
  ```bash
  [root@cn100 ~]# aws --no-sign-request s3 ls s3://models.huggingface.co/bert/uer/
                             PRE chinese_roberta_L-2_H-128/
                             PRE chinese_roberta_L-4_H-256/
                             PRE gpt2-chinese-couplet/
                             PRE gpt2-chinese-poem/
  ```
  But on the official website, there are a lot of models: ![image](https://user-images.githubusercontent.com/11755823/128987365-6db607ad-4492-46ea-be6e-16edab232a60.png)



2. And the updated time is different too.
  The updated time of ``uer/gpt2-chinese-couplet`` in S3:
  ```bash
  [root@cn100 ~]# aws --no-sign-request s3 ls s3://models.huggingface.co/bert/uer/gpt2-chinese-couplet/
  2020-11-25 06:25:59        859 config.json
  2020-11-25 06:26:01  420921295 pytorch_model.bin
  2020-11-25 06:26:20        112 special_tokens_map.json
  2020-11-25 06:26:21  408449360 tf_model.h5
  2020-11-25 06:26:26        414 tokenizer_config.json
  2020-11-25 06:26:27     109516 vocab.txt
  ```
  The updated time in website: ![image](https://user-images.githubusercontent.com/11755823/128987425-9360c9fa-145e-4334-afd0-97c6f2b440b5.png)

**Comment by JetRunner** [comment]
> Hi @JetRunner , hugging face is a great project. We also mirror the models in (https://mirrors.pku.edu.cn/hugging-face-models/). But we find the files in S3 is different from (https://huggingface.co/). Is this a designed feature? Or the S3 models is not updated? Thanks!
> 
> 1. There are only four models in S3 of /uer/:
> 
> ```shell
> [root@cn100 ~]# aws --no-sign-request s3 ls s3://models.huggingface.co/bert/uer/
>                            PRE chinese_roberta_L-2_H-128/
>                            PRE chinese_roberta_L-4_H-256/
>                            PRE gpt2-chinese-couplet/
>                            PRE gpt2-chinese-poem/
> ```
> 
> But on the official website, there are a lot of models: ![image](https://user-images.githubusercontent.com/11755823/128987365-6db607ad-4492-46ea-be6e-16edab232a60.png)
> 
> 1. And the updated time is different too.
>    The updated time of `uer/gpt2-chinese-couplet` in S3:
> 
> ```shell
> [root@cn100 ~]# aws --no-sign-request s3 ls s3://models.huggingface.co/bert/uer/gpt2-chinese-couplet/
> 2020-11-25 06:25:59        859 config.json
> 2020-11-25 06:26:01  420921295 pytorch_model.bin
> 2020-11-25 06:26:20        112 special_tokens_map.json
> 2020-11-25 06:26:21  408449360 tf_model.h5
> 2020-11-25 06:26:26        414 tokenizer_config.json
> 2020-11-25 06:26:27     109516 vocab.txt
> ```
> 
> The updated time in website: ![image](https://user-images.githubusercontent.com/11755823/128987425-9360c9fa-145e-4334-afd0-97c6f2b440b5.png)

Hi @fuzhenxin Thanks for the kind words. I'll let @julien-c answer that.

**Comment by julien-c** [comment]
Hi, we kept this S3 bucket for backward compatibility but we do not use it anymore, as we moved to a git/git-lfs backed storage system. (cc @pierrci)

Not sure whether there's an easy fix for this unfortunately.

I think the future-proof way to improve bandwidth for users based in China is for us to open an AWS China account.

**Comment by Harry-Chen** [comment]
Due to the change of upstream, I have now paused the synchronization of `hugging-face-models` on our server.

**Comment by fuzhenxin** [comment]
> Hi, we kept this S3 bucket for backward compatibility but we do not use it anymore, as we moved to a git/git-lfs backed storage system. (cc @Pierrci)
> 
> Not sure whether there's an easy fix for this unfortunately.
> 
> I think the future-proof way to improve bandwidth for users based in China is for us to open an AWS China account.

Got it. Thanks!

**Comment by Harry-Chen** [comment]
We have now removed `hugging-face-models` due to deprecation from upstream. https://mirrors.tuna.tsinghua.edu.cn/news/remove-hugging-face/

**Comment by JetRunner** [comment]
@fuzhenxin @Harry-Chen We deprecate the mirroring option and we're working with AWS China to provide a self-hosted solution.

**Comment by xxllp** [comment]
too bad

**Comment by wyh196646** [comment]
too bad

**Comment by vipcxj** [comment]
too bad

**Comment by zhaojinzhou** [comment]
希望重启。 
最近大模型太火了。 
何况这是一个 10年的树木 的工程。

**Comment by Harry-Chen** [comment]
@zhaojinzhou 是 hugging face 方面停止了对镜像的支持。

**Comment by adeenayakup** [comment]
目前hugging face 正在努力改善在中国的infra，希望可以更好的帮助中文社区。

**Comment by xianbaoqian** [comment]
感谢大家的支持。之前的镜像方案因为我们新功能的加入 (stats, git 等) 无法正常工作，所以我们停止了对镜像的支持。我们在筹划建立官方的国内镜像。敬请期待。

**Comment by livehl** [comment]
> 

我们有自己的机房。有大量空闲存储(100T+)，大量空闲服务器（1000+cpu），但是缺乏足够的带宽(500M)
我们自己也受困于大模型的下载问题，因此自建加速通道具备200M左右的国际加速带宽。
希望能一起合作，用咱们的这些闲置资源能帮助到广大的中国开发者。

**Comment by xxllp** [comment]
中国应该搞各自有源

**Comment by lovemyspring** [comment]
我这边可以提供存储、算力、以及网络带宽来支持该项目，期望国内的源能够尽快落地

**Comment by wylzabc** [comment]
> 感谢大家的支持。之前的镜像方案因为一些新功能的加入 (stats, git 等) 无法正常工作，所以我们停止了对镜像的支持。我们在筹划建立官方的国内镜像。敬请期待。

您好，huggingface是一个伟大的项目，十分期待你们的国内镜像建成。我所在的公司可以提供设备支持，来共同建设在中国的huggingface镜像源，让你们的项目惠及中国广大的开发者们。欢迎您联系我

**Comment by lsm03624** [comment]
期待！之前清华的huggingface镜像，现在不能用了。

**Comment by honglyua** [comment]
期待重启

**Comment by statelesshz** [comment]
> 感谢大家的支持。之前的镜像方案因为一些新功能的加入 (stats, git 等) 无法正常工作，所以我们停止了对镜像的支持。我们在筹划建立官方的国内镜像。敬请期待。

@xianbaoqian 您好，建立国内镜像的进展如何？期待您的回复

**Comment by Harry-Chen** [comment]
> > 感谢大家的支持。之前的镜像方案因为一些新功能的加入 (stats, git 等) 无法正常工作，所以我们停止了对镜像的支持。我们在筹划建立官方的国内镜像。敬请期待。
> 
> @xianbaoqian 您好，建立国内镜像的进展如何？期待您的回复

关于 Hugging Face 国内镜像的事宜，请直接联系对方公司。本 issue 不应用于相关的咨询或者催促用途。

**Comment by padeoe** [comment]
我们搭了一个huggingface镜像，欢迎大家使用 https://hf-mirror.com

**Comment by trotsky1997** [comment]
现在完全无法访问了
