### ISSUE TITLE
packagecloud.io/AtomEditor/atom

### ISSUE THREAD

**Issue by zypA13510** [tuna/issues#938]
#### 项目名称与简介(Project Intro.)
Atom
Hackable text editor created by GitHub
比VSCode更早的electron文本编辑器
https://atom.io/
https://github.com/atom/atom

#### 上游地址与镜像方法(How to Mirror)
https://packagecloud.io/AtomEditor/atom/mirror
(注意页面右上角分了DEB和RPM)

#### 其他信息(Other)
- 镜像大小(Mirror Size): 
粗略估计50-100GB?(最新版本单文件176M)

packagecloud速度极慢，基本无法在连接中断前下载完：
![image](https://user-images.githubusercontent.com/8077540/90801965-2882cd00-e349-11ea-8487-435d63e4a1e8.png)

**Comment by ZenithalHourlyRate** [comment]
https://github.blog/2022-06-08-sunsetting-atom
