### ISSUE TITLE
建议删除 HHVM

### ISSUE THREAD

**Issue by jiegec** [tuna/issues#939]
按照 #725 ，我建议删除镜像 HHVM: 访问量极低，并且 PHP7 发布后，HHVM 已经不需要了

附上删除的流程：

1. 选择候选的 repo ：最近三个月访问量小于一个阈值
2. 在本仓库新建一个相应的 issues，开始投票。
3. 指定的 TUNA 成员拥有一票否决权，通过关闭 issue 行使；其他成员享有正常的投票权，通过 Reaction 来投票
4. 一段固定的时间后，统计投票结果，如果同意删除镜像占总投票人数过半，则删除该镜像

#136

**Comment by Harry-Chen** [comment]
HHVM 已经移除。
