### ISSUE TITLE
Parrot Security OS Mirrors Request

### ISSUE THREAD

**Issue by xiashali** [tuna/issues#94]
#### 项目名称与简介(Project Intro.)
Parrot Security OS 是一个基于 GNU/Debian 的 Linux 发行版，用于渗透测试,对云友好。集成了众多的渗透测试工具，且 GUI 设计得十分酷炫。
#### 上游地址与镜像方法(How to Mirror)
rsync://archive.parrotsec.org/parrot/
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
252.08 GB

**Comment by Harry-Chen** [comment]
Done.
