### ISSUE TITLE
求一个fedora的riscv镜像

### ISSUE THREAD

**Issue by qq332982511** [tuna/issues#943]
#### 项目名称与简介(Project Intro.)
fedora的riscv镜像

#### 上游地址与镜像方法(How to Mirror)
http://fedora.riscv.rocks/repos-dist/rawhide/latest/riscv64/

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by ZenithalHourlyRate** [comment]
国内已有镜像站（ https://mirror.iscas.ac.cn/mirror/fedora-riscv.html ）

参考 #741 的第 6 条
> 用户群体小且国内已有其它镜像
