### ISSUE TITLE
emerge app-admin/sysklogd-1.5.1-r1失败

### ISSUE THREAD

**Issue by jun2982804** [tuna/issues#944]
#### 发生了什么（What happened）
我在emerge app-admin/sysklogd-1.5.1-r1时，不断提示搜索了很多镜像源都找不到sysklogd_1.5-6.diff.gz这个文件。
#### 期望的现象（What you expected to happen）
希望可以成功安装sysklogd。
#### 如何重现（How to reproduce it）
在命令行输入emerge --ask app-admin/sysklogd
#### 其他事项（Anything else we need to know）
我不知道如何从虚拟机中取出日志文件，日志文件有更详细的记录
#### 您的环境（Environment）
- 操作系统（OS Version）：在虚拟机下安装Gentoo时出现这个情况
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by dotkrnl** [comment]
经查，[Debian 现已不提供 sysklogd 包](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=sysklogd)。由于 Gentoo 的 `sysklogd ebuild` [似乎依赖于 Debian 提供此包](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/sysklogd/sysklogd-1.5.1-r1.ebuild?id=44c422f475b7131d4dbecf433ab2d2f32c808efb)，无法正常安装 sysklogd 为期望现象。

如您希望解决此问题，请联系 Gentoo 此 ebuild 文件的维护者，例如在 [Gentoo 官方的 bug 反馈网站]中反馈。由于镜像站的职能为原样提供官方文件，而官方行为即为失败，恕无法在本问题中解决。我将关闭这一 issue，如有其他问题，欢迎再次回复。

**Comment by jun2982804** [comment]
是这样吗？先谢谢你告诉我！
