### ISSUE TITLE
SaltStack Debian9 镜像同步有问题

### ISSUE THREAD

**Issue by hanbing0715** [tuna/issues#945]
### 发生了什么（What happened）
使用 SaltStack Debian9 镜像安装失败

#### 如何重现（How to reproduce it）
curl http://mirrors.tuna.tsinghua.edu.cn/saltstack/py3/debian/9/amd64/latest/dists/stretch/Release -s | head -n 10
可以看到此文件最后一次在2020年5月7日被同步
对比上游
curl http://repo.saltstack.com/py3/debian/9/amd64/latest/dists/stretch/Release -s | head -n 10
有较大差距

**Comment by shankerwangmiao** [comment]
与 #910 问题类似，在 https://github.com/tuna/tunasync-scripts/issues/88 处理
