### ISSUE TITLE
[tuna]404 at /manjaro/stable/multilib/x86_64/wine-5.12-1-x86_64.pkg.tar.zst

### ISSUE THREAD

**Issue by gabin22** [tuna/issues#946]
#### 发生了什么（What happened）

安装wine5.12-1,提示：
正在准备...
正在解决依赖关系...
正在检查内部冲突...
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/multilib/x86_64/wine-5.12-1-x86_64.pkg.tar.zst: 错误 404
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/community/x86_64/faudio-20.07-1-x86_64.pkg.tar.zst: 错误 404
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/multilib/x86_64/lib32-faudio-20.07-1-x86_64.pkg.tar.zst: 错误 404
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/community/x86_64/faudio-20.07-1-x86_64.pkg.tar.zst: 错误 404
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/multilib/x86_64/lib32-faudio-20.07-1-x86_64.pkg.tar.zst: 错误 404
https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/multilib/x86_64/wine-5.12-1-x86_64.pkg.tar.zst: 错误 404
提交事务失败:
无法检索某些文件

#### 您的环境（Environment）
- 操作系统（OS Version）：manjaro
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by dotkrnl** [comment]
当前 wine 版本为 `wine-5.15-1`。请检查您的本地包数据库（local repository databases）是否已同步（synchronized）。请尝试 `pacman -S`。镜像站亦或偶有可能因同步问题导致包数据库信息不一致，请您等待一段时候后重试。

若您等待后重试 `pacman -S` 后仍无法正常按照，请重新打开此 issue。由于本问题似乎并非服务故障，我将暂时关闭。如有误解，敬请谅解。

**Comment by dotkrnl** [comment]
抱歉，本人太久没有使用 Arch-based 系统了。同步本地包数据库的命令为 `pacman -Sy` 而非之前说的 `pacman -S`。
