### ISSUE TITLE
Mirror Requests for php

### ISSUE THREAD

**Issue by GeniusLe** [tuna/issues#947]
项目名称
       PHP
项目简介:
       通用脚本语言
上游源地址:
        https://github.com/php/php-src/releases
        https://www.php.net/releases/

**Comment by phy25** [comment]
Similar to #877,

**Comment by GeniusLe** [comment]
@phy25 If I can provide mirroring method, can join?

**Comment by shankerwangmiao** [comment]
我们不考虑镜像 PHP，因为 PHP 都被各发行版的官方仓库收录，直接安装即可。

**Comment by GeniusLe** [comment]
@shankerwangmiao 发行版所包含的仅仅是特定版本,且其都非常的老旧,可能存在各种安全问题,并不是一个理想的选择.

**Comment by shankerwangmiao** [comment]
发行版包含的版本，如果有安全问题，会 backport 相应的 fix，因此如果没有特别需要，我们反对用户自行从源代码编译。

**Comment by GeniusLe** [comment]
好吧,感谢回应,希望日后如果有考虑的话可以加入,谢谢. closed
