### ISSUE TITLE
镜像常见docker image

### ISSUE THREAD

**Issue by zhsj** [tuna/issues#948]
https://github.com/ustclug/mirrorrequest/issues/276

理论上可以把每个 docker image 当成独立的软件、系统，按需镜像，而不是反代整个 docker hub 或者整个 gcr。目前 skopeo 等工具的出现，也让这个方法变得可行。

**Comment by jiegec** [comment]
opentuna 有计划实现一个类似的东西

**Comment by hanbing0715** [comment]
@jiegec I have already transform skopeo into a api server, also use skopeo make async registry sync pipeline, i think i can give some help.

**Comment by jiegec** [comment]
We have our solutions as well at https://github.com/tuna/aws-ecr-proxy

**Comment by Harry-Chen** [comment]
根据新政策，我们不接受此类镜像。
