### ISSUE TITLE
Jenkins镜像

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#95]
#### 项目名称与简介(Project Intro.)
Jenkins是一个现代化的CI工具，社区活跃度很高，很多大型公司都使用Jenkins做自己的CI工具。

#### 上游地址与镜像方法(How to Mirror)
直接镜像Jenkins的官方仓库即可: http://pkg.jenkins-ci.org/

#### 其他信息(Other)
单文件大约70MB左右

另: Jenkins仓库有mirror，不知道可否申请成为官方mirror: http://mirrors.jenkins-ci.org/

**Comment by abcfy2** [comment]
看到[mirror status](http://mirrors.jenkins-ci.org/status.html)页面只有5个regions:  de   es   jp   pl   us 
如果成为官方承认的镜像仓库，那么会直接增加一个大区cn了，哈哈

**Comment by abcfy2** [comment]
找到了Jenkins的wiki页关于mirror的部分，可以看出他们对于mirror还是很欢迎的。https://jenkins.io/content/mirrors/

**Comment by bigeagle** [comment]
好棒！

**Comment by scateu** [comment]
棒！

--
Wang Kang
Blog: http://scateu.me
Fingerprint: 011F 0492 97D6 5D75 8AC4  6458 D43F 3CE2 3353 B7BD
HAM Callsign: BH1RLW

**Comment by bigeagle** [comment]
给他们发邮件了 还没回

**Comment by bigeagle** [comment]
搞定。

**Comment by abcfy2** [comment]
直接同步http似乎有问题，看到官方仓库中是这个路径(ubuntu/debian):

```
deb http://pkg.jenkins.io/debian-stable binary/
```

> 官方仓库LTS版本的文档: http://pkg.jenkins-ci.org/debian-stable/

可以看到实际`debian-stable`目录下面有个`binary/`目录，但是进一步访问这个目录的时候返回`403`。

这样的话直接同步这个仓库的时候是没法用的，apt-get update会报404:

```
W: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/jenkins/debian-stable/binary/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

等等官方邮件的回复吧，问问他们应该怎么镜像这个仓库。

**Comment by bigeagle** [comment]
他们说的就是从  rsync://rsync.osuosl.org/jenkins 同步

**Comment by bigeagle** [comment]
http://mirrors.jenkins-ci.org/ 显然这个目录结构和 pkg.jenkins.io 不一样，简直坑

**Comment by abcfy2** [comment]
自己用`apt-mirror`同步了下`debain-stable`仓库，发现路径应该是这样的：

```
$ tree pkg.jenkins.io/
pkg.jenkins.io/
└── debian-stable
    └── binary
        ├── jenkins_2.7.2_all.deb
        ├── Packages
        ├── Packages.bz2
        ├── Packages.gz
        ├── Release
        └── Release.gpg

2 directories, 6 files
```

和http页面看到的路径的确不一样。

**Comment by abcfy2** [comment]
我突然想到一种可怕的情况，jenkins的pkg仓库貌似不给同步，其他镜像只能同步哪些deb/rpm/exe/war包文件。

而jenkins的文档中也确实没提供怎么使用下游镜像的方法，都是直接将仓库指向pkg.jenkins-ci.org，然后这个仓库似乎会有302跳转，自动跳转到相对比较快的镜像地址上，但是这个跳转感觉并不准，有时候跳转到日本的镜像上，有时候跳转到德国的镜像上，速度时快时慢的，每次跳转的镜像可能还不一样。这个在apt-get的输出能看到- -

**Comment by abcfy2** [comment]
这个issue目前有新的进展吗？官方有没有提到怎么镜像repo呢？

**Comment by bigeagle** [comment]
没提，我们的官方源申请也没消息。

**Comment by abcfy2** [comment]
如果官方迟迟不回应的话其实也可以考虑反向代理，直接代理到`http://pkg.jenkins.io/`，这样应该能解决仓库的问题

**Comment by abcfy2** [comment]
我的issue官方终于有了回应，已经分配了: https://issues.jenkins-ci.org/browse/INFRA-924

**Comment by abcfy2** [comment]
这个issue应该是已经解决了，我发现jenkins的mirror已经出现了tuna的镜像: http://mirrors.jenkins-ci.org/status.html

**Comment by Harry-Chen** [comment]
Done.

**Comment by icyleaf** [comment]
https://issues.jenkins-ci.org/browse/INFRA-924
最新的状态是因为镜像只支持 https 会有问题，可否在支持下呢？

**Comment by huiyiqun** [comment]
主要问题是，当时登记的镜像站地址是https的，从jenkins跳转到我们的镜像站时就出错了，这并不是我们这边能够解决的问题。

实际上从jenkins跳转到我们时直接跳转到我们的http地址即可，我们对于非浏览器是支持http的。

**Comment by bigeagle** [comment]
应该已经好了，测试一下？

**Comment by icyleaf** [comment]
thanks

**Comment by LinuxSuRen** [comment]
我这里有个镜像的改进思路，有兴趣的可以了解下 https://github.com/jenkins-zh/mirror-adapter

**Comment by abcfy2** [comment]
我觉得直接给jenkins官方提交issue，希望他们改进重定向的策略更省事，而且更靠谱一些。

```
curl -LI http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_2.190.2_all.deb
HTTP/1.1 302 Found
Date: Wed, 13 Nov 2019 11:13:39 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: http://mirrors.jenkins.io/debian-stable/jenkins_2.190.2_all.deb
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 302 Found
Date: Wed, 13 Nov 2019 11:13:39 GMT
Server: Apache/2.4.29 (Ubuntu)
X-MirrorBrain-Mirror: ftp-chi.osuosl.org
X-MirrorBrain-Realm: other
Link: <http://mirrors.jenkins.io/debian-stable/jenkins_2.190.2_all.deb.meta4>; rel=describedby; type="application/metalink4+xml"
Link: <http://ftp-chi.osuosl.org/pub/jenkins/debian-stable/jenkins_2.190.2_all.deb>; rel=duplicate; pri=1; geo=us
Link: <http://ftp-nyc.osuosl.org/pub/jenkins/debian-stable/jenkins_2.190.2_all.deb>; rel=duplicate; pri=2; geo=us
Link: <http://mirror.serverion.com/jenkins/debian-stable/jenkins_2.190.2_all.deb>; rel=duplicate; pri=3; geo=nl
Location: http://ftp-chi.osuosl.org/pub/jenkins/debian-stable/jenkins_2.190.2_all.deb
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Wed, 13 Nov 2019 11:13:41 GMT
Server: Apache
Last-Modified: Mon, 28 Oct 2019 20:33:58 GMT
ETag: "49ef528-595fe6b567d07"
Accept-Ranges: bytes
Content-Length: 77526312
```

通过`curl -LI`检测官方的镜像的302跳转，看`Location`，可以发现跳转路径是这样的: `pkg.jenkins-ci.org` --> `mirrors.jenkins.io` --> `ftp-chi.osuosl.org`。应该是`mirrors.jenkins.io`对于镜像的检测机制不是太好，应该可以给jenkins官方反馈这个问题，只要官方解决下这个问题就好了
