### ISSUE TITLE
404 with wget https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-updates/multiverse/Contents-i386.gz

### ISSUE THREAD

**Issue by rubinliudongpo** [tuna/issues#950]
#### 发生了什么（What happened）
xxxx@xxxx:~/xxxxx$ wget  https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-updates/multiverse/Contents-i386.gz  
--2020-09-01 16:52:15--  https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/focal-updates/multiverse/Contents-i386.gz
Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.8.193, 2402:f000:1:408:8100::1
Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.8.193|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-01 16:52:15 ERROR 404: Not Found.

#### 期望的现象（What you expected to happen）

it is expected to get above Contents-i386.gz readily.

#### 如何重现（How to reproduce it）

this issue can be reproduced readily.

#### 其他事项（Anything else we need to know）

NA

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 20.04 
- 浏览器（如果适用）（Browser version, if applicable）：Chrome
- 其他（Others）：NA

**Comment by shankerwangmiao** [comment]
上游亦无此文件 http://archive.ubuntu.com/ubuntu/dists/focal-updates/multiverse/ ，怀疑是您的 `sources.list` 配置有误，请检查。

**Comment by rubinliudongpo** [comment]
> 上游亦无此文件 http://archive.ubuntu.com/ubuntu/dists/focal-updates/multiverse/ ，怀疑是您的 `sources.list` 配置有误，请检查。
My sources list contents:
deb-i386 https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse
deb-i386 https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse

**Comment by shankerwangmiao** [comment]
您好，请提供您当前操作系统版本、架构，并提供下述命令的输出。`deb-i386` 不是正确的指令。

``` bash
cat /etc/*release
```
