### ISSUE TITLE
AOSP初始化包里包含了什么

### ISSUE THREAD

**Issue by addhaloka** [tuna/issues#951]
最新的aosp-latest.tar达到了84.3 GiB, 里面包含了全部分支的代码?
https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-20200901.tar

理论上讲, 如果我只需要某个分支, 比如android-10.0.0_r45, 是否有办法得到更小的包?

repo sync -c -j4 一天了, 快20G了还没完...

**Comment by addhaloka** [comment]
或者说只需要某个分支下的某些project

**Comment by shankerwangmiao** [comment]
您好，aosp-latest.tar 中包含了打包时完整的 AOSP 源代码仓库。下载展开后可以使用 repo sync 以较快的速度与上游最新的代码取得同步。目前，由于存储空间有限，我们无法针对每个分支分别打包。由于 AOSP 代码仓库较大，您直接使用 repo sync 可能会面临时间较长，且中断后进度难以恢复的问题，这就是我们推荐使用初始化包的原因。

**Comment by addhaloka** [comment]
@shankerwangmiao aosp-latest.tar离线展开后是不是完整的代码呢?假设我并不需要同步最新代码, 是不是不需要联网sync了

**Comment by shankerwangmiao** [comment]
理论上可以，请见 https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/ ，可以使用 `repo sync -l`，`-l` 意为 `--local-only`

**Comment by addhaloka** [comment]
@shankerwangmiao 
https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/external/brotli
这个project好像有问题, checkout不了, 删除后重新repo sync下来也是提示失败
error: external/brotli/: platform/external/brotli checkout 75da6227c64a7c3f271fefa1843711b94d763ea8

**Comment by google-mirror** [comment]
> 您好，aosp-latest.tar 中包含了打包时完整的 AOSP 源代码仓库。下载展开后可以使用 repo sync 以较快的速度与上游最新的代码取得同步。目前，由于存储空间有限，我们无法针对每个分支分别打包。由于 AOSP 代码仓库较大，您直接使用 repo sync 可能会面临时间较长，且中断后进度难以恢复的问题，这就是我们推荐使用初始化包的原因。

怎么切换分支, 只有repo start master是成功的, repo start其他分支都是失败, 如果repo init切换manifest到其他分支, 感觉aosp-latest.tar没啥用了啊, repo sync同样需要同步很长时间

**Comment by JailedBird** [comment]
您好， 可以完善下基于tar进行Aosp历史版本切换的文档么？  目前想切换到 android-4.0.1_r1后同步代码，但是报错；【PS：不懂如何切换分支、（离线）同步】

![image](https://github.com/tuna/issues/assets/113177053/6b36c100-5253-415a-9d6e-7809486ea38e)
