### ISSUE TITLE
[Mirror request] gradle distributions

### ISSUE THREAD

**Issue by Rsplwe** [tuna/issues#955]
#### 项目名称与简介(Project Intro.)
Gradle
#### 上游地址与镜像方法(How to Mirror)
https://services.gradle.org/
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by jiegec** [comment]
见 #505 的讨论

**Comment by Rsplwe** [comment]
发这个镜像请求之前已经看过这个issue了，不过根据我的实际情况来看，Cloudflare大部分网络的访问速度还是比较不理想的，大部分时候只有10kb/s - 150kb/s左右

**Comment by jiegec** [comment]
上游没有支持，见 https://github.com/tuna/issues/issues/505#issuecomment-458856323

**Comment by jiegec** [comment]
可以去 https://github.com/gradle/gradle/issues/5943#issuecomment-466927610 反应一下国内 CDN 结点的问题

**Comment by Rsplwe** [comment]
> 可以去 [gradle/gradle#5943 (comment)](https://github.com/gradle/gradle/issues/5943#issuecomment-466927610) 反映一下国内 CDN 结点的问题

查询了一下 gradle-dn.com 的ICP备案，貌似已经不存在了，所以应该不会有国内CDN节点的存在

**Comment by pan3793** [comment]
Found a mirror provided by Tencent. https://mirrors.cloud.tencent.com/gradle/
