### ISSUE TITLE
LLVM 新官方 git 库镜像

### ISSUE THREAD

**Issue by cheese** [tuna/issues#957]
LLVM git 库已正式迁移为 https://github.com/llvm/llvm-project
https://mirrors.tuna.tsinghua.edu.cn/help/llvm/ 当前同步的 https://github.com/llvm-mirror 已归档。
请转移至镜像新 git 库

**Comment by phy25** [comment]
Related to https://github.com/tuna/issues/issues/939

**Comment by shankerwangmiao** [comment]
> Related to #939

跟它没关系，那个是 HHVM，不是 LLVM

**Comment by happyaron** [comment]
bare repo 有 1.1G……

**Comment by Harry-Chen** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/llvm-project.git/
