### ISSUE TITLE
申请NetBSD镜像

### ISSUE THREAD

**Issue by zhangteng331** [tuna/issues#96]
#### 项目名称与简介(Project Intro.)

    NetBSD,4.4BSD后裔，可参考https://en.wikipedia.org/wiki/NetBSD

#### 上游地址与镜像方法(How to Mirror)

NetBSD镜像列表：http://www.netbsd.org/mirrors/
其他所有相关信息包括各种问题的解答：http://www.netbsd.org/docs/mirror.html

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

详见：http://www.netbsd.org/docs/mirror.html

备注：1.NetBSD的硬件平台较多（http://www.netbsd.org/ports/），
              建议只同步i386、amd64、armv7（可能不是NetBSD的具体应用名）
              和loogsoon。
           2. pkgsrc是包管理工具（类似于apt/yum），其软件包汇总的目录名称也是pkgsrc。

**Comment by bigeagle** [comment]
终于同步完了，测试一下？

**Comment by zhangteng331** [comment]
好的好的，我也等了很长时间，是不是同步的镜像服务器太慢了呀，原来同步OpenBSD的时候没有这样的问题呀
非常感谢你们对NetBSD社区的支持，谢谢。

2016-08-21 18:29 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by bigeagle** [comment]
的确，镜像不大，你之前用的是哪个上游？

**Comment by zhangteng331** [comment]
日本：ftp.jaist.ac.jp(http,ftp,rsync）

在TUNA同步OpenBSD之前，我用的也是ftp.jaist.ac.jp

对了，我刚刚下载了NetBSD的amd64镜像，下载后可以正常安装，it's done.



2016-08-25 15:07 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by bigeagle** [comment]
可能的话，能否仿照 https://github.com/tuna/mirror-web/tree/master/_posts/help 里的内容写个帮助文档，发 Pull Request ？

**Comment by bigeagle** [comment]
或者直接跟在这里也可以。

**Comment by zhangteng331** [comment]
嗯，写在这里吧

支持ftp协议的镜像列表：
      日本：
               ftp2.jp.netbsd.org/pub/NetBSD
               ftp6.jp.netbsd.org/pub/NetBSD
               ftp7.jp.netbsd.org/pub/NetBSD
               core.ring.gr.jp/pub/NetBSD
               ftp.jaist.ac.jp/pub/NetBSD
     韩国：
               ftp.kaist.ac.kr/NetBSD

支持http协议的镜像列表：
     日本：
              ftp.jaist.ac.jp/pub/NetBSD
     韩国：
              ftp.kaist.ac.kr/NetBSD

支持rsync协议的镜像列表：
     日本:
             rsync2.jp.netbsd.org/netbsd
             rsync3.jp.netbsd.org/NetBSD
             rsync://ftp.jaist.ac.jp/pub/NetBSD (未经过验证，字符可能为netbsd或者NetBSD）
    韩国：
             rsync://ftp.kaist.ac.kr/netbsd

同步方法同首次的方法，详见github上的issue或者http://www.netbsd.org/docs/mirror.html

备注：上述部分服务器不包含在Net BSD官方的列表中，是我自己整理的。
          我感觉很别扭的关于镜像服务器的一点就是，他们并不能严格遵循镜像官方的命名
          方法，例如镜像不在pub目录下，还有最普遍的是大小写不一致（Debian/debian,
          NetBSD/netbsd, ...), 所以有的时候会出现404目录不存在的情况，请你在同步时注意
          一下啊，谢谢。


2016-08-25 15:31 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by zhangteng331** [comment]
日本和韩国的服务器比美国的相对来说快些，
但是实际情况受到磁盘读取，网络延迟，系统处理等许许多多的因素，
性能以实际为准。
建议使用ftp.jaist.ac.jp进行同步，看起来这个服务器的目录挺标准的。

2016-08-25 15:31 GMT+08:00 bigeagle <notifications@github.com>:

**Comment by bigeagle** [comment]
放在 pub 目录下很重要吗？除了一些历史悠久的镜像受条件限制之外，没有必要再弄这么一层了吧，因为现在的镜像都是 pub 的。

**Comment by zhangteng331** [comment]
嗯，我以偏概全了，对新兴的project了解不多。(看起来，大部分都是这样的）
也许以兼容性的理由建立pub目录有点不值吧。

2016-08-25 21:35 GMT+08:00 bigeagle <notifications@github.com>:
