### ISSUE TITLE
[opentuna]Mirror Request for new mirror linuxmint

### ISSUE THREAD

**Issue by netroby** [tuna/issues#960]
#### 项目名称与简介(Project Intro.)
Linuxmint
#### 上游地址与镜像方法(How to Mirror)
https://linuxmint.com/mirrors.php
#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by netroby** [comment]
opentuna.cn上面没有linuxmint，请求支持

**Comment by jiegec** [comment]
@netroby 需要 linuxmint-cd 吗

**Comment by netroby** [comment]
一起加一下呗，大佬，造福众生。

**Comment by jiegec** [comment]
https://opentuna.cn/linuxmint/
