### ISSUE TITLE
镜像速度不稳定吗？经常会变成0，甚至断掉

### ISSUE THREAD

**Issue by zfavourite99** [tuna/issues#963]
今天使用 cocoapods 镜像的时候，速度很不稳定

`git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master`

一开始是几百k，后来会变成 几k，过一两分钟又会回到1m多，几天前在另一台电脑还能达到10m。而且经测试不是我网络问题，我下载 cocos creator IDE 速度稳定在 4-5m 每秒，但是 clone 这个仓库就是上述的情况，很不稳定，慢的很，有时候直接就报错停止了。

![image](https://user-images.githubusercontent.com/2630290/92718993-22569e00-f395-11ea-8d89-17aaa37f9cd8.png)

**Comment by shankerwangmiao** [comment]
您好，我刚才测试了一下，速度基本在 5MiB/s  以上。

![image](https://user-images.githubusercontent.com/6825907/92725954-76668000-f39f-11ea-8b03-a8ac051bffb9.png)
![image](https://user-images.githubusercontent.com/6825907/92726042-98600280-f39f-11ea-8dbd-7ae28c11a878.png)
