### ISSUE TITLE
[bfsu]404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by Qa7060123** [tuna/issues#964]
#### 发生了什么（What happened）
源没啦！！
#### 期望的现象（What you expected to happen）
源没啦！！
#### 如何重现（How to reproduce it）
源没啦！！
#### 其他事项（Anything else we need to know）
源没啦！！
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by jiegec** [comment]
见 https://github.com/tuna/issues/issues/619
