### ISSUE TITLE
[404 Not Found | BFSU Mirror Site] openSUSE Tumbleweed ISO 无法下载

### ISSUE THREAD

**Issue by whriedplanck** [tuna/issues#966]
任意一个 Tumbleweed ISO 链接（从网站右侧的「获取下载链接」处）点开都会如下报告 404：

![图片.png](https://i.loli.net/2020/09/12/iT6hUtND1wbqZgB.png)

**Comment by whriedplanck** [comment]
已自行进一步了解到是 openSUSE 镜像同步失败的缘故。

**Comment by imbillow** [comment]
openwrt 也有
https://mirrors.bfsu.edu.cn/openwrt/snapshots/targets/ramips/mt7621/packages/Packages.gz
![image](https://user-images.githubusercontent.com/24983369/92994382-51ebde80-f52c-11ea-8fad-dd14f84e7eec.png)

**Comment by whriedplanck** [comment]
openSUSE 相关现已解决。

**Comment by dotkrnl** [comment]
> openwrt 也有
> https://mirrors.bfsu.edu.cn/openwrt/snapshots/targets/ramips/mt7621/packages/Packages.gz
> ![image](https://user-images.githubusercontent.com/24983369/92994382-51ebde80-f52c-11ea-8fad-dd14f84e7eec.png)

见 #619 ，snapshots 未被同步且暂无同步计划。

**Comment by dotkrnl** [comment]
> openSUSE 相关现已解决：再尝试可以下载了。

感谢。我将关闭这一 issue。
