### ISSUE TITLE
[镜像请求]RISCV GNU 工具链

### ISSUE THREAD

**Issue by SKTT1Ryze** [tuna/issues#968]
github 传送门：[riscv-gnu-toolchain](https://github.com/riscv/riscv-gnu-toolchain)  
这个 riscv 的 GNU 交叉编译工具链下载很慢，如果能加快速度，将会对国内的 riscv 开发者和爱好者提供很大便利

**Comment by jiegec** [comment]
你指的是源代码，还是二进制？

**Comment by SKTT1Ryze** [comment]
> 你指的是源代码，还是二进制？

源码可以吗

**Comment by SKTT1Ryze** [comment]
> 你指的是源代码，还是二进制？

archlinux 的 AUR 仓库可以直接下 riscv-known-elf-gcc 和 riscv64-unknown-elf-newlib 这些二进制文件，要是 ubuntu 也能直接从包管理里面下这些工具的话就好办了

**Comment by SKTT1Ryze** [comment]
Close this issure.
