### ISSUE TITLE
[tuna]404 at /404-help-hidden.html

### ISSUE THREAD

**Issue by daruo** [tuna/issues#970]
#### 发生了什么（What happened）
刚开始下载速度很快 2-5m/s
后来越来越慢 直至挂起
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
在进行cocoapods 克隆时，远端挂起
#### 期望的现象（What you expected to happen）
希望可以正常clone
#### 如何重现（How to reproduce it）
git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git master

#### 其他事项（Anything else we need to know）
以将 git http 和 https 的 传输buffer 设置为
#### 您的环境（Environment）
- 操作系统（OS Version）：MAC 10.15.6 (19G2021)
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
dup with #963
