### ISSUE TITLE
网站404，无法访问

### ISSUE THREAD

**Issue by Gladtbam** [tuna/issues#971]
#### 发生了什么（What happened）
无法访问镜像站

https://openwrt.proxy.ustclug.org/snapshots/targets/ath79/generic/packages
https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/base
https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/freifunk
https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/packages
https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/routing
https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/telephony

#### 您的环境（Environment）
- 操作系统（OS Version）：OpenWrt
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
请前往 https://github.com/ustclug/discussions/issues 报告。
