### ISSUE TITLE
Manjaro 软件仓库镜像站过期

### ISSUE THREAD

**Issue by SamLukeYes** [tuna/issues#972]
#### 发生了什么（What happened）
![2020-09-15 22.40.10 mirrors.tuna.tsinghua.edu.cn 03c2a3fb134a.png](https://i.loli.net/2020/09/15/9YeX8SCrNODZR7x.png)
![2020-09-15 20.27.16 repo.manjaro.org f44c6ebd66b1.png](https://i.loli.net/2020/09/15/uRBbAMdkGxLeoND.png)
TUNA 镜像站主页显示 Manjaro 仓库镜像同步成功，但 Manjaro 官网显示中国大陆的镜像站全员阵亡

#### 期望的现象（What you expected to happen）
在 https://repo.manjaro.org 应该看到 TUNA 镜像的三个分支都是 up to date

#### 如何重现（How to reproduce it）
打开 https://repo.manjaro.org 和 https://mirrors.tuna.tsinghua.edu.cn
两边显示的同步状况不一致

#### 其他事项（Anything else we need to know）
近期在 unstable 分支用国内的镜像站时不时会出现检测到某个软件包有更新，但下载时在所有国内镜像站都 404 的情况，因此我认为 Manjaro 官网显示的同步情况更可靠。根据 Manjaro 官网的数据，国内已经没有可靠的 Manjaro 镜像站。希望 TUNA 能尽快查明原因并予以修复。

#### 您的环境（Environment）
- 操作系统（OS Version）：Manjaro 20.1 (unstable branch)

**Comment by Harry-Chen** [comment]
我们从 rsync://mirror.yandex.ru/mirrors/manjaro/ 同步，多半是上游问题

**Comment by SamLukeYes** [comment]
> 我们从 rsync://mirror.yandex.ru/mirrors/manjaro/ 同步，多半是上游问题

现在包括 TUNA 在内的国内镜像已经不是标红了，但仍然没有一个 unstable 分支是最新的。这个上游确实不靠谱，现在我看它 unstable 分支也不是最新的，难怪我在 unstable 分支更新的时候经常出问题。

目前我添加了德国的镜像 https://mirror.alpix.eu/manjaro/ 备用，我这几天看这个镜像一直是标绿的。

**Comment by shankerwangmiao** [comment]
manjaro 是如何监测镜像站过期与否的机制我们不掌握。yandex.ru 的镜像是官方推荐的同步来源，详见 https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors 。目前 TUNA 服务器上的 unstable 的时间戳是北京时间今早 3 点，我不认为这种情况是过期。对于变化更新过于频繁的软件仓库分支，TUNA 无法保证其时时刻刻与官方都是一致的，镜像站存在延迟是正常现象。

**Comment by phy25** [comment]
https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors#Do_You_Manage_a_Potential_Manjaro_Mirror_Server.3F 提到镜像站需要每 6 小时进行一次同步，境内直连的网络速度完成这个频次的 unstable 同步较有难度。对 https://repo.manjaro.org/ 按 Last Sync 时间排序，显然同步时间较近的站点的状态相对较好。建议您 unstable 分支的使用需求，可通过直接使用境外镜像站解决。

Manjaro 的校验逻辑供参考：

- https://gitlab.manjaro.org/webpage/manjaro-web-repo/-/blob/master/src/mirror.py#L24
- https://gitlab.manjaro.org/webpage/manjaro-web-repo/-/blob/master/src/builder.py#L88-94

*利益声明：非 TUNA 成员。*

**Comment by shankerwangmiao** [comment]
> https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors#Do_You_Manage_a_Potential_Manjaro_Mirror_Server.3F 提到镜像站需要每 6 小时进行一次同步，境内直连的网络速度完成这个频次的 unstable 同步较有难度。对 https://repo.manjaro.org/ 按 Last Sync 时间排序，显然同步时间较近的站点的状态相对较好。建议您 unstable 分支的使用需求，可通过直接使用境外镜像站解决。
> 
> Manjaro 的校验逻辑供参考：
> 
> * https://gitlab.manjaro.org/webpage/manjaro-web-repo/-/blob/master/src/mirror.py#L24
> * https://gitlab.manjaro.org/webpage/manjaro-web-repo/-/blob/master/src/builder.py#L88-94
> 
> _利益声明：非 TUNA 成员。_

事实上，TUNA 就是 6 每隔六个小时进行的一次同步。

**Comment by SamLukeYes** [comment]
> manjaro 是如何监测镜像站过期与否的机制我们不掌握。yandex.ru 的镜像是官方推荐的同步来源，详见 https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors 。目前 TUNA 服务器上的 unstable 的时间戳是北京时间今早 3 点，同步是今早 8 点完成的，我不认为这种情况是过期。对于变化更新过于频繁的软件仓库分支，TUNA 无法保证其时时刻刻与官方都是一致的，镜像站存在延迟是正常现象。

奇怪，Manjaro 推荐的那几个镜像站没一个是标绿的

**Comment by SamLukeYes** [comment]
今天在更新系统的时候遇到有一个软件包无法下载了，大概还是这个问题吧

    错误：无法从 mirrors.ustc.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
    错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
    错误：无法从 mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
    错误：无法从 mirrors.aliyun.com : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'

**Comment by shankerwangmiao** [comment]
> 今天在更新系统的时候遇到有一个软件包无法下载了，大概还是这个问题吧
> 
> ```
> 错误：无法从 mirrors.ustc.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
> 错误：无法从 mirrors.sjtug.sjtu.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
> 错误：无法从 mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
> 错误：无法从 mirrors.aliyun.com : The requested URL returned error: 404 获取文件 'game-devices-udev-0.10-1-any.pkg.tar.zst'
> ```
> 
> 对照 repo.manjaro.org 上的信息，国内的镜像站确实都没有完成 unstable 分支的同步，而 tuna 上并没有显示同步失败或者同步中。 @shankerwangmiao

事实上，我们的上游也没有。http://mirror.yandex.ru/mirrors/manjaro/unstable/community/x86_64/

**Comment by 1900011604** [comment]
> > 我们从 rsync://mirror.yandex.ru/mirrors/manjaro/ 同步，多半是上游问题
> 
> 现在包括 TUNA 在内的国内镜像已经不是标红了，但仍然没有一个 unstable 分支是最新的。这个上游确实不靠谱，现在我看它 unstable 分支也不是最新的，难怪我在 unstable 分支更新的时候经常出问题。
> 
> 目前我添加了德国的镜像 https://mirror.alpix.eu/manjaro/ 备用，我这几天看这个镜像一直是标绿的。

如果上游要用俄罗斯的镜像的话，`mirror.truenetwork.ru/manjaro`如何？这个的同步挺快的

**Comment by taoky** [comment]
> > > 我们从 rsync://mirror.yandex.ru/mirrors/manjaro/ 同步，多半是上游问题
> > 
> > 
> > 现在包括 TUNA 在内的国内镜像已经不是标红了，但仍然没有一个 unstable 分支是最新的。这个上游确实不靠谱，现在我看它 unstable 分支也不是最新的，难怪我在 unstable 分支更新的时候经常出问题。
> > 目前我添加了德国的镜像 https://mirror.alpix.eu/manjaro/ 备用，我这几天看这个镜像一直是标绿的。
> 
> 如果上游要用俄罗斯的镜像的话，

https://github.com/tuna/issues/issues/972#issuecomment-693155536

> yandex.ru 的镜像是官方推荐的同步来源，详见 https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors 

如果镜像要换上游的话，最好在这个列表里面选。
