### ISSUE TITLE
Mirror request: EndeavourOS

### ISSUE THREAD

**Issue by EndeavourOS** [tuna/issues#974]
Hi,

We are an Arch Linux based distro and one of our Chinese community members has been dedicating your service to act as a mirror.

Hereby I submit a request for mirroring our repo on your servers, to make our packages better available in China. We are more than happy to provide you with the necessary info in case you decide to act as our mirror.

Best regards,

Bryan Poerwoatmodjo
Project leader EndeavourOS

**Comment by jiegec** [comment]
Can you provide a url of rsync server?

**Comment by jiegec** [comment]
> Can you provide a url of rsync server?

Thanks, got it off issue.

**Comment by EndeavourOS** [comment]
> Can you provide a url of rsync server?

I've emailed you the info.

**Comment by jiegec** [comment]
> > Can you provide a url of rsync server?
> 
> I've emailed you the info.

Side note: we publicize upstreams of our repos at https://mirrors.tuna.tsinghua.edu.cn/status/, is that ok?

**Comment by EndeavourOS** [comment]
that's okay.

**Comment by shankerwangmiao** [comment]
The mirror is up online at https://mirrors.tuna.tsinghua.edu.cn/endeavouros/ and rsync://mirrors.tuna.tsinghua.edu.cn/endeavouros/ now.
