### ISSUE TITLE
opentuna少了很多镜像啊，比如Manajaro, Ubuntu-cloud-images等等

### ISSUE THREAD

**Issue by abcfy2** [tuna/issues#977]
看opentuna的说明是直接托管在CDN上，是否考虑干脆直接反向代理tuna呢？这样以前的镜像一个都不少，而且还有CDN加速？不然看到新站点上少了一大半镜像好难受

**Comment by jiegec** [comment]
> 看opentuna的说明是直接托管在CDN上，是否考虑干脆直接反向代理tuna呢？这样以前的镜像一个都不少，而且还有CDN加速？不然看到新站点上少了一大半镜像好难受

不考虑。回源的带宽不足以提供优质的服务。

> opentuna少了很多镜像啊，比如 Manjaro, Ubuntu-cloud-images 等等

会逐渐增加的。
