### ISSUE TITLE
请求更新deepin软件包仓库

### ISSUE THREAD

**Issue by luisleee** [tuna/issues#979]
deepin 20现已发布.请求更新deepin软件包仓库

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/deepin-cd/20/

**Comment by luisleee** [comment]
Hey.这是CD镜像,不是软件包仓库.

**Comment by shankerwangmiao** [comment]
https://mirrors.tuna.tsinghua.edu.cn/deepin/
http://packages.deepin.com/deepin/

二者是一致的。

**Comment by luisleee** [comment]
但最新的仓库在community-packages.deepin.com

**Comment by shankerwangmiao** [comment]
Deepin 反馈，您提及的仓库将会在近期合并入 packages.deepin.com/deepin，届时所有的镜像站都会原样同步。

**Comment by luisleee** [comment]
🙏


在2020年9月18日 20:15，Miao Wang<notifications@github.com> 写道：

Deepin 反馈，您提及的仓库将会在近期合并入 packages.deepin.com/deepin，届时所有的镜像站都会原样同步。
