### ISSUE TITLE
[Rust] request for crates.io mirror

### ISSUE THREAD

**Issue by cdluminate** [tuna/issues#98]
#### 项目名称与简介(Project Intro.)

[The Rust community’s crate host](https://crates.io/)  
Note, USTC has this [mirror](http://ftp.cn.debian.org/crates/) already.  
#### 镜像方法(How to Mirror)
1. https://github.com/tennix/crates-mirror  
2. https://github.com/ustcmirror/docker-cratesmirror [the one used by USTC]  
#### 其他信息(Other)
- 镜像大小(Mirror Size): Unknown, found nothing on [this page](http://ftp.cn.debian.org/status/) neither.  
- 镜像使用方法(Mirror Usage): https://lug.ustc.edu.cn/wiki/mirrors/help/crates

**Comment by loggerhead** [comment]
也可以考虑用这个：https://github.com/ChrisMacNaughton/cargo-cacher

**Comment by bigeagle** [comment]
不太理解这个，怎么还牵扯到 git ……
我理解应该就是把所有包下下来，然后有个索引文件，拿 nginx 直接 serve 出去就好了。
如果太复杂的话，我们没有专业 rust 开发者，很难维护，最后可能就跟 npm 一样只能关掉了。

**Comment by Matrix-Zhang** [comment]
求！！！

**Comment by bigeagle** [comment]
我想知道……cargo-cacher 要怎么 build ……

**Comment by loggerhead** [comment]
@bigeagle 得先安装 rust 的环境，然后将仓库 clone 到本地，再 `cargo build` 就行了

**Comment by huiyiqun** [comment]
https://hub.docker.com/r/gaoyifan/cargo-cacher/

直接用隔壁的docker吧

**Comment by Harry-Chen** [comment]
似乎这个问题被搁置了很久。 @jiegec 好像很熟悉 rust，不如让他看看？

**Comment by jiegec** [comment]
ustc 的 crates mirror 我记得是可用的。不过需要额外装软件，需要一些维护成本。

**Comment by redtankd** [comment]
rustup已经有镜像了，crate可以有吗？

**Comment by zzhaolei** [comment]
16年接受的，到现在还没有影子，希望快点上线啊

**Comment by jiegec** [comment]
看了下 https://github.com/ChrisMacNaughton/cargo-cacher 比较完善，但实际上还是个反代？

**Comment by z4yx** [comment]
有办法全量下载和同步吗，避免使用反代的方式

**Comment by jiegec** [comment]
我自己测试了一下，是可以的：

```
git clone git@github.com:rust-lang/crates.io-index.git
```

然后修改 ~/.cargo/config：

```
git@github.com:rust-lang/crates.io-index.git
[source.crates-io]
replace-with = 'local'

[source.local]
registry = "ssh://localhost:/path/to/crates.io-index"

```

如果换成 git http-backend，应该就能用了？

**Comment by z4yx** [comment]
求搞一个类似rustup的docker镜像，或者整合到rustup的镜像里面。方便tunasync调用。

**Comment by luojia65** [comment]
2333希望可行，等了好久了

**Comment by jiegec** [comment]
@z4yx 我的意思是可以当成普通git仓库来镜像

**Comment by z4yx** [comment]
已添加 https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git

**Comment by Sherlock-Holo** [comment]
@z4yx 
```toml
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
```

如此配置的话，使用时 cargo 会说

>  Couldn't get package repository: empty index directory.

ustc 的 registry 是可以 `git://mirrors.ustc.edu.cn/crates.io-index` 或者 `https://mirrors.ustc.edu.cn/crates.io-index`

把 tuna 的地址改为 `https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index` `git://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git` `git://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index` 均不行

请问正确的地址是多少？

**Comment by z4yx** [comment]
这个地址没问题。 @jiegec 帮忙复现一下？

**Comment by jiegec** [comment]
我这用起来是正常的，估计是网络问题？

**Comment by z4yx** [comment]
那有可能，之前也接到过很多关于TUNA的git镜像不可用的报告，但目前我能接触到的网络环境都不能复现问题，因此无从调试。

**Comment by Sherlock-Holo** [comment]
测试网络为中国电信和腾讯云 HK

均返回 

> Couldn't get package repository: empty index directory.

**Comment by Sherlock-Holo** [comment]
另外 `.cargo/config` 内容为 https://fars.ee/YtRD/

**Comment by z4yx** [comment]
> 测试网络为中国电信和腾讯云 HK
> 
> 均返回
> 
> > Couldn't get package repository: empty index directory.

我在腾讯云HK上用你的配置文件测试没有问题

```
root@55e83d836ae5:~/.cargo# cargo search
    Updating `https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git` index
a = "0.0.1"
a1 = "0.1.1"             # This is a test crate. Thanks for coming my homepage.
a2 = "0.5.1"             # A native, asynchronous Apple push notification client
a2s = "0.1.1"            # Rust implementation of Source A2S query
a3mo_lib = "0.3.0"       # Arma3 Mod Organizer libary. Provides functions for CLI Client and GUI
a42-__- = "0.1.0"        # Answer to the Ultimate Question of Life, The Universe, and Everything
a793556702 = "0.1.3"     # A very simple crate to test publishing to crates.io.
aa = "0.0.1"             # Placeholder. You can contact me (visit crate homepage) and I will be happy to transfer this name to yo…
aa2 = "0.0.0"            # add all files in git repository to index, optionally limited to one or more directories
aaaaa-codec = "0.0.0"    # Lightweight, efficient, binary serialization and deserialization codec
... and 37846 crates more (use --limit N to see more)
```

![image](https://user-images.githubusercontent.com/2733275/77821436-35e2b500-7125-11ea-8b6c-37137f626ed1.png)

**Comment by Sherlock-Holo** [comment]
3.30 测试，中国电信正常，无法得知问题原因
