### ISSUE TITLE
Mirror Requests 镜像请求

### ISSUE THREAD

**Issue by zhaoliangcn** [tuna/issues#983]
项目名称 Linux-libre
项目简介 https://baike.baidu.com/item/Linux-libre/19866742
上游源地址 http://linux-libre.fsfla.org/pub/linux-libre/releases/
镜像方法 http站点镜像即可

**Comment by shankerwangmiao** [comment]
由于该项目使用人数较少，且没有合适的同步方法，暂时不考虑镜像。

**Comment by zhaoliangcn** [comment]
实际上清华是有镜像的，只不过没有更新到最新，最后一次更新时间是 2018-07-26 12:55
https://mirrors.tuna.tsinghua.edu.cn/gnu/linux-libre/
