### ISSUE TITLE
BFSU镜像教程似乎存在一点问题

### ISSUE THREAD

**Issue by sjllls** [tuna/issues#986]
教程地址： https://mirrors.bfsu.edu.cn/help/lineageOS/

其中

> 将
> ```
>   <remote  name="aosp"
>            fetch="https://android.googlesource.com"
> ```
> 改成
> ```
>   <remote  name="aosp"
>            fetch="https://aosp.tuna.tsinghua.edu.cn"
> ```

在同步Lineage OS的过程中，BFSU的教程把AOSP mirror定向到了TUNA，但是BFSU本身是有mirror的，这是为了减轻服务器压力，还是一处小错误呢？

**Comment by jiegec** [comment]
@sjllls 你可以试试：

```
  <remote  name="aosp"
           fetch="https://mirrors.bfsu.edu.cn/git/AOSP"
```

**Comment by sjllls** [comment]
> @sjllls 你可以试试：
> 
> ```
>   <remote  name="aosp"
>            fetch="https://mirrors.bfsu.edu.cn/git/AOSP"
> ```

@jiegec  这我倒是知道，我只是提醒一下BFSU的教程可能存在问题 XD
如果本意是为了给TUNA分流减压的话，教程这里AOSP源忘记修改了话，可能分流效果就不太明显了。

**Comment by jiegec** [comment]
> > @sjllls 你可以试试：
> > ```
> >   <remote  name="aosp"
> >            fetch="https://mirrors.bfsu.edu.cn/git/AOSP"
> > ```
> 
> @jiegec 这我倒是知道，我只是提醒一下BFSU的教程可能存在问题 XD
> 如果本意是为了给TUNA分流减压的话，教程这里AOSP源忘记修改了话，可能分流效果就不太明显了。

嗯，如果这样没问题的话，我去改一下文档。

**Comment by sjllls** [comment]
> 
> 嗯，如果这样没问题的话，我去改一下文档。

@jiegec  `force-sync` 之后查看了一下git目录下的config，已经从BFSU同步源码了，这样修改应该没问题

```
[remote "aosp"]
	url = https://mirrors.bfsu.edu.cn/git/AOSP/platform/external/python/google-api-python-client
	review = android-review.googlesource.com
	projectname = platform/external/python/google-api-python-client
	fetch = +refs/heads/*:refs/remotes/aosp/*

```
