### ISSUE TITLE
Anaconda源的flask和pandas版本过低

### ISSUE THREAD

**Issue by Rutherford1895** [tuna/issues#987]
如题

**Comment by shankerwangmiao** [comment]
您好，我们 anaconda 的镜像与上游保持一致，如果上游版本也不符合您需求，请您与上游联系；如果上游版本和镜像站上版本不一致，可能是由于同步的固有延迟所致，请耐心等候下一次同步。如果后一种问题持续存在，请继续反馈，我们会进一步排查。
