### ISSUE TITLE
[tuna]404 at /anaconda/cloud/pytorch/win-64/current_repodata.json

### ISSUE THREAD

**Issue by NasonChan** [tuna/issues#988]
conda install django-request
Collecting package metadata (current_repodata.json): failed

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
请给出完整的出错信息，该文件不存在一般不影响正常使用。

**Comment by shankerwangmiao** [comment]
该文件上游亦不存在，https://conda.anaconda.org/pytorch/win-64/current_repodata.json
