### ISSUE TITLE
Can not locate config makefile for product "lineage_lavender"

### ISSUE THREAD

**Issue by huo108** [tuna/issues#989]
repo sync 成功后
执行：source build/envsetup.sh
然后执行：breakfast lavender 提示错误
user@user-System-Product-Name:/media/user/abc/lineageOS$ breakfast lavender
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "lineage_lavender".
14:28:05 dumpvars failed with: exit status 1
Device lavender not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Failed to search GitHub
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "lineage_lavender".
14:28:06 dumpvars failed with: exit status 1
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "lineage_lavender".
14:28:06 dumpvars failed with: exit status 1

请问这个是lavender没有镜像么，还是其他什么原因？如何解决？

**Comment by huo108** [comment]
这是我repo sync的代码和分支
repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
repo sync -c -f -j1 --force-sync --no-clone-bundle

**Comment by shankerwangmiao** [comment]
您好，经查，https://github.com/LineageOS/android_device_xiaomi_lavender 该仓库在 TUNA 镜像中存在，地址是https://mirrors.tuna.tsinghua.edu.cn/git/lineageOS/LineageOS/android_device_xiaomi_lavender 。具体软件的编译问题请向该软件官方咨询。
