### ISSUE TITLE
[tuna]404 at /openwrt/snapshots/targets/

### ISSUE THREAD

**Issue by izwb003** [tuna/issues#991]
#### 发生了什么（What happened）
OpenWRT的镜像好像并没有提供snapshots的镜像，访问直接404。https://downloads.openwrt.org/snapshots/targets/则可以直接访问。

#### 期望的现象（What you expected to happen）
https://mirrors.tuna.tsinghua.edu.cn/openwrt/snapshots/targets/可以提供服务。

#### 如何重现（How to reproduce it）
...直接访问就好

#### 其他事项（Anything else we need to know）
无（另，辛苦各位的努力！）

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 ver.1909
- 浏览器（如果适用）（Browser version, if applicable）：Mozilla Firefox 81.0
- 其他（Others）：无

**Comment by phy25** [comment]
Duplicate of #619.
