### ISSUE TITLE
homebrew-cask-versions 镜像请求

### ISSUE THREAD

**Issue by qianbinbin** [tuna/issues#992]
#### 项目名称与简介(Project Intro.)

homebrew-cask-versions
Alternate versions of Casks

#### 上游地址与镜像方法(How to Mirror)

https://github.com/Homebrew/homebrew-cask-versions
目前清华源上 brew 的其它镜像都有了，但是没有 homebrew-cask-versions

#### 其他信息(Other)
- 镜像大小(Mirror Size):

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-versions.git
现已在 tuna 上增加了镜像。

https://github.com/tuna/mirror-web/commit/357ff93a9f9f39583edf578ca4eb46b60c164c1f
同时增加了使用说明。
