### ISSUE TITLE
ubuntu镜像地址有点问题

### ISSUE THREAD

**Issue by daichenglong** [tuna/issues#994]
https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/

这个目录是不是有点深了？

**Comment by xavieryao** [comment]
1 或更多个重复的 /ubuntu 均可作为镜像地址。
