### ISSUE TITLE
aosp-monthly文件太大

### ISSUE THREAD

**Issue by ZR-RAN** [tuna/issues#997]
为了下载某一个分支而把所有分支都下载下来是不划算的，能否在新的包中删除过旧的分支或者按照Android版本分别打包。

**Comment by shankerwangmiao** [comment]
如果您对 git 的版本控制机制比较熟悉的话，git 的分支实际上是指向特定提交的指针引用，因此删除分支并不会缩小代码仓库大小。如果您不需要历史版本，而是仅需要查看代码的话，可以直接前往 https://cs.android.com 。

**Comment by ZR-RAN** [comment]
虽然我对git不是很熟悉，但是事实就是你可以看到每个月打包的大小都比上个月增加了好几个G。

**Comment by shankerwangmiao** [comment]
是的，这是因为有新的代码不断进入仓库。
