### ISSUE TITLE
Mirror Requirement for Python

### ISSUE THREAD

**Issue by Forrest-Zhang** [tuna/issues#998]
# 项目名称
Python
Official WEB site: https://www.python.org

# 项目简介
Python is a programming language that lets you work quickly and integrate systems more effectively.

# 上游源地址，或镜像方法
https://www.python.org/ftp/python/

# 尽量详细的镜像信息（例如镜像大小）

Requested by Forrest Zhang
2020-10-8

**Comment by shankerwangmiao** [comment]
dup with #846
