### ISSUE TITLE
请求建立Stellarium镜像

### ISSUE THREAD

**Issue by ultrapre** [tuna/issues#999]
stellarium天文馆，著名的GPL自由软件。版本更新算是很勤的。

release地址：https://github.com/Stellarium/stellarium/releases

stellarium项目的DSS图片在线请求url：https://dss.stellarium.org/survey/ （加载巡天图像的，小文件太多，而且国内访问速度很差）
对应的有顺带分发的离线assets，可以考虑挂上去：https://dss.stellarium.org/offline/

**Comment by ZenithalHourlyRate** [comment]
stellarium 本体，由于在 github-release 中，且 tuna 支持对github-release的镜像，感觉可以直接在 [github-release.py](https://github.com/tuna/tunasync-scripts/blob/master/github-release.py) 中加一行 `Stellarium/stellarium`.

相类似的，stellarium 的 DSO catalog 数据也是通过 github-release 分发，在 [Stellarium/stellarium-data](https://github.com/Stellarium/stellarium-data/releases/tag/dso-3.11) 中，可以通过类似的方式镜像。此数据的安装方式参照 User Guide 0.20.3-1 第 5.5.2 节（可以写在镜像的使用帮助页面中）。

两种巡天数据，对于 Histfiles，由于一些版权原因，感觉较难镜像；对于TOAST，感觉镜像站可以先同步[离线版本](https://dss.stellarium.org/offline/)，然后在镜像端解压形成目录，便可提供在线请求url，如果第11层过大，感觉可以只镜像10层。

对TOAST的版权问题不太了解，不知是否可以再分发。

该数据应该不会有更新，可以一次同步后不再同步。

**Comment by ZenithalHourlyRate** [comment]
如 PR 所示，stellarium 本体已经镜像；对于 dso 与 dss ，由于不知其镜像策略，可以提供新的镜像方法，或可以关闭该 issue

**Comment by Harry-Chen** [comment]
需要向官方确认 DSS 图片是否能够镜像，以及对此的需求是否足够

**Comment by ultrapre** [comment]
我给项目作者Alexander发邮件确认过，上面的TOAST图片可以镜像，虽然数据不在gpl协议下。stellarium-data的release页面的恒星和深空数据、每周发布的内测程序也是stellarium的一部分，gpl有效。

**Comment by ZenithalHourlyRate** [comment]
由于需求情况未知，暂不镜像数据集

**Comment by ultrapre** [comment]
你好，请问Stellarium已经镜像到的地址在哪里？tuna上找不到

**Comment by ZenithalHourlyRate** [comment]
https://mirrors.tuna.tsinghua.edu.cn/github-release/Stellarium/stellarium/LatestRelease/
与
https://mirrors.bfsu.edu.cn/github-release/Stellarium/stellarium/LatestRelease/
